### PR TITLE
Replaced `HEATPROOF` flag with `HEAT_IMMUNE` flag for consistency

### LINKED ISSUE #51656: HEAT_IMMUNE does not protect against flame and heat exposure when used in an effect.
### Describe the bug

The flag "HEAT_IMMUNE" has a bug that prevents it from working, but only if given to the character as part of an effect. The protection still works if it's given as part of a wearable item.

### Steps To Reproduce

1. Make a new world with Magiclysm active.
2. Give the avatar the "debug_full_protection" effect included with Magiclysm which has the "HEAT_IMMUNE" flag.
3. Debug spawn a fire vent.
4. Try to step into the fire vent. The player will get heavily injured by the flame despite supposedly being invincible from the "debug_full_protection" effect.
5. Give the character a modded wearable item with the flag "HEAT_IMMUNE". 
6. Step into an open flame again while wearing this item. This time the protection works.

### Expected behavior

HEAT_IMMUNE should work both when given to wearable items and effects. I tried to wade into the source code  to find the culprit, and it seems that the problem stems from the deletion of this line `has_effect_with_flag( flag_EFFECT_HEAT_IMMUNE )` from character.cpp by https://github.com/CleverRaven/Cataclysm-DDA/pull/47633 without also adding an equivalent `has_effect_with_flag( flag_HEAT_IMMUNE )`. Though I can't say for sure since I don't have any real experience reading or writing C++ code myself.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 89a5de5 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
None

#### Purpose of change
* Closes #51656.

Having `HEATPROOF` flag, which makes you immune to high temperatures, isn't consistent with existence of flags like `ACID_IMMUNE`, `COLD_IMMUNE` and so on, which make you immune to corresponding type of damage. While check for `HEAT_IMMUNE` flag exists, it's checked only for worn items, and not for effect type.

#### Describe the solution
Replaced `HEATPROOF` flag with `HEAT_IMMUNE` flag everywhere, for consistency.

#### Describe alternatives you've considered
Only replace `HEAT_IMMUNE` with `HEATPROOF` in `debug_full_protection` effect for Magiclysm. It would resolve #51656, but I decided to make some work for consistency.

#### Testing
Reproduced steps in #51656: gave my character `debug_full_protection` effect and made him walk into a fire vent. Character was immune to fire damage.

#### Additional context
None.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -291,7 +291,7 @@ static const json_character_flag json_flag_ELECTRIC_IMMUNE( "ELECTRIC_IMMUNE" );
 static const json_character_flag json_flag_ENHANCED_VISION( "ENHANCED_VISION" );
 static const json_character_flag json_flag_EYE_MEMBRANE( "EYE_MEMBRANE" );
 static const json_character_flag json_flag_FEATHER_FALL( "FEATHER_FALL" );
-static const json_character_flag json_flag_HEATPROOF( "HEATPROOF" );
+static const json_character_flag json_flag_HEAT_IMMUNE( "HEAT_IMMUNE" );
 static const json_character_flag json_flag_HEATSINK( "HEATSINK" );
```
Comment (kevingranade) [inline src/character.cpp:295]:
```suggestion
static const json_character_flag json_flag_HEATSINK( "HEATSINK" );
static const json_character_flag json_flag_HEAT_IMMUNE( "HEAT_IMMUNE" );
```

File: src/character_body.cpp [hunk 2]
```diff
@@ -46,7 +46,7 @@ static const efftype_id effect_sleep( "sleep" );
 
 static const itype_id itype_rm13_armor_on( "rm13_armor_on" );
 
-static const json_character_flag json_flag_HEATPROOF( "HEATPROOF" );
+static const json_character_flag json_flag_HEAT_IMMUNE( "HEAT_IMMUNE" );
 static const json_character_flag json_flag_HEATSINK( "HEATSINK" );
```
Comment (kevingranade) [inline src/character_body.cpp:50]:
```suggestion
static const json_character_flag json_flag_HEATSINK( "HEATSINK" );
static const json_character_flag json_flag_HEAT_IMMUNE( "HEAT_IMMUNE" );
```
