### PR TITLE
basecamps: add an emergency recall option

### LINKED ISSUE #31872: NPC ordered to construct blueprint can eventually switch to his/her long term goal and run away.
# Describe the bug

NPC ordered to construct blueprint can eventually switch to his/her long term goal and run away.
Usually that happens when they are interrupted.

# Steps To Reproduce

1. Spawn NPC
2. Define construction blueprint zone and provide required tools and materials. Constructions should be time-consuming.
3. Order NPC to complete blueprint.
4. Wait until NPC interrupts building (for example, goes to bed)
5. Watch him run away after waking up.

# Expected behavior

NPC returns to the activity before interrupt and stays on the base.

# Screenshots
N/A
# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-4979-g6a0f1c8
 - Graphics version: Tiles
 - Mods loaded: [ "dda", "no_npc_food", "filthy_morale", "craftgp", "safeautodoc", "aftershock", "realguns", "More_Survival_Tools", "Medieval_Stuff", "makeshift", "modular_turrets", "Salvaged_Robots", "Mining_Mod", "mutant_npcs", "alt_map_key", "cityside", "more_locations", "FujiStruct", "Urban_Development", "boats", "blazemod", "deoxymod", "Tanks", "DP_REMIX_INDICATORS", "EngineeringEssentials", "StatsThroughSkills", "sleepdeprivation", "more_classes_scenarios", "manualbionicinstall" ]

# Additional context

Save file from #31799 can be used to track down this problem.

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Features "basecamps: add an emergency recall option"```

#### Purpose of change
Fixes #31872

Some basecamps are getting stuck in extremely weird states, where an NPC is shown as having completed a mission but can't be selected for recall.

Add the option to recall any NPC that has been on a mission for more than 24 hours.  This cancels the mission without refunding any resources, but can be used to recover NPCs that are otherwise
stuck.

#### Describe the solution
Add a new parameter to `mission_companion_choose_return()` called `by_mission` that defaults to `true`.  If `by_mission` is `false`, the `mission_id` check to determine whether a companion is valid to return is skipped.

Added an emergency recall mission that works with all camp workers, has a variable deadline of more than 24 hours, and uses a special return function that directly calls `mission_companion_choose_return()` with `by_mission = false`.

#### Alternate Solutions
I need to look at the timed events code so that NPCs return automatically when their missions are complete.

#### Additional context
Tested by retrieving the 3 companions who could not be recalled normally from the save game in #31872.  Also sent out a companion and verified that the emergency recall option didn't happen until 24 hours had passed.

### CODE REVIEW

File: src/faction_camp.cpp [hunk 1]
```diff
@@ -1265,6 +1272,22 @@ void basecamp::get_available_missions( mission_data &mission_key, bool by_radio
             }
         }
     }
+
+    if( !camp_workers.empty() ) {
+        const base_camps::miss_data &miss_info = base_camps::miss_info[ "_faction_camp_recall" ];
+        entry = string_format( _( "Notes: \n"
```
Comment (Qrox) [inline src/faction_camp.cpp]:
```suggestion
        entry = string_format( _( "Notes:\n"
```

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

**Comment by mlangsdorf** [comment]
Stupid dyslexia - this fixes #31782.
