### PR TITLE
Fixes activity zone sorting for comestibles in containers.

### LINKED ISSUE #44245: Perishable items in containers don't get sorted correctly
# Describe the bug
when setting zones for sorting perishable and nonperishable food/drink, foods in paper wrappers and plastic bags go into the nonperishable zone and perishable drinks are being sorted as nonperishable foods

# Steps To Reproduce

1. make a zone for Unsorted loot, one for Food, one for P. Food, and one for P. Drink
2. spawn a bag of popcorn and a bottle of fruit juice in the unsorted loot zone
3. sort loot and see they go into the Food zone 
4. unload the plastic bag and put the popcorn back in the unsorted zone
5. sort and see it ends up in the P. Food zone

# Expected behavior
that food is sorted as perishable in containers that don't prevent spoilage and drinks are sorted properly 

# Screenshots

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5927-g27d4c34 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

### PR DESCRIPTION
**Pull request by Squishums**
#### Summary

SUMMARY: Bugfixes "Fixes activity zone sorting for comestibles in containers"

#### Purpose of change
Fixes #44245

This is something that really bothered me as a player, tbh. Using zones and `Shift+O` to sort items doesn't play nicely with containers, which isn't a problem for most items, since they're usually loose, but comestibles from house scrounging are almost always contained within something. The logic for whether an item is food [changed when pockets were added](https://github.com/CleverRaven/Cataclysm-DDA/commit/09ee4e1b90e0fcda8a92fd65707ae3e74f43c360#diff-cf2f58ea33a10af6dd682696f8de84f99dd3bf923c00fb0cd38ff4894e7cd538R6070-R6074), about 6 months ago.

#### Describe the solution

Well... just kinda fixed the logic? When sorting comestible containers, consider the contained item, but also account for whether the spoilage rate of the containing pocket. If a container will *ever* spoil if left out at room temperature, consider it perishable.

#### Describe alternatives you've considered

Freezing all food so there are no liquids and nothing ever spoils. It could all go on the same tile then. Would make life much simpler.

This cooouuulllldddd be fixed by making changed to `get_food` to mirror the pre-pocket logic, but without any test coverage I'm not confident it won't break more things than it'll solve. item.cpp desperately needs a refactor. There's logic for weapons, food, clothing, tools, whatever, all in one huge file.

Could expand this to be a general solution for sorting containers but it's not as obvious what the correct behaviour is for non-comestibles. Going to limit the scope here to where it makes the biggest difference.

Finally, I don't think relatively shelf stable comestibles, [like lasagne sheets which last a literal year](https://github.com/CleverRaven/Cataclysm-DDA/blob/ac95f65dd008750531af8268d8422429c716fcc6/data/json/items/comestibles/wheat.json#L47), should be considered perishable for the sorting logic. It's not like you're refrigerating it anyway. Will want to come up with some cutoff threshold in the future.

#### Testing

Why I added tests of course. The auto sort logic was *completely* untested, and honestly anything touching either pockets or spoilage is arcane voodoo at best. I also set up an in-game test using a bunch of different item types, which you can see below. Before the change, the two drink zones were completely unused, as all liquids require a container, and the perishable food zone was only filled with perishables outside of a container.

| Setup | After Sort (looking at drinks) |
| ------------- | ------------- |
| image  | image |

Please don't judge my nude shame, I was testing a new clothing feature 😔

#### Additional context

The pocket spoilage logic really only looks at a item's direct parent for the spoilage rate. It should be really be doing a tree walk to the root pocket and multiplying all the spoilage reductions, but like again, not gonna change that here.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -6821,6 +6821,11 @@ item_pocket *item::contained_where( const item &contained )
     return contents.contained_where( contained );
 }
 
+const item_pocket *item::contained_where( const item &contained ) const
+{
+    return const_cast<item *>( this )->contained_where( contained );
```
Comment (andrei8l) [inline src/item.cpp:6826]: I don't think this `const_cast` does anything here. The method is already marked `const` so `this` is `const` already.

Comment (Squishums) [reply src/item.cpp:6826]: It's actually casting `this` to a mutable `item *` so that we can use the mutable `contained_where` implementation. We can't call it without the cast, because the mutable version returns a mutable reference, which is a no-go from a const object. It's a common C++ trick to avoid having to duplicate the entire method body for these const/mutable method pairs, and it's safe as long as your mutable version doesn't have side effects.

Comment (andrei8l) [reply src/item.cpp:6826]: I see; thanks!

**Comment by Squishums** [comment]
Astyle failure is suffer.cpp, which I didn't touch 🤷‍♀️

File: tests/clzones_test.cpp [hunk 2]
```diff
@@ -0,0 +1,235 @@
...
+
+// Comestibles sorting is a bit awkward. Unlike other loot, they're almost
+// always inside of a container, and their sort zone changes based on their
+// shelf life and whether the container prevents rotting.
+TEST_CASE( "zone sorting comestibles ", "[zones][items][food][activities]" )
+{
+    clear_map();
+    zone_manager &zm = zone_manager::get_manager();
+
+    const tripoint origin_pos = tripoint_zero;
```
Comment (AMurkin) [inline tests/clzones_test.cpp:30]:
```suggestion
    const tripoint origin_pos;
```

**Comment by Squishums** [comment]
Took some time to get the clang tidy plugin working locally. PR should be good now. Clang Build Analyze failure isn't related.

**Comment by Squishums** [comment]
The travis build failure is kinda directly contradicting the clang-tidy complaint about wanting the the tripoint to default initialize itself.

What it's complaining about now has been [allowed on major compilers for a while now](https://stackoverflow.com/questions/7411515/why-does-c-require-a-user-provided-default-constructor-to-default-construct-a), and particularly on clang since 3.9... unfortunately travis is using 3.8.

File: tests/clzones_test.cpp [hunk 3]
```diff
@@ -0,0 +1,235 @@
...
+
+// Comestibles sorting is a bit awkward. Unlike other loot, they're almost
+// always inside of a container, and their sort zone changes based on their
+// shelf life and whether the container prevents rotting.
+TEST_CASE( "zone sorting comestibles ", "[zones][items][food][activities]" )
+{
+    clear_map();
+    zone_manager &zm = zone_manager::get_manager();
+
+    const tripoint origin_pos;
```
Comment (anothersimulacrum) [inline tests/clzones_test.cpp:30]: It's easier to make it work for clang 3.8 than the other options, though (especially because that means we don't need to reexamine what compilers we support).
```suggestion
    const tripoint origin_pos = tripoint_zero;
```

Comment (Squishums) [reply tests/clzones_test.cpp]: Ah, alrighty. Do I need to add something to suppress clang tidy here too or will it be fine once it's pushed?

Comment (anothersimulacrum) [reply tests/clzones_test.cpp]: AFAIK clang-tidy will be fine with this, but we'll see if it gets cranky.

File: tests/clzones_test.cpp (hunk 2 above)
Comment (kevingranade) [inline tests/clzones_test.cpp:30]:
```suggestion
    const tripoint origin_pos;
```

File: tests/clzones_test.cpp (hunk 3 above)
Comment (kevingranade) [inline tests/clzones_test.cpp:30]:
```suggestion
    const tripoint &origin_pos = tripoint_zero;
```

File: src/clzones.cpp [hunk 4]
```diff
@@ -839,17 +839,40 @@ zone_type_id zone_manager::get_near_zone_type_for_item( const item &it,
     }
 
     if( cat.get_id() == item_category_food ) {
-        // skip food without comestible, like MREs
-        if( const item *it_food = it.get_food() ) {
+        const item *it_food = nullptr;
+        bool perishable = false;
+        // Look for food, and whether any contents which will spoil if left out.
+        // Food crafts and food without comestible, like MREs, will fall down to LOOT_FOOD.
+        it.visit_items( [&]( const item * node, const item * parent ) {
```
Comment (kevingranade) [inline src/clzones.cpp:846]: Need targeted capture, capturing the whole environment is an antipattern.
```suggestion
        it.visit_items( [&it_food, &perishable]( const item * node, const item * parent ) {
```

File: tests/clzones_test.cpp (hunk 3 above)
Comment (jbytheway) [reply tests/clzones_test.cpp]: For future reference, I think the way you can appease both clang-tidy and clang in this situation is to initialize it like
```
const tripoint origin_pos{};
```
