### PR TITLE
Fix vehicle repair

### LINKED ISSUE #17857: Vehicle repairs sometimes do not work
http://smf.cataclysmdda.com/index.php?topic=13025

> some objects in vehicles wont repair, ever.
> http://i.imgur.com/vxFUtZS.png
> http://i.imgur.com/fnDc8wo.png

> pressing r to repair jumps to the tile the bed is on, r again highlights the bed itself, a third r starts the repairs and then it asks for a tool to use to repair, have tried welder, ductape, and integrated toolset. a minute passes in game time and then comes back to the vehicle screen and the bed is not repaired.

> this also happens with my heavy duty hatches and minireactor.

I couldn't reproduce, but looking at `vehicle::set_hp` there may be a rounding error. The math there looks rather fragile.

### PR DESCRIPTION
**Pull request by mugling**
Fixes #17857

> I'm going to special case for min and max durability for now as I want to overhaul vehicle repair to an interruptible long action which gradually repairs and item consuming time and other resources proportionally

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -227,8 +227,16 @@ vehicle::~vehicle()
 
 void vehicle::set_hp( vehicle_part &pt, int qty )
 {
-    double k = pt.base.max_damage() / double( pt.info().durability );
-    pt.base.set_damage( pt.base.max_damage() - ( qty * k ) );
+    if( qty == pt.info().durability ) {
```
Comment (Coolthulhu) [inline src/vehicle.cpp]: We don't support reinforced parts yet, this should probably be `>=`.

File: src/vehicle.cpp [hunk 2]
```diff
@@ -227,8 +227,16 @@ vehicle::~vehicle()
...
+        pt.base.set_damage( 0 );
+
+    } else if( qty == 0 ) {
```
Comment (Coolthulhu) [inline src/vehicle.cpp]: Same here: `<=`
