### PR TITLE
Preserve ammo linkage on zone unload

### LINKED ISSUE #60310: Using the unload zone on ammo belts destroys the linkages.
### Describe the bug

If you create an unload zone on a tile within a vehicle and place an ammo belt onto it and then unload them using the zone interface, the linkages disappear but the ammunition is correctly removed from the belt and sorted.

### Steps to reproduce

1. Create a loot zone on a cargo space or other vehicle container for unloading.
2. Place an ammo belt onto the space.
3. Unload the ammunition.
4. The linkages dissapear.

### Expected behavior

The linkages should still exist.

### Screenshots

N/A

### Versions and configuration

07d8e66

### Additional context

none

### PR DESCRIPTION
**Pull request by robob27**
#### Summary
Bugfixes "Preserve ammo belt linkages when unloading with zones"

#### Purpose of change

Fixes #60310

#### Describe the solution

As a quick fix for stable, and as suggested by @RenechCDDA, copies the code that is responsible for preserving ammo belt linkages from `unload_activity_actor::unload` (the player manually unloading)  to other code that is responsible for unloading using zones so that the linkages will also be preserved there. An ideal fix would be more DRY.

The copied code is from: https://github.com/CleverRaven/Cataclysm-DDA/blob/57c865ece207986decd6db4ccb403e14a15fad5a/src/activity_actor.cpp#L2929-L2936

I made some small modifications to spawn the linkages on the tile the unloaded item is on and not show the disassembly message so it doesn't spam them if many belts get unloaded back to back.

#### Testing
- Spawn some ammo belts
- Put them in an unload zone
- Unload them using SHIFT+O
- Check that the ammo linkages don't disappear and that the number of linkages created = the number of ammo unloaded
- The linkages should be unloaded on the tile that the ammo belt was on
- The ammo belt should be removed if it's empty

### CODE REVIEW

**Comment by robob27** [comment]
After I got the test setup somewhat properly it didn't fail a single time locally but of course it fails in CI and I can't replicate the failure. It seems like after 

```
complete_activity( dummy, unload_loot_activity_actor() );
```

the items are not always available on the map right away, so it can fail. Not sure what the best fix is for that but it's probably real simple. I gotta sleep but this gets this issue most of the way there, I think!

File: tests/clzones_test.cpp [hunk 1]
```diff
@@ -1,29 +1,97 @@
...
+            return it.typeId() == itype_belt223;
+        } ).front()->ammo_remaining();
+    };
+
+    const int belt_ammo_count_before_unload = get_belt_ammo_count();
+
+    CHECK( belt_ammo_count_before_unload == ammo_belt.ammo_capacity(
+               ammo_belt.loaded_ammo().ammo_type() ) );
+
+    complete_activity( dummy, unload_loot_activity_actor() );
```
[the remark this answers is not in the document]
Comment (robob27) [reply tests/clzones_test.cpp:81]: Thanks, wasn't aware of this helper.

File: tests/clzones_test.cpp [hunk 2]
```diff
@@ -1,29 +1,97 @@
...
+
+    calendar::turn += 1_turns;
+
+    THEN( "Check that the ammo and linkages were both unloaded" ) {
+        CHECK( count_items_or_charges( tripoint_east, itype_belt223 ) == 1 );
```
[the remark this answers is not in the document]
Comment (robob27) [reply tests/clzones_test.cpp:86]: Yeah you're right, fixing

**Comment by robob27** [comment]
The test is still passing 100% of the time locally and failing 100% of the time on the "GCC 9, Curses, LTO" check (I assume my latest commit won't change this). I don't understand 🙃. Otherwise, everything seems to be working as described in the testing steps. I'll probably have to leave this as is, I'm out of ideas for now. Please feel free to ping me here or on the discord if anyone has any suggestions to fix the test, or drop it or whatever works best for stable release 🚀

File: tests/clzones_test.cpp [hunk 3]
```diff
@@ -1,29 +1,79 @@
...
+TEST_CASE( "zone unloading ammo belts", "[zones][items][ammo_belt][activities][unload]" )
+{
+    avatar &dummy = get_avatar();
+    map &here = get_map();
+
+    clear_avatar();
+    clear_map();
+
+    dummy.setpos( tripoint_east );
+    create_tile_zone( "Unload All", zone_type_zone_unload_all, tripoint_east );
```
Comment (andrei8l) [inline tests/clzones_test.cpp:55]: You need to use absolute coordinates. Something like this:
```suggestion
    tripoint_abs_ms const start = here.getglobal( tripoint_east );
    dummy.set_location( start );
    create_tile_zone( "Unload All", zone_type_zone_unload_all, start.raw() );
```
The other tests work because they don't interact with the reality bubble.

Comment (robob27) [reply tests/clzones_test.cpp]: Thank you! This fixed the test failure. Is this documented somewhere or do you just happen to have this knowledge from personal experience? And do you have any idea why, even without absolute coordinates, the test was working locally? Either way, thanks again. The test not working consistently between my computer and CI was driving me mad.

Comment (andrei8l) [reply tests/clzones_test.cpp]: The zone manager is global so it makes sense for it to use global coordinates. The `tripoint` type is supposed to give you this info, but the zones code (particularly `zone_manager::add()`) hasn't been fully migrated yet.

Using local coordinates can still work if the reality bubble is anchored at zero, so local coord == global coord. That's always the case if you only run one test case in isolation, though I'm not entirely sure why the LTO build with the full test suite exposes this issue more often than the non-LTO one.

**Comment by robob27** [comment]
Current failure is from an unrelated test, I think this is probably good to go.
