### PR TITLE
Fix aiming window and show it if any gun_mode is viable

### LINKED ISSUE #30907: Guns with multiple different magazine firing mods wont trigger if the main magazine is empty
# Describe the bug
When you have a gun like the Kel-Tec KSG and try to fire it while the main clip is empty you cannot fire the alternate fire modes no matter what, pressing fire prompts you with "you need to reload". 
Another related issue is if you fire the L523-MBR rifles grenade launcher you cannot fire a single shot from the rifle. You can still press shift F to burst fire but even changing firing modes in the firing menu to single shot will still cause you to fire a burst fire.

# Steps To Reproduce

1. Get a Kel-Tec KSG
2. Put ammo in the alternate magazine while having the main magazine empty
3. There's no way to fire the secondary magazine.

# Expected behavior
Being able to use all features of a gun reliably 

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3509-ge10d164 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Folding Parts pack [deoxymod],
    Classes and Scenarios Mod [more_classes_scenarios],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA]
]

### PR DESCRIPTION
**Pull request by ymber**
#### Summary
SUMMARY: Bugfixes "Display correct ammo and range in aiming window"

#### Purpose of change
The aiming window would always display the ammo of whatever you opened it with even if you switched to a mode that used different ammo. Range calculations were also not being updated when mode changed.

Fixes #30907

#### Describe the solution
Update ammo pointer and range value on mode switch.

#### Testing
Works as expected in game with an M16A4 with an M320 and a KSG with 00 buck in one tube and slugs in the other.

### CODE REVIEW

File: src/ranged.cpp [hunk 1]
```diff
@@ -1594,6 +1594,8 @@ std::vector<tripoint> target_handler::target_ui( player &pc, target_mode mode,
                 ammo = on_mode_change( relevant );
             } else {
                 relevant->gun_cycle_mode();
+                ammo = relevant->gun_current_mode().target->ammo_data();
```
Comment (ZhilkinSerg) [inline src/ranged.cpp]: Crashes if item has no `ammo_data` - see #36499.
