### PR TITLE
Skip Melee in Firing Mode

### LINKED ISSUE #30676: Combat Knife bayonet crashing
# Describe the bug

Switching firing modes with a gun equipped with a combat knife bayonet causes a crash.

# Steps To Reproduce

1. Equip a loaded gun with a combat knife bayonet
2. Enter the firing menu
3. Cycle through all the firing modes 

# Expected behavior

Seems like the game is attempting to change to a "combat knife" firing mode that just doesn't work

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3197-gda3edc5
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Extended Realistic Guns [realguns],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Content [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Fungal Monsters [No_Fungi],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

first time reporting a bug ^.^

# Crash log

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3195846/crash.log)

### LINKED ISSUE #35117: non GUNMOD type gunmods with gunmod_data cannot be installed
# Describe the bug
Gunmod items that have a `type` other than `GUNMOD` and have their properties defined in a `gunmod_data` object cannot be installed on a weapon.

# Steps To Reproduce
1. Spawn a combat knife and an M16A4.
2. Activate the combat knife and observe that no option is presented to install it as a gunmod. No such option exists in the % menu either.
3. Spawn a pistol bayonet and a Glock 17
4. Activate the pistol bayonet and observe that it can be installed on the Glock 17 as expected.

# Expected behavior
Non `GUNMOD` gunmods can be installed normally and behave as other gunmods do.

# Versions and configuration
 - OS: Arch Linux x86_64
 - Game Version: Current master at ffe470b975559b3c6a125aef7f237429ab655760
 - Graphics version: Tiles
 - Mods loaded: dda, no_npc_food

# Additional context
I bisected back a few days and found that #35067 was introduced in #34735. I can't tell if this issue was introduced by the same because #35067 makes it impossible to test for but I confirmed that this bug is not present in builds from one commit prior to #34735 (42e22fad5db2becfe5b368a27c54646281de108f).

### PR DESCRIPTION
**Pull request by LetterShapedGlyphs**
#### Summary
```SUMMARY: Bugfixes "Fixes crashes involving bayonet type items"```

#### Purpose of change
Fixes #35117 and Fixes #30676 

#### Describe the solution
Reverted an erroneous change that broke the loading of gunmods.
Added extra logic to skip over melee gun modes when in the firing screen.

#### Describe alternatives you've considered
Automatically switch between `reach_attack()` targeting view and `fire()` targeting view.
Merge the two firing views.

#### Testing
Created a new character.
Spawned in a rifle.
Spawned in one of every bayonet type gunmod (combat knife, makeshift bayonet, etc.)
Tested that each can be installed as a gunmod on a rifle.
Spawned in ammo and a magazine for the rifle.
Tested switching firing modes both inside of and outside of the `fire()` targeting view.
Also tested that regular reach attacks still worked.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -1875,7 +1875,7 @@ std::string item::info( std::vector<iteminfo> &info, const iteminfo_query *parts
             info.emplace_back( "GUNMOD", _( "Handling modifier: " ), "",
                                iteminfo::show_plus, mod.handling );
         }
-        if( is_gun() && !type->mod->ammo_modifier.empty() && parts->test( iteminfo_parts::GUNMOD_AMMO ) ) {
+        if( !type->mod->ammo_modifier.empty() && parts->test( iteminfo_parts::GUNMOD_AMMO ) ) {
```
Comment (Karthas077) [inline src/item.cpp]: Checking if ammo_modifier is empty is sufficient for all gunmods now that all gunmod items actually have `def.mod` instantiated, and makes sure that any gunmod which isn't itself a gun, but still modifies ammo, will work in the future (none exist currently)

File: src/item_factory.cpp [hunk 2]
```diff
@@ -2202,8 +2202,10 @@ void Item_factory::load_basic_info( JsonObject &jo, itype &def, const std::strin
     load_slot_optional( def.brewable, jo, "brewable", src );
     load_slot_optional( def.fuel, jo, "fuel", src );
     load_slot_optional( def.relic_data, jo, "relic_data", src );
+
+    // optional gunmod slot may also specify mod data
     load_slot_optional( def.gunmod, jo, "gunmod_data", src );
-    load_slot_optional( def.mod, jo, "mod_data", src );
+    load_slot_optional( def.mod, jo, "gunmod_data", src );
```
Comment (Karthas077) [inline src/item_factory.cpp]: `load_gunmod()` Already calls both of these functions, as both are needed. This revert allows items which are not typed as GUNMOD to exhibit correct behavior.

**Comment by Karthas077** [comment]
As mentioned in my code comment, `load_gunmod()` already calls both `load_slot( islot_mod [...] )` and `load_slot( islot_gunmod [...] )` so items which can be optional gunmods need to call both of those with `load_slot_optional()`.

The resulting  'unvisited JSON' errors either need to be ignored, or the entire `def.gunmod` and `def.mod` dichotomy needs to be fixed for non GUNMOD typed items.

**Comment by AMurkin** [comment]
> Fixes #35117 and #30676

Rewrite it like so:
Fixes #35117 and Fixes #30676

**Comment by Karthas077** [comment]
> Rewrite it like so:
> Fixes #35117 and Fixes #30676
Ah, didn't realize the word "Fixes" was important. Thank you.

**Comment by snipercup** [comment]
Tested:
- spawned a m4a1 and a glock 17
- spawned some gunmods
- attached a combat knife to the m4a1
- removed the combat knife and added a sword bayonet to the m4a1
- attached pistol bayonet to the pistol
- switched firing modes (auto, semi auto) when in firing mode using the m4a1
- tested reach attack by spawning a blob and pressing tab while wielding my m4a1 2 tiles away
- tested firing the m4a1 normally using semi-auto and full auto

no crashes or errors.
