### PR TITLE
Fix ui.cpp scrolling bug

### LINKED ISSUE #45274: Clothing modification menu navigation inconsistency
# Describe the bug

When all items in "clothing modification menu" are inactive, up and down keys behave inconsistently:
* "up" key works as intended: moves cursor one line up
* while "down" key always moves cursor to the beginning of the list

# Steps To Reproduce

1. spawn tailors kit and socks
2. don't have any materials around
3. `a`ctivate tailor's kit and select "modify clothing"
4. ensure that all items in the menu are greyed out
5. observe the behavior of up and down keys

# Expected behavior

"Down" key should move cursor one line at a time, similar to "up" key.

# Screenshots

modif_bug

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14; Build: 18A391; 
- Game Version: 0.E-7368-g891488a81b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

Might be a good first issue for those who want to start with C++.

### PR DESCRIPTION
**Pull request by Pupsi-Mupsi**
#### Summary

`SUMMARY: Bugfixes "Fix ui.cpp scrolling bug"`

#### Purpose of change

This fixes #45274.

- Fixing a bug that was implemented by yours truly. **My apologies.**
- My thanks to @irwiss and @Aivean. 

#### Testing

- Compiled using microsoft visual studio 2019.
- Checked that everything is working as expected.

### CODE REVIEW

File: src/ui.cpp [hunk 1]
```diff
@@ -823,17 +823,13 @@ bool uilist::scrollby( const int scrollby )
         if( fselected >= recmax ) {
             fselected = 0;
         }
-        int x = 0;
         for( size_t i = 0; i < fentries.size(); ++i ) {
```
Comment (Aivean) [inline src/ui.cpp:826]: Not in the scope of this PR, but I'd suggest to look into merging these two nearly identical loops.
