### PR TITLE
mutation enchantment item fix

### LINKED ISSUE #42936: Some mutations gained by relics not working
# Describe the bug

Adding passive mutations to armor via "relic_data" will cause the mutation to properly show on the character sheet, however it seems that the mutations themselves will often not actually work when added to the character sheet in this manner. Examples of mutations that I have verified are **not** working in this scenario:

- Gills
- Nictitating Membrane
- Ursine Vision
- Wayfarer
- Illiterate
- Strong

The Fangs mutation does seem to work, however. Additionally, straight stat bonuses added to the item (when not done via mutations) will work as expected.

# Steps To Reproduce

1. Created two different clothing items which add mutations.
2. Spawned these items in game and equipped them; verified that the mutations were correctly added to the character sheet.
3. Engaged in activity which would normally produce very obvious results given the appropriate mutation, such as Gills allowing underwater breathing.
4. In the Gills example, my character could not breathe underwater despite having this mutation listed on the character sheet. If I use Debug to simply add the mutation permanently, it works as intended (whether or not the relic is equipped).

# Expected behavior

Mutations listed on the character sheet should work as normal, even if they are only temporary.

# Screenshots

Mutations Bug

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5001-gec1deea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP]
  ]

Build #10914 - August 14, 2020 at 4:10:43 AM -0400

# Additional context

JSON of the item I created: 

	{
    "id": "Wildshape Cloak: Fish",
    "type": "ARMOR",
    "name": "Wildshape Cloak: Fish",
    "description": "A magical cloak that shimmers like fresh water under a warm sun. It can be worn to morph your body to a form that is excellent for swimming, but ill-suited for combat.",
    "looks_like": "cloak_leather",
	"weight": "2060 g",
    "volume": "3050 ml",
    "price": 500000,
    "symbol": "w",
    "color": "blue",
	"covers": [ "torso", "arm_l", "arm_r", "leg_l", "leg_r" ],
    "coverage": 0,
    "encumbrance": 0,
	"flags": [ "OUTER", "OVERSIZE", "NONCONDUCTIVE", "WATER_FRIENDLY", "RAINPROOF" ],
    	"relic_data": {
      "passive_effects": [
        {
          "has": "WORN",
          "condition": "ALWAYS",
          "mutations": [ "GILLS", "MEMBRANE", "AMPHIBIAN" ]
        } 
      ]
	}
	}

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: Bugfixes "Fixes relic enchantments giving mutations"```

#### Purpose of change
Fixes #42936

#### Describe the solution
adds a new item::mutations_from_wearing and invokes that in Character::on_wear, while also checking that you don't gain double effects.

#### Testing
```
  {
  "id": "Wildshape Cloak: Fish",
  "type": "ARMOR",
  "name": "Wildshape Cloak: Fish",
  "description": "A magical cloak that shimmers like fresh water under a warm sun. It can be worn to morph your body to a form that is excellent for swimming, but ill-suited for combat.",
  "looks_like": "cloak_leather",
  "weight": "2060 g",
  "volume": "3050 ml",
  "price": 500000,
  "symbol": "w",
  "color": "blue",
  "covers": [ "torso", "arm_l", "arm_r", "leg_l", "leg_r" ],
  "coverage": 0,
  "encumbrance": 0,
  "flags": [ "OUTER", "OVERSIZE", "NONCONDUCTIVE", "WATER_FRIENDLY", "RAINPROOF" ],
    "relic_data": {
    "passive_effects": [
      {
        "has": "WORN",
        "condition": "ALWAYS",
        "mutations": [ "STR_UP" ]
      } 
    ]
  }
  },
```
Used this, and a variation of this with different `mutations`  to test various mutations, such as gills and rubbery limbs

#### Additional context
Mutations gained from enchantments still don't cancel current mutations. i don't really want to deal with that in this PR, and it's somewhat amusing to me that you can get weak and strong at the same time in magiclysm. There's also a non-negligible amount of work needed to go into doing that, so that can be punted to a follow-up.

### CODE REVIEW

File: src/character.h [hunk 1]
```diff
@@ -1042,7 +1042,7 @@ class Character : public Creature, public visitable<Character>
         float mabuff_attack_cost_mult() const;
 
         /** Handles things like destruction of armor, etc. */
-        void mutation_effect( const trait_id &mut );
+        void mutation_effect( const trait_id &mut, bool worn_destroy_override );
```
Comment (ZhilkinSerg) [inline src/character.h:1045]:
```suggestion
        void mutation_effect( const trait_id &mut, bool worn_destroyed_override );
```
