### PR TITLE
Prevent duplicate selection of same item when inserting into a container

### LINKED ISSUE #48573: Crash when inserting items into container
# Describe the bug

When inserting items from the ground into a wielded container, if you attempt to insert an item loaded with its ammo, ammo inside the item, and the ammo as separate stack game crashes.

# Steps To Reproduce

Replicated a few times, this is the smallest crashing sample
Didn't tried with other configurations (not wielded item, not from the ground, magazine and ammo)

Wield cardboard box
Insert
Select from the ground tailor kit loaded with thread, thread inside it and a separate stack of the thread

# Expected behavior

No crash

# Screenshots

image
Note weird indent for the lower stack of the thread (placed under other thread and not tailor kit)

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10383-gad91f6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

Bugfixes "Prevent duplicate selection of same item when inserting into a container"

#### Purpose of change
Fixes #48573

#### Describe the solution

The crash was caused when selecting the same item twice to be inserted into a container. This fix avoids the problem by disallowing the selection of the same item twice. This changes the code to detect all of a container contents in `deselect_contained_items()` - before it was not detecting loaded ammo so would not test for it.

Also found that inserting less than a full stack was not checking for deselection.

#### Describe alternatives you've considered

Initially tried to check for a nullptr but that turned out to be the wrong approach. Lesson learned.

#### Testing
Full test program: no problems found.

To recreate the problem: have a container on the player and insert a tailor's kit and its thread ammo by selecting both. A null pointer crash happens.

After the fix:
Test with pistol loaded with a loaded magazine, a magazine containing ammo, and a tailor's kit leaded with thread. 

If the tool is selected then the ammo is not allowed as a selection. If the ammo is selected first and the tool later, then the tool is selected and the ammo deselected.

During testing found that a selection less than a full stack was not triggering deselection, and it was an easy fix.

### CODE REVIEW

**Comment by BrettDong** [comment]
Calling a member function on a NULL class object itself is undefined behaviour.

File: src/item.cpp [hunk 1]
```diff
@@ -712,6 +712,9 @@ item item::split( int qty )
 bool item::is_null() const
 {
     // Actually, type should never by null at all.
+    if( !this ) {
```
Comment (Salty-Panda) [inline src/item.cpp:715]:
```suggestion
    if( this == nullptr ) {
```
Not exactly sure, but it's my best guess

**Comment by jbytheway** [comment]
@BrettDong is right; this is not a good solution.  Callers need to be sure the pointer is not `nullptr` before calling `is_null`.  The `is_null` function tests tests for nullness in a different sense.

File: src/item.cpp (hunk 1 above)
Comment (RoyBerube) [reply src/item.cpp:715]: That is not allowed either. As BrettDong mentioned above, it is undefined behavior when the item is null. 

It looks to me that the item::is_null() method is not repairable - and it gets called from a lot of places.

I think I'll try filtering how the items are presented for insertion instead, so that the ammo is not shown.
