### PR TITLE
Fix timing related bugs when eating

### LINKED ISSUE #42608: Inventory menu: eating from a sealed can does not consume item
# Describe the bug

Using the inventory menu to (E)at from a sealed can causes all the contents to be transferred to other containers before the consumption fails on a null pointer object.

# Steps To Reproduce

1. Have a sealed can of food in inventory.
2. Open the inventory 'i' and try to 'E'at the food.
3. Transfer all the food to other containers or onto the ground, as prompted.
4. Get a null object failure message.

# Expected behavior

Food should be consumed before transferring to other containers.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 0.E-4666-g853fa2a5df [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Relevant debug.log line:
13:38:24.862 ERROR : D:\Cataclysm Master\Cataclysm-DDA\src\activity_actor.cpp:1143 [finish] Item location/name to be consumed should not be null.

https://github.com/CleverRaven/Cataclysm-DDA/blob/853fa2a5df4959d5717995dea1efe17c3f278a91/src/game.cpp#L2287-L2290

Source of the problem. Contents are processed before the activity is handled.

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary
SUMMARY: Bugfixes "Eating from sealed containers."

#### Purpose of change
Fixes #42608 
Eating from a sealed container in the 'i'nventory menu would prompt the player to unload the contents and then would fail to eat along with a null pointer debug message.

This also fixes a problem when 'E'ating directly from a sealed can. The food would be eaten but would not prompt the player to spill the contents, resulting in being able to keep an open tin can filled with its contents in inventory.

#### Describe the solution

The bug was caused by processing of the container with handle_contents_changed() before the contents were consumed. This fix enables the opening of sealed containers in consume(). handle_contents_changed() is still needed in case of nested parent sealed pockets, so it gets moved to the activity actor finish() method.

This happens to fix the 'E'at menu bug as well.

#### Testing

Had a sealed can in inventory. Chose 'E'at it from the inventory screen. Food was eaten first and then was prompted to spill or transfer the contents. Behaved as expected.

Tested eating from sealed container food directly with 'E' from game. Working as expected.

Tested consumption of aspirin and application hydrogen peroxide. Working as expected.

Ran the test build with no errors detected.

#### Additional context

This timing related bug may be present in other inventory methods that call handle_contents_changed() and use an activity actor. I searched for related open issues and did some testing for each possible menu option but came up empty. Still, I suspect this may be the cause of other obscure bugs.

Changed player::consume() methods to return a trinary enum instead of bool to improve logic. Added some doxygen comments to related methods to improve clarity.

### CODE REVIEW

File: src/activity_actor.cpp [hunk 1]
```diff
@@ -1140,6 +1140,7 @@ void consume_activity_actor::finish( player_activity &act, Character & )
     if( !canceled ) {
         if( consume_location ) {
             player_character.consume( consume_location, /*force=*/true );
```
Comment (Qrox) [inline src/activity_actor.cpp:1142]: It seems there's code in `player::consume` to handle liquid spilling, but it is currently not working.

Comment (RoyBerube) [reply src/activity_actor.cpp:1142]: Dang, I should have looked into that method. I'll take a closer at it look tomorrow. Seems a bit of redundancy has creeped in.

File: src/consumption.cpp [hunk 2]
```diff
@@ -1858,17 +1855,14 @@ bool player::consume( item &target, bool force, item_pocket *const parent_pocket
...
-            target.on_contents_changed();
-        }
+    if( consume_med( target, *this, parent_pocket ) ||
+        eat( target, *this, force, parent_pocket ) ||
+        feed_reactor_with( target, parent_pocket ) ||
+        feed_furnace_with( target, parent_pocket ) ||
+        fuel_bionic_with( target, parent_pocket ) ) {
 
-        return comest.charges <= 0;
+        target.on_contents_changed();
```
Comment (Qrox) [inline src/consumption.cpp:1864]: Some of the calls in the if condition only returns true if the item is completely consumed (`consume_med` for example).

Comment (RoyBerube) [reply src/consumption.cpp:1864]: Will look at that. Thanks for the feedback.
