### PR TITLE
Fix cow milking from cows from old saves with old milk not raw milk.

### LINKED ISSUE #37899: Cows from older saves come with milk, not milk_raw, leading to errors
# Describe the bug
Milkable animals were switched over to producing milk_raw, but the game doesn't seem to migrate old saves correctly on this.
Thus you get "cow/sheep/whatever is milkable but has no milk in its starting ammo!" errors whenever they enter the reality bubble, and when you try to milk one, which produces nothing.

# Steps To Reproduce

1. Make a player with a gun, magazine, and some ammo.
2. Try to aim at a wall.
3. There's no way to increase aim level.

# Expected behavior
Old saves should be updated.

# Screenshots

# Versions and configuration

- OS: Linux
  - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 9.11 (stretch); Release: 9.11; Codename: stretch; 
- Game Version: 0.D-12149-g7a3893221e [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools]
]
# Additional context
Looks like it won't take my zipped save for some reason. Uploaded to a free file host: https://anonfiles.com/X9j9H6Xcn8/HartwickCounty.tar_gz

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

```SUMMARY: Bugfixes "Fix cow milking from cows from old saves with old milk not raw milk."```

#### Purpose of change
Fixes #37899 
#### Describe the solution
In the milking PR, I forgot that cows used to produce `milk` not `raw_milk` so the functions to find raw_milk in their ammo failed, producing debugmsgs.
Well theres no point crying over spilt milk, so heres a fix.

It looks for raw_milk, if that fails, it then looks for milk, and goes with that.

I coulda taken this opportunity to convert their udders to raw milk, but I guess some people prefer their old milk in their old saves, and once that cows been milked theres no point trying to squirt it back up the udders, so ill let them keep their milk.

#### Describe alternatives you've considered
N/A

#### Testing
Loaded attached save in linked issue, now no errors, and milking works nad produces milk, not raw milk

#### Additional context
N/A

### CODE REVIEW

**Comment by BevapDin** [comment]
Would be better to fix once while loading the monster. That way you only have one place to change, instead of changing three places.

It also seems the code will spawn "milk" (not "raw milk") when the old save is used (it takes the item id directly form the content of the ammo map, if that map still contains "milk", the spawned item will be milk).

**Comment by davidpwbrown** [comment]
> Would be better to fix once while loading the monster. That way you only have one place to change, instead of changing three places.
> 
> It also seems the code will spawn "milk" (not "raw milk") when the old save is used (it takes the item id directly form the content of the ammo map, if that map still contains "milk", the spawned item will be milk).

Yep, I considered taking this opportunity to convert it to the new format of raw_milk, but thought people might not want that, but you think its preferable to convert ?

And yes Ill change to fix once when loading.

**Comment by BevapDin** [comment]
> Yep, I considered taking this opportunity to convert it to the new format of raw_milk, but thought people might not want that, but you think its preferable to convert ?

That would lead to inconsistency, which will be seen and reported as bugs:

In old saves, existing cows given "milk", but newly spawned cows give "raw milk".
With the same game version, cows in old saves given "milk", cows in new saves give "raw milk".

**Comment by davidpwbrown** [comment]
Theres some complications here, in the  linked issues attached save, the sheep in that save must be *very* old, they have no starting ammo defined for their type at all, so they musta been spawned prior to 2018 when sheep milking went in.

And yet, they have the new milkable flag, but not the starting_ammo.

So I cannot give their udders milk_raw on load, when there is no starting ammo amount defined for how much to give them, only solution there I think, is just to exit early without a debugmsg, with a player message.

**Comment by davidpwbrown** [comment]
Fixed to update on load once.

File: src/monster.cpp [hunk 1]
```diff
@@ -362,15 +362,37 @@ void monster::try_reproduce()
...
-    if( !has_flag( MF_MILKABLE ) ) {
-        return;
+    auto milked_item = type->starting_ammo.find( "milk_raw " );
+    if( milked_item == type->starting_ammo.end() ) {
+        milked_item = type->starting_ammo.find( "milk" );
+        if( milked_item == type->starting_ammo.end() ) {
+            // this may be a sheep from a very old save.
+            // sheep didnt use to be milkable, but now they have that flag,
+            // but the old save would keep their old blank starting ammo.
+            // cant modify the type, and cant get what their starting ammo should be.
```
Comment (BevapDin) [inline src/monster.cpp]: Why can't you get what their starting ammo is? What exactly does `type->starting_ammo` contain, if not the starting ammo?

`MonsterGenerator::check_monster_definitions` should check for this problem (a monster type with milkable flag, but no milk starting ammo) and issue a debug message. This problem should not appear out of nowhere in the middle of the game.

File: src/monster.cpp [hunk 2]
```diff
@@ -362,15 +362,37 @@ void monster::try_reproduce()
...
+            debugmsg( "%s has neither milk nor raw milk in its udders", get_name() );
+            return;
+        } else {
+            // take this opportunity to update udders to raw_milk
+            std::swap( ammo["milk_raw"], current_milk->second );
+            // Erase old key-value from map
+            ammo.erase( current_milk );
+            current_milk = ammo.find( "milk_raw" );
+            if( current_milk == ammo.end() ) {
+                //how?
```
Comment (BevapDin) [inline src/monster.cpp]: Exactly: "How?" this is unreachable. The expression `ammo["milk_raw"]` has created that entry in map. So it is definitively there.

File: src/monster.cpp (hunk 1 above)
Comment (davidpwbrown) [reply src/monster.cpp]: Its currently the case on the attached save in the linked issue, 

The sheep in that save has neither milk nor milk_raw in their starting ammo, and yet they have the milkable flag.

Comment (BevapDin) [reply src/monster.cpp]: > The sheep in that save has neither milk nor milk_raw in their starting ammo, and yet they have the milkable flag.

Well, *that* is the problem. The game should not allow this case as it can't handle this. This should be checked for when the game data is loaded, not in the middle of the game when the player stumbles upon that case.

Comment (davidpwbrown) [reply src/monster.cpp]: Issuing a debugmsg would be ok on that mismatch on load? I dont know whether that sheep in that save in the linked issue, is a weird case, or just what happens when very very old savegames are loaded from before sheep were milkable.

( it gives them the milkable flag, so I dont kno wwhy it didnt give them milk? ) if the sheep in that save is just a very weird edge case, then I guess I can do the debugmsg on load if theres a mismatch

Comment (BevapDin) [reply src/monster.cpp]: Here is a guess (or at least another bug): when a lamb matures (via `monster::try_upgrade`), it becomes a sheep by calling `monster::poly`. That function changes the type of the monster, but does not change its current starting ammo. So the adult sheep keeps the starting ammo of the lamb (which is unsurprising not containing milk). That could be the cause of the bug in the linked game.

Or it is just another bug.

**Comment by BevapDin** [comment]
I suggest the following:

When the monsters are checked for consistency (`monstergenerator::check_monster_definitions`), check that milkable monsters have raw milk in their starting ammo list.

When milking a monster, check it's actually milkable (via the flag) - this is probably already done. Afterwards, if it does not have raw milk in the starting ammo list, *just add it*.

At this point it does not matter. It is milkable (according to the flag), so it should contain milk. Maybe add a debug message there in case it happens again and again on the same monster.

File: src/monster.cpp (hunk 1 above)
Comment (davidpwbrown) [reply src/monster.cpp]: Nevermind, Im an absolute idiot, the sheep type starting_ammo is valid, I got my checks mixed up, knew it was weird that was happening.

Comment (davidpwbrown) [reply src/monster.cpp]: Ah, that is something else to consider yeah, my latest commit fixes the upgrade from milk to raw_milk, but dosnt hardcode the need for milk ( so mods can do weird stuff and define chocolate_milk or something if they want )

I think the latest commit should fix this case, as, when it changes to mon_sheep from lamb, its type still has the sheeps starting_ammo defined, and if its milkable, yet has empty ammo but type->starting ammo defined, the function will fill it up with its type->starting_ammo

`    if( type->starting_ammo.empty() ) {
        debugmsg( "monster %s has no starting ammo to refill udders", get_name() );
        return;
    }
    if( ammo.empty() ) {
        // legacy animals got empty ammo map, fill them up now if needed.
        ammo[type->starting_ammo.begin()->first] = type->starting_ammo.begin()->second;
    }`

If the type->starting_ammo is empt,y thats the real problem, but luckily, thats not actually happening, i was wrongf before.

**Comment by davidpwbrown** [comment]
> I suggest the following:
> 
> When the monsters are checked for consistency (`monstergenerator::check_monster_definitions`), check that milkable monsters have raw milk in their starting ammo list.
> 
> When milking a monster, check it's actually milkable (via the flag) - this is probably already done. Afterwards, if it does not have raw milk in the starting ammo list, _just add it_.
> 
> At this point it does not matter. It is milkable (according to the flag), so it should contain milk. Maybe add a debug message there in case it happens again and again on the same monster.

This is pretty much what ive ended up doing, added some checks to check_monster_definitions.
And just added its types ammo to its ammo when refilling udders.

Seemed silly to restrict it to milk_raw, when the JSOn allowed any item to be defined, so Ive just added a check if its a liquid item to the definition checker. and that there isnt more than one.

File: src/savegame_json.cpp [hunk 3]
```diff
@@ -1931,10 +1931,18 @@ void monster::load( const JsonObject &data )
     data.read( "dragged_foe_id", dragged_foe_id );
 
     if( data.has_int( "ammo" ) && !type->starting_ammo.empty() ) {
-        // Legacy loading for ammo.
+        // Legacy loading for ammo.z
```
Comment (davidpwbrown) [inline src/savegame_json.cpp]:
```suggestion
        // Legacy loading for ammo.
```
