### PR TITLE
Fix #79551

### LINKED ISSUE #79551: Crash on game exit
### Describe the bug

I get consistent crashes/process freezes when exiting the game from the main menu on any local build I make, starting from commit [032101a](https://github.com/CleverRaven/Cataclysm-DDA/commit/032101a6786bf19a30c054b0c0a241c3902e94ec).

The last commit without this issue is [5c6ee96](https://github.com/CleverRaven/Cataclysm-DDA/commit/5c6ee960253f49c8c080858eb62738ca6b5bc5ad)

Happens with both clang and gcc.
```
Debian clang version 14.0.6
gcc (Debian 12.2.0-14) 12.2.0
```

### Attach save file

N/A

### Steps to reproduce

```
$ git checkout 032101a # but any newer commit has the same issue
$ make RELEASE=1 TILES=1 SOUND=1 LOCALIZE=0 ASTYLE=0 LINTJSON=0 TESTS=0 RUNTESTS=0 CLANG=1
```

Then

1. run cataclysm-launcher
2. open options->settings or options->keybindings screen
3. Exit the game

EITHER
 
4a. Get the following output, can happen on release and debug, clang and gcc:
```
$ ./cataclysm-tiles
corrupted double-linked list
```
and the process hangs, need to kill/terminate it. No error in debug.log.

OR (only when compiled with clang in RELEASE)

4b. Get this crash (but at least the process exits and doesn't hang)
```
$ ./cataclysm-tiles
free(): double free detected in tcache 2
The program has crashed.
See the log file for a stack trace.
...
```

OR (only when compiled with gcc in RELEASE)

4c. Get this crash (but at least the process exits and doesn't hang)
```
$ ./cataclysm-tiles
munmap_chunk(): invalid pointer
The program has crashed.
See the log file for a stack trace.
...
```

### Expected behavior

Game exits cleanly.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 12 (bookworm); Release: 12; Codename: bookworm; 
- Game Version: 032101a678 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/18682174/crash.log)
[debug.log](https://github.com/user-attachments/files/18682175/debug.log)

Edit: added gcc-specific error

### PR DESCRIPTION
**Pull request by alef**
#### Summary
Bugfixes "#79551 Crash calling destructor twice"

#### Purpose of change
Rename the destructor to deinit.

#### Describe the solution
Avoid calling manually this destructor because it will called again at program exit and try to deallocate internal components on the heap twice.

#### Testing
✔ Tested on WSL/Ubuntu and Windows

### CODE REVIEW

File: src/debug.cpp [hunk 1]
```diff
@@ -704,8 +704,8 @@ struct OutputDebugStreamA : public std::ostream {
 #endif
 
 struct DebugFile {
-    ~DebugFile();
```
Comment (moxian) [inline src/debug.cpp:707]: We still want to have a destructor that calls `deinit()` in it, right? In case `deinitDebug()` isn't called for whatever reason..

**Review by moxian — APPROVED** [review]
