### PR TITLE
Fix "Repair auto-snap does not work in Horizontal/Hybrid modes"

### LINKED ISSUE #10873: Vehicle Examine Interface: Repair auto-snap does not work in Horizontal/Hybrid modes
In vertical mode, `r` will auto-snap to damaged sections (i.e. if the currently-highlighted section has no damaged parts) so if you're repairing a vehicle in its entirety, you can just hold down `r` and hit Enter occasionally to choose the tool to repair with.

In Horizontal/Hybrid modes, repeatedly hitting `r` when a non-damaged section is highlighted just makes the cursor snap around randomly, as far as I can tell.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7772905-vehicle-examine-interface-repair-auto-snap-does-not-work-in-horizontal-hybrid-modes?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BevapDin**
Fixes #10873

### CODE REVIEW

File: src/veh_interact.cpp [hunk 1]
```diff
@@ -643,7 +643,11 @@ void veh_interact::do_repair()
             int xOffset = veh->parts[p].mount.y + ddy;
             int yOffset = -(veh->parts[p].mount.x + ddx);
 
-            move_cursor(xOffset, yOffset);
+            if (vertical_menu) {
+                move_cursor(xOffset, yOffset);
+            } else {
+                move_cursor(-yOffset, xOffset);
+            }
```
Comment (narc0tiq) [inline src/veh_interact.cpp]: Since you're here anyway, you may as well make `xOffset` actually calculate an offset on the vehicular X axis, with the same happening to `yOffset` on the Y axis, and re-sign and re-order as needed:

```C++
int xOffset = veh->parts[p].mount.x + ddx;
int yOffset = veh->parts[p].mount.y + ddy;

if (vertical_menu) {
    move_cursor(-yOffset, xOffset);
} else {
    move_cursor(xOffset, yOffset);
}
```

As I understand it, the vertical menu vehicle rotation is the one that's non-canonical, so we shouldn't be judging X and Y based on its orientation.

Comment (BevapDin) [inline src/veh_interact.cpp]: You're right. It has been fixed.
