### PR TITLE
fix negative KCAL and VITAMIN_ABSORB_MOD enchantments

### LINKED ISSUE #74974: [Perks] Can eat despite compressed eating window thanks to other calorie boosters
### Describe the bug

Using things that increase the calories gained from eating allows to gain calories despite having an effect preventing calorie gain

### Attach save file

[TEST PERK-trimmed.tar.gz](https://github.com/user-attachments/files/16169500/TEST.PERK-trimmed.tar.gz)

### Steps to reproduce

1. Debug in the compressed eating window perk and set time at 8:00 AM
2. See that anything you eat got zero calories
3. Install the expanded digestive system CBM
4. See how you can gain calories despite CEW saying that you won't gain any

If using the save:
1. Look at the inventory. See that protein rations are zero-calorie
2. Activate the CBM to install it. See that protein rations grant calories now

### Expected behavior

Not being able to gain calories due to the effect being intended to prevent calorie gain

### Screenshots

Compressed
Compressed Expanded

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3737 (23H2)
- Game Version: cdda-experimental-2024-06-11-0319 99ed329 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bombastic Perks [bombastic_perks]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Fix #74974
#### Describe the solution
Prevent the enchantment from making food with negative calories and vitamins
Throw a ludicriously high negative multiplier for enchantments in perk_eating_window trait, so no another enchantment can move it
Replace `150% bonus` text in description to one that people understand more clearly, `250% bonus`

### CODE REVIEW

File: src/consumption.cpp [hunk 1]
```diff
@@ -245,6 +245,8 @@ static int compute_default_effective_kcal( const item &comest, const Character &
     }
 
     kcal = you.enchantment_cache->modify_value( enchant_vals::mod::KCAL, kcal );
+kcal = std:
+           max( 0, kcal );
```
Comment (GuardianDll) [inline src/consumption.cpp:249]:
```suggestion
kcal = std::max( 0, kcal );
```

File: src/consumption.cpp [hunk 2]
```diff
@@ -288,6 +290,8 @@ static std::map<vitamin_id, int> compute_default_effective_vitamins(
     for( std::pair<const vitamin_id, int> &vit : res ) {
         vit.second = you.enchantment_cache->modify_value( enchant_vals::mod::VITAMIN_ABSORB_MOD,
                      vit.second );
+vit.second = std:
+                     max( 0, vit.second );
```
Comment (GuardianDll) [inline src/consumption.cpp:294]:
```suggestion
vit.second = std::max( 0, vit.second );
```

File: data/mods/BombasticPerks/perks.json [hunk 3]
```diff
@@ -716,7 +716,7 @@
     "id": "perk_eating_window",
     "name": { "str": "Compressed Eating Window" },
     "points": 0,
-    "description": "You're so used to squeezing all your meals into a short time that your body has adapted to it.  You gain +150% kcal and vitamins from any meals eaten between noon and 6 p.m., but 0 calories and vitamins for any meals eaten outside that time period.",
+    "description": "You're so used to squeezing all your meals into a short time that your body has adapted to it.  You gain +250% kcal and vitamins from any meals eaten between noon and 6 p.m., but 0 calories and vitamins for any meals eaten outside that time period.",
```
Comment (Hyperseeker) [inline data/mods/BombasticPerks/perks.json:719]: This is misleading: it implies a 250% *bonus*, for a total of 350% caloric and vitamin content. The perk actually does add 150% to those, for a total of 250%.

I think "You gain 250% <...>", without the plus, should relate the idea clearly.

Comment (GuardianDll) [reply data/mods/BombasticPerks/perks.json:719]: Would `2.5 times` work better here? Because i saw people who assumed 150% means x0.5 bonus to calories

Comment (Hyperseeker) [reply data/mods/BombasticPerks/perks.json:719]: That should work better. I suspect someone will still stumble over "2.5 times" as "*extra* 250%", because users are human, but at that stage, there's little the developers can do to make it any clearer.

Comment (GuardianDll) [reply data/mods/BombasticPerks/perks.json:719]:
```suggestion
    "description": "You're so used to squeezing all your meals into a short time that your body has adapted to it.  You gain 2.5 times as much calories and vitamins from any meals eaten between noon and 6 p.m., but 0 calories and vitamins for any meals eaten outside that time period.",
```

Comment (Hyperseeker) [reply data/mods/BombasticPerks/perks.json:719]: Should probably me "as many calories", since both calories and vitamins are countable.

File: src/consumption.cpp [hunk 4]
```diff
@@ -245,6 +245,7 @@ static int compute_default_effective_kcal( const item &comest, const Character &
     }
 
     kcal = you.enchantment_cache->modify_value( enchant_vals::mod::KCAL, kcal );
+    kcal = std::max( 0, kcal );
```
Comment (GuardianDll) [inline src/consumption.cpp:248]:
```suggestion
    kcal = std::max( 0.0f, kcal );
```
