### PR TITLE
vision_transparency_cache improvements

### LINKED ISSUE #78092: Reduced performance
### Describe the bug

I did an experiment. I took two versions of the game:
- cdda-windows-tiles-x64-2024-08-01-0043
- cdda-windows-with-graphics-x64-2024-11-23-0704

I loaded the game from August 1. I set item spawn scaling factor = 0.01. Then I created a world and a character. Started with Liam. And made a save.

Savings copied to the game from November 23.

Each version of the game had a save loaded and a standby mode enabled until dawn (19 hours and 59 minutes). (And video recording was enabled).

The duration amounted to:
- 48 seconds for the August version
- 77 seconds for the November version.

The difference 77/48 ~ 60%. Which is quite significant.

Repeating the experiment (new start: additionally removed character stuff and changed the language to English): 65 seconds vs. 95 or ~46%. 

### Attach save file

I'm not sure it's needed. But just in case, this is the full archive:
[test.zip](https://github.com/user-attachments/files/17879388/test.zip)

### Steps to reproduce

n/a

### Expected behavior

n/a

### Screenshots

_No response_

### Versions and configuration

cdda-windows-tiles-x64-2024-08-01-0043
cdda-windows-with-graphics-x64-2024-11-23-0704

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Performance "vision_transparency_cache isn't rebuilt if transparency_cache_dirty isn't set"

#### Purpose of change
Fixes #78092

#### Describe the solution
vision_transparency_cache rebuilds regardless of player z level
vision_transparency_cache only rebuilds if transparency_cache_dirty is set (which as far as I can tell it should be everywhere relevent)

#### Describe alternatives you've considered
Planning on attempting a followup PR making translucency non binary

#### Testing
Load save from linked issue, wait in place until daylight (20hr). Before it took 59s now it takes 34s.
Before hotpath for building the vision_transparency_cache was ~50% now it's ~0.02%
Tested that running past a window with Digitigrade Legs, Paws and Beast "correctly" obscured vision

### CODE REVIEW

**Comment by zakhad** [comment]
https://github.com/user-attachments/assets/c2e5101b-29aa-490c-b010-70be77ceb7a5

https://github.com/user-attachments/assets/eeb45af2-5a0b-4c6f-b3f7-7d530203d990

Been trying to figure out why my game has been running abysmally slow is this related? as it comes and goes when my game suddenly goes slow, for a while idk a few days, then suddenly fast again.

- OS: Windows
    - OS Version: 7
- Game Version: 78d8461 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Slowdown Fungal Growth [no_fungal_growth]
]

**Comment by Procyonae** [comment]
I doubt it bc that looks alot more severe, if you're not over a lab or something and can reproduce it opening an issue with your save would be good

**Comment by zakhad** [comment]
> It could be but I can't really magically tell that without a save where it can be reproduced


I have updated today, to see if any recent changes have helped, but it has not. 

- OS: Windows
    - OS Version: 7
- Game Version: 71b3dbe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Disable NPC Needs [no_npc_food],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Bombastic Perks [bombastic_perks],
    Slowdown Fungal Growth [no_fungal_growth]
]
https://discord.com/channels/598523535169945603/598523535169945607/1309656626814390365
here is a video in discord i shared as i have no nearby lab that's close enough where i believe i can discount this as an influence

https://github.com/user-attachments/assets/4f33c550-1bd5-4eaa-97da-5c348fb24c84
[Zakhadia_BigCity-trimmed.tar.gz](https://github.com/user-attachments/files/17894839/Zakhadia_BigCity-trimmed.tar.gz)

My issue is that the game goes slow for a while but then after a while uncertain honestly a few days, it resumes playing at "normal" speed i can't for the life of my figure out why this is happening so i presume it's some sort of cache issue which made me wondered if this pr would fix it,

Thank you for your time.

**Comment by zakhad** [comment]
https://github.com/user-attachments/assets/d49fa1e3-120a-4629-80bb-62fc07211289

This is another save where now my game is running fast again, all i've been doing is tailoring repair jobs for the most part in the same location, i have been disassembling clothing after repairing them, one to improve my skill and 2 to get more resources from some of the items.

**Comment by Procyonae** [comment]
Your slowdown is something EOC related so I'd open up an issue for it (Here's the eocs.output renamed so I can upload it if anyone wants to take a gander now)
[eocs.txt](https://github.com/user-attachments/files/17901800/eocs.txt)

**Comment by GuardianDll** [comment]
lol, it was closed because of #78136?

**Comment by Night-Pryanik** [comment]
That's weird. I didn't know that a PR could close another PR.

File: src/lightmap.cpp [hunk 1]
```diff
@@ -187,65 +187,88 @@ bool map::build_transparency_cache( const int zlev )
...
-    if( is_crouching || is_prone || low_profile ) {
-        for( const tripoint_bub_ms &loc : points_in_radius( p, 1 ) ) {
-            if( loc != p && coverage( loc ) >= 30 ) {
-                // If we're crouching or prone behind an obstacle, we can't see past it.
-                dirty |= vision_transparency_cache[loc.x()][loc.y()] != LIGHT_TRANSPARENCY_SOLID;
-                solid_tiles.emplace_back( loc );
+    if( is_player_z ) {
+        // This segment handles vision when the player is crouching or prone. It only checks adjacent tiles.
+        // If you change this, also consider creature::sees and map::obstacle_coverage.
+        // TODO: Is fairly nonsense because it changes vision for everyone only (eg if you @ crouch behind the window W then the NPC N and monster M can't see each other bc the window is counted as opaque)
```
Comment (osuphobia) [inline src/lightmap.cpp:218]: Did you actually tested this scene? I commented this segment out and it didn't change how creautre see each other except for player. Looks like `Creature::sees( const Creature &critter )` is not affected by vision_transparency_cache? @Procyonae

Comment (Procyonae) [reply src/lightmap.cpp:218]: Yes I did test it and Creature::sees should definitely be taking transparency into account and idk where else it would do it if it's not using this cache

Comment (osuphobia) [reply src/lightmap.cpp:218]: I think `vision_transparency_cache` is used to build `seen_cache` and `camera_cache` for the player.
While `Creature::sees` is calling `map::sees`, and only `transparency_cache` is used there?
https://github.com/CleverRaven/Cataclysm-DDA/blob/aea8979a08f4275ac0d42b9e10862f58e7f85d39/src/creature.cpp#L648
https://github.com/CleverRaven/Cataclysm-DDA/blob/aea8979a08f4275ac0d42b9e10862f58e7f85d39/src/map.cpp#L7284-L7289
And `Creature::sees( const Creature &critter )` is taking account of `coverage` separately.
https://github.com/CleverRaven/Cataclysm-DDA/blob/aea8979a08f4275ac0d42b9e10862f58e7f85d39/src/creature.cpp#L531-L610

Comment (Brambor) [reply src/lightmap.cpp:218]: Maybe you mean screenshots of profiling. That is here: https://discord.com/channels/598523535169945603/598523535169945607/1310565162511499335

Comment (osuphobia) [reply src/lightmap.cpp:218]: To make it clearer, I mean the `changes vision for everyone` scene is not happening bc `vision_transparency_cache` is not used when it's not a sight to/from the player.
