### PR TITLE
Weather type refactor

### LINKED ISSUE #42373: gear get's damaged when it snows
# Describe the bug

walking aroun wile it's snowing damages worn gear.

# Steps To Reproduce

1. get you character outside in open air
2. make it snow
3. move around some and observe as your gear starts ripping itself apart

# Expected behavior

gear not getting destroyed

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4329-ga3e5f32 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    More Survivor Stuff [more_survivor_stuff],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

tried to reproduce without mods to be sure and it still happens

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: None```

#### Purpose of change

Allow different damage types in weather effects instead of only bash.

Probably fixes #42373.

#### Describe the solution

See commit messages

#### Testing

1. Add following effects to `clear` weather type and see player getting damaged with various damage types when the weather is clear:

```JSON
    "effects": [
      {
        "must_be_outside": true,
        "time_between": "1 seconds",
        "one_in_chance": 1,
        "damage_data": [
          { "damage_type": "electric", "amount": 1.0 },
          { "damage_type": "biological", "amount": 3 },
          { "damage_type": "bash", "amount": 4.0 },
          { "damage_type": "heat", "amount": 2.0 }
        ]
      }
    ]
```

### CODE REVIEW

File: src/weather_type.cpp [hunk 1]
```diff
@@ -209,7 +209,12 @@ void weather_type::load( const JsonObject &jo, const std::string & )
         optional( weather_effect_jo, was_loaded, "trait_id_to_add", effect.trait_id_to_add );
         optional( weather_effect_jo, was_loaded, "trait_id_to_remove", effect.trait_id_to_remove );
         optional( weather_effect_jo, was_loaded, "target_part", effect.target_part );
-        optional( weather_effect_jo, was_loaded, "damage", effect.damage, 0 );
+        // TODO: make this work with `was_loaded`
+        if( weather_effect_jo.has_array( "damage_data" ) ) {
+            effect.damage_data = load_damage_instance( weather_effect_jo.get_array( "damage_data" ) );
+        } else if( weather_effect_jo.has_object( "damage_data" ) ) {
+            effect.damage_data = load_damage_instance( jo );
+        }
```
Comment (anothersimulacrum) [inline src/weather_type.cpp:217]: I believe you can use `assign()` here, like items do.

Comment (ZhilkinSerg) [reply src/weather_type.cpp]: Thanks.

**Comment by Ramza13** [comment]
In #42786 I have incorporated this change as its a great idea.  This PR would still be fine, just letting you know the functionality will eventually be added if you don't want to un draft this.
