### PR TITLE
Camp upgrade vehicle fixes

### LINKED ISSUE #30691: Upgrading faction camp puts buildings into vehicles
# Describe the bug

Recovered an NPC from the faction_base_camp_5 mission, and had a car parked at the place of the second tent. When the tent appeared, it fused with the car.

# Steps To Reproduce

1. Park a car on the second tent place.
2. Finish the mission.

# Expected behavior

Warning that a vehicle is in the way.

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3251-gba376ea
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Boats [boats],
    No Filthy Clothing [no_filthy_clothing]
]

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Camp upgrade vehicle fixes"```

#### Purpose of change
Fixes #30691

#### Describe the solution
Add proper vehicle collision checks to update_mapgen for other jmapgen types.

#### Describe alternatives you've considered
In the linked issue, there is a comment stating that starting a faction camp on a vehicle makes the vehicle dissappear.

I noticed this too, it reappears after a while, but contsant unboarding vehicle debugmsgs appear, Ill try and fix this in a separate PR

#### Testing
Sent NPC at camp on mission to build tents, put vehicle over where the tents would appear, NPC could not be recalled ( with a popup info msg  about there being a vehicle in the way )

#### Additional context
Thanks to ralreegorganon for assisting me through this, infact lets be honest, he wrote this commit mostly, told me to "clean it up" , seeing as I couldnt actually see anything wrong with it, I may not be the best person to judge what needs cleaning, but here it is.

### CODE REVIEW

File: src/faction_camp.cpp [hunk 1]
```diff
@@ -555,7 +555,7 @@ void talk_function::start_camp( npc &p )
     }
     const recipe &making = camp_type.obj();
     if( !run_mapgen_update_func( making.get_blueprint(), omt_pos ) ) {
-        popup( _( "%s failed to start the %s basecamp." ), p.disp_name(), making.get_blueprint() );
+        popup( _( "%s failed to start the %s basecamp, perhaps there is a vehicle in the way." ), p.disp_name(), making.get_blueprint() );
```
Comment (kevingranade) [inline src/faction_camp.cpp]:
```suggestion
        popup( _( "%s failed to start the %s basecamp, perhaps there is a vehicle in the way." ),
               p.disp_name(), making.get_blueprint() );
```

File: src/faction_camp.cpp [hunk 2]
```diff
@@ -2383,7 +2383,7 @@ bool basecamp::upgrade_return( const point &dir, const std::string &miss,
         return false;
     }
     if( !run_mapgen_update_func( making.get_blueprint(), upos ) ) {
-        popup( _( "%s failed to build the %s upgrade." ), comp->disp_name(),
+        popup( _( "%s failed to build the %s upgrade, perhaps there is a vehicle in the way." ), comp->disp_name(),
```
Comment (kevingranade) [inline src/faction_camp.cpp]:
```suggestion
        popup( _( "%s failed to build the %s upgrade, perhaps there is a vehicle in the way." ),
               comp->disp_name(),
```

File: src/faction_camp.cpp [hunk 3]
```diff
@@ -2720,7 +2720,7 @@ bool basecamp::survey_return()
                                      _( "Select an expansion:" ) );
 
     if( !run_mapgen_update_func( expansion_type.str(), where ) ) {
-        popup( _( "%s failed to add the %s expansion" ), comp->disp_name(),
+        popup( _( "%s failed to add the %s expansion, perhaps there is a vehicle in the way." ), comp->disp_name(),
```
Comment (kevingranade) [inline src/faction_camp.cpp]:
```suggestion
        popup( _( "%s failed to add the %s expansion, perhaps there is a vehicle in the way." ),
               comp->disp_name(),
```
