### PR TITLE
Fix radio mod not working

### LINKED ISSUE #16774: radio activation mod doesn't work
just activate it and press the correspoding button on the RC control

### PR DESCRIPTION
**Pull request by Coolthulhu**
Fixes #16774

While I was at it, I changed the recipe to be a bit cheaper. It's not really an overpowered item, it's one-use and requires good explosives to be worth it.

### CODE REVIEW

**Comment by illi-kun** [comment]
Replacement of receiver by antenna looks weird.

**Comment by Rivet-the-Zombie** [comment]
I think the assumption in the original recipe was that a 'receiver' also contains an antenna?

File: src/map.cpp [hunk 1]
```diff
@@ -5300,8 +5300,7 @@ static bool trigger_radio_item( item_stack &items, std::list<item>::iterator &n,
                                 std::string signal )
 {
     bool trigger_item = false;
-    // Check for charges != 0 not >0, so that -1 charge tools can still be used
-    if( n->charges != 0 && n->has_flag("RADIO_ACTIVATION") && n->has_flag(signal) ) {
+    if( n->has_flag("RADIO_ACTIVATION") && n->has_flag(signal) ) {
```
Comment (mugling) [inline src/map.cpp]: astyle?
