### PR TITLE
Bugfix: Fix widget and label alignment

### LINKED ISSUE #59611: Sidebar widgets with `rows` layout are mis-aligned
### Describe the bug

Sidebar widgets that stack `columns` layouts in `rows` are mis-aligned, if cells have defined width.

### Steps to reproduce

Not really sure. Make a sidebar widget using a `rows` layout, which contains `columns` layouts, which contain elements with a defined width.

Added code for a sidebar that reproduces the behaviour under "Additional context". The important points are the layouts with `width` defined, and stacking multiple `column` layouts.

### Expected behavior

Alignment/cell width should not change when stacking rows.

### Screenshots

Top: Tree separate widgets with `columns` layout.  
Bottom: the same three widgets, but into a `rows` layout widget.  
Both should look the same.

grafik

Note the indent, already in the first!

### Versions and configuration

- OS: Windows 10
- Game version: [cdda-experimental-2022-07-25-0625](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-07-25-0625) (32ee0b1)
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: [ dda, no_npc_food, no_fungal_growth ]

### Additional context

Sidebar code reproducing the issue. Put into `data/json/ui`, e.g. as `sidebar-test.json`.

```json
[
  {
    "id": "test_environment_layout",
    "type": "widget",
    "label": "Environment",
    "description": "Shows environment and place information, like time, weather, light, etc.",
    "style": "layout",
    "arrange": "rows",
    "widgets": [ "test_time_moon_layout", "test_weather_layout", "test_place_sound_layout" ]
  },
  {
    "id": "test_time_moon_layout",
    "type": "widget",
    "label": "Date/Time/Moon",
    "description": "Shows date, time and moon phase.",
    "style": "layout",
    "arrange": "columns",
    "widgets": [ "date_desc_no_label", "test_time_layout", "moon_phase_graph" ]
  },
  {
    "id": "test_weather_layout",
    "type": "widget",
    "style": "layout",
    "label": "Weather",
    "description": "Shows weather, light and wind.",
    "arrange": "columns",
    "widgets": [ "weather_desc_no_label", "test_lighting_layout", "test_wind_layout" ]
  },
  {
    "id": "test_place_sound_layout",
    "type": "widget",
    "style": "layout",
    "label": "Place/Sound",
    "description": "Shows the current location and sound emitted.",
    "arrange": "columns",
    "widgets": [ "test_place_layout", "test_sound_layout" ]
  },
  {
    "id": "test_time_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 10,
    "widgets": [ "sundial_time_desc_no_label" ]
  },
  {
    "id": "test_lighting_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 10,
    "widgets": [ "lighting_desc_no_label" ]
  },
  {
    "id": "test_wind_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 18,
    "widgets": [ "wind_desc_no_label" ]
  },
  {
    "id": "test_place_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 26,
    "widgets": [ "test_place_desc" ]
  },
  {
    "id": "test_sound_layout",
    "type": "widget",
    "style": "layout",
    "arrange": "rows",
    "width": 10,
    "widgets": [ "sound_num" ]
  },
  {
    "id": "test_place_desc",
    "type": "widget",
    "copy-from": "place_desc",
    "flags": [ "W_LABEL_NONE" ]
  },
  {
    "id": "test_sidebar",
    "type": "widget",
    "style": "sidebar",
    "label": "test",
    "description": "Test sidebar",
    "separator": ": ",
    "width": 48,
    "padding": 1,
    "widgets": [
      "separator",
      "test_environment_layout",
      "separator",
      "test_time_moon_layout",
      "test_weather_layout",
      "test_place_sound_layout",
      "separator"
    ]
  }
]
```

### PR DESCRIPTION
**Pull request by mlange-42**
#### Summary
Bugfixes "Fix widget and label alignment"

#### Purpose of change

Originally, I just wanted to fix #59611: mis-aligned/off widgets in row layouts containing column layouts.

Turned out that is requires several changes to the label width propagation logic. Hopefully makes layouts and label padding more consistent.

#### Describe the solution

* [x] Make recursion for bottom-up propagation of label width start only at top-level elements (sidebars).
* [x] Make recursion for top-down propagation of separator and padding start only at top-level elements (sidebars).

> Originally, each widget did its own propagation pass. In the best case, things were done with unnecessary repetitions. In the worst case, the result depended on load order.

* [x] Modify label width propagation to cover the entire tree.
* [x] Modify label width propagation to only align in "rows" layouts.

> Widgets above each other are aligned, while those next to each other are not.
> Maybe this was even the original intent?

* [x] Add a bool property `pad_labels` to enable/disable label alignment for layouts and individual widgets.

> Implemented so that using default `pad_labels` on all widgets and sub-widgets gives the same result as without the feature:
> `row` layouts and elementary widgets default to `true`, all column layouts to `false`.

* [x] Document the new widget property `pad_labels`.

Taken over from #59646, as it is closely related and probably better to test in conjunction

* [x] Get rid of special handling of multiline widgets in column width calculation

> Currently, multiline widgets (overmap, legends) don't pad to the calculated column width. The intention here was probably to automatically shrink them, butit causes problems with widgets in neighboring columns that exceed the multiline widget's height.
> The same effect can now be achieved by using `minimum_columns`, or wrapping widgets into layouts with explicit width.

* [x] Use only `width = 0` as "not specified", not also `width = 1` 

> Currently, a width of 0 or 1 is interpreted as "make the column as wide as calculated". This has the effect that small widgets of width 1 (wrapped into a layout for explicit width) are not possible.
> Only a width of 0 should be interpreted as such, and 0 should be the default if width is not specified (currently it is 1)

* [x] Fix sidebars affected by the multiline widget changes

> Several instances of overmap and bodygraph usage were "broken"

* [x] Fix all tests 

> Some tests had to be adapted due to the fix for label padding, as well as changed space-filling by multiline widgets.

#### Describe alternatives you've considered

None

#### Testing

Tried different setups of the original issue, as well as top-level and nested "rows" widgets.

All other sidebars still looking ok. ~~Some are still broken due to changed multiline widget handling.~~

#### Additional context

Fixes #59611

Potentially part of the solution for #58991

Screenshot. 

* 1st and 2nd block: solved issue #59611 (both blocks look the same now)
* 3rd block: `rows` layout widget with padded labels, all `pad_labels` default
* 4th block: `cols` layout widget of `rows` widgets with padded labels, all `pad_labels` default (align only within rows)
* 5th block: `cols` layout widget of `rows` widgets. `pad_labels` is `true` for the top-level layout (everything pads for `Activity`), and `false` for the Heat widget

Screenshot of the widgets that had broken tests and required changes to the test code (the space next to the overmap is as expected due to no more special handling).

### CODE REVIEW

**Comment by mlange-42** [comment]
Tests are currently failing as they use plain widgets, no sidebar to start the recursions.

**Comment by mlange-42** [comment]
> Tests are currently failing as they use plain widgets, no sidebar to start the recursions.

Fixed tests by starting recursions on test widgets explicity (eba1f75).

**Comment by mlange-42** [comment]
Moved the final changes from #59646 oder here.

File: tests/widget_test.cpp [hunk 1]
```diff
@@ -2473,71 +2473,71 @@ TEST_CASE( "Widget alignment", "[widget]" )
...
                "           " + line3 );
 
         bp_legend._label_align = widget_alignment::LEFT;
         bp_legend._text_align = widget_alignment::LEFT;
 
         CHECK( bp_legend.layout( ava, sidebar_width ) ==
-               line1 + "\n" +
+               line1 + "      \n" +
                line2 + "\n" +
                line3 + "           " );
```
Comment (mlange-42) [inline tests/widget_test.cpp:2501]: There are still 6 failing tests. However, there is no difference between actual and expected (using a diff tool).

E.g., for this test:

```
  "<color_c_yellow>B</color> bitten  <color_c_pink>I</color> infected
  <color_c_magenta>%</color> broken      
  <color_c_light_gray>=</color> splinted  <color_c_white>+</color> bandaged
  <color_c_light_green>$</color> disinfected  <color_c_light_red>b</color>
  bleeding           "
  ==
  "<color_c_yellow>B</color> bitten  <color_c_pink>I</color> infected
  <color_c_magenta>%</color> broken      
  <color_c_light_gray>=</color> splinted  <color_c_white>+</color> bandaged
  <color_c_light_green>$</color> disinfected  <color_c_light_red>b</color>
  bleeding           "
```

Comment (mlange-42) [reply tests/widget_test.cpp:2501]: It is weird! When comparing `length()` of both strings, I get different results: 288 vs. 274 (actual vs. expected).

Comment (mlange-42) [reply tests/widget_test.cpp:2501]: Finally found that there was no visible difference due to how the test framework prints things. Actually, there are spaces after `bandaged`.

**Comment by Inglonias** [comment]
Holy crap, how did I miss this? If this does everything you say it does, mad props. Excellent work. I'm going to need to spend some time looking through this.

File: src/widget.cpp [hunk 2]
```diff
@@ -545,10 +549,10 @@ void widget::finalize()
     widget_factory.finalize();
 
     for( const widget &wgt : widget::get_all() ) {
-        if( wgt.explicit_separator || wgt.explicit_padding ) {
+        if( wgt._style == "sidebar" ) {
```
Comment (Inglonias) [inline src/widget.cpp:552]: The idea here was to propagate separators and padding down from widgets that explicitly defined it so we didn't need to redefine it everywhere in JSON. Does it still work that way? It doesn't look like it.

Comment (Inglonias) [reply src/widget.cpp:552]: Starting up the game, it looks like my tired brain forgot how I implemented `finalize_label_width_recursive`, and things still work just fine. Again - Marvelous work.

Comment (mlange-42) [reply src/widget.cpp:552]: Thanks!

Yes, still works I hope. The change just prevents it from traversing partial trees multiple times. Which could also have resulted in unwanted overwrites, depending on load order. Now, it should be consistent independent of the order of definition.

**Comment by mlange-42** [comment]
@Inglonias This certainly deserves some code review and I was surprised about the quick merge.

It does what I wrote, but hopefully nothing else. 😉 

The bunch of existing sidebars only required expected changes, which is probably a good sign. Sidebar "structured", which I maintain, has quite a complex layout with exactly defined widths, and survived the changes unharmed. And finally, three bugs were seemingly fixed (#58991, #59669, #59611) and sidebar "mobile" is even already published!

However, this was completely unexpected when I started to fix a seemingly small bug. Thanks for the props!

**Comment by YehnBeep** [comment]
Thank you for this - it fixed the sidebar I made for myself and some stuff that stubbornly wouldn't align.
