### PR TITLE
Restore query for manual installation

### LINKED ISSUE #32462: Manual CBM Install lacks confirmation/success chance
# Describe the bug

When activating CBMs to perform a manual installation, the installation happens instantly without prompting you to confirm, or giving chances of success.

# Steps To Reproduce

1. Navigate to CBM in inventory or use 'a'ctivate
2. Activate the CBM.

# Expected behavior

Manual Installation should prompt a confirmation before proceeding, and should give at least an estimate of success. Why: This is how it worked previously, and how it works currently with the autodoc.

# Screenshots

https://i.imgur.com/gGB7qGE.png
https://i.imgur.com/4iphb24.png

Can't show that something doesn't exist in a screenshot, but Activating the CBM causes the log events seen in second screen

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version   ((Windows 7))
- Game Version: 0.D-5599-gfd556e6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Fast Healing [fast_healing],
    Hydroponics [hydroponics],
    More Locations [more_locations],
    Urban Development [Urban_Development],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classic Roguelike Classes [RL_Classes],
    **Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],**
    SpeedyDex [speedydex],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context

Character is a mod-added profession (C.R.I.T. Night-Walker) with numerous traits/mutations, and zero bionics, in a lab start. The last 5 mods on the list (including Manual Installtion andSafe Autodoc) were added post world-gen. Doing so threw a few errors at me, but otherwise the game seems to perform as expected.

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: None```

#### Purpose of change
Fixes #32462 

#### Describe the solution
Add `can_install_bionics()` check in the proper place

#### Additional context
This also fixe a bug where installation by the surgeon would have displayed message about autodoc upon completion

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -3115,24 +3115,34 @@ void activity_handlers::try_sleep_finish( player_activity *act, player *p )
...
-        sounds::sound( autodocs.front(), 10, sounds::sound_t::music,
-                       _( "a sad beeping noise: \"Operation failed\"" ), true,
-                       "Autodoc",
-                       "failure" );
+        if( act->values[1] > 0 ) {
+            add_msg( m_good,
+                     _( "The operation is a success." ) );
+        } else {
+            add_msg( m_bad,
+                     _( "The operation is a failuer." ) );
```
Comment (Rail-Runner) [inline src/activity_handlers.cpp]:
```suggestion
                     _( "The operation is a failure." ) );
```

File: src/activity_handlers.cpp [hunk 2]
```diff
@@ -3115,24 +3115,34 @@ void activity_handlers::try_sleep_finish( player_activity *act, player *p )
...
-        const std::list<tripoint> autodocs = g->m.find_furnitures_in_radius( p->pos(), 1,
-                                             furn_str_id( "f_autodoc" ) );
-        sounds::sound( autodocs.front(), 10, sounds::sound_t::music,
-                       _( "a short upbeat jingle: \"Operation successful\"" ), true,
-                       "Autodoc",
-                       "success" );
+    if( act->str_values[6] == "true" ) {
+        if( act->values[1] > 0 ) {
+            add_msg( m_good,
+                     _( "The Autodoc retuns to its resting position after succesfully performing the operation." ) );
```
Comment (Rail-Runner) [inline src/activity_handlers.cpp]:
```suggestion
                     _( "The Autodoc returns to its resting position after succesfully performing the operation." ) );
```

File: src/activity_handlers.cpp [hunk 3]
```diff
@@ -3115,24 +3115,34 @@ void activity_handlers::try_sleep_finish( player_activity *act, player *p )
...
-        const std::list<tripoint> autodocs = g->m.find_furnitures_in_radius( p->pos(), 1,
-                                             furn_str_id( "f_autodoc" ) );
-        sounds::sound( autodocs.front(), 10, sounds::sound_t::music,
-                       _( "a short upbeat jingle: \"Operation successful\"" ), true,
-                       "Autodoc",
-                       "success" );
+    if( act->str_values[6] == "true" ) {
+        if( act->values[1] > 0 ) {
+            add_msg( m_good,
+                     _( "The Autodoc returns to its resting position after succesfully performing the operation." ) );
```
Comment (Rail-Runner) [inline src/activity_handlers.cpp]:
```suggestion
                     _( "The Autodoc returns to its resting position after successfully performing the operation." ) );
```
