### PR TITLE
Make it  possible to directly use vehicle mounted electric tools

### LINKED ISSUE #41018: Tool-rigs (welder, kitchen) attached to vehicles claim to have 0 charges
# Describe the bug

When  directly (e) using vehicle tool-rigs such as Kitchen Unit or Vehicle Welding Rig, the game claims that they have zero charges, even when the vehicle is properly powered via a charged battery and can be used normally indirectly, for crafting.  

# Steps To Reproduce

1. Create a functional, powered vehicle with a tool-rig, ie. Kitchen Unit
2. Try to (e) use it to activate it (ie. to activate it's Hotplate)
3. There game claims the tool has no charges.

# Expected behavior

The in-built tool should activate and consume charges from vehicle's battery

# Versions and configuration

    OS: Win 7
    Game Version: 0.E 2769-gf387ce8
    Graphics version: Tiles
    Ingame language: English

    Mods loaded: DDA, Disable NPC Needs, Blaze Ind., Magiclysm, No Rail Stations, Graphical Overmap, Graph. Overmap Magiclysm, No Fungal Monsters, Stats Through Skills

### PR DESCRIPTION
**Pull request by Menschheit**
#### Summary

SUMMARY: Bugfixes "Make it  possible to directly use vehicle mounted electric tools "

#### Purpose of change

Fix #41018

#### Describe the solution

While using vehicle mounted kichen or welding rig, the generated pseudo item doesn't have a magazine, gave it a pseudo magazine to make a happy family. 
Only made change for electric tools, didnt touch anything else because I don't know if there are actually bugs related.

#### Describe alternatives you've considered

Don't make a copy which is identical to the tool but define a new vehicle item.

#### Testing

Be able to use vehicle kichen and welding rig, other tools not tested. 

#### Additional context

Did additional test to make sure that it drains battery, but you may not be able to notice the 5 charges per use.

temp

### CODE REVIEW

**Comment by Menschheit** [comment]
Update: It seem that `item::ammo_capacity` works fine if a magazine exists, but I can confirm that `item::ammo_set` is broken even if I put a magazin into.

**Comment by Menschheit** [comment]
Update `item::ammo_set` and reverse some change in vehicle_use.cpp

File: src/item.cpp [hunk 1]
```diff
@@ -628,7 +629,8 @@ item &item::ammo_set( const itype_id &ammo, int qty )
     // check ammo is valid for the item
     const itype *atype = item_controller->find_template( ammo );
     if( atype->ammo && ammo_types().count( atype->ammo->type ) == 0 &&
-        !magazine_compatible().count( atype->get_id() ) ) {
+        !magazine_compatible().count( atype->get_id() ) && !( magazine_current() ) &&
```
Comment (BevapDin) [inline src/item.cpp:632]: `!( magazine_current() )` is only true when `magazine_current()` returns a null pointer. But the condition continues with dereferencing that pointer in the next check. That won't work.
```suggestion
        !magazine_compatible().count( atype->get_id() ) && magazine_current() &&
```

Comment (Menschheit) [reply src/item.cpp]: Some thing is wrong, I think what I made is
`if( atype->ammo && ammo_types().count( atype->ammo->type ) == 0 &&
        !magazine_compatible().count( atype->get_id() ) && !( magazine_current()  &&
        magazine_current()->ammo_types().count( atype->ammo->type ) ) )`

Need to wash my face and get some fresh air...

Comment (Menschheit) [reply src/item.cpp]: I wanted to explain again
We want to ckeck if the "ammo" is available.
1. "ammo" is not right ammo for the item.
2. "ammo" is not a magazine for the item.
the 3rd condition I want to make is
the item has no magazine or the  "ammo" is not suitable for the magazine
that is `!( magazine_current() && magazine_current()->ammo_types().count( atype->ammo->type ) )`
which is aquivalent to `!( magazine_current() || magazine_current()->ammo_types().count( atype->ammo->type )`.

both ways, if  magazine_current() is false the next condition won't checked so it's safe

Comment (ZhilkinSerg) [reply src/item.cpp]: You had parentheses put in wrong places then as you had:

`!( magazine_current() ) && magazine_current()->ammo_types().count( atype->ammo->type )`

which would cause crashes as `magazine_current()->ammo_types()` would only be called when `magazine_current()` is `nullptr`.

Comment (Menschheit) [reply src/item.cpp]: Yes I know, sorry for being incautious for that obvious mistake. I just want to explain that I am not agree with the suggested change and what I actually should have done.
