### PR TITLE
Fixed infinite water in puddles

### LINKED ISSUE #53638: Limited-water ponds still show as infinite when washing clothes
### Describe the bug

This is referring to the little one-tile ponds that were recently changed to have a limited amount of water in them. When washing clothes next to one, the interface still shows infinite and water does not appear to be consumed.

### Steps to reproduce

1. Craft a washboard
2. Get some filthy clothes
3. Find a puddle
4. Activate washboard
5. See that water shows as `0/inf`

### Expected behavior

Water shows as the amount in the nearby puddle(s)

### Screenshots

image
image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 49c6f2d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Bugfixes "Fixed infinite water in puddles."

#### Purpose of change
Closes #53638 - Limited-water ponds still show as infinite when washing clothes.

#### Describe the solution
- Removed separate check for `finite_water_source` iexamine function as now water is taken by the `water_from` function;
- Fixed infinite charges from tiles with `MURKY` flag;
- `map::use_amount_square` and `map::use_charges` functions create infinite water only is water source is indeed has infinite charges;
- Taught `item_stack::use_charges` function to correctly handle liquid items on the ground with `LIQUIDCONT` flag. Now you can spill liquid to any terrain with `LIQUIDCONT` flag and use it for crafting or washing items or any other activity involving liquids.

#### Describe alternatives you've considered
None.

#### Testing
- Tried to wash filthy item standing next to a puddle.
изображение
изображение
изображение
изображение

- Tried crafting standing next to a puddle.
изображение

#### Additional context
While you can examine terrain with`LIQUIDCONT` flag to pick up water, or use crafting or washing menu to consume water, you still can't pick it up directly (by pressing `g`). This could be done in subsequent PR.

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -4540,13 +4540,16 @@ item map::water_from( const tripoint &p )
...
-        return ret;
+        for( item &ret : get_map().i_at( p ) ) {
+            if( ret.made_of( phase_id::LIQUID ) ) {
+                ret.set_item_temperature( temp_to_kelvin( std::max( weather.get_temperature( p ),
+                                          temperatures::cold ) ) );
+                ret.poison = rng( 1, 6 );
+                ret.get_comestible()->parasites = 5;
+                ret.get_comestible()->contamination = { { disease_bad_food, 5 } };
+            }
+            return ret;
```
Comment (ZhilkinSerg) [inline src/map.cpp:4551]: This would return unconditionally after a very first iteration, so it would only check for a a single item in a map cell. Looks like an error.
