### PR TITLE
Fix insane plant mutation calorie production

### LINKED ISSUE #35494: No NPC Needs: Plant mutation leads to obesity
NPCs with roots go and sleep outside, which is nice. However, the more time they spend rooted the fatter they get. I'm guessing this might be an issue with players, too, though I assume it's manageable with detachable vines or a simple exercise bike. 

# Steps To Reproduce

1. Spawn NPC with the plant mutation class.
2. Spend a few months doing as you do.
3. Watch them grow into a mighty oak!

# Expected behavior

This seems like an unintended effect, and one that's unmanageable as far as I can see. If heart failure at high obesity is a thing then there may be a big issue here. It seems reasonable that an NPC would only absorb what they need, to a maximum of overweight at least. Obese seems like overkill. It could be modified by personality I guess, though that should be exposed somehow if it is the case.

# Screenshots

image

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9343-geb3c2fd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    Disable NPC Needs [no_npc_food],
    No Fungal Monsters [No_Fungi]
]

# Additional context

If it's not already a feature it might be good to reduce the food consumption for base camp tasks based on certain mutations and CBMs that an NPC has.

### PR DESCRIPTION
**Pull request by Saint-of-Grey**
#### Summary
`SUMMARY: Features "Removed plant mutant calorie generation"`

#### Purpose of change
Did you know that calories and Calories are different units of measurement? I didn't.

Turns out, while my math was roughly correct, my units were not. Referencing the papers I found that were talking about the calorie intake of plants in the new england region, I made my plant redux PR blissfully unaware of the fact that kilocalories are often referred to as Calories (with an uppercase 'C'). Whoops.

Fixes #35494

#### Describe the solution
~~As it would turn out, this code is from before the stomach system, so I swapped `mod_nutrition()` with `mod_stored_calories()`, which actually references the correct unit. Also, the event that increases calories goes off twice as often, which will come out to an astounding 28 calories a day assuming you get 12 hours of uninterrupted sunlight at LEAVES3, and 14 for LEAVES2. Yipee!~~

Changed my mind, got rid of it entirely, unless someone has different magic numbers I think we can live without 30 extra calories a day.

This change does not affect vitamin or water intake at all.

#### Describe alternatives you've considered
~~You read the number right, 28 calories. I've found various sources that say a human-sized tree could get far more but they don't actually store them, so for the purposes of the game they might as well not be getting them. Given the extremely small amount a human-plant hybrid with a large amount of leaves would actually get, it might be worth taking that calorie bit entirely, which is certainly a possibility I thought of.~~

Could just leave it in for the correct amount if we really wanted.

#### Testing
Well, the game compiles, runs, and generates a new world, and standing in the sun is now a net caloric loss.

#### Additional context
The era of the nuclear powered man-plant is no more.

### CODE REVIEW

**Comment by KorGgenT** [comment]
is that miniscule of an amount even worth keeping the code for?

**Comment by wapcaplet** [comment]
This may be a little *too* extreme a nerf? 28 small-c calories is less than 1 grain of rice.

File: src/suffer.cpp [hunk 1]
```diff
@@ -737,11 +737,9 @@ void Character::suffer_in_sunlight()
         vitamin_mod( vitamin_id( "vitC" ), 1, true );
     }
 
-    if( x_in_y( sunlight_nutrition, 12000 ) ) {
-        mod_hunger( -1 );
-        // photosynthesis absorbs kcal directly
-        mod_stored_nutr( -1 );
-        stomach.ate();
+    if( x_in_y( sunlight_nutrition, 6000 ) ) {
```
Comment (anothersimulacrum) [inline src/suffer.cpp:740]:
```suggestion
    if( x_in_y( sunlight_nutrition, to_seconds<int>( 100_minutes ) ) ) {
```

**Comment by Saint-of-Grey** [comment]
> > a human-sized tree could get far more but they don't actually store them
> 
> Oh?

Most of it is lost during the glucose creation process, with a sizable junk being used to move nutrients around as well.

> is that miniscule of an amount even worth keeping the code for?

I thought the same thing, but am not sure on removing it entirely, but if that's the consensus here then I'm open to that option.

File: src/suffer.cpp (hunk 1 above)
Comment (Saint-of-Grey) [reply src/suffer.cpp:740]: I'll see if it compiles and commit it if it works.

**Comment by actual-nh** [comment]
> > > a human-sized tree could get far more but they don't actually store them
> > 
> > 
> > Oh?
> 
> Most of it is lost during the glucose creation process, with a sizable junk being used to move nutrients around as well.

Regarding the former, that there's a ready supply of CO2 and water available with no stoma-opening or significant CO2 concentration process needed may help. If the latter is for transpiration or similar, then blood flow is already doing that job.

> > is that miniscule of an amount even worth keeping the code for?
> 
> I thought the same thing, but am not sure on removing it entirely, but if that's the consensus here then I'm open to that option.

**Comment by Saint-of-Grey** [comment]
> Regarding the former, that there's a ready supply of CO2 and water available with no stoma-opening or significant CO2 concentration process needed may help. If the latter is for transpiration or similar, then blood flow is already doing that job.

I'd be willing to try and figure out what could be saved on the CO2 front and if it makes a significant difference, but a plant mutant with all the plant mutations already has transpiration (for their planty appendages that didn't mutate with added blood veins).

**Comment by actual-nh** [comment]
> > Regarding the former, that there's a ready supply of CO2 and water available with no stoma-opening or significant CO2 concentration process needed may help. If the latter is for transpiration or similar, then blood flow is already doing that job.
> 
> I'd be willing to try and figure out what could be saved on the CO2 front and if it makes a significant difference, but a plant mutant with all the plant mutations already has transpiration (for their planty appendages that didn't mutate with added blood veins).

They are still likely doing some blood flow to the joining-part of the appendages, although this will be more limited (and would also limit the CO2 input to some degree, unfortunately). (While I am a biologist, I am by no means a botanist - I teach (Human) Anatomy & Physiology.)

**Comment by souricelle** [comment]
> > > a human-sized tree could get far more but they don't actually store them
> > 
> > 
> > Oh?
> 
> Most of it is lost during the glucose creation process, with a sizable junk being used to move nutrients around as well.
> 
> > is that miniscule of an amount even worth keeping the code for?
> 
> I thought the same thing, but am not sure on removing it entirely, but if that's the consensus here then I'm open to that option.

This is not true and we went over that in chat with Kevin and everybody. 5% of the available sunlight energy is used to convert co2 to energy, the other 95% is either missed by or lost in the process of conversion. That 5% is about 75 kcal a day in the case of our survivor here. Yes it's a very small amount that isn't worth keeping the mutations for, and the mutations should go. It's photosynthesis, not cold fusion.

**Comment by Saint-of-Grey** [comment]
> This is not true and we went over that in chat with Kevin and everybody. 5% of the available sunlight energy is used to convert co2 to energy, the other 95% is either missed by or lost in the process of conversion. That 5% is about 75 kcal a day in the case of our survivor here. Yes it's a very small amount that isn't worth keeping the mutations for, and the mutations should go. It's photosynthesis, not cold fusion.

The mutations do other things, but the calorie aspect can be removed entirely if needed.

**Comment by souricelle** [comment]
Absolutely, the vitamin thing is cool and I could think of other benefits of having leaves IE shade or protection from rain effects.

**Comment by actual-nh** [comment]
Also note that cold-"blooded" plants may be hibernating during the winter - not much caloric consumption, but a lot less light OTOH.

**Comment by MarlossCDDA** [comment]
I think this should also update the mutation descriptions so people don't get confused that they're still getting hungry, though then this would be subject to the string freeze.

**Comment by actual-nh** [comment]
> I think this should also update the mutation descriptions so people don't get confused that they're still getting hungry, though then this would be subject to the string freeze.

True, although only the description for LEAVES3 really needs changing. Perhaps (at least temporarily) obsolete that one and move its boost to the vitamin supply component to LEAVES2?

**Comment by Saint-of-Grey** [comment]
> I think this should also update the mutation descriptions so people don't get confused that they're still getting hungry, though then this would be subject to the string freeze.

I could just replace "nutrition" with "vitamins" or "nutrients" to be more clear in the descriptions. The current one is technically correct, but someone who doesn't read the changelogs would be caught by surprise.

**Comment by Saint-of-Grey** [comment]
> > I think this should also update the mutation descriptions so people don't get confused that they're still getting hungry, though then this would be subject to the string freeze.
> 
> True, although only the description for LEAVES3 really needs changing. Perhaps (at least temporarily) obsolete that one and move its boost to the vitamin supply component to LEAVES2?

LEAVES3 and ROOTS3 are a massive step up from their predecessors, LEAVES2 and ROOTS2, as both of them go from 50% of RDI to 100% (assuming the player stays in ideal plant conditions). I think obsoleting LEAVES3 just because one if its features is now gone is not the right move.

**Comment by actual-nh** [comment]
> > > I think this should also update the mutation descriptions so people don't get confused that they're still getting hungry, though then this would be subject to the string freeze.
> > 
> > 
> > True, although only the description for LEAVES3 really needs changing. Perhaps (at least temporarily) obsolete that one and move its boost to the vitamin supply component to LEAVES2?
> 
> LEAVES3 and ROOTS3 are a massive step up from their predecessors, LEAVES2 and ROOTS2, as both of them go from 50% of RDI to 100% (assuming the player stays in ideal plant conditions). I think obsoleting LEAVES3 just because one if its features is now gone is not the right move.

Well, my reasoning is no longer applicable given that this is in Feature Freeze anyway - I was concerned about avoiding String Freeze if possible.

**Comment by Saint-of-Grey** [comment]
> > > > I think this should also update the mutation descriptions so people don't get confused that they're still getting hungry, though then this would be subject to the string freeze.
> > > 
> > > 
> > > True, although only the description for LEAVES3 really needs changing. Perhaps (at least temporarily) obsolete that one and move its boost to the vitamin supply component to LEAVES2?
> > 
> > 
> > LEAVES3 and ROOTS3 are a massive step up from their predecessors, LEAVES2 and ROOTS2, as both of them go from 50% of RDI to 100% (assuming the player stays in ideal plant conditions). I think obsoleting LEAVES3 just because one if its features is now gone is not the right move.
> 
> Well, my reasoning is no longer applicable given that this is in Feature Freeze anyway - I was concerned about avoiding String Freeze if possible.

I could change the category, it's a fix, just not a bugfix. Unless you count two year old contributor bugs.

**Comment by actual-nh** [comment]
> > Well, my reasoning is no longer applicable given that this is in Feature Freeze anyway - I was concerned about avoiding String Freeze if possible.
> 
> I could change the category, it's a fix, just not a bugfix. Unless you count two year old contributor bugs. Still not sure what category this falls in.

I have one up myself that is debatable whether it's a bugfix or a feature (#47653). (Personally, I'd call them both bugfixes, but I can see other arguments.)

**Comment by Saint-of-Grey** [comment]
> > I could change the category, it's a fix, just not a bugfix. Unless you count two year old contributor bugs. Still not sure what category this falls in.
> 
> I have one up myself that is debatable whether it's a bugfix or a feature (#47653). (Personally, I'd call them both bugfixes, but I can see other arguments.)

Well, the code is functioning as intended, it's just my intentions were a tad incorrect at the time.

**Comment by anothersimulacrum** [comment]
Feature freeze is a little arbitrary, but I stuck it on there because I skimmed through and anticipated string changes, but couldn't assign that label yet. It's ultimately up to the mergers whether or not this is frozen, but it doesn't need the tag.
