### PR TITLE
vehicles: align turn directions in increments of 15 degrees

### LINKED ISSUE #26549: 'offset' cars cannot be driven straight if repaired
**Describe the bug**  
Vehicles that are spawned at an offset (such as roadblock police cars, wreckages, and V-22 Ospreys)  have faceDir and turnDir that may not line up to 'straight', and so always drift if repaired

**To Reproduce**  
1. Find a vehicle that has been spawned in a partially-turned state, like a police car at a roadblock.
2. Repair it as needed to get it driveable
3. Attempt to drive straight, note that you always drift left or right

**Expected behavior**  
The character should be able to drive in a straight line in a repaired vehicle, or have some way to correct the drift

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33849-gcd5965ed4a
 - Graphics version Tiles
 - Mods loaded
    "dda",
    "no_npc_food",
    "novitamins",
    "craftgp",
    "realguns",
    "FPaF",
    "Medieval_Stuff",
    "SM",
    "mutant_npcs",
    "npc_traits",
    "Urban_Development",
    "deoxymod",
    "blazemod",
    "Tanks",
    "Nonperishable_Overhaul",
    "manualbionicinstall",
    "rmod",
    "safeautodoc",
    "StatsThroughSkills"

**Additional context**
Some savegame diving reveals that the vehicle had 
"faceDir":173,"moveDir":158,"turn_dir":173
Changing that to 
"faceDir":180,"moveDir":180,"turn_dir":180
seemed to resolve the issue. 
It seems like there should be a case to round to the closest 'real' direction (potentially on turning) to resolve this

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "vehicles: align turn directions in increments of 15 degrees"```

#### Purpose of change
Fixes #26549
Smooth a vehicle's turn direction to be in increments of 15 degrees.

#### Describe the solution
When updating a vehicle's turn direction, return an canonical turn direction that is the rounded direction in increments of 15 degrees.
Facing should eventually align with turn direction as the vehicle moves.

#### Describe alternatives you've considered
Storing the actual turn direction in increments of 1 degree but smooth it out for all uses is more complicated without making things better.

### CODE REVIEW

File: src/vehicle.h [hunk 1]
```diff
@@ -1448,7 +1448,10 @@ class vehicle
         // id of the om_vehicle struct corresponding to this vehicle
         int om_id;
         // direction, to which vehicle is turning (player control). will rotate frame on next move
+        // must be a multiple of 15 degrees
         int turn_dir = 0;
+        // actual direction in degrees
+        int actual_turn_dir = 0;
```
Comment (BevapDin) [inline src/vehicle.h]: Why do we need this separate member? Can`t you just use `turn_dir` directly? (Only add the rounding code at the end of the PR, but use `turn_dir` as input.)

Comment (mlangsdorf) [reply src/vehicle.h]: I'm not sure what I was thinking here.  Removed.
