### PR TITLE
Fix monster::impact healing monsters instead of damaging them.

### LINKED ISSUE #16870: Manhacks not accepting damage (melee, ranged, firearms, vehicle ramming)
Manhacks dont seem to be taking damage in the latest build. See below, RM228 shorty with 20x66mm buckshot loaded at close range does not appear to do any damage. Also, ramming with a vehicle or attempting melee (reach or hand-to-hand) doesn't appear to impart any damage. 

screen shot 2016-05-25 at 9 31 46 am

### PR DESCRIPTION
**Pull request by BevapDin**
Fixes #16870

To reproduced: drive into a manhack with a vehicle and make it fling away. Use the map editor to see the actual HP of the monster (debug -> editmap -> move cursor over manhack -> press 'm' -> look at the JSON dump). The manhack has more HP than it should have (normal HP is 10).

---

The return of `monster::fall_damage_mod` can be small (0.2 for TINY monsters, 0 for all flying monsters).
Combined with a relatively high armor value (`monster::get_armor_cut`), the final damage amount can be negative.
`monster::apply_damage` will happily apply this "damage", which results in an effective health boost - even above the maximum.

Note that it's still difficult to damage a manhack with a car, but it's possible if you drive fast enough (> 40mph).

### CODE REVIEW

File: src/monster.cpp [hunk 1]
```diff
@@ -1469,12 +1469,12 @@ int monster::impact( const int force, const tripoint &p )
     const float mod = fall_damage_mod();
     int total_dealt = 0;
     if( g->m.has_flag( TFLAG_SHARP, p ) ) {
-        const int cut_damage = 10 * mod - get_armor_cut( bp_torso );
+        const int cut_damage = std::max( 0.0f, 10 * mod - get_armor_cut( bp_torso ) );
```
Comment (mugling) [inline src/monster.cpp]: out of curiosity why the trailing literal `f` given that there is no other inference the compiler could take?

Comment (Coolthulhu) [inline src/monster.cpp]: Sometimes it complains if the choice is between `std::max<float>` and `std::max<double>` (or `int` or whatever).

Comment (mugling) [inline src/monster.cpp]: Thanks, its good to learn something new.
