### PR TITLE
Speed up crafting menu tab loading

### LINKED ISSUE #57975: Armor and other Recipes causing slowdowns (possibly some recursive recipes)
### Describe the bug

For the last few updates going into recipes, particularly selecting "armor" and to a lesser degree "other" takes a very long time to load.

I believe its because of some recursive recipe because I also happen to note that the hitchiker guide to the cataclysm fails to load any recipe for the latest few updates complaining about recursion, I believe it might be related. Take fx vacuum pump:

https://nornagon.github.io/cdda-guide/#/item/vac_pump

But if you select an earlier verision there is less than issue. Say the verision from 05/15 2022

https://nornagon.github.io/cdda-guide/?v=cdda-experimental-2022-05-15-1852#/item/vac_pump

What more is, my main base is massively slowed down, it takes a long time to sleep and craft. I figure its because of the massive amount of loot I have there, but even getting rid of the usual sinners of glass shards don't do anything to help, so I am wondering if there is some other sinner.

### Steps to reproduce

1. Open crafting menu
2. Try to tab into Armor 
3. Wait for a while while it loads

### Expected behavior

1. Open crafting menu
2. Try to tab into Armor 
3. Open tab quickly

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 9ab7cf1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    Alternative Map Key [alt_map_key],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Useful Helicopters Experimental [useful_helicopters],
    Gun Cotton [guncotton],
    More Survivor Stuff [more_survivor_stuff],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

[Everetts.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8790632/Everetts.zip)

There is another bug also in there where my character save gets duplicated for some reason, although they both refer to the exact same save. 
Oh, and I am currently on a older computer, so these slowdowns are probably a bit more noticeable because of it.

### PR DESCRIPTION
**Pull request by mqrause**
#### Summary
Performance "Speed up crafting menu tab loading"

#### Purpose of change

Fixes #57975

#### Describe the solution

1. Cache the quality query results in the crafting inventory. --> Drops loading time of armor tab from ~20s to ~4-5s
2. Only calculate proficiency maluses when you need them. --> Further drops loading time of armor tab from ~4-5s to <1.5s

#### Describe alternatives you've considered

An alternative would be to iterate through the whole inventory once to calculate all the fulfilled requirements and save them in an easy and quick to access way, but that would mean pretty much a rewrite of the `inventory` class. It also might be worse depending on the situation.

#### Testing

Load the save from the issue and tab through the crafting menu.

#### Additional context

That's what tabbing through the crafting menu looks like now. Armor tab is still noticable on my system, but it's just a short stutter, not hanging. The rest is just instant.
grafik
~50% of the remaining time is spent in `read_only_visitable::amount_of` when checking the required components. But I don't think I can do much there.

### CODE REVIEW

File: src/inventory.h [hunk 1]
```diff
@@ -89,6 +89,26 @@ class invlet_favorites
...
+
+    bool operator<( const quality_query &other ) const {
+        if( qual == other.qual ) {
+            if( level == other.level ) {
+                return count < other.count;
+            }
+            return level < other.level;
+        }
+        return qual < other.qual;
+    }
```
Comment (dseguin) [inline src/inventory.h:109]:
```suggestion
    bool operator<( const quality_query &other ) const {
        return std::tie( qual, level, count ) < std::tie( other.qual, other.level, other.count );
    }
```
It's up to you, but this could be shortened to use tuples to avoid nesting

Comment (mqrause) [reply src/inventory.h:109]: Hard to decide (for me as a non C++ guy). It looks really neat, but I don't think I would know what I'm looking at if I just saw that without knowing what it does. Cppreference does have an example doing exactly this, though.
