### PR TITLE
Can't manual install filthy/fauly/non sterile bionic

### LINKED ISSUE #34332: Faulty and filthy CBM can be installed manually but not by Autodoc.
# Describe the bug

When using the mod "Manual Bionic Installation", we can installed a faulty and filthy CBM manually,  but Autodoc can't.

# Steps To Reproduce

1. Create a world with mods "Manual Bionic Installation" and "Safe Autodoc"
2. Get a faulty and filthy CBM. (I don't know how to spawn one so I spawned a shocker zombie then killed and dissected it to get one...)
3. Spawn an "Autodoc Mk. XI" and an "Autodoc operation couch".
4. Try to use Autodoc to install the faulty and filthy CBM, then you will fail because "CBM is highly contaminated".
5. Try to install the CBM manually, and you'll succeed start the install process.

# Expected behavior

Here are three expected behavior.

1. Only sterile CBM can be installed manually. (more difficult but and more realistic）
2. Faulty and filthy CBM can also be installed by Autodoc. (still easy)
3. We can install faulty and filthy CBM at the expense of higher failure rates or infection. (a balance)

# Screenshots

N/A

# Versions and configuration

 - OS: Arch Linux
 - Game Version: 0.D-7934-g28028a57ba
 - Graphics version: Terminal
 - Mods loaded: [ "dda",  "no_npc_food",  "manualbionicinstall",  "safeautodoc" ]

BTW, I think the game should be able to generate the information above automatically.

# Additional context

N/A

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
``SUMMARY: Balance "Can't manual install filthy/fauly/non sterile bionic"```

#### Purpose of change
Can't manual install filthy/fauly/non sterile bionic
Fixes #34332 
#### Describe the solution
Add the proper checks in `can_use()`

### CODE REVIEW

File: src/iuse_actor.cpp [hunk 1]
```diff
@@ -4078,6 +4078,15 @@ ret_val<bool> install_bionic_actor::can_use( const player &p, const item &it, bo
...
         !p.has_trait( trait_id( "DEBUG_BIONICS" ) ) ) {
         return ret_val<bool>::make_failure( _( "You can't self-install bionics." ) );
+    } else if( !p.has_trait( trait_id( "DEBUG_BIONICS" ) ) ) {
+        if( it.has_flag( "FILTHY" ) ) {
+            return ret_val<bool>::make_failure( _( "You can't install a filthy CBM!" ) );
+        } else if( it.has_flag( "NO_STERILE" ) ) {
+            return ret_val<bool>::make_failure( _( "This CBM is not sterile, you can't install it." ) );
+        } else if( it.has_fault( fault_id( "fault_bionic_salvaged" ) ) ) {
+            return ret_val<bool>::make_failure(
+                       _( "This is CBM already deployed.  You need to reset it to factory state." ) );
```
Comment (Night-Pryanik) [inline src/iuse_actor.cpp]:
```suggestion
                       _( "This CBM is already deployed.  You need to reset it to factory state." ) );
```
