### PR TITLE
Fixed base camp bb handling of multi line entries

### LINKED ISSUE #45372: Base camp bulletin board list treats multi line entries as single line=>scrolling screwed up
The base camp bulletin board list code fails to distinguish between entries in the lists and lines in the display window. This causes the list to fail to bring up a scroll bar when the window gets full and fails to display scrolled entries at the end when entries have been folded into multiple lines (you get the conditions on the right, but not what they're for on the left).

The code in mission_companion.cpp, talk_function::display_and_choose_opts uses "sel" both as the item index and as the index of the lines for the viewport. The call to calcStartPos, for instance, is fed "sel" as if it was the line rather than the index, and the resultant "name_offset" from that function is then used as both the line and the item index.

The condition to determine whether to use a scroll bar uses the number of entries rather than the number of lines.

# Steps To Reproduce

I did get the situation when reworking the JSON layouts for the base camp and the extensions, which led to there being enough multi line entries in the list for the issue to be visible. It might be sufficient to correct the current recipes to display the construction material used (pushing them to become two lines).
Otherwise, just adding a lot of recipes with multi line descriptions that become available immediately after a base camp has been set up ought to be sufficient, as would modifying the workshop crafting recipes to have multi line descriptions, for a fully built workshop.

# Expected behavior

A scroll bar should be displayed when the number of lines to present exceeds the number of lines available in the viewport. Similarly, the currently selected entry, as well as the nearby ones further down the list (within half the size of the viewport), should be displayed.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: Please install `git` to generate VERSION [64-bit] (zip file of the source downloaded a couple of days ago, but also in 0.E2 stable)
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]
# Additional context

It might be useful to take a look at other usages of calcStartPos to see if similar confusion exists at those locations. There are a 10-20 usages that it might be useful to take a look at.

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
SUMMARY: Bugfixes "Fixed base camp bb handling of multi line entries"

#### Purpose of change
Fixes #45372

Reproduction:
Introduce enough available base camp multi line expansion recipes (in the JSON files) to require scrolling to view them all. Verify that when they take up more lines than the viewports can hold, but fewer entries, the scroll bar won't appear.
Also verify that when you have enough entries to actually get a scroll bar, the scrolling is out of sync, allowing to pass through the bottom of the viewport (so entry is highlighted) to select recipes beyond those displayed.
I don't expect there to be any difference between expansion and base recipes, but my test case used an expansion.

The issue mentions that other code sections might need to be reviewed. I've done a cursory check, and it seems the other cases where multi line entries exist at least attempt to handle it, but it probably won't hurt if someone familiar with the code double checks it.

#### Describe the solution
The bug is fixed by separating items to be displayed from the lines to be displayed, translating between the two as needed, rather than treating the entry index as the line index.

#### Describe alternatives you've considered

None. It's probably possible to make a more elegant solution, but given that it's locked in a display loop the iterations over a limited number of entries should have no performance impact.

#### Testing

My test case was my in progress work for a revised modular base camp, which contains a fair number of multi line recipe entries. However, the reproduction section indicates how to reproduce the issue, so verification should be to repeat the situation and see that the menu actually works.

#### Additional context

None

### CODE REVIEW

File: src/mission_companion.cpp [hunk 1]
```diff
@@ -476,11 +476,32 @@ bool talk_function::display_and_choose_opts(
...
+        for (size_t i = 0; i < sel; i++) { // Translate from entry index to line index
+            sel_pos += folded_names[i].size();
+        }
+
+        calcStartPos( name_offset, sel_pos, info_height, folded_names_lines );
+
+        int name_index = 0;
+        bool last_section = folded_names_lines < info_height || folded_names_lines - info_height <= size_t(name_offset);  // Are we so far down the list that we bump into the end?
+
+        if (name_offset > 0) {  // Translate back from desired line index to the corresponding entry, making sure to round up near the end to ensure the last line gets included.
```
Comment (anothersimulacrum) [inline src/mission_companion.cpp:489]: If it's not a short statement, I'd recommend keeping the comments above or below it, instead of after.
After makes it very ugly, especially when astyle gets involved.
```suggestion
        // Translate from entry index to line index
        for (size_t i = 0; i < sel; i++) {
            sel_pos += folded_names[i].size();
        }

        calcStartPos( name_offset, sel_pos, info_height, folded_names_lines );

        int name_index = 0;
        // Are we so far down the list that we bump into the end?
        bool last_section = folded_names_lines < info_height || folded_names_lines - info_height <= size_t(name_offset);

        // Translate back from desired line index to the corresponding entry, making sure to round up near the end to ensure the last line gets included.
        if (name_offset > 0) {
```

**Comment by PatrikLundell** [comment]
Thanks. Astyle's complaint was completely unhelpful, so I needed help understanding what it didn't like.

**Comment by PatrikLundell** [comment]
As far as I can tell appveryor's test failure is unrelated to the PR, as it complains about "C:\Projects\Cataclysm-DDA\tests\string_formatter_test.cpp(107)", and there are no changes to any strings in the changed code.
It looks like the travis test also fails due to reasons unrelated to the PR "ERROR : src/npc_class.cpp:157 [static void npc_class::check_consistency()] Invalid skill marksmanship", which seems totally unrelated to the PR.
And, of course, I still have no idea why Astyle sniffs at the code, lifts it legs, pees on it, and walks away offended.

File: src/mission_companion.cpp [hunk 2]
```diff
@@ -476,11 +476,35 @@ bool talk_function::display_and_choose_opts(
...
+            sel_pos += folded_names[i].size();
+        }
+
+        calcStartPos( name_offset, sel_pos, info_height, folded_names_lines );
+
+        int name_index = 0;
+        // Are we so far down the list that we bump into the end?
+        bool last_section = folded_names_lines < info_height || folded_names_lines - info_height <= size_t(name_offset);
+
+        // Translate back from desired line index to the corresponding entry, making sure to round up near the end to ensure the last line gets included.
```
Comment (mlangsdorf) [inline src/mission_companion.cpp:491]: Since astyle doesn't do it, please manually break comment lines at 100 characters.  Thank you.,

File: src/mission_companion.cpp [hunk 3]
```diff
@@ -476,11 +476,35 @@ bool talk_function::display_and_choose_opts(
...
+                    break;
+                }
+                name_index++;
+            }
+        }
 
         size_t list_line = 2;
-        for( size_t current = name_offset; list_line < info_height &&
-             current < cur_key_list.size(); current++ ) {
+        for (size_t current = name_index; list_line < info_height &&
```
Comment (mlangsdorf) [inline src/mission_companion.cpp:506]:
```suggestion
        for( size_t current = name_index; list_line < info_height &&
```
CDDA C++ style is parentheses are not spaced after `for` or `if` and there is always a space after a `(` and before a `)`.

I'm not saying that it's a pretty style, just that it is the style.

File: src/mission_companion.cpp [hunk 4]
```diff
@@ -504,12 +528,12 @@ bool talk_function::display_and_choose_opts(
             }
         }
 
-        if( cur_key_list.size() > info_height + 1 ) {
+        if (folded_names_lines > info_height + 1) {
```
Comment (mlangsdorf) [inline src/mission_companion.cpp:531]:
```suggestion
        if (folded_names_lines > info_height + 1) {
```
```suggestion
        if( folded_names_lines > info_height + 1 ) {
```

**Review by mlangsdorf — COMMENTED** [review]
Some minor astyle fixes and a request to keep your comments within 100 characters per line.

Thanks for debugging this!

File: src/mission_companion.cpp (hunk 3 above)
Comment (PatrikLundell) [reply src/mission_companion.cpp]: This one is going to be very painful as Astyle refuses to point out each and every instance. I very strongly recommend trying to get the style checker to provide feedback on what it rejects: you shouldn't have to waste time on correcting style issues.

It doesn't exactly help that the style is completely backwards for me, so I have to consciously check every single instance to adjust the style (not a complaint as such, but more of a heads up that I'm unlikely to be able to adjust to the style without a lot of slip ups, and probably never completely, as it conflicts with other styles used elsewhere).

Comment (anothersimulacrum) [reply src/mission_companion.cpp]: You can (and should) be running astyle through a tool. You can do it with `make astyle` if you're using make, and if you're not there's probably other ways mentioned in the documentation.
