### PR TITLE
Fix mx_craters hitting the building roof

### LINKED ISSUE #53241: Crater on top of rooftop creates dirt tile
### Describe the bug

Confusing looking rooftop had dirt floor which turned out to be a crater which lead to me dying from rad poisoning. 

### Steps to reproduce

1.Find rooftop with crater
2.See the dirt tiles on top of it 

### Expected behavior

for craters to destroy rooftops or not appear on them at all

### Screenshots

vlcsnap-2021-12-05-23h24m04s688

### Versions and configuration

version: c232b41

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nabebin**
#### Summary
Bugfixes "Make craters destroy roofs in a right way"

#### Purpose of change
Fixes #53241
Update `mx_crater` to make it destroy roofs properly 

#### Describe the solution
I've removed the line of the code that overrides destroyed roof tiles with `t_dirt`.
I haven't dug deep into the code so this change might have some side effects, please help me to review it.

#### Describe alternatives you've considered
N/A

#### Testing
1. Temporary update json configs to make `mx_crater` appear more often
2. Create a new world
3. Find any 1-storey building
4. Check the roof
5. Observe the properly looking crater (see the screenshot below)

#### Additional context
Before:
image
After:
image

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -3508,15 +3508,10 @@ void map::bash_ter_furn( const tripoint &p, bash_params &params )
...
-    if( smash_ter && ter( p ) == t_open_air ) {
-        if( !zlevels ) {
-            // We destroyed something, so we aren't just "plugging" air with dirt here
-            ter_set( p, t_dirt );
-        } else {
-            tripoint below( p.xy(), p.z - 1 );
-            const auto roof = get_roof( below, params.bash_floor && ter( below ).obj().movecost != 0 );
-            ter_set( p, roof );
-        }
+    if( smash_ter && ter( p ) == t_open_air && zlevels ) {
```
Comment (ZhilkinSerg) [inline src/map.cpp:3511]: zlevels are always on, so you could remove this check.

Comment (Lamberthassel) [reply src/map.cpp:3511]: It's actually not. I get a crash after removing the `zlevels` check:

```
map::get_roof(tripoint const&, bool)
    …/src/map.cpp:3218
    map::bash_ter_furn(tripoint const&, bash_params&)
    …/src/map.cpp:3513 (discriminator 10)
    map::bash(tripoint const&, int, bool, bool, bool, vehicle const*)
    …/src/map.cpp:3565
    map::destroy(tripoint const&, bool)
    …/src/map.cpp:3641 (discriminator 1)
    MapExtras::mx_crater(map&, tripoint const&)
    …/src/map_extras.cpp:1530
    MapExtras::apply_function(string_id<map_extra> const&, map&, coords::coord_point<tripoint, (coords::origin)1, (coords::scale)1> const&)
    …/src/map_extras.cpp:3017
    MapExtras::apply_function(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, map&, coords::coord_point<tripoint, (coords::origin)1, (coords::scale)1> const&)
    …/src/map_extras.cpp:3074
    map::generate(tripoint const&, time_point const&)
    …/src/mapgen.cpp:239
    map::loadn(tripoint const&, bool, bool)
    …/src/map.cpp:6939
    map::loadn(point const&, bool, bool)
    …/src/map.h:1731
    map::load(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)1> const&, bool, bool)
    …/src/map.cpp:6598
    game::load_map(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)1> const&, bool)
    …/src/game.cpp:735
    game::place_player_overmap(coords::coord_point<tripoint, (coords::origin)1, (coords::scale)2> const&)
    …/src/game.cpp:9667
```

**Comment by kevingranade** [comment]
This looks good to go, but we're having some trouble with the tests.

**Comment by Lamberthassel** [comment]
> This looks good to go, but we're having some trouble with the tests.

It seems not to be related to the MR content, right?
Is there something I could help you with to get it merged?

**Comment by ZhilkinSerg** [comment]
You can try to (optionally rebase your branch on top of current `master` branch and) force push to trigger rebuild.
