### PR TITLE
Fix issue with foods not inheriting anything during canning

### LINKED ISSUE #32564: Jarring/Canning woods soup does not inherit its ingredients vitamins and calories
# Describe the bug

It looks like when you jar or can woods soup (possibly other items) the resulting calories and vitamins are not taken from the ingredients like normal cooking.  Instead it gives a preset item which has different vitamins and calories.

Included are two screenshots.  One I made by jarring broth and jarring wood soup.  The other made by cooking broth and cooking woods soup but simply putting it in a container.  Both used the same ingredients but the result is significantly different.

I suspect this may affect all jarred/canned preserved food but that would require a large amount of testing or inspecting the code.

# Steps To Reproduce

1. Craft jarred broth then jarred woods soup.
2. Craft non jarred broth and non jarred woods soup.
3. Compare the two items.

# Expected behavior

Jarred, canned or other preserved items should inherit vitamins and calories from their ingredients just like normal cooking does.

# Screenshots

Jarred
Self Jarred

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-5805-g50eb478 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Disable NPC Needs [no_npc_food],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex]
]

### PR DESCRIPTION
**Pull request by Davi-DeGanne**
#### Summary
```SUMMARY: Bugfixes "Fix issue with foods not inheriting anything during canning"```

#### Purpose of change
Fixes #32564
Fixes other bugs as well (see below).

#### Describe the solution
The crafting finalization process was attempting to perform the following operations on the can/jar/container rather than the food contained within:
- Flag inheritance
- Poison inheritance
- Assigning components (which governs kcal/vitamin inheritance)
- Rot carryover
- Temperature assignment

So all these systems weren't working when crafting contained food. I changed it so that when the crafted item is a non-empty container, the contents undergo these operations rather than the container.

#### Testing
Craft soup twice with identical ingredients, except craft one canned, and the other not. They should have identical vitamins and calories.
I tested it myself with a few different recipes and it seems to work.

### CODE REVIEW

**Comment by DaviBones** [comment]
A note for code reviewers:

For some reason, I don't like that I used a pointer here (though granted, that's most likely because I'm still not very experienced with using them so they scare me). Was there a good way to get `content_ptr` as a reference rather than a pointer? And would that have been a better solution for any reason? Or am I overthinking this and it's fine as is?

**Comment by esotericist** [comment]
> A note for code reviewers:
> 
> For some reason, I don't like that I used a pointer here (though granted, that's most likely because I'm still not very experienced with using them so they scare me). Was there a good way to get `content_ptr` as a reference rather than a pointer? And would that have been a better solution for any reason? Or am I overthinking this and it's fine as is?

A pointer to an object is implicitly a reference to that object.

File: src/crafting.cpp [hunk 1]
```diff
@@ -1186,12 +1188,12 @@ void player::complete_craft( item &craft, const tripoint &loc )
...
                 // Temperature is not functional for non-foods
-                newit.set_item_temperature( 293.15 );
-                newit.reset_temp_check();
+                content_ptr->set_item_temperature( 293.15 );
+                content_ptr->reset_temp_check();
             }
         }
 
-        finalize_crafted_item( newit, get_faction() );
+        finalize_crafted_item( *content_ptr, get_faction() );
```
Comment (esotericist) [inline src/crafting.cpp]: This line concerns me somewhat, in that in the scenario of soup, you're finalizing the contents but not the container.

I'm not entirely sure if this is a problem, but given that ownership is set in the finalization step, I worry if it might be possible to have a can of soup with different ownership than the contents of the can.

**Comment by DaviBones** [comment]
> A pointer to an object is implicitly a reference to that object.

Hmm I worded my question poorly due to lack of knowledge of the nomenclature. I guess I meant, is there any way to end up with 
```cpp
item &content;
```
instead of
```cpp
 item *content_ptr;
```
and is it preferable for any reason?

File: src/crafting.cpp [hunk 2]
```diff
@@ -1072,6 +1084,16 @@ void player::complete_craft( item &craft, const tripoint &loc )
...
     for( item &newit : newits ) {
+
+        // Points to newit unless newit is a non-empty container, then it points to newit's contents.
+        // Necessary for things like canning soup; sometimes we want to operate on the soup, not the can.
+        item *content_ptr;
+        if( newit.is_container() && !newit.contents.empty() ) {
+            content_ptr = &newit.contents.back();
+        } else {
+            content_ptr = &newit;
+        }
```
Comment (kevingranade) [inline src/crafting.cpp]: You can replace this with:
item &food_item = ( newit.is_container() && !newit.contents.empty() ) ? newit.contents.back() : newit;

The pointer isn't *bad* per se, but that does make things tidier, also a more descriptive name is nice.

Comment (DaviBones) [reply src/crafting.cpp]: Oh cool, didn't think about trying an inline if statement to satisfy the "must initialize reference" requirement. Will change that now.
