### PR TITLE
[RDY] Rewrite drop code, resolve some issues and implement the "backpack logic"

### LINKED ISSUE #13126: Item dropping bug then items disappearing
windows experimental graphical version 0a526bf

I was in a mansion (everything otherwise going fine) and I dropped some stuff before fighting a zombie. I don't think the items I tried to 'D'rop included my lighter, a lit cigarette, and one butt. The following inventory message appeared on my screen, and the game continued after:

20:23:15.576 : src/inventory.cpp:47 Attempted to access stack 7 in an inventory (size 7)

I picked the items back up, continued on my way, but it appears my lighter vaporized after a few turns. It's not in my inventory, and it's nowhere on the ground around me. A pretty painful bug as a smoker. There should not have been any mods active, and "Harbor" was the name of the world.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/25149008-item-dropping-bug-then-items-disappearing?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #14035: Crash when removing power armor
When wearing a power armor, power armor helmet and hauling frame, when you decide to drop all three at once, the game crashes. Only crashes if they are arranged in specific order.

Steps to reproduce:
1) create a character
2) drop everything
3) wish for light power armor, light power armor helmet, power armor hauling frame
4) wear all three
5) open layering menu and rearrange them: frame first, then the armor, then the helmet
6) open multidrop menu, select all three items, drop them
7) crash:
src/activity_item_handling.cpp:80: tripoint get_item_pointers_from_activity(std::list<item *> &, std::list<int> &, std::list<item *>, std::list<int> &): Assertion `!armor.is_null' failed

### LINKED ISSUE #14346: dropping items due to over-volume inside a vehicle drops to the ground instead of the vehicle
This really doesn't make sense. If I take off my backpack while driving, the items should fall off inside the car. When I'm prompted to drop the backpack, it should also end up in the car.

### PR DESCRIPTION
**Pull request by codemime**
Rationale: make drop code simpler and more maintainable. The current implementation does rather simple thing by tangled means using wrong indirection. I'm gonna mitigate the complexity so that issues (#14035 is one of them) could be resolved without ugly workarounds. 

~~This PR is pretty much WIP (just a start actually) so it's too early to criticise the intermediate changes, but I want to share the intent. It's still WIP, but suggestions are welcome.~~

EDIT:

Fixes #13126.
Fixes #14035.
Fixes #14346.

Implements some ideas from #16650.
### Summary:
- The code became much cleaner and [I hope] easier to comprehend / maintain. No more tangled conditions, passing big numbers of arguments, "dummy" arguments, copying where references are possible, big functions with non-obvious side effects, e.t.c.
- There were three code paths of dropping (x2 via placing items directly on the map; x1 via the drop/stash activity). Now there's the single path for the player - through the activity. Even NPCs use it, but support of the activity for them is a bit hackish (same as for pulping corpses). Also, there's still a function for NPCs to drop items directly which I didn't touch for now. We probably should process activities for NPCs like we do for the player
- There was a bug caused by that ambiguity: dropping an item using `'d'rop` was consuming 250 moves, using `multidrop` - only 100. Now it's 100 in all cases. The drop cost will become calculable in future PRs
- The "backpack logic" is now here and is working well (the implementation in the current `master` is broken and doesn't work). The new algorithm consists of the following steps:

```
1. Add a weapon (if it's held) to the resulting list 
using zero drop cost (you simply let go)
2. Sort chosen inventory items by volume in ascending order
3. Add missing dependent armor/clothes (e.g. additional powerarmor 
components if powerarmor itself is dropped)
4. Sort the selected worn items by storage in descending order, but so that 
the dependent items always go first
5. While chosen inventory items "fit" into the "freed" storage, add them to 
the resulting list using zero drop cost (they're "contained")
6. Add the following clothing to the resulting list and continue to the step 5
with the next one (if obvious conditions are met)
7. If player's volume capacity is exceeded, add the excess (random items) 
to the list using zero drop cost (no more the "Some items tumble to the ground." 
message. The items were in the container and shouldn't tumble independently)
8. If there's something left after excluding what was added on the step 7,
load that into the next activity and proceed, otherwise cancel the activity.
```
- List of items reordered for dropping can be viewed in the DEBUG MODE. Here's an example (the power armor itself, the riffle and the camo tank tops were selected for dropping):

drop
- I plan to show the drop costs (and the actual list of dropped items) in the multidrop dialog (in a further PR)
- Volume recalculation was fixed (it's not linear because of the `PACKMULE` and `DISORGANIZED` traits. The previous code didn't take that into account). This will be useful for recalculating volumes without cloning `g->u` (in a further PR)
- Dropped items are handled correctly: when dropped in a vehicle (after taking them off or if the storage capacity is exceeded) they stay in the vehicle when they can
- The terrain where you drop items is described better (e.g. `"pavement"`/`"grass"`/`"dirt"` e.t.c instead of simply `"ground"` for any terrain).

Known issues: There are still player-oriented messages in the activity handlers, so when NPCs drop items, the game says that its you who drop them. I'll address that in a further PR.

### CODE REVIEW

**Comment by kevingranade** [comment]
Can you outline what you've done?  It's quite a lot of (unnecessary) work to reverse-engineer what you've changed and whether it's working as expected.

**Comment by codemime** [comment]
Sure, I'll write a detailed summary soon. There are a lot of changes. The PR is almost done (the "backpack logic" is what remains unfinished) and works fine. Some pieces of the information can be found in the commit descriptions.

**Comment by Zireael07** [comment]
Where's the summary for this?

**Comment by codemime** [comment]
I've just finished the code and 'll write the summary today, a few hours later. Sorry for the delay, was quite busy recently.

**Comment by codemime** [comment]
@kevingranade @Zireael07 See the description.

File: src/activity_item_handling.cpp [hunk 1]
```diff
@@ -7,266 +9,383 @@
...
+        const int dropcount = items.size() * ( it.count_by_charges() ? it.charges : 1 );
+        add_msg( ngettext( "You put your %1$s in the %2$s's %3$s.",
+                           "You put your %1$s in the %2$s's %3$s.", dropcount ),
+                 it.tname( dropcount ).c_str(), veh.name.c_str(), part_name.c_str() );
+    } else {
+        add_msg( _( "You put several items in the %1$s's %2$s." ), veh.name.c_str(), part_name.c_str() );
+    }
+
+    if( fallen_count > 0 ) {
+        add_msg( m_warning, _( "The trunk is full, so some items fell to the %2$s." ), ter_name.c_str() );
```
Comment (BevapDin) [inline src/activity_item_handling.cpp]: %2$s doesn't have a matching argument, probably should be %1$s.

File: src/activity_item_handling.cpp [hunk 2]
```diff
@@ -7,266 +9,383 @@
...
-                    item_quantities.push_back( qty_to_drop );
-                    items_dropped += qty_to_drop;
-                } else {
-                    item_quantities.push_back( 1 );
-                    items_dropped++;
-                }
-                if( items_dropped >= quantity ) {
-                    break;
-                }
+    if( pet.inv.empty() ) {
```
Comment (BevapDin) [inline src/activity_item_handling.cpp]: This checks seems redundant, the loop below will take care of an empty input. Or is it planned to extend the function after the loop?

File: src/activity_item_handling.cpp [hunk 3]
```diff
@@ -7,266 +9,383 @@
...
+        const bool too_big = it.volume() > max_volume;
+
+        pet.add_effect( effect_controlled, 5 );
+
+        if( too_heavy || too_big ) {
+            const std::string it_name = it.display_name();
+            const std::string ter_name = g->m.name( pet.pos() );
+
+            if( too_big ) {
+                add_msg( m_bad, _( "%s did not fit and fell to the %1$s." ), it_name.c_str(), ter_name.c_str() );
```
Comment (BevapDin) [inline src/activity_item_handling.cpp]: `it_name` will be printed twice (%s and %1$s), but `ter_name` will not be printed at all. Same with the message below.

File: src/activity_item_handling.cpp (hunk 1 above)
Comment (codemime) [inline src/activity_item_handling.cpp]: Yes to all the remarks about the arguments. Thank you, I'll double check them.

File: src/activity_item_handling.cpp (hunk 2 above)
Comment (codemime) [inline src/activity_item_handling.cpp]: The loop below checks a different condition: not a zlave's inventory but the items to put there. This condition prevents undefined behavior in `max_volume = pet.inv.front().get_storage();`. Now, when you pointed it, I see that it can be moved out of the loop too since it doesn't change. I woner if `weight_capacity()` could ever be changed after putting some items into the zed's backpack (an artefact when they will affect monsters too, or something similar).

Comment (BevapDin) [inline src/activity_item_handling.cpp]: > The loop below checks a different condition

I missed that. But looking closer at the function, if `pet.inv` is empty, the content of `items` is effectively lost. If `pet.inv` is not empty, they are either dropped on the map or stashed on the pet. Does the caller expect this behavior?

File: src/activity_item_handling.cpp [hunk 4]
```diff
@@ -7,266 +9,383 @@
...
+        }
+
+        items.pop_front();
+    }
+    // Avoid tumbling to the ground. Unload cleanly.
+    const int excessive_volume = p.volume_carried() - p.volume_capacity();
+    if( excessive_volume > 0 ) {
+        const auto excess = p.inv.remove_randomly_by_volume( excessive_volume );
+
+        res.reserve( res.size() + excess.size() );
```
Comment (BevapDin) [inline src/activity_item_handling.cpp]: Why not just `res.insert( res.begin(), excess.begin(), excess.end() );` instead of the five lines?

Btw. you're moving from a reference to const (`const auto &random_item`), `item` does not have any mutable members, so I wonder what can actually be moved here.

File: src/activity_item_handling.cpp (hunk 2 above)
Comment (codemime) [inline src/activity_item_handling.cpp]: Yes, the `pet.inv` check is a sanity check. It should never really happen, since the caller checks this prior to calling the function and never calls it for an empty handed zed. But it does make sense to show a `debugmsg` here.

File: src/activity_item_handling.cpp (hunk 4 above)
Comment (codemime) [inline src/activity_item_handling.cpp]: > Why not just res.insert( res.begin(), excess.begin(), excess.end() ); instead of the five lines?

Good point.


> so I wonder what can actually be moved here.

Probably none, but I want to avoid copying in either case (keeping in mind possible item uids).

File: src/player.cpp [hunk 5]
```diff
@@ -10379,85 +10379,132 @@ hint_rating player::rate_action_takeoff( const item &it ) const
...
+bool player::takeoff( const item &it )
+{
+    if( !get_dependent_worn_items( it ).empty() ) {
+        add_msg_player_or_npc( m_info,
+                               _( "You can't take off power armor while wearing other power armor components." ),
+                               _( "<npcname> can't take off power armor while wearing other power armor components." ) );
+        return false;
+    }
+
+    return takeoff( it, [ this ]( const item &it ) {
```
Comment (kevingranade) [inline src/player.cpp]: I agree that the dummy vectors that were only sometimes used were worth removing, but this is the only location that passes in a function for any reason other than to track the dropped items, and this is harder to read than the equivalent code without injecting a lambda.
I'd recommend dropping the passable function and restore the functionality where a passed in vector is populated with the dropped items, and handle this use case in a more straightforward way.

Comment (codemime) [inline src/player.cpp]: Apart from the vector, that would also require a passed in boolean `interactive`. It's not the third argument I want to avoid, but the hard-coded interactivity. If we inject it into the function by means of a lambda, we can get whichever interactivity (e.g. various UI) / additional-filtering we want without polluting the actual logic. I'd prefer either to keep it, or implement another less hard-coded solution.

Comment (kevingranade) [inline src/player.cpp]: There are two well-defined behaviors, a boolean switch and a data structure that captures some data, having these two explicitly supported is much better than injecting an extremely general-purpose mechanism into the method.
Think about it this way, you want as small an API as possible for any given method, injecting a general-purpose function into the method makes the API effectively very large.
Another way to look at it is to evaluate it for testability.  Ask yourself how hard it is to exercise the functionality of the function.  With the bool and the vector arguments it's easy (ignoring the fact that our unit tests don't support interactivity), fully exercising the functionality provided by an injectable method is basically impossible.

Sometimes this overhead is worthwhile, but I'm not seeing it here, the solution is much more complex than the problem.

Comment (codemime) [inline src/player.cpp]: The point is taken. I'd suggest a lambda for interaction only (for asking the question in case of overweight), but since our UI isn't separated from game objects yet, I'll drop the lambda entirely. Another drawback of passing the container is that it must have a defined type (or the function has to be templated to support any container).

**Comment by codemime** [comment]
Anything else to do before it's mergeable?

**Comment by mugling** [comment]
Let me read through this now

File: src/activity_item_handling.cpp [hunk 6]
```diff
@@ -7,266 +9,368 @@
...
 #include <list>
 #include <vector>
 #include <cassert>
+#include <algorithm>
 
 const efftype_id effect_controlled( "controlled" );
 const efftype_id effect_pet( "pet" );
 
-bool game::make_drop_activity( enum activity_type act, const tripoint &target, bool to_vehicle )
+struct act_item {
```
Comment (mugling) [inline src/activity_item_handling.cpp]: Documenting this struct with doxygen comments could help even if only one line

File: src/character.cpp [hunk 7]
```diff
@@ -793,7 +793,12 @@ int Character::weight_capacity() const
 
 int Character::volume_capacity() const
 {
-    int ret = 0;
+    return volume_capacity_reduced_by( 0 );
+}
+
+int Character::volume_capacity_reduced_by( int mod ) const
```
Comment (mugling) [inline src/character.cpp]: Why this change?

**Comment by mugling** [comment]
This is a lot of lines. Are there any smaller units it could be practically broken up into?

File: src/character.cpp (hunk 7 above)
Comment (codemime) [inline src/character.cpp]: > Volume recalculation was fixed (it's not linear because of the PACKMULE and DISORGANIZED traits. The previous code didn't take that into account). This will be useful for recalculating volumes without cloning g->u (in a further PR)

The cleanest solution of the problem would look somewhat like [this](https://github.com/CleverRaven/Cataclysm-DDA/pull/16923#issuecomment-222509334), but it's out of scope for now. I've chosen the easiest way.

**Comment by codemime** [comment]
I don't think so. It compiles after each commit, but functions properly only as a whole. Its size still seems reasonable though.

**Comment by mugling** [comment]
Don't disagree it's just you're a lot more familiar with this code and I suspect that why this hasn't received it's fair share of attention.

**Comment by codemime** [comment]
Rebased.

**Comment by Coolthulhu** [comment]
NPCs told to put on an item will take the conflicting item off twice. It may be just a duplicated message.

**Comment by Coolthulhu** [comment]
Had this happen:
* Spawn NPC
* NPC was wearing a riot helmet
* Gave him a top hat
* He swapped the headwear and dropped the helmet
* I picked up the helmet
* Told NPC to wear the helmet
* Debugmsg about top hat not being worn

Possibly caused by the morale system and not here.

**Comment by codemime** [comment]
> Possibly caused by the morale system and not here.

That happens: could reproduce. Will look into that.

**Comment by codemime** [comment]
That was a bug I introduced myself lately (d729ca7346fc54e99583b5a3b60fe60ec6267607). See 7a719e2.

**Comment by Coolthulhu** [comment]
* Place some items on the ground
* Place a wearable items on top of them
* Open advanced inventory menu
* Open worn items in one tab, items on the ground in the other
* Move all from ground to worn
* Asks whether to wield or wear (expected: wear silently)
* Tries to pick up all the other items (a feature?), but if the inventory capacity is exceeded, it tries to pick them up normally (a minor bug)

Not a huge problem, just a weirdness.

**Comment by codemime** [comment]
I'm not absolutely sure, but that probably isn't related to this PR. I didn't touch wear / pick-up code here.

**Comment by Coolthulhu** [comment]
Zlave item stashing is totally broken.

**Comment by Coolthulhu** [comment]
Also, has a tiny conflict now. Trivial, but still.

**Comment by codemime** [comment]
> Zlave item stashing is totally broken.
How exactly? I tried it just now and it worked fine.

**Comment by Coolthulhu** [comment]
I did this:
* Spawn a hulk, kill it, enzlave it and rez it
* Put a backpack on it
* Try to drop items on it
* Doesn't wait there, wanders off. Expected: gets the status, waits and receives items
* Advanced inventory drop items on it
* Takes noticeably less time than manual dropping
* All items go on the floor instead of on the zlave
* Wall it off so it can't run
* Drop items on it
* Items drop to the ground instead
* 'e'xamine it and try to drop the items that way
* Says that the items are too heavy and they drop to the floor

**Comment by codemime** [comment]
Well, dropping items on a zlave (via 'D'rop command) doesn't work in the master either. Stashing using 'D'rop makes perfect sense, but you request a new feature that just isn't there yet. Please don't say that something is "broken" when it works like it did.

**Comment by Coolthulhu** [comment]
Pretty sure it worked a while ago. I'll test it in master and check the differences.
Still, all the other options are also broken.

**Comment by codemime** [comment]
I've fixed the last one (`weight` and `volume` were swapped). The rest seem to be fine.

**Comment by Coolthulhu** [comment]
OK, looks like master doesn't have drop-stash either.

But master does have an effect preventing the zlave from moving when stashing stuff onto it.

**Comment by Coolthulhu** [comment]
Has a regression regarding zlaves, but those are a minor feature.
