### PR TITLE
Fix for Heat Induced Vomit Loop

### LINKED ISSUE #26238: Player vomit until he die when temperature is too high
before describe the bug, i guess should say sorry for my awful english.

**Describe the bug**  
Player vomit until he die when temperature is too high although he have plenty time to escape.

**To Reproduce**  
1. start a game with character have matchbook
2. set on a fire on to somewhere of building.
3. go two tiles away outside building and wait until die. 
4. check log.

**Expected behavior**  
Player should not do vomitting when temperature is too high.
behavior like this make high temperature more dangerous than it should be.

**Screenshots** 
vomit till die

**Versions and configuration(please complete the following information):**
 - OS: Windows
 - Game Version 0.C-33303-g9b3eff3
 - Graphics version Tiles
 - Mods loaded DDA, novitamin,disable npc need, filthy clothing.

**Additional context**  
things like i reported can be a bug? i`m afraid of if here is not a place like this.

### PR DESCRIPTION
**Pull request by OrenAudeles**
#### Summary
```SUMMARY: Bugfixes "Prevent heat induced vomiting until dead"```

#### Purpose of change
Fixes #26238 - Player vomit until he die when temperature is too high

#### Describe the solution
Heat induced vomiting typically increases in frequency as long as the conditions are met. Vomiting applies a 100 movement point penalty and it is likely the player's speed is sub-100, causing a loss of at least one turn. The player's situation is likely to continue to degrade to the point their head's temperature is in excess of `15000`, causing the chance to vomit to be 100%. The change made forces a maximum chance to vomit less than 100% to make it possible to escape their fatal situation.

#### Describe alternatives you've considered
Within the comments of the issue mentioned above an idea was put forward to add an effect that just blocks vomiting for some duration, triggered by vomiting. This is a good idea and worth exploring, but will take some time to design and implement. This proposed solution handles the immediate problem in a non-intrusive manner, able to be removed once a better solution is available.

### CODE REVIEW

File: src/player_hardcoded_effects.cpp [hunk 1]
```diff
@@ -370,6 +370,9 @@ static void eff_fun_hot( player &u, effect &it )
             { { bp_foot_r, 2 }, { 0, 0, 0, 0, "", 0, "" } },
         }
     };
+    // Maximum chance of 1 in MIN_EFFECTIVE_TEMPERATURE to vomit
+    const int MIN_EFFECTIVE_TEMPERATURE = 25;
```
Comment (BevapDin) [inline src/player_hardcoded_effects.cpp]: Please just use the number directly. A name for it is not needed, it's used exactly once in a very specific context (which uses other magic numbers anyway). And it makes the expression much longer and more difficult to understand.

Comment (OrenAudeles) [reply src/player_hardcoded_effects.cpp]: Understandable. Figured it being a named constant would be easier to handle if the value needed to be tuned up or down. Modification applied.
