### PR TITLE
fix smoking racks delete calories

### LINKED ISSUE #67411: Smoking fish deletes all its calories.
### Describe the bug

When I smoke fish with the basecamp charcoal smoker, it comes out with 0 calories. This only seems to happen with fish. When I smoked some human meat earlier it came out fine.

### Attach save file

[Sisyphus, 2023-08-02 6-02AM-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12252843/Sisyphus.2023-08-02.6-02AM-trimmed.tar.gz)

### Steps to reproduce

1. Observe 0 calorie smoked fish already in inventory.
2. Place raw fillets of fish in charcoal smoker, and light it.
3. Wait 5 hours for fish to smoke.
4. Retrieve 0 calorie smoked fish from smoker.

### Expected behavior

For smoked fish to have 260 calories as is listed on [the guide](https://cdda-guide.nornagon.net/item/fish_smoked). Or even have any caloric content at all.

### Screenshots

Screenshot 2023-08-03 101712

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 5eaa457 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    <color_cyan>Arcana and Magic Items</color> [Arcana],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Hope [no_hope],
    Xedra Evolved [xedra_evolved],
    <color_cyan>Arcana</color>/Magiclysm Patchmod [Arcana_Magiclysm_Patch],
    Mythical Martial Arts [MMA],
    Translate Complex Dialogue [translate_dialogue],
    No Rail Stations [No_Rail_Stations],
    Magiclysm No Class Limit [magiclysm_no_class_limit],
    Xedra Expanded No Class Limit [xedra_no_class_limit],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Tamable Wildlife [Tamable_Wildlife],
    Aftershock [aftershock],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens],
    Mind Over Matter [mindovermatter]
]

### Additional context

_No response_

### LINKED ISSUE #67627: Smoking food remove caloric value
### Describe the bug

When smoking food (in smoker made from build menu) it loses caloric value
I'm not sure if smoked meat loses it or it is lost for dehydrated meat, as i without checking smoked double time for dehydrated meat
When smoking (dehydrating) vegetables (cattail stalk) it also loses caloric value

### Attach save file

[Pound Ridge-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12328389/Pound.Ridge-trimmed.tar.gz)

### Steps to reproduce

There is some cattail stalk in fridge on the ground floor, smoker is on the roof
1. put food in the smoker
2. smoke it to dehydrated level
3. food no longer have calories

### Expected behavior

I expect that food will lose some nutrition, but not all

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: 3a3d124 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    No Hope [no_hope]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rtxyd**
#### Summary
Bugfixes "Smoking racks delete calories of fishes and fruits"

#### Purpose of change
Fixes #67411 
Fixes #67627 

#### Describe the solution
As [mqrause](https://github.com/mqrause) said
> Pretty sure that'd break when you save and load during smoking, because stuff can't have charges anymore. The issue is in `smoker_finalize`, which still assumes charges exist.

If the problem is in `finalize` still assumes charges exist, so I try another method for finalize result, 
https://github.com/CleverRaven/Cataclysm-DDA/blob/3a3d124fce4699c680175298a29c8c4c2600f0c3/src/iexamine.cpp#L5930
to ` item result( it.get_comestible()->smoking_result, start_time + 6_hours, it.count() ); `
https://github.com/CleverRaven/Cataclysm-DDA/blob/3a3d124fce4699c680175298a29c8c4c2600f0c3/src/iexamine.cpp#L5947
to ` result.recipe_charges = it.count(); `

#### Describe alternatives you've considered
N/A

#### Testing
Testing with dehydrated fruits, and dehydrated fishes, both test from loading the save during smoking.
image

image

#### Additional context
I see the bot's comment, so I make a new pull request for standards, This is the first time for me, hope for forgiveness.

### CODE REVIEW

File: src/iexamine.cpp [hunk 1]
```diff
@@ -5927,7 +5927,7 @@ static void smoker_finalize( Character &, const tripoint &examp, const time_poin
             } else {
                 it.calc_rot_while_processing( 6_hours );
 
-                item result( it.get_comestible()->smoking_result, start_time + 6_hours, it.charges );
+                item result( it.get_comestible()->smoking_result, start_time + 6_hours, it.count() );
```
Comment (mqrause) [inline src/iexamine.cpp:5930]:
```suggestion
                item result( it.get_comestible()->smoking_result, start_time + 6_hours );
                if( it.count_by_charges() ) {
                    result.charges = it.charges;
                }
```

To avoid setting charges on non-charge items. It shouldn't cause issues if it's only set to 1, but it's cleaner nonetheless.

Comment (rtxyd) [reply src/iexamine.cpp:5930]: I see it in annotation, method `count()` already includes two conditions that you are concerned . Still I should accept your suggestion in case.

Comment (rtxyd) [reply src/iexamine.cpp]: Tested S/L during smoking again, with no new problem.

Comment (mqrause) [reply src/iexamine.cpp]: > I see it in annotation, method `count()` already includes two conditions that you are concerned . Still I should accept your suggestion in case.

The difference is having 0 or 1 charges on an item that isn't allowed to have charges. The latter will be migrated and set to 0 when you load a save, but as long as it's just 1 charge nothing really happens. But it's still not supposed to happen.
