### PR TITLE
Fix unable to run message, allow mount to run when your legs are broken.

### LINKED ISSUE #46530: "Your steed is too tired to go faster" when player has broken legs
# Describe the bug

When you have broken legs and try to run, you get the message "You are too tired to run" or something similar. When you are riding a horse, you get the equivalent message, but for horses: "Your steed is too tired to go faster".

# Expected behavior

To be clear, I don't expect a paraplegic character to gallop, or worse, trot with an unmodified saddle (altho those modifications are quite simple), but the message is unfitting. Hell, getting on a horse with broken legs should probably require a stepladder.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-8659-g4c521a8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Aftershock [aftershock],
    Magiclysm [magiclysm]
]

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix unable to run message, allow mount to run when your legs are broken."

#### Purpose of change
Fixes #46530
Fix unable to run message, allow mount to run when your legs are broken.

#### Describe the solution
1. When you can't run updated the message to indicate the possibility of it being due to injury.
2. Allowed you to "sprint" when mounted with broken legs.

#### Describe alternatives you've considered
Adding a lot of complexity to movement modes to allow custom json messages or behavior for all these scenarios.  Decided this was a lot simpler and cleaner.

### CODE REVIEW

File: src/character.h [hunk 1]
```diff
@@ -35,6 +35,7 @@
 #include "item_location.h"
 #include "magic_enchantment.h"
 #include "memory_fast.h"
+#include "move_mode.h"
```
Comment (kevingranade) [inline src/character.h:38]: Please forward-declare steed_type instead, this header is huge and included in a lot of places, and it significantly increases compile time.

File: src/character.h [hunk 2]
```diff
@@ -96,6 +96,7 @@ template <typename E> struct enum_traits;
 
 enum npc_attitude : int;
 enum action_id : int;
+enum steed_type;
```
Comment (anothersimulacrum) [inline src/character.h:99]:
```suggestion
enum class steed_type : int;
```
