### PR TITLE
fix item duping on wear

### LINKED ISSUE #42525: Loophole when "wearing" and canceling the "stop wielding" prompt
# Describe the bug

When I `W`ear any item of clothing, and I don't have enough space in my inventory to pick up the thing before wearing it, I get a prompt to stop wielding my current weapon, which seems good and proper since I need my hands free to put it on.

However, if I press ESC to cancel this prompt, I end up wearing the item anyway, and the weapon remains wielded (with fewer total moves than if I had dropped my weapon).

# Steps To Reproduce

1. Drop everything (get nekkid)
2. Wield something (anything)
3. Try to wear something (anything) - get "Stop wielding xxx?" prompt
4. Press ESC
5. Check inventory - wielded item remains wielded, and other item is now worn

This is the simplest use case, but it is the same regardless of what you're already wearing or carrying - if you don't have enough storage to hold the item you're trying to `W`ear, the "Stop wielding" prompt will appear, and can be cheated with ESC to wear the item anyway, with no additional movement penalty.

# Expected behavior

ESC should cancel the action of attempting to wear the item; the wielded item should remain wielded, and the desired item should not be worn afterwards.

# Screenshots

Wearing nothing, wielding a pocket knife:

image

Pressing `W` to wear a nearby item:

image

Prompt for what to do with the pocket knife - there is only one option, and I do not like it:

image

When I press ESC, the backpack gets worn anyway, while still wielding the pocket knife:

image

image

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-4551-geb830227c0 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### LINKED ISSUE #47326: Duplicating anything with armor
Duplicating armor by using the sort armor tab. Actually I can duplicate any items as well because any item in the bag gets duplicated as well. 

1. Wield an item.
2. Using the sort armor tab, equip any armor.
3. Get a drop wielded item message, and press Esc.
4. Get a error message, press space.

 I expected to equip the item without having to unwield wielded item, I mean like why do you even have to unwield your wielded item when you can just equip the armor without hindrances 

 - OS: Windows 7
 - Game Version: [0.E-9355-g203e8c9-dirty [64-bit]]
 - Graphics version: [Tiles]
 - Ingame language: [System Language]
 - Mods loaded: [    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    My Sweet Cataclysm [my_sweet_cataclysm],
    My Sweet Cataclysm - UndeadPeople Tileset [My_Sweet_CataclysmUDP],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    C.R.I.T Expansion Mod [crt_expansion],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Useful Helicopters [useful_helicopters],
    Stats Through Skills [StatsThroughSkills],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Manual Bionic Installation [manualbionicinstall],
    Portable Autodoc [portable_autodoc],
    Fuji's Military Profession Pack [fuji_mpp],
    Clean CBMs [clean_cbm],
    Alternative Map Key [alt_map_key]]

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
Bugfixes "Fixes duping items when trying to wear an item while naked and wielding another item."

#### Purpose of change
Fixes #42525
Fixes #47326

#### Describe the solution
so in item_location::impl::item_on_map::obtain(), Character::i_add() is used. and the player has a prompt dispose_item() that they could cancel. if they cancel it, the item_location returned was what the item_location _would_ be if not cancelled, but now it is incorrect since it doesn't exist on the Character, it's on the ground. Since that is the case, if returned from that function after disposing, the debugmsg would appear "Tried removing item from object which did not contain it", not removing the item, therefore duplicating it.
The solution, then, is to return a brand new null item_location when the character doesn't actually have the item, showing that obtain() failed.

#### Testing

[repro.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5941640/repro.zip)
Press `+`, `e`, `return`, `esc` to trigger the bug (fixed with the PR)

#### Additional context
player::sort_armor() really needs to be split up into smaller parts. it's 500 lines long and has a ton of indentation.

### CODE REVIEW

File: src/item_location.cpp [hunk 1]
```diff
@@ -222,12 +222,19 @@ class item_location::impl::item_on_map : public item_location::impl
 
             on_contents_changed();
             item obj = target()->split( qty );
+            auto get_local_location = []( Character & ch, item * it ) {
```
Comment (anothersimulacrum) [inline src/item_location.cpp:225]:
```suggestion
            const auto get_local_location = []( Character & ch, item * it ) {
```

**Review by anothersimulacrum — APPROVED** [review]
