### PR TITLE
Main menu overhaul (Part 1.5): mouse control fixes & improvements

### LINKED ISSUE #58086: Issues with new main menu
### Describe the bug

- [x] Scrolling down on credits/MOTD to the very end AND further down (for example, press down 3 times after you've scrolled to the very end) make the game require pressing up 3 times before text begins to scroll up;
- [ ] There is no sound of highlighting the menus by hovering the mouse, while manual old-style switching (pressing left or right) produces sound;
- [ ] Popup prompts like when pressing "Delete world" (`Delete world and all world within?`) or `Really quit?` are not mouse-clickable.
- [ ] Tertiary menu options (`Manage world: Foo`) can be pressed by left mouse button, but you can't return to previous menu by pressing right mouse button, like in secondary menus.

### Steps to reproduce

See above.

### Expected behavior

See above.

### Screenshots

_No response_

### Versions and configuration

Windows 10 x64, 0.F-8778.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dseguin**
#### Summary
None

#### Purpose of change
- Follow up to #57764

Fixes #58086 (except the scrolling issue which is addressed by #58140).

#### Describe the solution

1. Trigger the "menu_move" sounds when mousing over main menu options.
2. Modify external UI elements to be mouse-aware (for prompts and popups).
3. Add a mouse-accessible method of exiting tertiary menus.
4. In general, right-click can act as `ESC` if there are no visible buttons for exiting a window.

Changes to `uilist`/`query_popup`:
- Highlight list items when mousing over

Changes to Settings/World/Help menus:
- Full mouse control

#### Example - creating a world using only the mouse:

https://user-images.githubusercontent.com/12537966/172040871-49c3f232-daf3-4904-99fa-6c864e20efeb.mp4

#### Example - navigating settings and help menus in-game:

https://user-images.githubusercontent.com/12537966/172075415-79398167-0411-42dc-8330-bab028b6a6ea.mp4

#### Additional context

TODO:
- Mouse-ify all remaining sub-menu items:
  - [x] New Character
  - [x] Load Character
  - [x] World
  - [x] Settings
  - [x] Help

### CODE REVIEW

File: src/popup.cpp [hunk 1]
```diff
@@ -289,8 +296,11 @@ query_popup::result query_popup::query_once()
     }
     if( anykey ) {
         ctxt.register_action( "ANY_INPUT" );
-        // Mouse movement, button, and wheel
-        ctxt.register_action( "COORDINATE" );
```
[the remark this answers is not in the document]
Comment (Qrox) [reply src/popup.cpp:293]: And I'm not quite sure about allowing mouse input by default because some old code might not expect it, especially when the popup is not set up to ask the user to pick an option.

[the remark this answers is not in the document]
Comment (dseguin) [reply src/popup.cpp:293]: Cheers, it didn't occur to me that the mouse input was for keybindings. I added that back in and it's working as before:



I also switched mouse control to disabled by default for `query_popup`. `uilist` already handles "SELECT" so I haven't changed it.

**Comment by Night-Pryanik** [comment]
Is it possible to move mods up and down in world creation menu using only mouse?

**Comment by dseguin** [comment]
> Is it possible to move mods up and down in world creation menu using only mouse?

No, sorry. As far as I know click-and-drag is not possible.

**Comment by Night-Pryanik** [comment]
Maybe we should add separate up and down buttons which will move highlighted mod up and down. Just a thought.

**Comment by leemuar** [comment]
> > Is it possible to move mods up and down in world creation menu using only mouse?
> 
> No, sorry. As far as I know click-and-drag is not possible.

As far as I can understand the code drag-n-drop is possible, but will require more code to write around

**Comment by leemuar** [comment]
> > Is it possible to move mods up and down in world creation menu using only mouse?
> 
> No, sorry. As far as I know click-and-drag is not possible.

Why not? Because current implementation does not distinguish between mouse button clicked and released?
I have some ideas on how to implement drag-n-drops, but I haven't finished my research on this case

**Comment by leemuar** [comment]
Please note I did a help window scrolling here: https://github.com/CleverRaven/Cataclysm-DDA/pull/58145

**Comment by leemuar** [comment]
I did some research, SELECT mouse action currently triggers when user release left mouse button. To make drag possible we only need to add tracking for the event of pressing mouse button. I'll make another PR for dragging support when Im done with my research

File: src/options.cpp [hunk 2]
```diff
@@ -2945,48 +2968,102 @@ std::string options_manager::show( bool ingame, const bool world_options_only,
...
         }
 
+        if( action == "MOUSE_MOVE" || action == "SELECT" ) {
+            bool found_opt = false;
+            sel_worldgen_tab = 1;
+            if( world_options_only ) {
+                // worldgen tabs
+                cata::optional<point> coord = ctxt.get_coordinates_text( w_options_border );
+                for( const auto &ent : worldgen_tab_map ) {
+                    if( coord.has_value() && ent.second.contains( coord.value() ) ) {
```
Comment (BevapDin) [inline src/options.cpp:2993]: You may want to put this logic for "find element by point in a std::map<..., inclusive_rectangle<point>>" into a separate function. It's repeated not only here, but also in `help::display_help` above.

File: src/output.cpp [hunk 3]
```diff
@@ -731,11 +731,22 @@ bool query_yn( const std::string &text )
            .option( "YES", allow_key )
            .option( "NO", allow_key )
            .cursor( 1 )
+           .allow_mouse_ctrl( mousectrl )
            .default_color( c_light_red )
            .query()
            .action == "YES";
 }
 
+bool query_yn_mouse( const std::string &text )
```
Comment (BevapDin) [inline src/output.cpp:740]: Is there any reason to have this as special function instead of being the default?

In other words: why not enable mouse control all the time, and only disable it when required?

Comment (Qrox) [reply src/output.cpp:740]: See https://github.com/CleverRaven/Cataclysm-DDA/pull/58142#discussion_r889506071.

I think `query_yn` can have mouse control on by default because the mouse handling code is completely internal to the function. `query_popup` cannot though unless the mouse handling code is changed to be internal to `query_once`. Currently the code changes behavior on mouse clicks and some old code might not expect that.

File: src/worldfactory.cpp [hunk 4]
```diff
@@ -719,7 +771,9 @@ void worldfactory::draw_mod_list( const catacurses::window &w, int &start, size_
             }
         }
 
-        calcStartPos( start, iActive, iMaxRows, iModNum );
+        if( recalc_start ) {
```
Comment (Qrox) [inline src/worldfactory.cpp:774]: Need to recalculate starting position on screen resizing.

File: src/worldfactory.cpp [hunk 5]
```diff
@@ -1262,24 +1436,26 @@ int worldfactory::show_worldgen_tab_modselection( const catacurses::window &win,
...
         } else if( action == "SAVE_DEFAULT_MODS" ) {
             if( mman->set_default_mods( active_mod_order ) ) {
-                popup( _( "Saved list of active mods as default" ) );
+                popup( _( "Saved list of active mods as default" ), PF_MOUSECTRL );
                 draw_modselection_borders( win, ctxt );
             }
         } else if( action == "VIEW_MOD_DESCRIPTION" ) {
             if( const MOD_INFORMATION *selmod = get_selected_mod() ) {
-                popup( "%s", mman_ui->get_information( selmod ) );
+                popup( mman_ui->get_information( selmod ), PF_MOUSECTRL );
```
Comment (Qrox) [inline src/worldfactory.cpp:1452]: Using "%s" here is preferred because using a string directly as the first parameter to `popup` is ambiguous because `popup( char * )` and `popup( std::string )` behave differently (the first treats the string as a format string whereas the second shows the string as-is).

File: src/options.cpp [hunk 6]
```diff
@@ -2808,7 +2821,9 @@ std::string options_manager::show( bool ingame, const bool world_options_only,
             }
         }
 
-        calcStartPos( iStartPos, iCurrentLine, iContentHeight, page_items.size() );
+        if( recalc_startpos ) {
+            calcStartPos( iStartPos, iCurrentLine, iContentHeight, page_items.size() );
```
[the remark this answers is not in the document]
Comment (dseguin) [reply src/options.cpp:2825]: The flag is just to prevent the list from scrolling when mousing over options (when there are lots of options, mousing over anywhere but the center would cause a scroll, which puts the selection on a different option). I will add this to the resize callback, though.

**Comment by dseguin** [comment]
Cheers for the feedback. New changes:
- Redo mouse control for `query_popup`, only register "SELECT" and "MOUSE_MOVE" when options exist
- Do not check for "MOUSE_MOVE" in `uilist` when using an external loop
- Undo changes to `query_yn` and `popup` (ie: PF_MOUSECTRL)
- Recalc scroll position when resizing
- Remove prefixes from `QUIT` keybindings
- Use `run_for_point_in` to process button rectangle logic

**Comment by leemuar** [comment]
run_for_point_in()  is a nice thing, Ill definitely reuse it

**Comment by leemuar** [comment]
@dseguin, run_for_point_in() iterates over all items in collection, even if it already found a rectangle.
Do you think it is OK? In my cases all rectangles in the collection do not overlap, so finding first is enough to end iteration early.

I can easily copy run_for_point_in() and modify it to be like run_for_first_point_in(), I just want to know you opinion on that. Maybe Im missing some cases where iterating over all rectangles and counting all hits is actually required

**Comment by dseguin** [comment]
No problem. I've added a default parameter to return early after the first match. These are intended to be general purpose functions so I do want the option to run for any element, but for UI buttons you can just leave `first_only` as 'true'.

**Comment by leemuar** [comment]
Finally merged!
It's time to reuse those helper functions!
image

**Comment by leemuar** [comment]
> Is it possible to move mods up and down in world creation menu using only mouse?

I figured out how to implement it,  see https://github.com/CleverRaven/Cataclysm-DDA/issues/58214#issuecomment-1157266968
I made an issue to gather suggestions on where to add drag-n-drop: https://github.com/CleverRaven/Cataclysm-DDA/issues/58454
