### PR TITLE
Companion_choose() guard fix

### LINKED ISSUE #28864: Guarding npcs sent to missions can be used in other missions
So i think its the bug that got fixed with nonguard npcs, if npcs on guard are sent to a mission, they can then be sent to another mission, wasting progress on the mission there were on

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Companion_choose() camp mission guard fix"```

#### Purpose of change
Fixes #28864 

#### Describe the solution
Change to the logic so that guarding NPCs already out on missions can't be used in new missions.

#### Describe alternatives you've considered
N/A
#### Additional context
N/A

### CODE REVIEW

**Comment by davidpwbrown** [comment]
jenkins rebuild

File: src/mission_companion.cpp [hunk 1]
```diff
@@ -1793,18 +1793,13 @@ std::vector<comp_rank> talk_function::companion_rank( const std::vector<npc_ptr>
...
+        npc_ptr guy = overmap_buffer.find_npc( elem );
         npc_companion_mission c_mission = guy->get_companion_mission();
-        if( g->u.sees( guy->pos() ) ) {
-            if( guy->is_friend() && c_mission.role_id.empty() ) {
-                available.push_back( guy );
-            } else if( guy->mission == NPC_MISSION_GUARD_ALLY &&
-                       guy->companion_mission_role_id != "FACTION_CAMP" ) {
-                available.push_back( guy );
-            }
+        if( ( g->u.sees( guy->pos() ) ) && ( !guy->has_companion_mission() ) ) {
```
Comment (mlangsdorf) [inline src/mission_companion.cpp]:
```suggestion
        if( g->u.sees( guy->pos() ) && !guy->has_companion_mission() ) {
```
I'm all for extra parenthesis to improve clarity, but these are straightforward booleans.
