### PR TITLE
Fix rot sort in advanced inventory

### LINKED ISSUE #29720: SIGABRT in spoilage_sort_order next to dead acid zombie
**Describe the bug**  

Unexpected crash while raiding a hospital. I moved onto a door and got my first crash ever. Next to me was a freshly killed acid zombie, some acid (from said zombies), and various butchered zombies and their refuse/fats/meats and tainted items.

Backtrace shows it happening in `spoilage_sort_order`, as part of the advanced inventory functionality.

**To Reproduce**  

1. Open the attached save
1. Open the advanced inventory (`/`)

**Expected behavior**  

No crash. :)

**Versions and configuration(please complete the following information):**
 - OS: Ubuntu 16.04, x64
 - Game Version: 0.D-1937-ge21f209c8e (e21f209c8e2ad3ec07653f7eb2f64a3048338bda with updated DeadPeopleTileset, and #29700 applied)
 - Graphics version: Tiles
 - Mods loaded: None

**Additional context**  

<details>
  <summary>Stack Trace - Click to Expand</summary>

```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: /home/pjf/.cataclysm-dda/config/crash.log
VERSION: 0.D-1937-ge21f209c8e
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

	./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x23) [0x957af8]
	./cataclysm-tiles() [0x944e83]
	./cataclysm-tiles() [0x944af8]
	/lib/x86_64-linux-gnu/libc.so.6(+0x354b0) [0x7efd75b6e4b0]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0x38) [0x7efd75b6e428]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x16a) [0x7efd75b7002a]
	/lib/x86_64-linux-gnu/libc.so.6(+0x2dbd7) [0x7efd75b66bd7]
	/lib/x86_64-linux-gnu/libc.so.6(+0x2dc82) [0x7efd75b66c82]
	./cataclysm-tiles(_ZN4item19spoilage_sort_orderEv+0x147) [0xaf6463]
	./cataclysm-tiles(_ZN19advanced_inv_sorterclERK21advanced_inv_listitemS2_+0x115) [0x850205]
	./cataclysm-tiles(_ZSt16__insertion_sortIN9__gnu_cxx17__normal_iteratorIP21advanced_inv_listitemSt6vectorIS2_SaIS2_EEEENS0_5__ops15_Iter_comp_iterI19advanced_inv_sorterEEEvT_SC_T0_+0x96) [0x84f8aa]
	./cataclysm-tiles(_ZSt22__chunk_insertion_sortIN9__gnu_cxx17__normal_iteratorIP21advanced_inv_listitemSt6vectorIS2_SaIS2_EEEElNS0_5__ops15_Iter_comp_iterI19advanced_inv_sorterEEEvT_SC_T0_T1_+0x50) [0x850fb9]
	./cataclysm-tiles(_ZSt24__merge_sort_with_bufferIN9__gnu_cxx17__normal_iteratorIP21advanced_inv_listitemSt6vectorIS2_SaIS2_EEEES3_NS0_5__ops15_Iter_comp_iterI19advanced_inv_sorterEEEvT_SC_T0_T1_+0x28) [0x850bbf]
	./cataclysm-tiles(_ZSt22__stable_sort_adaptiveIN9__gnu_cxx17__normal_iteratorIP21advanced_inv_listitemSt6vectorIS2_SaIS2_EEEES3_lNS0_5__ops15_Iter_comp_iterI19advanced_inv_sorterEEEvT_SC_T0_T1_T2_+0xa8) [0x84f351]
	./cataclysm-tiles(_ZN18advanced_inventory11recalc_paneENS_4sideE+0x321) [0x839d3b]
	./cataclysm-tiles(_ZN18advanced_inventory11redraw_paneENS_4sideE+0x4c) [0x839fe4]
	./cataclysm-tiles(_ZN18advanced_inventory7displayEv+0x948) [0x83ce4a]
	./cataclysm-tiles(_Z12advanced_invv+0x1d) [0x840c54]
	./cataclysm-tiles(_ZN4game13handle_actionEv+0x372a) [0xa643e6]
	./cataclysm-tiles(_ZN4game7do_turnEv+0x4fa) [0x9f0a7c]

	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	??:?
	log_crash(char const*, char const*)
	crash.cpp:?
	signal_handler(int)
	crash.cpp:?
	killpg
	??:?
	__GI_raise
	/build/glibc-Cl5G7W/glibc-2.23/signal/../sysdeps/unix/sysv/linux/raise.c:54
	__GI_abort
	/build/glibc-Cl5G7W/glibc-2.23/stdlib/abort.c:91
	__assert_fail_base
	/build/glibc-Cl5G7W/glibc-2.23/assert/assert.c:92
	__assert_fail
	??:?
	item::spoilage_sort_order()
	??:?
	advanced_inv_sorter::operator()(advanced_inv_listitem const&, advanced_inv_listitem const&)
	??:?
	void std::__insertion_sort<__gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, __gnu_cxx::__ops::_Iter_comp_iter<advanced_inv_sorter> >(__gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, __gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, __gnu_cxx::__ops::_Iter_comp_iter<advanced_inv_sorter>)
	??:?
	void std::__chunk_insertion_sort<__gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<advanced_inv_sorter> >(__gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, __gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<advanced_inv_sorter>)
	??:?
	void std::__merge_sort_with_buffer<__gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, advanced_inv_listitem*, __gnu_cxx::__ops::_Iter_comp_iter<advanced_inv_sorter> >(__gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, __gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, advanced_inv_listitem*, __gnu_cxx::__ops::_Iter_comp_iter<advanced_inv_sorter>)
	??:?
	void std::__stable_sort_adaptive<__gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, advanced_inv_listitem*, long, __gnu_cxx::__ops::_Iter_comp_iter<advanced_inv_sorter> >(__gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, __gnu_cxx::__normal_iterator<advanced_inv_listitem*, std::vector<advanced_inv_listitem, std::allocator<advanced_inv_listitem> > >, advanced_inv_listitem*, long, __gnu_cxx::__ops::_Iter_comp_iter<advanced_inv_sorter>)
	??:?
	advanced_inventory::recalc_pane(advanced_inventory::side)
	??:?
	advanced_inventory::redraw_pane(advanced_inventory::side)
	??:?
	advanced_inventory::display()
	??:?
	advanced_inv()
	??:?
	game::handle_action()
	??:?
	game::do_turn()
	??:?
```

</details>

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary

```SUMMARY: Bugfixes "Fix crash in advanced inventory when sorting by rot with corpses"```

#### Purpose of change
Fixes #29720 

When advanced inventory is set to sort by rot the game tries to look at the shelf life of the rotting item.
Previously all rotting items were comestible so the the game checks for the shelf life of the comestible. But since corpses are not comestible this caused the game to crash.

#### Describe the solution
Add if statement to handle corpses differently.

#### Describe alternatives you've considered
Make a new function for getting the shelf life of an item and replace every instance of `get_comestible()->spoils` with that.

### CODE REVIEW

**Comment by Hirmuolio** [comment]
Build finished. Fix works.

File: src/item.cpp [hunk 1]
```diff
@@ -3786,6 +3786,9 @@ int item::spoilage_sort_order()
     }
 
     if( subject->goes_bad() ) {
+        if( subject -> is_corpse() ) {
+            return to_turns<int>( 14400_turns - subject->rot );
```
Comment (ifreund) [inline src/item.cpp]: I'd consider putting this `14400_turns` value in `game_constants.h` as `CORPSE_ROT_TIME` or something similar.

**Comment by pjf** [comment]
Running this locally and confirming it's working for me. Thank you!
