### PR TITLE
[RDY] Fix for crash while iterating over multiple vehicle tanks' contents

### LINKED ISSUE #19789: Segfault while batching clean water in vehicle
See the attached save, the build is from sometime around 2016-12-08. I'll try it in a newer build tomorrow.
```
/usr/include/c++/6/debug/safe_iterator.h:298:
Error: attempt to increment a singular iterator.

Objects involved in the operation:
    iterator "this" @ 0x0x7fff4eaee130 {
      type = __gnu_debug::_Safe_iterator<std::__cxx1998::_List_const_iterator<item>, std::__debug::list<item, std::allocator<item> > > (constant iterator);
      state = singular;
      references sequence with type 'std::__debug::list<item, std::allocator<item> >' @ 0x0x55e1de0f4cc8
    }
Aborted
```
[Pyatts.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/658572/Pyatts.zip)

### PR DESCRIPTION
**Pull request by keyspace**
~~This is the result of a gnarly `bisect` session. Solution covers target issue only, not the underlying cause.~~

Fixes #19789 - segfault when batching from multiple tanks' contents.

AFAIU the segfault happened from trying to iterate the contents that have already been removed. ~~Could be wrong here.~~

As I understand, there can only be one member of `pt.contents()` here (`pt` is a fluid tank part of a vehicle), so it should be OK to just skip "the rest". ~~Could be very wrong here.~~ EDIT: This is ensured by `vehicle_part::can_reload(...)` when filling tank.

Won't dump debug notes - crafting from vehicles with tanks and faucets seems to have been broken for a long time.

-----

EDITs: clarification, style

### CODE REVIEW

**Comment by mutability** [comment]
Right, the segfault here is because vehicle_part::drain may mutate pt.contents so it's not safe to continue iterating over it.

**Comment by keyspace** [comment]
Removed hotfix loop exit, and the loop for that matter.

**Comment by sethsimon** [comment]
Looks good, and I couldn't break it while testing. I think the assumption is okay- `vehicle_part::can_reload`, `vehicle_part::fill_with` -> `item::fill_with`, and `vehicle_part::ammo_current` all seem to indicate that tanks have at most 1 item in it.

**Comment by keyspace** [comment]
Thanks for reviewing! IMO ready.

Note/TODO: f50eda88d412f383e7fd13da3324d5f408d561db and 02177fb80721b345be8969277e3a4137d68fef43 fixed previous wonkiness and refactored two similar (but not identical) sections, one of which is polished up here.

The other one - in `inventory::form_from_map()` - also iterates over tanks' contents. It calls `inventory::add_item()`, which doesn't seem to cause a crash (doesn't mutate the iterated list?). So not touched.

File: src/map.cpp [hunk 1]
```diff
@@ -5083,15 +5083,11 @@ std::list<item> map::use_charges(const tripoint &origin, const int range,
...
-                if( pt.is_tank() ) {
-                    for( const auto &obj : pt.contents() ) {
-                        if( obj.typeId() == type ) {
-                            ret.push_back( pt.drain( quantity ) );
-                            quantity -= ret.back().charges;
-                            if( quantity == 0 ) {
-                                return ret;
-                            }
-                        }
+                if( pt.is_tank() && pt.ammo_current() == type ) {
```
Comment (codemime) [inline src/map.cpp]: `pt.is_tank()` is excessive. `drain()` won't let you drain non-tanks.

File: src/map.cpp [hunk 2]
```diff
@@ -5083,15 +5083,11 @@ std::list<item> map::use_charges(const tripoint &origin, const int range,
...
+                    ret.push_back( pt.drain( quantity ) );
```
Comment (codemime) [inline src/map.cpp]: I'd check the result via `is_null()` before placing it into `ret`.

**Comment by codemime** [comment]
Appears to be working, but I couldn't reproduce the initial issue.

File: src/map.cpp (hunk 1 above)
Comment (keyspace) [inline src/map.cpp]: True. `ammo_current()` does, too.

The loop iterates over all vehicle parts. IMO the check is good for readability.

Also, if `ammo_current()` returned a matching type for something that is not a tank (e.g. a turret, engine, funnel, hydroponic unit, - anything in the future that could have a matching `ammo` due to implementation details), this could result in breakage. The intent is to craft from tanks only.

Should I add a comment to this effect?

Comment (codemime) [inline src/map.cpp]: > Also, if ammo_current() returned a matching type for something that is not a tank, this could result in breakage. The intent is to craft from tanks only.

`drain()` should exclude everything that you can't drain from (and it does). `is_tank()` is IMO too "specific" here. Imagine that we introduced multiple types of water sources for vehicles (say, giant funnels, windtraps, e.t.c.). You would need to add the checks everywhere to be able to drain them: `if( is_tank() || is_funnel() || is_windtrap() || ... ) { drain() }`.

The point is: the only thing you need to know about the part here is whether you can drain it for your purposes.

>Should I add a comment to this effect?

I still think that the first check should be dropped.

File: src/map.cpp (hunk 2 above)
Comment (keyspace) [inline src/map.cpp]: Huh. This was originally checked by the first if-clause in the removed loop. :/

Ironically, this wouldn't happen here now, since the previous check of `ammo_type()` masks the `vehicle_part::drain()` conditional that would return a null item. But you are correct, and that conditional could change.

There aren't (m)any examples of `vehicle_part::drain()` use (it's been added recently, in b899bf05), and I'm very unfamiliar with the code base, so will change [RDY] back to [CR].

File: src/map.cpp (hunk 1 above)
Comment (keyspace) [inline src/map.cpp]: That is very much not for me to decide.

Currently, this section allows draining tanks (only) from vehicles that have a faucet, even if not inside the vehicle.

Using vehicle parts that are "pseudo-tools" is covered a little earlier in `map::use_charges(...)`, around line 5057. (It has a nice lambda to avoid unnecessarily verbose checks.) These "pseudo-tools" are available only when inside the vehicle.

**Comment by keyspace** [comment]
Attaching a savegame used for testing.

The RV has multiple tanks and faucets. (The latter were needed during bisection for a different bug.) There is also a hotplate and pot outside the vehicle. The only sources of water are in the RV, 2 units each in two tanks.

To test, craft 2 and 3 waters via batch craft menu. Before this fix, crafting 3 should result in a crash.

This does not allow testing with other water locations (river, inventory, containers in the vehicle's cargo or the ground, vehicle "pseudo-tools", etc.). Only shows the effects of:

* multiple faucets
* multiple tanks, including an empty one
* inside/outside the vehicle

A full test case would be complex - outside the scope.

[bisect-19789.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/671992/bisect-19789.zip)

**Comment by keyspace** [comment]
I think the `is_null()` check is OK as is, changing back to [RDY] again.
