### PR TITLE
Fix list_(item/monster) distance display.

### LINKED ISSUE #12485: Quirky distance sorting in list_monsters & list_items
screenshot from 2015-05-28 00 12 00

While fiddling with item lists, I've noticed that items/monsters don't always sort properly (based on distance).

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/18215900-quirky-distance-sorting-in-list_monsters-list_items?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by OzoneH3**
Fixes #12485

Adds: Sort items in category sort by distance as well.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -9726,7 +9726,7 @@ int game::list_monsters(const int iLastState)
                         int numw = iMonsterNum > 9 ? 2 : 1;
                         mvwprintz(w_monsters, y, width - (6 + numw),
                                   (selected ? c_ltgreen : c_ltgray), "%*d %s",
-                                  numw, trig_dist(0, 0, critter->posx() - u.posx(),
+                                  numw, square_dist(0, 0, critter->posx() - u.posx(),
```
Comment (BevapDin) [inline src/game.cpp]: You probably want `rl_dist`, which behaves like `square_dist` or `trig_dist`, depending on the "Circular distances" option.

**Comment by OzoneH3** [comment]
I want to display the amount of squares an item is away from the player, the same number as `line_to()` draws. With `rl_dist()` the `closest_tripoints_first()` in `find_nearby_items()` would have to be rewritten to respect the circular distance as well.

**Comment by kevingranade** [comment]
They probably should be rewritten to respect circular distances, yes.
