### PR TITLE
Broken limbs

### LINKED ISSUE #31323: Crafting with broken arm does not produce crafted item
# Describe the bug

Attempting to craft some items with broken arm does not produce item.

# Steps To Reproduce

1. Break character's arm
2. ensure character not wielding any item, and no table is nearby
3. attempt to craft tiny motor 
4. tiny motor not wielded, or placed in surrounding tiles, despote crafting being successful

# Expected behavior
 
item should be crafted, then dropped onto player's current tile, 
OR
crafting should fail immediately, with a message informing the player that crafting this required two hands

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4155-g2afc018 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Error occurs both when arm is unsplinted, and when arm splinted. no effect on behaviour

Error does not occur when table nearby. tiny motor ends up placed on the table.

If an item is already wielded, a menu to select what to do appears. If "dispose of your wielded \<item\> and start working" is selected, this bug occurs. If "put it down and start working" is selected, the completed item is placed on the ground, as expected. 

Suspect - but cannot confirm - that this is related to attempting to wield an item that needs to be held in two hands. A few items I tested that can be picked up with one hand (2-by-sword for instance, or rioter mask) craft without this bug, and are wielded at the end of the crafting.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
```SUMMARY: Bugfixes "Consolidated references to broken limbs in one location and fixed crafting with broken limbs"```

#### Purpose of change
Fixes #31323
While looking into fixing this bug I noticed how disorganized the mechanics of broken and injured limbs is and decided to clean it up a little bit. 

#### Describe the solution
The bug fix is to simply force you to craft on the ground if you don't have two functional arms.  Previously this was the only functional work flow that always worked so now it is the only allowed one.
Plus realistically if you have a broken or heavily injured arm you are lucky to be crafting at all let alone without setting it on the ground.

I moved all the code that was checking if limb health is 0 to instead call a method in character that determines if a limb is broken.  Right now it just checks if health is 0 but in the future it will be easier to have more ways like the planned wound system.

There are two new limbs states I created methods to access, hindered and disabled.  These both already existed but were not named and were defined in very different places.  Hindered at the moment checks whether limb health is less than 40% and is used in calculating run cost.  Disabled is less than 12.5% limb health and is used to check if a limb is strong enough to wield a two handed weapon.

The only functional change of the refactoring in is that you can no longer activate an arm based muscle powered vehicle if your arms are at less than 12.5% health as opposed to the old behavior of not being able to activate if if your arms are broken. The new logic is now the same as being able to wield a two handed weapon.

#### Describe alternatives you've considered
Trying to still allow wielding of smaller crafts with only one arm.  The way everything is set up it would be impossible to tell if this would be allowed until the user has chosen all of their ingredients which gets tricky

### CODE REVIEW

**Comment by dunstad** [comment]
>The bug fix is to simply force you to craft on the ground if you don't have two functional arms. Previously this was the only functional work flow that always worked so now it is the only allowed one.

Is this just a way to introduce a crafting speed penalty when one arm is broken? I can understand there being a penalty, but this seems like a strange way to do it. For one, most crafting recipes don't involve items so heavy you couldn't put them on a table. For two, it would make crafting on the ground no slower when your arm is broken than when it isn't, right?

**Comment by Ramza13** [comment]
I think its kind of a side effect.  So if you craft an object first it creates an in progress item.  If this is too large then the code that handles allowing you to wield things prevents you from holding it but after you made it.  Its not really about the broken arm, if your strength is too low the same thing happens i think.

**Comment by dunstad** [comment]
That makes sense. I see you also mentioned this at the bottom in a section I didn't read! Oops.

File: src/panels.cpp [hunk 1]
```diff
@@ -858,7 +858,8 @@ static void draw_limb_health( avatar &u, const catacurses::window &w, int limb_i
             wprintz( w, color, sym );
         }
     };
-    if( u.hp_cur[limb_index] == 0 && ( limb_index >= hp_arm_l && limb_index <= hp_leg_r ) ) {
+    if( u.is_limb_broken( ( hp_part )limb_index ) && ( limb_index >= hp_arm_l &&
```
Comment (kevingranade) [inline src/panels.cpp]: This is failing because of the "old style cast", this should work
```suggestion
    if( u.is_limb_broken( static_cast<hp_part>( limb_index ) ) && ( limb_index >= hp_arm_l &&
```

File: src/player.cpp [hunk 2]
```diff
@@ -1781,7 +1781,7 @@ bool player::digging() const
 
 bool player::is_on_ground() const
 {
-    return hp_cur[hp_leg_l] == 0 || hp_cur[hp_leg_r] == 0 || has_effect( effect_downed );
```
Comment (cainiaowu) [inline src/player.cpp]: this one looks more like get_broken_leg_count() instead of get_working_leg_count(). The logic is not right here.

File: src/player_hardcoded_effects.cpp [hunk 3]
```diff
@@ -161,8 +161,8 @@ static void eff_fun_fungus( player &u, effect &it )
                 }
                 // We're fucked
             } else if( one_in( 36000 + bonus * 120 ) ) {
-                if( u.hp_cur[hp_arm_l] <= 0 || u.hp_cur[hp_arm_r] <= 0 ) {
-                    if( u.hp_cur[hp_arm_l] <= 0 && u.hp_cur[hp_arm_r] <= 0 ) {
+                if( u.is_limb_broken( hp_arm_l ) || u.is_limb_broken( hp_arm_r ) ) {
+                    if( u.is_limb_broken( hp_arm_l ) <= 0 && u.is_limb_broken( hp_arm_r ) ) {
```
Comment (cainiaowu) [inline src/player_hardcoded_effects.cpp]: what is this <= 0 ?

Comment (Ramza13) [reply src/player_hardcoded_effects.cpp]: A mistake, thanks

File: src/player.cpp (hunk 2 above)
Comment (Ramza13) [reply src/player.cpp]: Wow thanks you are right I got it backwards.

Comment (Ramza13) [reply src/player.cpp]: Thanks, I got the logic backwards.
