### PR TITLE
fix arithmetical error crash

### LINKED ISSUE #73355: Arithmetical error crash
### Describe the bug

values like strength etc. go below zero when bleeding out, causing the game to crash.

### Attach save file

N/A, game crashes when it happens, also it's easy to reproduce.

### Steps to reproduce

1. Spawn a hostile turret to inflict heavy wounds on player
2. move to safety and watch stats go down when bleeding out
3. once it reaches 0 after few turns game crashes

### Expected behavior

I expected the stats to not lower below 0

### Screenshots

_No response_

### Versions and configuration

OS: Windows 10
Game Version: latest experimental
Graphics Version: Titles
Ingame Language: English
Mods Loaded: dda, no_npc_food, personal_portal_storms, no_fungal_growth, blazemod, secronom(happens even without this mod)

### Additional context

[mods.json](https://github.com/CleverRaven/Cataclysm-DDA/files/15142148/mods.json)
[worldoptions.json](https://github.com/CleverRaven/Cataclysm-DDA/files/15142149/worldoptions.json)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15142151/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/15142152/debug.log)

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
fix #73355
#### Describe the solution
Put failsafe against dividing by zero
#### Describe alternatives you've considered
Use some another value but 100
Make custom return if u.weight_capacity() < 0

### CODE REVIEW

**Review by anothersimulacrum — APPROVED** [review]

File: src/display.cpp [hunk 1]
```diff
@@ -986,7 +986,14 @@ std::pair<std::string, nc_color> display::move_count_and_mode_text_color( const
 // Weight carried, relative to capacity, in %, like "90%".
 std::pair<std::string, nc_color> display::carry_weight_text_color( const avatar &u )
 {
-    int carry_wt = ( 100 * u.weight_carried() ) / u.weight_capacity();
+    int carry_wt;
+
+    if( u.weight_capacity() > 0 ) {
```
Comment (GuardianDll) [inline src/display.cpp:991]:
```suggestion
    if( u.weight_capacity() > 0_gram ) {
```

**Comment by osuphobia** [comment]
> I don't think the "new contributor" tag on this PR is accurate at all.

There must be something wrong, the checks only start hours after a PR is created and are running slow AF.
