### PR TITLE
Fix popup when moving from [A] using AIM

### LINKED ISSUE #61922: Regression in AIM functionality (move all)
### Describe the bug

When one pane is selected as All and the other is set to any other tile, using the move all functionality will repeatedly spit out the message "No eligible items found to be moved". Spoke to @RenechCDDA about this on the Discord, and we believe it stems from a change in #61839.

### Steps to reproduce

One pane set to All, one pane set to elsewhere, hit the keybind for move all. Message is shown repeatedly.

### Expected behavior

Items should move properly.

### Screenshots

https://user-images.githubusercontent.com/717574/197829939-25533a05-ca48-433c-8412-b4ea791e91bb.mp4

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1098 (21H2)
- Game Version: d7a8a9b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    No Fungal Growth [no_fungal_growth],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations],
    Megafauna [megafauna],
    DinoMod [DinoMod]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
Bugfixes "Fixes AIM popup when trying to use [A] and there are empty tiles"

#### Purpose of change
Fixes #61922

#### Describe the solution
Solution designed by @RenechCDDA. I admit that I don't understand it, but it works well enough, so I'm not complaining.

#### Describe alternatives you've considered
Letting them do this. I was given the blessing to go ahead in the Discord.

#### Testing
Tried moving from [A] in AIM when there were empty tiles. Seems to work.

### CODE REVIEW

File: src/advanced_inv.cpp [hunk 1]
```diff
@@ -922,7 +922,7 @@ bool advanced_inventory::move_all_items()
         }
     }
 
-    if( spane.items.empty() || liquid_items == spane.items.size() ) {
+    if( ( spane.items.empty() || liquid_items == spane.items.size() ) && !is_processing() ) {
         popup( _( "No eligible items found to be moved." ) );
```
Comment (mqrause) [inline src/advanced_inv.cpp:926]:
```suggestion
    if( spane.items.empty() || liquid_items == spane.items.size() ) {
        if( !is_processing() ) {
            popup( _( "No eligible items found to be moved." ) );
        }
```

You don't skip the return this way.
