### PR TITLE
Made takeoff time cost unavoidable. 

### LINKED ISSUE #46935: Unintended time difference between Wield and Drop for worn items.
# Describe the bug

"Dropping" worn items from your body is slower than "wielding" worn items from your body and then "dropping" them from your hands. 

The discrepancy is sometimes so large that it incentivizes 4x as many keystrokes to reach the desired encumbrance 2x quicker. 

# Steps To Reproduce

Load up a character and go from "starting state" to "final state" using both "option one" and "option two" as defined here. Note the time difference between the two options.  

**Starting State**:
*Axe in hand
*Backpack on back.
*Zombie is in sight but far away.
(This is how you wander around looting a town.)

**Final State**:
*Axe in hand
*Backpack on ground. 
*Zombie has not yet attacked you. 
	(This is how you want to fight when you are worried about torso encumbrance and you want to take advantage of nested inventories.)

**Option one**:
1. Drop Backpack.
(This option takes two keystrokes and ~5 seconds depending on volume.)

**Option two**:
1. Drop Axe.
2. Wield Backpack.
3. Drop Backpack.
4. Wield Axe. 	
(this option takes 8 keystrokes and ~2 seconds depending on volume)

# Expected behavior

Wielding a worn item should simulate the cost of removing that item. Currently it doesn't.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-9072-g1bb53ba-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: 
[
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

I might be wrong about this explaination, feel free to correct me if I am misunderstanding something here. 

"Wielding" a worn item into the hand takes a base amount of time because `avatar::wield()` modifies `Creature::moves -= obtain_cost` and doesn't otherwise affect turn count (from what I can tell).

"Dropping" a worn item to the ground takes an extra 250 moves because not only does `Character::drop()` call `creature::mod_moves( obtain_cost )` but it also calls `player::takeoff()` which adds `mod_moves( -250 )`.

### PR DESCRIPTION
**Pull request by topherclay**
#### Summary

Moved the time costs for removing worn clothing to the same files, so that all actions that remove clothing calculate their costs the same way. 

SUMMARY: Bugfixes "[made take_off times consistent]"

#### Purpose of change

Both the WIELD action and the DROP action can remove clothing from the player, but only the DROP action was calculating a 250 move cost. 

This change makes so players can't avoid the cost of removing clothing by wielding the clothing to the hand for cheap and then dropping from the hand for free. 

Fixes #46935.

#### Describe the solution

This change elevates the 250 move cost from deeper inside the player::takeoff() function up to the item::ontakeoff() function, which both actions were already drawing from.

This makes the superfluous and avoidable cost in player::takeoff() no longer superfluous, and no longer avoidable. Both actions for removing clothing (DROP and WIELD) now draw their costs from the same source. 

#### Describe alternatives you've considered

The flat 250 cost can perhaps be dropped altogether.

The flat 250 cost can be made to scale with volume similar to how all items already are in obtain_cost.

The flat 250 cost can be made to vary with strapped items, inner clothing layers, outer clothing layers, etc.   

#### Testing

✔Reproduced the steps in #46935 to make sure the inconsistency is resolved. 
✔Checked if the UI display of wield time costs is aware of the added cost that was previously bypassed. 

#### Additional context

✔~~This change also makes drawing weapons from holsters take extra time. I'm gonna mark it as a WIP draft until I make sure that worn items that are in holsters still have the same obtain_cost as before.~~

### CODE REVIEW

**Comment by topherclay** [comment]
This Pr failed `General build matrix / varied_builds (g++-7, 1, 1) (pull_request)` because of a test 

```-------------------------------------------------------------------------------
Wield time test
  Wielding without hand encumbrance
-------------------------------------------------------------------------------
/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/tests/wield_times_test.cpp:94
...............................................................................

/home/runner/work/Cataclysm-DDA/Cataclysm-DDA/tests/wield_times_test.cpp:42: FAILED:
  CHECK( Approx( expected_moves ).epsilon( 0.1f ) == move_cost )
with expansion:
Error:   Approx( 375.0 ) == 500 (0x1f4)
```

This wield time test was written without #46935 in mind so the reason the PR fails the test is because the tests are still exploiting that issue.

**Comment by topherclay** [comment]
~~This change also makes drawing weapons from holsters take extra time. I'm gonna mark it as a WIP draft until I make sure that worn items that are in holsters still have the same obtain_cost as before.~~

Actually this change doesn't slow down any holstered items, it only slows down *worn* items like a gun-modded shotgun which is worn with a shoulder strap mod. 

Items like the spear strap, which count as holsters **still** allow the holstered item to be quickly wielded as intended, because the strap itself stays worn.

File: src/player.cpp [hunk 1]
```diff
@@ -1967,8 +1967,6 @@ bool player::takeoff( item &it, std::list<item> *res )
                            _( "<npcname> takes off their %s." ),
                            takeoff_copy.tname() );
 
-    // TODO: Make this variable
-    mod_moves( -250 );
```
Comment (wapcaplet) [inline src/player.cpp:1971]: Can you help me understand how you are compensating for removing this line? This function does not appear to invoke `obtain_cost` in any way, so this would appear to make `player::takeoff` a free (instant) action now.

Because this function is where the actual removal of clothing occurs (and the messaging stating it has occurred), I think it makes sense for the movement cost to be deducted here as well, but maybe I have misunderstood the flow of operations.

Comment (topherclay) [reply src/player.cpp:1971]: I understand what you're saying here. It is unclear when and where the move costs are tallied up, which makes it hard to track the actual move costs. 

This function in handle_action.cpp at line 1270 looks to me like it's already handling the obtain cost as it evaluates the parameter to be passed into the `player::takeoff` function. 

```
static void takeoff()
{
    avatar &player_character = get_avatar();
    item_location loc = game_menus::inv::take_off( player_character );

    if( loc ) {
        player_character.takeoff( *loc.obtain( player_character ) );
    } else {
        add_msg( _( "Never mind." ) );
    }
}
```

It modifies moves of the character who owns the location of the item before it passes that location to `player::takeoff`.

File: src/item_location.cpp [hunk 2]
```diff
@@ -381,6 +381,7 @@ class item_location::impl::item_on_person : public item_location::impl
             } else {
                 // then we are wearing it
                 mv = who->item_handling_cost( obj, true, INVENTORY_HANDLING_PENALTY / 2 );
+                mv += 250;
```
[the remark this answers is not in the document]
Comment (topherclay) [reply src/item_location.cpp:384]: I fully agree about the magic number. 

The reason I did it this way for now is because I didn't want to change any behavior other than closing the exploit of #46935, where the flat cost was paid in the `T`akeoff and `D`rop but not `W`ield actions.  

I think there has to be some compromise between the two philosophies on accessing worn items:
* The 250 cost says that disrobing is slow and should cost extra time. 
* The `item_handling_cost` function says that retrieving worn items should be faster because they are on your body and not tucked away inside inventory. 

Once I have some ideas or feedback on what the compromise should be, the cost would ideally be all contained in one function. 

This change doesn't address that compromise it just addresses #46935.

File: src/player.cpp (hunk 1 above)
Comment (wapcaplet) [reply src/player.cpp:1971]: The `player::takeoff` function is also invoked from `activity_actor.cpp`, `advanced_inv.cpp`, `game.cpp`, `npc.cpp` and `npcmove.cpp`. None of these appear to use the `static void takeoff()` function from `handle_action.cpp`, nor do they invoke `obtain` like that function does. I'm concerned that those other uses of `player::takeoff` will now take zero moves.

Comment (topherclay) [reply src/player.cpp:1971]: Hmm, That makes me want to put the obtain_cost function inside of `player::takeoff` to make sure it happens every time, but then I'll have to de-tangle it from from the `handle_action.cpp` call where it happens "on the way."

**Comment by Maleclypse** [comment]
Is this ready to review?

**Comment by topherclay** [comment]
> 
> Is this ready to review?

I think so? 

I haven't looked at it for 6 months but now that I see #46989 was pulled then that should mean user wapcaplet's latest observation was addressed.
