### PR TITLE
Give NPCs the handicap bonus to use out of LOS welding rigs for vehicle repair

### LINKED ISSUE #35612: NPCs half repair vehicles
Currently NPCs are held to higher standards than the PC when using welding rigs. If they have  to move out of the line of sight or too far from the rig they're unable to use it, reducing the combined utility of welding rigs and NPCs.

# Steps To Reproduce

1. Set up a powered welding rig near a damaged vehicle.
2. Set a vehicle repair zone around vehicle.
3. Order NPC to repair vehicle.
4. Once NPC is finished check damage of vehicle. Many parts will remain damaged.

Edit: Could not reproduce this behaviour at first, then realised it was due to having the debug hammerspace mutation. So, turn that off. Yeah. Reproducible in unmodded game.

# Expected behavior

Vehicle repair is a dull process, but micromanaging NPCs in order to get them to repair can become frustrating. The vehicle welding rig, in the hands of an NPC, is almost a waste depending on the availability of materials. Supplying them with a welder and rechargeable batteries becomes desirable, despite the fact that the welding rig exists purely to streamline this process (at least, I assume that's the reason, plus it means you don't have to muck around with charging batteries). As the rig exists purely for convenience and QOL I see no reason that it shouldn't do the same for NPCs. Indeed, this seems more of an oversight than intentional design.

I would expect that a vehicle welding rig attached to, or within four tiles of, a vehicle should be enough for an NPC to be able to use it, regardless of the position of the NPC in relation to the rig. As the exact nature of the rig is undefined in the description I feel this is an acceptable implementation. If not, explicitly adding a couple of batteries to the recipe requirements should suffice. Or maybe a heavy duty cable.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

For your convenience, a bombed military vehicle including boards to block sight with a welding cart stationed below it is located to the NW in this world. All NPCs have welding goggles and mechanics skills to carry out repairs.
[Bug Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3867258/Bug.Test.zip)

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Give NPCs the handicap bonus to use out of LOS welding rigs"```

#### Purpose of change
Fixes #35612 

Because NPCs cannot drag welding rigs, or use the vehicle interaction menu, nor positoin themselves smartly to have a welding rig within crafting inventory LOS, this then makes up for that somewhat by allowing them to use a welding rig within crafting range, even if the vehicle they are workng on is blocking LOS to it.

#### Describe the solution
Restructure the requirements check a bit, to not require a clear path to form inventory from map,
and manually add welding rig to the inventory where appropiate.

#### Describe alternatives you've considered
N/A

#### Testing
spawned a hatchback, smashed it up a bit, put a welding rig on the opposite side of it
told my follower to go repair it, even though they couldnt see the welding rig, they could use it in the repairing, and recognised they didnt need to fetch anything else as it was nearby.

#### Additional context
N/A

### CODE REVIEW

File: src/activity_item_handling.cpp [hunk 1]
```diff
@@ -1207,8 +1215,28 @@ static bool are_requirements_nearby( const std::vector<tripoint> &loot_spots,
...
+        for( const tripoint &elem : g->m.points_in_radius( src_loc, PICKUP_RANGE - 1 ) ) {
+            const optional_vpart_position vp = g->m.veh_at( elem );
+            if( vp ) {
+                vehicle *const veh = &vp->vehicle();
+                const cata::optional<vpart_reference> weldpart = vp.part_with_feature( "WELDRIG", true );
+                if( weldpart ) {
+                    item welder( "welder", 0 );
+                    welder.charges = veh->fuel_left( "battery", true );
+                    welder.item_tags.insert( "PSEUDO" );
+                    if( !found_welder ) {
```
Comment (Night-Pryanik) [inline src/activity_item_handling.cpp]: This is useless check, you already check for `!found_welder` above, on line 1219.

File: src/activity_item_handling.cpp [hunk 2]
```diff
@@ -1207,8 +1215,26 @@ static bool are_requirements_nearby( const std::vector<tripoint> &loot_spots,
...
         }
     }
-    for( item *elem : p.inv_dump() ) {
-        temp_inv += *elem;
+    // use nearby welding rig without needing to drag it or position yourself on the right side of the vehicle.
+    if( !found_welder ) {
+        for( const tripoint &elem : g->m.points_in_radius( src_loc, PICKUP_RANGE - 1 ) ) {
+            const optional_vpart_position vp = g->m.veh_at( elem );
+            if( vp ) {
+                vehicle *const veh = &vp->vehicle();
```
Comment (BevapDin) [inline src/activity_item_handling.cpp]:
```suggestion
                vehicle &veh = vp->vehicle();
```
You really don't need a pointer here.
