### PR TITLE
Fix manually assigned item letter being removed on unwield

### LINKED ISSUE #50154: Unwielding an item with assigned inventory letter causes the inventory letter to be reset
### Describe the bug

Unwielding an item with assigned (yellow) inventory letter causes the inventory letter to be reset

### Steps To Reproduce

1. Wear a spear strap with a spear
2. Assign an inventory letter to the spear
3. Wield the spear
4. Unwield the spear
5. See that the assigned inventory letter is reset

### Expected behavior

The spear keeps its inventory letter.

### Screenshots

_No response_

### Versions and configuration

f0170fea37d442fcab33e6303e10c9594a8cab7a

### Additional context

Probably caused by #49925, since when the wielded item is added to the inventory, the original wielded item is not removed, which causes the newly added item to lose its inventory letter.

### LINKED ISSUE #50323: Associated hotkey to a item gets lost after being wielded
### Describe the bug

Self explanatory.

### Steps To Reproduce

If you use (i) Inventory -> (=) reassign to give a letter to an item, (w) wield the item, and put it away (w) back into a storage, the letter assigned gets lost.

### Expected behavior

The assigned key should stick.

### Screenshots

_No response_

### Versions and configuration

Windows 10
Version 64x-tiles  15dd993
mods used: statsThroughkills, speedydex, bionic slots, 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by exuvo**
#### Summary
Bugfixes "Fix manually assigned letter being removed on unwield, regression from pull request 49925"

#### Purpose of change

Fixes #50154
Fixes #50323

#### Describe the solution

If item has a manually assigned letter then skip check for favorite letters in cache, which would fail and clear the inventory letter.

When unwielding the item is still in the inventory when being added to pockets and as such a letter collision always occurs, add parameter to ignore the item being moved from this check.

#### Describe alternatives you've considered

None

#### Testing

With auto letter assignment enabled:
Assign letter to wielded item, unwield, letter should stay. Wield again, letter should stay.
Repeat for pocketed item to wield, pocketed item to worn, worn to wield, worn to pocket.
Rotate these operations in any order.

See related issue for more potential test cases.

#### Additional context
Regression from https://github.com/CleverRaven/Cataclysm-DDA/pull/49925 .

Not sure why the previous commits are being picked up for this pull request as they are already merged, if you have any ideas what i have done wrong please tell.

With this 49925 can probably be marked for backporting again.

### CODE REVIEW

**Comment by exuvo** [comment]
Also tested on F branch.

File: src/character.cpp [hunk 1]
```diff
@@ -2904,7 +2904,7 @@ item *Character::try_add( item it, const item *avoid, const bool allow_wield )
         // this will set ret to either it, or to stack where it was placed
         pocket.second->add( it, &ret );
         if( !keep_invlet && ( !it.count_by_charges() || it.charges == ret->charges ) ) {
-            inv->update_invlet( *ret );
+            inv->update_invlet( *ret, true, avoid );
```
Comment (Qrox) [inline src/character.cpp:2907]: `avoid` is not always the original item. For example, `item_pocket::handle_liquid_or_spill` takes `avoid` as the container to avoid, which calls `i_add_or_drop` when the content is solid, in which case `it` is the content whereas `avoid` is the container.

Comment (exuvo) [reply src/character.cpp:2907]: I'll have to add a new parameter to that function then, but i was hoping to avoid large changes.

Comment (exuvo) [reply src/character.cpp:2907]: While working on adding a new parameter i noticed in player.cpp:1820 player::wear it calls has_item with a stack local copy of an item. has_item just seems to do a pointer comparison which will always fail unless i am missing a global specialiced item* == operator somewhere. If it does indeed work then i could also use that which would simplify things a lot.

Comment (Qrox) [reply src/character.cpp:2907]: I don't think there is an overload like that; that would be rather hacky and prone to confusion.

Comment (exuvo) [reply src/character.cpp:2907]: In that case i think most checks in player:wear are broken as they are all comparing pointers to a stack local copy of the item.

Comment (exuvo) [reply src/character.cpp:2907]: I made an issue for it #50194.

Comment (exuvo) [reply src/character.cpp]: I have added the new parameter and gone through all the call sites (so damn many) and modified where necessary. The patch is now larger than what i had hoped for but it should handle your frozen liquid case.

I placed the new parameter after the existing avoid so other patches should not break due to this. At most they need to add a nullptr parameter if they were using the trailing boolean settings.

**Comment by actual-nh** [comment]
Can add "Fixes #50323".

**Comment by exuvo** [comment]
Done.

Also want to mention that i tested the additional commits on F branch too.

**Comment by kevingranade** [comment]
Also merged into 0.F-branch
