### PR TITLE
Don't add duplicate options to the page

### LINKED ISSUE #37534: Display shown twice in graphics settings
# Describe the bug

Display is shown twice in the graphics settings.

# Steps To Reproduce

1. Start game, check graphics options.

# Expected behavior

Display would be shown once.

# Screenshots

Screenshot_2020-01-30_01-41-27

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 18.1.5; Codename: Juhraya; 
- Game Version: 0.D-11756-g77d267957e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

Have only one display, can't test what happens when option changed.

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: None```

#### Purpose of change

Fixes #37534

#### Describe the solution

Check for duplicates before adding options to the their page.

#### Testing

Go to `Options` menu and see that `Display` option on `Graphics` tab is not duplicated anymore.

#### Additional context

While I am there, I've also added early return, so we don't iterate remaining pages once required page is found.

### CODE REVIEW

File: src/options.cpp [hunk 1]
```diff
@@ -135,7 +135,14 @@ void options_manager::addOptionToPage( const std::string &name, const std::strin
 {
     for( Page &p : pages_ ) {
         if( p.id_ == page ) {
+            // Don't add duplicate options to the page
+            for( const cata::optional<std::string> &i : p.items_ ) {
+                if( i.has_value() && i.value() == name ) {
```
Comment (codemime) [inline src/options.cpp]: Shouldn't duplicates be handled in the calling code? I mean something tries to add duplicate entries and that's weird.

Comment (ZhilkinSerg) [reply src/options.cpp]: Well, yes, `DISPLAY` option is added both through `find_videodisplays` and `add_graphic_options`.
