### PR TITLE
Fix Battery System CBM not accepting batteries

### LINKED ISSUE #41744: Battery System CBM does not allow consumption of batteries in inventory
# Describe the bug

The Battery System CBM does not allow consumption of batteries in the inventory.

# Steps To Reproduce

1. Spawn 2 disposable light batteries
2. Pick up one, leave the other one on the ground beside you
3. [E]at
4. Only the battery not in your inventory will show up

# Expected behavior

Player should be able to consume batteries whether they're in the inventory or not

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-3547-g7d8b016 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    No Rail Stations [No_Rail_Stations],
    Mythical Martial Arts [MMA]

### PR DESCRIPTION
**Pull request by UrbanCMC**
#### Summary

SUMMARY: Bugfixes "Fix Battery System CBM not accepting batteries"

#### Purpose of change

Fixes #41744 which was made even worse by #42095 which made directly accessing the batteries, and thus fuelling the CBM, impossible.

#### Describe the solution

This modifies the checks used to determine valid fuel sources for CBMs. Any item of the `MAGAZINE` type that contains an ammo type that would be considered a fuel source will now be seen as valid.
  * This explicitly checks for `it.type->magazine` instead of using `is_magazine()`, because the latter would include anything that has a `MAGAZINE_WELL`, which would show things like smartphones as valid fuel sources.

Anything related to charging CBMs through item consumption now distinguishes between magazines and normal items.

I also adjusted the relevant test case for checking battery magazines.
  * One consequence of this is that it is now possible to charge the CBM from vehicle batteries, since they're defined just like ordinary batteries in JSON.

#### Describe alternatives you've considered

Reverting #42095, which would bring back batteries and cents floating around the inventory.

#### Testing

* Made sure consuming batteries works both from the inventory and other containers.
* If a battery contains too much charge, the CBM removes only as much as it can contain.
* Tested other CBMs (ethanol burner and gasoline fuel cell) to ensure they still work as expected.

#### Additional context

The `E`at menu correctly displaying fuel sources
Success

### CODE REVIEW

File: src/consumption.cpp [hunk 1]
```diff
@@ -1500,28 +1500,42 @@ bool Character::fuel_bionic_with( item &it )
 
     const bionic_id bio = get_most_efficient_bionic( get_bionic_fueled_with( it ) );
 
-    const int loadable = std::min( it.charges, get_fuel_capacity( it.typeId() ) );
-    const std::string str_loaded  = get_value( it.typeId().str() );
+    const bool is_magazine = !!it.type->magazine;
```
Comment (Fris0uman) [inline src/consumption.cpp:1503]: Why the double `!` ?

Comment (UrbanCMC) [reply src/consumption.cpp:1503]: It's the easiest way to get the `bool` I wanted, and follows what is done in `item::is_magazine()` and its friends.

Is there a preferred alternative?

Comment (jbytheway) [reply src/consumption.cpp:1503]: There's precedent; it's used elsewhere in the codebase so it's probably fine.  But the alternative would be `it.type->magazine != nullptr`, which might be clearer.  It's a question of personal taste.

Comment (Fris0uman) [reply src/consumption.cpp:1503]: To me it looked like a typo ^^" so I feel like `it.type->magazine != nullptr` would be clearer.
