### PR TITLE
Parallel Bridge Bridgehead Generation Fix

### LINKED ISSUE #42523: Bridge body perpendicular to ramps
# Describe the bug
Bridge is constructed incorrectly. Middle parts are disconnected from the entrance/exit, rendering the bridge unusable.

# Steps To Reproduce

This happens by chance, there are plenty of bridges that are constructed correctly. This is approximately the 10th bridge I've encountered.

# Expected behavior

Bridges are not comically mishappen.

# Screenshots

Untitleddd

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4551-geb83022 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Bionic Slots [cbm_slots],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm]
]

# Additional Info
To the left of the screenshot is no road, by the way, so looking at it again, it would seem to me that this bug is caused by the game trying to construct two bridges right next to each other, the road wants to go over the river and makes a bridge and on the other side of the river the road immediately makes a U turn and makes another bridge back, with no spacing between the two bridges, I'd reckon that the precedent of two bridges so close to each other is not set, so the game defaults to making the bridge parts vertical. (This is pure conjecture, I don't actually know how the game handles bridges.)

This is the bridge on the map:
Untitleddddd

### PR DESCRIPTION
**Pull request by KamikazieBoater**
Fix for parallel bridges being composed entirely of bridgeheads

#### Summary

SUMMARY: Bugfixes "Parallel Bridge Generation All Bridgeheads"

#### Purpose of change

Parallel bridges lead to issues in map generation that cause any parallel bridge segments to be replaced entirely with bridgeheads. Fixes #42523

#### Describe the solution

Bridgehead generation is now rotation-aware with respect to adjacent bridge tiles, ensuring bridgeheads are only generated at the end of a bridge and having the correct orientation.

#### Describe alternatives you've considered

None

#### Testing

Implemented logic fix, generated a new world, found parallel bridges to have generated correctly.

#### Additional context

Current Build:
parallel_bridge_gen

After Fix:
parallel_bridge_fix

### CODE REVIEW

File: src/overmap.cpp [hunk 1]
```diff
@@ -1805,11 +1805,15 @@ void overmap::generate_bridgeheads( const std::vector<point_om_omt> &bridge_poin
...
         const oter_id oter_ground_south = ter( tripoint_om_omt( bp, 0 ) + tripoint_south );
         const oter_id oter_ground_east = ter( tripoint_om_omt( bp, 0 ) + tripoint_east );
-        const oter_id oter_ground_west = ter( tripoint_om_omt( bp, 0 ) + tripoint_west );
-        const bool is_bridge_north = is_ot_match( "bridge", oter_ground_north, ot_match_type::type );
-        const bool is_bridge_south = is_ot_match( "bridge", oter_ground_south, ot_match_type::type );
-        const bool is_bridge_east = is_ot_match( "bridge", oter_ground_east, ot_match_type::type );
-        const bool is_bridge_west = is_ot_match( "bridge", oter_ground_west, ot_match_type::type );
+        const oter_id oter_ground_west = ter(tripoint_om_omt(bp, 0) + tripoint_west);
+        const bool is_bridge_north = is_ot_match( "bridge", oter_ground_north, ot_match_type::type )
+                                     && ( oter_get_rotation_string( oter_ground_north ).compare( 4, 2, "th" ) == 0 );
```
Comment (ZhilkinSerg) [inline src/overmap.cpp:1810]: I think you should better use `oter_get_rotation` function here instead of string hacks.
