### PR TITLE
Display correct item info for each item in V menu.

### LINKED ISSUE #12228: Snippets are not being displayed properly in "V"-mode
WHat it says on the can. Find several pieces of newspaper, press V, change the selection between them, and it will always show the same text. I assume this is due to snippet stuff. 
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/12399961-snippets-are-not-being-displayed-properly-in-v-mode?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #44594: List items screen `V` shows same charges for items with different charges
# Describe the bug

When using `V` to view items in the current surroundings, all charged items of the same type such as inhalers will appear to have the same charges, even if they are all different.

# Steps To Reproduce

1. Load the provided save game [ViewInhalerSameCharges.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5322463/ViewInhalerSameCharges.zip)
2. Use `g`rab or advanced inventory to check out the two nearby inhalers - see they have different charges
3. Move closer to the top inhaler and press `V` to view surrounding items, and arrow key left and right to see the inhalers - both appear to have the same charges as the top inhaler (37)
4. Move closer to the bottom inhaler and press `V` again - see they both appear to have the bottom inhaler's charges (47) now

More generally:

1. Have two or more nearby charged items with different charges (refillable lighter, for another example)
2. Drop them both in different spots on the ground
3. Use `V` to view them both - see they seem to have the same charges

# Expected behavior

Items appear to have correct charges when viewed with `V`.

# Screenshots

Two inhalers with different charges, visible using `g`rab:

image

They appear to have the same charges when viewed from `V`iew items:

image

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-6461-gf70482e6e8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Many item drops do not correctly have any charges, or do not have different random charges, per #44071 - it may be necessary to define `charges-min` and `charges-max` in the death-drop JSON to get different charges for item drops.

Save game: [ViewInhalerSameCharges.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5322463/ViewInhalerSameCharges.zip)

### PR DESCRIPTION
**Pull request by OzoneH3**
#### Summary
SUMMARY: Interface "Display correct item info for each item in V menu."

#### Purpose of change
Fixes #44594
Fixes #12228

#### Describe the solution
Save pointers to all items not just the first.

#### Testing
Spawn lighters with different charges.
Drop lighters.
Open V menu.
Cycle through lighters and see correct item_info/name for each

### CODE REVIEW

File: src/map_item_stack.h [hunk 1]
```diff
@@ -18,10 +18,11 @@ class map_item_stack
             public:
                 tripoint pos;
                 int count;
+                const item *it;
 
                 //only expected to be used for things like lists and vectors
                 item_group();
-                item_group( const tripoint &p, int arg_count );
+                item_group( const tripoint &p, const int arg_count, const item *itm );
```
Comment (ZhilkinSerg) [inline src/map_item_stack.h:25]:
```suggestion
                item_group( const tripoint &p, int arg_count, const item *itm );
```
