### PR TITLE
Translate faction strings

### LINKED ISSUE #23482: Faction name and first paragraph of faction description is not translated
Game version: ae5bdc0

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: N/A

### Summary
The faction name and first paragraph of faction description is not translated.

Example: “Your followers”

### How to reproduce
Use German. The just press the faction key in a new world. If you check de.po you'll see that both relevant strings are translated.

### PR DESCRIPTION
**Pull request by AMurkin**
Fixes #23482

### CODE REVIEW

File: src/faction.cpp [hunk 1]
```diff
@@ -378,7 +378,7 @@ bool faction::matches_us(faction_value v) const
 std::string faction::describe() const
 {
     std::string ret;
-    ret = desc + "\n \n" + string_format( _("%1$s have the ultimate goal of %2$s."), name.c_str(),
+    ret = string_format( "%1$s\n \n%2$s have the ultimate goal of %3$s.", _( desc.c_str() ), _( name.c_str() ),
```
Comment (BrettDong) [inline src/faction.cpp]: Shouldn't it be `string_format( _( "%1$s\n \n%2$s have the ultimate goal of %3$s." ), ... )` ?

Also, I'd rather fix the issue like this:
```c++
std::string ret = _( desc.c_str() );
ret = ret + "\n\n" + string_format( _( "%1$s have the ultimate goal of %2$s." ), _( name.c_str() ), _( facgoal_data[goal].name.c_str() ) );
```

Comment (AMurkin) [reply src/faction.cpp]: I agree.
