### PR TITLE
Toss&Turn and Sleep interruption 

### LINKED ISSUE #28326: Sleeping causes the player to roll till the player is tired and then puts them to sleep, regardless of actual tiredness
When going to sleep and confirming to go to sleep, the player will toss and turn as if troubled sleeping and will due this action till such time as tiredness is at a low enough level to fall asleep. This chain of events can be done at any time, even if the player has just woken up from a full night of sleep. This leads the player to "sleep" long amounts of time without any chance to stop the action. Normal actions of waking the player up such as noise, attacks, or alarms gives the player the option to wake up or ignore said item of trying to get them out of the action.

**To Reproduce**  
1. Hit your context key for player sleep, default ($)
2. Allow sleep to progress after confirming in menus
3. Watch as time fly's by without being able to stop. (.) will still allow for you to stop while on tossing phase.

**Expected behavior**  
I am unsure how changes to sleeping were changed, it has been some time since I last played CDDA, after asking on the discord chat about this issue, some of the other have stated that other people have asked about this. The last time I have played CDDA (nine or more months ago) attempting to sleep when not sleepy will prevent the player from sleeping with a cannot sleep message with some minor time passage. If this is a current feature for sleeping and is as intended then I am sorry for opening this issue ticket. If intended as feature, perhaps a lock on how long you will spend attempting to sleep again be added, faster computers or where slow down is not an issue has time flying by if you are not paying attention.

 - OS: Windows 10 (1809 build)
 - Game Version: 0.C-37555-gf76242f
 - Graphics version: Tiles
 - Mods loaded: No mods used in the testing

Note this may be related to Impossible to sleep with insomniac trait on uncomfortable surfaces i,e pine lean-to. #28247

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Features "Add querry to stop trying to fall of sleep after 30min of trying"```

#### Purpose of change
Add querry to stop trying to fall of sleep after 30min of trying
Fixes #28326
Adresses at least part of #34362 
#### Describe the solution
call `try_sleep_query()` every 30_min of toss&turning, querry has 3 options keep trying, stop, keep trying and stop asking.

No blackout if asleep, and no dizzyness if asleep.

#### Additional context
Regarding #34362  I tried the very bad day start and only the cough would interrupt my sleep, so I'm not sure the issue is solved but the situation should be better.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -2986,9 +2986,38 @@ void activity_handlers::try_sleep_do_turn( player_activity *act, player *p )
...
+{
+    if( p->get_value( "sleep_query" ) == "false" ) {
+        return;
+    }
+    uilist sleep_query;
+    sleep_query.text = _( "You have trouble sleeping, keep trying?" );
+    sleep_query.addentry( 1, true, 'S', _( "Stop trying to fall asleep and get up." ) );
+    sleep_query.addentry( 2, true, 'c', _( "Continue trying to fall asleep." ) );
+    sleep_query.addentry( 3, true, 'C',
+                          _( "Continue trying to fall asleep and don't prompt further querry." ) );
```
Comment (Night-Pryanik) [inline src/activity_handlers.cpp]: Query instead of a "querry".
