### PR TITLE
Prevent possible nullptr crash

### LINKED ISSUE #56382: Looking at the shoulder strap or its recipe crashes the game
### Describe the bug

Attempting to looking at a shoulder strap, its recipe, or attempting to remove one from a gun that spawns with it will crash the game.

### Steps to reproduce

1. Get fab 1 so you unlock shoulder strap recipe/find an unattached shoulder strap/pick a profession with a gun that has one.
2. Attempt to look at the recipe/look at the item/detach the shoulder strap or look at the gun.
3. Crash.

### Expected behavior

No crash

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.556 (21H2)
- Game Version: 0cc5c05 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[SStrapCrash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8357768/SStrapCrash.zip)
[WorldSettings.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8357775/WorldSettings.zip)

### LINKED ISSUE #56389: Game crash when player wants to make shoulder_strap
### Describe the bug

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0cc5c05
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

  #0
    (dbghelp: @0x7ff7adb67680[cataclysm-tiles.exe+0x1f7680]), 
    (libbacktrace: debug_write_backtrace(std::ostream&)+0x9e@0x1401f7680),
    (libbacktrace: 0x1401f7680    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff7adb50c91[cataclysm-tiles.exe+0x1e0c91]), 
    (libbacktrace: log_crash+0x1d2@0x1401e0c91),
    (libbacktrace: 0x1401e0c91    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff7adb50ebf[cataclysm-tiles.exe+0x1e0ebf]), 
    (libbacktrace: signal_handler+0x52@0x1401e0ebf),
    (libbacktrace: 0x1401e0ebf    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff7ae41c092[cataclysm-tiles.exe+0xaac092]), 
    (libbacktrace: gnu_exception_handler+0x182@0x140aac092),
    (libbacktrace: 0x140aac092    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crt_handler.c:224    _gnu_exception_handler),
  #4
    (dbghelp: _C_specific_handler+0x98@0x7ff85b507ff8[msvcrt.dll+0x27ff8]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #5
    (dbghelp: _chkstk+0x11f@0x7ff85bdf20cf[ntdll.dll+0xa20cf]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #6
    (dbghelp: RtlRaiseException+0x434@0x7ff85bda1454[ntdll.dll+0x51454]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: KiUserExceptionDispatcher+0x2e@0x7ff85bdf0bfe[ntdll.dll+0xa0bfe]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #8
    (dbghelp: @0x7ff7add48367[cataclysm-tiles.exe+0x3d8367]), 
    (libbacktrace: item::armor_info(std::vector<iteminfo, std::allocator<iteminfo> >&, iteminfo_query const*, int, bool) const+0x1487@0x1403d8367),
    (libbacktrace: 0x1403d8367    [unknown src]:0    [unknown func]),
  #9
    (dbghelp: @0x7ff7add661ef[cataclysm-tiles.exe+0x3f61ef]), 
    (libbacktrace: item::info[abi:cxx11](std::vector<iteminfo, std::allocator<iteminfo> >&, iteminfo_query const*, int) const+0x4b9@0x1403f61ef),
    (libbacktrace: 0x1403f61ef    [unknown src]:0    [unknown func]),
  #10
    (dbghelp: @0x7ff7add6652b[cataclysm-tiles.exe+0x3f652b]), 
    (libbacktrace: item::info[abi:cxx11](bool, std::vector<iteminfo, std::allocator<iteminfo> >&, int) const+0x31@0x1403f652b),
    (libbacktrace: 0x1403f652b    [unknown src]:0    [unknown func]),
  #11
    (dbghelp: @0x7ff7adb49868[cataclysm-tiles.exe+0x1d9868]), 
    (libbacktrace: item_info_data_from_recipe(item_info_cache&, int*, int*, recipe const*, int, int&)+0xda@0x1401d9868),
    (libbacktrace: 0x1401d9868    [unknown src]:0    [unknown func]),
  #12
    (dbghelp: @0x7ff7adb4b7d6[cataclysm-tiles.exe+0x1db7d6]), 
    (libbacktrace: select_crafting_recipe(int&, string_id<recipe>)::{lambda(ui_adaptor const&)#3}::operator()(ui_adaptor const&) const [clone .constprop.0]+0x1e6e@0x1401db7d6),
    (libbacktrace: 0x1401db7d6    [unknown src]:0    [unknown func]),
  #13
    (dbghelp: @0x7ff7ae2b40c9[cataclysm-tiles.exe+0x9440c9]), 
    (libbacktrace: ui_adaptor::redraw_invalidated()+0x16d@0x1409440c9),
    (libbacktrace: 0x1409440c9    [unknown src]:0    [unknown func]),
  #14
    (dbghelp: @0x7ff7adb4da2d[cataclysm-tiles.exe+0x1dda2d]), 
    (libbacktrace: select_crafting_recipe(int&, string_id<recipe>)+0x2135@0x1401dda2d),
    (libbacktrace: 0x1401dda2d    [unknown src]:0    [unknown func]),
  #15
    (dbghelp: @0x7ff7adb34e6a[cataclysm-tiles.exe+0x1c4e6a]), 
    (libbacktrace: Character::craft(cata::optional<tripoint> const&, string_id<recipe> const&)+0x2e@0x1401c4e6a),
    (libbacktrace: 0x1401c4e6a    [unknown src]:0    [unknown func]),
  #16
    (dbghelp: @0x7ff7adca8d8d[cataclysm-tiles.exe+0x338d8d]), 
    (libbacktrace: game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x2e45@0x140338d8d),
    (libbacktrace: 0x140338d8d    [unknown src]:0    [unknown func]),
  #17
    (dbghelp: @0x7ff7adcac736[cataclysm-tiles.exe+0x33c736]), 
    (libbacktrace: game::handle_action()+0xafa@0x14033c736),
    (libbacktrace: 0x14033c736    [unknown src]:0    [unknown func]),
  #18
    (dbghelp: @0x7ff7adbae540[cataclysm-tiles.exe+0x23e540]), 
    (libbacktrace: do_turn()+0x546@0x14023e540),
    (libbacktrace: 0x14023e540    [unknown src]:0    [unknown func]),
  #19
    (dbghelp: @0x7ff7aede2f66[cataclysm-tiles.exe+0x1472f66]), 
    (libbacktrace: main+0x18f6@0x141472f66),
    (libbacktrace: 0x141472f66    [unknown src]:0    [unknown func]),
  #20
    (dbghelp: @0x7ff7ad9713c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: _tmainCRTStartup+0x231@0x1400013c1),
    (libbacktrace: 0x1400013c1    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:323    __tmainCRTStartup),
  #21
    (dbghelp: @0x7ff7ad9714d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: WinMainCRTStartup+0x16@0x1400014d6),
    (libbacktrace: 0x1400014d6    /opt/mxe/tmp-gcc-x86_64-w64-mingw32.static.gcc11/gcc-11.2.0.build_/mingw-w64-v9.0.0/mingw-w64-crt/crt/crtexe.c:178    WinMainCRTStartup),
  #22
    (dbghelp: BaseThreadInitThunk+0x14@0x7ff85a267034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #23
    (dbghelp: RtlUserThreadStart+0x21@0x7ff85bda2651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),

### Steps to reproduce

1.Start game;
2.Press the & key and open "craft item" interface;
3.Try to select weapon—shoulder_strap;
4.Game crash.

### Expected behavior

This is clearly wrong.

### Screenshots

_No response_

### Versions and configuration

cdda-windows-tiles-x64-2022-03-27-0725

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary
Bugfixes "Prevent possible nullptr crash"

#### Purpose of change

Fixes #56382
Fixes #56389

#### Describe the solution
A pointer that can be a nullptr was being referenced, causing a crash when viewing a shoulder strap mod or its recipe. This avoids the use of the pointer when nullptr - behaviour is the same as in other sections of code that use the same pointer.

#### Testing
Viewing the recipe or shoulder strap item causes no problems. Viewed all recipes with no crashes.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -3574,16 +3574,18 @@ void item::armor_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
...
-            std::string coverage = _( "<bold>Rigid</bold>:" );
-            for( const armor_portion_data &entry : armor->sub_data ) {
-                if( entry.rigid ) {
-                    for( const sub_bodypart_str_id &sbp : entry.sub_coverage ) {
-                        coverage += string_format( _( ", <info>%s</info>" ), sbp->name );
+        if( armor != nullptr ) {
+            if( armor->rigid ) {
+                std::string coverage = _( "<bold>This armor is rigid</bold>" );
+                info.emplace_back( "ARMOR", coverage );
+            } else if( !!armor ) {
```
Comment (anothersimulacrum) [inline src/item.cpp:3581]: Isn't this redunant with the above nullptr check?

Comment (RoyBerube) [reply src/item.cpp:3581]: You are correct. I rewrote my code and forgot to remove that.

File: src/item.cpp [hunk 2]
```diff
@@ -3593,16 +3595,18 @@ void item::armor_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
...
-            for( const armor_portion_data &entry : armor->sub_data ) {
-                if( entry.comfortable ) {
-                    for( const sub_bodypart_str_id &sbp : entry.sub_coverage ) {
-                        coverage += string_format( _( ", <info>%s</info>" ), sbp->name );
+        if( armor != nullptr ) {
+            if( armor->comfortable ) {
+                std::string coverage = _( "<bold>This armor is comfortable</bold>" );
+                info.emplace_back( "ARMOR", coverage );
+            } else {
+                //only some parts are comfortable
```
Comment (NetSysFire) [inline src/item.cpp:3603]:
```suggestion
                // only some parts are comfortable
```

File: src/item.cpp [hunk 3]
```diff
@@ -3574,16 +3574,18 @@ void item::armor_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
...
-            for( const armor_portion_data &entry : armor->sub_data ) {
-                if( entry.rigid ) {
-                    for( const sub_bodypart_str_id &sbp : entry.sub_coverage ) {
-                        coverage += string_format( _( ", <info>%s</info>" ), sbp->name );
+        if( armor != nullptr ) {
+            if( armor->rigid ) {
+                std::string coverage = _( "<bold>This armor is rigid</bold>" );
+                info.emplace_back( "ARMOR", coverage );
+            } else {
+                //only some parts are rigid
```
Comment (NetSysFire) [inline src/item.cpp:3582]:
```suggestion
                // only some parts are rigid
```

**Review by NetSysFire — COMMENTED** [review]
Just some minor whitespace changes so it is consistent with existing whitespace

**Comment by Inglonias** [comment]
I'm curious what it was about shoulder straps in particular that causes this to happen. Is it because shoulder straps aren't technically armor?

**Comment by RoyBerube** [comment]
@Inglonias  The call to `find_armor_data()` returns a nullptr if the item has no armor data. Failure to check if it was a nullptr caused the crash.
