### PR TITLE
Fix gas mask to allow filter reload and activation

### LINKED ISSUE #40889: Acoustic guitar produces no music
# Describe the bug

Playing acoustic guitar, electric guitar or harmonica gives no morale boost and produces no messages in the log. mp3 player works as intended though.

# Steps To Reproduce

1. Wish for an acoustic guitar
2. Activate it
3. Wait for 5 minutes
4. [v]iew morale
5. See that there is no morale bonus

# Expected behavior

Playing music should give a morale bonus.

# Screenshots

none

# Versions and configuration

- OS: Linux
    - OS Version: Fedora release 32 (Thirty Two)
- Game Version: 0.E-2476-g1b2af09 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

none

### LINKED ISSUE #40894: Gas masks don't work
# Describe the bug

The problem described in #40765 still persists, it's not possible to reload gas masks with cartridges (tested on gas mask, survivor gas mask, light survivor gas mask, XL gas mask), thus rendering them impossible to activate. However, testing it on a gas mask which I had loaded and activated beforehand (in build 10614), I found out that this mask stays activated and works in gas clouds without any charges loaded. 

# Steps To Reproduce

1. Spawn a gas mask
2. Spawn gas mask cartridges
3. Try to reload the mask
4. Get the "you can' reload the mask" message in the log. 
5. Get an activated gas mask (with no charges)
6. Spawn a bloated zombie
7. Walk into a gas cloud while wearing this activated gas mask with no charges, gas poisoning does not happen, no messages about "inhaling toxic gas" appear in the log. 

# Expected behavior

Gas masks can be reloaded with cartridges and consume them as charges when activated and used. 

# Screenshots

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2532-gf4bb830 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
this error occurs when trying to activate an empty light survivor mask - 

```
DEBUG    : can't set ammo null as it is not an ammo
FUNCTION : item& item::ammo_set(const itype_id&, int)
FILE     : src/item.cpp
LINE     : 583
```

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

SUMMARY: Bugfixes "Fix gas mask to allow filter reload and activation"

#### Purpose of change

Fix #40894

Allow gas mask to be reloaded with a filter, and activated to protect the wearer against gas clouds, and cause gas mask filter to be depleted when worn in a smoke cloud.

Fix #40889 

Allow guitar and harmonica to give ongoing morale buffs when active and playing music (seemingly unrelated, but had the same cause as gas mask depletion).

#### Describe the solution

This includes a patch provided by @anothersimulacrum to use the new pocket_data JSON format for the gas mask, rebreather, scuba tank and other tool-armors having reloadable charges, allowing them to be correctly reloaded (instead of saying "You can't reload a ...")

Changes the references to `charges` with `ammo_remaining()` in the `iuse::gasmask` function, so the loaded filter "ammo" can be correctly detected when activating the gas mask.

#### Describe alternatives you've considered

Considered buffing the gas mask filter depletion to be more realistic - it is quite fast now, about 1 charge every 7 turns in a Mi-go encampment, or 1 charge every 9-10 turns in the cloud of a smoke bomb. This is the same filter depletion rate as 0.E-2. In the worst case, it would take about 700 turns or ~12 minutes of in-game time to completely use up a filter inside a Mi-go encampment.

By comparison, "Most combined gas mask filters will last around 8 hours in a nuclear biological chemical (NBC) situation. Chemical specific filters can last up to 20 hours in an NBC situation" - [Gas mask, Wikipedia](https://en.wikipedia.org/wiki/Gas_mask)

I did not change the filter depletion rate, preferring to leave that for another PR. Getting gas masks working again like they did in 0.E-2 is good enough for me.

#### Testing

Before applying this patch, reloading a gas mask, rebreather, or scuba tank, it would simply fail, saying you cannot reload:

image

After the patch, reloading those same tool-armors becomes possible (though I didn't have any compressed air for the scuba tank):

image

Activating the gas mask also becomes possible:

image

Wearing the gas mask in a cloud of smoke protects me (and taking it off causes me to cough). Gas mask filters are depleted after walking around in smoke for a while:

image

Measuring the filter depletion rate in the foul air of a Mi-go encampment, it used about 1 charge every 7 turns. This is the same rate observed in version 0.E-2 in the same circumstances.

Finally, as gas masks actively filter air pollutants, guitars actively produce music and happiness:

image

#### Additional context

Many thanks to @anothersimulacrum @KorGgenT @ifreund and @chaosvolt for the assists on this one.

### CODE REVIEW

**Comment by wapcaplet** [comment]
Through in-game testing and setting debugger breakpoints, I've become fairly confident that `iuse::gasmask` is only called when the gas mask is first activated - and never again after that, during the item processing event loop every turn - so its filters are never depleted.

File: src/item_factory.cpp [hunk 1]
```diff
@@ -1821,12 +1822,25 @@ void Item_factory::load_toolmod( const JsonObject &jo, const std::string &src )
     }
 }
 
+// TODO: Refactor this with load_armor
+// This function does load_slog( def.tool ), but otherwise they are the same
```
Comment (anothersimulacrum) [inline src/item_factory.cpp:1826]: It may have been one, but I think this is a typo
```suggestion
// This function does load_slot( def.tool ), but otherwise they are the same
```

Comment (wapcaplet) [reply src/item_factory.cpp:1826]: Oops, thank you!
