### PR TITLE
Handle broken arms with mech

### LINKED ISSUE #46764: Combat mech "consumes" your gun if you have an arm broken
# Describe the bug

"grunt" combat mech does not use its laser cannon if one of your arms is broken, it will ask you to draw your own guns if you use the [f]ire command, which will make the selected gun disappear

# Steps To Reproduce

spawn combat mech
break one of your arms
give yourself a gun, any will suffice
get inside the mech
try to fire, it will ask you to draw your gun
draw the gun
now the mech uses the gun until you dismount, then the gun will disappear
the cycle repeats until you have both of your arms functional, in which case the mech uses its laser cannon.

# Expected behavior

the mech using its laser cannon

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-8965-gad0e7ae-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Safe Autodoc [safe_autodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Portable Autodoc [portable_autodoc]
]

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fixes  #46764
Having broken arms with a mech was not working correctly.

#### Describe the solution
Added several checks to allow using mech weapon with broken arms and prevent weapon deletion.  In theory several of these are redundant but better to correctly handle the situation of wielding something with a mech in case it happens anyway.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -9827,8 +9828,10 @@ ret_val<bool> Character::can_wield( const item &it ) const
         return ret_val<bool>::make_failure( _( "The %s is preventing you from wielding the %s." ),
                                             weapname(), it.tname() );
     }
-
-    if( it.is_two_handed( *this ) && ( !has_two_arms() || worn_with_flag( flag_RESTRICT_HANDS ) ) ) {
+    monster *mount = mounted_creature.get();
+    if( it.is_two_handed( *this ) && ( !has_two_arms() || worn_with_flag( flag_RESTRICT_HANDS ) ) &&
+        !( is_mounted() && mounted_creature.get()->has_flag( MF_RIDEABLE_MECH ) &&
+           mount->type->mech_weapon && it.typeId() == mounted_creature.get()->type->mech_weapon ) ) {
```
Comment (kevingranade) [inline src/character.cpp:9834]:
```suggestion
        !( is_mounted() && mount->has_flag( MF_RIDEABLE_MECH ) &&
           mount->type->mech_weapon && it.typeId() == mount->type->mech_weapon ) ) {
```

File: src/character.cpp [hunk 2]
```diff
@@ -9840,6 +9843,10 @@ ret_val<bool> Character::can_wield( const item &it ) const
                                                 it.tname() );
         }
     }
+    if( is_mounted() && mounted_creature.get()->has_flag( MF_RIDEABLE_MECH ) &&
+        mount->type->mech_weapon && it.typeId() != mounted_creature.get()->type->mech_weapon ) {
```
Comment (kevingranade) [inline src/character.cpp:9847]:
```suggestion
    if( is_mounted() && mount->has_flag( MF_RIDEABLE_MECH ) &&
        mount->type->mech_weapon && it.typeId() != mount->type->mech_weapon ) {
```
