### PR TITLE
fixes various text input issues on ncurses

### LINKED ISSUE #78879: string_input_popup_imgui prompts do not let you input text properly on ncurses
### Describe the bug

the popups for searching for keybindings and the prompt for choosing your world name do not work (backspace inserts a `î` character into the prompt, keys are pressed twice, etc)

### Attach save file

N/A

### Steps to reproduce

1. load any world (on ncurses mode)
2. press `?`
3. press `/` or `f`
4. try typing, especially noticable with backspace

(same issue happens when trying to choose the name for a new world as well, both use the same imgui popup widget)

### Expected behavior

I expect to be able to type the same way I would be able to in, say, the inventory/crafting/construction/etc filter screens 

### Screenshots

image

### Versions and configuration

```
-----------------------------------------
13:53:08.540 : Starting log.
13:53:08.542 INFO : Cataclysm DDA version 76c2d106b9
13:53:08.542 INFO : [main] C locale set to C.UTF8
13:53:08.542 INFO : [main] C++ locale set to C.UTF8
13:53:08.556 INFO : [options] C locale set to C.UTF8
13:53:08.556 INFO : [options] C++ locale set to C.UTF8
13:54:27.458 :  GAME REPORT:
- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.17; Codename: n/a; 
- Game Version: 76c2d106b9 [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

13:54:30.966 : Log shutdown.
-----------------------------------------
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by JodiJodington**
#### Summary
Bugfixes "Fixed several issues with imgui text input on ncurses"

#### Purpose of change

Fixes #78879

#### Describe the solution

It makes input non-blocking (fixes odd behavior of the keybinding menu filtering described in #78879 for example, [thanks](https://github.com/CleverRaven/Cataclysm-DDA/issues/78879#issuecomment-2577606597) for the hint @casmic!)
Also now handles special characters specially instead of pushing them through `ImGuiIO::AddInputCharacter()`

#### Describe alternatives you've considered

I can't think of another alternative save for some implementation details
namely input being non-blocking could potentially cause the game to do more work than it has to each frame, if that presents an issue it could make sense to just add a tiny timeout instead of using no delay at all

#### Testing

I launched the game and entered the world name prompt and played around with it and it worked, then I did the same for the keybindings menu, and then I loaded a save and played around for a bit to make sure nothing was broken and there certainly don't seem to be any regressions
for reproducing it might help to see the issue this closes, it explains the issues with the old behavior

#### Additional context

I don't understand [these](https://github.com/JodiJodington/Cataclysm-DDA/blob/7062ba7a1e57cb8d9305dcab149c8d2405bae9ce/src/third-party/imtui/imtui-impl-ncurses.cpp#L296-L313) lines at all and don't seem to be correct at all, but they are also mirrored [upstream](https://github.com/ggerganov/imtui/blob/ec0d62d06175b369c31381e69f615cb5d337361d/src/imtui-impl-ncurses.cpp#L260-L265) so I didn't feel comfortable removing them, in general this entire file felt cargo culted but I suppose that's alright
The lines deleted [here](https://github.com/JodiJodington/Cataclysm-DDA/blob/12d57d4c22d8285320964e03eec1f9da58236c23/src/third-party/imtui/imtui-impl-ncurses.cpp#L118-L139) also don't make any sense to me and were actively creating issues (specifically it was causing the Home button to be held down which would cause issues text input), they are also not there upstream and I can only imagine it was a misunderstanding when [bumping the imgui version](https://github.com/JodiJodington/Cataclysm-DDA/commit/12d57d4c22d8285320964e03eec1f9da58236c23#diff-cd9051f5f2e994df571a2538030b7339085271a9787ecca9b76668cb43018273)

### CODE REVIEW

File: src/third-party/imtui/imtui-impl-ncurses.cpp [hunk 1]
```diff
@@ -153,13 +131,139 @@ void ImTui_ImplNcurses_Shutdown()
...
+    ImGuiKeyTranslation( ImGuiKey k, bool s = false ) :
+        key( k ),
+        shift( s )
+    {}
+};
+
+
+// returns ImGuiKey_None if it doesn't have an ImGui_Key counterpart
+// or if it is a character compatible with `ImGuiIO::addInputCharacter()`
+static ImGuiKeyTranslation ncurses_special_key_to_imgui_key( int key )
```
Comment (RenechCDDA) [inline src/third-party/imtui/imtui-impl-ncurses.cpp:154]: This feels like it could/should be a map instead of a switch. I don't have a *strong* opinion on this, but I figure I'd point it out while I'm here.

Is there a reason for this is a #define? I'm not seeing usage in this PR that would require that.

**Comment by JodiJodington** [comment]
the CI failure seems to be unrelated to the PR, is there any way to request to retry it or skip it since it’s required?

**Comment by RenechCDDA** [comment]
I restarted it. If a merger/triage sees it they'll generally do it for you. You can also ask (obviously), or push an empty commit.

File: src/ncurses_def.cpp [hunk 2]
```diff
@@ -420,6 +420,9 @@ input_event input_manager::get_input_event( const keyboard_mode /*preferred_keyb
         previously_pressed_key = 0;
         // flush any output
         catacurses::doupdate();
+        // could also just do this each time a window is created to ensure every ncurses window has this property,
+        // but this function is virtually free anyway
+        nodelay( stdscr, true );
```
Comment (BevapDin) [inline src/ncurses_def.cpp:425]: This line seems to cause #80386, at least removing it fixes the high CPU usage.

I don't understand how **repeatedly** setting the option for **only** the standard window (`stdscr`) will "ensure every ncurses window has this property".

`nodelay` is only called here, one call for `stdsrc` (at the start of the program) would be enough as it is never turned off anyway.

However, setting the nodelay option causes the function to return immediately with a timeout event. Most input context don't care about that event end will just call `get_input_event` again, which returns immediately again and so on. (This causes the high CPU usage.)

That option should probably remain disabled.

Comment (JodiJodington) [reply src/ncurses_def.cpp:425]: I'm not on a computer and don't play CDDA anymore so don't know if I can test this any time soon, but iirc if I didn't have that line, some curses imgui windows would misbehave and flicker since they wouldn't get redrawn, but I don't remember in what way. Sorry for not leaving a good comment there, but I hope this is at least enough to help you test for any regressions
