### PR TITLE
Fixing muscle engines failing to start randomly

### LINKED ISSUE #43119: The Bicycles engine fails to start.
# Describe the bug
Being told the engine fails to start on my bicycle with a damaged pedal.

# Steps To Reproduce
1. Find a bicycle with damaged pedals (not fualty)
2. attempt to use bicycle until it decided to fail an engine start.
3. Question how a non-faulty part is causing an issue, and why it says engine for bicycle pedals.

# Expected behavior
Only having start failure on faulty parts?

# Screenshots
image
image

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.E-5283-ga1a0bf0
 - Graphics version: Tiles
 - Ingame language: Egnlish
 - Mods loaded: "dda", "no_npc_food", "blazeindustries", "crt_expansion", "magiclysm", "DinoMod", alt_map_key", "MMA", "cbm_slots", "fuji_mpp", "speedydex", "stats_through_kills", "StatsThroughSkills"

# Additional context
While I can understand the gear refusing to turn sometimes, its strange to get that message from a damaged, yet not faulty pedal on a bicycle.

### LINKED ISSUE #44504: Randomly grabs and releases bicycle controls on the same button press
# Describe the bug

When I press the "Control Vehicle" hotkey while sitting on this bicycle, it will both grab and release the controls in one button press, but randomly it will work.

# Steps To Reproduce

1. Sit on bike
2. Hit Control Vehicle hotkey (not via examine)
3. If you successfully mount, stop driving, then repeat until it triggers.

# Expected behavior

I expect to reliably be able to grab the controls.

# Screenshots

image

Video of the bug:
https://youtu.be/HO0gHcPu1w8

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909 (Version	10.0.18363 Build 18363) x64
- Game Version: 0.E-6346-g722966a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap]
]

I also edited the hand_axe recipe to require different things but doubt that's relevant.

# Additional context

Save file (i hope, never sent one before)
[Flushing.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5298880/Flushing.zip)

I'm also using a Swedish keyboard layout, but I have tried swapping to the English one, and I also had an extra keybind set so it said "# or ^", but I cleared it and set it to only "#" which is shift+3 for me, and it made no difference.

### PR DESCRIPTION
**Pull request by lancewf**
#### Summary
BugFixes "The Bicycles engine fails to start" 

#### Purpose of change
Fixes #43119
Fixes #44504

To reproduce the bug: 
1. Spawn bicycles until you have one with a badly damaged pedal
2. Use '^' to start riding the bicycle. The response sometimes is that the engine fails start, or that you let go of the controls. If this does not happen, stop riding the bicycle with '^', 'e' and try again. 

#### Describe the solution

The problem was that muscle engines that were damaged were allowed to behave like a combustion engine. The below code shows the problem. The solution was to exclude muscle engines like how electric engines were excluded. 

https://github.com/CleverRaven/Cataclysm-DDA/blob/3446d6cf8a65477e23a371d3f76ee1f41b449deb/src/vehicle_use.cpp#L1056-L1061

#### Testing
Manual testing with the bicycle and unit tests were added.

### CODE REVIEW

File: src/vehicle_use.cpp [hunk 1]
```diff
@@ -1065,7 +1066,7 @@ bool vehicle::start_engine( const int e )
     if( sfx::has_variant_sound( "engine_start", eng.info().get_id().str() ) ) {
         sfx::play_variant_sound( "engine_start", eng.info().get_id().str(),
                                  eng.info().engine_noise_factor() );
-    } else if( is_engine_type( e, fuel_type_muscle ) ) {
+    } else if( einfo.fuel_type == fuel_type_muscle ) {
```
Comment (lancewf) [inline src/vehicle_use.cpp:1069]: Using "einfo.fuel_type == fuel_type_muscle" was better for testing because "is_engine_type" function does not always work.

**Comment by Inglonias** [comment]
I always thought of this failure as "I tried to put my feet on the pedals and they slipped off because the pedals suck"

**Comment by actual-nh** [comment]
> I always thought of this failure as "I tried to put my feet on the pedals and they slipped off because the pedals suck"

A message to that effect could be nice for 0.F-dev.
