### PR TITLE
Can't skin skinless

### LINKED ISSUE #28209: Zombie Dogs are able to be skinned, produce no hides
Issue:
Skinning zombie dogs and rot-weilers produces no skins/hides/furs at all despite being able to skin them through the butchery menu and afterwards even getting messages about successful skinning. After finishing skinning process corpse turns into a skinned one, you can't try to skin again ("corpse is already skinned"), upon further "full butchery" you are getting just fat, meat and butchery refuse, as you normally would, no hide to be seen.

To reproduce:
Make a character, raise survival skill to, for example, 6 level, give character necessary tools (for example, butchering knife and x-octo knife), kill a zombie dog in your nearest town, choose "Skin a corpse" in the butchery menu.

Expected:
Either to get skins from those corpses, OR not being able to skin in the first place due to lack of skin, OR at least not getting a successful messages upon skinning that produces nothing.

WIN10
0.C-37442-gd597d68
Tiles
Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, DDA: Lua, Safe Autodoc, Manual Bionic Installation, Prevent Zombie Revivication, (DP_RP) Xotto Indicators, Alternative Map Key, Classes and Scenarios Mod, Medieval and Historic Content

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Bugfixes "Skinning action no longer available when corpse has no skin to begin with"```
#### Purpose of change

Fixes #28209
and reduces keypresses for butchery when dark.
#### Describe the solution

Checks the harvest list of the mtype related to the item when butchering, and puts that logic into the UI
#### Additional context

The text descriptions in the code were very long, so i broke them up a little bit.

image
image

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -7953,37 +7951,91 @@ static void butcher_submenu( const std::vector<map_stack::iterator> &corpses, in
...
                                        msgFactor ) );
-    smenu.addentry_col( F_DRESS, enough_light, 'f', _( "Field dress corpse" ), cut_time( F_DRESS ),
+    smenu.addentry_col( F_DRESS, enough_light &&
+                        has_organs, 'f', _( "Field dress corpse" ),
+                        enough_light ? ( has_organs ? cut_time( F_DRESS ) : colorize( _( "has no organs" ),
+                                         c_red ) ) : cannot_see,
                         string_format( "%s  %s",
-                                       _( "Technique that involves removing internal organs and viscera to protect the corpse from rotting from inside. Yields internal organs. Carcass will be lighter and will stay fresh longer.  Can be combined with other methods for better effects." ),
+                                       _( "Technique that involves removing internal organs and "
+                                          "viscera to protect the corpse from rotting from inside. "
```
Comment (Qrox) [inline src/game.cpp]:
```suggestion
                                          "viscera to protect the corpse from rotting from inside.  "
```

File: src/game.cpp [hunk 2]
```diff
@@ -7953,37 +7951,91 @@ static void butcher_submenu( const std::vector<map_stack::iterator> &corpses, in
...
+            }
+        }
+    }
+
     uilist smenu;
     smenu.desc_enabled = true;
     smenu.text = _( "Choose type of butchery:" );
 
-    smenu.addentry_col( BUTCHER, enough_light, 'B', _( "Quick butchery" ), cut_time( BUTCHER ),
+    const std::string cannot_see = colorize( _( "can't see!" ), c_red );
```
Comment (Night-Pryanik) [inline src/game.cpp]: Maybe change it to something like "too dark"? Otherwise players might think that there are some problems with their eyes.

Comment (Qrox) [reply src/game.cpp]: Huh, so what happens if the player is boomered etc and actually cannot see? Will they be able to start butchering or is this message displayed?

Comment (KorGgenT) [reply src/game.cpp]: i didn't check with boomered, but i checked with a blindfold.
