### PR TITLE
Feet-related mutations rework

### LINKED ISSUE #29540: Ankle storage items count as boots for Padded Feet
**Describe the bug**  
Wearing Ankle Ammo Pouch, Ankle Sheet and Ankle Holster counts as boots and cancels the 10% movement speed bonus coming from the Padded Feet mutation.

**To Reproduce**  
1. Spawn in the three ankle storage items.
2. Wear either of them.
3. Get Padded Feet mutation.
4. Movement speed stays default, rather than getting the 10% bonus.

**Expected behavior**  
Wearing either of these items should count as being barefoot and should grant the bonus.

**Additional context**  
The soundpack "CDDA-Soundpack" plays the shoe footstep soundfile instead of the barefoot footstep soundfile while wearing either of these three items.

Edit: Also the mutation "Hooves" prevents wearing these items, however they are worn over the ankle and have nothing to do with the anatomy of the feet.

### PR DESCRIPTION
**Pull request by LcsTen**
#### Summary

SUMMARY: Balance "Ankle storage items don't affect feet-related mutations anymore"

#### Purpose of change

Prevent ankle storage items (ankle holster, ankle sheath and ankle ammo pouch) to affect the feet-related mutations (Padded Feet, Roots, Rooter and Tentacle Bracing) by differenciating between shoes/socks/... and items worn at the ankle. Fixes #29540.

#### Describe the solution

The shoes/socks/... and items worn at the ankle are differentiated with the NOT_FOOTWEAR flag.
The function Character::footwear_factor now checks if there are footwear which aren't NOT_FOOTWEAR items.

#### Describe alternatives you've considered

A rather unpopular alternative would be to simply move ankle storage items from feet to legs.

#### Testing

1. Remove the shoes/socks/... you might be wearing
1. Mutate with Padded Feet
1. Check your Base Move Cost (the bonus must apply)
1. Wish for an ankle holster, an ankle sheath and an ankle ammo pouch and wear them all
1. Make sure your Base Move Cost doesn't change (the bonus must still apply)
1. Wear the shoes you worn (or wish for new ones)
1. Make sure your Base Move Cost increased (the bonus must not apply anymore)
1. Remove the shoes you are wearing
1. Mutate with Plant then Rooters
1. Wait for 5 minutes on a Plowable tile
1. Make sure the message "You sink your roots into the soil" appears
1. Wear the shoes your worn and rewait for 5 minutes on a Plowable tile
1. Make sure the message "You sink your roots into the soil" doesn't appear

#### Additional context

As opposed as the issuer told, characters with the Hooves mutation can still wear these items because they suit "abnormally large mutated anatomy".

### CODE REVIEW

**Comment by FuelType-Memes** [comment]
I think you're looking at it from the wrong angle: it's padded feet that need rework, not ankle storage. Maybe add a flag akin to `ALLOWS_NATURAL_ATTACKS` so it doesn't affect feet mutations?

**Comment by LcsTen** [comment]
You're right, I probably overlooked it.

I will try to add a new flag to differentiate the ankle storage items to other items such as socks and shoes, does "DONT_CONNECT_GROUND" sound good?
For now, all the feet-related mutation relies on the Character::footwear_factor, which check if there is any items worn at the feet. I should modify these calls to a new function (maybe Character::ground_factor?), which will check if there is any items worn at the feet which DONT_CONNECT_GROUND.

**Comment by FuelType-Memes** [comment]
Maybe `NOT_FOOTWEAR` ?

**Comment by LcsTen** [comment]
Sounds good, I'll stick with NOT_FOOTWEAR.
Can I edit this PR, or should I rather make a new one? After all, it shifted from "Move ankle storage items from feet to legs" to "Feet-related mutations rework".

**Comment by anothersimulacrum** [comment]
You can edit this one.

File: src/character.cpp [hunk 1]
```diff
@@ -384,6 +384,7 @@ static const std::string flag_SWIMMABLE( "SWIMMABLE" );
 static const std::string flag_SWIM_GOGGLES( "SWIM_GOGGLES" );
 static const std::string flag_UNDERSIZE( "UNDERSIZE" );
 static const std::string flag_USE_UPS( "USE_UPS" );
+static const std::string flag_NOT_FOOTWEAR( "NOT_FOOTWEAR" );
```
Comment (Night-Pryanik) [inline src/character.cpp:387]: Please place it alphabetically.

File: src/character.cpp [hunk 2]
```diff
@@ -9509,7 +9510,7 @@ void Character::update_vitamins( const vitamin_id &vit )
 
 void Character::rooted_message() const
 {
-    bool wearing_shoes = is_wearing_shoes( side::LEFT ) || is_wearing_shoes( side::RIGHT );
+    bool wearing_shoes = ( ground_factor() == 1.0 );
```
Comment (Night-Pryanik) [inline src/character.cpp:9513]: Braces are redundant.

File: src/suffer.cpp [hunk 3]
```diff
@@ -916,7 +916,7 @@ void Character::suffer_from_other_mutations()
                        "insect_wings" );
     }
 
-    bool wearing_shoes = is_wearing_shoes( side::LEFT ) || is_wearing_shoes( side::RIGHT );
+    bool wearing_shoes = ( ground_factor() == 1.0 );
```
Comment (Night-Pryanik) [inline src/suffer.cpp:919]: Here too.

Comment (LcsTen) [reply src/suffer.cpp]: Thank you for your feedback!

**Comment by kevingranade** [comment]
The sole remaining caller of footwear_factor() is also checking for whether leg/foot mutations are unimpeeded by footwear, so all you really need to do here is make footwear_factor() respect the new flag and make sure it's called consistently.

**Comment by LcsTen** [comment]
Good point, I overlooked it for some reasons. I removed the function Character::ground_factor and changed the function Character;:footwear_factor to respect the NOT_FOOTWEAR flag.
Thank you for your feedback.
