### PR TITLE
Special bionic installation messages for Prototype mutants and masochists

### LINKED ISSUE #27664: Bionic installation message without anesthetic kit doesn't make sense for Prototypes
**Describe the bug**  
Bionic installation message without anesthetic kit doesn't make sense for Prototypes.

**To Reproduce**  
1. Became a Prototype (cross threshold in Medical category).
2. Install Sensory Dulling CBM or become Deadened. 
3. Try installing any CBM.
4. Watch how strangely you Prototype feels and behaves: "you stay very, very still, focusing intently on an interesting rock on the ceiling, as the Autodoc slices painlessly into you.  Mercifully, you pass out when the blades reach your line of sight.

**Expected behavior**  
I expect my character as a Prototype to show interest rather than fear, watch the Autodoc with excitement, not pass out and maybe even get a positive morale and a small buff to the first aid.

Why?.. Cause after passing out my character is having a dream of doctors and nurses doing unnatural things to his body, which brings him perverse pleasure. Might be just a dream though...

**Versions and configuration(please complete the following information):**
- OS: Windows 7
- Game Version: 0.C-35552-g52e69d5]
- Graphics version: Tiles
- Mods loaded: dda

**Additional context**
Masochists, Pain Junkies, Cenobites are likely rather to feel sad and sorry about being unable to feel the pain, seem less likely to pass out and if using Sensory Dulling might even delay turning it on to perceive the pain and pass out of pain only.

### PR DESCRIPTION
**Pull request by Firestorm01X2**
Special bionic installation messages for deadended mutants and masochists.

#### Summary

SUMMARY: Bugfixes "Bionic installation message without anesthetic kit doesn't make sense for Prototypes"

#### Purpose of change

Fixes #27664- Bionic installation message without anesthetic kit doesn't make sense for Prototypes

#### Describe the solution

Added special messages for Prototypes, deadned mutants and masochists.

1) Prototypes do not fear operations any more.
"You feel excited, as operation starts.". 
"You feel excited, as the Autodoc slices painlessly into you. View of scalpels slicing you apart was entertaining but as operation proceeded you suddenly felt tired and passed out.  Probably you missed the most interesting part.". 
But not: "You stay very, very still, focusing intently on an interesting rock on the ceiling, as the Autodoc slices painlessly into you.  Mercifully, you pass out when the blades reach your line of sight."

2) Masochists feel slightly sad about missing pain opportunity. 
"Before passing out you've felt sorry for missing wonderful pain from operation process."

Only messages are affected.

#### Describe alternatives you've considered

None.

#### Additional context

Mood changes may be added in future.
But likely it is not worth it:  all "the fun" likely wears off during long operation.

### CODE REVIEW

**Comment by Firestorm01X2** [comment]
Jenkins, rebuild

File: src/bionics.cpp [hunk 1]
```diff
@@ -1543,15 +1548,33 @@ void player::introduce_into_anesthesia( const time_duration &duration, player &i
...
+
         add_msg_if_player( m_mixed,
                            _( "You feel a tiny pricking sensation in your right arm, and lose all sensation before abruptly blacking out." ) );
 
         //post-threshold medical mutants with Deadened don't need anesthesia due to their inability to feel pain
     } else {
+        //post-threshold medical mutants do not fear operations.
+        if( has_trait( trait_THRESH_MEDICAL ) ) {
+            add_msg_if_player( m_mixed,
+                               _( "You feel excited, as the Autodoc slices painlessly into you.  You pass out when the blades reach your line of sight." ) );
```
Comment (Night-Pryanik) [inline src/bionics.cpp]: Don't fears of pain because of Deadened, excited because of Prototype, but still passes out? Why? I guess we need an explanation for this.

Comment (Firestorm01X2) [reply src/bionics.cpp]: Operation is stress for body. So let's go for "suddenly feel tired".

File: src/bionics.cpp [hunk 2]
```diff
@@ -1543,15 +1548,34 @@ void player::introduce_into_anesthesia( const time_duration &duration, player &i
...
+
         add_msg_if_player( m_mixed,
                            _( "You feel a tiny pricking sensation in your right arm, and lose all sensation before abruptly blacking out." ) );
 
         //post-threshold medical mutants with Deadened don't need anesthesia due to their inability to feel pain
     } else {
+        //post-threshold medical mutants do not fear operations.
+        if( has_trait( trait_THRESH_MEDICAL ) ) {
+            add_msg_if_player( m_mixed,
+                               _( "You feel excited, as the Autodoc slices painlessly into you. View of scalpels slicing you apart was entertaining but as operation proceed you suddenly feeling tired and passed out.  Probably you missed most intresting part." ) );
```
Comment (Night-Pryanik) [inline src/bionics.cpp]:
```suggestion
                               _( "You feel excited, as the Autodoc slices painlessly into you. View of scalpels slicing you apart was entertaining but as operation proceeded you suddenly felt tired and passed out.  Probably you missed the most interesting part." ) );
```

File: src/bionics.cpp [hunk 3]
```diff
@@ -1543,15 +1548,34 @@ void player::introduce_into_anesthesia( const time_duration &duration, player &i
...
+
         add_msg_if_player( m_mixed,
                            _( "You feel a tiny pricking sensation in your right arm, and lose all sensation before abruptly blacking out." ) );
 
         //post-threshold medical mutants with Deadened don't need anesthesia due to their inability to feel pain
     } else {
+        //post-threshold medical mutants do not fear operations.
+        if( has_trait( trait_THRESH_MEDICAL ) ) {
+            add_msg_if_player( m_mixed,
+                               _( "You feel excited, as the Autodoc slices painlessly into you. View of scalpels slicing you apart was entertaining but as operation proceeded you suddenly felt tired and passed out.  Probably you missed the most interesting part." ) );
```
Comment (ZhilkinSerg) [inline src/bionics.cpp]:
```suggestion
                               _( "You feel excited, as the Autodoc slices painlessly into you.  View of scalpels slicing you apart was entertaining but as operation proceeded you suddenly felt tired and passed out.  Probably you missed the most interesting part." ) );
```
