### PR TITLE
Fix vents not emitting gas/smoke etc

### LINKED ISSUE #32735: Gas Vents in mines don't work anymore.
# Describe the bug

All the Gas Vents in mines, which used to spread toxic gas, no longer spread anything at all.

# Steps To Reproduce

1. Find a mine.
2. Investigate Gas Vents.
3. They broken.

# Expected behavior

Gas Vents spread big green clouds of unhealthy air.

# Screenshots

Untitled

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5942-g666b2ec [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Flaming Weapons [no_flaming_weapons],
    Bionic Slots [cbm_slots],
    Simplified Nutrition [novitamins]
]

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
SUMMARY: Bugfixes "Fix vents not emitting gas/smoke etc"

#### Purpose of change
Fixes #32735. Vents were not emitting gas/smoke etc because the relevant wandering field property was not finalized.

#### Describe the solution
Finalize all field type objects and fix wrong json key string in the loading code. Also restore the number of intensity levels of vents to 3, as that was the number before the previous field type refactor.

#### Additional context
That const cast is no doubt a bit hacky, but that seems to be what all the current json finalizing methods are doing, such as in `anatomy` and `npc_class`. I'm not sure if it was a hack from the beginning or if it had any design considerations, but some classes loaded using `generic_factory` do not have the `finalize` method (so finalization of objects cannot be done in `generic_factory` without some heavy modification to existing code) so I'm following the `const_cast` approach for now.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
It was intended to get rid of three intensity levels for vent fields with exactly the same settings and leave only one. If some code still expects 3 levels (and thus broken) - that should be changed to use a single intensity level.

File: src/field_type.cpp [hunk 1]
```diff
@@ -176,6 +176,9 @@ void field_types::finalize_all()
 {
     set_field_type_ids();
     all_field_types.finalize();
+    for( const field_type &fd : all_field_types.get_all() ) {
```
Comment (ZhilkinSerg) [inline src/field_type.cpp]: The line above does finalize already.

File: src/field_type.cpp [hunk 2]
```diff
@@ -139,7 +139,7 @@ void field_type::load( JsonObject &jo, const std::string & )
     optional( jo, was_loaded, "accelerated_decay", accelerated_decay, false );
     optional( jo, was_loaded, "display_items", display_items, true );
     optional( jo, was_loaded, "display_field", display_field, false );
-    optional( jo, was_loaded, "wandering_field_id", wandering_field_id, "fd_null" );
+    optional( jo, was_loaded, "wandering_field", wandering_field_id, "fd_null" );
```
Comment (ZhilkinSerg) [inline src/field_type.cpp]: Using of `wandering_field_id` was intentional, so we could finalize later, but json node name should be changed from `wandering_field` to `wandering_field_id`.

File: src/field_type.cpp (hunk 1 above)
Comment (Qrox) [reply src/field_type.cpp]: Except it does not... Otherwise I would not have created this PR. There doesn't seem to be any relevant code that finalizes the objects in `generic_factory::finalize`, either:

https://github.com/CleverRaven/Cataclysm-DDA/blob/2c5d4f789754f2059a5e029e7603617173b5b75f/src/generic_factory.h#L284-L287

I also debugged the game in gdb with a breakpoint set to `field_type::finalize`, and without  this change the breakpoint did not fire.

**Comment by Qrox** [comment]
The intensity level of vents are used to represent the amount of field they should emit, such as here:

https://github.com/CleverRaven/Cataclysm-DDA/blob/2c5d4f789754f2059a5e029e7603617173b5b75f/src/map_field.cpp#L974-L985

The other vents without wandering field also uses the intensity to represent the amount of effect they will produce, so they should not be merged into one level.

File: src/field_type.cpp (hunk 1 above)
Comment (ZhilkinSerg) [reply src/field_type.cpp]: Sorry, you are correct - I've got confused.

**Comment by ZhilkinSerg** [comment]
Thanks for catching that up. While I am not fond of multiple levels for vents, I agree we should restore 3 levels for all vents right now and review what can be refactored later.
