### PR TITLE
Fix inconsistent liquids

### LINKED ISSUE #25056: Frozen toilet water can be poured into plastic bottles
**Describe the bug**  
You can pour water (frozen) from a toilet into a plastic bottle

**To Reproduce**  
Go to a toilet with a plastic bottle press e to examine it, select pour into a container, select plastic bottle.

**Expected behavior**  
Expected to be told, "You cannot pour a frozen liquid into the *item*". i.e. not allowed

Because you can't pour frozen liquids.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-30780-gf121021
 - Graphics version Tiles

Mods loaded
-------------------
Dark Days Ahead
Filthy Clothing
Disable NPC Needs
Simplified Nutrition
Vehicle Additions Pack
Tanks and Other Vehicles
Extended Realistic Guns
-----------------------------

### LINKED ISSUE #25330: Temperature / rot behavior when liquids mixed
When liquids mixed:
- [x] Temperature should average out
- [x] Rot should take on older value

---

### Describe the bug
When two "stacks" of the same liquid at different temperatures are mixed, they take on the temperature of the target stack (container)

### Expected behavior
Temperature should average out when liquids mixed

### To Reproduce

Prepare two sets of
- gallon jug of tea (frozen) (1)
- gallon jug of tea (frozen) (14)

**Test A**
- heat gallon jug of tea (frozen) (1)
- unload gallon jug of tea (frozen) (14) into gallon jug of tea (hot) (1)

Actual Result: gallon jug of tea (hot) (15)

**Test B**
- heat gallon jug of tea (frozen) (14)
- unload gallon jug of tea (hot) (14) into gallon jug of tea (frozen) (1)

Actual Result: gallon jug of tea (frozen) (15)

### LINKED ISSUE #25657: Conflicting behavior when trying to access vehicle water tank in freezing conditions
**Describe the bug**  
I have installed a FOODCO Kitchen Buddy and 60L tank on the same tile, along with a water faucet that I use to access said tank. When using `e` -> `d` to "have a drink", I get the message "You can't drink it while it's frozen." However, I can still use `e` -> `c` and fill containers with this same water.

**To Reproduce**  
1. Vehicle tank and faucet filled with water on a vehicle tile.
2. Using `e` menu, try to drink it directly.
3. Using `e` menu, try to fill a container.

**Expected behavior**  
Both actions should be consistent, either both resulting in frozen message, or both working as normal.

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.C-32136-g66e4d47
 - Graphics version: Tiles
 - Mods loaded: Nothing that is not packaged with base game.

### LINKED ISSUE #25914: Vehicle Tank Refill Error (Debug Error: Tried to reload zero or less charges)
**Summary**
Vehicle menu's refill function does not work.

**Steps to reproduce the behavior**
1. Make a player with frame, 2 60L tanks, tools for installing vehicle parts
2. Make a source of water, or generate gasoline lamps for gasoline.
3. Create a vehicle construction and install 1 60L tank
4. Use other 60L tank as storage for water or gasoline.
5. Enter the vehicle menu of the new vehicle and use the refill function to fill the installed tank with water or gasoline.
6. Either debug error: "Tried to reload with zero or less charges" appears or the game says "You refuel the Car's vehicle tank (60L)," the vehicle's tank is still empty, and the your storage for water or gasoline is untouched.

**Expected behavior**  
The refill function simply did not transfer the source of liquid to the vehicle's tank. However, other ways of refilling vehicle tanks do work, such as Unload item and Refill nearby vehicle functions.

**Screenshot of first encounter of the issue**
cataclysm_ dark days ahead - 0 c-32708-gd1849ee 9_30_2018 12_38_04 pm
 - Graphics version: Tiles
 - Mods loaded:  "dda",
  "no_npc_food",
  "novitamins",
  "filthy_morale",
  "npc_traits",
  "More_Survival_Tools",
  "more_locations",
  "No_Fungi",
  "No_Explosive_Zombies

**Additional context**  
I previously encountered this issue casually and could not fill my workshop's water tanks. However, I noticed the vehicle's tanks can be filled with liquid through the funnel option, and using the Unload option on a storage of any liquid then using the Refill nearby vehicle tank function. This isolated the vague issue from being unable to fill a vehicle tank to the specific issue that the vehicle menu's Refill function does not work.
Since I continuously update my game while playing the same world, I had to recreate this issue in a new world on change #7995 or 0.C-32708-gd1849ee (tiles). Again, I reproduced the same results with a world built on 0.C-32708-gd1849ee (tiles), or change #7995.

### PR DESCRIPTION
**Pull request by alanbrady**
#### Summary
SUMMARY: Bugfixes "Make frozen liquids solid"

#### Purpose of change
The goal here is to attempt to make liquids behave more consistently.

- If you mix two liquids together, the liquid that's poured in just inherits the pour-ees' properties.  E.g. adding hot liquid to frozen liquid will just make more frozen liquid.  This is weird.  This fixes it by averaging the temperatures between liquids.  Likewise for rot, the property is inherited.  This changes it so that it uses the maximum relative rot between liquids.  A future PR may want to add a Y/N confirmation when mixing something rotten with something not rotten because it's going to ruin the non-rotten item.

- We should should also fix frozen liquids to behave as if they were a solid.  This is a bit tricky because phase is dictated by itype.  We have to also be careful not to allow player to pick up frozen liquids (yet) because it still doesn't make sense to be able to do that.

- Now that frozen liquid is solid and cannot be manipulated while in a tank, this also adds some indicators on the vehicle overview screen so the player can know why they can't use their clean water (because it's frozen).

- We should also make E_HEATERs warm up vehicle fluid tanks as well.  While not actually "inside" the car, the residual heat should be warming up the tanks.  (Otherwise dealing with frozen liquid tanks in winter/spring is incredibly aggravating now that they're solid when frozen).

- If you drop liquids on the ground, it's going to make it irreparably dirty, we should indicate this.  An eventual future patch will also make them evaporate over time and maybe even give the player a way to deal with dirty liquids to reuse.

- I noticed I also horrifically broke processing fluid tanks in a previous commit.  Previously I was attempting to etch out a performance optimization in processing tanks but the way I did it is broken and we can do it in a slightly better way.

- There was a regression in #25851 which broke filling vehicles with containers.

#### Describe the solution
To fix mixing liquids, basically you have to boil down the current flags and item_counters into a raw number, average out the raw numbers between liquids (weighting for amount of liquid), then convert it back into flags and item_counters.  It's not super pretty but it works.  To mix rot, it's just a matter of checking which relative rot is greater.

To make frozen liquids solid, this adds a new field to items `current_phase` which is a mutable field vs the immutable itype phase field.  Along with this we need fix places that check for LIQUID phase to check the actual item phase not just the type phase.  Essentially items now inherit the phase from itype as a "room temperature" phase which can then be changed via temperature processing.

To fix fluid tank liquid processing, this removes the turn barrier I added which is broken and instead just makes it check for `is_food_container` before going down the `process` chain.  Things like fuels currently don't care about temperature processing so we should shortcut it sooner if possible.  Additionally the turn barrier is unnecessary here because food processing *already* has a turn barrier.

#### Additional context
Something missing still is the what happens when you mix two unlike liquids together.  I'm not really sure what should happen in this case, but multiple free liquids on the same tile doesn't really make sense.

screenshot from 2018-09-23 18-59-38

Fixes #25657
Fixes #25330
Fixes #25056
Fixes #25914

### CODE REVIEW

**Comment by Rivet-the-Zombie** [comment]
>This is actually sort of a problem since once they are unfrozen you have just a pile of liquid in your inventory.

We could make uncontained liquids in the inventory auto-drop.

**Comment by alanbrady** [comment]
Yeah that's pretty much what I was thinking as well.  We already check for inventory overflow so I'm sure I could chuck it in there somewhere.

**Comment by rubenpd** [comment]
if you wish a uncontained liquid it already drops to the floor the turn after you wished it

**Comment by rubenpd** [comment]
if you wish a uncontained liquid it already drops to the floor the turn after you wished it

**Comment by cake-pie** [comment]
I see you implemented mix rot also, but forgot to mention that in the OP?

**Comment by nexusmrsep** [comment]
What about putting frozen liquid in bottles? I can percieve this to be risky in a way that you might accidentally remove frozen water from container and not being able to put it back, thus losing it on defrost. And second possible issue: frozen liquid defrosting in a not watertight container. Will it escape from it to the ground too?

File: src/character.cpp [hunk 1]
```diff
@@ -1157,8 +1157,24 @@ bool Character::can_use( const item &it, const item &context ) const
...
+        if( it.get_current_phase() == LIQUID ) {
+            const int ipos = get_item_position( &it );
+            i_rem( ipos );
+            g->m.add_item_or_charges( pos(), it );
+            dropped_liquid = true;
+        }
+    }
+
+    if( dropped_liquid ) {
+        add_msg_if_player( "Liquid in your inventory has leaked out onto the ground." );
```
Comment (BevapDin) [inline src/character.cpp]: Needs to be translated.

File: src/character.cpp [hunk 2]
```diff
@@ -1157,8 +1157,24 @@ bool Character::can_use( const item &it, const item &context ) const
...
-{
+void Character::drop_invalid_inventory()
+{
+    bool dropped_liquid = false;
+    const_invslice invref = inv.const_slice();
+    for( const std::list<item> *stack : invref ) {
+        const item &it = stack->front();
+        if( it.get_current_phase() == LIQUID ) {
+            const int ipos = get_item_position( &it );
+            i_rem( ipos );
```
Comment (BevapDin) [inline src/character.cpp]: This needs to be *after* the last usage of `stack` because it removes (and deletes) the object that`stack` points to.
Current accessing `it` below is UB.

Alternatively: `i_rem` returns the removed item, so you can just pass that on to `add_item_or_charges`.

And there is an overload of `i_rem` that takes an item reference and removes the refered item, so you don't need to get the items position yourself, just pass `it` to `i_rem`.

File: src/character.cpp [hunk 3]
```diff
@@ -1157,8 +1157,24 @@ bool Character::can_use( const item &it, const item &context ) const
     return true;
 }
 
-void Character::drop_inventory_overflow()
-{
+void Character::drop_invalid_inventory()
+{
+    bool dropped_liquid = false;
+    const_invslice invref = inv.const_slice();
```
Comment (BevapDin) [inline src/character.cpp]: This does not need to be a separate varaible as it's only used once. You can iterate over the result of `const_slice` directly.

Btw. have you considered using `remove_items_with` and a filter that yields all liquid items instead of all this manual stuff? Something like this:
```C++
const auto items_removed = remove_items( []( const item &it ) { return it.get_current_phase() == LIQUID; } );
if( !items_removed.empty() ) {
    // todo: put the contents of items_removed on the map.
    add_msg("some liquids have been removed");
}
```

File: src/game.cpp [hunk 4]
```diff
@@ -8513,17 +8513,22 @@ bool game::get_liquid_target( item &liquid, item *const source, const int radius
                               const monster *const source_mon,
                               liquid_dest_opt &target )
 {
-    if( !liquid.made_of( LIQUID ) ) {
+    if( item::find_type( liquid.typeId() )->phase == SOLID ) {
```
Comment (BevapDin) [inline src/game.cpp]: You can still access the type of an item directly, it has a `type` member, you don't need to look this up.

File: src/game.cpp [hunk 5]
```diff
@@ -8513,17 +8513,22 @@ bool game::get_liquid_target( item &liquid, item *const source, const int radius
...
         dbg( D_ERROR ) << "game:handle_liquid: Tried to handle_liquid a non-liquid!";
         debugmsg( "Tried to handle_liquid a non-liquid!" );
         // "canceled by the user" because we *can* not handle it.
         return false;
     }
 
+    const std::string liquid_name = liquid.display_name( liquid.charges );
+    if( !liquid.made_of( LIQUID ) ) {
+        add_msg( string_format( _( "%s froze solid before you could finish." ), liquid_name.c_str() ) );
```
Comment (BevapDin) [inline src/game.cpp]: `add_msg` calls `string_format` on its own, you should not do this on your own.

File: src/game.cpp [hunk 6]
```diff
@@ -8513,17 +8513,22 @@ bool game::get_liquid_target( item &liquid, item *const source, const int radius
...
 {
-    if( !liquid.made_of( LIQUID ) ) {
+    if( item::find_type( liquid.typeId() )->phase == SOLID ) {
         dbg( D_ERROR ) << "game:handle_liquid: Tried to handle_liquid a non-liquid!";
         debugmsg( "Tried to handle_liquid a non-liquid!" );
         // "canceled by the user" because we *can* not handle it.
         return false;
     }
 
+    const std::string liquid_name = liquid.display_name( liquid.charges );
```
Comment (BevapDin) [inline src/game.cpp]: Get the name *inside* the `if` block below. You only need it inside that block (which may not even be run at all).

File: src/iexamine.cpp [hunk 7]
```diff
@@ -573,6 +573,8 @@ void iexamine::toilet(player &p, const tripoint &examp)
 
     if( water == items.end() ) {
         add_msg(m_info, _("This toilet is empty."));
+    } else if( water->item_tags.count( "FROZEN" ) ) {
```
Comment (BevapDin) [inline src/iexamine.cpp]: This looks inconsistent. In the code above you used `get_current_phase() == LIQUID`, here you check some item tag. Why the difference? Is there a difference? Why is this not just checking `get_current_phase() != LIQUID`?

File: src/item.cpp [hunk 8]
```diff
@@ -5685,10 +5772,15 @@ void item::fill_with( item &liquid, long amount )
         }
         ammo_set( liquid.typeId(), ammo_remaining() + amount );
     } else if( !is_container_empty() ) {
-        contents.front().mod_charges( amount );
+        // make a copy of the current contents, modify it, then replace current
+        // contents with copy
```
Comment (BevapDin) [inline src/item.cpp]: I can see *what* the code does, but *why* is it done that way. Why is the item in the container not changed directly?

File: src/item.h [hunk 9]
```diff
@@ -696,6 +706,9 @@ class item : public visitable<item>
         /** remove frozen tag and if it takes freezerburn, applies mushy/rotten */
         void apply_freezerburn();
 
+        phase_id get_current_phase() const {
+            return static_cast<phase_id>( current_phase );
```
Comment (BevapDin) [inline src/item.h]: Why is the type of `current_phase` not directly `phase_id`? That would remove the need to cast it here.

File: src/item.h [hunk 10]
```diff
@@ -714,8 +727,25 @@ class item : public visitable<item>
          */
         void calc_temp( const int temp, const float insulation, const time_duration &time );
 
+        /**
+         * Set temperature tags and counter according to a static counter
+         * @param counter Static counter representation of item temperature
```
Comment (BevapDin) [inline src/item.h]: You do not need to write a separate sentence for every parameter. If the function description already explains what the parameter is used for, that's good and enough. This line adds no information and is just redundant clutter.

File: src/veh_interact.cpp [hunk 11]
```diff
@@ -1168,9 +1169,16 @@ bool veh_interact::overview( std::function<bool( const vehicle_part &pt )> enabl
         if( pt.is_tank() && !pt.is_broken() ) {
             auto details = []( const vehicle_part & pt, const catacurses::window & w, int y ) {
                 if( pt.ammo_current() != "null" ) {
+                    std::string specials = "";
```
Comment (BevapDin) [inline src/veh_interact.cpp]: `std::string` is automatically initialized to an empty string, you don't need to do this explicitly.

File: src/veh_interact.cpp [hunk 12]
```diff
@@ -1168,9 +1169,16 @@ bool veh_interact::overview( std::function<bool( const vehicle_part &pt )> enabl
...
+                    const item &it = pt.base.contents.front();
+                    if( it.item_tags.count( "FROZEN" ) ) {
+                        specials += "(frozen)";
```
Comment (BevapDin) [inline src/veh_interact.cpp]: Needs translation, same as below.

File: src/item.h [hunk 13]
```diff
@@ -564,6 +564,16 @@ class item : public visitable<item>
          * @param allow_bucket Allow filling non-sealable containers
          */
         bool is_container_full( bool allow_bucket = false ) const;
+        /**
+         * Mix the rot from one item to another, sets to max relative rot
+         * @param other Item to take temperature from
+         */
+        void mix_rot( const item &other );
```
Comment (BevapDin) [inline src/item.h]: Do we need those `mix_` function to be public and available to all? They are used only at one place. Are you expecting to use them elsewhere? Maybe their code can be used directly instead of having it in separate (and public) functions.

**Comment by alanbrady** [comment]
Thanks for the thorough review @BevapDin will address all those.

File: src/item.h (hunk 9 above)
Comment (alanbrady) [reply src/item.h]: Pretty much because I was lazy and couldn't figure out the json archive io stuff to get it to read a phase_id like an int.  I'll dig through it some more because I hate this too.

File: src/character.cpp (hunk 2 above)
Comment (alanbrady) [reply src/character.cpp]: I even tried to remind myself not to screw this up after seeing your infinite loop patch.  It's just too easy to do.  I like your filter suggestion below, will go with that.

File: src/iexamine.cpp (hunk 7 above)
Comment (alanbrady) [reply src/iexamine.cpp]: Not really any good reason.  I was actually really sad to see how toilet water works and just went with this.  Should probably be a check for SOLID instead, but I think toilets/sinks need to be looked at next in general to be less weird.

File: src/item.cpp (hunk 8 above)
Comment (alanbrady) [reply src/item.cpp]: It seemed good at the time?  I was going off the `else` below that makes a copy of the liquid and assumed it had a good reason but now looking closer at it I understand why it's making a copy of the passed in liquid and why I don't need to do that.

File: src/item.h (hunk 13 above)
Comment (alanbrady) [reply src/item.h]: In my mind at the time it seemed like they might be useful for later.  A follow-up PR is going to fix crafting temperatures such that crafting results inherit the average temperature of their components.  I've thought about it more since and these functions probably aren't necessary there either.  Will fix.

File: src/character.cpp (hunk 3 above)
Comment (alanbrady) [reply src/character.cpp]: Bleh I wanted this to work to make it super easy but the visitable goes digging through containers as well which I don't want to do because then it dumps out all the liquids in all your containers.

**Comment by alanbrady** [comment]
I think I'm pretty much done.  I ended up forbidding picking picking up frozen liquids too because it causes too many weird problems and you can't really do anything with free frozen liquids anyway.  I think the utility will really shine when we have containers that can hold solids, but for now it's better to just forbid picking up them.  I left in the drop invalid inventory changes because you can debug free liquids into your inventory currently and just in case the player does manage to get free liquid in their inventory somehow.

Currently doing some playtesting to try and make sure I didn't miss anything, then I'll call it good.

File: src/advanced_inv.cpp [hunk 14]
```diff
@@ -2136,7 +2136,7 @@ bool advanced_inventory::query_charges( aim_location destarea, const advanced_in
     amount = input_amount;
 
     // Includes moving from/to inventory and around on the map.
-    if( it.made_of( LIQUID ) ) {
+    if( it.type->phase == LIQUID ) {
```
Comment (BevapDin) [inline src/advanced_inv.cpp]: Would be nice if you kept the encapsulation by wrapping this into a function.

Comment (alanbrady) [reply src/advanced_inv.cpp]: I'm not opposed to that.  Thoughts on overloading `made_of` to take an optional boolean 'at_room_temp' or 'from_itype' or something like that?

**Comment by alanbrady** [comment]
Jenkins rebuild

**Comment by alanbrady** [comment]
Jenkins rebuild

**Comment by l29ah** [comment]
B-but how do i get usable liquid from all those frozen toilets if i can't pick it up?
