### PR TITLE
Fixing sizing issues with downsizing/upsizing items and refitting

### LINKED ISSUE #27641: cannot resize some items when you are a small mouse
*SOME* items cannot be downsized (when you are a tiny mouse)
you either get "you wont learn anything form this"  if your skill is high or you will try to resize it forever if you skill is low enough
items tested include: backpacks, scabbard, spear strap, wrist bandolier

**To Reproduce**  
have a small mutation like "unassuming"
obtain a leather backpack
use a sewing kit on it
get sad.

**Expected behavior**  
stuff marked as downsizable in the crafting menu should, in fact, be resizable

**Screenshots**  
image

**Versions and configuration(please complete the following information):**
windows 10, 64bit Tiles
build 8421

### PR DESCRIPTION
**Pull request by MetroidHunter**
#### Summary
SUMMARY: Bugfixes "Fixing sizing issues with downsizing/upsizing when you are smaller/larger size"

#### Purpose of change
Fixes #27641 

#### Describe the solution

- Add ability to query size of item relative to size of character
- Expand descriptions for items when character is various sizes and gear is various sizes, fits or doesnt fit, and is refittable or isnt
- Expanding encumberance penalties for small gear, normal character and normal gear/small character to encompass large gear and large characters and the combinations of small gear and small characters
- Ensuring items can only be downsized/upsized if they actually can be with VARSIZE and the current rules of UNDERSIZED and OVERSIZE

#### Describe alternatives you've considered
There are several alternatives here. The encumberance does not have to be adjusted to consider oversized clothes but then there is a disconnect between the information presented to the player and the actual encumberance differences. It makes sense that gear sized for someone that stands 2 feet tall is nearly impossible to wear for someone who is huge (I imagine 10-12ft)

There are some questions here with things like security glasses or knit scarves. They sort of fall into the category of items like panties/bras etc. but with this rework, they now have encumberance penalities for Huge and Small characters. This makes sense in realism terms as if your head has grown 3 sizes or shrunk 3 sizes, glasses built for a normal human would not fit well.

### Large gear, fits
large_char_large_fits
### Large gear, doesnt fit
large_char_large_gear
### Leather Backpack
large_char_leather_backpack
### Zero encumberance, same across all character sizes
large_char_no_encumberance
### Normal sized gear, cannot be modified
large_char_normal_cannot_refit
### Normal sized gear, doesnt fit
large_char_normal_gear
### Undersized gear
large_char_small_gear

### Leather backpack
normal_char_leather_backpack
### Normal gear, fits
normal_char_normal_fits
### Normal gear, poor fit
normal_char_normal_poor_fit
### Normal gear, cannot be modified
normal_char_normal_static
### Oversized gear
normal_char_oversized
### Undersized gear
normal_char_small_clothes

### Leather Backpack
small_char_leather_backpack
### Normal sized gear, can resize
small_char_normal_can_resize
### Normal sized gear, cannot resize
small_char_normal_cant_resize
### Small sized gear, fits
small_char_small_fits
### Oversized gear
small_char_xl_gear
### A zero encumberance item, same across all character sizes
small_char_zero_enc_item

### CODE REVIEW

**Comment by int-ua** [comment]
Will safety glasses be right size for non-normal player when crafted?

**Comment by MetroidHunter** [comment]
> Will safety glasses be right size for non-normal player when crafted?

No they wont be but that is also existing behavior. At head right now, if you are small and use safety glasses, you will get an encumberance penalty. However, at head right now, if you are huge and use safety glasses, you will not.

The difference now is that instead of the encumberance penalty just happening without any information on it, you are being told that you have an encumberance penalty and, to bring huge and small in line with each other, you now get an encumberance penalty when huge and are also told about it

It may make sense, in a different PR more than likely, to decouple resizing clothes from VARSIZE since the intention there is fit/poor fit and not sizing and add a new flag, DOWNSIZABLE. Then, if present, any clothing that is downsizable would be able to go from normal to small and small to normal and if you are small and you craft gear that is DOWNSIZABLE, then it can automatically be made with UNDERSIZE as a flag on it.

I would say this is beyond the scope of this PR unless the current fix is unacceptable.

**Comment by MetroidHunter** [comment]
@ZhilkinSerg Have you had a chance to review and validate this PR? Is there any feedback on the approach or changes I can make? No rush of course and thank you for all your efforts

**Comment by ZhilkinSerg** [comment]
Didn't test it yet.

**Comment by dissociativity** [comment]
How would this affect a player with near sighted?
Can a mouse make some kind of goggles for it that are adjustable regardless of size due to the implied strap?

**Comment by MetroidHunter** [comment]
It doesnt change any existing constraint on a small character with near sightedness. You at the moment on head will have increased encumberance from the goggles you make or find and will not be told that you cannot downsize it nor that they are too big. This change will now explicitly tell you they are too big and cannot be downsized.

I considered making crafted items be downsized when you craft them or making more items downsizable as outside the scope of this PR but im happy to revisit. The goal was keep scope only to fixing the lack of messaging but I also understand if that now surfaces some issues we may want to address

File: src/item.h [hunk 1]
```diff
@@ -1797,6 +1797,21 @@ class item : public visitable<item>
...
+            human_sized_human_char = 0,
+            big_sized_human_char,
+            small_sized_human_char,
+            big_sized_big_char,
+            human_sized_big_char,
+            small_sized_big_char,
+            small_sized_small_char,
+            human_sized_small_char,
+            big_sized_small_char,
+            not_wearable
```
Comment (codemime) [inline src/item.h]: Yuck! Why explicitly specify all possible combinations? This approach is awkward at best (a pain to maintain).

A character can be either: big, small, or normal sized.
A piece of clothing can be either: undersided, fit, oversized.

These are two natural and well normalized `enum`s.

Comment (MetroidHunter) [reply src/item.h]: I started with that approach and found that it made the implementation harder to maintain. In addition, explicit enums make checks on those enums more straight forward and readable in the actual logic places. The item info method is already in great need of a refactor as is so I chose to move complexity into the enum declaration and out of the use cases.

In order to create constructive dialogue and maintain a level of respect, its a good idea to reframe from using expletives in code reviews.

Comment (codemime) [reply src/item.h]: > In order to create constructive dialogue and maintain a level of respect, its a good idea to reframe from using expletives in code reviews.

I didn't mean to be rude or something. Apologies if it looked that way.

> I started with that approach and found that it made the implementation harder to maintain

Why not introduce a more explicit `enum` along with a function to calculate the difference? This would probably be both more readable and maintainable. Something like:

```c++
switch (armor_size - char_size) {
    case -2:  return armor_fitting::tiny;
    case -1:  return armor_fitting::too_small;
    case 0:   return armor_fitting::okay;
    case 1:   return armor_fitting::too_big;
    case 2:   return armor_fitting::huge;
}
```

Comment (MetroidHunter) [reply src/item.h]: Im very much in favor of an enum like youve outlined and also had an iteration that had a relative size enum like that but, the issue there was in how specific the differences are between being small with variable clothes and being huge with fixed clothes. Since you cannot change huge clothes and cannot upsize small or normal clothes to a huge size, just knowing how the armor fits isnt enough information to tell the user why the armor doesnt fit from an armor sizing stand point and a character size stand point without introducing more complexity in the item info function. With an item info refactor and maybe a harder definition of clothing size vs fit, a relative enum like that may make since. 

In general, DRY is a good principle to follow but in this specific case, even though I also would like a simpler and more elegant enum, doing so just moves the complexity into the places its used. For maintainability, the info function will be modified more often than the enum of clothes or character sizes so we gain some ease with having that function be more straight forward

**Comment by MetroidHunter** [comment]
> Something about this has changed effective encumbrance, causing some unit test failures.
Will fix. I've been unavailable recently but should be ramping back up into development soon

**Comment by MetroidHunter** [comment]
> Something about this has changed effective encumbrance, causing some unit test failures.
The ranged test creates a shooter with a cloak_wool which has 5 encumbrance but is marked OVERSIZE. From my changes in `item::get_encumber_when_containing`, when we calculate encumbrance per item, we double encumberance for oversized items on normal characters now and so the output of:
> ranged_balance.cpp:202: FAILED:
>   REQUIRE( shooter.encumb( bp ) == encumbrance )
> with expansion:
>   10 == 5
> with message:
>   Body Part: torso
is that doubling shown from 10 to 5.  This is working as intended by this PR

The wield time tests all involve the boxing_glove which is also an item that is marked OVERSIZE and so is beholden to the same rules. Instead of an expected encumbrance of 70, we get 140 which gets added to the base cost of handling something (100) to get our 240 moves instead of the expected 170. This is also working as intended for the PR.
> wield_times_test.cpp:24: FAILED:
>   CHECK( move_cost <= max_cost )
> with expansion:
>   240 <= 187

The other tests are the same dealing with the boxing_gloves

> AFAICT these are not intentional changes, so there's a bug somewhere in here that needs fixing.

I see 3 solutions:

1. Remove the penalties for OVERSIZE added here. I think they add some degree of realism to the game and would not particularly want to do that but I do agree that the definitions are loose atm so that might be best.
2. Remove OVERSIZE from the boxing_gloves and wool_coat and also the wedding_veil, which would be to say that these items are not OVERSIZE but the definition of the flag in the system
3. Update the tests to reflect the new OVERSIZE penalty. This would be to say that the items marked OVERSIZE are correct and the boxing_gloves, wool_coat, et al are correct to have this penalty. Optionally, perhaps I should also audit what is marked OVERSIZE and make a note of what OVERSIZE means in this new context so that further items are marked accordingly

What are your thoughts @kevingranade ?

**Comment by kevingranade** [comment]
Sorry I didn't get back to this sooner, I lost track of it.
In short, remove the extra penalty for OVERSIZE.  It wasn't called out in the PR description, I'm not clear on the rationale for it, and I expect items with OVERSIZE to already have an encumbrance penalty assessed if they need it, so the penalty doubles up on it.

**Comment by MetroidHunter** [comment]
> Sorry I didn't get back to this sooner, I lost track of it.
> In short, remove the extra penalty for OVERSIZE. It wasn't called out in the PR description, I'm not clear on the rationale for it, and I expect items with OVERSIZE to already have an encumbrance penalty assessed if they need it, so the penalty doubles up on it.
> 
> Side note: Hooray, the test is working as intended by surfacing unexpected changes.

Hooray indeed!

Also, my bad. The PR description says
> Expanding encumberance penalties for small gear, normal character and normal gear/small character to encompass large gear and large characters and the combinations of small gear and small characters

But I can definitely see how that is not clear what is actually being changed. I will try to be clearer in the future.

I will make these changes now, fix conflicts, and roll out

**Comment by MetroidHunter** [comment]
Gorgon is having trouble accessing its origin remote. Is that expected?

**Comment by ZhilkinSerg** [comment]
> 
> 
> Gorgon is having trouble accessing its origin remote. Is that expected?

That was some temporary issue probably.
