### PR TITLE
Imgui input popups

### LINKED ISSUE #75676: Filter input for ImGui uilist menus shows up behind the menu
### Describe the bug

The user can still filter the menu, but the input box shows up behind the menu. On large menus it is invisible, on narrow ones it is merely obstructed.

### Attach save file

n/a

### Steps to reproduce

1. Open the main menu
2. Type ‘/’ to filter it

### Expected behavior

The input is a `string_input_popup` which has not yet been ported to ImGui.

### Screenshots

Screenshot 2024-08-14 at 11-50-39 uilist issues from migration #74341 · Issue #75661 · CleverRaven_Cataclysm-DDA

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: ad2c7edf6a-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mqrause**
#### Summary
Infrastructure "Imgui input popups"

#### Purpose of change

General imgui migration and I need this for #55503.
Fixes #75676

#### Describe the solution

Make new classes for string and number input popups. The number input is templated to work on any number type (in theory, need to learn more template magic to really enforce that without having to implement `number_input_popup::draw_input_control` for every type we want). Some places don't use `string_input_popup` as a popup but as an integrated element, so I can't simply replace it completely.

When using non-uilist input history, I had to use imgui callback input handling instead of our usual input_context, because imgui's input fields reset the buffer when redrawing while they're the focused element. This is kinda ugly because it mixed two methods of input handling, but I don't see a better solution right now.

notable string input features:
 - description can be forced to monospace (so I can avoid redesigning how descriptions are set and the offending descriptions themselves)
 - can have an actual title bar (but doesn't have to)

notable number input features:
 - +/- buttons, which offer two different step sizes (click or ctrl-click), uses default values from imgui, which is 1/100 for int and disabled for float

Issues that probably won't be addressed in this PR unless required:
- float input always uses system decimal separator instead of the one from the language settings
- a ton of instances left to be migrated
- extra keybinds such as `*` for randomization in world creation world name popup only register when the input field is unfocused

#### Describe alternatives you've considered

Mirroring the code style of the old popup for easier transitioning. But it's the only place in the code base where that style is used and nobody insisted I keep it.

#### Testing

Int and float input is implemented in the settings menu and tested there.
String input is implemented in a few places, mostly tested in world creation world name and V menu item filtering.
Input length limiting tested in auto note menu.

**Not** tested with CJK characters.

#### Additional context

Screenshots slightly outdated since style updates.

float input:
grafik

int input:
grafik

item filter input:
grafik

### CODE REVIEW

File: src/auto_pickup.cpp [hunk 1]
```diff
@@ -517,45 +517,24 @@ void user_interface::show()
...
+                                              "wooden ar*      matches items beginning with wood ar\n"
+                                              "*rrow           matches items ending with rrow\n"
+                                              "*avy fle*fi*arrow     multiple * are allowed\n"
+                                              "heAVY*woOD*arrOW      case insensitive search\n"
+                                              "\n"
+                                              "Pickup based on item materials:\n"
+                                              "m:kevlar        matches items made of Kevlar\n"
+                                              "M:copper        matches items made purely of copper\n"
+                                              "M:steel,iron    multiple materials allowed (OR search)"
+                                          );
```
Comment (db48x) [inline src/auto_pickup.cpp:535]: For anything with a long description I would much rather see them use a custom ImGui window that can use both mono and variable‐width text, columns, colors, and so on.

File: src/input_popup.cpp [hunk 2]
```diff
@@ -0,0 +1,381 @@
...
+            cataimgui::PushMonoFont();
+        }
+        // todo: you should not have to manually split text to print it as paragraphs
+        uint64_t offset = 0;
+        uint64_t pos = 0;
+        while( pos != std::string::npos ) {
+            pos = description.find( "\n", offset );
+            std::string str = description.substr( offset, pos - offset );
+            cataimgui::TextColoredParagraph( description_default_color, str, std::nullopt,
+                                             str_width_to_pixels( width ) );
```
Comment (db48x) [inline src/input_popup.cpp:89]: Just leave off the width to wrap to the available width of the window.

File: src/input_popup.cpp [hunk 3]
```diff
@@ -0,0 +1,381 @@
...
+        flags |= ImGuiInputTextFlags_CallbackHistory;
+    }
+
+    // shrink width of input field if we only allow short inputs
+    float input_width = str_width_to_pixels( max_input_length );
+    if( input_width < ImGui::CalcItemWidth() ) {
+        ImGui::SetNextItemWidth( input_width );
+    }
+
+    ImGui::InputText( "##string_input", text.data(), max_input_length, flags, callback, data );
```
Comment (db48x) [inline src/input_popup.cpp:173]: ImGui comes with a helper function that lets you directly use a `std::string` as an argument here. You’ll have to import the code [from the ImGui repository](https://github.com/ocornut/imgui/blob/master/misc/cpp/imgui_stdlib.cpp), but it does string resizing properly.

File: src/input_popup.cpp [hunk 4]
```diff
@@ -0,0 +1,381 @@
...
+}
+
+void string_input_popup_imgui::set_identifier( const std::string &ident )
+{
+    identifier = ident;
+}
+
+void string_input_popup_imgui::set_text( const std::string &txt )
+{
+    snprintf( text.data(), text.size(), "%s", txt.c_str() );
```
Comment (db48x) [inline src/input_popup.cpp:183]: If you call `set_text` with a string that is longer than `text` can hold, this chops off the end of the input instead of resizing `text`.

**Review by db48x — APPROVED** [review]
Looks great so far, but I do have a couple of suggestions.

File: src/auto_pickup.cpp (hunk 1 above)
Comment (mqrause) [reply src/auto_pickup.cpp:535]: I'd love a flexible solution too, but I don't want to do that in this PR (and honestly don't plan to do it any time soon after it either).

File: src/input_popup.cpp (hunk 3 above)
Comment (mqrause) [reply src/input_popup.cpp:173]: Yes, I've seen that and also tried it out and it seemed to work properly, but @katemonster33 pointed out that casting `std::string::c_str` to non-const to be written to is undefined behavior, so I refrained from adding it.

File: src/input_popup.cpp (hunk 4 above)
Comment (mqrause) [reply src/input_popup.cpp:183]: That is intentional. If we actually want to support inputs >255 chars, we should make a multiline version of the popup.

Comment (db48x) [reply src/input_popup.cpp:183]: Well, ok. I’ll let it stand for now.

**Comment by db48x** [comment]
I sent you a little pull request that makes the UI list use this new input popup. Thanks!

File: src/input_popup.cpp (hunk 3 above)
Comment (katemonster33) [reply src/input_popup.cpp:173]: https://en.cppreference.com/w/cpp/string/basic_string/c_str is what I was referencing when I called it undefined behavior, but data() points to the same piece of memory (or it should) and the only difference is the non-const, it also doesn't have the note about undefined behavior attached to it. If we prefer the imgui_stdlib method then I'm fine with it

Comment (mqrause) [reply src/input_popup.cpp:173]: Made #77979 for this.

**Comment by mqrause** [comment]
There are a couple issues about menus with hidden search/filter inputs, but I didn't check if those menus use the uilist functionality for that, so I'm not sure which will actually fixed by this.

**Comment by moxian** [comment]
I've built this locally and played a bit in a "normal" playthrough (not specifically hunting for bugs), and it works great. The only issue i've ran into is the (indicated in the OP)

>  extra keybinds such as * for randomization in world creation world name popup only register when the input field is unfocused

(this also applies to `CTRL+U: clear line` in the lookaround (`V`) filter. Notably up/down to search history work beautifully). I don't think this is a blocker for merging.

**Comment by mqrause** [comment]
`Ctrl-U` is actually something I only implemented because it was there before. With imgui you can just mark all text and delete as you're used to from other text editors. But I'm not sure if that also works in curses builds, as I can't test that easily, so I decided to keep it around. Alternatively, imgui has the option of binding `Esc` to clearing input, but since we're already using that for completely cancelling the popup, using that would need some slight redesigning I didn't want to do.

As for fixing it, I only see two most likely complicated options:
1. Somehow don't make imgui completely steal inputs when it handles them.
2. Hook our input_context up with imgui so we can let imgui handle our custom keybinds.
