### PR TITLE
Fix MORALE_BOOK Bonuses

### LINKED ISSUE #27496: Cannot read recreational books
**Describe the bug**  
I read a novel or religious text if I have the spiritual trait, I the time for a chapter passes, yet the chapter is not read, no morale gain whatsoever and no messages in the log other than to press 5 or . to stop reading.

Behavior does not change with bookworm or fast reader other than less time passed with fast reader.

**To Reproduce**  
1:create any new character
2:wish in a novel
3:read novel

**Expected behavior**  
Read recreational book: successfully read a chapter, gain morale

**Versions and configuration(please complete the following information):**
 - OS: Windows 8.1
 - Game Version: Self-compiled 8/01/2019 (D/MM/YYYY)
 - Graphics version: Tiles
 - Mods loaded: default, also occurs with PK rebalance and Arcana, mods do not affect it.

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
```SUMMARY: Bugfixes "Fixes morale issues with books"```

#### Purpose of change
Fixes #27496 

#### Describe the solution
Changed the fun bonus from books away from zero and back to what it was supposed to be: The fun value of the book times 5.

#### Describe alternatives you've considered
N/A

#### Additional context
My bad. This should fix things, though.

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -9539,7 +9539,7 @@ void player::do_read( item &book )
 
         if( book_fun_for( book, *learner ) != 0 ) {
             //Fun bonus is no longer calculated here.
-            learner->add_morale( MORALE_BOOK, 0, book_fun_for( book, *learner ) * 5, 6_minutes, 3_minutes, true,
+            learner->add_morale( MORALE_BOOK, book_fun_for( book, *learner ) * 5, book_fun_for( book, *learner ) * 5, 6_minutes, 3_minutes, true,
```
Comment (kevingranade) [inline src/player.cpp]: Is it intentional that the max morale is *5 instead of *15?

Comment (Inglonias) [reply src/player.cpp]: Nope. It sure isn't.
