### PR TITLE
Fix folding stock's unexpected decreased wielding time (fix #19892)

### LINKED ISSUE #19892: Folding stock reduced wield time by ~50%
Folding stock description says it will increase the wield time in exchange for lowering the volume.  After installing a folding stock on my A7 rifle the volume goes down to 1.5 from 3, and the time to wield goes from 810 to 578 to equip and from 810 to 450 unequip to inv.

I can attach a savefile if necessary.

### PR DESCRIPTION
**Pull request by BrettDong**
Issue #19892: A gun with a folding stock attached should take longer to wield because it needs to be unfolded before use, but in game actually it is faster to wield than a plain gun.

The reason is that the decline on wielding time due to the decreased gun volume is more significant than the flag `SLOW_WIELD` penalizes.

In this PR I

1. replace the original `SLOW_WIELD` flag with `NEEDS_UNFOLD` flag to simulate the unfolding process. The penalty time of `SLOW_WIELD` is inversely proportional to the skill level, which is unsuitable for the stock unfolding. It should be linear decreasing, and that's how `NEEDS_UNFOLD` penalizes the player.

2. nerf the folding stock a little bit. The 50% of the entire gun volume except barrel is "collapsed", I assume it's taking a total gun without barrel as a stock, but in reality stock is just one of the parts of a gun except for barrel.

Finally this fixes #19892: for a character with gun skill level at 3, wielding a plain AK-74M takes 24 seconds, and wielding a AK-74M with a folding stock takes 36 seconds.

### CODE REVIEW

**Comment by keyspace** [comment]
Would be good to document the magicnums. That is, why `300` was chosen.

Although this wouldn't happen here, `std::max( <calc>, 0 )`, just to be safe.

As is now, `penalty` can be between 200 and 300. Sounds OK to me.

**Comment by keyspace** [comment]
Might also consider dexterity stat. Stats can go really high, IMO this would make sense for battle-battered characters getting a penalty, not stats-through-skills weirdos getting it easy.

Say (untested!):

```c++
// @magicnum 6 - "low" stat, used in "random character" rolls in newcharacter.cpp
///\EFFECT_DEX reduces unfolding time slightly if high, increases dramatically if low (doubles if at 0)
penalty += p.dex_cur < 6: ( 6 - p.dex_cur ) * ( penalty / 6 ) ? -p.dex_cur * 2;
```

I can submit a PR to `master` later, or one to `BrettDong/foldstock` if this is acceptable.

-----

`has_effect( effect_shakes )` + `has_trait( "JITTERY" )`... Out of scope for this PR.

**Comment by Coolthulhu** [comment]
> // @magicnum 6 - "low" stat, used in "random character" rolls in newcharacter.cpp

Stat-based penalties shouldn't be "centered" around a number. That makes it harder to calculate it without really making it make more sense.
And using dexterity for more ranged-related bonuses doesn't make much sense, as ranged characters want it anyway.

**Comment by keyspace** [comment]
Would need updating `doc/JSON_FLAGS.md` to include this new `NEEDS_UNFOLD` flag. Section "Guns"...

-----

Actually, looking at the docs and doing `grep -E "(COLLAPSIBLE_STOCK|NEEDS_UNFOLD)" data src` reveals that both these flags are only used in `folding_stock` in base `dda` files. So, instead of introducing `NEEDS_UNFOLD`, `COLLAPSIBLE_STOCK` can be used instead!

-----

The only other occurence of `COLLAPSIBLE_STOCK` is in `realguns` mod, `data/mods/realguns/gun.json`, item `m6_asw`. Its description says "designed to fold for compact storage", so can be thought of as "integrated mod" in non-mod terms. Due to having that flag, it also has `SLOW_WIELD`, which could be removed.

-----

I think this is reasonable, and will submit a PR to `BrettDong/foldstock`.

**Comment by keyspace** [comment]
Ping @BorkBorkGoesTheCode and @DangerNoodle - to inform of the new flag that touches their maintained mod.

**Comment by keyspace** [comment]
On the volume changes - here's tables for comparison. Left side is before, right side - after.

Notice how there is no longer a jump when `tmpvol` is 4.

tmpvol | (ml)     | ret -= | ret == | tmpvol | (ml)     | ret -= | ret ==
:---:  | :---:    | :---:  | :---:  | :---:  | :---:    | :---:  | :---:
**3**  | 750      | 0      | 750    | **3**  | 750      | 0      | 750
4      | 1000     | 500    | 500    | 4      | 1000     | 250    |750
**5**  | 1250     | 500    | 750    | **5**  | 1250     | 250    |1000
**6**  | 1500     | 750    | 750    | **6**  | 1500     | 500    |1000
7      | 1750     | 750    | 1000   | 7      | 1750     | 750    |1000
**8**  | 2000     | 1000   | 1000   | 8      | 2000     | 750    |1250
9      | 2250     | 1000   | 1250   | **9**  | 2250     | 750    |1500
10     | 2500     | 1000   | 1500   | 10     | 2500     | 1000   |1500
**11** | 2750     | 1250   | 1500   | 11     | 2750     | 1000   |1750
12     | 3000     | 1250   | 1750   | **12** | 3000     | 1000   |2000
13     | 3250     | 1250   | 2000   | 13     | 3250     | 1250   |2000
14     | 3500     | 1250   | 2250   | 14     | 3500     | 1250   |2250
15     | 3750     | 1250   | 2500   | **15** | 3750     | 1250   |2500
**16** | 4000     | 1500   | 2500   | 16     | 4000     | 1500   |2500
17     | 4250     | 1750   | 2500   | 17     | 4250     | 1500   |2750
18     | 4500     | 1750   | 2750   | 18     | 4500     | 1500   |3000

Having checked this, I now think this PR is OK.

**Comment by DangerNoodle** [comment]
Very well then, can implement this after merging.

**Comment by keyspace** [comment]
@DangerNoodle see 43b8ccf - required change already made.

File: src/item.cpp [hunk 1]
```diff
@@ -2082,6 +2083,13 @@ void item::on_wield( player &p, int mv )
         mv += penalty;
     }
 
+    // weapons with a folding stock
+    if( has_flag( "NEEDS_UNFOLD" ) && !is_gunmod() ) {
+        int penalty = std::max( 0, 300 - p.get_skill_level( gun_skill() ) * 10 );
```
Comment (keyspace) [inline src/item.cpp]: Just noticed: need to check `is_gun()`, like with `SLOW_WIELD` above.

Will work now without it, but if an item that is not a gun is introduced with `NEEDS_UNFOLD`, results might be unexpected.

**Comment by DangerNoodle** [comment]
Oh. In that case no change should be required from me, since I do not have the mod as a separate repository.
