### PR TITLE
Fix recipe search prefixes [RDY]

### LINKED ISSUE #18573: Crafting menu search prefixes don't work
Win 7 bulid ver.  0.C-18865-g595705b (tiles) / bulid 5601

- Unlock all recipes
- bring up crafting menu
- press / and type `c:dehydrated` or `t:hammer` or `s:elec `

It doesn't show any corresponding recipes.

It worked all right in bulid 5579 (i didn't download versions in between )

### PR DESCRIPTION
**Pull request by epsilon-phase**
So, this seems to work for me.

I don't expect that I've handled searching for qualities in a manner that will make internationalization easy, so I'm not convinced that I have that part right.

Otherwise, I've not finished implementing some of the prefixes, and I'm not sure that I've done the matching in the preferred manner.

In any case, any advice would be welcome.

In any case (in case the commit alone doesn't trigger the mention), this fixes #18573.

### CODE REVIEW

File: src/recipe_dictionary.cpp [hunk 1]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
 std::vector<const recipe *> recipe_subset::search( const std::string &txt ) const
 {
     std::vector<const recipe *> res;
-
+    std::vector<std::string> subqueries;
+    std::vector<std::string> requirement_qualities,
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: I'd repeat the definition here and then add a line break after this section. I don't think the continuation declaration adds much in terms of clarity

File: src/recipe_dictionary.cpp [hunk 2]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
...
+        names,
+        components,
+        tools,
+        result_qualities,
+        skills;
+    std::string pattern = txt; //Copy the search string.
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Why do you need this copy?

File: src/recipe_dictionary.cpp [hunk 3]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
...
+    size_t split;
+    if( ( split = pattern.find( ',' ) ) != std::string::npos ) {
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Can you document why this code is required/what it does

File: src/recipe_dictionary.cpp [hunk 4]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
...
+    }
+    for( const auto &query : subqueries ) {
+        if( ( split = query.find( ':' ) ) == std::string::npos ) { //search by name
+            names.push_back( query );
+        } else {
+            switch( query[split - 1] ) { //Find the appropriate key
+                case 'Q'://search by quality
+                    result_qualities.push_back( query.substr( split + 1 ) );
+                    break;
+                case 'q':
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: All other cases have documentation, why not this one?

File: src/recipe_dictionary.cpp [hunk 5]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
...
+            pattern = pattern.substr( split + 1 );
+        }
+    } else {
+        subqueries.push_back( pattern );
+    }
+    for( const auto &query : subqueries ) {
+        if( ( split = query.find( ':' ) ) == std::string::npos ) { //search by name
+            names.push_back( query );
+        } else {
+            switch( query[split - 1] ) { //Find the appropriate key
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Style, one space after `//` comments

File: src/recipe_dictionary.cpp [hunk 6]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
...
+                    tools.push_back( query.substr( split + 1 ) );
+                    break;
+                case 's'://search by skill.
+                    skills.push_back( query.substr( split + 1 ) );
+                    break;
+            }
+        }
+    }
+    auto name_match =
+    [names]( const recipe * r ) {
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Style: lambda capture and arguments should also be on first line

File: src/recipe_dictionary.cpp [hunk 7]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
...
+        return std::any_of( names.begin(), names.end(),
+        [r]( const std::string & name ) {
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Try for the nested lambda on one line maybe? It's quite hard to read this section

File: src/recipe_dictionary.cpp [hunk 8]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
...
+            return lcmatch( item::nname( r->result ), name );
+        } );
+    };
+    auto tools_match =
+    [tools]( const recipe * r ) {
+        return std::any_of( tools.begin(), tools.end(),
+        [r]( const std::string & tool ) {
+            const auto c = r->requirements().get_tools();
+            for( const auto &t : c ) {
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Either documentation (preferred) or less cryptic variable names. A one line comment at the start of each 'task' is often the best approach as opposed to more verbose variable names

File: src/recipe_dictionary.cpp [hunk 9]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
...
+            auto a = item( r->result );
+            return std::any_of( a.type->qualities.begin(),
+                                a.type->qualities.end(),
+            [result_quality]( std::pair<quality_id, int> quality ) {
+                return lcmatch( quality.first->name, result_quality );
+            } );
+        } );
+    };
+    auto requirement_quality_match = [requirement_qualities]( const recipe * r ) {
+        return std::any_of( requirement_qualities.begin(),
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Mismash of indenting levels needs fixing

File: src/recipe_dictionary.cpp [hunk 10]
```diff
@@ -32,10 +32,121 @@ const recipe &recipe_dictionary::get_uncraft( const itype_id &id )
...
+        return std::any_of( skills.begin() , skills.end(),
+        [r]( const std::string & skill ) {
+            return lcmatch( r->required_skills_string(), skill );
+        } );
+    };
     std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ),
-    [ &txt ]( const recipe * r ) {
-        return lcmatch( item::nname( r->result ), txt );
+    [&]( const recipe * r ) {//sadly it seems easier to copy the scope here for the moment
+        return name_match( r ) || tools_match( r ) ||
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: It would be clearer if you moved those earlier named lambdas here as they are used only once and it would help avoid some of your nesting problems

File: src/recipe_dictionary.cpp (hunk 2 above)
Comment (jaked122) [inline src/recipe_dictionary.cpp]: Because I iteratively alter the value in order to make the parsing easier. 

I'd have to change the method declaration to make the copy implicitly.

File: src/recipe_dictionary.cpp (hunk 10 above)
Comment (jaked122) [inline src/recipe_dictionary.cpp]: You think so? Okay.

**Comment by jaked122** [comment]
@mugling, I've fixed (I hope) a lot of your issues with the code.

I've been wondering if you might prefer to do away with this awkward multiple match system, just one flag search at a time was what I was thinking, would you prefer that?

**Comment by mugling** [comment]
I must admit I was wrong about the prefixes (I thought nobody would be using them). But multiple search fields via some domain specific query language sounds very excessive.

**Comment by jaked122** [comment]
@mugling The worst part is that all that complexity doesn't quite do that. It just lets you chain together all of these queries inclusively.

**Comment by mugling** [comment]
Yes, then go with one (typed) search term

**Comment by jaked122** [comment]
@mugling, okay, good, I think I've gotten it working.

File: src/recipe_dictionary.cpp [hunk 11]
```diff
@@ -33,9 +33,57 @@ std::vector<const recipe *> recipe_subset::search( const std::string &txt ) cons
...
+        value = txt.substr( split + 1 );
+    } else {
+        value = txt;
+    }
+
     std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ),
-    [ &txt ]( const recipe * r ) {
-        return lcmatch( item::nname( r->result ), txt );
+    [&]( const recipe * r ) {//sadly it seems easier to copy the scope here for the moment
+        if( key == _( "Q" ) ) { // result quality match
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: i18n isn't a good idea here. Asides from there being no context this won't match the UI description of those options

File: src/recipe_dictionary.cpp [hunk 12]
```diff
@@ -33,9 +33,57 @@ std::vector<const recipe *> recipe_subset::search( const std::string &txt ) cons
 {
     std::vector<const recipe *> res;
 
+    size_t split;
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Could easily go on one line. By any chance did you start programming in C as that's C89 style you're writing there?

File: src/recipe_dictionary.cpp [hunk 13]
```diff
@@ -33,9 +33,57 @@ std::vector<const recipe *> recipe_subset::search( const std::string &txt ) cons
...
+    split = txt.find( ":" );
+    std::string key = "", value;
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: In C++ std::string is always empty by default so you don't need the "" initialization. Also fundamental types can share a declaration but objects should be declared individually (so that if they later acquire parameters you don't need to do too much reformating).

File: src/recipe_dictionary.cpp [hunk 14]
```diff
@@ -33,9 +33,57 @@ std::vector<const recipe *> recipe_subset::search( const std::string &txt ) cons
...
+    if( split != std::string::npos ) {
+        key = txt.substr( 0, split );
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: This all looks a bit weird. Couldn't you just check `txt[1] == ":"` and then `switch( txt[0] )`? Obviously add some bounds checking.

Comment (mugling) [inline src/recipe_dictionary.cpp]: You could even put each of the different search functions inside each `case` statement

File: src/recipe_dictionary.cpp [hunk 15]
```diff
@@ -33,9 +33,57 @@ std::vector<const recipe *> recipe_subset::search( const std::string &txt ) cons
...
+            const auto &result = item( r->result );
+            return std::any_of( result.type->qualities.begin(), result.type->qualities.end(),
+            [value]( const std::pair<quality_id, int> &quality ) {
+                return lcmatch( quality.first->name, value );
+            } );
+        } else if( key == _( "t" ) ) { // tool match
+            const auto &toolsets =
+                r->requirements().get_tools();
+            return std::any_of( toolsets.begin(), toolsets.end(),
+            [value]( const std::vector<tool_comp> &tool_set ) {
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Lambda can probably use reference capture here.

File: src/recipe_dictionary.cpp [hunk 16]
```diff
@@ -33,9 +33,57 @@ std::vector<const recipe *> recipe_subset::search( const std::string &txt ) cons
...
+    } else {
+        value = txt;
+    }
+
     std::copy_if( recipes.begin(), recipes.end(), std::back_inserter( res ),
-    [ &txt ]( const recipe * r ) {
-        return lcmatch( item::nname( r->result ), txt );
+    [&]( const recipe * r ) {//sadly it seems easier to copy the scope here for the moment
+        if( key == _( "Q" ) ) { // result quality match
+            const auto &result = item( r->result );
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Constructing an `item` just to access `type` is very inefficient. You can use `item::find_type` which would be hugely more efficient

File: src/recipe_dictionary.cpp [hunk 17]
```diff
@@ -33,9 +33,57 @@ std::vector<const recipe *> recipe_subset::search( const std::string &txt ) cons
...
+            const auto &req_sets = r->requirements().get_qualities();
+            return std::any_of( req_sets.begin(), req_sets.end(),
+            [value]( const std::vector<quality_requirement> &req_set ) {
+                return std::any_of( req_set.begin(), req_set.end(),
+                [value]( const quality_requirement & qr ) {
+                    return lcmatch( qr.to_string(), value );
+                } );
+            } );
+        } else if( key == _( "c" ) ) { // component match
+            const auto &required_comp = r->requirements().get_components();
```
Comment (mugling) [inline src/recipe_dictionary.cpp]: Is there not an indexed map for this in `recipe_dictionary` that you could instead exploit?

File: src/recipe_dictionary.cpp (hunk 12 above)
Comment (mugling) [inline src/recipe_dictionary.cpp]: Isn't there a FORTRAN joke about removing the O character?

File: src/recipe_dictionary.cpp (hunk 14 above)
Comment (jaked122) [inline src/recipe_dictionary.cpp]: Fair enough. I wanted the search to tolerate spurious spaces. I trust our users might accidentally do that.

File: src/recipe_dictionary.cpp (hunk 17 above)
Comment (jaked122) [inline src/recipe_dictionary.cpp]: Can the indexed map do partial matching? I think partial mapping is somewhat important here.

At least, I really don't think that there's any substring matching we can do here with the sorted map (or an unsorted one).

That's something I want because I prefer being able to search for "string" instead of "long string".

Do you think that its worthwhile?

File: src/recipe_dictionary.cpp (hunk 16 above)
Comment (jaked122) [inline src/recipe_dictionary.cpp]: Can do.

File: src/recipe_dictionary.cpp (hunk 17 above)
Comment (mugling) [inline src/recipe_dictionary.cpp]: I didn't think of the partial matching. Technically you could do a binary search but you're right it's too much work in that case

File: src/recipe_dictionary.cpp (hunk 11 above)
Comment (jaked122) [inline src/recipe_dictionary.cpp]: Sure, that would prevent using it in a switch anyway.

File: src/recipe_dictionary.cpp (hunk 17 above)
Comment (jaked122) [inline src/recipe_dictionary.cpp]: Yeah, it works for some things (as it searches by item id), like rags, but not things like strings. (for which you need string_6)

File: src/recipe_dictionary.cpp (hunk 14 above)
Comment (jaked122) [inline src/recipe_dictionary.cpp]: is that what the trim in `output.h` is?

**Comment by jaked122** [comment]
@mugling, should be good to go, presuming I understood what you meant.

**Comment by AMurkin** [comment]
Maybe indexing all of the items at game init and assign each of them a unique digital identifier would accelerate the search here and in other places. I mean instead of string match. (sorry for my english)

**Comment by mugling** [comment]
> Maybe indexing all of the items at game init and assign each of them a unique digital identifier would accelerate the search here and in other places

To be honest indexing a string is surprisingly efficient (almost comparable to int). I have a reference for that somehere...

**Comment by mugling** [comment]
I separated the parsing and searching stages in 5add2d5
