### PR TITLE
Fix garage door knockback crash

### LINKED ISSUE #34963: Closing Firestation door crashes game
# Describe the bug

Closing Firestation door crashes game.

# Steps To Reproduce

1. Walk to Firestation
2. Close garage door.

# Expected behavior

The game to not crash

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8720-gf7e743c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

My save and logs.

[New folder.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3759920/New.folder.zip)

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Fix garage door knockback crash"```

#### Purpose of change
Fixes #34963 
#### Describe the solution
knockback() was passed two points from from `forced_door_closing()` though in some circumstances, that could pass two identical points, which caused crashes in slope_from() in line.cpp.

Used points_in_radius() instead of the previous rng method, and added checking for two identical points.

#### Describe alternatives you've considered
N/A

#### Testing
I cant actually reproduce the issue myself, but anothersimulacrum and others have been able to and they have tested this change.

#### Additional context
N/A

### CODE REVIEW

**Comment by davidpwbrown** [comment]
Never mind, this was just tested by anothersimulacrum who can repro the crash reliably, and its still crashing for them.

**Comment by davidpwbrown** [comment]
Reopened as @anothersimulacrum has been assisting me with finding the real problem here for the real fix.

File: src/game.cpp [hunk 1]
```diff
@@ -5050,18 +5050,19 @@ bool game::forced_door_closing( const tripoint &p, const ter_id &door_type, int
...
-        const int x_ = x + rng( -1, +1 );
-        const int y_ = y + rng( -1, +1 );
-        if( is_empty( {x_, y_, get_levz()} ) ) {
-            // invert direction, as game::knockback needs
-            // the source of the force that knocks back
-            kbx = -x_ + x + x;
-            kby = -y_ + y + y;
+    for( const tripoint &tmp : m.points_in_radius( p, 2 ) ) {
+        if( is_empty( pt ) ) {
+            const int
```
Comment (anothersimulacrum) [inline src/game.cpp]:
```suggestion
```

**Comment by kevingranade** [comment]
This has a teensy bug, it'll now prefer flinging in specific directions instead of it being random.

**Comment by kevingranade** [comment]
Take a look at random_point() for how to pick a random point filtered by criteria.

**Comment by davidpwbrown** [comment]
yup, added that now.
