### PR TITLE
Minor enhancements to the mission window

### LINKED ISSUE #18751: The list of missions is not scrollable
After completing 20+ missions the list of completed missions overflows... Mission 21 is displayed on top of the bottom border, other missions are not displayed at all (but still can be selected)... I suppose, the lists of active and failed missions behave the same way...
PS: I guess, mission-related bugs are ultra-low priority at this stage...
0.C-19058-g4b775d0 (tiles)

### PR DESCRIPTION
**Pull request by sethsimon**
- Fix erroneous 'You have no...missions'

Suppose, for example, you have 5 active missions and 1 failed mission. If you select the last active mission, then change to the 'failed missions' tab, you'll get the erroneous message. This is fixed by resetting `selection` to 0 whenever you switch tabs.
- Print the deadline in a human-readable format

This was a `todo` in `game::list_missions()`.
- Don't print stuff in the middle of the window

Before, the y-coordinates of the missions's description, deadline, target, etc. were fixed, so there could be a bunch of empty space if there wasn't anything to print on the first couple lines.
- Allow scrolling

This fixes #18751.
- Very minor refactor

I saw an opportunity to eliminate about half a dozen lines of code: `nope` can be a `static const std::string[]`.

### CODE REVIEW

**Comment by illi-kun** [comment]
Ideally it should be extracted into the separate file (```mission_ui.cpp```) because we have a lot of stuff in ```game.cpp```.

**Comment by sethsimon** [comment]
>Ideally it should be extracted into the separate file (`mission_ui.cpp`) because we have a lot of stuff in `game.cpp`.

Good idea. The deed is done.

File: src/mission_ui.cpp [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+#include <string>
+
+
+void game::list_missions()
+{
+    WINDOW *w_missions = newwin( FULL_SCREEN_HEIGHT, FULL_SCREEN_WIDTH,
+                                 ( TERMY > FULL_SCREEN_HEIGHT ) ? ( TERMY - FULL_SCREEN_HEIGHT ) / 2 : 0,
+                                 ( TERMX > FULL_SCREEN_WIDTH ) ? ( TERMX - FULL_SCREEN_WIDTH ) / 2 : 0 );
+
+    int tab = 0;
```
Comment (illi-kun) [inline src/mission_ui.cpp]: Not mandatory for this PR but nice to have thing:
plain numbers are not self-explanatory, so it will be much better to use ```enum``` here. Something like
```
enum mission_tab_mode {
    TAB_ACTIVE,
    TAB_COMPLETED,
    TAB_FAILED
};
```
So lines like ```if( tab != 1 ) {``` becomes to ```if( tab != TAB_COMPLETED ) {``` which is much easier to understand.

Example of this approach is available here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/bionics_ui.cpp#L20

Comment (sethsimon) [inline src/mission_ui.cpp]: I agree. Since I don't see any reason not to do that (the diff already involves every line), I'll look into it.

**Comment by sethsimon** [comment]
This is ready.

**Comment by illi-kun** [comment]
Great! I'm testing it now. BTW, please fix astyling, buildbot isn't happy with the latest changes.

File: src/mission_ui.cpp [hunk 2]
```diff
@@ -0,0 +1,182 @@
...
+        if( selection < umissions.size() ) {
+            const auto miss = umissions[selection];
+            int y = 4;
+            if( !miss->get_description().empty() ) {
+                mvwprintz( w_missions, y++, 31, c_white, "%s", miss->get_description().c_str() );
+            }
+            if( miss->has_deadline() ) {
+                calendar deadline( miss->get_deadline() );
+                std::string dl = string_format( season_name_upper( deadline.get_season() ) + ", day " +
+                                                std::to_string( deadline.days() + 1 ) + " " + deadline.print_time() );
```
Comment (sethsimon) [inline src/mission_ui.cpp]: The deed is done.
