### PR TITLE
Skip water when bringing home logging results

### LINKED ISSUE #71007: NPC camp loggers bring back water
### Describe the bug

When a logger returns, among the items teleported to the center of the camp are puddles of liquid. With a fully built camp center, you get a popup letting you know there's nowhere for it to go.

### Attach save file

[Bellaire-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13956613/Bellaire-trimmed.tar.gz)

### Steps to reproduce

Have puddles of liquid in a forest, send a logger. 

### Expected behavior

No random puddles of liquid being brought along with the wood.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: 2a67568 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved],
    Translate Complex Dialogue [translate_dialogue],
    Alternative Map Key [alt_map_key],
    Bombastic Perks [bombastic_perks],
    Extra Mutated Scenarios [extra_mut_scens]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary

None

#### Purpose of change

Fix #71007, i.e. don't bring back water or liquids from logging expeditions.

#### Describe the solution

Only add items to bring back if they're not liquid in their base phase.

#### Describe alternatives you've considered

None

#### Testing

Testing was done backwards because I'm not 100% sure where logging products are placed when brought back:
- Create a check for the things to exclude when collecting items and make a message stating what item it detected.
- Order a logging expedition, and finding no message.
- Restarted and teleported to that tile, finding there probably aren't any puddles there.
- Walked around a bit to find a puddle.
- Debug spawn gasoline and dumped it.
- Noting the tile I was in and teleported back.
- Ordered logging of that tile and saw messages for two water and one gasoline.
- Restarted, debug shifted time to winter, debug killed a bunch of pesky assassins and a portal storm before being able to actually do something useful.
- Ordered logging of the same tile as before, and noted two messages about water.
- Changed the code to actually exclude the matching items (which meant inverting the various conditions).
- Ordered logging of the same tile, without the game crashing.

Changed the logic to a better one (suggested by @mqrause) and retested:
- Dropped clean water, antiseptic, and gasoline on the tile with a test version with output for all skipped items.
- TP back and order logging.
- Verify the dropped items plus two water were skipped.
- Restarted and moved time to winter.
- TP to the same log location and dropped the same things, noting that the dropped clean water was frozen.
- TP back and order logging.
- Verify the same as above.
- Removed the logs before committing.

### CODE REVIEW

File: src/faction_camp.cpp [hunk 1]
```diff
@@ -4637,16 +4637,18 @@ mass_volume om_harvest_itm( const npc_ptr &comp, const tripoint_abs_omt &omt_tgt
     tripoint mapmax = tripoint( 2 * SEEX - 1, 2 * SEEY - 1, omt_tgt.z() );
     for( const tripoint &p : target_bay.points_in_rectangle( mapmin, mapmax ) ) {
         for( const item &i : target_bay.i_at( p ) ) {
-            total_m += i.weight( true );
-            total_v += i.volume( true );
-            total_num += 1;
-            if( take && x_in_y( chance, 100 ) ) {
-                if( comp ) {
-                    comp->companion_mission_inv.push_back( i );
+            if( i.typeId() != itype_id( "water" ) && !i.made_of( phase_id::LIQUID ) ) {
```
Comment (mqrause) [inline src/faction_camp.cpp:4640]: You might want to consider `item::made_of_from_type` instead of specifically checking for water. That checks for the phase from the item definition independent of the current state of the item.

Comment (PatrikLundell) [reply src/faction_camp.cpp:4640]: Thanks for the quick comment. "!i.made_of_from_type(phase_id::LIQUID)" is what I'm about to test, and the reason I put this into draft. Your comment is a great indicator this is a promising approach.
