### PR TITLE
Avoid error when siphoning from vehicle with an empty tank

### LINKED ISSUE #47803: Activating a hose to siphon fuel gives a debug message
# Describe the bug

When using the `a`ctivate function of a rubber hose near a vehicle with *any* empty tank gives a debug message, `naively asked for first content item and will get a nullptr`

# Steps To Reproduce

1. Get a vehicle having an empty tank installed
2. Get a rubber hose
3. Stand next to the vehicle and `a`ctivate the rubber hose

# Expected behavior

No error

# Screenshots

Full error message:

```
 DEBUG    : naively asked for first content item and will get a nullptr

 FUNCTION : const item &item_contents::legacy_front() const
 FILE     : src/item_contents.cpp
 LINE     : 1144
```

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9865-g0c24435c6b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

Bugfixes "Avoid error when siphoning from vehicle with an empty tank"

#### Purpose of change

Vehicles having an empty fuel tank or other tank were getting a debug message from `contents.legacy_front()` since they did not check for emptiness first.

Fix #47803

#### Describe the solution

Add `vehicle_part::contains_liquid()` to check for emptiness before calling `legacy_front()`, and use that function in `act_vehicle_siphon()`.

#### Describe alternatives you've considered

There may be other code using similar logic for checking vehicle tanks which could now use `contains_liquid` instead, but I did not attempt to refactor those here.

#### Testing

See issue for test steps. Basically, get a vehicle with one of its tanks being empty, then `a`ctivate a hose (rubber hose or garden hose) while adjacent to the vehicle.

There are two use cases - a single-tank vehicle such as a Beetle, and a vehicle with multiple tanks such as a luxury RV.

#### Additional context

Thanks @Jamuro-g for raising the issue and @anothersimulacrum for providing code to fix it.

### CODE REVIEW

File: src/vehicle_part.cpp [hunk 1]
```diff
@@ -530,6 +530,12 @@ bool vehicle_part::is_tank() const
     return base.is_watertight_container();
 }
 
+bool vehicle_part::contains_liquid() const
+{
+    return is_tank() && !base.contents.empty() &&
+           base.contents.legacy_front().made_of( phase_id::LIQUID );
```
Comment (Qrox) [inline src/vehicle_part.cpp:536]:
```suggestion
           base.contents.only_item().made_of( phase_id::LIQUID );
```

Comment (wapcaplet) [reply src/vehicle_part.cpp:536]: OK, I guess this makes sense, since tanks can only hold one kind of liquid.
