### PR TITLE
Acetylene torch fix

### LINKED ISSUE #31877: Acetylene torch doesn't consume charges when activated
# Describe the bug

Acetylene torch doesn't consume charges when used to cut through metal obstacle.

# Steps To Reproduce

1. Obtain acetylene torch
2. Activate it near the closed metal door and target that door
3. Check torch charges

# Expected behavior

Charges are consumed when cutting obstacles.

# Screenshots

N/A
# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-4979-g6a0f1c8
 - Graphics version: Tiles
 - Mods loaded: [ "dda", "no_npc_food", "filthy_morale", "craftgp", "safeautodoc", "aftershock", "realguns", "More_Survival_Tools", "Medieval_Stuff", "makeshift", "modular_turrets", "Salvaged_Robots", "Mining_Mod", "mutant_npcs", "alt_map_key", "cityside", "more_locations", "FujiStruct", "Urban_Development", "boats", "blazemod", "deoxymod", "Tanks", "DP_REMIX_INDICATORS", "EngineeringEssentials", "StatsThroughSkills", "sleepdeprivation", "more_classes_scenarios", "manualbionicinstall" ]

# Additional context

N/A

### PR DESCRIPTION
**Pull request by eilaattwood**
#### Summary
```SUMMARY: Bugfixes "Acetylene torch doesn't consume charges when activated"```
#### Purpose of change
Fixes #31877 - Acetylene torch doesn't consume charges when activated
#### Describe the solution
Removed unnecessary division by 100 (previously used to convert moves to turns, not needed now)
#### Describe alternatives you've considered
None
#### Additional context
None

### CODE REVIEW

File: src/iuse.cpp [hunk 1]
```diff
@@ -4752,33 +4752,33 @@ int iuse::oxytorch( player *p, item *it, bool, const tripoint & )
 
     const ter_id ter = g->m.ter( pnt );
     const auto furn = g->m.furn( pnt );
-    int moves;
+    int turns;
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
    int turns = 0;
```
