### PR TITLE
Change milking to an activity, restore udders on load catchup

### LINKED ISSUE #36826: Cows do not produce milk outside reality bubble
### Expected behavior
Cows milk production catches up when entering reality bubble

### Actual behavior
Cows milk is not produced when out of reality bubble

### Steps to reproduce the behavior
Have cows outside reality bubble
Pass time
Enter reality bubble
No milk

I assume most people keep their cows within reality bubble of their base, however I have a base on a lake and use surrounding islands for farms and livestock. Therefore, I ran into this annoying problem.
I don't think it will cause a performance issue because cows naturally have full milk when spawned.
My survivor needs cheese pls fix :)

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Change milking to an activity, restore udders on load catchup"```

#### Purpose of change
Fixes #36826 

#### Describe the solution
Instead of subtracting moves and adding a timed effect to the cow, turn milking into an interruptable activity.
This now takes around 25 minutes in-game ( as per googling hand-milking cow time tells me ) but the real time it takes is around the same, as before subtracting movs just made the seconds tick by slowly.

also , the udders now refill every day, either oncatchup on load, or in reality bubble, which acts the same as the checking for the effect did in monexamine.cpp  but is more robust now, and potentially ready for NPC milking activities in the future.

also added try_reproduce() and biosig ( poop ) to the monster do turn once_every( 1_days ) check, so now animals can poop and lay eggs whilst in reality bubble too.

#### Describe alternatives you've considered
N/A

#### Testing
I did a lot of milking, teleporting, and waiting. all seems ok.

#### Additional context
N/A

### CODE REVIEW

**Comment by Brian-Otten** [comment]
I feel slightly guilty for sending you off course into this rabbit hole and very thankful that you got it done. Don't have a equal/better understanding of the code than you to do a meaningful review of it but the milking time changes seem perfect.

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -1274,6 +1275,38 @@ void activity_handlers::butcher_finish( player_activity *act, player *p )
...
+    }
+    const auto milked_item = source_mon->ammo.find( "milk_raw" );
+    if( milked_item == source_mon->ammo.end() ) {
+        debugmsg( "animal has no milk ammo type" );
+        return;
+    }
+    item milk( milked_item->first, calendar::turn, milked_item->second );
+    milk.set_item_temperature( 311.75 );
+    if( liquid_handler::handle_liquid( milk, nullptr, 1, nullptr, nullptr, -1, source_mon ) ) {
+        source_mon->ammo["milk_raw"] = 0;
```
Comment (codemime) [inline src/activity_handlers.cpp]: There's already `milked_item->second` for this purpose. It can be made non-const and reused (here and below).

File: src/activity_handlers.cpp [hunk 2]
```diff
@@ -1274,6 +1275,38 @@ void activity_handlers::butcher_finish( player_activity *act, player *p )
...
+    monster *source_mon = dynamic_cast<monster *>( c );
+    if( source_mon == nullptr ) {
+        debugmsg( "could not find source creature for liquid transfer" );
+        return;
+    }
+    const auto milked_item = source_mon->ammo.find( "milk_raw" );
+    if( milked_item == source_mon->ammo.end() ) {
+        debugmsg( "animal has no milk ammo type" );
+        return;
+    }
```
Comment (codemime) [inline src/activity_handlers.cpp]: if wouldn't hurt to also check for `milked_item->second` being greater than zero.

File: src/game.cpp [hunk 3]
```diff
@@ -4109,7 +4109,11 @@ void game::monmove()
         }
 
         m.creature_in_field( critter );
-
+        if( calendar::once_every( 1_days ) ) {
+            critter.refill_udders();
+            critter.try_biosignature();
+            critter.try_reproduce();
```
Comment (codemime) [inline src/game.cpp]: I agree, this is more realistic, but it would also drastically increase the amount of crap if player lingers around for a while (sleeping, crafting). There's already an issue with tedious cleanup (mentioned in #24294). It can become worse.

File: src/monster.h [hunk 4]
```diff
@@ -548,6 +549,7 @@ class monster : public Creature
         cata::optional<time_point> baby_timer;
         bool biosignatures;
         cata::optional<time_point> biosig_timer;
+        time_point udder_timer;
```
Comment (codemime) [inline src/monster.h]: The previous approach (adding an `effect`) was sound. Can it still be used?

File: src/monster.cpp [hunk 5]
```diff
@@ -359,6 +360,28 @@ void monster::try_reproduce()
...
+        debugmsg( "%s is milkable but has no milk in its starting ammo!", get_name() );
+        return;
+    }
+    if( current_milk->second == milked_item->second ) {
+        // already full up
+        return;
+    }
+    if( calendar::turn - udder_timer > 1_days ) {
+        // no point granularizing this really, you milk once a day.
+        ammo["milk_raw"] = milked_item->second;
```
Comment (codemime) [inline src/monster.cpp]: Same thing with `current_milk`.

File: src/monexamine.cpp [hunk 6]
```diff
@@ -668,39 +668,23 @@ void monexamine::tie_or_untie( monster &z )
...
-    const time_duration milking_freq = 1_days / milk_per_day;
-
-    int remaining_milk = milk_per_day;
-    if( source_mon.has_effect( effect_milked ) ) {
-        remaining_milk -= source_mon.get_effect_dur( effect_milked ) / milking_freq;
-    }
-
-    if( remaining_milk > 0 ) {
+    if( milked_item->second > 0 ) {
+        int moves = to_moves<int>( time_duration::from_minutes( milked_item->second / 2 ) );
```
Comment (codemime) [inline src/monexamine.cpp]: Can be made `const`.

File: src/activity_handlers.cpp [hunk 7]
```diff
@@ -1274,6 +1275,38 @@ void activity_handlers::butcher_finish( player_activity *act, player *p )
...
 }
 
+void activity_handlers::milk_finish( player_activity *act, player *p )
+{
+    if( act->coords.empty() ) {
+        debugmsg( "milking activity with no position of monster stored" );
+        return;
+    }
+    const tripoint source_pos = g->m.getlocal( act->coords.at( 0 ) );
+    Creature *c = g->critter_at( source_pos );
```
Comment (BevapDin) [inline src/activity_handlers.cpp]:
```suggestion
    monster *source_mon = g->critter_at<monster>( source_pos );
```
So you don't have to cast it yourself.

File: src/activity_handlers.cpp [hunk 8]
```diff
@@ -1274,6 +1275,38 @@ void activity_handlers::butcher_finish( player_activity *act, player *p )
...
+    milk.set_item_temperature( 311.75 );
+    if( liquid_handler::handle_liquid( milk, nullptr, 1, nullptr, nullptr, -1, source_mon ) ) {
+        source_mon->ammo["milk_raw"] = 0;
+        if( milk.charges > 0 ) {
+            source_mon->ammo["milk_raw"] = milk.charges;
+        } else {
+            p->add_msg_if_player( _( "The %s's udders run dry." ), source_mon->get_name() );
+        }
+    }
+    source_mon->remove_effect( effect_tied );
```
Comment (BevapDin) [inline src/activity_handlers.cpp]: This removes the effect unconditionally, so it gets removed even when the player has manually tied to animal.

The original code had a check for this and would only remove the effect when it was added within that function.

File: src/monster.h (hunk 4 above)
Comment (BevapDin) [reply src/monster.h]: Effects do not progress outside of the reality bubble.

File: src/game.cpp (hunk 3 above)
Comment (davidpwbrown) [reply src/game.cpp]: The amount of crap would be the same as if they had walked away from their farm and then back again, it wouldnt be any more than the usual poop catchup because itd update the biosig timers etc .
whether that same amount of poop appears in real-time or when you come back from a journey shouldnt really change how annoying it is?

File: src/monster.h (hunk 4 above)
Comment (codemime) [reply src/monster.h]: Isn't it fast-forwarded when the player re-enters the reality bubble. If it's not, I'd consider that a bug.

File: src/game.cpp (hunk 3 above)
Comment (codemime) [reply src/game.cpp]: Fair enough.

**Comment by davidpwbrown** [comment]
Ok I shouldn't be deleting the milked effect from effects.json, because that will pop up errors ( harmless ones though ) on load if youve got a milked cow on your save.
Im not at my dev machine right now though, so will get around to it tomorrow.

**Comment by davidpwbrown** [comment]
dammit, rebase mixup
