### PR TITLE
Fix starting a fire with a firewood source

### LINKED ISSUE #31056: Lighting Brazier won't pull from marked firewood source
**Describe the bug**
Attempting to light a brazier will not pull wood from a marked firewood source.

**Steps To Reproduce**
Have nearby activated(placed) Brazier
Have ignition source in inventory
Have nearby marked firewood source
`e`xamine brazier
`f` Start a fire
"You attempt to start a fire with your matchbook..."
"There is nothing to light there."

**Expected behavior**
Game will pull firewood from the marked firewood source, ignite the brazier, and start a fire

**Versions and configuration**
- OS: Windows 10 Pro
- Game Version: 0.D-3795-g0c044d3
- Graphics version: Tiles
- Mods loaded:
"dda",
"no_npc_food",
"growable-pots",
"makeshift",
"Medieval_Stuff",
"More_Survival_Tools",
"nw_pack",
"no_freeze",
"PK_REBALANCE",
"alt_map_key",
"Cata++",
"hydroponics",
"Mining_Mod",
"national_guard_camp_edit",
"more_locations",
"FujiStruct",
"mapgen_demo",
"deoxymod",
"boats",
"Arcana",
"DP_Old_Floor",
"DP_REMIX_INDICATORS",
"cbm_slots",
"Battery_Overhaul_Legacy_Mode",
"manualbionicinstall",
"no_filthy_clothing",
"no_reviving_zombies",
"safeautodoc",
"StatsThroughSkills"

**Additional context**
Save (Including Mods):
[NoFiresourceSave+Mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3244230/NoFiresourceSave%2BMods.zip)

**Screenshot**
Screenshot 2019-06-01 13 45 31

### PR DESCRIPTION
**Pull request by matthemsteger**
#### Summary

```SUMMARY: Bugfixes "Fix starting a fire with a firewood source"```

#### Purpose of change

Fixes #31056 - ```Lighting Brazier won't pull from marked firewood source```

#### Describe the solution

This was broken with #31002 which attempted to fix the problem with the previous logic where the charges were consumed prior to the activity finishing. The activity is complicated in that it runs through code to actually move fuel into the fire, and then check whether there is fuel there to continue. I delayed charge usage until the activity finished instead (which is done by several other activities) and added a comment. I also delayed the practice call and stored the possible number in the index field.

#### Describe alternatives you've considered

My first thought was to decouple the moving items with the notion of checking if there is fuel, but these methods are fairly complex and I did not want to duplicate that code and just delaying the taking of the charge until after the activity seemed better.

#### Additional context

There are some edge cases that are not accounted for, I suppose .. charges that should be taken even if interrupted.

### CODE REVIEW

**Comment by matthemsteger** [comment]
Forgot about astyle again, let me setup my tooling and check

File: src/iuse_actor.cpp [hunk 1]
```diff
@@ -1256,12 +1253,16 @@ int firestarter_actor::use( player &p, item &it, bool t, const tripoint &spos )
         p.mod_moves( -moves );
         return it.type->charges_to_use();
     }
-    p.assign_activity( activity_id( "ACT_START_FIRE" ), moves, -1, p.get_item_position( &it ),
+
+    // skill gains are handled by the activity, but stored here in the index field
+    const int potential_skill_gain =  moves_modifier + moves_cost_fast / 100 + 2;
```
Comment (Night-Pryanik) [inline src/iuse_actor.cpp]:
```suggestion
    const int potential_skill_gain = moves_modifier + moves_cost_fast / 100 + 2;
```
