### PR TITLE
Ensure that a new character's submap is in the center of the map

### LINKED ISSUE #17815: Segfault in scent_map::update
```
(gdb) bt
#0  scent_map::update (this=0x55555661abe0, center=..., m=...) at src/scent_map.cpp:146
#1  0x0000555555a23221 in game::do_turn (this=0x5555565bf040) at src/game.cpp:1451
#2  0x0000555555a3feb2 in main (argc=<optimized out>, argv=0x7fffffffe0a0) at src/main.cpp:469

(gdb) info locals
y = 144
x = 17
scentmap_minx = 18
scentmap_maxx = 98
scentmap_miny = 64
scentmap_maxy = 144
diffusivity = 100

[maxx][maxy] should not exceed [SEEX*MAPSIZE][SEEY*MAPSIZE] (both 132) but its 144, so it explodes with out of bound access.
Comment indicates it should not exceed [2*SCENT_RADIUS+3][2*SCENT_RADIUS+1] (83 and 81, respectively), but clearly this assumption is not true anymore. My build of -Og is too crippled with inlining to get gdb to tell me more usefull things and i cant spot a easy fix.
```

what i did was start a new random scenario in a old world, i got prison break, i started it, i tried to open the gate, it proceeded to give lots of debugmessages about finding nonants or somethings (sorry i wasnt expecting something exciting like a segfault so i didnt note them down) and then boom. Sorry this isnt the most usefull writeup but maybe someone familiar with the code can guess where it took a wrong turn, if its too little info to be usefull feel free to close it.

### PR DESCRIPTION
**Pull request by sethsimon**
Fixes #17815.

If the player's submap is centered, their x and y are between 60 and 71 (inclusive). `scent_map::update` assumes that the player's submap is centered in the map. However, the character who crashed was at (58, 104)- 4 submaps south and 1 submap west of the center.

So the root cause of the crash is that new characters (this doesn't apply to loaded ones) don't get `update_map` called on them until they move.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Are you sure that this will work correctly? Map shifting does some operations on monsters and caches that might not be loaded yet.

**Comment by BevapDin** [comment]
The approach should work, but it should probably be called from `game::start_game` (after `start_location::place_player` has returned). There are a local variables in `start_game` (`omtstart` for example) that refer to the player position and that aren't updated.

When `place_player` moves the player character outside of its original starting point, `omtstart` is now wrong and will reveal the wrong area (slightly off-center). It is also used to call `start_location::burn` (btw. that function could use `g->m` directly).

After calling `place_player`, `omtstart` in `game::start_game` should be recalculated.

**Comment by sethsimon** [comment]
Okay, after work, I'll fix that if I have time.

File: src/start_location.cpp [hunk 1]
```diff
@@ -369,6 +369,10 @@ void start_location::place_player( player &u ) const
         }
     }
 
+    int posx = u.posx();
+    int posy = u.posy();
+    g->update_map( posx, posy ); // The player's submap must be in the center of the map
```
Comment (codemime) [inline src/start_location.cpp]: Can be replaced with just `g->update_map( &u )` (quite similar code inside the function).
Side note: the function should accept references instead of pointers, especially since it's main usage is: `update_map(&...)`

**Comment by sethsimon** [comment]
@BevapDin Couldn't I just make it the last thing that `game::start_game` does before returning?

File: src/start_location.cpp (hunk 1 above)
Comment (sethsimon) [inline src/start_location.cpp]: Somehow I missed the other `update_map`. And since its argument shouldn't ever be null, so I agree that it should be a reference.

**Comment by BevapDin** [comment]
> @BevapDin Couldn't I just make it the last thing that  game::start_game  does before returning?

You mean the call to `update_map`? Yes, that might work.

**Comment by sethsimon** [comment]
>This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.

Jenkins means that my branch has a conflict with master, right? So I should rebase?

**Comment by Coolthulhu** [comment]
You can rebase or merge the current master onto your branch.
Rebase is cleaner, while merging is easier and safer if you don't know what you're doing.

**Comment by sethsimon** [comment]
Okay, thanks.

**Comment by mugling** [comment]
Where are we up to with this?

**Comment by sethsimon** [comment]
@mugling It's ready.
