### PR TITLE
fix issue with charge use of some tools

### LINKED ISSUE #40937: Segfault when firing a flaregun and glowstick dying too fast
# Describe the bug

A. Firing a flare gun raises a SIGSEGV: Segmentation fault.
B. Glowstick goes out after ~10 in game turns.

# Steps To Reproduce

A1. Spawn in a loaded flare gun/obtain a flare gun.
A2. Shoot it anywhere.

B1. Obtain a glowstick.
B1. Activate it.
B2. After around 10-20 turns (12 turns on my tries), it goes out.
B3. Saving, existing and opening the game presents this error:

   DEBUG    : Item glowstick_dead was loaded with charges, but can not have any!

   FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
   FILE     : src/savegame_json.cpp
   LINE     : 2325

# Expected behavior

No SIGSEG crash.

The glowstick should last a couple hours.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2532-gf4bb830 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4699801/logs.zip)

### PR DESCRIPTION
**Pull request by ThePotatomancer**
because of changes in item factory that would add magazine pockets
to any tool with charges, even those without ammo, tools with charges
but no ammo would bug-out and throw debug errors and use up charges
abnormally fast

#### Summary
SUMMARY: None

#### Purpose of change
fixes #40937

#### Describe the solution
added check in check_and_create_magazine_pockets to ignore tools with no ammo types

#### Describe alternatives you've considered
manually adding "fake" ammo to each tool without ammo and removing special code for ammo-less tools and guns

#### Testing
summoned glowsticks, candles and torches and made sure they survive more than a few minutes,
checked that no ammo error are thrown upon loading worlds with dead glowsticks

### CODE REVIEW

**Comment by ThePotatomancer** [comment]
I could this fix the build in the evening. I suspect changing the null check is use is_null() would solve this.
If someone wants to do it earlier feel free

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/candles-nerfed-into-oblivion/23952/2

File: src/item_factory.cpp [hunk 1]
```diff
@@ -2312,8 +2312,9 @@ void Item_factory::check_and_create_magazine_pockets( itype &def )
     if( def.magazines.empty() && !( def.gun || def.magazine || def.tool ) ) {
         return;
     }
-    if( def.pockets.empty() && def.tool && def.tool->max_charges == 0 ) {
-        // if a tool has no max charges, it doesn't need an ammo
+    if( def.pockets.empty() && def.tool &&
+        ( def.tool->max_charges == 0 || def.tool->ammo_id.empty() ) ) {
+        // if a tool has no max charges, it doesn't need an ammo. likewise, if tool has charges but no ammo type it needs no magazine
```
Comment (ZhilkinSerg) [inline src/item_factory.cpp:2317]:
```suggestion
        // If a tool has no max charges, it doesn't need an ammo.
        // Likewise, if tool has charges, but no ammo type it needs no magazine.
```
