### PR TITLE
[RDY] NPCs capable of getting away from live/armed explosives

### LINKED ISSUE #22770: Friendly NPCs will walk towards live grenades I throw
Game version:
7054
Operating system:
Windows (WINE)
Tiles or curses:
Tiles
Mods active:

### Expected behavior
NPC does not move towards the live grenade I just threw even if there are targets for them to melee, moves away if the blast radius might catch them. Anything intelligent enough to recognize a live grenade or other explosive should begin moving away from the potential blast radius once it's thrown.
### Actual behavior
NPC moves towards the live grenade in order to engage in melee combat with monsters I'm trying to blow up, tries to get blown up along with the monsters.
### Steps to reproduce the behavior
Throw a live grenade at monsters your friendly NPC would advance to fight in melee.

### PR DESCRIPTION
**Pull request by codemime**
Closes #22770.
Supersedes #22920 (which is closed).

## Overview

The vector-based approach was implemented here as a first resort (see acbab6a). It had worked fine in the open, but failed hard when it came to obstacles. NPCs rushed in whichever direction they considered safe, and even avoided dangerous fields as they did. However, they were completely ignorant of the surroundings and could easily get stuck in a corner waiting for their doom.

So I replaced the whole thing with the pathfinding-based implementation. It's still quite simple, but NPCs now seem rather intelligent in their explosion-avoidance behavior. They'd also occasionally comment their actions.

## Implementation details

Performance concern that @Coolthulhu outlined in #22920 shouldn't become an issue. This implementation uses the cache of active items (in the `map` class) which was already up and running (see 4fef523). The new code conforms to the existing action-based mechanism. ~I don't like the path estimation here, though. `npc::estimate_path_cost()` essentially duplicates the logic of `npc::move_to()`, but could have used the already-known overall path cost produced by `map::route()`. It doesn't return the cost for now, but it might.~

### CODE REVIEW

File: src/npcmove.cpp [hunk 1]
```diff
@@ -1716,6 +1792,60 @@ static tripoint nearest_passable( const tripoint &p, const tripoint &closest_to
...
+        return;
+    }
+
+    const auto candidate_points = closest_tripoints_first( safe_distance, pos() );
+    int least_danger = std::numeric_limits<int>::max();
+    int cheapest_path = std::numeric_limits<int>::max();
+
+    tripoint best_hideout = pos();
+
+    for( const auto &elem : candidate_points ) {
```
Comment (Coolthulhu) [inline src/npcmove.cpp]: This part could be expensive since there is a lot of overdraw.
Test it with a semi-winding path and 3+ NPCs. If it doesn't chug, then it's fine.
If it does, you could skip the actual pathfinding and just implement "inverse Dijkstra" here. That is, a flood fill with the checks you have here. Then call `update_path` once, at the end.

File: src/npcmove.cpp [hunk 2]
```diff
@@ -263,6 +318,7 @@ void npc::regen_ai_cache()
     ai_cache.danger = 0.0f;
     ai_cache.total_danger = 0.0f;
     ai_cache.my_weapon_value = weapon_value( weapon );
+    ai_cache.live_explosives = find_live_explosives( explosion_avoidance_radius );
```
Comment (Coolthulhu) [inline src/npcmove.cpp]: I'd keep it to friendly NPCs. Consider the following exploit:
* Set C-4 to a year
* Set it by your door
* Go to sleep knowing that no NPC will dare to get near

Comment (codemime) [reply src/npcmove.cpp]: NPCs are now aware of explosion delays and ranges. They would simply ignore the armed explosives that aren't going to explode any time soon. Once it becomes a problem, they sprint away and keep safe distance (which is power-dependent).

File: src/npcmove.cpp (hunk 1 above)
Comment (codemime) [reply src/npcmove.cpp]: > If it doesn't chug, then it's fine.

It didn't, but my computer is a bit far from a toaster. You're right: it might be a problem. So I rewrote the whole thing to be less computationally intensive. I've been testing it with a couple of dozens NPCs in the woods for quite a while. Now it seems to be working fine.

File: src/npcmove.cpp (hunk 2 above)
Comment (Coolthulhu) [reply src/npcmove.cpp]: Sprint? As in actually run faster than walk or just a figure of speech?
Last time I checked, panicked NPCs calmly walked away from things.

File: src/line.cpp [hunk 3]
```diff
@@ -526,92 +526,108 @@ std::vector<point> squares_in_direction( const int x1, const int y1, const int x
...
 
-float rl_vec2d::dot_product (rl_vec2d &v)
+float rl_vec2d::dot_product (rl_vec2d &v) const
 {
     float dot = x * v.x + y * v.y;
     return dot;
 }
 
-float rl_vec3d::dot_product (rl_vec3d &v)
+float rl_vec3d::dot_product (rl_vec3d &v) const
```
Comment (BevapDin) [inline src/line.cpp]: As you're changing the signature of this function anyway: it should take a const reference.

File: src/npcmove.cpp (hunk 2 above)
Comment (codemime) [reply src/npcmove.cpp]: You're right, of course: that was a figure of speech. They don't literally run. I suppose, this should be changed at some point.

File: src/cata_algo.h [hunk 4]
```diff
@@ -0,0 +1,49 @@
...
+ * @brief Sort elements of a sequence by their rating (the smaller the better).
+ *
+ * @param  begin           An iterator (usual meaning).
+ * @param  end             An iterator (usual meaning).
+ * @param  rating_func     A functor which calculates ratings (the outcome
+ *                         must be comparable using '<' operator).
+ *
+ * The rating is calculated only once per each element.
+ *
+ * @return  Nothing.
```
[the remark this answers is not in the document]
Comment (codemime) [reply src/cata_algo.h]: I simply was mimicking the STL way of documenting things. "Since it's a general-purpose function and its signature is similar to `std::sort`'s, why wouldn't I document it similarly?" I thought. BTW `std::sort`'s documentation is a bit funny:
```c++
   *  @param  __first   An iterator.
   *  @param  __last    Another iterator.
```

**Comment by codemime** [comment]
Jenkins, rebuild.
