### PR TITLE
Npc can handle multipe power gen cbm

### LINKED ISSUE #35559: NPC dies when completing CBM installation
# Describe the bug
I tried to install the CBM in the NPC, the first three were installed normally, when the installation of the fourth CBM was finished, the NPC died and an error occurred:
 DEBUG    : NPC Bridget Lacroix, Bone Seer entered infinite loop.  Turning on debug mode
 FUNCTION : void game::monmove()
 FILE     : src/game.cpp
 LINE     : 4259

Upd: NPC dies one turn after
how to wake up from the auto-dock
Upd x2: NPC dies when install Metabolic Interchange or Joint Torsion Ratchet CBM
Upd (again): NPC dies when recharge bionic energy.
I gave her ethanol for recharge bionic energy (Ethanol Burner CBM) and she again dies with the same error (entered infinite loop)

# Versions and configuration

 - OS: Windows 7
 - Game Version: 0.D-9380-ge0332e1 [64-bit]; build: 9903
 - Graphics version: Tiles
 - Mods loaded: 
C.R.I.T Expansion Mod
Disable NPC Needs
Fuji's More Buildings
Icecoon's Arsenal
More Locations
Modular Turrets
SpeedyDex
Vehicle Additions Pack
Tanks and Other Vehicles
DeadLeaves' Fictional Guns

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Bugfixes "Npc can handle multipe power gen cbm"```

#### Purpose of change
Npc can handle multipe power gen cbm
Fixes #35559 
Internal Furnace CBM is NPC useable

#### Describe the solution
Fix `wants_to_recharge_cbm()` and `recharge_cbm()` logic to handle having multiple power gen CBMs
Add "BIONIC_NPC_USABLE" flag to Internal Furnace since it already has code to handle useage by NPCs

#### Testing
Get NPC
Give power bank Mk2, Laser finger, ethanol burner
NPC ask for ethanol,
Give ethanol
NPC refuel CBM
wait
Ethanol Burner turns off
wait
No message, no crash
Spawn Z
NPC shoots Z
Turns ethanol burner on
Power is recharged
Turns ethanol burner off

Install Battery system
No infinite loop
Spawn Z/NPC shoots
NPC ask for battery and turns on ethanol burner
wait 
Power goes up
wait, no complain, no infinite loop

Spawn new NPC
Give power bank and internal furnace
NPC ask for junk
Give plank
NPC recharge 70 kJ with plank
Give another
Same

#### Additional context
NPC will use the first CBM with fuel

### CODE REVIEW

File: src/npcmove.cpp [hunk 1]
```diff
@@ -1644,19 +1644,17 @@ bool npc::wants_to_recharge_cbm()
...
 
-    bool no_fueled_cbm = true;
-    for( const bionic_id bid : get_fueled_bionics() ) {
-        no_fueled_cbm = false;
-        if( get_fuel_available( bid ).empty() ) {
-            return true;
-        } else if( curr_power < max_pow_allowed && !use_bionic_by_id( bid ) ) {
-            return true;
+    if( curr_power < max_pow_allowed ) {
+        for( const bionic_id bid : get_fueled_bionics() ) {
```
Comment (anothersimulacrum) [inline src/npcmove.cpp]:
```suggestion
        for( const bionic_id &bid : get_fueled_bionics() ) {

File: src/npcmove.cpp [hunk 2]
```diff
@@ -1644,19 +1644,17 @@ bool npc::wants_to_recharge_cbm()
...
-            return true;
-        } else if( curr_power < max_pow_allowed && !use_bionic_by_id( bid ) ) {
-            return true;
+    if( curr_power < max_pow_allowed ) {
+        for( const bionic_id &bid : get_fueled_bionics() ) {
+            if( !has_active_bionic( bid ) ) {
+                return true;
+            }
         }
+        return no_fueled_cbm;
```
Comment (BevapDin) [inline src/npcmove.cpp]:
```suggestion
        return get_fueled_bionics().empty();
```
And get rid of the variable. It's only used here.

And why do NPC want to recharge their bionic power if they don't have any fuelled CBMs?

Comment (Fris0uman) [reply src/npcmove.cpp]: bio_furnace and bio_reactor don't use the fuel system but NPC can use them.
