### PR TITLE
Initialize avatar position on game start

### LINKED ISSUE #52300: Crash to desktop if you start too many games
### Describe the bug

If you repeatedly start a character and then die, the game will eventually crash to desktop while creating the world. This typically only occurs if you start multiple characters, one after the other, without quitting out of the game at any point. This crash is intermittent - I have seen it occur in as few as two runs, and as many as 6 to 8, but it does eventually occur unless you quit out of the game before starting a new run.

### Steps To Reproduce

1. Press "Play Now" on the main menu to create a character quickly.
2. Kill your character.
3. Repeat this process until the game crashes with a segfault. This usually occurs on the screen that says "Please wait while we build your world", but I have also seen it occur as a world is resetting because the last character in it has died.

It seems that if the character actually does stuff before they commit suicide, this occurs more quickly.

### Expected behavior

I expect the game to not crash if I'm bad at it. That's just a little silly.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 95019f2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7354977/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7354978/debug.log)

### LINKED ISSUE #52715: Game crashes Segmentation fault
### Describe the bug

Games seems to crash sometimes when creating a new character after the previous dies. 

### Steps To Reproduce

1. Create a new character 
2. Kill the character 
3. Create a new character
4. Repeat until the crash

### Expected behavior

Not crash?

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 46fe95c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    Bionic Slots [cbm_slots]
]

### Additional context

[debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7499536/debug.zip)

### LINKED ISSUE #52720: Game crashes when attempting to create a new character in a world where one died
### Describe the bug

If a character dies in a world, attempting to create a new character in that world causes the game to crash when it finalizes the world.

### Steps To Reproduce

1. Start a character
2. Die
3. Create a new character in the same world
4. ???

### Expected behavior

I suppose I expected the game to not implode when creating a new character.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 3b51b62 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### LINKED ISSUE #53103: Out-of-bounds seen cache array access when starting a new game
### Describe the bug

When starting a new game there is an out-of-bounds array access on `seen_cache` array in `lightmap.cpp`:

https://github.com/CleverRaven/Cataclysm-DDA/blob/d8a51aad1883a5e88e104204f87bc44c661e66cd/src/lightmap.cpp#L989-L990

```
src/lightmap.cpp:990:17: runtime error: index -4768 out of bounds for type 'float [132][132]'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/lightmap.cpp:990:17 in 
    ...
    frame #4: 0x000000010a620ab8 libclang_rt.asan_osx_dynamic.dylib`__ubsan_handle_out_of_bounds_abort + 52
    frame #5: 0x000000010221e934 cataclysm-tiles`map::build_seen_cache(tripoint const&, int) + 4700
    frame #6: 0x00000001024735a0 cataclysm-tiles`map::build_map_cache(int, bool) + 1616
    frame #7: 0x0000000101594050 cataclysm-tiles`game::start_game() + 2976
    frame #8: 0x00000001023bbdb4 cataclysm-tiles`main_menu::new_character_tab() + 5704
    frame #9: 0x00000001023b93e4 cataclysm-tiles`main_menu::opening_screen() + 6812
    frame #10: 0x0000000102398cf8 cataclysm-tiles`main + 7856
    frame #11: 0x00000001a0f89430 libdyld.dylib`start + 4
```

### Steps to reproduce

1. Compile with Address Sanitizer and Undefined Behaviour Sanitizer: `make RELEASE=1 SANITIZE=address,undefined cataclysm -j4`
2. Start a new game by pressing `N` -> `N` [Play Now]
3. Wait for JSON data loading to finish
4. Crash on `"Please wait as we build your world"`

### Expected behavior

Game starts without memory access errors.

### Screenshots

_No response_

### Versions and configuration

- OS: macOS 11.6.1
- Compiler: LLVM Community 13.0.0 ARM64
- Game Version: d8a51aad1883a5e88e104204f87bc44c661e66cd

### Additional context

_No response_

### LINKED ISSUE #53614: Crash when starting world
### Describe the bug

I made a new character for that world and when I tried to load into the world, the game crashed.
I had already played with a character in the same world, it crashed when I created the same character for the second time (after the first one died).

### Steps to reproduce

Create new character, enter world, crash message.

### Expected behavior

Crash shouldn't happen

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 579f907 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7744647/config.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7744650/save.zip)

### LINKED ISSUE #54489: Crash upon starting a new game
### Describe the bug

Started a new game, walked around a bit, realized i chose suboptimal background, suicided;

Started a new game -> preset character -> last character -> tweaked stats a tiny bit (got +nicotine addiction, and +to mechanics; probably irrelevant) -> tab tab tab -> crash. Attached.

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7878052/crash.log)

### Steps to reproduce

Does not reproduce

### Expected behavior

No crash.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 56ae13e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
Bugfixes "Fix out-of-bound memory access on game start"

#### Purpose of change
* Fix #52300
* Fix #52715
* Fix #52720
* Fix #53103
* Fix #53614
* Fix #54489

#### Describe the solution
Initialize avatar position to a sane value (but not equal to origin so `seen cache` is recalculated) to avoid accessing a random address in memory.

#### Testing
Compile with ASan and UBSan. No memory access violation on game start.

#### Additional context
I don't fully understand why avatar position was not initialized before building map caches, and whether there will be any side effect setting avatar position before building map cache in `game::start_game()`. Need feedback from someone who is more familiar with game setup procedure.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -798,6 +798,7 @@ bool game::start_game()
     load_map( lev, /*pump_events=*/true );
 
     int level = m.get_abs_sub().z;
+    u.setpos( tripoint_south );
```
Comment (kevingranade) [inline src/game.cpp:801]: As start_position::place_player() re-invokes cache builds anyway, it should be fine to place the player at an arbitrary position on the map, which tripoint_south does, but just to more closely comply with game invariants, I'd rather stick the player in the central submap instead of in a corner.
```suggestion
    u.setpos( project_to<coords::ms>( omtstart );  );
```

**Comment by kevingranade** [comment]
ugh I'm a dumb, I'll have this fixed in a few minutes.

File: src/game.cpp [hunk 2]
```diff
@@ -798,6 +798,7 @@ bool game::start_game()
     load_map( lev, /*pump_events=*/true );
 
     int level = m.get_abs_sub().z;
+    u.setpos( project_to<coords::ms>( omtstart ) );
```
Comment (kevingranade) [inline src/game.cpp:801]: Whoopsie
```suggestion
    u.setpos( m.getlocal( project_to<coords::ms>( omtstart ) ) );
```

**Comment by BrettDong** [comment]
`map::furn_set` out-of-bounds error in `mx_portal_in()` is unrelated and should be fixed by #54344.

**Comment by BrettDong** [comment]
Tested on Ubuntu Linux 20.04 with GCC 9 Address Sanitizer and Undefined Behavior Sanitizer, no out-of-bounds memory access on game start after the change.

**Comment by Inglonias** [comment]
...this was a one-line fix? It's amazing to me how something so small can be so annoying, but here we are.
