### PR TITLE
fix unloading containers which also have other types of pockets

### LINKED ISSUE #54330: Multi Cooker Battery cannot be changed
### Describe the bug

Multi Cooker has a Battery according to its description. It uses Medium Batteries as Magazines. But you cannot unload the Batteries and reload only offers  liquids to be stored inside the Multicooker.
Unload does not remove the Battery

### Steps to reproduce

Get a Multi Cooker
Make Sure its empty
Try to replace the Battery

### Expected behavior

Being able to unload the Multi Cooker to replace the Battery

### Screenshots

image
image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 96e8d40 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    No Rail Stations [No_Rail_Stations],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

_No response_

### LINKED ISSUE #55481: Unable to unload RC Car
### Describe the bug

`U`nload does not work on the RC car. It does nothing. You can still `r`eload it with nearby batteries, though, so it doesn't block use.

### Steps to reproduce

1. Have an RC car with an ultralight battery (the type it accepts).
2. Attempt to `U`nload the RC car, menu closes, but checking inventory shows it's still got the battery.

### Expected behavior

The battery is removed from the RC car.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 7fa132e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

[McGill.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8099394/McGill.zip)
Here's the save file. I'm standing on the RC car. Just hit `U`nload and pick the RC car. The mods are all stock mods so shouldn't have an issue loading.

### PR DESCRIPTION
**Pull request by maspri**
#### Summary
Bugfixes "fix unloading containers which also have other types of pockets"

#### Purpose of change
fix #55481, fix #54330

#### Describe the solution

If an item has a CONTAINER pocket it is treated as container by *character::unload* and nothing else.

Before, containers with additional multiple pocket types, for example *rc_car* or *multi_cooker*, still had **all** their standard pockets unloaded as a side-effect. This included unloading batteries.

Then pr #53250 changed this to only unloading CONTAINER pockets (which makes sense):
```diff
@@ -9897,7 +9897,7 @@ bool Character::unload( item_location &loc, bool bypass_activity )
         }

         int moves = 0;
-        for( item *contained : it.all_items_top() ) {
+        for( item *contained : it.all_items_top( item_pocket::pocket_type::CONTAINER, true ) ) {
             moves += this->item_handling_cost( *contained );
         }
         assign_activity( player_activity( unload_activity_actor( moves, loc ) ) );
```
However, batteries are now no longer unloaded, causing #55481 and #54330.

The fix in this pr *restores* the old behaviour by explicitly unloading all standard pocket types of a container using the function introduced in pr #53250, maintaining the functionality of the pr. 

#### Describe alternatives you've considered
There could probably be some better refactoring of *character::unload*, but I feel this changes the code as little as possible avoiding regressions. 
There could be unintended side-effects with the originial behaviour, for example if a new gun is added which has a **snack compartment**. This gun would be treated as container and mods with magazines could no longer be unloaded. But until then this should be fine :smiley:

### CODE REVIEW

File: src/activity_actor.cpp [hunk 1]
```diff
@@ -2801,23 +2801,32 @@ void unload_activity_actor::unload( Character &who, item_location &target )
...
         contents_change_handler handler;
         bool changed = false;
-        for( item *contained : it.all_items_top( item_pocket::pocket_type::CONTAINER, true ) ) {
-            int old_charges = contained->charges;
-            const bool consumed = who.add_or_drop_with_msg( *contained, true, &it, contained );
-            if( consumed || contained->charges != old_charges ) {
-                changed = true;
-                handler.unseal_pocket_containing( item_location( target, contained ) );
+
+        for( auto ptype : {
```
Comment (dseguin) [inline src/activity_actor.cpp:2805]:
```suggestion
        for( item_pocket::pocket_type ptype : {
```

File: src/character.cpp [hunk 2]
```diff
@@ -9888,8 +9888,17 @@ bool Character::unload( item_location &loc, bool bypass_activity )
         }
 
         int moves = 0;
-        for( item *contained : it.all_items_top( item_pocket::pocket_type::CONTAINER, true ) ) {
-            moves += this->item_handling_cost( *contained );
+
+        for( auto ptype : {
```
Comment (dseguin) [inline src/character.cpp:9892]:
```suggestion
        for( item_pocket::pocket_type ptype : {
```
