### PR TITLE
Fix mouse overmap navigation while using an isometric non-overmap tileset

### LINKED ISSUE #74455: Mouse overmap navigation while using a isometric non-overmap tileset is borked
### Describe the bug

The fix to #59974 corrected rendering for the overmap when using an isometric non-overmap tileset but mouse movement still seems to think it's isometric or something else funky is going on

### Attach save file

N/A

### Steps to reproduce

1. Enable Ultica_iso
2. Try moving around the overmap with mouse

### Expected behavior

The map cursor to move where I click

### Screenshots

https://github.com/CleverRaven/Cataclysm-DDA/assets/45432782/fb33c4c5-1f10-4ed1-8f29-6d58e2748b66

### Versions and configuration

N/A

### Additional context

I wouldn't be surprised if this is a dupe issue bc it's not remotely new iirc but I can't see one

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
Bugfixes "Fix mouse overmap navigation while using an isometric non-overmap tileset"

#### Purpose of change
Fixes #74455

#### Describe the solution
Applies Qrox's suggested fix on the linked issue

#### Testing
Checked it worked

### CODE REVIEW

File: src/sdltiles.cpp [hunk 1]
```diff
@@ -3968,10 +3968,11 @@ std::optional<tripoint> input_context::get_coordinates( const catacurses::window
     }
 
     const point screen_pos = coordinate - win_min;
+    const bool use_isometric = g->w_overmap ? false : g->is_tileset_isometric();
```
Comment (Qrox) [inline src/sdltiles.cpp:3971]:
```suggestion
    const bool use_isometric = capture_win_ == g->w_overmap ? false : g->is_tileset_isometric();
```
Might be better to check against the argument.
