### PR TITLE
Fix apparently broken infinite water sources

### LINKED ISSUE #17200: Infinite water sources are broken
Infinite water sources nolonger provide `water` and when in range also prevent using any `water` from any finite source.

EDIT: Possibly relates to #17067?

### PR DESCRIPTION
**Pull request by BevapDin**
Each water item from an infinite source is initialized with `item::INFINITE_CHARGES` charges, which is `std::numeric_limits<long>::max()`. When another of those water item is added to the crafting inventory, its charges are added to the existing item. Now what do you get when you add `std::numeric_limits<long>::max()` to `std::numeric_limits<long>::max()`?

Right, undefined behavior. Because it's signed integers.

My tests worked fine because I'm lazy and did not teleport to a river, but used the map editor to create a single deep water tile nearby. And a single infinite water source tile does not trigger the overflow.

Fixes #17200

### CODE REVIEW

**Comment by Coolthulhu** [comment]
This replaces undefined behavior with "less undefined" behavior, though.

Couldn't it just be a special case for the max value instead? It is extremely unlikely that we'll get something evem close to `MAX_LONG / 2` that isn't exactly `MAX_LONG`.

File: src/item.cpp [hunk 1]
```diff
@@ -480,11 +481,19 @@ bool item::merge_charges( const item &rhs )
     if( !count_by_charges() || !stacks_with( rhs ) ) {
         return false;
     }
+    // assumes that charges are always >= 0 (as negative charges make no sense for items counted by charges)
```
Comment (mugling) [inline src/item.cpp]: Slightly misleading, `charges` is always >= 0 for all items irrespective of whether they are counted by charges or not. Any other value is a bug.

**Comment by mugling** [comment]
Agreed, probably best just to special case on `MAX_LONG`

File: src/item.cpp (hunk 1 above)
Comment (codemime) [inline src/item.cpp]: If so, they have to be unsigned in all cases (`size_t` is a good option).

**Comment by BevapDin** [comment]
Testing for `MAX_LONG / 2` is indeed simpler, it has been changed.

> This replaces undefined behavior with "less undefined" behavior, though.

What other undefined behavior did I overlook in my first commit?

**Comment by mugling** [comment]
> What other undefined behavior did I overlook in my first commit?

I'm not sure. Unsigned overflow is well defined so I don't think it would have been that.
