### PR TITLE
discharged smartphone read fix

### LINKED ISSUE #77919: It's possible to read smartphone stored books without battery charge / power connection
### Describe the bug

Player can reed books stored in smartphone when the smartphone battery is dead and the smartphone is disconnected.

### Attach save file

N/A

### Steps to reproduce

1. Store a book into smartphone.
2. Bring the battery to 0, so the smartphone refuses to light up flashlight etc.
3. Read menu > select the book stored.

### Expected behavior

Books stored in electronic device can be only read when the device is operational.

### Screenshots

_No response_

### Versions and configuration

OS: Windows 10 Pro 64-bit 22H2 19045.5131
Game Version: 0f2c155 (tiles)
build 2024-11-15-0512
Ingame Language: Enskt

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SomeName42**
#### Summary
Bugfixes "Fixed able to read books stored in smartphone through the read menu without enough charge to read."

#### Purpose of change

Fixes #77919.

#### Describe the solution

In the read menu if the book is stored in a smartphone it is only displayed if it has enough charge to be read.

#### Testing

I spawned a smart phone using the debug menu and checked that the book only shows in the read menu if the smartphone has enough charge for reading it and doesn't show when it is discharged. I also discovered that when reading the book using the read menu it doesn't consume charges from the smartphone which probably should be fixed in a separate pull request. I also tested that regular books still show in the read menu.

### CODE REVIEW

File: src/game_inventory.cpp [hunk 1]
```diff
@@ -1459,7 +1459,11 @@ class read_inventory_preset: public pickup_inventory_preset
         }
 
         bool is_shown( const item_location &loc ) const override {
-            return loc->is_book() || loc->type->can_use( "learn_spell" );
+            const item_location p_loc = loc.parent_item();
+
+            return ( loc->is_book() || loc->type->can_use( "learn_spell" ) ) &&
+                   ( p_loc.where() == item_location::type::invalid || !p_loc->is_ebook_storage() ||
+                     p_loc->energy_remaining().value() >= 1000000 );
```
Comment (ZhilkinSerg) [inline src/game_inventory.cpp:1466]: I think you can do something like this:

```suggestion
                     p_loc->energy_remaining() >= 1000_kJ );
```

Just replace 1000_kJ with the value that allows reading.

**Comment by jwgrawe** [comment]
It seems that with your added game_inventory.cpp checks, EBOOKREAD items will need a parent item with "energy_remaining" to display any books.
Items without such (e.g. integrated systems using bionic energy, "atomic" items, possibly any principally similar magical item as well) might not allow any ebooks to be read. 

(After testing, I found the Flawless memory item from Bombastic perk to have the same problem as the other related issues above.)

**Comment by SomeName42** [comment]
Thank you for commenting I'll try to fix it

**Comment by SomeName42** [comment]
Created a PR with the fixes: https://github.com/CleverRaven/Cataclysm-DDA/pull/78831
