### PR TITLE
Trade for container without getting traded items back

### LINKED ISSUE #45772: When buying container item it might contain items you paid with
# Describe the bug

Bought a dimensional toolbelt from Forge Lord.
It contained items I paid him with.

# Steps To Reproduce

Spawn Forge Lord (the best to test this specific bug due to the high amount of expensive items and not wearing separate storage items)
Trade high volume of items while buying containers he's wearing/using
The items you paid with will be in the bought container

# Expected behavior

Items traded are only stored in containers after the trade is finished

# Screenshots

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-7886-g76fd581 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

SUMMARY: Bugfixes "Trade for container without getting traded items back"

#### Purpose of change

Fixes #45772

#### Describe the solution
Uses an escrow list of the items traded to the npc to defer transferring the items to npc inventory until after the npc has given items to the player.

Also disabled wielding of the items by the npc to prevent them from dropping the weapon if no inventory space remains.

#### Describe alternatives you've considered

Had made PR #46478 but came to the conclusion that it had irrepairable flaws.

#### Testing

Full test program: no errors.

Traded items to an npc for a leather backpack. Npc kept its traded for items while dropping any excess items on the ground with ownership. Player's traded for items appeared in player inventory. No problems found.

Tested various other trades and noticed no issues.

### CODE REVIEW

File: src/npctrade.cpp [hunk 1]
```diff
@@ -61,8 +64,15 @@ void npc_trading::transfer_items( std::vector<item_pricing> &stuff, player &give
...
 
-        if( ip.charges ) {
-            gift.charges = charges;
+        // Items are moving to escrow.
+        if( use_escrow && ip.charges ) {
+            escrow.emplace_back( gift );
+        } else if( use_escrow ) {
+            for( int i = 0; i < count; i++ ) {
+                escrow.emplace_back( gift );
+            }
```
Comment (BrettDong) [inline src/npctrade.cpp:73]:
```suggestion
            std::fill_n( std::back_inserter( escrow ), count, gift );
```

**Review by BrettDong — APPROVED** [review]
Confirm NPC now drops traded items on the ground instead of giving it back together with container items bought by the player
