### PR TITLE
3D draw point generation

### LINKED ISSUE #69973: You can see what is on top of rooftops from below with 3D FoV
### Describe the bug

You can see the top of roofs whilst e(x)amining from lower than them with 3D FoV.

### Attach save file

[Etta-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13541379/Etta-trimmed.tar.gz)

### Steps to reproduce

 1. Go to a crossroad
 2. e(x)amine
 3. Go at least one z-level higher than the desired rooftop's level
 4. Know exactly where the birds lay their eggs

### Expected behavior

e(x)amining upwards doesn't reveal something above you just because it's lower than where you're looking.

### Screenshots

_From z-level 1 and upward_
z-level1
z-level2
z-level3
z-level4
z-level5
z-level6

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: e1b1331 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Tamable Wildlife [Tamable_Wildlife],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Disable NPC Needs [no_npc_food]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rewryte**
#### Summary
Bugfixes "3D draw point generation"

#### Purpose of change
Tiles draw sprites on screen by generating a draw_point for each grid.  To handle visibility differences on different z-levels in 3D vision, draw_points recalculate their visibility variables on each z-level.  However, there are situations where a grid that should not have a draw_point could inherit a draw_point from the grid above it which would cause the grid to show up as visible when it should not.
Fix #69973

draw_points generation now also includes caching and "occlusion culling" features, replacing my previous code.  Doing these during draw_points generation is not only more efficient, but also substantially reduces code clutter.

#### Describe the solution

- draw_points are now generated separately for each z-level.
- draw_points no longer track the lowest level it should draw.  If a grid should not be drawn, it would not have a draw_point in the first place.
- draw_points, overlay_strings and color_blocks are now cached, which will reduce cpu load per draw.  Visibility variables are contained in draw_points and are no longer cached separately.

#### Describe alternatives you've considered
draw_points are stored in a map within a map (std::map<int, std::map<int, std::vector<tile_render_info>>>).  Not sure if there is a more efficient way of storing the data.

#### Testing
Compiles ok.
Confirmed that #69973 is fixed.
Debug overlays work normally.
Up to 13% faster draw time when displaying multiple z-levels.

### CODE REVIEW

File: src/handle_action.cpp [hunk 1]
```diff
@@ -263,6 +263,10 @@ input_context game::get_player_input( std::string &action )
     const visibility_variables &cache = m.get_visibility_variables_cache();
     const level_cache &map_cache = m.get_cache_ref( u.posz() );
     const auto &visibility_cache = map_cache.visibility_cache;
+#if defined(TILES)
+    // Mark cata_tiles draw caches as dirty
+    tilecontext->set_draw_cache_dirty();
+#endif
```
Comment (Qrox) [inline src/handle_action.cpp:269]: This is already called in the call to `update_visibility_cache` above.

**Review by Qrox — COMMENTED** [review]
Thanks for fixing this!

File: src/cata_tiles.cpp [hunk 2]
```diff
@@ -1446,237 +1410,253 @@ void cata_tiles::draw( const point &dest, const tripoint &center, int width, int
...
-                                                       tile_render_info::vision_effect{ offscreen_type } );
-                    }
-                    continue;
-                }
-            } else {
-                ll = ch.visibility_cache[x][y];
-            }
+    if( here.draw_points_cache_dirty ) {
+        here.draw_points_cache_dirty = false;
+        // overlay_strings and color_blocks are generated with draw_points and thus are cleared together
```
[the remark this answers is not in the document]
Comment (Rewryte) [reply src/cata_tiles.cpp:1415]: Thanks.  Good catches.

File: src/handle_action.cpp (hunk 1 above)
Comment (Rewryte) [reply src/handle_action.cpp:269]: This is a special case for moving the camera.  While it does call `update_visibility_cache`, it doesn't move the player nor flag the visibility cache as dirty and hence the function returns before `set_draw_cache_dirty()` is called.
