### PR TITLE
Fix mishandled limits for items counted by charges

### LINKED ISSUE #14115: Cant drop large amounts of ammo
build:cataclysmdda-0.C-3935 64bit
win 7 64bit

Ok I have 746 .50 BMG Ball ammo in my inventory
If I press d or even D then direction and try to drop it here

http://i.imgur.com/spaRcXT.png

It all falls to the ground.

BUT

If I press D then select just one .50 BMG and dop it on the same sqaure then drop the remaining 745 all is ok?.

http://i.imgur.com/LukAxQe.png

### PR DESCRIPTION
**Pull request by sethsimon**
-Fixes #14115
-Fixes not being able to put 1 nail onto an area with exactly 0 free volume and exactly 99 nails (99 nails have the same volume as 100 nails).
-Fixes not being able to do the aforementioned in the advanced inventory
-Fixes not being able to put 1 nail onto an area with exactly 4096 items and more than 0 nails
-Fixes not being able to do the aforementioned in the advanced inventory

This is achieved by creating an `item::room_for` function. It returns how many of the item (or how many charges if it's counted by charges) could be added given the free volume and the item that's already there that stacks with it. To reduce code duplication between the map and vehicle, a function that calls `item::room_for` has been added to `class item_stack`.

Also,since some functions in `map_stack` and `vehicle_stack` were identical, I moved them to `item_stack`.

### CODE REVIEW

**Comment by sethsimon** [comment]
Since this conflicts with #18189, I am going to put this on hold until that's merged.

File: src/activity_item_handling.cpp [hunk 1]
```diff
@@ -66,6 +66,7 @@ void put_into_vehicle( player &p, const std::list<item> &items, vehicle &veh, in
             continue;
         }
         if( !veh.add_item( part, it ) ) {
+            it.charges -= veh.add_charges( part, it );
```
Comment (codemime) [inline src/activity_item_handling.cpp]: Some items aren't counted by charges. I see than `add_charges()` returns zero in this case, but that's misleading and quite hackish. Also, `item::mod_charges()` is much safer than changing the value directly (not mentioning encapsulation) as it can handle various cases (not-counted-by-charges, infinite charges, negative charges, e.t.c ).

File: src/map.cpp [hunk 2]
```diff
@@ -4450,35 +4385,23 @@ void map::spawn_item(const tripoint &p, const std::string &type_id,
...
 }
 
-units::volume map::max_volume(const tripoint &p)
+units::volume map::max_volume( const tripoint &p )
 {
-    if (has_furn(p)) {
-        return furn( p ).obj().max_volume;
-    }
-    return ter(p).obj().max_volume;
+    return i_at( p ).max_volume();
```
Comment (codemime) [inline src/map.cpp]: Doesn't it ignore `furn_t::max_volume` now?

File: src/activity_item_handling.cpp (hunk 1 above)
Comment (sethsimon) [inline src/activity_item_handling.cpp]: Thanks, I didn't know about `item::mod_charges`.

>Some items aren't counted by charges. I see than add_charges() returns zero in this case, but that's misleading and quite hackish.

Noted.

File: src/advanced_inv.cpp [hunk 3]
```diff
@@ -2040,23 +2040,37 @@ bool advanced_inventory::query_charges( aim_location destarea, const advanced_in
...
-        const long volmax = free_volume / unitvolume;
-        if( volmax <= 0 ) {
+        long room_for;
+        if( it.volume() == 0 ) {
+            // No item should have 0 volume, but I think some of them still do.
+            room_for = item::INFINITE_CHARGES;
+        } else if( !by_charges ) {
+            room_for = free_volume / it.volume();
+        } else {
+            room_for = it.charges_per_volume( free_volume );
```
Comment (BevapDin) [inline src/advanced_inv.cpp]: `charges_per_volume` handles item with 0 volume (returns `INFINITE_CHARGES`) and items not counted by charges (same logic as here). You can replace the whole if-else block with a single call to it.

**Comment by mugling** [comment]
Where are we at with this?

**Comment by mugling** [comment]
> Since this conflicts with #18189, I am going to put this on hold until that's merged.

Appears stalled but could be reopened and resumed now the above PR is merged

**Comment by sethsimon** [comment]
@mugling Sorry for the delay, this is ready as of 997a96851939c12bb1a1f2cb562676c7645087a1. It's not reopened because I lack the permissions.

>`charges_per_volume` handles item with 0 volume (returns INFINITE_CHARGES) and items not counted by charges (same logic as here). You can replace the whole if-else block with a single call to it.

@BevapDin Thanks, I did that. Note that I modified `charges_per_volume` for the reason described in 997a96851939c12bb1a1f2cb562676c7645087a1.

**Comment by mugling** [comment]
> It's not reopened because I lack the permissions.

I always assumed it worked like issues and you could re-open them as easily. I am wrong on that?

**Comment by sethsimon** [comment]
I think so. According to https://help.github.com/articles/repository-permission-levels-for-an-organization/, I can close my issues, but reopening or assigning any issue requires at least write permissions. I think PRs work the same way.

**Comment by mugling** [comment]
Struggling to get through this. A second pair of eyes anyone?

**Comment by BorkBorkGoesTheCode** [comment]
>I think so. According to https://help.github.com/articles/repository-permission-levels-for-an-organization/, I can close my issues, but reopening or assigning any issue requires at least write permissions. I think PRs work the same way.

If a PR or issue is closed by a contributor, it cannot be reopened by the PR writer. You can close and reopen issues and PRs until then.

**Comment by Coolthulhu** [comment]
What's the problem here? Is it ready for testing?

**Comment by mugling** [comment]
Yes, ready for test

**Comment by sethsimon** [comment]
>If a PR or issue is closed by a contributor, it cannot be reopened by the PR writer. You can close and reopen issues and PRs until then. Observed behavior.

@BorkBorkGoesTheCode Thanks so much, it makes perfect sense now.
