### PR TITLE
Minefields spawn fix

### LINKED ISSUE #38289: Minefields don't spawn
# Describe the bug

Though the two no longer exist in the game, auto-notes still marks them as though they are there.

A minefield marked west of a railway station.
image

A minefield marked on the entrance to a farm.
image

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12445-g55cabb7 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi]
]

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Bugfixes "Made "minefield" map extra actually spawn."```

#### Purpose of change
Closes #38289 - Minefields don't spawn.

#### Describe the solution
Previously` minefield` map extra's conditions were so strict that effectively it won't spawn at all. Every `road` overmap terrain had to roll one-in-75 = 1.33% check to decide whether this particular location should spawn map extra at all. If this 1-percent roll succeeded, an attempt to select `mx_minefield` map extra from a set is made. `mx_minefield` has a weight of 80, and there is plenty of other map extras with this weight or even larger in this set. If we're lucky to successfully roll these two checks on a particular road overmap terrain, we then need to check if this OT has a bridge nearby. The resulting chance to successfully all satisfy these three checks was very tiny. So I reworked the conditions to make this map extra actually spawn.

Created a separate `bridge` set of map extras and filled it with `mx_minefield` map extra with 20% chance to spawn on every bridge entry. Updated most coordinates in map extra's mapgen to reflect change from `road` to `bridge` spawning location.

#### Describe alternatives you've considered
None.

#### Testing
Teleported around map to find bridges, checked these bridges' entries for spawning of minefields.

#### Additional context
The chance to spawn (currently 20% per every bridge entry) could be lowered or increased if needed.

Thanks @ralreegorganon for looking into matter of this issue and explaining me how to fix it.

### CODE REVIEW

**Comment by jbytheway** [comment]
Hopefully the test in `map_extra_test` now passes reliably?  If so, please remove the `[!mayfail]` tag therefrom.

**Comment by Night-Pryanik** [comment]
Yes, test passes now. Updated tests file, removed theoretical spawn case.

**Comment by ralreegorganon** [comment]
I don't see a reason to nuke the `mx_minefield theorertical spawn` case--just update the setup in it so that it sets up a valid case again, reflecting the changes you made for it to pass.

File: tests/map_extra_test.cpp [hunk 1]
```diff
@@ -5,31 +5,23 @@
...
-    find_params.types = {{"road", ot_match_type::type}};
+    find_params.types = {{"bridge", ot_match_type::type}};
     find_params.search_range = 180;
-    const std::vector<tripoint> roads = overmap_buffer.find_all( origin, find_params );
+    const std::vector<tripoint> bridges = overmap_buffer.find_all( origin, find_params );
 
-    // The rest of this check is pointless if there are no roads.
-    REQUIRE( roads.size() > 0 );
+    // The rest of this check is pointless if there are no bridges.
+    REQUIRE( bridges.size() > 0 );
```
Comment (jbytheway) [inline tests/map_extra_test.cpp]: Please change to `!bridges.empty()` otherwise clang-tidy will be sad.
