### PR TITLE
Fixed Advanced Microreactor CBM not being installable

### LINKED ISSUE #24494: Advanced Microreactor CBM can't be installed
This bug seems to be caused by special conditions set up for installing the Internal Microreactor CBM, the Microreactor Upgrade CBM, and the Advanced Microreactor CBM.

For context: The Internal Microreactor is the base version of this bionic. The Microreactor Upgrade CBM will upgrade the base version into the Advanced Microreactor. Lastly, it's possible to just create and install the Advanced Microreactor CBM to go straight to the upgraded microreactor.

The Advanced Microreactor CBM has an upgraded_bionic field to indicate that it's an upgraded version of the Internal Microreactor, so you can't install them together. However, the following line treats this as if it were _upgrading_ the Internal Microreactor rather than being _an upgrade to_ the bionic. This condition should be permitting the install under the conditions set, but currently it denies it.
https://github.com/CleverRaven/Cataclysm-DDA/blob/bf95129b57ab8798b74dcc6700bd43344dda4727/src/iexamine.cpp#L3536

### PR DESCRIPTION
**Pull request by KnightosMaster**
#### Summary
```SUMMARY: Bugfixes "Fixed Advanced Microreactor CBM not being installable."```  

#### Purpose of change
Fixes #24494

#### Describe the solution
Added the "is_upgrade" field to CBMs. It is used if a CBM upgrades an existing bionic.

#### Additional context
Also added an entry for CBMs to JSON_INFO.md.

### CODE REVIEW

File: src/iexamine.cpp [hunk 1]
```diff
@@ -3598,7 +3598,7 @@ void iexamine::autodoc( player &p, const tripoint &examp )
                 popup_player_or_npc( patient, _( "You have already installed this bionic." ),
                                      _( "%1$s has already installed this bionic." ) );
                 return;
-            } else if( bid->upgraded_bionic && !patient.has_bionic( bid->upgraded_bionic ) ) {
+            } else if( bid->upgraded_bionic && !patient.has_bionic( bid->upgraded_bionic ) && it->is_upgrade() ) {
```
Comment (BevapDin) [inline src/iexamine.cpp]: This is more a property of the bionic, not of the item that is used to install it.

Comment (KnightosMaster) [reply src/iexamine.cpp]: Both bio_advreactor and bio_reactor_upgrade refer to the bionic called bio_advreactor, so you have to check the item if it is an upgrade of an existing bionic or not.
