### PR TITLE
Prevent taking traits in chargen when a bionic conflicts with it

### LINKED ISSUE #39187: Losing Night Vision starting trait after reloading save
# Describe the bug

Upon reloading a save (Save and quit, then load save again) with the "Night Vision" starting trait/mutation with the "Bionic Sniper" profession (with it's starting CBMs), your night vision mutation disappears. This happens even if you give the mutation via the debug menu as well, mutation still disappears on reload.

I believe it's an issue/conflict with one of the sniper's starting CBMs and Night Vision, but I'm unable to determine which one is causing the issue.

Night Vision seems to work correctly on other professions, loaded up a bog standard "Evacuee ; Survivor" Evac shelter start w/ night vision and trait/mutation stayed after reload.

# Steps To Reproduce

1. Create a new character & world
2. Select "Helicopter Crash" scenario, "Bionic Sniper" profession
3. Take "Night Vision" trait (stats/other traits don't seem to matter)
4. Load into world, then save and quit.
5. Reload save, and you no longer will have the night vision trait

# Expected behavior
Character keeps inherent night vision mutation even if they start with CBMs 

# Screenshots
When first loading into world (haven't quit yet):
brokennightvision - pre reload
After reloading save:
brokennightvision - post reload

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-63-g8abe67d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

# Additional context

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: Bugfixes "Prevent taking traits in character generation when you start with a conflicting CBM"

#### Purpose of change
Fixes #39187

#### Describe the solution
Before applying a trait, check if it's cancelled by one of the selected professions mutations.

#### Testing
Take the bionic sniper profession, and attempt to take the night vision trait.

### CODE REVIEW

File: src/newcharacter.cpp [hunk 1]
```diff
@@ -1220,6 +1231,8 @@ tab_direction set_traits( avatar &u, points_left &points )
             } else if( u.prof->is_forbidden_trait( cur_trait ) ) {
                 popup( _( "Your profession of %s prevents you from taking this trait." ),
                        u.prof->gender_appropriate_name( u.male ) );
+            } else if( bionic_conflicts ) {
+                popup( _( "One of your bionics prevents you from taking this trait." ) );
```
Comment (Night-Pryanik) [inline src/newcharacter.cpp:1235]: Maybe mention the conflicting bionic instead of vague "One of your bionics..."?
