### PR TITLE
Limit the kinds of terrain that are vulnerable to mattack::growplants

### LINKED ISSUE #24995: Triffid queens can remove stairs to their nest.
**Describe the bug**  
Triffid queens have the ability to change nature at their will, but also allows them to remove the entrance to the underground system they produce.

**To Reproduce**  
1. Find a triffid grove
2. Allow triffid queen to pass over top their nest.

**Expected behavior**  
I could imagine there are bushes over top the entrance, but when the triffid queen passes overhead, the underground entrance should not be covered with trees and inaccessible.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version 0.C-30421-gf615e24
 - Graphics version tiles
 - Mods loaded none

### PR DESCRIPTION
**Pull request by Kodiologist**
#### Summary
SUMMARY: Balance "Limit the kinds of terrain that are vulnerable to mattack::growplants"

#### Purpose of change
The TODO comment I replaced said "Make this sensible - it can destroy EVERYTHING". Triffid queens could destroy liquids, stairs, computers, etc.

Fixes #24995.

#### Describe the solution
Only DIGGABLE terrain or trees can be affected by triffid queens.

#### Testing
I watched a triffid queen tear up the area outside a shelter without affecting the inside.

### CODE REVIEW

File: src/monattack.cpp [hunk 1]
```diff
@@ -1329,7 +1329,19 @@ static body_part body_part_hit_by_plant()
...
     for( const auto &p : g->m.points_in_radius( z->pos(), 3 ) ) {
-        // TODO: Make this sensible - it can destroy EVERYTHING
+
+        // Only certain kinds of terrain can be destroyed by this attack.
+        // Stairs, lava, card readers, etc. are unaffected.
+        for( auto flag : {
+                 "DIGGABLE", "ROAD", "RAIL", "TREE", "WALL"
+             } ) {
+            if( g->m.has_flag_ter( flag, p ) ) {
+                goto okay;
```
Comment (anothersimulacrum) [inline src/monattack.cpp]: Please don't use `goto`, it's not necessary here.

Comment (BevapDin) [inline src/monattack.cpp]: You can put this loop into a separate function and return from within the loop so you avoid using goto.

Comment (Kodiologist) [reply src/monattack.cpp]: Why?

**Comment by kevingranade** [comment]
Avoid auto, never use goto.
I recomend you build your list as a static const map, and instead of the goto shuffle, capture a boolean indicating success or failure and use it to decide to bail out.

From a game logic point of view, I suspect the only flag we actually care about here is DIGGABLE, which makes things even simpler.  I like the logic of simply needing to retreat to man made structures to avoid most of the danger.

**Comment by Kodiologist** [comment]
> I recomend you build your list as a static const map

Probably it's just because my C++ is rusty, but I'm not sure what that is or how I would solve the problem with it.

> 

> From a game logic point of view, I suspect the only flag we actually care about here is DIGGABLE, which makes things even simpler. I like the logic of simply needing to retreat to man made structures to avoid most of the danger.

Oh, I see. I thought it was intended that triffid queens could tear up buildings.

**Comment by I-am-Erk** [comment]
Long term, not in this pr, it would be nice to make flammable flagged terrain become overgrown with vines rather than replaced fully with trees

**Comment by Kodiologist** [comment]
This PR now takes a completely different approach, per Kevin's comment. Check it out.

File: src/monattack.cpp [hunk 2]
```diff
@@ -1329,9 +1329,12 @@ static body_part body_part_hit_by_plant()
...
     for( const auto &p : g->m.points_in_radius( z->pos(), 3 ) ) {
-        // TODO: Make this sensible - it can destroy EVERYTHING
-        if( !g->m.has_flag( "DIGGABLE", p ) && one_in( 4 ) ) {
-            g->m.ter_set( p, t_dirt );
+
+        // Only affect natural, dirtlike terrain, or terrain of the
+        // types we create (it's important that we can destroy our own
+        // trees, so we can't trap ourself).
+        if( !( g->m.has_flag_ter( "DIGGABLE", p ) ||
+               g->m.ter( p ) == t_tree_young || g->m.ter( p ) == t_tree ) ) {
```
Comment (BevapDin) [inline src/monattack.cpp]: I recommend checking for the "TREE" flag instead of "t_tree". There are all kinds of trees in the game, and they all have different ids.

Comment (Kodiologist) [reply src/monattack.cpp]: I know, but I didn't think we would want to allow triffid queens to destroy fruit trees, etc.; the only reason to allow tree destruction at all is to keep them from getting trapped.

Comment (ZhilkinSerg) [reply src/monattack.cpp]: Outworld triffids won't differentiate between Earth plant genera.

Comment (Kodiologist) [reply src/monattack.cpp]: Okay, done. We still need an explicit check `t_tree_young` because it's not technically a `TREE`.

**Comment by Kodiologist** [comment]
Regarding the "Mutations / Traits / Professions" tag, this function should only be available to triffid queens, not player plant-type mutants (yet?).
