### PR TITLE
fix uncanny dodge seatbelt & passenger flag issue

### LINKED ISSUE #48000: Uncanny dodging out of driver's seat, with vehicle dismount debug
# Describe the bug

Ah, yet another UD "feature". If you have UD active, either by bionic or by mutation, it can fire up when you're attacked while driving the vehicle and because it shifts you randomly, you can blink right out of the vehicle. With all applicable debug messages, i.e. that you're driving but there's no vehicle, and then when you finally get to the vehicle, that you're already driving it (even though you are not).

# Steps To Reproduce

Make a character with UD, spawn a bicycle or some other small vehicle that you can shift off from, run around zeds with UD active, see what happens. Can also use this [save](https://drive.google.com/file/d/1VzrvV8ilDtkuJiuDhztpa3Gd1qreKdt1/view?usp=sharing), just catch up to the scouter and run over the eastern side of the bridge, you'll get attacked from z-level 0 and dodge-dismount from the bike.

# Expected behavior

I guess it should just give a flat dodge bonus while you're driving? it's not like you have much place to dodge to but if regular dodge work, UD should be somewhat better if even just a little.

# Versions and configuration

OS: Windows 7x64
Game Version: 0.E-9955-g425255a [64-bit]
Graphics Version: Tiles
Game Language: English [en]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Aftershock [aftershock],
Magiclysm [magiclysm],
Alternative Map Key [alt_map_key],
sees-player icon, retrodays [sees_player_retro],
Stats Through Skills [StatsThroughSkills],
Bionic Professions [package_bionic_professions],
Ye olde Aftershock vehicle parts [afs_veh_goodies]
]

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
Bugfixes "Fix uncanny dodge inside vehicles"

#### Purpose of change
Uncanny dodge had some issue with the vehicle code.

- It ignored the seatbelt flag (doesn't make sense that you jump out of your seatbelt)
- It failed to remove/apply appropriate vehicle flags (passenger flag & the controlling_vehicle variable)

Fixes #48000

#### Describe the solution

Now uncanny dodge check if the player is inside a vehicle and:

- checks if a vehicle_part with a seatbelt flag is present (prevents the dodge from happening and sends a msg to the player)
- if the character ends up being moved due to uncanny dodge, then it unboards him (removes him from passenger part list and takes vehicle control from him in case the character was driving)
- finaly if the characters dodge has a vehicle tile as it's destination, it sets the appropriate flags

#### Describe alternatives you've considered

I am not entriely happy with the seatbelt situation.
On one hand it makes sense that you shouldn't be able to just dodge out of your seatbelt, but then again we don't ask the player if they want to strap in (instead we automatically assume they do)

#### Testing

- Debug yourself immortal (you are going to take a lot of hits)
- Debug uncanny dodge cbm and install it (there is a debug trait for that)
- Spawn in a car and zombie
- activate your uncanny dodge (check power) and let the Z bash you around inside the vehicle

- Try to get the Z to cause you to dodge outside of the vehicle, from and to a control tile, from and to a seat (check seatbelt exception) and repeat the same while the car is driving.

#### Additional context
I tried to be as diligent as possible with testing but there certainly is a not too small chance for missed edge cases ... so help with testing is very much appreciated.

### CODE REVIEW

**Comment by actual-nh** [comment]
If this PR were to leave out the seatbelt part, it would not need to be in string freeze, BTW.

**Comment by Jamuro-g** [comment]
> If this PR were to leave out the seatbelt part, it would not need to be in string freeze, BTW.

yeah but i would feel more at easy if this one gets merged after 0.F hits. I am just not 100% confident that there aren't some weird issues that might need fixing. (in particular involving npcs being shuffled around inbetween cars and similar cases)

File: src/character.cpp [hunk 1]
```diff
@@ -1445,9 +1445,31 @@ bool Character::uncanny_dodge()
...
         mod_stamina( -300 );
     }
+
+    map &here = get_map();
+    const optional_vpart_position veh_part = here.veh_at( position );
+    if( in_vehicle && veh_part && veh_part.avail_part_with_feature( "SEATBELT" ) ) {
+        if( is_u ) {
+            add_msg( _( "You try to dodge, but the seatbelt is in the way!" ) );
+        } else if( seen ) {
+            add_msg( _( "%s tries to dodge, but the seatbelt is in the way!" ), this->disp_name() );
```
Comment (Night-Pryanik) [inline src/character.cpp:1455]: Do we really need to fill the log with these messages? They are obvious, and don't need to be explicitly shown in log IMO.

Comment (ZhilkinSerg) [reply src/character.cpp:1455]: Yeah - getting rid of new strings would also allow merging it into master before 0.F.

Comment (Jamuro-g) [reply src/character.cpp:1455]: very well, i ll remove it
