### PR TITLE
Prevent endless loop during butchering

### LINKED ISSUE #47233: Butchering: bleeding hangs forever
# Describe the bug

Try to *bleed* the corpse of an animal (as a butchering action).
The action hangs forever:
* the UI is not responding
* sending a `SIGINT` signal (CTRL-C) unfreezes the UI and presents the expected confirmation dialog for quitting the game

Letting this run for some hours does not produce any progress (the game time visible when sending `SIGINT`) stays unchanged.

# Steps To Reproduce

1. place an animal corpse next to a butcher rack
2. select the *bleed* action in the butcher menu

# Expected behavior

The operation should finish within a reasonable time.

# Versions and configuration

 - OS: Linux (Debian testing)
 - Game Version: 0.E-9353-g6f0e582 (#11429)
 - Graphics version: tiles
 - Ingame language: English
 - Mods loaded: default

# Additional context

Attached you find a save game, that was stored during the bleed action. Thus simply loading the save game causes the UI freeze.
[save-hanging-butcher-bleeding.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5928578/save-hanging-butcher-bleeding.zip)

### PR DESCRIPTION
**Pull request by satheon49**
#### Summary
Bugfixes "Abort butchering if blood gets frozen"

#### Purpose of change

Fixes #47233

Bleeding a creature could result in an endless loop if the temparature got to low and the blood started to freeze. This prevented blood from being poured onto the ground.

#### Describe the solution

Abort the loop if either charges are 0 (as before) or no blood could be removed (new). A proper message was already in place for that use case and is now displayed: `"The %s froze solid before you could finish."`

#### Describe alternatives you've considered

Allow bleeding to be aborted. However everything to manage frozen liquids was already present and just not working.

#### Testing

Load the save from #47233. Without PR game runs forever, with PR game shows above message.

### CODE REVIEW

File: src/handle_liquid.cpp [hunk 1]
```diff
@@ -99,11 +99,10 @@ namespace liquid_handler
...
 {
-    while( liquid.charges > 0 ) {
-        // handle_liquid allows to pour onto the ground, which will handle all the liquid and
-        // set charges to 0. This allows terminating the loop.
-        // The result of handle_liquid is ignored, the player *has* to handle all the liquid.
-        handle_liquid( liquid, avoid, radius );
+    // handle_liquid allows to pour onto the ground, which will handle all the liquid and
+    // set charges to 0. This allows terminating the loop.
+    // The result of handle_liquid is ignored, the player *has* to handle all the liquid.
+    while( liquid.charges > 0 && handle_liquid( liquid, avoid, radius ) ) {
```
Comment (Qrox) [inline src/handle_liquid.cpp:105]: Does this affect other places where you have to handle all the liquid such as crafting? I suspect this might make it possible to cancel handling in such case and make the result disappear.

File: src/handle_liquid.cpp [hunk 2]
```diff
@@ -460,6 +457,14 @@ bool handle_liquid( item &liquid, const item *const source, const int radius,
...
         return false;
     }
+    return true;
+}
+
+bool handle_liquid( item &liquid, const item *const source, const int radius,
+                    const tripoint *const source_pos,
+                    const vehicle *const source_veh, const int part_num,
+                    const monster *const source_mon )
+{
```
Comment (Qrox) [inline src/handle_liquid.cpp:467]:
```suggestion
{
    if( !can_handle_liquid( liquid ) ) {
        return false;
    }
```

Comment (satheon49) [reply src/handle_liquid.cpp:467]: That change would cause the endless loop again this PR aims to fix. The problem is that jumping out of handle_liquid before it has a chance to lower charges results in the loop in 102 to run forever.

Comment (Qrox) [reply src/handle_liquid.cpp:467]: You already test `can_handle_liquid( liquid )` in the loop condition so there won't be an infinite loop. (If the loop does not terminate, it means `can_handle_liquid( liquid )` must be true, and because `can_handle_liquid` does not modify `liquid`, it is still true here, so this branch is never executed.)

**Comment by Qrox** [comment]
On second though, the butchery code should skip handling blood and marking corpse as bled if the blood would be frozen, and `handle_all_liquid` should drop solid or frozen items to the ground, because otherwise the item just disappears.

**Comment by satheon49** [comment]
I don't think that is still in the scope of this PR and I would keep it as is. The aim here was only to fix the crash/freeze of handle_all_liquids. Even if the bleeding acivity was fixed, the current changes should still remain in place because there is no guarantee that every current and future call to handle_all_liquids properly checks for frozen before (and they shouldn't have to in any case).

I have taken a look at what changes would need to be made to the butchering bleeding action and there are quite a few:
1. `butcher_submenu` needs not to allow frozen corpses to be bled so it can not even be started (which probably requires refactoring on those nested ternary operators to keep any level of readability)
2. `butcher_finish` still needs to check frozen again because it might have frozen during the butcher activity. This requires careful analysis of everything done here to be sure it is safe to `return;` early before corpse is flagged as bled.
