### PR TITLE
Speedydex bonus fix

### LINKED ISSUE #62977: Character does not get correct speed bonus from SpeedyDex mod
### Describe the bug

For Dex, every point greater than 12 points increases speed by 2 points. But the resulting speed bonus is multiplied by 2.

### Steps to reproduce

1 Create a clean character with Dex of 13.

2 It also says "Bio/Mut/Effects +2" . But the final speed is 104. 

### Expected behavior

The final speed  should be 102.

### Screenshots

Screenshot_20230103_150408_com cleverraven catacl

### Versions and configuration

The android version downloads from "Cataclysm-DDA experimental build 2023-01-02-0647".
Screenshot_20230103_151347_com cleverraven catacl
Screenshot_20230103_150645_com cleverraven catacl

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Dan1ss1mo**
#### Summary
Bugfixes "fix for speed bonus from Speedydex applying twice"

#### Purpose of change
fix #62977 
Bonus from speedy dex apply it's bonuses twice, once as modifier and once as base speed bonus

#### Describe the solution
Moving get_speedydex_bonus into Character::recalc_speed_bonus

#### Describe alternatives you've considered
Smacking 0.5 multiplier in get_speedydex_bonus formula and calling it a day

#### Testing
Everything seems to work fine

#### Additional context
current bonus
image

fixed bonus
image

My first c++ contribution, I'm so proud of myself

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -10752,6 +10751,8 @@ void Character::recalc_speed_bonus()
         carry_penalty = 25 * ( weight_carried() - weight_cap ) / weight_cap;
     }
     mod_speed_bonus( -carry_penalty );
+	
+	mod_speed_bonus( +get_speedydex_bonus( get_dex() ) );
```
Comment (dseguin) [inline src/character.cpp:10755]:
```suggestion
    mod_speed_bonus( +get_speedydex_bonus( get_dex() ) );
```
