### PR TITLE
Reset wait popup on activity finish

### LINKED ISSUE #73810: "interacting with the vehicle" dialog stays visible after action is complete
### Describe the bug

When removing a swappable storage battery from an electric street sweeper, the "interacting" IMGUI dialog stays visible after the action is done. The dialog does disappear when exiting the vehicle screen.

### Attach save file

N/A

### Steps to reproduce

1. Spawn an electric street sweeper
2. (e)xamine it, find the battery
3. rem(o)ve the battery

### Expected behavior

The "interacting" dialog should appear, then disappear.

### Screenshots

Screenshot 2024-05-15 at 10 48 54

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.3; Build: 23D56; 
- Game Version: cdda-experimental-2024-05-12-1705 39e2afa [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by irwiss**
#### Summary
None

#### Purpose of change

Fixes #73810

#### Describe the solution

Reset wait popup on activity cancel/finish

Also clean up access to game::wait_popup and remove advanced_inventory friend from game as accessing wait_popup seems to be it's only use

#### Testing

Steps in the issue

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -12965,6 +12965,12 @@ void game::display_om_pathfinding_progress( size_t /* open_set */, size_t /* kno
     inp_mngr.pump_events();
 }
 
+void game::wait_popup_reset()
+{
+    wait_popup.reset();
+    ui_manager::redraw();
```
Comment (Qrox) [inline src/game.cpp:12971]: Is this line necessary for the wait popup to disappear? I think `wait_popup.reset()` will call `ui_adaptor`'s deconstruction function which should mark the underlying UI for redraw, as long as the `ui_adaptor`'s dimensions are correctly set, and the underlying UI will call `ui_manager::redraw` before checking for the next input, so this line is probably not needed if everything works as intended.

File: src/do_turn.cpp [hunk 2]
```diff
@@ -566,8 +566,7 @@ bool do_turn()
                 sounds::process_sound_markers( &u );
                 if( !u.activity && g->uquit != QUIT_WATCH
                     && ( !u.has_distant_destination() || calendar::once_every( 10_seconds ) ) ) {
-                    g->wait_popup.reset();
-                    ui_manager::redraw();
```
Comment (Qrox) [inline src/do_turn.cpp:570]: Except here where there is no underlying UI so `ui_manager::redraw` is needed.
