### PR TITLE
Don't delete map note when pressing escape or entering empty string

### LINKED ISSUE #14443: Map notes disappear when examined and escaped
Build 0.C-8241 or 4043 on jenkins.

If I examine a Map note and hit escape it seems like the note just gets deleted.  This isn't desirable.  If I hit the escape button I want whatever was there to be preserved (no action taken, I just want to get out of the screen).

So to reproduce, hit "m" inside the running game to get to the map screen.  Then hit "N" to make a note.  Make some note and hit enter.  Then hit "N" again on the same square to examine the note.  Then hit escape.  The note appears to have been deleted.  Ideally it should be left intact.

### PR DESCRIPTION
**Pull request by sparr**
There's a hotkey to delete a note on the map, so let's assume that if a player uses the note edit interface that they don't intend to erase the note. This will prompt if you press escape while editing, or if you enter a blank string over an existing note.

closes #14443

### CODE REVIEW

File: src/overmap.cpp [hunk 1]
```diff
@@ -2157,7 +2157,11 @@ tripoint overmap::draw_overmap(const tripoint &orig, const draw_data_t &data)
             const std::string new_note = string_input_popup(
                 _("Note (X:TEXT for custom symbol, G; for color):"),
                 45, old_note, color_notes); // 45 char max
-            if(old_note != new_note) {
+            if(new_note == "" && old_note != "") {
```
Comment (BevapDin) [inline src/overmap.cpp]: Why not use `std::String::empty()` here instead of magic string constants?

Comment (sparr) [inline src/overmap.cpp]: that magic string constant is what string_input_popup returns when you hit escape

Comment (BevapDin) [inline src/overmap.cpp]: `""` is an empty string. calling `empty()` and comparing with `""` it is completely equivalent. And string_input should probably returns `std::string()`.

To avoid any potential confusing:
```C++
std::string a = "";
std::string b;
// this is always true:
assert(a == b);
// but this *might* not be true:
assert("" == "")
```
In other words: an empty string is the same as a default constructed string.

**Comment by chaosvolt** [comment]
Given I actually got in the habit of clearing my map notes via escape, I can see this being yet another minor change where it'll vary individually as to whether it's an annoyance. -_-

File: src/overmap.cpp [hunk 2]
```diff
@@ -2157,8 +2157,12 @@ tripoint overmap::draw_overmap(const tripoint &orig, const draw_data_t &data)
             const std::string new_note = string_input_popup(
                 _("Note (X:TEXT for custom symbol, G; for color):"),
                 45, old_note, color_notes); // 45 char max
-            if(old_note != new_note) {
-                overmap_buffer.add_note(curs, new_note);
+            if ( new_note.empty() && !old_note.empty() )
```
Comment (kevingranade) [inline src/overmap.cpp]: styling
