### PR TITLE
Remove food monotony penalty from junk foods and psychoactives

### LINKED ISSUE #38625: Junk food ceases to be enjoyable as you eat it
# Describe the bug

The enjoyment value of some junk foods drops when you eat them, just like non-junk food. 

# Steps To Reproduce

1. Spawn a big pile of chocolate waffles
2. Eat it
3. Enjoyment value drops with each piece consumed, until it reaches zero

# Expected behavior

Junk food should not get boring when eaten.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-12453-g05940bf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

### PR DESCRIPTION
**Pull request by Soadreqm**
#### Summary
SUMMARY: Bugfixes "Removes food monotony penalty from junk foods"

#### Purpose of change
Fixes #38625
~~While I was at it, I also excluded caffeine and alcohol products from having the penalty, on the basis that taste doesn't matter as much for stimulants and depressants.~~

#### Describe the solution
Moved the junk food check so that both "material" and "primary_material" get checked. ~~Added check for nonzero "stim" value, which covers all stimulants and depressants.~~

#### Describe alternatives you've considered
Giving a monotony penalty to bee balm tea and chamomile tea. Removing penalty from herbal tea, pine needle tea, dandelion tea, brownies (both kinds) and semi-fancy foods with small portion sizes.
Since the monotony penalty is applied per portion, foods with high charges are affected more. The various pies are the worst right now, coming in stacks of 8 and losing all flavor by the third slice. That's something that should be considered per-item, though.
Brownies are interestingly enough not junk food, despite having chocolate, and don't have a stim effect, despite having marijuana, so they still get boring.
The non-tea teas are kind of borderline. I don't think any of them have any caffeine in reality, but in-game bee balm tea has 1 stim, chamomile is copied from regular tea, and the rest are just mildly flavored water.

#### Testing
Spawned chocolate waffles, chocolate drink, regular chocolate, cola, coffee, tea, vodka and lasagne. Chocolate products, ~~caffeine and booze~~ did not get boring when eaten, while lasagne did.
~~Searched through json files in data/items/comestibles for "stim" to see if anything weird was using it. Noted that "alien fronds" and "leech flowers" act as stimulants, but that seems fairly reasonable considering the item descriptions.
Spawned alien fronds and leech flowers, which did not get boring when eaten.~~

### CODE REVIEW

File: src/item_factory.cpp [hunk 1]
```diff
@@ -1857,15 +1855,28 @@ void Item_factory::load( islot_comestible &slot, const JsonObject &jo, const std
...
     }
 
-    if( is_junkfood ) { // Junk food never gets old by default, but this can still be overriden.
+    bool is_not_boring = false;
+    if (jo.has_member("primary_material")) {
+        std::string mat = jo.get_string("primary_material");
+        is_not_boring = is_not_boring || mat == "junk";
+    }
+    if (jo.has_member("material")) {
+        for (auto& m : jo.get_tags("material")) {
```
Comment (anothersimulacrum) [inline src/item_factory.cpp]: Please replace auto with the proper type.

Comment (Soadreqm) [reply src/item_factory.cpp]: What's the proper type? String? I didn't write that, just copied it from the existing material check.

Comment (anothersimulacrum) [reply src/item_factory.cpp]: Looks like std::string.

Comment (Soadreqm) [reply src/item_factory.cpp]: It didn't crash on item load, so that seems to be it. Thanks. Switched both of them.

File: src/item_factory.cpp [hunk 2]
```diff
@@ -1841,31 +1841,42 @@ void Item_factory::load( islot_comestible &slot, const JsonObject &jo, const std
...
         slot.specific_heat_liquid = material_id( mat )->specific_heat_liquid();
         slot.latent_heat = material_id( mat )->latent_heat();
-        is_junkfood = is_junkfood || mat == "junk";
     } else if( jo.has_member( "material" ) ) {
         float specific_heat_solid = 0;
         float specific_heat_liquid = 0;
         float latent_heat = 0;
 
-        for( auto &m : jo.get_tags( "material" ) ) {
+        for( std::string m : jo.get_tags( "material" ) ) {
```
Comment (anothersimulacrum) [inline src/item_factory.cpp]:
```suggestion
        for( std::string &m : jo.get_tags( "material" ) ) {
```

File: src/item_factory.cpp [hunk 3]
```diff
@@ -1841,31 +1841,42 @@ void Item_factory::load( islot_comestible &slot, const JsonObject &jo, const std
...
     }
 
-    if( is_junkfood ) { // Junk food never gets old by default, but this can still be overriden.
+    bool is_not_boring = false;
+    if( jo.has_member( "primary_material" ) ) {
+        std::string mat = jo.get_string( "primary_material" );
+        is_not_boring = is_not_boring || mat == "junk";
+    }
+    if( jo.has_member( "material" ) ) {
+        for( std::string m : jo.get_tags( "material" ) ) {
```
Comment (anothersimulacrum) [inline src/item_factory.cpp]:
```suggestion
        for( std::string &m : jo.get_tags( "material" ) ) {
```

File: src/item_factory.cpp (hunk 1 above)
Comment (anothersimulacrum) [reply src/item_factory.cpp]: It would fail to compile if you put the wrong type, so you can know you've got it right.

File: src/item_factory.cpp (hunk 2 above)
Comment (Soadreqm) [reply src/item_factory.cpp]: This doesn't work. I'm not actually sure why it did before, with auto.

Comment (anothersimulacrum) [reply src/item_factory.cpp]: Try again, I was missing the const.

**Comment by Soadreqm** [comment]
@kevingranade I assumed it's because they're made of mostly fat and sugar. It was the intended behaviour back in #35910, you'd have to ask @Davi-DeGanne for his original reason.

**Comment by wapcaplet** [comment]
@Soadreqm Did you test that items with an explicitly-defined `monotony_penalty` override the default penalty of 0?

**Comment by Soadreqm** [comment]
@wapcaplet No, I didn't. I actually don't think there are any. I don't think messing with the default should change how that works, but I guess I should try it out anyway.

**Comment by Soadreqm** [comment]
Set monotony_penalty of meat pie to 0 and meat pizza to 1, spawned and ate several pieces. It works as advertised.

File: src/item_factory.cpp [hunk 4]
```diff
@@ -1841,31 +1841,42 @@ void Item_factory::load( islot_comestible &slot, const JsonObject &jo, const std
...
+    if( jo.has_member( "material" ) ) {
+        for( const std::string &m : jo.get_tags( "material" ) ) {
+            is_not_boring = is_not_boring || m == "junk";
+        }
+    }
+    if( jo.has_member( "stim" ) ) {
+        is_not_boring = is_not_boring || jo.get_int( "stim" ) != 0;
+    }
+
+    if( is_not_boring ) { // Junk food, stimulants and depressants never get old by default, but this can still be overriden.
```
Comment (anothersimulacrum) [inline src/item_factory.cpp]: Please out the comment on the line above or below, this can be hard to read.

**Comment by kevingranade** [comment]
After revisiting the parent issue, I see what you're doing now, part of the problem is you mixed a bugfix with a balance change, which made me think that it was all balance change.
That doesn't change the fact that I still don't agree with the concept that all food suffers from a monotony penalty except for junk food.  If anything my intuition says it's the opposite, junk food is habit forming in the short term, but eating a large amount of it quickly erodes the things about it your body finds rewarding.
The stim issue is similar, I can buy the argument that the the stimulant effect itself is not subject to the monotony penalty, but that is not what you've implemented here, which is that any degree of stimulant effect makes a food eternally novel.

The bugfix part of this that prevents "primary_material" from making the code ignore "materials" can go in as-is, but please drop the stimulant part.

Also I'm going to be reconsidering the junkfood exclusion in general in the future, because I'm very unconvinced it should be immune to this effect.

**Comment by Soadreqm** [comment]
Sure, I really should have separated the changes to begin with.
What do you mean by 

> I can buy the argument that the the stimulant effect itself is not subject to the monotony penalty, but that is not what you've implemented here, which is that any degree of stimulant effect makes a food eternally novel.

though? If I did a new PR for the stims, what would you actually expect it to have?

**Comment by Soadreqm** [comment]
By the way, I don't know why the automated tests are failing. It says it's the distribution of attacks to body parts, but I don't see how anything I've done could have messed with that.

**Comment by anothersimulacrum** [comment]
Test failures are due to randomness and #38983.

**Comment by wapcaplet** [comment]
Other failures you may have seen are now fixed by #38979
