### PR TITLE
bike racked vehicle fixes

### LINKED ISSUE #46298: Vehicle interface displays misleading fill percentages when other vehicles are racked
# Describe the bug

My car's electric battery isn't gaining charge the way it feels like it should.

# Steps To Reproduce

1. Load the attached save.
2. Note that the battery charge is at 68%, and nothing is draining power.
3. Wait for six hours.
4. Note that the battery charge is _still_ 68%.

# Expected behavior

I expected to see my battery levels rise.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.685)
- Game Version: 0.E-8388-gb85c4a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills]

# Additional context

[Woodcock.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5740280/Woodcock.zip)

### LINKED ISSUE #46564: Incorrect fuel content shown when bike rack in use (not the % full one)
# Describe the bug

When a vehicle with fuel is loaded onto another vehicle with a bike rack the number of litres of fuel present may be shown incorrectly.

# Steps To Reproduce

1. Have a car with bike racks installed.
2. Have a motorcycle with fuel in the tank.
3. Load motorcycle onto bike racks.
4. (e)xamine vehicle

See impossible and / or inaccurate amount of fuel for motorcycle tank.

# Expected behavior

Accurate amount of fuel shown.

# Screenshots

tanks

In my case it shows 71.2L of gasoline in a 60L tank (actual value is 56.9L).

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8729-geba9219 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

Not the same as a similar sounding bug "Vehicle interface displays misleading fill percentages when other vehicles are racked" https://github.com/CleverRaven/Cataclysm-DDA/issues/46298

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary

SUMMARY: Bugfixes "Fixed display issues with/caused by bike racked vehicles"

#### Purpose of change

1. unloading a racked vehicle caused it's engine stats to show up empty (due to valid engines not being set to enabled upon creation)
2. fuel tanks of bike racked vehicles showed up in the parts list and caused wrong fuel amounts to show up in the overview
3. merged several for loops
4. fuel gauges didn't make sure to avoid racked car parts when calculating capacity and showed wrong stats whenever racked vehicles (with batteries/fuel tanks) were present

Fixes #46564
Fixes #46298

#### Describe the solution

1. added code to vehicle::remove_carried_vehicle() that enables working engines once the unracked vehicle is created
2. veh_interact::calc_overview() the vehicle tank section used a pointer of a pointer by accident.
3. veh_interact::calc_overview() merged 5 for loops that all were cycling through the same part list and instead sorted the final result
4. vehicle::fuel_capacity() added an is_avaliable() check to ensure that carried car parts aren't falsifying fuel gauges.

#### Describe alternatives you've considered
1. in theory engines disabled by default is fine, but probably not what players expect when they unload a racked vehicle.
2. alternative would be to split the ui into different sections for the main car and it's carried vehicles (currently working on that, but no clue when i have something that works to show)

#### Testing

1. debug spawn in a car with bike racks
2. spawn in a motorbike (or any rackable vehicle with a fuel tank)
3. rack & compare pr with original to see offending fuel tank(s)
3.1. compare fuel/battery gauges at the bottom of the overview screen to before the vehicle got racked 
4. unload racked vehicle
5. examine newly unracked vehicle to see it's engine stats intact and shown

### CODE REVIEW

File: src/veh_interact.cpp [hunk 1]
```diff
@@ -1445,123 +1445,127 @@ void veh_interact::calc_overview()
...
-                right_print( w, y, 1, pt.passenger_id == who->getID() ? c_green : c_light_gray, who->name );
-            }
-        };
-        if( vpr.part().is_seat() && vpr.part().is_available() ) {
-            overview_opts.emplace_back( "SEAT", &vpr.part(), next_hotkey( vpr.part(), hotkey ), details );
-        }
-    }
+    auto compare = []( veh_interact::part_option & s1,
+    veh_interact::part_option & s2 ) {
+        return  s1.key <  s2.key;
```
Comment (BrettDong) [inline src/veh_interact.cpp:1565]: The warning can be silenced by
```suggestion
        // NOLINTNEXTLINE cata-use-localized-sorting
        return s1.key < s2.key;
```

File: src/veh_interact.cpp [hunk 2]
```diff
@@ -1445,123 +1445,127 @@ void veh_interact::calc_overview()
...
-                             string_format( fmtstring, item::nname( pt.ammo_current() ),
-                                            round_up( vol_L, 1 ) ) );
+            };
+            if( vpr.part().is_reactor() && vpr.part().is_available() ) {
+                overview_opts.emplace_back( "REACTOR", &vpr.part(), next_hotkey( vpr.part(), hotkey ),
+                                            details_ammo );
+            }
+            if( vpr.part().is_turret() && vpr.part().is_available() ) {
+                overview_opts.emplace_back( "TURRET", &vpr.part(), next_hotkey( vpr.part(), hotkey ),
+                                            details_ammo );
```
Comment (BrettDong) [inline src/veh_interact.cpp:1545]: You have checked for `vpr.part().is_available()` in line 1526 above.

Comment (Jamuro-g) [reply src/veh_interact.cpp]: i ve removed the is_avaliable() checks from the old if statements.
i probably can merge them into a single check, but will have to check if that doesn't interfere with an expansion to the ui that i am working on.

**Review by mlangsdorf — APPROVED** [review]
