### PR TITLE
Fix error when aiming turrets via a remote vehicle controller

### LINKED ISSUE #23902: Error when aiming a turret via a remote vehicle controller: "Tried to aim turret while outside vehicle"
Game version: f4ade2c9098b6067f456a36c7e7def488ed0fc6c

Operating system: Linux

Tiles or curses: Tiles

Mods active:
More Survival Tools
blazemod
Tanks and Other Vehicles
Boats
Folding Parts pack
Disable NPC Needs
Simplified Nutrition

### Expected behavior
Users should be able to remotely aim a turret without errors popping up.

### Actual behavior
This error pops up upon selecting the turret.
https://github.com/CleverRaven/Cataclysm-DDA/blob/f4ade2c9098b6067f456a36c7e7def488ed0fc6c/src/ranged.cpp#L771

Also, there's a minor visual bug in the aiming dialog after the error pops up if the user opts to "continue": https://imgur.com/K9Ctugs This goes away if the user stops aiming and restarts aiming again.

### Steps to reproduce the behavior
1. Build a vehicle with drive by wire controls, a turret mount, and a mounted gun (the specific gun shouldn't matter, tried with M249 and Mark 19 Grenade Launcher).
2. Obtain a remote vehicle controller (or a Remote Controller CBM).
3. Remote control the vehicle.
4. Attempt to manually aim the turret.

Probably related: #22512

### PR DESCRIPTION
**Pull request by olanti-p**
#### Summary
```SUMMARY: Bugfixes "Fixed error when aiming turrets via a remote vehicle controller"```

#### Purpose of change
Fixes #23902 - Error when aiming a turret via a remote vehicle controller.
Changes `All turrets are offline or set to manual targeting mode` message to say `automatic` when failing to find any turrets that are ready and set to _manual_ mode.

#### Describe the solution
Reorganized turret selection and aiming code to get rid of `auto`s, be more clear and somewhat confer to single-responsibility principle.

Then, instead of assuming that player stays inside the vehicle and tries to fire its turrets, made target_ui accept relevant vehicle & list of fired turrets as arguments.

#### Testing
Assembled the thing from #36574, used it remotely to gun down some zeds.
Added a second turret, tried `Aim automatic turrets`, `Aim manual turrets` & `Aim single turret` with turrets set to various combinations of modes.

### CODE REVIEW

File: src/turret.cpp [hunk 1]
```diff
@@ -288,6 +295,139 @@ int turret_data::fire( player &p, const tripoint &target )
...
+    turrets.push_back( turret );
+    turrets_aim_and_fire( turrets );
+}
+
+bool vehicle::turrets_aim_and_fire_all_manual( bool complain )
+{
+    std::vector<vehicle_part *> turrets = find_all_ready_turrets( true, false );
+
+    if( turrets.empty() ) {
+        if( complain ) {
```
Comment (Night-Pryanik) [inline src/turret.cpp]: This check could be merged with the above check.

Comment (olanti-p) [reply src/turret.cpp]: `!complain` was intended as 'suppress message but do not change returned value', so merging that check would require another one for function result. I updated comments/names to be less confusing

Comment (Night-Pryanik) [reply src/turret.cpp]: Look: `show_msg` check makes sense _only_ if `turrets` is empty. If `turrets` isn't empty, nothing happens at all, and you don't need to check for `show_msg` at all too. So instead of checking for emptiness and _then_ for `show_msg`, you could check for emptiness _and_ for `show_msg` simultaneously.

Comment (olanti-p) [reply src/turret.cpp]: I think you've missed `return false;` statement 2 lines below. If it wasn't there, then yeah, that would've worked.

Comment (Night-Pryanik) [reply src/turret.cpp]: Look once again: your current checks are as follows

```
if( x ) {
    if( y ) {
      foo;
    }
}
```

It doesn't really matter what we have in `foo`. 
Let's check what if `x` is false: program will do nothing. That means `if( x )` check **by itself** (i.e. solitary) is useless. 
The whole 

```
if( y ) {
  foo;
}
```
check occurs **only** if `x` is true. That means we should merge both `x` and `y` checks:

```
if( x && y ) {
   foo;
}
```
In other words: show message only if `turrets` is empty **and** `show_msg` is true. If either of this conditions are false, don't do anything at all.

Comment (olanti-p) [reply src/turret.cpp]: No, my current checks are as follows
```c++
if( x ) {
    if( y ) {
        add_msg();
    }
    return false;
}
```
if I merge `x` and `y` it's either gonna be
```c++
if( x && y ) {
    add_msg();
    return false;
}
```
which is invalid, or
```c++
if( x && y ) {
    add_msg();
}
if( x ) {
    return false;
}
```
which is unnecessary duplication.

Comment (Night-Pryanik) [reply src/turret.cpp]: Yeah, my bad. Sorry.
