### PR TITLE
Bionic fingerpick fix

### LINKED ISSUE #39740: Finger Pick CBM Stuck Picking Forever
# Describe the bug
When trying to use the Fingerpick a door open it gets stuck in picking the lock. The Yes and No prompts can stop the picking.

# Steps To Reproduce
1. Have a player with the Fingerpick.
2. Activate the Fingerpick in front of a locked door.
3. Player gets stuck trying to pick the lock.

# Expected behavior
Successfully opening the locked door or failing.

# Screenshots
cataclysm-tiles_2jAbvdNkHB

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-960-gec91719 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Character is Rey Villarreal
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4501121/debug.log)
[CBM Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4501124/CBM.Test.zip)

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Bugfixes "Bionic fingerpick fix."```

#### Purpose of change
Closes #39740 - Finger Pick CBM Stuck Picking Forever.

#### Describe the solution
Replaced creating a temporary item and then invoking it with creating a temporary item, placing it into player inventory, assigning activity with this item, and destroying this item immediately after use. Using bionic lockpick will always consume fixed 4 seconds and will always be successful.

Also cancel activity if lockpick item location is lost for some reason.
Also replaced hardcoded list of allowed terrain/furniture within lockpicking actor with check for a newly added `PICKABLE` flag. Added documentation for this flag.
Also removed several unused `const`s from `activity_handlers.cpp` and `iexamine.cpp`.

#### Describe alternatives you've considered
Directly use `invoke` method for a temporary created item - no luck.

#### Testing
Debug-added bionic lockpicks CBM to my character. Activated it next to a locked gun safe. Spent 4 seconds, opened safe. Also tested mundane lockpicks on the locked gun safe - worked as intended.

#### Additional context
There is some strange reason activating the bionic fingerpick CBM and then selecting direction brings the bionic UI menu up front. You can activate the same CBM once again, and select direction once again. Lockpicking activity will occur only after you close the bionic UI menu. I couldn't get rid of this behavior, and I don't know if it's related to my changes.

### CODE REVIEW

**Comment by ifreund** [comment]
What happens if an activity using the fingerpick gets cancelled? It seems that the pseudo item would live in the player's inventory forever with the current code which potentially cause issues.

**Comment by Pupsi-Mupsi** [comment]
Well done and thank you!

You may have accidentally deleted this:

> static const bionic_id bio_fingerhack( "bio_fingerhack" );

bio_fingerhack != bio_fingerpick

**Comment by Night-Pryanik** [comment]
`static const bionic_id bio_fingerhack( "bio_fingerhack" )` isn't used anywhere in `activity_handlers.cpp`, so I deleted it as well.

**Comment by Night-Pryanik** [comment]
> What happens if an activity using the fingerpick gets cancelled? It seems that the pseudo item would live in the player's inventory forever with the current code which could potentially cause issues.

Added a special case if lockpicking activity is canceled mid-way: remove fake bionic lockpick.

File: src/character.cpp [hunk 1]
```diff
@@ -9184,6 +9185,14 @@ void Character::cancel_activity()
...
         remove_value( "sleep_query" );
     }
+    if( has_activity( ACT_LOCKPICK ) ) {
+        std::vector<item *> bio_picklocks = g->u.items_with( []( const item & itm ) {
+            return itm.typeId() == "pseudo_bio_picklock";
+        } );
+        if( !bio_picklocks.empty() ) {
+            g->u.i_rem( bio_picklocks[0] );
+        }
+    }
```
Comment (ifreund) [inline src/character.cpp:9195]: Hmm, this still seems a little fragile as this wont be run if the activity is stopped using `player_activity::set_to_null()` for example. I think we could instead set a variable on the activity to indicate that it is using the bionic lockpick. Then we could insert the pseudo item into the player's inventory on completion of the activity if that variable is set. What do you think?

Comment (Night-Pryanik) [reply src/character.cpp:9195]: >if the activity is stopped using player_activity::set_to_null()

I didn't find any cases which could stop this activity by the means of `set_to_null`. Could you please list any?

> Then we could insert the pseudo item into the player's inventory on completion of the activity if that variable is set.

The item must be inserted prior to completion of activity, not after it.

Comment (ifreund) [reply src/character.cpp:9195]: > I didn't find any cases which could stop this activity by the means of set_to_null. Could you please list any?

It may very well be fine with the current code. When i said "fragile" i meant likely to break and cause bugs in the future if the code is changed. 

> The item must be inserted prior to completion of activity, not after it.

This behavior isn't set in stone, it could be changed. One way to do this would be to set the first member of `player_activity::str_values` to `bio_picklock` if using the fingerpick and check for that string before checking the `targets` vector at the start of the finish function.  If that string is present, the pseudo item could then be inserted into the players inventory and used instead of the first `item_location` in the `targets` vector. In my opinion, such an approach would be less prone to cause problems in the future.
