### PR TITLE
Fix loading problem for guns with internal magazine (still need json change for specific guns)

### LINKED ISSUE #41547: <bug> Marlin 39A can`t be reloaded
# Describe the bug
The Marlin 39A can`t be reloaded with it compatible magazine

# Steps To Reproduce
1. Spawn the Marlin 39A with some .22 19-round tube loader.
2. Try to reload.

# Versions and configuration
 OS: Windows 10
Game Version: 0.E-2993-gd2b512e
Graphics version: Tiles
Mods loaded: 
imagen

### LINKED ISSUE #41582: Seg Fault when reloading with shotgun speedloader
# Describe the bug

Trying to reload m1014, Wingmaster and other similar shotguns (with speedloader chute mod attached) with shotgun speedloader (6- or 8-round) results in a seg fault crash.

# Steps To Reproduce

1. Spawn a shotgun with loading port mod slot (like m1014 or Remington 870 Wingmaster), speedloader chute, shotgun 8-round speedloader.
2. Unload shotgun.
3. Modify shotgun with speedloader chute. 
4. Press reload button, select shotgun.
5. Seg fault crash.

# Expected behavior

Rounds from speedloader should transfer to shotgun.

# Versions and configuration

- OS: Windows
    - OS Version: Windows 8.1
- Game Version: 0.E-3486-ge60e4d8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

Also crashes on default mod world.

# Additional context

[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4831093/config.zip)

As for revolver's speedloader - they just doesn't work. Maybe that is another issue.

### PR DESCRIPTION
**Pull request by Menschheit**
#### Summary

SUMMARY: Bugfixes "Allow marlin 39A reloading again, fix a crash caused by speed loader"

#### Purpose of change

Fix #41547 

Fix #41582 

#### Describe the solution

For #41547 , We only need json changes. Guns with internal magazine must have a magazine pocket. But then  #41582 is comming.

For #41582 , there is some dangerous codes without concerning invalid types. So I made an additional check to avoid that Statement (didn't read itype and itype_id very carefully, but i confirmed the crash here with my own tests)

#### Testing

Empty speedloader is invalid ammo; non-empty gun can't be loaded with speed loader, can be loaded with bulletsr; empty guns can be reloaded with both bulltes and non-empty speedloaders. Everything works fine .

#### Additional context

If a gun which can be loaded with speedloader, but also has other normal magazines available in magazine_well or in a magazine_well of attached mod, there may be problems...

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -6582,6 +6582,13 @@ bool item::is_reloadable_helper( const itype_id &ammo, bool now ) const
                 return false;
             }
         }
+        //Now single shoted gun also has magazine_well slot for speedloader
+        //If ammo is not an ammo it may be dangerous to use parameters like ammo->ammo->type
+        //It is complicated: normal magazine in addition to speedloader? Magazines of mods?
+        if( !ammo->ammo ) {
```
Comment (anothersimulacrum) [inline src/item.cpp:6588]:
```suggestion
        if( now && !ammo->ammo ) {
```

Comment (Menschheit) [reply src/item.cpp]: But seem like no real difference? It's deep in the night dont have clear headed now...

Comment (anothersimulacrum) [reply src/item.cpp]: Before, it would do:
```cpp
if( !now ) {
   return true;
} else {
   return ammo_remaining() < ammo_capacity( ammo->ammo->type );
}
```
Without this change, it does
```cpp
if( !now || !ammo->ammo ) {
   return magazine_compatible().count( ammo );
} else {
   return ammo_remaining() < ammo_capacity( ammo->ammo->type );
}
```
now it does:

```cpp
if( !now ) {
    return true;
else if( !ammo->ammo ) {
   return magazine_compatible().count( ammo );
} else {
   return ammo_remaining() < ammo_capacity( ammo->ammo->type );
}
```

**Comment by Menschheit** [comment]
Made more json changes but PR not updating, I'll try close and reopen it.

**Comment by kevingranade** [comment]
I think this is going in the right direction, but we have a logic error in item_contents::ammo_consume() where having an empty magazine well causes a debugmsg because it reports that nothing was consumed when there is an empty magazine well.
Actually nevermind, I have a fix handy.
