### PR TITLE
Fixes a divide by zero situation with zero dex

### LINKED ISSUE #15243: Spilling gasoline with 0 dex deletes all the gas inside the pump
Spilling gasoline with 0 dex simply erases the gasoline from existence. Should at least make a big puddle in the floor.

Other than that I don't know why 1 in every 20 refill attempts must result in my characters deciding that their hands don't want to work,

### PR DESCRIPTION
**Pull request by NickGrease**
As titled. Fixes #15243

### CODE REVIEW

File: src/iexamine.cpp [hunk 1]
```diff
@@ -73,7 +73,7 @@ void iexamine::gaspump(player *p, map *m, const tripoint &examp)
                 item spill( item_it->type->id, calendar::turn );
                 const auto min = item_it->liquid_charges( 1 );
                 ///\EFFECT_DEX decreases amount of gas spilled from a pump
-                const auto max = item_it->liquid_charges( 1 ) * 8.0 / p->dex_cur;
+                const auto max = item_it->liquid_charges( 1 ) * 8.0 / ( std::max( 1, p->dex_cur) );
```
Comment (codemime) [inline src/iexamine.cpp]: You could safely omit the braces.

Comment (NickGrease) [inline src/iexamine.cpp]: Will do, thanks.

File: src/iexamine.cpp [hunk 2]
```diff
@@ -73,7 +73,7 @@ void iexamine::gaspump(player *p, map *m, const tripoint &examp)
                 item spill( item_it->type->id, calendar::turn );
                 const auto min = item_it->liquid_charges( 1 );
                 ///\EFFECT_DEX decreases amount of gas spilled from a pump
-                const auto max = item_it->liquid_charges( 1 ) * 8.0 / p->dex_cur;
+                const auto max = item_it->liquid_charges( 1 ) * 8.0 / std::max( 1, p->dex_cur );
```
Comment (mugling) [inline src/iexamine.cpp]: This would work but there are several possible enhancements:

* You now can (and should where possible) pass `charges` to the `item` constructor.
* `max` is a confusing variable name and `auto` doesn't help either. Consider `qty` and `int`
* consider using `Character::get_dex()` accessor rather than the `dex_cur` member directly

Comment (NickGrease) [inline src/iexamine.cpp]: @mugling I'm trying to do:
```C++
auto items = g->m.i_at( examp );
for( item item_it : items ) {
  ....
if( item_it.charges < 1 ) {
   items.erase( item_it );
}
```
but the compiler is throwing an error on items.erase. I think it's because item_it isn't an iterator, but unsure how to fix.

Comment (mugling) [inline src/iexamine.cpp]:
```
for( auto iter : items ) {
    .... // iter is the iterator
}
```

Dependent upon what you're trying to do `std::remove` and `std::remove_if` are often less error-prone and more idiomatic.

What is your intended aim?

Comment (NickGrease) [inline src/iexamine.cpp]: > What is your intended aim?

Well, I made the changes you suggested, then I was trying to 'update' the code a bit. This is what I have so far.
```C++
void iexamine::gaspump(player &p, const tripoint &examp)
{
  ...
    auto items = g->m.i_at( examp );
    for( item item_it : items ) {
        if( item_it.made_of(LIQUID) ) {
            if( one_in(10 + p.get_dex()) ) {
                add_msg(m_bad, _("You accidentally spill the %s."), item_it.type_name());
                item spill( item_it.typeId(), calendar::turn );
                const auto min = item_it.charges;
                const auto max = item_it.charges * 8.0 / std::max( 1, p.get_dex() );
                spill.charges = rng( min, max );
                g->m.add_item_or_charges( p.pos(), spill, 1 );
                item_it.charges -= spill.charges;
                if( item_it.charges < 1 ) {
                    items.erase(  item_it ); <==== I'm doing something wrong.
                }
            } else {
              ...
            return;
        }
    }
    add_msg(m_info, _("Out of order."));
}
```

I promise I won't take much more of you time (today at least :)

Comment (NickGrease) [inline src/iexamine.cpp]: For now I'll stick to the original for loop until I get a better understanding.
