### PR TITLE
Ownership fixes - disallow crafting with / eating stolen items

### LINKED ISSUE #33134: faction ownership doesn't deter hungry player, guards oblivious
# Describe the bug

I'm allowed to cook, eat, and craft with owned items in direct view of members of the owning faction, without repercussions.

# Steps To Reproduce

Go to refugee center storage, and eat food right in front of the guards.

# Expected behavior
Guards and other NPCs berate me for trying to eat their food, and prevent it.

# Versions and configuration

Posting from phone, but win 7 on a very recent master.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Ownership fixes - disallow crafting with / eating stolen items"```

#### Purpose of change
Fixes #33134 

#### Describe the solution
You can now no longer eat directly from the refugee centers food shelves, the eat menu now acts similarly to the pickup menu.
If you eat an apple tha tbelongs to someone else from the E menu, then youll get a verbal warning, few more and then theyll start shooting.
They cant demand the item back, cos well, youve eaten it.

Also disallowed using their items as crafting components, so you cant make stuff out of their stuff.

Had to pass player parameter through the inventory form_from_map() code, so that it knew what to add to the inventory and what not to, based on the players faction, to form the crafting inventory.
Feels a bit inelegant, but ... idk how else to do that.

#### Describe alternatives you've considered
N/A
#### Additional context
I kinda want the eat menu to use the visual signifier of stealing status, ( the red ! next to the name ) but I could not penetrate that area of the code to find out how the inventory_picker code displays the names.

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -7004,12 +7004,50 @@ bool player::consume_med( item &target )
...
+                }
+                return false;
+            }
+        }
+        std::vector<npc *> witnesses;
+        for( npc &elem : g->all_npcs() ) {
+            if( rl_dist( elem.pos(), p.pos() ) < MAX_VIEW_DISTANCE && elem.sees( p.pos() ) ) {
+                witnesses.push_back( &elem );
+            }
+            for( npc *elem : witnesses ) {
```
Comment (BevapDin) [inline src/player.cpp]: I assume this and the following should be outside of the loop over `g->all_npcs()`.

File: src/inventory.cpp [hunk 2]
```diff
@@ -394,11 +394,31 @@ static int count_charges_in_list( const itype *type, const map_stack &items )
...
+                               bool assign_invlet,
+                               bool clear_path )
+{
+    form_from_map( g->m, origin, range, pl, assign_invlet, clear_path );
 }
 
 void inventory::form_from_map( map &m, const tripoint &origin, int range, bool assign_invlet,
                                bool clear_path )
+{
+    form_from_map( m, origin, range, nullptr, assign_invlet, clear_path );
```
Comment (BevapDin) [inline src/inventory.cpp]: Instead of making a bunch of new overloads, you could add the `player *` parameter to the existing functions and default it to be `nullptr`.

File: src/inventory.h [hunk 3]
```diff
@@ -124,10 +124,17 @@ class inventory : public visitable<inventory>
          * the player's worn items / weapon
          */
         void restack( player &p );
+        void form_from_map( const tripoint &origin, int range, player *pl, bool assign_invlet = true,
```
Comment (BevapDin) [inline src/inventory.h]: This overloads seems to be unnecessary. Calling `form_from_map( tripoint, int, player * )` will chose the overload `form_from_map( const tripoint &origin, int range, const player *pl, ... )` - the `player*` is automatically converted to `const player *`.

File: src/player.cpp [hunk 4]
```diff
@@ -5313,7 +5313,7 @@ void player::suffer()
 
         if( in_sleep_state() && !has_effect( effect_narcosis ) ) {
             inventory map_inv;
-            map_inv.form_from_map( g->u.pos(), 2 );
+            map_inv.form_from_map( g->u.pos(), 2, dynamic_cast<player *>( &g->u ) );
```
Comment (BevapDin) [inline src/player.cpp]: This cast shouldn't be necessary. `g->u` is a `avatar`, which is a `player`, so `&g->u` should be convertible to `player *`.

File: src/player.cpp (hunk 1 above)
Comment (davidpwbrown) [reply src/player.cpp]: Ah yes.

File: src/pickup.cpp [hunk 5]
```diff
@@ -171,6 +171,44 @@ static pickup_answer handle_problematic_pickup( const item &it, bool &offered_sw
...
+    };
+    std::string answer = query_popup()
+                         .context( "YES_NO_ALWAYS_NEVER" )
+                         .message( "%s",
+                                   _( "Picking up this item will be considered stealing, continue?" ) )
+                         .option( "YES", allow_key ) // yes, steal all items in this location that is selected
+                         .option( "NO", allow_key ) // no, pick up only what is free
+                         .option( "ALWAYS", allow_key ) // Yes, steal all items and stop asking me this question
+                         .option( "NEVER", allow_key ) // no, only grab free item and never ask me again
+                         .cursor( 1 ) // default to the third option `QUIT`
```
Comment (alkemann) [inline src/pickup.cpp]: hey can you fix my copypasta here.  should ofc be `// default to the second option, "NO"`

**Comment by Xenomorph-III** [comment]
Can you still eat it they're not able to see you?

**Comment by davidpwbrown** [comment]
> Can you still eat it they're not able to see you?

Yes, there wont be any confrontation if you arent witnessed eating it.

**Comment by davidpwbrown** [comment]
Well this currently doesnt work quite well, the choice isnt remembered in the menu until you press it twice.... but im done for the night so will come back to it tomorrow.

**Comment by LaVeyanFiend** [comment]
> They cant demand the item back, cos well, youve eaten it

Idk mate, make a surgeon angry and they might.

File: src/inventory.cpp [hunk 6]
```diff
@@ -391,13 +391,15 @@ static int count_charges_in_list( const itype *type, const map_stack &items )
     return 0;
 }
 
-void inventory::form_from_map( const tripoint &origin, int range, bool assign_invlet,
+void inventory::form_from_map( const tripoint &origin, int range, const player *pl,
+                               bool assign_invlet,
                                bool clear_path )
 {
-    form_from_map( g->m, origin, range, assign_invlet, clear_path );
+    form_from_map( g->m, origin, range, pl ? pl : nullptr, assign_invlet, clear_path );
```
Comment (AMurkin) [inline src/inventory.cpp]:
```suggestion
    form_from_map( g->m, origin, range, pl, assign_invlet, clear_path );
```

**Comment by LaVeyanFiend** [comment]
Does this also fix cutting up their items in front of them?

**Comment by davidpwbrown** [comment]
> Does this also fix cutting up their items in front of them?

Nope, I can do that in a separate PR.

File: src/iexamine.cpp [hunk 7]
```diff
@@ -4929,7 +4929,7 @@ static void smoker_load_food( player &p, const tripoint &examp,
     comps.push_back( item_comp( what->typeId(), amount ) );
 
     // select from where to get the items from and place them
-    inv.form_from_map( g->u.pos(), PICKUP_RANGE );
+    inv.form_from_map( g->u.pos(), PICKUP_RANGE, dynamic_cast<player *>( &g->u ) );
```
Comment (BevapDin) [inline src/iexamine.cpp]:
```suggestion
    inv.form_from_map( g->u.pos(), PICKUP_RANGE, &g->u );
```

File: src/iexamine.cpp [hunk 8]
```diff
@@ -5037,7 +5037,7 @@ static void mill_load_food( player &p, const tripoint &examp,
...
```
Comment (BevapDin) [inline src/iexamine.cpp]:
```suggestion
    inv.form_from_map( g->u.pos(), PICKUP_RANGE, &g->u );
```

**Comment by alkemann** [comment]
@davidpwbrown to avoid the problem of reseting on yes/no, we could drop the "keep" value and just have the `thief_mode` have 5 different values `ASK`, `YES`, `NO`, `HONEST`, `THIEF`  ( `HONEST` and `THIEF` being replacement for `NEVER` and `ALWAYS` respectively. The only other check we would need to do is that we ask if the `thief_mode` is `NO` OR `HONEST`, return before theft.

**Comment by ImportTaste** [comment]
I don't mean to intrude, but does adding this as a O.E milestone mean that this probably isn't going to be merged, say, within the next week?

**Comment by davidpwbrown** [comment]
> I don't mean to intrude, but does adding this as a O.E milestone mean that this probably isn't going to be merged, say, within the next week?

No, it means it's one of the things that would be wanted for 0.E to be considered ready, itll still get merged when its reviewed and considered ok to merge like normal, but its in a list of things that should be done before we consider 0.E release.
