### PR TITLE
rearrange spellcasting_finish

### LINKED ISSUE #39219: Magiclysm spell xp not incrementing from use
# After updating to 0.E-207-gb6cc66a (tiles) 10484, using spells in Magiclysm no longer adds xp, making it impossible to level up spells through use. 

I've verified with multiple spells, both with success xp and failure xp. The log message still shows the correct gain amounts but does not add them to the total.  Example "You lose your concentration. You gain 15 experience. New total 18753.
You lose your concentration. You gain 15 experience. New total 18753.
You lose your concentration. You gain 15 experience. New total 18753." but the new Total is never higher. 
Example 2 "You cast Grotesque Enhancement. You gain 76 experience. New total 19210.
You cast Grotesque Enhancement. You gain 77 experience. New total 19211.
You cast Grotesque Enhancement. You gain 76 experience. New total 19210."

The xp gained from book or scroll study DOES increment the "to Next Level" counter in the spell choice popup.

# Steps To Reproduce

1. Load a save using Magiclysm
2. Cast any spell
3. observe that the xp to next level counter does not change.

# Expected behavior

I expect the stated amount of gained xp to be reduced from the needed to next level counter.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-207-gb6cc66a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

# Additional context

<!-- Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Bugfixes "fix spells not gaining levels on cast"```
#### Purpose of change

Fixes #39219
#### Describe the solution

the lgtm fixes sort of changed how this worked, it needed a reference to the player's spell and it became a copy, so modifying it didn't modify the original spell. this version of it does not require a global, though it does not use the static function.
#### Testing

I haven't had the time to test this yet. if you run the game with magiclysm and cast any spell that has a max level higher than 0, if you gain a level in the spell then it works.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -4755,27 +4755,22 @@ static void blood_magic( player *p, int cost )
...
 void activity_handlers::spellcasting_finish( player_activity *act, player *p )
 {
     act->set_to_null();
     const int level_override = act->get_value( 0 );
-    spell spell_being_cast;
-    player_or_item_spell( p, spell_id( act->name ), level_override, spell_being_cast );
+    spell_id sp( act->name );
+
+    // if level is -1 then we know it's a player spell, otherwise we build it from the ground up
+    spell &spell_being_cast = level_override == -1 ? p->magic.get_spell( sp ) : spell( sp );
```
Comment (kevingranade) [inline src/activity_handlers.cpp:4765]:
```suggestion
    spell temp_spell( sp );
    spell &spell_being_cast = ( level_override == -1 ) ? p->magic.get_spell( sp ) : temp_spell;
```
