### PR TITLE
Unconditionally update overmap vision

### LINKED ISSUE #35059: Silo overmap view distance does not change with telescope or binoculars
# Describe the bug

When climbing a silo while carrying either a survivor telescope or pair of binoculars the view distance does not change. This is to say that the default via distance, i.e. ground level, is used even when venturing to the top. This is in striking contrast to the boost in range gained from climbing single-story buildings/radio towers. 

# Steps To Reproduce

1) Equip survivor telescope/binoculars
2) Climb a silo found in farm locations
3) check map 

# Expected behavior

As with climbing to the second story of a building or to the top of a radio tower, one would expect an increase of field of view when climbing a silo while equipping a tool with the "ZOOM" flag, such as a survivor telescope or pair of binoculars.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.D-8435-g5483ad5 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

### PR DESCRIPTION
**Pull request by ymber**
### Summary
SUMMARY: Bugfixes "Fix updating overmap vision"

#### Purpose of change
Fixes #35059 

#### Describe the solution
Unconditionally call `update_overmap_seen` from  `game::update_map`.

#### Describe alternatives you've considered
We might want to avoid calculating overmap vision every turn.

#### Testing
Compiles fine, overmap vision bug is fixed.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -10583,6 +10583,9 @@ point game::update_map( int &x, int &y )
         shift.y++;
     }
 
+    // Update what parts of the world map we can see
+    update_overmap_seen();
```
Comment (ifreund) [inline src/game.cpp]: I think you probably need to put this back where it was and add an additional call right before the early return on 10593.  Pretty sure it needs to happen after any potential map shift

File: src/game.cpp [hunk 2]
```diff
@@ -10586,6 +10586,8 @@ point game::update_map( int &x, int &y )
     if( shift == point_zero ) {
         // adjust player position
         u.setpos( tripoint( x, y, get_levz() ) );
+        // Update what parts of the world map we can see
+        update_overmap_seen();
```
Comment (ifreund) [inline src/game.cpp]: Would you mind adding a comment for the sake of the future developer scratching their head over why this needs to be here?
```suggestion
        // We need this call because even if the map hasn't shifted we may have changed z-level and can now see farther
        // TODO: only make this call if we changed z-level
        update_overmap_seen();
```
