### PR TITLE
Don't crash when forest mapgen requests groundcover from a biome with no groundcover

### LINKED ISSUE #72877: Crash when getting close to any caves in recent Innawood experimental build
### Describe the bug

I'm currently playing an innawood+dinomod+megafauna+MOM game and started out underground in a cave. Now, however, when going to explore other caves, it crashes with a segmentation fault as soon as the new cave enters the reality bubble. I tested it 3 different times, completely new worlds, new characters, and only cdda+innawood loaded and every time it would crash at any cave. I loaded to .G and did the same thing, new world, new char, only cdda+innawood and now my character can teleport and explore caves fine.

### Attach save file

[Knife River-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14895837/Knife.River-trimmed.tar.gz)
Knife river is my main one, innawood+dinomod+megafauna+MOM
[Bridge-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14895843/Bridge-trimmed.tar.gz)
Tested, new world, new char, same result, only CDDA+Innawood on latest experimental
[Harmar Heights-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14895851/Harmar.Heights-trimmed.tar.gz)
Tested, new world, new char, same result, only CDDA+Innawood on latest experimental

### Steps to reproduce

1. Generate a new world with only CDDA+Innawood, make sure to not pick the starting cave option or else it will CTD on latest experimental, my knife river is from an experimental a week ago.
2. Teleport outside the reality bubble of cave, then walk to it, it will CTD with a segmentation error.
3. Repeat on any cave on any world

### Expected behavior

I expected that I would be able to walk to a cave and pick up resources from it and possibly shelter during portal storms, not CTD.

### Screenshots

_No response_

### Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14895857/debug.log)
Knife River Debug Log
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14895860/debug.log)
Harmar Heights Debug Log
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14895862/debug.log)
Bridge Debug Log

### Additional context

Crash on Knife
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14895866/crash.log)
Crash on Harmar Heights
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14895869/crash.log)
Crash on Bridge
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14895871/crash.log)

### PR DESCRIPTION
**Pull request by akrieger**
#### Summary
None

#### Purpose of change
Fixes #72877, #72872. #72812 exposed that some forest mapgen code assumes adjacent biomes have groundcover. This is not true.

#### Describe the solution
Patch the code to fallback to regional groundcover like the other fallback cases use, in case the chosen adjacent biome in the feathering algorithm does not have groundcover of its own.

Also, noticed the adjacent biomes array wasn't being fully populated, with the last entry being skipped due to an off by one error in the initialization loop. Fix that too.

#### Testing
Use one of the repro saves from the issue, it doesn't crash anymore when mapgenning an innawoods cave tile.

### CODE REVIEW

**Comment by akrieger** [comment]
So to test the crash, what I did is I moved `cave_innawood` out of the first slot for forest terrains, and the crash stopped happening even on the save that already had a cave generated. There's something funky that arrangement is exposing, but I can't take the time to look harder so I'm just monkeypatching the crash away.

**Comment by Procyonae** [comment]
> There's something funky that arrangement is exposing, but I can't take the time to look harder so I'm just monkeypatching the crash away.

It probably expects the first one in the list to be the oter the others are mimicking somewhere along the line, I didn't really think twice when alphabetising them.
I'm going to bed now but I'll have a look in the morning.

**Comment by mqrause** [comment]
I got a theory: `cave_innawood` is a terrain that does not exist in vanilla dda. So because that is loaded first, it can't use the actual region settings from vanilla and creates a new empty one, which causes mapgen to trip over it.
https://github.com/CleverRaven/Cataclysm-DDA/blob/a1e69f11b86d2a63d604d3eefe4fc647f0d6fc5d/src/regional_settings.cpp#L175-L177

**Comment by akrieger** [comment]
*squint*

I'll change this to a debugmsg then which explains what needs to happen in the json, and fix the json for innawood.

**Comment by akrieger** [comment]
The other option is changing it so the forest biome regional setting loading code always prefers to inherit from the forest biome of the name of the region, if its available and in the terrains list (which seems to be always?), otherwise to use the first biome.

**Comment by mqrause** [comment]
> The other option is changing it so the forest biome regional setting loading code always prefers to inherit from the forest biome of the name of the region, if its available and in the terrains list (which seems to be always?), otherwise to use the first biome.

From what I can see, the loading code is kinda sketchy because it treats regional settings and overlays the same. But overlays can skip all the required checks, because they expect a regional setting to already exists to inherit all the required data from. Except they don't in cases like this. So it should be forbidden to just create a new forest_biome object when loading an overlay.

**Comment by akrieger** [comment]
oic, because `forest_mapgen_settings.unfinalized_biomes` will create an _empty_ biome if the string is novel. And this function is called from both loadpaths. I can throw an error instead if overlay = true and the first terrain is not seen yet.

File: src/regional_settings.cpp [hunk 1]
```diff
@@ -172,19 +172,26 @@ static void load_forest_mapgen_settings( const JsonObject &jo,
...
-                std::string first_ter = forest_biome_ter_keys.get_string( 0 );
-                load_forest_biome( forest_biome_jo, forest_mapgen_settings.unfinalized_biomes[first_ter],
-                                   overlay );
-                for( size_t biome_ter_idx = 1; biome_ter_idx < forest_biome_ter_keys.size(); biome_ter_idx++ ) {
+                std::string default_ter_name = member.name();
+                auto default_ter_it = forest_mapgen_settings.unfinalized_biomes.find( default_ter_name );
+                if( default_ter_it == forest_mapgen_settings.unfinalized_biomes.end() ) {
+                    forest_biome_jo.throw_error( "Terrain " + default_ter_name +
+                                                 " is not defined, cannot be used for forest biome." );
+                }
```
Comment (mqrause) [inline src/regional_settings.cpp:180]: I think this error should only throw if `overlay` is `true`. At some point the biome has to be created after all.
