### PR TITLE
Fix saving of player data

### LINKED ISSUE #48281: Item endochitin was loaded with charges, but can not have any!
# Describe the bug

 DEBUG    : Item endochitin was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2567

# Steps To Reproduce

Unknown, randomly pops up. Usually after loading a save game. The item in error varies.

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10088-g74e26ac [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

Had other similar errors previously, again seemingly randomly after loading a savegame.

 DEBUG    : Item mre_meatball_box was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2567

 DEBUG    : Item mre_bbqbeef_box was loaded with charges, but can not have any!

 FUNCTION : void item::io(Archive&) [with Archive = io::JsonObjectInputArchive]
 FILE     : src/savegame_json.cpp
 LINE     : 2567

### LINKED ISSUE #48291: Failed To Write Player data
# Describe the bug
The game is unable to save data.

# Steps To Reproduce
1.) Make a new world
2.) Start a new character
3.) Save and quit
4.) Fail message appears 

# Expected behavior
Being able to save my progress

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10255-g6b8dd00 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

Bugfixes "Fix saving of player data"

#### Purpose of change

Fixes #48291

#### Describe the solution

Change data format in a save to use array of float/int pairs instead of object with enum strings/ints (old format still could be read for backward compatibility).

**Old format:**
```JSON
"activity": { "NO_EXERCISE": 1, "LIGHT_EXERCISE": 0, "MODERATE_EXERCISE": 0, "BRISK_EXERCISE": 0, "ACTIVE_EXERCISE": 0, "EXTRA_EXERCISE": 0 }
```

**New format (note that zero values aren't saved to keep savegames smaller):**
```JSON
"activity": [ [ 1.000000, 1 ] ]
```

#### Describe alternatives you've considered

Keep perma-death in place.

#### Testing

Try loading and saving savegames from different game versions.

#### Additional context

- I've added some optional refactoring in second commit. The fix itself is in first commit and could be applied separately.
- There is another previously existing bug I discovered while working on current PR - it would be fixed in #48319.

Binary for testing:

[Cataclysm-vcpkg-static-Release-x64_48291.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6249439/Cataclysm-vcpkg-static-Release-x64_48291.zip)

### CODE REVIEW

**Comment by actual-nh** [comment]
General Build Matrix problem is that it couldn't find the g++-7 compiler.

**Comment by BrettDong** [comment]
GitHub Action removed GCC 7 and GCC 8 from the latest Ubuntu virtual environment image:
> GNU C++ 9.3.0, 10.2.0

Now: https://github.com/actions/virtual-environments/blob/ubuntu20/20210330.1/images/linux/Ubuntu2004-README.md
Yesterday: https://github.com/actions/virtual-environments/blob/ubuntu20/20210330.1/images/linux/Ubuntu2004-README.md

**Comment by actual-nh** [comment]
Travis:
```
src/avatar.cpp:1723:39: error: loop variable 'level' has type 'const std::pair<float, int> &' but is initialized with type 'const std::pair<const float, int>' resulting in a copy [-Werror,-Wrange-loop-construct]
    for( const std::pair<float, int> &level : activity_levels ) {
                                      ^
src/avatar.cpp:1723:10: note: use non-reference type 'std::pair<float, int>' to keep the copy or type 'const std::pair<const float, int> &' to prevent copying
    for( const std::pair<float, int> &level : activity_levels ) {
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/avatar.cpp:1739:51: error: loop variable 'member' has type 'const std::pair<std::string, float> &' (aka 'const pair<basic_string<char>, float> &') but is initialized with type 'const std::pair<const std::__cxx11::basic_string<char>, float>' resulting in a copy [-Werror,-Wrange-loop-construct]
        for( const std::pair<std::string, float> &member : activity_levels_map ) {
                                                  ^
src/avatar.cpp:1739:14: note: use non-reference type 'std::pair<std::string, float>' (aka 'pair<basic_string<char>, float>') to keep the copy or type 'const std::pair<const std::__cxx11::basic_string<char>, float> &' to prevent copying
        for( const std::pair<std::string, float> &member : activity_levels_map ) {
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
Makefile:962: recipe for target 'obj/avatar.o' failed
```

File: src/character.cpp [hunk 1]
```diff
@@ -5056,26 +5056,20 @@ int Character::get_stored_kcal() const
...
-        return _( "LIGHT_EXERCISE" );
-    } else if( level <= MODERATE_EXERCISE ) {
-        return _( "MODERATE_EXERCISE" );
-    } else if( level <= BRISK_EXERCISE ) {
-        return _( "BRISK_EXERCISE" );
-    } else if( level <= ACTIVE_EXERCISE ) {
-        return _( "ACTIVE_EXERCISE" );
-    } else {
-        return _( "EXTRA_EXERCISE" );
+static std::string activity_level_to_str( float level )
```
Comment (ZhilkinSerg) [inline src/character.cpp:5059]:
```suggestion
static std::string exert_lvl_to_str( float level )
```

File: src/character.cpp [hunk 2]
```diff
@@ -5056,26 +5056,20 @@ int Character::get_stored_kcal() const
...
+{
+    for( const std::pair<std::string, float> &activity_level : activity_levels_map ) {
```
Comment (ZhilkinSerg) [inline src/character.cpp:5061]:
```suggestion
    for( const std::pair<const std::string, float> &activity_level : activity_levels_map ) {
```

File: src/character.cpp [hunk 3]
```diff
@@ -5056,26 +5056,20 @@ int Character::get_stored_kcal() const
...
+        }
     }
+    return ( --activity_levels_map.end() )->first;
 }
+
 std::string Character::debug_weary_info() const
 {
     int amt = activity_history.weariness();
-    std::string max_act = exert_lvl_to_str( maximum_exertion_level() );
+    std::string max_act = _( activity_level_to_str( maximum_exertion_level() ) );
```
Comment (ZhilkinSerg) [inline src/character.cpp:5072]:
```suggestion
    std::string max_act = exert_lvl_to_str( maximum_exertion_level() );
```

File: src/character.cpp [hunk 4]
```diff
@@ -5056,26 +5056,20 @@ int Character::get_stored_kcal() const
...
-    } else {
-        return _( "EXTRA_EXERCISE" );
+static std::string activity_level_to_str( float level )
+{
+    for( const std::pair<std::string, float> &activity_level : activity_levels_map ) {
+        if( level <= activity_level.second ) {
+            return activity_level.first;
+        }
     }
+    return ( --activity_levels_map.end() )->first;
```
Comment (ZhilkinSerg) [inline src/character.cpp:5066]:
```suggestion
    return _( ( --activity_levels_map.end() )->first );
```

File: src/character.cpp [hunk 5]
```diff
@@ -5056,26 +5056,20 @@ int Character::get_stored_kcal() const
...
 }
+
```
Comment (ZhilkinSerg) [inline src/character.cpp:5068]:
```suggestion
```

File: src/character.cpp [hunk 6]
```diff
@@ -5056,26 +5056,20 @@ int Character::get_stored_kcal() const
...
-        return _( "BRISK_EXERCISE" );
-    } else if( level <= ACTIVE_EXERCISE ) {
-        return _( "ACTIVE_EXERCISE" );
-    } else {
-        return _( "EXTRA_EXERCISE" );
+static std::string activity_level_to_str( float level )
+{
+    for( const std::pair<std::string, float> &activity_level : activity_levels_map ) {
+        if( level <= activity_level.second ) {
+            return activity_level.first;
```
Comment (ZhilkinSerg) [inline src/character.cpp:5063]:
```suggestion
            return _( activity_level.first );
```

**Comment by wapcaplet** [comment]
Using this branch, I am able to save a new game successfully. However, that game cannot be loaded again, giving this error followed by a crash:

```
 DEBUG    : Bad save json
Json error: <unknown source file>:22:28,706: Integers cannot have a decimal point or negative order of magnitude.

 "active_mission": -1, "active_missions": [  ], "completed_missions": [  ], "failed_missions": [  ], "show_map_memory": true, "assigned_invlet": [  ], "invcache": [  ], "calorie_diary": [ { "spent": 0, "gained": 15, "activity": [ [ 0.000000,
                                                                                                                                                                                                                                                 ^
                                                                                                                                                                                                                                                  1 ] ] } ], "preferred_aiming_mode": "" },
  "player_messages": { "messages": [ { "turn": 5212800, "message": "You have survived the initial wave of panic, and have achieved (relative) safety in one of the many government evac shelters.", "c

 FUNCTION : void game::unserialize(std::istream &)
 FILE     : src/savegame.cpp
 LINE     : 238
```

**Comment by ZhilkinSerg** [comment]
Thanks for testing - I was actually getting a different error when loading your save (because I used `at` instead of `[]` operator) and I fixed that.

I can load your save with latest changes, but saving it again changes activity level for each subsequent save (looks like it adds 1 time of `NO_EXERCISE` activity):

**before**:
```JSON
"activity": [ [ 0.000000, 1 ], [ 1.000000, 1 ] ]
```
**after save 1:**
```JSON
"activity": [ [ 0.000000, 1 ], [ 1.000000, 1 ] ]
```
**after save 2:**

```JSON
"activity": [ [ 0.000000, 1 ], [ 1.000000, 2 ] ]
```

**Comment by actual-nh** [comment]
The github ones were resource-related failures; feel free to cancel any of the #47791 5a229a8-commit (or before) jobs if desirable to be able to rerun this one's tests.

**Comment by actual-nh** [comment]
> **after save 2:**
> 
> ```json
> "activity": [ [ 0.000000, 1 ], [ 1.000000, 2 ] ]
> ```

What's the `0.000000, 1` entry from?

**Comment by ZhilkinSerg** [comment]
> 
> 
> > **after save 2:**
> > ```json
> > "activity": [ [ 0.000000, 1 ], [ 1.000000, 2 ] ]
> > ```
> 
> What's the `0.000000, 1` entry from?

That's just a manually added entry - the issue there is with `1.000000`.

File: src/character.cpp [hunk 7]
```diff
@@ -5058,19 +5058,12 @@ int Character::get_stored_kcal() const
...
-        return _( "MODERATE_EXERCISE" );
-    } else if( level <= BRISK_EXERCISE ) {
-        return _( "BRISK_EXERCISE" );
-    } else if( level <= ACTIVE_EXERCISE ) {
-        return _( "ACTIVE_EXERCISE" );
-    } else {
-        return _( "EXTRA_EXERCISE" );
+    for( const std::pair<const std::string, float> &activity_level : activity_levels_map ) {
+        if( level <= activity_level.second ) {
+            return _( activity_level.first );
```
Comment (actual-nh) [inline src/character.cpp:5063]: I am guessing the `_(` should work because of the previously-translated strings?

Comment (BrettDong) [inline src/character.cpp:5063]: `exert_lvl_to_str()` is for debug output so actually it doesn't need to be translated.
```suggestion
            return activity_level.first;
```

File: src/character.cpp [hunk 8]
```diff
@@ -5058,19 +5058,12 @@ int Character::get_stored_kcal() const
...
+        }
     }
+    return _( ( --activity_levels_map.end() )->first );
```
Comment (BrettDong) [inline src/character.cpp:5066]:
```suggestion
    return ( --activity_levels_map.end() )->first;
```

**Comment by kevingranade** [comment]
I could reproduce locally and this fixes the primary issue for me, please post if you still have an error after this is merged (i.e. wapletcaplet's thing), and we need to track down the phantim activity entries thing, but that's a lot less pressing than total save-eating disfunction :D

**Comment by wapcaplet** [comment]
I am still getting the error and subsequent crash when saving and loading a new game:

```
DEBUG    : Bad save json
Json error: <unknown source file>:22:28,706: Integers cannot have a decimal point or negative order of magnitude.
```

Save made immediately after creating a new game: [StillCrash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6252992/StillCrash.zip)

**Comment by linonetwo** [comment]
This seems to be a breaking change, can you manage to fix the Android release CI, so sync mod from PC to Android won't cause a save corruption?
