### PR TITLE
Do not save map on init failure in tests

### LINKED ISSUE #71050: error during JSON loading in tests results in error spam due to trying to save test world
### Describe the bug

The following results in a JSON error 

`Json error: data/json/snippets/snippets.json:399:14: missing mandatory member "text"`

```diff
diff --git a/data/json/snippets/snippets.json b/data/json/snippets/snippets.json
index a20564e0c4..d385b758c5 100644
--- a/data/json/snippets/snippets.json
+++ b/data/json/snippets/snippets.json
@@ -393,6 +393,11 @@
       }
     ]
   },
+  {
+    "type": "snippet",
+    "category": "<punc>",
+    "text": [ { "a": null } ]
+  },
   { 
     "type": "snippet",
     "category": "pyromania_withdrawal",
```

But I cannot see it because the test log is filled with
```
ERROR : src/map.cpp:8013 [void map::saven(const tripoint &)] Tried to save submap node (0) but it's not loaded
...
ERROR : src/map.cpp:8013 [void map::saven(const tripoint &)] Tried to save submap node (2540) but it's not loaded
```

### Attach save file

N/A

### Steps to reproduce

1. Apply the diff above.
2. Run `tests/cata_test` (no arguments)

### Expected behavior

I am shown the JSON error, and no attempt is made to save the test world.

### Screenshots

_No response_

### Versions and configuration

On f2c8c58036e1a48099055586e77fe175e9f4cca4, Ubuntu Linux 22.04

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
None

#### Purpose of change
* Fix #71050

#### Describe the solution
Do not save non-existent maps if game initialization fails.

#### Testing
* All tests pass -> Test save is removed as expected
* Some test cases fail -> Test save is kept as expected
* JSON error -> Test world is not saved, and no map save error spam

### CODE REVIEW

File: tests/test_main.cpp [hunk 1]
```diff
@@ -203,7 +203,14 @@ struct CataListener : Catch::TestEventListenerBase {
...
+            try {
+                init_global_game_state( mods, option_overrides_for_test_suite, user_dir );
+            } catch( ... ) {
+                DebugLog( D_INFO, DC_ALL ) << "Error during initializing global game state" << std::endl;
+                // NOLINTNEXTLINE(cata-tests-must-restore-global-state)
+                error_during_initialization = true;
+                throw;
+            }
             // NOLINTNEXTLINE(cata-tests-must-restore-global-state)
             error_during_initialization = debug_has_error_been_observed();
```
Comment (Qrox) [inline tests/test_main.cpp:215]: `error_during_initialization` is also set when there are debug messages, but in that case the save should probably still be saved if loading succeeds.

Comment (BrettDong) [reply tests/test_main.cpp:216]: I changed it to a dedicated variable to mark initialisation failure.
