### PR TITLE
Hallucinations don't reset limb healing

### LINKED ISSUE #22849: Hallucination Attacks Reset Broken Limb Healing Progress
Game version: 7093 0.Cooper

Operating system: Windows

Tiles or curses: Tiles

Mods active: Several, none expected to be a cause.

### Expected behavior
Being attacked by hallucinated monsters (via Schizophrenia trait) does not actually damage the player.

### Actual behavior
If attacked by hallucinated monsters and hit in a splinted and healing broken limb, this re-breaks the limb.

### Steps to reproduce the behavior
1: Create character with Schizophrenia trait
2: Break a limb
3: Wait for hallucinations, and be attacked
4: Observe health screen.

### PR DESCRIPTION
**Pull request by Rawng**
Prevent hallucinated enemies from removing the mending effect when they attack the player.

This resolves #22849

~~I'm not sure why the test is failing. It's only for one compiler and this change wouldn't seem to affect shooting accuracy except through contrived circumstances.~~

### CODE REVIEW

**Comment by BorkBorkGoesTheCode** [comment]
The same compiler error happened to me. It's not your doing.

File: src/player.cpp [hunk 1]
```diff
@@ -4151,7 +4151,7 @@ void player::apply_damage(Creature *source, body_part hurt, int dam)
         hp_cur[hurtpart] = 0;
     }
 
-    if( hp_cur[hurtpart] <= 0 ) {
+    if( source->is_hallucination() != true && hp_cur[hurtpart] <= 0 ) {
```
Comment (BevapDin) [inline src/player.cpp]: Why `foo != true` instead of just `!foo`? You must also check `source` being non-null as there are several calls to that function that supply `nullptr` as first argument.

**Comment by Rawng** [comment]
@BevapDin thanks for the review, really should have checked that first.

Updated with your recommendations.

File: src/player.cpp [hunk 2]
```diff
@@ -4151,7 +4151,7 @@ void player::apply_damage(Creature *source, body_part hurt, int dam)
         hp_cur[hurtpart] = 0;
     }
 
-    if( hp_cur[hurtpart] <= 0 ) {
+    if( hp_cur[hurtpart] <= 0 && (source != nullptr && !source->is_hallucination())) {
```
Comment (boydkr) [inline src/player.cpp]: maybe just check if `dam > 0` instead?

Comment (Rawng) [reply src/player.cpp]: That fix has already been rejected as far as I'm aware

Comment (boydkr) [reply src/player.cpp]: What's the `source` when you fall in a pit or trip on rubble?  If it's `null`, then those would prevent mending from resetting

Comment (Rawng) [reply src/player.cpp]: Good point. I didn't see that in my review but it's likely to be null.

Looks like it'll just have to be some extra logic of that's the case.

Comment (kevingranade) [reply src/player.cpp]: I think you can just do ```( source == nullptr || !source->is_hallucination() )```
That way damage from the environment will still reset mending.

Comment (Rawng) [reply src/player.cpp]: @kevingranade thank you... this really shouldn't have been so difficult for me -.-

**Comment by Rawng** [comment]
Updated per recommendations. Tested and the desired behavior is observed.

Thanks to everyone for the reviews and advice.
