### PR TITLE
Convert container to its unsealed variant only if unsealing has actually happened

### LINKED ISSUE #17924: Changing your mind about unloading aluminum/tin cans of liquid unseals it
To reproduce:
Spawn an aluminum can of energy cola and a tin can of red sauce.
Unload them, and press escape when asked what to do with the liquid.
The items are now an opened aluminum can of energy cola and an opened tin can of red sauce.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #17924.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
This sounds incredibly fragile - `contents.front()` may not even exist (this would cause a crash).
Additionally, directly comparing charges is a bit of a hack.

It may be a bit ugly and inefficient, but a more robust solution would be to copy the entire `contents` vector to a temporary variable and compare its value to one after removal. From what I recall, `vector::operator==` only returns true if all elements are identical, which is exactly what we want to compare here.

**Comment by kevingranade** [comment]
The first invocation of contents.front() is safe because it immediately follows a (failing) check of contents.empty(), the second would need another contents.empty() check.  IMO it would be fine if it checked both contents.size() and contents.front().charges.  I'm not totally against the deep check, though that might end up more involved than you expect, what does the implementation of item::operator== look like?

**Comment by Coolthulhu** [comment]
> what does the implementation of item::operator== look like?

Oops, I was wrong - there is none.
While default `operator==` would be enough, as the `item` class has no mutable caches at the moment, it could make implementing said caches harder. And I'm sure I want one such cache (name cache - for NPC/autopickup recognition) to exist.

So I guess size and charges would be good enough. I can't think of a counterexample.

**Comment by Night-Pryanik** [comment]
How this size check should like? Similar to charges - 

```
int old_size = it.contents.size();
...
if( it.contents.front().charges != old_charges && it.contents.size() != old_size ) {
...
```
?

**Comment by Coolthulhu** [comment]
Yes, but you must check size before checking charges.

**Comment by Night-Pryanik** [comment]
It worked, but have minor issue.
Now we don't have non-resealable containers that can hold more than 1 volume and have non-null `unseals_into`, so we can't partially unload these containers.
But if we increase `contains` value to, say, 10, we could do that.

Before adding size check it worked like this: we have 10 volume unsealed tin can of red sauce, and an empty 2 volume plastic bottle. Unloading red sauce to bottle leaves us with `opened tin can of red sauce (8)`.

Adding size check leaves us with ordinary, unsealed `tin can of red sauce (8)`.

**Comment by Coolthulhu** [comment]
Use `||` instead of `&&` in the check.

File: src/game.cpp [hunk 1]
```diff
@@ -10715,7 +10717,9 @@ bool game::unload( item &it )
             u.moves -= mv;
             return true;
         } ), it.contents.end() );
-        it.on_contents_changed();
+        if( it.contents.size() != old_size || it.contents.front().charges != old_charges ) {
```
Comment (codemime) [inline src/game.cpp]: This looks a bit fragile and won't work as expected if an item from somewhere in the middle of `it.contents` changes its charge.  I suppose something like this would be a bit better (though, still quite ugly):

```c++
bool changed = false;
it.contents.erase( std::remove_if( it.contents.begin(), it.contents.end(), [this, &changed]( item& e ) {
    long old_charges = e.charges;
    const bool consumed = add_or_drop_with_msg( u, e );
    changed = changed || consumed || e.charges != old_charges;
    if( consumed ) {
        u.mod_moves( -u.item_handling_cost( e ) );
    }
    return consumed;
} ), it.contents.end() );

if( changed ) {
    it.on_contents_changed();
}
```
