### PR TITLE
Fix "CTRL+C breaks screen refreshing" 

### LINKED ISSUE #20047: CTRL+C (SIGINT) bouncing between `y`/`n` is bypassable, and breaks screen refreshing
System: Arch Linux, curses, self-built, current git master (`0.C-20619-g463eeccf51`), using `gnome-terminal`.

Bisected to f3b564bd82458da447454712849e50ae948c8b97 (part of PR #19961, first commit). Commit has a missing `#include "input.h"` in `src/iuse_software_kitten.cpp`, which is added in fea2ea55229c8c937c5c47e84e181c4bdb61c31d (next commit).

Previously, the bouncing couldn't be bypassed by pressing left/right (bouncing would continue). It required pressing either `y` or `n`.

In its currect form, CTRL+C is broken: pressing any "unhandled" key stops the query bouncing. Selecting `n` stops the screen from auto-refreshing until a key is pressed again. I.e., rain "stops falling".

Ping @BevapDin as author of #19961.

### PR DESCRIPTION
**Pull request by BevapDin**
Fixes #20047

Removes the strange bouncing of the default answer (y or n). It comes from the previously set timeout (used to draw raindrops in the main game loop). Instead the timeout is reset, the y/n query appears and the timeout is set again.

### CODE REVIEW

File: src/main.cpp [hunk 1]
```diff
@@ -564,4 +566,5 @@ void exit_handler(int s)
 
         exit( exit_status );
     }
+    inp_mngr.set_timeout( old_timeout );
```
Comment (keyspace) [inline src/main.cpp]: Would doing

``` c++
g->refresh_all();
```

be inappropriate?

**Comment by keyspace** [comment]
Checked locally - fixed indeed.

Sidenote: thought the bouncing was intentionally annoying.

File: src/main.cpp (hunk 1 above)
Comment (BevapDin) [inline src/main.cpp]: Strikes me as potentially dangerous. `refresh_all` accesses many things, some may not exist while the game is still in the main menu. It also refreshes only the main terrain window, which is pointless if another window (e.g. overmap, inventory, ...) is currently open.

Comment (keyspace) [inline src/main.cpp]: Ah, never mind then.

Comment (keyspace) [inline src/main.cpp]: Originally proposed it because CTRL+C leaves a black rectangle underneath, but CTRL+C is enough of an edge case not to bother.

Only tried in-game, not the main menu, so yeah, _bad idea_.
