### PR TITLE
Return 0 on fuel consumption if the engine isn't running

### LINKED ISSUE #28684: Game crash after vehicle crash
After crashing vehicle and getting a message it was too heavy for its engines, I attempted to 'e'xamine vehicle, at which point the game crashed.

The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: ./config/crash.log
VERSION: 0.D-215-g6b7bfbff67
TYPE: Signal
MESSAGE: SIGFPE: Arithmetical error
STACK TRACE:

        ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x43) [0x5583236d28be]
        ./cataclysm-tiles(+0x477ffc) [0x5583236c3ffc]
        ./cataclysm-tiles(+0x47822c) [0x5583236c422c]
        /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20) [0x7fd0bae9cf20]
        ./cataclysm-tiles(_ZNK7vehicle20consumption_per_hourERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEi+0xf8) [0x558323c38ba6]
        ./cataclysm-tiles(_ZN7vehicle20print_fuel_indicatorERKN10catacurses6windowEiiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt3mapIS9_iSt4lessIS9_ESaISt4pairISA_iEEEbb+0x35a) [0x558323c42d72]
        ./cataclysm-tiles(_ZN7vehicle21print_fuel_indicatorsERKN10catacurses6windowEiiibbbb+0x290) [0x558323c433fa]
        ./cataclysm-tiles(_ZNK12veh_interact13display_statsEv+0xdf8) [0x558323c03432]
        ./cataclysm-tiles(_ZN12veh_interact16allocate_windowsEv+0x223) [0x558323c064ed]
        ./cataclysm-tiles(_ZN12veh_interactC2ER7vehicleii+0x787) [0x558323c06caf]
        ./cataclysm-tiles(_ZN12veh_interact3runER7vehicleii+0x2a) [0x558323c0bfe2]
        ./cataclysm-tiles(_ZN4game12exam_vehicleER7vehicleii+0x2a) [0x55832374e2ce]
        ./cataclysm-tiles(_ZN6Pickup7pick_upERK8tripointi+0x1477) [0x558323aee3d7]
        ./cataclysm-tiles(_ZN4game13handle_actionEv+0x166b) [0x5583237ab9db]
        ./cataclysm-tiles(_ZN4game7do_turnEv+0x387) [0x5583237739f7]
        ./cataclysm-tiles(main+0x1293) [0x558323529aeb]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7fd0bae7fb97]
        ./cataclysm-tiles(_start+0x2a) [0x5583235548ba]

        Attempting to repeat stack trace using debug symbols...
        debug_write_backtrace(std::ostream&)
        ??:?
        log_crash
        crash.cpp:?
        signal_handler
        crash.cpp:?
        ??
        ??:0
        vehicle::consumption_per_hour(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) const
        ??:?
        vehicle::print_fuel_indicator(catacurses::window const&, int, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, int> > >, bool, bool)
        ??:?
        vehicle::print_fuel_indicators(catacurses::window const&, int, int, int, bool, bool, bool, bool)
        ??:?
        veh_interact::display_stats() const
        ??:?
        veh_interact::allocate_windows()
        ??:?
        veh_interact::veh_interact(vehicle&, int, int)
        ??:?
        veh_interact::run(vehicle&, int, int)
        ??:?
        game::exam_vehicle(vehicle&, int, int)
        ??:?
        Pickup::pick_up(tripoint const&, int)
        ??:?
        game::handle_action()
        ??:?
        game::do_turn()
        ??:?
        main
        ??:?
        __libc_start_main
        /build/glibc-OTsEL5/glibc-2.27/csu/../csu/libc-start.c:344
        _start
        ??:?

### PR DESCRIPTION
**Pull request by esotericist**
#### Summary
SUMMARY: Bugfixes "Prevents div by 0 when examining vehicle"

#### Purpose of change
Fixes #28684 

It's possible for a vehicle to be moving (have a `velocity` > 0) and not be running (`engine_on` = false). This can cause a divide-by-zero when calculating fuel costs on a vehicle which has had the engine cut off but not yet come to a complete halt (such as when examining a vehicle after you 'stop driving' but the vehicle hasn't completely zeroed velocity yet).

See: [`vehicle::consumption_per_hour`]( https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/vehicle.cpp#L2909 )

#### Describe the solution
Added a check at the top of consumption_per_hour to return 0 if the engine is off.

#### Describe alternatives you've considered
I also considered replacing the `is_moving()` check in the middle of the method with `!( engine_on )`, but it seemed more natural to shortcut out of calculating fuel consumption up at the top.

I don't know for sure if there's anything my change might potentially break.

#### Additional context
I'm still not super clear why others couldn't replicate this with the save I provided in #28684 but my best guess is that for some reason time was passing before they attempted to examine the vehicle (resulting in it coming to a complete halt). 

I know if I wait a single turn after loading that save file, the crash does NOT occur, but if I examine the vehicle immediately after the save loads, I get the crash.

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -2892,7 +2892,7 @@ int vehicle::basic_consumption( const itype_id &ftype ) const
 int vehicle::consumption_per_hour( const itype_id &ftype, int fuel_rate_w ) const
 {
     item fuel = item( ftype );
-    if( fuel_rate_w == 0 || fuel.has_flag( "PERPETUAL" ) ) {
+    if( fuel_rate_w == 0 || fuel.has_flag( "PERPETUAL" ) || !( engine_on ) ) {
```
Comment (mlangsdorf) [inline src/vehicle.cpp]: remove the parentheses from engine_on.  it's a bool, negating it is a normal and uncomplicated thing to do.

Thanks for finding and debugging this.

Comment (esotericist) [reply src/vehicle.cpp]: Sorry, I got used to stuff like that while working on java stuff. Which is *also* alien to me. Change made.
