### PR TITLE
Fix crash activating item outside of inventory

### LINKED ISSUE #35673: Crash when activating item not from inventory
# Describe the bug

When using the (a)ctivate command on some items outside of the player's inventory, the game crashes.

# Steps To Reproduce

1. Have any activate-able item nearby but not in player inventory
2. Use (a)ctivate on the item
3. The game crashes

# Expected behavior

The item should activate as normal.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-9615-gefbacc3 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

I initially discovered this bug when trying to unfold a vehicle, but others have since reported many other items for which it occurs. I have updated this post to reflect the broader scope of the bug. It is generally advised to not attempt the activation of items outside of player inventory until this is fixed. However, there are some items which appear to still work just fine (I have tested the filled charcoal kiln and lit charcoal kiln and they worked successfully, but you do so at your own risk).

[Logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3882358/Logs.zip)
[Crash Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3882359/Crash.Test.zip)

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
SUMMARY: Bugfixes "Fix crash activating item outside of inventory"

#### Purpose of change
Fix #35673

#### Describe the solution
Properly create a new `item_location` after obtaining the item.

#### Testing
Reproduced the crash, then wrote this code. Can no longer reproduce the crash.

#### Additional context
This code currently allows players to teleport items from the ground to their inventory with no move cost.  This probably isn't intended behavior, but I think that's out of scope for this crash fix PR.

### CODE REVIEW

File: src/avatar_action.cpp [hunk 1]
```diff
@@ -1000,20 +1001,25 @@ void avatar_action::use_item( avatar &you, item_location &loc )
...
-            loc.obtain( you );
+            const int obtain_cost = loc.obtain_cost( you );
+            loc = item_location( you, &you.i_at( loc.obtain( you ) ) );
+            if( !loc ) {
+                debugmsg( "Failed to obtain target item" );
+                return;
+            }
+
+            // TODO: the following comment is inaccurate and this mechanic needs to be rexamined
             // This method only handles items in te inventory, so refund the obtain cost.
```
Comment (ZhilkinSerg) [inline src/avatar_action.cpp]:
```suggestion
            // This method only handles items in the inventory, so refund the obtain cost.
```

Comment (ifreund) [reply src/avatar_action.cpp]: fixed :+1:

File: src/avatar_action.cpp [hunk 2]
```diff
@@ -1000,20 +1001,25 @@ void avatar_action::use_item( avatar &you, item_location &loc )
...
-            use_loc = true;
+        if( loc->has_flag( "ALLOWS_REMOTE_USE" ) ) {
+            use_in_place = true;
         } else {
-            int obtain_cost = loc.obtain_cost( you );
-            loc.obtain( you );
-            // This method only handles items in te inventory, so refund the obtain cost.
+            const int obtain_cost = loc.obtain_cost( you );
+            loc = item_location( you, &you.i_at( loc.obtain( you ) ) );
+            if( !loc ) {
```
Comment (BevapDin) [inline src/avatar_action.cpp]: I believe this will never trigger. `you.i_at` returns a reference, therefor the pointer passed to `item_location` will always be non-null, which in turn makes `loc` always valid (even through it refers to the null-item returned by `i_at`).

You need to check either the result of `i_at` (via `item::is_null`) or check the result of `loc.obtain`.

File: src/avatar_action.cpp [hunk 3]
```diff
@@ -1000,20 +1001,25 @@ void avatar_action::use_item( avatar &you, item_location &loc )
             return;
         }
 
-        const item &it = *loc.get_item();
-        if( it.has_flag( "ALLOWS_REMOTE_USE" ) ) {
-            use_loc = true;
+        if( loc->has_flag( "ALLOWS_REMOTE_USE" ) ) {
```
Comment (BevapDin) [inline src/avatar_action.cpp]: This will be true if the item has the flag, regardless of *where* the item currently is. That means: it does not actually check *where* the item is (map/inventory). Is this the intended check?

File: src/avatar_action.cpp (hunk 2 above)
Comment (ifreund) [reply src/avatar_action.cpp]: Yes, you're right. Good catch

File: src/avatar_action.cpp (hunk 3 above)
Comment (ifreund) [reply src/avatar_action.cpp]: I believe so.  Items with this flag are able to be activated from anywhere and are not meant to be picked up.  For example, a kiln.
