### PR TITLE
Change the code for deployable furniture to work for all item types

### LINKED ISSUE #30921: Deploying a wielded mattress does not remove it from inventory
# Describe the bug

Deploying a wielded mattress does not remove it from inventory.

# Steps To Reproduce

1. Deconstruct a bed.
2. Wield mattress.
3. Deploy mattress.

# Expected behavior

Deploying a wielded mattress should remove it from inventory.

# Screenshots

Screenshot (2042)
Screenshot (2043)
Screenshot (2044)

# Versions and configuration

 - OS: Windows 10
 - Game Version: 9062
 - Graphics version: Tiles
 - Mods loaded: None

# Additional context

### PR DESCRIPTION
**Pull request by Yunatan**
#### Summary
```SUMMARY: Bugfixes "Change the code for deployable furniture to work for all item types"```

#### Purpose of change
Fixes #30921 - Deploying a wielded mattress does not remove it from inventory

#### Describe alternatives you've considered
#30960

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -9290,7 +9290,7 @@ bool player::invoke_item( item *used, const std::string &method, const tripoint
 
     if( used->is_tool() || used->is_medication() || used->get_contained().is_medication() ) {
         return consume_charges( *actually_used, charges_used );
-    } else if( used->is_bionic() && charges_used > 0 ) {
+    } else if( used->is_bionic() && charges_used > 0 || used->is_deployable() ) {
```
Comment (anothersimulacrum) [inline src/player.cpp]:
```suggestion
    } else if( ( used->is_bionic() && charges_used > 0 ) || used->is_deployable() ) {
```
