### PR TITLE
Performance Improvement item::can_contain 

### LINKED ISSUE #60277: large amount of stackable items in inventory causing lag when using(a) or picking up(g) items
### Describe the bug

A save folder has been provided(.zip), this happened on Experimental(2022-08-18-1622).
We tried to search for similar issues with a generic "lag" word and looked through a dozen but none seemed too similar.

In more detail, the character has a daypack with 448 cotton patches inside(amongst various other items) and a large amount of items in the top left corner from them(numpad 7), when trying to pick up items(with "g") from that top left corner or trying to open the "use item" menu(with "a") the game loads for ~14s(slightly less when opening the "use item" menu) before opening the requested menu.
When either the whole daypack, or at least all 448 cotton patches are dropped from the daypack, the game only loads for  ~1s before opening the requested menu.

### Steps to reproduce

1. Load the save.
2. Try opening the "use item" or "pick up item" menus, the latter from that specific tile.

### Expected behavior

Expected the game to load the requested menus much quicker.

### Screenshots

image

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Linuxmint; Description: Linux Mint 20.2; Release: 20.2; Codename: uma; 
- Game Version: f54229a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

[2035.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/9376276/2035.zip)

### PR DESCRIPTION
**Pull request by EIIKaO**
#### Summary
Performance "Performance Improvement for item::can_contain"

#### Purpose of change
- Fixes #60277
Delay was reduced from 16 seconds to 2 seconds.

#### Describe the solution
- The delay occurs when `item::can_contain` was recursed, avoid the recurrence by checking in advance.

#### Describe alternatives you've considered
- Trying to improve performance `item::volume` related process, the true bottleneck, revealed in the analysis by andrei8l.

#### Testing
1. Load the savedata what attached by issue authors.
2. Invoke [g]et command and press num 7 key(target to NW).
3. After a second or two, the pickup screen appears( the latest release build takes 16-20 seconds ).

Also made a debugging code and verified in-game testing that there was no difference between the return value before and after the fix as far as I could grab something at random there and then.

#### Additional context
During testing, `pocket_type::MOD` and others were acting suspiciously (although eventually adjusted them so that there was no difference). Please point out if you know of any cases where there would be a difference in return values.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -10243,15 +10243,24 @@ ret_val<void> item::can_contain( const item &it, const bool nested,
 
         // If the current pocket has restrictions or blacklists the item,
         // try the nested pocket regardless of whether it's soft or rigid.
+        bool is_container;
+        bool bool_contain;
```
Comment (BevapDin) [inline src/item.cpp:10247]: Why are those variables declared outside of the loop? They are not used outside of it it.

In fact, you can remove them completely:
```C++
if( !internal_it->is_container() ) {
    continue;
}
```

Comment (EIIKaO) [reply src/item.cpp:10247]: It is the remains of the code for testing.
At the time of testing, I had commented out that continue and compared it at the point before returning.
Indeed it is possible to remove it as you have mentioned.
If there are no other suggestions on what to do in this area, I would like to follow your instruction.

Comment (BevapDin) [reply src/item.cpp:10247]: > In this case, does declaring inside the loop make no difference (or even improve) performance?

I don't known, you have to measure it.
Since the behaviour is the same in either case, the compiler can issue the same instructions in either case. So there might not be a difference at all.

>  I would beinitializing variable every time.
Well, the code is not initializing the variable every time, but it is assigning it every time, which is practically the same for a bool. So there is probably no difference at all.

But regarding optimization: we are talking about assignment of a single bool. The surrounding code is much more expensive, there are function calls etc. - the single bool assignment will not have a noticeable effect on runtime.

And the current code may even prevent optimization. The compiler doesn't even need a variable with the direct check of the condition `if( internal_it->is_container() ) {`

And there is the potential of a future bug when somebody uses those variables after the loop when they are potentially uninitialized.

Comment (EIIKaO) [reply src/item.cpp:10247]: Thanks a lot.
I learned a lot from your advice.

> And there is the potential of a future bug when somebody uses those variables after the loop when they are potentially uninitialized.

I will be conscious of that in the future.

The code will be fixed later.
