### PR TITLE
Fix removed depressant&stim cap

### LINKED ISSUE #25684: Experimental. Stimulants can not got above certain number. Build #7930
**Describe the bug**  
Stimulants such as caffeine, cocaine, and any other drug that increases the stimulant stat do not increase it above 61 stimulated and 31 stimulate overdose.

**To Reproduce**  
1. Mass consume any stimulate inducing drugs or items.
2. Wait any amount of time and the stimulant level will return to 0 as expected

**Expected behavior**  
After sniffing 80 units of cocaine and 120 caffeine pills I expected the stimulant stat to increase to the required number for a heart attack.

**Screenshots**  
bug
Time is then passed and stimulants reduce as expected. Failed to equip a watch but approximately an hour and thirty minutes was passed by the wait function.

bug time

**Versions and configuration**
 - OS: [Windows 10]
 - Game Version [0.C-32214-g0c28494]
 - Graphics version [Tiles]
 - Mods loaded [No additional mods loaded]

**Additional context**  
This has been reproduced on other builds by other people.

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
Bugfixes "Fix stim&depressant cap removed. Overdoses are now possible again"

#### Purpose of change
The stim/depressant lvls were capped at 3 times the drugs strength. 
Which meant it was impossible to overdose.

Fixes #25684

#### Describe the solution

Removed the cap and tried to restore some of the old behavior by adding a softcap.
Once the stim lvl exceeds that cap, the drugs strength gets halfed but never ignored.

#### Testing

- Spawn in any drug you want and go on a binge. 
- Get interrupted by heartattack/stoped breathing message.
- More details to the tests done below

#### Additional context

Doeses needed to reach +/-200 stim (deadly side effects happen once that point is reached)

1. crack (str 40) strongest vanilla stim
	-> without: 5 doses needed to reach 200 stim
	-> with reduction: 8 doses needed

2. cocaine (str 20) [might be a bit weak overall]:
	-> without: 10 doses needed
	-> with reduction: 16 doses needed

3. antipsychotic (str -30):
	-> without: 7 doses
	-> with: 11 doses

### CODE REVIEW

**Comment by actual-nh** [comment]
Cocaine is definitely weaker than it should be - Adderall is 24.

**Comment by actual-nh** [comment]
General Build Matrix failure was a fields test (yet again... sigh), BTW.

File: src/consumption.cpp [hunk 1]
```diff
@@ -1024,14 +1024,16 @@ void Character::modify_health( const islot_comestible &comest )
...
-          sgn( current_stim ) != sgn( comest.stim ) ) ) {
-        if( comest.stim < 0 ) {
-            set_stim( std::max( comest.stim * 3, current_stim + comest.stim ) );
+    if( comest.stim != 0 || sgn( current_stim ) != sgn( comest.stim ) ) {
+        if( ( std::abs( comest.stim ) * 3 ) > std::abs( current_stim ) ) {
+            mod_stim( comest.stim );
         } else {
-            set_stim( std::min( comest.stim * 3, current_stim + comest.stim ) );
+            comest.stim > 0 ? mod_stim( std::max( comest.stim / 2, 1 ) ) : mod_stim( std::min( comest.stim / 2,
+                    -1 ) );
```
Comment (kevingranade) [inline src/consumption.cpp:1036]: This is always true since if comest.stim == 0 we already returned from the function.

Comment (actual-nh) [reply src/consumption.cpp]: Umm... what about if comest.stim is below 0?
