### PR TITLE
Artifacts regenerating ammo

### LINKED ISSUE #40847: Enchanted Tailor's Kit doesn't recharge
# Describe the bug

Enchanted Tailor's Kit doesn't recharge.

# Versions and configuration

it used to work fine a few weeks ago, but now it's broken in 10694

# Additional context

https://i.imgur.com/W3Fb3Td.png

### LINKED ISSUE #42163: Spider Box and Enchanted Tailor Kit do not generate thread
The enchanted tailor kit and spider box do not slowly produce string as the description states.

# Steps To Reproduce

Create character and wish for spider box or enchanted tailor kit.  Wait a few days. See that no thread has been created

# Expected behavior

Some thread should generate in both items. It may be because the items have not been updated to the new storage system.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4149-gf17b26f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: Features "Artifacts regenerate ammo option"```

#### Purpose of change
This PR brings relic code up to parity with the old artifact code, with the exception of the procedurally generated names.
Fixes #42163
Fixes #40847

#### Describe the solution
add a new bool in the relic recharge info class called `regenerate_ammo` and if it is true, relic::accumulate_charge() will act upon the ammo contained rather than the charges.

#### Testing
Spawned escape boots, used them, made sure i could both use them and they recharged their crystallized ammo.

#### Additional context
@Maleclypse 

Ammo still does not interact properly with the usage of the artifact activation. this should be all right for now; i'm not even sure i can think of a reason to use that instead of iuse actions at this time.

### CODE REVIEW

File: src/relic.cpp [hunk 1]
```diff
@@ -261,22 +262,38 @@ void relic_charge_info::serialize( JsonOut &jsout ) const
...
+void relic_charge_info::accumulate_charge( item &parent )
 {
-    if( charges >= max_charges || activation_time == 0_seconds ) {
+    if( activation_time == 0_seconds ) {
         // return early, no accumulation required
         return;
+    } else if( regenerate_ammo ) {
+        if( parent.remaining_ammo_capacity() == 0 ) {
+            return;
+        }
```
Comment (anothersimulacrum) [inline src/relic.cpp:280]:
```suggestion
    } else if( regenerate_ammo && parent.remaining_ammo_capacity() == 0 ) {
        return;
    }
```

Comment (KorGgenT) [reply src/relic.cpp:280]: i had a lot of issues with that so i had to expand it out so i could reason it out. i'll experiment a little bit more with simplification a little bit later.
