### PR TITLE
Fix keg iexamine with bathtubs

### LINKED ISSUE #31541: bathtub causeing game to freeze/crash
# bathtubs cause the game to freeze/crash  if there is an item inside when you try and pick it up 

# Steps To Reproduce

Steps to reproduce:
1.  walk into a room with a bathtub with items already inside it 
2. go and pick up said items
3. watch as the game freezes then crashes 

# Expected behavior

the game freezes up and crashes. i think this is caused by the change made to bathtubs to allow them to hold liquids. 

# Versions and configuration
 - OS:  Windows 10 
 - Game Version: 0.D-4522-g4d34142 
 - Graphics version: Tiles
 - Mods loaded:  StatsThroughSkills, no fungus monsters

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
SUMMARY: Bugfixes "Fix keg iexamine with bathtubs."

#### Purpose of change

Fixes #31541

Bathtubs don't have the NOITEM flag that iexamine::keg expects, which
causes unexepected things to happen.

#### Describe the solution

This commit introduces a fake `f_no_item` furniture to use in a hack
to handle item displacement from the keg tile correctly.

#### Additional context
It seems the crash on examining while empty of liquid may have been fixed by #31406 already, but there were still issues if there was liquid preset.

### CODE REVIEW

File: src/iexamine.cpp [hunk 1]
```diff
@@ -2713,6 +2731,11 @@ void iexamine::keg( player &p, const tripoint &examp )
         g->m.add_item( examp, drink );
         return;
     } else {
+
```
Comment (Night-Pryanik) [inline src/iexamine.cpp]:
```suggestion
```
