### PR TITLE
Translated fertilizer name for "ran out of fertilizer" message

### LINKED ISSUE #38255: Message "you have run out of fertilizer_liquid"
# Describe the bug

When doing auto-fertilize ("O") with liquid fertilizer, when you run out, the ingredient key ("fertilizer_liquid") is used instead of the name ("liquid fertilizer").

# Steps To Reproduce

Auto-fertilize plots using "O" while holding liquid fertilizer until the fertilizer runs out.

# Expected behavior

Message should use the translated name, not the key.

# Screenshots

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12430-g142295b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    More City Locations [cityside],
    Urban Development [Urban_Development],
    No Fungal Monsters [No_Fungi]
]

### PR DESCRIPTION
**Pull request by jkraybill**
#### Summary
```SUMMARY: Bugfixes "Translated fertilizer name for ran-out-of-fertilizer message"```

#### Purpose of change
Fixes #38255 to show the name of the fertilizer that ran out, instead of the item key.

#### Describe the solution
Added code to get the tname() of the item instead of using the item key.

After fix:

image

#### Describe alternatives you've considered
I wasn't sure about the "right way" to get a tname from an item ID, so there are probably other ways to do this in code.

#### Testing
Fertilized with small amounts of fertilizer before and after the fix.

#### Additional context
If there is a better way to get to a translated name from an item ID, please let me know.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -4103,7 +4103,7 @@ void activity_handlers::fertilize_plot_do_turn( player_activity *act, player *p
         if( have_fertilizer() ) {
             iexamine::fertilize_plant( p, tile, fertilizer );
             if( !have_fertilizer() ) {
-                add_msg( m_info, _( "You have run out of %s" ), fertilizer );
+                add_msg( m_info, _( "You have run out of %s." ), item( fertilizer ).tname() );
```
Comment (BevapDin) [inline src/activity_handlers.cpp]:
```suggestion
                add_msg( m_info, _( "You have run out of %s." ), item::nname( fertilizer ) );
```
There is no need to create a full `item` instance just to get the item type name.

Comment (jkraybill) [reply src/activity_handlers.cpp]: Thanks, appreciate it!
