### PR TITLE
map: clear the entire vehicle cache at once instead of by level

### LINKED ISSUE #44534: Half of the vehicle disappears permanently when you walk over the ramp on the bridge
# Describe the bug

Vehicle is located over the ramp (half is on the upper level).  
If you leave the vehicle and travel by foot over the ramp (going up), upper half of the vehicle is nowhere to be found.

Also, just exiting the vehicle in the upper part of the ramp triggers error message and vehicle disappearance.

Saving and reloading the game restores the missing part.

# Steps To Reproduce

1. Spawn a vehicle
2. Position it over the ramp of the bridge
3. Step out from the upper part (or step out from the lower part and walk up the ramp)
4. Upper part of the vehicle disappears

# Expected behavior

Vehicle should not disappear.

# Screenshots

bridge-bug

bridge-bug2

# Versions and configuration

- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14; Build: 18A391; 
- Game Version: 0.E-6413-gbc6fb39649 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context

```
21:05:05.131 ERROR : (error message will follow backtrace)
    0   cataclysm-tiles                     0x000000010b6f0c4f _Z21debug_write_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 57
    1   cataclysm-tiles                     0x000000010b6f0035 _Z8DebugLog10DebugLevel10DebugClass + 513
    2   cataclysm-tiles                     0x000000010b6ef98d _Z12realDebugmsgPKcS0_S0_RKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 125
    3   cataclysm-tiles                     0x000000010bbcc9d2 _ZN3map13board_vehicleERK8tripointP9Character + 332
    4   cataclysm-tiles                     0x000000010b87291a _ZN4game12place_playerERK8tripoint + 5858
    5   cataclysm-tiles                     0x000000010b856642 _ZN4game9walk_moveERK8tripointb + 7208
    6   cataclysm-tiles                     0x000000010b4e6ebf _ZN13avatar_action4moveER6avatarR3mapRK8tripoint + 4722
    7   cataclysm-tiles                     0x000000010b8e701d _ZN4game13handle_actionEv + 3605
    8   cataclysm-tiles                     0x000000010b83bdda _ZN4game7do_turnEv + 2096
    9   cataclysm-tiles                     0x000000010bbb44f0 main + 4411
    10  libdyld.dylib                       0x00007fff75e78085 start + 1
    11  ???                                 0x0000000000000001 0x0 + 1

    Attempting to repeat stack trace using debug symbols…
    backtrace: Could not extract binary name from line
...
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/map.cpp:1013 [void map::board_vehicle(const tripoint &, Character *)] map::board_vehicle: vehicle not found
```

Save file: 
[Test11.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5323542/Test11.zip)

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "map: clear the entire vehicle cache at once instead of by level"```

#### Purpose of change
Fixes #44534

Vehicles that were parked across levels were having their parts on higher levels disappear during map::shift() calls.

The reason was that vehicles are added to level cache by z-level, but a vehicle that spawns multiple levels is added to all the caches when the level with its centerpoint is processed.  However, when the next z-level is handled, the vehicle cache is cleared and the vehicle's split components are deleted from the cache.

#### Describe the solution
Move level_cache into its own file for easier analysis.  Make the vehicle elements private, and access them only through getters and setters.  Add two dirty bits: one detects if the cache has changed at all, and another detects if the cache is still empty.  Exit the reset function early if it is empty.

Split reseting the vehicle cache into two operations: one operation that clears all levels of the cache, and then one operation that add vehicles back to the cache for all zlevels.

Change the names of the relevant functions to make them clearer.

#### Describe alternatives you've considered
Now that z-levels are always enabled, we should consider replace the matrix of level_cache by z-levels with a single 3D cache.  But that's a big change and I'll leave it to smarter people than me.

Also, `map::shift()` is a crazy function and someone should rewrite it to be less crazy.

#### Testing
Spawned a vehicle, drop it so only one tile was up a ramp, and then verified that no matter how I walked around the vehicle, moving up the ramp showed the vehicle.  Without the patch, the vehicle would disappear if the movement caused `map::shift()` to be called.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Segfault in the explosion testing code, joy.

File: src/editmap.cpp [hunk 1]
```diff
@@ -686,7 +686,7 @@ void editmap::draw_main_ui_overlay()
         } else {
 #endif
             hilights["mapgentgt"].draw( *this, true );
-            tmpmap.reset_vehicle_cache( target.z );
+            tmpmap.rebuild_vehicle_cache( target.z );
```
Comment (Aivean) [inline src/editmap.cpp:689]: Since `rebuild_vehicle_cache` now doesn't call `clear_vehicle_cache`, you probably need to clear the cache explicitly before calling `rebuild_vehicle_cache`?

File: src/vehicle.cpp [hunk 2]
```diff
@@ -6552,7 +6552,7 @@ void vehicle::shift_parts( const point &delta )
     pivot_anchor[0] -= delta;
     refresh();
     //Need to also update the map after this
-    get_map().reset_vehicle_cache( sm_pos.z );
+    get_map().rebuild_vehicle_cache( sm_pos.z );
```
Comment (Aivean) [inline src/vehicle.cpp:6555]: Same here, are you sure that cache was cleared before building?

File: src/vehicle_use.cpp [hunk 3]
```diff
@@ -1942,7 +1942,7 @@ void vehicle::use_bike_rack( int part )
     if( success ) {
         map &here = get_map();
         here.invalidate_map_cache( here.get_abs_sub().z );
-        here.reset_vehicle_cache( here.get_abs_sub().z );
+        here.rebuild_vehicle_cache( here.get_abs_sub().z );
```
Comment (Aivean) [inline src/vehicle_use.cpp:1945]: Same here, are you sure that cache was cleared before building?

File: src/map.cpp [hunk 4]
```diff
@@ -212,12 +212,31 @@ VehicleList map::get_vehicles()
...
+            if( inbounds( p ) ) {
+                ch.veh_exists_at[p.x][p.y] = false;
+            }
+            ch.veh_cached_parts.erase( part );
+        }
+        ch.veh_in_active_range = false;
+    }
+}
+
+void map::rebuild_vehicle_cache( const int zlev )
```
Comment (Aivean) [inline src/map.cpp:234]: Since now `rebuild_vehicle_cache` doesn't clear the cache before building, perhaps rename the method to `build_vehicle_cache` to emphasize that?

**Review by Aivean — COMMENTED** [review]
Beside the couple of places that I commented on, where it's not immediately obvious if cache is cleared before building, everything looks good to me.

**Comment by mlangsdorf** [comment]
The problem with calling `reset_all_vehicle_caches()` from `build_vehicle_cache()` is that `build_vehicle_cache()` is often called in a loop, and `build_vehicle_cache()` can adjust the cache for more than the level it is called on.  So all the caches have to be cleared before any of the caches can be built.

**Comment by Aivean** [comment]
> The problem with calling `reset_all_vehicle_caches()` from `build_vehicle_cache()` is that `build_vehicle_cache()` is often called in a loop, and `build_vehicle_cache()` can adjust the cache for more than the level it is called on. So all the caches have to be cleared before any of the caches can be built.

Yes, you are right.  Another possible alternative is to mark cache as dirty and (re)build it on demand.

But I'm not suggesting to implement any of these alternatives in this PR, it's just an ideas to consider for the possible future cache improvement.

Currently the best course of action seems to just ensure that cache is cleared before `build_vehicle_cache`  is called.

**Comment by mlangsdorf** [comment]
Fixed the segfault in the explosion code by adding dirty bits to the vehicle cache.  This should also speed up performance slightly (I hope), because the vehicle cache won't attempt to clear itself if it's already clear.

**Comment by Aivean** [comment]
Mark, I've seen your review request, but I've been a bit busy recently. I promise to take a look ASAP.

File: src/level_cache.cpp [hunk 5]
```diff
@@ -0,0 +1,107 @@
...
+}
+
+void level_cache::set_veh_exists_at( const tripoint &pt, bool exists_at )
+{
+    veh_exists_at[ pt.x ][ pt.y ] = exists_at;
+    veh_cache_dirty = true;
+    veh_cache_active |= exists_at;
+}
+
+void level_cache::set_veh_cached_parts( const tripoint &pt, vehicle *veh, int part_num )
```
Comment (Aivean) [inline src/level_cache.cpp:62]: Is `veh` arg here ever expected to be `nullptr`? 

If yes, then what's the point of `veh_cached_parts[ pt ] = std::make_pair( veh, part_num );` when `veh == nullptr`?
If `veh` cannot be null, `veh_cache_active |= veh != nullptr;` doesn't make sense.

I suspect that `veh` is not expected to be `nullptr` and if that's the case, it probably makes sense to change the type of the `veh` argument to `const vehicle &veh`.

File: src/level_cache.h [hunk 6]
```diff
@@ -0,0 +1,126 @@
...
+
+        void set_veh_in_active_range( bool is_active );
+        void set_veh_exists_at( const tripoint &pt, bool exists_at );
+        void set_veh_cached_parts( const tripoint &pt, vehicle *veh, int part_num );
+        void verify_vehicle_cache();
+        void clear_vehicle_cache();
+        void clear_veh_from_veh_cached_parts( const tripoint &pt, vehicle *veh );
+
+    private:
+        bool veh_cache_dirty = true;
```
Comment (Aivean) [inline src/level_cache.h:120]: Maybe add some comments on these boolean flags to help with understanding possible states and intended transitions between them?

**Review by Aivean — APPROVED** [review]
Looks good to me!

Also, I confirm that it fixes #44534.

File: src/level_cache.cpp (hunk 5 above)
Comment (mlangsdorf) [reply src/level_cache.cpp:62]: so the veh_cached_parts is returned through `veh_at_internal()` as `vehicle *`; I'm not going to change that and I'm nervous about changing the stored `vehicle *` but I guess I can pass it as a reference.

File: src/level_cache.h (hunk 6 above)
Comment (mlangsdorf) [reply src/level_cache.h:120]: Good idea, I'll do that.

File: src/level_cache.cpp (hunk 5 above)
Comment (Aivean) [reply src/level_cache.cpp:62]: I think changing the method signature to `void set_veh_cached_parts( const tripoint &pt, const vehicle &veh, int part_num )` and replacing `veh_cache_active |= veh != nullptr;` inside with `veh_cache_active = true;` would make it a bit cleaner, but it's also ok if you leave it as is.

Comment (mlangsdorf) [reply src/level_cache.cpp]: Fixed, thanks for the suggestion.

**Comment by mlangsdorf** [comment]
Can't get the explosions test to fail on my system; it looks like an unrelated failure anyway.
