### PR TITLE
Dissecting with only a scalpel

### LINKED ISSUE #26514: Unable to Dissect without a Butchering tool
**Describe the bug**
The option to Dissect a corpse using a "fine-cutting" tool does not show up without also having a tool with the Butchering quality.

**To Reproduce**
1. Make a player with an X-Acto Knife or a Scalpel
2. Stand on top of a corpse
3. Press the Butchering hotkey.

**Expected behavior**  
The player can Dissect using an appropriate tool.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-33929-g268e51c
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead, Filthy Clothing, Disable NPC Needs

### PR DESCRIPTION
**Pull request by LetterShapedGlyphs**
#### Summary
```SUMMARY: Bugfixes "Enables dissection without extra butchering tools"```

#### Purpose of change
Fixes #26514  - Players cannot dissect corpses without a butchering tool even while carrying something with fine cutting.

#### Describe the solution
One section already utilized a ternary operator to solve this problem, but this was not extended to other parts of the code. Where possible, this was done, and failing that a secondary dissection factor variable was used to correct program flow.

#### Describe alternatives you've considered
Adding butchering qualities to all items suitable for dissection would also solve this problem, but would also enable the player to perform butchering operations with only a scalpel or X-Acto knife.

### CODE REVIEW

File: src/action.cpp [hunk 1]
```diff
@@ -485,14 +485,15 @@ bool can_butcher_at( const tripoint &p )
 {
     // TODO: unify this with game::butcher
     const int factor = g->u.max_quality( quality_id( "BUTCHER" ) );
+    const int factorD = g->u.max_quality( quality_id( "CUT_FINE" ) );
```
Comment (Karthas077) [inline src/action.cpp]: Unfortunately this section doesn't yet know what action the player might be performing and must check both. Rather than change the const nature of factor, I decided to add a second variable.

File: src/activity_handlers.cpp [hunk 2]
```diff
@@ -255,9 +255,9 @@ void set_up_butchery( player_activity &act, player &u, butcher_type action )
         return;
     }
 
-    int factor = u.max_quality( quality_id( "BUTCHER" ) );
+    int factor = u.max_quality( action == DISSECT ? quality_id( "CUT_FINE" ) : quality_id( "BUTCHER" ) );
     auto items = g->m.i_at( u.pos() );
-    if( ( size_t )act.index >= items.size() || factor == INT_MIN ) {
```
Comment (Karthas077) [inline src/activity_handlers.cpp]: This would print a "No Corpses" error when it returns to butcher_finish. This has been handled by code following this.

**Comment by Karthas077** [comment]
Well I thought that might have been the problem but apparently I can't see where the astyle error I made is.

**Comment by Karthas077** [comment]
Alright well if running the files through the Astyle-Extension using the parameters outlined in the Code Style Guide didn't fix whatever gorgon-ghprb thinks is wrong, I have no clue what to do from here.
