### PR TITLE
draw_colored_text should “draw” an empty line if given an empty string

### LINKED ISSUE #75685: Component selection menu only ever shows a single menu item
### Describe the bug

Some recipes have alternate component lists that result in a menu asking you which combination you prefer. This menu is quite weird; none of the menu items have any text! Instead, each one has a long description that is shown in the footer.

The footer is displayed correct (and even with color, thanks to #75673), but the menu items themselves are all drawn on one line.

### Attach save file

n/a

### Steps to reproduce

The screenshot was taken from an attempt to craft the “high steel brigandine coat”, learned from a book called “Studies in Historic Armorsmithing”.

### Expected behavior

The menu has many options, not just one.

### Screenshots

Screenshot 2024-08-14 at 14-05-05 ImGui uilist menus render their footer text without color tags · Issue #75673 · CleverRaven_Cataclysm-DDA

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 809cfa67eb-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by db48x**
#### Summary
Interface "draw_colored_text should “draw” an empty line if given an empty string"
#### Purpose of change

It needs to be consistent and always end with the cursor on a new line.

#### Additional context

Fixes #75685

### CODE REVIEW

File: src/cata_imgui.cpp [hunk 1]
```diff
@@ -436,6 +436,11 @@ void cataimgui::draw_colored_text( std::string const &text,
     ImGui::PushID( text.c_str() );
     int startColorStackCount = GImGui->ColorStack.Size;
     ImGuiID itemId = GImGui->CurrentWindow->IDStack.back();
+
+    if( text.empty() ) {
+        ImGui::NewLine( );
+    }
+
```
Comment (ZhilkinSerg) [inline src/cata_imgui.cpp:443]:
```suggestion
    if( text.empty() ) {
        ImGui::NewLine( );
        return;
    }

    ImGui::PushID( text.c_str() );
    int startColorStackCount = GImGui->ColorStack.Size;
    ImGuiID itemId = GImGui->CurrentWindow->IDStack.back();

```

Comment (ZhilkinSerg) [reply src/cata_imgui.cpp:443]: I guess there is no need to do anything if the string is empty and you can simply return early after drawing a new line?

Comment (db48x) [reply src/cata_imgui.cpp:443]: Yea, there really is no need to even push an ID only to do nothing and then pop it again.
