### PR TITLE
update_mapgen:  rotation fixes to solve the teleporting NPC issue

### LINKED ISSUE #35430: Refugee Center NPC's Teleport After Handing in Quest
# Describe the bug

Upon handing in the "Kill Bandits" quest to the Old Guard Representative a new NPC "Hunter" is spawned in the southwest corner of the refugee center. Most of the other refugee center NPC's who were previously there get teleported to the road outside of northwest wall of the refuge center. 

This "Hunter" had not been there before, I assume this "Hunter" in the refugee center is either a new NPC who got added in a recent update or is spawned upon completion of the "Kill Bandits" quest.

# Steps To Reproduce

1. Go to a refugee center and look at everyone happily standing around in the southwest corner.
2. Get the "Kill Bandits" quest from the Old Guard Representative in the southeast corner of the refugee center.
3. Complete and turn in the "Kill Bandits" and accept the next quest.
4. Go back to the southwest room of the refugee center.

# Expected behavior

Refugee Center NPC's should not be teleported onto the side of the road, excepting the very slim chance that this is actually the expected outcome of the "Kill Bandits" quest. I talked to a couple of the NPC's who were teleported and none of them had any dialogue referencing this movement.

# Screenshots

cddarefugeecenterbug1
cddarefugeecenterbug2
cddarefugeecenterbug3
cddarefugeecenterbug4

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9240-g1bb08dd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

I would've attached my save here but apparently my 41 MB save is too big for github, so screenshots will have to do.

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "update_mapgen:  rotation fixes to solve the teleporting NPC issue"```

#### Purpose of change
Fixes #35430 

NPCs teleport to the upper left corner to the reality bubble when an `update_mapgen` function needs to rotate their overmap tile.

While investigating that issue, I noticed that basecamps built in rotated fire stations or evac shelters didn't rotate after setting up the camp, which kept the NPC in place but meant that the upgrades were applied to the wrong part of the map.

Fix both issues.

#### Describe the solution
For the base camp issue, create a new rotational overmap tile ID for basecamps and set the overmap tile ID to that new ID including the rotation information.  Further `update_mapgen` calls will continue to rotate the map properly to put the updates in the correct relative position.

`map::rotate()` uses `npc::spawn_at_precise()` to move NPCs during rotation, but this explicitly clips the NPC's position to upper left of the reality bubble.  Pass a `setpos_safe` bool to `rotate()` when `rotate()` is called from an `update_mapgen` function, and use `npc::setpos()` instead of `npc::spawn_at_precise()` so that position isn't clipped.  `npc::setpos()` explicitly can't be called during normal mapgen, so this split is required.

#### Describe alternatives you've considered
I hate CDDA's co-ordinate systems.  Fixing them to be type safe isn't feasible.

#### Testing
Started a new game and went to an east facing refugee center.  Performed the first two Old Guard rep missions, the second of which calls `update_mapgen` to place some NPCs, and verified that the other NPCs were not teleported away.

Started a fire station faction camp in a west facing faction camp, and verified that the companion NPC wasn't teleported away and that the kitchen upgrade spawned in the kitchen correctly.

### CODE REVIEW

File: src/mapgen.cpp [hunk 1]
```diff
@@ -6725,10 +6726,22 @@ void map::rotate( int turns )
...
-        np.spawn_at_precise( { abs_sub.xy() }, { new_pos, abs_sub.z } );
-        overmap_buffer.insert_npc( npc_ptr );
+        const point new_pos = point{ old_x, old_y } .rotate( turns, { SEEX * 2, SEEY * 2 } );
+        if( setpos_safe ) {
+            // setpos can't be used during mapgen, but spawn_at_precise clips position
+            // to be between 0-11,0-11 and teleports NPCs when used inside of update_mapgen
+            // calls
+            const tripoint new_global_sq = sq - local_sq + new_pos;
+            const tripoint &new_local_pos = g->m.getlocal( new_global_sq );
+            np.setpos( tripoint( new_local_pos ) );
```
Comment (BevapDin) [inline src/mapgen.cpp]: Why does this make an explicit copy of `new_local_pos`?
```suggestion
            np.setpos( new_local_pos );
```

Comment (mlangsdorf) [reply src/mapgen.cpp]: I have no idea, thanks for the review.
