### PR TITLE
prevent negative focus total (except in debug cases)

### LINKED ISSUE #47047: Integer overflow at getting driving to 1
# Describe the bug

Integer overflow at skill, vehicles skill started as 0 and starts -2 million % towards learning 1.

# Steps To Reproduce

No idea how it happened. I did hop in a car and drive all the way home, it was half broken.

# Expected behavior

Vehicles skill to not start at -2million%

# Screenshots

image

# Versions and configuration

OS: Windows 10
Game Version: 0.E-9229-G6902525-DIRTY
Graphics version: DeadPeople
Ingame language: English
Mods loaded: Blaze Industries, Blaze Industries Dead People

# Additional context

I started reading a book to get my vehicles to 1 from 0, and the percentage started at -2mil%.

@kevingranade I'm told you'd be interested in this, so I tagged you.

### LINKED ISSUE #47096: Healthcare skill will not increase under any circumstance
# Describe the bug
Healthcare is stuck at 0% regardless of anything I do, even skill books are bugged

I noticed it was at 0%, read Big Book of First Aid, and it produces a very large negative number.

# Steps To Reproduce
I have no idea, really.

# Expected behavior

My healthcare skill would increase :)

# Screenshots

https://i.imgur.com/VKZjbI9.jpg

# Versions and configuration

# Additional context

Not sure how to provide my save

> 
> 
> What happens if you debug edit your Healthcare skill to 1? Can you increase it by reading / practice after that or is it still bugged up?

I should've mentioned that this was the first thing I did. It has no effect as far as I could tell. I spammed bandages on limbs to see if it'd go up again, as well as reading the book again, same issue.

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
Bugfixes "Prevent xp 'underflow' due to negative focus"

#### Purpose of change
prevents negative focus from being set (except in debug cases), due to it causing an negative maxint whenever practice sessions tried to take the square root from a negative number

Fixes #47096 
Fixes #47047

#### Describe the solution

changed mod_focus to check for results smaller than 1 (that's the min get_focus allows for, so i ve taken it as the min for this too)

#### Testing

- Spawn in a character with albino trait
- grind a few percent of survival xp by picking through some shrubbery
- wait for an hour or two (until your focus reaches 1 due to sunburns)
- scavange another srubbery and check xp

in the old version your xp should be reset to 0 (it actually is a lot lower)
verify by spawning in alpha male quarterly and starting reading (shown skill percent should be very far in the negative)

This version prevents that

#### Additional context
thanks to ferociousdork for pretty much solving this one

### CODE REVIEW

File: src/character.h [hunk 1]
```diff
@@ -1998,7 +1998,7 @@ class Character : public Creature, public visitable
             return std::max( 1, focus_pool / 1000 );
         }
         void mod_focus( int amount ) {
-            focus_pool += amount * 1000;
+            focus_pool + amount * 1000 > 0 ? focus_pool += amount * 1000 : 1;
```
Comment (anothersimulacrum) [inline src/character.h:2001]: This doesn't look like it does what you want, I think you want
```suggestion
            focus_pool = focus_pool + amount * 1000 > 0 ? focus_pool + amount * 1000 : 1;
```
Regardless, I think these are clearer and cleaner
```suggestion
            focus_pool += std::max( amount * 1000, 1 );
```
or
```suggestion
            focus_pool += amount * 1000;
            focus_pool = std::max( focus_pool, 0 );
```

Comment (Jamuro-g) [reply src/character.h:2001]: it does work due to focus_pol += amount*1000 being the result of the if but your 3rd version is cleaner. (the 2nd doesn't work due to mod_focus also handling negative amounts)

Comment (anothersimulacrum) [reply src/character.h]: Yeah, I commented a bit early and spent the next few minutes editing my reply. The second one didn't work, the third one is cleaner, as it is (well, was) if modifying focus would make it negative, nothing would happen.

**Review by BrettDong — APPROVED** [review]
