### PR TITLE
fixed message string when AUTO_INV_ASSIGN = false

### LINKED ISSUE #10768: Minor text hitch when auto-assign letters is disabled.
When "Auto-assign letters" is set to "False" in the Interface options, any time a new item is picked up, there's an open bracket shows up next to the "You pick up:" text.
cataexperimentalautoassignfalseglitch

I'll need to keep testing to see if there are any other similar graphics issues when auto-assign letters is set to false, but that was the most prominent one to me.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7535902-minor-text-hitch-when-auto-assign-letters-is-disabled?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by bkentel**
This fixes #10768 .
There could be other mixups with item::invlet being '\0' elsewhere.
Added named temporaries for clarity.

### CODE REVIEW

File: src/pickup.cpp [hunk 1]
```diff
@@ -847,20 +847,35 @@ void Pickup::show_pickup_message(std::map<std::string, int> &mapPickup,
...
         // name seems to be a fitting test
-        if(mp_iter->first == ii_iter->first) {
-            add_msg(_("You pick up: %d %s [%c]"),
-                    mp_iter->second, ii_iter->second.display_name(mp_iter->second).c_str(), ii_iter->second.invlet);
+        if(mp_name == ii_name) {
+            auto const &itm       = ii_iter->second;
+            auto const quantity   = mp_iter->second;
+            auto const name       = itm.display_name(mp_iter->second).c_str();
+            auto const letter     = itm.invlet;
+            auto const use_letter = letter != 0;
```
Comment (DavidKeaton) [inline src/pickup.cpp]: Curious to all the `const` usage.

**Comment by bkentel** [comment]
When the type isn't critical for understanding, or implicit conversions are not intended, I like to generally follow [AAA style] (http://herbsutter.com/2013/08/12/gotw-94-solution-aaa-style-almost-always-auto/).

File: src/pickup.cpp (hunk 1 above)
Comment (bkentel) [inline src/pickup.cpp]: When the type isn't critical for understanding, or implicit conversions are not intended, I like to generally follow AAA style.

Comment (DavidKeaton) [inline src/pickup.cpp]: I can understand a style guideline, but to obfuscate variable typing makes it harder for those without an implicit understanding of the variable's true type. I have rambled on this before, and it is by no means my call, but the over usage of auto is purely unneeded. This is merely my opinion, a lone one I guess. *sigh*

Comment (bkentel) [inline src/pickup.cpp]: The type was just as obscure before -- it wasn't named at all when it was used directly in the original expression; how is this less clear? You could name the types here, but then if the types change elsewhere you could have implcit conversion that you have to rely on warnings telling you about.

I can certainly understand where you are coming from; and you're not at all alone in your opinion: auto is still a bit controversial within the cpp community.

Comment (kevingranade) [inline src/pickup.cpp]: I agree, auto typing isn't helpful here.

**Comment by KA101** [comment]
I just picked up: `1 You pick up: %d %s`

Gonna make clean just in case but I'm thinking this isn't ready for prime time.

**Comment by kevingranade** [comment]
If you're going to do a refactor, do it either before or after the actual fix, not in the same commit.
You have a large and questionable refactor hiding a very simple change here.
On the subject of breaking out the variables, I'm not at all this makes anything clearer, because it introduces a huge number of variables for what is happening, most of which are only used once or twice, and some of which are only ever used to populate other variables.  The end result of which is there is more code shuffling variable references around than there is accomplishing anything.

File: src/pickup.cpp [hunk 2]
```diff
@@ -847,20 +847,35 @@ void Pickup::show_pickup_message(std::map<std::string, int> &mapPickup,
...
         // name seems to be a fitting test
-        if(mp_iter->first == ii_iter->first) {
-            add_msg(_("You pick up: %d %s [%c]"),
-                    mp_iter->second, ii_iter->second.display_name(mp_iter->second).c_str(), ii_iter->second.invlet);
+        if(mp_name == ii_name) {
+            item const &itm       = ii_iter->second;
+            int  const quantity   = mp_iter->second;
+            char const *name      = itm.display_name(mp_iter->second).c_str();
+            char const letter     = itm.invlet;
+            bool const use_letter = letter != 0;
```
Comment (DavidKeaton) [inline src/pickup.cpp]: Sorry to be a grumpy hardass, but thank you.

File: src/pickup.cpp [hunk 3]
```diff
@@ -847,20 +847,35 @@ void Pickup::show_pickup_message(std::map<std::string, int> &mapPickup,
...
+
+            if (use_letter) {
```
Comment (bkentel) [inline src/pickup.cpp]: The above temporaries are a bit superfluous, but the temporaries here are needed IMO, but the comment w.r.t refactoring is noted; should have made this two successive pull requests I guess.

**Comment by DavidKeaton** [comment]
Not an additive to kevingranade's statement, more of a question to you sir.

Wouldn't comments suffice in explaining them without needing one time vars for clarity's sake?

**Comment by bkentel** [comment]
Here, because of the two format strings, the inner temporaries (not itm though) are needed. Don't you think?

**Comment by KA101** [comment]
Comments are generally better, and in any event this created a blank when I picked up and autowielded the emergency jacket, after the make clean.  Literally `Wielding : ` and then nothing.

**Comment by bkentel** [comment]
KA101
That would be a different bug, no? Wielding messages aren't touched here AFAK.

File: src/pickup.cpp [hunk 4]
```diff
@@ -847,20 +847,35 @@ void Pickup::show_pickup_message(std::map<std::string, int> &mapPickup,
...
+        auto const &ii_name = ii_iter->first;
+
         // name seems to be a fitting test
-        if(mp_iter->first == ii_iter->first) {
-            add_msg(_("You pick up: %d %s [%c]"),
-                    mp_iter->second, ii_iter->second.display_name(mp_iter->second).c_str(), ii_iter->second.invlet);
+        if(mp_name == ii_name) {
+            item const &itm       = ii_iter->second;
+            int  const quantity   = mp_iter->second;
+            char const *name      = itm.display_name(mp_iter->second).c_str();
```
Comment (BevapDin) [inline src/pickup.cpp]: There's a subtle bug here: the result of `std::string::c_str` is only valid as long as the string itself is valid and unchanged. The result of `item::display_name` is value, this calls `c_str` on a temporary object. Right after this declaration, name is invalid as the temporary string is deleted.

Comment (bkentel) [inline src/pickup.cpp]: Good catch -- fixed.
Totally my fault here; didn't expect it to return a copy instead of a const reference.

**Comment by KA101** [comment]
When I picked up the evac jacket, it gave me the blanks I described earlier.  You'd still failed, even if one bug was preexisting.

**Comment by bkentel** [comment]
I fixed the wield messages too -- totally different area of the code mind you.

**Comment by KA101** [comment]
Thanks.

File: src/pickup.cpp [hunk 5]
```diff
@@ -285,8 +287,13 @@ void Pickup::pick_one_up( const point &pickup_target, item &newit, vehicle *veh,
                                                       g->u.remove_weapon(), 1 );
                             g->u.inv.assign_empty_invlet( newit, true ); // force getting an invlet.
```
Comment (BevapDin) [inline src/pickup.cpp]: This will or at least might change the invlet. `use_invlet` is now outdated and could be wrong. Same below.

Comment (bkentel) [inline src/pickup.cpp]: Fixed; thanks.

**Comment by bkentel** [comment]
Found one more after grepping around; think this should be all.

**Comment by kevingranade** [comment]
You still have the refactor that IMO makes things unclear (and was, btw the source of the bug), please back that out.

**Comment by DavidKeaton** [comment]
Looking better. :-)
