### PR TITLE
Correctly predict craftability of recipes with overlapping item requirements

### LINKED ISSUE #32311: Crafts can be started with missing components if a single component satisfies multiple requirements
# Describe the bug

Certain recipes constantly "missing components" and continuously prompt for more. No matter how many times I accept the dialogue, it will keep on asking for the missing components

Update: I have tried crafting a clay crucible as well, and the same bug appears, however this time it's constantly asking for water. Since this time I was crafting it near a river and had access to a practically unlimited amount of the asked for ingredient, I can just hold Y and spam it. This results in crafting percentage actually proceeding when I hit N again. It then consumes an amount of time and percentage advances.

# Steps To Reproduce

1. Try crafting certain recipies, know items so far are the Can Forge asking for clay and the Bow Scope which asked for high quality lenses

# Expected behavior

To start the crafting for the item with the available ingredients

# Screenshots
cataclysm-tiles_dGEEewcCjS
cataclysm-tiles_UU8T4nWrpr
Note the number of used ingredients

# Versions and configuration

    - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-5491-g54a24dd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Packaging [Packaging],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Draco's Dog Mod [DracoDogMod],
    Cataclysm++ [Cata++],
    Crazy Cataclysm [crazy_cataclysm],
    Fast Healing [fast_healing],
    Mining Mod [Mining_Mod],
    Mutant NPCs [mutant_npcs],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Jury-Rigged Robots [jury_rigged_robots],
    No Acid Zombies [No_Acid_Zombies],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    No Filthy Clothing [no_filthy_clothing],
    Simplified Nutrition [novitamins],
    Sleep Deprivation [sleepdeprivation],
    StatsThroughSkills [StatsThroughSkills]

# Additional context

Using an integrated toolset and kitchen unit hotplate as the crafting tools

### LINKED ISSUE #32554: Crash in item::is_tool after trying to pick the same one available ingredient for two different components of the vegetable soup
# Describe the bug

```
#3  <signal handler called>
#4  0x0000556aff1d2e23 in item::is_tool (this=this@entry=0x556b19d58630) at src/item.cpp:5452
#5  0x0000556affa78d08 in <lambda(const item*)>::operator() (e=0x556b19d58630, this=0x556b0a60e0d0) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#6  std::_Function_handler<VisitResponse(const item*), charges_of_internal(const T&, const itype_id&, int, const std::function<bool(const item&)>&) [with T = item; itype_id = std::__cxx11::basic_string<char>]::<lambda(const item*)> >::_M_invoke(const std::_Any_data &, const item *&&) (__functor=..., __args#0=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:282
#7  0x0000556affa7d1be in std::function<VisitResponse (item const*)>::operator()(item const*) const (__args#0=<optimized out>, this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#8  std::_Function_handler<VisitResponse (item*), std::function<VisitResponse (item const*)> >::_M_invoke(std::_Any_data const&, item*&&) (__functor=..., __args#0=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:282
#9  0x0000556affa7d26e in std::function<VisitResponse (item*)>::operator()(item*) const (__args#0=<optimized out>, this=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#10 visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}::operator()(item*, item*) const (this=<optimized out>, it=<optimized out>) at src/visitable.cpp:347
#11 std::_Function_handler<VisitResponse (item*, item*), visitable<item>::visit_items(std::function<VisitResponse (item*)> const&)::{lambda(item*, item*)#1}>::_M_invoke(std::_Any_data const&, item*&&, std::_Any_data const&) (
    __functor=..., __args#0=<optimized out>, __args#1=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:282
#12 0x0000556affa76e44 in std::function<VisitResponse (item*, item*)>::operator()(item*, item*) const (__args#1=<optimized out>, __args#0=<optimized out>, this=0x7fff5d663290)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#13 visit_internal(const std::function<VisitResponse(item*, item*)> &, item *, item *) (func=..., node=0x556b19d58630, parent=<optimized out>) at src/visitable.cpp:356
#14 0x0000556affa7de12 in visitable<item>::visit_items(std::function<VisitResponse (item*, item*)> const&) (func=..., this=<optimized out>) at src/visitable.cpp:387
#15 visitable<item>::visit_items(std::function<VisitResponse (item*)> const&) (this=this@entry=0x556b19d58630, func=...) at src/visitable.cpp:348
#16 0x0000556affa7e791 in visitable<item>::visit_items(std::function<VisitResponse (item const*)> const&) const (this=this@entry=0x556b19d58630, func=...) at src/visitable.cpp:336
#17 0x0000556affa791a2 in charges_of_internal<item> (filter=..., limit=<optimized out>, id=..., self=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:87
#18 visitable<inventory>::charges_of(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::function<bool (item const&)> const&) const (this=<optimized out>, what=..., limit=1, filter=...)
    at src/visitable.cpp:823
#19 0x0000556aff8d6eb8 in requirement_data::<lambda(std::vector<item_comp, std::allocator<item_comp> >&)>::operator()(std::vector<item_comp, std::allocator<item_comp> > &) (comps=..., __closure=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/new:169
#20 0x0000556aff8d7f64 in __gnu_cxx::__ops::_Iter_pred<requirement_data::continue_requirements(const std::vector<item_comp>&, const std::__cxx11::list<item>&)::<lambda(std::vector<item_comp, std::allocator<item_comp> >&)> >::operator()<__gnu_cxx::__normal_iterator<std::vector<item_comp>*, std::vector<std::vector<item_comp> > > > (__it=..., this=0x7fff5d663538) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/predefined_ops.h:282
#21 std::__remove_if<__gnu_cxx::__normal_iterator<std::vector<item_comp>*, std::vector<std::vector<item_comp> > >, __gnu_cxx::__ops::_Iter_pred<requirement_data::continue_requirements(const std::vector<item_comp>&, const std::__cxx11::list<item>&)::<lambda(std::vector<item_comp>&)> > > (__pred=..., __last=..., __first=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_algo.h:869
#22 std::remove_if<__gnu_cxx::__normal_iterator<std::vector<item_comp>*, std::vector<std::vector<item_comp> > >, requirement_data::continue_requirements(const std::vector<item_comp>&, const std::__cxx11::list<item>&)::<lambda(std::vector<item_comp>&)> > (__pred=..., __last=..., __first=...) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_algo.h:939
#23 requirement_data::continue_requirements (required_comps=..., remaining_comps=...) at src/requirements.cpp:1018
#24 0x0000556afef6bf03 in item::get_continue_reqs (this=0x556b0ddaabf0) at src/crafting.cpp:1055
#25 0x0000556afef770e8 in player::can_continue_craft (this=this@entry=0x556b00d20b90, craft=...) at src/crafting.cpp:1221
#26 0x0000556afed9e00d in activity_handlers::craft_do_turn (act=0x556b00d23a70, p=0x556b00d20b90) at src/activity_handlers.cpp:3272
#27 0x0000556afede0b2b in std::function<void (player_activity*, player*)>::operator()(player_activity*, player*) const (__args#1=<optimized out>, __args#0=<optimized out>, this=<optimized out>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/std_function.h:682
#28 activity_type::call_do_turn (this=0x556b01177508, act=act@entry=0x556b00d23a70, p=p@entry=0x556b00d20b90) at src/activity_type.cpp:111
#29 0x0000556aff854992 in player_activity::do_turn (this=0x556b00d23a70, p=...) at src/string_id.h:128
#30 0x0000556aff0a2490 in game::process_activity (this=0x556b00cc6ae0) at src/game.cpp:1620
#31 game::process_activity (this=0x556b00cc6ae0) at src/game.cpp:1608
#32 0x0000556aff0ec390 in game::do_turn (this=0x556b00cc6ae0) at src/game.cpp:1399
#33 0x0000556afed2b119 in main (argc=<optimized out>, argv=<optimized out>) at /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/unique_ptr.h:342
```

0.D-5752-ge348498b04-dirty

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Bugfixes "Correctly predict craftability of recipes with overlapping item requirements"

#### Purpose of change
Fixes #32311.
Fixes #32554.

When recipes have overlapping requirements the current implementation for checking for availability of those requirements does not properly take into account the fact that a single item cannot be used to satisfy more than one.

(Actually, for overlaps between components and tools, there is some code to check for this, but not between different component requirements.)

This causes problems with some recipes.  In particular, survivor telescope is discussed in #32311.  The most severe example of this phenomenon is `chainmail_suit_faraday` which has 6 requirements each of which can be satisfied either by some chainmail sheets or by a specific piece of chainmail armour.

As things stand, the crafting GUI will display these items as being craftable, but if you try to craft them then various strange things can happen, including `debugmsg` errors, and you end up with an in-progress craft object with 0% progress which you can't continue nor disassemble to recover the ingredients.  This is clearly unsatisfactory.

#### Describe the solution
(Description of the solution adapted from the [discussion](https://github.com/CleverRaven/Cataclysm-DDA/issues/32311#issuecomment-570068721) in #32311).

The basic idea is to detect recipes with overlapping requirements and refactor them into a set of alternative requirements, each of which is internally non-overlapping, then try each of these in turn.

So, for example, the survivor telescope recipe currently has the requirements:
```
1 high-quality lens
AND
1 high-quality lens OR 1 small high-quality lens
```
These would internally be changed to have two sets of requirements:
```
2 high-quality lens
OR
1 high-quality lens AND 1 small high-quality lens
```
No change to the json is required, this is calculated as part of recipe finalization.

Implementation-wise, this is done via a new class `deduped_requirement_data`, which contains a `vector` of `requirement_data` objects.

Recipes now expose both representations of their requirements, because code can want either the original or the deduped version depending on its needs.  The original version is typically smaller and easier to understand, so that's used for example for displaying the requirements to the player.

As another example, the vegetable soup recipe (as discussed in #32554) was a bit more complex (looks like it's since been edited to not have any overlap, but it's still a good example).  It used to look essentially like:
```
eggs OR wild veggies
AND
other veggies OR wild veggies
```
and is now transformed into
```
eggs AND (other veggies OR wild veggies)
OR
wild veggies AND other veggies
OR
2 wild veggies
```
With more overlapping requirements or more items in the overlap the number of alternatives rises fast, but nothing in the core game gets too absurd.  The worst case is the aforementioned `chainmail_suit_faraday`, which requires 63 alternative `requirement_data` objects.  I've set a limit of 100 as a sanity-check to prevent mods performing a denial-of-service attack on the algorithm.

The crafting GUI now correctly displays when items are craftable.

As a side-effect, I have reworked how `player::can_start_craft` operates.  This seeks to detect whether a craft can be *started* (but maybe not finished), which requires only 5% of the tool charges.  It used to do this by creating a whole new requirements object with different tools requirements, but this interacted poorly with this new feature.  So, instead, I've added a new flag that can be passed to the various test-craftability functions, which ultimately gets used at the very innermost function to tweak the number of tool charges sought.  I'm a little unhappy at how the "5%" arbitrary constant is scattered all over the codebase; I think it might be good to refactor that further, but not in this PR.

TODO:
- [x] When an item is in this strange corner case all the requirements in the crafting menu are green.  Need to add a message to help the player understand what's going on.
- [x] When an item is actually crafted, the player needs to decide how to allocate their resources (in the event there are multiple options).  This requires a new choice interface that is more holistic than the existing one for choosing ingredients for a specific requirement within the recipe.  @ifreund has [suggested one approach](https://github.com/CleverRaven/Cataclysm-DDA/issues/32311#issuecomment-570093440) which would fit well with the existing approach, but would be tricky to implement.  I plan to add something simpler initially.  If it proves unwieldy then we can think about how to improve it.
- [x] Test that partial crafting (starting a craft that you can't finish, and resuming later) hasn't been broken.

#### Describe alternatives you've considered
Various options are discussed in the comments for #32311.

This PR only tackles overlapping item requirements.  There could in principle be a similar issue with overlapping tools requirements, which could be solved in the same way.  I haven't seen that be an issue in practice, though, so I'm hoping YAGNI.  In particular, because tool charges are consumed gradually you will probably always at least be able to *start* the craft.

#### Testing
Added several new unit tests to test the requirement refactoring algorithm.

Experiments in-game to test the crafting GUI.

#### Additional context
The crafting code is a complex beast that deals with many semi-orthogonal but interconnected issues.  This is a sufficiently invasive change that I'm fairly sure I must have broken *something*.  In particular, I'm not confident I've used the correct `inventory` in all cases.

Recipe finalization is already the slowest step in game data finalization, and this is making it even slower again.  It's not too bad, even on a debug build as I'm using, but it's something we need to keep in mind.

(My apologies for adding a new function to `player`...)

The new error message that appears in the crafting GUI for this situation:
crafting-detects-overlap
Crafting a survivor telescope is possible with sufficient lenses:
crafting-works-with-overlap-when-appropriate
When you craft and have *all* the lenses, you must now choose between these options:
craft-telescope-1
craft-telescope-2
Things can get more complicated for recipes like the faraday suit.  Here are three options when you have a reasonable selection of chainmail items on hand:
craft-faraday-1
craft-faraday-2
craft-faraday-3
Here's the most crazy possibility, when all 63 options are possible and you must choose from them all.  The uilist code still handles it correctly.  It doesn't look great, but it does work.
craft-faraday-crazy

### CODE REVIEW

**Comment by jbytheway** [comment]
While working on the next steps for this I discovered a bug in basecamp upgrades that needs to be fixed before this can be, so this will be on hold while I work on that.

**Comment by jbytheway** [comment]
The extra features I wanted are now done, although this is now built on top of #33678 
I've added a bunch of screenshots to the PR description above showing the new UI elements.

If anyone has any reasonable suggestions for any names to give the (currently blank) uilist entries pictured there, I'd welcome them.

I still want to do some more testing that partial crafting is still working correctly.

**Comment by jbytheway** [comment]
As I suspected, I had broken partial crafting.  But it's fixed now.

**Comment by jbytheway** [comment]
Now #33678 is merged I'm not aware of any more blockers for this merge.  @ifreund did mention that he was hoping to review the changes, though.

File: src/requirements.cpp [hunk 1]
```diff
@@ -496,11 +498,14 @@ std::vector<std::string> requirement_data::get_folded_components_list( int width
...
 std::vector<std::string> requirement_data::get_folded_list( int width,
         const inventory &crafting_inv, const std::function<bool( const item & )> &filter,
-        const std::vector< std::vector<T> > &objs, int batch, const std::string &hilite ) const
+        const std::vector< std::vector<T> > &objs, int batch, const std::string &hilite,
+        requirement_display_flags flags ) const
 {
     // hack: ensure 'cached' availability is up to date
     can_make_with_inventory( crafting_inv, filter );
 
+    bool no_unavailable = static_cast<bool>( flags & requirement_display_flags::no_unavailable );
```
Comment (ifreund) [inline src/requirements.cpp]:
```suggestion
    const bool no_unavailable = static_cast<bool>( flags & requirement_display_flags::no_unavailable );
```

File: src/requirements.cpp [hunk 2]
```diff
@@ -1087,3 +1100,207 @@ void requirement_data::consolidate()
...
     components = std::move( all_comps );
 }
+
+/// Helper function for deduped_requirement_data constructor below.
+///
+/// The goal of this function is to consolidate a particular item_comp that
+/// would otherwise be duplicated between two requirements.
+///
+/// It operates recursively (increasing @p index with the depth of recursion),
+/// searching for another item_comp to marge @p leftover with.  For each
```
Comment (ifreund) [inline src/requirements.cpp]:
```suggestion
/// searching for another item_comp to merge @p leftover with.  For each
```

File: src/crafting.cpp [hunk 3]
```diff
@@ -472,14 +472,14 @@ std::vector<const item *> player::get_eligible_containers_for_crafting() const
 
 bool player::can_make( const recipe *r, int batch_size )
 {
-    const inventory &crafting_inv = crafting_inventory();
+    inventory crafting_inv = crafting_inventory();
```
[the remark this answers is not in the document]
Comment (jbytheway) [reply src/crafting.cpp]: I didn't realise that would be safe.  Misunderstood what was happening in the implementation of `crafting_inventory`.

File: src/requirements.cpp (hunk 1 above)
Comment (jbytheway) [reply src/requirements.cpp]: Done.
