### PR TITLE
Fix collapse/expand reflow

### LINKED ISSUE #57044: Problems with inventory screen collapsing and expanding
### Describe the bug

There's a problem with the inventory involving containers and collapsing and expanding the inventory listing.

### Steps to reproduce

In an inventory with stuff in a container, navigate to the container holding items:
image
Push the > command to collapse the container list:
image
Now push the < command to re-expand:
image
Close and re-open the inventory and it goes back to normal:
image
But only if you have it expanded. If it's closed when container inventories are collapsed and re-opened, it re-opens collapsed and if you attempt to expand it, you get a slightly different weird menu again:
image

### Expected behavior

Not this. Returning to the regular inventory is preferable.

### Screenshots

_No response_

### Versions and configuration

Latest experimental branch for Windows
Vanilla install

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by IndecisionTree**
#### Summary
Bugfixes "Fix collapsing/expanding reflowing the inventory into a single column"

#### Purpose of change
Fixes #57044 

#### Describe the solution
Inventory entry cell width calculations were being made before revealing/hiding entries that were expanded/collapsed. This didn't matter if an item of greater width was still uncollapsed in that column when it occurred, but would cause an incorrect reflow when there was nothing else in the column.

This PR fixes that by just moving the width calculation til after all entries that are now visible are moved from `entries_hidden` to `entries`.

#### Describe alternatives you've considered
A more extensive rewrite of inventory_ui to make things clearer and better documented which could prevent other bugs in the future.

#### Testing
All tests passed locally. Inventory still seems fully functional as well as other selectors (multidrop and pickup).

#### Additional context
Demo collapsing and expanding the inventory in category mode and then in hierarchy mode with switch to category mode:

https://user-images.githubusercontent.com/84244762/177232507-0593d497-d9e7-4d6c-b9f5-fe6dd7676dda.mp4

### CODE REVIEW

File: src/inventory_ui.cpp [hunk 1]
```diff
@@ -271,23 +271,21 @@ static const selection_column_preset selection_preset{};
...
-            if( prnt.get_item() == topmost_parent ) {
-                break;
-            }
-            it = prnt;
+
+    item_location item = locations.front();
+    while( item.has_parent() ) {
+        item_location parent = item.parent_item();
+        if( parent.get_item()->contained_where( *item )->settings.is_collapsed() ) {
+            return true;
```
Comment (andrei8l) [inline src/inventory_ui.cpp:283]: This breaks uncollapsing items inside the "Examine contents" window (`o` by default)

Comment (IndecisionTree) [reply src/inventory_ui.cpp:283]: My mistake, didn't know about inventory examiner. Should be fixed now. Also, the is_hidden() cleanup is non-essential to this bugfix and can be removed if you want. 

Just saw it along the way when trying to debug the reflow issue and thought it'd be more efficient to shortcircuit the 'or' once it found a parent that was collapsed.

Comment (andrei8l) [reply src/inventory_ui.cpp:283]: In general you shouldn't restyle code unless you're fixing bugs in it. But this bit looks much better now so I think it's OK.
