### PR TITLE
Fix crash by using vehicle welding rig

### LINKED ISSUE #41784: Using Vehicle welder to repair items causes Seg Fault
# Describe the bug
A Seg fault occurs when using the "use the welding rig" from a Vehicle welding rig command to repair items

# Steps To Reproduce
1."e"axmine vehicle rig welder
2. Select "use the welding rig"
3. Have correct repair materials near by
4. Select item to repair
5. Seg Fault

# Expected behavior
Be able to repair with the Vehicle welding rig without a crash

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3669-g1c69950 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context
[Crash-Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4867132/Crash-Debug.zip)

[Seg Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4867134/Seg.Save.zip)
(Welding rig adjacent with a damaged crow bar in inventory with scrap nearby to do the steps)

### PR DESCRIPTION
**Pull request by Menschheit**
#### Summary

SUMMARY: Bugfixes "Modifiy weldrig_hack used in `activity_handlers::repair_item_finish`"

#### Purpose of change

Fix #41784.

#### Describe the solution

In #41700 I modified the pseudo item to allow using vehicle mounted tools, but I am relative new to the codes and didn't know how long term activity is proccessed.

I checked the codes today and found out that `activity_handlers::repair_item_finish` uses weldrig_hack to simulate the energy drain and again a pseudo item will be created. So I did the same thing to prevent possible nullptr occuring during checking ammo.

#### Describe alternatives you've considered

nothing

#### Testing

Successfully repaired my damaged weapon by using welding rig.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -2546,7 +2546,11 @@ struct weldrig_hack {
 
     item &get_item() {
         if( veh != nullptr && part >= 0 ) {
-            pseudo.charges = veh->drain( itype_battery, 1000 - pseudo.charges );
+            item pseudo_magazine( pseudo.magazine_default() );
+            pseudo.put_in( pseudo_magazine, item_pocket::pocket_type::MAGAZINE_WELL );
+            pseudo_magazine.contents.clear_items();
```
Comment (BevapDin) [inline src/activity_handlers.cpp:2551]: This statement appears to be pointless. It modifies the variable `pseudo_magazine` (well, one of its members), but that should not have any effect on other variables. It would make sense *before* the call to `pseudo.put_in`.
