### PR TITLE
Auto-travel; prompt when overburdened, and allow stamina-resting

### LINKED ISSUE #37785: Auto-move doesn't rest when moving overburdened
#  Steps To Reproduce

1. Become severely overburdened.
2. `m`, `WW` somewhere.
3. Lots of pain

# Expected behavior

Resting as needed to keep the stamina meter green or yellow.

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-11988-gf45a15f107-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Auto-travel; prompt when overburdened, and allow stamina-resting"```

#### Purpose of change
Fixes #37785 

#### Describe the solution
Prompt when starting autotravel, if player is overburdened, if the yare sure they want to.
Also, fix the fact that the travelling activity, never stopped to catch breath like other activities did.
This was made harder by the fact that the travellign activity, every do_turn() call, nulled itself, and the stamina did not drop as a result of its do_turn(), it dropped afterwards, when the player pathed their automove route, I did something which is perhaps a bit inelegant? and simulated a small drop in stamina after travel do_turn(), so that it passed the stamina < previous_stamina test in player_activity.cpp

#### Describe alternatives you've considered
N/A

#### Testing
Picked u pan XL wind turbine, used autotravel, I got the prompt, and if I said yes, then the player moved but paused to catch breath every second or so, so stamina didnt drain completely.

#### Additional context
N/A

### CODE REVIEW

File: src/player_activity.cpp [hunk 1]
```diff
@@ -158,11 +158,18 @@ void player_activity::do_turn( player &p )
         p.drop_invalid_inventory();
         return;
     }
-
+    const bool travel_activity = id() == activity_id( "ACT_TRAVELLING" );
```
Comment (ZhilkinSerg) [inline src/player_activity.cpp]:
```suggestion
    const bool travel_activity = id() == ACT_TRAVELLING;
```

Comment (ZhilkinSerg) [reply src/player_activity.cpp]: You would possibly need to add `#include "cata_string_consts.h"` on top as well.

File: src/overmap_ui.cpp [hunk 2]
```diff
@@ -1483,7 +1483,13 @@ static tripoint display( const tripoint &orig, const draw_data_t &data = draw_da
             }
             const tripoint player_omt_pos = g->u.global_omt_location();
             if( !g->u.omt_path.empty() && g->u.omt_path.front() == curs ) {
-                if( query_yn( _( "Travel to this point?" ) ) ) {
+                std::string confirm_msg;
+                if( g->u.weight_carried() > g->u.weight_capacity() ) {
+                    confirm_msg = _( "You are overburdened, are you sure you want to travel? ( it may be painful )" );
```
Comment (Night-Pryanik) [inline src/overmap_ui.cpp]:
```suggestion
                    confirm_msg = _( "You are overburdened, are you sure you want to travel (it may be painful)?" );
```

File: src/player_activity.cpp [hunk 3]
```diff
@@ -158,11 +158,18 @@ void player_activity::do_turn( player &p )
...
     // This might finish the activity (set it to null)
     type->call_do_turn( this, &p );
     // Activities should never excessively drain stamina.
-    if( p.get_stamina() < previous_stamina && p.get_stamina() < p.get_stamina_max() / 3 ) {
+    // adjusted stamina because;
```
Comment (Night-Pryanik) [inline src/player_activity.cpp]:
```suggestion
    // adjusted stamina because
```

File: src/player_activity.cpp [hunk 4]
```diff
@@ -158,11 +158,18 @@ void player_activity::do_turn( player &p )
...
+    // autotravel dosnt reduce stamina after do_turn()
```
Comment (Night-Pryanik) [inline src/player_activity.cpp]:
```suggestion
    // autotravel doesn't reduce stamina after do_turn()
```

File: src/cata_string_consts.h [hunk 5]
```diff
@@ -4,6 +4,7 @@
 
 #include "type_id.h"
 #include "player_activity.h"
+#include "itype.h"
```
Comment (BevapDin) [inline src/cata_string_consts.h]: Why is this required in this header? There are no other changes to the header, so why is this suddenly required?

Comment (davidpwbrown) [reply src/cata_string_consts.h]: It could've been something weird, but for some reason cata_string_consts.h started complaining about not knowing what itype was, this fixed it, no idea why it was required or why it started complaining.
Just wouldnt compile without.

Ill try a rebase now.

Comment (ZhilkinSerg) [reply src/cata_string_consts.h]: That is due to circular reference of headers (`cata_string_consts.h` <-> `player_activity.h`). I want to to resolve it in #38141.

Comment (davidpwbrown) [reply src/cata_string_consts.h]: ah ok, thanks.
