### PR TITLE
vehicles: stop solar panels from charging in moonlight

### LINKED ISSUE #29443: 0.D Upgraded solar panels working well even in complete darkness
**Describe the bug**  
Upgraded solar panels working in the cloudy day, night, and even indoors.
**To Reproduce**  
1. Build a generator indoors
2. Expand it outside the building
3. Build upgraded solar panels outside and indoors 

**Expected behavior**  
Solar panels working well on a clear day, not so good on a cloudy day, and not at all at night and/or in a dark building.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D release version
 - Graphics version: Terminal
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "filthy_morale",
  "craftgp",
  "safeautodoc",
  "brightnights",
  "FIC_Weapons",
  "growable-pots",
  "Medieval_Stuff",
  "More_Survival_Tools",
  "modular_turrets",
  "Salvaged_Robots",
  "mutant_npcs",
  "more_locations",
  "FujiStruct",
  "oa_additional_buildings_mod",
  "Urban_Development",
  "boats",
  "blazemod",
  "Tanks",
  "necromancy"
]

Untitled

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "vehicles: stop solar panels from charging in moonlight"```

#### Purpose of change
Fixes #29443 
Solar panels were getting moonlight that was up to 10% as powerful as sunlight and recharging at night.  Actual moonlight is 1/400,000 the brightness of sunlight and should not meaningfully charge solar panels.

#### Describe the solution
Solar panels were accumalating power at 10% of normal rates because sunlight() is used both to get minimum moonlight levels for vison and to get minimum moonlight levels for solar panels.  Add a boolean value to sunlight() that defaults to the current behavior for vision, but can be set to false to get 0 sunlight at night for weather purposes.

Adjust the vehicle power test to include a test to make sure that solar panels are not charging at night.

### CODE REVIEW

File: src/calendar.h [hunk 1]
```diff
@@ -550,8 +550,11 @@ bool is_sunrise_now( const time_point &p );
 double current_daylight_level( const time_point &p );
 /** How much light is provided in full daylight */
 double default_daylight_level();
-/** Returns the current sunlight or moonlight level through the preceding functions. */
-float sunlight( const time_point &p );
+/** Returns the current sunlight or moonlight level through the preceding functions.
+ *  By default, returns sunlight level for vision, with moonlight providing a measurable amount
+ *  of light.  with vision == false, returns sunlight for solar panel purposes, and moonlight
+ *  provides 0 light */
+float sunlight( const time_point &p, const bool vision = true );
```
Comment (ZhilkinSerg) [inline src/calendar.h]:
```suggestion
float sunlight( const time_point &p, bool vision = true );
```

Comment (mlangsdorf) [reply src/calendar.h]: why remove the const?  it's not like vision's value should change in the function.

Comment (ZhilkinSerg) [reply src/calendar.h]: To appease clang-tidy:

image

Comment (mlangsdorf) [reply src/calendar.h]: Things I learn.
