### PR TITLE
Comestible test update and fruit pulp kcal decrease

### LINKED ISSUE #28444: Plum fruit juice has negative calories
**Describe the bug**  
Made fruit juice from 2 plums

**To Reproduce**  
1. Get 2 plums
2. Make fruit juice using recipe that consumes both

**Expected behavior**  
Fruit juice with >0 calories

**Screenshots**  
fruit_juice_recipe
fruit_juice

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version: 0.C-37566-g60ad4a4
 - Graphics version: Tiles
 - Mods loaded: active_mods

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Infrastructure "Adds byproduct calculation to recipe permutation tests and adjusts kcal in failed tests"```
#### Purpose of change

the recipe permutation calculation did not include byproducts, which is a pretty important thing to include when you're trying to make sure comestibles don't have a negative (or zero, but we'll address that later) kcal value!
Fixes #28444
#### Describe the solution

moves a couple of the bools outside of the for loop to hopefully improve the test speed, and adds another function to calculate the kcal from byproducts and then subtract them from the output of the recipe.

additionally put a check that the minimum recipe permutation would have a kcal value of at least 0.
as a result, needed to reduce kcal of juice_pulp

### CODE REVIEW

File: tests/comestible_tests.cpp [hunk 1]
```diff
@@ -93,30 +113,35 @@ item food_or_food_container( item it )
 TEST_CASE( "recipe_permutations" )
 {
     for( auto i = recipe_dict.begin(); i != recipe_dict.end(); i++ ) {
-        all_stats mystats = run_stats( recipe_permutations(
-                                           i->first.obj().requirements().get_components() ) );
         // the resulting item
         item res_it = food_or_food_container( i->first.obj().create_result() );
```
Comment (AMurkin) [inline tests/comestible_tests.cpp]: `i->first.obj()` - probably worth it to create a variable for it.

File: tests/comestible_tests.cpp [hunk 2]
```diff
@@ -76,7 +76,27 @@ std::vector<std::vector<item_comp>> recipe_permutations( const
     return output;
 }
 
-all_stats run_stats( std::vector<std::vector<item_comp>> permutations )
+int byproduct_calories( std::vector<item> byproducts )
```
Comment (AMurkin) [inline tests/comestible_tests.cpp]: You may pass a recipe here instead. And call the `create_byproducts()` on it.

**Comment by AMurkin** [comment]
Error from Jenkins log:
```
comestible_tests.cpp:99:76: error: unused parameter 'byproduct_calories' [-Werror,-Wunused-parameter]
all_stats run_stats( std::vector<std::vector<item_comp>> permutations, int byproduct_calories )
                                                                           ^
```
