### PR TITLE
Fix NPC dropping equipment

### LINKED ISSUE #26121: NPC drops equipment when told to use new equipment, even if new equipment is rejected.
**Describe the bug**  
For example, an NPC will drop what they are wearing on the ground, when told to use an item that would replace what they are currently wearing, even if they reject the item they are being told to use (for instance, if the item is too encumbering due to mutations.)

**To Reproduce**  
1. Recruit an NPC (with armor inhibiting mutations if needed).
2. Have the NPC wear an item they can wear.
3. Have the NPC wear an item they can't wear.
4. NPC's item will be on the ground (along with other items if the item gave storage capacity,)

**Expected behavior**  
NPC should not drop current gear if the new gear is rejected.

**Versions and configuration(please complete the following information):**
 - OS [Win 7 64-bit]
 - Game Version [Experimental Build 7983]
 - Graphics version [Tiles]
 - Mods loaded [dda, disable npc needs, filthy clothing, simplified nutrition, bionics systems mod, deadleaves' fictional guns, extended realistic guns, medieval and historic content, modular turrets, salvaged robots, cataclysm++, npc traits, mxotto+ cosmetics p10, mining mod, mutant npcs, more locations, fuji's more buildings, more city locations, oa's additional buildings mod, boats, folding parts pack, vehicle additions pack, tanks and other vehicles, arcana and magic items, extended_buildings, statsthroughskills]

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Prevent NPC from dropping equipment"

#### Purpose of change
Fixes #26121
Prevent NPC dropping all worn items when ordered to wear impossible equipment.

#### Describe the solution
I added a new parameter to can_wield and rearranged it slightly to allow NPC logic to prevent dropping equipment when it can't help.  I also noticed that the splint logic would allow double equipping so I fixed that.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -2279,12 +2279,50 @@ bool Character::can_use( const item &it, const item &context ) const
     return true;
 }
 
-ret_val<bool> Character::can_wear( const item &it ) const
+ret_val<bool> Character::can_wear( const item &it, bool with_equip_change /* = false*/ ) const
```
Comment (ZhilkinSerg) [inline src/character.cpp]:
```suggestion
ret_val<bool> Character::can_wear( const item &it, bool with_equip_change ) const
```
