### PR TITLE
Only list tilesets once

### LINKED ISSUE #36617: Tilesets listed twice in the options menu
# Describe the bug

Every entry on the list of Tilesets avaliable in the Options menu seems to be duplicated.

# Steps To Reproduce

Go to Settings > Options > Graphics tab > "Choose Tileset" and check the list of possible options on top. 

# Expected behavior

Only one option for each Tileset avaliable.

# Screenshots

Default options from a fresh install: 

Image 2008

After downloading "UltimateCataclysm" Tileset, confirming there's only one entry of it on the "gfx" folder and rechecking the listing: 
Image 2010

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-10932-g9eb7975 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Urban Development [Urban_Development],
    Mapgen Demo [mapgen_demo],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Beta National Guard Camp [national_guard_camp],
    Safe Autodoc [safeautodoc],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

"gfx" folder seems to only have one of each tileset, "options.json" shows duplicated entries.

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
 ```SUMMARY: Bugfixes "Only list tilesets once"```

#### Purpose of change
Fixes #36617 

#### Describe the solution
When building tileset list check if the the tileset is already in the list before adding it.

#### Testing
image

#### Additional context
There might be a better way to compare two vector

### CODE REVIEW

File: src/options.cpp [hunk 1]
```diff
@@ -916,12 +916,19 @@ std::vector<options_manager::id_and_option> options_manager::build_tilesets_list
...
-    auto user_tilesets = load_tilesets_from( PATH_INFO::user_gfx() );
-    result.insert( result.end(), user_tilesets.begin(), user_tilesets.end() );
+    std::vector<options_manager::id_and_option> user_tilesets = load_tilesets_from(
+                PATH_INFO::user_gfx() );
+    for( options_manager::id_and_option id : user_tilesets ) {
+        if( std::find( result.begin(), result.end(), id ) == result.end() ) {
+            result.emplace_back( id );
+        }
+    }
+   // result.insert( result.end(), user_tilesets.begin(), user_tilesets.end() );
```
Comment (Night-Pryanik) [inline src/options.cpp]:
```suggestion
```

Comment (Fris0uman) [reply src/options.cpp]: Oops
