### PR TITLE
Fix disassembly time inconsistency in Butcher UI

### LINKED ISSUE #41897: Disassembly takes longer than is stated in the UI
# Describe the bug
The disassembly UI tells the player how much time the disassembly is going to take, but the actual time it takes is longer.

# Steps To Reproduce
1. Drop two short strings on the ground
2. Wish for a pair of scissors
3. Open the [B]utcher menu
4. See that the option "disassemble everything once" claims it will take 5 minutes
5. Select the option "disassemble everything once"
6. Watch 10 minutes go by

An even bigger difference:
1. Drop two **long** strings on the ground
2. --//--
3. --//--
4. See that the option "disassemble everything **recursively**" claims it will take 10 minutes
5. Select the option "disassemble everything **recursively**"
6. Watch 70 minutes go by

# Expected behavior

The UI should accurately display the actual disassembly time

# Screenshots

none

# Versions and configuration
```
- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 32 (Thirty Two); Release: 32; Codename: ThirtyTwo; 
- Game Version: 0.E-3777-gbfaf4fe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
```

# Additional context

none

### PR DESCRIPTION
**Pull request by LcsTen**
#### Summary

SUMMARY: Bugfixes "Fix disassembly time inconsistency in Butcher UI"

#### Purpose of change

Fix inconsistency between displayed and actual disassembly time in [B]utcher UI. Fixes #41897.

#### Describe the solution

The time for "Disassemble everything once" was previously the time to disassemble one item of each stack, although the whole stacks were disassembled. It was changed accordingly.
The time for "Disassemble everything recursively" was previously the time to disassemble all the visible items, not counting the resulting components. I created a function item::get_recursive_disassemble_moves in order to compute the time to disassemble the visible items as well as their resulting components.
I renamed the variables from ``time_to_disassemble`` to ``time_to_disassemble_once`` and from ``time_to_disassemble_all`` to ``time_to_disassemble_recursive`` in order to make their purposes clearer.

#### Testing

Reminders:
- Disassemble a short string takes 5 minutes and results in 50 units of thread.
- Disassemble a long string takes 5 minutes and results in 6 short strings.
- A unit of thread can't be disassembled.
- Disassemble a light wooden frame made of ropes (default) takes 4 minutes and results in 3 short ropes.
- Disassemble a short rope takes 7 minutes and 30 seconds and results in 6 long strings.
- Disassemble a light wooden frame made of vines takes 4 minutes and results in 3 short vines.
- A short vine can't be disassembled.
Note: Displayed in-game times are approximate.

1. Wish for a pair of scissors
2. Wish for two short strings and drop them on the ground.
3. Open the [B]utcher menu and make sure the values for both "Disassemble everything once" and "Disassemble everything recursively" are **10 minutes** (``2 * 5 minutes``).
4. Dispose of the two short strings, wish for two long strings and drop them on the ground.
5. Open the [B]utcher menu and make sure the value for "Disassemble everything once" is **10 minutes** (``2 * 5 minutes``) and the value for "Disassemble everything recursively" is **70 minutes** (``2*5 + 2*6*5 minutes``), but see below.
 5a. Because of ``the to_string_clipped`` function, the displayed time will be **1 hour**. You may want to temporarily replace ``to_string_clipped`` by ``to_string`` to see **1 hour and 10 minutes**.
1. Dispose of the two long strings, wish for two light wooden frame and drop them on the ground.
1. Open the [B]utcher menu and make sure the value for "Disassemble everything once" is **8 minutes** (``2 * 4 minutes``) and the value for "Disassemble everything recursive" is **1313 minutes** (``2*4 + 2*3*7.5 + 2*3*6*5 + 2*3*6*6*5 minutes``).
	7a. Then again, the interface will show **21 hours**, modify it so it shows **21 hours and 53 minutes**.
1. Dispose of the two light wooden frames, wish for 6 short vines and 6 planks, craft two light wooden frames using the short vines and drop them on the ground.
1. Open the [B]utcher menu and make sure the values for both "Disassemble everything once" and "Disassemble everything recursively" are **8 minutes** (``2 * 4 minutes``).

Edit: Added a test case
Edit: Corrected a test result

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -8717,19 +8742,20 @@ void game::butcher()
...
+            int time_to_disassemble_once = 0;
+            int time_to_disassemble_recursive = 0;
             for( const auto &stack : disassembly_stacks ) {
                 const int time = recipe_dictionary::get_uncraft( stack.first->typeId() ).time_to_craft_moves(
                                      get_player_character() );
-                time_to_disassemble += time;
-                time_to_disassemble_all += time * stack.second;
+                time_to_disassemble_once += time * stack.second;
+                time_to_disassemble_recursive += get_recursive_disassemble_moves( get_player_character(),
+                                                 stack.first->typeId(), stack.second );
```
Comment (mqrause) [inline src/game.cpp:8752]: Using item::typeId here will always calculate the time for the default recipe, not for the actual components the item might be made of. So for example a light frame made from short vines will calculate as if it was made from short ropes instead. Vines are not disassemblable, while short ropes disassemble down to threads. Things with a lot of disassembly depth also make this really slow, because every single resulting item will be calculated (1 light frame -> 3 short ropes -> 18 long strings -> 104 short strings).

I'd suggest moving the method to item and then calling it directly on the item to get the duration for the actual components. I'm not qualified to make suggestions to improve performance, though.

Comment (LcsTen) [reply src/game.cpp]: Thank you for your feedback, I moved the method to item and modified the signature. It should now take the actual components of the item into account, I added a test case for it.
Unfortunately, it seems there's a bug of some sort. The last time I tried, it displayed ``21 hours and 53 minutes`` instead of ``21 hours and 50 minutes`` when disassembling the light wooden frame made of short rope. I'm still tracking the issue.
