### PR TITLE
Mp3/stereo sound vs player position fixes, mp3 behavior fixes

### LINKED ISSUE #10880: Vehicle stereo system string badness
Version: 0.B-2487-ge57fa9f

1. Get a Music CD and a vehicle with stereo system installed.
2. Play music in the vehicle (i.e. `Turn on music` in the vehicle control menu).
3. Walk away from the vehicle.

```
From the south you hear You listen to a
funky bassline.
From the south you hear You listen to a
sweet guitar solo!
```

Should probably be `From the <direction> you hear a <music>` or something.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7777961-vehicle-stereo-system-string-badness?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tvm1**
- Checks player position vs the music source and formats the strings properly now
- Makes mp3 player actually print music messages (was semi-broken, as the zero volume of the player's music wasn't handled properly during noisy weather)
- Player has to have mp3 player in inventory now to get morale boost

Closes #10880.

### CODE REVIEW

File: src/iuse.cpp [hunk 1]
```diff
@@ -5628,8 +5628,12 @@ void iuse::play_music( player * const p, const tripoint &source, int const volum
     if( int(calendar::turn) % 50 == 0 ) {
         // Every 5 minutes, describe the music
         auto const music = get_music_description( *p );
-        if( !music.sound.empty() ) {
+        // mp3 or stereo playing on the same square
+        if( !music.sound.empty() && p->pos() == source ) {
             sound = string_format( _("You listen to %s"), music.sound.c_str() );
+        } else if ( !music.sound.empty() ) {
+            // music from other squares, leave only music description
+            sound = string_format( _("%s"), music.sound.c_str() );
```
Comment (BevapDin) [inline src/iuse.cpp]: Translating the string "%s" is a bit pointless, the translators have no context information.
Calling `string_format` like this is similar pointless. It will just return the second argument without any changes.

Just write `sound = music.sound;`

Comment (narc0tiq) [inline src/iuse.cpp]: Indeed, you could even default to it and override only if necessary, i.e.:
```C++
if(!music.sound.empty()) {
    sound = music.sound
    if(source == p.pos()) {
        sound = string_format( _("You listen to %s"), music.sound.c_str() );
    }
}
```

**Comment by tvm1** [comment]
All fixed.

File: src/iuse.cpp [hunk 2]
```diff
@@ -5646,7 +5651,10 @@ void iuse::play_music( player * const p, const tripoint &source, int const volum
 int iuse::mp3_on(player *p, item *it, bool t, const tripoint &pos)
 {
     if (t) { // Normal use
-        play_music( p, pos, 0, 50 );
+        if (p->has_item(it)) {
+            // player has earbuds on, we can listen
+            play_music( p, pos, 5, 50 );
```
Comment (BevapDin) [inline src/iuse.cpp]: Any reason you changed the volume to 5? Ah, I see: so you can hear it during rain.

@kevingranade This conflicts with the ambient noise from the weather. The character should always be able to listen to their MP3 player (assuming they wear the earbuds), but even drizzling reduces the effective range of the sound. if the MP3 player uses volume=0, it will not be heard by the character during slightly bad weather. If it uses a larger volume, it will be heard by nearby Creatures as well.

Another bug: `player::can_hear` does not respect the weather based hearing reduction. `player::can_hear` returns true (and the music morale is applied), but the sounds class will not print the music description because the bad weather prevents the character from actually hearing it (so thinks the sounds class).

I suggest a special case for sounds having volume 0 and coming from the same tile as the player: noise from weather should be ignored there.

**Comment by BevapDin** [comment]
The volume change needs discussion or at least acknowledgment (the code is fine). Giving the MP3 player a volume of 5 will alter nearby monsters (if they are within the range). Bad weather will prevent this because of the noise from weather, but if you do use it during clear weather and the monster is near enough, it will hear it.

However, default footstep sound is 6, so it's even louder and the monster might already be alarmed by the footstep and not by the MP3 player. There are traits that reduce footstep sounds to 2 (and an artifact that reduces it to 0).

**Comment by tvm1** [comment]
I'm not keen of that change either, but It's currently only way, how to get it handled correctly.

I think that best would be to handle the mp3 player separately from the rest of the `play_music`, because all we want to do is to print `"You listen to %s"` and boost morale. There's IMHO no point in processing the mp3 player via `sounds::ambient_sound()` where we have to battle weather and such

My assumptions:
- PC should be able to hear the mp3 player (with earbuds on) unless deaf
- Mp3 player should produce absolutely no sound to surrounding environment
- Active mp3 player should prevent player from hearing other sounds (set some effect?)

`play_music` would just need additional argument, if we're doing in-ear listening, then do the above.

I could do this, opinions ?

**Comment by tvm1** [comment]
Perhaps we could continue to use `0 volume` and assume that such volumes come from in-ear devices and handle them accordingly.

**Comment by BevapDin** [comment]
> I think that best would be to handle the mp3 player separately from the rest of the  play_music , because all we want to do is to print  "You listen to %s"  and boost morale. There's IMHO no point in processing the mp3 player via  sounds::ambient_sound()  where we have to battle weather and such

Yes.

> Mp3 player should produce absolutely no sound to surrounding environment

Can be done by skipping the whole sound part when it's not in the inventory.

> Active mp3 player should prevent player from hearing other sounds (set some effect?)

I consider this as optional. This is very different from person to person.

Probably not completely deaf but a reduction like it comes from noise weather is fine. An effect might be be useful,  indeed. Needs to be checked either in the sound handling or in `player::hearing_ability` or both, probably.

But make sure that the MP3 player sound does not prevent the MP3 player sound, that means the check for whether the character can hear the MP3 player must not include the deaf-like effect from above.

**Comment by kevingranade** [comment]
Sounds reasonable, just check if player is capable of hearing, and apply
some amount of hearing reduction, and bypass the normal ambient noise
processing.

**Comment by tvm1** [comment]
Well, it's all in. I've tested it quite thoroughly (including noise-cancelling gear)and didn't notice any problems. Player gets reduced hearing effect, if all conditions are met and he's actually not deaf. `can_hear` handles zero volume sounds originating from square as 'in-ear' and unless deaf, they're always audible to PC. This also solves the mp3 player emitting noise into area around.

I've made the hearing reduction `*= .25` while it may sound harsh to someone, I think that it is still quite liberal.

I've added a future TODO for `can_hear`, because as said earlier, it is currently not handling sound attenuation caused by weather.
