### PR TITLE
Fix harvest spawning.

### LINKED ISSUE #25187: "Assertion failed" when collecting farm plot
**Describe the bug**  
When I collect grown plants from my farm plot, the following window pops up sometimes (maybe 10% chance):

    Assertion failed!

    Program: D:\Games\Cataclysm\cataclysm-tiles.exe
    File: src/optional.h, Line 45

    Expression: full

When the problem does not occur, i get 1 _wild vegetables_ and 1 _withered plant_ to collect. When the problem triggers, i only get 1 _withered plant_ to collect and find 1 _wild vegetables_ under my feet later.

Continuing after the assertion does not seem to cause any problems.

The plots were planted on older game version before #24291 .

**To Reproduce**  
1. Load the attached save.
2. Go to the farm plots to the left and collect every grown plant.

**Expected behavior**  
All plants should be collected the same way without errors.

Also using assertion popups for release builds is very annoying, I accidentally closed my game few times. Better to report such errors using in-game error handler.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10 x64
 - Game Version: 0.C-31236-g981effa 
 - Graphics version: Tiles
 - Mods loaded: `[
  "dda",
  "Experimental-Z-Level",
  "More_Survival_Tools",
  "blazemod",
  "Tanks",
  "Urban_Development",
  "boats",
  "filthy_morale",
  "makeshift",
  "more_buildings",
  "more_locations",
  "mutant_npcs",
  "national_guard_camp",
  "npc_traits",
  "craftgp",
  "brightnights",
  "bio_mod"
]`

**Additional context**  
[Saved game](https://github.com/CleverRaven/Cataclysm-DDA/files/2325932/default.zip)

### PR DESCRIPTION
**Pull request by Vasyan2006**
#### Summary
```SUMMARY: Bugfixes "Remove rare chash during harvesting"```

#### Purpose of change
Remove rare crash during harvesting a plant.
Close #25187

#### Describe the solution
Move checking the plant type outside the loop. Dont understand why it works, but I was not able to reproduce this bug after.

### CODE REVIEW

File: src/iexamine.cpp [hunk 1]
```diff
@@ -1841,11 +1841,13 @@ void iexamine::aggie_plant( player &p, const tripoint &examp )
         } else {
             std::list<item> harvest_items = get_harvest_items( seed );
             proceed_plant_after_harvest( examp );
-            for( auto &i : harvest_items ) {
-                if( seed.type->seed->is_shrub || seed.type->seed->is_mushroom ) {
-                    // shrubs and mushrooms add items at player position
+            if( seed.type->seed->is_shrub || seed.type->seed->is_mushroom ) {
```
Comment (ZhilkinSerg) [inline src/iexamine.cpp]: Maybe something like this?

```CPP
            // shrubs and mushrooms add items at player position
            const tripoint harvest_pos = ( seed.type->seed->is_shrub || seed.type->seed->is_mushroom ) ? p.pos() : examp;
            for( auto &i : harvest_items ) {
                g->m.add_item_or_charges( harvest_pos, i );
            }
```

File: src/iexamine.cpp [hunk 2]
```diff
@@ -1841,11 +1841,13 @@ void iexamine::aggie_plant( player &p, const tripoint &examp )
         } else {
             std::list<item> harvest_items = get_harvest_items( seed );
             proceed_plant_after_harvest( examp );
```
Comment (Robik81) [inline src/iexamine.cpp]: It is no longer safe to access seed variable after proceed_plant_after_harvest is called, because that function calls `g->m.i_clear( examp );` which kills the seed you are referring to. If you need some information from seed, you should store it in some temporary variable before calling the proceed_plant_after_harvest.

**Comment by Vasyan2006** [comment]
Now I see, thanks. I created harvest_items list to save it after deleting the seed, but forgot to do it for planttype checks.

**Comment by alanbrady** [comment]
I think the reason this fixes this is because when then game does add_item_or_charges, if there's multiple seeds on the ground, it does a merge_charges.  If the `seed` item we were holding on to was the item that got merged, then our `seed` object is now a reference to an object that doesn't exist anymore.
