### PR TITLE
Handles proper claws/blade deactivation during CBM removal

### LINKED ISSUE #12420: Bionic removal with active bioclaws or bioblade
Remove any bionic with active bionic claws or bionic blade cause these bionics (claws or blade) stuck in active mode. 
How to reproduce:
  Get character with bionic claws ("bionic monster" profession for example)
  Get fist aid kit (for bionic removal)
  Activate claws
  Remove some other bionic using bionic screen ("p" key)
  Try activate bionic claws again. We have claws in hand, but after bionic removal game disable active bionic. So game try to activate claws again and this fails because claws already in hand. As result character stuck with claws in his hands and no way to deactivate claw. Same for bionic blade.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/16261910-bionic-removal-with-active-bioclaws-or-bioblade?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by tvm1**
All installed CBMs are deactivated after uninstall of any CBM. Thus it's logical to remove the claws/blade from hand before performing surgery. Otherwise PC ends up with disabled Claws/Blade bionic, but with active weapon still in hand.

Closes #12420

### CODE REVIEW

File: src/bionics.cpp [hunk 1]
```diff
@@ -1278,6 +1278,21 @@ bool player::uninstall_bionic(std::string const &b_id)
         return false;
     }
 
+    // surgery is imminent, retract claws or blade if active
+    if (has_bionic("bio_claws")) {
+        if (weapon.type->id == "bio_claws_weapon") {
+            add_msg(m_neutral, ("You withdraw your claws."));
```
Comment (BevapDin) [inline src/bionics.cpp]: Ahhh, so close. The `(` and `)` are there, but the `_` is missing. That means: No translation for you!

**Comment by tvm1** [comment]
So close, I'm saddened. Translation must be possible. Will be fixed!

File: src/bionics.cpp (hunk 1 above)
Comment (Rivet-the-Zombie) [inline src/bionics.cpp]: Drat! I always forget to check for translation bracketing.
