### PR TITLE
Tile Memorisation Fix

### LINKED ISSUE #26646: Map memory only extends as far as the active window can "see".
**Describe the bug**  
Map memory only "remembers" what is on the active window. That means that if something is visible to the character but outside of the player's active window, it will not be remembered. This is affected among others by "z"ooming in and out, or by looking around (x).

**To Reproduce**  
1. Go in game underground or at night
2. Use light of some sort to illuminate a large area (I used headlights while driving at night)
3. After turning it off and moving, you will only "remember" that which your active window saw

**Expected behavior**  
I'd expect anything the character sees to be remembered, whether I had my active window over it, simply because map memory represents the character's memory, not the player's.

**Screenshots**  
image
(Here I was driving at night with my headlights on. I quickly went to furthest zoom then back to "normal" zoom. I only remember up to what I saw when my zoom was very far.

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-34412-gd37cc74
 - Graphics version: Tiles
 - Mods loaded: Disable NPC needs, Filthy Clothing, No Fungal Monsters, More Survival Tools

**Additional context**  
This issue was reproduced by another user on the Discord.

### PR DESCRIPTION
**Pull request by LetterShapedGlyphs**
#### Summary
```SUMMARY: Bugfixes "Allows for memorising visible but not displayed tiles."```

#### Purpose of change
Fixes #26646 - Player does not memorise tiles not displayed on screen even when visible.

#### Describe the solution
Following all of the draw actions to render visible tiles, all tiles within vision range which were not just drawn, are passed through the draw actions to trigger memory. Because draw_from_id_string terminates when asked to draw something outside the window, the memorisation function is called without any extra work beyond an int comparison per visible tile.

#### Describe alternatives you've considered
Separating the memorisation functionality from the drawing process entirely would prevent the need for relying on draw_from_id_string knowing what tiles are within the bounds of the window, but said decoupling would result in quite a bit of code duplication and/or refactoring to make it work properly.

#### Additional context
In terms of cost, this should be even less weight than the mini-map which can be displayed, as it goes through a very similar process but skips things that have "already been done".
Currently, this functionality does not apply to non-tile displays of the game, and touches code that is at the moment unfamiliar to me.

### CODE REVIEW

File: src/cata_tiles.cpp [hunk 1]
```diff
@@ -1184,6 +1184,26 @@ void cata_tiles::draw( int destx, int desty, const tripoint &center, int width,
         }
     }
 
+    //Memorize everything the character just saw even if it wasn't displayed.
+    for( int y = 0; y < MAPSIZE * SEEY; y++ ) {
```
Comment (ZhilkinSerg) [inline src/cata_tiles.cpp]: There is `points_in_radius` function to get collection of tripoints - maybe you can use it here?

Comment (Karthas077) [reply src/cata_tiles.cpp]: I would, except that both makes it harder to verify that I'm not re-checking a tile that was just handled, and makes how this code is formatted different from both draw_pixel_minimap and the draw function this is inside (both of which use nested for loops)

**Comment by OzoneH3** [comment]
This broke ISO tiles #26864
