### PR TITLE
Correctly describe an obstacle

### LINKED ISSUE #16095: Incorrect description when a character is bumping into car
I'm blind, and there is a car with headlights turned on to the south of me. When I'm going south, there is a message like in pic above. I suppose there should be description of car's part, not a terrain.

### PR DESCRIPTION
**Pull request by illi-kun**
Fixes #16095.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -12097,10 +12097,22 @@ bool game::plmove(int dx, int dy, int dz)
...
     // Invalid move
-    const bool waste_moves = u.has_effect( effect_blind ) || u.worn_with_flag("BLIND") || u.has_active_bionic("bio_blindfold") || u.has_effect( effect_stunned );
+    const bool waste_moves = u.is_blind() || u.has_active_bionic("bio_blindfold") || u.has_effect( effect_stunned );
     if( waste_moves || dest_loc.z != u.posz() ) {
+        std::string obtacle_name;
+        int part;
+        vehicle *veh = m.veh_at( dest_loc, part );
+        if( veh != nullptr ) {
+            // redefine variable as id of obtacle part
+            part = veh->obstacle_at_part( part );
```
Comment (BevapDin) [inline src/game.cpp]: That functions name is kind of inconsistent, it should be `obtacle_at_part`. Or change "obtacle" in the variable name to "obstacle". Just for consistency.

Comment (illi-kun) [inline src/game.cpp]: Oops, I'll fix this in a moment, thanks for the note.
