### PR TITLE
Fix for some unarmed styles giving bashing skill

### LINKED ISSUE #23454: Martial art styles are using Bashing Weapons instead of Unarmed Combat
Game version: latest

Operating system: Windows 7

Tiles or curses: tiles

Mods active: N/A

### Expected behavior
When using martial arts without a weapon, the unarmed combat skill should be used.

### Actual behavior
The bashing weapons skill is used instead, the damage output is very low.

### Steps to reproduce the behavior
Create a Blackbelt character, choose Muay-Thai as a preffered style (should work with any style, it's just the one I typically use), try to punch some zombies. Watch yourself dealing ridiculously low damage and training Bashing Weapons instead of Unarmed Combat. Upon selecting "No style" everything works as intended.

Looks like the bug was introduced in one of these commits https://github.com/CleverRaven/Cataclysm-DDA/commit/651fce62a30fe1588d34100a76408a044bd71c6b https://github.com/CleverRaven/Cataclysm-DDA/commit/4c1e7f35c4151d82caa4224f39f4de8995466b56 https://github.com/CleverRaven/Cataclysm-DDA/commit/063f797bf7b0c0074e872777012f3b798fe8b6cb https://github.com/CleverRaven/Cataclysm-DDA/commit/cc3b7172682e9e0342177365f7a8df237f1b3851

### PR DESCRIPTION
**Pull request by NotFuji**
closes #23454

While it does work, it's probably worth investigating why certain unarmed attacks don't count as unarmed, while some do.

### CODE REVIEW

File: src/melee.cpp [hunk 1]
```diff
@@ -273,7 +273,7 @@ static void melee_train( player &p, int lo, int hi, const item &weap ) {
     p.practice( skill_stabbing, ceil( stab / total * rng( lo, hi ) ), hi );
 
     // Unarmed skill scaled bashing damage and so scales with bashing damage
-    p.practice( weap.has_flag( "UNARMED_WEAPON" ) ? skill_unarmed : skill_bashing,
+    p.practice( ( weap.is_null() || weap.has_flag( "UNARMED_WEAPON" ) ) ? skill_unarmed : skill_bashing,
```
Comment (Night-Pryanik) [inline src/melee.cpp]: There's already an `unarmed_attack` function for that.
