### PR TITLE
Fix android build

### LINKED ISSUE #66927: Android builds failing to generate (again)
### Describe the bug

Android builds failing to generate, since [Cataclysm-DDA experimental build 2023-07-15-0601](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2023-07-15-0601)

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

To have android builds.

### Screenshots

_No response_

### Versions and configuration

Current master.

### Additional context

I'm currently unable to build locally to test, but here's a possible fix:

```diff
diff --git a/src/sdltiles.cpp b/src/sdltiles.cpp
index 04cdfc919b..7e3c9d97aa 100644
--- a/src/sdltiles.cpp
+++ b/src/sdltiles.cpp
@@ -2814,22 +2814,21 @@ static void CheckMessages()
                         // Check if we're near a vehicle, if so, vehicle controls should be top.
                         {
                             const optional_vpart_position vp = here.veh_at( pos );
-                            vehicle *const veh = veh_pointer_or_null( vp );
-                            if( veh ) {
-                                if( veh->part_with_feature( vp->mount(), "CONTROLS", true ) >= 0 ) {
+                            if( vp ) {
+                                if( const std::optional<vpart_reference> controlpart = vp.part_with_feature( "CONTROLS", true ) ) {
                                     actions.insert( ACTION_CONTROL_VEHICLE );
                                 }
-                                const int openablepart = veh->part_with_feature( vp->mount(), "OPENABLE", true );
-                                if( openablepart >= 0 && veh->part( openablepart ).open && ( dx != 0 ||
+                                const std::optional<vpart_reference> openablepart = vp.part_with_feature( "OPENABLE", true );
+                                if( openablepart && openablepart->part().open && ( dx != 0 ||
                                         dy != 0 ) ) { // an open door adjacent to us
                                     actions.insert( ACTION_CLOSE );
                                 }
-                                const int curtainpart = veh->part_with_feature( vp->mount(), "CURTAIN", true );
-                                if( curtainpart >= 0 && veh->part( curtainpart ).open && ( dx != 0 || dy != 0 ) ) {
+                                const std::optional<vpart_reference> curtainpart = vp.part_with_feature( "CURTAIN", true );
+                                if( curtainpart && curtainpart->part().open && ( dx != 0 || dy != 0 ) ) {
                                     actions.insert( ACTION_CLOSE );
                                 }
-                                const int cargopart = veh->part_with_feature( vp->mount(), "CARGO", true );
-                                if( cargopart >= 0 && ( !veh->get_items( cargopart ).empty() ) ) {
+                                const std::optional<vpart_reference> cargopart = vp.cargo();
+                                if( cargopart && ( !cargopart->items().empty() ) ) {
                                     actions.insert( ACTION_PICKUP );
                                 }
                             }

```

### PR DESCRIPTION
**Pull request by WhiteCloud0123**
#### Summary
Bugfixes "Fix android build"

#### Purpose of change
Fix #66927  ( The bug in this issue has been fixed, and linking this issue is because its title is "Android builds failing to generate (again) " and it has been reopened. )

#### Describe the solution
The NDK‘s ’compiler seems to encounter difficulties in Deduction and Type conversion in this part. Here, we make the types correspond according to the previous error message to solve the puzzle of the NDK's compiler.

#### Testing
The Android version has been built locally and passed. I played for a while, aimed and fired several times, and the situation was normal.

### CODE REVIEW

**Comment by SurFlurer** [comment]
Fix #66927 .

File: src/character.cpp [hunk 1]
```diff
@@ -913,7 +913,7 @@ aim_mods_cache Character::gen_aim_mods_cache( const item &gun )const
 
 double Character::fastest_aiming_method_speed( const item &gun, double recoil,
         const Target_attributes target_attributes,
-        std::optional<std::reference_wrapper<const parallax_cache>> parallax_cache ) const
+        const std::optional<std::reference_wrapper<parallax_cache>> parallax_cache ) const
```
Comment (Qrox) [inline src/character.cpp:916]: This can simply be a pointer which is by definition an "optional reference"...

Comment (SurFlurer) [reply src/character.cpp:916]: I knew, but I want to make the code's meaning more explicit to those who reads the code so for now I often avoid using nullptr to indicate "no cache"...

Comment (WhiteCloud0123) [reply src/character.cpp:916]: An hour has passed and there is no further debate, so leave it as is. Close this discussion.
