### PR TITLE
Fix: ::practice causing complete focus drain

### LINKED ISSUE #50810: Learn from NPC tanks focus to 1.
### Describe the bug

Learning skills from NPC immediately sets focus to 1, even if the focus was 110 before, even if it's only taking 90seconds.

This renders NPC learning useless and is utterly unrealistic.

------Might be related------

Performing tasks no longer gradually reduces focus; instead, focus gains normally during task, then gets a full hit upon finishing. This made it possible to force-interrupt crafting type tasks right before the finish, effectively "restore" focus during the day, and save the final hit for after a good night's sleep. 

I dont believe that was the case before.

### Steps To Reproduce

1. Befriend a NPC. 
2. Sleep to get some perfect clarity in mind.
3. Ask NPC to teach you some skill, such as how to use a BandAid.
4. Watch your focus becomes 1 after the session.

### Expected behavior

Not drooling two minutes into a lecture, no matter how boring the lecture is. 

Even my algebraic geometry teacher cant manage that feat and need about 100x longer.

### Screenshots

Before

After

note the focus and time difference.

### Versions and configuration

- OS: WIn10
- Game Version: 0.F experimental - 34F8ED3 
- Graphics version: Tiless
- Ingame language: English
- Mods loaded: default (DDA, No NPC Needs, Bionic Professions)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MagratGarlick**
#### Summary
Bugfixes "Fix NPC training causing complete focus drain"

#### Purpose of change

Fixes #50810 . This should also fix other focus drain runaway issues when the amount provided to practice is large enough.

Original Bug:
```
    Befriend a NPC.
    Sleep to get some perfect clarity in mind, eg, 120 focus.
    Ask NPC to teach you some skill, such as how to use a BandAid.
    Watch your focus becomes 1 after the 90seconds session raising healthcare from 2/25% to 2/32%
```

#### Describe the solution

Caps the use of square function in focus drain calculation to 1000 (or 1 effective focus). Apply direct subtraction when that threshold is exceeded.

#### Describe alternatives you've considered

Instead of setting a threshold, introduce a more complex function to "smooth the curve". It will probably cause slowness on the function that can get triggered per tick on crafting tho, and the curve is already artificiality skewed on the 1% focus comparison so it's probably not worth the effort. 

#### Testing

- Befriend a NPC.
- Sleep to get some perfect clarity in mind, eg, 120 focus.
- Ask NPC to teach you some skill, such as how to use a BandAid.
- Watch your focus no longer becomes 1 but merely drops by 12 after raising healthcare from 2/25% to 2/32%.

#### Additional context

Core cause of issue: 

```
            // The purpose of having this squared is that it makes focus drain dramatically slower
            // as it approaches zero.
            focus_pool -= ( focus_drain * focus_drain ) / 1000;
```

The square function here, in addition to its original intended effect (makes drain slower when the number is less than 1000), also causes a runaway when the drain would be higher (affecting anything that would cost more than 1 effective focus).

Using the 120focus example. Training a skill by NPC calls `finish_training` which calls `practice(player, 100)`, ie, the `amount` is 100. 
`amount` got adjusted by `adjust_for_focus` and is now 100*120=12,000 (assuming no other modifiers such as INT, Savant etc in play).

Enter the focus drain calculation:
```
            // Base reduction on the larger of 1% of total, or practice amount.
            // The latter kicks in when long actions like crafting
            // apply many turns of gains at once.
            int focus_drain = std::max( focus_pool / 100, amount );
            // For large values of amount, amount^2 can exceed INT_MAX.
            // We're going to be draining all of the focus if it gets that large, so cap it at a safe value
            focus_drain = std::min( focus_drain, INTMAX_SQRT );
            // The purpose of having this squared is that it makes focus drain dramatically slower
            // as it approaches zero.
            focus_pool -= ( focus_drain * focus_drain ) / 1000;
```
Focus_pool is `120*1000=120000`. This makes focus_drain to be `max(1200, 12000)` = 12000. 
The drain, because of the square function, is now `12000*12000/1000` = 144,000, or 144 focus. 
Result: focus is completely drained.

Noteworthy fun with original code: say the effective focus is 50 instead of 120 then focus_drain would be `max(500,5000)=5000`, which results in `5000*5000/1000`=25,000 or 25 focus to be removed from pool, and leaving player with 25 focus - so _the higher your focus is, the worse off you'd be_. Similarly, but worse, when your focus pool is a constant value but you're under the effect of positive modifiers (such as int bonus, FAST_LEARNER etc): you will gain extra `amount`, but pay the sqaure cost of `amount` in terms of focus (eg. FAST_LEARNER will give you 15% extra xp, but cost you 33% extra focus).

After the threshold capping fix, the drain amount of 12000 would be used directly instead of going thru the square function, result in the more reasonable amount of 12 focus to be deducted from player.

This change retains the behavior of insignificant amount of practice, such as the one generated by crafting, would still get focus draining modified by the square function and slowing down the drain, but for any `amount` >= 10 sent to `practice`, the square would not be applied result in greater-than-intended draining of focus.

Sample: Before, 100 focus, learning from NPC, focus->1
Sample Before

Sample: After, 94 focus, learning from NPC, focus->85
Sample After

Sample: Crafting a quarterstaff. The submitted amount to ::practice is 1 and is thus unaffected by the change. (Starting with 85 focus, end up on 16 after crafting the staff)
Sample Craft

### CODE REVIEW

**Comment by MagratGarlick** [comment]
A little bit of pondering of why this was not spotted before: the comparison would be 10xFD (focus displayed) vs `amount`XFD, which means the max() function would always favor `amount` as long as its greater than 10. 

It should traditionally be very observable, however with https://github.com/CleverRaven/Cataclysm-DDA/pull/47186 in place the tick (`amount`) is reduced to single digit numbers, which masked the underlying issue. 

Specifically, the focus_test.cpp as shown in https://github.com/CleverRaven/Cataclysm-DDA/pull/47186/files#diff-62303516dafeccb10152ecd67546a91ba2e662bce36e502144e40cd8f25d1e4f is testing on `practice(player, 1)` steps, which is likely why the drain is not showing up.

**Comment by MagratGarlick** [comment]
I actually gave this a little bit more thought, and believes the disproportional drain is ultimately the result of the square function - which means while my current proposed solution is _one_ solution, its not necessary the _most desirable_ one. 

The problem here lies in using the comparison of 1% of focus pool vs amount as baseline; while 1% of focus pool is relatively stable on the "degree", amount is not (or at least does not appear to be documented so). 

Take code as-is for example: existence of SQRT means that so long as amount is the dominating factor of the two, a change of 10 fold in amount is going to result in 100x variance in focus drain but same xp gains.  
ie: (simplified, so think in terms of "unit", not actual "value")
if you have amount=10, then ::practice 10 times, you gain 100 XP, and you drain 10*10=100 units worth of focus pero call, totaling to 1000 units of focus
if you have amount=100, then ::practice just 1 time, you gain 100XP, and you drain 100*100=10000 units worth of focus - 10times larger than you'd otherwise pay

This means the ideal kind of activities would be those generating a tickling stream of practice, with "sweet spot" being the amount exactly equal to the focus pool number in comparison; going "down" below that number and you'll be paying by 1% of focus, which is not ideal but still acceptable (due to square function minimizing the drain), but going "over" that number, such as the NPC learning, is extremely punishing.

**Comment by eltank** [comment]
In order to pass the PR validation check, change this:
```
Category "Bugfixes"
```
to something like
```
Bugfixes "Fix NPC training causing complete focus drain"
```

**Comment by eltank** [comment]
In the testing section, could you mention how much focus you lost after the code change? You should also try training skills at different skill levels (you can use the debug menu to edit your player skills as well as the NPC skills to make this possible).

**Comment by MagratGarlick** [comment]
More than convinced I'm attacking this from the wrong angle now. 
Making amends - please withhold review (if anyone happens to be looking),

File: src/character.cpp [hunk 1]
```diff
@@ -2597,13 +2596,16 @@ void Character::practice( const skill_id &id, int amount, int cap, bool suppress
             // Base reduction on the larger of 1% of total, or practice amount.
             // The latter kicks in when long actions like crafting
             // apply many turns of gains at once.
-            int focus_drain = std::max( focus_pool / 100, amount );
-            // For large values of amount, amount^2 can exceed INT_MAX.
-            // We're going to be draining all of the focus if it gets that large, so cap it at a safe value
-            focus_drain = std::min( focus_drain, INTMAX_SQRT );
+            int focus_drain = std::max( focus_pool / 100, amount);
```
Comment (kevingranade) [inline src/character.cpp:2599]:
```suggestion
            int focus_drain = std::max( focus_pool / 100, amount );
```

File: src/character.cpp [hunk 2]
```diff
@@ -2597,13 +2596,16 @@ void Character::practice( const skill_id &id, int amount, int cap, bool suppress
...
+
             // The purpose of having this squared is that it makes focus drain dramatically slower
-            // as it approaches zero.
-            focus_pool -= ( focus_drain * focus_drain ) / 1000;
+            // as it approaches zero. As such, the square function would not be used if the drain is
+            // larger or equal to 1000 to avoid the runaway, and the original drain gets applied instead.
+            if( focus_drain >= 1000) {
```
Comment (kevingranade) [inline src/character.cpp:2604]:
```suggestion
            if( focus_drain >= 1000 ) {
```
