### PR TITLE
Experimental path name encoding conversions (fix #19994)

### LINKED ISSUE #19994: Cannot create maps with Chinese name
Using Win 10 64bit Tiled version, system language is Chinese.

After trying to create a map with any default map name(already translated in Chinese), the game prompts:
failed to write data into "./save/mapname(Chinese here)/gameoptions.json":opening file failed

### PR DESCRIPTION
**Pull request by BrettDong**
Fixes #19994 . On Simplified Chinese Windows, file and path names are encoded in GB18030, but CDDA is using UTF-8. The different character encodings was causing mojibake, and the player couldn't create a world with a Chinese name. And if I remember correctly, Traditional Chinese Windows (Big5), Japanese Windows (Shift_JIS) and Korean (EUC-KR) Windows are also using non-UTF8 encodings.

In this PR, I add an option "Experimental path name encoding conversion":
1. Convert from UTF-8 to native encoding to get the usable file path when saving the world.
2. Correctly convert UTF-16 wide char string (`wchar_t*`) to single character sequence(aka. multi byte string, `char*`) when traversing the file system. In the old code, `wcstombs_s` function can't make the successful conversion because it relies on the program locale and I guess it's modified by gettext thus unusable. Now I use `WideCharToMultiByte` Windows API to do the conversion. This function allows manually explicitly specify a code page for conversion.

Then it's working fine:

### CODE REVIEW

**Comment by BrettDong** [comment]
Now made this an option. Wish this would get merged sooner, then I'll be able to hear the feedbacks from users using different Windows versions and different languages.

File: src/cata_utility.cpp [hunk 1]
```diff
@@ -509,3 +509,47 @@ bool read_from_file_optional( const std::string &path, JsonDeserializer &reader
...
 }
+
+std::string native_to_utf8( const std::string &str )
+{
+    if( !get_options().has_option( "ENCODING_CONV" ) || !get_option<bool>( "ENCODING_CONV" ) ) {
+        return str;
+    }
+#if defined(_WIN32) || defined(WINDOWS)
+    // native encoded string --> Unicode sequence --> UTF-8 string
+    int unicode_size = MultiByteToWideChar( CP_ACP, 0, str.c_str(), -1, NULL, NULL ) + 1;
```
Comment (narc0tiq) [inline src/cata_utility.cpp]: Naturally, this compiled fine when the PR builder hit it (for speed reasons, it only builds lincurses), but none of the Windows compilers are actually happy with this:

```
src/cata_utility.cpp: In function 'std::string native_to_utf8(const string&)':
src/cata_utility.cpp:497:83: error: passing NULL to non-pointer argument 6 of 'int MultiByteToWideChar(UINT, DWORD, LPCCH, int, LPWSTR, int)' [-Werror=conversion-null]
     int unicode_size = MultiByteToWideChar( CP_ACP, 0, str.c_str(), -1, NULL, NULL ) + 1;
                                                                                   ^
src/cata_utility.cpp: In function 'std::string utf8_to_native(const string&)':
src/cata_utility.cpp:519:87: error: passing NULL to non-pointer argument 6 of 'int MultiByteToWideChar(UINT, DWORD, LPCCH, int, LPWSTR, int)' [-Werror=conversion-null]
     int unicode_size = MultiByteToWideChar( CP_UTF8, 0, str.c_str(), -1, NULL, NULL ) + 1;
                                                                                       ^
```

<http://ci.narc.ro/job/Cataclysm-Matrix/Graphics=Curses,Platform=Windows/6218/console>
