### PR TITLE
[Rdy] Bow/Quiver fixes

### LINKED ISSUE #17761: Cancelling shot with Bow stores arrow in inventory instead of Quiver
Arrows that are picked up are automatically stored in the Quiver so i guess the same should be done with an arrow that the player decides to not shoot.

### LINKED ISSUE #20761: Reloading held quivers from activation menu is very bugged.
Version: 4c8f943

When loading arrows into an empty quiver using the activation menu, the quiver will ignore the selection in favour of the last type reloaded by any quiver, as long as that arrow type in in the player's inventory.  If the player has a second quiver in their inventory, containing that arrow type, it will be taken from that quiver.

Reloading using the inventory menu or by wielding and reloading bypasses the issue.

### PR DESCRIPTION
**Pull request by OzoneH3**
Fixes #17761
Fixes #20761

* Fixes ammo selection when pressing ENTER twice, which defaulted to the first entry.
* Nocked arrow when not firing the bow will be put back into the quiver (Except if it's the last one, which will be stored in the inventory).
* Picked up arrows/bolts will be puck into a quiver containing the same ammo type. (Including Autopickup)
* Prevents unloading the contents of one quiver into another one (Which would in some circumstances result in dissapearing arrows).

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -596,6 +596,54 @@ std::vector<item_location> Character::nearby( const std::function<bool(const ite
     return res;
 }
 
+long int Character::i_add_to_container(const item &it)
```
Comment (Coolthulhu) [inline src/character.cpp]: Do you actually use any `Character` methods here? I only see `inv`, which can be easily passed from above.
`Character` class is very bloated already.

File: src/character.cpp [hunk 2]
```diff
@@ -596,6 +596,54 @@ std::vector<item_location> Character::nearby( const std::function<bool(const ite
...
+{
+    long int charges = it.charges;
+    
+    if( it.is_ammo() && (!it.has_flag( "TEMP_UNLOADING" ) || (it.has_flag( "TEMP_UNLOADING" ) && charges == 1) ) ) {
```
Comment (Coolthulhu) [inline src/character.cpp]: This whole `TEMP_UNLOADING` thing is confusing and needs a lot of comments.
What exactly is being checked in this line? Why exactly 1 charge?

File: src/character.cpp [hunk 3]
```diff
@@ -596,6 +596,54 @@ std::vector<item_location> Character::nearby( const std::function<bool(const ite
...
+        const itype_id item_type = it.typeId();
+        
+        auto add_to_container = [it](item &container) {
```
Comment (Coolthulhu) [inline src/character.cpp]: You sure this capture won't create a copy of the item instead of properly referencing it?

File: src/character.cpp [hunk 4]
```diff
@@ -596,6 +596,54 @@ std::vector<item_location> Character::nearby( const std::function<bool(const ite
...
+            if( container.contents.front().charges < container.ammo_capacity() ) {
+                const long int diff = container.ammo_capacity() - container.contents.front().charges;
+                add_msg( _( "You put the %s in your %s." ), it.tname().c_str(), container.tname().c_str() );
+                if( diff > it.charges ) {
+                    container.contents.front().charges += it.charges;
+                    return (long int) 0;
```
Comment (Coolthulhu) [inline src/character.cpp]: `return 0L`

File: src/character.cpp [hunk 5]
```diff
@@ -596,6 +596,54 @@ std::vector<item_location> Character::nearby( const std::function<bool(const ite
...
+                    return it.charges - diff;
+                }
+            }
+            return it.charges;
+        };
+        
+        for( auto &w : worn ) {
+            if( w.is_ammo_container() && item_type == w.contents.front().typeId() ) {
+                charges = add_to_container(w);
+                if( !charges ) {
```
Comment (Coolthulhu) [inline src/character.cpp]: Comparison with `0` is clearer.

**Comment by Coolthulhu** [comment]
That `TEMP_UNLOADING` is a massive hack that will almost certainly lead to far more problems than it fixes.

Sounds like what you want is an argument for item addition to exclude containers and use that when unloading items.

File: src/character.cpp (hunk 1 above)
Comment (OzoneH3) [inline src/character.cpp]: I could move it but where? It uses u.inv and u.worn.

Comment (Coolthulhu) [inline src/character.cpp]: Instead of using `u.inv` and `u.worn` explicitly, you could use `visitable<T>::visit_items`. Then it would be easy to also apply on drop on map/vehicle (those are also `visitable`, so that you could reload a stack of quivers in the trunk by dropping a stack of arrows on the trunk.

Using `visitable` would not change the preference to reload worn items first - for characters, it visits items in order: `weapon->worn->inv`.

Comment (Coolthulhu) [inline src/character.cpp]: As for location: it could be in `pickup.h/cpp` - it handles pickup, after all.

**Comment by OzoneH3** [comment]
Got rid of TEMP_UNLOADING and added function arguments instead.

File: src/character.cpp [hunk 6]
```diff
@@ -596,6 +596,54 @@ std::vector<item_location> Character::nearby( const std::function<bool(const ite
     return res;
 }
 
+long int Character::i_add_to_container(const item &it, const bool unloading)
+{
+    long int charges = it.charges;
+    
+    if( it.is_ammo() && !unloading ) {
```
Comment (Coolthulhu) [inline src/character.cpp]: You could save an indent by inverting this `if` into
```
if( !it.is_ammo() || unloading ) {
    return 0L;
}
```

File: src/character.cpp (hunk 1 above)
Comment (OzoneH3) [inline src/character.cpp]: Switched to visit_items. Won't let me use visit_items in Pickup namespace. Would have to change it to a class and inherit like in character.h?

```Character::Character() : Creature(), visitable<Character>()```

File: src/game.cpp [hunk 7]
```diff
@@ -10796,10 +10802,10 @@ bool game::unload( item &it )
                 return false; // no liquid was moved
             }
 
-        } else if( !add_or_drop_with_msg( u, ammo ) ) {
+        } else if( !add_or_drop_with_msg( u, ammo, qty > 1 ) ) {
             return false;
         }
-
+
```
Comment (Coolthulhu) [inline src/game.cpp]: Extra spaces
Double-newline lines should not have any spaces in them

File: src/character.cpp [hunk 8]
```diff
@@ -596,6 +596,41 @@ std::vector<item_location> Character::nearby( const std::function<bool(const ite
...
+    long int charges = it.charges;
+    
+    if( !it.is_ammo() || unloading ) {
+        return charges;
+    }
+    
+    const itype_id item_type = it.typeId();
+    
+    auto add_to_container = [&it, &charges](item &container) {
+        if( container.contents.front().charges < container.ammo_capacity() ) {
```
Comment (Coolthulhu) [inline src/character.cpp]: Would be clearer if you wrapped `container.contents.front()` in a reference.
Something like `contained_ammo` or something like that.

File: src/player.cpp [hunk 9]
```diff
@@ -7521,7 +7521,8 @@ item::reload_option player::select_ammo( const item &base, const std::vector<ite
 
             bool key( const input_event &event, int idx, uimenu * menu ) override {
                 auto cur_key = event.get_first_input();
-                if( default_to != -1 && cur_key == last_key ) {
+                //Prevent double RETURN (10) to default to the first entry
+                if( default_to != -1 && cur_key == last_key && cur_key != 10 ) {
```
Comment (BevapDin) [inline src/player.cpp]: Why the magic value 10 and not `'\n'`?

File: src/game.cpp [hunk 10]
```diff
@@ -10649,13 +10649,19 @@ void game::mend( int pos )
...
-bool add_or_drop_with_msg( player &u, item &it )
+bool add_or_drop_with_msg( player &u, item &it, const bool unloading = false )
 {
     if( it.made_of( LIQUID ) ) {
         g->consume_liquid( it, 1 );
         return it.charges <= 0;
     }
-    if( !u.can_pickVolume( it ) ) {
+
+    //Try to add ammo to container
```
Comment (BevapDin) [inline src/game.cpp]: Why this comment? Isn't this exactly what the called function does? Why do you think this needs a comment, especially as you have added the *same* comment to both function calls? If the function name does describe what it does, it should be changed.

File: src/character.h [hunk 11]
```diff
@@ -353,6 +353,7 @@ class Character : public Creature, public visitable<Character>
          */
         int get_item_position( const item *it ) const;
 
+        long int i_add_to_container(const item &it, const bool unloading);
```
Comment (BevapDin) [inline src/character.h]: Probably needs a comment saying *what* the returned value indicates. Is it the amount that was added or the remaining amount? What does `unloading` indicate?
