### PR TITLE
Fix NPC equip fail message

### LINKED ISSUE #23409: NPC follower can wear items incompatible with mutant anatomy.
I found this issue when helping deanec64 with a crash error. When equipping a suit to a spider mutant follower, his game would crash. I was unable to reproduce the crash but I did find this bug.

Game version:
cataclysmdda-0.C-7259

Operating system:
Win 10

Tiles or curses:
curses

Mods active:
none

### Expected behavior
Telling a follower to wear invalid clothing should give a "I can't wear that" message, preferably a "I can't wear that due to my spider limbs" message.

### Actual behavior
Clothing worn when a mutations develops is properly pushed off, however, asking them to wear a new invalid item succeeds. (As a side note, ponchos should fit mutant anatomy.) 

### Steps to reproduce the behavior
Spawn an NPC, get him to join you, mutate him with arachnid limbs, tell him to wear a suit.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix NPC equip due to mutation fail message"

#### Purpose of change
Fixes #23409
NPC refusing to equip items due to mutation had incorrect message.

#### Describe the solution
#23409 was already mostly fixed, the NPC would correctly refuse to equip an incompatible item but the message was wrong so I fixed the message.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -2153,7 +2153,9 @@ ret_val<bool> Character::can_wear( const item &it, bool with_equip_change ) cons
         for( const trait_id &mut : get_mutations() ) {
             const auto &branch = mut.obj();
             if( branch.conflicts_with_item( it ) ) {
-                return ret_val<bool>::make_failure( _( "Your %s mutation prevents you from wearing your %s." ),
+                return ret_val<bool>::make_failure( is_player() ?
+                                                    _( "Your %s mutation prevents you from wearing your %s." ), branch.name(), it.type_name() :
+                                                    _( "My %s mutation prevents me from wearing this %s." ), branch.name(), it.type_name(),
```
Comment (BevapDin) [inline src/character.cpp]: Have you tested this? Because I think the second operand of the ternary will evaluate to just the `type_name`. That second operand consists of some invocations of the comma operator, so it evaluates to the right operand of them.
```C++
is_player ? "...", name(), type_name() : ...
// Is parsed as
is_player ? ( "...", name(), type_name() ) : ...
// Which is the same as
is_player ?( type_name() ) : ...
```
I suggest writing it like this:
```C++
make_failure( is ? "text 1" : "text 2", additional, parameters, that, will, apply, to, both, strings )
```
