### PR TITLE
Fix various problems with aiming / target_ui

### LINKED ISSUE #39136: Problem with aiming at practice target
# Describe the bug

When I fire at practice target, the usual way [f] [p] to make the most precise shot is not working correctly. I need to press [p] several times.

# Steps To Reproduce

1. "Build" practice target.
2. Stand few tiles away.
3. Aim at it using [f] [p] and notice how you didn't shoot yet but only increased your aim slightly.

# Expected behavior

Firing after pressing [p] for the first time.

# Screenshots

After pressing [p] twice already:
obraz

# Versions and configuration

- OS: Windows
    - OS Version: 8.1
- Game Version: 0.D-13486-g5a52d64 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

I was using pistol crossbow, but probably it works so for other ranged weapons as well.

### LINKED ISSUE #42318: Endless Aiming
# Describe the bug
Character was stuck in auto-aim until frostbite set in, which took a long time.
I found myself in a state of aiming that was uninterruptible, mashed every button on my keyboard in a wild panic, see screenshot for the exact positioning of actors (various manhacks, their dispenser vehicles and the player character). It went as following:

# Steps To Reproduce

1. Stand in the doorway to a Barracks in a Lab, where there are 2 manhack spawning enemies.
2. Aim at a manhack that emerges from one of the two Northtrop manhack dispenser enemies (it was the riot control version in my case. though it still dispensed C4 and Grenade hacks, feel like that stuff doesn't belong in a non-or-less-lethal unit?) (the most precise aim option was used, I should mention).
3. When you are still aiming and a new manhack is spawned, ignore the prompt you are given to stop aiming.
4. Player character never reaches full steadiness, dispensers keep spawning manhacks until their limit is reached, process of aiming can't be interrupted by any means.

This happened to me in an ice lab (on the first level, so it wasn't too cold and my character had just entered the lab and was still comfortable (falling) when it happened), and my character aimed until he got a hurt prompt that was caused by frostbite, none of the manhacks, flashbang hacks, grenade hacks, C4 hacks, etc ever put a scratch on me. It might've been that the first few manhacks in front of me were retreating as manhacks do, but couldn't get far away to trigger their attack pattern because they were blocked in by the mountain of other manhacks.

# Expected behavior

Not sure, as this seems like a pretty convoluted bug, maybe add a time limit that the player character can spend automatically aiming, then give him a prompt that he's not making any progress in getting the target into his crosshairs or something like that. The steadiness meter went up and down like a wild rollercoaster, but never managed to reach the max, which was needed to fire.
Or just make the auto-aim interruptable with 5 like crafting and other activities. Normally you don't see this mode much since it takes less than a second (irl) to auto-aim and fire but I was stuck in that mode for about 60 irl seconds.

# Screenshots

Untitled

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4226-g1ea5556 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Bionic Slots [cbm_slots],
    Blaze Industries [blazeindustries]
]

# Additional context

My character got away by running about 20 tiles back to the exit at 34 speed, somehow none of the explosive manhacks triggered as I ran, not sure if this means anything since I don't know the exact behavior of manhacks apart from that hit-and-run strategy they employ. I very strongly feel like if any manhack had triggered I would've lost my character, and I also feel like they should've triggered, given the situation, they were kinda hugging me for many in-game minutes.

### LINKED ISSUE #45923: Can't fire weapons into tiles that I can't see directly
# Describe the bug
Currently if I press "fire" button while not aiming at any particular directly seen creature, the character aims instead by passing time and not actually shooting. I'm not sure if it's a bug or a feature, but often there are indirect ways when I know which direction I want to shoot: infravision, sound and electric receptors can all point to a creature and I want to be able to shoot it at, but I can't. 

# Steps To Reproduce

1. Go into a dark area
2. Get electroreceptors
3. Put a turret outside of night vision radius
4. Try shooting a rifle or a bow at its electrorecepted position

# Expected behavior

I expect to be able to shoot at any position regardless whether it's inside of my direct vision radius or outside of it.

# Screenshots

# Versions and configuration

Happens both in experimental and in stable.

# Additional context

### PR DESCRIPTION
**Pull request by olanti-p**
#### Summary
SUMMARY: Bugfixes "Fixed various problems with aiming"

#### Purpose of change
1. Fix #42318
This issue can be encountered when avatar tries to precisely aim at something while surrounded by many enemies. In that case, the loop happens roughly like this (someone on discord figured it out):
    * pc spends all moves on aiming, ends turn
    * enemies attack the pc
    * pc dodges
    * the dodge throws off the aim

    Target creature, when moves, also throws off the pc's aim - this can lead to another loop where pc tries to precisely aim a big, unwieldy gun at a small, fast target.
    
2. Fix #39136
3. Fix #45923
4. Stop target ui from revealing full info about creatures visible only in IR

#### Describe the solution
1. Abort aim-and-fire after 10 turns. I don't think anything else can be done here, since the exact conditions are hard to pinpoint.
2. Introduce separate variable that indicates whether pc is aiming at a creature or an empty tile, and rewrite initial target selection / existing target re-acquisition code based on that variable. As a bonus, the code is now actually readable.
3. Include `pc.sees_with_specials()` in list of ways to see the creature while aiming
4. Check how creature was detected before printing info

#### Testing
1. Surrounded myself with zombie dogs, tried to 'precise' fire at a zombie brute 15 tiles away. After approx. 10 seconds aiming stopped.
2. 'precise' firing (`f`->`p`) at practice targets now works. Also, the following things didn't break:
    * target selection priority when opening the ui (last targeted creature -> closest targetable creature -> closest archery target -> nothing)
    * aim-and-fire at a creature tracks the creature, does not break if there are creatures closer to pc
    * aim-and-fire at a creature interrupts if creature has died / is no longer visible
    * aim-and-fire at a tile does not break if there are creatures nearby
    * aim-and-fire at a tile interrupts if a creature moves into that tile
    * closing target ui without doing anything does not impact recoil / does not change last targeted creature
3. Gave myself electroreceptors, spawned a police bot, aim-and-fired at it. Aim cursor successfully tracks the robot, even if it's not visible.
4. Spawned a bunch of creatures, tried aiming at them.

#### Additional context
Maybe I should write target_ui tests one of these days...

### CODE REVIEW

File: src/ranged.cpp [hunk 1]
```diff
@@ -1382,12 +1386,24 @@ static int print_ranged_chance( const player &p, const catacurses::window &w, in
...
+    return char_sees( get_player_character(), cr );
+}
+
 // Handle capping aim level when the player cannot see the target tile or there is nothing to aim at.
 static double calculate_aim_cap( const player &p, const tripoint &target )
 {
     double min_recoil = 0.0;
     const Creature *victim = g->critter_at( target, true );
-    if( victim == nullptr || ( !p.sees( *victim ) && !p.sees_with_infrared( *victim ) ) ) {
+    if( victim == nullptr || !char_sees( p, *victim ) ) {
```
Comment (olanti-p) [inline src/ranged.cpp:1406]: Hmm. Actually, how precise are special senses?
I've changed this line assuming they're precise enough to make a difference while aiming, but on the other hand description in 'Look around' menu suggests they do not reveal much beyond general location. If that's the case, this part should be reverted
