### PR TITLE
Fixing position of morale and power on skinny sidebar

### LINKED ISSUE #27878: New UI: Power numbers are displayed in the incorrect place on the sidebar
**Describe the bug**  
In the screenshot below, the numeric value of the bionic power is placed directly to the left of the Power label, as opposed to the right where it presumably should be. Captured in an unmodded world on version 8473

**To Reproduce**  
1. Mutate "debug bionic power" through the debug menu
2. Activate to give bionic power
3. Observe where the numbers appear in the sidebar

**Screenshots**  
capture

### LINKED ISSUE #27927: Horizontal Morale meter cut off with narrow sidebar
**Describe the bug**  
Horizontal morale meter is one space too far over to the right, and is cut off when using the narrow sidebar.
**To Reproduce**  
1. Start a game
2. Make sure you're using the narrow sidebar
3. In Options, set "Morale Style" to "Horizontal" in the interface tab.

**Expected behavior**  
I can see all three characters in the morale meter
**Screenshots**  
image

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.C-37114-g7e78b20
 - Graphics version: Tiles
 - Mods loaded: N/A

### PR DESCRIPTION
**Pull request by MetroidHunter**
#### Summary
SUMMARY: Bugfixes "Fix alignment of power and morale on narrow sidebar"

#### Purpose of change
Fixes #27878 
Fixes #27927 
I recognize that #27878 is fixed in #27809 but that seems to have quite a debate going on around it. For now, I figured we can just align power where its meant to be and change when that issue is resolved.

#### Describe the solution
For the mood, on the narrow sidebar when horizontal, increase the offset from 2 to 3 to show the extra 3 characters.
For the power, use the getmaxx of the window and apply the already calculated offset for the digits to right justify.

#### Describe alternatives you've considered
I considered leaving power alone but we might as well fix it.

Showing fixed morale and power issue
power
Showing fixed power issues < 1k
power2
Showing fixed power issue > 1k
power3

### CODE REVIEW

File: src/sidebar.cpp [hunk 1]
```diff
@@ -458,9 +458,18 @@ void player::disp_status( const catacurses::window &w, const catacurses::window
     }
 
     // display mood smiley
-    mvwprintz( w, sideStyle ? 6 : 3, sideStyle ? getmaxx( w ) - 2 : 0, col_morale,
-               morale_emotion( morale_cur, fc,
-                               get_option<std::string>( "MORALE_STYLE" ) == "horizontal" ) );
+    bool mood_style_hor = get_option<std::string>( "MORALE_STYLE" ) == "horizontal";
```
Comment (Night-Pryanik) [inline src/sidebar.cpp]: Could be const.

**Comment by SirPendrak** [comment]
Why your int changed to 60?

File: src/sidebar.cpp (hunk 1 above)
Comment (nsklaus) [reply src/sidebar.cpp]: apologies, this one slipped me by unnoticed.
i use vertical smiley, and was busy on other PR.
i should check the issues tab more often. 
otoh, this is probably already fixed in the sidebar_info3 waiting for the merge.
but i would have provided interim fix in the same time as for the power value placement one.

**Comment by nsklaus** [comment]
apologies, this one slipped me by unnoticed.
i use vertical smiley, and was busy on other PR.
i should check the issues tab more often.
otoh, this is probably already fixed in the sidebar_info3 waiting for the merge.
but i would have provided interim fix in the same time as for the power value placement one.

File: src/sidebar.cpp (hunk 1 above)
Comment (MetroidHunter) [reply src/sidebar.cpp]: > apologies, this one slipped me by unnoticed.
> i use vertical smiley, and was busy on other PR.
> i should check the issues tab more often.
> otoh, this is probably already fixed in the sidebar_info3 waiting for the merge.
> but i would have provided interim fix in the same time as for the power value placement one.
Its np. I called out your fix in #27809 in the summary up top but figured it was good to go ahead and fix this before 0.D in case the discussion on your PR lasts a bit

**Comment by MetroidHunter** [comment]
> apologies, this one slipped me by unnoticed.
> i use vertical smiley, and was busy on other PR.
> i should check the issues tab more often.
> otoh, this is probably already fixed in the sidebar_info3 waiting for the merge.
> but i would have provided interim fix in the same time as for the power value placement one.

Its np. I called out your fix in #27809 in the summary up top but figured it was good to go ahead and fix this before 0.D in case the discussion on your PR lasts a bit

**Comment by nsklaus** [comment]
> > apologies, this one slipped me by unnoticed.
> > i use vertical smiley, and was busy on other PR.
> > i should check the issues tab more often.
> > otoh, this is probably already fixed in the sidebar_info3 waiting for the merge.
> > but i would have provided interim fix in the same time as for the power value placement one.
> 
> Its np. I called out your fix in #27809 in the summary up top but figured it was good to go ahead and fix this before 0.D in case the discussion on your PR lasts a bit

maybe it would be better that i clean my own problems. especially considering,
power value placement was fixed and merged in an interm PR #27907.
half of this PR is now trying to fix something that was already fixed.

i must admit the horizontal smiley went unnoticed to me though.

**Comment by MetroidHunter** [comment]
Thats true. Ive merged your change from #27907 which was already in master and applied the change on top of it. I believe this solution is still more effective since I am using the max x of the window instead of the 24 magic number

**Comment by nsklaus** [comment]
> Thats true. Ive merged your change from #27907 which was already in master and applied the change on top of it. I believe this solution is still more effective since I am using the max x of the window instead of the 24 magic number

why not .. while my sidebar_info3 is waiting, and i can't tell if it's going to be accepted or not, there's no harm in providing this. i must admit i don't like when error slip through me. i must recognize there's a need to fix the smiley offset too. if asked i'll gladly provide a fix for it, if this is chosen instead then thanks again for cleaning after me. i just wish i had seen this problem sooner.

**Comment by MetroidHunter** [comment]
These things happen all the time, dont feel bad about missing a detail here and there. Half the companies ive worked for have a team dedicated to fixing bugs like these so that development can keep rolling forward without having to switch gears for bugs. Were all in this together :)

**Comment by nsklaus** [comment]
> These things happen all the time, dont feel bad about missing a detail here and there. Half the companies ive worked for have a team dedicated to fixing bugs like these so that development can keep rolling forward without having to switch gears for bugs. Were all in this together :)

:)
