### PR TITLE
[WIP] NPC AI: Improve noise handling, retreating, and general QoL fixes

### LINKED ISSUE #29333: NPC activity control
NPCs need a couple of new features to deal with fleeing and investigating noises:
- [x]  For followers, distinguish between "guard and investigate noises" and "stay here for a bit."
- [ ]  Get rid of the follower attitude, which is only causing problems, and replace it with checking if an NPC is part of the player's faction.
- [x]  Add a "don't investigate here" zone so that you can tell NPCs to not investigate the shoggoth noises.
- [x]  Add a "investigation limits" zone so that NPCs don't wander too far off.
- [x]  Add a "retreat target" zone so that NPCs can have a sensible place to retreat.
- [ ]  Add the ability to define zones in mapgen so pre-gren NPCs can have a limit or retreat zone.
- [x]  Add an NPC AI rule to not open doors (so useful for exploring labs!)
- [x]  Add an NPC AI rule to not move through obstructed terrain/doorways that are adjacent to the player (teach NPCs to hold a chokepoint!)
- [x]  Add rule overrides, so that players can temporarily set several rules at once or unset them, but doesn't change the underlying behavior.
- [x]  Add a shout command "we're in a danger zone" that (via rule overrides) shuts NPCs up, prevents them from sleeping, makes them flee with the player, prevents them from opening doors, and prevents them from moving past chokepoints and a shout command "we're safe" that clears the overrides.
- [x]  Bugfix: shouts should work on NPCs the player can't see but that can hear the player, but not on NPCs the player can see but who can't hear the player.  Obviously.

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Features "NPC AI: Improve noise handling, retreating, and general QoL fixes"```

#### Purpose of change
Fixes #29333 
NPC AI has gotten some improvements recently, specifically the ability to investigate noises and run from danger.  Player influence of NPC AI has lagged, so add support to make NPCs somewhat differently suicidal.

#### Describe the solution
This is a tracker PR for a mess of smaller PRs.

#### Additional context
- [x] Add a rule to ignore noises in general.
- [x] Add a rule to not open doors.
- [x] Add a rule to not move past a chokepoint.
- [x] Add AI rule overrides
- [x] Use AI rule overrides to add a shout that sets several NPC AI rules at once relating to danger.
- [ ] Add a way to specify a zone in mapgen JSON.
- [ ] Add a way to tag zones by faction.
- [ ] Add an "investigate limits" zone and make NPCs who are in that zone not investigate noises outside of it.
- [ ] Add a "no investigate" zone and make NPCs ignore noises in that zone.
- [ ] Have shouts affect all NPCs in earshot instead of visible NPCs.

### CODE REVIEW

File: src/npc.cpp [hunk 1]
```diff
@@ -2428,6 +2429,20 @@ std::set<tripoint> npc::get_path_avoid() const
         // TODO: Cache this somewhere
         ret.insert( critter.pos() );
     }
+    if( rules.has_flag( ally_rule::avoid_doors ) ) {
+        for( const tripoint &p : g->m.points_in_radius( pos(), 30 ) ) {
```
Comment (Night-Pryanik) [inline src/npc.cpp]: NPC will check a 30-tiles radius area every turn? Isn't it super-heavy strain on performance?

Comment (mlangsdorf) [reply src/npc.cpp]: Doesn't seem to be but my development rig is really beefy.  I suspect the fact that it trims the available options for pathfinding makes up for it.
