### PR TITLE
EMP effect changed to tripoints to support z

### LINKED ISSUE #43032: EMP blasts don't care about Z-levels
# Describe the bug

I'm in science lab tower, at z-level 6. There's incandescent hulk on ground floor. Each time I go over its location I get hit by EMP blast.

# Steps To Reproduce

Well, I guess, spawn high enough building, spawn incandescent hulk on ground level, go to the top level, move around where it is on the ground, see bionic energy drained.

# Expected behavior

As their fields are about 4-5 tiles wide, and I recall Kevin just recently [saying](https://discourse.cataclysmdda.org/t/make-creatures-with-the-leap-ability-able-to-jump-up-one-z-level/24404/4) z-distances are about x5 "regular" distances, it probably should only reach to adjacent z-levels, at the very most +2. Not 5 levels up (I guess it just doesn't check z coordinate).

# Versions and configuration

- OS: Windows 7
- Game Version: 0.E-5059-g10b2315 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

### PR DESCRIPTION
**Pull request by kaffo**
#### Summary

SUMMARY: Bugfixes "Adds z-support to EMP explosions"

#### Purpose of change

Fixes #43032

#### Describe the solution

Legacy EMP code used a point co-ord to check where the effect took place, and never bothered to check Z. I've changed this to use tripoint.

#### Describe alternatives you've considered

Use the 2D Point struct and compare z levels manually.

#### Testing

1. Start with any bionic profession with storage to make sure you get the "your power has been drained" message
2. Enable experimental 3D view in Debug options
3. Debug spawn 5 EMP grenades
4. Climb up a Z-level (roof-top up a drain pipe) and stand on a ledge above an open door
5. Pull the pin and chuck it 1 tile off the ledge so it lands outside the door
6. Wait 3 turns for the grenade to explode, the effect should carry into the space directly below you
7. Ensure you don't get the "your power has been drained" message 

#### Additional context

N/A

### CODE REVIEW

File: src/explosion.cpp [hunk 1]
```diff
@@ -655,36 +655,34 @@ void scrambler_blast( const tripoint &p )
...
         if( rn > 80 ) {
             if( sight ) {
                 add_msg( _( "The nearby doors slide open!" ) );
             }
             for( int i = -3; i <= 3; i++ ) {
                 for( int j = -3; j <= 3; j++ ) {
-                    if( here.ter( p2 + point( i, j ) ) == t_door_metal_locked ) {
-                        here.ter_set( p2 + point( i, j ), t_floor );
+                    if( here.ter( p + tripoint( i, j, 0 ) ) == t_door_metal_locked ) {
+                        here.ter_set( p + tripoint( i, j, 0 ), t_floor );
```
Comment (jbytheway) [inline src/explosion.cpp:685]: For your future reference: you didn't need to change the type of the right-hand addend here; adding a `tripoint` to a `point` works fine.
