### PR TITLE
Fix crash from examning vehicles with minireactors

### LINKED ISSUE #40991: Segmentation fault on examining a few specific vehicles (Atomic SUV/Fire Engine/Survivor's Militarized RV)
# Describe the bug

When examining an Atomic SUV that I found, upon examining the vehicle which normally takes you to the vehicle customization screen, my game crashes with a Segmentation fault every time. Every other vehicle I've come across has enabled me to examine it just fine. I've experimented by debug spawning in a variety of vehicles - including Atomic SUV's, but they all work just fine. It's just the Atomic SUV that I came across that's giving me an issue. 

EDIT: It seems to be Atomic SUV's that I find naturally on the map are the issue. I found another one just teleporting around the map, and it gives me the same problem as the other Atomic SUV did. Spawned in Atomic SUV's are fine.

2nd EDIT: Creating a new world from scratch and finding/examining an Atomic SUV produces the same results.

3rd EDIT: The "Fire Engine" and "Survivor's militarized RV" vehicles are also giving me the same crash if I find them naturally. Spawning the vehicles in through debug menu enables me to examine them as normal.

# Steps To Reproduce

1. Find a naturally spawned Atomic SUV ingame. 
2. Press [e] on Atomic SUV
3. Press [e] again to examine the vehicle
4. Crash

# Expected behavior

Entering the vehicle customization menu. 

# Screenshots

image

# Versions and configuration

OS: Windows 10
Version: 0.E-2733-g6a45cf7
Graphics version: Tiles
Ingame language: English
Mods loaded: Aftershock, Dark Days Ahead, Disable NPC Needs, Secronom, Arcana and Magic Items, Blaze Industries, C.R.I.T Expansion Mod, Magiclysm, XEAS, No Freeze, DinoMod, Cataclysm++, More Survivor Stuff, My Sweet Cataclysm, Mythical Martial Arts, No Rail Stations, Graphical Overmap, Graphical Overmap Magiclysm, Mutation Changes, Tankmod: Revived. 
# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4708092/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4708095/debug.log)

### LINKED ISSUE #41063: Vehicle in the lab Segmentation error on examination
# Describe the bug

Found a vehicle in a lab. Tried examining it hoping to find a rare electric engine there. Got an error.

# Screenshots

https://i.imgur.com/km3Gitj.png

# Versions and configuration

I'm on 10725
Windows 10
Tiles

I have a bunch of mods loaded, but I think the only one that's not in repo is Cata++, which I doubt is a reason here.

# Additional context

I'm adding the crash log and the save right near the car in question.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4726675/crash.log)
[Earth2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4726676/Earth2.zip)

### PR DESCRIPTION
**Pull request by Nannaquin**
#### Summary
SUMMARY: Bugfixes "Fix crash upon examining vehicles containing minireactor"

#### Purpose of change
Fixes a segmentation fault crash caused by examining vehicles with installed minireactors, specifically naturally spawned vehicles (as opposed to debug menu spawned ones).

Fixes #40991, fixes #41063.

Original means of invoking the bug:
1. Find vehicle with minireactor (say, a bubble car in a lab from the aftershock mod).
2. e->e (Examine the vehicle, entering the examination menu)
3. Behold, the segmentation fault has arrived.

#### Describe the solution
This may be a consequence of the nested inventory system. There was an issue with vehicles being spawned by mapgen that caused said nuclear vehicles to be spawned with no contents, which would cascade into a seg fault when the code would try to find the ammo in the part to display. Pictures of my research available upon request (Around 20 screenshots).

What I did to fix this involved altering two lines of code. The first is in vehicle.cpp, where the whole map vehicle spawning issue occurs (not preloading the minireactor with plutonium charges).  I specifically changed a line within init_state(), the one immediately after the is_reactor() conditional, since putting through the "plut_cell" ammotype through ammo_set caused it to not actually set anything due to a mismatch in what the magazine of the reactor accepted ("plutonium"), thus making them the same fixed the problem.

Stemming from this is the issue of refilling the reactor, which without adjustments would just consume the cells without increasing the plutonium charges. This required a change in item::reload(), specifically the line 7742. calling ammo_capacity with the value being for "plut_cell" caused std::min to return 0, again being an issue of mismatching values. Changing the value to ammo_plutonium allowed the cells to be consumed properly (500 plutonium per cell) and added to the loaded fuel.

#### Describe alternatives you've considered

Allowing minireactor seg faults to persist.

#### Testing
Examined vehicle -> No crash.
re'f'illed the minireactor -> minireactor fuel increased.

More testing could probably be done but I'm not sure what more would be necessary.

#### Additional context

A week of detective work. Very proud to have a solution for this one.
There is a semi-related bug regarding fire engines (specifically their watercannons) which I had a PR for but seemed like a dirty quick fix. Gonna re-examine that.

### CODE REVIEW

**Comment by methanolium** [comment]
There is/was another kind of crash from minireactor car a week or so ago. Somehow I was able to examine one of them without crash, but game crashed on attempt to remove storage battery or on smashing the vehicle till storage battery was destroyed. After removing minireactor from car I could remove battery without crash. Sorry, cannot provide additional details.

**Comment by Nannaquin** [comment]
> There is/was another kind of crash from minireactor car a week or so ago. Somehow I was able to examine one of them without crash, but game crashed on attempt to remove storage battery or on smashing the vehicle till storage battery was destroyed. After removing minireactor from car I could remove battery without crash. Sorry, cannot provide additional details.

Its all good this detail is already great enough to provide two more tests. Although I must ask do you remember, vaguely (or specifically), what kind of car it was? I want to ensure I don't gloss over this particular case.

**Comment by methanolium** [comment]
> Its all good this detail is already great enough to provide two more tests. Although I must ask do you remember, vaguely (or specifically), what kind of car it was? I want to ensure I don't gloss over this particular case.

It was Atomic Car facing East and the minireactor was empty. Storage battery was || health, but I completely don't remember if it was charged or empty. Another detail is - I was able to remove other parts of the vehicle without crash.

Right now I tried to reproduce this bug (with latest build and creating world with just DDA and Aftershok). What was done - spawned Atomic Car using Debug menu and tried to remove battery, but there was no crash (No crash on examining and no crash on removing). Then I removed reactor, unloaded it and when I installed empty reactor back game crashed. So I'm unable to reproduce original bug.

File: src/item.cpp [hunk 1]
```diff
@@ -7739,7 +7739,7 @@ bool item::reload( player &u, item_location ammo, int qty )
 
             // any excess is wasted rather than overfilling the item
             item plut( *ammo );
-            plut.charges = std::min( qty * PLUTONIUM_CHARGES, ammo_capacity( ammotype( "plut_cell" ) ) );
+            plut.charges = std::min(qty * PLUTONIUM_CHARGES, ammo_capacity(ammo_plutonium) );
```
Comment (ZhilkinSerg) [inline src/item.cpp:7742]:
```suggestion
            plut.charges = std::min( qty * PLUTONIUM_CHARGES, ammo_capacity( ammo_plutonium ) );
```

File: src/vehicle.cpp [hunk 2]
```diff
@@ -508,7 +508,7 @@ void vehicle::init_state( int init_veh_fuel, int init_veh_status )
         }
 
         if( pt.is_reactor() ) {
-            const ammotype plut( "plut_cell" );
+            const ammotype plut("plutonium");
```
Comment (ZhilkinSerg) [inline src/vehicle.cpp:511]:
```suggestion
            const ammotype plut( "plutonium" );
```

**Comment by 3NC3PH4L0ND1V3** [comment]
Still get crashes when examining Atomic SUV's. Atomit cars work fine though.
Here is the crash log:
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4777141/crash.log)

**Comment by Nannaquin** [comment]
That does infact look like the same kind of crash, @3NC3PH4L0ND1V3 . Lemme ask, is this a new world made after this commit or one that existed before it? If the latter, this fix just makes sure the crash doesnt occur going forward (in other words, from vehicle spawning), so if theres an atomic vehicle from before this fix it probably still has the bugged fuel contents.

**Comment by methanolium** [comment]
@Nannaquin check this one https://github.com/CleverRaven/Cataclysm-DDA/issues/41321 it might be related. I've made it in brand new world 1-2 hours ago.

**Comment by 3NC3PH4L0ND1V3** [comment]
> 
> 
> That does infact look like the same kind of crash, @3NC3PH4L0ND1V3 . Lemme ask, is this a new world made after this commit or one that existed before it? If the latter, this fix just makes sure the crash doesnt occur going forward (in other words, from vehicle spawning), so if theres an atomic vehicle from before this fix it probably still has the bugged fuel contents.

I made a new world yesterday (after updating to build #10760)
