### PR TITLE
fix map radiation deserializatoin(fixes #44209)

### LINKED ISSUE #44209: Map radiation disappears due to broken deserialization
# Describe the bug

Map radiation disappears when a character revisits a tile with radiation 
after the tile has left character's reality bubble. Save/reload act the same

# Steps To Reproduce
1. Load a character or create a new one
2. Turn on radiation map
3. Create a crater(the 24x24 one) nearby using debug->edit map
4. Ensure that the crater tiles do have some radiation levels
5. Save & exit
6. Optionally locate and examine the .map file with our crater and ensure that "radiation" field of subtiles != [0, 144]
7. Reload the character
8. Notice that the radiation on the crater tiles has disappeared(except two 24 tiles high columns).
9. Optionally repeat save/reload and notice the crater became totally clean of mSv

# Expected behavior

Map radiation should persist or change according to the game logic

# Versions and configuration
 
Windows 10 x64 tiles vanilla

# Additional context

In effect this means that each time we revisit a radiation spot or save/reload while being on the spot
our survivors acts as if they possess a supernatural decontamination trait
This bug was introduced with https://github.com/CleverRaven/Cataclysm-DDA/pull/36903. Oddly enough it has not popped up for 9 months. Probably survivors are happy with the situation

### PR DESCRIPTION
**Pull request by behemotl**
#### Summary

SUMMARY: Bugfixes "fix map radiation deserialization"

#### Purpose of change

fix submap radiation deserialization  issue  #44209

#### Describe the solution

Fix presumably a copy/paste error  in `submap::load` accordingly

### CODE REVIEW

File: src/savegame_json.cpp [hunk 1]
```diff
@@ -3996,7 +3996,7 @@ void submap::load( JsonIn &jsin, const std::string &member_name, int version )
             int rad_num = jsin.get_int();
             for( int i = 0; i < rad_num; ++i ) {
                 if( rad_cell < SEEX * SEEY ) {
-                    set_radiation( { 0 % SEEX, rad_cell / SEEX }, rad_strength );
+                    set_radiation( { rad_cell % SEEX, rad_cell / SEEX }, rad_strength );
```
Comment (ZhilkinSerg) [inline src/savegame_json.cpp:3999]: I wonder why operators are different too.

Comment (AMurkin) [reply src/savegame_json.cpp:3999]: It should be 1D to 2D conversion.
