### PR TITLE
Don't wait for stamina recovery unless activity needs stamina.

### LINKED ISSUE #32171: Picking up from a fast-going or heavily damaged bicycle while tired results in an infinite loop
# Describe the bug

It waits until the stamina gets up to 33% but it never does since it's spent on moving the bicycle. The bicycle never stops and it's impossible to actively interrupt the routine as a result.

I think picking stuff up shouldn't wait for the stamina regeneration at all since it also creates awkward and dangerous situations during hit-and-run looting.

0.D-5241-g62d7d41397-dirty

### LINKED ISSUE #32443: Enemies teleporting during aiming
# Describe the bug
[Searingtown.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3399379/Searingtown.zip)
While playing I encountered a situation where enemies were seemingly teleporting into melee with me while I was aiming. 

# Steps To Reproduce

Besides this save file I have never seen the issue, I not do I know how to truly reproduce it.
To reproduce the behavior with the save:
1. Load the included save
2. Run away from enemies until a gap of 4-5 tiles is achived
3. Use '.' to aim a few times

***Edit, To reproduce this in a new game, run until low stamina and aim at an aggressed zombie.

# Expected behavior
Enemies should take incremental steps to approach, unless leaping occurs.

# Versions and configuration

Windows 10, vanilla version:Windows_x64-Tiles-9295

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
As reported by @derval, dropping an item while stamina is critically low would result in the player waiting until their stamina had recovered before completing the action, even though the activity did not drain stamina.
Fixes #32171 
Fixes #32443 

#### Describe the solution
Only check the stamina threshold after processing an activity that drains stamina.
When the threshold is breached, assign a "wait until stamina recovers" activity that will halt when the player's stamina rises above the threshold.

#### Describe alternatives you've considered
This might need to wait for a slightly higher threshold, because waiting just one turn at a time might be excessive in some

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -2855,20 +2855,26 @@ void activity_handlers::wait_npc_finish( player_activity *act, player *p )
 
 void activity_handlers::wait_stamina_do_turn( player_activity *act, player *p )
 {
-    if( p->stamina == p->get_stamina_max() ) {
+    int stamina_threshold = p->get_stamina_max();
+    if( !act->values.empty() ) {
+        stamina_threshold = values.front();
```
Comment (kevingranade) [inline src/activity_handlers.cpp]:
```suggestion
        stamina_threshold = act->values.front();
```

File: src/activity_handlers.cpp [hunk 2]
```diff
@@ -2855,20 +2855,26 @@ void activity_handlers::wait_npc_finish( player_activity *act, player *p )
...
         wait_stamina_finish( act, p );
     }
 }
 
 void activity_handlers::wait_stamina_finish( player_activity *act, player *p )
 {
-    // in case it takes longer then expected
-    if( p->stamina != p->get_stamina_max() ) {
+    if( !act->values.empty() ) {
+        if( p->stamina < values.front() ){
```
Comment (kevingranade) [inline src/activity_handlers.cpp]:
```suggestion
        if( p->stamina < act->values.front() ){
```

File: src/activity_handlers.cpp [hunk 3]
```diff
@@ -2855,20 +2855,26 @@ void activity_handlers::wait_npc_finish( player_activity *act, player *p )
...
+            debugmsg( "Failed to wait until stamina threshold %d reached, only at %d. You may not be regaining stamina.",
+                      values.front(), p->stamina );
```
Comment (kevingranade) [inline src/activity_handlers.cpp]:
```suggestion
                      act->values.front(), p->stamina );
```

File: src/activity_handlers.cpp [hunk 4]
```diff
@@ -2855,20 +2855,26 @@ void activity_handlers::wait_npc_finish( player_activity *act, player *p )
...
+                      act->values.front(), p->stamina );
+        }
+    } else if( p->stamina < p->get_stamina_max() ) {
         p->add_msg_if_player( _( "You are bored of waiting, so you stop." ) );
-        act->set_to_null();
-        return;
-    }
-    p->add_msg_if_player( _( "You finish waiting and feel refreshed." ) );
+    } else {
+        p->add_msg_if_player( _( "You finish waiting and feel refreshed." ) );
```
Comment (kevingranade) [inline src/activity_handlers.cpp]:
```suggestion
        p->add_msg_if_player( _( "You finish waiting and feel refreshed." ) );
    }
```

File: src/player_activity.cpp [hunk 5]
```diff
@@ -80,10 +72,19 @@ void player_activity::do_turn( player &p )
...
     // This might finish the activity (set it to null)
     type->call_do_turn( this, &p );
 
+    // Activities should never excessively drain stamina.
+    if( previous_stamina < p.stamina && p.stamina < p.get_stamina_max() / 3 ) {
+        if( one_in( 50 ) ) {
+            p.add_msg_if_player( _( "You pause for a moment to catch your breath." ) );
+        }
+        player_activity new_act( activity_id( "ACT_WAIT_STAMINA" ), to_moves<int>( 1_minute ), 0 );
+        u.assign_activity( new_act );
```
Comment (kevingranade) [inline src/player_activity.cpp]:
```suggestion
        p.assign_activity( new_act );
```

File: src/player_activity.cpp [hunk 6]
```diff
@@ -80,10 +72,19 @@ void player_activity::do_turn( player &p )
...
+    int previous_stamina = p.stamina;
     // This might finish the activity (set it to null)
     type->call_do_turn( this, &p );
 
+    // Activities should never excessively drain stamina.
+    if( previous_stamina < p.stamina && p.stamina < p.get_stamina_max() / 3 ) {
+        if( one_in( 50 ) ) {
+            p.add_msg_if_player( _( "You pause for a moment to catch your breath." ) );
+        }
+        player_activity new_act( activity_id( "ACT_WAIT_STAMINA" ), to_moves<int>( 1_minute ), 0 );
```
Comment (kevingranade) [inline src/player_activity.cpp]:
```suggestion
        player_activity new_act( activity_id( "ACT_WAIT_STAMINA" ), to_moves<int>( 1_minutes ), 0 );
```

File: src/activity_handlers.cpp [hunk 7]
```diff
@@ -2855,20 +2855,27 @@ void activity_handlers::wait_npc_finish( player_activity *act, player *p )
...
         wait_stamina_finish( act, p );
     }
 }
 
 void activity_handlers::wait_stamina_finish( player_activity *act, player *p )
 {
-    // in case it takes longer then expected
-    if( p->stamina != p->get_stamina_max() ) {
+    if( !act->values.empty() ) {
+        if( p->stamina < act->values.front() ){
```
Comment (kevingranade) [inline src/activity_handlers.cpp]:
```suggestion
        if( p->stamina < act->values.front() ) {
```

File: src/player_activity.cpp [hunk 8]
```diff
@@ -80,10 +72,19 @@ void player_activity::do_turn( player &p )
             moves_left = 0;
         }
     }
-
+    int previous_stamina = p.stamina;
     // This might finish the activity (set it to null)
     type->call_do_turn( this, &p );
 
+    // Activities should never excessively drain stamina.
+    if( previous_stamina < p.stamina && p.stamina < p.get_stamina_max() / 3 ) {
```
Comment (kevingranade) [inline src/player_activity.cpp]:
```suggestion
    if( p.stamina < previous_stamina && p.stamina < p.get_stamina_max() / 3 ) {
```

File: src/player_activity.cpp [hunk 9]
```diff
@@ -80,10 +72,19 @@ void player_activity::do_turn( player &p )
...
+        if( one_in( 50 ) ) {
+            p.add_msg_if_player( _( "You pause for a moment to catch your breath." ) );
+        }
+        player_activity new_act( activity_id( "ACT_WAIT_STAMINA" ), to_moves<int>( 1_minutes ), 0 );
```
Comment (kevingranade) [inline src/player_activity.cpp]:
```suggestion
        player_activity new_act( activity_id( "ACT_WAIT_STAMINA" ), to_moves<int>( 1_minutes ),
                                 p.get_stamina_max() / 3 );
```

**Comment by kevingranade** [comment]
Sorted out the issues, wait activity now reliably triggers, waits until stamina recovery occues, then returns to the previous activity.
