### PR TITLE
Fix a crash when npc tries to heal horse-mounted player

### LINKED ISSUE #40001: Game crashes upon returning to my base
# Describe the bug

The game crashes as i auto-walk back into my base, i have no real idea of what it causes it but i suspect something to do with npc's, since i had 3 of them there reading books by themselves. I play with the third party mod named Arcana so this may or may not be something to do with that mod.

# Steps To Reproduce

1-Open Map, directly below of the location of the player its the evac shelter with a note called "My base"
2-Autowalk (or just walk normally) straight south to said evac shelter

# Expected behavior

"i expected the game to not crash"?
i dont understand what this part means, sorry

# Versions and configuration

    -- OS: Windows 8.1 (pretty pirated and cracked, not updated either)
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E [32-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    DinoMod [DinoMod]

# Additional context
I tried updating to the last experimental version 0.E Tiles-10590 and also the lastest build of the arcana mod but the game still crashes regardless. 
I put the save folder and the crash.log and debug.log all in the same .zip
I took this files from the original 0.E folder, but it still does exactly the same on the experimental version
I had the game in spanish btw.

[save folder + crash and debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4548866/save.folder.%2B.crash.and.debug.zip)

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
SUMMARY: Bugfixes "Fix a crash when npc tries to heal horse-mounted player."

#### Purpose of change
Fixes #40001.

`game::shared_from` assumed that the player cannot be at the same location as a monster, which no longer holds now that mounting creatures is possible. If the player is mounted on a creature `g->shared_from( g->u )` returns the mounted creature, so `patient` in `npc::execute_action` becomes nullptr after dynamic casting it to `player`.

#### Describe the solution
In `npc_execute_action`, check `patient` is not null before dereferencing it.

In `game::shared_from`, check `critter` is a monster/npc before searching for its shared pointer, and only return the shared pointer if it refers to the same object as `critter`.

#### Testing
Loaded the save from #40001 and it no longer crashed. NPCs now also heal the player when they are mounted.

#### Additional context
Should probably be backported to 0.E.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -4710,13 +4710,15 @@ template const Creature *game::critter_at<Creature>( const tripoint &, bool ) co
...
-    }
     if( static_cast<const Creature *>( &critter ) == static_cast<const Creature *>( &u ) ) {
         // u is not stored in a shared_ptr, but it won't go out of scope anyway
         return std::dynamic_pointer_cast<T>( u_shared_ptr );
     }
+    for( auto &cur_mon : critter_tracker->get_monsters_list() ) {
+        if( static_cast<const Creature *>( cur_mon.get() ) == static_cast<const Creature *>( &critter ) ) {
+            return std::dynamic_pointer_cast<T>( cur_mon );
+        }
+    }
```
Comment (jbytheway) [inline src/game.cpp:4721]: I don't think this is a good solution; it makes this function O(n) in the number of monsters, which could have a bad performance impact.

I think it would also work to instead replace the initial `if` block with:
```
    if( const shared_ptr_fast<monster> mon_ptr = critter_tracker->find( critter.pos() ) ) {
        if( shared_ptr<T> result = std::dynamic_pointer_cast<T>( mon_ptr ) ) {
            return result;
        }
    }
```
Then for this case (player riding monster) the cast would fail and the code would fall through to the next check and succeed in returning the player.
