### PR TITLE
Implement deferred color loading. Fix field coloring.

### LINKED ISSUE #21618: Error: Couldn't find color 0
### Expected behavior
No error appears. Tiles with blood splatter are colored with bright red.

### Actual behavior
Error regarding color 0 not being found appears: http://dump.bitcheese.net/files/mapoxet/color_0_bug.png
Also, tiles with blood splatter look completely black, and the items dropped on it are invisible.

### Steps to reproduce the behavior
Save file: http://dump.bitcheese.net/files/loxebig/save.7z
Drop an item (e.g. stethoscope) onto adjusent south tile of the south car door (3 tiles south from the character). Shift+v, select the dropped item, get the error.
Alternatively, leave the car and go east along the road until the next road crossing (there are 2 tiles with blood splatter). The error appears when these tiles come into view.

### Note
The error appears in commit 92a1d9e. If rolled back to 95fe85d, the save works fine. Since 92a1d9e has only 2 small fixes unrelated to colors, the bug must have been introduced in 3fcc06e.

### PR DESCRIPTION
**Pull request by BevapDin**
Should fix #21618 - the colors of fields had been assigned before the `color_manager` had loaded them from JSON. This PR adds a class that wraps the `color_id` (just an enum) and translates it when needed into the actual color. It changes `field_t` to store such a wrapped `color_id`, which should fix the bug.

### CODE REVIEW

File: src/color.h [hunk 1]
```diff
@@ -400,6 +400,25 @@ class color_manager : public JsonSerializer, public JsonDeserializer
...
 
+/**
+ * For color values that are created *before* the color definitions are loaded
+ * from JSON. One can't use the macros (e.g. c_white) directly as they query
+ * the color_manager, which may not be initialized. Instead one has to use
+ * the color_id (e.g. def_c_white) and translate the id to an actual color
+ * later. This is done by this class: it stores the id and translates it
+ * when needed to the color value.
+ */
+class deferred_color
```
Comment (codemime) [inline src/color.h]: I may be wrong, but looks like `def_` work out-of-the-box and this functor isn't really needed.

Comment (BevapDin) [inline src/color.h]: It's not working, I just tried it. The result is the same, only with different color ids - but still a debug message and all fields have the same white color in the editmap menu.

The base problem is that the macro `c_white` resolves to `get_all_colors().get(def_c_white)`, which calls `color_manager::get`. But the manager loads the color definitions *after* `main` has been entered, which is *after* the initialization of static objects. So it basically returns values from an uninitialized `std::array<> color_array`, which get stored in `fieldlist`.

Anyway, I tested this solution and it works fine. It even allows to change the color at runtime via the color manager (e.g. you can change `c_red` to mean blue in the color manager and all blood tiles will appear blue).

**Comment by pierredavidbelanger** [comment]
I just pulled this branch on my code (because I wanted to play and this issue is bugging me), indeed it fix #21618
