### PR TITLE
Fix remote vehicles teleporting when folding

### LINKED ISSUE #36963: Remote controller can teleport foldable vehicle
# Describe the bug
A vehicle controller can be used on a foldable remote vehicle to fold the vehicle. The folded vehicle item will then appear on the character's tile.

# Steps To Reproduce
1. Create a foldable remote control vehicle
2. Use a remote vehicle controller to fold the vehicle

# Expected behavior
Vehicles can't teleport.

# Versions and configuration
- OS: Linux
    - OS Version: Kernel 5.4.7-arch1-1
- Game Version: 0.D-11179-gf050457446-dirty [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by saurocyte**
#### Summary

```SUMMARY: Bugfixes "no more teleporting vehicles"```
#### Purpose of change

Fixes #36963

### CODE REVIEW

File: src/vehicle_use.cpp [hunk 1]
```diff
@@ -828,7 +828,7 @@ bool vehicle::fold_up()
         bicycle.set_var( "description", string_format( _( "A folded %s." ), name ) );
     }
 
-    g->m.add_item_or_charges( g->u.pos(), bicycle );
+    g->m.add_item_or_charges( global_part_pos3(0), bicycle );
```
Comment (ZhilkinSerg) [inline src/vehicle_use.cpp]:
```suggestion
    g->m.add_item_or_charges( global_part_pos3( 0 ), bicycle );
```

Comment (ZhilkinSerg) [reply src/vehicle_use.cpp]: You did not apply suggested changes.

Comment (kevingranade) [inline src/vehicle_use.cpp]:
```suggestion
    g->m.add_item_or_charges( global_part_pos3( 0 ), bicycle );
```
