### PR TITLE
Apply fixed price malus to filthy clothing

### LINKED ISSUE #49469: Discussion: Trading value of filthy clothing?
I'm back at poking around the trading code again, and it's bothering me that filthy items seem to have the same value as non-filthy items. Especially since filthy items have lots of disadvantages (infection risk, can't be used for crafting, unsightly colour in inventory, etc). I feel that merchants and survivors should refuse or pay considerably less for filthy things.

I've been poking around the trading and item price code, and would like to fix this, but I see a few options available, such as:

1. Disallow filthy trading entirely.
1. Make filthy items worth a percentage less than clean items. (Eg: half-price)
2. Reduce the value of filthy items by a set amount, representing the labour and materials needed to clean them.
3. Something more complex (based on NPC flags, etc)

Of all of these, I like reducing the value by a set amount, as it means:

- Cheap, common items lose most or all of their value. Merchants don't want your stack of twenty torn and filthy t-shirts
- Valuable items are still valuable. Good armour is worth it, even if it needs a wash.
- Minimal code changes (100% confined to `item::price()`).

With a set price reduction of `-100` for filthy items, for example:

- Common clothes (including hoodies) become worthless
- Midline clothes (eg: leather vests) are about half-price
- Valuable clothes and above (good boots, real armour, etc) retain most of their value

Thoughts and feedback?

**tl;dr: I'd like to add a fixed price malus to filthy items in trade**

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

Balance "Filthy items now have a fixed price malus. Common filthy items no longer have value unless washed first."

#### Purpose of change

As per #49469, traders would accept mountains of filthy underwear in trade, but I can't imagine anyone valuing a pair of filthy boxers from a zombie corpse.

#### Describe the solution

Filthy items now have a fixed price malus ($1) rather than being reduced by a percentage.

This means that common clothing has no value unless washed, but valuable items will retain most of their value, even if filthy.

Includes a tip for the title screen.

#### Describe alternatives you've considered

Not doing this.

#### Testing

Loaded an existing game with and without the changes applied. Went through a pile of assorted filth, and verified that common filthy clothing is worth nothing in trade, but things like military backpacks and leather belts still have value, albeit less than if they were clean.

#### Additional context

Closes #49469

### CODE REVIEW

**Comment by pjf** [comment]
Test failure appears unrelated.

Also C++ isn't my native language, so I'm not sure what best practice is for constants these days.

File: src/item.cpp [hunk 1]
```diff
@@ -6597,10 +6600,6 @@ int item::price_no_contents( bool practical ) const
         price -= price * static_cast< double >( damage_level() ) / 5;
     }
 
-    if( is_filthy() ) {
-        price *= 0.8;
```
Comment (anothersimulacrum) [inline src/item.cpp:6601]: You can keep both, but with what sensible prices are for most items, it probably doesn't make a difference.

Comment (pjf) [reply src/item.cpp:6601]: We can keep both, but I feel having only the fixed malus better reflects that a valuable item is still very valuable while filthy.

It also makes it easier to calculate prices for the test cases I didn't write. :)

**Comment by I-am-Erk** [comment]
Hmm, I was going to argue in favour of keepign the proportional value but you've got a point, a bulletproof vest isn't worth much less just because it has zombie puke on it, but a pair of jeans are almost worthless. OK.
