### PR TITLE
Some activities not allowed when dark now, sorry.

### LINKED ISSUE #31190: Dissecting can be done in dark
# Describe the bug

Some activities, like dissecting a corpse or repairing a vehicle can be done in complete darkness. These things would require light as they are very delicate activities that can be easily messed up without seeing what you are doing.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Some activities not allowed when dark"```

#### Purpose of change
Fixes #31190 

#### Describe the solution
Addded checks for light level when starting butchery, vehicle work or construction.
Simple butchery, quartering and dismembering is still possible in the dark.
Siphoning or filling vehicle tanks is still possible.

#### Describe alternatives you've considered
Thought maybe that some constructions would be possible in the dark.
Thats subjective...
 could always open up some with a json entry for " dark_possible" or something in the future.

#### Additional context
The butchery menu does not have a bit where it says why the option is not available.
I don't know the best way to structure it so it does show the reason why that option isnot available.
So I just did a popup to say that some options may not be available.
Would welcome anyone saying to me how best to re-structure the butchery menu to allow the description to show when the option is grayed out.

### CODE REVIEW

File: src/handle_action.cpp [hunk 1]
```diff
@@ -1962,6 +1963,8 @@ bool game::handle_action()
                     add_msg( m_info, _( "You can't construct while you're in your shell." ) );
                 } else if( u.has_effect( effect_riding ) ) {
                     add_msg( m_info, _( "You can't construct while you're riding." ) );
+                } else if( g->u.fine_detail_vision_mod() > 4 && !g->u.has_trait( trait_DEBUG_HS ) ) {
+                    add_msg( m_info, _( "It is too dark to construct right now" ) );
```
Comment (matskuman5) [inline src/handle_action.cpp]:
```suggestion
                    add_msg( m_info, _( "It is too dark to construct right now." ) );
```

**Comment by davidpwbrown** [comment]
jenkins rebuild

File: src/game.cpp [hunk 2]
```diff
@@ -7836,22 +7836,31 @@ static void butcher_submenu( map_stack &items, const std::vector<int> &corpses,
...
+        popup( _( "Some types of butchery are not possible when it is dark." ) );
+    }
     uilist smenu;
     smenu.desc_enabled = true;
     smenu.text = _( "Choose type of butchery:" );
+
     smenu.addentry_col( BUTCHER, true, 'B', _( "Quick butchery" ), cut_time( BUTCHER ),
                         _( "This technique is used when you are in a hurry, but still want to harvest something from the corpse.  Yields are lower as you don't try to be precise, but it's useful if you don't want to set up a workshop.  Prevents zombies from raising." ) );
-    smenu.addentry_col( BUTCHER_FULL, true, 'b', _( "Full butchery" ), cut_time( BUTCHER_FULL ),
+    smenu.addentry_col( BUTCHER_FULL, enough_light ? true : false, 'b', _( "Full butchery" ),
```
Comment (Night-Pryanik) [inline src/game.cpp]:
```suggestion
    smenu.addentry_col( BUTCHER_FULL, enough_light, 'b', _( "Full butchery" ),
```

Here and below.

File: src/game.cpp [hunk 3]
```diff
@@ -7836,22 +7836,31 @@ static void butcher_submenu( map_stack &items, const std::vector<int> &corpses,
         }
         return to_string_clipped( time_duration::from_turns( time_to_cut / 100 ) );
     };
+    bool enough_light = true;
+    if( g->u.fine_detail_vision_mod() > 4 ) {
+        enough_light = false;
+        popup( _( "Some types of butchery are not possible when it is dark." ) );
+    }
```
Comment (Night-Pryanik) [inline src/game.cpp]:
```
    const bool enough_light = g->u.fine_detail_vision_mod() > 4;
    if( !enough_light ) {
        popup( _( "Some types of butchery are not possible when it is dark." ) );
    }
```

Comment (Night-Pryanik) [inline src/game.cpp]:
```
    const bool enough_light = g->u.fine_detail_vision_mod() <= 4;
    if( !enough_light ) {
        popup( _( "Some types of butchery are not possible when it is dark." ) );
    }
```

**Comment by davidpwbrown** [comment]
jenkins rebuild

**Comment by kevingranade** [comment]
I'm super skeptical of quartering or simple butchery in the dark.  Both of these require a lot of detail work around bones and such, while trying to not cut yourself open with a knife.

**Comment by davidpwbrown** [comment]
> I'm super skeptical of quartering or simple butchery in the dark. Both of these require a lot of detail work around bones and such, while trying to not cut yourself open with a knife.

I think I was scared of the potential salt, and backed halfway out.
Perhaps a survival skill check allows people to quarter/do some simple butchery with their eyes closed/in the dark?
