### PR TITLE
Search the overmap around the cursor.

### LINKED ISSUE #21686: Map searches should search more than just the current overmap
### Expected Behavior
Searching on the map will search across all revealed tiles.

### Actual behavior
Searches are seemingly only run across tiles on the overmap the cursor is on. It may be even less than the current overmap - not positive. This was noticed in #19997.

### Steps to reproduce the behavior
This can be easily reproduced by locating the refugee center found on the computer at the beginning of the Evacuee start.

screen recording 2017-08-20 at 02 29 pm

### PR DESCRIPTION
**Pull request by OzoneH3**
Closes #21686

* Search the size of one overmap around the cursor.
* Sort by nearest first.
* Display distance and direction.
* Display number of matches.

### CODE REVIEW

File: src/overmap.cpp [hunk 1]
```diff
@@ -2643,15 +2643,45 @@ tripoint overmap::draw_overmap(const tripoint &orig, const draw_data_t &data)
...
+                    }
+                }
+            }
+
             if( locations.empty() ) {
                 continue;
             }
+
+            std::sort( locations.begin(), locations.end(), [&](const point &lhs, const point &rhs) {
+                return square_dist( curs, tripoint( lhs, curs.z ) ) < square_dist( curs, tripoint( rhs, curs.z ) );
```
Comment (codemime) [inline src/overmap.cpp]: Why `square_dist()` instead of `rl_dist()` which chooses between `square_dist()` and `trig_dist()`?

File: src/overmap.cpp [hunk 2]
```diff
@@ -2643,15 +2643,45 @@ tripoint overmap::draw_overmap(const tripoint &orig, const draw_data_t &data)
...
             std::transform( term.begin(), term.end(), term.begin(), tolower );
 
-            // This is on purpose only the current overmap, otherwise
-            // it would contain way to many entries
-            overmap &om = overmap_buffer.get_om_global(point(curs.x, curs.y));
-            std::vector<point> locations = om.find_notes(curs.z, term);
-            std::vector<point> terlist = om.find_terrain(term, curs.z);
-            locations.insert( locations.end(), terlist.begin(), terlist.end() );
+            std::vector<point> locations;
+            std::list<point> overmap_checked;
```
Comment (codemime) [inline src/overmap.cpp]: You probably want `std::set<point>` here (or even `std::vector<point>` which is more verbose, but extremely cheap).

File: src/overmap.cpp [hunk 3]
```diff
@@ -2668,13 +2698,19 @@ tripoint overmap::draw_overmap(const tripoint &orig, const draw_data_t &data)
                 tmp.y = locations[i].y;
                 draw(g->w_overmap, g->w_omlegend, tmp, orig, uistate.overmap_show_overlays, show_explored, NULL, draw_data_t());
                 //Draw search box
-                draw_border(w_search);
-                mvwprintz(w_search, 1, 1, c_red, _("Find place:"));
+                mvwprintz(w_search, 1, 1, c_red, _("Find place: %*d/%d"), 6, i+1, locations.size());
```
Comment (Leland) [inline src/overmap.cpp]: Might recommend changing this to "Search results" now that there's a number sitting next to the string

screen shot 2017-08-29 at 1 16 01 pm
