### PR TITLE
Jsonize crafting skill penalty from mutations

### LINKED ISSUE #36439: Paws mutation makes low-level crafting impossible.
# Describe the bug

The paws mutation, which among other things applies a what appears to be a flat skill penalty to crafting, makes crafting items requiring 1 tailoring, electronics or mechanics fail seemingly every time when your relevant skills are at 1, even with very high intelligence. This makes levelling those skills without a book extremely difficult, as you gain no XP for the failed crafts, but still waste materials.

# Steps To Reproduce

1. Give yourself the paws mutation.
2. Give yourself tailoring 1.
3. Give yourself a full set of tailoring tools and materials.
4. Observe as every attempted level 1 craft fails perpetually.

# Expected behavior

Per it's description, Paws should moderately impact your success when crafting, but it should use a multiplier or some other scaling penalty rather than a flat skill reduction, so that a character can eventually grow to overcome the penalty naturally rather than being stonewalled by it if they are not already skilled. Causing you to fail more often is fine, but causing you fail EVERY time is not.

# Screenshots
image
image

Note the lack of any progress toward the next level of tailoring.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-10673-ga5cd648 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Infrastructure "Jsonize crafting skill penalty from mutations"```

#### Purpose of change
Jsonize crafting skill penalty from mutations
Halve penalty from Paws, and Broad Paws to fix #36439 

#### Testing
Start game without error
Debug paw mutation
Get supply for level 1 tailor craft
Try crafting
Immedialty fail
Halve penalty
Try again
Mess up craft several times
Eventually succeed to craft the gloves and get 33% toward the next tailoring level

### CODE REVIEW

File: src/mutation_data.cpp [hunk 1]
```diff
@@ -411,6 +411,16 @@ void mutation_branch::load( const JsonObject &jo, const std::string & )
...
     }
 
+    for( JsonArray ja : jo.get_array( "craft_skill_bonus" ) ) {
+        const skill_id skid( ja.next_string() );
+        if( skid.is_valid() ) {
+            craft_skill_bonus.emplace( skid, ja.next_int() );
+        } else {
+            jo.throw_error( "invalid skill_id" );
+        }
+
```
Comment (Night-Pryanik) [inline src/mutation_data.cpp]:
```suggestion
```

File: src/mutation_data.cpp [hunk 2]
```diff
@@ -411,6 +411,15 @@ void mutation_branch::load( const JsonObject &jo, const std::string & )
         spells_learned.emplace( sp, ja.next_int() );
     }
 
+    for( JsonArray ja : jo.get_array( "craft_skill_bonus" ) ) {
+        const skill_id skid( ja.next_string() );
+        if( skid.is_valid() ) {
```
Comment (BevapDin) [inline src/mutation_data.cpp]: What if the skill definition is loaded *after* the mutation is loaded? This will report that skill id as invalid. Id checking should be done after everything has been loaded.

File: src/crafting.cpp [hunk 3]
```diff
@@ -923,17 +922,12 @@ double player::crafting_success_roll( const recipe &making ) const
...
-        if( has_trait( trait_PAWS_LARGE ) ) {
-            paws_rank_penalty += 1;
-        }
-        if( making.skill_used == skill_id( "electronics" )
-            || making.skill_used == skill_id( "tailor" )
-            || making.skill_used == skill_id( "mechanics" ) ) {
-            paws_rank_penalty += 1;
+    for( const std::pair< trait_id, trait_data > &mut : my_mutations ) {
+        for( const std::pair<skill_id, int> &skib : mut.first->craft_skill_bonus ) {
+            if( making.skill_used == skib.first ) {
```
Comment (BevapDin) [inline src/crafting.cpp]: `craft_skill_bonus` is a `std::map`. You can lookup keys in a map, there is a function for that. You do not need to iterate over all entries of the map.

**Comment by Fris0uman** [comment]
Right, I can't work on it right now, but I'll fix it next tuesday if no one else has done it by then.
