### PR TITLE
Limit time taken for NPCs to train new spells

### LINKED ISSUE #36090: Training Spells from NPCs
# Describe the bug
Once completing a mission for a spellcasting npc, attempting to gain training in a spell that is unknown to the player produces an infinite loop of training.

# Steps To Reproduce

1. Find and complete mission for spellcasting NPC from magiclysm.
2. Ask for training in a spell unknown to the player.
3. Enter infinite training loop.

# Expected behavior
Theoretically, asking for training in a spell unknown to the player should teach the player the spell to level 0, just like the initial reading of a spell from a book or scroll.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10157-gcf1dc76 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context
Asking for training in a spell known to the player appears to work correctly. Learning a spell from the same spell group, such as asking to be trained in Cure Light Wounds while knowing any other Biomancer spell does not seem to impact the loop. Essentially it does not appear to be an issue with spell casting classes, but with learning a spell that is not already known.

[test npc spell learn.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3963365/test.npc.spell.learn.zip)

This is a world with a test character prepared to show the issue. The setup isn't difficult though, if there are issues with launching this save. To launch this save you will have to pull the files from the PR #35597 You will spawn in the wizard tower with all 3 spellcasting npcs next to you.

### LINKED ISSUE #36166: NPC(s) do not pulp corpses while following player, nor follow player after.
# Describe the bug

NPC(s) do pulp bodies properly. They state they are going to do it, run over, and stand atop the corpse not moving. They also cease to follow me at this point, despite still being a 'follower'. This goes on until I re-'hire' them.

# Steps To Reproduce

1. Spawn in with a starting NPC.
2. Have them kill a zombie.
3. Witness them state they want to pulp the corpse, run over, and stand atop the corpse.
4. They stand atop the corpse, unmoving, not saying anything or pulping.
5. Step away. They do not follow me.
6. Speak to them, dismiss them, and rehire them in order to get them to even follow me again.

# Expected behavior

NPC(s) will move towards the zombie's corpse, state their intention to pulp it. 
They will then pulp it and promptly return to the player's side, continuing to follow.

# Screenshots

https://i.gyazo.com/d151ec59792b02548626532eeb1f5fed.jpg

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-10279-gc698d3d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Crazy Cataclysm [crazy_cataclysm],
    EZ-Mode Medical [fast_healing],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Necromancy [necromancy],
    Bionic Slots [cbm_slots],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Fuji's Military Profession Pack [fuji_mpp],
    No Filthy Clothing [no_filthy_clothing],
    Sleep Deprivation [sleepdeprivation],
    Simplified Nutrition [novitamins],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Cataclysm++ [Cata++]
]

# Additional context

Save file?  I guess?

[Mountain Pine.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3970025/Mountain.Pine.zip)

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Limit time taken for NPCs to train new spells"```

#### Purpose of change
Fixes #36090 

#### Describe the solution
Added a max and min to the return of time to learn spell.

#### Describe alternatives you've considered
N/A

#### Testing
Spawned magiclysm test NPC, asked them to train me in various spells I didnt yet know, some took 3 hours, some took 6, none were lower or higher than that.

#### Additional context
In the future, we would ideally want a system where NPCs can train you a new style or spell over many sessions, remembering their progress towards it, but we dont have that yet, so in th emeantime I can just make the training times feasible.

### CODE REVIEW

File: src/npctalk_funcs.cpp [hunk 1]
```diff
@@ -914,11 +914,14 @@ void talk_function::start_training( npc &p )
...
         // if player doesnt know this spell, then the NPC will teach all of it
-        // which takes as long as it takes.
+        // which takes max 6 hours, min 3 hours.
+        // TODO: a system for NPCs to train new stuff in bits and pieces
+        // and remember the progress.
         if( knows ) {
             time = 1_hours;
         } else {
-            time = time_duration::from_seconds( g->u.magic.time_to_learn_spell( g->u, sp_id ) / 2 );
+            time = time_duration::from_seconds( std::max( 7200, std::min( 21600,
```
Comment (KorGgenT) [inline src/npctalk_funcs.cpp]: you should use the `clamp` function here for clarity.
