### PR TITLE
Fix crash resulting from NPC activity migration (loading 0.F saves)

### LINKED ISSUE #50661: Crash on the next game tick in the experimental, works fine on stable.
### Describe the bug

Game crashes on next tick. Works fine at stable, disabling outdated mod doesn't matter.

### Steps To Reproduce

1. Start game, select world, select the only character, load.
2. Do anything that takes time (wait, talk with NPC)
3. Crash

### Expected behavior

No crash

### Screenshots

_No response_

### Versions and configuration

- OS: Win 10
- Game Version:  ed2f630
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: [
  "dda",
  "no_npc_food",
  "MMA",
  "stats_through_kills",
  "StatsThroughSkills",
  "speedydex",
  "fuji_mpp",
  "MADA_bows_rebalance" //same thing without it
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6964902/debug.log)
There's no crash.log.
[Wayne Lakes Park_crashonnexttick_2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6964905/Wayne.Lakes.Park_crashonnexttick_2.zip) (sorry about ((save)7z)zip)

### LINKED ISSUE #51127: Some 0.F stable saves crash in 0.F experimental
### Describe the bug

It's been discovered that 0.F stable saves supplied with bug reports crash when loaded in 0.F experimental (after ignoring reports about PARKOUR and items being too large) as soon as the next action is taken.

This report contains some info, as well as a save https://github.com/CleverRaven/Cataclysm-DDA/issues/50596

### Steps To Reproduce

1. Load the save in #50596 
2. Do something (probably anything advancing time)
3. Crash to desktop

### Expected behavior

Migrated saves should migrate.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: bc28921 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

My best guess is that the activity of one of the companions may have been modified in such a way that the migration fails to handle it properly, but that's just a wild guess.

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Bugfixes "Fix crash resulting from NPC activity migration (loading 0.F saves)"

#### Purpose of change

Fixes #51127 
Fixes #50661

NPC `player_activity` objects for saves made in 0.F have `actor` set to `null`, causing segfault in `do_turn()` despite migration code attempting to cancel them by setting the activity ID to `ACT_MIGRATION_CANCEL`. The problem is that the migration code doesn't also set the `actor` field (even though we do have an actor class for that activity type).

#### Describe the solution

~Add a null guard, with a debug error message.~ [removed, not necessary]
Change the migration code to also set the actor correctly when creating `ACT_MIGRATION_CANCEL` activities.

#### Testing

Load the saves from the 2 bugs. No crashes and NPCs stop what they were doing (as expected due to how migration works).

#### Additional context

Thanks to @hexagonrecursion for helping to track down the source of the bug and for pointing out a 17-day old alternative fix (#50669).

### CODE REVIEW

**Comment by hexagonrecursion** [comment]
Probably also fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/50661. I notice your approach is different from #50669. I think the fix in the deserialization code makes the null guard obsolete.

**Comment by eltank** [comment]
Yeah, the null guard seems unnecessary now, I'll remove it.

File: src/savegame_json.cpp [hunk 1]
```diff
@@ -334,13 +334,15 @@ void player_activity::deserialize( JsonIn &jsin )
     // this may cause inconvenience but should avoid any lasting damage to npcs
     if( is_obsolete || ( has_actor && ( data.has_null( "actor" ) || !data.has_member( "actor" ) ) ) ) {
         type = activity_id( "ACT_MIGRATION_CANCEL" );
+        actor = activity_actors::deserialize_functions.at( type )( jsin );
```
Comment (hexagonrecursion) [inline src/savegame_json.cpp:337]: This line is suspicious. `JsonIn` is a stream - once you read something it is gone. By this point `player_activity::deserialize()` has already consumed the entire activity and turned it into `JsonObject data`.
Currently `migration_cancel_activity_actor::deserialize()` does not read JsonIn and simply returns `migration_cancel_activity_actor().clone()` if in the future it does read JsonIn this may corrupt the stream.

https://github.com/CleverRaven/Cataclysm-DDA/blob/e49b6f7cc0b5038c8ca7ee940783b0ac07a77841/src/activity_actor.cpp#L2288-L2291
I would replace this line with:
```
actor = migration_cancel_activity_actor().clone(); 
```

Comment (eltank) [reply src/savegame_json.cpp:339]: Oh yeah, I had a comment explaining why it's safe to give it jsin but forgot to push it.
I considered instantiating the actor directly but I'd need to include a large header file.
Alternatively, I could pass in a dummy JsonIn, but I couldn't find an easy way to make one.

Comment (eltank) [reply src/savegame_json.cpp]: Alright, I added the extra include and instantiated the actor directly. It's cleaner.

**Comment by eltank** [comment]
Rebased to pick up VS build fix, 51151.
