### PR TITLE
Forbid learning spells from spellbooks with low morale

### LINKED ISSUE #39195: can study spells while morale is low, unlike studying skill books
# Describe the bug

You can learn/read spells when morales are low
# Steps To Reproduce

1. Get your morale to go low. Like depress
2. Learn/read a spell
3. Result

# Expected behavior

You can read/learn the spells,even with a very low morale, when you shouldn't be able to

# Screenshots

# Versions and configuration

Game version : Danny experimental release 10399
Android version
Graphic : Tiles
Ingame language : English
Mods loaded : Magicclysm, C.R.I.T expansion mod, Aftershock.

# Additional context

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Bugfixes "Forbid learning spells from spellbooks with low morale"

#### Purpose of change
* Closes #39195.

#### Describe the solution
Added a check for morale `learn_spell_actor::use`.

#### Describe alternatives you've considered
None.

#### Testing
In a world with Magiclysm debug-spawned `A Beginner's Guide to Magic`. Killed several zombie children to get a very low morale. Tried to read the book, got a `What's the point of studying?  (Your morale is too low!)` message.

#### Additional context
Reading spellbooks is too permissive compared to reading usual books. For example, you can read spellbooks while driving, or without reading glasses or vision-fixing bionic (while being hyperopic). Initially I wanted to simply put checks for these conditions into `learn_spell_actor::use` but decided not to because of code duplication. Added a TODO instead.

### CODE REVIEW

File: src/iuse_actor.cpp [hunk 1]
```diff
@@ -2386,14 +2386,20 @@ void learn_spell_actor::info( const item &, std::vector<iteminfo> &dump ) const
     }
 }
 
-std::optional<int> learn_spell_actor::use( Character *p, item &, const tripoint & ) const
+std::optional<int> learn_spell_actor::use( Character *p, item &it, const tripoint & ) const
```
Comment (Night-Pryanik) [inline src/iuse_actor.cpp:2389]:
```suggestion
std::optional<int> learn_spell_actor::use( Character *p, item &, const tripoint & ) const
```

File: src/iuse_actor.h [hunk 2]
```diff
@@ -697,7 +697,7 @@ class learn_spell_actor : public iuse_actor
 
         ~learn_spell_actor() override = default;
         void load( const JsonObject &obj, const std::string & ) override;
-        std::optional<int> use( Character *p, item &, const tripoint & ) const override;
+        std::optional<int> use( Character *p, item &it, const tripoint & ) const override;
```
Comment (Night-Pryanik) [inline src/iuse_actor.h:700]:
```suggestion
        std::optional<int> use( Character *p, item &, const tripoint & ) const override;
```
