### PR TITLE
Shifting fixes

### LINKED ISSUE #54465: Portal Storm Teleports Player Ahead of Moving Vehicle Without Warning Prompt or Any Messaging
### Describe the bug

Never saw this before today however, while driving I've repeatedly had my character thrown about 10-15 squares in front of my vehicle while driving in a portal storm. There is no prompt or warning (unlike the time-reverse one, which can also throw player out of vehicle) however this could potentially kill a player almost instantly, because the car is still moving and will hit them, without much time to dodge.

In the screenshots provided, I was thrown out of my car and re-entered it, then 3-4 minutes later in-game I was teleported forward again and then hit by the car, then tried to move out of the way and was hit again before being pushed aside. Full health to having every limb nearly broken, as well as a number of pieces of armor and weapon which were destroyed.

The fact that there's no warning or any message at all in the log means that a player who's driving in a line hitting Num5 repeatedly, may likely end up badly injured and breaking a bunch of gear before they could react. FWIW, I haven't seen the time-reverse happen since this began occurring.

### Steps to reproduce

1. Start portal storm.
2. Drive around.
3. Observe character moved ahead of moving car with no prompt.
4. Try to dodge away in time.

### Expected behavior

Expected some kind of warning prompt, and possibly not moving the  character ahead in path of vehicle every time.

### Screenshots

image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### LINKED ISSUE #54569: Portal Storm Teleport That Also Spawns Enemies - Does Not Interrupt Picking Up Items
### Describe the bug

There's a new teleport (as of this morning's update, or so) where it throws you a ways away and also spawns in enemies at the same time. I was picking up multiple items from a crate and got teleported with enemies spawning in at the same time, but continued the pickup action and got hit a couple times before I could do anything so they had plenty of time to move up to me and hit me more than once.

For funsies, I almost landed on an active landmine - would it have been set off? Probably! lol

(screenshot doesn't show the landmined area, because I didn't stop to screenshot until I got popped around out of my car a little later, but it's at "9 minutes" you can see the message and subsequently being hit 3x)

### Steps to reproduce

1. Start Portal Storm
2. Pick up items from crate (or other containers, possibly?).
3. Observe being teleported and attacked multiple times before able to react.

### Expected behavior

Expected action to interrupt when teleported, to prevent multiple free enemy actions.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 98a8e80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fixes #54465
Fixes #54569
Fix issue with long distance transforms, mapgen updates and teleports moving around avatar.
Add code so that timed events are saved.
Reorder debug menu due to complaints

### CODE REVIEW

File: src/teleport.cpp [hunk 1]
```diff
@@ -77,8 +79,9 @@ bool teleport::teleport_to_point( Creature &critter, tripoint target, bool safe,
             if( c_is_u && display_message ) {
                 add_msg( m_bad, _( "You cannot teleport safely." ) );
             }
-            if( shifted ) {
-                g->place_player_overmap( critter.global_omt_location() );
+            if( shifted ) {
```
Comment (kevingranade) [inline src/teleport.cpp:82]:
```suggestion
            if( shifted ) {
```
