### PR TITLE
Fix incorrect display of gunmods

### LINKED ISSUE #16803: Segmentation fault viewing A7 Laser Rifle in inventory
On the latest experimental, when I pull my A7 Laser rifle out of my back holster and inspect it or drop it I get a segfault. I've included a backtrace... sort of new to this hope it helps.
**File Removed**

### LINKED ISSUE #16850: Trying to examine a gun with a sword bayonet mod active causes a crash
Windows 10
Tiles
Version 0.C-14379-ga3bc3ca

When examining a gun with an active sword bayonet mod, either in the inventory or on the ground, an error message pops up saying:
```
DEBUG    : unknown skill none

FUNCTION : const T& string_id<T>::obj() const [with T = Skill]
FILE     : src/skill.cpp
LINE     : 25

Press spacebar to continue the game...
Press I (or i) to also ignore this particular message in the future...  
```
Pressing spacebar causes cataclysm-tiles.exe to stop working.

### LINKED ISSUE #16882: All guns are described as having a current gunmod
Slings are unlikely to get auxiliary mods, yet they are described as if having a current gunmod.

Gunmod description should probably be hidden when the default mode is selected.

### PR DESCRIPTION
**Pull request by mugling**
Trivial fix #16882

EDIT: Also fix #16850
EDIT: Also fix #16803

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -817,8 +817,10 @@ std::string item::info( bool showtext, std::vector<iteminfo> &info ) const
 
     } else {
         const item *mod = this;
-        if( !is_gunmod() ) {
-            mod = &*gun_current_mode();
+        auto& aux = *gun_current_mode();
+        // if we have an active auxiliary gunmod display stats for this instead
+        if( aux.is_gunmod() && aux.is_gun() ) {
```
Comment (BevapDin) [inline src/item.cpp]: Crashes because `aux` is null when displaying masterkey shotgun item in the wish item menu.

Comment (mugling) [inline src/item.cpp]: @BevapDin well spotted see d84c5a6
