### PR TITLE
Fix formatting error at @ screen

### LINKED ISSUE #22643: basic_string::substr: appears in @ menu
screenshot 458

There's also a blank line in the perception subscreen, though that is probably intended.

### PR DESCRIPTION
**Pull request by AMurkin**
Fixes #22643

### CODE REVIEW

File: src/player_display.cpp [hunk 1]
```diff
@@ -696,8 +696,8 @@ Strength - 4;    Dexterity - 4;    Intelligence - 4;    Perception - 4" ) );
                     mvwprintz( w_stats, 6, 21, c_magenta, "%+.1lf", get_hit_base() );
                     mvwprintz( w_stats, 7, 1, c_magenta, _( "Ranged penalty:" ) );
                     mvwprintz( w_stats, 7, 23, c_magenta, "%+3d", -( abs( ranged_dex_mod() ) ) );
-                    mvwprintz( w_stats, 8, 1, c_magenta, _( "Throwing penalty per target's dodge: +%d" ) );
-                    mvwprintz( w_stats, 8, 22, c_magenta, "%3d", throw_dispersion_per_dodge( false ) );
+                    mvwprintz( w_stats, 8, 1, c_magenta, _( "Throwing penalty per target's dodge:" ) );
+                    mvwprintz( w_stats, 8, 22, c_magenta, "+%3d", throw_dispersion_per_dodge( false ) );
```
Comment (cainiaowu) [inline src/player_display.cpp]: shouldn't it be "%+3d" like the one at two lines above?

Comment (AMurkin) [reply src/player_display.cpp]: Perhaps, but this differs from the variant, if the substitution was performed in the original code.

Comment (AMurkin) [reply src/player_display.cpp]: Although, I think you're right. I will do the same as in the previous line.
