### PR TITLE
Faction camp overseer fixes

### LINKED ISSUE #25103: No way to recover faction camp after camp manager is dead
**Describe the bug**  
We have underlying infrastructure to mark a basecamp in src/basecamp.cpp.
But the currently implement use the NPC pointer to store Faction Camp info.
When the camp manager is dead, there is no way to recover the Faction Camp.

**To Reproduce**  
1. Make a camp
2. Kill that camp manager.
3. Enjoy the dead camp and lost all your companions who are doing missions.

**Expected behavior**  
1. Camp manager is dead.
2. Talk to one of your minions.
3. Setup the Camp via talk_function::become_overseer.
4. Choose the old camp on the map.
5. Old camp is reclaimed.

or

1. Camp manager is dead.
2. But we have a bulletin_board in the camp.
3. iexamine::bulletin_board then choose a minion.
4. Camp is reclaimed, the minion is now the new camp manager .

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Any
 - Game Version: master
 - Graphics version: Any
 - Mods loaded: Any

**Additional context**  
the basecamp.cpp and basecamp.h is dead code, let it have some new use.

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Features "Faction camp overseer fixes"```

#### Purpose of change
Fixes #25103 - Moves the faction camp creation dialogue into a separate talk topic, which includes the
tutorial and adds an option to recover a faction camp that doesn't have a camp overseer.

#### Describe the solution
Adds two new response conditions:
* u_at_om_location, which tests whether the player is on a particular type of overmap tile
* npc_role_nearby, which tests whether any NPCs nearby have a particular mission companion role.

These response conditions are documented in NPCs.md and are included in the npc_talk_test unit tests.

Use these new response conditions in a new dialogue entry, with 5 basic responses:
* ask for the faction camp tutorial
* tell the NPC to start a faction camp; only appears when the PC is standing in a field
* tell the NPC to recover a faction camp; only appears when the PC is standing in a faction camp without an overseer
* return to the previous talk topic
* end the dialogue

Also, camp overseers who abandon a camp have the ", Camp Manager" tag removed from their names.

#### Describe alternatives you've considered
I'd like to merge basecamps with faction camps.  The player would be able to give assignments to NPCs through dialogue, and recover NPCs from companion missions by interacting with the bulletin board.  That's a huge overhaul, and will take some time.  For now, this fixes an open issue.

### CODE REVIEW

**Comment by mlangsdorf** [comment]
Jenkins rebuild

**Comment by Qrox** [comment]
There's another possible way to remove an NPC from overseer position: 'OBEY ME' option with debug mind control. Could you please also look into it? From what I see in the code it might not be properly cleaned up.

File: tests/npc_talk_test.cpp [hunk 1]
```diff
@@ -24,37 +25,47 @@ const efftype_id effect_infected( "infected" );
 static const trait_id trait_PROF_FED( "PROF_FED" );
 static const trait_id trait_PROF_SWAT( "PROF_SWAT" );
 
-npc create_test_talker()
+npc *create_test_talker()
```
Comment (BevapDin) [inline tests/npc_talk_test.cpp]: This should return a reference (the pointer it currently returns is never null anyway). Then you could store the result as reference in the calling function below and you would not need to change all the lines above from `.` to `->`.

**Comment by mlangsdorf** [comment]
Debug mind control clears the TALK_CAMP_OVERSEE topic from the conversation list.  The NPC still has the suffix but I'm not going to spend a lot of time special casing a debug function.

File: tests/npc_talk_test.cpp (hunk 1 above)
Comment (mlangsdorf) [reply tests/npc_talk_test.cpp]: Fixed, thanks.
Still doesn't resolve Travis failing the tests that work fine on my test box.

Comment (mlangsdorf) [reply tests/npc_talk_test.cpp]: Test harness has STATIC_NPCS set to off. Fixed the test harness.
