### PR TITLE
Disable scenarios that require a city start when city_size option set to 0

### LINKED ISSUE #21667: Starting in city location with City Size at 0 freezes game
### Steps to reproduce the behavior

1. In world creation, set "Size of cities" to 0.
    The help text notes that this disables cities entirely.
2. Create a character in a scenario that only has city-based starting locations. An example is the "missed" scenario.
3. Finish character creation. The game will display a dialog, "Please wait as we build your world," as the game steadily takes up more memory.

I have a hunch that what's going on behind the scenes is, with #21212, the game is generating more and more overmaps to find a suitable location for a starting location special. That will never happen, however, as no spawn locations have suitable areas for placement.

### PR DESCRIPTION
**Pull request by laeaton2001**
Fixes #21667.
Updates:
Added a new flag to scenarios JSON to indicate that the scenario requires a city to start in.
Updated option text to include that a size of 0 disables some scenarios.
Updated character creation to sort disabled scenarios to bottom of list, color them dark grey & add explanation text to thier description.
Updated confirm action to do nothing for disbaled scenarios.

If someone can confirm I flagged the right scenarios before a merge it would be great.

### CODE REVIEW

File: src/newcharacter.cpp [hunk 1]
```diff
@@ -1887,8 +1901,11 @@ tab_direction set_scenario(WINDOW *w, player *u, points_left &points)
                   sorted_scens[cur_id]->gender_appropriate_name(u->male).c_str(),
                   pointsForScen);
 
-        fold_and_print(w_description, 0, 0, TERMX - 2, c_green,
-                       sorted_scens[cur_id]->description(u->male).c_str());
+        std::string scenUnavailable = "This scenario is not available in this world due to city size settings. ";
```
Comment (BevapDin) [inline src/newcharacter.cpp]: Needs to be translated - add `_(  )`.

File: src/newcharacter.cpp [hunk 2]
```diff
@@ -1887,8 +1901,11 @@ tab_direction set_scenario(WINDOW *w, player *u, points_left &points)
...
+        std::string scenDesc = ( sorted_scens[cur_id]->has_flag( "CITY_START" ) && !scenario_sorter.cities_enabled ) ? 
+            (scenUnavailable + sorted_scens[cur_id]->description( u->male ).c_str()) :
+            sorted_scens[cur_id]->description( u->male ).c_str();
```
Comment (BevapDin) [inline src/newcharacter.cpp]: Why the call to `c_str` here? It should work fine without it. Same in the line above.

File: src/newcharacter.cpp [hunk 3]
```diff
@@ -2002,20 +2025,21 @@ tab_direction set_scenario(WINDOW *w, player *u, points_left &points)
...
-            g->scen = sorted_scens[cur_id];
-            u->prof = &default_prof.obj();
-            u->empty_traits();
-            u->empty_skills();
-            u->add_traits();
-            points.init_from_options();
-            points.skill_points -= sorted_scens[cur_id]->point_cost();
-
-
+            if( sorted_scens[cur_id]->has_flag( "CITY_START" ) && !scenario_sorter.cities_enabled ) {}
```
Comment (BevapDin) [inline src/newcharacter.cpp]: The styling is terrible, one can easily miss the `{}`. And the indentation is not needed, just `continue` when the selected scenario is not allowed:
```C++
if( confirm ) {
    if( scenario not allowed ) {
        continue;
    }
    ... // remaining original code.
```

File: src/newcharacter.cpp [hunk 4]
```diff
@@ -1752,8 +1754,18 @@ struct {
         } else if (a == gen) {
             return true;
         }
-
-        if (sort_by_points) {
+        if( !cities_enabled ) {
+            if( a->has_flag( "CITY_START" ) == b->has_flag( "CITY_START" ) ) {
```
Comment (BevapDin) [inline src/newcharacter.cpp]: You don't need to repeat all the comparisons here. You can return quickly when the two scenarios differ in the flag and otherwise continue with the existing comparison:
```C++
if( a->has_flag != b->has_flag ) {
    return a->has_flag < b->has_flag;
}
... // original code
```

**Comment by laeaton2001** [comment]
Thanks for the feedback.

**Comment by Leland** [comment]
Quick screenshot for posterity:
screen shot 2017-10-22 at 10 43 23 am

Looks good. Would be much improved if the part of the description noting the disable could be made red, but I bet that's rather hardcoded.

**Comment by laeaton2001** [comment]
Turns out making it red wasn't hard.
image

**Comment by Leland** [comment]
It's weird – I'm still getting #21667's behavior (endlessly building world) when doing the Evacuee start on this PR, but the evac shelter special doesn't spawn in the city. Wonder what the deal is.

https://github.com/CleverRaven/Cataclysm-DDA/blob/3f6775fe081493a0950970747ad55b7632fc7874/data/json/overmap_specials.json#L753-L761

**Comment by laeaton2001** [comment]
It's probably the road connection requirement of the evac shelter causing this since no cities means no roads. Hadn't thought of that.

**Comment by laeaton2001** [comment]
I've added the city_start flag to the scenarios I found where required a road for their overmap special. Since this included the Evacuee, I've updated the code to not default to that scenario if city_size is 0.

**Comment by angoddu** [comment]
Somewhat off topic but what happens when city size is 0? Are there just no cities period or will you see the city label where a city would be? What kind of buildings would be left if there are no cities?

**Comment by Leland** [comment]
@angoddu give it a shot! It's just wilderness. Few buildings, no cities or labels.

**Comment by angoddu** [comment]
I've been playing on a size 2 space 8 world. Almost no cities but some. Then I can get some rags, pots, and nails. 0 would be interesting to see what is and isn't possible.
