### PR TITLE
Serialize requirements for fetch activity

### LINKED ISSUE #34874: NPCs abandon tasks after game reload
# Describe the bug

When you give task to NPC, he will do it until you reload game (quit and load). After this they will follow you as though you didn't tell them to do something.

# Steps To Reproduce

1. Give NPC task to do (tree chopping).
2. Quit game.
3. Load game.
4. NPC should abandon task and start follow you.

# Expected behavior

NPC should do his/her task as long as it isn't finished.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-8583-g08353e3 [64-bit]
 - Graphics version: Tiles
 - Mods loaded: Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Hydroponics [hydroponics],
    Vehicle Additions Pack [blazemod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
 ```SUMMARY: Bugfixes "Serialize requirements for fetch activity"```

#### Purpose of change
Fixes #34874 

#### Describe the solution
This makes some changes to save/loading to enable NPCs to continue where they left off with their activities after loading. It saves automove route and destination_activity properly so npcs can have that restored, and sets up a proper serialization for requirement_data, so that custom requirements created on the fly during gameplay can be stored and retrieved.

#### Describe alternatives you've considered
N/A

#### Testing
Told an NPC to go and chop some trees, with a wood axe nearby, while they were walking toward the wood axe, I saved and loaded, they remembered they were walking there, and when they got there and retrieved the requirement_id stored in the backlog activity, it still pointed to a valid requirement_data object, as that had been reconstructed on load.

Also tested with construction, and they remembered their requirements there too, but this also  revealed that currently, NPCs are not repeating the construction task after fetching, but thats something seperate Ill look at.

#### Additional context
N/A

### CODE REVIEW

File: src/character.h [hunk 1]
```diff
@@ -1063,7 +1063,7 @@ class Character : public Creature, public visitable<Character>
         // Means player sit inside vehicle on the tile he is now
         bool in_vehicle;
         bool hauling;
-
+        player_activity destination_activity;
```
Comment (KorGgenT) [inline src/character.h]: in `player` this was private. this should be private in `Character` as well.

File: src/savegame_json.cpp [hunk 2]
```diff
@@ -296,6 +296,39 @@ void player_activity::deserialize( JsonIn &jsin )
...
 
+////////////////////////////////////////////////////////////////////////////////////////////////////
+///// requirements.h
+void requirement_data::serialize( JsonOut &json ) const
+{
+    json.start_object();
+
+    if( !is_null() ) {
+        json.member( "blacklisted", blacklisted );
+        std::vector<std::vector<item_comp>> req_comps = get_components();
```
Comment (KorGgenT) [inline src/savegame_json.cpp]:
```suggestion
        const std::vector<std::vector<item_comp>> req_comps = get_components();
```

File: src/savegame_json.cpp [hunk 3]
```diff
@@ -296,6 +296,39 @@ void player_activity::deserialize( JsonIn &jsin )
...
+        std::vector<std::vector<tool_comp>> tool_comps = get_tools();
```
Comment (KorGgenT) [inline src/savegame_json.cpp]:
```suggestion
        const std::vector<std::vector<tool_comp>> tool_comps = get_tools();
```

File: src/savegame_json.cpp [hunk 4]
```diff
@@ -296,6 +296,39 @@ void player_activity::deserialize( JsonIn &jsin )
...
+        std::vector<std::vector<quality_requirement>> quality_comps = get_qualities();
```
Comment (KorGgenT) [inline src/savegame_json.cpp]:
```suggestion
        const std::vector<std::vector<quality_requirement>> quality_comps = get_qualities();
```

File: src/savegame_json.cpp [hunk 5]
```diff
@@ -679,6 +743,17 @@ void player::store( JsonOut &json ) const
     }
     json.end_array();
 
+    json.member( "automoveroute" );
+    json.start_array();
+    for( const auto &elem : auto_move_route ) {
```
Comment (KorGgenT) [inline src/savegame_json.cpp]: please remove this auto
additionally, if it's a supported type, `json.member( "automoveroute", auto_move_route )` should work rather than writing the for loop here.

File: src/savegame_json.cpp [hunk 6]
```diff
@@ -781,6 +858,13 @@ void player::load( JsonObject &data )
         known_traps.insert( trap_map::value_type( p, t ) );
     }
 
+    JsonArray automoveroute = data.get_array( "automoveroute" );
```
Comment (KorGgenT) [inline src/savegame_json.cpp]: same as the serialize for this member

File: src/savegame_json.cpp [hunk 7]
```diff
@@ -667,6 +730,7 @@ void player::store( JsonOut &json ) const
     // "Looks like I picked the wrong week to quit smoking." - Steve McCroskey
     json.member( "addictions", addictions );
     json.member( "followers", follower_ids );
+
```
Comment (KorGgenT) [inline src/savegame_json.cpp]:
```suggestion
```
random line addition?
