### PR TITLE
fix capacity info for integral magazines

### LINKED ISSUE #31488: Some guns not showing their compatible ammo type
# Describe the bug

After #30874 some guns are not showing compatible ammo types in their description.

# Steps To Reproduce

1. Spawn Remington 870 with no ammo in it.
2. Open inventory and inspect weapon.

# Expected behavior

Compatible ammo type should show in description like it did before.

# Screenshots
### Beretta M9 still shows it's ammo type:
M9
### Remington 870 doesn't:
Remington 870

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-4382-gf1a5f47
 - Graphics version: Tiles
 - Mods loaded: [
  "dda",
  "no_npc_food",
  "aftershock",
  "More_Survival_Tools",
  "makeshift",
  "craftgp",
  "growable-pots",
  "modular_turrets",
  "mutant_npcs",
  "alt_map_key",
  "hydroponics",
  "more_locations",
  "FujiStruct",
  "Urban_Development",
  "boats",
  "blazemod",
  "deoxymod",
  "Tanks",
  "DP_REMIX_INDICATORS",
  "MMA",
  "safeautodoc",
  "no_reviving_zombies",
  "more_classes_scenarios",
  "StatsThroughSkills",
  "EngineeringEssentials"
]

# Additional context
None

### PR DESCRIPTION
**Pull request by ymber**
#### Summary
SUMMARY: Bugfixes "Fix ammo type and capacity display for weapons with internal magazines"

#### Purpose of change
Fixes #31488

#### Describe the solution
Print capacity data in all cases. Previously it was only printed if mod->magazine_current() returned a valid item.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -1442,6 +1442,13 @@ std::string item::info( std::vector<iteminfo> &info, const iteminfo_query *parts
                         info.emplace_back( "GUN", _( "<bold>Capacity:</bold> " ), fmt, iteminfo::no_flags,
                                            mod->ammo_capacity() );
                     }
```
Comment (ZhilkinSerg) [inline src/item.cpp]:
```suggestion
```

File: src/item.cpp [hunk 2]
```diff
@@ -1442,6 +1442,13 @@ std::string item::info( std::vector<iteminfo> &info, const iteminfo_query *parts
...
+                    else {
```
Comment (ZhilkinSerg) [inline src/item.cpp]:
```suggestion
                   } else {
```
