### PR TITLE
Camp serialization via overmap, rename a camp.

### LINKED ISSUE #28872: More bugs with faction camps
**Describe the bug**  
If you create a camp, then safe-load your game, your camp name will be reset to "Faction Camp 1". Moreover, if you create more than 1 camp, all will be removed from your factions menu, except for last one. There will be only "+" symbol on the map, and all buildings will stay there. Also i tried to remove the camp data from .map file, and was able to occupy it and enter new name, but the same result on save-load

**To Reproduce**  
1. Create new world
2. Spawn some camps
3. Press save and exit
4. Load

**Additional context**  
If you can't reproduce the bug, use the save file from that issue: #28868

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

```SUMMARY: Bugfixes "Camp serialization via overmap, rename a camp."```

#### Purpose of change
Fixes #28872 

#### Describe the solution
In the previous attempt to move camps to overmap, I did not do it properly.
This time, I have made the camps sit properly owned by overmaps, all the functions to get them, find them etc, are overmap functions, the serialization is on the overmap.

This means that saving/loading should now function properly in showing all of your camps, also a renaming camp function in the camp summary menu.

If you have an older camp from an older save, you will need to be at it's location and examine it's bulletin board to add it to the overmap manually ( or open the summary menu near the camp )

All new camps created going forward will be added correctly though.

#### Describe alternatives you've considered
Once again I tried many things to avoid the big work that this would involve, tried lazy validation on load to repopulate lists, but these were all nasty hacks, the best solution was always the one I was avoiding. this one.

#### Additional context
I am fairly certain that all new camps going forward will be correctly on the overmp, and all legacy camps will be correctly converted. Although obtaining legacy camp older savegames has been a bit laborious to test all the possible permutations.

This does not fix the other faction camp bugs with upgrades and displaying the missions - those I am not sure of the cause, possibly the changes to editmap from the UI changes changing the terrain window padding, or possibly somethign else, I will look into those next.

I've removed the un-used NPC mission assign_base as I will be reworking that hopefully anyway soon and it was causing problems with the new camp structure.

### CODE REVIEW

File: src/faction_camp.cpp [hunk 1]
```diff
@@ -428,18 +428,22 @@ static bool update_time_fixed( std::string &entry, const comp_list &npc_list,
...
     g->m.add_camp( p.pos(), "faction_camp" );
-    bcp = g->m.camp_at( p.pos(), 60 );
-    if( bcp ) {
-        bcp->define_camp( p );
+    bcp = overmap_buffer.find_camp( omt_tri.x, omt_tri.y );
+    if( !bcp ) {
+        return cata::nullopt;
     }
-    return bcp;
+    basecamp *temp_camp = *bcp;
```
Comment (mlangsdorf) [inline src/faction_camp.cpp]: why aren't you calling define_camp() on bcp and returning bcp?

File: src/faction_camp.cpp [hunk 2]
```diff
@@ -428,18 +428,22 @@ static bool update_time_fixed( std::string &entry, const comp_list &npc_list,
     return avail;
 }
 
-static basecamp *get_basecamp( npc &p )
+static cata::optional<basecamp *> get_basecamp( npc &p )
 {
-    basecamp *bcp = g->m.camp_at( p.pos(), 60 );
+
+    tripoint omt_tri = p.global_omt_location();
+    cata::optional<basecamp *> bcp = overmap_buffer.find_camp( omt_tri.x, omt_tri.y );
```
Comment (mlangsdorf) [inline src/faction_camp.cpp]: I've been using omt_pos to indicate an omt tripoint and it wouldn't hurt to be consistent within this code.

File: src/map.cpp [hunk 3]
```diff
@@ -5434,46 +5434,24 @@ computer *map::computer_at( const tripoint &p )
...
 }
 
 void map::add_camp( const tripoint &p, const std::string &name )
 {
-    if( !allow_camp( p ) ) {
-        dbg( D_ERROR ) << "map::add_camp: Attempting to add camp when one in local area.";
-        return;
-    }
     point omt = ms_to_omt_copy( g->m.getabs( p.x, p.y ) );
     tripoint omt_tri = tripoint( omt.x, omt.y, p.z );
```
Comment (mlangsdorf) [inline src/map.cpp]: Not your code, but
```
-    point omt = ms_to_omt_copy( g->m.getabs( p.x, p.y ) );
-    tripoint omt_tri = tripoint( omt.x, omt.y, p.z );
+    tripoint omt_tri = ms_to_omt_copy( g->m.getabs( p ) );
```

File: src/faction_camp.cpp (hunk 1 above)
Comment (davidpwbrown) [reply src/faction_camp.cpp]: Because it doesn't work, something to do with it being a cataoptional.
Can't run define_camp on it directly, have to create a basecamp pointer to it.
I'm not entirely sure why

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Okay.
