### PR TITLE
Fix issue #10779

### LINKED ISSUE #10779: Crash when pressing E in craft menu when no items are in the list.
Saw this issue in version 0B. 

To reproduce:

Open Craft menu.
Use find to search for something such as "blah", it brings up no results.
Press E
Game will crash and exit and any unsaved progress will be lost. 

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7562434-crash-when-pressing-e-in-craft-menu-when-no-items-are-in-the-list?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by VlasovVitaly**
Closes  #10779

### CODE REVIEW

File: src/crafting.cpp [hunk 1]
```diff
@@ -806,6 +811,11 @@ const recipe *select_crafting_recipe( int &batch_size )
             filterstring = "";
             redraw = true;
         } else if (action == "CYCLE_BATCH") {
+            if (current.empty()) {
+                popup(_("Nothing selected!"));
```
Comment (KA101) [inline src/crafting.cpp]: popup is moot thanks to the redraw, but that's a trivial issue.
