### PR TITLE
Make butcher menu use proper disassembly

### LINKED ISSUE #12971: Minor: Sandwich disassemble
Certain food can be disassembled and resetting the rot status even if pre-disassembled food has already rotted.  Currently I only find some of the sandwich having this property.  It's nothing broken as food isn't an issue by the time you can reliably make sandwiches but something to note.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24505381-minor-sandwich-disassemble?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by drbig**
Fixes #12971.

It works. Here. At least...

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -11153,22 +11153,15 @@ void game::butcher()
...
-    if( !dis_item.is_corpse() && butcher_corpse_index < (int)salvage_index) {
-        const recipe *cur_recipe = get_disassemble_recipe(dis_item.type->id);
-        assert(cur_recipe != NULL); // tested above
-        if( !query_dissamble( dis_item ) ) {
-            return;
-        }
-        u.assign_activity(ACT_DISASSEMBLE, cur_recipe->time, cur_recipe->id);
-        u.activity.values.push_back(corpses[butcher_corpse_index]);
-        u.activity.values.push_back(1);
+    item *dis_item = &items[corpses[butcher_corpse_index]];
```
Comment (BevapDin) [inline src/game.cpp]: Why a pointer, can't you keep it as reference? That would require less code changes below (-;

Consequently, the new `disassemble` should take the item as reference, it makes no sense to supply a `nullptr` for it, so there is no advantages of using a pointer.

Comment (drbig) [inline src/game.cpp]: > so there is no advantages of using a pointer

Ok, that convinces me. Will look into that :)
