### PR TITLE
Defer autopickup item lookups until first use.

### LINKED ISSUE #19620: Game wont start after successful build - Assertion failed
Hey folks, just did a pull and build on my recently updated Mac and found I couldn't play due to the below error message. Not sure where to go from there

Macintosh-2:Cataclysm-DDA_tiles admin$ ./cataclysm-tiles 
Assertion failed: (frozen), function all, file src/item_factory.cpp, line 2301.
Abort trap: 6

### PR DESCRIPTION
**Pull request by mutability**
Disable autopickup UI `<T>est` option if no world is loaded.

The map_items cache and the `<T>est` option require that all the item
json is loaded. Defer populating the cache until an autopickup
check is actually made, which must be after the world is loaded.

Fixes #19620

### CODE REVIEW

File: src/auto_pickup.cpp [hunk 1]
```diff
@@ -78,7 +78,9 @@ void auto_pickup::show( const std::string &custom_name, bool is_autopickup )
     tmpx += shortcut_print(w_header, 0, tmpx, c_white, c_ltgreen, _("<M>ove")) + 2;
     tmpx += shortcut_print(w_header, 0, tmpx, c_white, c_ltgreen, _("<E>nable")) + 2;
     tmpx += shortcut_print(w_header, 0, tmpx, c_white, c_ltgreen, _("<D>isable")) + 2;
-    shortcut_print(w_header, 0, tmpx, c_white, c_ltgreen, _("<T>est"));
+    if( g->u.name != "" ) {
```
Comment (codemime) [inline src/auto_pickup.cpp]: I'd encapsulate these four checks with a function. It could have almost the same condition inside `!u.name.empty()`.

File: src/auto_pickup.cpp [hunk 2]
```diff
@@ -343,9 +345,9 @@ void auto_pickup::show( const std::string &custom_name, bool is_autopickup )
             if( g->u.name != "" ) {
                 save_character();
             }
-        } else {
-            create_rules();
         }
+
+        ready = false;
```
Comment (codemime) [inline src/auto_pickup.cpp]: Looks very vague. Ready for what? Probably `invalidate_map_items()` could help (a pair for `refresh_map_items()`).

File: src/auto_pickup.cpp (hunk 1 above)
Comment (mutability) [inline src/auto_pickup.cpp]: This is a minimal bugfix so builds don't crash; I didn't want to refactor further.

File: src/auto_pickup.cpp (hunk 2 above)
Comment (mutability) [inline src/auto_pickup.cpp]: There's a doxygen comment on the field.

File: src/auto_pickup.h [hunk 3]
```diff
@@ -48,13 +48,15 @@ class auto_pickup : public JsonSerializer, public JsonDeserializer
...
+        mutable bool ready; //< true if map_items has been populated from vRules
+
         /**
          * The currently-active set of auto-pickup rules, in a form that allows quick
          * lookup. When this is filled (by @ref auto_pickup::create_rules()), every
          * item existing in the game that matches a rule (either white- or blacklist)
          * is added as the key, with RULE_WHITELISTED or RULE_BLACKLISTED as the values.
          */
-        std::unordered_map<std::string, rule_state> map_items;
+        mutable std::unordered_map<std::string, rule_state> map_items;
```
Comment (codemime) [inline src/auto_pickup.h]: The name looks very intrinsic. It should reference rules instead of `map` (at least all the relevant functions should do that).

File: src/auto_pickup.cpp (hunk 1 above)
Comment (codemime) [inline src/auto_pickup.cpp]: I see, but you've doubled the number of ugly checks.

File: src/auto_pickup.h (hunk 3 above)
Comment (mutability) [inline src/auto_pickup.h]: See above - this code is ugly, sure, but I am going for the minimum changes to get things working, not a wholesale cleanup.

File: src/auto_pickup.cpp (hunk 2 above)
Comment (codemime) [inline src/auto_pickup.cpp]: I've seen it too, but you could have got rid of it completely. Private things don't require doxygen comments, clearer names are preferable.

**Comment by mutability** [comment]
note that I am out of time to work on this further today; please feel free to use this PR as a starting point and tweak as necessary to get a fix for 19620 in ASAP.

**Comment by mugling** [comment]
@codemime has some good points but this does for now at least get things working again
