### PR TITLE
Crafting menu shows range of possible nutrients for food crafts

### LINKED ISSUE #28180: Recipe display in crafting menu doesn't match resulting product.
**Describe the bug**  
Look at Vitamins/Calories/Volume/Weight for Cooked Oatmeal and Deluxe Cooked Oatmeal. 

Cooked Oatmeal: Iron (12% RDA)
Deluxe Cooked Oatmeal (Using Sugar in my example): Vitamin C (58% RDA)

Wot?

I haven't checked values for other recipe results but I imagine similar things will be seen throughout these valuesfor different foods (I.E Nonsensical results).

**To Reproduce**  
1. Look at the foods in the crafting menu. 

**Expected behavior**  
 Values should likely be calculated based off the food included in an recipe. 

For example, if something is Cooked Meat + Zuchinni, it should combine the values of the two to reach the value of the prepared item. 

While this isn't exactly how it works in real life (Bioavailble nutrients can change based off of how food is prepared if I'm not mistaken), it will likely make sense from a development and maintenance perspective. 

Instead of the value of a resulting recipe being hard coded as they are now, we can do a larger initial amount of work adding values to all food recipe components and add a simple system to combine that value into an end result.  

https://github.com/CleverRaven/Cataclysm-DDA/blob/7bbaecb61eb35e429f8619fe6ba74a67cee7018e/data/json/items/comestibles/wheat.json#L227

https://github.com/CleverRaven/Cataclysm-DDA/blob/7bbaecb61eb35e429f8619fe6ba74a67cee7018e/data/json/items/comestibles/wheat.json#L248

**Versions and configuration(please complete the following information):**
 - OS: **Win10**
 - Game Version: **0.C-37404-g6895100 (tiles)**
 - **Tiles**
 - Mods loaded: **ALL the mods. Really, there are a few.**

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Interface "Crafting menu shows range of possible nutrients for food crafts"

#### Purpose of change
Fixes  #28180.

Currently when crafting a comestible the crafting GUI declares a particular calorie and vitamin content for it.  But the true value that will result depends on the ingredients used.  This is unhelpful and can be confusing for players.

#### Describe the solution
This turns out to be quite tricky in practice, for a few reasons:
* The nutrient calculation is recursive, meaning that we need to know the possible content of ingredients in order to calculate the range for each product.
* It's possible for there to be loops in the recipe graph such that the potential nutrient content is unbounded.  Even in more reasonable loops which preserve nutrient content, it can still be the case that the code needs to search arbitrarily deep through item components in order to calculate the nutrient content.  I decided to consider any loops to be a bug.  Loops can be broken either by editing recipes or by marking one item in the loop with `NUTRIENT_OVERRIDE`.
* The nutrient content depends on player traits (primarily various mutations that affect diet).  In some cases the trait effect depends on the materials involved.  In turn, that means that you cannot simply calculate the "true" overall nutrient content and apply traits to the final value.  To get consistent results requires applying the traits at the 'leaves' of the component tree that is searched.  In particular, this means that it's not practical to cache the results of this calculation; it needs to be calculated afresh each time.

The solution has a number of components:
* At startup (when finalizing game data):
  * Cache a list of non-obsolete recipes that can be used for each item.
  * Search for loops involving comestibles in the recipe graph.  Mark any such comestibles as in a loop (there are no loops in the core game data any more, but mods could add them, so the code still needs to handle the possibility).  Report any loops via `debugmsg` so they can be dealt with.
* New `player::compute_nutrient_range` functions.  One overload for a specific recipe, and another for a generic item intended to take into account all recipes.
* Update `item::foodinfo` to display the new values.  To avoid infinite recursion we don't try to calculate the ranges for any items which were earlier detected to lie on problematic recipe loops.
* Add some tests for the above.

#### Describe alternatives you've considered
When the player has specific ingredients on hand, it might be nice to see the (range of) actual values that would result from those, rather than the complete range of all possibilities.  I decided not to do that because we need to support the more generic situation (where not all ingredients are present) anyway, so that made sense to implement first.  The other feature can be added later (but it won't be trivial!).

We could display the "true" nutritional content rather than the effective content based on player traits.  That would allow simplification, but it would be a change from prior behaviour, and probably less helpful.

We could make it clearer that the displayed values *are* dependent on player traits; I suspect most players don't realise this.

Currently the nutrient values displayed are always per-charge, whereas most of the values displayed in this are increase with charges.  This can be a bit deceptive, and we might want to clarify or change this, but I think that should be a separate PR.

#### Testing
New unit tests, and lots of staring at recipe values.  Found and fixed various unreasonable-looking values.  Some issues were a result of poor recipe design, others were algorithmic issues in my code.  I've fixed all the ones I found, but I would not be surprised to hear that I missed some corner cases.

@DaviBones would appreciate you taking a look at this since you've also been working on & finding bugs in this part of the code recently.

#### Additional context
nutrients-cake
nutrients-woods-soup

### CODE REVIEW

**Comment by KorGgenT** [comment]
as we are trying to deprecate player, i humbly request the scope of player::compute_nutrient_range() be moved to the appropriate class, probably Character here.

**Comment by DaviBones** [comment]
This looks great, I've been looking forward to this change! It is not only good for players, but also will be helpful for debugging/balancing.

The only thing I have to say is that you are not taking account for the `RAW` flag, which is actually a regression in some instances. To see what I mean, spawn some wild vegetables and cook them -- notice that the crafting preview says they will have 25 calories, but they end up with 34 calories. Let me briefly explain how it works:
- If an item has the `RAW` flag, it is worth 25% less calories, **unless** it also has the `COOKED` flag.
- Upon crafting, if `recipe.hot_result()` returns true, then `COOKED` is added to the result and all components via `item::set_flag_recursive`.

It's not trivial to fix, unfortunately. The only quick fix I can think of is to take `comest` as a copy in `player::compute_nutrient_range` so you can recursively add `COOKED` without modifying the original object, but that is an ugly performance hit that doesn't seem worth it at all.

File: src/consumption.cpp [hunk 1]
```diff
@@ -207,6 +213,106 @@ nutrients player::compute_effective_nutrients( const item &comest ) const
...
+{
+    if( !comest.is_comestible() ) {
+        return {};
+    }
+
+    // if item has components, will derive calories from that instead.
+    if( comest.has_flag( "NUTRIENT_OVERRIDE" ) ) {
+        nutrients result = compute_default_effective_nutrients( comest, *this );
+        return { result, result };
+    } else {
```
Comment (BevapDin) [inline src/consumption.cpp]:
```suggestion
    }
```
And remove the indentation of the remaining code.

**Comment by jbytheway** [comment]
> as we are trying to deprecate player, i humbly request the scope of player::compute_nutrient_range() be moved to the appropriate class, probably Character here.

It depends on other functions that are still in `player`.  I'd rather not move those other functions in this same PR, because it will make the changes less clear.  I think it will be easy to move these along with the other nutrient functions when the time comes.

File: src/consumption.cpp (hunk 1 above)
Comment (jbytheway) [reply src/consumption.cpp]: Thanks.  Done.

**Comment by jbytheway** [comment]
@DaviBones I think I found a reasonable solution to the `COOKED` / `RAW` issue.  It seems to be working correctly now.

**Comment by DaviBones** [comment]
Looks great!

As an aside, I struggle to think of an instance where we'll want to use `extra_flags` for anything else, though I also can't think of any meaningful downside to using it instead of a boolean parameter, so I suppose it's better to have it and not need it, than to need it and not have it.

File: src/cata_algo.h [hunk 2]
```diff
@@ -2,10 +2,14 @@
 #ifndef CATA_ALGO_H
 #define CATA_ALGO_H
 
+#include <assert.h>
```
Comment (BevapDin) [inline src/cata_algo.h]:
```suggestion
#include <cassert>
```

"assert.h" is a C header. "cassert" is the matching C++ header.

File: src/stomach.cpp [hunk 3]
```diff
@@ -7,6 +7,60 @@
...
+    auto it = vitamins.find( vit );
+    if( it == vitamins.end() ) {
+        return 0;
+    }
+    return it->second;
+}
+
+bool nutrients::operator==( const nutrients &r ) const
+{
+    if( kcal != r.kcal ) {
```
Comment (BevapDin) [inline src/stomach.cpp]: I do wonder why `return  kcal == r.kcal && vitamins == r.vitamins;` does not work?

**Comment by jbytheway** [comment]
> As an aside, I struggle to think of an instance where we'll want to use `extra_flags` for anything else, though I also can't think of any meaningful downside to using it instead of a boolean parameter, so I suppose it's better to have it and not need it, than to need it and not have it.

Mostly I did it that way for maintenance reasons.  If in the future anyone alters the way these flags work they are likely to grep the code for `"COOKED"`, and I wanted them to find this code when they did that.

File: src/stomach.cpp (hunk 3 above)
Comment (jbytheway) [reply src/stomach.cpp]: Because non-entries in the vitamins map have to be considered equivalent to zero entries.

File: src/cata_algo.h (hunk 2 above)
Comment (jbytheway) [reply src/cata_algo.h]: Done.  If you're watching out for those kind of issues I guess it's time for someone to enable the `modernize-deprecated-headers` check in `.clang-tidy` :).

**Comment by jbytheway** [comment]
I think this is good to go now.
