### PR TITLE
Fix and clean NPC gun code, allow NPCs to shoot again

### LINKED ISSUE #21564: Npcs won't fire guns with bayonets
### Expected Behavior
Npcs shoot guns at range and when enemies get close or they run out of ammo they use the bayonet.
### Actual behavior
they only use the gun as a spear.
### Steps to reproduce the behavior
get a gun, put a bayonet on it, give the gun to companion, have companion fight something.

Npcs only use ranged weapons at point blank due to #19798 
so I'm unsure if under normal conditions they would use bayonets appropriately.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Fixes #21564

NPC aiming code now uses the same "units" as item display one. They are also much less strict in their aiming, so they will actually shoot now.

Other fixes:
* Removed hardcoded "keep 10 moves at end of aiming" behavior. NPCs now aim as well as player.
* NPCs understand that they can hit more distant targets by aiming, won't choose non-combat actions or less important targets if they can aim
* NPCs won't aim at targets they would not want to shoot due to distance
* Fixed a bug with NPCs told to stay in place still wandering off to melee things
* Removed adjustment on burst range confidence. The math behind it was changed, confidence multiplier got inverted for no reason at all, it's bitrotten and untested for all practical intents and purposes. So let's just treat it the same as regular shots, which are working now.
* Renamed `Character::get_best_sight` to `Character::get_fastest_sight` because this is what it actually returns

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
You are breaking fun of training melee to 7 when spawned in the closet together with gun-armed NPC who refuses to shoot at point blank range.

File: src/character.cpp [hunk 1]
```diff
@@ -201,16 +201,13 @@ int Character::effective_dispersion( int dispersion ) const
...
     int sight_speed_modifier = INT_MIN;
     int limit = 0;
-    if( !gun.has_flag( "DISABLE_SIGHTS" ) && effective_dispersion( gun.type->gun->sight_dispersion ) < recoil ) {
-        sight_speed_modifier = 6;
-        limit = effective_dispersion( gun.type->gun->sight_dispersion );
-    } else if ( gun.has_flag( "DISABLE_SIGHTS" ) && effective_dispersion( gun.type->gun->sight_dispersion ) < recoil ) {
-        sight_speed_modifier = 0;
+    if( effective_dispersion( gun.type->gun->sight_dispersion ) < recoil ) {
+        sight_speed_modifier = gun.has_flag( "DISABLE_SIGHTS" ) ? 0 : 6;
         limit = effective_dispersion( gun.type->gun->sight_dispersion );
```
Comment (codemime) [inline src/character.cpp]: This worth extracting to a temp variable for the sake of readability.

File: src/npcmove.cpp [hunk 2]
```diff
@@ -1231,48 +1231,45 @@ double npc::confidence_mult() const
...
             break;
     }
 
     return 1.0f;
 }
 
-int npc::confident_shoot_range( const item &it ) const
+int npc::confident_shoot_range( const item &it, bool at_perfect_aim ) const
 {
+    const int recoil = at_perfect_aim ? get_most_accurate_sight( it ) : recoil_total();
```
Comment (codemime) [inline src/npcmove.cpp]: Boolean flags obscure the meaning. It would be better to pass `recoil` explicitly as an argument.

File: src/character.cpp [hunk 3]
```diff
@@ -227,6 +224,23 @@ std::pair<int, int> Character::get_best_sight( const item &gun, double recoil )
...
+int Character::get_most_accurate_sight( const item &gun ) const
+{
+    if( !gun.is_gun() ) {
+        return 0;
+    }
+
+    int limit = effective_dispersion( gun.type->gun->sight_dispersion );
+    for( const auto e : gun.gunmods() ) {
+        const islot_gunmod &mod = *e->type->gunmod;
+        if( mod.aim_speed >= 0 ) {
```
Comment (codemime) [inline src/character.cpp]: The function above (which somewhat reminds me this one, but stripped of `sight_speed_modifier`) also checks if `mod.sight_dispersion < 0` and skips the `mod` if it's true. Can `limit` become negative here, will it still be meaningful in this case?

Comment (Coolthulhu) [reply src/character.cpp]: I can add that check, but item factory guarantees it anyway:
```
if( ( type->gunmod->sight_dispersion < 0 ) != ( type->gunmod->aim_speed < 0 ) ){
    msg << "gunmod must have both sight_dispersion and aim_speed set or neither of them set" << "\n";
}
```

**Comment by smolbird** [comment]
> You are breaking fun of training melee to 7 when spawned in the closet together with gun-armed NPC who refuses to shoot at point blank range.

Amusing as that mental image is, you usually get ventilated doing that, even prior to these changes. You want to exploit armed NPCs, then do what most people who do that go for: get armor first.

File: src/npcmove.cpp [hunk 4]
```diff
@@ -1231,48 +1234,45 @@ double npc::confidence_mult() const
 
     switch( rules.aim ) {
         case AIM_WHEN_CONVENIENT:
-            return emergency() ? 1.0f : 0.75f;
+            return emergency() ? 1.5f : 1.0f;
```
Comment (BevapDin) [inline src/npcmove.cpp]: Btw. why is this function returning `float` values when it's declared as return `double` values. The `f` at the end of the number is completely pointless, the compiler will effectively remove it (at compile or at runtime).
