### PR TITLE
Make spots craftable in the dark

### LINKED ISSUE #38227: Abstract constructions can't be made in the dark
# Describe the bug

Abstract constructions (like mark firewood source or mark target practice), which serve more a practical purpose rather than being structures, can't be made in the dark.

# Steps To Reproduce

1. Be in darkness.
2. Open construction menu and select mark firewood source.
3. Be notified that you can't construct in the dark.

# Expected behavior

Being able to mark firewood sources in the dark.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12475-g7206b26 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    No Rail Stations [No_Rail_Stations],
    Urban Development [Urban_Development],
    sees-player icon, retrodays [sees_player_retro],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
 ```SUMMARY: Infrastructure "Make spots craftable in the dark"```

#### Purpose of change
Fixes #38227 

#### Describe the solution
Move some checks from construction_menu() to player_can_build()
Add dark_craftable bool to construction
Check for it if in the dark and allow crafting
Make firewood source, target, crafting spot dark craftable

#### Testing
Compile without error
Try to craft in the drak
Get popup "It is too dark to construct right now." for most recipes
Try building firewood
No popup

### CODE REVIEW

**Comment by GhostEcho** [comment]
Bless you

File: src/construction.cpp [hunk 1]
```diff
@@ -738,14 +733,23 @@ bool player_can_build( player &p, const inventory &inv, const std::string &desc
...
 
     if( !p.meets_skill_requirements( con ) ) {
         return false;
     }
-    return con.requirements->can_make_with_inventory( inv, is_crafting_component );
+
+    const bool can_build = con.requirements->can_make_with_inventory( inv, is_crafting_component );
+    if( !can_build ) {
+        popup( _( "You can't build that!" ) );
+    } else if( g->u.fine_detail_vision_mod() > 4 && !con.dark_craftable ) {
```
Comment (BevapDin) [inline src/construction.cpp]: This is referring to the player character, what's the purpose of the `player` parameter when the function is going to use the global player character anyway?

File: src/construction.cpp [hunk 2]
```diff
@@ -738,14 +733,23 @@ bool player_can_build( player &p, const inventory &inv, const std::string &desc
...
     }
 
     if( !p.meets_skill_requirements( con ) ) {
         return false;
     }
-    return con.requirements->can_make_with_inventory( inv, is_crafting_component );
+
+    const bool can_build = con.requirements->can_make_with_inventory( inv, is_crafting_component );
+    if( !can_build ) {
+        popup( _( "You can't build that!" ) );
```
Comment (Qrox) [inline src/construction.cpp]: This is probably the culprit of #38266. `player_can_build` is used for generating the list of available constructions and shouldn't call any UI or input code.
