### PR TITLE
[RDY] fix construction screen crash)

### LINKED ISSUE #18890: Construction Menu Crashes with Right Arrow Key Press after previous construction
0.C-19238-g7dd7a8a compiled using git clone and pull on Ubuntu 16.04

When opening the construction menu and pressing the right arrow key, the game crashes. I can use the number pad to scroll through the different options, but the arrow key crashes my game.

The error message seems to read,

>/usr/include/c++/5/debug/vector:409:error: attempt to subscript container with out-of-bounds index 38, but container only holds 38 elements.

>Objects involved in the operation: sequence "this" @ 0x0x7ffd9866e140 {type = NSt7_debug6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS6_EEE;}

>Aborted (core dumped)

Just to note, I transcribed that from my screen, so there might be some typos and parts of the error might be missing, cause my terminal is all wonky due to the crash.

So far, it crashes when I press the right arrow key after having made a construction.
It crashed when I tried to use the search function to find crates typed: "cra"

### PR DESCRIPTION
**Pull request by epsilon-phase**
Also made the hotkeys print all the time, which seems like a good idea
Fixes #18890

### CODE REVIEW

File: src/construction.cpp [hunk 1]
```diff
@@ -331,23 +331,26 @@ void construction_menu()
...
-
+            // print the hotkeys regardless of if there are constructions
+            trim_and_print( w_con, w_height - 5, ( w_list_width + w_list_x0 + 2 ),
+                       available_window_width, c_white,
+                       _("Press %s or %s to tab."), 
+                       ctxt.get_desc("LEFT").c_str(),
+                       ctxt.get_desc("RIGHT").c_str() );
+            mvwprintz( w_con, w_height - 4, ( w_list_width + w_list_x0 + 2 ), c_white,
+                       _( "Press %s to search." ), ctxt.get_desc( "FILTER" ).c_str() );
+            // Print instructions for toggling recipe hiding.
```
Comment (illi-kun) [inline src/construction.cpp]: this comment duplicates the content of string (so it's pretty useless).

Comment (jaked122) [inline src/construction.cpp]: That's not mine actually, it was where this general section of code used to live.

I'll get rid of it anyway.

Comment (illi-kun) [inline src/construction.cpp]: Yeah, I know that wasn't introduced by you, I'm just saying something I missed previously.
Thanks for the quick fix, BTW.
