### PR TITLE
Restore minimap enemy blink/fade functionality

### LINKED ISSUE #30730: Minimap icons for enemies cease blinking unless a key input is detected
# Describe the bug

After upgrading to Build 9020, minimap icons for enemies cease to blink unless you press a key.

Downgrading to Build 9016 appears to resolve the issue.

# Steps To Reproduce

1. View minimap behavior on Build 9016 or prior. Enemy icons blink all the time.
2. Upgrade to Build 9020, the blinking will cease unless you hit a key.

# Screenshots

Here are the relevant Menu Settings, although I do not know if its limited to Solid drawing mode as I forgot to test before downgrading.

Adjusting Blink Speed to 1 will better illustrate the issue.

Untitled

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3275-g29e897c (This is the downgraded Build 9016)
- Graphics Version: Tiles
- Mods loaded: 
    Dark Days Ahead [dda],
    Urban Development [Urban_Development],
    More Locations [more_locations],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Filthy Clothing [filthy_morale],
    Classes and Scenarios Mod [more_classes_scenarios],
    StatsThroughSkills_2x [StatsThroughSkills_2x],
    More Survival Tools [More_Survival_Tools],
    Makeshift Items Mod [makeshift],
    Extended Realistic Guns [realguns],
    No Fictional Guns [no_rivtech_guns],
    Mutant NPCs [mutant_npcs],
    Mining Mod [Mining_Mod],
    NPC traits [npc_traits],
    [DP_MOD] Indicators: Chesthole [DP_AMAZING_CHEST_INDICATORS],
    [DP_MOD] No Highlight [DP_No_Highlight],
    Hydroponics [hydroponics],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots]

### PR DESCRIPTION
**Pull request by esotericist**
#### Summary
`SUMMARY: Bugfixes "Restore minimap enemy blink/fade functionality"`

#### Purpose of change
Pull requests #30713 and #30725 substantially reduced the CPU consumption while the game was mostly idle, but at the consequence of no longer updating the pixel minimap in many cases where the user may well expect it to do so.

Fixes #30730 

#### Describe the solution
Reverted both #30713 and #30725 while implementing a framework to ensure panels are only redrawn when one of:
*  the current turn has incremented
*  the panel has `always_draw` set to `true` in its instantiation in `panels.cpp`
*  the `draw_panels()` invocation passes `true` for the `force_draw` parameter

Right now only the pixel minimap has `always_draw` in its instantiation, but this could be added to others if it's ever necessary.

Also updated several `g->draw_panels()` calls to `g->draw_panels( true )` (and removed a couple of calls to `draw_panels` that were provably not useful)

#### Describe alternatives you've considered
Longer term it would be much more constructive to keep track of "dirty" bits for specific windows, to know whether or not any part of window has actually been overwritten by another window, and initiating redraw only on windows that either have a data change or have been occluded and now need to be redrawn.

I also considered inverting the meaning of the boolean that gets passed to `game::draw_panels()` to be an "optional update" parameter, but I felt this would be more obvious and less intuitive than using that `true` argument to say "no for really reals draw the damn panels" as I did here.

#### Additional context
It's possible I might have missed converting a `g->draw_panels()` to `g->draw_panels( true )` somewhere that is actually necessary; if there's a report of the sidebar not updating after a UI element is closed, there's a chance this is the cause.

Also, the animation loop isn't active while in most "menu" states (look_around, aiming a weapon, etc) so the minimap will not update under those circumstances. This is possibly unexpected, but neither a reversion nor related to the recent changes.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -7201,9 +7210,8 @@ game::vmenu_ret game::list_items( const std::vector<map_item_stack> &item_list )
         iScrollPos = 0;
 
         if( action == "HELP_KEYBINDINGS" ) {
-            draw_ter();
+            game::draw_ter();
```
Comment (ifreund) [inline src/game.cpp]: Minor, but i wouldn't mind keeping this style fix here and just below

File: src/action.cpp [hunk 2]
```diff
@@ -1043,6 +1043,8 @@ cata::optional<tripoint> choose_adjacent_highlight( const std::string &message,
     }
     if( highlighted ) {
         wrefresh( g->w_terrain );
+        // prevent hiding panels when examining an object
```
Comment (ifreund) [inline src/action.cpp]: This comment is no longer accurate, and I'm fairly certain there's no need to redraw here either.

Comment (esotericist) [reply src/action.cpp]: You're right. I removed a couple of other provably-unnecessary draw_panels calls elsewhere, this is demonstrably useless too since it can't occlude the sidebar

File: src/game.cpp (hunk 1 above)
Comment (esotericist) [reply src/game.cpp]: I didn't realize this was part of your earlier PR. I'll fix that.

**Comment by esotericist** [comment]
> Looks good. I still don't like how many places we're calling `draw_panels()` (I _think_ all the ones I removed were strictly unnecessary) but now that you've made it low-cost it shouldn't really matter too much.

When I was restoring some of those, it was before I knew the animation loop is frozen while in a menu. Some of those are arguably unnecessary as long as the animation loop can't run, although I personally think the minimap animation should still be running while in `look_around()`, most *especially* from a `X` peek.

So I'd like to fix that if it can be done in a reasonable fashion.
 
> It would be nice to have some system that doesn't require manually calling draw calls all over the codebase, but I don't really know how that would work and that's definitely out of scope for this pr.

That's one of my long term objectives, because this really is silly.

Unfortunately we still need things to work some kind of correct while we're aiming for that. :D

**Comment by esotericist** [comment]
as a side note: I used a profiler and verified that `draw_panels()` is basically free as long as the animation loop is not playing. Like, it actually doesn't show up in the summary of "things that used CPU", it's that inconsequential.
