### PR TITLE
Camp Bugfixes again

### LINKED ISSUE #31200: Camp extensions still broken, just slightly differently
#31183 
#31141
#31147

# Describe the bug

When an extension is made by surveying it's tab is inaccessible in the menu after saving and reloading the tab is accessible but selecting an option just closes the menu

# Steps To Reproduce

1. Create a Faction Camp
2. Survey an Extension
3. Attempt to access extension tab on the bulletin board menu
4. Save and Reload
5. Open the now accessible extension Tab and select any option

# Expected behavior

Extension tabs should be accessible without saving and reloading, and after saving and reloading options should do something besides simply closing the menu

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-4012-g0121072 [32-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

attached are three saves one before sending an NPC to survey one with them ready to be recovered at the end of the survey and one after the extension has been placed

[Camp test 3 saves at different stages.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3264348/Camp.test.3.saves.at.different.stages.zip)

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Fix bugged camp expansion missions"```

#### Purpose of change
Fixes #31200 

#### Describe the solution
Fixes the bugs, properly this time.
updates provides when expansion is first parsed, instead of just on load.
Typo in string comparison when checking which NPCs were out on the mission meant that you would not be able to recall them.
Substring checking and size checking was off by a few characters, so checking the mission id never prompted to start the mission.
And a missing zero in the substr range, meant that they couldnt be recalled even when the menu "knew" that you had an NPC to recall.
Also, the blacksmith upgrades tried to set a provides for a fake forge and fake charcoal kiln, but no such items were defind in the JSON so I've added them.

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

### CODE REVIEW

File: src/basecamp.cpp [hunk 1]
```diff
@@ -106,13 +106,15 @@ std::string basecamp::board_name() const
...
 // This is legacy support for existing camps; future camps don't use cur_level at all
-static expansion_data parse_expansion( const std::string &terrain, const tripoint &new_pos )
+expansion_data basecamp::parse_expansion( const std::string &terrain, const tripoint &new_pos )
 {
     expansion_data e;
     int last_bar = terrain.find_last_of( '_' );
     e.type = terrain.substr( base_camps::prefix_len, last_bar - base_camps::prefix_len );
     e.cur_level = std::stoi( terrain.substr( last_bar + 1 ) );
     e.pos = new_pos;
+    const std::string &bldg = base_camps::faction_encode_abs( e, e.cur_level );
```
Comment (mlangsdorf) [inline src/basecamp.cpp]: This only updates the provides for the most recent upgrade.  It's probably simpler to invalidate the camp resources and regenerate them:
```
        resources_updated = false;
        reset_camp_resources( by_radio );
```
though then you have to pass by_radio to parse_expansions =/

**Comment by davidpwbrown** [comment]
jenkins rebuild
