### PR TITLE
Fix erroneous mapgen monster names in non-English games

### LINKED ISSUE #71634: Error in the name of the mobs. Mob_name:none
### Describe the bug

While traveling, came across a strange display of the monster's name. The name is displayed with the ending ":нет". See screenshot.

"нет" means no, maybe none

### Attach save file

[Пис-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14220232/-trimmed.tar.gz)

### Steps to reproduce

N/A

### Expected behavior

N/A

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: 2013584 [64-bit]
- Graphics Version: Tiles
- Game Language: <s>Системный язык []</s> Ru
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    Характеристики за убийства [stats_through_kills]
]

### Additional context

Language switch, turns "оса: нет" to "wasp: нет"

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
Bugfixes "Fix erroneous mapgen monster names in non-English games"

#### Purpose of change
* Fix #71634

#### Describe the solution
Following the analysis in https://github.com/CleverRaven/Cataclysm-DDA/issues/71634#issuecomment-1935661047, use `std::optional<std::string>` instead of a hardcoded `"NONE"` value to signify the absence of a custom monster name.

#### Testing
1. Change game language to Chinese or Russian
2. Spawn an Island Prison in debug menu
3. Custom monsters like "The Chief", "The Doctor" have their custom names correct
4. General monsters like zombie cops do not have custom names as expected

### CODE REVIEW

File: src/mapgen.cpp [hunk 1]
```diff
@@ -2429,18 +2436,21 @@ class jmapgen_monster : public jmapgen_piece
...
+                    chosen_name.emplace( SNIPPET.expand( "<female_given_name>" ) );
                 } else if( random_name_str == "male" ) {
-                    chosen_name = SNIPPET.expand( "<male_given_name>" );
+                    chosen_name.emplace( SNIPPET.expand( "<male_given_name>" ) );
                 } else if( random_name_str == "random" ) {
-                    chosen_name = SNIPPET.expand( "<given_name>" );
+                    chosen_name.emplace( SNIPPET.expand( "<given_name>" ) );
                 } else if( random_name_str == "snippet" ) {
-                    chosen_name = SNIPPET.expand( name.translated() );
+                    chosen_name.emplace( SNIPPET.expand( random_name_snippet_id ) );
```
Comment (Qrox) [inline src/mapgen.cpp:2448]: Previously this allowed strings with snippet tags be used (such as `Mr. <given_name>`), and the string extraction script also extracts this string, so I think we should keep this behavior.

**Comment by IdleSol** [comment]
It's not working

test


- OS: Windows
    - OS Version: 10.0.18362 (21H1)
- Game Version: fa90782 [64-bit] cdda-windows-tiles-x64-msvc-2024-02-19-1617
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(90,5%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth]
]

**Comment by Wishbringer** [comment]
This generates `.map` files with `null` values rather than `"none"` in them causing error messages, expected string found null, thus bricking save games (compiled with LOCALIZE=0).

**Comment by IdleSol** [comment]
#71857

File: src/submap.h [hunk 2]
```diff
@@ -43,11 +43,11 @@ struct spawn_point {
     int faction_id;
     int mission_id;
     bool friendly;
-    std::string name;
+    std::optional<std::string> name;
     spawn_data data;
     explicit spawn_point( const mtype_id &T = mtype_id::NULL_ID(), int C = 0, point P = point_zero,
                           int FAC = -1, int MIS = -1, bool F = false,
-                          const std::string &N = "NONE", const spawn_data &SD = spawn_data() ) :
+                          const std::optional<std::string> &N = std::nullopt, const spawn_data &SD = spawn_data() ) :
```
Comment (Inglonias) [inline src/submap.h:50]: I think this line is what's breaking save files.
