### PR TITLE
Fix bugs with bikeracks by making racked parts unavailable

### LINKED ISSUE #26365: Boats and bike racks bug
**Describe the bug**  
Loaded a canoe on my bike rack but now the car thinks it is a boat.  Claims it is too leaky to drive.  

**To Reproduce**  
1. Try to load a valid boat onto a bike rack.
2. Attempt to drive away with your multi-terrain RV 

**Expected behavior**  
I'd like to haul boats, especially since you can find them in the new riverside buildings.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version 0.C-33466-g1948a66
 - Graphics version tiles
 - Mods loaded
"dda",
"filthy_morale",
"no_npc_food",
"novitamins",
"bio_mod",
"makeshift",
"Medieval_Stuff",
"More_Survival_Tools",
"WHALEYCASSETTE",
"mutant_npcs",
"npc_traits",
"more_locations",
"more_buildings",
"Experimental-Z-Level",
"boats",
"deoxymod",
"blazemod",
"Tanks",
"hacktheplanet",
"jury_rigged_robots",
"Arcana",
"FujiStruct",
"No_Fungi",
"StatsThroughSkills"

### LINKED ISSUE #26366: Racked vehicle and NPC
**Describe the bug**  
NPC wants to sit in the racked vehicle instead of the car.  (Haven't assigned them a seat yet).

**To Reproduce**  
1. Attach a vehicle with the bike rack and have NPC companion (I was using a canoe)
2. See where they sit.

**Expected behavior**  
NPC recognizes valid seating.

**Screenshots**  
image

**Versions and configuration(please complete the following information):**

    OS:Windows 10
    Game Version: O.C-33466-g1948a66
    Graphics version Tiles
    Mods loaded:
    "dda",
    "filthy_morale",
    "no_npc_food",
    "novitamins",
    "bio_mod",
    "makeshift",
    "Medieval_Stuff",
    "More_Survival_Tools",
    "WHALEYCASSETTE",
    "mutant_npcs",
    "npc_traits",
    "more_locations",
    "more_buildings",
    "Experimental-Z-Level",
    "boats",
    "deoxymod",
    "blazemod",
    "Tanks",
    "hacktheplanet",
    "jury_rigged_robots",
    "Arcana",
    "FujiStruct",
    "No_Fungi",
    "StatsThroughSkills"

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "Fix bugs with bikeracks by making racked parts unavailable"```

#### Purpose of change
Fixes #26366
Fixes #26365

Most vehicle parts on a bike rack are supposed to be unavailable to the carrying vehicle.  I went back
through the code and added some checks to some parts that were missing them, and then cleaned up
some code references to remove duplicate or redundant code.

#### Describe the solution
The existing carried flag is supposed to keep parts on a bike rack from affecting the parent vehicle,
but it wasn't be honored in a lot of cases.  Adding checks for it resolves those issues.

### CODE REVIEW

**Comment by BevapDin** [comment]
If they are not available (whatever that means) why are they even there in `vehicle::parts`? The could go into a separate member of `vehicle_part` or something similar. Adding a check for availability to every piece of code that needs it (how is that even determined) is time-consuming and likely never complete.

**Comment by kevingranade** [comment]
The issue is they need to be present for *some* calculations, but not *all*.
But now that I think about it the list of things they contribute to is probably far smaller than the list of things they do not.

Count for:
Weight, center of mass, aerodynamism, serialization, collisions, vehicle splitting, taking damage.
Do not count for:
Power production/consumption, wheel count, accessories, turrets, repair, fuel supply.

**Comment by mlangsdorf** [comment]
Bike racks are a feature that are in the game and seem to be well-liked by the player base.  They work by merging two vehicle's part vectors and flagging one of the vehicle's parts as being carried.  Carried parts are also unavailable and don't count for turrets, seats, engines, wheels/boat boards, power production, etc. and shouldn't count for repair.

That's the existing design.  I'm open to other ways to implement it, but I don't want to remove an existing and useful feature.  How would you prefer I do this?

**Comment by kevingranade** [comment]
I think the best way to describe it is currently you're blacklisting sections of the code that shouldn't interact with racked vehicle components, but it'll be simpler and more robust to whitelist sections of the code that should interact with them.

And implementation-wise, consider storing the parts seperately instead of just flagging them, though I think that might be something to work toward instead of doing it all at once.

**Comment by BevapDin** [comment]
I suggest storing the carried parts as members of `vehicle_part`. All code that needs to access it, can do so. But code that does not need it, will automatically skip it. It would also be much clear and much easier regarding new code.

We already have the status flags "enabled", "broken" and now "available", that gives 8 configurations to consider.

**Comment by mlangsdorf** [comment]
I don't understand how storing a carried vehicle as part of a vehicle_part would work.

Currently, we have a vehicle with set of bike racks and a single tile wide vehicle, like this:
```
/=\
|#R o
|#R ^
|#R o
+=+
```
after putting the single tile wide vehicle on the racks, we have this as a single vehicle.
```
/=\
|#Ro
|#R^
|#Ro
+=+
```
All of the vehicle_parts in the bike's parts vector are now in the carrier vehicle's parts vector, but the bike's tiles are still present on the map, can be damaged, etc.

I don't see how storing the bike's parts in the bike rack's vehicle_parts would make it easier or clearer to have the current code access them.  It seems like it would make the collision code, for instance, much more complicated.

**Comment by kevingranade** [comment]
I agree that storing 5he parts inside other parts sounds problemstic, for the sake of qrgument though you could syn5hesize a "rack" part at that location to use as storage.

I'd prefer to split the racked parts onto their own vector parallel to vehicle::parts, then they become totally invisible to any code that doesn't seek them out.  This IMO is secondary to tge "whitelist" vs "blacklist" issue though, and can be adressed later.

**Comment by BevapDin** [comment]
I misread how carried parts are stored. Yes, they must be separate, normal `vehicle_part` instances. Ignore that post.

But why do we need to ignore them (via the `is_available` check) in so many cases? I get wheels and traction (output of engines), but why make them a separate electric circuit? Every other vehicle part is connected to the main power grid of the vehicle. Even standard wooden frames contain power cables (or how else is electricity handled there)?


And now we have a `get_parts` with *three* boolean parameters. What does `get_parts(..., true, false, true)` mean? How is it different from `get_parts(..., false, true, true)`? Which of the three booleans is `unbroken`, `avail` and ... what was the other thing we may check for?

**Comment by mlangsdorf** [comment]
Apparently I forgot to post my comment on this.

There's a hierarchy of states:
enabled parts can't be broken or not available
available parts can't be broken
any part can be broken

Instead of passing true, false, true, would it be better to pass VPS_ENABLED | VPS_AVAILABLE and then vehicle_part_with_feature can sort that out to bool unbroken_, bool enabled_, and bool available_ internally?

**Comment by BevapDin** [comment]
Flags would be better than multiple booleans, but even better would be dedicated function names because those parameters are always compile-time constants.

**Comment by mlangsdorf** [comment]
The vehicle_part_with_feature_range constructor is the problem child here and it probably shouldn't ever be called directly.  Instead, people should call
get_enabled_parts() - returns enabled and available parts
get_available_parts() - returns available and non-broken parts
get_parts_including_broken() - returns all parts, including unavailable or broken parts

but that still leaves the question of what do to with vehicle_part_with_feature_range().  Pass the current boolean arguments as flags or add another boolean or something else?

**Comment by BevapDin** [comment]
> Pass the current boolean arguments as flags or add another boolean or something else?

An enumeration would make this even simpler:
```C++
required_part_flags_enum { unbroken = 1 >> 0, enabled = 1 >> 1, available 1 >> 2 };
bool matches( const vehicle_part &p, required_part_flags_enum e) {
    // logic: when unbroken required, check for p.is_broken() and so on
}
```
Store just the `required_part_flags_enum` in the `vehicle_part_ranges` and change `contained` to call `matches` plus its own necessary checks (e.g. feature).
Add wrapper functions as you mentioned that combine the necessary enumeration values and pass them to the ranges.

This can be extended easily: add a new enumeration value, add a function that uses it to pass to the range objects and add a check for it in `matches`.

**Comment by mlangsdorf** [comment]
I figured there was some clever C++ way to do that.  Okay, I'll code that up tomorrow.

**Comment by mlangsdorf** [comment]
Pushed the new, enum based version of get_parts(), which I like a lot more because it's much easier to read and comprehend get_parts( part_status_flag::working ) than get_parts( false, true ).

The travel distance in the vehicle efficiency case dropped by about 15% across the board.  I'm not sure what's up with that.  I reviewed everything twice but couldn't see a good reason for the change beyond using the wheelcache instead of recalculating the wheels from get_parts( VPF_WHEEL ) and I can't see why that would change the results.  I'm not super concerned, because those values are going to change when the vehicle speed reworks goes through.  A careful review by someone else may find the culprit.

Please review before merging!

**Comment by kevingranade** [comment]
> Please review before merging!

Pffff why start now?

File: src/vpart_range.h [hunk 1]
```diff
@@ -35,7 +36,8 @@ class vehicle_part_iterator
             return range_.get();
         }
         void skip_to_next_valid( size_t i ) {
-            while( i < range().part_count() && !range().contained( i ) ) {
+            while( i < range().part_count() &&
+                   !range().matches( i, static_cast<part_status_flag>( 0 ) ) ) {
```
Comment (BevapDin) [inline src/vpart_range.h]: Why are you using a fixed value 0 here? If the parameter is always the same, why have it at all? The ranges should store their own `part_status_flag` value (and already do so when needed).

File: src/vpart_range.h [hunk 2]
```diff
@@ -161,15 +163,14 @@ class vehicle_part_with_feature_range : public
 {
     private:
         feature_type feature_;
-        bool unbroken_;
-        bool enabled_;
+        part_status_flag required_;
```
Comment (BevapDin) [inline src/vpart_range.h]: This is initialized but never read.

File: src/vehicle.h [hunk 3]
```diff
@@ -734,24 +741,32 @@ class vehicle
         vehicle_part_range get_parts() const;
         /**
          * Yields a range of parts of this vehicle that each have the given feature
-         * and are not broken. Removed parts are also excluded. The enabled status
-         * of the part is ignored.
+         * and are available: not broken, removed, or part of a carried vehicle.
+         * The enabled status * of the part is ignored.
```
Comment (BevapDin) [inline src/vehicle.h]: Random `*` in sentence.

File: src/vehicle.h [hunk 4]
```diff
@@ -734,24 +741,32 @@ class vehicle
...
+        vehicle_part_with_feature_range<vpart_bitflags> get_parts_including_carried(
             vpart_bitflags f ) const;
         /**@}*/
         /**
-         * Like @ref get_parts, but only yield enabled parts. They must still be unbroken.
+         * Like @ref get_avail_parts, but also yields broken parts and parts on carried vehicles.
+         */
+        /**@{*/
+        vehicle_part_with_feature_range<std::string> get_all_parts( std::string feature ) const;
+        vehicle_part_with_feature_range<vpart_bitflags> get_all_parts( vpart_bitflags f ) const;
```
Comment (BevapDin) [inline src/vehicle.h]: Out of curiosity what is the difference between `get_parts` and `get_all_parts`. Judging by the name, the former seems to yield less parts than the later (`get_parts` returns "not all part", if it did, why would it be named different from `get_all_parts`).

File: src/vehicle.cpp [hunk 5]
```diff
@@ -4758,21 +4787,25 @@ vehicle_part_range vehicle::get_parts() const
...
+        const part_status_flag e ) const
 {
     const vehicle_part &vp = this->vehicle().parts[part];
     return vp.info().has_flag( feature_ ) &&
            !vp.removed &&
-           ( !unbroken_ || !vp.is_broken() ) &&
-           ( !enabled_ || vp.enabled );
+           ( !( e && part_status_flag::working ) || !vp.is_broken() ) &&
+           ( !( e && part_status_flag::available ) || vp.is_available() ) &&
+           ( !( e && part_status_flag::enabled ) || vp.enabled );
```
Comment (BevapDin) [inline src/vehicle.cpp]: The `&&` is boolean-and, the condition is equivalent `e != 0 and part_status_flag::working != 0`, which is equivalent to `e != 0` (as the second operand is always `true`). Did you mean `&` (arithmetic operator)?

Comment (mlangsdorf) [reply src/vehicle.cpp]: Yes.

File: src/vehicle.h [hunk 6]
```diff
@@ -734,24 +741,32 @@ class vehicle
...
          */
         /**@{*/
-        vehicle_part_with_feature_range<std::string> get_parts( std::string feature ) const;
-        vehicle_part_with_feature_range<vpart_bitflags> get_parts( vpart_bitflags f ) const;
+        vehicle_part_with_feature_range<std::string> get_avail_parts( std::string feature ) const;
+        vehicle_part_with_feature_range<vpart_bitflags> get_avail_parts( vpart_bitflags f ) const;
         /**@}*/
         /**
-         * Like @ref get_parts, but also yields broken parts.
+         * Like @ref get_avail_parts, but also yields parts on carried vehicles.
```
Comment (BevapDin) [inline src/vehicle.h]: These functions do not call each other (`get_parts_including_carried` does not call `get_avail_parts`), yet they reference each other. This can easily go wrong: if someone changes `get_avail_parts` (but not the other function), they will probably net check what other documentation referees to it. So the current comment ("like `get_avail_parts`") may not be correct anymore.

Beside that it gets a bit difficult to understand: `get_avail_parts` lists a bunch of attributes that will exclude the part, and the function comments below list a bunch of attributes that suddenly include that part again.

Ideally each function would simply list what attributes are required.

File: src/vehicle.cpp [hunk 7]
```diff
@@ -2137,44 +2142,65 @@ int vehicle::next_part_to_open( int p, bool outside ) const
...
 }
 
-vehicle_part_with_feature_range<std::string> vehicle::get_parts( std::string feature ) const
+vehicle_part_with_feature_range<std::string> vehicle::get_avail_parts( std::string feature ) const
 {
     return vehicle_part_with_feature_range<std::string>( const_cast<vehicle &>( *this ),
-            std::move( feature ), true, false );
+            std::move( feature ),
+            static_cast<part_status_flag>( part_status_flag::working |
+                                           part_status_flag::available ) );
```
[the remark this answers is not in the document]
Comment (mlangsdorf) [reply src/vehicle.cpp]: Fixed I think.

File: src/vehicle.h [hunk 8]
```diff
@@ -49,6 +49,13 @@ constexpr int SCATTER_DISTANCE = 3;
 //adjust this to balance collision damage
 constexpr int k_mvel = 200;
 
+enum part_status_flag : int {
```
[the remark this answers is not in the document]
Comment (mlangsdorf) [reply src/vehicle.h]: Not sure that's true, but fixed.

File: src/vpart_range.h (hunk 1 above)
Comment (mlangsdorf) [reply src/vpart_range.h]: Not sure what I was thinking here.
Revised.

File: src/vpart_range.h (hunk 2 above)
Comment (mlangsdorf) [reply src/vpart_range.h]: Fixed.

File: src/vehicle.h (hunk 3 above)
Comment (mlangsdorf) [reply src/vehicle.h]: Fixed.

File: src/vehicle.h (hunk 4 above)
Comment (mlangsdorf) [reply src/vehicle.h]: Renamed to get_any_parts for "gets any part with a feature", get_all_parts for "gets all the parts on a vehicle" and get_parts_at for "get parts at pos."

File: src/vehicle.cpp (hunk 5 above)
Comment (mlangsdorf) [reply src/vehicle.cpp]: Fixed.

File: src/vehicle.h (hunk 6 above)
Comment (mlangsdorf) [reply src/vehicle.h]: I was copying the style of the docs but it was bad as you pointed out.

Fixed.

**Comment by zombiethoughts** [comment]
I was searching for a problem I was having and this was the closest I could find. It looks like the attached vehicle should not be repairable while attached?

I noticed after attaching a vehicle, it had damage after inspecting the vehicle it was attached to. I repaired the attached vehicle and then could no longer 'R'emove the vehicle from the rack. I ended up removing the parts and rebuilding the attached vehicle.

Wasn't sure if this is the same issue, but it seems likely?

**Comment by mlangsdorf** [comment]
It's a different but related issue.  Posting in a closed PR is generally not useful because I don't review them - it's better to open a new issue.
