### PR TITLE
Fix endless activation loop when starving

### LINKED ISSUE #41441: reflex Photophore spams log every second
# Describe the bug

The mutation Reflex Photophore spams log every second withte 2 followign messages
You feel like using Reflex Photophore will kill you
You're so happy your glowing

# Steps To Reproduce

1. gain the mutation 
2. wait or pass time

# Expected behavior

chat should not be spammed over and over again

# Screenshots

cataclysm-tiles_WSVtl6r01u

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3371-g99aa7cb [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    My Sweet Cataclysm [my_sweet_cataclysm],
    Mythical Martial Arts [MMA],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

SUMMARY: None

#### Purpose of change
When starving reflex photophore would enter and endless loop of trying to activate and failing because the player doesn't have enough calories.

Fixes #41441 
#### Describe the solution

Check if the mutation can be powered before checking the trigger conditions

#### Testing
Get mutation
Get to starving
No spam message

### CODE REVIEW

File: src/mutation.cpp [hunk 1]
```diff
@@ -182,9 +182,19 @@ void Character::switch_mutations( const trait_id &switched, const trait_id &targ
...
 }
 
+bool Character::can_power_mutation( const trait_id &mut )
+{
+    if( ( mut->hunger && get_kcal_percent() < 0.5f ) || ( mut->thirst &&
+            get_thirst() >= 260 ) ||
+        ( mut->fatigue && get_fatigue() >= fatigue_levels::EXHAUSTED ) ) {
+        return false;
+    }
+    return  true;
```
Comment (anothersimulacrum) [inline src/mutation.cpp:192]: Slight style thing and/or clang-tidy might complain about the `if(x) { return false; } return true;` structure.
```suggestion
    bool hunger = mut->hunger && get_kcal_percent() < 0.5f;
    bool thirst = mut->thirst && get_thirst() >= 260;
    bool fatigue = mut->fatigue && get_fatigue() >= fatigue_levels::EXHAUSTED;

    return  hunger && fatigue && thirst;
```
