### PR TITLE
Prevent auto drive seg_fault

### LINKED ISSUE #47094: Segmentation fault
# Describe the bug

The game crashes whenever I try to load the save. I crashed after using the auto-travel function and now cannot load saves without the game crashing before loading in. Fresh install didn't help.

# Steps To Reproduce

Whenever loading the save

# Expected behavior

I thought the game would just load normally

# Screenshots

# Versions and configuration

Dark Days Ahead, BlazeIndustries, CRT_Expansion, Graphical_Overmap, speedydex, StatsThroughSkills

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5890946/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5890951/debug.log)
[save file](https://drive.google.com/file/d/1WTnrtfJxyGdbExAI6jlhDddRNBdyOnzj/view?usp=sharing)

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fixes #47094
Prevents segfault from auto driving

### CODE REVIEW

File: src/activity_actor.cpp [hunk 1]
```diff
@@ -355,7 +355,7 @@ void autodrive_activity_actor::start( player_activity &act, Character &who )
 
 void autodrive_activity_actor::do_turn( player_activity &act, Character &who )
 {
-    if( who.in_vehicle && who.controlling_vehicle && player_vehicle->is_autodriving &&
+    if( who.in_vehicle && who.controlling_vehicle && player_vehicle && player_vehicle->is_autodriving &&
```
Comment (BrettDong) [inline src/activity_actor.cpp:358]: There is another dereference of `player_vehicle` in line 369 below.

**Comment by BrettDong** [comment]
What happened to cause `player_vehicle` becoming `nullptr` in the first place?

File: src/activity_actor.cpp (hunk 1 above)
Comment (Ramza13) [reply src/activity_actor.cpp:358]: Yes but it doesn't matter because if its null then the check on 358 catches it and it goes to the else on 365 where it returns before hitting that.

**Comment by Ramza13** [comment]
> 
> 
> What happened to cause `player_vehicle` becoming `nullptr` in the first place?

No idea, in the linked bug I've asked the finder, my guess is maybe some sort of save/load issue but thats just a guess.

**Comment by bunnybananza** [comment]
I'm not quite sure how to apply the fix. Very confused.

**Comment by anothersimulacrum** [comment]
Wait until this PR is merged and a build with it is released.

**Review by BrettDong — APPROVED** [review]
