### PR TITLE
Fix vehicle dismantling crash

### LINKED ISSUE #19003: Completely dismantling vehicles (pre-existing or self-made) causes CTD.
If I destroy the last part of a vehicle the game doesn't crash.

<a href='https://postimg.org/image/3t1zmrmhp/' target='_blank'>Removing the last frame of a Hatchback CTD<br />

<a href='https://postimg.org/image/u3wzyza8t/' target='_blank'>Completely dismantling pre-existing vehicles cau<br />

### LINKED ISSUE #19045: Activities that are of ACT_NULL type are still "true"
* Spawn vehicle
* Dismantle it completely
* `activity_handlers::vehicle_finish` will call `veh_interact::complete_vehicle()`, which invokes `g->u.activity.set_to_null()`
* `act->type` is now `activity_id( NULL_ID )`
* `!act` is still `false`
* Game crashes

Pinging @sethsimon who reworked activities.

### PR DESCRIPTION
**Pull request by sethsimon**
Sorry for the bug. Fixes #19003. Fixes #19045.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -1287,7 +1287,7 @@ void activity_handlers::vehicle_finish( player_activity *act, player *pl )
     // complete_vehicle set activity type to NULL if the vehicle
     // was completely dismantled, otherwise the vehicle still exist and
     // is to be examined again.
-    if( !act ) {
+    if( !*act ) {
```
Comment (mugling) [inline src/activity_handlers.cpp]: Perhaps you should write this as `!act.is_null()` for greater clarity?

Comment (sethsimon) [inline src/activity_handlers.cpp]: It does look a little strange, so I don't see why not.
