### PR TITLE
Fix NPC under operation teleporting away

### LINKED ISSUE #32497: Freed cyborg moved while under anesthetic coma
# Describe the bug

After freeing and recruiting a prototype cyborg in a lab, i started to remove some CMB's from my new follower. I then went on to explore a bit while the coma wears off.

When i came back i discovered the follower was gone. I went to the map and saw the follower had left the lab and moved north. Chasing after the follower in a car i chased them down and found them in the middle of nowhere, still sleeping in a coma.

# Steps To Reproduce

1. put npc in autodoc induced coma
2. walk away
3. watch them move through the out of reality bubble movement.

# Expected behavior

The npc should stay put while in a coma

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-5622-g3d4a952 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Stats Through Kills [stats_through_kills],
    StatsThroughSkills [StatsThroughSkills],
    Prevent Zombie Revivication [no_reviving_zombies],
    Classes and Scenarios Mod [more_classes_scenarios],
    No Fungal Monsters [No_Fungi]
]

# Additional context

Save
https://mega.nz/#!JUk2XIDA!0ZZF1_APgzSgCXtkItZ3eOozJpPYs8krvqt7hl-Eq7g

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Bugfixes "Fix NPC under operation teleporting away"```

#### Purpose of change
Fix NPC under operation teleporting away
Fixes #32497 

#### Describe the solution
Check for activity instead of effect, the effect check was falling through and the NPC was able to plan its longteerm goal and move away once out of the reality bubble. Thanks @davidpwbrown  for figuring it out.

### CODE REVIEW

**Comment by Fris0uman** [comment]
jenkins rebuild

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -2985,7 +2985,7 @@ void activity_handlers::operation_do_turn( player_activity *act, player *p )
     const time_duration half_op_duration = difficulty * 10_minutes;
     time_duration time_left = time_duration::from_turns( act->moves_left / 100 ) ;
 
-    if( autodoc ) {
+    if( autodoc && !( p->posx() < 0 || p->posy() < 0 || p->posx() > 121 || p->posy() > 121 ) ) {
```
Comment (BevapDin) [inline src/activity_handlers.cpp]: If you want to check whether the position of the NPC is within the reality bubble, use this:
```suggestion
    if( autodoc && !g->m.inbounds( p->pos() ) ) {
```
Otherwise: add at least some comment why you are comparing with some magic numbers.
