### PR TITLE
Invalidate all levels of map cache on map shift

### LINKED ISSUE #29175: Attacks from under ceiling with 3D FOV on.
**Describe the bug**  
When on a roof, zombies from inside the building can use special attacks on you, most notably shockers.

**To Reproduce**  
1. Turn on 3D FOV
2. Get a nice hoard and lure it into a json roofed building.
3. Get on roof, enjoy endless perfectly targeted shocks.

**Expected behavior**  
No attacks through the roof from inside.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.D:1214
 - Graphics version: TILES
 - Mods loaded: none 

**Additional context**  
On roof getting shocked
shocker below
shocker below & inside
shocker
gifs are fun
shocker

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Fixes #29175 *again*

#### Solution
The previous PR fixed one cause, but I finally stumbled across another cause of the problem, which occurs due to the map shifting code failing to invalidate the entire map cache.

#### Testing
Setup:
Locate a building with a roof you can climb onto, ideally one that is isolated.
Spawn a shocker inside the building, ideally shut in a closet or similar.
Climb onto the roof and walk above the area with the shocker.

Expected result:
Nothing happens
Actual Result:
Shocker shocks you through the roof, and you can sometimes see the shocker appear in the threat compass.

Follow-up:
Cross to the other side of the roof and then return.
The shocker no longer shocks you through the roof (because crossing the roof invalidated the appropriate caches).

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -1334,7 +1334,7 @@ void game::calc_driving_offset( vehicle *veh )
 
     const point offset_sign( ( offset_difference.x < 0 ) ? -1 : 1,
                              ( offset_difference.y < 0 ) ? -1 : 1 );
-    // Shift the current offset in the direction of the calculated offset by one tile
+    // ( the current offset in the direction of the calculated offset by one tile
```
Comment (kevingranade) [inline src/game.cpp]:
```suggestion
    // Shift the current offset in the direction of the calculated offset by one tile
```

File: src/game.cpp [hunk 2]
```diff
@@ -10498,7 +10498,13 @@ point game::update_map( int &x, int &y )
     load_npcs();
 
     // Make sure map cache is consistent since it may have shifted.
-    m.invalidate_map_cache( get_levz() );
+    if( m.hasm.has_zlevels() ) {
```
Comment (kevingranade) [inline src/game.cpp]:
```suggestion
    if( m.has_zlevels() ) {
```
