### PR TITLE
fix ammo_capacity() and implement item_id_restriction infrastructure

### LINKED ISSUE #40125: Cannot reload the sewing kit with thread. Thread is gone, no reloading.
Cannot reload the sewing kit with thread. Thread is gone, no reloading. 

DEBUG    : tried to put an item in a container that cannot contain it

 FUNCTION : int item::fill_with(const itype&, int)
 FILE     : src/item.cpp
 LINE     : 8146

# Steps To Reproduce

1. Try to reload sewing kit with thread.
2. After reload - sewing kit is empty, thread is gone.

# Expected behavior

Reload should reload thread in a sewing kit.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1713-gd15c896 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    More Survivor Stuff [more_survivor_stuff],
    More City Locations [cityside],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

DEBUG    : tried to put an item in a container that cannot contain it

 FUNCTION : int item::fill_with(const itype&, int)
 FILE     : src/item.cpp
 LINE     : 8146

### LINKED ISSUE #40158: Unloading sewing kit creates a "none" item
# Describe the bug
Unloading sewing kit creates a "none" item

# Steps To Reproduce
1. Debug spawn `sewing kit`
2. Unload your `sewing kit (50/200)`
3. Get a debug message (see below)
4. Open inventory and witness 2 items: `sewing kit (0/200)` and `none`

# Expected behavior
`thread` not losing identity

# Versions and configuration
- OS: Linux
    - OS Version: Ubuntu 20.04
- Game Version: 0.E-1745-gce33f39cfd-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm]
]

# Additional context
```
02:01:22.096 ERROR : (error message will follow backtrace)
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_Z21debug_write_backtraceRSo+0x23) [0x1bcc763]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x106) [0x1bcc1b6]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x49) [0x1bcbcc9]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_Z12realDebugmsgIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvPKcS7_S7_S7_DpOT_+0x43) [0x19085e3]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_ZNK6player16item_reload_costERK4itemS2_i+0x388) [0x248e528]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_ZN6player6unloadER4item+0xc35) [0x248fc85]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_ZN13avatar_action6unloadER6avatar+0x139) [0x19fefa9]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_ZN4game13handle_actionEv+0xe33) [0x1d9bd73]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_ZN4game7do_turnEv+0x578) [0x1cfa858]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(main+0xc82) [0x202ff72]
    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7ffff7a2b0b3]
    /mnt/Data/code/git/Cataclysm-DDA/cataclysm(_start+0x2e) [0x189f89e]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:777
    DebugLog(DebugLevel, DebugClass)
    …/src/debug.cpp:943
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.cpp:115
    void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
    …/src/debug.h:?
    player::item_reload_cost(item const&, item const&, int) const
    …/src/player.cpp:?
    player::unload(item&)
    …/src/player.cpp:3238
    avatar_action::unload(avatar&)
    …/src/avatar_action.cpp:1292
    game::handle_action()
    …/src/handle_action.cpp:2022
    game::do_turn()
    …/src/game.cpp:1515
    main
    …/src/main.cpp:697
    __libc_start_main
    ??:?
    _start
    ??:?
Backtrace emission took 6 seconds.
src/player.cpp:2894 [int player::item_reload_cost(const item &, const item &, int) const] cannot determine reload cost as none is neither ammo or magazine
```

### LINKED ISSUE #40203: Vehicle Welding Rig... Not enough charge
When trying to use the Vehicle Welding Rig the game tells me that the tool doesn't have enough charge, despite being installed in a vehicle with 100% charge. I am using the latest experimental build 10628.

### LINKED ISSUE #40307: Kitchen unit in vehicle not considered "hot plate" while crafting
cooking recipes which require "hot plate" or other fire based cooking do not recognize the vehicle kitchen unit as valid and will not craft.

When (e)xamining the kitchen unit, "use hot plate" functionality works, but only heats items. Crafting food items that require the hot plate will show "hot plate (2 charges)" in red text and is not available to craft. Vehicle has power, standing right next to kitchen unit.

# Expected behavior

These recipes should be able to craft using the kitchen unit hot plate.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

### LINKED ISSUE #40315: Unloading or Reloading items like (misc repair kit, gas mask, or sewing kit) result in none items and nothing being reloaded Respectively
# Describe the bug, Steps To Reproduce, and Screenshots

When you unload an item like (misc repair kit, gas mask, or sewing kit) it will result in an error message. 

 DEBUG    : cannot determine reload cost as none is neither ammo or magazine

 FUNCTION : int player::item_reload_cost(const item&, const item&, int) const
 FILE     : src/player.cpp
 LINE     : 2860

and a none item instead of duct tape, gas mask cartridges, and thread Respectively
**EXAMPLE when unloading:** 
_spawn in a gas mask using the Debug menu_
Gas 1
_take the action "Unload"_
Gas 2
_open inventory and verify that the none item is there_
gas 3

When you reload an item like (misc repair kit, gas mask, or sewing kit) it will simply say that it was reloaded and do nothing. 
**EXAMPLE when reloading:** 
_spawn in a misc repair kit and duct tape using the Debug menu_
Tape 1
_take the action Reload_
Tape 2
Tape 3
_open inventory and verify that the misc repair kit is still empty_
Tape 4

# Expected behavior
**When unloading**
When I unload a gas mask I expected to get the appropriate gas mask cartridges from it. 
I expected this behavior because that is how it worked before and how I think it should function. 
**When reloading**
When I reload a misc repair kit I expected to fill it with the appropriate item(duct tape). 
I expected this behavior because that is how it worked before and how I think it should function. 

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1864-gb8fb092 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Cataclysm++ [Cata++]
]
using Windows 10

# Additional context

1. I loaded a new save, new world, and a new character for my test. 
2. Both of the **EXAMPLES** have been repeated with the following items: 
- misc repair kit
- gas mask
- filter mask
- firefighter PBA mask
- survivor fire mask
- winter survivor mask
- survivor divemask (tho not unloaded sins it spawns in empty)
- sewing kit
- tailor's kit
3. this bug has also been repeated with a soda can stove kit where unloading it results in a none and same ERROR. Tho I have not tried to reload it sens I do not know how to spawn in concentrated alcohol in a container. 

this is my first time making a Bug report so pleas give me feedback on how I did (aka tell me what I did wrong)

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: Infrastructure "fix ammo_capacity() and implement item_id_restriction infrastructure"```

#### Purpose of change
This fixes the bug with not being able to load sewing kits. It also makes it so the magazine code relies more on pockets than the islots. This PR also requires that gun json gets updated first, because copy-from is being very frustratingly broken with the item factory fake pocket loading code.

So, when you get the ammo_capacity() of an item, before you know it could only have 1 type of clip_size whether it's a mag or a gun. however, now, you can have a different clip size (for lack of better term) per ammotype per pocket - so it's imperative that is calculated correctly.

After working on this from the ammo_capacity direction, it became clear to me that i needed to implement item_id_restriction and MAGAZINE_WELL type pockets in order for the gun/reloading/unloading code to work properly.
#### Testing
TBD - running the tests locally for now is breaking things

#### Additional Comments
Closes #40382
Fixes #40315
Fixes #40158
Fixes #40307
Fixes #40203
Fixes #40125

### CODE REVIEW

**Comment by Resok** [comment]
I'm trying to validate the JSON changes to the jackhammer (gas powered) using this branch and I'm getting an exception in xtree when reloading the Jackhammer.  Error reads: 

xtree
Line: 241

Expression: map/set iterators in range are from different containers

I have the callstack if it's useful to you.

This was after updating the JSON to have a pocket magazine that can only contain gasoline.

Callstack -

```>	Cataclysm-vcpkg-static-Debug-x64.exe!std::_Verify_range(const std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>> & _First, const std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>> & _Last) Line 241	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!std::_Adl_verify_range<std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>>,std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>>>(const std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>> & _First, const std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>> & _Last) Line 1044	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!std::distance<std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>>>(std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>> _First, std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>> _Last) Line 1658	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!enumerate_as_string<std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>>,std::string <lambda>(const string_id<ammunition_type> &)>(std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>> first, std::_Tree_const_iterator<std::_Tree_val<std::_Tree_simple_types<string_id<ammunition_type>>>> last, player::select_ammo::__l26::std::string <lambda>(const string_id<ammunition_type> &) string_for, enumeration_conjunction conj) Line 676	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!player::select_ammo(const item & base, bool prompt, bool empty) Line 2478	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!game::reload(item_location & loc, bool prompt, bool empty) Line 8545	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!game::inventory_item_menu(item_location locThisItem, int iStartX, int iWidth, game::inventory_item_menu_positon position) Line 2231	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!game_menus::inv::common(avatar & you) Line 239	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!game::handle_action() Line 1956	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!game::do_turn() Line 1517	C++
 	Cataclysm-vcpkg-static-Debug-x64.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 697	C++
 	[External Code]	```

**Comment by KorGgenT** [comment]
ok there might be a bit of scop creep here, but i need to get it to where the bugs i introduced with the adjustments to the foundational functions get reduced. i'm going to keep this in draft for a while so that it's transparent what i'm doing

**Comment by Resok** [comment]
Did some testing with these changes. Was able to add the new "MAGAZINE_WELL" type pocket to the json of a few items to test out. So far it seems to work better at least - though I still see things like this:

01:07:49.721 ERROR : src\item.cpp:600 [ammo_set] Tried to set invalid magazine of batteries for medium plutonium fuel battery
01:07:53.755 ERROR : src\item.cpp:600 [ammo_set] Tried to set invalid magazine of batteries for medium plutonium fuel battery
01:07:53.945 ERROR : src\item.cpp:600 [ammo_set] Tried to set invalid magazine of batteries for light plutonium fuel battery

when trying to reload an item that I set with the following:

    "pocket_data": [
      {
        "pocket_type": "MAGAZINE_WELL",
        "holster": true,
        "max_contains_volume": "5 L",
        "max_contains_weight": "5 kg",
        "item_restriction": [
          "light_battery_cell",
          "light_plus_battery_cell",
          "light_minus_battery_cell",
          "light_atomic_battery_cell",
          "light_minus_atomic_battery_cell",
          "light_minus_disposable_cell",
          "light_disposable_cell"          
        ]
      }
    ],

However when I go to reload them it seems to work fine and only shows me valid items in my list of reload targets.

image

**Comment by Resok** [comment]
Looks like this unhooked the vehicle tool crafting checks - Save below.

[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4611954/Save.zip)

File: src/item_contents.cpp [hunk 1]
```diff
@@ -347,21 +348,38 @@ void item_contents::heat_up()
...
 }
 
-int item_contents::ammo_consume( int qty )
+int item_contents::ammo_consume( int qty, const tripoint &pos )
 {
     for( item_pocket &pocket : contents ) {
-        if( !pocket.is_type( item_pocket::pocket_type::MAGAZINE ) ) {
-            continue;
+        if( pocket.is_type( item_pocket::pocket_type::MAGAZINE_WELL ) ) {
+            // we are assuming only one magazine per well
```
Comment (ymber) [inline src/item_contents.cpp:355]: This assumption is fine to bake into the code. There should only ever be one magazine per well. Going forward we should handle multiple magazines with multiple `MAGAZINE_WELL` type pockets.

File: src/item_contents.cpp [hunk 2]
```diff
@@ -347,21 +348,38 @@ void item_contents::heat_up()
...
+        } else if( pocket.is_type( item_pocket::pocket_type::MAGAZINE ) ) {
+
+            qty = pocket.ammo_consume( qty );
         }
-        qty = pocket.ammo_consume( qty );
     }
     return qty;
 }
 
 item *item_contents::magazine_current()
```
Comment (ymber) [inline src/item_contents.cpp:379]: Should this return an `item_location`?

File: src/item_contents.cpp [hunk 3]
```diff
@@ -372,9 +390,38 @@ item *item_contents::magazine_current()
...
 }
 
+int item_contents::ammo_capacity( const ammotype &ammo ) const
+{
+    int ret = 0;
+    for( const item_pocket &pocket : contents ) {
+        if( !pocket.is_type( item_pocket::pocket_type::MAGAZINE ) ) {
+            continue;
+        }
+        ret += pocket.ammo_capacity( ammo );
```
Comment (ymber) [inline src/item_contents.cpp:400]:
```suggestion
        if( pocket.is_type( item_pocket::pocket_type::MAGAZINE ) ) {
            ret += pocket.ammo_capacity( ammo );
        }
```

File: src/item_contents.cpp [hunk 4]
```diff
@@ -372,9 +390,38 @@ item *item_contents::magazine_current()
...
+std::set<ammotype> item_contents::ammo_types() const
+{
+    std::set<ammotype> ret;
+    for( const item_pocket &pocket : contents ) {
+        if( !pocket.is_type( item_pocket::pocket_type::MAGAZINE ) ) {
+            continue;
+        }
+        for( const ammotype &ammo : pocket.ammo_types() ) {
+            ret.emplace( ammo );
+        }
```
Comment (ymber) [inline src/item_contents.cpp:414]:
```suggestion
        if( pocket.is_type( item_pocket::pocket_type::MAGAZINE ) ) {
            for( const ammotype &ammo : pocket.ammo_types() ) {
                ret.emplace( ammo );
            }
        }
```

File: src/item_contents.cpp [hunk 5]
```diff
@@ -714,6 +764,20 @@ std::vector<const item *> item_contents::gunmods() const
...
+std::set<itype_id> item_contents::magazine_compatible() const
+{
+    std::set<itype_id> ret;
+    for( const item_pocket &pocket : contents ) {
+        if( !pocket.is_type( item_pocket::pocket_type::MAGAZINE_WELL ) ) {
+            continue;
+        }
+        for( const itype_id &id : pocket.item_type_restrictions() ) {
+            ret.emplace( id );
+        }
```
Comment (ymber) [inline src/item_contents.cpp:776]:
```suggestion
        if( pocket.is_type( item_pocket::pocket_type::MAGAZINE_WELL ) ) {
            for( const itype_id &id : pocket.item_type_restrictions() ) {
                ret.emplace( id );
            }
        }
```

File: src/item_contents.cpp (hunk 2 above)
Comment (KorGgenT) [reply src/item_contents.cpp:379]: most functions that take item * or item & as parameters and return item * or item & really should imo. it's not important enough to do that in this PR though.

File: src/item.cpp [hunk 6]
```diff
@@ -6945,42 +6970,28 @@ int item::ammo_remaining() const
...
+int item::remaining_ammo_capacity() const
 {
-    return ammo_capacity( false );
+    if( ammo_types().empty() ) {
+        return 0;
+    }
+
+    const itype *loaded_ammo = ammo_data();
+    if( loaded_ammo == nullptr ) {
+        return ammo_capacity( item::find_type( ammo_default() )->ammo->type ) - ammo_remaining();
```
[the remark this answers is not in the document]
Comment (KorGgenT) [reply src/item.cpp:6981]: This function is used in a couple places to ask "can this be reloaded?" and sometimes there's no ammo type available. I thought that it would make sense to have the default ammo as a fallback if there was no ammo loaded in order to calculate some number, instead of just returning 0.

File: src/dump.cpp [hunk 7]
```diff
@@ -216,7 +215,7 @@ bool game::dump_stats( const std::string &what, dump_mode mode,
                 if( !gun.magazine_integral() ) {
                     gun.put_in( item( gun.magazine_default() ), item_pocket::pocket_type::MAGAZINE );
```
Comment (KorGgenT) [inline src/dump.cpp:216]:
```suggestion
                    gun.put_in( item( gun.magazine_default() ), item_pocket::pocket_type::MAGAZINE_WELL );
```

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/psa-nested-containers-is-now-live-in-experimental/23529/62

File: src/item.cpp [hunk 8]
```diff
@@ -7668,18 +7637,29 @@ bool item::reload( player &u, item_location ammo, int qty )
...
-            put_in( to_reload, item_pocket::pocket_type::MAGAZINE );
+        if( ammo->has_flag( flag_SPEEDLOADER ) ) {
+            // sets curammo to one of the ammo types contained
+            curammo = ammo->contents.first_ammo().type;
+            qty = std::min( qty, ammo->ammo_remaining() );
+            item ammo_copy( ammo->contents.first_ammo() );
+            ammo_copy.charges = qty;
+            put_in( ammo_copy, item_pocket::pocket_type::MAGAZINE );
+            ammo->ammo_consume( qty, tripoint_zero );
+        } else if( ammo->ammo_type() == "plutonium" ) {
```
Comment (kevingranade) [inline src/item.cpp:7648]:
```suggestion
        } else if( ammo->ammo_type() == ammotype( "plutonium" ) ) {
```

File: src/item.cpp [hunk 9]
```diff
@@ -7645,7 +7645,7 @@ bool item::reload( player &u, item_location ammo, int qty )
             ammo_copy.charges = qty;
             put_in( ammo_copy, item_pocket::pocket_type::MAGAZINE );
             ammo->ammo_consume( qty, tripoint_zero );
-        } else if( ammo->ammo_type() == "plutonium" ) {
+        } else if( ammo->ammo_type() == ammotype( "plutonium" ) ) {
```
Comment (Wishbringer) [inline src/item.cpp:7648]:
```suggestion
        } else if( ammo->ammo_type() == ammo_plutonium ) {
```

**Comment by kevingranade** [comment]
Wielded gun, hit 'f'ire, nothing happened.

**Comment by KorGgenT** [comment]
I fixed some issues, but I have run into the main crux of the problem:
Item_factory::check_and_create_magazine() is not sufficient anymore. every gun that has copy-from and that changes the magazine will now incorrectly have the previous magazine data, which conflicts with islot_gun and will show this error message
image
I have already spent too many hours copy-pasting by hand, the rest of them just need some python scripting or something.

File: data/json/items/tool/tailoring.json [hunk 10]
```diff
@@ -160,9 +160,7 @@
     "material": [ "plastic", "steel" ],
     "symbol": ",",
     "color": "red",
-    "ammo": [ "thread" ],
-    "initial_charges": 50,
-    "max_charges": 200,
+    "pocket_data": [ { "pocket_type": "MAGAZINE", "ammo_restriction": { "thread": 200 } } ],
```
Comment (protodave) [inline data/json/items/tool/tailoring.json:163]: Will `tailors_kit` require a similar change?

```
"pocket_data": [ { "pocket_type": "MAGAZINE", "ammo_restriction": { "thread": 400 } } ],
```

**Comment by Lamandus** [comment]
since it will be handled as a container, is it now possible to load a weapon with different types of ammo (for example FMJ and AP)? And if so, what ammo will it use? The one loaded in last?

File: data/json/items/tool/tailoring.json (hunk 10 above)
Comment (KorGgenT) [reply data/json/items/tool/tailoring.json:163]: yes and likely i have missed more json items. i'll fix this one here at least.

**Comment by KorGgenT** [comment]
> since it will be handled as a container, is it now possible to load a weapon with different types of ammo (for example FMJ and AP)? And if so, what ammo will it use? The one loaded in last?

not as of this PR, MAGAZINE type pockets when using ammo_restriction only take 1 stack of items. you might be able to fudge it  by using item_restriction maybe, but that would be a pretty hacky solution imo and mod-only because of it, for now

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/psa-nested-containers-is-now-live-in-experimental/23529/94

File: src/item.cpp [hunk 11]
```diff
@@ -6143,7 +6179,7 @@ bool item::is_bionic() const
 
 bool item::is_magazine() const
 {
-    return !!type->magazine;
+    return !!type->magazine || contents.has_pocket_type( item_pocket::pocket_type::MAGAZINE );
```
Comment (anothersimulacrum) [inline src/item.cpp:6182]: This change means that things that use this to gate accessing `type->magazine` will no longer work, and will crash on attempting to access non-existent magazine data.

File: src/item_factory.cpp [hunk 12]
```diff
@@ -2222,36 +2222,50 @@ void Item_factory::check_and_create_magazine_pockets( itype &def )
...
+    pocket_data mag_data;
+    mag_data.holster = true;
+    mag_data.volume_capacity = 200_liter;
+    mag_data.max_contains_weight = 400_kilogram;
+    mag_data.max_item_length = 2_km;
+    mag_data.watertight = true;
+    if( !def.magazines.empty() ) {
+        mag_data.type = item_pocket::pocket_type::MAGAZINE_WELL;
+        mag_data.rigid = false;
+        for( const std::pair<ammotype, std::set<itype_id>> &mag_pair : def.magazines ) {
```
Comment (anothersimulacrum) [inline src/item_factory.cpp:2243]:
```suggestion
        for( const std::pair<const ammotype, std::set<itype_id>> &mag_pair : def.magazines ) {
```

File: src/item_pocket.cpp [hunk 13]
```diff
@@ -397,18 +404,39 @@ item *item_pocket::magazine_current()
...
+        return 0;
+    } else {
+        return found_ammo->second;
+    }
+}
+
+std::set<ammotype> item_pocket::ammo_types() const
+{
+    std::set<ammotype> ret;
+    for( const std::pair<ammotype, int> &type_pair : data->ammo_restriction ) {
```
Comment (anothersimulacrum) [inline src/item_pocket.cpp:436]:
```suggestion
    for( const std::pair<const ammotype, int> &type_pair : data->ammo_restriction ) {
```

File: src/item.cpp (hunk 11 above)
Comment (KorGgenT) [reply src/item.cpp:6182]: this is true, and i have come across these that do cause crashes and fixed them. islot_magazine is on the chopping block in favor of pocket_data (need to check with yutna for sure but i'm confident that this is true), and if i do not have this bool in here it will backpedal a lot of the work on this pr

Comment (anothersimulacrum) [reply src/item.cpp:6182]: Not this one
https://github.com/CleverRaven/Cataclysm-DDA/pull/40399/files#diff-f7ca61cf749eba039da961e8a7be1630L8408
`if( !is_magazine() || !type->magazine->protects_contents ) {`
