### PR TITLE
Fix aiming if target moves out of LOS.

### LINKED ISSUE #27035: Character shoots at nothing if target leaves los while aiming
**Describe the bug**  
If a monster is being aimed at by the survivor using precise aim and the monster loses sight, the game pops and error and the survivor shoots at nothing. 

**To Reproduce**  

1. Make a player with a gun, magazine, and some ammo.
2. Try to precise aim at a zombie that will pass out of los during the aiming period (easiest with randomly moving zombie at night vision range)
3. Pops up error, generates noise, and generates casing 

**Expected behavior**  
Character does not aim at nothing. 

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Win 10
 - Game Version 0 .C 35097-g6d3d71b
 - Graphics version Tiles

### PR DESCRIPTION
**Pull request by OzoneH3**
#### Summary
```SUMMARY: Bugfixes "Fix aiming if target moves out of LOS."```

#### Purpose of change
Fixes #27035

#### Describe the solution
* Aim at last known monster location instead of character after losing LOS.
* Prevent firing and auto aiming at oneself.
* Cancel auto aim activity on losing LOS.

### CODE REVIEW

File: src/ranged.cpp [hunk 1]
```diff
@@ -934,6 +934,14 @@ std::vector<tripoint> target_handler::target_ui( player &pc, target_mode mode,
             idx = -1;
             if( pc.last_target_pos ) {
                 dst = *pc.last_target_pos;
+
+                if( pc.last_target.expired() && pc.has_activity( activity_id( "ACT_AIM" ) ) &&
```
Comment (kevingranade) [inline src/ranged.cpp]: If the monster is out of sight but still on the map, pc.last_target.expired() will return true.
I think what you want here is to check for ``pc.last_target.expired() || !pc.sees( pc.last_target.lock().get() )``.
If that works I'll patch it in and merge.
