### PR TITLE
Containers inherit longest side from longest item inside

### LINKED ISSUE #41852: Container max length can be bypassed with holsters, sheaths
# Describe the bug

Containers are allowing storage of items longer than their maximum length, if the item is sheathed inside another container which can fit.

# Steps To Reproduce

1. Spawn a survivor rucksack, axe ring holster, and battle axe
2. Insert the battle axe into the holster, then insert the holster into the rucksack

# Expected behavior

Containers should be least as long as the longest item inside

# Screenshots

cataclysm-tiles_IakVIQhXoQ

# Versions and configuration

- OS: Windows
- Game Version: 0.E-3706-g16fb746 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Stats Through Kills [stats_through_kills],
    No Rail Stations [No_Rail_Stations],
    Mythical Martial Arts [MMA],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion]
]

### PR DESCRIPTION
**Pull request by mqrause**
#### Summary

SUMMARY: Bugfixes "Containers can't hold too large items contained in other containers"

#### Purpose of change

Fixes #41852

#### Describe the solution

item::length checks child items recursively and returns the biggest length found

#### Testing

See issue. Also put a bunch of stuff in a container and checked the resulting length of the container.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -5023,12 +5023,22 @@ units::mass item::weight( bool, bool integral ) const
...
-    if( made_of( phase_id::LIQUID ) || is_soft() ) {
+    if( made_of( phase_id::LIQUID ) || ( is_soft() && is_container_empty() ) ) {
         return 0_mm;
     }
     if( is_corpse() ) {
         return units::default_length_from_volume<int>( corpse->volume );
     }
+    if( is_container() ) {
+        units::length max = is_soft() ? 0_mm : type->longest_side;
+        for( auto it : contents.all_items_top( item_pocket::pocket_type::CONTAINER ) ) {
```
Comment (KorGgenT) [inline src/item.cpp:5034]: please change this from `auto` to its explicit type.

File: src/item.cpp [hunk 2]
```diff
@@ -5023,12 +5023,22 @@ units::mass item::weight( bool, bool integral ) const
...
+            units::length it_length = it->length();
+            if( it_length > max ) {
+                max = it_length;
+            }
```
Comment (KorGgenT) [inline src/item.cpp:5038]:
```suggestion
            max = std::max( it->length(), max );
```

File: src/item.cpp [hunk 3]
```diff
@@ -5023,12 +5023,19 @@ units::mass item::weight( bool, bool integral ) const
...
 units::length item::length() const
 {
-    if( made_of( phase_id::LIQUID ) || is_soft() ) {
+    if( made_of( phase_id::LIQUID ) || ( is_soft() && is_container_empty() ) ) {
         return 0_mm;
     }
     if( is_corpse() ) {
         return units::default_length_from_volume<int>( corpse->volume );
     }
+    if( is_container() ) {
```
Comment (KorGgenT) [inline src/item.cpp:5032]: this check is actually unecessary, since contents.all_items_top( item_pocket::pocket_type::CONTAINER ) already does some checks if there are any items in the container. the for loop would therefore not run at all if it didnt' have any contents in CONTAINER pockets.
