### PR TITLE
fix item_contents save/load

### LINKED ISSUE #40876: Sealed items open across save
Sealed items open themselves after loading.

Containers that are sealed will be not sealed after saving and loading.

# Steps To Reproduce

1. Make a player with vaccum sealer, salt water, plastic bag and vegtables and some cooking skill
2. Make salted Veggie chunks. Bag will be sealed
3. Save and quit. Then reload, bag will be unsealed and veggies will start to spoil

# Expected behavior

Bags and other containers stay sealed after saving and loading. Otherwise no point in preserving food.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2476-g1b2af09 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    DinoMod [DinoMod],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    Stats Through Skills [StatsThroughSkills]

# Additional context

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: Bugfixes "fix item_contents save/load"```

#### Purpose of change
related #40127 - possibly fixes it but i haven't checked random item spawns as this doesn't effect them at all

Fixes #40876

#### Describe the solution
the load function for item_contents incorrectly assumes that the insert_item function will insert the item into the same pocket that the item was saved in - but this is definitely not the case as items are dynamically assigned and possibly specifically assigned by the player. additionall, the MIGRATION item pocket was never utilized such that items won't disappear on save/load.

a weakness of this implementation is the following example: an item has multiple pockets, and someone changes the json to rearrange the pockets, or add a MAGAZINE pocket to the front. in this case, most of the items will be moved to the MIGRATION pocket, necessitating the player to pick up the items after they fall to the ground after moving once.

#### Testing
several save/load cycles, with 2 army jackets and jeans and assorted sundry of items. also spawned in canned sardines to make sure they stay sealed across the save/load cycle.

#### Additional context
this might be one of the main things that are causing cans to appear to spawn open, maybe people are saving and loading near enough to houses to have the items spawned and go through the save/load cycle. it's worth reassessing the related bug report after this bugfix.

### CODE REVIEW

File: src/item_contents.cpp [hunk 1]
```diff
@@ -95,14 +95,36 @@ size_t item_contents::size() const
 
 void item_contents::combine( const item_contents &read_input )
 {
+    std::vector<item> uninserted_items;
+    int pocket_index = 0;
```
Comment (kevingranade) [inline src/item_contents.cpp:99]:
```suggestion
    size_t pocket_index = 0;
```
