### PR TITLE
Fix corpse materials

### LINKED ISSUE #19662: prioritize {m:flesh} no longer marks bodies
To help me spot unpulped zombies I usually prioritize (+) "{m:flesh}" and filter "-pulped", but that prioritize isn't working anymore.

### PR DESCRIPTION
**Pull request by sethsimon**
Fixes #19662.

Corpses have no materials in `type->materials` because it depends on which mtype `corpse` is. However, some material-getters only looked at `type->materials`. Hence the changes to `item::get_random_material` and `item::get_base_material`, since I doubt that's what the author(s) intended.

These changes alone are enough to fix #19662, but in `item_filter_from_string`, the material filter is only compared to the base material, which causes oddities such as leather patches matching m:flesh but not m:leather, being able to find leather clothing manually but not via the filter, etc.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -3912,18 +3912,14 @@ void item::mark_chapter_as_read( const player &u )
 
 const material_type &item::get_random_material() const
 {
-    if( type->materials.empty() ) {
-        return material_id( "null" ).obj();
-    }
-    return random_entry( type->materials ).obj();
+    const std::vector<material_id> mats = made_of();
+    return mats.empty() ? material_id( "null" ).obj() : random_entry( mats ).obj();
```
Comment (codemime) [inline src/item.cpp]: That's `material_id::NULL_ID.obj()` (same below).

**Comment by sethsimon** [comment]
Thanks, those are all good ideas.
