### PR TITLE
NPC jobs at camps

### LINKED ISSUE #34402: NPC disappeared after telling them to do construction
# Describe the bug

I told an NPC follower I'd just befriended to work on deconstructing the fences around my farmhouse, and when I went back toward him a minute later he had disappeared. Wasn't on the map, wasn't seemingly anywhere. I forgot to give him a toolbox as well. He's still alive, because his quest which I've since completed is still up, but I just can't find him. It's been like two ingame weeks now since I saw him.

# Steps To Reproduce

1. Blueprint fences to be deconstructed.
2. Tell NPC to work on constructions.
3. NPC seemingly disappears after leaving them offscreen.

# Expected behavior

Having some way of tracking NPCs, or for them not to disappear like this?

# Screenshots

image
My follower was at the top of my farm (circled) when I told him to work on construction. I went to the bottom of my farm (to set more fence deconstruction blueprints), and when I walked back up, he was gone from my view and not even on the map. There are no enemies nearby.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-7542-ga5d33f6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Craftable Gun Pack [craftgp],
    Garden Pots [growable-pots],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Fungal Monsters [No_Fungi],
    No Gasoline Boomers [No_Gasoline_Boomers-DANTE],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    Stats Through Kills [stats_through_kills],
    Hair aka Rainbow [Hairs]
]

# Additional context

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Features "NPC jobs at camps"```

#### Purpose of change
Fixes #34402 
This allows NPCs to be assigned jobs at camp, then they will periodically scan for multi-activities that they can do, thats their job and they will keep doing it until told otherwise.

#### Describe the solution
Adds a UI to the bulletin board - under "assign jobs" entry, which will allow you to give each NPC stationed at that camp a job, this job will have a list of activity types that it will go through periodically ( every 30 minutes currently whilst testing impact on performance ), otherwise theyll hang around the camp waiting for the next moment they check if theres something to do.

To support this ive changed how "assign to camp" works, previously anyone asked to guard , whilst they were at a camp, were considered "stationed" there, now you have to explicitly say tht you want them to be assigned to this camp.

They will then act similar to an NPC on guard, they will be stationary ( pending future work in NPC being idle and getting food/drink in their downtime etc ), until they find work to do.

There is no priority currently to the list of activities per job category, it just checks a random one every checking interval, some sort of priority queue to work through would be ideal eventually.

I would like eventually some feedback on why the NPC dosnt complete their task, there are a lot of reasons why the work isnt possible, but often it just looks like the NPC stands there and dosnt move, because no feedback is given as to why.

The problem with this is that if it did a message every time they discounted a tile to work on, the message log would have horrendous spam, so im going to eventually work out a way to feed the activity code failure reasons into a seperate UI , like a basecamp work log, where you can search for why the NPC didnt have the skills to repair that vehicle, or the tools to build that wall.

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

### CODE REVIEW

File: src/faction_camp.cpp [hunk 1]
```diff
@@ -717,6 +718,15 @@ void basecamp::get_available_missions( mission_data &mission_key, bool by_radio
                                       "Items that do not have a loot destination zone will be sorted "
                                       "using the normal rules for automatic zone sorting." ) );
             mission_key.add( "Reset Sort Points", _( "Reset Sort Points" ), entry );
+            validate_assignees();
+            std::vector<npc_ptr> npc_list = get_npcs_assigned();
+            entry = string_format( _( "Notes:\n"
+                                      "Assign repeating job duties to NPCs stationed here. "
```
Comment (Qrox) [inline src/faction_camp.cpp]: Missing a linebreak?
```suggestion
                                      "Assign repeating job duties to NPCs stationed here.\n"
```
