### PR TITLE
Fix nones in items made by jmapgen_loot

### LINKED ISSUE #19639: "Paper shot cartridge with none" found in gun safe
I found this item in a gun safe in a basement. In the item description it says, "seeing this is a bug."

### PR DESCRIPTION
**Pull request by sethsimon**
Fixes #19639. The cause of this is similar to what #17048 fixed (note the diffs). This is marked as WIP because in hindsight, I suspect it would be a better idea to create the item groups once instead of each time items need to spawned.

SECOND EDIT: Incidentally #19670 is partially (not fully, like I previously thought) addressed by this.

### CODE REVIEW

**Comment by sethsimon** [comment]
Ready.

File: src/mapgen.cpp [hunk 1]
```diff
@@ -859,39 +860,28 @@ class jmapgen_loot : public jmapgen_piece {
...
-                }
+                const std::vector<item> spawn = result_group->create( calendar::turn );
                 m.spawn_items( tripoint( rng( x.val, x.valmax ), rng( y.val, y.valmax ), m.get_abs_sub().z ), spawn );
             }
         }
 
     private:
-        const std::string group;
-        const std::string name;
+        std::unique_ptr<Item_spawn_data> result_group;
```
Comment (codemime) [inline src/mapgen.cpp]: You probably don't need the `unique_ptr` anymore. There are no polymorphic classes.
