### PR TITLE
Fix AIM duping items and wrong "source area is the same"

### LINKED ISSUE #12178: More AIM Problems
Looked around and didn't see these reported yet. Apologies if they have been and I missed them. Tested on the latest experimental (cb7dabb).

1. Can't move items between two ground tiles using "move item/move item stack":
untitled-1

2. Moving anything with charges/multiples moves one charge/item at a time. This results in duplicated items with one charge apiece:
untitled-2

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/12112777-more-aim-problems?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #12178

Forgot to check whether the vehicle is not null and whether the items are counted by charges.

### CODE REVIEW

File: src/advanced_inv.cpp [hunk 1]
```diff
@@ -1901,7 +1901,7 @@ bool advanced_inv_area::is_same( const advanced_inv_area &other ) const
         id != AIM_WORN      && other.id != AIM_WORN      &&
         id != AIM_CONTAINER && other.id != AIM_CONTAINER ) {
 
-        if( veh == other.veh ) {
+        if( veh != nullptr && veh == other.veh ) {
```
Comment (BevapDin) [inline src/advanced_inv.cpp]: Why this? It leads to the previously fixed bug where the ALL pane shows the content of a adjacent vehicle cargo part. Example: select ALL in the left pane, select vehicle part (with items!) in the right pane. The items from the vehicle part show up in the all pane.

Comment (KrazyTheFox) [inline src/advanced_inv.cpp]: I'm playing with this right now and this doesn't seem to be the case. I can select ALL in a pane, then in the other select a vehicle part and the items in the vehicle disappear from the ALL pane. Was there some other situation that would cause this I can test?

**Comment by Coolthulhu** [comment]
OK, disabled the ability to move items from ground to veh and veh to ground on the same tile.

This would be a cool feature, but it takes too much work to hack around the current implementation of panes and squares etc.
