### PR TITLE
Fix fuel being lost when canceling the siphon action.

### LINKED ISSUE #16828: Fuel disappears when cancelling siphon
In 4900, if you attempt to siphon gasoline or diesel without a suitable container (or if you cancel the siphon), the fuel disappears from the tank.  It doesn't spill on the ground or anything like that, it just disappears.

### PR DESCRIPTION
**Pull request by BevapDin**
Fixes #16828

### CODE REVIEW

**Comment by codemime** [comment]
Doh, I was just about to push a fix for this issue (along with some other changes).

File: src/player.h [hunk 1]
```diff
@@ -686,7 +686,7 @@ class player : public Character, public JsonSerializer, public JsonDeserializer
         int  addiction_level(add_type type) const;
 
         /** Siphons fuel from the specified vehicle into the player's inventory */
```
Comment (mugling) [inline src/player.h]: Needs documentation of return value

**Comment by baldamundo** [comment]
Thank you! <3
