### PR TITLE
Check if entire pane is liquid items before allowing moving all in AIM

### LINKED ISSUE #33962: Crash after trying to move spilled dried water
# Describe the bug

```
VERSION: 0.D-7542-ga5d33f6e61-dirty
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

	cataclysm(_Z21debug_write_backtraceRSo+0x33) [0x557c003a766e]
	cataclysm(+0x1803da8) [0x557c00377da8]
	cataclysm(+0x1803fb4) [0x557c00377fb4]
	/lib64/libc.so.6(+0x396b0) [0x7feb865bf6b0]
	/lib64/libc.so.6(gsignal+0x10b) [0x7feb865bf5eb]
	/lib64/libc.so.6(abort+0x123) [0x7feb865a8539]
	/lib64/libc.so.6(+0x22411) [0x7feb865a8411]
	/lib64/libc.so.6(+0x30c92) [0x7feb865b6c92]
	cataclysm(_ZN18advanced_inventory13query_chargesE12aim_locationRK21advanced_inv_listitemRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERi+0x1b3) [0x557c000875b3]
	cataclysm(_ZN18advanced_inventory7displayEv+0x1f34) [0x557c00083dc4]
	cataclysm(_Z12advanced_invv+0x39) [0x557c00088b3f]
	cataclysm(_ZN4game13handle_actionEv+0x126a) [0x557c00604506]
	cataclysm(_ZN4game7do_turnEv+0x86f) [0x557c00519611]
	cataclysm(main+0x111e) [0x557c009a6b24]
	/lib64/libc.so.6(__libc_start_main+0xeb) [0x7feb865a9ecb]
	cataclysm(_start+0x2a) [0x557bfff758ca]

	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	.../src/debug.cpp:620
	log_crash
	.../src/crash.cpp:263
	signal_handler
	.../src/crash.cpp:292
	killpg
	??:?
	gsignal
	??:?
	abort
	??:?
	??
	??:0
	__assert_fail
	??:?
	advanced_inventory::query_charges(aim_location, advanced_inv_listitem const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&)
	.../src/advanced_inv.cpp:2163
	advanced_inventory::display()
	.../src/advanced_inv.cpp:1668 (discriminator 1)
	advanced_inv()
	.../src/advanced_inv.cpp:2451
	game::handle_action()
	.../src/handle_action.cpp:1780
	game::do_turn()
	.../src/game.cpp:1450
	main
	.../src/main.cpp:688
	__libc_start_main
	??:?
	_start
	??:?
```

# Steps To Reproduce

1. Spill some water on the floor.
2. Put a brazier there.
3. Light it.
4. Observe it spending all your fuel reserve rapidly.
5. Try to move the zero volume of water from the brazier tile using AIM.
6. Enjoy the crash.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

```SUMMARY: Bugfixes "Check if entire pane is liquid items before allowing moving all in AIM"```

#### Purpose of change
Fixes #33962 

#### Describe the solution
Add check that the entire list of items in the pane can be moved before moving all.
The AIM currently checks if its liquid when you select one item to move, or when there is more than one item, and you select move all, but *not* when you select move all on just one item that is liquid.

#### Describe alternatives you've considered
N/A

#### Testing
before fix - dropped water on floor, opened AIM, tried to move it with , key to move all. it turned into a zero-charge weird item, then subsequent attempts to move it, caused a crash.

After fix - cannot "move all" when its a liquid item.
#### Additional context
N/A

### CODE REVIEW

File: src/advanced_inv.cpp [hunk 1]
```diff
@@ -841,7 +841,15 @@ bool advanced_inventory::move_all_items( bool nested_call )
     }
 
     // Check some preconditions to quickly leave the function.
-    if( spane.items.empty() ) {
+    int liquid_items = 0;
```
Comment (ifreund) [inline src/advanced_inv.cpp]:
```suggestion
    size_t liquid_items = 0;
```

File: src/advanced_inv.cpp [hunk 2]
```diff
@@ -841,7 +841,15 @@ bool advanced_inventory::move_all_items( bool nested_call )
...
+    for( const advanced_inv_listitem elem : spane.items ) {
+        for( const item *elemit : elem.items ) {
+            if( elemit->made_of_from_type( LIQUID ) && !elemit->is_frozen_liquid() ) {
+                liquid_items++;
+            }
+        }
+    }
+    if( spane.items.empty() || liquid_items == static_cast<int>( spane.items.size() ) ) {
```
Comment (ifreund) [inline src/advanced_inv.cpp]:
```suggestion
    if( spane.items.empty() || liquid_items == spane.items.size() ) {
```
