### PR TITLE
Clamp size of loading screen image so loading screen text always shows

### LINKED ISSUE #76359: New loading screen does not display loading progress
### Describe the bug

image

### Attach save file

N/A loading screen

### Steps to reproduce

Load game

### Expected behavior

This should be in the window and visible. (image made by replacing the loading screen image)

loading progress

### Screenshots

_No response_

### Versions and configuration

master dd272dd1852db13f7f4b11af861a06dccf6c8d34

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Bugfixes "GUI Loading screen shows progress again"

#### Purpose of change
* Fixes #76359

#### Describe the solution
Clamp the size of the loading screen image so that there's always room for the text
image

This should preserve aspect ratio of the image, for real this time!

#### Describe alternatives you've considered
~~Stretch the image to use all available space?!~~ I am actually doing that...

#### Testing
Here's another one, with a dummy 1 pixel wide blank image
image

### CODE REVIEW

**Comment by RenechCDDA** [comment]
Hmm I notice the source image for our loading screen is 1365x1024, and so it ends up stretching the aspect ratio despite what I wrote in the comments. Let's see if I can avoid any stretching/compression that changes the aspect ratio.

File: src/loading_ui.cpp [hunk 1]
```diff
@@ -92,7 +92,18 @@ static void update_state( const std::string &context, const std::string &step )
 #ifdef TILES
         cata_path path = PATH_INFO::gfxdir() / "cdda.png";
         SDL_Surface_Ptr surf = load_image( path.get_unrelative_path().u8string().c_str() );
-        gLUI->splash_size = { static_cast<float>( surf->w ), static_cast<float>( surf->h ) };
+        // leave some space for the loading text...
+        ImVec2 max_size = ImGui::GetMainViewport()->Size * 0.9;
+        // since drawing the loading text depends on the width of the loading image(?!), enforce a minimum size
```
Comment (db48x) [inline src/loading_ui.cpp:97]: The text is simply centered relative to the image. It could just as easily be centered relative to the viewport or the window, but I‌ already had the splash size ready to hand so I‌ just wrote it that way. And you don’t actually use `min_size` anyway.

**Review by db48x — CHANGES_REQUESTED** [review]

**Comment by Night-Pryanik** [comment]
@RenechCDDA could you please resolve conflicts?

**Comment by RenechCDDA** [comment]
I have been wasting all my free time on Satisfactory, hopefully I'll get back to this today

File: src/loading_ui.cpp (hunk 1 above)
Comment (RenechCDDA) [reply src/loading_ui.cpp]: (Sorry for the *extremely* late reply, I really was gaming hard with Satisfactory!)

It actually cuts off any text that is outside of the image's width. It is not merely centered, but just plain gone. Actually it seems it's cutting off some pixels on the right-hand side too? This is a roughly 100x100 example loading screen, with a white box around the edge to make it easy to identify.

(This image is from master, without this PR applied)
image

Scaling it both "up" (if below maximum available space) and "down" should resolve both of these issues. Though I'm not sure why the text is like this - it doesn't seem to be how you described it and I don't think it's what you intended.

min_size was just left over from an earlier approach, I removed it now.

Comment (RenechCDDA) [reply src/loading_ui.cpp]: >I'm not sure why the text is like this

Oh it's just because the text is running outside of the gLUI "window", isn't it? 😆

`gLUI->window_size = gLUI->splash_size + ImVec2{ 0.0f, 2.0f * ImGui::GetTextLineHeightWithSpacing() };`

That's funny. There's room for a better way to resolve this but scaling the splash size to 90% of the window does still resolve this. Open to suggestions though.

Also for comparison's sake, here is the loading screen example with this PR applied:

image

Comment (db48x) [reply src/loading_ui.cpp]: Yea, the window size is based on the image size rather than the screen size. I only did that because centering a window takes less typing than centering something inside a window. Like I said in the original PR, I did the easiest thing.

Comment (RenechCDDA) [reply src/loading_ui.cpp]: Just a misunderstanding on my part then. I wasn't thinking about the gLUI itself being a window.

Sounds like this should be resolved? Normal stuff, feel free to unmark this resolved or yell if something's wrong, otherwise marking as resolved. And thanks again for the help.

Comment (db48x) [reply src/loading_ui.cpp]: You’re welcome!

**Review by db48x — APPROVED** [review]
