### PR TITLE
Move Terranian sonar check from `sees` to `sees_with_specials`

### LINKED ISSUE #33855: Terranian Sonar not working as described
# Describe the bug
Terranian Sonar is supposed to show creatures through walls, however it does not work properly.

The creatures the Terranian Sonar show can be viewed from the V-menu or the compass. They do not show tiles wheere they are supposed to be, and using x on their location does not reveal their information.

# Steps To Reproduce
1. Explore an area with walls
2. Spawn a Giant Worm behind the wall
3. Activate Terranian Sonar
4. The Giant Worm will appear in the V-menu and the compass, but does not show a sprite at it's location

# Expected behavior
Seeing the digging monsters through walls when Terranian Sonar is active (as described in player.cpp)

# Screenshots
image
Giant Worm in the V-menu

image
Giant Worm in compass

# Versions and configuration
- OS: MacOs
    - OS Version: Name: Mac OS X; Version: 10.14.2; Build: 18C54; 
- Game Version: 0.D-7355-g235aca2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Vehicle Additions Pack [blazemod]
]

# Additional context
I also tried spawning giant worms in different light levels, but it made no difference to the result.

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Bugfixes "Terranian sonar allow to see digging monsters behind walls"```

#### Purpose of change
Terran sonar allow to see digging monsters behind walls
Fixes #33855

#### Describe the solution
Move Terranian sonar check from `sees` to `sees_with_specials`
Move non IR vision from `sees_with_infrared` to  `sees_with_specials` to allow for #33728 in the futur

This does affect balance a bit since you can no longer know the identity of the burrowing monster like you could before.

#### Testing
Turn on the sonar
Spawn giant worm
You see the Infrared sprite
image

No Giant worm in the V list
Move behind a wall
image

You still see the infra red sprite
Get close to worm
image
You see it normally

### CODE REVIEW

**Comment by ymber** [comment]
This kind of thing should be split from infrared. #33728.

File: src/player.cpp [hunk 1]
```diff
@@ -10112,7 +10106,7 @@ std::vector<Creature *> player::get_targetable_creatures( const int range ) cons
     return g->get_creatures_if( [this, range]( const Creature & critter ) -> bool {
         return this != &critter && pos() != critter.pos() && // TODO: get rid of fake npcs (pos() check)
         round( rl_dist_exact( pos(), critter.pos() ) ) <= range &&
-        ( sees( critter ) || sees_with_infrared( critter ) );
+        ( sees( critter ) || sees_with_infrared( critter ) || sees_with_specials( critter ) );
```
Comment (kevingranade) [inline src/player.cpp]: I'm not sure "targetable" is appropriate here, does this let you aim and fire guns at targets you can detect with sonar?

Comment (Fris0uman) [reply src/player.cpp]: Yes it does, just tested it on Giant worm, you can shoot at it but the shot goes through it and doesn't connect
