### PR TITLE
Fix items with undefined temperature

### LINKED ISSUE #40732: Clean water is frozen when crafted.
When crafting:
image

After putting inside container:
image

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary

SUMMARY: Bugfixes "Fix items with undefined temperature"

#### Purpose of change

Fixes #40732

#### Describe the solution

Two bugs that independently caused same issue.

items were created without defined temperature. Solved by defining their temperature.

Items lost all their unique attributes when they were moved to container. Temperature was the easiest to see but other things like parasites, flags and other attributes would also get lost.
`item::fill_with` took item type and and filled the container with that item type. Now it takes the whole item, creates a copy of it and fills the container with the copied item.

Also changed the gathered liquid bday to be the current turn.

#### Testing

Touches many areas.
Getting liquid from lakes works
Pouring liquid from one container to another works
Pouring liquid to vehicle and siphoning it out work
Magazines that contain liquid work work (flamethrower)

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -4472,17 +4472,21 @@ item &map::add_item( const tripoint &p, item new_item )
 item map::water_from( const tripoint &p )
 {
     if( has_flag( "SALT_WATER", p ) ) {
-        return item( "salt_water", 0, item::INFINITE_CHARGES );
+        item ret( "salt_water", 0, item::INFINITE_CHARGES );
+        ret.set_item_temperature( std::max( temp_to_kelvin( g->weather.get_temperature( p ) ), 277.15 ) );
```
Comment (ZhilkinSerg) [inline src/map.cpp:4476]: `277.15` is used in three more places now, so it would be nice to extract it to static constexpr expression.

Comment (Hirmuolio) [reply src/map.cpp:4476]: `constexpr int cold = 40; // ~4.4 C`  happens to be that already so we can use that.

Comment (Wishbringer) [reply src/map.cpp]: int doesn't match double, some typecasting needed?

File: msvc-full-features/Cataclysm-vcpkg-static.sln [hunk 2]
```diff
@@ -39,7 +39,6 @@ Global
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Debug|x86.ActiveCfg = Debug|Win32
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Debug|x86.Build.0 = Debug|Win32
 		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release|x64.ActiveCfg = Release|x64
-		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release|x64.Build.0 = Release|x64
```
Comment (ZhilkinSerg) [inline msvc-full-features/Cataclysm-vcpkg-static.sln:42]:
```suggestion
		{2C1ECEE1-9686-4C3C-8DE1-88996EE43378}.Release|x64.Build.0 = Release|x64
```

File: msvc-full-features/Cataclysm-vcpkg-static.sln [hunk 3]
```diff
@@ -55,7 +54,6 @@ Global
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Debug|x86.ActiveCfg = Debug|Win32
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Debug|x86.Build.0 = Debug|Win32
 		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Release|x64.ActiveCfg = Release|x64
-		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Release|x64.Build.0 = Release|x64
```
Comment (ZhilkinSerg) [inline msvc-full-features/Cataclysm-vcpkg-static.sln:58]:
```suggestion
		{35D74C75-FC4A-442F-AF44-43BC9D845BAF}.Release|x64.Build.0 = Release|x64
```

File: msvc-full-features/Cataclysm-vcpkg-static.sln (hunk 2 above)
Comment (Hirmuolio) [reply msvc-full-features/Cataclysm-vcpkg-static.sln:42]: Yeah those will be slipping though a bit occaionally. VS doesn't like something about tests and JSON formatter and fails to compile them completelyh.

File: src/activity_handlers.cpp [hunk 4]
```diff
@@ -1588,7 +1588,7 @@ void activity_handlers::fill_liquid_do_turn( player_activity *act, player *p )
         const int original_charges = liquid.charges;
         if( liquid.has_temperature() && liquid.specific_energy < 0 ) {
             liquid.set_item_temperature( std::max( temp_to_kelvin( get_weather().get_temperature( p->pos() ) ),
-                                                   277.15 ) );
+                                                   static_cast<double>( temperatures::cold ) ) );
```
Comment (ZhilkinSerg) [inline src/activity_handlers.cpp:1591]: Isn't `temperatures::cold` in Celsius?

Comment (Hirmuolio) [reply src/activity_handlers.cpp:1591]: It is in farenheit. But that temp_to_kelvin needs to move now since the map temperature and cold temperature are in farenheit but set_item_temperature wants kelvins.

**Comment by Hirmuolio** [comment]
Did some testing with moving liquids around in items. Everything seems to be working.
