### PR TITLE
Fix: Display proficiency progress with more accuracy

### LINKED ISSUE #71167: Displayed progress is different between proficiencies panel and actual description
### Describe the bug

image

Note 2% displayed on the bottom right and 3% in the actual description.

### Attach save file

[Thebes-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14007183/Thebes-trimmed.tar.gz)

### Steps to reproduce

1. Load said save.
2. View player info (whats the keybind again, is it `@`? I set it to ctrl+x for that nethack feel)
3. Admire the buggy progress.

### Expected behavior

Both display the same, like all other profiencies in that save.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 31e4c0e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by inogenous**
#### Summary
Bugfixes "Display proficiency progress with more accuracy"

#### Purpose of change

* Updates proficiency explanation text percentage progress to use two decimals instead of one.
* Fixes #71167 .

#### Describe the solution

* The proficiency list in `@` uses `floor( .progress * 100 )` with format `%2.0f`: https://github.com/CleverRaven/Cataclysm-DDA/blob/1c310e706371fcebdb589ea20e81adb497330a84/src/player_display.cpp#L335-L337
* The proficiency ui reachable by pressing `p` while in `@` uses `.practice * 100.0f` with format `%.2f`: https://github.com/CleverRaven/Cataclysm-DDA/blob/1c310e706371fcebdb589ea20e81adb497330a84/src/proficiency_ui.cpp#L172-L173
* This commit updates the proficiency explanation text percentage progress so that it uses the same formatting as proficiency ui above.

#### Describe alternatives you've considered

* Maybe extract that formatting to a separate reusable function?

#### Testing

Tested the save from #71167 .

snapshot2

Proficiency ui reachable by pressing `p` while in `@` (not changed here)
snapshot3

### CODE REVIEW

**Review by NetSysFire — APPROVED** [review]

File: src/player_display.cpp [hunk 1]
```diff
@@ -364,7 +364,7 @@ static void draw_proficiencies_info( const catacurses::window &w_info, const uns
         if( cur.known ) {
             progress = _( "You know this proficiency." );
         } else {
-            progress = string_format( _( "You are %2.1f%% of the way towards learning this proficiency." ),
+            progress = string_format( _( "You are %.2f%% of the way towards learning this proficiency." ),
```
Comment (Maleclypse) [inline src/player_display.cpp:367]:
```suggestion
            progress = string_format( _( "You are %.2f%% of the way towards learning this proficiency." )
```

File: src/player_display.cpp [hunk 2]
```diff
@@ -364,7 +364,7 @@ static void draw_proficiencies_info( const catacurses::window &w_info, const uns
         if( cur.known ) {
             progress = _( "You know this proficiency." );
         } else {
-            progress = string_format( _( "You are %2.1f%% of the way towards learning this proficiency." ),
+            progress = string_format( _( "You are %.2f%% of the way towards learning this proficiency." )
```
Comment (Maleclypse) [inline src/player_display.cpp:367]:
```suggestion
            progress = string_format( _( "You are %.2f%% of the way towards learning this proficiency." ),
```
