### PR TITLE
Prevent oversized item in pocket after reload

### LINKED ISSUE #44505: Reloaded item inside pocket gives error "cannot fit into pocket while loading: item too big" and disappears
# Describe the bug

You can reload items inside small pockets which makes them no longer fit inside. After saving and loading with such a pocket item disappears and error is generated.

# Steps To Reproduce

1. Create a world with no mods, create a character.
2. Drop all items and clothing.
3. Spawn waistcoat and tailor's kit.
4. Wear the waistcoat.
5. Unload tailor's kit.
6. Put tailor's kit into waistcoat's pocket (it should fit)
7. Reload tailor's kit (you might need a couple of tries if it appears on the ground, there was one time when I somehow dropped it automatically while trying to reproduce, but usually you can reload it).
8. Observe that loaded tailor's kit no longer fits into your pocket.
9. Save.
10. Load.
11. Observe "src/item_contents.cpp:324 [void item_contents::combine(const item_contents&, bool)] error: item tailors_kit cannot fit into pocket while loading: item too big"
12. Move around. Your tailor's kit and 400 thread are gone for good.

# Expected behavior

1. You shouldn't be able to load/reload, activate/deactivate or manipulate item anyhow without taking it out of the pocket (well there might be some exceptions, but they're more exceptions than the rule). So if you want to load, unload, activate or deactivate something, make a check afterwards that the item still fits into the pocket and, if not, ask the player what to do with it (drop, wield. store in inventory).
2. Ensure items do not disappear on load. there might be many reasons why item size has changed (normally a bug or a change related to capacity of the container's pockets or size of the item. There might a another not yet discovered bug that could cause similar error. My character had a spare tailor's kit, but in some cases losing an item on load might be a death sentence. Drop item on the ground or generate a message but keep it in the pocket, it won't be a game-breaker.

# Screenshots

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-6384-ge4f17b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [] (English)
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm],
    Bionic Slots [cbm_slots],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5300847/debug.log)

Save file has empty world with a waistcoat-wearing character, tailor's kit and 400 thread. Reload tailor's kit to reproduce.
[Pocket issue replicator.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5300873/Pocket.issue.replicator.zip)

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

SUMMARY: Bugfixes "Prevent oversized item remaining in pocket after reload"

#### Purpose of change

Fixes #44505

Some items could expand after a reload. It would only be a problem if it exceeded the limit of the container or location. This avoids the problem by not allowing the item to remain in the same location.

#### Describe the solution

The volume and weight limit - if applicable - of the storage space are checked whether they have exceeded the limits. If so, the item is wielded or dropped. All item_location types are checked.

Player inventory will wield the item if hands are free, otherwise the item will be dropped. Other locations will have the player drop the item on the nearest available space.

In any case the player is given a message to inform them what has happened.

#### Describe alternatives you've considered

To prevent the reload in the first place would be an alternative. I think it would be more troublesome to implement however.

#### Testing
Full test program. No related problems.

Tested with inventory, map location, and vehicle storage. Tested with soldering iron using heavy battery mod, and with oxy-acetylene torch. 
1. Filled inventory to maximum with the tool. Tool and reload item not starting in the same pocket. Reloaded tool. 
2. Observed destination and source of tool being moved due to tool expansion.
3. Confirmed tool is moved correctly and reliably.

### CODE REVIEW

File: src/item.h [hunk 1]
```diff
@@ -853,6 +853,12 @@ class item : public visitable<item>
         void reset_temp_check();
 
         int get_comestible_fun() const;
+        /**
+        * Find the containing pocket for this item in the character's inventory.
+        * @param who Character holding the item.
+        * @returns item_pocket Containing pocket. nullptr if not found.
+        */
+        item_pocket &get_containing_pocket( Character &who );
```
Comment (Aivean) [inline src/item.h:861]: It returns a reference, not a pointer. Contrary to the description it won't return `nullptr` if nothing is found, it will crash trying to dereference `nullptr`.

File: src/activity_actor.cpp [hunk 2]
```diff
@@ -2351,6 +2351,50 @@ void reload_activity_actor::finish( player_activity &act, Character &who )
     } else {
         add_msg( m_neutral, _( "You reload the %1$s with %2$s." ), reloadable_name, ammo_name );
     }
+    item_location loc = reload_targets[0];
+    tripoint point = loc.position();
+    // Reload may have caused the item to increase in size more than the pocket can contain.
+    // We want to avoid this because items will be deleted on a save/load.
+    if( loc.where() == item_location::type::container &&
+        loc.held_by( who ) ) {
+        item_pocket pocket = reloadable.get_containing_pocket( who );
```
Comment (Aivean) [inline src/activity_actor.cpp:2360]: `reloadable` comes from `reload_targets`, which has `item_location` type. `item_location` allows to get `parent` directly. When you have parent, you can use `item::contained_where` to find parent's pocket where item is contained.

**Review by Aivean — CHANGES_REQUESTED** [review]
I think that `get_containing_pocket` method is not needed, there is a better way to find the pocket already.

Please take a closer look at `item_location`, if you use its API your code could be simplified.

Also, consider adding capacity calculating method to the `item_location`, this way you can collapse these three nearly-identical branches into one.

Finally, don't use references to the item after item is removed (or moved). Such references become invalid and will trigger a crash.

File: src/activity_actor.cpp [hunk 3]
```diff
@@ -2351,6 +2351,50 @@ void reload_activity_actor::finish( player_activity &act, Character &who )
...
+                item replace = reloadable;
+                who.remove_item( reloadable );
+                add_msg( m_neutral, _( "The %s no longer fits in your inventory so you drop it instead." ),
+                         reloadable_name );
+                get_map().add_item_or_charges( point, replace );
+            }
+        }
+        // Check if in a vehicle.
+    } else if( loc.where() == item_location::type::vehicle ) {
+        const cata::optional<vpart_position> vp = get_map().veh_at( point );
```
Comment (Aivean) [inline src/activity_actor.cpp:2377]: Same here, you can get the vehicle and part index from the `item_location` directly.

File: src/activity_actor.cpp [hunk 4]
```diff
@@ -2351,6 +2351,50 @@ void reload_activity_actor::finish( player_activity &act, Character &who )
...
+        const cata::optional<vpart_reference> vp_cargo = vp->part_with_feature( "CARGO", true );
+        units::volume capacity = vp->vehicle().free_volume( vp_cargo->part_index() );
+        if( capacity < units::volume() ) {
+            item replace = *loc.get_item();
+            loc.remove_item();
+            add_msg( m_neutral, _( "The %s no longer fits in the storage compartment so you drop it instead." ),
+                     replace.tname() );
```
Comment (Aivean) [inline src/activity_actor.cpp:2384]: Accessing item after it was removed using `loc.remove_item();` will cause a crash.

File: src/activity_actor.cpp (hunk 2 above)
Comment (RoyBerube) [reply src/activity_actor.cpp:2360]: Will look into that.

File: src/activity_actor.cpp (hunk 3 above)
Comment (RoyBerube) [reply src/activity_actor.cpp:2377]: Ok will take a look.

File: src/activity_actor.cpp (hunk 4 above)
Comment (RoyBerube) [reply src/activity_actor.cpp:2384]: The intention is for replace to be a copy. I'll take another look at it.

File: src/item.h (hunk 1 above)
Comment (RoyBerube) [reply src/item.h:861]: Will probably remove this method anyway once I look it over again.

File: src/activity_actor.cpp (hunk 4 above)
Comment (Aivean) [reply src/activity_actor.cpp:2384]: My bad, you're right. I mistook `item` for `item &`.

File: src/activity_actor.cpp (hunk 2 above)
Comment (RoyBerube) [reply src/activity_actor.cpp:2360]: Ok have removed the get_containing_pocket() addition and changed it to use the item_location. It makes more sense; I should know better.

**Comment by RoyBerube** [comment]
Essentially rewrote it. Thanks for the suggestions Aivean.

**Review by Aivean — APPROVED** [review]
I haven't tested it, but overall looks good. 

Thank you for spending your time to refactor it.

File: src/activity_actor.cpp [hunk 5]
```diff
@@ -2351,6 +2351,31 @@ void reload_activity_actor::finish( player_activity &act, Character &who )
...
+    // We want to avoid this because items will be deleted on a save/load.
+    if( loc.volume_capacity() < units::volume() ||
+        loc.weight_capacity() < units::mass() ) {
+        // In player inventory and player is wielding nothing.
+        if( !who.is_armed() && loc.held_by( who ) ) {
+            add_msg( m_neutral, _( "The %s no longer fits in your inventory so you wield it instead." ),
+                     reloadable_name );
+            who.wield( reloadable );
+        } else {
+            item replace = reloadable;
```
Comment (kevingranade) [inline src/activity_actor.cpp:2365]:
```suggestion
            const item &replace = reloadable;
```

Comment (kevingranade) [inline src/activity_actor.cpp:2365]:
```suggestion
```

File: src/activity_actor.cpp [hunk 6]
```diff
@@ -2351,6 +2351,31 @@ void reload_activity_actor::finish( player_activity &act, Character &who )
...
+            // In player inventory and player is wielding something.
+            if( loc.held_by( who ) ) {
+                add_msg( m_neutral, _( "The %s no longer fits in your inventory so you drop it instead." ),
+                         reloadable_name );
+                // Default handling message.
+            } else {
+                add_msg( m_neutral, _( "The %s no longer fits its location so you drop it instead." ),
+                         reloadable_name );
+            }
+            get_map().add_item_or_charges( loc.position(), replace );
```
Comment (kevingranade) [inline src/activity_actor.cpp:2375]:
```suggestion
            get_map().add_item_or_charges( loc.position(), reloadable );
```
