### PR TITLE
Fragmentation armor fix

### LINKED ISSUE #24796: Bomb fragments deal too much damage to armored targets.
Game version:
Since #24171 
Operating system:
All
Tiles or curses:
Both
Mods active:
Any
### Expected behavior
Small fragmentation explosives deal significant damage to unarmored targets, but are easily blocked by armor.
### Actual behavior
Small fragmentation explosives easily penetrate armor.
### Steps to reproduce the behavior
Spawn and wear a full survivor suit.
Spawn, arm and throw a grenade 8 tiles away.
When the grenade goes off, you should survive, but with the current code you frequently die.
(need to double check coverage, if it's simply bypassing the armor due to lack of coverage, it's working as intended.)

Spawn and wear a light power armor and light power armor helmet.
Spawn, arm and throw a grenade 3 squares away.
As above, you should avoid all damage.

Based on a post on discourse: https://discourse.cataclysmdda.org/t/personal-opnion-explosions-are-overbuffed-with-two-examples-updated-see-new-long-post-by-me/16058/24?u=kevin.granade

### PR DESCRIPTION
**Pull request by kevingranade**
Fixes #24796 
Fixes #24863
Drops fragment damage a bit overall, and also decreases fragment size.
The result is there are about 10x as many fragments flying around, but they deal about 1/20th the damage they did previously, so they dont defeat armor.

- [x] cant damage power armor. (Even light)
- [x] minimal damage to vehicles.
- [x] minimal damage to buildings.
- [x] avoid log spam from huge numbers of fragments.

This is built on top of the perf fix.

### CODE REVIEW

**Comment by kevingranade** [comment]
Well that was super not fun, it was quite a pain to generate these messages.
Even better, I'm not 100% that they're at the right level of detail, let me know what you think.

File: src/explosion.cpp [hunk 1]
```diff
@@ -435,93 +435,115 @@ std::vector<tripoint> game::shrapnel( const tripoint &src, int power,
...
-                if( m.impassable( target ) ) {
-                    if( optional_vpart_position vp = m.veh_at( target ) ) {
-                        vp->vehicle().damage( vp->part_index(), damage );
+                int total_hits = damaging_hits + non_damaging_hits;
+                if( total_hits > 0 && g->u.sees( *critter ) ) {
+                    // Building a phrase to summarize the fragment effects.
+                    // Target, Number of impacts, total amount of damage, proportion of deflected fragments.
+                    std::map<int, std::string> impact_count_descriptions = {
+                        { 1, _( "a" ) }, { 2, _( "several" ) }, { 5, _( "many" ) },
+                        { 20, _( "a large number" ) }, { 100, _( "a huge number" ) }
```
Comment (narc0tiq) [inline src/explosion.cpp]: As this will be used in, e.g., "[You are/NPC is/The Monster is] hit by %s bomb fragments", I think you want "a [large/huge] number ***of***".

**Comment by ZhilkinSerg** [comment]
Game hangs when you explode grenade in your inventory while wearing decent armor (full winter survivor suit with hood, gloves, boots, and mask).

**Comment by kevingranade** [comment]
hrm, that is a rather large number of projectiles to handle, I wonder if I can shortcut that by comparing the potential damage vs the armor and skipping all the special effects if it has no possibility of dealing damage.

Also I'll just profile it, should be pretty straightforward to reproduce, there might be something dumb happening in there... ooh, like an animation delay.

**Comment by kevingranade** [comment]
Final commit should adress the hang, player::deal_damage was drawing thousands of hitboxes for all the non-damaging fragment hits, and waiting for thousands of animation delay-length ticks.

**Comment by ZhilkinSerg** [comment]
Performance is much better now - still noticeable "Hang on a bit" message sometimes, but game doesn't hang.

Grenade explosions seems to be a little underpowered as I couldn't shatter car windshields from a single explosion, but it looks the same in `master` branch.

I guess it is good to be merged now.

**Comment by kevingranade** [comment]
That's working as expected, fragment shouldn't hard targets, but the blast
itself would, and blasts haven't been fixed.

File: src/explosion.cpp [hunk 2]
```diff
@@ -435,93 +435,116 @@ std::vector<tripoint> game::shrapnel( const tripoint &src, int power,
...
+                        critter->add_msg_if_npc(
+                            ngettext( "<npcname> is hit by %s bomb fragment, %s.",
+                                      "<npcname> is hit by %s bomb fragments, %s.",
+                                      total_hits ),
+                            impact_count, damage_description );
                     } else {
-                        m.bash( target, damage / 10, true );
+                        add_msg( ngettext( "The %s is hit by %s bomb fragment, %s.",
+                                           "The %s is hit by %s bomb fragments, %s.", total_hits ),
+                                 critter->disp_name().c_str(), impact_count, damage_description );
```
Comment (narc0tiq) [inline src/explosion.cpp]: I just noticed this creates lines like "The the zombie is hit..." and "The the crawling zombie....". I think you wanted `critter->get_name()` instead?

**Comment by KurzedMetal** [comment]
Shouldn't this merge close #24748 and probably #24861 too?

**Comment by CoroNaut** [comment]
I ran over a landmine by accident going 60kph in my bike and all it did was damage my stethoscope i was wearing by 1 point, didn't even damage the vehicle any. Is this intentional or did I get extremely lucky to not have 2 bikes with 1 wheel each?
