### PR TITLE
Don't unnecessarily copy items in a tight loop in get_uncraft_components

### LINKED ISSUE #73502: Analyzing the perfomance of hot dogs
### Describe the bug

While playing the game, i made a lot of hotdogs, put them all in the same vehicle tile, and found my PC needs at least two seconds to open AIM with said hotdogs
image
Perfomance analyzer shows enormous amount of hits in uncraft components
image
Further discussion and @RenechCDDA making suggestions is [here](https://discord.com/channels/598523535169945603/598529174302490644/1236041870518521876), tho i barely undestand where exactly the problem is, but i guess the game, for some reason, scan all the food to check their disassembly components

### Attach save file

[Freedom-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15209322/Freedom-trimmed.tar.gz)

### Steps to reproduce

open the save file
open AIM pointing to south west ↙
notice the lag

### Expected behavior

no lag

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-01-0547 5590543 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Work in Progress Limb Stuff [limb_wip],
    Mind Over Matter [mindovermatter]
]

### Additional context

_No response_

### LINKED ISSUE #76514: Examining or opening advanced inventory on a tile with a lot of cooked foodstuffs causes big slowdown when it tries to stack items
### Describe the bug

If you have like 200-300 already-cooked foodstuffs on a tile and examine or use advanced inventory on that tile to get the contents, there is a slowdown. This is due to it grabbing the crafting components of said food to check if it can stack everything together. 

As you can see from the flame graph below, when I open advanced inventory and select the tile with cooked meat, most of the cpu time is spent on `get_uncraft_components` while it tries to stack each individual item.

### Attach save file

[TESTINGTWO-trimmed.tar.gz](https://github.com/user-attachments/files/17041100/TESTINGTWO-trimmed.tar.gz)

### Steps to reproduce

1. Load save or alternatively craft a crap ton of food yourself
2. examine the freezer with 500 cooked meats and notice a slowdown.
3. Open advanced inventory manager and set a pane to look at that tile, notice a slowdown.

### Expected behavior

Food should not save its crafting components like electronics, clothing, armor, vehicle parts, etc. It is food. Once it's cooked or transformed, it can't be disassembled, and this is enforced in-game. It is completely unused information from the games' perspective, saved and forgotten.

The only use for it is the `Made from` section for food. I definitely don't think this is worth keeping around when it causes this much slowdown. I'm sure we could go without this tidbit of information as we play the game.

My proposal is to remove the crafting ingredients from food. This will make the stacking code much faster, and will barely affect the user experience, except for increased performance.

### Screenshots

opening fridge with cooked items3
Untitled

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: cdda-experimental-2024-09-18-0513 7b773c1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by akrieger**
#### Summary
Performance "Fix lag examining large stacks of crafted items"

#### Purpose of change
Fixes #76514. Fixes #73502. A performance problem was reported. The performance problem smasher showed up for duty.

#### Describe the solution
Inside `get_uncraft_components`, take the inner loop `item` by ref for the lambda to `std::find_if`.

#### Testing
`e`xamine the repro save freezer full of food three times before/after.

image

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -14909,7 +14909,7 @@ std::vector<item_comp> item::get_uncraft_components() const
                     continue;
                 }
                 // NOLINTNEXTLINE(clang-analyzer-cplusplus.NewDeleteLeaks)
```
Comment (RenechCDDA) [inline src/item.cpp:14911]: Is this compiler instruction still relevant? It was added in #65902 to suppress an apparent false positive, but given that we were copying the items...

Now AFAIK Pass-by-copy into a lambda should create a temporary which goes out of scope and is automatically `delete`d, but I would generally trust clang's opinion? Worth pointing out to you if nothing else

Comment (akrieger) [reply src/item.cpp:14911]: Apparently not anymore!
