### PR TITLE
Make a code for prof migration

### LINKED ISSUE #83571: Error on launch after slime weakpoint proficiencies were removed
### Describe the bug

 It appears that the game does not handle proficiency removal migration. I get an error on launch after #83554 was merged. Pressing "I" does not prevent the message from appearing on subsequent launches. There is also a ghost proficiency in the @ screen proficiency list that doesn't get removed even after toggling all proficiencies as unknown.

```
DEBUG : invalid proficiency id "prof_wp_slime_basic"

 REPORTING FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = proficiency]
 C++ SOURCE FILE    : src/generic_factory.h
 LINE               : 506
 VERSION            : cdda-experimental-2025-11-02-1519 f73f3fc
```

### Attach save file

[Iowa Point-trimmed.tar.gz](https://github.com/user-attachments/files/23317245/Iowa.Point-trimmed.tar.gz)

### Steps to reproduce

Try to launch my save on latest experimental.

Edit player in debug menu and toggle all proficiencies off, there is a ghost proficiency in the list. See screenshot.

### Expected behavior

I expect to not have an error appear each time I open the game, and for there to be a bugged proficiency in my proficiency list forever.

### Screenshots

Image

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: cachyos; Description: CachyOS; Release: rolling; Codename: n/a; 
- Game Version: cdda-experimental-2025-11-02-1519 f73f3fc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

If my save doesn't work, I imagine that creating a character before that pr, adding the proficiency, then updating the game to the latest and opening would also create the error.

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Fix #83571
#### Describe the solution
Add a code to handle prof migration, use it
#### Testing
Save from issue loads with no error now

### CODE REVIEW

File: src/proficiency.h [hunk 1]
```diff
@@ -151,6 +151,9 @@ class proficiency_set
         std::vector<proficiency_id> known_profs() const;
         std::vector<proficiency_id> learning_profs() const;
 
+        cata::flat_set<proficiency_id> &known_profs_mod();
+        std::vector<learning_proficiency> &learning_profs_mod();
+
```
Comment (ehughsbaird) [inline src/proficiency.h]: You can make a `migrate_prof` function instead of exposing these and keep better encapsulation.

File: src/proficiency.h [hunk 2]
```diff
@@ -225,6 +228,22 @@ class book_proficiency_bonuses
         float time_factor( const proficiency_id &id ) const;
 };
 
+class proficiency_migration
+{
+    public:
+        proficiency_id id_old;
+        proficiency_id id_new;
```
Comment (ehughsbaird) [inline src/proficiency.h]: Make this optional and you can use `null` or omit it to remove, instead of requiring a dummy `"null"` proficiency that isn't used.
```suggestion
        std::optional<proficiency_id> id_new;
```

File: src/savegame_json.cpp [hunk 3]
```diff
@@ -766,6 +766,38 @@ void Character::load( const JsonObject &data )
...
+            if( m->id_new == proficiency_id::NULL_ID() ) {
+                it = profs_learned->erase( it );
+            } else {
+                *p_id = m->id_new;
+            }
+        } else {
+            ++it;
+        }
+    }
+
```
Comment (ehughsbaird) [inline src/savegame_json.cpp:770]:
```suggestion
    _proficiencies->migrate_proficiencies();
```

Cleaned up and fixed a few bugs (inserting while iterating over, infinite loop if the proficiency in `learn` is replaced instead of removed).
```c++
void proficiency_set::migrate_proficiencies()
{
    // it's not safe to insert while iterating
    std::vector<proficiency_id> to_know;
    for( auto it = known.begin(); it != known.end(); ) {
        const proficiency_migration *m = proficiency_migration::find_migration( *it );
        if( m != nullptr ) {
            if( m->id_new.has_value() ) {
                to_know.push_back( m->id_new.value() );
            }
            it = known.erase( it );
        } else {
            ++it;
        }
    }
    for( const proficiency_id &prof : to_know ) {
        known.insert( to_know );
    }

    for( auto it = learned.begin(); it != learned.end(); ) {
        const proficiency_migration *m = proficiency_migration::find_migration( it->id );
        if( m != nullptr ) {
            if( !m->id_new.has_value() ) {
                it = profs_learned->erase( it );
                continue;
            }
            it->id = m->id_new.value();
        }
        ++it;
    }
}
```

File: src/proficiency.cpp [hunk 4]
```diff
@@ -658,3 +670,40 @@ float book_proficiency_bonuses::time_factor( const proficiency_id &id ) const
...
+{
+    proficiency_migration *migration = nullptr;
+
+    const auto &migration_it = prof_migrations.find( original );
+    if( migration_it == prof_migrations.cend() ) {
+        return migration;
+    }
+    migration = &migration_it->second;
+
+    return migration;
```
Comment (ehughsbaird) [inline src/proficiency.cpp]: Typically you don't make references (even const ones) to iterators.
You can also just return the values directly, instead of making a variable to store them.
```suggestion
    const auto migration_it = prof_migrations.find( original );
    if( migration_it == prof_migrations.cend() ) {
        return nullptr;
    }
    return &migration_it->second;
```

**Review by ehughsbaird — CHANGES_REQUESTED** [review]

File: src/proficiency.cpp (hunk 4 above)
Comment (GuardianDll) [reply src/proficiency.cpp]: That was a copy (with some adjustments) of vpart_migration::find_migration(), but okay

Comment (ehughsbaird) [reply src/proficiency.cpp]: It is required for that because it handles chain migrations.

File: doc/JSON/OBSOLETION_AND_MIGRATION.md [hunk 5]
```diff
@@ -147,6 +147,22 @@ A mutation migration can be used to migrate a mutation that formerly existed gra
...
 
+# Proficiency migration
+
+Prof migration can be migrated to new prof (with progress being transferred) or to null
+
+```jsonc
+  {
+    "type": "proficiency_migration",
+    "from": "prof_wp_slime_basic",  // Mandatory. Id of the prof that has been removed.
+    "to": "prof_wp_mi-go_basic"     // Mandatory. Id of the new prof that will be set instead. can be omitted to remove the prof
```
Comment (ehughsbaird) [inline doc/JSON/OBSOLETION_AND_MIGRATION.md]:
```suggestion
    "to": "prof_wp_mi-go_basic"     // Optional. Id of the new prof that will be set instead. can be omitted to remove the prof
```

File: src/proficiency.h [hunk 6]
```diff
@@ -225,6 +226,22 @@ class book_proficiency_bonuses
         float time_factor( const proficiency_id &id ) const;
 };
 
+class proficiency_migration
+{
+    public:
+        std::optional<proficiency_id> id_old;
```
Comment (ehughsbaird) [inline src/proficiency.h]: Why is this optional?

File: src/proficiency.cpp [hunk 7]
```diff
@@ -658,3 +660,67 @@ float book_proficiency_bonuses::time_factor( const proficiency_id &id ) const
...
+
+void proficiency_migration::check()
+{
+    for( const auto &[from_id, _] : prof_migrations ) {
+        const proficiency_migration &pm = *find_migration( from_id.value() );
+        if( pm.id_new.has_value() && !pm.id_new.value().is_valid() ) {
+            debugmsg( "proficiency migration specifies invalid id '%s'", pm.id_new.value().str() );
+            continue;
+        }
+    }
```
Comment (ehughsbaird) [inline src/proficiency.cpp]:
```suggestion
    for( const auto &[from_id, pm] : prof_migrations ) {
        if( pm.id_new.has_value() && !pm.id_new.value().is_valid() ) {
            debugmsg( "proficiency migration specifies invalid id '%s'", pm.id_new.value().str() );
            continue;
        }
    }
```

File: src/proficiency.h (hunk 6 above)
Comment (GuardianDll) [reply src/proficiency.h]: Because i'm an idiot, obv

**Review by ehughsbaird — APPROVED** [review]

File: src/proficiency.cpp [hunk 8]
```diff
@@ -17,6 +17,8 @@ const float book_proficiency_bonus::default_time_factor = 0.5f;
 const float book_proficiency_bonus::default_fail_factor = 0.5f;
 const bool book_proficiency_bonus::default_include_prereqs = true;
 
+static std::map<std::optional<proficiency_id>, proficiency_migration> prof_migrations;
```
Comment (GuardianDll) [inline src/proficiency.cpp]:
```suggestion
static std::map<proficiency_id, proficiency_migration> prof_migrations;
```
