### PR TITLE
World Generation Instructions Rework (Fix for #18394)

### LINKED ISSUE #18394: World creation is confusing. New users get stuck.
New users are often confused by the need to hit > on the world creation screen.
I myself experienced this problem when I was new.
I see this question a lot on Reddit and other places.

image

Could the key be changed to a more uniform one?  Or maybe a prominent help text could be added?

### PR DESCRIPTION
**Pull request by Shinino**
#### Summary
Bugfixes: World Generation Instructions Rework

#### Purpose of change
Closes #18394 

Changed menu to be more clear and changed menu behavior on this screen to be consistent with every other menu.

#### Describe the solution
Changed the text of the instructions to be clear (further edits can be made), explaining what key does what.  Also, as this menu is the only time that the top bar uses '>' while the lower bar uses 'Tab' and 'Backtab', changed this menu to use '<' and '>' for choosing mods, and 'TAB' and 'BACKTAB' to be consistent with every other top-level menu in the game.

#### Describe alternatives you've considered
The only alternative I originally considered what changing every -other- menu to use NEXT_CATAGORY_TAB instead of NEXT_TAB -- then realized that this was easier, quicker and much more elegant of a solution.

#### Additional context
clipboard02

### CODE REVIEW

File: src/worldfactory.cpp [hunk 1]
```diff
@@ -1510,4 +1515,4 @@ void worldfactory::delete_world( const std::string &worldname, const bool delete
     } else {
         get_world( worldname )->world_saves.clear();
     }
-}
+}
```
Comment (cosmiccoincidence) [inline src/worldfactory.cpp]: Add a blank line at the end of this file.

File: src/worldfactory.cpp [hunk 2]
```diff
@@ -1251,9 +1252,13 @@ void worldfactory::draw_modselection_borders( const catacurses::window &win, con
 
     // Add tips & hints
     fold_and_print(win, FULL_SCREEN_HEIGHT - 7, 2, getmaxx(win) - 4, c_green,
-                   _("Press %s to save the list of active mods as default. Press %s for help."),
+                   _("Press %s = Save Load Order as default.  %s = Controls %s/%s= Prev/Next Option. %s/%s = Prev/Next Tab."),
```
Comment (Night-Pryanik) [inline src/worldfactory.cpp]: "Press X = " sounds weird. Old "Press X to ~win~ save..." was better. Or remove the "Press" part.
Also, decapitalize all text. 
Also, add a space in `%s/%s=`.

Comment (Shinino) [reply src/worldfactory.cpp]: Good point there.  And yeah, I wasn't sure if %s/%s or %s / %s was better.  Changes made.

File: src/worldfactory.cpp (hunk 1 above)
Comment (Shinino) [reply src/worldfactory.cpp]: Thank you, I was a bit sleep deprived yesterday :)

File: data/raw/keybindings.json [hunk 3]
```diff
@@ -1540,13 +1540,9 @@
         "id": "NEXT_TAB",
         "name": "Go to next tab",
         "bindings":[
-            {
+                        {
```
[the remark this answers is not in the document]
Comment (Shinino) [reply data/raw/keybindings.json]: Ran this through the validator and linter.  That should resolve all three comments.  Thanks!

File: src/worldfactory.cpp (hunk 2 above)
Comment (Night-Pryanik) [reply src/worldfactory.cpp]: Uhmm, sorry for not being clear enough. I mean add space between `%s/%s` and `=`. I liked the old way (`%s/%s`) by the way.

**Comment by Shinino** [comment]
Just curious (as I'm learning), I can't see what changed on worldfactory.cpp -- what was it?

**Comment by TheEskir** [comment]
How do I get a version without this change? It's bugging me immensely.

**Comment by ZhilkinSerg** [comment]
> 
> 
> How do I get a version without this change? It's bugging me immensely.

Just change your keybindings.
