### PR TITLE
Reset mount moves on dismount

### LINKED ISSUE #32463: Horse sounds lag the game upon dismounting
# Describe the bug
When you ride a horse for a long time and then dismount, the game lags massively to the point of freezing, depending on how long you have been riding. After riding a couple of map screens worth of distance, I dismounted, the game froze for a couple of minutes; then I got a message that said "You hear footsteps. x1559952" and the game resumed.

# Steps To Reproduce

1. Tame horse.
2. Ride horse for a long distance.
3. Dismount.

# Expected behavior
Game shouldn't lag severely.

# Screenshots
Screenshot_2

# Versions and configuration

- OS: Windows 7
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-5703-g850f19c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mutant NPCs [mutant_npcs],
    Mythical Martial Arts [MMA],
    No Flaming Weapons [no_flaming_weapons],
    Classes and Scenarios Mod [more_classes_scenarios],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills],
    Mythological Replicas [nw_pack],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots]
]

# Additional context

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Reset mount moves on dismount"```

#### Purpose of change
Fixes #32463 

#### Describe the solution
Horses - all mounts, stored up their moves while you are riding them, and never used them.
So it was quite possible for them to have 100,000 moves + after a while.
Then when you dismounted, they used all of them at once.
This resulted in lag, sound /message spam, and often,t he horse zooming off into the distance.
#### Describe alternatives you've considered
N/A

#### Additional context
N/A

### CODE REVIEW

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/horse-went-poof/21132/4

File: src/player.cpp [hunk 1]
```diff
@@ -11013,6 +11013,8 @@ void player::forced_dismount()
     bool mech = false;
     if( mounted_creature ) {
         auto mon = mounted_creature.get();
+        // monster has been storing up moves while riding, reset them now so it dosnt zoom off.
```
Comment (BevapDin) [inline src/player.cpp]: Would be a much better fix if the monster would *not* store up their moves. The current fix just hides the problem after it has already been created.

Comment (davidpwbrown) [reply src/player.cpp]: Yep, this was my original fix, Other devs advised that it might be cleaner to put it all here.
But I can just add a check for mountedness in creature.cpp where moves are regenerated.

**Comment by jeremyshannon** [comment]
It might be worth giving the mount a few free moves to use when you're forcibly dismounted. When dismounting voluntarily, a horse should (hopefully) stand there while you do it, but when a brute knocks you flying out of the saddle it would probably look less goofy if the horse were to jump away in the process, rather than just stand there with a surprised look on his face.

**Comment by davidpwbrown** [comment]
> It might be worth giving the mount a few free moves to use when you're forcibly dismounted. When dismounting voluntarily, a horse should (hopefully) stand there while you do it, but when a brute knocks you flying out of the saddle it would probably look less goofy if the horse were to jump away in the process, rather than just stand there with a surprised look on his face.

It will get its moves as normal as soon as your dismounted. it will be able to react just as quickly as the player does.

And infact often its the horse that is hulk smashed and yeeted long distance, which prompts the forced dismount,  so they would react in the same way as the player would then aswell, or any other monster smashed by a julk.

**Comment by jeremyshannon** [comment]
> It will get its moves as normal as soon as your dismounted. it will be able to react just as quickly as the player does.
I'm aware, it just seems like the mount, who is technically able to move on his own and only held back by the riding code, should react as it happens instead of after you land. Which I think is not entirely feasible, but might be approximated by giving him some extra moves.

**Comment by kevingranade** [comment]
The current status of this is that the mount's moves when the player mounts them is preserved through the riding process, so when the player is dismounted, the mount is most likely going to have a non-zero number of moves.
