### PR TITLE
monsters: add a check for vehicles before drowning

### LINKED ISSUE #33559: Cow on boat immediately drowns
# Describe the bug

If a cow is in the seat of your boat, it will drown in deep water.

# Steps To Reproduce

1: Create a cow and a boat.
2: Tame the cow and lead it onto the boat. Optionally tie it in place.
3: Sail onto the water.
4: The cow drowns.

# Expected behavior

Cows, like NPCs, would be expected to not drown when sitting in a boat.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-6964-g60e0ca9 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda]
]

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "monsters: add a check for vehicles before drowning"```

#### Purpose of change
Fixes #33559

Monsters drown in deep water, even if they're in a vehicle.  Monsters in a vehicle shouldn't drown.

#### Describe the solution
Unify the two bits of code in monmove.cpp that check for drowning and add a check for a vehicle before drowning a monster.  If there is a vehicle at the monster's location, don't drown it.

#### Additional context
Tested by spawning a boat and a cow.  I brought the cow onto the boat and drove around the deep water of a lake.  The cow did not drown.

### CODE REVIEW

File: src/monmove.cpp [hunk 1]
```diff
@@ -1723,13 +1736,9 @@ void monster::knock_back_to( const tripoint &to )
...
-        if( g->m.has_flag( "LIQUID", to ) && can_drown() ) {
-            die( nullptr );
-            if( u_see ) {
-                add_msg( _( "The %s drowns!" ), name() );
-            }
-
-        } else if( has_flag( MF_AQUATIC ) ) { // We swim but we're NOT in water
+        // die_if_drowning will kill the monster if necessary, but if the deep water
+        // tile is on a vehicle, we should check for swimmers out of water
+        if( !die_if_drowning( to, 1 ) && has_flag( MF_AQUATIC ) ) {
```
Comment (Night-Pryanik) [inline src/monmove.cpp]: Nitpick, but chance = 1 is default.
```suggestion
        if( !die_if_drowning( to ) && has_flag( MF_AQUATIC ) ) {
```

File: src/monmove.cpp [hunk 2]
```diff
@@ -536,6 +536,23 @@ static float get_stagger_adjust( const tripoint &source, const tripoint &destina
     return std::max( 0.01f, initial_dist - new_dist );
 }
 
+bool monster::die_if_drowning( const tripoint &at_pos, const int chance )
+{
+    if( g->m.has_flag( "LIQUID", at_pos ) && can_drown() && one_in( chance ) ) {
+        vehicle *veh = veh_pointer_or_null( g->m.veh_at( at_pos ) );
+        // if there's a vehicle here, the monster is on it and not drowning
```
Comment (BevapDin) [inline src/monmove.cpp]: This should check for boardable parts. A zombie standing on a wing mirror would like interesting, but it's not even close to being realistic.

Comment (mlangsdorf) [reply src/monmove.cpp]: Fixed, thanks.

File: src/monmove.cpp [hunk 3]
```diff
@@ -536,6 +536,25 @@ static float get_stagger_adjust( const tripoint &source, const tripoint &destina
     return std::max( 0.01f, initial_dist - new_dist );
 }
 
+bool monster::die_if_drowning( const tripoint &at_pos, const int chance )
+{
+    if( g->m.has_flag( "LIQUID", at_pos ) && can_drown() && one_in( chance ) ) {
+        // if there's a vehicle here with a boardable part, the monster is on it
+        // and not drowning
+        const cata::optional<vpart_reference> bp = g->m.veh_at( at_pos ).part_with_feature( "BOARDABLE",
```
Comment (BevapDin) [inline src/monmove.cpp]:
```suggestion
        if( g->m.veh_at( at_pos ).part_with_feature( "BOARDABLE", false ) ) {
```
The variable `bp` is not needed.

Comment (mlangsdorf) [reply src/monmove.cpp]: Fixed, thanks.
