### PR TITLE
Rain fills all

### LINKED ISSUE #24251: Funnel doesn't fill containers that are not sealable
### Expected behavior
After leaving an opened tin can, opened aluminum can or opened plastic cup in the rain with a funnel, there should be collected water after some time.

### Actual behavior
The game doesn't consider these watertight containers as eligible to collect water.

### Steps to reproduce the behavior
Place an opened plastic cup under a funnel in the rain.

### PR DESCRIPTION
**Pull request by lucasmr**
Fixes #24251. This commit does some refactoring as well. Added function is_watertight_resealable_container() and changed every call from is_watertight_container() to it, except one: rain now checks if a container is only watertight to be filled with water. Other possible changes from is_watertight_resealable_container() to is_watertight_container() should be looked into another PR.

Edit: after rebase, refactoring and new function are not needed.

### CODE REVIEW

**Comment by lucasmr** [comment]
Worth to note, a funnel is still needed.

File: src/item.h [hunk 1]
```diff
@@ -545,6 +545,8 @@ class item : public visitable<item>
     bool is_container() const;
     /** Whether this is a container which can be used to store liquids. */
     bool is_watertight_container() const;
+    /** Wheter this is a container that is both watertight and sealable. */
```
Comment (Rivet-the-Zombie) [inline src/item.h]: >Wheter 

Should be:

Whether

**Comment by lucasmr** [comment]
Separated original commit into refactoring and feature.

**Comment by woutershep** [comment]
is_watertight_container currently means watertight+sealable, is_bucket means watertight+unsealable if i understand correctly. Sounds like the behavior you want for funnels is semantically is_watertight_container() || is_bucket(). Reading the is_bucket code would suggest that your logic might possibly have a problem with sealed cans which are watertight but not meant to be filled by funnels.

**Comment by lucasmr** [comment]
You're right, I'll forego the refactoring and just use is_bucket().
