### PR TITLE
Fix some issues with extracting/showing translations

### LINKED ISSUE #83194: A few more untranslatable strings
### Describe the bug

Some strings in the game cannot be translated, some translations are not used.

### Attach save file

N/A

### Steps to reproduce

Look around.

### Expected behavior

I expected that this text can be translated from English.

## Month name (#81493)
The abbreviated month name does not use translation (May, Sep, Jan). I don't know where the error is exactly, but it's most likely somewhere in the getter in the PR mentioned, as it appears everywhere:

Chargen menu:
Image

`<restock_time_point>` tag:
Image

Sidebar:
Image

EN sidebar for reference:
Image

## Mission menu
Untranslatable placeholder text in empty tabs in the mission UI (M). Most likely the error is here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/4688691d3fca5b8f44901759add7d13ced29877d/src/mission_ui.cpp#L258

Image

## Armor protection table
"chance", "Median" in the untranslatable string. Maybe it should be split into smaller ones.
https://github.com/CleverRaven/Cataclysm-DDA/blob/4688691d3fca5b8f44901759add7d13ced29877d/src/item_info.cpp#L1738
https://github.com/CleverRaven/Cataclysm-DDA/blob/4688691d3fca5b8f44901759add7d13ced29877d/src/item_info.cpp#L1742

Image

## E-port of devices
`_()` function includes an already concatenated string. Also there are no spaces between the names of banned ports.
https://github.com/CleverRaven/Cataclysm-DDA/blob/4688691d3fca5b8f44901759add7d13ced29877d/src/item_info.cpp#L2718-L2724

Image

Image

## Sidebar widgets
Some widgets also don't use translation:
1. Faction name in sidebar widget ["Owner"](https://github.com/CleverRaven/Cataclysm-DDA/blob/4688691d3fca5b8f44901759add7d13ced29877d/data/json/ui/faction.json) and in the mission menu.

Image
Image

2. Speed ​​units in ["Speed"](https://github.com/CleverRaven/Cataclysm-DDA/blob/4688691d3fca5b8f44901759add7d13ced29877d/data/json/ui/vehicle.json#L12)
Image

### Versions and configuration

build type: linux-with-graphics-x64
build number: 2025-10-01-0039
commit sha: 718c6b7cc90d9960a14abb1127a608e7cf1c5e91
commit url: https://github.com/CleverRaven/Cataclysm-DDA/commit/718c6b7cc90d9960a14abb1127a608e7cf1c5e91
ingame language: Russian

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
None

#### Purpose of change
* Fixes #83194

#### Describe the solution
Replace some translate_marker calls with the `_` macro instead of just discarding the translation.

Expanded some comments in mission_ui/translations.h after finding the previous comments insufficient. The comment in mission_ui was from me previously; I expanded it greatly because of the cargo culting of raw_description and parsed_description for POIs. That code was totally dead, always drawing an empty string. So I figured it was worth explaining. (It is *not* intuitive behavior!)

Removed that dead code from mission_ui.

Also fixed a bug the description parse_tags() call, in case anyone writes a mission that uses snippets that reference the NPC.

Fix faction name displays by making name a protected variable and adding a getter. The getter returns the a translated version of the name.

#### Testing
Month/date and faction names:
image

Speed widget:
image

Item armor table still works (extracts new translations so no screenshots of it translated)

#### Additional context

Known defects:
-Haven't done anything for the e-port stuff mentioned in the linked issue

### CODE REVIEW

**Comment by RenechCDDA** [comment]
I pushed a second commit for the faction names... in a lot of places we were "sidestepping" this by calling for translation directly at the site. That relied on knowing to do that, and there were lots of places it missed.

Instead, I wrapped it into a getter which simply does it for you. And I removed some incorrect translation calls in the process.

It seems that those translation calls were separate instances over the years to try and display the name properly... e.g. #32740 #34389 #38301 and so on. But none of these addressed the root cause, that name was just a raw string expecting to be translated "on site". This should hopefully help with that.

File: src/faction.h [hunk 1]
```diff
@@ -141,7 +140,16 @@ class faction_template
         // debug access to food supply
         cata::list<std::pair<time_point, nutrients>> &debug_food_supply();
 
+        // Returns (hopefully) translated version of the faction's name.
+        std::string get_name() const;
+        // TODO: Move to faction constructor?
+        void set_name( std::string new_name );
+
+    protected:
+        // TODO: Shouldn't this be a translation object...
```
Comment (mqrause) [inline src/faction.h:149]: With the way it is used, it absolutely should, yes. I assume the names are extracted for translation from json to make this work at all?

Comment (RenechCDDA) [reply src/faction.h:149]: Yes, that is the case.

File: src/basecamp.cpp [hunk 2]
```diff
@@ -886,7 +886,7 @@ void basecamp::handle_takeover_by( faction_id new_owner, bool violent_takeover )
     camp_workers.clear();
 
     add_msg_debug( debugmode::DF_CAMPS, "Camp %s owned by %s is being taken over by %s!",
-                   name, fac()->name, new_owner->name );
+                   name, fac()->get_name(), new_owner->get_name() );
```
Comment (mqrause) [inline src/basecamp.cpp]: I just noticed this and all the other cases in this file affect debug messages. Those shouldn't actually use translations.

Comment (RenechCDDA) [reply src/basecamp.cpp]: Why not? I'm pretty sure we use item::tname() in a lot of debugmsgs.

Comment (GuardianDll) [reply src/basecamp.cpp]: To avoid "Error in 马罵嗎妈" leaving you trying to understand what the heck 马罵嗎妈 is

Comment (RenechCDDA) [reply src/basecamp.cpp]: Why would my language be set to Chinese when debugging if I didn't understand Chinese?

Comment (mqrause) [reply src/basecamp.cpp]: It's relevant for reports from other people. Debug messages are for the developers, not for the players.

> I'm pretty sure we use item::tname() in a lot of debugmsgs.

If that's the case (and I'm sure it is), then the old rule of "false things existing doesn't justify adding more false things" applies.

Comment (GuardianDll) [reply src/basecamp.cpp]: > Why would my language be set to Chinese when debugging if I didn't understand Chinese?

Why would Chinese player's language be set to English when they report a bug?

Comment (RenechCDDA) [reply src/basecamp.cpp]: > > Why would my language be set to Chinese when debugging if I didn't understand Chinese?
> 
> Why would Chinese player's language be set to English when they report a bug?

This is add_msg_debug, not debugmsg.
