### PR TITLE
[Ready]Prefer dropping items into cargo

### LINKED ISSUE #24673: Removing a battery from a item inside a car drops the battery in the ground instead of the cargo space
Game version: 

### Steps to reproduce the behavior
Add Battery Compartment Mod to a Welder
Add a Car Battery to the Welder
Walk to an empty Cargo Space tile inside your Car
Unload the Welder

### Expected behavior
I'd expect the removed car battery to be dropped inside the cargo space, since I'm inside the car.

### Actual behavior
The car battery is dropped in the ground, outside the car.

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Interface "Prefer dropping items into vehicle cargo spaces where available in more situations"

#### Purpose of change
There are various situations where characters will drop items onto the ground even when standing in a location with vehicle storage.  Often there is no message explaining what happened.  This can be annoying, particularly when living in a mobile vehicle base.  It can be tricky to figure out what happened to some items which were just created, and you can end up driving away and leaving them on the ground.

#### Describe the solution
This changes (at least some of) those situations to prefer dropping into vehicle storage (with a fallback to the ground as usual).  Fixes #24673.  In particular:
* When dropping an item which is too large or heavy for your inventory.
* When disassembling an item.
* When removing a part from a vehicle.
* When items tumble from the inventory due to e.g. a backpack being destroyed.

Some happy side-effects of this change are that the messages received in these situations are clearer.  For example, when you remove a vehicle part you now get a message saying what part you got and where it went (sometimes it's hard to know what items will result from vehicle disassembly).

I also tweaked the messages to be more precise and handle item plurality better.  So, for example what used to say "Some items tumble to the ground" might now say "Your glass shard tumbles to the pavement" when appropriate.

cata-drop-into-vehicle

As a side note I have also introduced `item::count()` as a shortcut for `count_by_charges() ? charges : 1` and applied that where the latter expression was used.

#### Where I need advice
This all relies on the function `put_into_vehicle_or_drop` which already existed, but was a private implementation detail inside `activity_item_handling.cpp`.  I've exposed it through `activity_handler.h` but I think it should really be moved to a different file now that it's being used more widely.  I'd like advice on what file would be best.  Currently I'm thinking `map.cpp`?

There are doubtless more places in the code where items are being dropped and a similar change might be desirable.  I've just changed the ones that I remember encountering in play.  I didn't find any related issues other than #24673, so I guess no other cases seem pressing, and they can be fixed in the future as required.  Does that sound reasonable?

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -1183,11 +1184,18 @@ void Character::drop_invalid_inventory()
...
 
     if( volume_carried() > volume_capacity() ) {
-        for( auto &item_to_drop :
-             inv.remove_randomly_by_volume( volume_carried() - volume_capacity() ) ) {
-            g->m.add_item_or_charges( pos(), item_to_drop );
+        auto items_to_drop = inv.remove_randomly_by_volume( volume_carried() - volume_capacity() );
+        /// @todo For now this only supports dropping into vehicle for the
+        /// player, not other characters, because put_into_vehicle_or_drop
+        /// requires a player as an argument.  This could probably be
+        /// generalized, but would require looking into.
```
Comment (alanbrady) [inline src/character.cpp]: NPCs are 'players', what other characters are you referring to here?  Things like monsters don't have this ability.

File: src/visitable.cpp [hunk 2]
```diff
@@ -104,7 +104,7 @@ static int has_quality_internal( const T &self, const quality_id &qual, int leve
 
     self.visit_items( [&qual, level, &limit, &qty]( const item * e ) {
         if( e->get_quality( qual ) >= level ) {
-            qty = sum_no_wrap( qty, e->count_by_charges() ? int( e->charges ) : 1 );
+            qty = sum_no_wrap( qty, int( e->count() ) );
```
Comment (alanbrady) [inline src/visitable.cpp]: Seems like `qty` and limit should actually be a long?

Comment (jbytheway) [reply src/visitable.cpp]: I thought the same, but didn't want to suffer too much fix creep in this PR.  There are many other places in the code where charges is cast to an int; this is a can of worms I don't think is worth opening here.

File: src/character.cpp (hunk 1 above)
Comment (jbytheway) [reply src/character.cpp]: Thanks for the clarification; I had an inkling that NPCs were `player`s but I hadn't quite confirmed that was the case.
Having looked into this, it appears that this function (`Character::drop_invalid_inventory`) is only called on `player`s, so I could just move it from `Character` to `player` and the problem would go away.  Any objection?

Comment (alanbrady) [reply src/character.cpp]: I actually didn't notice what function we were in here, I just glanced over the comment and it didn't seem to make sense.

Looking into it a bit more, this function should live in the `character` class because the member `inv` lives here.  Moreover I don't see a reason why `put_into_vehicle_or_drop` actually needs a player reference and not `*this` other than the fact it's calling `handle_spillable_contents` which asks for a player reference, but can be changed as well for similar reasons.

File: src/visitable.cpp (hunk 2 above)
Comment (alanbrady) [reply src/visitable.cpp]: Fair enough, however I would then add a comment explaining we can probably overflow here and it needs to be fixed (even though it was actually this way before you changed anything).

File: src/character.cpp (hunk 1 above)
Comment (jbytheway) [reply src/character.cpp]: I considered that option.  I thought it would lead down a big rabbit hole, but you're right, it seems straightforward.  So, that's done and pushed.

File: src/visitable.cpp (hunk 2 above)
Comment (jbytheway) [reply src/visitable.cpp]: I opened #26103 to discuss the wider issue.  I really don't think it's worth a comment here, since it's so widespread.

**Comment by jbytheway** [comment]
No one offered an opinion on whether / where to move `put_into_vehicle_or_drop`.  Having seen that `map.cpp` is >8000 lines I'm less keen on putting it there.  So I'll just leave it where it is.  Refactoring to put it elsewhere can happen in the future if anyone cares to.

So, removing [WIP].  I think this is ready to go.  Of course, comments still welcome.

**Comment by alanbrady** [comment]
Definitely do not put it into `map.cpp`.  Where it is now is probably fine.

**Comment by jbytheway** [comment]
It's been a week with no objections, so I'm marking this ready.
