### PR TITLE
Fix salted cotton resistances 

### LINKED ISSUE #86499: Ichcahuipilli is likely overpowered
### Describe the bug

Let's play a game, which do you think is more protective, a steel chestplate, or a mesoamerican gambeson made from loose cotton covered in salt between quilted fabric.
If you guessed the gambeson, you'd be right! (for some steel types anyhow)

Image

These protection figures are straight up ludicrous. I know it takes days to craft this and all, but these outperform modern kevlar, and rival the protection of tempered steel ballistic plates. Even the closest comparison in game we have material wise, the gambeson is strictly worse in performance, and layer usage.

### Attach save file

N/A Go look at HHG or my screenshot.

### Steps to reproduce

1: Look at the values for this
2: See other aztec themed items had balance issues
3: Look at tempered steel ballistic plates being equivalent.
4: Scratch your head in confusion

### Expected behavior

I expect that quilted fabric, leather, unspun cotton, and salt to not match the performance of the top tier tempered steel plates. 
With less snark, I would assume that these would perform similarly to the gambesons present in the game given they're similar in construction, and weight.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26200.6899 (25H2)
- Game Version: cdda-experimental-2026-04-11-2307-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bombastic Perks [bombastic_perks],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Mind Over Matter [mindovermatter],
    Xedra Evolved [xedra_evolved]
]

### Additional context

A number of other aztec items were found to be unreasonable in the past, I think a similar balance problem happened here. See #77779 for comparison. Also see #74983 as the protection values were noted to be obscene by kevin, and he removed one of the material types by not the other salt hardened one. Perhaps a similar change would work?

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
Fixes #86499 

#### Describe the solution
Adjusts cotton material resistances

#### Describe alternatives you've considered
none

### CODE REVIEW

**Comment by GuardianDll** [comment]
```
-------------------------------------------------------------------------------
armor_protection
  no protection from physical, no protection from environmental
-------------------------------------------------------------------------------
../tests/iteminfo_test.cpp:1412
...............................................................................

../tests/iteminfo_test.cpp:1287: FAILED:
  REQUIRE( armor.resist( damage_bullet ) == Approx( bullet ) )
with expansion:
  0.05f == Approx( 0.200000003 )
with message:
  armor.typeId().str() := "test_longshirt"

-------------------------------------------------------------------------------
armor_protection
  complex protection from physical and environmental damage
-------------------------------------------------------------------------------
../tests/iteminfo_test.cpp:1527
...............................................................................

../tests/iteminfo_test.cpp:1287: FAILED:
  REQUIRE( armor.resist( damage_bullet ) == Approx( bullet ) )
with expansion:
  10.16667f == Approx( 10.6666698456 )
with message:
  armor.typeId().str() := "test_complex_tanktop"

-------------------------------------------------------------------------------
armor_stats
-------------------------------------------------------------------------------
../tests/iteminfo_test.cpp:1293
...............................................................................

../tests/iteminfo_test.cpp:1287: FAILED:
  REQUIRE( armor.resist( damage_bullet ) == Approx( bullet ) )
with expansion:
  0.025f == Approx( 0.1000000015 )
with message:
  armor.typeId().str() := "tshirt"
```

**Comment by BruhddyTheThird** [comment]
Does this actually fix #86499? I.e. what are the resistance values of the "Ichcahuipilli" after this change?

File: tests/iteminfo_test.cpp [hunk 1]
```diff
@@ -121,10 +121,10 @@ static const itype_id itype_test_thumb( "test_thumb" );
 static const itype_id itype_test_tool_belt_pocket_mix( "test_tool_belt_pocket_mix" );
 static const itype_id itype_test_waterskin( "test_waterskin" );
 static const itype_id itype_test_wine( "test_wine" );
-static const itype_id itype_test_zentai_resist_stab_cut( "test_zentai_resist_stab_cut" );
+static const itype_id itype_test_zentai_test_resist_stab_cut( "test_zentai_test_resist_stab_cut" );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
static const itype_id itype_test_zentai_resist_stab_cut( "test_zentai_resist_stab_cut" );
```

File: tests/iteminfo_test.cpp [hunk 2]
```diff
@@ -96,7 +96,7 @@ static const itype_id itype_test_hallu_nutmeg( "test_hallu_nutmeg" );
 static const itype_id itype_test_hazmat_suit( "test_hazmat_suit" );
 static const itype_id itype_test_jack_small( "test_jack_small" );
 static const itype_id itype_test_jug_plastic( "test_jug_plastic" );
-static const itype_id itype_test_longshirt( "test_longshirt" );
+static const itype_id itype_test_longshirt_test( "test_longshirt_test" );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
static const itype_id itype_test_longshirt( "test_longshirt" );
```

File: tests/iteminfo_test.cpp [hunk 3]
```diff
@@ -827,9 +827,9 @@ TEST_CASE( "armor_coverage_warmth_and_encumbrance", "[iteminfo][armor][coverage]
 
     SECTION( "armor with coverage shows covered body parts, warmth, encumbrance, and protection values" ) {
         // Long-sleeved shirt covering torso and arms
-        item longshirt( itype_test_longshirt );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 4]
```diff
@@ -1413,12 +1413,12 @@ TEST_CASE( "armor_protection", "[iteminfo][armor][protection]" )
         // Long-sleeved shirt, material:cotton, thickness:0.2
         // 1/1/1 bash/cut/bullet x 1 thickness
         // 0/0/0 acid/fire/env
-        item longshirt( itype_test_longshirt );
-        expected_armor_values( longshirt, 0.2f, 0.2f, 0.16f, 0.2f );
-        REQUIRE( longshirt.get_covered_body_parts().any() );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 5]
```diff
@@ -1477,14 +1477,14 @@ TEST_CASE( "armor_protection", "[iteminfo][armor][protection]" )
     }
 
     SECTION( "check that material resistances are properly overriden" ) {
-        // Zentai suit, material:lycra_resist_override_stab, thickness:1
+        // zentai_test suit, material:lycra_resist_override_stab, thickness:1
         // 2/2/2/50 bash/cut/bullet/stab x 1 thickness
-        item zentai( itype_test_zentai_resist_stab_cut );
-        REQUIRE( zentai.get_covered_body_parts().any() );
-        expected_armor_values( zentai, 2, 2, 50, 2, 9, 2, 10 );
+        item zentai_test( itype_test_zentai_test_resist_stab_cut );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item zentai_test( itype_test_zentai_resist_stab_cut );
```

File: tests/iteminfo_test.cpp [hunk 6]
```diff
@@ -3303,50 +3303,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
 
     SECTION( "default human sees standard limb names" ) {
         clear_avatar();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_BODYPARTS } );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 7]
```diff
@@ -3303,50 +3303,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
         CHECK( info.find( arms_frag ) != std::string::npos );
         CHECK( info.find( alt_arms_frag ) == std::string::npos );
         CHECK( info.find( torso_frag ) != std::string::npos );
     }
 
     SECTION( "alt-arm character sees alt limb names" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_BODYPARTS } );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 8]
```diff
@@ -3303,50 +3303,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
         CHECK( info.find( alt_arms_frag ) != std::string::npos );
         CHECK( info.find( arms_frag ) == std::string::npos );
         CHECK( info.find( torso_frag ) != std::string::npos );
     }
 
     SECTION( "coverage section filtered by viewer anatomy" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_COVERAGE } );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 9]
```diff
@@ -3303,50 +3303,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_COVERAGE } );
         CHECK( info.find( alt_arms_frag ) != std::string::npos );
         CHECK( info.find( arms_frag ) == std::string::npos );
     }
 
     SECTION( "warmth section filtered by viewer anatomy" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_WARMTH } );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 10]
```diff
@@ -3303,50 +3303,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_WARMTH } );
         CHECK( info.find( alt_arms_frag ) != std::string::npos );
         CHECK( info.find( arms_frag ) == std::string::npos );
     }
 
     SECTION( "encumbrance section filtered by viewer anatomy" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_ENCUMBRANCE } );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 11]
```diff
@@ -3303,50 +3303,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_ENCUMBRANCE } );
         CHECK( info.find( alt_arms_frag ) != std::string::npos );
         CHECK( info.find( arms_frag ) == std::string::npos );
     }
 
     SECTION( "breathability section filtered by viewer anatomy" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_BREATHABILITY } );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 12]
```diff
@@ -3373,17 +3373,17 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
 
     SECTION( "coverage value correct for default human" ) {
         clear_avatar();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_COVERAGE } );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 13]
```diff
@@ -3373,17 +3373,17 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
         CHECK( info.find( "<color_c_yellow>90</color>%" ) != std::string::npos );
         CHECK( info.find( arms_frag ) != std::string::npos );
         CHECK( info.find( torso_frag ) != std::string::npos );
     }
 
     SECTION( "coverage value correct for alt-arm character" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_COVERAGE } );
+        item longshirt_test( itype_test_longshirt_test );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt_test( itype_test_longshirt );
```

File: data/json/materials.json [hunk 14]
```diff
@@ -629,7 +629,7 @@
       { "fuel": 0.1, "smoke": 1, "burn": 0.04 },
       { "fuel": 0.2, "smoke": 1, "burn": 0.06 }
     ],
-    "resist": { "bash": 1, "cut": 1, "acid": 3, "heat": 0, "bullet": 1 },
+    "resist": { "bash": 1, "cut": 1, "acid": 3, "heat": 0, "bullet": 0.25 },
```
Comment (Maleclypse) [inline data/json/materials.json]:
```suggestion
    "resist": { "bash": 1, "cut": 1, "acid": 3, "heat": 0, "bullet": 1 },
```

File: data/json/materials.json [hunk 15]
```diff
@@ -640,15 +640,16 @@
     "copy-from": "cotton",
     "repaired_with": "null",
     "wind_resist": 75,
-    "resist": { "bash": 2, "cut": 2, "acid": 3, "heat": 0, "bullet": 1.5 }
+    "resist": { "bash": 1.25, "cut": 1.5, "acid": 3, "heat": 0, "bullet": 0.5 }
```
Comment (Maleclypse) [inline data/json/materials.json]:
```suggestion
    "resist": { "bash": 2, "cut": 2, "acid": 3, "heat": 0, "bullet": 1.5 }
```

File: data/json/materials.json [hunk 16]
```diff
@@ -640,15 +640,16 @@
...
   },
   {
     "type": "material",
     "id": "cotton_quilted_salted",
     "name": "Salt Hardened Quilted Cotton",
+    "//": "Biggest change is reducing heat resistance from ten to 2.  Aramids have 3 heat resistance and sources say that salt hardened cotton has lower than aramid fire resistance.",
     "copy-from": "cotton",
     "repaired_with": "null",
-    "resist": { "bash": 3.5, "cut": 3.5, "acid": 5, "heat": 10, "bullet": 2 }
+    "resist": { "bash": 1.75, "cut": 2, "acid": 5, "heat": 2, "bullet": 0.6 }
```
Comment (Maleclypse) [inline data/json/materials.json]:
```suggestion
    "resist": { "bash": 3, "cut": 3, "acid": 5, "heat": 2, "bullet": 1.5 }
```

File: data/mods/TEST_DATA/items.json [hunk 17]
```diff
@@ -5707,5 +5707,74 @@
...
+    "price": "20 USD",
+    "price_postapoc": "50 cent",
+    "material": [ "test_cotton" ],
+    "symbol": "[",
+    "looks_like": "dress_shirt",
+    "color": "blue",
+    "warmth": 5,
+    "material_thickness": 0.1,
+    "flags": [ "VARSIZE", "SKINTIGHT" ],
+    "armor": [ { "coverage": 90, "covers": [ "torso", "arm_l", "arm_r" ] } ]
```
Comment (Maleclypse) [inline data/mods/TEST_DATA/items.json]:
```suggestion
```

File: data/mods/TEST_DATA/materials.json [hunk 18]
```diff
@@ -24,5 +24,30 @@
...
+    "dmg_adj": [ "ripped", "torn", "shredded", "tattered" ],
+    "bash_dmg_verb": "ripped",
+    "cut_dmg_verb": "cut",
+    "burn_data": [
+      { "fuel": 0.05, "smoke": 1, "burn": 0.015 },
+      { "fuel": 0.1, "smoke": 1, "burn": 0.04 },
+      { "fuel": 0.2, "smoke": 1, "burn": 0.06 }
+    ],
+    "resist": { "bash": 1, "cut": 1, "acid": 3, "heat": 0, "bullet": 1 },
+    "repair_difficulty": 1
```
Comment (Maleclypse) [inline data/mods/TEST_DATA/materials.json]:
```suggestion
```

File: tests/iteminfo_test.cpp [hunk 19]
```diff
@@ -123,8 +123,8 @@ static const itype_id itype_test_waterskin( "test_waterskin" );
 static const itype_id itype_test_wine( "test_wine" );
 static const itype_id itype_test_zentai_resist_stab_cut( "test_zentai_resist_stab_cut" );
 static const itype_id itype_textbook_chemistry( "textbook_chemistry" );
-static const itype_id itype_tshirt( "tshirt" );
-static const itype_id itype_zentai( "zentai" );
+static const itype_id itype_tshirt_test( "tshirt_test" );
+static const itype_id itype_zentai_test( "zentai_test" );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
static const itype_id itype_tshirt( "tshirt" );
static const itype_id itype_zentai( "zentai" );
```

File: tests/iteminfo_test.cpp [hunk 20]
```diff
@@ -827,9 +827,9 @@ TEST_CASE( "armor_coverage_warmth_and_encumbrance", "[iteminfo][armor][coverage]
 
     SECTION( "armor with coverage shows covered body parts, warmth, encumbrance, and protection values" ) {
         // Long-sleeved shirt covering torso and arms
-        item longshirt( itype_test_longshirt );
+        item longshirt_test( itype_test_longshirt );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
```

File: tests/iteminfo_test.cpp [hunk 21]
```diff
@@ -827,9 +827,9 @@ TEST_CASE( "armor_coverage_warmth_and_encumbrance", "[iteminfo][armor][coverage]
...
         verify_item_coverage(
-        longshirt, {
+        longshirt_test, {
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        longshirt, {
```

File: tests/iteminfo_test.cpp [hunk 22]
```diff
@@ -844,7 +844,7 @@ TEST_CASE( "armor_coverage_warmth_and_encumbrance", "[iteminfo][armor][coverage]
         }
         );
 
-        CHECK( item_info_str( longshirt, { iteminfo_parts::ARMOR_BODYPARTS } ) ==
+        CHECK( item_info_str( longshirt_test, { iteminfo_parts::ARMOR_BODYPARTS } ) ==
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        CHECK( item_info_str( longshirt, { iteminfo_parts::ARMOR_BODYPARTS } ) ==
```

File: tests/iteminfo_test.cpp [hunk 23]
```diff
@@ -856,11 +856,11 @@ TEST_CASE( "armor_coverage_warmth_and_encumbrance", "[iteminfo][armor][coverage]
         std::vector<iteminfo_parts> cov_warm_shirt = {
             iteminfo_parts::ARMOR_COVERAGE, iteminfo_parts::ARMOR_WARMTH
         };
-        int shirt_cov = longshirt.get_avg_coverage();
-        int shirt_warmth = longshirt.get_warmth();
+        int shirt_cov = longshirt_test.get_avg_coverage();
+        int shirt_warmth = longshirt_test.get_warmth();
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        int shirt_cov = longshirt.get_avg_coverage();
        int shirt_warmth = longshirt.get_warmth();
```

File: tests/iteminfo_test.cpp [hunk 24]
```diff
@@ -856,11 +856,11 @@ TEST_CASE( "armor_coverage_warmth_and_encumbrance", "[iteminfo][armor][coverage]
...
         REQUIRE( shirt_cov > 0 );
         REQUIRE( shirt_warmth > 0 );
-        CHECK( item_info_str( longshirt, cov_warm_shirt )
+        CHECK( item_info_str( longshirt_test, cov_warm_shirt )
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        CHECK( item_info_str( longshirt, cov_warm_shirt )
```

File: tests/iteminfo_test.cpp [hunk 25]
```diff
@@ -871,7 +871,7 @@ TEST_CASE( "armor_coverage_warmth_and_encumbrance", "[iteminfo][armor][coverage]
                " The <color_c_cyan>arms</color>. The <color_c_cyan>torso</color>.\n" );
 
         verify_item_encumbrance(
-        longshirt, item::encumber_flags::none, 3, {
+        longshirt_test, item::encumber_flags::none, 3, {
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        longshirt, item::encumber_flags::none, 3, {
```

File: tests/iteminfo_test.cpp [hunk 26]
```diff
@@ -887,7 +887,7 @@ TEST_CASE( "armor_coverage_warmth_and_encumbrance", "[iteminfo][armor][coverage]
         );
 
         verify_item_encumbrance(
-        longshirt, item::encumber_flags::assume_full, 3, {
+        longshirt_test, item::encumber_flags::assume_full, 3, {
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        longshirt, item::encumber_flags::assume_full, 3, {
```

File: tests/iteminfo_test.cpp [hunk 27]
```diff
@@ -902,7 +902,7 @@ TEST_CASE( "armor_coverage_warmth_and_encumbrance", "[iteminfo][armor][coverage]
         }
         );
 
-        CHECK( item_info_str( longshirt, { iteminfo_parts::ARMOR_ENCUMBRANCE } ) ==
+        CHECK( item_info_str( longshirt_test, { iteminfo_parts::ARMOR_ENCUMBRANCE } ) ==
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        CHECK( item_info_str( longshirt, { iteminfo_parts::ARMOR_ENCUMBRANCE } ) ==
```

File: tests/iteminfo_test.cpp [hunk 28]
```diff
@@ -1292,9 +1292,9 @@ static void expected_armor_values( const item &armor, float bash, float cut, flo
 
 TEST_CASE( "armor_stats", "[armor][protection]" )
 {
-    expected_armor_values( item( itype_zentai ), 0.1f, 0.1f, 0.08f, 0.1f );
-    expected_armor_values( item( itype_tshirt ), 0.1f, 0.1f, 0.08f, 0.1f );
-    expected_armor_values( item( itype_dress_shirt ), 0.1f, 0.1f, 0.08f, 0.1f );
+    expected_armor_values( item( itype_zentai_test ), 0.1f, 0.1f, 0.08f, 0.1f );
+    expected_armor_values( item( itype_tshirt_test ), 0.1f, 0.1f, 0.08f, 0.1f );
+    expected_armor_values( item( itype_dress_shirt ), 0.1f, 0.1f, 0.08f, 0.025f );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
    expected_armor_values( item( itype_zentai ), 0.1f, 0.1f, 0.08f, 0.1f );
    expected_armor_values( item( itype_tshirt ), 0.1f, 0.1f, 0.08f, 0.1f );
    expected_armor_values( item( itype_dress_shirt ), 0.1f, 0.1f, 0.08f, 0.1f );
```

File: tests/iteminfo_test.cpp [hunk 29]
```diff
@@ -1413,12 +1413,11 @@ TEST_CASE( "armor_protection", "[iteminfo][armor][protection]" )
         // Long-sleeved shirt, material:cotton, thickness:0.2
         // 1/1/1 bash/cut/bullet x 1 thickness
         // 0/0/0 acid/fire/env
-        item longshirt( itype_test_longshirt );
-        expected_armor_values( longshirt, 0.2f, 0.2f, 0.16f, 0.2f );
-        REQUIRE( longshirt.get_covered_body_parts().any() );
+        item longshirt_test( itype_test_longshirt );
+        expected_armor_values( longshirt_test, 0.2f, 0.2f, 0.16f, 0.05f );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
        expected_armor_values( longshirt, 0.2f, 0.2f, 0.16f, 0.2f );
        REQUIRE( longshirt.get_covered_body_parts().any() );
```

File: tests/iteminfo_test.cpp [hunk 30]
```diff
@@ -1413,12 +1413,11 @@ TEST_CASE( "armor_protection", "[iteminfo][armor][protection]" )
...
 
         // Protection info displayed on two lines
-        CHECK( item_info_str( longshirt, protection ) ==
+        CHECK( item_info_str( longshirt_test, protection ) ==
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        CHECK( item_info_str( longshirt, protection ) ==
```

File: tests/iteminfo_test.cpp [hunk 31]
```diff
@@ -1477,14 +1476,14 @@ TEST_CASE( "armor_protection", "[iteminfo][armor][protection]" )
     }
 
     SECTION( "check that material resistances are properly overriden" ) {
-        // Zentai suit, material:lycra_resist_override_stab, thickness:1
+        // zentai_test suit, material:lycra_resist_override_stab, thickness:1
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        // Zentai suit, material:lycra_resist_override_stab, thickness:1
```

File: tests/iteminfo_test.cpp [hunk 32]
```diff
@@ -1477,14 +1476,14 @@ TEST_CASE( "armor_protection", "[iteminfo][armor][protection]" )
...
         // 2/2/2/50 bash/cut/bullet/stab x 1 thickness
-        item zentai( itype_test_zentai_resist_stab_cut );
-        REQUIRE( zentai.get_covered_body_parts().any() );
-        expected_armor_values( zentai, 2, 2, 50, 2, 9, 2, 10 );
+        item zentai_test( itype_test_zentai_resist_stab_cut );
+        REQUIRE( zentai_test.get_covered_body_parts().any() );
+        expected_armor_values( zentai_test, 2, 2, 50, 2, 9, 2, 10 );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item zentai( itype_test_zentai_resist_stab_cut );
        REQUIRE( zentai.get_covered_body_parts().any() );
        expected_armor_values( zentai, 2, 2, 50, 2, 9, 2, 10 );
```

File: tests/iteminfo_test.cpp [hunk 33]
```diff
@@ -1477,14 +1476,14 @@ TEST_CASE( "armor_protection", "[iteminfo][armor][protection]" )
...
 
         // Protection info displayed on two lines
-        const std::string info = item_info_str( zentai, protection );
+        const std::string info = item_info_str( zentai_test, protection );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        const std::string info = item_info_str( zentai, protection );
```

File: tests/iteminfo_test.cpp [hunk 34]
```diff
@@ -1528,7 +1527,7 @@ TEST_CASE( "armor_protection", "[iteminfo][armor][protection]" )
         item super_tanktop( itype_test_complex_tanktop );
         REQUIRE( super_tanktop.get_covered_body_parts().any() );
         // these values are averaged values but test that assumed armor portion is working at all
-        expected_armor_values( super_tanktop, 15.33333f, 15.33333f, 12.26667f, 10.66667f );
+        expected_armor_values( super_tanktop, 15.33333f, 15.33333f, 12.26667f, 10.16667f );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        expected_armor_values( super_tanktop, 15.33333f, 15.33333f, 12.26667f, 10.66667f );
```

File: tests/iteminfo_test.cpp [hunk 35]
```diff
@@ -3303,50 +3302,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
 
     SECTION( "default human sees standard limb names" ) {
         clear_avatar();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_BODYPARTS } );
+        item longshirt_test( itype_test_longshirt );
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_BODYPARTS } );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_BODYPARTS } );
```

File: tests/iteminfo_test.cpp [hunk 36]
```diff
@@ -3303,50 +3302,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
         CHECK( info.find( alt_arms_frag ) == std::string::npos );
         CHECK( info.find( torso_frag ) != std::string::npos );
     }
 
     SECTION( "alt-arm character sees alt limb names" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_BODYPARTS } );
+        item longshirt_test( itype_test_longshirt );
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_BODYPARTS } );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_BODYPARTS } );
```

File: tests/iteminfo_test.cpp [hunk 37]
```diff
@@ -3303,50 +3302,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
         CHECK( info.find( arms_frag ) == std::string::npos );
         CHECK( info.find( torso_frag ) != std::string::npos );
     }
 
     SECTION( "coverage section filtered by viewer anatomy" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_COVERAGE } );
+        item longshirt_test( itype_test_longshirt );
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_COVERAGE } );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_COVERAGE } );
```

File: tests/iteminfo_test.cpp [hunk 38]
```diff
@@ -3303,50 +3302,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
         CHECK( info.find( alt_arms_frag ) != std::string::npos );
         CHECK( info.find( arms_frag ) == std::string::npos );
     }
 
     SECTION( "warmth section filtered by viewer anatomy" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_WARMTH } );
+        item longshirt_test( itype_test_longshirt );
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_WARMTH } );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_WARMTH } );
```

File: tests/iteminfo_test.cpp [hunk 39]
```diff
@@ -3303,50 +3302,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
         CHECK( info.find( alt_arms_frag ) != std::string::npos );
         CHECK( info.find( arms_frag ) == std::string::npos );
     }
 
     SECTION( "encumbrance section filtered by viewer anatomy" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_ENCUMBRANCE } );
+        item longshirt_test( itype_test_longshirt );
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_ENCUMBRANCE } );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_ENCUMBRANCE } );
```

File: tests/iteminfo_test.cpp [hunk 40]
```diff
@@ -3303,50 +3302,50 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
         CHECK( info.find( alt_arms_frag ) != std::string::npos );
         CHECK( info.find( arms_frag ) == std::string::npos );
     }
 
     SECTION( "breathability section filtered by viewer anatomy" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_BREATHABILITY } );
+        item longshirt_test( itype_test_longshirt );
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_BREATHABILITY } );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_BREATHABILITY } );
```

File: tests/iteminfo_test.cpp [hunk 41]
```diff
@@ -3373,17 +3372,17 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
...
         CHECK( info.find( arms_frag ) != std::string::npos );
         CHECK( info.find( torso_frag ) != std::string::npos );
     }
 
     SECTION( "coverage value correct for alt-arm character" ) {
         make_alt_arm_viewer();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_COVERAGE } );
+        item longshirt_test( itype_test_longshirt );
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_COVERAGE } );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_COVERAGE } );
```

File: tests/iteminfo_test.cpp [hunk 42]
```diff
@@ -3373,17 +3372,17 @@ TEST_CASE( "armor_info_character_aware_body_parts", "[iteminfo][armor][limbs]" )
 
     SECTION( "coverage value correct for default human" ) {
         clear_avatar();
-        item longshirt( itype_test_longshirt );
-        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_COVERAGE } );
+        item longshirt_test( itype_test_longshirt );
+        std::string info = item_info_str( longshirt_test, { iteminfo_parts::ARMOR_COVERAGE } );
```
Comment (Maleclypse) [inline tests/iteminfo_test.cpp]:
```suggestion
        item longshirt( itype_test_longshirt );
        std::string info = item_info_str( longshirt, { iteminfo_parts::ARMOR_COVERAGE } );
```
