### PR TITLE
Window resize fixes

### LINKED ISSUE #23761: Issues with the new screen resizing
Game version: 0.C-7407

Operating system: Windows XP SP3 x86

Tiles or curses: curses

Mods active: default only

- Minimizing game screen causes CTD;

default

- Resizing game screen to less than 80x24 causes CTD;
- New game screen dimensions ain't saved after resizing, so restarting game requires resize it again.

### PR DESCRIPTION
**Pull request by OzoneH3**
Continuation of #23161

Maybe Closes #23761
The minimum window size prevents me from resizing below 80x24 on Win 10.
Don't have a XP Machine to test if it behaves differently there.

* Display intro() after resizing. (curses)
* Handle main menu resizing.
* Save screen dimensions after resizing.
* Resize window after changing screen dimensions in the options.
* Fixed minimum window size. (linux)

~~If someone could test these changes on Mac it would be very much appreciated.~~
* Mac approved.

### CODE REVIEW

File: src/options.cpp [hunk 1]
```diff
@@ -1979,6 +1979,7 @@ std::string options_manager::show(bool ingame, const bool world_options_only)
     bool used_tiles_changed = false;
     bool pixel_minimap_changed = false;
     bool sidebar_style_changed = false;
+    bool termial_size_changed = true;
```
Comment (Night-Pryanik) [inline src/options.cpp]: Minor, but maybe rename to `terminal_size_changed`?

File: src/main_menu.cpp [hunk 2]
```diff
@@ -136,6 +136,52 @@ std::vector<std::string> main_menu::load_file( const std::string &path,
     return result;
 }
 
+void main_menu::handle_input_timout( input_context &ctxt, std::string &action )
```
Comment (BevapDin) [inline src/main_menu.cpp]: I wonder why you "return" the action as out parameter instead of directly via `return action`? This makes the code that uses this function a bit confusing as one can not see that `action` is an output of the function (the call site does not show whether the argument is taken as const or non-const reference).

Also: why is it called `timout` - has it anything to do with a "Tim" going "out"?

Comment (OzoneH3) [reply src/main_menu.cpp]: The evil copypasta god tricked me once more. Bless me oh great BevapDin and I shall repent my sinful deeds.

```bool game::handle_mouseview(input_context &ctxt, std::string &action)``` 

R.I.P Tim, you'll be missed.

PS: Passive aggressive much? I'd rather have your input on the error that occurs in only one build than whatever this BS is.

**Comment by OzoneH3** [comment]
Weird error in only one build: https://travis-ci.org/CleverRaven/Cataclysm-DDA/jobs/390884311

```../cataclysm.a(options.o):options.cpp:(.text+0x163b6): undefined reference to `handle_resize(int, int)'```

Something wrong with the includes maybe?!

**Comment by BevapDin** [comment]
> ../cataclysm.a(options.o):options.cpp:(.text+0x163b6): undefined reference to `handle_resize(int, int)'

"src/wincurses.cpp" only implements a `void handle_resize()` functions, but you're calling a `handle_resize( int, int )`. You probably need to change the signature of that function to match the function declaration in the header.

**Comment by Leland** [comment]
> If someone could test these changes on Mac it would be very much appreciated.

Looks good! Resize works all the way down to smallest size, and window size persists after app restarts.

**Comment by ZhilkinSerg** [comment]
Sidebar is not being updated properly after resize:

image

Also not being fully updated after returning back from map screen:

image

An I am not sure how I did that, but it does this:

image

**Comment by OzoneH3** [comment]
@ZhilkinSerg Fixed the first two issues. Can't repoduse the third one.

**Comment by ZhilkinSerg** [comment]
> Can't repoduse the third one.

Me too. I will try to in updated build.
