### PR TITLE
Various perf improvements for moving the firing cursor

### LINKED ISSUE #64765: Performance regression related to limb scores when using gcc
### Describe the bug

#62092 introduced a significant performance regression when I build with gcc 12.2.1, but not when I build with clang.

The poor performance is exhibited in almost all in-game interactions, but not in UI interactions. For testing purposes I focused on moving the cursor in the firing interface, which does not involve any time passing.

### Attach save file

N/A, reproduced with new games.

### Steps to reproduce

1. Build with gcc 12.2.1 (and possibly other parameters I haven't narrowed down)
2. Play the game and observe significantly longer delays when moving around, or when moving the firing cursor

### Expected behavior

No slowdown

### Screenshots

_No response_

### Versions and configuration

Compiled current git master, and bisected back to the PR linked above.
Sorry for lack of game report, I didn't keep those binaries around through my other testing and improvement efforts.

### Additional context

Profile from `perf` when moving the firing cursor. Almost all time spent in get_limb_score. I have made a small improvement in  #64761 that should slightly reduce total number of times through this call stack, but not nearly the factor of four that would be appropriate. I initiated some discussions on Discord about caching the duplicated function calls here, but had trouble implementing that myself. I suspect clang is optimizing these repeated calls away and making the impact of the problematic PR 1/4 as bad so I don't notice it with clang, while gcc is failing to optimize it so the calls get repeated.
image

Profile from `perf` within get_limb_score, for which I have made very small improvements in #64759 
image

`calculate_ranged_chances` calls `predict_recoil` and `Character::gun_engagement_moves`, both of which call `Character::aim_per_move`, so caching/memoizing that result could cut the problem in half.

`Character::aim_per_move` calls `Character::fastest_aiming_method_speed` and `Character::most_accurate_aiming_method_limit`, both of which call `Character::effective_dispersion`, so caching/memoizing that result could cut the problem in half [again].

And, finally, `Character::effective_dispersion` calls a few things that eventually call `Character::get_limb_score` which could probably also be improved with caching.

### PR DESCRIPTION
**Pull request by SurFlurer**
#### Summary
none

#### Purpose of change
Address #64765 .

#### Describe the solution
This can be reviewed by commits.

1. Speed up Character::has_flag() by caching whether bionics has certain json flags. The reason I didn't do the same thing for other aspects ( mabuff, effect, trait... ) is that tracking their changes is beyond my capabilities. Effects are inherited from `Creature`, mabuffs are basically effects, and traits are deeply entangled with enchantments.
2. Reduce dupliate calls of get_character_parallax() for performance. `effective_dispersion()` just calls `get_character_parallax()` and adds a number to it, so I manually inlined that func to improve perf. For heavily modified guns, there can be many gunmods, but there will only be two cases for `get_character_parallax()`, so cache the result and reuse when possible.
3. Move computational heavy operations outside the aiming loop. To do this, I created 2 structs to cache variables that are actually constant during the aiming loop, and made a func to initialize those variables. Then, I passed them down the call chain.

#### Describe alternatives you've considered
Venera once talked about caching results of `get_modifiers()`, but the same reason for not caching flags for traits, mabuffs and effects prevented me from doing so. I couldn't find out when to refresh the cache to not break swimming tests.

#### Testing
All tests passed.

Some perf data:

Before: 
Around 60% to 80% of cpu cycles are consumed by `get_limb_scores()` when moving the firing cursor.
https://user-images.githubusercontent.com/22912139/244914636-cd491b34-06c3-48d0-9b2b-315fb44d53de.png

After: 
With a late-game character, aiming with a HWP+9:
image

image

So most cpu cycles are consumed by UI drawing, which is expected.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -892,8 +892,17 @@ int Character::point_shooting_limit( const item &gun )const
     }
 }
 
+aim_mods_cache Character::gen_aim_mods_cache( const item &gun )const
+{
+    parallax_cache parallaxes{ get_character_parallax( true ), get_character_parallax( false ) };
+    auto parallaxes_opt = std::make_optional( std::ref( parallaxes ) );
```
Comment (BrettDong) [inline src/character.cpp:898]: I think you're creating dangling references here.
