### PR TITLE
Fix semi-manual turret mode

### LINKED ISSUE #17071: "Semi-manual" turret mode doesn't work
You can only set turrets to the fully automatic (acquire targets + shoot) or fully manual mode (sit at turret, grab it and point it at stuff). The "sit at controls, point turrets at stuff, otherwise have them sit still" mode is no longer accessible.

### LINKED ISSUE #20088: Game crashes when manually controlling turrets in a vehicle
It just crashes when I go and manually aim a turret. I do not know if it is just me or if it happens to others also, could someone test this and verify? This is happening on build 6164.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Fixes #17071
Fixes #20088

### CODE REVIEW

File: src/ranged.cpp [hunk 1]
```diff
@@ -1160,7 +1160,7 @@ std::vector<tripoint> game::pl_target_ui( target_mode mode, item *relevant, int
 
     std::vector<aim_type> aim_types;
     std::vector<aim_type>::iterator aim_mode;
-    int sight_dispersion = u.effective_dispersion( relevant->sight_dispersion() );
+    int sight_dispersion = relevant != nullptr ? u.effective_dispersion( relevant->sight_dispersion() ) : 0;
```
Comment (brian-donovan) [inline src/ranged.cpp]: This currently won't do much since #20094 ensures `relevant` is not a null.
