### PR TITLE
fix invalid bionic id null

### LINKED ISSUE #45641: `invalid bionic id "null"` when opening the `E`at menu
# Describe the bug

# Steps To Reproduce
Load the save, press `E`, observe the warning.

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-7820-g7c1533deb6-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.04.12.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5600959/2020.04.12.zip)

### LINKED ISSUE #45666: invalid bionic id "null"
# Describe the bug
When trying to eat something, an error occurs: `ERROR : src/generic_factory.h:433 [const T &generic_factory<bionic_data>::obj(const string_id<T> &) const [T = bionic_data]] invalid bionic id "null"`.
Backtrace:
```
    0   cataclysm-tiles                     0x000000010d0aa461 _Z21debug_write_backtraceRNSt3__113basic_ostreamIcNS_11char_traitsIcEEEE + 57
    1   cataclysm-tiles                     0x000000010d0a95da _Z8DebugLog10DebugLevel10DebugClass + 789
    2   cataclysm-tiles                     0x000000010d0a8ed5 _Z12realDebugmsgPKcS0_S0_RKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE + 111
    3   cataclysm-tiles                     0x000000010cfce8f4 _Z12realDebugmsgIJRKNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEEPKcEEvSA_SA_SA_SA_DpOT_ + 100
    4   cataclysm-tiles                     0x000000010ced6daf _ZNK15generic_factoryI11bionic_dataE3objERK9string_idIS0_E + 131
    5   cataclysm-tiles                     0x000000010d04735a _ZNK9Character21get_acquirable_energyERK4item + 416
    6   cataclysm-tiles                     0x000000010d25416a _ZNSt3__128__invoke_void_return_wrapperINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEE6__callIJRZN27comestible_inventory_presetC1ERK6playerEUlRK13item_locationE9_SF_EEES6_DpOT_ + 32
    7   cataclysm-tiles                     0x000000010d254116 _ZNSt3__110__function6__funcIZN27comestible_inventory_presetC1ERK6playerEUlRK13item_locationE9_NS_9allocatorIS9_EEFNS_12basic_stringIcNS_11char_traitsIcEENSA_IcEEEES8_EEclES8_ + 18
    8   cataclysm-tiles                     0x000000010d32cc1d _ZNSt3__110__function6__funcIZN25inventory_selector_preset11append_cellERKNS_8functionIFNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEERK13item_locationEEERKS9_SI_E3$_3NS7_ISJ_EEFS9_RK15inventory_entryEEclESN_ + 83
    9   cataclysm-tiles                     0x000000010d31aa22 _ZNK25inventory_selector_preset6cell_t8get_textERK15inventory_entry + 36
    10  cataclysm-tiles                     0x000000010d31a894 _ZNK25inventory_selector_preset13get_cell_textERK15inventory_entrym + 108
    11  cataclysm-tiles                     0x000000010d31b1fc _ZNK16inventory_column20get_entry_cell_widthERK15inventory_entrym + 46
    12  cataclysm-tiles                     0x000000010d31b77f _ZN16inventory_column13expand_to_fitERK15inventory_entry + 177
    13  cataclysm-tiles                     0x000000010d31ceaf _ZN16inventory_column9add_entryERK15inventory_entry + 1205
    14  cataclysm-tiles                     0x000000010d3205f9 _ZN18inventory_selector9add_entryER16inventory_columnONSt3__16vectorI13item_locationNS2_9allocatorIS4_EEEEPK13item_category + 199
    15  cataclysm-tiles                     0x000000010d320cb5 _ZN18inventory_selector19add_contained_itemsER13item_locationR16inventory_column + 189
    16  cataclysm-tiles                     0x000000010d3219aa _ZN18inventory_selector13add_map_itemsERK8tripoint + 544
    17  cataclysm-tiles                     0x000000010d3222a3 _ZN18inventory_selector16add_nearby_itemsEi + 297
    18  cataclysm-tiles                     0x000000010d246a8e _ZL12inv_internalR9CharacterRK25inventory_selector_presetRKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEiSC_SC_ + 319
    19  cataclysm-tiles                     0x000000010d24851b _ZN10game_menus3inv7consumeER6player + 350
```
# Steps To Reproduce
`Shift+E`
# Expected behavior
No error.
# Versions and configuration
- OS: MacOs
    - OS Version: Name: macOS; Version: 11.0.1; Build: 20B50; 
- Game Version: 0.E-7887-g0aab8538b6-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: Русский [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у NPC [no_npc_food],
    Без ж/д станций [No_Rail_Stations]
]
# Additional context
I think the problem is here:
```cpp
int Character::get_acquirable_energy( const item &it ) const
{
    const bionic_id &bid = get_most_efficient_bionic( get_bionic_fueled_with( it ) ); // <---
```

### PR DESCRIPTION
**Pull request by akirashirosawa**
#### Summary
SUMMARY: None
#### Purpose of change
Fix #45641
Fix #45666 (duplicate)
#### Describe the solution
Check if `get_bionic_fueled_with` returns an empty vector.
#### Describe alternatives you've considered
You can see that in this piece of code to draw the "`E`at menu", `get_bionic_fueled_with` is already called (and emptiness tested) and there is no need to call it again. But I quickly didn’t figure out how to combine it (didn't work before with menu rendering).
```cpp
append_cell( [&p]( const item_location & loc ) {
    std::string cbm_name;
    if( p.can_fuel_bionic_with( *loc ) ) {
        std::vector<bionic_id> bids = p.get_bionic_fueled_with( *loc ); // <---
        if( !bids.empty() ) {  // <---
            bionic_id bid = p.get_most_efficient_bionic( bids );
            cbm_name = bid->name.translated();
        }
    }

    if( !cbm_name.empty() ) {
        return string_format( "<color_cyan>%s</color>", cbm_name );
    }

    return std::string();
}, _( "CBM" ) );

append_cell( [&p]( const item_location & loc ) {
    return good_bad_none( p.get_acquirable_energy( *loc ) );  // <---
}, _( "ENERGY (kJ)" ) );
```
In theory, don't even need to try to draw the next column (`append_cell`) if `bids.empty()`.
#### Testing
Tested in game. And `All tests passed (3480808 assertions in 612 test cases)`.
#### Additional context

### CODE REVIEW

File: src/consumption.cpp [hunk 1]
```diff
@@ -1470,7 +1470,11 @@ bool Character::fuel_bionic_with( item &it )
 
 int Character::get_acquirable_energy( const item &it ) const
 {
-    const bionic_id &bid = get_most_efficient_bionic( get_bionic_fueled_with( it ) );
+    std::vector<bionic_id> bids = get_bionic_fueled_with( it );
```
Comment (Fris0uman) [inline src/consumption.cpp:1473]:
```suggestion
   const std::vector<bionic_id> &bids = get_bionic_fueled_with( it );
```
I think this can also be a const

**Comment by emptytriangle** [comment]
wasn't this happening because the ethanol burner is broken? I think you just suppressed the symptoms of the bug and not the cause

**Comment by ZhilkinSerg** [comment]
> 
> 
> wasn't this happening because the ethanol burner is broken? I think you just suppressed the symptoms of the bug and not the cause

Bug appeared in characters with no CBM installed.
