### PR TITLE
Fixes limbs without sublocations not showing layer conflics with =

### LINKED ISSUE #52800: `=` menu no longer highlights items sharing a layer resulting in encumbrance penalty
### Describe the bug

`=` menu no longer highlights items sharing a layer resulting in encumbrance penalty

### Steps To Reproduce

Wear multiple things on the same layer on the same body part, see the nonzero + stuff in encumbrance in `@` but no yellow on the items in `=`.

### Expected behavior

Highlight.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-3826-g610e7d5502-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
Bugfixes "fixes non sub location limbs not showing layer conflicts on the = screen"

#### Purpose of change
fixes #52800

#### Describe the solution
test for sublocations. If they exist do the test the new way, if they don't do it the old way. 

#### Testing
image

### CODE REVIEW

File: src/armor_layers.cpp [hunk 1]
```diff
@@ -84,20 +84,32 @@ item_penalties get_item_penalties( std::list<item>::const_iterator worn_item_it,
         if( !worn_item_it->covers( bp ) ) {
             continue;
         }
-        for( const auto &sbp : bp->sub_parts ) {
-            if( !worn_item_it->covers( sbp ) ) {
-                continue;
-            }
+        // if no subparts do the old way
+        if( bp->sub_parts.size() == 0 ) {
```
Comment (BrettDong) [inline src/armor_layers.cpp:88]:
```suggestion
        if( bp->sub_parts.empty() ) {
```

File: src/armor_layers.cpp [hunk 2]
```diff
@@ -84,20 +84,32 @@ item_penalties get_item_penalties( std::list<item>::const_iterator worn_item_it,
...
+                    return i.get_layer() == layer && i.covers( bp ) && !i.has_flag( flag_SEMITANGIBLE ) &&
+                           i.covers( sbp );
+                } );
+                if( num_items > 1 ) {
+                    body_parts_with_stacking_penalty.push_back( bp );
+                }
+            }
         }
 
+
```
Comment (BrettDong) [inline src/armor_layers.cpp:112]:
```suggestion
```
