### PR TITLE
[Bugfixes] Fix ethereal item info

### LINKED ISSUE #84729: Invalid string format specifier error on inventory items with durations
### Describe the bug

Since the #84332 change, limited duration items that are created by Magicklysm/Xedra Evolved spells such as "Dream Dagger" that normally have their remaining duration added to the end of their names have been giving an invalid string format specifier error instead.

### Attach save file

[TestWorld-trimmed.tar.gz](https://github.com/user-attachments/files/24664000/TestWorld-trimmed.tar.gz)

### Steps to reproduce

1.Loading the save will show the fullscreen error.
2.Ignore the errors to finish loading save.
3.Open player inventory and check the name of the equipped "dream dagger" item

### Expected behavior

It's expected that the remaining duration of the temporary items will be appended to the end of their names without causing errors.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.6466 (22H2)
- Game Version: cdda-experimental-2026-01-16-0347-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by yuganxia**
#### Summary
Bugfixes "Fix ethereal item info"

#### Purpose of change
Fixes #84729, Related to #84332
Non-permanent items now display their duration in turns.

#### Describe the solution
Correct the class using a similar method as before.

#### Testing
Done

### CODE REVIEW

File: src/item_tname.cpp [hunk 1]
```diff
@@ -346,7 +347,8 @@ std::string ethereal( item const &it, unsigned int /* quantity */,
                       segment_bitset const &/* segments */ )
 {
     if( it.ethereal ) {
-        return string_format( _( " (%s turns)" ), it.get_var( "ethereal", 0 ) );
+        const int turns = static_cast<int>( std::lround( it.get_var( "ethereal", 0.0 ) ) );
+        return string_format( _( " (%d turns)" ), turns );
```
Comment (GuardianDll) [inline src/item_tname.cpp]: Something i wanted to fix for a long time, thank you for finding it
```suggestion
        const time_duration turns = time_duration::from_turns(
                                        std::lround( it.get_var( "ethereal", 0.0 ) ) );
        return string_format( _( " (%s)" ), to_string( turns, true ) );
```

Let's be a bit fancy shall we?
Image

Comment (GuardianDll) [reply src/item_tname.cpp]: alternatively you can use `to_string_clipped( turns )`, this might work even better
