### PR TITLE
Fixed display of charge usage for interrupted batch production

### LINKED ISSUE #46518: Error in display of charge usage for batch production
# Describe the bug

When crafting something that uses charges on a tool (in this case Soda Can Stove kit) an incorrect number is shown for charges required at one point.

# Steps To Reproduce

1. Have the stuff ready to make a lot of Fruit Wine Must (including soda can stove kit)
2. Batch produce just as much as you have charges in the can to make
(e.g. 114 charge use when you have 117 charges in the kit)
3. Select Soda  Can Stove Kit from the list of possible cooking tools
4. Note that the charge usage is shown as 19/117
(N.B. I was making 19 batches. So it is showing the number of batches to be made, not the number of charges to be used)

# Expected behavior

Charge usage should show as 114/117. 

# Screenshots

batch1

batch2

# Versions and configuration

- OS: Windows x64 8.1
- Game Version: 0.E-8531-gea3e6a3 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    No Fungal Monsters [No_Fungi],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context

I have not checked for other tools / crafting tasks but I suspect it is a general problem.

Actual charge used is correct, it's just the display that's wrong.

Also, I don't know why it listed the Soda Can Stove Kit twice when I only have one.

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
SUMMARY: Bugfixes "Interrupted batch jobs were showing the internal energy calculation, instead of the actuall number of tool-charges needed."

#### Purpose of change
Interrupted/Paused crafting jobs showed the internal charge per tick calculation instead of the actuall charges needed to finish the job.

Fixes #46518

#### Describe the solution
I took the crafting variable full_craft_charges out of it's original scope to use in the ui section. This way the original behavior remains intact and only the information given to the user got altered.

#### Describe alternatives you've considered
No real alternative that wouldn't generate redundant code.

#### Testing
Create a batch crafting job and interrupt it. Empty out the tool or change the amount of charges it has left and spawn in a new (full) version of the tool.
This should ensure that the tool selection window gets opened up whenever you try to resume with the crafting job.
Compare the number of needed charges listed to the items remaining in the batch job and multiply by the charge cost.
The displayed numbers should be correct now.
save file with an example job set up: [Sunny Isles.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5768892/Sunny.Isles.zip)

#### Additional context
That problem resolved, the crafting.cpp method: select_tool_component() still has some minor leftover issues that need to be taken care off in the future.

- The tool selection right now ignores any tool with a charge of less than 20. A leftover behavior that probably made sense before crafting jobs could be paused and tools switched.
- Right now the ui can show charge requirements that exceed the tools current charge. This maybe could use some sort of clarification or a different way to present the information to avoid possible confusion.

### CODE REVIEW

File: src/crafting.cpp [hunk 1]
```diff
@@ -1769,10 +1769,13 @@ Character::select_tool_component( const std::vector<tool_comp> &tools, int batch
...
-
-    auto calc_charges = [&]( const tool_comp & t ) {
+    auto calc_charges = [&]( const tool_comp & t, bool ui = false ) {
         const int full_craft_charges = item::find_type( t.type )->charge_factor() * t.count * batch;
         const int modified_charges = charges_required_modifier( full_craft_charges );
+        if( ui ) {
+            return std::max( full_craft_charges, 1 );
+        }
+
         return std::max( modified_charges, 1 );
```
Comment (BrettDong) [inline src/crafting.cpp:1779]:
```suggestion
        return std::max( ui ? full_craft_charges : modified_charges, 1 );
```
