### PR TITLE
melee: treat NPCs as humans for using techniques

### LINKED ISSUE #34427: Fatal crash on neutral NPCs angered from deaf players when attacking
# Describe the bug

A neutral NPC got angered from players not responding with `deaf` status, then crashes when  the NPC attacks. 

# Steps To Reproduce

1. Deafen yourself (grenade explosions, etc.)
2. Go and talk with a neutral NPC that spawned newly into the world.
3. The [crash log](https://imgur.com/a/Z6rpQ1e) will appear.

# Expected behavior

NPCs attacking the unable-to-respond `deaf` player should not lead to a fatal crash.

# Versions and configuration

 - OS: Windows 7 Ultimate
 - Game Version: 0.D-8176-ga35bb25
 - Graphics version: Tiles
 - Mods loaded: just a plain cdda

# Additional context

This is the [crash log](https://pastebin.com/3w0ptRUQ).

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "melee: treat NPCs as humans for using techniques"```

#### Purpose of change
Fixes #34427 

The melee technique selection code was crashing because of a check against either of `is_player()` or `monster::type->in_species( HUMAN )`.  NPCs aren't players though they inherit from the player:: class, and they aren't monsters and don't have an `in_species()` function.

This is all symptomatic of some poor abstraction, because the code would be easier to read and more robust if `in_species()` could be called from `Creature::`.

#### Describe the solution
Add `in_species()` as a virtual function to `Creature::` and override it in `monster::` and `Character::`.  Use this new function in a couple of other places to simplify or clarify the code, most noticeably in the dissector function in `trapfunc.cpp`.

As a bonus, this future proofs us for when avatars and NPCs are not necessarily human.

#### Additional context
Tested by running the unpatched game, spawning a bunch of NPCs, and seeing it crash on a random melee hit.  Repeated the test multiple times after applying the patch without crashing.

Also spawned some dissectors and verified that robots where not harmed by them but that zombie children were carved into many small pieces.

### CODE REVIEW

File: src/creature.cpp [hunk 1]
```diff
@@ -895,6 +895,11 @@ bool Creature::is_warm() const
     return true;
 }
 
+bool Creature::in_species( const species_id & ) const
+{
+    return false;
```
Comment (jbytheway) [inline src/creature.cpp]: I feel that this function should be pure-virtual, not always-returning-false.
