### PR TITLE
Fix display of volumes

### LINKED ISSUE #18288: Volume needs appropriate display units
On OSX (`10.11.6`), with a custom build (compiled from a424d42 + [ChezzoSounds](https://github.com/Chezzo/Cataclysm-DDA/tree/ChezzoSounds)).

The `make` command I use:
```sh
make app -j4 NATIVE=osx OSX_MIN=10.11 TILES=1 SOUND=1 LOCALIZE=0 RELEASE=1 CLANG=1 MACPORTS=1 USE_HOME_DIR=1
```

I understand this is a work in progress, so if those are known bugs, please ignore this issue.

In this (`+` re-layer screen) capture, I see 2 strange things:

1) in the left column, I see `0`s and `m`s , are those supposed to be there, what they mean ?
2) also, storage does not seems to be consistent (see also the `i` inventory and `/` advanced inventory screen captures bellow)

cataclysm__dark_days_ahead_-_0_c-18216-gb7e955e

cataclysm__dark_days_ahead_-_0_c-18216-gb7e955e

cataclysm__dark_days_ahead_-_0_c-18216-gb7e955e

EDIT (mugling):

Required fixes:
- [ ] Inventory
- [ ] Advanced inventory
- [ ] Sort armor
- [ ] Item info?

### PR DESCRIPTION
**Pull request by mugling**
- Follows #18293 
- Fixes #18288

Display format is `%6.1fL` eg. `38.2L` similar to the current system for `weight`

### CODE REVIEW

File: src/inventory_ui.cpp [hunk 1]
```diff
@@ -490,13 +490,13 @@ void inventory_selector::draw_inv_weight_vol( WINDOW *w, int weight_carried, uni
     wprintz(w, c_ltgray, "/%-6.1f", convert_weight(u.weight_capacity()));
 
     // Print volume
-    mvwprintw(w, 0, 61, _("Volume (ml): "));
+    mvwprintw(w, 0, 61, _("Volume (L): "));
     if (vol_carried > vol_capacity) {
-        wprintz(w, c_red, "%3d", to_milliliter( vol_carried ) );
+        wprintz(w, c_red, "%6.1f", ( to_milliliter( vol_carried ) / 1000.0 ) + 0.05 ); // +0.05 to round up
```
Comment (codemime) [inline src/inventory_ui.cpp]: This round up thing is rather evil. It would show that you carry some volume (0.1L I suppose) when you actually carry nothing at all.

Comment (mugling) [inline src/inventory_ui.cpp]: It's inherited from the weight code. Suggestions?

**Comment by nornagon** [comment]
Also maybe update src/pickup.cpp:938?

File: src/inventory_ui.cpp (hunk 1 above)
Comment (codemime) [inline src/inventory_ui.cpp]: Plain old `ceil()` for positive numbers?  `std::ceil( 10.0 * x ) / 10.0`. We could have a dedicated function for this.

Comment (mugling) [inline src/inventory_ui.cpp]: As in round up to `n` decimal places?

Comment (codemime) [inline src/inventory_ui.cpp]: Yep, something like:
```c++
double round_up( double x, unsigned int decimals ) {
    const double denominator = std::pow( 10.0, double( decimals ) );
    return std::ceil( denominator * x ) / denominator;
}
```

**Comment by DangerNoodle** [comment]
I see. Possibly, but I think that setting things to liters as done in the pull request might be the best current method.

Adding an option to display it in quarts might be the acceptable Imperial equivalent, but it wouldn't be a perfect conversion of milliliter (or in this case, small fractions of the displayed liter) to quarts, since a quart is 946.353 milliliters if I recall.

**Comment by WizardOfOoo** [comment]
Frankly, it could be in board-feet as long as it's readable.

**Comment by Coolthulhu** [comment]
Could also fix the ones in item display. Those are still in ml.

**Comment by DangerNoodle** [comment]
I thought that was the focus of this pull request?

**Comment by mugling** [comment]
@Coolthulhu yes, but separate PR, want to concentrate on #18286
