### PR TITLE
Adaptive perishable stacking

### LINKED ISSUE #25744: Food with very high spoilage timers clutters inventory
**Describe the bug**  
I think it's time to address the elephant in the room.
Here's what my eat menu looks like after raiding a school and loading the loot into a cart (so, just things that were found there):
food1
food2
Keep in mind, #25429 happened - for example, the chocolate lasts 360 days, putting it just under a year, which shows up as 3 seasons, but it's really a year. Another thing to keep in mind is that even in worst conditions, this food would experience freezing during winter, and to some degree spring and autumn, meaning it would last even longer, even without efforts to preserve it.

To sum it up, these are food items that can last around two years on the ground, and possibly even more if tossed into the fridge. This makes them functionally immortal. They will simply never spoil during normal gameplay, and when they do, it will have no effect on the game. A survivor that makes it through to a second year isn't going to be affected by some chocolates spoiling, especially if they didn't eat them during the first year.

These timers, that affect a tiny minority of characters in a slight way, are a major inconvenience for any survivor raiding a school, to a lesser degree arcade, emptying several vendors, or any other place where lots of junk food can be found.

Eat menu becomes a nightmare to navigate with this baggage. Regular inventory gets pretty cluttered as well. If you try to filter the food and put all spoiling ones into the fridge, you will end up filling it with items that don't really need it, forcing you to either sift through all your food to filter out ones with long timers or fill your fridge space with junk.

I want to say that the timers on long-lasting food should just be removed, but that idea seems to not resonate well with people for some reason. I have no other ideas for fixing this at the moment and would like to start a discussion.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
```SUMMARY: Interface "Adaptively stack perishables based on remaining time before rot."```

#### Purpose of change
Fixes #25744 
Since the massive extension of perishable durations, it has become possible to amass huge numbers of perishables with similar rot times that nevertheless are displayed seperately. This change causes these items with similar rot times to stack, and stack more coarsely the further in the future the rot time is.

#### Describe the solution
Extracted the code to produced truncated durations ("1 year", "three months", "2 days" etc) and used it to bucket items based on remaining time until spoilage.

#### Describe alternatives you've considered
Replacing the stacking code with menu code that dynamically stacks the items would be preferable, but is a much more involved change.
This uses a bucketing approach because the comparisons must be transitive.  An approach where "items stack if they are within x% of each other" would be unstable and cause items to swap between stacks chaotically.

#### Additional context
Re-using the truncated time code minimises conflicts between stacks and displayed expiration times.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -598,9 +604,6 @@ bool item::stacks_with( const item &rhs ) const
     if( corpse != nullptr && rhs.corpse != nullptr && corpse->id != rhs.corpse->id ) {
         return false;
     }
-    if( contents.size() != rhs.contents.size() ) {
-        return false;
-    }
```
Comment (Qrox) [inline src/item.cpp]: Why is this removed? `rhs.contents.end()` is not passed to `std::equal` below so this comparison is necessary.

File: src/item.cpp [hunk 2]
```diff
@@ -578,8 +578,14 @@ bool item::stacks_with( const item &rhs ) const
...
-        if( bday != rhs.bday ) {
-            return false;
+        // Stack items that fall into the same "bucket" of freshness.
+        // Distant buckets are larger than near ones.
+        std::pair<int, clipped_unit> my_clipped_time_to_rot =
+            clipped_time( type->comestible->spoils - rot );
+        std::pair<int, clipped_unit> other_clipped_time_to_rot =
+            clipped_time( rhs.type->comestible->spoils - rhs.rot );
+        if( my_clipped_time_to_rot == other_clipped_time_to_rot ) {
+            return true;
```
Comment (Qrox) [inline src/item.cpp]: Items belonging to the same bucket may belong to different buckets after their rot timer advances, which might cause erratic stacking of items. For example, if two items have perish time values of 1.8 hours and 1.2 hours, after 0.3 hours the values becomes 1.5 hours and 54 minutes, and then the two items should not stack.

Also, better test `my_clipped_time_to_rot != other_clipped_time_to_rot` and return false if it's true, since there are other tests below. And the test `std::abs( to_turns<int>( rot - rhs.rot ) ) > processing_speed()` below probably should be removed.

File: src/item.cpp (hunk 1 above)
Comment (kevingranade) [reply src/item.cpp]: This was a mistake yea.

File: src/item.cpp (hunk 2 above)
Comment (kevingranade) [reply src/item.cpp]: I need to add some tests for this, but I believe they will split and rejoin when necessary, and I observed this happening in practice when manually testing.

Point taken with !=, I had a different solution in place and ended up here via refactoring.

You're right about the processing speed thing, it's no longer necessary either.
