### PR TITLE
don't allow vehicle planter to operate in the cold, same as planting by hand

### LINKED ISSUE #14359: Seed drills skip the temperature check for planting seeds
Planting seeds via a seed drill mounted on a vehicle doesn't seem to do the same temperature check as hand-planting does. So you can successfully plant seeds mid-winter when handplanting would fail.

1cf825189dec9cc1cd2399b0d1da89da538b8c8f

### PR DESCRIPTION
**Pull request by sparr**
Tells player they can't enable the planter when it's too cold. Disables already-on planter when temperature drops.

The `temp<50` check now exists in three places. If I should move this out to a helper, I'd appreciate some guidance on where to put it. Tossing it in `game` next to `get_temperature()` seems weird.

closes #14359

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -3955,6 +3959,12 @@ void vehicle::idle(bool on_map) {
         engine_on = false;
     }
 
+    if ( planter_on && g->get_temperature() < 50) { // copied from iexamine::dirtmound
+        add_msg(m_info, _("Planter system stopped due to cold"));
```
Comment (Coolthulhu) [inline src/vehicle.cpp]: Should mention the vehicle name and possibly also check for visibility. `idle` is processed even when player doesn't see the vehicle.

**Comment by Coolthulhu** [comment]
Helper could be in weather.cpp, I think.

**Comment by sparr** [comment]
ok, I think this is ready now.
