### PR TITLE
Fix float values provided in json silently converting into ints

### LINKED ISSUE #80804: Some artifacts in physics lab have insane resonance
### Describe the bug

Some artifacts in physics lab have ridiculously high resonance. As a result even just picking them up will cause you some major troubles or death. In attached example artifact to northwest from player has a resonance of 2147483528.000000. Other effect it has is a passive carry weight mod of -1.000000 and active effect AO_SLOW which should not amount to that much resonance. Seeing how they are both negative they should not amount to any positive resonance at all.

### Attach save file

[Beaverlick-trimmed.tar.gz](https://github.com/user-attachments/files/20021961/Beaverlick-trimmed.tar.gz)

### Steps to reproduce

Loot twisted floor of physics labs. Usually you can find at least one such artifact per lab.

### Expected behavior

Reasonable amount of resonance on artifacts.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 29f74da [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

As far as I know those kind of artifacts were present for a while in the game, but until recently this abnormally high resonance somehow was not affecting the character at all.

### PR DESCRIPTION
**Pull request by maniak1349**
#### Summary
Bugfixes "Fix float values provided in json silently converting into ints"

#### Purpose of change
Due to incorrect checks in `JsonValue` for integer values it was possible to specify in json a number with fractions for a value represented by int in C++. `AsInt64` was used on them and fractions were silently gone.

That was allowing things like #80804 to happen without error. It was most likely also causing invalid or undesired behavior in every other such case. Specifically I've tested MindOverMatter's `clairsentient_crystal_procgen` preset. It defines for example
```
      {
        "weight": 50,
        "min_value": 0.1,
        "max_value": 1,
        "type": "AVOID_FRIENDRY_FIRE",
        "increment": 0.1,
        "power_per_increment": 75,
        "ench_has": "HELD"
      },
```
`min_value` and `increment` were rounded to zero resulting in `AVOID_FRIENDRY_FIRE` never appear on any artifact (0/10000).

Fixes #80804

#### Describe the solution
- Make `JsonValue` use for integer values `IsIntOrUint` instead of `IsNumeric`.
- Allow `relic_procgen_data` accept floats values for `passive_add_procgen_values`
Reasoning: There is already a lot of magic enchantments which expect a float value - like multiplier or a 0.0 .. 1.0 chance. That contradicts int only restriction on add values, but it's already there. Options are - ether lift the restriction, or rework all of those values for something suitable for int add mechanic. Much more work and less flexibility. It will also likely to break a lot of not-in-repo mods. So unless there is some specific reason to add values be restricted to ints first option is preferable. Would really appreciate some input from people knowledgeable on the matter with this one.
- Fix all the incorrect values in json. Use `math` workaround where it is possible and round values down where it is not.
Note: not sure if workaround works. But worst case scenario should be - things were broken and remain broken.
- Remove from `turn_cost` info in EOC documentation a statement about ability to use fractions of a turn. That does not work since EOC durations use `time_duration` which stores time `int turns_`, not in moves.

#### Describe alternatives you've considered
- Keep int add values and rework enchants instead.
- Do nothing, pretend everything is good. No really, that may be a good option.

#### Testing
Run cata_tests. Runs ok.
Make a world with each in-repo mod and start a game. Game starts.
Spawn some `clairsentient_crystal_procgen` based arts in MindOverMatter and check if they have `AVOID_FRIENDRY_FIRE` now. They do: 818/10000.
Save/load save with arts to see if they will retain their properties. Look same.
Load old 215hr hoarder save. Loads.

No matter how much I test I don't think I will be able to cover everything.

#### Additional context
Expect thing to break!

### CODE REVIEW

**Comment by RenechCDDA** [comment]
Well that's terrifying.

File: src/flexbuffer_json.cpp [hunk 1]
```diff
@@ -147,15 +147,15 @@ bool JsonValue::read( bool &b, bool throw_on_error ) const
 }
 bool JsonValue::read( char &c, bool throw_on_error ) const
 {
-    if( !test_number() ) {
+    if( !test_int() ) {
         return error_or_false( throw_on_error, "Syntax error.  Expected number" );
```
Comment (mqrause) [inline src/flexbuffer_json.cpp]: The error messages should be adjusted as well so contributors know what's wrong.

Comment (maniak1349) [reply src/flexbuffer_json.cpp]: Right, forgot about those. Mainly because you don't see them during load process since `throw_on_error` is false. You get ones from `JsonValue::operator`'s instead.
Edit: Oh wait, you do get them. It was falling through when check was wrong. Fixed them anyway.

File: data/mods/TropiCataclysm/region_settings/tropical_regional_map_settings.json [hunk 2]
```diff
@@ -3,7 +3,7 @@
     "type": "region_settings_river",
     "id": "default",
     "copy-from": "default",
-    "river_scale": 1.65
+    "river_scale": 1
```
Comment (Karol1223) [inline data/mods/TropiCataclysm/region_settings/tropical_regional_map_settings.json:6]: Does this really not work? I modified this recently and it really looked like it changed mapgen during testing, though I didn't know of any objective ways to test if it worked.

Comment (maniak1349) [reply data/mods/TropiCataclysm/region_settings/tropical_regional_map_settings.json:6]: Well :
https://github.com/CleverRaven/Cataclysm-DDA/blob/266d8905dbf913491e32aaaa7d62ad1c42bbcb05/src/regional_settings.h#L250
so something was happening to those values one way or the other. I was changing values with assumption that float->int by `AsInt64` truncates values based on [this](https://github.com/google/flatbuffers/blob/8914d06ab7123167424438cf293bb349833bcb7d/include/flatbuffers/flexbuffers.h#L468-L471). If that is correct then yes - it didn't really work.

If it is not the case, if CDDA uses some other flexbuffer then maybe `AsInt64` was doing rounding instead and 1.65 was turning into 2.

Edit: actually there we go
https://github.com/CleverRaven/Cataclysm-DDA/blob/266d8905dbf913491e32aaaa7d62ad1c42bbcb05/src/third-party/flatbuffers/flexbuffers.h#L434-L437
So it was going back to 1.
