### PR TITLE
Fixes for abandoning camps

### LINKED ISSUE #45731: Crash when trying to re-establish an abandoned camp
I did not know how to add or edit zone in a faction camp, so I decided to abandon it and to create it again. At the time it did not have any upgrades, or anything else, except for a few loot zones. After being abandoned, my NPC had a dialog option: "We need to abandon this camp", which did nothing when clicked. He also had an option: "Something-something, this is your new job at the faction camp", which prompted "Enter the new camp name", and upon entering the name and pressing 'y', the game crashed.

Attached is the save with the bug. To reproduce, load in the only character there and head to the nearest shelter. Then talk to the NPC there.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5613378/save.zip)

### LINKED ISSUE #47332: [Faction Camp] Re-entering camp after abandoning is broken
# Describe the bug

When you abandon the base camp and then de-abandon it (via "show me what needs to be done at the camp."), you lose options. Partially related to #47319.

If you complete the mission than the options will return.

# Steps To Reproduce

1. Teleport to an empty field.
2. Spawn an NPC
3. Finish their quest
4. Start a camp `d` -> `i`
5. Abandon Camp `d` -> `j`
6. Ask the NPC to "show me what needs to be done at the camp." `d` -> `k`

# Expected behavior

That all options are maintained. 

# Screenshots
Before:
image
After:
image

Relevant dialogue options (in orange):
image

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9442-ge9e4d33-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### LINKED ISSUE #47838: [Faction Camp]Giving NPC order to "show me what needs to be done at the camp." crashes the game
# Describe the bug
[Faction Camp]Game crashes when re-entering camp after abandoning 

(via "show me what needs to be done at the camp."), 
# Steps To Reproduce

1. Start a camp d -> i
2. Abandon Camp d -> j
3. Ask the NPC to "show me what needs to be done at the camp." d -> k

# Describe the bug

[Faction Camp]Game crashes when re-entering camp after abandoning 

# Expected behavior

The npc giving the list of thing needed to be done in the camp 

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.E-9867-gadceb7b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    sees-player icon, retrodays [sees_player_retro],
    Graphical Overmap [Graphical_Overmap],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Alternative Map Key [alt_map_key],
    Stats Through Skills [StatsThroughSkills],
    No Fungal Monsters [No_Fungi]
]

# Additional context
[crash+debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6071259/crash%2Bdebug.zip)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6071260/save.zip)

### PR DESCRIPTION
**Pull request by angleKH**
#### Summary
Bugfixes "Fix being unable to re-establish camps near abandoned camps as well crashing when attempting to access an abandoned camp's missions"

#### Purpose of change
Fixes #45731, fixes #47838, and fixes #47332

#### Describe the solution

When the game creates a camp, it adds camps to the global camps list, but also overwrites the overmap terrain where the camp is. When the game abandons a camp it only deletes the camp from the global camps list, but does not restore the previous overmap terrain from before the camp was constructed. This fix checks for an existence of a camp by checking both things, instead of just one.
#### Describe alternatives you've considered
It would be better if the previous overmap terrain was restored, but I think that is currently not possible, but I am not familiar with the map system. The downside of not restoring overmap terrain is that if a new camp is constructed in the same place, only the barebones camp type can be constructed.

### CODE REVIEW

**Comment by Marcos6226** [comment]
Good work!

File: src/faction_camp.cpp [hunk 1]
```diff
@@ -683,8 +683,14 @@ void talk_function::start_camp( npc &p )
     for( const auto &om_near : om_building_region( omt_pos, 3 ) ) {
         const oter_id &om_type = oter_id( om_near.first );
         if( is_ot_match( "faction_base", om_type, ot_match_type::contains ) ) {
-            popup( _( "You are too close to another camp!" ) );
-            return;
+            auto const &building_omt_pos = om_near.second;
+            auto const &camps = overmap_buffer.get_om_global( building_omt_pos ).om->camps;
+            if( std::any_of( camps.cbegin(), camps.cend(), [&building_omt_pos]( const auto & camp ) {
```
Comment (irwiss) [inline src/faction_camp.cpp:688]: imo auto makes this harder to read than it can be with proper types (they're pretty short in this case)

Comment (dseguin) [reply src/faction_camp.cpp:688]:
```suggestion
            auto const &building_omt_pos = om_near.second;
            auto const &camps = overmap_buffer.get_om_global( building_omt_pos ).om->camps;
            if( std::any_of( camps.cbegin(), camps.cend(), [&building_omt_pos]( const basecamp & camp ) {
```

File: src/faction_camp.cpp [hunk 2]
```diff
@@ -683,8 +683,14 @@ void talk_function::start_camp( npc &p )
     for( const auto &om_near : om_building_region( omt_pos, 3 ) ) {
         const oter_id &om_type = oter_id( om_near.first );
         if( is_ot_match( "faction_base", om_type, ot_match_type::contains ) ) {
-            popup( _( "You are too close to another camp!" ) );
-            return;
+            auto const &building_omt_pos = om_near.second;
+            auto const &camps = overmap_buffer.get_om_global( building_omt_pos ).om->camps;
```
Comment (dseguin) [inline src/faction_camp.cpp:687]:
```suggestion
            tripoint_abs_omt const &building_omt_pos = om_near.second;
            std::vector<basecamp> const &camps = overmap_buffer.get_om_global( building_omt_pos ).om->camps;
```
