### PR TITLE
Fix is_ot_type matching incorrect locations

### LINKED ISSUE #30638: Refugee Center bay clearance mission not spawning target zombie.
# Describe the bug
The first mission given by the 'Trader' NPC at the Refugee Center to clear out their barricaded bay does not spawn the targeted zombie.

# Steps To Reproduce

1. Start new world with default settings. Turn on NPCs. Wandering Spawns.
2. Locate and Teleport to nearest Refugee Center.
3. Speak to an accept the NPC's question. proceed to the locked bay.
4. Fail to find the appropriate zombie.

# Expected behavior

4. Find and Kill the zombie.
5. Profit.

# Screenshots

# Versions and configuration
- OS: Windows [64-bit]
- Game Version: 0.D-3178-g258b2e8
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

### PR DESCRIPTION
**Pull request by ralreegorganon**
#### Summary

SUMMARY: Bugfixes "Fix is_ot_type matching incorrect locations"

#### Purpose of change

Fixes #30638 

`overmap::is_ot_type` was allowing partial matches for an overmap terrain, which is ok and desired in some cases, but was doing it based on checking that the substring had a particular format which lead to false positives when matching locations that happened to have common substrings.

#### Describe the solution

* Rename `is_ot_type` to `is_ot_prefix`.
* Add a new `is_ot_type` which replaces the substring matching with a comparison to the underlying type for the overmap terrain, which will allow matching rotated terrains and linear terrains, but won't match unrelated terrains that happen to have the same substring.
* Review all the usages of `is_ot_type` and change to `is_ot_prefix` where necessary to maintain current behavior. Almost all of these could (and probably should) be subsequently updated to match a set of overmap terrains using the new `is_ot_type`, as matching on prefix is error prone and requires people creating JSON content to be aware of implicit behaviors when picking internal ids.
* Fix two instances where the MGOAL_GO_TO_TYPE destinations were no longer valid (since they were prefixes instead of types).

#### Describe alternatives you've considered

We should probably ultimately deprecate and remove the prefix (and "subtype," which allows variable prefixes and suffixes) based approach entirely in favor of using more explicit specifications--be it updating the code to explicitly check specific overmap terrain types, converting the checks to flags, updating the mission code to allow specifying multiple valid destinations, and/or any other additional reasonable fixes (and combos of the aforementioned).

#### Additional context

An easy way to replicate the type of bug this fixes is to start a new game using the evacuee in the evac shelter and use the computer to find the evac center. Before this fix, it will find it and place the mission target on z-4 because the mission targets `refctr_S3e` but matches `refctr_S3e_z-4` before it gets a chance to match `refctr_S3e` because it scans from the bottom up. After the fix, it'll correctly target the actual `refctr_S3e` terrain on z0.

*he's baaaaaaaack*
image

### CODE REVIEW

File: src/newcharacter.cpp [hunk 1]
```diff
@@ -567,7 +567,7 @@ bool avatar::create( character_type type, const std::string &tempname )
     // Learn recipes
     for( const auto &e : recipe_dict ) {
         const auto &r = e.second;
-        if( !r.has_flag( "SECRET" ) && !knows_recipe( &r ) && has_recipe_requirements( r ) ) {
+        if( !knows_recipe( &r ) && has_recipe_requirements( r ) ) {
```
Comment (Night-Pryanik) [inline src/newcharacter.cpp]: This seems wrong.

Comment (ralreegorganon) [reply src/newcharacter.cpp]: Yeah, some garbage caused by my computer crashing, corrupting .git/HEAD, and then missing something in cleanup.
