### PR TITLE
Better vehicle dragging

### LINKED ISSUE #65972: || 4" Casters make moving a cart harder.
### Describe the bug

My strength 6 character uses a foldable cart he calls "gopher".  After updating to the newest experimental, he can no longer pull the cart except on streets, and even on streets my messages gets spammed by, "It takes some time to move the gopher."

Removing the casters lets me once again pull the cart over grass, and over roads without spam messages.

### Attach save file

[Holcomb-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11635822/Holcomb-trimmed.tar.gz)

### Steps to reproduce

1. Open save.  Character should already have an EMPTY foldable cart grabbed.  
2. Drag the wheeled cart around.  See lots of, "It takes some time to move the gopher" messages, and you strain yourself pulling it on the grass.
3. Remove casters.
4. Drag the cart around.  You will have no problem dragging it over the street or the grass to the left.

### Expected behavior

Wheels make a cart easier to move over pavement, dirt and short grass.

If || no longer means "like new," it still means nothing more than a wobbly wheel, which doesn't make it more difficult to move than no wheels at all.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.6 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.G-2161-g1484ebeee9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Sly's Skill Antirust [slysskillantirust]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
None

#### Purpose of change
* Closes #65972

#### Describe the solution
Granularize the str_req so that there's a difference between dragging a wheel-less 1kg and a wheel-less 99kg object. Gameplay effect: Vehicles below 100kg are no longer anti-gravity devices.

Clamp the str_req for wheeled vehicles. If it's easier to push the thing without wheels... just don't use the wheels. Gameplay effect: It's no longer easier to push a cart with the wheels off.

#### Testing
I've been pushing carts and trucks around for like an hour now

### CODE REVIEW

File: src/grab.cpp [hunk 1]
```diff
@@ -74,14 +74,17 @@ bool game::grabbed_veh_move( const tripoint &dp )
 
     //vehicle movement: strength check. very strong humans can move about 2,000 kg in a wheelbarrow.
     int mc = 0;
-    int str_req = grabbed_vehicle->total_mass() / 100_kilogram; //strength required to move vehicle.
+    //strength required to move vehicle.
+    int str_points_req = grabbed_vehicle->total_mass() / 1_kilogram;
```
Comment (wormingdead) [inline src/grab.cpp:78]: Am I reading this right that moving a 25 kg (55 lb) vehicle requires 25 STR?

Comment (wormingdead) [reply src/grab.cpp:78]: It seems like you could change this to divide by `10_kilogram` and remove/reduce the other divisions. Whenever `str_points_req` is used, it's being divided by a multiple of ten.

Comment (RenechCDDA) [reply src/grab.cpp:78]: > Am I reading this right that moving a 25 kg (55 lb) vehicle requires 25 STR?

No, the math works out the same as before (100kg vehicle requires 10 str) but it's more granular. Rather than increasing by 10 every 100 kilograms, it's 1 every 10 kilos.

Comment (wormingdead) [reply src/grab.cpp:78]: Is there a better way to word the comment on line 77, then? I'm not sure how to parse it.

Comment (RenechCDDA) [reply src/grab.cpp]: This last commit might be a little more understandable

Comment (wormingdead) [reply src/grab.cpp]: Makes a lot more sense, thanks

**Comment by wormingdead** [comment]
Maybe this is a bit nitpicky, but the commit message for [82eeea8](https://github.com/CleverRaven/Cataclysm-DDA/pull/72515/commits/82eeea8e8637dae447787fdda46c4c9e6f80f6a7) doesn't mention the value changes, which can make searching through the history difficult.
