### PR TITLE
Fix proficiency books' effect on crafting

### LINKED ISSUE #48465: Mitigated proficiency penalties do not apply correctly to crafting time
# Describe the bug

Mitigated proficiency time penalties from books do not actually decrease the time to complete the craft. The crafting interface shows the penalties as mitigated, but the "Time to complete" still shows the unmitigated penalty, and crafting itself also uses this value.

# Steps To Reproduce

1. Spawn in a copy of "The Historic Weaponsmith".
2. Set fabrication skill to 9.
3. Give yourself the 'Principles of Metalworking', 'Blacksmithing' and 'Carving' proficiencies, for easier values to calculate with.
4. Open the crafting interface and search for 'zweihänder'. Its base crafting time is 8 hours, the mitigated Bladesmithing time penalty shows as 1.5x, but the time to complete is still 16 hours (using Bladesmithing's unmitigated time penalty of 2x).

# Expected behavior

"Time to complete" should show "12 hours".

# Screenshots

proficiency_penalty_mitigation

# Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: 0.E-10367-g47c9250-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
    ]

# Additional context

[recipe::time_to_craft_moves](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/recipe.cpp#L75) uses the raw `time_multiplier` and does not take book bonuses into account. [recipe::proficiency_time_maluses](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/recipe.cpp#L743) looks like it does pretty much what's needed here (modulo `const`-ness).

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Bugfixes "Fix proficiency books' effect on crafting"

#### Purpose of change

Fixes #48465
PR #46347 added the ability for books to partially mitigate the crafting penalties incurred due to missing proficiencies, as described in FR #44680. However, it introduced some issues.

1. It changed the crafting UI but didn't actually change the crafting time. If you read recipe::time_to_craft_moves() it's pretty clear that book proficiencies are not used. The total time taken to craft an item when you're missing proficiencies is unaffected by books (verified via gameplay as well). Reported in #48465

2. It implemented the mitigation formula incorrectly, which would result in books letting you craft faster when missing a proficiency than when you had the proficiency (if they actually took effect). This caused player confusion, e.g. #46662
When a book provides a proficiency time_factor of 0.1, a malus of 1.5 due to lacking that proficiency should become 1.05 (1 + 0.5 * 0.1) not 0.15 (1.5 * 0.1). The book is supposed to reduce the penalty, not turn it into a bonus.

3. The formula for stacking mitigation effects from multiple books is also wrong and can result in negative proficiency malus.
With 2 books that provide time_factors of 0.1 and 0.5, the formula from #44680 (as implemented in the current code) yields a combined time_factor of 1 - sqrt((1 - 0.1)^2 + (1 - 0.5)^2) = -0.03, which is nonsense.

4. The book proficiency mitigation effect on the failure rate was also not getting applied ~~(in addition to the penalty acting as a bonus, see #48673)~~

#### Describe the solution

1. Modified recipe::time_to_craft_moves() to call proficiency_time_maluses().
2. See #48658
3. See #48658
4. Divide the crafting success roll by the recipe's proficiency_time_maluses().

~~Unresolved issues:~~

- ~~it makes the game slow to a crawl when crafting in the middle of a pile of books and ingredients~~ [fixed]
- ~~it removes const qualifiers from a bunch of APIs, which feels very wrong~~ [fixed]

The slowdown was due to calling Character::crafting_inventory() from the proficiency_time_maluses() added to recipe::time_to_craft_moves(), which is called many times while crafting from craft_activity_actor::do_turn(). Character::crafting_inventory() is an expensive member function of the player object that needs to scan all nearby items. It's non-const (hence the removal of const qualifiers) because it does caching. But the cache is only valid for one turn, which doesn't help in this situation.
The fix for this was to cache the results of the two rec.batch_time() calls in craft_activity_actor::do_turn(). The cache is invalidated when crafting speed or assistants change, and at 5% progress increments when proficiencies may be gained.

#### Describe alternatives you've considered

Rolling back #46347. But I like the idea and I really want this to work. 

~~Not sure if I need to also check for a change in craft.charges as a condition that invalidates the cache.~~ [no, it doesn't change] On the other hand, it may be possible to remove the check for changing speed and assistants (which may also slow down crafting due to looking around the map) and rely entirely on the 5% progress updates. We might be using the wrong crafting times sometimes, but not for longer than 5% of the crafting progress. But, 5% could be a long time for some recipes.

Comparing floating point numbers in the cache invalidation check is probably not ideal. Maybe use epsilon equality.

Considered changing craft_activity_actor::start() to calculate the total number of moves required there instead of in craft_activity_actor::do_turn(). But the number of moves may change during crafting.

To avoid propagating non-const references, I have 2 ideas for changing Character::crafting_inventory() to be a const member function. One is to put the crafting inventory cache into a static global variable, the other is to use a const_cast inside that function to force-allow modification of the cache object. I can't say that I'm a big fan of either approach.

#### Testing

Build 2 game binaries, one without this change ("before") and one with ("after").
Using "before", start a new game in evac shelter. Debug all skills to 10 and INT to 20. Debug unlock all recipes. Debug the Life Support, HVAC mutations. Move next to a computer terminal for the light (but not next to any counter, which boosts crafting speed) or spawn and activate an atomic light. Debug kill all monsters. Debug spawn a plank and 2 long strings. Save.

Bring up the crafting menu and look at "short bow".
<details>

</details>
Due to lacking proficiencies it will take 20 hours (5x increase) as indicated by "Time to complete".
Craft the bow, using a stopwatch to measure how long it takes in real time. Observe that it finishes at 4am (20 game hours later).
On my computer it takes 30s of real time.

Reload (still using "before"). Spawn "The Bowyer's Buddy", and bring up the crafting UI again.
<details>

</details>
Although the text indicates that your crafting penalty has changed to 3.8x the "Time to complete" still shows 20 hours. This is the buggy behavior we're trying to fix.
Craft the bow. Observe that it finishes at 4am (20 hours later). 

Switch to the "after" binary and reload. Verify that the crafting UI looks the same as in "before" without a book, and you can craft the bow in 20 hours (finish at 4am).
To measure performance regression, time the operation. On my computer it took 31 seconds, which agrees with the "before" timing within measurement error.

Reload. Spawn the book. The UI should now look like this:
<details>

</details>
The "Time to complete" is now 17 hours. (4h base * 4.25 mitigated crafting malus).
Craft the bow. Observe that it finishes at around 1 am (17 game hours).
On my computer it takes 27s of real time.

Here's a more complicated example with a multiple-proficiency craft and a pile of books.
<details><summary>Before</summary>

</details>
<details><summary>After</summary>

</details>
Crafting time reduced from 3 days to 1 day 18 hours by the presence of proficiency-mitigating books.

#### Additional context

For my next PR I plan to implement another of Erk's ideas from #44680:
`Once we have the ability to reduce proficiency penalties by a factor, the same infrastructure could and should be used to make proficiency penalties gradually fall off as you get close to the necessary xp to have the proficiency.`

### CODE REVIEW

**Comment by eltank** [comment]
I am moving fixes 2 and 3 to a separate PR (#48658), since fixing 1 is going to take a while. Please review that first.

**Comment by Salty-Panda** [comment]
Looking good.
About cached_inv, maybe chek book_proficiency_bonuses at the start/resume of crafting and put it in proficiency?
Not sure how simple will it be to pass it from there to the crafting function though.

**Comment by eltank** [comment]
I found a simple solution that seems to work. I'm caching the calls to rec.batch_time() in craft_activity_actor::do_turn(). The cache is invalidated when crafting speed or assistants change, and at 5% progress increments when proficiencies may be gained. Playtesting confirms that the massive slowdown is eliminated by doing this. I used debug messages to verify that the cache is re-populated only at the 5% increment marks under normal conditions. PR updated.

**Comment by ferociousdork** [comment]
> **Still looking for advice regarding the non-const references (see also alternatives considered).**

Standard practice would be to make the members involved in the caching `mutable` so you can keep the methods const.

**Comment by eltank** [comment]
Thanks, I'm ashamed to admit that I didn't know C++ had a "mutable" keyword. Sounds good, I'll give that a shot.

**Comment by eltank** [comment]
I was stuck in "const hell" for a while because item_location code is really not designed to work with const item pointers. I bailed out because I think it would take a lot of work to change that. 
In the end I ended up marking the Character inventory cache fields "mutable" but I still needed to use a const_cast in order to call Character::all_items_loc() from Character::crafting_inventory(). It was either that or mark "worn" and "weapon" as mutable too, which seemed worse.

I also noticed that the crafting failure formula is making recipes X times more likely to succeed instead of X times less likely when you're missing proficiencies (and it's also not affected by books), so I need to investigate/fix that before marking the PR as ready. 
I will fix the formula in a separate PR though since it could make a lot of players angry -- so far nobody complained about the harsh proficiency penalties on crafting success rates because they were not taking effect, but once it's fixed crafting without required proficiencies will become a lot harder. But I'll handle the book-based failure mitigation in this PR.

**Comment by eltank** [comment]
All the fixes are in, ready for review now. I would prefer to get #48658 and #48673 in first (although this PR contains the work from the others too). That would allow me to rebase and shrink this PR (actually not sure if rebase is needed or GitHub will recompute the diff against master's head automatically).

**Comment by Evrze** [comment]
There is no bonus to mitigation, if you mitigate it can only to at best to 0x, which pushes it closes to the normal rates of 50% chance success or the value of 1. Any increment of the multiplier will increment the value of 1 a degree higher.

It's just unclear to people because they don't know where the normal point exists between the calculations. Having proficiency already provides a bonus effect. You can even see the difference in time between the normal value and the proficiency mitigating closer to 0x.

**Comment by I-am-Erk** [comment]
Before I add this to the pile, are there any string changes for translation in here? I see on the other pr you were conscious of the concerns there.

**Comment by actual-nh** [comment]
> Before I add this to the pile, are there any string changes for translation in here? I see on the other pr you were conscious of the concerns there.

I'm not seeing any.

**Comment by actual-nh** [comment]
@eltank: Rebasing looks likely to fix the clang build analyzer and clang-tidy fixes; see #48977. Checking Travis.

**Comment by eltank** [comment]
Correct, I avoided modifying any strings in order to make it possible to put this in 0.F.
@actual-nh  Sorry, I didn't see your last edit so I rebased my PRs on the current version of master. I'll rebase again after that fix is in.

**Comment by eJ0opb** [comment]
> Correct, I avoided modifying any strings in order to make it possible to put this in 0.F.
> @actual-nh Sorry, I didn't see your last edit so I rebased my PRs on the current version of master. I'll rebase again after that fix is in.

The commit that made that #49048 necessary was reverted on master.

**Comment by eltank** [comment]
> The commit that made that #49048 necessary was reverted on master.

Thanks for the clarification. If the reversion you're talking about is #49053 then I already picked it up when I rebased so I expect to not need another rebase. I see that the tests appear to be passing (though not all have finished).

**Comment by eltank** [comment]
I've updated the PR (rebased on master now that #48658 has been merged), reducing the number of diffs.

File: src/character.h [hunk 1]
```diff
@@ -2929,9 +2922,11 @@ class Character : public Creature, public visitable
...
         struct weighted_int_list<std::string> melee_miss_reasons;
 
-        int cached_moves;
-        tripoint cached_position;
-        pimpl<inventory> cached_crafting_inventory;
+        /* crafting inventory cached time */
+        mutable time_point cached_time;
+        mutable int cached_moves;
+        mutable tripoint cached_position;
+        mutable pimpl<inventory> cached_crafting_inventory;
```
Comment (jbytheway) [inline src/character.h:2929]: If these are all related to the cached crafting inventory then it might be cleaner to separate them out into a new `struct` and then you could have just one mutable member of `Character` which is that new `struct`.  OTOH, that's probably a lot of churn which maybe should be a separate PR.

File: src/crafting.cpp [hunk 2]
```diff
@@ -561,7 +554,7 @@ const inventory &Character::crafting_inventory( const tripoint &src_pos, int rad
         cached_crafting_inventory->form_from_map( inv_pos, radius, this, false, clear_path );
     }
 
-    for( const item_location &it : all_items_loc() ) {
+    for( const item_location &it : const_cast<Character *>( this )->all_items_loc() ) {
```
Comment (jbytheway) [inline src/crafting.cpp:557]: So the morally correct thing here would be to introduce a new `const_item_location` class which is like `item_location`, except with const access to the underlying item, and then have a `const` overload of `all_items_loc` which uses that.  It looks like `cached_crafting_inventory.add_item` copies its argument, so I think that should work.

That's the sort of thing that could reasonably go in a follow-up PR.

**Review by jbytheway — COMMENTED** [review]
I think the `const` additions here are generally a step in the right direction, so thanks for that.

I haven't understood the details of exactly how your other changes affect the logic.  I'd be happier if you could add a unit test that fails with the old code but passes with the new code.  There's already some crafting tests that you could hopefully use for inspiration.

**Comment by eltank** [comment]
I'll work on adding a unit test in crafting_test.cpp today. In order to avoid brittle expectations such as finishing the craft in a specific number of turns I'll probably just compare the time taken to craft with and without a book present.

**Comment by actual-nh** [comment]
> I'll work on adding a unit test in crafting_test.cpp today. In order to avoid brittle expectations such as finishing the craft in a specific number of turns I'll probably just compare the time taken to craft with and without a book present. [Done]

Is a further check vs how long with the actual proficiency (that that's less time still) desirable?

**Comment by eltank** [comment]
> > I'll work on adding a unit test in crafting_test.cpp today. In order to avoid brittle expectations such as finishing the craft in a specific number of turns I'll probably just compare the time taken to craft with and without a book present. [Done]
> 
> Is a further check vs how long with the actual proficiency (that that's less time still) desirable?

Good idea. The time taken with the book should be strictly between the time taken with no prof and no mitigation and time taken with the prof.

File: src/character.h (hunk 1 above)
Comment (eltank) [reply src/character.h]: Done. I considered doing that earlier but wasn't sure where to put the struct definition. I've now added it in-place since I've seen that being done in other places. Also noticed that the "radius" cache parameter was stored in a static var instead of a field for reasons I could not comprehend so I added it to the struct.
Do you think it's worth adding any methods (like reset/invalidate) to the struct?

File: src/crafting.cpp (hunk 2 above)
Comment (eltank) [reply src/crafting.cpp:555]: I still have a bit of PTSD from the last time I tried propagating const-ness to item_location. I would definitely prefer to leave it for another PR since even if I succeed with this new approach it will introduce a lot of extra diffs.

**Comment by eltank** [comment]
> I haven't understood the details of exactly how your other changes affect the logic. I'd be happier if you could add a unit test that fails with the old code but passes with the new code. There's already some crafting tests that you could hopefully use for inspiration.

Summary of key changes:
- recipe.cpp:70 (calls proficiency_time_maluses(), which incorporates book mitigation, instead of applying unmitigated penalties)
`return time * proficiency_time_maluses( guy );`
- crafting.cpp:1015 (calls proficiency_failure_maluses() instead of applying unmitigated penalties)
`return ( skill_roll / diff_roll ) / making.proficiency_failure_maluses( *this );`

The caching in craft_activity_actor::do_turn (activity_actor.cpp:1769) was necessary to fix a performance issue resulting from the above changes.
Everything else is code cleanup because I didn't want to drop more const qualifiers from existing methods and I added back some of the const qualifiers removed by #46347.

The newly added test fails on master because of the first check (`mitigated_time_taken < unmitigated_time_taken`) since book proficiency mitigations have no effect in that branch so the times are equal. 
I don't have a test for checking that the failure rate is mitigated. I thought about simulating the crafting operation but that seems brittle due to the non-determinism of the failure calculations.

File: src/character.h (hunk 1 above)
Comment (jbytheway) [reply src/character.h]: > Do you think it's worth adding any methods (like reset/invalidate) to the struct?

Potentially.  If such code is currently duplicated, or there are `Character` methods that only refer to these fields, then they could sensibly be made a method of the struct.  Go with whatever you think makes the code most readable.

Comment (eltank) [reply src/character.h]: Ok, I'll leave it as is. The only "duplication" is between Character::Character() and Character::invalidate_crafting_inventory(), both of which call `crafting_cache.time = calendar::before_time_starts;` which seems reasonable to me.

File: src/crafting.cpp (hunk 2 above)
Comment (I-am-Erk) [reply src/crafting.cpp:555]: Can you add a comment suggesting that this would be a good thing to add, perhaps?

**Review by I-am-Erk — APPROVED** [review]
As far as I can tell this is good to go. I would not mind seeing a few more comments on it for future editors. I will clear with a more versed person before merging.

**Review by mlangsdorf — APPROVED** [review]

File: src/crafting.cpp (hunk 2 above)
Comment (eltank) [reply src/crafting.cpp:557]: Done.
