### PR TITLE
typified a little bit of map.h + dependents

### LINKED ISSUE #76336: map::process_fields_in_submap is probably bugged
### Describe the bug

The operation process_fields_in_submap defined in map.h is defined using an untyped tritype and is called from a single location in map_field.cpp, This call is made from map::process_fields, where the untyped tripoint is created from x, y, z, which are iterators over the submaps of the calling map, which implies the proper type should be tripoint_bub_sm.
However, the first thing done in map::process_fields_in_submap is to convert the untyped tripoint to be an OMT reference, and then cast it to tripoint_abs_omt, before being sent to overmap_buffer.ter to get the terrain of the overmap tile.
As far as I can see, a bubble submap coordinate cannot be converted into an OMT coordinate, as it's may not be OMT aligned. Instead of feeding "submap" to "sm_to_omt_copy" the code should feed it "abs_sub.raw() + submap" in order to actually convert an absolute submap location to the OMT conversion and ultimately to the "overmap_buffer.ter" call.

Edit:
It's even worse, as the operation also calls map::on_field_modified with the untyped parameter being fed with submap coordinates (in three places), while the other uses of that operation feeds it bubble coordinates and its implementation implies usage of bubble coordinates, which should cause the wrong location's caches to be marked as dirty.

### Attach save file

N/A. It's the source code referenced.

### Steps to reproduce

Examine the code as per the description.

### Expected behavior

I don't know what the overmap terrain id is used for, but it's probably not extremely important, given that serious issues aren't reported.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4780 (22H2)
- Game Version: 0.G-12001-gab062c5e8b-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]
Only the game version is relevant. It's dirty because I'm working on typification, which is where I encountered this.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
A baby step converting usage of untyped coordinates into typed ones.
Still working on map.h and dependents.
Edit:
Fix #76336. Correction slipped in inadvertently (failed to clear it out after investigation). Note that the misapplied type part still remains, but it can be cleaned up when the operation is typified (probably the next PR), and it has no technical impact.

#### Describe the solution
Convert/duplicate untyped operations into corresponding types ones and converting usages to the typed one when it can be done with reasonable ease.
Ended up with a tangent into testing code... Has to be done eventually regardless.

Note that it should result in no functional change.
Edit: That turned out not to be correct. A correction to #76336 happened to remain in the code as I missed to remove it. However, that correction should be done, but I don't know how we'd be able to detect or test it.

#### Testing
Loaded a save, walked out of a basement, into a car, drove a bit through hay bales. Nothing odd seen.

#### Additional context
Another goose chase after template messes suddenly deciding it couldn't resolve unchanged code. A theory is that inclusion of coords_fwd.h in some header that might have been included transitively caused it to suddenly fail to resolve types (or it could just be pure spite...). This time it was possible to nail down the type to use by specifying it (although it should change to a typed one eventually, but that pain is for another day).
If anyone is interested, the mess was caused by visitable_zone_test.cpp operation place_structures, where "rectangle" decided it wasn't resolved any longer.

### CODE REVIEW

**Comment by mqrause** [comment]
I only noticed this PR after #76623, which caused a small conflict that hopefully shouldn't be too hard to fix. Now with #76671 there are even more chances for conflicts, or even code errors if they're merged independently, so I'll probably leave that in draft until this one is merged.

> If anyone is interested, the mess was caused by visitable_zone_test.cpp operation place_structures, where "rectangle" decided it wasn't resolved any longer.

Interestingly my VS tells me that's an error, but still compiles it without issues. The fix isn't wrong, though.

**Comment by PatrikLundell** [comment]
@mqrause: Merge conflicts happen all the time with this. Both because the tentacles spread all over the place, and thus bump into a lot of stuff, and because it often takes a lot of time for these PRs to be merged.

I haven't looked at your new PR yet, but I think in general it should be sufficient to provide a warning against concurrent merging. If it's anything like the previous typification PR it should be rather contained and quickly reviewed and merged, while this PR may well linger for another month.

Finally, thanks for looking at the template issue. It's definitely helpful to get a competent assessment of such issues.

File: src/map.h [hunk 1]
```diff
@@ -1228,9 +1220,6 @@ class map
         // TODO: fix point types (remove the first overload)
         bool has_flag_furn( ter_furn_flag flag, const tripoint &p ) const;
         bool has_flag_furn( ter_furn_flag flag, const tripoint_bub_ms &p ) const;
-        bool has_flag_furn( ter_furn_flag flag, const point &p ) const {
-            return has_flag_furn( flag, tripoint( p, abs_sub.z() ) );
-        }
```
Comment (mqrause) [inline src/map.h:1233]: There are a few `point` overloads like this that you simply removed instead of making a `point_bub_ms` version. Is there a particular reason for that? I didn't check all of them, but they seemed to have been rarely used anyway, so I don't think it's a real issue, I'm just wondering.

**Review by mqrause — APPROVED** [review]
Looks good to me, just minor comments that don't really require action.

But as expected there are a few minor cases where this and #76671 will clash, so they definitely can't be merged together. Should be easy fixes for whoever gets merged last, though.

File: src/npcmove.cpp [hunk 2]
```diff
@@ -3416,17 +3416,17 @@ void npc::move_away_from( const std::vector<sphere> &spheres, bool no_bashing )
...
+        pt_min.x() = std::min( pt_min.x(), elem.center.x - elem.radius );
+        pt_min.y() = std::min( pt_min.y(), elem.center.y - elem.radius );
+        pt_max.x() = std::max( pt_max.x(), elem.center.x + elem.radius );
+        pt_max.y() = std::max( pt_max.y(), elem.center.y + elem.radius );
     }
 
-    tripoint_bub_ms minp( pt_min.x, pt_min.y, pos_bub().z() );
-    tripoint_bub_ms maxp( pt_max.x, pt_max.y, pos_bub().z() );
+    tripoint_bub_ms minp( pt_min, pos_bub().z() );
+    tripoint_bub_ms maxp( pt_max, pos_bub().z() );
```
[the remark this answers is not in the document]
Comment (PatrikLundell) [reply src/npcmove.cpp:3429]: I wasn't clear on why you'd done it the way you did, but decided you probably had a good reason, and at worst it's not harmful.

File: src/map.h (hunk 1 above)
Comment (PatrikLundell) [reply src/map.h:1233]: I removed them when they weren't used anyway. My thinking was that it's better to try to use 3D coordinates than to use 2D with an implicit Z coordinate coming in from the side, so removing unused operations pushes future use towards the existing 3D versions.

It's not a clear cut and obvious path, though, so I'd like to hear if you think it's misguided.

**Comment by PatrikLundell** [comment]
Note that we just had a rare case of no tests failing. Just noting this, as it's unlikely to remain the case after updating based on the review.

File: src/map.h (hunk 1 above)
Comment (mqrause) [reply src/map.h:1233]: I'm not deep enough into map code to really have a preference there, so I'm fine with it either way.
