### PR TITLE
Fix long text in item action menu

### LINKED ISSUE #59253: Being able to repair many materials disrupts UI
### Describe the bug

In menus listing the option to repair materials, being able to repair a large number of different materials causes the window to be needlessly large. This can also cause certain pieces of the UI to be obscured, because there is insufficient room for them.

### Steps to reproduce

1. Add arc welder to inventory
2. Open actions menu (% by default)

### Expected behavior

This is technically correct behavior, but there should really be some kind of maximum length, and anything after that should be replaced by ellipses.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1766 (21H1)
- Game Version: 10a4412 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Alternative Map Key [alt_map_key]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by irwiss**
#### Summary
None

#### Purpose of change
Fixes #59253

#### Describe the solution
Add 2 overloads to `uilist` and `uilist_entry` to allow description overload use `input_event` instead of `int` for hotkey.
Add `get_description` to `use_function` and `iuse_actor`
This allows uilist description box to list repair materials.

May be other use actors could use description box for something as well?
Currently it's a bit awkward that only repair uses it

#### Describe alternatives you've considered
The alternative is ellipsis after N items as suggested in original issue or may be removing materials list altogether?

Would be nicer to have a specialized repair/mend UI but that'd go way out of scope for bugfix

#### Testing
* Apply patch, debug arc welder + battery, insert battery into arc welder
* Press %, menu should now have sensible width on screen
* Scroll down to "Repair" with welder, materials should be listed in description box

#### Additional context

image

(Before can be seen in the original issue #59253)

### CODE REVIEW

File: src/iuse_actor.cpp [hunk 1]
```diff
@@ -3322,6 +3322,11 @@ std::string repair_item_actor::action_description( repair_item_actor::repair_typ
 }
 
 std::string repair_item_actor::get_name() const
+{
+    return string_format( _( "Repair" ) );
```
Comment (Qrox) [inline src/iuse_actor.cpp:3326]:
```suggestion
    return _( "Repair" );
```

Comment (irwiss) [reply src/iuse_actor.cpp:3326]: Put the string_format because cast_spell_actor::get_name had it, thought it was an idiomatic way to write it, i'll resolve soon
https://github.com/CleverRaven/Cataclysm-DDA/blob/f0b7411fe50efa396fba91de33e870384890be92/src/iuse_actor.cpp#L2509-L2516
