### PR TITLE
bugfix_line_spell: prevent narrow line spells from being stopped early

### LINKED ISSUE #39955: Line attack spells only damage the enemy at target
# Describe the bug

I tried using Lightening bolt and Mana beam, both of them are like this.

# Steps To Reproduce
Just simply cast a line attck spell.

# Expected behavior
Those spells should damage all enemies in the area.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-1078-gb459021 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    No Rail Stations [No_Rail_Stations],
    DinoMod [DinoMod],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    Stats Through Skills [StatsThroughSkills],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

# Additional context
I tried to solve this bug by my self but I cannot as I am not experiance in C++ and also not familiar with the game's code. It is very strange. I guess there should be some problem with in this function.
`void spell_effect::line_attack( const spell &sp, Creature &caster,
                              const tripoint &target )
{
    damage_targets( sp, caster, spell_effect_area( sp, target, spell_effect_line, caster,
                    sp.has_flag( spell_flag::IGNORE_WALLS ) ) );
}`
as function damage_targets and spell_effect_area works fine in function cone_attack and target_attack I think its not the problem. But function spell_effect_line has worked nicely in the aiming related code as when I choose target for the spell the affected area are is shown correctly. However it didn't work when executed in damage_targets, because when I cast fireball there are 30+ of sounds produced as each tile in the affected area should have sound produced, but the two line attack spells that I have tested only have one sound produced. That means only one tile was captured as the area of spell effect.

### PR DESCRIPTION
**Pull request by OrenAudeles**
#### Summary
```SUMMARY: Bugfixes "Fix Narrow Line Spell Effects"```

#### Purpose of change
Line attack spells with narrow AOE (0 or 1) were being prevented from
actually working as intended. The exception added to the condition
prevents exiting early if the spell is a line attack.

Fixes #39955 

#### Describe the solution
Add an exception for line spells to `spell_effect_area` which generates the final list of points to have damage applied.

#### Testing
In the referenced issue spells such as `mana beam` and `lightning bolt` would at most produce a single sound, and damage a single monster. With the exception applied the same spells were able to damage all zombies covered by the targeting UI.

### CODE REVIEW

File: src/magic_spell_effect_helpers.h [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+class spell;
+struct tripoint;
+
+// spells do not reduce in damage the further away from the epicenter the targets are
+// rather they do their full damage in the entire area of effect
+std::set<tripoint> calculate_spell_effect_area( const spell &sp, const tripoint &target,
+        std::function<std::set<tripoint>( const spell &, const tripoint &, const tripoint &, int, bool )>
+        aoe_func, const Creature &caster, bool ignore_walls = false );
+
+#endif // CATA_SRC_MAGIC_SPELL_EFFECT_HELPERS_H
```
Comment (ZhilkinSerg) [inline src/magic_spell_effect_helpers.h:18]:
```suggestion
#endif // CATA_SRC_MAGIC_SPELL_EFFECT_HELPERS_H

```
