### PR TITLE
Fix unable to reload ammo nearby

### LINKED ISSUE #40814: Can not load Tailor's Kit from floor
# Describe the bug
Unable to load thread in Tailor's Kit from the floor or adjacent tile
Only able to "reload" from Inventory
Unsure if actually a bug or just the new way of thing

# Steps To Reproduce
1. Have unloaded Tailor's kit
2. Stand near thread, hit reload button,  "Nothing to Reload"
3. Stand on thread, hit reload button, "Nothing to Reload"
4. Pick up thread, hit reload button,  Reload works as normal

# Expected behavior

Previous versions one could load items while adjacent or on top of their "ammo"

# Screenshots
image

image

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2411-g7fcce2c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

### PR DESCRIPTION
**Pull request by kwl01skz**
#### Summary

SUMMARY: Bugfix "Fix unable to reload ammo nearby "

#### Purpose of change
Remove the useless code that caused the error

Before
We can only reload when we have ammo in our backpack.

After
We can reload when there is ammo on the map around us.

#### Describe the solution

When we reload an empty item  . This code verifies that we have ammo for reloading.
 But  Our code has been checked before. And these code is outdated, it does not check nearby items.
Simply deleting this code will work fine.

#### Describe alternatives you've considered

Rewrite these things, they are nested too many layers.

#### Testing
Now we can reload the ammunition nearby, and there will be a reasonable prompt when there is no ammunition, because other code does this.
fixed #40814

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -2485,12 +2485,6 @@ hint_rating player::rate_action_wear( const item &it ) const
 
 bool player::can_reload( const item &it, const itype_id &ammo ) const
 {
-    if( ammo.is_empty() ) {
```
Comment (KorGgenT) [inline src/player.cpp:2488]: this could cause crashes because `ammo` is often passed through as `""`, and is_reloadable_with will crash if the input is empty.

Comment (ZhilkinSerg) [reply src/player.cpp:2488]: `is_reloadable_helper` has checks for ammo string (non)emptiness.

Comment (ZhilkinSerg) [reply src/player.cpp:2488]: On second thought - looks like not all cases are covered there, so it probably caused #40830.

Comment (ZhilkinSerg) [reply src/player.cpp:2488]: Possible fix:

```CPP
bool item::is_reloadable_helper( const itype_id &ammo, bool now ) const
{
    if( !is_reloadable() ) {
        return false;
    }

    // empty ammo is passed for listing possible ammo apparently, so it needs to return true.
    if( ammo.is_empty() ) {
        return true;
    }

    if( magazine_integral() ) {
        if( ammo_data() ) {
            if( ammo_current() != ammo ) {
                return false;
            }
        } else {
            const itype *at = find_type( ammo );
            if( ( !at->ammo || !ammo_types().count( at->ammo->type ) ) &&
                !magazine_compatible().count( ammo ) ) {
                return false;
            }
        }
        return now ? ammo_remaining() < ammo_capacity( find_type( ammo )->ammo->type ) : true;
    }
    return magazine_compatible().count( ammo );
}
```
