### PR TITLE
Adjust effect intensity decay

### LINKED ISSUE #51332: Effect intensity never decays
### Describe the bug

Effects with their intensity supposedly decremented by the field `int_decay_tick` never change their intensity.

### Steps To Reproduce

1. Apply an effect with its intensity decremented by time (e.g. `paralyzepoison`) with a long duration - a drug effect or a monster special attack works in a pinch since the debug effect menu does not allow for defining the effect intensity or repeat applications of the same effect
2. Activate Debug mode's effect filter and check the intensity's effect on your @ menu
3. Wait an arbitrary amount of time and note that the intensity doesn't decrement (intensity is supposed to decrement every 10 minutes)

### Expected behavior

Effect code doing what it promises. Also, intensity decay working its way down to removing the effect, while we're at it.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 515f804 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

This is one of the few remaining effect fields not covered by unit tests, unsurprisingly. I also have to admit I don't recall if I tested the decay of the unseen hunter's venom.

### PR DESCRIPTION
**Pull request by Venera3**
#### Summary
Features "Effect intensity decay changes"

#### Purpose of change

Fixes #51332 and allows for effects with intensity decay to be removed completely (until now decay only worked down to intensity 1, where the effect was stuck until its duration ran out).

#### Describe the solution

- Changed effects to use the default `max_duration` of 1 year, removed the checks for the max duration being 0 turns (previously checked as a filter to see if there's a max duration at all)
- Allowed intensity decay to remove the effect completely

TODO:
- [x] Check if martial arts buffs need some adjustments - they are universally balanced around their intensity being capped at one and being limited only by duration, so I introduced a new `int_decay_remove` effect field to preserve that behavior for any effect that would need it
- [x] Try writing up a unit test

#### Describe alternatives you've considered

Simply defining a `max_duration` in the effects I want `int_decay_tick` to work and documenting it as a mandatory requirement.

#### Testing

Setting no max duration allows effects to accumulate duration up to one year. Intensity decay works as advertised, decay messages print and on the 1->0 decay step the effect gets removed and the removal message gets printed.

#### Additional context

The check for max intensity to the effect decay got added back in #31733, but the only vanilla effects that would have relied on intensity decay are  the paralytic venom (applied in too-short duration by triffids to be noticeable) and getting dusted by fungal spores (which everybody and their dog avoids like the plague) so it could fly under the radar for a while.
The only mainline mod affected is Aftershock, neither foamcrete nor the generic speedup effect decayed as desired, those should work now.

### CODE REVIEW

**Comment by Hymore246** [comment]
My biggest concern is that the decay will override the duration of martial arts buffs. It is perfectly fine from an MA stand point to let a decaying buff stay at one stack for whatever length of time. I am afraid this will reintroduce the bug I fixed in #31733 because everything instantly lost a turn the moment it was applied. Literally every buff and effect in the martial arts system needed to be +1 turn length to compensate and it was confusing. Static buffs are applied every turn if I remember right. If they are not showing up something is very wrong.

**Comment by Venera3** [comment]
I left the "only decay if duration < max duration" check in place so it shouldn't change any effect that has a defined buff duration.

**Comment by Venera3** [comment]
Okay, MA buffs ran into the intensity removal messing with their fine-tuned balance. Introduced a new bool `int_decay_remove` to protect them from being removed and updated the docs accordingly.

**Comment by Venera3** [comment]
The tests are probably a bit clumsy, but they test the permutations that seemed important and passed without weirdness. MA bonuses stack as expected, stay for the same duration and only get removed when their duration runs out.

File: tests/effect_test.cpp [hunk 1]
```diff
@@ -260,13 +279,119 @@ TEST_CASE( "effect decay", "[effect][decay]" )
...
+        CHECK( rem_bps.empty() );
+
+        // Skip the intermediate levels, set intensity to 1 manually before proceeding
+        eff_debugged.set_intensity( 1 );
+        calendar::turn += 1_turns;
+        eff_debugged.decay( rem_ids, rem_bps, calendar::turn, false );
+        CHECK( eff_debugged.get_intensity() == 0 );
+        // Effect is removed
+        CHECK( rem_ids.size() == 1 );
+        CHECK( rem_bps.size() == 1 );
```
Comment (actual-nh) [inline tests/effect_test.cpp:336]:
```suggestion
        REQUIRE( rem_ids.size() == 1 );
        REQUIRE( rem_bps.size() == 1 );
```
Since the remainder of this test doesn't work if these aren't true.

File: tests/effect_test.cpp [hunk 2]
```diff
@@ -260,13 +279,119 @@ TEST_CASE( "effect decay", "[effect][decay]" )
...
+        CHECK( rem_bps.empty() );
+
+        // Fourth decay - 0 turns left, intensity stays 1 (but wouldn't proc anyway)
+        calendar::turn += 1_turns;
+        eff_test_int_remove.decay( rem_ids, rem_bps, calendar::turn, false );
+        CHECK( to_turns<int>( eff_test_int_remove.get_duration() ) == 0 );
+        CHECK( eff_test_int_remove.get_intensity() == 1 );
+        // Effect is removed
+        CHECK( rem_ids.size() == 1 );
+        CHECK( rem_bps.size() == 1 );
```
Comment (actual-nh) [inline tests/effect_test.cpp:388]:
```suggestion
        REQUIRE( rem_ids.size() == 1 );
        REQUIRE( rem_bps.size() == 1 );
```

File: tests/effect_test.cpp [hunk 3]
```diff
@@ -260,13 +279,119 @@ TEST_CASE( "effect decay", "[effect][decay]" )
...
+        eff_debugged.set_intensity( 1 );
+        calendar::turn += 1_turns;
+        eff_debugged.decay( rem_ids, rem_bps, calendar::turn, false );
+        CHECK( eff_debugged.get_intensity() == 0 );
+        // Effect is removed
+        CHECK( rem_ids.size() == 1 );
+        CHECK( rem_bps.size() == 1 );
+        // Effect ID and body part are pushed to the arrays
+        CHECK( rem_ids.front() == eff_debugged.get_id() );
+        CHECK( rem_bps.front() == bodypart_id( "bp_null" ) );
```
Comment (actual-nh) [inline tests/effect_test.cpp:339]:
```suggestion
        REQUIRE( rem_ids.size() > 0 );
        CHECK( rem_ids.front() == eff_debugged.get_id() );
        REQUIRE( rem_bps.size() > 0 );
        CHECK( rem_bps.front() == bodypart_id( "bp_null" ) );
```

File: tests/effect_test.cpp [hunk 4]
```diff
@@ -260,13 +279,119 @@ TEST_CASE( "effect decay", "[effect][decay]" )
...
+        calendar::turn += 1_turns;
+        eff_test_int_remove.decay( rem_ids, rem_bps, calendar::turn, false );
+        CHECK( to_turns<int>( eff_test_int_remove.get_duration() ) == 0 );
+        CHECK( eff_test_int_remove.get_intensity() == 1 );
+        // Effect is removed
+        CHECK( rem_ids.size() == 1 );
+        CHECK( rem_bps.size() == 1 );
+        // Effect ID and body part are pushed to the arrays
+        CHECK( rem_ids.front() == eff_test_int_remove.get_id() );
+        CHECK( rem_bps.front() == bodypart_id( "bp_null" ) );
```
Comment (actual-nh) [inline tests/effect_test.cpp:391]:
```suggestion
        REQUIRE( rem_ids.size() > 0 );
        CHECK( rem_ids.front() == eff_test_int_remove.get_id() );
        REQUIRE( rem_bps.size() > 0 );
        CHECK( rem_bps.front() == bodypart_id( "bp_null" ) );
```

**Review by actual-nh — COMMENTED** [review]
Better (IMO) version of what I was thinking earlier - do the checks as long as it's possible.

File: doc/EFFECTS_JSON.md [hunk 5]
```diff
@@ -230,11 +230,12 @@ future applications decreasing the overall time left.
...
 Intensities are used to control effect effects, names, and descriptions. They are defined with:
-```C++
-    "int_add_val": 2        - Defaults to 0! This means future applications will not increase intensity unless changed!
-    and/or
+```JSON
+    "int_add_val": 2         - Defaults to 0! This means future applications will not increase intensity unless changed!
+
     "int_decay_step": -2,    - Defaults to -1
-    "int_decay_tick": 10
+    "int_decay_tick": 10     - Defaults to 0, preventing intensity decay
```
Comment (Maleclypse) [inline doc/EFFECTS_JSON.md:237]: is this in seconds or turns or the amount decayed by each unit of time?

Comment (Venera3) [reply doc/EFFECTS_JSON.md:237]: Seconds, there's a bit-too-longwinded explanation below that section that I didn't try to integrate into the table. I'll add some notes to make it more obvious at a skim.
