### PR TITLE
Proportional part salvaging

### LINKED ISSUE #37063: Salvage/cutting up items should be mass based, not volume based
# Problem
Currently, salvaging an object through a mechanism such as the "cut up" action results in materials based on the volume of the object, rather than the mass.

This results in needing to special-case a lot of objects with disassembly recipes in order to adjust how much you actually get out of them.

Further, the accretion of disassembly recipes adds additional complication to our crafting/disassembly cycles, since disassembly recipes override our component system, and creates future maintenance burden through the use of unclear purpose recipes.

# Preferred solution
Moving to mass-based salvaging would produce more consistent results, and reduce the need for special-cased disassembly recipes.

Ideally the no-longer-necessary disassembly recipes would be removed at the same time.

# Alternative solutions
We could continue accreting disassembly recipes, I guess?

# Additional context
An incomplete list of prior examples (Which were resolved with disassembly recipes)
#27478
#29114

### LINKED ISSUE #39093: Blankets cut up into too many resources.
# Describe the bug
Blankets, fur blankets, and down blankets cut up into a really large amount of resources they are made of, way more than you get dissembling them 

# Steps To Reproduce
1. Cut up a fur blanket and note how many resources you get
2. compare it to the lengthy disassembly process and see the difference.

# Expected behavior
Cutting to be the quick inefficient harvest method instead of the quick and bountiful method 

# Screenshots
What disassembly can potentially get you
image
What cutting up can get you.
image

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-13400-gace1923 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

### LINKED ISSUE #42375: Boiled horse barding gives too much resources when cut up
# Describe the bug

Boiled leather horse barding (with barding/bones) takes ~150 leather/rags to make, but gives ~300 when cut up. More bone skewers than could be crafted directly from the same amount of bones are also obtained, it's basically cut up bones though.

# Steps To Reproduce

1. Make boiled leather horse barding (any).
2. Place it on floor.
3. Butcher it.
4. ???
5. Profit.

# Expected behavior

Salvaged items generally seem to give about 50% of resources consumed? In any case, >100% is clearly a bug.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### LINKED ISSUE #45063: Blanket can be exploited for extra materials.
# Describe the bug
Blanket can be either disassembled or "butchered" to get it material, cutting the blanket was supposed to give me less than 35 rags, but instead it give me around 59 rags in a matter of 15 seconds. disassembling give me 35 rags in 20 minutes, sure something is wrong here.

# Steps To Reproduce
1. Have a cutting tool.
2. Spawn 2 blankets.
3. Disassembly one and cut the other.
4. Notice the difference.

# Expected behavior
Salvaging less material after cutting the blanket, something around 20 to 30.

**Edit from devs: for the purposes of fixing this bug, the resources to craft the blanket need to be increased to be equal to or greater than what you get from butchering it, or the weight/volume of the blanket need to be reduced to match the components that go into it. These are both very easy JSON fixes.  --erk**

# Screenshots
image

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.1 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7041-gdb7d137 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [    Dark Days Ahead [dda],    Disable NPC Needs [no_npc_food],    Bionic Professions [package_bionic_professions],    Stats Through Skills [StatsThroughSkills]]

### LINKED ISSUE #46211: Cutting up hiking backpacks for infinite leather patches.
# Describe the bug

The hiking backpack requires 25 leather patches to craft, and gives just as many when disassembled, but gives upwards of 55 patches when just cut up.

# Steps To Reproduce

Just cut up a hiking backpack with a cutting tool. Works even with a basic survivor with no skills using a pocket knife and a debug-spawned hiking backpack.

# Expected behavior

For a hiking backpack to only give 25 or less leather patches when cut up.

# Screenshots

https://media.discordapp.net/attachments/598523535169945607/790511761886543892/unknown.png

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-8201-gc49b2cc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: Bugfixes "Base returned materials from salvaging on mass instead of volume."

#### Purpose of change
Fixes #37063
Fixes #45063 
Fixes #42375
Fixes #39093
Fixes #46211

We have chronically encountered problems wit lack of "conservation of mass" when salvaging items.  There is a gross mismatch between volumes of items and the products used to make them, but the mass should be the same.

#### Describe the solution
Bases salvage yields on mass of salvaged item.
Fixes a latent bug that has arisen since the "salvage_into" items do not have the same volume or mass as assumed by the existing code.

#### Describe alternatives you've considered
I'm not super happy with the code I ended up with, it's pretty convoluted in an attempt to be fully general, even though items composed of many materials are vanishingly rare.

#### Testing
Added a unit test to disassemble a number of items and assert that they are disassembling into a mass of products less than or equal to the mass of the disassembled items.
Suggestions for more items to test are welcome.

#### Additional context
This also needs a quick audit of disassembly recipes that end up being redundant with salvage. Ideally we can drop a lot of explicit recipes in favor of a better tuned heuristics.

### CODE REVIEW

File: src/iuse_actor.cpp [hunk 1]
```diff
@@ -1462,39 +1490,49 @@ int salvage_actor::cut_up( player &p, item &it, item_location &cut ) const
...
+                                        weight_to_item_map.end(), 0_gram, []( const units::mass & a,
+        const std::pair<units::mass, itype_id> &b ) {
+            return a + b.first;
+        } );
+        if( components_weight > remaining_weight ) {
+            int count = remaining_weight / components_weight;
+            for( std::pair<units::mass, itype_id> mat_pair : weight_to_item_map ) {
+                materials_salvaged[mat_pair.second] += count;
+            }
+            remaining_weight -= components_weight;
```
Comment (CAHEK7) [inline src/iuse_actor.cpp:1533]: If `components_weight` > `remaining_weight` then `remaining_weight / components_weight` is always less than 1 and thus `int count` is always 0 and `remaining_weight` becomes negative after `remaining_weight -= components_weight`.
Seems `<=` condition is needed here.

Comment (CAHEK7) [reply src/iuse_actor.cpp:1533]: Apologies, didn't notice that PR is still WIP.

File: src/iuse_actor.cpp [hunk 2]
```diff
@@ -1359,11 +1359,40 @@ int salvage_actor::use( player &p, item &it, bool t, const tripoint & ) const
...
+}
 
 int salvage_actor::time_to_cut_up( const item &it ) const
 {
-    int count = it.volume() / minimal_volume_to_cut;
+    units::mass total_material_weight;
+    int num_materials = 0;
+    visit_salvage_products( it, [&total_material_weight, &num_materials]( const item & exemplar ) {
+        total_material_weight += exemplar.weight();
+        num_materials += 1.0f;
```
[the remark this answers is not in the document]
Comment (kevingranade) [reply src/iuse_actor.cpp:1389]: Whoops, I toggled this back and forth between float and int a few times.

File: src/iuse_actor.cpp (hunk 1 above)
Comment (kevingranade) [reply src/iuse_actor.cpp:1533]: No problem, you're right and that saved me some time.

File: tests/iuse_actor_test.cpp [hunk 3]
```diff
@@ -99,3 +99,71 @@ TEST_CASE( "tool transform when activated", "[iuse][tool][transform]" )
...
+    here.i_at( guy.pos() ).clear();
+
+    CAPTURE( target );
+    salvage_actor test_actor;
+    item cut_up_target{ target };
+    item tool{ "knife_butcher" };
+    const std::vector<material_id> &target_materials = cut_up_target.made_of();
+    units::mass smallest_yield_mass = units::mass_max;
+    for( const material_id &mater : target_materials ) {
+        if( const cata::optional<itype_id> item_id = mater.obj().salvaged_into() ) {
```
Comment (anothersimulacrum) [inline tests/iuse_actor_test.cpp:120]:
```suggestion
        if( const cata::optional<itype_id> item_id = mater->salvaged_into() ) {
```

File: src/iuse_actor.cpp [hunk 4]
```diff
@@ -1462,39 +1490,49 @@ int salvage_actor::cut_up( player &p, item &it, item_location &cut ) const
...
     }
 
-    // Decided to split components evenly. Since salvage will likely change
-    // soon after I write this, I'll go with the one that is cleaner.
+    // Essentially we round-robbin through the components subtracting mass as we go.
+    std::map<units::mass, itype_id> weight_to_item_map;
     for( const material_id &material : cut_material_components ) {
-        if( const auto id = material->salvaged_into() ) {
-            materials_salvaged[*id] = std::max( 0, count / static_cast<int>( cut_material_components.size() ) );
+        if( const cata::optional<itype_id> id = material.obj().salvaged_into() ) {
```
Comment (anothersimulacrum) [inline src/iuse_actor.cpp:1517]:
```suggestion
        if( const cata::optional<itype_id> id = material->salvaged_into() ) {
```

**Comment by ZhilkinSerg** [comment]
Maybe we should run this kind of test for items of all item types?

**Comment by actual-nh** [comment]
#46211 should be added to the list of issues this could close...

File: tests/iuse_actor_test.cpp [hunk 5]
```diff
@@ -99,3 +99,80 @@ TEST_CASE( "tool transform when activated", "[iuse][tool][transform]" )
...
+    for( const item &salvage : salvaged_items ) {
+        salvaged_mass += salvage.weight();
+    }
+    CHECK( salvaged_mass <= cut_up_target_mass );
+    CHECK( salvaged_mass >= ( cut_up_target_mass * 0.99 ) - smallest_yield_mass );
+}
+
+TEST_CASE( "cut_up_yields" )
+{
+    cut_up_yields( "blanket" );
```
Comment (actual-nh) [inline tests/iuse_actor_test.cpp:145]:
```suggestion
    cut_up_yields( "blanket" );
    cut_up_yields("backpack_hiking");
```

**Comment by int-ua** [comment]
How will disassembly recipe definition change for cases where disassembly is not trivial and needs tools and time defined?

**Comment by leemuar** [comment]
Im sorry for bringing bad new, but it seems it introduced another "bug". Other items now give much more materials than probably intended. 

f.i. Kevlar vest used to give ~5 layered kevlar plates, now it gives 30+
Kevlar dog harness now gives ~60 layered kevlar plates, used to give 6

That's probably way too much

Steps to reproduce:

on latest stable Elisson version:
- spawn a knife
- spawn Kevlar vest
- cut the vest
- notice the amount of materials
- do same steps on latest daily build and notice the amount of salvaged materials increased significantly

**Comment by ZhilkinSerg** [comment]
It does not matter how much materials you've got in 0.E - that baseline was not correct.

Kevlar vest weighs 2.86 kg, layered Kevlar panel weighs 80 grams, so cutting up Kevlar vest should yield no more than 35 layered Kevlar panels. If weight of vest and panels are correct - everything works fine.

**Comment by leemuar** [comment]
I do understand the idea of "conservation of mass" behind it. Im just not sure if the increased yield is correct from game balance/sanity perspective (because Im still new to the game).

So you want to say it is OK to have that many materials now? I just need a calming confirmation from a more experienced people than I am that this is OK, this is a new norm.

> 
> 
> It does not matter how much materials you've got in 0.E - that baseline was not correct.
> 
> Kevlar vest weighs 2.86 kg, layered Kevlar panel weighs 80 grams, so cutting up Kevlar vest should yield no more than 35 layered Kevlar panels. If weight of vest and panels are correct - everything works fine.

**Comment by ZhilkinSerg** [comment]
The balance formula is in the description of current PR - salvage yields are based on mass of salvaged item. Also items should have similar weight and dimensions as their real world counterparts.

**Comment by actual-nh** [comment]
> The balance formula is in the description of current PR - salvage yields are based on mass of salvaged item. Also items should have similar weight and dimensions as their real world counterparts.

One question is whether some items actually are made of more than one thing but currently only have the material providing most of the functionality (e.g., kevlar in a K-9 vest) listed. That's not a reason to not make things salvageable, though - just to make sure the composition is realistic.

**Comment by leemuar** [comment]
What also was bothering me duting testing is that dog's harness yields almost twice as much kevlar plates (50+) than Kevlar vest (30+)
