### PR TITLE
Fix calling map::move_vehicle with a combined horizontal and vertical movement

### LINKED ISSUE #32490: DEBUG: move_vehicle called with 1,-1,-1 displacement vector
# Describe the bug

For some reason the error message in the debug log is different: `couldn't parse color: c_tan`
```
	cataclysm(_Z21debug_write_backtraceRSo+0x3a) [0x55cd6b51adfa]
	cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x260) [0x55cd6b51c770]
	cataclysm(_ZNK13color_manager10name_to_idERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x67) [0x55cd6b475ff7]
	cataclysm(_Z17color_from_stringRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2fa) [0x55cd6b47b6ea]
	cataclysm(_Z17load_season_arrayISt5arrayI8nc_colorLm4EEPFS1_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvR10JsonObjectSA_RT_T0_+0x4c) [0x55cd6b98ce8c]
	cataclysm(_ZN17map_data_common_t11load_symbolER10JsonObject+0x296) [0x55cd6b981c46]
	cataclysm(_ZN5ter_t4loadER10JsonObjectRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x20f) [0x55cd6b983c7f]
	cataclysm(_Z12load_terrainR10JsonObjectRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x2ae) [0x55cd6b98a8ce]
	cataclysm(_ZN17DynamicDataLoader11load_objectER10JsonObjectRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES9_S9_+0x17d) [0x55cd6b6fcb1d]
	cataclysm(_ZN17DynamicDataLoader18load_all_from_jsonER6JsonInRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEER10loading_uiS9_S9_+0x10f) [0x55cd6b6fecdf]
	cataclysm(_ZN17DynamicDataLoader19load_data_from_pathERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_R10loading_ui+0x358) [0x55cd6b6ff0e8]
	cataclysm(_ZN4game10load_packsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKSt6vectorI9string_idI15MOD_INFORMATIONESaISB_EER10loading_ui+0x22c) [0x55cd6b62ad4c]
	cataclysm(_ZN4game19load_world_modfilesER10loading_ui+0x45b) [0x55cd6b62cb1b]
	cataclysm(_ZN4game5setupEv+0xac) [0x55cd6b6549cc]
	cataclysm(_ZN9main_menu18load_character_tabEv+0x1bec) [0x55cd6b9063cc]
	cataclysm(_ZN9main_menu14opening_screenEv+0x108a) [0x55cd6b907a9a]
	cataclysm(main+0x10d2) [0x55cd6b2974c2]
```

# Steps To Reproduce

Load the game and waste time smashing the surrounding corpses.

# Versions and configuration

0.D-5714-gb6441480df-dirty

# Additional context

[2019.06.05-2.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3409638/2019.06.05-2.zip)

### PR DESCRIPTION
**Pull request by BevapDin**
```SUMMARY: None```

Fixes #32490

The function checks for the displacement vector indicating a vertical only or a horizontal only movement. If it indicates both at once (e.g. (1, 0, 1)), it would show the message (and not do anything).

Some other place called the function and did split the movement into two calls, so I moved that splitting into the function itself.

Also added vertical velocity to the vehicle as the function complained about that as well.

### CODE REVIEW

File: src/monmove.cpp [hunk 1]
```diff
@@ -1876,6 +1876,9 @@ void monster::shove_vehicle( const tripoint &remote_destination,
                 veh.skidding = true;
                 veh.velocity = shove_velocity;
                 if( shove_destination != tripoint_zero ) {
+                    if( shove_destination.z != 0 ) {
+                        veh.vertical_velocity = shove_destination.z < 0 ? -shove_velocity : +shove_velocity;
+                    }
                     g->m.move_vehicle( veh, shove_destination, veh.face );
                 }
                 veh.move = tileray( destination_delta_x, destination_delta_y );
```
Comment (Qrox) [inline src/monmove.cpp]: Should this use the new vehicle pointer returned by `move_vehicle`?

Comment (BevapDin) [reply src/monmove.cpp]: it doesn't really matter. `move_vehicle` either returns null or the input vehicle. It never creates a new one. Those movement functions need a rework anyway (returning bool instead of pointers, `displace_vehicle` taking a vehicle reference instead of a point and so on).
