### PR TITLE
Fixes power grid teleportation, crashes, and other buggy interactions

### LINKED ISSUE #66553: Non-directly connected freezer disappeared after a cable break
### Describe the bug

When I went on a scooter from my base, without removing a cable from the scooter, the freezer disappeared. There are no errors in Debug.log.

In the center of the base furniture. East is located most of the electrical appliances. But the freezer south. Further east is several electric vehicles with solar panels. All this is connected by cables. There is an electric scooter that I usually connect with a cable to the oven. And usually I do not remove the cable, but I just leave on the scooter. But this time a bug appeared.

### Attach save file

[Гвинед-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11918578/-trimmed.tar.gz)
Attached through the picture button. GitHub has a terrible interface.
Config does not matter.

### Steps to reproduce

0. Load.
1. "Control vehicle".
2. "Move north" at least 2 times.
3. "Pause" twice.

### Expected behavior

The freezer should not disappear.

### Screenshots

SQt4b

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: #######; Model: #######; Release: 13; Incremental: #########; 
- Game Version: 4250d57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### LINKED ISSUE #67971: Corrupted appliance take down results in crash
### Describe the bug

Somehow my appliances got corrupted. I can't take down 3 solar panels and battery (option to do that is grayed out). When I instead try to place new solar panel, my current appliances teleport few tiles to the left and taking any of them down results in crash.

Cross issue (maybe related due to save corruption): I have two large squares of eternal darkness near base. 

### Attach save file

[Circle Pines-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/12491903/Circle.Pines-trimmed.tar.gz)

### Steps to reproduce

Not sure how to reproduce without save file. But with save loaded:
1. Try to take down appliance, solar panel or battery.
2. Not possible, option grayed out,
3. Place new solar panel (`*`/`alt+8` -> `Place Solar Panel`),
4. Previous appliances teleport few tiles to the left,
5. Try to take down *teleported* appliance,
6. Game crashes.

I've been able to make it work without crash and "decorrupt" appliances doing:
1. Place new solar panel (`*`/`alt+8` -> `Place Solar Panel`),
2. Previous appliances teleport few tiles to the left,
3. Take down this new solar panel,
4. Place new solar panel (`*`/`alt+8` -> `Place Solar Panel`) again,
5. Now I've been able to take down everything without crash.

But I am not sure if my save isn't still corrupted in less apparent way.

### Expected behavior

I would expect I'll be able to take down my appliances without crash.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.2 LTS; Release: 22.04; Codename: jammy; 
- Game Version: 2e4ad5f [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/12491940/debug.log)
[Circle Pines.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/12491945/Circle.Pines.zip)

`crash.log` does not exist.

### LINKED ISSUE #69271: Taking down any battery breaks extension cord connections
### Describe the bug

When I "take down appliance" on any battery in my bank, extension cords stop delivering power. Removing and reconnecting the cords seems to fix the problem.

I've tested a handful of different batteries, and it doesn't seem to matter which one you take down, the result is the same either way.

### Attach save file

[Mindssachusetts-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13325849/Mindssachusetts-trimmed.tar.gz)

### Steps to reproduce

- Load up the save file
- Check that the workshop appliances are receiving power
- Take down a random battery
- Check that the workshop appliances are no longer receiving power

### Expected behavior

Removing something from one part of the electrical grid should not break connections to unrelated parts of the grid.

### Screenshots

image
The batteries and solar panels are directly connected to each other.

image
image
An outdoor extension cord runs from this point on the solar panels, to this workshop station, and then a regular extension cord runs from that to this freezer:
image
image
Everything in the workshop area receives power just fine

image
But if I take down (seemingly) any battery, such as this one, which doesn't have any connections to anything other than the batteries next to it...
image
Everything in the workshop loses power.
image
The actual power production is fine, it only seems to be the stuff on the other side of the extension cord that breaks. 

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3570 (22H2)
- Game Version: 8e12218 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Mind Over Matter [mindovermatter],
    Bionic Slots [cbm_slots],
    Stats Through Kills [stats_through_kills],
    Massachusetts [MA]
]

### Additional context

_No response_

### LINKED ISSUE #70263: Segmentation fault on taking down grid component
### Describe the bug

I have encountered a situation where the game crashes upon removing a car battery from a stationary grid with a segmentation fault. I have no idea how to replicate it elsewhere, but it does occur consistently on this save

### Attach save file

[Roachtown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13694823/Roachtown-trimmed.tar.gz)

### Steps to reproduce

1. Load the attached save
2. Examine the placed car battery directly west of the character
3. Take it down

Game should crash

### Expected behavior

The car battery is taken down and left as an item on the ground without crashing the game

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: 636f820 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13694860/crash.log)

Additional note: the save is from a month old experimental, but I loaded it into latest and after a json error from loading, the crash still occurs upon taking the battery down

### LINKED ISSUE #70287: Segfault and strange, gamebreaking behavior from messing with outdated solar panels(?)
### Describe the bug

I must have installed these solar panels atop on an old version, likely from July 2023. I don't update often. I have since tried to install some new ones, reposition some old ones, etc.
The game segmentation faults when attempting to uninstall a solar panel that, when examined, is labeled "power grid". Sometimes it lets me, sometimes it doesn't, but it's pretty consistent. Nothing interesting happens, just instantly throws an error and crashes.
Messing with the solar panels further, I found that sometimes the tiles get... moved in strange ways, pictured below.

### Attach save file

[Centertown - Pruned-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13707592/Centertown.-.Pruned-trimmed.tar.gz)

### Steps to reproduce

Segmentation Fault:
1. Load into save
2. Disconnect power connections from any solar panel which, when examined, is labeled "power grid" instead of "solar panel". There should be one immediately to the west when you load in.
3. Usually, messing with the power connections or uninstalling unrelated solar panels fixes the segfault.

Strange behavior:
1. If you do manage to uninstall the solar panel to the west, reinstall it. It moves the tiles around as pictured below.

### Expected behavior

I expect that installing or uninstalling solar panels wouldn't segfault or move tiles around strangely.

### Screenshots

These are screenshots of the "strange tile behavior"
before
Reinstalling the solar panel... moves the tiles.
after
The segfault is not very interesting, visually.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3693 (22H2)
- Game Version: b37cb38 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Skills [StatsThroughSkills]
]
Worth noting is that a lot of these solar panels were **installed on a much earlier version. Some as early as 2023-07-20-0251 ( 520db0c).**
I believe I installed StatsThroughSkills after world creation.

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13707541/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13707542/debug.log)

### LINKED ISSUE #70343: Taking down solar panel appliance removes different solar panel
### Describe the bug

Taking down the solar panel marked 1 in screenshot, left of player, results in solar paneld marked 2 being taken down instead.

### Attach save file

[Himassa-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13745446/Himassa-trimmed.tar.gz)

### Steps to reproduce

1. Examine panel on left
2. Select take down appliance
3. Observe that different panel disappears

### Expected behavior

Expectation is for the selected panel to be taken down

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.2861 (22H2)
- Game Version: c5cf8ed [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills [stats_through_kills]
]

### Additional context

_No response_

### LINKED ISSUE #70726: Cannot interact with batteries in Power Grid
### Describe the bug

Large Storage Batteries connected to the Solar Panels in the Solar Farm cannot be disconnected or taken down.

### Attach save file

[Frankfort-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13851451/Frankfort-trimmed.tar.gz)

### Steps to reproduce

I connected placed two Large Storage Batteries adjacent to the Solar Panels in the Solar Farm location. I then "turned on" each of the Solar Panels. This created a working Power Grid. I then placed an Autoclave next to a Battery, used the Autoclave, and then Disconnected it from the Grid, and took it down. I then attempted to remove the Batteries, however it only lets me interact with the Grid, and I cannot take them down, or deconstruct them.

### Expected behavior

I expected to be able to disconnect and take down the batteries.

### Screenshots

image
image

### Versions and configuration

Windows 10
Cataclysm DDA version 13b09b1 - cdda-windows-tiles-sounds-x64-2024-01-01-0221
"dda", "no_npc_food", "personal_portal_storms", "no_fungal_growth", "blazeindustries", "mindovermatter", "bombastic_perks", "MMA", "sees_player_retro", "translate_dialogue", "speedydex", "stats_through_kills", "StatsThroughSkills", "Tamable_Wildlife", "no_zombie_revive"

### Additional context

_No response_

### LINKED ISSUE #71692: Segfault when attempting to take down large grid battery
### Describe the bug

Upon attempting to take down a large grid battery, my game crashes and gives me a segmentation fault.

### Attach save file

[Stilwell-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14233428/Stilwell-trimmed.tar.gz)

### Steps to reproduce

1. Remove a heavy storage battery from an electric car (such as an electric SUV).
2. Place it down and connect it to a power grid (solar panels, for example).
3. Attempt to take down the large grid battery.
4. Segfault.

### Expected behavior

I expected removing a power grid to not cause a segfault, because most other actions don't.

### Screenshots

_No response_

### Versions and configuration

OS: EndeavourOS Build 2023.08.05
Game Version: CDDA Experimental 2024-02-11-0749
Graphics Version: Tiles
In-Game Language: English
Mods Loaded: Dark Days Ahead, Disable NPC Needs, Portal Storms Ignore NPCs, Slowdown Fungal Growth

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/14233426/crash.log)

### LINKED ISSUE #71733: Teleporting Power Grid
### Describe the bug

When adding/removing batteries to a power grid, the grid can be erroneously split and will teleport.

### Attach save file

[Magasco-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14256609/Magasco-trimmed.tar.gz)

### Steps to reproduce

1. Place 5 storage batteries in a line from left to right, as in the screenshot.
2. Remove the leftmost battery (using the "take down appliance" action).
3. Replace the leftmost battery (using the construction menu).
4. Remove the leftmost battery again.
5. Remove the battery circled in the screenshot. The entire grid will teleport one tile. This example is trivial, but as shown in one of the other buildings in the save, the results can teleport the power grid into the walls.

### Expected behavior

I expected the batteries to not teleport.

(this section of the bug report form is a little redundant sometimes)

### Screenshots

tpbug

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3996 (22H2)
- Game Version: 7140bea [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

Unsure what the cause is here, but it happened fairly regularly with my house in a longer game.

### PR DESCRIPTION
**Pull request by Kamayana**
#### Summary
Bugfixes "Fixes power grid teleportation, crashes, and other buggy interactions"

#### Purpose of change
1. Fixes #71692 
2. Fixes #70287 
3. Fixes #70263
4. Fixes #67971 
5. Fixes #71733 
6. Fixes #66553
7. Fixes #69271
8. Fixes #70343
9. Fixes #70726 
12. Vehicle parts with cable connections can't be removed until cables are disconnected in a separate menu.
13. Cable vehicle parts would stay at a mount point when the part with a valid connection is removed (jumper cables staying around after the battery is removed, for instance).
14. The maximum power grid size was not actually being enforced, letting grids be any size.

#### Describe the solution
1 to 4: The segfaults were caused by the vehicle part reference becoming invalid after splitting the power grid into two vehicles, leading to the game crashing by trying to remove part #GARBAGE DATA. Splitting also threw off the interaction point, leading to removing incorrect parts. Both problems were fixed by making appliance removal use absolute coordinates rather than vehicle-relative ones. This works for saves made both before and during 0.G.

4 to 6: The power grid's teleportation issues are caused by the power grid's `pivot_anchor` getting out of sync with its position value, which particularly comes up when loading older saves. When modifying the power grid, like by adding a solar panel, the position is erroneously "corrected". By applying `shift_if_needed`, subtracting the pivot from the position, and updating precalcs, the values will be corrected for any power grid.

7: All extension cords falling off when any part is changed is because it's calling `shed_loose_parts`, disconnecting all cables everywhere. It's now more specialized and only removes cables from the removed part.

8: Appliance interactions were relying on `part_at`, which uses precalc to find parts instead of the mount point, making it return -1 which meant it removed the first part of the grid rather than the interacted one. Appliance interaction now uses `veh_at`, which is more reliable and commonly used. `part_at` is still there as a backup (probably unnecessary, honestly).

9: `can_unmount` would always return false if removing a part would split a vehicle, which makes sense for vehicles but is necessary for power grids, and was even already accounted for in `complete_vehicle (remove part)`, so simply adding a parameter to allow splits fixed this.

10: Cables are ignored in `can_unmount` now, except for exiting the function early, as that should only be done for lone structural parts.

11: Added the `vehicle::unlink_cables()` function to consolidate code, and make it remove cable parts when a cable port or battery is removed from that mount point. This will erroneously disconnect both power cords and jumper cables if both a battery and dashboard are on the same tile, but that's a very fringe issue.

12: Bounding boxes were using precalc, but the precalc for power grids is weird because they aren't supposed to move, so it was returning the fallback bounding box that wouldn't enforce anything. Changed that, but that revealed that the calculation for when a grid is too big also needed fixing. If a grid was at the maximum width/height it would fail ALL merging, even when it should've been allowed. It now combines both grid's bounding boxes to get the minimum & maximum and calculating the width/height from that. It now only denies merging parts outside the maximum.

#### Describe alternatives you've considered
I originally included usability improvements inside this PR, but I think it made the PR too large and unfocused, so I trimmed it down to just the bugfixes. I'll make a separate PR for the rest of it.

#### Testing
Tested all the listed issues, all of them are fixed. Did a lot of various appliance placement and removal to ensure they worked properly. Connected/disconnected cables to vehicles to ensure nothing was broken there either.

#69938 is not fixed, as smashing wall wirings can still make the battery disappear for me. This is not the easiest bug to track down, unfortunately, but I believe I've fixed caches screwing up when merging/unmerging power grid parts, so it might be smashing specifically that's bugged.

#### Additional context
Testing ground savefile I used:
[MovApp AAA TESTING GROUND.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/14637128/MovApp.AAA.TESTING.GROUND.zip)

### CODE REVIEW

File: src/vehicle_use.cpp [hunk 1]
```diff
@@ -2068,52 +2068,23 @@ void vehicle::build_interact_menu( veh_menu &menu, const tripoint &p, bool with_
         }
     }
 
-    if( power_linked ) {
-        menu.add( _( "Disconnect power connections" ) )
+    if( power_grid ) {
+        menu.add( _( "Disconnect from power grid" ) )
```
Comment (Fris0uman) [inline src/vehicle_use.cpp:2072]: this will not show up when examining a car with a jumper cable?

Comment (Kamayana) [reply src/vehicle_use.cpp:2072]: It would, so I just added a conditional to keep the old menu text for vehicles.
