### PR TITLE
[RDY] Added morale editor to debug menu

### LINKED ISSUE #22879: No option to change morale via debug menu
Game version: ed53328 (git master)

Operating system: Ubuntu 16.04.3

Tiles or curses: Tiles

Mods active: None

### Expected behavior

1. Have low morale, but need to test something requiring higher morale (e.g. construction)
2. Open Debug menu
3. Select option to set morale or Select option to edit NPC, choose self, select option to set morale
4. Set morale

### Actual behavior

1. Have low morale, but need to test something requiring higher morale (e.g. construction)
2. Open Debug menu
3. Spawn mp3 player
4. Activate mp3 player and wait a few minutes for morale to improve

### Steps to reproduce the behavior

N/A

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
Closes #22879

# What was changed:

- added persistent debug morale;
- added morale editor to debug menu, which uses debug morale;
- display total morale level for NPC in debug menu (player morale detail are already visible in morale menu accessed by `v` key).

# Screenshots:

image

image

image

### CODE REVIEW

File: src/morale_types.cpp [hunk 1]
```diff
@@ -73,6 +73,8 @@ const morale_type &morale_type_data::convert_legacy( int lmt )
 
             morale_type( "morale_perm_filthy" ),
 
+            morale_type( "morale_perm_debug" ),
```
Comment (BevapDin) [inline src/morale_types.cpp]: Adding this here is quite pointless, there can't be any old savegame that uses this morale type.

File: src/debug_menu.cpp [hunk 2]
```diff
@@ -126,14 +127,15 @@ void npc_edit_menu()
         for( const auto &need : np->needs ) {
             data << need << std::endl;
         }
+        data << string_format( _( "Total morale: %d" ), int( np->get_morale_level() ) ) << std::endl;
```
Comment (BevapDin) [inline src/debug_menu.cpp]: `player::get_morale_level` already returns an `int`, why the cast?

Comment (ZhilkinSerg) [reply src/debug_menu.cpp]: Thanks. That was copy-paste error.

**Comment by codemime** [comment]
Appears to be working, but doesn't feel quite convenient in use. I would expect the option to clear any other morale (upon applying) and prevent it from reappearing until I reset the "debug morale" back to zero.

**Comment by ZhilkinSerg** [comment]
> Appears to be working, but doesn't feel quite convenient in use. I would expect the option to clear any other morale (upon applying) and prevent it from reappearing until I reset the "debug morale" back to zero.

I thought about this too, but it looked less convenient to me.
