### PR TITLE
Fix (my) recent stair bugs

### LINKED ISSUE #13602: Error and displacement when traversing z-level.
Utilizing any stairs gives the error game::vertical_notes invalid arguments: z_before == 0, z_after == 0 and may displace me to a random tile nearby. Bug present in v3703

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26811093-error-and-displacement-when-traversing-z-level?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #13623: Being placed on wrong tile/teleported when using stairs
OS: Windows 7 64

Version: Tiles 0.C-3706 d9562a2 (Latest Experimental)

I THINK this bug didn't occur on 3702, but I'm not sure when it started.

Reproduce:

1. Use any downstair in Evac shelter (*except for the bottom-right corner)
2.  Use upstair

*If you use the bottom-right downstair and then immediately go up, it works fine. Using any other downstair and going up will cause the bug to occur.

You can use some combination of moving left and right after going down before going back up to teleport to odd locations, including into solid rock. Seems like a game-breaking bug.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26850299-being-placed-on-wrong-tile-teleported-when-using-stairs?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #13602 
EDIT: Closes #13623
- `vertical_notes` shouldn't be called with identical `z_before` and `z_after`, but is. Nothing critical, so don't pester players with debugmsgs.
- Bad order of `update_map` could cause player's post-stair location to shift and become misaligned with stairs.
- Wrong order of `rope_ladder` and manhole cover checks could make them not work.

Also refactored the code a small bit. Yanked out the whole "Do you want to web-dive?", "Lava below. Descend?" query block into a function.
Removed the bullwhip section because it erroneously suggested that it isn't exactly the same as jumping down.

And minor debug bonus: short teleport (debug menu->2) can now be used to change z-levels.

### CODE REVIEW

**Comment by kevingranade** [comment]
I'm not seeing the error message from #13602, but I'm still getting the failure to find connecting stairs on a regular basis, along with a "there is a sheer drop" message.

File: src/game.cpp [hunk 1]
```diff
@@ -13265,23 +13173,134 @@ void game::vertical_move(int movez, bool force)
...
+            best = rl_dist( u.pos(), dest );
+        }
+    }
+
+    if( stairs != tripoint_min ) {
+        // Stairs found
+        return stairs;
+    }
+
+    // No stairs found! Try to make some
```
Comment (kevingranade) [inline src/game.cpp]: Seems like a TODO?

**Comment by Coolthulhu** [comment]
OK, I think I got it now.
I forgot that 3D mode differed quite significantly in one aspect (current z-level) and assumed that current z-level is the pre-shift level (in 2D mode it is, in 3D mode it wasn't).

In 3D mode, the map shift (`map::abs_sub`) is only changed at the very end now. This is good news, as it means that a great deal of 2D code has been replaced with 3D code.

**Comment by BevapDin** [comment]
There is one tiny (probably preexisting) bug when the z-levels option is false: starting shelter, the starting NPC is in the top left submap. The PC goes down the stairs, stays on the right stair (not the left, this seems to be important), goes up and the NPC isn't there anymore. I need to walk across a submap to trigger loading of the NPC (which is where it should be).

I think it's because `game::vertical_shift` calls `load_npcs` (if z-levels are disabled) and `load_npcs` uses the players position (via `overmapbuffer::get_npcs_near_player`), but the player is (at that time) *still* on the other z-level, so it looks up NPCs on that other z-level.

Does not affect nearby monsters. It's fine with z-levels enabled. Otherwise movement across z-levels works fine.

**Comment by Coolthulhu** [comment]
Marking as priority because the bug is quite crippling in some cases.

**Comment by BevapDin** [comment]
Preexisting bug: Moving up or down can easily place the character on the same square as an existing monster there. (with and without z-levels) There appears to be no check for this case.

**Comment by DanmakuDan** [comment]
It looks like the stair bug where the post-stair location is in the wrong map can still happen during game::find_or_make_stairs, the search radius is set to SEEX * 2 (48x48 total size?), which means some locations can pick a valid stairway in a basement to the north/northwest/west of the current map tile before the center map tile's stairway is picked. The original code appears to use a search area that is aligned to the current square (24x24).

**Comment by narc0tiq** [comment]
```
[narc@odin ~/src/Cataclysm-DDA]% git grep 'define SEEX'                                                  
src/game_constants.h:#define SEEX 12 // least, without scrolling).  All map segments will need to be
```
