### PR TITLE
Better in city check

### LINKED ISSUE #74177: `map_in_city` says you're not in a city when you very clearly are
### Describe the bug

When working on #74175, I noticed that `map_in_city` would repeatedly return false even when I was clearly inside the city limits.

### Attach save file

[Darfur-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15492179/Darfur-trimmed.tar.gz)

### Steps to reproduce

1) Place the following JSON somewhere where it loads:
`  {
    "type": "effect_on_condition",
    "id": "EOC_CONDITION_CHECK_HOMULLUS_IN_CIVILIZATION_ON_OMT_ENTER",
    "eoc_type": "EVENT",
    "required_event": "avatar_enters_omt",
    "condition": { "u_has_trait": "HOMULLUS" },
    "effect": [
      {
        "run_eocs": [
          {
            "id": "EOC_CONDITION_CHECK_HOMULLUS_IN_CIVILIZATION_ON_OMT_ENTER_2",
            "condition": {
              "or": [
                { "test_eoc": "EOC_CONDITION_HOMULLUS_NEAR_FACTION" },
                { "map_in_city": { "mutator": "loc_relative_u", "target": "(0,0,0)" } }
              ]
            },
            "effect": [ { "math": [ "u_homullus_is_in_civilization", "=", "1" ] }, { "u_message": "You are in a civilized OMT." } ],
            "false_effect": [ { "math": [ "u_homullus_is_in_civilization", "=", "0" ] }, { "u_message": "You are NOT in a civilized OMT." } ]
          }
        ]
      }
    ]
  }`

2) Load game. 

3) Run west. Check when you start receiving the "You are NOT in a civilized OMT" and compare it to the city area on the map.

### Expected behavior

`map_in_city` matches the city limits that are visible on your map.

### Screenshots

 `map_in_city` returned false for this location:

image

Once I moved north to here, it returned true:

image

Similarly, over here on the edge of town returns true:

image

But this spot returns false:

image

it's not until two OMTs to the east of that picture that it begins returning true.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4291 (22H2)
- Game Version: cdda-experimental-2024-05-28-2212 bf808f6 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Xedra Evolved [xedra_evolved]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change
Fixes #74177
Might be used for #71822 and the first commit is code from it mainly courtesy of anothersimulacrum

#### Describe the solution
Current checks for whether stuff is in a city or not use the difference between the test points distance from the nearest city's centre and the nearest city's size. Given that our cities are thankfully more organic than perfect circles that isn't particularly accurate.
Now every city road and building that gets placed is added to a set of `point_om_omt`s per overmap that can be checked against to determine if you're in a city. Once all cities are placed in an overmap the result is floodfilled so random fields in the middle of cities still count as being in the city limits.
Currently only affects EOCs `map_in_city` and overmap_specials city_distance
Falls back on calculating distance based on city size but cuts off at 0 as < 0 isn't a useful result

#### Describe alternatives you've considered
Keeping track of tripoints instead of just points but that seems excessive
Adding 1 tile padding to the edges of city_tiles after it's flood filled
Adding more initial usages but this has been sitting drafted for ages

#### Testing
For basic city_tiles testing or map_in_city testing plop this anywhere in the JSON and walk around, also tested post save/load to check that works
```json
  {
    "type": "effect_on_condition",
    "id": "EOC_TEST_IS_IN_CITY",
    "eoc_type": "EVENT",
    "required_event": "avatar_enters_omt",
    "condition": { "map_in_city": { "mutator": "u_loc_relative", "target": "(0,0,0)" } },
    "effect": [ { "u_message": "You are in a city OMT.", "type": "good" } ],
    "false_effect": [ { "u_message": "You are NOT in a city OMT.", "type": "bad" } ]
  },
```

For city_distance performance testing add this to a test cpp and run it with and without the changes, comparing the times
```c++
TEST_CASE( "overmap_generation_time", "[overmap]" )
{
    overmap_buffer.clear();
    const point_abs_om origin;
    for( const point_abs_om &overmap_point : closest_points_first( origin, 5 ) ) {
        overmap &om = overmap_buffer.get( overmap_point );
    }
}
```

### CODE REVIEW

File: src/condition.cpp [hunk 1]
```diff
@@ -1741,10 +1741,18 @@ conditional_t::func f_map_in_city( const JsonObject &jo, std::string_view member
...
-        c.distance = rl_dist( c.abs_sm_pos, project_to<coords::sm>( target_pos ) );
-        return c && c.get_distance_from_bounds() <= 0;
+        tripoint_abs_omt target_pos = project_to<coords::omt>( tripoint_abs_ms( tripoint::from_string(
+                                          target.evaluate( d ) ) ) );
+
+        // TODO: Remove this in favour of a seperate condition for location z-level that can be used in conjunction with this map_in_city as needed
+        point_abs_om overmap_pos;
+        tripoint_om_omt potential_city_tile;
+        std::tie( overmap_pos, potential_city_tile ) = project_remain<coords::om>( target_pos );
+        if( potential_city_tile.z() < -1 ) {
```
Comment (ehughsbaird) [inline src/condition.cpp:1751]: I don't think any projection will change the z position
```suggestion
        if( target_pos.z() < -1 ) {
```

**Review by ehughsbaird — APPROVED** [review]

File: src/condition.cpp (hunk 1 above)
Comment (Procyonae) [reply src/condition.cpp]: Oops yes that's much less ugly ;D
