### PR TITLE
Fix the activation of traps and falling upon being flung

### LINKED ISSUE #23537: If player is pushed/thrown off a ledge, player doesn't fall
Game version: a98c6b1827773cd0d5a122924da9dae551ca54cb

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: Dark Days Ahead, Filthy Clothing, Disable NPC Needs, Simplified Nutrition

### Expected behavior
If a throwing monster (e.g. zombie brute) throws you far and you end up in mid-air, you fall.

### Actual behavior
If a throwing monster throws you far and you end up in mid-air, you do not fall until you move. You just float and can wait forever on the spot.

### Steps to reproduce the behavior
* Step on a higher level of a building (e.g. mansion)
* Go close to the ledge
* Spawn a zombie brute
* Let it attack and throw you far
* Wait a few turns

### PR DESCRIPTION
**Pull request by ssorpg**
#### Summary
```SUMMARY: Bugfixes "Fixes creatures not setting off traps or falling z-levels after being flung."```

#### Purpose of change
Fixes #23537

#### Describe the solution
Added creature_on_trap() to fling_creature() in game.cpp to check if the creature ends up standing on any traps at the end of their trajectory after being flung. Also made sure that creatures that are flung off buildings but do not hit a wall simply fall z-levels and don't hit "empty space".

This solution has the side effect of fixing any bug where a creature is flung onto a trap but does not trigger it.

#### Describe alternatives you've considered
Changed the scope of ```bool thru``` since I need to access it with the new statements. Considered adding a new bool but found that I needed to add it to all the same places anyway.

After testing this fix under various conditions, I don't believe I introduced any additional bugs - but please let me know if you manage to find any bugs with this fix, thanks guys!

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -12316,15 +12316,23 @@ void game::fling_creature(Creature *c, const int &dir, float flvel, bool control
...
+            if( controlled ) {
+                force = std::max( force / 2 - 5, 0 );
+            }
+            if( force > 0 ) {
+                int dmg = c->impact( force, c->pos() );
+                // TODO: Make landing damage the floor
+                m.bash( c->pos(), dmg / 4, false, false, false );
+            }
+            // Always apply traps to creature i.e. bear traps, tele traps etc.
+            m.creature_on_trap( *c, false );
```
Comment (alanbrady) [inline src/game.cpp]: This is going to cause creature_on_trap to fire twice if `thru == true && trap_under_creature == tr_ledge` no?

Comment (alanbrady) [reply src/game.cpp]: Oh nevermind, I see now.  If it's a tr_ledge, ledge() will move them, then when the second creature_on_trap fires, it's checking if there's a trap on their new position.

But this begs another question, what happens if they are falling multiple z-levels?  I.e. what happens if the creature is falling 2 stories?  Obviously creature_on_trap with trigger twice as it should, but does the rest of it get handled gracefully as well?

Comment (ssorpg) [reply src/game.cpp]: Hmm from testing in VS, the `m.creature_on_trap( *c, false );` should only fire once - either `thru && trap_under_creature == tr_ledge`, meaning you didn't hit a wall or floor and you're standing on a ledge trap (open space), or you hit something/are standing on floor/a trap and impact the ground.

I think that once you activate a ledge trap it then checks to make sure you're not standing on another ledge, but I'll have to test it.

Comment (alanbrady) [reply src/game.cpp]: Right it should check if standing on another ledge in the second `m.creature_on_trap`, but then what happens if there's a third?

Comment (ssorpg) [reply src/game.cpp]: It should only activate that once though, right? Since I have `if( thru && trap_under_creature == tr_ledge ) {`, and then `} else {`, either I activate `m.creature_on_trap( *c, false );` or I activate `// Fall on ground`...`m.creature_on_trap( *c, false );`. I don't think it activates both if and else in an if statement, does it?

Also just tested multiple z-levels (good idea, I hadn't thought of that!) and it worked as intended.

Comment (alanbrady) [reply src/game.cpp]: I was mostly speculating through code inspection, if you tested it and everything seems to work well then we're good :+1: thanks!

Comment (ssorpg) [reply src/game.cpp]: No problem, and thank you too! I would not have remembered to test multiple z-levels if you hadn't brought it up.

Comment (alanbrady) [reply src/game.cpp]: > Since I have i if( thru && trap_under_creature == tr_ledge ) {, and then } else {, either I activate m.creature_on_trap( *c, false );

Wait, no, the second_ creature_on_trap is outside the if/else statement.  Is this what you intended?

Comment (ssorpg) [reply src/game.cpp]: Wait I think you're being confused by the GitHub page. On line 12328, which is just below our comments, is where the if else ends. It probably looks like it's ending on line 12333 though since there's a nested if in there.

Comment (alanbrady) [reply src/game.cpp]: That's exactly what happened, sorry for the thrash, I deleted my comment once I realized I had misread it.  Mea culpa.

Comment (ssorpg) [reply src/game.cpp]: Oh no problem at all! If anything, I just thought I was misunderstanding there, haha!
