### PR TITLE
Fixes adjusted tool requirements entering invalid state for tools with charges.

### LINKED ISSUE #32601: UI shows tools that don't exist when continuing crafting food item
# Describe the bug
UI shows tools that don't exist when continuing crafting food item as pictured, pressing enter appears to pass a turn, progress is made on the item

Save here: [https://drive.google.com/file/d/13URucCjxpju2njthHwUsBiyiR9i20Ujv/view?usp=sharing](url)
# Steps To Reproduce

1: load my save
2: light fire
3: 'a'ctivate the roasted acorns in progress in player hands
4: have screen pictured appear
image

# Expected behavior
Item crafting as per normal

# Screenshots

**If applicable**, add screenshots to help explain your problem.

above

# Versions and configuration

9368, latest build as of 25/07/2019 12:05PM GMT 10+ windows tiles x64
 - Mods loaded: [both mods that add more survival tools, medieval items, all location mods, graphical indicators]

### PR DESCRIPTION
**Pull request by ProfoundDarkness**
#### Summary

SUMMARY: Bugfixes "Fixes adjusted tool requirements entering invalid state for tools with charges."

#### Purpose of change

Fixes #32601 (there may be others)

#### Describe the solution

Observed that adjusted tools requirements was ending up with a count of 0 (though required count > 0 value to enter the section).  Later when code which checks if the tools are available to the player the count of 0 caused that code to think the tool was available (marked as available and flag of can craft was set/left true).

0 seems an invalid state for tools with charges so added code which sets to require at least 1 charge on the adjusted requirements.

#### Describe alternatives you've considered

An alternative is to modify requirements.cpp - requirement_data::has_comps() to do additional checking of if the tool is actually available even if it has 0 charges.  I barely comprehend this section so this would (probably) have to be done by someone else.

Remove the division operator near where I added my change.  This defeats the purpose of allowing the player to continue crafting a little bit more even though the next tool they selected is insufficient to complete crafting so didn't go with that path.

Re-structure the code near where my change is in order to operate on the batch level rather than percentage level (remove multiplication AND division operations).  This has the same problem as above where the player may have slightly insufficient tool charges with whatever tool is on hand and thus wouldn't be allowed to continue.  There are some tasks that even a single item in a batch requires a fair number of charges.

Switch count to be floating point.... nah that seems SO much overkill and a bad idea.

#### Additional context

I'm not really happy with the ternary operator I tossed in to keep things valid and welcome suggestions for an alternative.

### CODE REVIEW

File: src/crafting.cpp [hunk 1]
```diff
@@ -1274,6 +1274,8 @@ bool player::can_continue_craft( item &craft )
                     adjusted_alternative.count *= batch_size;
                     // Only for the next 5% progress
                     adjusted_alternative.count /= 20;
+                    // Tools which require charges MUST leave here with at least 1 charge requirement or enter invalid state.
+                    adjusted_alternative.count = ( adjusted_alternative.count < 1 ) ? 1 : adjusted_alternative.count;
```
Comment (AMurkin) [inline src/crafting.cpp]: Something like this maybe?
```suggestion
                    adjusted_alternative.count = clamp( adjusted_alternative.count, 1, INT_MAX );
```

Comment (ProfoundDarkness) [reply src/crafting.cpp]: I think so, gonna test it.

**Comment by ProfoundDarkness** [comment]
Hmm, gonna have to dig into the tests a bit since this is causing one to fail.
