### PR TITLE
Fixed crash related to map memory

### LINKED ISSUE #27600: Segmentation Fault (Tile Related?)
**Description**
Segmentation Fault occurs when walking below a certain point on the map

**Reproduce**
1)Load the save file that's included at the bottom of this issue.
2)Walk right to the road
3)Walk down to the shady Zombies
4)Segmentation Fault. (There is a screenshot as well In the Additional Info that shows the Rough location where the Segfault occurs)

**Additional Info**
VERSION: 0.C-36428-g9802051
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5CD6A5[cataclysm-tiles.exe+0x1CD6A5]
    @0x5CE252[cataclysm-tiles.exe+0x1CE252]
    SMPEG_error+0x4B034@0xE666D0[cataclysm-tiles.exe+0xA666D0]
    _C_specific_handler+0x8C@0x77417398[ntdll.dll+0x57398]
    _chkstk+0x9D@0x7742BF9D[ntdll.dll+0x6BF9D]
    RtlInitializeResource+0x53A@0x774004CA[ntdll.dll+0x404CA]
    KiUserExceptionDispatcher+0x2E@0x7742B63E[ntdll.dll+0x6B63E]
    @0xD6E56B[cataclysm-tiles.exe+0x96E56B]
    @0xD6F9AE[cataclysm-tiles.exe+0x96F9AE]
    @0x8B49BE[cataclysm-tiles.exe+0x4B49BE]
    @0x6F4668[cataclysm-tiles.exe+0x2F4668]
    IMG_LoadWEBP_RW+0x4CC7C9@0x1445599[cataclysm-tiles.exe+0x1045599]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0xD@0x771B59CD[kernel32.dll+0x159CD]
    RtlUserThreadStart+0x1D@0x7741383D[ntdll.dll+0x5383D]

**Settings**
Soundpack: 2ch sounpack https://drive.google.com/drive/folders/1e7NAT07njV5TkxnQxpo4nxeI0RfpN25N

Tileset: MSX++DeadPeopleEdition

Version: Windows 7 64-Bit, Tiles

Mods: Dark Days Ahead, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, Makshift Items Mod, More Survival Tools, Modular Turrets, Salvaged Robots, Alternative Map Key, Mining Mod, Mutant NPCs, Beta National Gaurd Camp, Big River Building Pack, More Locations, Fuji's More Buildings, Oa's Additional Buildings Mod, Boats, Folding Parts Pack, Vehicle Additions Pack, Tanks and Other Vehicles, Classes and Scenarios Mod, StatsThroughSkills 

Screenshot Of Crash Location: https://i.imgur.com/PJ6AMdK.png
Screenshot Of Vertical Position (crashes if you move south further): https://i.imgur.com/mKvQLDJ.png
Save File: http://www.dropbox.com/s/s47b9lapyo72ufv/Crash.rar?dl=0

### LINKED ISSUE #27606: Disappearing cars
**Describe the bug**  
Cars disappear in a area

**To Reproduce**  
1. walk south 
2. cars disappear

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS:  Windows 10 
 - Game Version [from the main menu, e.g. 0.C-36428-g980251]
 - Graphics version [Tiles]
 - Mods loaded [disable npc needs, filthy clothing, simplified nutition, craftable gun pack, deadleaves fictional guns, extended realistic guns, icecoons arsenal, medieval and historic content, more survival tools, mythological replicas, modular turrets, salvaged robots, alt map keys, beta national guard camp, more locations, map gen demo, urban development, vehicle additions pack, tanks and other vehicles
[O'Fallon.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2753839/O.Fallon.zip)
]

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: Bugfixes "Fixed crash related to map memory"```

#### Purpose of change

Fixes #27600.
Fixes #27606.

#### Describe the solution

See commit messages.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
On the second look that won't fix the issue, but shift it a little bit as caches are only MAPSIZE_X*MAPSIZE_Y and casting to `size_t` would certainly cause out-of-bounds exception.

File: src/map.h [hunk 1]
```diff
@@ -260,12 +260,12 @@ class map
         void set_pathfinding_cache_dirty( const int zlev );
         /*@}*/
 
-        void set_memory_seen_cache_dirty( const tripoint p ) {
-            get_cache( p.z ).map_memory_seen_cache[ p.x + p.y * MAPSIZE_Y ] = false;
+        void set_memory_seen_cache_dirty( const tripoint &p ) {
+            get_cache( p.z ).map_memory_seen_cache[ static_cast<size_t>( p.x + ( p.y * MAPSIZE_Y ) ) ] = false;
```
Comment (kevingranade) [inline src/map.h]:
```suggestion
            const int offset = p.x + ( p.y * MAPSIZE_Y );
            if( offset >= 0 && offset < MAPSIZE_X * MAPSIZE_Y ) {
                get_cache( p.z ).map_memory_seen_cache.reset( offset );
            }
```

File: src/map.h [hunk 2]
```diff
@@ -260,12 +260,15 @@ class map
         void set_pathfinding_cache_dirty( const int zlev );
         /*@}*/
 
-        void set_memory_seen_cache_dirty( const tripoint p ) {
-            get_cache( p.z ).map_memory_seen_cache[ p.x + p.y * MAPSIZE_Y ] = false;
+        void set_memory_seen_cache_dirty( const tripoint &p ) {
+            const int offset = p.x + ( p.y * MAPSIZE_Y );
+            if( offset >= 0 && offset < MAPSIZE_X * MAPSIZE_Y ) {
```
Comment (jbytheway) [inline src/map.h]: I'm pretty sure this logic is wrong.  If `p.x` is out of bounds then this can wrap around to set a dirty bit on the wrong row.  I guess technically it doesn't actually matter, since extra dirty bits are safe, but it seems dubious.

Comment (ZhilkinSerg) [reply src/map.h]: I guess we can just call `generic_inbounds` function here, similar to what's called in lightmap or scent_map with boundaries of `x=0...MAPSIZE_X, y = 0...MAPSIZE_Y`.
