### PR TITLE
Fixes zone farming segmentation fault

### LINKED ISSUE #70371: Segmentation Fault When Asking NPC to Farm
### Describe the bug

I was trying to get my NPC follower to harvest the corn in a pre-genned farm field. I set up a fairly large farming zone, but was holding no seeds so the zone was set to "No Seed". After making this zone, I saved it and told my NPC to do some farming work. After waiting a couple of turns an error pops up about an invalid recipe, and after telling the game to ignore the error, the client segfaults. The error before the segfault is as follows:

 DEBUG    : invalid recipe id ""

 FUNCTION : obj
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\recipe_dictionary.cpp
 LINE     : 68
 VERSION  : c6f6397

### Attach save file

[Lilymoor-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13757575/Lilymoor-trimmed.tar.gz)

### Steps to reproduce

1. Spawn a player on a Farm Field with harvestable corn.
2. Spawn an NPC follower for the player.
3. Use the Zone Manager to designate an area of corn to be harvested, with No Seed selected.
4. Speak to the NPC, and pick "There's something I want you to do.", then "Let's talk about your current activity.", followed by "Please do some farming work."
5. Wait several turns.
6. When the error report pops up, press "i" to ignore it.

### Expected behavior

The NPC should proceed to harvest the corn instead of crashing the game.

### Screenshots

cdda farming zone
It's hard to make out, but you should be able to see the farming zone encompassing the bottom 5 rows of the corn field.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: c6f6397 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Blaze Industries [blazeindustries],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Voidmod [VoidMod]
]

### Additional context

[debug - Copy.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13757571/debug.-.Copy.log)
[crash - Copy.log](https://github.com/CleverRaven/Cataclysm-DDA/files/13757572/crash.-.Copy.log)

### PR DESCRIPTION
**Pull request by Novacat**
#### Summary
Bugfixes "Fixes zone farming segmentation fault"

#### Purpose of change
Fixes a segmentation fault when trying to zone farm without any seeds defined. Fixes #70371

#### Describe the solution
The issue is that if no seed is defined when it reaches the has_flag_ter_or_furn check, it causes a segmentation fault. Considering that part of the proc has to do with planting seeds anyway, it is probably better for the no seed check to happen before that check, instead of after.

#### Describe alternatives you've considered
There are probably better solutions but I am baby C++ programmer who barely groks basics.

#### Testing
I have tested tilling both with and without seeds using this code, and it works both times without a segmentation fault. It also properly plants seeds if you have seeds in your inventory and it is warm enough.

### CODE REVIEW

File: src/activity_item_handling.cpp [hunk 1]
```diff
@@ -1317,18 +1317,17 @@ static activity_reason_info can_do_activity_there( const activity_id &act, Chara
...
                     return activity_reason_info::fail( do_activity_reason::NEEDS_TILLING );
                 }
+                // do we have the required seed on our person?
+                // If its a farm zone with no specified seed, and we've checked for tilling and harvesting.
+                // then it means no further work can be done here
+            } else if( seed.is_empty() ) {
+                return activity_reason_info::fail( do_activity_reason::ALREADY_DONE );
             } else if( here.has_flag_ter_or_furn( seed->seed->required_terrain_flag, src_loc ) &&
                        // TODO: fix point types
                        warm_enough_to_plant( src_loc.raw() ) ) {
```
Comment (BrettDong) [inline src/activity_item_handling.cpp:1327]: One way to fix the clang-tidy error is to merge this "seed is empty" block with the else block at line 1341
```suggestion
            } else if( here.has_flag_ter_or_furn( seed->seed->required_terrain_flag, src_loc ) &&
                       // TODO: fix point types
                       warm_enough_to_plant( src_loc.raw() ) &&
                       // do we have the required seed on our person?
                       // If its a farm zone with no specified seed, and we've checked for tilling and harvesting.
                       // then it means no further work can be done here
                       !seed.is_empty() ) {
```

Comment (Novacat) [reply src/activity_item_handling.cpp:1327]: I am worried that allowing has_flag_ter_or_furn to even check will cause the segfault. Based on reading the clang error, it seems clang wants me to turn

`            } else if( seed.is_empty() ) {`

into

`            }
            else if( seed.is_empty() ) {`

This would require me to edit substantial portions of the proc, since most of the proc does this.

**Comment by Novacat** [comment]
I tested the suggested fix and unfortunately it brought the segfault back.
