### PR TITLE
Fixes regression introduced in previous PR concerning gunmods

### LINKED ISSUE #47320: Some gun mods cannot be installed despite the weapon being unloaded.
# Describe the bug
The following gun mods cannot be installed despite meeting installation requirements and having an unloaded weapon capable of having them:
drop-in auto sear
firearm waterproofing
lightning link
match trigger

#47200 might be related.

# Steps To Reproduce

1. Wield an unloaded AR-15.
2. Try installing one of the gun mods mentioned above.

# Expected behavior

Gun mods should be allowed to be installed if you meet all requirements, including the weapon being unloaded.

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.2.1; Codename: Nibia; 
- Game Version: 0.E-9461-g0638fba7a9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    No Fungal Monsters [No_Fungi],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]

# Additional context

N/A

### PR DESCRIPTION
**Pull request by ToxiClay**
#### Summary
Interface "Fixes regression introduced in previous PR concerning gunmods"

#### Purpose of change

Closes #47320

#### Describe the solution

I replaced a conditional check I accidentally removed.

#### Testing

I tested the ability of my head to phase into my desk after reading the issue.

#### Additional context

God, I'm dumb.

### CODE REVIEW

**Comment by actual-nh** [comment]
>Testing
I tested the ability of my head to phase into my desk after reading the issue.

>Additional context
God, I'm dumb.

Eh, everyone makes mistakes...

File: src/item.cpp [hunk 1]
```diff
@@ -8029,7 +8029,8 @@ ret_val<bool> item::is_gunmod_compatible( const item &mod ) const
         return ret_val<bool>::make_failure( _( "cannot have a brass catcher" ) );
 
     } else if( mod.type->gunmod->location.name() == "magazine" ||
-               mod.type->gunmod->location.name() == "mechanism" ) {
+               mod.type->gunmod->location.name() == "mechanism" ) &&
+               ( ammo_remaining() > 0 || magazine_current() ) ){
```
Comment (Trioct) [inline src/item.cpp:8033]:
```suggestion
               mod.type->gunmod->location.name() == "mechanism" &&
               ( ammo_remaining() > 0 || magazine_current() ) ) {
```
I'm using this as an excuse to test suggestions since I've never used this feature ;)

Comment (ToxiClay) [reply src/item.cpp]: > I'm using this as an excuse to test suggestions since I've never used this feature ;)

:)

File: src/item.cpp [hunk 2]
```diff
@@ -8028,8 +8028,9 @@ ret_val<bool> item::is_gunmod_compatible( const item &mod ) const
     } else if( mod.typeId() == itype_brass_catcher && has_flag( flag_RELOAD_EJECT ) ) {
         return ret_val<bool>::make_failure( _( "cannot have a brass catcher" ) );
 
-    } else if( mod.type->gunmod->location.name() == "magazine" ||
-               mod.type->gunmod->location.name() == "mechanism" ) {
+    } else if( ( mod.type->gunmod->location.name() == "magazine" ||
+                 mod.type->gunmod->location.name() == "mechanism" ) &&
+               ( ammo_remaining() > 0 || magazine_current() ) ){
```
Comment (BrettDong) [inline src/item.cpp:8033]:
```suggestion
               ( ammo_remaining() > 0 || magazine_current() ) ) {
```
