### PR TITLE
fix METABOLISM enchantment `multiply: -1` causing the game to hang

### LINKED ISSUE #72242: Regression--METABOLISM of 0 causes the game to hang.
### Describe the bug

Setting METABOLISM to zero (such as by enchantment with `{ "value": "METABOLISM", "multiply": -1.0 }`) causes the game to hang indefinitely on the turn after it's set. This was explicitly fixed in #69894, so there's been a regression since then. 

### Attach save file

[Hagerstown-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/14534044/Hagerstown-trimmed.tar.gz)

### Steps to reproduce

1) Cast the spell Stones' Fortitude, which reduces metabolism to zero at max level.
2) Attempt to move
3) Game hangs indefinitely

### Expected behavior

Metabolism of 0 is supported post- #69894

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4046 (22H2)
- Game Version: 9f08089 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Magiclysm [magiclysm]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
None
#### Purpose of change
Fix #72242
`weariness_level` uses `weary_threshold`, which uses `base_bmr`, which uses `metabolic_rate_base`, which uses `hunger_rate`, and this one may be make zero using METABOLISM enchantment; since all of stuff that happens between these two are multiplicative only, it can carry zero value all way back to `weariness_level` calculations, which then stuck in the loop infinitely, trying to subtract zero `threshold` from whatever `weariness` is
#### Describe the solution
Put failsafe code, that checks if `weary_threshold` is zero, and if true, simply return zero, bypassing entire loop
Added test, that checks the trait, that turns off METABOLIC, to prevent regressions of this type in the future
#### Describe alternatives you've considered
Return some another value
Make BMI not being able to be zero
#### Testing
Compiled, casted `Stones' Fortitude` lvl 20, the game do not stop responding
#### Additional context
I have no clue how the entire chain works ngl, not even sure BMI = 0 makes any sense

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -4920,26 +4920,37 @@ int Character::weariness_level() const
     int threshold = weary_threshold();
     int level = 0;
     amount -= threshold * get_option<float>( "WEARY_INITIAL_STEP" );
-    while( amount >= 0 ) {
-        amount -= threshold;
-        if( threshold > 20 ) {
-            threshold *= get_option<float>( "WEARY_THRESH_SCALING" );
+    // failsafe if threshold is zero; see #72242
+    if( threshold == 0 ) {
+        return level;
```
Comment (LetterShapedGlyphs) [inline src/character.cpp:4925]: The closer to 0 metabolism is the closer to 0 threshold is which means as you approach zero this function returns increasingly higher levels. Suddenly dropping that to 0 instead of whatever the max is when you finally hit 0 seems like the opposite of the trend.

Comment (GuardianDll) [reply src/character.cpp:4925]: it is indeed not correct, but it is not something i made, and i clearly have no idea how to resolve it, so i just assume it is a feature and character with no metabolism should not be tired

File: src/character.cpp [hunk 2]
```diff
@@ -4872,10 +4872,15 @@ std::pair<int, int> Character::weariness_transition_progress() const
     int amount = weariness();
     int threshold = weary_threshold();
     amount -= threshold * get_option<float>( "WEARY_INITIAL_STEP" );
-    while( amount >= 0 ) {
-        amount -= threshold;
-        if( threshold > 20 ) {
-            threshold *= get_option<float>( "WEARY_THRESH_SCALING" );
+    // failsafe if threshold is zero; see #72242
+    if( threshold = 0 ) {
```
Comment (GuardianDll) [inline src/character.cpp:4876]:
```suggestion
    if( threshold == 0 ) {
```
