### PR TITLE
Fix Segmentation Fault When Removing Last Part Of Vehicle

### LINKED ISSUE #41464: Seg Fault when fully taking apart any vehicle
# Describe the bug
Seg fault occurs whenever you remove the last bit of any vehicle 

# Steps To Reproduce
1. Start a vehicle with any frame
2. Examine vehicle
3. Use O menu to removes the last piece
4. Experience crash
(Vehicle to direct south in the save)

# Expected behavior
Being able to fully dismantle a vehicle without a crash

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-3388-gc2cd66c [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[Crash-Debug.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4807276/Crash-Debug.zip)

[Seg Fault save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4807277/Seg.Fault.save.zip)

### PR DESCRIPTION
**Pull request by Rhxydos**
#### Summary
SUMMARY: Bugfixes "The game will no longer crash when you remove the last part from a vehicle."

#### Purpose of change
Previously, when a vehicle as fully deconstructed by rem'o'ving the last part, the game would attempt to cache the now non-existent vehicle, and crash. Now it doesn't do that.

Fixes #41464

#### Describe the solution
Added a boolean flag to the 'complete_vehicle' function in veh_interact.cpp, and used that flag to stop the game from trying to cache the non-existent vehicle.

#### Describe alternatives you've considered
Reworking how caching is handled to prevent this sort of issue from being possible. I decided against it because I'm not knowledgable about the game or c++ to make that happen.

#### Testing
Constructed a vehicle with a frame, and then removed that frame. The game didn't crash. I also ran far away from my test locations, and saved/reloaded the game, to make sure that the lack of cache updating wouldn't break anything during the saving/loading of the map.

#### Additional context
This probably isn't the most elegant solution possible, but this bug has been in the game for over a week now, and it's been causing me problems, so I wanted to fix it.

### CODE REVIEW

File: src/veh_interact.cpp [hunk 1]
```diff
@@ -3182,6 +3185,7 @@ void veh_interact::complete_vehicle( player &p )
                 p.add_msg_if_player( _( "You completely dismantle the %s." ), veh->name );
                 p.activity.set_to_null();
                 g->m.destroy_vehicle( veh );
+                safe_to_cache = false;
             } else {
                 veh->remove_part( vehicle_part );
                 veh->part_removal_cleanup();
```
Comment (mlangsdorf) [inline src/veh_interact.cpp:3191]: it would be simpler to move the `update_vehicle_cache()` call to the end of this if block.

Comment (SageB) [reply src/veh_interact.cpp:3191]: My concern with that was that it could mess with other things that were relying on that call to update_vehicle_cache() for caching.

Comment (anothersimulacrum) [reply src/veh_interact.cpp:3191]: It won't change anything about how this code works - the caching is only triggered in that else branch, because the precondition to it is set to false in the non-else branch.

Nothing that happens between that else branch and the caching happening would be impacted/impact the caching.

Comment (SageB) [reply src/veh_interact.cpp:3191]: Alright, I'll make the change.
