### PR TITLE
Better handling of item templates

### LINKED ISSUE #19566: Undefined behavior due to item_factory::m_templates map scrambling
Introduced in #19058

That pointer indirection wasn't needless after all.

Hard to replicate due to high dependency on system, compiler and possibly runtime, but can be reproduced like:
* Start game
* Create some items (preferably of different types)
* Create new item types (artifacts)
* `m_templates` is scrambled to keep the tree structure
* Items' pointers to their `itype`s now point at undefined locations
* Crash - or worse

Fixing this would require reverting #19058 or getting rid of artifacts and prohibiting future runtime types.
Runtime types would be a good thing to have and artifacts - while rare - are still an important part of the game.

### PR DESCRIPTION
**Pull request by mugling**
Fixes #19566

Testing shows that removing pointer indirection from #19058 provides a significant performance benefit (16386ms to 12824ms) for the unit test described in #19566. This PR separates the fixed and runtime templates as they have differing storage requirements so that you only pay for what you need. The changes are relatively unobtrusive (59cbb24)

A considerable performance increase (12824ms to 1684ms) is provided by a change from `std::map` to `std::unordered_map` in 3d886fb

### CODE REVIEW

**Comment by mutability** [comment]
I am still uncomfortable about returning long-lived pointers into the internal storage of an (unordered_)map.

Can we maybe put in a "freeze" step which is called when the static templates are fully populated and

(a) refuse to hand out pointers before the freeze step is done
(b) refuse to modify the static templates after the freeze step is done

Alternatively just have both maps use unique_ptr (you can still hand out raw pointers; the change is that map mutation won't invalidate the raw pointer if the object is being managed by a unique_ptr)

**Comment by mugling** [comment]
> Can we maybe put in a "freeze" step which is called when the static templates are fully populated and

That conditional could easily be implemented in `Item_factory::finalize()` providing it doesn't affect performance too badly.

> Alternatively just have both maps use unique_ptr

This comes with a relatively significant performance overhead which is important since anything that converts an `itype_id` uses this function including item construction, group lookup, ammo handling, vehicle parts etc.

The performance overhead probably has more to do with cache coherency than the actual indirection so perhaps the above conditional will be fast enough. It's tempting to suggest an assertion instead that gets excluded in the release build - this should catch any nasty bugs during development.

Overall we don't do error handling well. I'm not sure how everyone feels about exceptions but we should certainly make more use of assertions. We also need to consider performance more than we have historically. In this case profiling and testing shows an obvious performance benefit so the next step could be a free step plus assertion in debug builds that should catch any problems during loading.

**Comment by mutability** [comment]
Sounds like there is scope for storing the result of item::find_type() in callers (e.g. vehicle parts seem like an obvious win). It'd be useful to look at the dynamic call graph for find_type, I'm sure it'll be 2-3 callers that account for almost all of the cost.

**Comment by mugling** [comment]
> Sounds like there is scope for storing the result of item::find_type() in callers

Yes, we already do this optimisation for `item`. This won't work in all situations though so keeping this lookup quick is important. Caching can bring it's own subtle bugs too.

I'm leaning towards a conceptually simple `assert` catching any lookups requested prior to `finalize`

**Comment by mutability** [comment]
Yeah, that assert would be good (plus enforcing no-modifications-after-finalize, which shouldn't be an issue to always do)

Really need to look at the profile to work out where any caching would help. While there is some lowhanging fruit here (unordered_map et al) any further gains are going to be about doing less work - call find_type() less often.

**Comment by mugling** [comment]
There is also the (unproven) possibility that keeping all the `itypes` in the same space might improve cache locality improving the performance of `itype` and it's dependent members overall. This may explain why that pointer indirection seems to matter far more than it should. If we're not careful we may add a further huge but immeasurable performance loss. I'm not sure if I have the exact terminology correct here but I should think you can comprehend the point I'm trying to make.

**Comment by mugling** [comment]
> plus enforcing no-modifications-after-finalize, which shouldn't be an issue to always do

`m_templates` is already `private` and therefore short of writing an easily subverted private acessor this is already de facto the case

**Comment by mutability** [comment]
It is exactly things with access to m_templates that need to enforce the no-modification rule. For example find_templates() will currently modify m_templates if you ask for an undefined ID. This is Bad and will cause hard-to-find bugs. Either that needs to assert if it happens post-freeze, or you need to put the placeholder type in the dynamic map not m_templates (and m_templates can probably lose the mutable in that case..)

The other enforcement point I see is load_basic_info which should never be called post-freeze anyway so let's enforce that obviously rather than having a subtle bug if it ever happens.

**Comment by mugling** [comment]
I'm going to add the suggested `assert` to this now and also fix missing items to use a runtime (not static) type

**Comment by mugling** [comment]
Note this isn't a buildbot failure - it just updates the Makefile so that `RELEASE` builds include the `NDEBUG` macro encouraging liberal usage of `assert` without regards to performance.

**Comment by mugling** [comment]
Final commit changes missing items to be created as runtime not static types. I think we should probably better handle missing items overall (refuse to create them) but that can come in a separate PR.

No further changes

**Comment by mutability** [comment]
I think the NDEBUG change needs to be a separate thing.

**Comment by mugling** [comment]
> I think the NDEBUG change needs to be a separate thing.

No. it needs to go in this once or I'm dropping the `assert`

**Comment by mutability** [comment]
also, can you fix your system clock / timezone? Having commits appear in the future is pretty confusing when looking at the issue in sequence.

**Comment by mutability** [comment]
Setting NDEBUG turns off asserts everywhere. Have you checked that none of them anywhere have side-effects? That would be a bug, but it is also why I object to setting NDEBUG without care.

**Comment by mugling** [comment]
> also, can you fix your system clock / timezone? Having commits appear in the future is pretty confusing when looking at the issue in sequence.

Yes, after this merge run

**Comment by mugling** [comment]
> Setting NDEBUG turns off asserts everywhere. Have you checked that none of them anywhere have side-effects? That would be a bug, but it is also why I object to setting NDEBUG without care.

There aren't many in the project so I'm going to check for side effects now
```
$ grep 'assert' src/* | cut -d: -f1 | sort | uniq -c                                                                                             
   1 Binary file src/item_factory.o matches
   5 src/activity_item_handling.cpp
  37 src/advanced_inv.cpp
   1 src/catalua.cpp
   5 src/debug.cpp
   1 src/enums.h
   2 src/game.cpp
   1 src/inventory_ui.cpp
   1 src/item.cpp
   2 src/item_factory.cpp
   2 src/item_group.cpp
   1 src/iuse_software_snake.cpp
   1 src/line.cpp
   2 src/map.cpp
   1 src/mapgen.cpp
   1 src/mapgenformat.cpp
   4 src/mapgenformat.h
   2 src/newcharacter.cpp
   3 src/overmap.cpp
   4 src/overmapbuffer.cpp
   2 src/scent_map.cpp
   9 src/units.h
   2 src/veh_interact.cpp
   1 src/vehicle.cpp
   1 src/wdirent.h
```

**Comment by Coolthulhu** [comment]
No asserts in release isn't a good idea.
Line asserts are a great example - if not for the asserts, we wouldn't find them unless someone built a debug and noticed why things are all going wrong.

We need feedback from users, not just dedicated testers.

**Comment by mugling** [comment]
No side effects:
```
$ grep 'assert(' src/*.cpp | cut -d: -f2 | sort | uniq -c                                                                                        
   1                         assert(!elem.is_null());
   1                     assert(!moving_item.is_null());
   1                     assert(msg != nullptr);
   1                 assert( d1.cat != nullptr );
   1                 assert( d2.cat != nullptr );
   1                 assert( fuel->ammo->energy > 0 ); // enforced in item_factory.cpp
   1                 assert( g->u.has_activity( activity_id( "ACT_ADV_INVENTORY" ) ) );
   1                 assert( pt->base.max_damage() > 0 ); // why repairing part that cannot be damaged?
   1             // assert( false );
   1             // assert( type == PLTYPE_NOW );
   1             assert( !cont->contents.empty() );
   1             assert( !sitem->items.empty() );
   1             assert( &cont->contents.front() == sitem.items.front() );
   1             assert( actor );
   1             assert( amount_to_move > 0 );
   1             assert( cont != nullptr );
   1         assert( AIM_NORTHEAST - AIM_SOUTHWEST == 8 );
   1         assert( d_cargo >= 0 );
   1         assert( d_veh != nullptr );
   1         assert( g->m.inbounds( local ) );
   1         assert( ms.x >= 0 && ms.x < SEEX );
   1         assert( ms.y >= 0 && ms.y < SEEX );
   1         assert( s_cargo >= 0 );
   1         assert( s_veh != nullptr );
   1         assert( squares[menu.ret].canputitems() );
   1         static_assert( std
   1     assert( !items.empty() );
   1     assert( !items.empty() ); // index would not be valid, and this would be an endless loop
   1     assert( !sitem.items.empty() );
   1     assert( !sitem.items.empty() ); // valid item is obviously required
   2     assert( destarea != AIM_ALL ); // should be a specific location instead
   1     assert( dir != om_direction
   1     assert( div != 0 );
   1     assert( dt >= DT_NULL && dt < NUM_DT );
   1     assert( filename != nullptr );
   1     assert( funcname != nullptr );
   1     assert( get_cur_item_ptr() != nullptr ); // index must already be valid!
   1     assert( id != AIM_ALL ); // should be a specific location instead
   1     assert( input_amount > 0 ); // there has to be something to begin with
   1     assert( line != nullptr );
   1     assert( menu != nullptr );
   1     assert( menu->entries.size() >= 9 );
   4     assert( offset != 0 ); // 0 would make no sense
   2     assert( offset == -1 || offset == +1 ); // only those two offsets are allowed
   1     assert( p != invalid_tripoint );
   1     assert( sitem.area != AIM_ALL );        // should be a specific location instead
   1     assert( sitem.area != AIM_INVENTORY );  // does not work for inventory
   1     assert( square.id != AIM_ALL );
   1     assert( stacks >= 1 );
   1     assert( static_cast<size_t>( index ) < items.size() ); // valid index is required
   1     assert( w_inv );
   1     assert( zlevels );
   1     assert(!line.empty() && line.front() != line.back());
   1     assert(ptr.get() != NULL);
   1     assert(stacks >= 1);
   1  * assert(it.id == "water");
```

This is good because once we have `NDEBUG` we can start adding a lot more `assert` - in particular to document preconditions and the like with out concern as to performance.

**Comment by mutability** [comment]
Also, looking at the assert, it _tests a boolean field_. Are you seriously suggesting that testing a boolean field is sufficiently expensive that you'd rather risk unpredictable bugs? This has already broken nastily once, can we please keep the safety net here?

**Comment by mutability** [comment]
> No side effects:

That is a naive assertion (heh) if you're just basing it on a grep.
Obvious things:

 * There are multi-line assertions;
 * You excluded any case where there's a space after the assert
 * There are calls to nontrivial functions in the asserts you did list

**Comment by mugling** [comment]
> No asserts in release isn't a good idea.

`assert` means should never happen and should only be used to effectively localize a crash during development. If something can potentially happen and/or recovered from it should be an explicit conditional plus an exception or `debugmsg`.

We should use `assert` for it's intended function otherwise we're just going to end up with `real_assert` macro that does have the expected characteristics.

Our current error handling is awful. We don't fail on bad JSON we just keep going. Someone even wrote a PR that swallows thrown exceptions during the process (which also eats the file and line number). The nett effect is that you get a dozen unattributed load errors followed by a segfault.

`assert` means should never happens and will always result in a hard crash. `debugmsg` means might happen and should be recovered from gracefully.

We do need an `assert` macro and it should actually be called `assert`

**Comment by mugling** [comment]
> Are you seriously suggesting that testing a boolean field is sufficiently expensive that you'd rather risk unpredictable bugs?

No I'm suggesting that if they aren't compiled out they are defacto `debugmsg` and therefore very few assertions will be added to the codebase which is unfortunate as they are self-documenting preconditions.

**Comment by mugling** [comment]
Or put more eloquently (via stack overflow)

*"If you're even thinking of leaving assertions on in production, you're probably thinking about them wrong. The whole point of assertions is that you can turn them off in production, because they are not a part of your solution. They are a development tool, used to verify that your assumptions are correct. But the time you go into production, you should already have confidence in your assumptions"*

They are effectively comments that don't become outdated and make development easier by turning stopping a nullptr deference at source as opposed to allowing it to occur half a dozen function calls later. If any calls should be enabled in production those should be `debugmsg`

**Comment by mutability** [comment]
In this particular case:

 * Callers expect the returned pointer to be stable; item_factory needs to guarantee that
 * If it does not guarantee that then we have unpredictable bugs at an indeterminate later point. It is not an immediate crash

If you can't (or don't want to) enforce the stability guarantee via freezing the map then I think we need to go back to unique_ptr which does provide that guarantee.

If you think that assert() is the wrong thing to use to enforce the guarantee then that's fine, but I don't know if there's a simple way to get the same facilities (popup window so the user knows what's going on before you call abort()).

Note that debugmsg is no good here because _we cannot safely continue_ if a lookup is done on a nonfrozen map.

**Comment by mutability** [comment]
> We should use assert for it's intended function otherwise we're just going to end up with real_assert macro that does have the expected characteristics.

I would be fine with an `expensive_assert` that was disabled in release builds. Or we could rename existing `assert` calls to something else (`enforce` or whatever) and have plain `assert` be the "expensive debug-only assert" path. The call in this PR would need to be to the version that is present in release builds.

But I think that is all discussion that better belongs in a separate PR, as I originally suggested. It should not prevent this PR getting merged; drop the NDEBUG change and argue it out separately.

**Comment by mugling** [comment]
I do want to enforce via freezing as it's a good solution. There's a demonstrable performance difference for `unique_ptr` and as discussed above probably another massive but immeasurable difference elsewhere due to cache locality so that's excluded.

I don't want production asserts though because that removes one developer tool which can be quite effective and which we currently don't use.

**Comment by mutability** [comment]
> we cannot safely continue if a lookup is done on a nonfrozen map.

On reflection this is not strictly true, we could have lookups on a nonfrozen map entirely ignore m_templates and treat it like a missing itemtype. But that's potentially more confusing (why is this itemtype missing when it's clearly present?)

**Comment by mugling** [comment]
> On reflection this is not strictly true, we could have lookups on a nonfrozen map entirely ignore m_templates and treat it like a missing itemtype

We shouldn't do though. This problem is only going to occur if there is call to `find_template` prior to `finalize` and that will only occur if JSON loading order isn't sensible and should be readily identifiable during development.

Helpfully these assertions actually fail due to some odd looking NPC code. This is `assert` working as intended - you litter it everywhere and then it stops you during development as soon as your preconditions no-longer hold true. If there is a performance penalty in production your tempted not to add them, especially in loops, and this rather obviates their purpose.

**Comment by mutability** [comment]
I would be slightly happier with setting NDEBUG for a milestone build (that mythical creature)
as at that point we'd be fairly confident in our assumptions (as the SO quote suggests)
though I am worried about changing the code from what-was-tested in that case.

I agree with @Coolthulhu that we need to retain asserts in release builds of experimentals, because our users are also our testers here and we need to see those asserts trigger when random non-developers are playing.

**Comment by Coolthulhu** [comment]
By the way, I test all builds in release, because debug is unworkably slow here and because debug often hides compiler/system issues.

**Comment by mugling** [comment]
All that does though is reduce `assert` to a convenience-variant of `debugmsg`. If we are expecting failures we should call `debugmsg` otherwise we then need a `real_assert` macro.

**Comment by mutability** [comment]
debugmsg is "hey this is weird but I can continue"
assert is "hey this is weird and I am going to give up now"

**Comment by mugling** [comment]
> By the way, I test all builds in release, because debug is unworkably slow here and because debug often hides compiler/system issues.

I'm aware of that. There is no reason the debug build couldn't have optimizations enabled. There isn't much point in it existing if developers don't actually make use of it.

**Comment by Coolthulhu** [comment]
You can introduce the non-assert define in a separate PR. Otherwise this one will be held up until we agree on one option.

**Comment by mugling** [comment]
> debugmsg is "hey this is weird but I can continue"
> assert is "hey this is weird and I am going to give up now"

So what do we do here?

```
if( tight_loop() ) {
   assert( trash_performance = true )
  ...
```

**Comment by mutability** [comment]
> So what do we do here?

```
assert( hoisted_condition );
while( tight_loop() ) {
  expensive_assert( trash_performance() );
}
```

**Comment by mutability** [comment]
> EDIT: What your actually proposing is that we have fatal_debugmsg

That is exactly how I have always used assert()

**Comment by mugling** [comment]
> That is exactly how I have always used assert()

With intended respect (seriously, no snark) that's not correct and the authors of the C standard library agree with that (hence `NDEBUG`).

You're confounding two of the three possible outcomes

1. Recoverable error (debugmsg plus action)
2. Irrecoverable error (fatal debugmsg)
3. Documented precondition (assert)

**Comment by mutability** [comment]
Failure of a documented precondition is a type of irrecoverable error.
There are other types of irrecoverable error that should not be handled via assert().

**Comment by mutability** [comment]
If you can give me a `fatal` or `enforce` macro that works just like `assert` except it isn't called `assert` and isn't affected by NDEBUG I am happy to switch to using that.

**Comment by mugling** [comment]
> Failure of a documented precondition is a type of irrecoverable error.

Yes, but it's one that is expected to never occur. If the (2) and (3) are confounded all expensive precondition checks have to be removed from the codebase whereas if they are not then you can leave them in as documentation. `assert` is a developer tool.

**Comment by mugling** [comment]
> If you can give me a fatal or enforce macro that works just like assert except it isn't called assert and isn't affected by NDEBUG I am happy to switch to using that.

Sounds good. I think that would be an excellent addition and I'm going to do it in this PR as we've already done most of the discussion step

**Comment by mugling** [comment]
@mutability something simple should work in `debug.h` where `STRING` is our existing stringification macro

```
#define fatal(cond) \
    if( !( cond ) ) { \
        realDebugmsg( "Assertion failed: %s", STRING( cond ) ); \
        std::terminate(); \
    }
```

**Comment by mugling** [comment]
@Coolthulhu I've pushed the above macro and updated the item_factory to use it having confirmed no performance regression

**Comment by mugling** [comment]
@mutability it's the same grep results without the parenthesis. Only two could potentially contain unintended side effects (but probably don't) and are updated in 1558fe5. Notwithstanding macros should never contain code with side-effects amyway as such code may be evaluated multiple times.

File: src/debug.h [hunk 1]
```diff
@@ -53,6 +53,12 @@
 #define __FUNCTION_NAME__ __func__
 #endif
 
+#define fatal(cond) \
```
Comment (mutability) [inline src/debug.h]: fatal() is probably a poor choice of name here since it is fatal if the condition is false, not if it is true.

File: src/debug.h [hunk 2]
```diff
@@ -53,6 +53,12 @@
...
+    if( !( cond ) ) { \
+        debugmsg( "Assertion failed: %s", STRING( cond ) ); \
+        std::terminate(); \
```
Comment (mutability) [inline src/debug.h]: This is not equivalent to assert; it won't tell the user anything if it's triggered before there's a window (e.g. on Windows, where the user doesn't see cerr)

**Comment by mutability** [comment]
Can you globally replace the existing asserts? Unless they're shown to have a performance problem, it's more useful to have them in than not.

File: src/debug.h (hunk 1 above)
Comment (mugling) [inline src/debug.h]: It does look a little odd, suggestions?

File: src/debug.h (hunk 2 above)
Comment (mugling) [inline src/debug.h]: That's a known issue with `debugmsg` that has been noticed before and should be fixed upstream. I'll probably tackle this in a further PR once I dig out the windows API reference

**Comment by mugling** [comment]
> Can you globally replace the existing asserts? Unless they're shown to have a performance problem, it's more useful to have them in than not.

Fair enough

File: src/debug.h (hunk 2 above)
Comment (mutability) [inline src/debug.h]: I understand, but it's a regression.

A simpler fix, if you can deal with assert not meaning quite what you think it should mean, is to leave assert() alone and have something like:

```
#ifdef RELEASE
#  define debugassert(x)
#else
#  define debugassert(x) assert(x)
#endif
```
which retains all the existing platform-specific parts of assert.

**Comment by mutability** [comment]
> Fair enough, but what are we naming it first?

"enforce"? "require"? (possibly all-caps?)

File: src/debug.h (hunk 2 above)
Comment (mugling) [inline src/debug.h]: No, we have enough non-standard idioms. Anyone external to the project is going to expect `assert` to have certain characteristics.

We need to fix that `debugmsg` problem anyway.

I'm going to rename `fatal` to `enforce` - how does that sound?

**Comment by mugling** [comment]
> "enforce"? "require"? (possibly all-caps?)

Heh, we wrote that in duplicate. Lets go with `ENFORCE`

**Comment by mugling** [comment]
Why have us work on this all day and then unassign?

**Comment by Coolthulhu** [comment]
I won't be able to test it properly this run if `-DNDEBUG` stays.

**Comment by mugling** [comment]
> I won't be able to test it properly this run if -DNDEBUG stays.

Already the new checks are including in production builds - the only part that still to be resolved is naming the function which is pretty much agreed upon.

**Comment by mugling** [comment]
Done

**Comment by mugling** [comment]
Having to define an `enforce` macro as an alternative to `assert` means either the C standard library authors got it wrong or we lack a sane development model. Always compiling as `RELEASE` and then shipping directly to the userbase via rolling releases strongly suggests the latter. **Why do we even have `DEBUG` builds?** Regardless I've done as requested so there shouldn't be an obstacle to merging.

This is however part of our wider problem with error handling. If we're dependent upon users to report `assert` failures then we've already lost. Code should always work correctly without assertions. We should instead actually be encouraging (or indeed requiring) their use to document preconditions. Everything else should be a `debugmsg` with sane recovery as opposed to continuing blindly onwards - for example non-existent ammo should prevent a reload not spawn an *"undefined-foo"* and then reload using that.

This PR demonstrates a chilling effect on future bug or performance fixes which we so desperately need to attract. Currently JSON changes gain prompt review whereas this PR has just lead to a (further) days worth of work for no tangible benefit.

It's frustrating in the extreme to profile and then construct unit tests to prove a huge (>10x) increase in performance and at the same time close a significant bug. Indeed given how little we expected that pointer indirection to affect things it's not unreasonable to propose that cache locality might actually improve more general performance by much more.

The chilling effect is that it's now best to either decline review comments *"No I don't want to do that"* or just stop writing such PR's altogether. Such PR's should be a priority and as much as possible should be done to merge them because if that's not the case (and what matters is the authors assessment of that) then it's unlikely that we'll receive many such submissions.

So, **why do we even have DEBUG builds?**

**Comment by mutability** [comment]
I think the main stumbling block with this PR is that you are trying to do 4 different things in the same PR. If you'd broken the NDEBUG / assert stuff into a separate PR then I suspect the fix would already have been applied. Can you do that and we can argue about assert in the separate PR? Fixing master is kinda important at this point.

**Comment by mugling** [comment]
I've expended a lot of time on the above, both today and previously, so the motivation isn't there for anything further. If such fixes aren't considered a priority then the chilling effect very much applies. The same thought arguably apply to unit tests - what is the actual value if we don't ever run them?

**Comment by mutability** [comment]
If you don't mind then, I can extract just the fix/optimization parts of your changes into a separate PR?

**Comment by mugling** [comment]
> If you don't mind then, I can extract just the fix/optimization parts of your changes into a separate PR?

That's a reasonable idea providing it actually leads to the code being merged so ensure you test it adequately.

**Comment by mugling** [comment]
> So, why do we even have DEBUG builds?

^ this does need answering though

**Comment by mutability** [comment]
> So, why do we even have DEBUG builds?

Because debug symbols and enabling the standard library debugging is invaluable for, well, debugging?

**Comment by mugling** [comment]
> Because debug symbols and enabling the standard library debugging is invaluable for, well, debugging?

Well we already have your PR for including debug symbols in release

**Comment by mutability** [comment]
I don't see much value in shipping debug symbols to end users, what would they do with them?

The standard library debug options are another kettle of fish: they are very usedful, but they also have a big performance impact.

**Comment by mugling** [comment]
We should have a development and a release build. If performance of the former is so poor as to be useless we need to fix that

**Comment by mutability** [comment]
>> and enabling the standard library debugging is invaluable for, well, debugging?

> Like say assert?

Like expensive asserts. If standard library debugging was cheaper, we'd always have it on.

Going to reiterate that I think the right thing here is to distinguish garden-variety asserts that should always be on (so that if users tickle an undiscovered bug in a release build, we can get some useful information from it - for example, exactly as happened with the `squares_closer_to` bug that I diagnosed starting only from an assert reported in the wild), from expensive asserts that are only turned on in debug builds.

**Comment by Coolthulhu** [comment]
> Code should always work correctly without assertions.

Of course. But "should" and "will" are incredibly far apart.
I'm not saying that the assertion change is wrong, it's just that I can't test if it is here. I'd need to rebuild the game in debug build (which takes ~1 hour), which on windows has abysmal performance. And I'll need some performance for #19426

> Such PR's should be a priority and as much as possible should be done to merge them because if that's not the case (and what matters is the authors assessment of that) then it's unlikely that we'll receive many such submissions.

We have multiple worse issues right now.
And most of them were caused by lenient standards. My lenient standards. Instead of saying "no, fix it. I'll hold it up", I said "OK, but fix it ASAP".

The issue has a giant log of messages. I'd need to read and understand most of them to get why are we changing the asserts into some new macro.
An issue totally unrelated to "Better handling of item templates", but just piggybacked on it. Despite explicit warnings that it will slow down the review.

I had enough of those rushed "must have now or else highway" PRs. It seems that the more "we must have it now" a PR is, the worse and longer lasting is the fallout from it.

**Comment by mutability** [comment]
I am having trouble reproducing your unique_ptr benchmark results.
How did you benchmark this?

I took a slightly modified version of the unit test (added a volatile to act as an optimization fence, just in case):

```
#include "catch/catch.hpp"

#include "item.h"
#include "item_factory.h"

#include <chrono>

volatile int sink;

TEST_CASE( "perf_test" ) {
    int n = 5000;

    std::vector<const itype *> res;
    const auto opts = item_controller->get_all_itype_ids();

    const auto begin = std::chrono::high_resolution_clock::now();

    res.reserve( opts.size() * n );
    for( int i = 0; i != n; ++i ) { 
        for( const auto &e : opts ) {
            res.push_back( item::find_type( e ) );
        }
        sink = res.size();
    }

    const auto finish = std::chrono::high_resolution_clock::now();

    std::cout << "Fetched " << res.size() << " entries in "
              << std::chrono::duration_cast<std::chrono::milliseconds>( finish - begin ).count() << "ms"
              << std::endl;
}
```

With 8464700 (unique_ptr)

```
Fetched 16435000 entries in 7304ms
```

With 59a85697ceb7e66e604e05e0084fdf93f70fb5dd (no unique_ptr)

```
Fetched 16435000 entries in 7504ms
```

(i.e. no unique_ptr is actually slightly slower, though it's in the noise)
Ubuntu 16.04
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
release build

**Comment by mugling** [comment]
The full test code was:
```
#include "catch/catch.hpp"

#include "item.h"
#include "item_factory.h"

#include <chrono>

TEST_CASE( "perf_test" ) {
    int n = 5000;

    std::vector<const itype *> res;
    std::vector<itype_id> opts;

    for( const itype *e : item_controller->all() ) {
        opts.push_back( e->get_id() );
    }

    const auto begin = std::chrono::high_resolution_clock::now();

    res.reserve( opts.size() * n );
    for( int i = 0; i != n; ++i ) { 
        for( const auto &e : opts ) {
            res.push_back( item::find_type( e ) );
        }
    }

    const auto finish = std::chrono::high_resolution_clock::now();

    std::cout << "Fetched " << res.size() << " entries in "
              << std::chrono::duration_cast<std::chrono::milliseconds>( finish - begin ).count() << "ms"
              << std::endl;
}
```

It may be implementation dependent - presumably based upon how a given version of platforms standard library chooses to allocate the memory.

**Comment by mugling** [comment]
That `volatile` probably does something you don't intend as your also 7x slower than my very old box

**Comment by mutability** [comment]
This is the std::map implementation, so it's actually faster than the benchmarks you quoted previously.

**Comment by mutability** [comment]
| hash | map | unordered_map |
| -- | -- | -- |
8464700 (unique_ptr) | 7411ms | 1506ms  | 
59a8569 (no unique_ptr) | 7191ms | 1513ms |

3% difference for `std::map` and no difference for `std::unordered_map`

Based on that I think I am going to go for a super-minimal bugfix PR

**Comment by mugling** [comment]
> Based on that I think I am going to go for a super-minimal bugfix PR

No, we need to work out why there is such a huge difference in the first instance. Did you use the **exact** test case I posted or your own? What compiler flags?

**Comment by mutability** [comment]
I used your testcase, changed the testcase name (so it didn't collide with my copy), and changed this:

```
    for( const itype *e : item_controller->all() ) {
        opts.push_back( e->get_id() );
    }
```

to this:

```
    for( auto &e : item_controller->get_all_itype_ids() ) {
        opts.push_back( e );
    }
```

so that it would compile against versions before this PR.
Standard release flags.

**Comment by mugling** [comment]
Try with that `get_id()` call

**Comment by mutability** [comment]
What, exactly?

**Comment by mugling** [comment]
Try the exact version I posted an hour ago that includes the call to `get_id()`.

**Comment by mugling** [comment]
I'm assuming your using this branch as a baseline and then reimplementing `std::unique_ptr`

**Comment by mugling** [comment]
Tangent: It may be that the same performance benefits are available via a custom allocator for itype

**Comment by mutability** [comment]
> I'm assuming your using this branch as a baseline and then reimplementing std::unique_ptr

No,  I am comparing the performance before and after your original PR that removed unique_ptr on performance grounds. See the git hashes above.

My minimal bugfix currently reintroduces unique_ptr and I still don't see a performance change..

**Comment by mugling** [comment]
> No, I am comparing the performance before and after your original PR that removed unique_ptr on performance grounds. See the git hashes above.

Something may have changed since.

> My minimal bugfix currently reintroduces unique_ptr and I still don't see a performance change..

It does exist for me though and may also exist on other platforms.

Are you definitely doing `e->get_id()` in that loop and storing the return in the vector - confirm it doesn't make a difference?

**Comment by mutability** [comment]
> Something may have changed since.

Since when? I am comparing the commit before your PR with the commit that merged your PR.

**Comment by mutability** [comment]
> Are you definitely doing e->get_id() in that loop and storing the return in the vector - confirm it doesn't make a difference?

I am not calling get_id() and that loop is in setup code outside the benchmarked region.

**Comment by mutability** [comment]
> It does exist for me though and may also exist on other platforms.

What is your platform, compiler, build flags, results if you run the same test against the same hashes above?

**Comment by mugling** [comment]
> I am not calling get_id() and that loop is in setup code outside the benchmarked region.

My bad on the above.

Ultimately I can demonstrate a significant performance difference on at least one platform and have a reasonably sensible explanation for why that might be which also suggests there could be further immeasurable benefits.

Short of demonstrating that `unique_ptr` is significantly faster (should be impossible) additional performance tests don't change much. In a similar manner we don't close bugs with 'I cant repeat on my platform'.

> If you don't mind then, I can extract just the fix/optimization parts of your changes into a separate PR?

This didn't include redoing all of the work. If you want to PR everything except NDEBUG that's more than agreeable, otherwise we can wait for another review cycle of this PR.

**Comment by mutability** [comment]
Tried with get_id(), no difference.

**Comment by mugling** [comment]
> Tried with get_id(), no difference.

It's my bad - the previous version of my test stashed id's not pointers so I misled you there.

The above holds true though - it's either this PR minus NDEBUG or wait for another cycle of review

**Comment by mutability** [comment]
>> If you don't mind then, I can extract just the fix/optimization parts of your changes into a separate PR?

> This didn't include redoing all of the work. If you want to PR everything except NDEBUG that's more than agreeable, otherwise we can wait for another review cycle of this PR.

Doing my due diligence on the changes I would end up pushing. The complexity of maintaining two maps and freezing one of them is only needed if we need to avoid unique_ptr. If we don't need to avoid unique_ptr then there is a simpler set of changes that fixes the underlying bug until this PR gets there eventually.

**Comment by mugling** [comment]
> Doing my due diligence on the changes I would end up pushing. The complexity of maintaining two maps and freezing one of them is only needed if we need to avoid unique_ptr. If we don't need to avoid unique_ptr then there is a simpler set of changes that fixes the underlying bug until this PR gets there eventually.

That's fine but I've proven a significant difference on at least one platform which is an adequate reason. It probably does relate to contiguous memory which is another advantage.

**Comment by mutability** [comment]
What is your platform and compiler?

**Comment by mugling** [comment]
FreeBSD (amd64). gcc 4.9, clang 3.4

**Comment by mutability** [comment]
Let me try building with 4.9 here and see if I can reproduce it.

**Comment by mugling** [comment]
I can reproduce it with both clang and gcc

**Comment by mugling** [comment]
Like I said though the original suggestion you made was that you PR without `NDEBUG`. The only other options are to:

1. Find a flaw in this PR
2. Demonstrate significant performance benefit of `std::unique_ptr` (presumably impossible)
3. Write more performant implementation on all platforms (custom allocator etc)

I'm going back to my original post and restating the chilling effect this all has on any attempts to provide fixes for bugs or performance.

**Comment by mutability** [comment]
Built with 4.9, no measurable difference, so I guess it is a FreeBSD-specific thing.

**Comment by mutability** [comment]
With respect, you made it pretty clear that you don't have much motivation to work on this PR further. The consequence of that is that it probably won't get merged for a while. I'm trying to get a small bugfix in so we don't have a build that has subtle bugs for an extended period.

**Comment by mugling** [comment]
Removing the `NDEBUG` change, confirming it works for you, and then submitting a PR would be sufficient for a merge

**Comment by mutability** [comment]
> Removing the NDEBUG change, confirming it works for you, and then submitting a PR would be sufficient for a merge

I will keep that in mind, thanks.

**Comment by mugling** [comment]
> Removing the NDEBUG change, confirming it works for you, and then submitting a PR would be sufficient for a merge
> 
> I will keep that in mind, thanks.

Sounds good. I'm presuming you already have done such changes locally and verified them already given your above results.

**Comment by mugling** [comment]
I've rebased this to everything prior to `NDEBUG`. Someone else confirming this works for them would be helpful so that this can close #19566

File: src/item_factory.cpp [hunk 3]
```diff
@@ -2275,14 +2293,36 @@ void item_group::debug_spawn()
...
+    for( const auto &e : m_runtimes ) {
+        res.push_back( e.second.get() );
+    }
+
+    return res;
+}
+
+/** Find all templates matching the UnaryPredicate function */
+std::vector<const itype *> Item_factory::find( const std::function<bool( const itype & )> &func ) {
+    assert( item_controller->frozen );
```
Comment (mutability) [inline src/item_factory.cpp]: This needs to move up into Item_factory::all()

**Comment by mutability** [comment]
Snap. Was 3/4 of the way through the same, but let's go with yours. I found one assert that needed to be moved (see above). Also a couple of places that could use map::emplace but those aren't a big deal.

File: src/item_factory.cpp [hunk 4]
```diff
@@ -952,20 +956,28 @@ void Item_factory::check_definitions() const
...
-    def.name_plural = string_format( "undefined-%s", id.c_str() );
-    def.description = string_format( "Missing item definition for %s.", id.c_str() );
+    itype *def = new itype();
+    def->id = id;
+    def->name = string_format( "undefined-%ss", id.c_str() );
+    def->name_plural = string_format( "undefined-%s", id.c_str() );
+    def->description = string_format( "Missing item definition for %s.", id.c_str() );
 
-    return &( m_templates[ id ] = def );
+    m_runtimes[ id ].reset( def );
```
Comment (mutability) [inline src/item_factory.cpp]: This could use emplace

File: src/item_factory.h [hunk 5]
```diff
@@ -209,7 +208,7 @@ class Item_factory
          * @param new_type The new item type, must not be null.
          */
         void add_item_type( const itype &def ) {
-            m_templates[ def.id ] = def;
+            m_runtimes[ def.id ].reset( new itype( def ) );
```
Comment (mutability) [inline src/item_factory.h]: This could also use emplace

Comment (mugling) [inline src/item_factory.h]: How so?

**Comment by mugling** [comment]
I've pushed that change to `assert` but left the `emplace` out. I can't get the syntax to work and I'd be surprised if they offered any measurable performance difference

**Comment by mugling** [comment]
Merge as per above review

**Comment by mutability** [comment]
Yeah, not too worried about the emplace, it just makes it a little clearer that you are inserting a new entry and passing ownership to a unique_ptr. there's no real difference in functionality.

```
m_templates.emplace( id, std::unique_ptr<itype>( def ) );

**Comment by mutability** [comment]
```release-cataclysm-tiles: src/item_factory.cpp:2301: std::vector<const itype*> Item_factory::all() const: Assertion `frozen` failed.```

Rebuilding with symbols now.

**Comment by mugling** [comment]
Not sure how that escaped, I'm going to compile also

**Comment by mutability** [comment]
```
#4  0x0000000000727150 in Item_factory::all (this=<optimised out>) at src/item_factory.cpp:2301
#5  0x00000000006ec788 in auto_pickup::create_rules (this=this@entry=0xf3e360 <get_auto_pickup()::single_instance>) at src/auto_pickup.cpp:532
#6  0x00000000006ed115 in auto_pickup::load (this=0xf3e360 <get_auto_pickup()::single_instance>, bCharacter=bCharacter@entry=false) at src/auto_pickup.cpp:628
#7  0x00000000006ed1e1 in auto_pickup::load_global (this=<optimised out>) at src/auto_pickup.cpp:608
#8  0x00000000006aacb5 in game::load_static_data (this=this@entry=0x9c46390) at src/game.cpp:282
#9  0x000000000041e61a in main (argc=<optimised out>, argv=<optimised out>) at src/main.cpp:440
```

**Comment by mugling** [comment]
Note also #19240 but I'm not sure if it's relevant

**Comment by mugling** [comment]
The comments in `game::load_static_data` are helpful - it looks like that call should be later

**Comment by mutability** [comment]
Can probably skip initializing the ruleset after loading global rules? They're meaningless until the world data is loaded at a later point anyway. I guess it only works because the rules get regenerated when the character-specific rules get loaded.

**Comment by mugling** [comment]
I was looking at moving that call elsewhere - the code comment say should only include static data but that code attempts a JSON load?

**Comment by mugling** [comment]
Probably in `game::setup` after `load_world_modfiles`?

**Comment by mutability** [comment]
comment at the very top of `load_static_data`:
```
// Load everything that will not depend on any mods
```
So it seems OK to load the global autopickup config since it's just text and doesn't directly depend on any sort of moddable data, but it doesn't make sense to actually match them up to items (in `create_rules()`) until the world is loaded.

Delaying the loading of global rules entirely is trickier since you can edit the global rules from the settings menu with no world loaded at all.

**Comment by mugling** [comment]
Yes but see also the comments below that
```
    // The content they load/initialize is hardcoded into the program.
    // Therefore they can be loaded here.
    // If this changes (if they load data from json), they have to
    // be moved to game::load_mod or game::load_core_data
```

**Comment by mugling** [comment]
Continued in #19618
