### PR TITLE
Fix radio towers not emitting

### LINKED ISSUE #42493: "Scan" function on radios does not work.
# Describe the bug

Using the "Scan" function on a standard radio results in only static.

# Steps To Reproduce

1. Spawn in a radio and compatible battery.
2. Activate the radio.
3. Activate the radio again and select "Scan"
4. Repeat and note that there is only static

# Expected behavior

Hear a garbled version of the appropriate snippet from radio.json so the player can then triangulate with a directional antenna.

# Versions and configuration

 - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4457-g92af4ff [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Rail Stations [No_Rail_Stations],
    Useful Helicopters [useful_helicopters]
]

 -->

# Additional context

Has been an issue since before 0.E but nobody else seems to have noticed.

### PR DESCRIPTION
**Pull request by LcsTen**
#### Summary

SUMMARY: Bugfixes "Fix radio towers not emitting"

#### Purpose of change

Fix radio towers not emitting, allowing to hear them when using the "Scan" function on radios. Fixes #42493.
Allow directional antenna to be used on a radio on the ground, rather than having to carry both.
Change radio tower messages to use the snippets from "radio_archive" rather than the two hardcoded ones.

#### Describe the solution

To check if a terrain is a radio tower or not, the overmap::place_radios checked for an equality: ``ter( pos_omt ) == "radio_tower"``. The problem is that no terrain have the id "radio_tower" anymore, they instead have id such as "radio_tower_1_north", etc. 
Because of this, no radio tower could emit, as the overmap::radios vector was always empty, and the radios naturally couldn't work.
I changed the check so it checks only the beginning of the string with ``is_ot_match( "radio_tower", ter( pos_omt ), ot_match_type::prefix )``.

#### Describe alternatives you've considered

I replaced the two hardcoded messages by random messages from "radio_archive" snippets. These snippets are actually used by computers. Maybe these snippets are out of place and we should create another radio-specific snippets?

#### Testing

1. Create a new world.
1. Reveal map.
1. Wish for a radio (off) and a light battery, and reload the radio.
1. Turn the radio on and Scan.
1. Make sure the radio emits a garbled version of one of the "radio_archive" snippets or emits a weather forecast.
 a. If it still results in static, please open the map and make sure there's a radio tower nearby. If there is indeed one, well, it means my fix doesn't work :|
1. Drop the radio and wish for a directional antenna.
1. Find direction using the antenna, note the displayed direction and make sure it indeed points to a radio tower.

Edit: Update from last commit

### CODE REVIEW

File: src/overmap.cpp [hunk 1]
```diff
@@ -4337,28 +4338,19 @@ void overmap::place_radios()
...
-                        break;
-                    case 1:
-                        radios.push_back( radio_tower( pos_sm, strength(),
-                                                       _( "Head West.  All survivors, head West.  Help is waiting." ) ) );
-                        break;
-                    case 2:
-                        radios.push_back( radio_tower( pos_sm, strength(), "", radio_type::WEATHER_RADIO ) );
-                        break;
+            // Since location have id such as "radio_tower_1_north", we must check the beginning of the id
+            if( string_starts_with( ter( pos_omt ).id().str(), "radio_tower" ) ) {
```
Comment (ZhilkinSerg) [inline src/overmap.cpp:4342]: Can you use `is_ot_match` here and below?

Comment (LcsTen) [reply src/overmap.cpp]: Of course, thank you for your feeback!

File: src/overmap.cpp [hunk 2]
```diff
@@ -4337,28 +4338,19 @@ void overmap::place_radios()
...
-                        break;
-                    case 1:
-                        radios.push_back( radio_tower( pos_sm, strength(),
-                                                       _( "Head West.  All survivors, head West.  Help is waiting." ) ) );
-                        break;
-                    case 2:
-                        radios.push_back( radio_tower( pos_sm, strength(), "", radio_type::WEATHER_RADIO ) );
-                        break;
+            // Since location have id such as "radio_tower_1_north", we must check the beginning of the id
+            if( is_ot_match( "radio_tower", ter( pos_omt ), ot_match_type::prefix ) ) {
```
Comment (Qrox) [inline src/overmap.cpp:4342]: Maybe we can use a flag here instead of checking a hardcoded id.

File: src/overmap.cpp [hunk 3]
```diff
@@ -4337,28 +4338,19 @@ void overmap::place_radios()
...
+                if( one_in( 3 ) ) {
+                    radios.push_back( radio_tower( pos_sm, strength(), "", radio_type::WEATHER_RADIO ) );
+                } else {
+                    message = SNIPPET.expand( SNIPPET.random_from_category( "radio_archive" )->translated() );
```
Comment (Qrox) [inline src/overmap.cpp:4346]:
```suggestion
                    message = SNIPPET.expand( SNIPPET.random_from_category( "radio_archive" ).value_or( translation() ).translated() );
```
To avoid accessing empty optional value.

File: src/overmap.cpp (hunk 2 above)
Comment (LcsTen) [reply src/overmap.cpp:4342]: I would like to, but the flags would be stored in ``overmap_special`` items, while in the overmap::place_radios I have only access to ``oter_id`` items. Is there any way to get the overmap_special from an oter_id?

Comment (Qrox) [reply src/overmap.cpp:4342]: `oter_id` points to `struct oter_t` which in turn points to `struct oter_type_t`, which is `overmap_terrain` in json. Maybe you can add the flag to that instead (the id of `overmap_terrain` is the id without suffix it seems, for example `radio_tower_1`)

Comment (LcsTen) [reply src/overmap.cpp:4342]: I don't know, the flags of ``struct oter_type_t`` are stored as a bitset, rather than as a set of strings like most other objects in the game. If I want to add a flag, it means I must add it both in ``enum class oter_flags`` and in ``static const std::map<std::string, oter_flags> oter_flags_map``. Would it be alright?

Comment (Qrox) [reply src/overmap.cpp:4342]: Well, that bitset actually having a mapping of flag strings to values is a sign of extendability to me. We can of course leave it for a later PR if things are too uncertain.

Comment (LcsTen) [reply src/overmap.cpp:4342]: I would prefer to have a confirmation. Thank for your feedback anyway!

**Comment by jbytheway** [comment]
It would be good if the random snippet was selected based on the radio tower's position so that it's consistent.  `SNIPPET.random_from_category` has an overload taking a seed to help with exactly this sort of use case.

**Comment by LcsTen** [comment]
I have trouble understanding what you mean, it's not consistent?
Do you mean the selected snippet isn't saved and is randomized on each load?

**Comment by jbytheway** [comment]
Ah, I see.  I was wrong.  It is indeed saved, so it's probably fine.  I misunderstood the code.
