### PR TITLE
Fix handling, text of giving npc's items

### LINKED ISSUE #37352: Follower won't wear an arm splint cause it's too cumbersome
# Describe the bug

Having a follower with a broken arm and a splint wear something else makes em take off their arm splint. and upon trying to give them the arm splint back they will refuse to wear it back.

# Expected behavior

I would expect the follower to refuse to wear something that I want them to use because it would be too cumbersome for them because of their arm being broken and currently in a splint.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-11545-ge497763 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Generic Guns [generic_guns],
    Alternative Map Key [alt_map_key],
    Cars to Wrecks [cars_to_wrecks],
    Disable Religious Texts [no_religious_Texts],
    No Explosive Zombies [No_Explosive_Zombies],
    Classes and Scenarios Mod [more_classes_scenarios],
    Safe Autodoc [safeautodoc],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

https://www.twitch.tv/videos/541066175

### LINKED ISSUE #37398: "Use this item" in NPC dialogue can lead to bugged armor removal
# Describe the bug

When trying to make NPC wear a piece of armor/clothing, it may result in removal of other piece(s) of armor/clothing even when they are on different layer(s).

# Steps To Reproduce

1. Load [save](https://drive.google.com/open?id=1YplTX7J1GxGrjHPokhhEgzzxE9uGi84c). Or create a follower and spawn kevlar vest, swat armor and backpack.
2. Try to make the follower (Soledad Marks in attached save, next to player character) wear all those 3 items via "talk -> use this item" dialogue.
3. Fail horribly:
* armor+vest, try adding backpack, she takes off the vest
* armor+backpack, try adding vest, she takes off the armor
* vest+backpack, try adding armor, she takes off *both* vest and backpack
4. Use "sort armor" window instead -> succeed.

# Expected behavior

Items actually being worn if they don't conflict with each other.

# Versions and configuration

- OS: Windows 7 x64
- Game Version: 0.D-11601-g30a5718 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix handling, text of giving npc's items"

#### Purpose of change
Fix #37398
Fix #37352
Giving an npc items to wear is bugged and will display unhelpful information,

#### Describe the solution
Added prompt before NPC's take off armor to equip what you give them.  NPC's had an unfinished and arbitrary max encumbrance for each body part that was already ignored by the sort armor screen and was confusing to the users so I removed it.  Refactored functions to display what is or is not being equipped by its place in the code and gave user better insight into what NPC is doing with given item.  Added check to prevent NPC removing needed splints.

### CODE REVIEW

File: src/npctalk.cpp [hunk 1]
```diff
@@ -3218,84 +3221,82 @@ std::string give_item_to( npc &p, bool allow_use, bool allow_carry )
...
+    bool taken = false;
+    std::string reason = _( "Nope." );
+    int our_ammo = p.ammo_count_for( p.weapon );
+    int new_ammo = p.ammo_count_for( given );
+    const double new_weapon_value = p.weapon_value( given, new_ammo );
+    const double cur_weapon_value = p.weapon_value( p.weapon, our_ammo );
+    add_msg( m_debug, "NPC evaluates own %s (%d ammo): %0.1f",
+             p.weapon.type->get_id(), our_ammo, cur_weapon_value );
+    add_msg( m_debug, "NPC evaluates your %s (%d ammo): %0.1f",
+             given.type->get_id(), new_ammo, new_weapon_value );
```
Comment (BevapDin) [inline src/npctalk.cpp]:
```suggestion
             given.typeId(), new_ammo, new_weapon_value );
```
Same for the user usage of `get_id()` above.

File: src/npctalk.cpp [hunk 2]
```diff
@@ -3218,84 +3221,82 @@ std::string give_item_to( npc &p, bool allow_use, bool allow_carry )
...
+        else if( !given.is_gun() && given.is_armor() ) {
+            //if it is impossible to wear return why
+            ret_val<bool> can_wear = p.can_wear( given, true );
+            if( !can_wear.success() ) {
+                reason = can_wear.str();
+            } else {
+                //if we can wear it with equip changes prompt first
+                can_wear = p.can_wear( given );
+                if( ( can_wear.success() ||
+                      query_yn( std::string( can_wear.c_str() ) += std::string(
```
Comment (BevapDin) [inline src/npctalk.cpp]:
```suggestion
                      query_yn( can_wear.str() + 
```
`ret_val::str` already returns a `std::string`, no need to reconstruct one via the C-string. And the other string can be added as C-String and does not need to be converted to a `std::string` first.

File: src/npctalk.cpp [hunk 3]
```diff
@@ -3218,84 +3221,82 @@ std::string give_item_to( npc &p, bool allow_use, bool allow_carry )
...
+                                    _( " Should I take something off?" ) ) ) )
+                    && p.wear_if_wanted( given, reason ) ) {
+                    taken = true;
+                } else {
+                    reason = can_wear.c_str();
```
Comment (BevapDin) [inline src/npctalk.cpp]:
```suggestion
                    reason = can_wear.str();
```

File: src/npctalk.cpp [hunk 4]
```diff
@@ -3218,84 +3221,82 @@ std::string give_item_to( npc &p, bool allow_use, bool allow_carry )
...
+                }
+            }
+        } else {
+            reason += _( "My current weapon is better than this." );
+            reason += "\n" + string_format( _( "(new weapon value: %.1f vs %.1f)." ), new_weapon_value,
```
Comment (BevapDin) [inline src/npctalk.cpp]: The two string literals should be one as it's probably better for translators.
```C++
reason += string_format( _( "My current ... \n(new weapon value: %.1f vs %.1f)." ), ... );
```

File: src/npctalk.cpp [hunk 5]
```diff
@@ -3218,84 +3221,82 @@ std::string give_item_to( npc &p, bool allow_use, bool allow_carry )
...
+                                            cur_weapon_value );
+        }
+    } else {//allow_use is false so try to carry instead
+        if( p.can_pickVolume( given ) &&
+            p.can_pickWeight( given ) ) {
```
Comment (BevapDin) [inline src/npctalk.cpp]:
```suggestion
        if( p.can_pickVolume( given ) && p.can_pickWeight( given ) ) {
```
Certainly this fits on one line.

File: src/npctalk.cpp [hunk 6]
```diff
@@ -3218,84 +3221,80 @@ std::string give_item_to( npc &p, bool allow_use, bool allow_carry )
...
+        else if( !given.is_gun() && given.is_armor() ) {
+            //if it is impossible to wear return why
+            ret_val<bool> can_wear = p.can_wear( given, true );
+            if( !can_wear.success() ) {
+                reason = can_wear.str();
+            } else {
+                //if we can wear it with equip changes prompt first
+                can_wear = p.can_wear( given );
+                if( ( can_wear.success() ||
+                      query_yn( _( can_wear.str() ) += _( " Should I take something off?" ) ) )
```
Comment (BevapDin) [inline src/npctalk.cpp]: `can_wear` is already translated.
```suggestion
                      query_yn( can_wear.str() + _( " Should I take something off?" ) ) )
```

File: src/npctalk.cpp [hunk 7]
```diff
@@ -3218,84 +3221,80 @@ std::string give_item_to( npc &p, bool allow_use, bool allow_carry )
...
+                    && p.wear_if_wanted( given, reason ) ) {
+                    taken = true;
+                } else {
+                    reason = can_wear.str();
+                }
+            }
+        } else {
+            reason += "" + string_format(
```
Comment (BevapDin) [inline src/npctalk.cpp]:
```suggestion
            reason += string_format(
```
