### PR TITLE
Move theoretical skill display into the skill info panel

### LINKED ISSUE #50731: Character Info Panel can't display all skills with knowledge levels
### Describe the bug

Have a bunch of skills with a high knowledge but low practical and you can't see the level of your skills in the character information window.

Related to new skill rust change I think #50176

### Steps To Reproduce

Debug mode assign all your skills to 10 then all to 0 and open the character info panel.

### Expected behavior

Either need a more concise way of displaying the practical/knowledge skills on one line or that panel needs to sub scroll.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0f8bd78 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by eltank**
#### Summary
Interface "Move theoretical skill display into the skill info panel"

#### Purpose of change

Fixes #50731
#50176 added extra "knowledge" rows to the skill list panel, which hides the bottom-most skills

#### Describe the solution

Move that information into the skill info panel, visible when the player selects the skill.

#### Describe alternatives you've considered

Also adding something like "Currently gaining bonus xp". Didn't really fit well and it seemed too meta-gamey.

Changing the highlight of rusty skills to only trigger when the loss is more than 25%.
Changing the highlight of rusty skills to only trigger when there is a level loss.
Using different colors for level loss and practice% loss.
Many possible tweaks here, couldn't decide. Hoping for some feedback.

#### Additional context

Before:

image

"social" and "vehicles" skills are gone

After:

image

### CODE REVIEW

**Comment by I-am-Erk** [comment]
This is reasonable.

It might be worth considering showing just the knowledge and practical levels in the skill list, and putting the progress percent of each into the skill display. Knowledge level is pretty relevant a lot of the time.

File: src/player_display.cpp [hunk 1]
```diff
@@ -875,9 +864,14 @@ static void draw_skills_info( const catacurses::window &w_info, unsigned int lin
     werase( w_info );
 
     if( selectedSkill ) {
+        const SkillLevel &level = get_avatar().get_skill_level_object( selectedSkill->ident() );
+        std::string info_text = selectedSkill->description();
+        if( level.isRusting() ) {
+            info_text = string_format( _( "%s\n\nTheoretical level: %d (%d%%)" ), info_text,
```
Comment (I-am-Erk) [inline src/player_display.cpp:870]:
```suggestion
            info_text = string_format( _( "%s\n\nKnowledge level: %d (%d%%)" ), info_text,
```
The theoretical term was dropped in favour of "knowledge".

**Comment by eltank** [comment]
> It might be worth considering showing just the knowledge and practical levels in the skill list, and putting the progress percent of each into the skill display. Knowledge level is pretty relevant a lot of the time.

I don't know about other folks but when I'm grinding skill levels I check the [practical] percentage very frequently, usually before and after crafting something, so it's nice to have it available directly in the `@` menu.

At least when reading the theoretical percentage gets printed after every chapter.

Hmm, I just found another skill display bug in the reading UI. Time for another PR.

**Comment by eltank** [comment]
@I-am-Erk Do you have any thought regarding the red highlight changes considered in "alternatives"?
A mid-game character will have pretty much all of their skills highlighted in red when they wake up in the morning. Maybe we should only highlight those with at least 25% loss or 1 level drop.

**Comment by I-am-Erk** [comment]
I spent some time thinking on the red highlight and also didn't have a good answer come to mind. I think maybe at this point just highlighting it red when knowledge is different from skill is enough, that tells people there is more to know with the skill.

Eventually we may want some line about how much of a learning bonus you're getting in the skill info, like "you are learning practical skills xx% more quickly due to your knowledge base."

I also use the xp percent often, but I think we're going to similarly want to refer to the knowledge level pretty often. You can leave it here for now and see how it shakes out in play.

**Comment by eltank** [comment]
This seems good to go as far as I can tell. Are we waiting for code review from @anothersimulacrum ?

**Comment by anothersimulacrum** [comment]
If anyone is, don't.

**Review by anothersimulacrum — APPROVED** [review]
But, while I'm here.
This is tricky because I think these are all things you'd want to see at a glance, but we'll try this out and it fixes a fairly painful bug.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/confused-with-new-learning-system/26876/4
