### PR TITLE
Fix Devices XP gained from lockpicking.

### LINKED ISSUE #45043: Lockpicking gives huge amounts of experience at high device level
# Describe the bug

Picking locks gives increasing amounts of experience depending on the devices level of the character.
At level 8 it takes around 12 locked bar doors to increase devices level.
At level 10 it takes only 7.
After level 14 or so you get a level each time you open a door.

# Steps To Reproduce
Find a prison.
Find a lockpick or hairpin, get devices level to 8 or higher.
Close, lock and pick open some bar doors.
Observe the devices level.

# Expected behavior

Expected devices level to increase by a very small amount or not at all.

# Versions and configuration

 - Game Version: 0.E-6779-gc3caa74
 - Mods loaded: dda

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary

SUMMARY: Bugfixes "Fix Devices XP gain scaling in the wrong direction with lockpicking"

#### Purpose of change
Fixes #45043 

Lockpicking was set to grant XP based on your devices skill ^ 2, and so reached insanely high levels when your devices skill increased. I suspect this was a typo of some kind.

#### Describe the solution
Rewrites lockpicking XP gains to be based mostly on the `lock_roll`, a randomly generated number that stands in for lock difficulty, plus a modifier based on your skill level, decreasing as you gain skill. The modifier is actually fairly small, mostly you get the same amount of XP and it's a smaller drop in the bucket as your level goes up.

You get a substantial boost to XP if you successfully pick the lock, but failed attempts still give a good amount.

#### Describe alternatives you've considered
There are infinite other ways to do this, this model seems OK to me though.

#### Testing
after fixing the divide by zero error...

at device 2, a failed attempt offered 4-6% of a skill level, and not quite double that for success.
at devices 8, each lock grants about 1% on a successful pick, and a bit less on a fail.

#### Additional context
We really need to make terrain/furniture definitions for locked furniture include a difficulty level dangit. The random lock_roll makes me IRRATIONALLY ANGRY (or at least mildly annoyed)

### CODE REVIEW

File: src/activity_actor.cpp [hunk 1]
```diff
@@ -1108,9 +1108,13 @@ void lockpick_activity_actor::finish( player_activity &act, Character &who )
 
     add_msg( m_debug, _( "Rolled %i. Mean_roll %g. Difficulty %i." ), pick_roll, mean_roll, lock_roll );
 
-    int xp_gain = 0;
+    // Your base skill XP gain is derived from the lock difficulty (which is currently random but shouldn't be).
+    int xp_gain = ( 3 * lock_roll );
```
Comment (Night-Pryanik) [inline src/activity_actor.cpp:1112]:
```suggestion
    int xp_gain = 3 * lock_roll;
```

**Comment by GGgatherer** [comment]
> at devices 8, each lock grants about 1% on a successful pick, and a bit less on a fail.
@I-am-Erk doesn't seem to work, my character has devices at 7 and gets 0 exp per picked lock. She's permanently at 1.7%. Should I make a bug report? Or are there some other factor at play that can result in no exp gained?

**Comment by I-am-Erk** [comment]
I'm not sure how focus works so it may have an impact.
