### PR TITLE
Fix NPCs not trying to wear their weapon if it has a shoulder strap.

### LINKED ISSUE #20540: Make NPC able to wear guns with shoulder strap
If gun has shoulder strap installed, then NPC must wear this gun when "% puts away the *gun"

And it would be good idea if he don't forget to wield it if needed ;)

### PR DESCRIPTION
**Pull request by nshcat**
This fixes #20540 . This seems to work fine with `npc::wield_better_weapon()`.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
Hardcoding the shoulder strap id here is not the proper way to fix it. It does not handle naturally wearable weapons such as bows.
`wear_item` already checks for wearability.

File: src/npc.cpp [hunk 1]
```diff
@@ -941,14 +941,23 @@ bool npc::wear_if_wanted( const item &it )
...
-            g->m.add_item_or_charges( pos(), remove_weapon() );
-        }
+		// If weapon has a shoulder strap, try to wear it.
+		if( weapon.gunmod_find( "shoulder_strap" ) != nullptr && wear_item( weapon, false ) ) {		
+			// Wearing the item was successful, remove weapon and post message.
+			add_msg_if_npc( m_info, _( "<npcname> wears the %s." ), weapon.tname().c_str() );
+			remove_weapon();
+			moves -= 15;
+		}
+		else { // Weapon cannot be worn or wearing was not successful. Store it in inventory if possible, otherwise drop it.
```
Comment (Coolthulhu) [inline src/npc.cpp]: Coding style: should be
```
} else {
```

**Comment by nshcat** [comment]
Thanks for the feedback. I both fixed the coding style mistake and removed the hardcoded shoulder strap condition.

File: src/npc.cpp [hunk 2]
```diff
@@ -941,14 +941,22 @@ bool npc::wear_if_wanted( const item &it )
...
+		} else { // Weapon cannot be worn or wearing was not successful. Store it in inventory if possible, otherwise drop it.
+			if ( volume_carried() + weapon.volume() <= volume_capacity() ) {
+				add_msg_if_npc( m_info, _( "<npcname> puts away the %s." ), weapon.tname().c_str() );
+				i_add( remove_weapon() );
+				moves -= 15;
+			} else { // No room for weapon, so we drop it
+				add_msg_if_npc( m_info, _( "<npcname> drops the %s." ), weapon.tname().c_str() );
+				g->m.add_item_or_charges( pos(), remove_weapon() );
+			}
+		}
```
Comment (Coolthulhu) [inline src/npc.cpp]: You have 3 separate cases here:
* Wear
* Stash
* Drop

The two latter cases shouldn't be wrapped in one `else`, but rather be on the same "level" as wear.
Like this:
```
if( wear ) {
...
} else if( stash ) {
...
} else {
...
}
```

File: src/npc.cpp [hunk 3]
```diff
@@ -941,14 +941,22 @@ bool npc::wear_if_wanted( const item &it )
...
-        } else { // No room for weapon, so we drop it
-            add_msg_if_npc( m_info, _( "<npcname> drops the %s." ), weapon.tname().c_str() );
-            g->m.add_item_or_charges( pos(), remove_weapon() );
-        }
+		// If weapon has a shoulder strap, try to wear it.
+		if( wear_item( weapon, false ) ) {		
+			// Wearing the item was successful, remove weapon and post message.
+			add_msg_if_npc( m_info, _( "<npcname> wears the %s." ), weapon.tname().c_str() );
+			remove_weapon();
+			moves -= 15;
```
Comment (codemime) [inline src/npc.cpp]: Please write `mod_moves( -15 )` instead. Even though there's plenty of assignments like this one, all of them are subjects for replacement.
