### PR TITLE
Fixed issue where ImGui windows display wrong when window is scaled

### LINKED ISSUE #72959: Window scaling causes misaligned screen popups (Off screen)
### Describe the bug

Menus that use the ImGui are off screen when scaling factor set to 2x.
- Keybindings
- Quit screen (Save, Abandon, etc)
- Debug enabling (Generate Report prompt, etc)

suspect #72937 

### Attach save file

N/A

### Steps to reproduce

1. Set to scaling factor to 2x
2. Use menu that utilizes imGui (Quit)

### Expected behavior

Menus are viewable

### Screenshots

Screenshot of Cataclysm at Apr 11, 2024 at 02_55_00

### Versions and configuration

- OS: MacOs
    - OS Version: Name: macOS; Version: 14.4.1; Build: 23E224; 
- Game Version: cdda-experimental-2024-04-11-0340 a573b71 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Tamable Wildlife [Tamable_Wildlife]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by katemonster33**
#### Summary
Bugfixes "fixes issue where all ImGui windows display wrong when the window scaling is not 1"

#### Purpose of change
Fixes: #72959 

#### Describe the solution
Had a similar issue with Android earlier. There is likely a more permanent solution within ImGui that involves how it behaves when rendering scaling is used, but this fix should work just fine.

#### Describe alternatives you've considered
Bug the ImGui devs to fix it and wait for a really really long time (probably)

#### Testing
Loaded CDDA, set scaling to 2x, make sure the keybindings screen shows properly and responds to mouse input properly.

### CODE REVIEW

File: src/third-party/imgui/imgui_impl_sdl2.cpp [hunk 1]
```diff
@@ -74,6 +74,7 @@
 
 #include "imgui.h"
 #include "imgui_impl_sdl2.h"
+float x_scale = 1.f, y_scale = 1.f;
```
Comment (ZhilkinSerg) [inline src/third-party/imgui/imgui_impl_sdl2.cpp:77]:
```suggestion
float x_scale = 1.f;
float y_scale = 1.f;
```
