### PR TITLE
Fixes 100% chances to trigger teleglow effects

### LINKED ISSUE #39894: Some teleglow effects show up for 100% chance
# Describe the bug

When teleglow duration > 4 hours, some effects like `effect_blind` and `effect_shakes` will be triggered  once every turn for 100% chance.

# Steps To Reproduce

1. Make a player and a flaming eye, make sure the monster can see the player.
2. Wait until the flaming eye "stare"-s at the player for at least 4 times (each give an 80-minute teleglow duration addon, so the total duration is above 4 hours)
3. You can see a new message "Your vision is filled with bright lights…" every second.

# Expected behavior

The chance to be blind or shaking shouldn't be 100%.

# Screenshots

image
After 4 "stare" the message became crasy.
# Versions and configuration

- OS: Win10 or any other OS
- Game Version: 0.E-1052-g43af505 or any version after 1_turns=1_seconds
- Graphics version: Either
- Ingame language: Any
- Mods loaded: dda and any other mods except Dark Skys Above 

# Additional context

This bug is caused by the change of the definition of 1_turns. In old versions the chance to be blind is `one_in( 12000 - to_turns<int>( dur ) )` which was at least 1/9600, but after 1_turns became 1_seconds but no changes happened here, the `chance` attribute has become at most -2400. Additionally, the `one_in` function is like this:
```
bool one_in( int chance )
{
    return ( chance <= 1 || rng( 0, chance - 1 ) == 0 );
} 
```
So a minus attribute will lead this chance to 100%. 

The same thing happens in `effect_shakes`'s situation.

### PR DESCRIPTION
**Pull request by RedShakespeare**
#### Summary

```SUMMARY: Bugfixes "Fixes 100% chances to trigger teleglow effects"```
#### Purpose of change

Fixes #39894.
#### Describe the solution

Change the outdated `1_turns` into `6_turns` and add "chance>=0" assertion to rng.cpp.

#### Describe alternatives you've considered

Adjust the `turns` definition.

#### Testing

Repeat the "Reproduce Steps" of #39894 and you'll see much less messages about "bright lights"

### CODE REVIEW

**Comment by Hirmuolio** [comment]
Would probably be better to use 6_seconds instead of 6_turns.

**Comment by RedShakespeare** [comment]
> Would probably be better to use 6_seconds instead of 6_turns.

Indeed. wwww

File: src/rng.cpp [hunk 1]
```diff
@@ -57,6 +57,10 @@ double rng_exponential( double min, double mean )
 
 bool one_in( int chance )
 {
+    if( chance < 0 ) {
+        debugmsg( "Invalid one_in: %d", chance );
```
Comment (KorGgenT) [inline src/rng.cpp:61]: i don't agree that this should change current behavior, i also think that this debug message will cause more toruble than it's worth.

File: src/player_hardcoded_effects.cpp [hunk 2]
```diff
@@ -713,10 +713,10 @@ void player::hardcoded_effects( effect &it )
         }
         if( dur > 4_hours ) {
             // 8 teleports
-            if( one_in( 10000 - to_turns<int>( dur ) ) && !has_effect( effect_valium ) ) {
+            if( one_in( 10000 - ( dur / 6_seconds ) ) && !has_effect( effect_valium ) ) {
```
Comment (KorGgenT) [inline src/player_hardcoded_effects.cpp:716]: I'd rather not have anything that's like "previous value / 6", rather changing the new value to make sense with 1 second turns. i even believe there is a `once_in( time_duration )` function somewhere.

Comment (RedShakespeare) [reply src/player_hardcoded_effects.cpp:716]: I guess maybe `one_in( 10000 - ( dur - 240_minutes ) / 4_turns )` can be a choice? The previous changes is only meant to keep consistency because I was not sure whether a brand new value is allowed or not.

Comment (KorGgenT) [reply src/player_hardcoded_effects.cpp:716]: `one_in( to_seconds<int>( 1000_minutes - dur ) )` seems the most like what it was originally.

Comment (RedShakespeare) [reply src/player_hardcoded_effects.cpp:716]: Ye...s, sorry I forgot about the judgment frequency.

File: src/rng.cpp (hunk 1 above)
Comment (RedShakespeare) [reply src/rng.cpp:61]: ( Well this is just an optional addon... Will revert it if you say so.

Comment (KorGgenT) [reply src/rng.cpp:61]: please do
