### PR TITLE
Drop menu weight and volume calculations fix

### LINKED ISSUE #41782: "d"rop and "D"rop window not updating weight and volume correctly
For some reason in the recent updates the drop window don't show the weight and volume correctly, though the "g"et and AIM do it right.

# Steps To Reproduce

Just press "d" or "D" and see the Volume always on 0 and the weight is only updated for the items worn.

# Expected behavior

It should update the weight and volume in the same way as "g"etting items or using AIM.

# Screenshots

Cataclysm drop

# Versions and configuration

I am using using the CDDA 0.E-b10798 with the mods:

DDA
Disable NPC needs
Stats through skills
Stats through kills
SpeedyDex

### PR DESCRIPTION
**Pull request by mqrause**
#### Summary

SUMMARY: Bugfixes "Drop menu properly calculates weight and volume"

#### Purpose of change

Fixes #41782 
Due to pockets being a thing, the calculations were bugged.

#### Describe the solution

Weight:
Since items with pockets get heavier when they're being filled, this solution subtracts the weight of items selected for dropping. There is an additional helpermethod for calculating the weight of (partially) selected stackable items.

Volume:
Same as weight, except that only top level items in worn or wielded pockets are counted. Also added a method to calculate the total capacity depending on the selected items.

#### Describe alternatives you've considered

None.

#### Testing

Put stuff in stuff (in stuff), selected it for dropping to see if it works.

#### Additional context

Depends on #41988  to work properly.
The weight calculation was also used for a ton of other things and might have caused some bugs there, too. Without things being selected for dropping, it probably wasn't a problem, though.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -2867,45 +2867,59 @@ units::mass Character::weight_carried_with_tweaks( const item_tweaks &tweaks ) c
...
+            }
             ret += i.weight();
         }
     }
 
     // Items in inventory
-    const inventory &i = tweaks.replace_inv ? tweaks.replace_inv->get() : inv;
-    ret += i.weight_without( without );
+    //const inventory &i = tweaks.replace_inv ? tweaks.replace_inv->get() : inv;
+    //ret += i.weight_without( without );
```
Comment (Night-Pryanik) [inline src/character.cpp:2883]: Remove these commented lines if you don't need them.
