### PR TITLE
Fix #30061 - Reuse of a fix location object after it has been deleted.

### LINKED ISSUE #29849: "Repeat until fully repaired, but don't reinforce" on clothing causes Seg Fault
**Describe the bug**  
Game crashes when attempting repeat repairs on army jacket on the ground (poor fit, filthy) with wooden needle.

**To Reproduce**  
Pickup wooden needle with thread (not wielded)
A (use item)
Select wooden needle
Repair What? Choose army jacket
Repeat until fully repaired, but don't reinforce
Crash

**Expected behavior**  
Item gets repaired w/o game crashing

**Versions and configuration(please complete the following information):**
 - OS: Win10
 - Game Version: 0.D-2107-gf1de98d
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, Aftershock

**Additional context**  
Issue occurs in my little base, where I've probably got 200+ items in one stack on the ground, which includes said army jacket.

```
CRASH LOG FILE: config/crash.log
VERSION: 0.D-2107-gf1de98d
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x560C75[cataclysm-tiles.exe+0x160C75]
    @0x561742[cataclysm-tiles.exe+0x161742]
    SMPEG_error+0x4B034@0xE43FA0[cataclysm-tiles.exe+0xA43FA0]
    _C_specific_handler+0x98@0x7FF996B58068[msvcrt.dll+0x28068]
    _chkstk+0x11F@0x7FF9989346AF[ntdll.dll+0xA46AF]
    RtlWalkFrameChain+0x14BF@0x7FF998894BEF[ntdll.dll+0x4BEF]
    KiUserExceptionDispatcher+0x2E@0x7FF99893341E[ntdll.dll+0xA341E]
    @0x7189D0[cataclysm-tiles.exe+0x3189D0]
    @0x4291FE[cataclysm-tiles.exe+0x291FE]
    @0x43588C[cataclysm-tiles.exe+0x3588C]
    @0xBA88A0[cataclysm-tiles.exe+0x7A88A0]
    @0x638FB4[cataclysm-tiles.exe+0x238FB4]
    @0x687513[cataclysm-tiles.exe+0x287513]
    IMG_LoadWEBP_RW+0x4F81E9@0x142DFF9[cataclysm-tiles.exe+0x102DFF9]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FF996497974[KERNEL32.DLL+0x17974]
    RtlUserThreadStart+0x21@0x7FF9988FA271[ntdll.dll+0x6A271]

```

### LINKED ISSUE #30061: Segfault while fixing clothes inside a vehicle
**Describe the bug**  
I got a segmentation fault error while fixing my clothes inside a vehicle.

**To Reproduce**  
1. Try to fix clothes inside the vehicle

**Expected behavior**  
The clothes fixing will continue as usual

**Screenshots**  
image

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-2318-g1323624
 - Graphics version: Tiles
 - Mods loaded: 
  "dda",  "aftershock","Tolerate_This",  "FIC_Weapons",  "realguns",  "growable-pots",  "ew_pack",
  "makeshift",  "More_Survival_Tools",  "nw_pack",  "modular_turrets",  "Salvaged_Robots",  "alt_map_key",  "hydroponics",  "MMA",  "more_locations",  "FujiStruct",  "Urban_Development",  "boats",  "deoxymod",  "blazemod",  "Tanks",  "DP_XOTTO_INDICATORS",  "more_classes_scenarios",  "no_npc_food"

**Additional context**  
Crash and Debug logs
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3127162/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3127163/debug.log)
Save
[Main World_copy.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3127172/Main.World_copy.zip)

### PR DESCRIPTION
**Pull request by neitsa**
#### Summary

```SUMMARY: Bugfixes "Fix #30061 - Reuse of a fix location object after it has been deleted."```

#### Purpose of change

* Fix #30061 
* Close #29849

* Bug explained in details [in this post](https://github.com/CleverRaven/Cataclysm-DDA/issues/30061#issuecomment-488252883).

#### Describe the solution

* Check if the item was deleted and prevent its re-use.
* Add a comment (`**warning**` ) telling developers that if the item is popped back, then it is automatically deleted.
* A bit of C++ `auto` around the bug location.

#### Describe alternatives you've considered

I can't think of anything simpler.

#### Additional context

Tested the fix multiple times with the provided save file in #30061 and the bug couldn't be triggered anymore.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -2343,23 +2343,26 @@ void activity_handlers::repair_item_finish( player_activity *act, player *p )
...
             attempt == repair_item_actor::AS_SUCCESS ||
             old_level != p->get_skill_level( actor->used_skill );
 
-        const bool need_input =
+        const auto need_input =
             repeat == REPEAT_ONCE ||
-            ( repeat == REPEAT_EVENT && event_happened ) ||
-            ( repeat == REPEAT_FULL && fix->damage() <= 0 );
+            repeat == REPEAT_EVENT && event_happened ||
+            repeat == REPEAT_FULL && ( cannot_continue_repair || fix_location->damage() <= 0 );
```
Comment (ifreund) [inline src/activity_handlers.cpp]: Do need the parentheses here, since we have all the warnings enabled

Comment (neitsa) [reply src/activity_handlers.cpp]: Thanks ifreund! Fixed in next commit. I dumbly followed my IDE which was saying the parentheses were redundant...

**Comment by neitsa** [comment]
Also close #29849.

File: src/activity_handlers.cpp (hunk 1 above)
Comment (ifreund) [reply src/activity_handlers.cpp]: They are in this case cause of order of operations, but we trigger warnings cause people often write ```x || y && z``` intending to evaluate ```( x || y ) && z``` under the assumption that `||` and `&&` have the same precedence, while `&&` really has the higher precedence.

File: src/activity_handlers.cpp [hunk 2]
```diff
@@ -2320,11 +2320,11 @@ void activity_handlers::repair_item_finish( player_activity *act, player *p )
 
     // Valid Repeat choice and target, attempt repair.
     if( repeat != REPEAT_INIT && act->targets.size() >= 2 ) {
-        item_location &fix = act->targets[1];
+        auto &fix_location = act->targets[1];
```
Comment (kevingranade) [inline src/activity_handlers.cpp]: Please don't replace types with auto, I find that over time it makes the code harder to understand.
Unless you're replacing an obvious but unreadable type signature (e.g. iterators or function signatures) or explicitly using auto to make code generic, avoid auto.

Comment (neitsa) [reply src/activity_handlers.cpp]: Understood! Fixed in next commit. Thank you for your review.
