### PR TITLE
Unseal containers of components used in crafting

### LINKED ISSUE #43446: Crafting with sealed ingredients won't unseal the container
# Describe the bug

When crafting items with items in the sealed containers like cans, glass jars, the container would remain sealed.

# Steps To Reproduce

1. Spawn a medium tin can of condensed milk.
2. Craft reconstituted milk with it.
3. The reconstituted milk crafted with the condensed milk inside the can, but the tin can remained sealed.

# Expected behavior

Crafting items should also open the sealed containers, just like the way the character consumes the items inside of it.

# Screenshots

Here is an example of this issue; 2 units of condensed milk have already been used in crafting, but the can remains sealed.
image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-5650-g379a306 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

SUMMARY: Bugfixes "Unseals containers of components used in crafting"

#### Purpose of change

Fixes #43446 

#### Describe the solution

Unseals the pocket holding the crafting component.

#### Describe alternatives you've considered

Originally was using a handler to unseal up the parent chain, but feedback from @Qrox convinced me that would be unnecessary and ineffective.

#### Testing
Ran the test program: passed.

Spawned in some bread, jam, and peanut butter. Both containers indicated sealed. Placed the jam on a shelf and kept the PB in inventory. Crafted a PB&J sandwich. Containers of Jam and PB now both displayed as unsealed with some contents used.

Tested with canned salmon and bread to make a meat sandwich. The can is left empty. No problems found.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -8724,11 +8725,17 @@ bool item::use_charges( const itype_id &what, int &qty, std::list<item> &used,
         } else if( e->count_by_charges() ) {
             if( e->typeId() == what ) {
 
+                // Unseal the pocket and parent pockets.
+                if( parent != nullptr ) {
+                    map_cursor mc( pos );
+                    avatar &player = get_avatar();
+                    item_location container( mc, parent );
```
Comment (Qrox) [inline src/item.cpp:8732]: I think this assumes that parent is the outermost container on the map. Is that the case here?

File: src/item.cpp [hunk 2]
```diff
@@ -8724,11 +8725,17 @@ bool item::use_charges( const itype_id &what, int &qty, std::list<item> &used,
...
+                    handle_contents_changed_helper handler( player, item_location( container, e ) );
+                    handler.handle();
```
Comment (Qrox) [inline src/item.cpp:8734]: Calling `handle` may remove the content or container, but the content item `e` still need to be accessed later.

File: src/item.cpp (hunk 1 above)
Comment (RoyBerube) [reply src/item.cpp:8732]: No guarantee of that. Was having a similar thought this morning. So yeah, this is flawed.

File: src/item.cpp (hunk 2 above)
Comment (RoyBerube) [reply src/item.cpp:8734]: Very true. Will need to reconsider how to approach this.

File: src/item.cpp (hunk 1 above)
Comment (RoyBerube) [reply src/item.cpp:8732]: Did some more testing and it does not appear that the `item_location` created with the `map_cursor` is a problem. Put some sealed jars of peanut butter in a sling pack, put the sling pack inside a backpack, and put it on a counter. The container was unsealed after making a sandwich with the PB.

I'm not aware of a better way to create an `item_location` for items that may or may not be in inventory, and this appears to be working fine. I see no reason to change it.

File: src/item.cpp (hunk 2 above)
Comment (Qrox) [reply src/item.cpp:8734]: The handler may remove the item (or its container) if it is spillable. What happens if you craft with for example a tin can of broth in your inventory?

Comment (RoyBerube) [reply src/item.cpp:8734]: Did some tests with a bucket of clean water used to craft sweet water. 

Water bucket wielded - works as expected, and water is kept in the bucket with no prompt to spill it.

In backpack using 'w' to sheath the bucket, which certainly looks like a bug in itself. Bucket of water prompts for a container to spill it into, and then the sweet water prompts for a destination container. No debugmsg or problems encountered.

Comment (Qrox) [reply src/item.cpp:8734]: I think it's because `container` is a map item location, so when the handler handles `e`, it thinks the container of `e` is on the map and so `e` does not need handling. Then it simply unseals `parent`, and since `container` is a map location, it decides that `parent` does not have any further parents and returns. `Character::consume_items` then calls `empty_buckets`, which is where the containers are actually handled. The net effect is that calling `handle()` here is only equivalent to calling `unseal` on the parent's pocket that contains `e`.

Comment (RoyBerube) [reply src/item.cpp:8734]: So by that description all that needs to be done is to unseal the pocket. Which greatly simplifies things.

File: src/item.cpp [hunk 3]
```diff
@@ -8724,11 +8725,12 @@ bool item::use_charges( const itype_id &what, int &qty, std::list<item> &used,
...
 
+                if( parent != nullptr ) {
+                    parent->contained_where( *e )->unseal();
+                }
+
                 // if can supply excess charges split required off leaving remainder in-situ
                 item obj = e->split( qty );
-                if( parent ) {
-                    parent->on_contents_changed();
-                }
```
Comment (Qrox) [inline src/item.cpp:8731]: This does different things from `item_pocket::on_contents_changed` (such as resetting encumberance cache), and shouldn't be removed.

Also, please move the `unseal` call down here and change it to `parent->contained_where( *e )->on_contents_changed();` for consistency with the other unsealing code.

Comment (RoyBerube) [reply src/item.cpp:8731]: Done.
