### PR TITLE
Bug fix rotten food canned turns fresh

### LINKED ISSUE #26186: Vacuum Sealer makes rotten things fresh
**Describe the bug**  
Using the recipee to make vacuum fruit slices and using rotten fruit as ingredient causes the end product to become a fresh nonrotten product that you can safely eat.

**To Reproduce**  
1. Obtain Vacuum sealer, ingredients for the vacuum products and the rotten fruit
2. craft Vacuum fruit slices
3. activate the vacuumed fruit slices to notice how it is fresh now.

**Expected behavior**  
It should come out as rotten. sucking the air out of things doesnt just removes it from being rotten  

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version O.C-33196-g90d0a9b  (close to most current version in short) 
 - Graphics version does not matter.
 - Mods loaded Statsthroughskills, manual bionic installation, safe autodoc, no fungal mon, boats, folding parts pack, vehicle additions pack, tanks and other vehicles, Fuji's more buildings. more locations, Mutant NPCs, Hair aka rainbow, npc traits, alternative map key, extended realistic guns, more survival tools, medieval and historic content, makeshift items mod, filthy clothing, disable npc needs 

**Additional context**  
This issue would probably affect the vacuum recipes of meat, veggy and fish aswell, but i only tested with rotten fruit.

### PR DESCRIPTION
**Pull request by lancewf**
screen shot 2018-11-06 at 6 46 50 am

 ) with text describing your PR.
-->

#### Summary

SUMMARY: Bugfixes "Rotten food canned from crafting turns food fresh"

#### Purpose of change

Fixes #26186 - This fixes the problem when rotten food turning fresh when canning or jarring of food.

#### Describe the solution

The solution was to see if the crafted items were containers that contained items that spoil. Then set the rot values on these contained items.

#### Describe alternatives you've considered

I considered adding rot values to the container that are preserving food. This kind of makes sense because preserved food does not last forever. If this change was made the rot value of the components when crafting could be transferred to the preserving container. This ended up being a lot of work and did not work well with the current code base.

#### Additional context

This fix is going to make the feature of having a warning if the player is going to be using rotten food in crafting more important. 
https://github.com/CleverRaven/Cataclysm-DDA/issues/22129

This fixes the canning, dehydrating, soup jaring/canning, pickling, and smoking of food. 

The changes from PR #26554 with these changes will fix the rotten to fresh problem with vacuum-packing food.

### CODE REVIEW

File: src/crafting.cpp [hunk 1]
```diff
@@ -719,7 +719,16 @@ void player::complete_craft()
 
         if( newit.goes_bad() ) {
             newit.set_relative_rot( max_relative_rot );
+        } else {
+            if (newit.is_container()) {
```
Comment (ZhilkinSerg) [inline src/crafting.cpp]:
```suggestion
            if( newit.is_container() ) {
```
