### PR TITLE
Adapt to new definition of coord_to_angle

### LINKED ISSUE #26976: Compile error in ranged.cpp
**Describe the bug**  
Error when compiling on 64bit Linux. 

**To Reproduce**  
Git pull current experimental. Attempt to build release version. 

**Expected behavior**  
Compiles. 

**Versions and configuration(please complete the following information):**
 - OS: Arch Linux 64bit
 - Game Version: commit 4957555ea56606cece16765f7c2ca7904283ff56 

**Additional context**  
src/ranged.cpp: In lambda function:
src/ranged.cpp:1077:40: error: ‘class map’ has no member named ‘coord_to_angle’
         const int phi = std::abs( g->m.coord_to_angle( pc.pos().x, pc.pos().y, dst.x, dst.y ) -
                                        ^~~~~~~~~~~~~~
src/ranged.cpp:1078:40: error: ‘class map’ has no member named ‘coord_to_angle’
                                   g->m.coord_to_angle( pc.pos().x, pc.pos().y, recoil_pos.x, recoil_pos.y ) ) % 360;
                                        ^~~~~~~~~~~~~~
make: *** [Makefile:813: obj/tiles/ranged.o] Error 1
make: *** Waiting for unfinished jobs....

### PR DESCRIPTION
**Pull request by kevingranade**
Cross--pr conflict resolution between #26881 and #26959

#### Summary
```SUMMARY: none```  
Simple bugfix.
Fixes #26976

#### Additional Context
Submitted via website on a phone.

### CODE REVIEW

File: src/ranged.cpp [hunk 1]
```diff
@@ -1074,9 +1074,9 @@ std::vector<tripoint> target_handler::target_ui( player &pc, target_mode mode,
     auto recalc_recoil = [&recoil_pc, &recoil_pos, &pc]( tripoint & dst ) {
         static const double recoil_per_deg = MAX_RECOIL / 180;
 
-        const int phi = std::abs( g->m.coord_to_angle( pc.pos().x, pc.pos().y, dst.x, dst.y ) -
-                                  g->m.coord_to_angle( pc.pos().x, pc.pos().y, recoil_pos.x, recoil_pos.y ) ) % 360;
-        const double angle = phi > 180 ? 360 - phi : phi;
+        const double phi = std::abs( coord_to_angle( pc.pos(), dst ) -
+                                     coord_to_angle( pc.pos(), recoil_pos ) ) % 360.0;
```
Comment (ZhilkinSerg) [inline src/ranged.cpp]: `%` doesn't work on doubles, we need to use `std::fmod` here:

```CPP
        const double phi = std::fmod( std::abs( coord_to_angle( pc.pos(), dst ) -
                                                coord_to_angle( pc.pos(), recoil_pos ) ),
                                      360.0 );
```

**Comment by jbytheway** [comment]
This is complex enough that I'd argue it warrants creating an `angle_at_corner(tripoint, tripoint, tripoint)` function in `line.h`.
(But don't worry about that now; getting the build passing again is more urgent).
