### PR TITLE
Weather Tweaks - new light drizzle category and fix wind

### LINKED ISSUE #35535: Weather/Wind doesn't change.
# Describe the bug
Weather has not changed for me, in 180 days (I have to manually fill my vehicle with dirty swamp water every so often). Its always Clear, 

# Steps To Reproduce

There's not much I can say about how to reproduce, other then just play?

# Expected behavior
I would expect weather to be changing.

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9369-ge612365 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    More City Locations [cityside],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks],
    Prevent Zombie Revivication [no_reviving_zombies],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Simplified Nutrition [novitamins],
    No Fungal Monsters [No_Fungi]
]

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Weather Tweaks - new light drizzle category and fix wind"```

#### Purpose of change
Fixes #35535 

#### Describe the solution
After #34515 Occurences of rain and drizzle were significantly reduced, correctly.
This however opened up the space for very very light precipitation, which was the type of precipitation that occurs most irl in that geographic region, but there was no applicable category for it, as rain and drizzle had in-game effects that would've been too much for that light precipitation.

Also, due to that PRs fix to air pressure values generation, the windspeed calculations which were previously tailored to fit the previous pressure calculation, then became unvariable and stagnant.

So what ive done is added a new weather type - LIGHT_DRIZZLE, this has barely any wet effects or rain accumulation ( for funnel purposes ) etc, but is more common than drizzle or rain, this closely matches expectations of weather , based on real-life, without skewing their actual in-game effects.

Also I discovered that at some point the rng for wind direction changing was changed to a non-static rng engine, so wind direction was not changing at all,  ive fixed that.

Also I've boosted the variability of wind back up again, this is a brute force approach of just amplifying it a bit, I spent a long time tailoring the wind algorithm to the previous pressure calculation, now that pressure is correct and realistic, eventually the wind algorithm will need a similar amount of time given to it , to correlate it to real-world numbers, but in the meantime, this at least fixes it remaining at 5mph the entire year.

#### Describe alternatives you've considered
N/A

#### Testing
Used the debug menu to output 2 years of weather data, and pored over the data.
debug changed weather to light drizzle an dobsserved its in-game effects( morale, funnels ) etc, and considered it a mostly flavour change with minimal effects, that at least gives the perception of changeable weather and light rain.

#### Additional context
Screenshot of data summary over 2 years, before this change.

screen02

You can see how, rain+drizzle is very rare compared to the total non-precip hours, you can see theres hardly any wind variation.

After this change - 

screen01

Rain and drizzle are mostly unchanged, but total hours of precipitation is increased, most of which comes from the new light drizzle category

and Wind is much more variable, whilst still retaining the average.

### CODE REVIEW

File: src/weather_gen.cpp [hunk 1]
```diff
@@ -225,7 +227,7 @@ weather_type weather_generator::get_weather_conditions( const w_point &w ) const
 int weather_generator::get_wind_direction( const season_type season, unsigned seed ) const
 {
     unsigned dirseed = seed;
-    cata_default_random_engine wind_dir_gen( dirseed );
+    static cata_default_random_engine wind_dir_gen( dirseed );
```
Comment (BevapDin) [inline src/weather_gen.cpp]: This means the seed is essentially on any subsequent call. But this may get called with a new seed when a new game is started or loaded.
```suggestion
    cata_default_random_engine wind_dir_gen( dirseed );
```

Comment (davidpwbrown) [reply src/weather_gen.cpp]: Without that static, then it gets passed the same seed, and therefore wind never changes direction.

**Comment by Kodiologist** [comment]
If you want trace rainfall, why not change Cataclysm to represent rainfall continuously instead of with discrete categories?

**Comment by davidpwbrown** [comment]
> If you want trace rainfall, why not change Cataclysm to represent rainfall continuously instead of with discrete categories?

That'd be something to aim for in the future sure.

File: src/weather_gen.cpp (hunk 1 above)
Comment (BevapDin) [reply src/weather_gen.cpp]: I see what you mean: each invocation (while playing the same game) uses the same seed, so the random engine is in the same state each time.

But my argument still stands: loading a second save will carry over the random engine created from within the first game and will thereby *ignore* the seed of the second game.

Btw. what's the point of copying the function parameter `seed` into a local variable and using that one? Why not use the function parameter directly?

Comment (davidpwbrown) [reply src/weather_gen.cpp]: Seeing as the initial wind PR that added that code, over a year ago,  was one of my first PRs, and I was even more inexperienced than I am now, I can only  guess as to the reasons behind not using the function parameter directly, and I think the answer is " I have no idea what I was doing" , so I will change that. I will also think of a solution that solves the random engine seed problem.

Comment (davidpwbrown) [reply src/weather_gen.cpp]: Is it suitable to use the time_since_epoch based seed for the random engine? this was originally the case when I first added wind direction, then I passed the game seed down to it in a subsequent PR, for reasons I cannot remember.
