### PR TITLE
Prevent double decrement of comestibles with iuse functions.

### LINKED ISSUE #29428: Consumable items with an iuse are consumed twice per use.
**Describe the bug**  
If you consume any consumable with an iuse attached, mostly medications, it will consume two doses of it.
Examples: eyedrops, saline solution, quickclot, thorazine, codeine, pot brownies.

**To Reproduce**  
1. Spawn a player with some medicinal items.
2. Consume a medicinal item.
3. Two charges are consumed.

**Expected behavior**  
One charge should be consumed.

**Additional context**  
Traced the code involved:
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f245f880e50eb15f7e0207a15c92bfcf766a27d/src/player.cpp#L7415
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f245f880e50eb15f7e0207a15c92bfcf766a27d/src/player.cpp#L7419
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f245f880e50eb15f7e0207a15c92bfcf766a27d/src/player.cpp#L7378
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f245f880e50eb15f7e0207a15c92bfcf766a27d/src/player.cpp#L7399
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f245f880e50eb15f7e0207a15c92bfcf766a27d/src/player.cpp#L7341
Here invoke returns charges_to_consume(), normally one.
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f245f880e50eb15f7e0207a15c92bfcf766a27d/src/player.cpp#L7364
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f245f880e50eb15f7e0207a15c92bfcf766a27d/src/player.cpp#L7372
https://github.com/CleverRaven/Cataclysm-DDA/blob/4c5dace88492cce74e5a39442d430dcb2093a19a/src/consumption.cpp#L904
https://github.com/CleverRaven/Cataclysm-DDA/blob/4c5dace88492cce74e5a39442d430dcb2093a19a/src/consumption.cpp#L1074
https://github.com/CleverRaven/Cataclysm-DDA/blob/4c5dace88492cce74e5a39442d430dcb2093a19a/src/stomach.cpp#L192
Charges are decremented first here.
https://github.com/CleverRaven/Cataclysm-DDA/blob/4c5dace88492cce74e5a39442d430dcb2093a19a/src/stomach.cpp#L219
Then after returning up the stack to player::consume_meds() it's decremented again here.
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f245f880e50eb15f7e0207a15c92bfcf766a27d/src/player.cpp#L7374

This was discovered because this assertion failed in an iuse test:
https://github.com/CleverRaven/Cataclysm-DDA/blob/7f245f880e50eb15f7e0207a15c92bfcf766a27d/tests/iuse_test.cpp#L38

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
```SUMMARY: None```

#### Purpose of change
Fixes #29428 
Fixes double-counting of comestibles with an iuse.

#### Describe the solution
Moved decrement out of stomach::ingest and player::consume_effect into callers.

#### Additional context
Was the source of the failing eyedropper test.

### CODE REVIEW

File: src/consumption.cpp [hunk 1]
```diff
@@ -638,19 +638,24 @@ bool player::eat( item &food, bool force )
                                  units::to_milliliter( stomach.contains() ) ) > units::to_milliliter(
                                 stomach.capacity() );
     const bool saprophage = has_trait( trait_id( "SAPROPHAGE" ) );
+    bool eaten = true;
```
Comment (ZhilkinSerg) [inline src/consumption.cpp]: `consume_effects( food )` is called all paths of the if-else block, so you can just put it at the end of the block:

```CPP
    if( !consume_effects( food ) ) {
        return false;
    }
```

**Comment by pjf** [comment]
Reporting in that I've merged this locally and can confirm it fixes the double-consume for me. (Tested with makeshift bandages.)

File: src/consumption.cpp (hunk 1 above)
Comment (kevingranade) [reply src/consumption.cpp]: Aha, good point.
