### PR TITLE
Fix bug with crafting from ground on NOITEM tile

### LINKED ISSUE #29749: Crafting on open window leads to error (and might yields duplicate items)
**Describe the bug**  
When the character stands on an open window and start crafting, an “item location does not point to valid item” error occurs. The game can be continued, though duplicate items will be dropped on adjecent tile occasionally.

**To Reproduce**  
1. Wield something in hand.
2. Open a window.
3. Stand on the open window.
4. Craft a screwdriver.
5. Select "Put it down and start working".
6. The game prompts error.
7. Press space bar to continue.
8. Duplicate items dropped on adjecent tiles, one of them may be “in progress screwdriver (102%). 

**Expected behavior**  
Put item on the adjecent title and start working, get only one finished item upon success, and no error occurs.

**Versions and configuration(please complete the following information):**
 - OS: Win10-64bit
 - Game Version: 0.D-1990-g73d8779
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs

**Additional context**  
The occasion of duplicate items does not always happen. I found it by crafting fire drill, but could not reproduce later. The screwdrivers do come in pairs all the time here. Besides above I have tried 2-by-sword and it has never replicated.

Here goes the debug.log:

07:08:38.160 ERROR : (error message will follow backtrace)
	(@0x5734ee[cataclysm-tiles.exe+0x1734ee]), 
	(@0x573aca[cataclysm-tiles.exe+0x173aca]), 
	(@0x574882[cataclysm-tiles.exe+0x174882]), 
	(IMG_LoadWEBP_RW+0x111115@0x1043ef5[cataclysm-tiles.exe+0xc43ef5]), 
	(@0x41d419[cataclysm-tiles.exe+0x1d419]), 
	(@0x43505c[cataclysm-tiles.exe+0x3505c]), 
	(@0xba5f0b[cataclysm-tiles.exe+0x7a5f0b]), 
	(@0x636ec4[cataclysm-tiles.exe+0x236ec4]), 
	(@0x685493[cataclysm-tiles.exe+0x285493]), 
	(IMG_LoadWEBP_RW+0x4f9719@0x142c4f9[cataclysm-tiles.exe+0x102c4f9]), 
	(@0x4013ed[cataclysm-tiles.exe+0x13ed]), 
	(@0x4014fb[cataclysm-tiles.exe+0x14fb]), 
	(BaseThreadInitThunk+0x14@0x7ffed0cd7974[KERNEL32.DLL+0x17974]), 
	(RtlUserThreadStart+0x21@0x7ffed199a271[ntdll.dll+0x6a271]), 
Backtrace emission took 0 seconds.
src/item_location.cpp:601 [void item_location::remove_item()] item location does not point to valid item

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
```SUMMARY Bugfixes "Fix bug with crafting from ground on NOITEM tile."```

#### Purpose of change
Fixes #29749.

#### Describe the solution
The item_location created when the `map::add_item_or_charges()` call overflowed was invalid, leading to an error message and duplication.

### CODE REVIEW

File: src/crafting.cpp [hunk 1]
```diff
@@ -578,9 +578,27 @@ static item *set_item_inventory( player &p, item &newit )
...
+/**
+ * Helper for @ref set_item_map_or_vehicle
+ * This is needed to still get a vaild item_location if overflow occurs
+ */
+static item_location set_item_map( const tripoint &loc, item &newit )
+{
+    // Includes loc
+    const std::vector<tripoint> tiles = closest_tripoints_first( 2, loc );
+    for( const tripoint &tile : tiles ) {
+        // Pass false to disallow overflow, null_item_reference indicats failure.
```
Comment (Night-Pryanik) [inline src/crafting.cpp]:
```suggestion
        // Pass false to disallow overflow, null_item_reference indicates failure.
```
