### PR TITLE
Raytraced sunlight

### LINKED ISSUE #28295: Natural ambient light does not penetrate through open air tiles into underground areas.
**Describe the bug**  
If you turn on all of the experimental z-level options and blast a crater in the ground, then descend into the crater, the environment is dark regardless of whether there is natural light present on the surface level.

**To Reproduce**  
1. Turn on experimental z-levels support and experimental z-level vision.
2. Spawn an ANFO charge and take cover.
3. Descend into the resulting crater during the day.
4. Observe there is no light in the crater.

**Expected behavior**  
Light from the surface penetrates into the crater.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
```SUMMARY: Features "Raytrace sunlight."```

#### Purpose of change
Fixes #28295
Adds a raytracing implementation for natural light sources to better handle dynamic environments.

#### Describe the solution
This does a single pass over the entire loaded area, descending from the top to the bottom level.
At each level, the remaining light from the next higher level is applied, incorporating any obstacles or differences in transparency.

#### Additional context
In addition to dynamically determining light, I plan on adjusting this to incorporate azimuth and altitude of the incoming light.  In other words, handle terrain casting shadows.

### CODE REVIEW

**Comment by AMurkin** [comment]
No optimizations for uniform overmaps?

**Comment by kevingranade** [comment]
Good point, some things I want to add:
Optimize for uniform map slices.
Optimize for levels with no light remaining.
Optimize for uniform submaps.

Haven't had a chance to profile yet, do I don't know which ones are needed.

File: src/lightmap.cpp [hunk 1]
```diff
@@ -186,6 +186,86 @@ void map::apply_character_light( player &p )
...
+        }
+        for( int y = 0, prev_y = offset.y; y < MAPSIZE_Y; y++, prev_y++ ) {
+            bool inbounds = true;
+            if( !x_inbounds || prev_y < 0 || prev_y >= MAPSIZE_Y ) {
+                inbounds = false;
+            }
+            four_quadrants prev_light( outside_light_level );
+            float prev_transparency = static_cast<float>( LIGHT_TRANSPARENCY_OPEN_AIR );
+            if( inbounds ) {
+                prev_light = prev_lm[ prev_x ][ prev_y ];
```
Comment (jbytheway) [inline src/lightmap.cpp]: This code can be reached in the case that `x` is not in-bounds, in which case you're accessing outside the array.

File: src/lightmap.cpp [hunk 2]
```diff
@@ -186,6 +186,86 @@ void map::apply_character_light( player &p )
...
+                    prev_transparency /= sight_penalty;
+                }
+            }
+            // The formula to apply transparency to the light rays doesn't handle full opacity,
+            // so handle that seperately.
+            if( prev_transparency > LIGHT_TRANSPARENCY_SOLID &&
+                !prev_floor_cache[x][y] && prev_light.max() > 0.0 ) {
+                lm[x][y].fill( prev_light.max() * LIGHT_TRANSPARENCY_OPEN_AIR / prev_transparency );
+            } else {
+                lm[x][y].fill( LIGHT_AMBIENT_MINIMAL );
```
Comment (jbytheway) [inline src/lightmap.cpp]: In the old code this ambient light level was different above and below ground.  You've made it the same everywhere.  Was that intentional?

File: src/lightmap.cpp [hunk 3]
```diff
@@ -186,6 +186,86 @@ void map::apply_character_light( player &p )
...
+        for( int x = 0; x < MAPSIZE_X; x++ ) {
+            for( int y = 0; y < MAPSIZE_Y; y++ ) {
+                lm[x][y].fill( outside_light_level );
+            }
+        }
+        return;
+    }
+
+    // Replace this with a calculated shift based on time of day and date.
+    // At first compress the angle such that it takes no more than one tile of shift per level.
```
Comment (jbytheway) [inline src/lightmap.cpp]: You're saying it must be at most one file of shift, but the offset is an integer, so that means the only options are -1, 0, and 1 in each coordinate.  Do you intend to support narrower angles than that?  It will make things more complicated.

File: src/lightmap.cpp (hunk 2 above)
Comment (kevingranade) [reply src/lightmap.cpp]: No, I'll double check what that was, I'm guessing I set everywhere to be the underground level.

File: src/lightmap.cpp (hunk 3 above)
Comment (kevingranade) [reply src/lightmap.cpp]: That is what it means, and yes it will be a little more complicated.

I have some functions @KorGgenT tracked down for me to calculate solar azimuth and elevation, which I'll need to compress to I think a 9deg arc to meet this prerequisite.
This angle is used to calculate a vector (math vector not data structure vector) indicating the direction and magnitude of the shadow.
Then this vector is used to calculate a line descending from max height to max depth (bresenham-wise). We compare the offset for a given layer to the one above it, and if there is a difference, that layer is shifted one tile relative to it's antecedent.

I'll have to evaluate if this is a meaningful thing to do (if you almost never see shadows, there's no point), if my plan is workable, and if it is likely to cause artifacts.

There's a whole other thing where if the angle is greater than 9deg, we instead cast in from one side of the map instead of from directly overhead, but I don't even want to think about that right now.

File: src/lightmap.cpp (hunk 1 above)
Comment (kevingranade) [reply src/lightmap.cpp]: I'm not clear how that happens.
If prev_x is not inbounds, x_inbounds == false, which means inbounds is set to false on line 244.

I'd love a cleaner way to state this, but I don't see it.
Maybe I should just bite the bullet and do the whole inbounds check on each loop iteration instead of being parsimonious with checks.

Comment (jbytheway) [reply src/lightmap.cpp]: You're right, I misread.  Never mind.

File: src/lightmap.cpp (hunk 3 above)
Comment (jbytheway) [reply src/lightmap.cpp]: Ah, OK, so the offset will potentially span multiple z-levels.  That makes more sense.  In terms of in-game impact, though, I think the sideways casting would be much more relevant, because most buildings are only one or two levels high.  This version is only really going to matter for holes in roofs and things like that.

File: src/lightmap.cpp (hunk 2 above)
Comment (jbytheway) [reply src/lightmap.cpp]: Indeed.  We should really have some underground lighting tests; don't think we have any of those at the moment.

File: src/lightmap.cpp (hunk 3 above)
Comment (kevingranade) [reply src/lightmap.cpp]: And holes in the ground, which was the initial impetus for it.
Now you can set ofvan ANFO charge (debug immortality recommended) and when you jump into the resulting hole it'll have sunlight streaming in.

**Comment by ZhilkinSerg** [comment]
It is not directly related, but there are some strange visibility issues for tiles which are empty, but have rubble on level above - I think we would like to implement gravity someday, so rubble would actually fall.

Z=0
image

Z=-1
image

**Comment by kevingranade** [comment]
The explosion code needs an overhaul to make these craters more consistent.

Oh man, I need to test blasting my way into a lab.

**Comment by kevingranade** [comment]
The visibility issue you mention is a result of the same thing @jbytheway pointed out, I'm setting that light level way too low.  This is actually working way better than I expected, I think this might be good to go for a first cut.

**Comment by kevingranade** [comment]
Shaun Grimm _2019-05-14_05-18-15_+0000
Shaun Grimm _2019-05-14_05-18-44_+0000
Shaun Grimm _2019-05-14_05-19-04_+0000
Shaun Grimm _2019-05-14_05-20-09_+0000
Shaun Grimm _2019-05-14_05-20-26_+0000

Better late than never?
Series of screen shots showing the aftermath of an ANFO charge detonation in the top of an office tower.

**Comment by Night-Pryanik** [comment]
изображение
