### PR TITLE
Terrain can emit fields

### LINKED ISSUE #45614: "EMITTER" flag doesn't work for terrain
# Describe the bug

Currently the "EMITTER" flag when applied to terrain does not emit any fields.

# Steps To Reproduce

1. Make a simple piece of terrain that has the emitter flag and a simple emissions
2. Spawn it in via the map editor
2. Wait
3. Nothing happens

# Expected behavior

From what I was told in the discord, while the "EMITTER" flag only mentions furniture, it works for fields, items, monsters, and terrains, and I figured as well as the structure of both furniture vs terrain in json is very similar, down to using the same list of flags for some things that "EMITTER" and "EMISSIONS": would work for it as well.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-7759-gf3a1933 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock]
]

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

SUMMARY: Infrastructure "Terrain can emit fields"

#### Purpose of change

Fixes #45614 

#### Describe the solution

- Implement emissions for terrain
- Remove use of EMITTER flag because it's useless
#### Testing

Give white walls sparks and shock fields
image

#### Additional context

I don't see what's the point of the EMITTER flag so terrains don't use it. Should we also remove it from furnitures since it's useless?

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -7296,10 +7308,14 @@ void map::actualize( const tripoint &grid )
         for( int y = 0; y < SEEY; y++ ) {
             const tripoint pnt = sm_to_ms_copy( grid ) + point( x, y );
             const point p( x, y );
-            const auto &furn = this->furn( pnt ).obj();
+            const furn_t &furn = this->furn( pnt ).obj();
+            const ter_t &terr = this->ter( pnt ).obj();
             if( furn.has_flag( "EMITTER" ) ) {
```
Comment (ZhilkinSerg) [inline src/map.cpp:7313]: Could this be changed to `!furn.emissions.empty()`?

Comment (Fris0uman) [reply src/map.cpp:7313]: Yes it can. Should we do it and get rid of this flag?

File: src/game.cpp [hunk 2]
```diff
@@ -1587,11 +1587,17 @@ bool game::do_turn()
     }
     if( calendar::once_every( 10_seconds ) ) {
         for( const tripoint &elem : m.get_furn_field_locations() ) {
-            const auto &furn = m.furn( elem ).obj();
+            const furn_t &furn = m.furn( elem ).obj();
```
Comment (anothersimulacrum) [inline src/game.cpp:1590]:
```suggestion
            const furn_t &furn = *m.furn( elem );
```

File: src/game.cpp [hunk 3]
```diff
@@ -1587,11 +1587,17 @@ bool game::do_turn()
...
             for( const emit_id &e : furn.emissions ) {
                 m.emit_field( elem, e );
             }
         }
+        for( const tripoint &elem : m.get_ter_field_locations() ) {
+            const ter_t &ter = m.ter( elem ).obj();
```
Comment (anothersimulacrum) [inline src/game.cpp:1596]:
```suggestion
            const ter_t &ter = *m.ter( elem );
```

File: src/map.cpp [hunk 4]
```diff
@@ -7296,10 +7308,14 @@ void map::actualize( const tripoint &grid )
         for( int y = 0; y < SEEY; y++ ) {
             const tripoint pnt = sm_to_ms_copy( grid ) + point( x, y );
             const point p( x, y );
-            const auto &furn = this->furn( pnt ).obj();
+            const furn_t &furn = this->furn( pnt ).obj();
+            const ter_t &terr = this->ter( pnt ).obj();
```
Comment (anothersimulacrum) [inline src/map.cpp:7312]:
```suggestion
            const furn_t &furn = *this->furn( pnt );
            const ter_t &terr = *this->ter( pnt );
```

File: src/map.cpp (hunk 1 above)
Comment (ZhilkinSerg) [reply src/map.cpp:7313]: Yeah, it looks redundant.

**Comment by ZhilkinSerg** [comment]
Can you remove `EMITTER` flag from furniture definitions, please?

```
\Cataclysm-DDA\data\json\furniture_and_terrain\furniture-alien.json (4 hits)
	Line 34:     "flags": [ "TRANSPARENT", "EMITTER" ],
	Line 55:     "flags": [ "TRANSPARENT", "EMITTER" ],
	Line 77:     "flags": [ "TRANSPARENT", "EMITTER" ],
	Line 92:     "flags": [ "TRANSPARENT", "EMITTER" ],
\Cataclysm-DDA\data\json\furniture_and_terrain\furniture-emitters.json (2 hits)
	Line 13:     "flags": [ "TRANSPARENT", "EMITTER" ],
	Line 29:     "flags": [ "TRANSPARENT", "EMITTER" ],
\Cataclysm-DDA\data\json\furniture_and_terrain\furniture-terrains.json (1 hit)
	Line 626:       "EMITTER"
\Cataclysm-DDA\data\mods\Aftershock\maps\terrain_groundxeno.json (3 hits)
	Line 80:     "flags": [ "NOITEM", "MINEABLE", "BASHABLE", "BLOCK_WIND", "EMITTER" ],
	Line 110:     "flags": [ "NOITEM", "MINEABLE", "BASHABLE", "BLOCK_WIND", "EMITTER" ],
	Line 136:     "flags": [ "TRANSPARENT", "FLAT", "ROUGH", "EMITTER" ],
\Cataclysm-DDA\data\mods\Magiclysm\furniture.json (1 hit)
	Line 175:     "flags": [ "TRANSPARENT", "EMITTER" ],
```

And maybe rework vehicle parts to not use `EMITTER` flag too (could be another PR)?

```
\Cataclysm-DDA\data\json\vehicleparts\vehicle_parts.json (2 hits)
	Line 1234:     "flags": [ "CTRL_ELECTRONIC", "ENABLED_DRAINS_EPOWER", "SPACE_HEATER", "EMITTER" ],
	Line 1257:     "flags": [ "CTRL_ELECTRONIC", "ENABLED_DRAINS_EPOWER", "COOLER", "EMITTER" ],
```
