### PR TITLE
Don't warn on sludge inside vehicles

### LINKED ISSUE #44422: Unnecessary dangerous terrain warning prompt within vehicle
# Describe the bug

Moving onto a tile in a vehicle with a dangerous terrain such as acid, sludge trail, etc prompts you to confirm whether or not you want to move onto the sludge trail, but there is no movement penalty or other negative effect (that I am aware of...) while in a vehicle.

# Steps To Reproduce

1. Drive car partially over sludge trial or acid.
2. Move around in the vehicle from a 'clean' tile to a dangerous and get the prompt.
3. Compare to moving from a clean to clean tile (barring other movement penalties from vehicle tiles) and see that the movement time was unaffected.

# Expected behavior

No prompt since it doesn't matter in this scenario.

# Screenshots

image

image

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6255-g5528ace [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Kills [stats_through_kills]
]

# Additional context
Results may vary depending on the users Dangerous terrain warning prompt setting.

### PR DESCRIPTION
**Pull request by irwiss**
#### Summary

SUMMARY: None

#### Purpose of change

Fixes #44422

#### Describe the solution

Doesn't look like fields have anything check for immunity in vehicles,
so just hard code the id and check against it.

#### Describe alternatives you've considered

Adding field json to describe immunity in vehicles seems overkill until there's
more fields like sludge the player is immune to while riding

#### Testing

Spawn some sludge, roll over sludge with a car so you still have empty tiles
and sludgey ones, moving inside the car in/over/out of sludge should no longer
produce warnings, stepping out of car into any field should warn

### CODE REVIEW

**Comment by Night-Pryanik** [comment]
Even if it's just one field at the moment, it's always better to add new flag to it and check for said flag instead of hardcoded id.

**Comment by irwiss** [comment]
I'll look into adding a field then

**Comment by irwiss** [comment]
Apparently the code to have json effects is already sorta-partly there,
some of the fields, including sludge, appear to be hardcoded into
map_field.cpp, but sorting those out into json would need a much
bigger pr

For now I've put a sludge effect in json for sludge - so it can be checked
against. The effect json also specifies immunity inside/in vehicles which
is checked around map_field.cpp:1755 - made similar checks for warning
so similar effects could get same warning treatment.

Also moved is_blind() check upwards - so blinded players don't get
warnings for fields as they already don't get warning for terrains.

File: src/game.cpp [hunk 1]
```diff
@@ -9282,48 +9282,80 @@ bool game::prompt_dangerous_tile( const tripoint &dest_loc ) const
...
-        const bool boardable = static_cast<bool>( m.veh_at( dest_loc ).part_with_feature( "BOARDABLE",
-                               true ) );
-        // HACK: Hack for now, later ledge should stop being a trap
-        // Note: in non-z-level mode, ledges obey different rules and so should be handled as regular traps
-        if( tr == tr_ledge && m.has_zlevels() ) {
-            if( !boardable ) {
-                harmful_stuff.emplace_back( tr.name() );
+        // if the field is dangerous but has no effects apparently this
+        // means effects are hardcoded in map_field.cpp so we should...
+        bool warn = e.second.field_effects().size() == 0; // ... warn if effects are empty
```
Comment (Night-Pryanik) [inline src/game.cpp:9304]:
```suggestion
        bool warn = e.second.field_effects().empty(); // ... warn if effects are empty
```
