### PR TITLE
Fix removing item from object which did not contain it

### LINKED ISSUE #32622: Tried removing item from object which did not contain it
# Describe the bug

Found an "improvised field repairs" manual in a `XX stowboard` on a crashed V-22 Osprey. The stowboard shows as having a capacity of '0.25/0.00'. Upon removing the item, the following error is thrown. The player receives a copy of the manual, but it still appears in the stowboard.

<details>
  <summary>Backtrace - click to expand</summary> 

```
10:33:50.434 ERROR : (error message will follow backtrace)
        ./cataclysm-tiles(_Z21debug_write_backtraceRSo+0x23) [0xa6b2da]
        ./cataclysm-tiles(_Z8DebugLog10DebugLevel10DebugClass+0x210) [0xa6acb5]
        ./cataclysm-tiles(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x55) [0xa6a5a8]
        ./cataclysm-tiles(_Z12realDebugmsgIJEEvPKcS1_S1_S1_DpOT_+0x59) [0x8f6a78]
        ./cataclysm-tiles(_ZN9visitableI14vehicle_cursorE11remove_itemER4item+0x7e) [0x11cc11e]
        ./cataclysm-tiles(_ZN13item_location4impl15item_on_vehicle11remove_itemEv+0x65) [0xc56cbb]
        ./cataclysm-tiles(_ZN13item_location11remove_itemEv+0x2b) [0xc550b3]
        ./cataclysm-tiles(_ZN6Pickup9do_pickupERSt6vectorI13item_locationSaIS1_EERS0_IiSaIiEEb+0x3ab) [0xff1a47]
        ./cataclysm-tiles(_Z23activity_on_turn_pickupv+0x36) [0x911b33]
        ./cataclysm-tiles(_ZNK13activity_type12call_do_turnEP15player_activityP6player+0x58) [0x91d5d8]
        ./cataclysm-tiles(_ZN15player_activity7do_turnER6player+0xac) [0x10422fa]
        ./cataclysm-tiles(_ZN4game16process_activityEv+0x72) [0xb0c9f8]
        ./cataclysm-tiles(_ZN4game7do_turnEv+0x5ce) [0xb0ba28]
        ./cataclysm-tiles(main+0x10b1) [0xd1193d]
        /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7f1a95929830]
        ./cataclysm-tiles(_start+0x29) [0x8cc959]

        Attempting to repeat stack trace using debug symbols...
        debug_write_backtrace(std::ostream&)
        ??:?
        DebugLog(DebugLevel, DebugClass)
        ??:?
        realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
        ??:?
        void realDebugmsg<>(char const*, char const*, char const*, char const*)
        ??:?
        visitable<vehicle_cursor>::remove_item(item&)
        ??:?
        item_location::impl::item_on_vehicle::remove_item()
        ??:?
        item_location::remove_item()
        ??:?
        Pickup::do_pickup(std::vector<item_location, std::allocator<item_location> >&, std::vector<int, std::allocator<int> >&, bool)
        ??:?
        activity_on_turn_pickup()
        ??:?
        activity_type::call_do_turn(player_activity*, player*) const
        ??:?
        player_activity::do_turn(player&)
        ??:?
        game::process_activity()
        ??:?
        game::do_turn()
        ??:?
        main
        ??:?
        __libc_start_main
        /build/glibc-Cl5G7W/glibc-2.23/csu/../csu/libc-start.c:325
        _start
        ??:?
Backtrace emission took 1 seconds.
src/visitable.cpp:504 [item visitable<vehicle_cursor>::remove_item(item &) [T = vehicle_cursor]] Tried removing item from object which did not contain it
```

</details>

# Steps To Reproduce

1. Load the attached save.
1. Examine the stowboard directly south of the survivor.
1. Get the manual and observe error thrown.

# Expected behavior

Ruined containers should not hold items. Items should not remain in ruined containers after they are taken.

# Versions and configuration

- OS: Ubuntu 16.04 LTS (xenial)
- Game Version: 0.D-5830-g6dc98365e5 [64-bit] (a4acee28f41f741baca796b20fef4bb3246a0df7 with MSX tilesets applied)
- Graphics Version: Tiles
- Mods loaded:
    - Dark Days Ahead [dda],
    -    Disable NPC Needs [no_npc_food],
    -    Filthy Clothing [filthy_morale],
    -    Alternative Map Key [alt_map_key],
    -    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    -    sees-player icon, +attitude [sees_player],
    -    Modular Turrets [modular_turrets],
    -    Salvaged Robots [Salvaged_Robots],
    -    Sleep Deprivation [sleepdeprivation],
    -    Bionic Slots [cbm_slots]

# Additional context

- [save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3433743/save.zip)

### PR DESCRIPTION
**Pull request by ipcyborg**
#### Summary
SUMMARY: Bugfixes "Tried removing item from object which did not contain it #32622"

#### Purpose of change
Fixes #32622

#### Describe the solution
First: add a check for broken part in `vehicle::add_item`.

Second: The error happens during item removing from vehicle part in:
`visitable<vehicle_cursor>::remove_items_with`
because there is a check here: "fail if this cargo part is broken".
Quick fix for savegame: change it to allow getting from broken vehicle part.

Logic for transferring item in the code:

1. Copy the original item.
2. Add the copy to some target location.
3. If (2) is ok, the remove the original item from source location.

It assumes that (3) will never fail to remove some item from its location. Which is sometimes false (like in the above example with broken part). 
So I have changed it to not failing in this specific case of broken part.

#### Describe alternatives you've considered
I see a problem here: `vehicle::damage_direct`. Actually this is the only place which checks if the part is broken after damage and drops all items to the ground.
Vehicle part may be damaged by using `vehicle::mod_hp`, `vehicle::set_hp`, etc. So, need to handle all these cases. 
Not sure If I can handle it correctly.

#### Additional context
Also added a test case for adding item to the broken part.

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -4591,9 +4591,14 @@ cata::optional<vehicle_stack::iterator> vehicle::add_item( int part, const item
     }
     // const int max_weight = ?! // TODO: weight limit, calculation per vpart & vehicle stats, not a hard user limit.
     // add creaking sounds and damage to overloaded vpart, outright break it past a certain point, or when hitting bumps etc
+    vehicle_part &p = parts[ part ];
+    if( p.is_broken() ) {
+        //debugmsg( "Tried to add item (%s) to a broken part (%s)", itm.tname(), p.name() );
```
Comment (BevapDin) [inline src/vehicle.cpp]: Please don't commit commented out code. Either it's useful code and should be run, so it should not be a comment at all. Or it is useless code that should not be there in the first place.

Comment (ipcyborg) [reply src/vehicle.cpp]: Fixed. 
Thanks!

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/experimental-crashes-tried-removing-item-from-object-which-did-not-contain-it/23447/1
