### PR TITLE
Fix null pointer deference

### LINKED ISSUE #15434: Segfault when reloading from ammo pouch
* Spawn chest rig, glock magazine and glock 19
* Reload glock magazine
* Put glock magazine in chest rig
* Wield glock 19 and reload it

### LINKED ISSUE #15450: Reloading M4 with empty STANAG mag crashes game
Version is ge27b38d. Windows tiles build 4425. To reproduce, start as an evacuee military recruit, put last 3 points in strength, start game, open inventory, select M4, attempt to reload.

Multiple players in IRC reported same issue. Stack trace was requested in IRC. Not sure if this is that, but save me stackoverflow:

ntoskrnl.exe+0x75daa
ntoskrnl.exe+0x2e980
ntoskrnl.exe+0x657a1
ntoskrnl.exe+0x66c57
ntoskrnl.exe+0x78a0d
ntoskrnl.exe+0x77d1a
ntoskrnl.exe+0x369a0f
ntoskrnl.exe+0x396739
ntoskrnl.exe+0x72853
wow64cpu.dll!TurboDispatchJumpAddressEnd+0x6c0
wow64cpu.dll!TurboDispatchJumpAddressEnd+0xf5
wow64.dll!Wow64SystemServiceEx+0x1ce
wow64.dll!Wow64LdrpInitialize+0x42a
ntdll.dll!RtlUniform+0x6e6
ntdll.dll!EtwEventSetInformation+0x14e0c
ntdll.dll!LdrInitializeThunk+0xe
ntdll.dll!NtWaitForMultipleObjects+0x15
kernel32.dll!WaitForMultipleObjectsEx+0x8e
kernel32.dll!WaitForMultipleObjects+0x18
kernel32.dll!GetApplicationRecoveryCallback+0x2a7
kernel32.dll!GetApplicationRecoveryCallback+0x166
kernel32.dll!UnhandledExceptionFilter+0x161
kernel32.dll!UnhandledExceptionFilter+0xe0
ntdll.dll!RtlKnownExceptionFilter+0xb7
ntdll.dll!RtlInitializeExceptionChain+0x36

### PR DESCRIPTION
**Pull request by mugling**
Regression introduced by #15413
Provides solution to nullptr dereference identified by @ejseto

Closes #15434
Closes #15450

### CODE REVIEW

File: src/item_location.cpp [hunk 1]
```diff
@@ -128,31 +128,27 @@ class item_location::item_on_person : public item_location::impl
                 return INT_MIN;
             }
 
-            // invalidate this item_location
-            auto it = what;
-            what = nullptr;
```
Comment (mugling) [inline src/item_location.cpp]: Here

File: src/item_location.cpp [hunk 2]
```diff
@@ -163,9 +159,9 @@ class item_location::item_on_person : public item_location::impl
...
             who.moves -= mv;
 
-            if( &ch.i_at( ch.get_item_position( it ) ) == it ) {
+            if( &ch.i_at( ch.get_item_position( what ) ) == what ) {
                 // item already in target characters inventory at base of stack
-                return ch.get_item_position( it );
+                return ch.get_item_position( what );
             }
 
             item obj = what->split( qty );
```
Comment (mugling) [inline src/item_location.cpp]: and then here

**Comment by chaosvolt** [comment]
Glorious. And apologies for the redundant issue post.
