### PR TITLE
Properly handle attempts to wield or throw with two broken arms.

### LINKED ISSUE #41244: try wielding item with 2 arms broken, make the item disappear
Game version: 0.E-3104-g67830ad (tiles)

Operating system: windows 10

Tiles or curses: tiles

Mods active: vanilla

### Expected behavior
the item i try to wield (while my 2 arms are broken) should not disappear.

### Actual behavior
the item actually disappear

### Steps to reproduce the behavior
1- character with 2 arms broken :
image

2- select an item in the inventory :
image

3- in the item menu, select the wield action :
image

then got the two following error messages, and the item has disappeared :
image
image

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4770552/debug.log)

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Properly handle attempts to wield or throw with two broken arms."

#### Purpose of change
Fixes #41244
Properly handle attempts to wield or throw with two broken arms.

#### Describe the solution
Add a few checks for having at least one arm and add the menu color logic to indicate this.

### CODE REVIEW

File: src/avatar_action.cpp [hunk 1]
```diff
@@ -860,6 +860,10 @@ void avatar_action::eat( avatar &you, const item_location &loc,
 void avatar_action::plthrow( avatar &you, item_location loc,
                              const cata::optional<tripoint> &blind_throw_from_pos )
 {
+    if( you.get_working_arm_count() <= 0 ) {
+        add_msg( m_info, _( "You need at least one arm to even consider throwing something." ) );
+        return;
+    }
```
Comment (Qrox) [inline src/avatar_action.cpp:866]: I think it's better to move this check to `can_wield` and check the result of it in `plthrow` and `wield` instead, to avoid code duplication.

File: src/avatar_action.cpp [hunk 2]
```diff
@@ -860,6 +860,11 @@ void avatar_action::eat( avatar &you, const item_location &loc,
 void avatar_action::plthrow( avatar &you, item_location loc,
                              const cata::optional<tripoint> &blind_throw_from_pos )
 {
+    const auto ret = you.can_wield( *loc );
```
Comment (kevingranade) [inline src/avatar_action.cpp:863]: Almost Always Avoid Auto
```suggestion
    const ret_val<bool> ret = you.can_wield( *loc );
```
