### PR TITLE
Prevent integer overflows in bionic power

### LINKED ISSUE #34665: Bionic power constant int overflow
# Describe the bug

```
void Character::mod_power_level( units::energy npower )
{
    power_level = clamp( power_level + npower, 0_kJ, max_power_level );
}
```

There is no check for overflow when adding power_level to npower.
Whenever there is bionic power gain there is a chance for overflow resulting in some "random" value of power. Or loosing all the power.
I tried fixing it but gave up :(

# Steps To Reproduce

1. Make a player with maximum bionic power.
2. Use some bionic power.
3. Eat battery with more charges than you used in point 2.

There are other places when overflow happens, not only battery eating.

# Versions and configuration

build 9478

# Additional context

#34431 should be merged and bionic power should be cut to defined value (for now)
Also we have batteries with more than 2k power. If we would want to use energy units for them we won't be able without int64.

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: Bugfixes "Fix integer overflows when bionic power is modified and when a value is converted to units::energy"

#### Purpose of change
Resolves #34665 
The value by which power is modified in `Character::mod_power_level` could overflow when the new power was large enough that when it was added to the player's power_level the value it produced was larger than the value an int could store.
An overflow could also happen in `units::from_(kilo)joule` when the value provided, when converted to millijoules, was larger than it's type could store. 

#### Describe the solution
Add checks to prevent overflow in all the functions mentioned.

#### Describe alternatives you've considered
Add a check in `units::from_millijoule` to prevent overflow, but I couldn't think of a good way to do that without loosing precision.

#### Testing
Save that I used for testing provided.
[overflow.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/3720956/overflow.tar.gz)
To test for the overflow in `Character::mod_power_level`, eat the battery with ~650 charges (the character has 1980kJ of power, and their max capacity is the max power). The power will overflow  and be clamped to 0kJ.
To test for overflow in `units::from_kilojoule`, consume one of the batteries with 2500 charges, because this is more than can be stored in an int as a millijoule.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -1032,7 +1032,13 @@ void Character::set_max_power_level( units::energy npower_max )
 
 void Character::mod_power_level( units::energy npower )
 {
-    power_level = clamp( power_level + npower, 0_kJ, max_power_level );
+    int new_power = units::to_millijoule( power_level ) + units::to_millijoule( npower );
+    // An integer overflow has occurred - the sum of two positive things (power_level is always positive)
+    // cannot be negative, so if it is, we know integer overflow has occured
+    if( npower >= 0_mJ && new_power < 0 ) {
```
Comment (jbytheway) [inline src/character.cpp]: This test is relying on signed integer overflow, which is undefined behaviour, so it could potentially break depending on compiler optimization.  Easiest solution is to do the computation in `int64_t`s instead, then clamp and cast back to `int`.  Or you can do the more roundabout approach of subtracting `npower` from `max_power_level` and comparing with `power_level` (but then you start risking underflow if you're not careful, so it's hard to do correctly).

Comment (anothersimulacrum) [reply src/character.cpp]: Whoops, thanks #36686!
