### PR TITLE
Fix for counting player kills

### LINKED ISSUE #49837: Killing things doesn't count as killing, but violence counts as violence.
### Describe the bug

You can kill something, but your kill count won't increase, and you won't get the associated conducts/achievements. Note that I fail Non-Violence but I don't get any achievements.

### Steps To Reproduce

1. Find a monster/creature.
2. Kill it.
3. Have your violence acknowledged but fail to be acknowledged for _killing_ the monster.

### Expected behavior

I expected to be rewarded for my violence.

### Screenshots

log
log2
log3

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: aa126fe [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    No Rail Stations [No_Rail_Stations],
    No Fungal Monsters [No_Fungi]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RDru**
#### Summary
Bugfixes "Fix for counting player kills"

#### Purpose of change
Fix for counting player kills and failing pacifist on kill.
Fixes #49837 

#### Testing
Tested with success:
- killing a monster directly
- ramming and killing a monster with vehicle
- activating auto turret on vehicle while I was driving - kill was not registered as intended (as it was working before)
- monsters fighting each other didn't increase the kill count

### CODE REVIEW

File: src/creature.cpp [hunk 1]
```diff
@@ -2440,7 +2440,7 @@ void Creature::process_damage_over_time()
 void Creature::check_dead_state()
 {
     if( is_dead_state() ) {
-        die( nullptr );
+        die( this->killer );
```
Comment (anothersimulacrum) [inline src/creature.cpp:2443]:
```suggestion
        die( killer );
```
