### PR TITLE
Prevent items taking time when canceled.

### LINKED ISSUE #42893: When selecting a tool from the "activate" menu and cancelling, time passes anyway
# Describe the bug

When using the `a` to activate certain items from the "Use item" menu, selecting an item, then pressing ESC to cancel (choosing to do nothing with the item), some amount of time passes anyway.

# Steps To Reproduce

1. Have some items in the inventory that can be activated (but do not have inventory open)
2. Press `a` to open the "Use item" popup menu, showing all items that can be activated/used
3. Select an item and press Enter
4. When prompted for "Light where?" or "What do you want to play?" press ESC
5. Notice that several seconds of time pass, even though you have not done anything

This is true for a number of items with a secondary prompt for where/what to do with the item, including:
- lighter or refillable lighter (1-2 seconds)
- hammer (5 seconds)
- handheld game system (5 seconds)

# Expected behavior

When pressing ESC to cancel an action, I expect 0 time to pass, since I have not done anything.

# Screenshots

Here at 12:40:30 PM, I have pressed `a` and selected my lighter:

image

Press Enter on the lighter to get the "Light where?" prompt (still 12:40:30 PM)

image

Now pressing ESC cancels the prompt, but it's now 12:40:31 PM:

image

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-4984-ga364725156 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

**Important note** - This behavior does *not* occur when `a`ctivating an item from the `i`nventory screen. Activing an item directly from inventory, then cancelling, no time passes. It is only when activating directly from the "Use item" popup that cancelling causes time to pass.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
Bugfixes "Prevent items taking time when canceled."

#### Purpose of change
Fixes #42893
Prevent items taking time when canceled.

#### Describe the solution
Add code to reset the moves you spent for taking out an item if you don't use the item.  Refactor all iuse methods to return whether they were used or not.  If you pick up the item then don't refund the moves even if its not used but do tell the player you picked it up.

#### Describe alternatives you've considered
So many, see linked issue.

#### Testing
Spawned and tested several items but not every single one.

### CODE REVIEW

File: src/avatar_action.cpp [hunk 1]
```diff
@@ -1033,7 +1033,16 @@ void avatar_action::use_item( avatar &you, item_location &loc )
         // Adjustment because in player::wield_contents this amount is refunded.
         you.mod_moves( -loc.obtain_cost( you ) );
     } else {
+        item_location::type loc_where = loc.where();
+        if( loc_where != item_location::type::character && loc_where != item_location::type::container ) {
+            you.add_msg_if_player( "You pick up the %s", loc.get_item()->display_name() );
```
Comment (Night-Pryanik) [inline src/avatar_action.cpp:1038]:
```suggestion
            you.add_msg_if_player( _( "You pick up the %s." ), loc.get_item()->display_name() );
```

**Review by Ramza13 — COMMENTED** [review]
Ignore this, clicked wrong button

File: src/avatar_action.cpp [hunk 2]
```diff
@@ -1033,7 +1033,16 @@ void avatar_action::use_item( avatar &you, item_location &loc )
         // Adjustment because in player::wield_contents this amount is refunded.
         you.mod_moves( -loc.obtain_cost( you ) );
     } else {
+        item_location::type loc_where = loc.where();
+        if( loc_where != item_location::type::character && loc_where != item_location::type::container ) {
```
Comment (mqrause) [inline src/avatar_action.cpp:1037]: Does `item_location::type::container` mean it's in a container on the character, or can it be in a container on the map/in a vehicle, too?

Comment (Ramza13) [reply src/avatar_action.cpp:1037]: Good catch, just tested and yea that is a mistake I will have to amend.

Comment (mqrause) [reply src/avatar_action.cpp:1037]: If that's the case, `container` should not be part of that enum. Not as part of this PR obviously, but it would make a fix for this not awkward.

Comment (mqrause) [reply src/avatar_action.cpp:1037]: It's a bit different actually. But I made #46939 that you can make use of if it gets merged.

Comment (Ramza13) [reply src/avatar_action.cpp:1037]: That sounds perfect, I'll be sure to add it to this once it merges.  Thanks

**Comment by actual-nh** [comment]
@Ramza13: Should this be made a draft until #46939 is merged?

**Comment by kevingranade** [comment]
Merged  #46939

**Comment by Ramza13** [comment]
Updated to use  #46939 and now correctly handle items in containers on the ground.

**Comment by actual-nh** [comment]
@anothersimulacrum: Given that this is solving a blocker, why would this get a `Feature Freeze`?

**Comment by anothersimulacrum** [comment]
I was not aware this was a blocker. This seems like a very big/invasive fix for before a stable release, but I'll let mergers make the decision.

**Comment by kevingranade** [comment]
The invasiveness is exactly what has been holding up a merge, I have not had time to look into it to the extent necessary to come to a final decision, but if a less invasive solution is possible I'd much prefer it.
It's less about the iuse changes and more about the new parameter getting passed through the code leading to the iuse invocation that worries me.  That having been said, if there isn't a better way, this is a pretty bad behavior, so it NEEDS a fix.

**Comment by Ramza13** [comment]
> 
> 
> The invasiveness is exactly what has been holding up a merge, I have not had time to look into it to the extent necessary to come to a final decision, but if a less invasive solution is possible I'd much prefer it.
> It's less about the iuse changes and more about the new parameter getting passed through the code leading to the iuse invocation that worries me. That having been said, if there isn't a better way, this is a pretty bad behavior, so it NEEDS a fix.

I went through a lot of different approaches to get to this solution, in my comments of the linked bug there are a lot of alternatives listed and the reasons they couldn't be used.  As far as I can tell there is no easier or less invasive way to do this.

**Comment by kevingranade** [comment]
Yea, I finally had a while to review it, and I'm not seeing a better option.  If nothing else the iuse switch to optional is pretty ideal.
