### PR TITLE
Fix keybinding assignment in uilists (e.g., Map Notes)

### LINKED ISSUE #54778: Key conflicts with Map Note List
### Describe the bug

If you have too many map notes, from, say, auto-notes, you can't use the default keys to do anything to them.

### Steps to reproduce

Make 52 map notes.

### Expected behavior

That keys used on a screen were prevented from the allocation pool.  

Side note: the bionics menu can have collisions like this as well, but that usually needs to be purposefully made conflicting to the key defaults.

### Screenshots

image

### Versions and configuration

Win 10/tiles
2f4c5a5

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by haveric**
#### Summary
Bugfixes "Fix keybinding assignment in uilists (e.g., Map Notes)"

#### Purpose of change

Fixes #54778

#### Describe the solution

Reuse the input_context in uilists and create queues only from available hotkeys

#### Describe alternatives you've considered

1. Pass `input_context &ctx` around a whole bunch. This felt more difficult than adding a class variable and the set category function
2. Might be better code solutions and I am willing to take advice on anything that can be improved
3. Leave broken

#### Testing

Created a bunch of map notes. Opened the map and viewed the `List Notes` menu. Compared the keybindings and tested the key functionalities within the menu.

This probably needs testing on other uilists to see how this affects them.

#### Additional context

Next step would be to evaluate if `hotkey_queue &hotkey_queue::alphabets()` is causing similar issues for npctalk and veh_interact. I suspect it is, but have not tested this yet. I can make this into another PR once verified it's an issue and this one is validated as working correctly.

Before change:
image

After change: (Note that keys such as f (find), j (down), k (up), E (Edit), M (Mark dangerous), D (Delete) do not show up
image

### CODE REVIEW

**Comment by Qrox** [comment]
This has broken keycode mode.

File: src/input.cpp [hunk 1]
```diff
@@ -1896,26 +1896,19 @@ const hotkey_queue &hotkey_queue::alphabets()
...
-        queue->codes_keycode.emplace_back( '0' );
-        queue->codes_keychar.emplace_back( '0' );
-        for( int ch = 'a'; ch <= 'z'; ++ch ) {
-            queue->codes_keycode.emplace_back( ch );
-            queue->codes_keychar.emplace_back( ch );
-        }
-        for( int ch = 'A'; ch <= 'Z'; ++ch ) {
-            queue->codes_keychar.emplace_back( ch );
+
+        std::string available_hotkeys = ctxt.get_available_single_char_hotkeys();
```
Comment (Qrox) [inline src/input.cpp:1905]: This function only works for character mode. Not all charactered returned from this call is a valid key code, and that's why this function specifically did not call this function.

File: src/ui.cpp [hunk 2]
```diff
@@ -289,6 +289,7 @@ void uilist::init()
     max_column_len = 0;      // for calculating space for second column
 
     input_category = "UILIST";
+    input_context ctxt( input_category, keyboard_mode::keychar );
```
Comment (Qrox) [inline src/ui.cpp:292]: This only creates an input context in the local scope, which means the `ctxt` member still uses keycode mode, which breaks text input in keycode mode.

File: src/input.cpp [hunk 3]
```diff
@@ -1896,26 +1896,19 @@ const hotkey_queue &hotkey_queue::alphabets()
...
+        int input_length = available_hotkeys.length();
+
+        for( int i = 0; i < input_length; i++ ) {
+            queue->codes_keycode.emplace_back( available_hotkeys[i] );
+            queue->codes_keychar.emplace_back( available_hotkeys[i] );
         }
-        queue->modifiers_keycode.emplace_back();
-        queue->modifiers_keycode.emplace_back( std::set<keymod_t>( { keymod_t::shift } ) );
```
Comment (Qrox) [inline src/input.cpp:1918]: This was here for a reason and you shouldn't simply remove it. It makes the queue generates hotkeys modified with the shift key in place of capital characters in character mode.

File: src/input.cpp [hunk 4]
```diff
@@ -1896,26 +1896,19 @@ const hotkey_queue &hotkey_queue::alphabets()
     return *queue;
 }
 
-const hotkey_queue &hotkey_queue::alpha_digits()
+const hotkey_queue &hotkey_queue::create_from_available_hotkeys( input_context &ctxt )
```
Comment (Qrox) [inline src/input.cpp:1899]: This will always return the queue created for the first input context this function is called with, because `queue` is static.

File: src/ui.cpp [hunk 5]
```diff
@@ -348,7 +349,7 @@ void uilist::filterlist()
 
 void uilist::inputfilter()
 {
-    input_context ctxt( input_category, keyboard_mode::keychar );
+    ctxt.set_category( input_category );
```
Comment (Qrox) [inline src/ui.cpp:352]: This will make the filter context have actions registered in the list context, which may causes incorrect behavior,
