### PR TITLE
[RDY][CR] Rework inventory columns

### LINKED ISSUE #16504: Incorrect form of name of dropped item
Name of dropped item is always shown in plural form (ignoring the actual number of dropped items):
bug_plural

I guess that ```void inventory_selector::print_right_column() const``` in ```inventory_ui.cpp``` is bugged. Is everything ok with variable ```display_count```?
```
const int display_count = (count == -1) ? (it.charges >= 0) ? it.charges : stack.size() : count;
/.../
std::string item_name = it.tname( display_count );
```

### PR DESCRIPTION
**Pull request by codemime**
They definitely deserve a class of their own. It gives additional flexibility for managing them and makes the code cleaner. In the future this will enable us to have a shared functionality with the pick-up menu and support filtering by keyboard input (along with some other features).

TODO:
- [x] The column that shows selected items should become a descendant of `inventory_column`, not an ugly duplicate
- [x] Remove `first_item` and `second_item`
- [x] Adaptive width of columns
- [x] Ground and vehicle items in a separate column (only when there's free room on the screen)
- [x] Ability to select many items at once (I suppose via category mode).

EDIT:
### Summary:

Almost all the code of inventory columns was rewritten. Now it's much cleaner and more object-oriented. Due to length I'll omit the list of code changes, they can be seen in the code itself, but I'll describe observable changes in detail.

The most significant feature is the actual multidrop. You can drop a whole category within a couple of key-presses (i.e. get undressed). Number of items to drop (or NONE) is shown. Also, markers are colorized and no more red color for categories:
undress

You're free to use category selection in any mode, but those that require only one item, won't allow you to select more.

If you drop too many items at once, the last column (ITEMS TO DROP) becomes selectable and you can inspect it (see the old behavior below): 
long_drop
Here's the old behavior:
old_list_overflow

Selected column is always the topmost so that nothing's trimmed and can be fully read. Inactive columns don't show their selection (it was misleading):
select
The rightmost column is prepared for the longest item, so there's no "jerking":
space

Here's the old appearance:
old_trim
no_drop_list

Skimming through categories works mostly as usual, but was also improved. It will not skip pages in case of long categories (note TOOLS) and Page x/y is shown under each column, but only if it's necessary (more than one page):
categories

Page up/page down are now available:
page_updown

There's a short static summary:
middle_column

Selection mode is now correctly "remembered" when you select an item and then go back to the inventory (actually it doesn't change, because the object stays the same and doesn't get recreated).
Also, there are some more small changes that I probably forgot to mention.

I plan more extensive clean up for `inventory_ui.cpp` in further PRs.

EDIT: Fixes #16504.

### CODE REVIEW

**Comment by codemime** [comment]
The PR is ready for review / testing.

File: src/inventory_ui.cpp [hunk 1]
```diff
@@ -781,19 +967,28 @@ int inventory_selector::execute_pick( const std::string &title, const int positi
...
-            return get_selected_item_position();
+            const auto selection( get_active_column().get_all_selected() );
+
+            if( selection.empty() ) {
+                return INT_MIN;
+            } else if( selection.size() == 1 ) {
+                return selection.front()->item_pos;
+            } else {
+                const std::string msg( _( "Please pick only one item." ) );
+                popup( msg , PF_GET_KEY );
```
Comment (Coolthulhu) [inline src/inventory_ui.cpp]: This shouldn't really happen.
When the selector is in single-select mode, it should not look like it is in multi-select mode and should not allow selecting multiple items. Making it default to the first one is fine, as long as it displays only the first one as selected.

Also, "please" in user commands is a bit too polite. It sounds like we're giving the user a choice, which isn't the case. "Only one item can be selected" or something like that.

File: src/inventory_ui.cpp [hunk 2]
```diff
@@ -879,66 +1110,73 @@ void inventory_selector::execute_compare( const std::string &title )
...
+
+    int res;
+    do {
+        const int pos = inv_s.execute_pick( _( "Inventory:" ) );
+        if( pos == INT_MIN ) {
+            break;
+        }
+        refresh_all();
+        res = inventory_item_menu( pos );
+    } while( std::find( stoppers.begin(), stoppers.end(), res ) == stoppers.end() );
```
Comment (Coolthulhu) [inline src/inventory_ui.cpp]: Would be cleaner if you just made the `stoppers` a `set` and used `count` here.

File: src/inventory_ui.cpp [hunk 3]
```diff
@@ -767,10 +876,87 @@ void inventory_selector::remove_dropping_items( player &u ) const
...
+    for( auto &column : columns ) {
+        column->on_mode_change( navigation );
+    }
+}
+
+void inventory_selector::insert_column( decltype( columns )::iterator position, inventory_column *new_column )
+{
+    assert( new_column != nullptr );
+
+    std::unique_ptr<inventory_column> column( new_column );
```
Comment (Coolthulhu) [inline src/inventory_ui.cpp]: This looks risky. Why are you wrapping a non-unique ptr in a unique ptr? Why not pass unique one as argument instead?
Passing unique ptr would make the intention clear and prevent possible bugs resulting from someone trying to keep the column despite inserting it.

Also, all usages of the function are in the form:
```
insert_column( iter, uniqueptr.release() );
```

You could just change the `ptr.release()` into `std::move( ptr )`.

File: src/inventory_ui.cpp (hunk 1 above)
Comment (codemime) [inline src/inventory_ui.cpp]: Makes sense.

File: src/inventory_ui.cpp (hunk 2 above)
Comment (codemime) [inline src/inventory_ui.cpp]: Totally agreed.

File: src/inventory_ui.cpp (hunk 3 above)
Comment (codemime) [inline src/inventory_ui.cpp]: > Passing unique ptr would make the intention clear

That was my first intention and I implemented it. I had to use casting to achieve polymorphic unique pointers. That didn't look particularly elegant, so I abandoned the idea. But you probably right about the safety and clearness.

**Comment by codemime** [comment]
All set. Cleaned up and fixed a couple of bugs in the current `master`: 

Pressing PAGE DOWN. Note that page 4 is never shown because it has lesser items than would be selected. Moreover, PAGE UP and PAGE DOWN behave weird when there's only one page on the screen (i.e. press PAGE DOWN -> the topmost item will be selected and vice versa). The new mechanics is predictable and it feels right.

**Comment by codemime** [comment]
Position of inventory columns on the screen is now adaptive. They're aligned to the left of the screen if they occupy less than 2/3 of its width, otherwise they'll occupy all the width evenly. Also, the rounding error for the gaps was taken into account.

**Comment by codemime** [comment]
Anything else before it's mergeable? I'm going to PR an improvement that would depend on both this PR and #16766.

File: src/inventory_ui.cpp [hunk 4]
```diff
@@ -40,409 +32,697 @@ struct itemstack_or_category {
...
-    itemstack_or_category(const indexed_invslice::value_type &a)
-        : it(&(a.first->front())), slice(a.first), category(&it->get_category()), item_pos(a.second)
-    {
+    size_t chosen_count = 0;
+
+    inventory_entry( const indexed_invslice::value_type &slice, const item_category *cat = nullptr )
+        : it( &( slice.first->front() ) ), slice( slice.first ),
+          category( ( cat != nullptr ) ? cat : &it->get_category() ), item_pos( slice.second ) {}
+    inventory_entry( const item *it, int pos, const item_category *cat = nullptr )
+        : it( it ), slice( nullptr ), category( ( cat != nullptr ) ? cat : &it->get_category() ), item_pos( pos ) {}
```
Comment (Coolthulhu) [inline src/inventory_ui.cpp]: Those defaults are unreadable. If you're going to have ternary operators inside them, it would be a good idea to put each of them on a separate line.

Comment (codemime) [inline src/inventory_ui.cpp]: Agreed. Their formatting is a leftover.

**Comment by Coolthulhu** [comment]
* Get a screen size wide enough for 3 columns (mine is 135 columns)
* Get some items - worn and in inventory
* Displays as 2 columns
* Get a lot of items so that one page won't display them all at once
* Displays as 3 columns now, but the middle column is just empty space

**Comment by codemime** [comment]
I try but fail to get an unexpected behavior. Can it be this:

> Position of inventory columns on the screen is now adaptive. They're aligned to the left of the screen if they occupy less than 2/3 of its width, otherwise they'll occupy all the width evenly.

**Comment by Coolthulhu** [comment]
Pretty sure it's this PR:
Dropping charged items makes them uncharged. Dropping a specific amount of charges doesn't do that.

**Comment by codemime** [comment]
I tried to drop a vegetable pie and nobody has eaten it while it was falling. I'll try to rebase this PR against current master and try agian. Perhaps something has happened since then.

**Comment by Coolthulhu** [comment]
There is a slight chance some other PR did that, but it only seems to happen when dropping things with the inventory menu - autodrop, advanced inventory, throwing etc. are all unaffected.

**Comment by codemime** [comment]
Yes, it's changed after some very recent PR. I'm nailing it down now.

**Comment by codemime** [comment]
It's definitely not this PR. The issue is in the `master` branch already.

**Comment by Coolthulhu** [comment]
This PR can't be properly tested for as long as this bug exists.

**Comment by codemime** [comment]
I found a source of the bug and will PR a fix pretty soon.
