### PR TITLE
Increase butcher times to be 6 times as long

### LINKED ISSUE #31793: Butcher times too fast
# Describe the bug

Butcher times are too short and used to be longer. It is likely to be related to the change in issue #30018 

# Expected behavior

Butcher times to be 6 times as long.

# Screenshots

Old butcher times
Screenshot from 2019-06-24 13-16-28

New butcher times
Screenshot from 2019-06-24 13-07-15

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.2 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-4902-gdc3475c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [Dark Days Ahead [dda], Disable NPC Needs [no_npc_food]]

# Additional context

I've liked being able to dissect in 7 minutes but I think that it is a bit fast and not really that realistic.

### PR DESCRIPTION
**Pull request by Llama3013**
#### Summary
```Summary: Bugfixes "Increase butcher times to be 6 times as long"```

#### Purpose of change
Fixes #31793 - Butcher times too fast

#### Describe the solution
I have just increased the time it takes to butcher by 6 times as much, to match the old butcher times.

#### Describe alternatives you've considered
I am new to cataclysm dda so there might be things that I missed, or better alternative solutions but from what I tested it seems to work.

#### Additional context
before dissecting
Screenshot from 2019-06-24 15-04-13

after dissecting
Screenshot from 2019-06-24 15-04-33
(I am pretty sure it took slightly longer because of the character having -1 speed.)

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -516,26 +516,26 @@ int butcher_time_to_cut( const player &u, const item &corpse_item, const butcher
     switch( corpse.size ) {
         // Time (roughly) in turns to cut up the corpse
         case MS_TINY:
-            time_to_cut = 25;
+            time_to_cut = 125;
```
Comment (ZhilkinSerg) [inline src/activity_handlers.cpp]:
```suggestion
            time_to_cut = 150;
```

**Comment by ifreund** [comment]
Note that this sorta conflicts with #31781 which fixes the same problem in a different way.  This PR is much more straightforward though.

**Comment by ZhilkinSerg** [comment]
I am gonna merge it as an immediate fix as #31781 could take some time to get merged.
