### PR TITLE
Fix: Use same hunger names in consume menu as in sidebar

### LINKED ISSUE #71064: Hunger Rounding Issue
### Describe the bug

There can be a discrepancy between the hungry shown on the sidebar and the hunger shown in the consume menu. 

### Attach save file

[Earth-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13984346/Earth-trimmed.tar.gz)

### Steps to reproduce

1. Make a player. 
2. Get hungry (on the sidebar)
3. Check to see if the consume menu says very hungry

### Expected behavior

I expected the hunger level to be the same everywhere it is displayed. 

### Screenshots

Screenshot (302)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22621.3007 (22H2)
- Game Version: c16bfbd [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by inogenous**
#### Summary
Bugfixes "Use same hunger names in consume menu as in sidebar"

#### Purpose of change

Updates consume menu so that it shows the same names for hunger as what is used in the sidebar widget. Fixes #71064 .

#### Describe the solution

Names in `display::hunger_text_color` should use same names and colors as `data/json/ui/hunger.json`.

This commit also updates color for "Overweight" in the consume menu so that it uses the same color as in sidebar widget from `data/json/ui/weight.json`, as was changed in #69005 .

#### Describe alternatives you've considered

We could also update `display::hunger_text_color` so that it uses the json from the sidebar widget to get its display value.

#### Testing

Tested the savegame from #71064 . It now displays "Hungry" in consume menu:

snapshot1

#### Additional context

Ref #69005

### CODE REVIEW

File: src/display.cpp [hunk 1]
```diff
@@ -716,8 +716,8 @@ std::pair<std::string, nc_color> display::hunger_text_color( const Character &u
             std::forward_as_tuple( effect_hunger_full, translate_marker( "Full" ), c_yellow ),
             std::forward_as_tuple( effect_hunger_satisfied, translate_marker( "Satisfied" ), c_green ),
             std::forward_as_tuple( effect_hunger_blank, "", c_white ),
-            std::forward_as_tuple( effect_hunger_hungry, translate_marker( "Hungry" ), c_yellow ),
-            std::forward_as_tuple( effect_hunger_very_hungry, translate_marker( "Very hungry" ), c_yellow ),
+            std::forward_as_tuple( effect_hunger_hungry, translate_marker( "Peckish" ), c_light_gray ),
```
Comment (Maleclypse) [inline src/display.cpp:719]:
```suggestion
            std::forward_as_tuple( effect_hunger_hungry, translate_marker( "Peckish" ), c_light_gray )
```

File: src/display.cpp [hunk 2]
```diff
@@ -716,8 +716,8 @@ std::pair<std::string, nc_color> display::hunger_text_color( const Character &u
             std::forward_as_tuple( effect_hunger_full, translate_marker( "Full" ), c_yellow ),
             std::forward_as_tuple( effect_hunger_satisfied, translate_marker( "Satisfied" ), c_green ),
             std::forward_as_tuple( effect_hunger_blank, "", c_white ),
-            std::forward_as_tuple( effect_hunger_hungry, translate_marker( "Hungry" ), c_yellow ),
-            std::forward_as_tuple( effect_hunger_very_hungry, translate_marker( "Very hungry" ), c_yellow ),
+            std::forward_as_tuple( effect_hunger_hungry, translate_marker( "Peckish" ), c_light_gray )
```
Comment (Maleclypse) [inline src/display.cpp:719]:
```suggestion
            std::forward_as_tuple( effect_hunger_hungry, translate_marker( "Peckish" ), c_light_gray ),
```
