### PR TITLE
fix liquid spawning in containers

### LINKED ISSUE #40128: Bleach and ammonia are spawning with incorrect units by default
# Describe the bug

Bleach and ammonia are spawned by default in gallon jugs. However, they only contain 0.50 L of content upon spawning - even though gallon jugs should store 3.75 L. This applies to both in-game spawning (such as in well stocked evac shelter basements) and debug spawning.

I suspect that other liquids that spawn in gallon jugs, such as milk, may have this problem as well - but I haven't tested it yet.

# Steps To Reproduce

1. Debug spawn bleach or ammonia with a container.
2. Marvel at the low volume of bleach and ammonia present.

# Expected behavior

Brand-new gallon jugs of bleach and ammonia contain 3.75 L, not 0.50 L, of liquid.

# Screenshots

Bleach: 
image

Ammonia: 
image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-1713-gd15c896 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Graphical Overmap [Graphical_Overmap],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills]
]

# Additional context

### LINKED ISSUE #40197: Comestible containers only spawn with single charge
# Steps To Reproduce

1. Make a player with a bottle of water.
2. Open inventory.  See bottle with 1 charge of water.  
3. Open debug menu. 
4. Spawn contained clean water. Examine it as well. 1 charge.
5.  Go inside house and find bottle of clean water.
6. Examine them and see that they also only contain 1 charge of water.
7. Despair.

# Expected behavior

2 charges for full bottles.

# Screenshots

NA

# Versions and configuration

OS: Windows

OS Version: 10.0 1903
Game Version: 0.E-1739-g5de957a [64-bit]

Graphics Version: Tiles

Game Language: System language []

Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Aftershock [aftershock],
Blaze Industries [blazeindustries],
C.R.I.T Expansion Mod [crt_expansion],
Magiclysm [magiclysm],
DinoMod [DinoMod],
Alternative Map Key [alt_map_key],
Crazy Cataclysm [crazy_cataclysm],
Mythical Martial Arts [MMA],
Fuji's Military Profession Pack [fuji_mpp],
SpeedyDex [speedydex],
Stats Through Kills [stats_through_kills],
Stats Through Skills [StatsThroughSkills]
]
# Additional context

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: None```

#### Purpose of change
Fixes #40128

#### Describe the solution
make sure to call fill_with in item::in_its_container() and add an extra parameter that lets you specify the number of charges contained.

#### Testing
spawned a jug of bleach from wish menu - it has 30 charges.
went to a kitchen and found a jug of ammonia with 8 charges.

#### Additional context

Probably Fixes #40197 but needs some additional testing to make sure

### CODE REVIEW

**Comment by KorGgenT** [comment]
Probably Fixes #40197 but needs some additional testing to make sure

File: src/item_group.cpp [hunk 1]
```diff
@@ -74,8 +74,12 @@ item Single_item_creator::create_single( const time_point &birthday, RecursionLi
     if( modifier ) {
         modifier->modify( tmp );
     } else {
+        int qty = item::INFINITE_CHARGES;
+        if( modifier ) {
+            qty = rng( modifier->charges.first, modifier->charges.second );
+        }
```
Comment (ZhilkinSerg) [inline src/item_group.cpp:80]: This code is unreachable as you have already verified `modifier` is `false` in outer `if` (line 74).
