### PR TITLE
Fix divide by zero issue

### LINKED ISSUE #64613: Crash to desktop with no error logs or crash logs when creating a new item with same ID as game but different type
### Describe the bug

I have been working on updating and fixing my mods for 0.G, and I've encountered a crash to desktop that does not result in any error messages. Here is the debug log:

`
-----------------------------------------
17:56:03.366 : Starting log.
17:56:03.366 INFO : Cataclysm DDA version 0bba914
17:56:03.367 INFO : [main] C locale set to English_Canada.utf8
17:56:03.367 INFO : [main] C++ locale set to 
17:56:03.367 INFO : SDL version used during compile is 2.26.4
17:56:03.367 INFO : SDL version used during linking and in runtime is 2.26.4
17:56:03.423 INFO : Number of render drivers on your system: 6
17:56:03.423 INFO : Render driver: 0/direct3d
17:56:03.423 INFO : Render driver: 1/direct3d11
17:56:03.423 INFO : Render driver: 2/direct3d12
17:56:03.423 INFO : Render driver: 3/opengl
17:56:03.423 INFO : Render driver: 4/opengles2
17:56:03.423 INFO : Render driver: 5/software
17:56:03.426 INFO : [options] C locale set to English_Canada.utf8
17:56:03.426 INFO : [options] C++ locale set to 
17:56:03.426 INFO : Setting language to: 'en'
17:56:03.426 INFO : [i18n] Scanning core translations from lang/mo/
17:56:03.426 INFO : [i18n] Scanning mod translations from ./mods/
17:56:03.426 WARNING : opendir [./mods/] failed with "The system cannot find the path specified.".
17:56:03.573 INFO : Active renderer: 1/direct3d11
17:56:03.835 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
17:56:03.847 INFO : Setting language to: 'en'
17:56:03.925 WARNING : opendir [./mods] failed with "The system cannot find the path specified.".
17:56:09.800 INFO : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mod_tracker.h:68: Tried check if 'vampire_cathedral' had a duplicate, but type 'class overmap_special' does not track object sources
`

It happens before character generation, and seems to hit when the Items portion of the game loading is happening. I cannot get to the save menu, or far enough to enable debug menu.

### Attach save file

N/A

### Steps to reproduce

1. Create a world with Nymall's Foodlab and Nymall's Tools enabled.
2. Attempt to create a character

### Expected behavior

- It to work and allow through with errors if any exist
- The game to kick back to the world selection with an error
- A error log or crash log to be generated

### Screenshots

_No response_

### Versions and configuration

(this is pulled from a working version without the mod Nymalls Tools enabled - cannot generate report if foodlab is enabled)

20:44:32.207 :  GAME REPORT:
- OS: Windows
    - OS Version: 10.0.19045.2728 (22H2)
- Game Version: 0bba914 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Nymall's Tools [nymalltools]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fixes #64613

### CODE REVIEW

File: src/item_factory.cpp [hunk 1]
```diff
@@ -636,7 +636,7 @@ void Item_factory::finalize_pre( itype &obj )
 
     if( obj.longest_side == -1_mm ) {
         units::volume effective_volume = obj.count_by_charges() ?
-                                         ( obj.volume / obj.stack_size ) : obj.volume;
+                                         ( obj.volume / ( obj.stack_size != 0 ? obj.stack_size : 1 ) ) : obj.volume;
```
Comment (mqrause) [inline src/item_factory.cpp:639]: Github won't let me make a suggestion here thanks to the line break, but I came across the same issue in #60885 and solved it by checking `obj.count_by_charges() && obj.stack_size > 0`, which I find a little cleaner than your version.
