### PR TITLE
Gun magazine agreement

### LINKED ISSUE #42254: NPC carries Glock 22 loaded with .357 SIG, but Glock 22 can't use SIG
# Describe the bug

I looted a guard in the rescue center. He carried a Glock 22 with an extended magazine which was loaded with .357 SIG. But if I try to shoot it tells me that the Glock 22 can't fire with incompatible ammunition loaded.

I also spawned a Glock 22 and extended mag via the debug menu. The mag spawned loaded with .357 SIG. Same story. When I spawned .40 S&W and loaded that it worked.

# Steps To Reproduce

1. Make a player with a Glock 22, magazine, and some .357 SIG.
2. Try to shoot.
3. It doesn't shoot.
4. Check out npc guards in refugee center. They spawn with Glock 22s loaded with .357 SIG.

# Expected behavior
If Glock 22 is supposed to be able to shoot .357 then it should do so. And if it isn't it shouldn't spawn with .357 loaded.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-4241-g36ba9f8 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### LINKED ISSUE #42280: Generic Guns: pistol is not accepting ammunition.
# Describe the bug

The generic pistol 'defensive pistol' includes the magazine 'pistol magazine' which only accepts 9x19mm JHP munition, instead of  'Pistol ammo, JHP' which it ought to. Spawning in a loaded pistol magazine (15/15 9x19mm), loading it (which works) and trying to fire it, results in the message 'The defensive pistol can't be fired while loaded with incompatible ammunition 9x19mm JHP'. 

Further observations: 
Upon loading the save, the loaded magazine is unloaded. 
The sniper rifle has the same problem.
The antique pistol works fine.

On a maybe related note, trying to spawn in a AR pistol, Assault rifle +1, a pipe rifle or a pipe rifle .223 results in a null pointer.

Generic Gun magazines do not accept their generic munition.

# Steps To Reproduce
1. Make a player
2. Spawn in a defensive pistol or sniper rifle, plus their respective magazine and generic ammo.
3. Try to reload

# Expected behaviour

Defensive pistols should accept their ammunition. 

# Versions and configuration

 - OS:  Linux Mint 19.3
 - Game Version: 0.E-4254-gfea0266
 - Graphics version: Terminal
 - Ingame language: English
 - Mods loaded: dda, Generic Guns

### LINKED ISSUE #42332: Glock 22 Mag Bug
Glock 22 says it takes Sig 357 despite being chambered .40 S&W the mag states to only take 357

# Steps To Reproduce

try and fire a glock 22 as described by the game with a loaded glock 22 mag loaded with 357 any ammo (it only takes 357 despite the glock 22 being chambered in .40)

# Expected behavior

that the glock 22 should take a .40 S&W mag

# Screenshots

-

# Versions and configuration

Newest Experimental version, other users reported the same issue on other platforms

# Additional context

-

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Fixes #42332
Fixes #42254
Fixes #42280
A gun item's concept of "what ammo type can I use" had been redefined by the pocket system to defer that decision to the gun's magazine, and if no magazine is present, to an arbitrary "default magazine".
This is sometimes incorrect, for example in the case of the Glock 22, which uses a type of magazine that can hold both .357 and .40 rounds, leading to an incorrect stat display claiming the gun can fire .357 rounds.
It also impacts item spawns in that guns suffering from this problem spawn with their "default ammunition", which is not fireable.
A bonus is that debug-created guns now spawn with a loaded magazine again.
In the process of getting generic guns to load (along with aftershock and blazeindustries), I discovered some problems with some item definitions and with item migration code.

#### Describe the solution
Update item::ammo_types to return the set of ammunition types a gun can *chamber* instead of returning "what its magazine can hold".
Add a migration feature that updates magazine ammo restrictions when the matching ammo is migrated.  This was breaking the generic guns mod, because the ammo type was being migrated but the magazine was not, so the magazine would require an unobtainable ammunition type.
Fix a few data errors in generic guns.
Throw my hands up at whatever was happening to the obsoleted pipe rifles and just removed them (with migrations).

#### Describe alternatives you've considered
This could possibly be resolved by updating item::default_ammo() to make this determination instead of applying the change inside item::ammo_types(), but this strikes me as a tidier solution.

#### Testing
Unit tests pass (after some cleanup).
Examining an unloaded Glock 22 now displays the correct assumed ammunition type and stats.
All whitelisted mods will load properly and run data consistency checks.
Loaded an Aftershock/Generic guns world, spawned some guns, reloaded and fired and reloaded them.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -7681,6 +7681,9 @@ std::set<ammotype> item::ammo_types( bool conversion ) const
         }
     }
 
+    if( is_gun() ) {
+        return type->gun->ammo;
```
Comment (actual-nh) [inline src/item.cpp:7685]: If there are multiple of these, and only some overlap with contents.ammo_types(), should only the overlapping one(s) be returned?

**Comment by Mrzjadacz** [comment]
Fixes: #46548 
Probably should fix #45882
