### PR TITLE
More robust aim bars

### LINKED ISSUE #15790: Crash when using ranged weapon bionic while on a vehicle turret
* Spawn a flaming electric car with ammo in its machine gun turret
* Spawn a debug monster within the range of the turret
* Have empty hands
* Get on the machine gun turret
* Activate the laser finger bionic
* Segfault

### PR DESCRIPTION
**Pull request by codemime**
Fixes #15790 and reduces code duplication by introducing `get_labeled_bar()` function.

### CODE REVIEW

File: src/output.cpp [hunk 1]
```diff
@@ -1990,6 +1990,46 @@ std::pair<std::string, nc_color> const& get_light_level(const float light)
...
+template<typename RatingIterator>
+std::string get_labeled_bar( const double val, const int width, const std::string &label,
+    RatingIterator begin, RatingIterator end )
+{
+    std::string result;
+
+    result.reserve( width );
+    if( !label.empty() ) {
+        result += label;
+        result += std::string( " " );
```
Comment (BevapDin) [inline src/output.cpp]: `std::string` has an overloaded `operator+=` that works just fine with C-strings, you don't need to construct a temporary string here. You could even just add a single space *character* instead of a C-string. Same below.

File: src/output.h [hunk 2]
```diff
@@ -413,6 +413,27 @@ std::pair<std::string, nc_color> const& get_item_hp_bar(int dmg);
 
 std::pair<std::string, nc_color> const& get_light_level(const float light);
 
+/**
+ * @return String containing the bar. Example: "Label [********    ]".
+ * @param val Value to display. Can be unclipped.
+ * @param width Width of the entire string.
+ * @param label Label before the bar. Can be empty.
+ * @param begin Iterator over pairs <double percentage, char char>.
+ * @param end Iterator over pairs <double percentage, char char>.
```
Comment (BevapDin) [inline src/output.h]: Would be nice to explain what these iterators do. The meaning of `value`, `width` and `label` are explained, but for `begin` and `end`, it just says *what* type it expects, not what it actually does.

File: src/output.cpp [hunk 3]
```diff
@@ -1990,6 +1990,46 @@ std::pair<std::string, nc_color> const& get_light_level(const float light)
...
+        int used_width = 0;
+        for( RatingIterator it(begin); it != end; ++it ) {
+            const double factor = std::min( 1.0, std::max( 0.0, it->first * val ) );
+            const int seg_width = int( factor * bar_width ) - used_width;
+
+            if( seg_width <= 0 ) {
+                continue;
+            }
+            used_width += seg_width;
+            result += std::string( seg_width, it->second );
```
Comment (mugling) [inline src/output.cpp]: consider `std::string::insert` to avoid constructing an otherwise unused instance
eg. `result.insert( result.end(), seg_width, it->second )`

File: src/output.cpp [hunk 4]
```diff
@@ -1990,6 +1990,46 @@ std::pair<std::string, nc_color> const& get_light_level(const float light)
...
+        }
+        result += std::string( bar_width - used_width, ' ' );
```
Comment (mugling) [inline src/output.cpp]: and the same here
