### PR TITLE
Fix for fingerpick CBM

### LINKED ISSUE #11980: Fingerpick costs no energy
The description indicates it's supposed to cost 25, though it probably should be free considering all it saves you is 1.2 lbs for a picklock kit.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10894210-fingerpick-costs-no-energy?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by illi-kun**
Now it consumes 25 PU on activation, as it should.
Fixes #11980.

### CODE REVIEW

File: src/bionics.cpp [hunk 1]
```diff
@@ -944,7 +944,6 @@ bool player::activate_bionic(int b, bool eff_only)
     } else if(bio.id == "bio_lockpick") {
         tmp_item = item( "pseuso_bio_picklock", 0 );
         if( invoke_item( &tmp_item ) == 0 ) {
-            charge_power(bionics["bio_lockpick"].power_activate);
```
Comment (illi-kun) [inline src/bionics.cpp]: This line actually _charges_ the batteries (charge of +25 PU, consumption is done in another line);
