### PR TITLE
Fix crash when undefined items have no category

### LINKED ISSUE #18848: Artifacts causing crash
Using most recent build (0.C 5720), trying to (e)xamine an artifact instantly crashed the game both times I encountered one.

### PR DESCRIPTION
**Pull request by mugling**
Factored out of #18861
Fixes #18848

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -5056,7 +5056,7 @@ const item_category &item::get_category() const
     }
 
     static item_category null_category;
-    return type ? *type->category : null_category;
+    return type->category ? *type->category : null_category;
```
Comment (illi-kun) [inline src/item.cpp]: This creates empty category:
capture

Can we set 'OTHER' instead of null?
