### PR TITLE
Fix monster over reach

### LINKED ISSUE #47980: Monster's stretch_attack can hit through z-levels and around(through?) several tiles of walkable terrain
# Describe the bug

If you're at z-level N, and there's a monster nearby (XY-wise) at z-level N-1, that monster can attack you with stretch_attack even if there is no straight(ish) line of attack.

# Steps To Reproduce

load the [save](https://drive.google.com/file/d/1VzrvV8ilDtkuJiuDhztpa3Gd1qreKdt1/view?usp=sharing), walk around or slightly to the east, see uncanny dodge proc because of `huge dragonfly naiad` attacking you from below despite there being 3 or 4 tiles of a bridge its attack have to go around. More info here https://github.com/CleverRaven/Cataclysm-DDA/issues/47945#issuecomment-795712539

# Expected behavior

either find_clear_path should only work at same z-level, or there should be another function find_clear_and_somewhat_straightish_path for the purposes of deciding if stretch_attack can hit. Also, the length of the path should be a limiting factor: there's a check of straight (sqrt(x2+y2+z2)) distance here
~~~~
    if( distance < 2 || distance > 3 || !z->sees( *target ) ) {
        return false;
    }
~~~~
but the "straight" path is either calculated straight through the bridge pavement or is way longer than that.

# Versions and configuration

    OS: Windows 7x64
    Game Version: 0.E-9955-g425255a [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills],
    Bionic Professions [package_bionic_professions],
    Ye olde Aftershock vehicle parts [afs_veh_goodies]
    ]

# Additional context

`stretch_bite` and `longswipe` use almost the same code, probably should be checked too.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
None

#### Purpose of change
Fixes #47980 
Stretch attacks were hitting the player in situations where a wall should intervene.
Specifically, with a monster on z=0 adjacent to a building, and the player two tiles away on the roof.
i.e.   MW@
Where M is the monster on the ground, W is an intervening wall/rooftop, and @ is a player standing on the rooftop.

#### Describe the solution
Added a unit test for the situation.
Limit stretch attacks targeting enemies on a different z-level to adjacent targets.  These attacks have a range of 3 when on the same z-level, but only one when targeting a different z-level.

#### Describe alternatives you've considered
The underlying LOS check is incorrect, but that is not a can of worms I want to crack open right now, plus this change is arguably correct even when accounting for the los change since the distance between z-levels is greater than the distance between adjacent tiles.
On that note, another potential fix is making rl_dist() reflect vertical level changes differently, but again that's a big can of worms to open right now.

#### Testing
New test passes, manually reproduced scenario in-game as well, and it works as intended after the change.

### CODE REVIEW

**Comment by actual-nh** [comment]
@jbytheway: You might want to take a look at the clang-tidy failure, unless you've already seen it elsewhere.

**Comment by jbytheway** [comment]
> @jbytheway: You might want to take a look at the clang-tidy failure, unless you've already seen it elsewhere.

I hadn't, and I don't understand it.  `click` is installed during the prepare step, but missing during the build step.  Weird...

File: src/monattack.cpp [hunk 1]
```diff
@@ -4094,7 +4094,12 @@ bool mattack::stretch_bite( monster *z )
     // Let it be used on non-player creatures
     // can be used at close range too!
     Creature *target = z->attack_target();
-    if( target == nullptr || rl_dist( z->pos(), target->pos() ) > 3 || !z->sees( *target ) ) {
+    int distance = rl_dist( z->pos(), target->pos() );
```
Comment (BrettDong) [inline src/monattack.cpp:4097]: Now there is a risk of dereferencing a `null` `target` pointer.

Comment (BrettDong) [inline src/monattack.cpp:4097]:
```suggestion
    if( target == nullptr ) {
        return false;
    }
    int distance = rl_dist( z->pos(), target->pos() );
```

File: src/monattack.cpp [hunk 2]
```diff
@@ -4094,7 +4094,12 @@ bool mattack::stretch_bite( monster *z )
...
+    // Hack, only allow attacking above or below if the target is adjacent.
+    if( z->pos().z != target->pos().z ) {
+        distance += 2;
+    }
+    if( target == nullptr || distance > 3 || !z->sees( *target ) ) {
```
Comment (BrettDong) [inline src/monattack.cpp:4102]:
```suggestion
    if( distance > 3 || !z->sees( *target ) ) {
```

File: tests/monster_attack_test.cpp [hunk 3]
```diff
@@ -148,3 +148,22 @@ TEST_CASE( "monster_attack", "[vision][reachability]" )
...
+    clear_map();
+    restore_on_out_of_scope<time_point> restore_calendar_turn( calendar::turn );
+    calendar::turn = daylight_time( calendar::turn ) + 2_hours;
+    scoped_weather_override weather_clear( WEATHER_CLEAR );
+    restore_on_out_of_scope<bool> restore_fov_3d( fov_3d );
+    fov_3d = GENERATE( false, true );
+    override_option opt( "FOV_3D", fov_3d ? "true" : "false" );
+    get_map().ter_set( attacker_location + tripoint{ 2, 0, 0 }, ter_id( "t_wall" ) );
+    get_map().ter_set( attacker_location + tripoint{ 2, 0, 1 }, ter_id( "t_floor" ) );
+    get_map().ter_set( attacker_location + tripoint{ 1, 0, 0 }, ter_id( "t_wall" ) );
```
Comment (kevingranade) [inline tests/monster_attack_test.cpp:163]:
```suggestion
    get_map().ter_set( attacker_location + tripoint_east, ter_id( "t_wall" ) );
```
