### PR TITLE
Persist vehicle tracking status when folding

### LINKED ISSUE #59334: Folding a vehicle causes you to forget its position
### Describe the bug

Whether or not this is a "bug" is debatable. An unfolded vehicle can have its position remembered so that its position can be shown on the map screen. Folding the vehicle and then unfolding it again makes your character forget they were supposed to remember it.

### Steps to reproduce

1. Take any folding vehicle and unfold it.
2. Remember this vehicle
3. It should show up on the map
4. Fold the vehicle, then unfold it again
5. It won't show up on the map anymore

### Expected behavior

When the vehicle is folded into an item, I don't think it should be expected that your character can remember the _item's_ position. But when it's unfolded, seems reasonable for your character to start remembering the _vehicle's_ position again. This is especially useful for small vehicles like folding carts that are easy to lose track of.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1826 (21H2)
- Game Version: 554df77 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    No Hope [no_hope],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by irwiss**
#### Summary
Interface "Persist vehicle's tracked position toggle when folding"

#### Purpose of change

Fixes #59334

#### Describe the solution

Save tracking state into folded item's item_vars, restore when unfolding.

#### Testing

Get a foldable vehicle, `e` -> remember position, fold, unfold, see it's not tracked on map anymore.
Debug a `folding bicycle`, activate, remember position, fold, unfold, see it's not tracked on map anymore.
Apply patch
Get a foldable vehicle, `e` -> remember position, fold, unfold, see it's tracked (and message appears in log)
Debug a `folding bicycle`, activate, remember position, fold, unfold, see it's tracked (and message appears in log)

Just to make sure I did a save/load cycle and it keeps the item_vars intact on the folding bicycle too

#### Additional context

Considered adding a bool to `vehicle::toggle_tracking` to suppress the tracking toggle message when unfolding,
but I don't think it's that annoying (might be to screen readers though?) and might be informative
image

### CODE REVIEW

**Review by anothersimulacrum — APPROVED** [review]

**Comment by mlange-42** [comment]
Unfortunately, this does not work for `folding bicycle`, as spawned as an item.

Just finished a fix for #59334 when I saw this PR. I `set_var` outside `if( can_be_folded )` condition, and it works there. (Honestly, it is not really clear to me what `can_be_folded` means here.) See the diff here: https://github.com/CleverRaven/Cataclysm-DDA/compare/master...mlange-42:Cataclysm-DDA:track-folded-vehicle?expand=1

File: src/vehicle_use.cpp [hunk 1]
```diff
@@ -983,6 +983,7 @@ bool vehicle::fold_up()
         bicycle.set_var( "volume", total_folded_volume() / units::legacy_volume_factor );
         bicycle.set_var( "name", string_format( _( "folded %s" ), name ) );
         bicycle.set_var( "vehicle_name", name );
+        bicycle.set_var( "tracking", tracking_on ? 1 : 0 );
```
Comment (mlange-42) [inline src/vehicle_use.cpp:986]: Unfortunately, this does not work for `folding bicycle`, as spawned as an item.

Just finished a fix for #59334 when I saw this PR. I `set_var` outside `if( can_be_folded )` condition, and it works there. (Honestly, it is not really clear to me what `can_be_folded` means here.) See the diff here: https://github.com/CleverRaven/Cataclysm-DDA/compare/master...mlange-42:Cataclysm-DDA:track-folded-vehicle?expand=1

Comment (irwiss) [reply src/vehicle_use.cpp]: Seems `can_be_folded` is the "new" folding vehicles, `convertible` is the "old" hacky folding bicycle which has like 4 bug reports assigned to it and needs another place to handle that

Adjusted to handle both types according to your snippet

I tried to do the coauthoring thing, not sure it actually worked but it shows your icon next to the new commit now

**Review by mlange-42 — APPROVED** [review]

**Review by anothersimulacrum — APPROVED** [review]
