### PR TITLE
Fix unwielding/wearing removing items

### LINKED ISSUE #17362: Weapons disappearing when switched out and worn with shoulder strap.
Version 0.C-15797-g7dc0086 (tiles)
Build 5125 
Clean world, no mods selected.

Wielding a weapon with a shoulder strap, and swapping to something else. Choosing to wear the gun makes it disappear enitrely - not in inventory, on the ground nearby.
Holsters still work, just the strap doesn't.
Whatever mods are attached to the gun are removed when it disappears, including the strap.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Fixes #17362

### CODE REVIEW

**Comment by mugling** [comment]
An alternative fix could be `spill_contents` checking for `is_bucket`?

**Comment by mugling** [comment]
Still bugged after this patch:

1. Spawn Ruger 10/22 and insert magazine
2. Ensure both insufficient space in inventory and empty hands
3. Try to pickup the Ruger 10/22
4. Get prompt to wield item (correct) and disabled option to spill Ruger 10/22 then pickup

**Comment by Coolthulhu** [comment]
Fixed, spilling should only be offered for buckets now.

It would make sense to allow spilling non-rigid containers, but it would be some more advanced math.

File: src/item.cpp [hunk 1]
```diff
@@ -3661,6 +3661,10 @@ bool item::can_contain( const itype &tp ) const
 
 bool item::spill_contents( Character &c )
 {
+    if( is_container_empty() || !is_container() ) {
```
Comment (mugling) [inline src/item.cpp]: Why not `!is_bucket()`?

Comment (Coolthulhu) [inline src/item.cpp]: It could technically work and be useful for other things.
For example, waterskins too full to fit in inventory without spilling. Destroyed items, which currently drop their contents with hardcoded loops (this one would be quite useful).

Comment (mugling) [inline src/item.cpp]: Fair enough but I'd invert the order of the conditional - it both reads better that way and maybe more efficient

Comment (Coolthulhu) [inline src/item.cpp]: `is_container_empty()` checks just `contents.empty()`, meaning speed difference would be negligible. I'll change for readability, though.

Comment (mugling) [inline src/item.cpp]: Fair enough, it just reads nicer that way 'if its not a container of it's empty don't do anything'

**Comment by Coolthulhu** [comment]
Is this being tested? I'm starting a mergetest run and I don't want to cause conflicts.

**Comment by mugling** [comment]
Sorry yes, let me check your latest change now
