### PR TITLE
Deadened hide health even when using bandages

### LINKED ISSUE #38015: Deadened mutation: inconsistent prevention of showing limb health values
# Describe the bug

I have a character with this mutation. She also have Self-aware as a starting trait. In sidebar, limb status is shown as "good". I asked in forum, and people say Deadened overrides Self-aware for purpose of knowing exact limb health, you can only see either "good" or "damaged"(or w/e). Okay, fine, I guess?
...No. If I try using bandage or antiseptic, the menu with limb choice will show exact health values instead of "good" (or stick indicators).
So, the question is: what is the bug exactly? Deadened overriding Self-aware in sidebar, or bandage/antiseptic usage menu showing exact numbers while it shouldn't?

# Steps To Reproduce

1. Make a character with deadened+selfaware and a bandage
2. Look at the sidebar, see "good"
3. Try using the bandage, see exact limb health

# Expected behavior

Either it should override SA everywhere, or it should not apply at all.

# Versions and configuration

- OS: Windows 7x64
- Game Version: 0.D-12235-g3a8c5fb [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Interface "Deadened hide health even when using bandages"```

#### Purpose of change
Fixes #38015 

#### Describe the solution
Make the bandage window show Good/Bad instead of bars for characters with the NO_PAIN trait

Below 25% `Very Bad`
Between 25% and 50 % `Bad`
50% and 75% `Okay`
Above 75% `Good`

#### Testing
image

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -5226,6 +5226,12 @@ hp_part Character::body_window( const std::string &menu_header,
         } else if( limb_is_broken ) {
             desc += colorize( _( "It is broken.  It needs a splint or surgical attention." ), c_red ) + "\n";
             hp_str = "==%==";
+        } else if( has_trait( trait_NOPAIN ) ) {
+            if( current_hp < maximal_hp / 2 ) {
```
Comment (Qrox) [inline src/character.cpp]: It should probably be less coarse than this. Having no pain doesn't mean one can't notice large wounds on their body by sight.

File: src/character.cpp [hunk 2]
```diff
@@ -5226,6 +5226,12 @@ hp_part Character::body_window( const std::string &menu_header,
...
+                hp_str = colorize( string_format( " %s", _( "Bad" ) ), c_red );
```
Comment (BevapDin) [inline src/character.cpp]: Does this really need to go via `string_format`? It just adds a space in front of the word. A space that is not even needed. The other branches don't add a space in front of the string. And below where `hp_str` is actually used, a space is added anyway. So why add a space here?
```suggestion
                hp_str = colorize( _( "Bad" ), c_red );
```

**Comment by KorGgenT** [comment]
hmm, i think we could pick a better word for "Less Good". maybe "Ok"?

**Comment by Night-Pryanik** [comment]
> hmm, i think we could pick a better word for "Less Good". maybe "Ok"?

Mediocre?
