### PR TITLE
fix speedloader code

### LINKED ISSUE #42340: Marlin 39A Loading Bug
# Describe the bug

Cant load the Marlin 39A

# Steps To Reproduce

Get a Marlin 39A
cant be reloaded via single bullet nor speedloader

# Expected behavior

Normally reloadable single loading 19 Round 22LR chamber that can be loaded either single bullet or via speedloader.
neither works atm

# Screenshots

bugbug2
bugbug

# Versions and configuration

Newest Experimental
Tiles
Windows 10
English

# Additional context

-

### LINKED ISSUE #42724: Mosin (and potentially other non-detachable-mag weapons) bugged; speedloaders do not work
# Describe the bug

Mosin spits out error on firing; can't be reloaded with clip.
Also it seems like I cannot use speedloaders. 
image

# Steps To Reproduce

1. Make a player with a Mosin, Mosin clip, and some compatible ammo (54mmR).
2. Try to aim at a wall.
3. Fire.

or

1. Make a player with a an L2037 Backup (unloaded) and a LW-5 speedloader (5/5 loaded with .223).
2. Reload the revolver.
3. Fail.

# Expected behavior

I expect no errors and for the clip to be usable as a speedloader, but what I get is an incompatible clip as if it's from a different gun and this error when I fire:
image
Or it just doesn't recognize that I have it.
# Screenshots

Do not take a screenshot of the crashing window. Please provide the crash logs in the "Additional context" -->

# Versions and configuration

 - OS: Win7x64
 - Game Version: 0.E-4851-g7d816ea
 - Graphics version: Tiles
 - Ingame language: Eng
 - Mods loaded: Default NPCs need no food mod.

# Additional context

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
```SUMMARY: Bugfixes "Fix speedloader code and related json"```

#### Purpose of change
Fixes #42340
Fixes  #42724
and any related issues to do with spedeloaders

#### Describe the solution
1) identify the part of the code that made it so speedloaders were not selectable int he reloading interface
2) remove the magazine_compatible calls in order to see the reloading with speedloaders work
3) remove the extra magazine_well pocket in all related guns
4) add consistency check so items can't have more than one mgazine pocket without an error message
5) add allowed_speedloaders whitelist to pocket_data, so you can make a MAGAZINE pocket compatible with specific speedloaders. default behavior when not loaded is "everything is compatible"

#### Testing
Spawned in a S&W 619 and Marlin 39 A to test the speedloaders.

### CODE REVIEW

**Comment by wapcaplet** [comment]
This will fix #42724 as well:
- Marlin 39A with attached strap can be reloaded
- Mosin 1891/30 with attached strap can be reloaded
- L2037 can be reloaded with LW-5 speedloader

File: src/item_pocket.cpp [hunk 1]
```diff
@@ -1321,6 +1322,15 @@ bool item_pocket::airtight() const
     return data->airtight;
 }
 
+bool item_pocket::allows_speedloader( const itype_id &speedloader_id ) const
+{
+    if( data->allowed_speedloaders.empty() ) {
+        return true;
```
Comment (AMurkin) [inline src/item_pocket.cpp:1328]: Shouln't it be `false`?
```suggestion
        return false;
```

Comment (KorGgenT) [reply src/item_pocket.cpp:1328]: i did do that on purpose but i'm not exactly married to that decision

Comment (wapcaplet) [reply src/item_pocket.cpp:1328]: What is the reason to make it `true`? If a pocket does not allow any speedloaders at all, why would it allow a specific speedloader?

Comment (wapcaplet) [reply src/item_pocket.cpp:1328]: For example, with this logic, it appears that I can reload my COP .357 4-round Derringer with a 5-round, 6-round, or 7-round speedloader:

image
