### PR TITLE
Fix spells crashing when they can't find a target.

### LINKED ISSUE #34813: Casting spell with "RANDOM_TARGET" without a valid target in range leads to fatal crash
# Describe the bug

I was testing this feature in my project, then this crash suddenly appears.

# Steps To Reproduce

1. Create a spell (any type) with "RANDOM_TARGET" flag and `hostile` only as a valid target. Set it at minimal range.
2. Cast it alone.
3. There goes the crash.

# Expected behavior

Spell has to be cancelled if there's no valid target in range.

# Screenshots

Not helpful, but crash log may help.

# Versions and configuration

 - OS: Windows 10
 - Game Version: VERSION: 0.D-8583-g08353e3
 - Graphics version: Tiles
 - Mods loaded: (nothing actually affects this...)

# Additional context

Well, this is the crash log.

CRASH LOG FILE: config/crash.log
VERSION: 0.D-8583-g08353e3
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
    @0x5BD805[cataclysm-tiles.exe+0x1BD805]
    @0x5BE2D2[cataclysm-tiles.exe+0x1BE2D2]
    SMPEG_error+0x4B034@0xF9BD40[cataclysm-tiles.exe+0xB9BD40]
    _C_specific_handler+0x98@0x7FFA203C8048[msvcrt.dll+0x28048]
    _chkstk+0x11F@0x7FFA21C411FF[ntdll.dll+0xA11FF]
    RtlRaiseException+0x399@0x7FFA21C0A289[ntdll.dll+0x6A289]
    KiUserExceptionDispatcher+0x2E@0x7FFA21C3FE6E[ntdll.dll+0x9FE6E]
    IMG_LoadWEBP_RW+0x58F68A@0x161D23A[cataclysm-tiles.exe+0x121D23A]
    @0x8E21C9[cataclysm-tiles.exe+0x4E21C9]
    @0x8E2B71[cataclysm-tiles.exe+0x4E2B71]
    @0x4334B3[cataclysm-tiles.exe+0x334B3]
    @0x450D80[cataclysm-tiles.exe+0x50D80]
    @0xCC844B[cataclysm-tiles.exe+0x8C844B]
    @0x6A66AA[cataclysm-tiles.exe+0x2A66AA]
    @0x6F510D[cataclysm-tiles.exe+0x2F510D]
    IMG_LoadWEBP_RW+0x6143D8@0x16A1F88[cataclysm-tiles.exe+0x12A1F88]
    @0x4013ED[cataclysm-tiles.exe+0x13ED]
    @0x4014FB[cataclysm-tiles.exe+0x14FB]
    BaseThreadInitThunk+0x14@0x7FFA204F7BD4[KERNEL32.DLL+0x17BD4]
    RtlUserThreadStart+0x21@0x7FFA21C0CED1[ntdll.dll+0x6CED1]

### PR DESCRIPTION
**Pull request by BevapDin**
```SUMMARY: None```

Fixes #34813.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -4440,14 +4440,19 @@ void activity_handlers::spellcasting_finish( player_activity *act, player *p )
             }
         } while( !target_is_valid );
     } else if( casting.has_flag( RANDOM_TARGET ) ) {
-        target = casting.random_valid_target( *p, p->pos() );
+        const cata::optional<tripoint> target_ = casting.random_valid_target( *p, p->pos() );
+        if( !target_ ) {
+            p->add_msg_if_player( m_bad, _( "Your skill can't find a suitable target." ) );
```
Comment (Night-Pryanik) [inline src/activity_handlers.cpp]:
```suggestion
            p->add_msg_if_player( m_bad, _( "Your spell can't find a suitable target." ) );
```
