### PR TITLE
Fix mx_portal map extra spawning in air

### LINKED ISSUE #32326: set trap shimmering portal on top of terrain open air which already has a builit-in trap
# Describe the bug

When i was reaching a `research facility`.

```
	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	.../src/debug.cpp:621
	DebugLog(DebugLevel, DebugClass)
	.../src/debug.cpp:786
	realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
	.../src/debug.cpp:108
	std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/basic_string.h:657
	void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)
	.../src/debug.h:79
	std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/basic_string.h:657
	map::trap_set(tripoint const&, int_id<trap> const&)
	.../src/map.cpp:5174
	mtrap_set(map*, int, int, int_id<trap>)
	.../src/mapgen_functions.cpp:4555
	MapExtras::mx_portal(map&, tripoint const&)
	.../src/map_extras.cpp:812
	MapExtras::apply_function(string_id<map_extra> const&, map&, tripoint const&)
	.../src/map_extras.cpp:2496
	std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/basic_string.h:657
	string_id<map_extra>::~string_id()
	.../src/string_id.h:44
	MapExtras::apply_function(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, map&, tripoint const&)
	.../src/map_extras.cpp:2505
	map::generate(int, int, int, time_point const&)
	.../src/mapgen.cpp:159
	map::loadn(int, int, int, bool)
	.../src/map.cpp:6768 (discriminator 3)
	map::shift(int, int)
	.../src/map.cpp:6553 (discriminator 2)
	game::update_map(int&, int&)
	.../src/game.cpp:10440
	game::update_map(player&)
	.../src/game.cpp:10405
	map::displace_vehicle(tripoint&, tripoint const&)
	.../src/map.cpp:1104
	map::move_vehicle(vehicle&, tripoint const&, tileray const&)
	.../src/map.cpp:594
	vehicle::act_on_map()
	.../src/vehicle_move.cpp:1362
	map::vehproceed(std::vector<wrapped_vehicle, std::allocator<wrapped_vehicle> >&)
	.../src/map.cpp:419
	map::vehmove()
	.../src/map.cpp:374
	std::map<tripoint, submap*, std::less<tripoint>, std::allocator<std::pair<tripoint const, submap*> > >::begin()
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_map.h:355
	mapbuffer::begin()
	.../src/mapbuffer.h:65
	game::do_turn()
	.../src/game.cpp:1499
Backtrace emission took 1 seconds.
src/map.cpp:5175 [void map::trap_set(const tripoint&, const trap_id&)] set trap shimmering portal on top of terrain open air which already has a builit-in trap
```

17141af6c1ab649c0393fa4865f91ad19078cbb5

### PR DESCRIPTION
**Pull request by ralreegorganon**
#### Summary

SUMMARY: Bugfixes "Fix mx_portal map extra spawning in air"

#### Purpose of change

Fixes #32326

#### Describe the solution

Refactored the way in which the `mx_portal` map extra chooses its locations for the portal and monsters so that they are random locations that are actually valid for placement (e.g. not in the air, and without an existing trap).

#### Describe alternatives you've considered

The map extra itself is pretty mundane and could be made a bit more interesting or just retired/merged with the `mx_portal_in` map extra, but that's out of scope for fixing this bug.

#### Additional context

This issue mostly shows up in the research facility because it's one of the few locations that has the extra spawning at z > 0, has open air in those locations (e.g. the fancy atrium), and has a high enough density of extras to have a good chance of triggering this bug.

### CODE REVIEW

File: src/map_extras.cpp [hunk 1]
```diff
@@ -865,18 +866,50 @@ static void mx_supplydrop( map &m, const tripoint &/*abs_sub*/ )
...
+
+    // For our portal point and every adjacent location, make rubble if it doesn't have the NO_FLOOR flag.
+    for( const tripoint &p : m.points_in_radius( *portal_pos, 1 ) ) {
+        if( !m.has_flag_ter( TFLAG_NO_FLOOR, p ) ) {
+            m.make_rubble( p, f_rubble_rock, true );
         }
     }
-    mtrap_set( &m, x, y, tr_portal );
+
+    // Set the portal at our chosen location.
```
Comment (BevapDin) [inline src/map_extras.cpp]: Why are you repeating the code as comment?

**Comment by SpellingSword** [comment]
Had this just now. 

 DEBUG    : set trap shimmering portal on top of terrain open air which already has a builit-in trap

 FUNCTION : void map::trap_set(const tripoint&, const trap_id&)
 FILE     : src/map.cpp
 LINE     : 5294
