### PR TITLE
Make disassembly resumable, add progress counter to activity actors

### LINKED ISSUE #44561: Disassembly can take a day and can't be interrupted
# Describe the bug
When disassembling specific clothing, like a faux fur coat, it takes up to one day to disassemble it properly. But, like it was in the old days with crafting, you can't interrupt it for anything (sleep, drink (auto drink doesn't seem to work for me in the new experimental), something knocking at your door). Nothing is more annoying than going up to 90-95% completion and then having some zombie coming in for a visit asking for sugar. Then you have to start all over again. Are there plans to make it "crafting" like? Which makes more sense than having the object being poofed away at 100% and still okay at 99%.

# Steps To Reproduce

1. Disassamble some clothing with a estimated time of 1 day
2. wait or press 5 to cancel
3. rinse and repeat.

# Expected behavior
Having it as a "pseudo"-craftable object, like we have with crafting now. So we can stop it anytime and go on later. WIth the upside, that the object in question is no longer usable for normal usage (as it should be when disassembling something.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6459-ge49eaa0 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Stats Through Skills [StatsThroughSkills],
    Fewer Farms [Fewer_Farms],
    Nonperishable Overhaul [Nonperishable_Overhaul],
    Graphical Overmap [Graphical_Overmap]
]

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Make disassembly resumable, add progress counter to activity actors"

#### Purpose of change
Fixes  #44561
Make disassembly create an in progress item like crafting does so it can be stopped and resumed later.  Also added default progress display to activity_actor, such as digging, consuming, etc

#### Describe the solution
1st Commit is moving disassemble from activity handler to activity actor.
2nd Commit is adding a default progress display to activity actor to display turn by turn progress.
3rd Commit is adding and hooking up the in progress disassembly item

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -391,6 +392,39 @@ item::item( const recipe *rec, int qty, std::list<item> items, std::vector<item_
     }
 }
 
+item::item( const recipe *rec, item component )
```
Comment (anothersimulacrum) [inline src/item.cpp:395]: Does this need to be making a copy of the item?

**Comment by kevingranade** [comment]
Ran into what I think is a pre-existing issue that this makes more... apparent.
If you disassemble a container with contents, the contents will be bundled into the disassembly item and inaccessible until disassembly completes.

**Comment by Ramza13** [comment]
> Ran into what I think is a pre-existing issue that this makes more... apparent.
> If you disassemble a container with contents, the contents will be bundled into the disassembly item and inaccessible until disassembly completes.

Ahh so instead we should instantly drop all contents first?  That makes sense, and I can add that behavior.

File: data/json/items/generic.json [hunk 2]
```diff
@@ -2953,6 +2953,20 @@
     "use_action": [ "CRAFT" ],
     "flags": [ "NO_SALVAGE", "TRADER_AVOID", "CAN_HAVE_CHARGES" ]
   },
+  {
+    "type": "GENERIC",
+    "id": "disassembly",
+    "symbol": "%",
+    "color": "white",
+    "name": { "str": "in progress disassembly" },
+    "description": "This is an in progress disassembly.",
```
Comment (actual-nh) [inline data/json/items/generic.json:2962]:
```suggestion
    "name": { "str": "in-progress disassembly" },
    "description": "This is an in-progress disassembly.",
```
Could also be "in-process" or "incomplete".

File: src/activity_actor.cpp [hunk 3]
```diff
@@ -2525,6 +2524,95 @@ std::unique_ptr<activity_actor> milk_activity_actor::deserialize( JsonIn &jsin )
...
+{
+    item *disassembly = target.get_item();
+
+    // item_location::get_item() will return nullptr if the item is lost
+    if( !disassembly ) {
+        who.add_msg_player_or_npc(
+            _( "You no longer have the in progress disassembly in your possession.  "
+               "You stop disassembling.  "
+               "Reactivate the in progress disassembly to continue disassembling." ),
+            _( "<npcname> no longer has the in progress disassembly in their possession.  "
```
Comment (actual-nh) [inline src/activity_actor.cpp:2537]:
```suggestion
            _( "You no longer have the in-progress disassembly in your possession.  "
               "You stop disassembling.  "
               "Reactivate the in-progress disassembly to continue disassembling." ),
            _( "<npcname> no longer has the in-progress disassembly in their possession.  "
```
Ditto.

File: src/activity_actor.cpp [hunk 4]
```diff
@@ -2525,6 +2524,95 @@ std::unique_ptr<activity_actor> milk_activity_actor::deserialize( JsonIn &jsin )
...
+    if( !check_if_disassemble_okay( target, who ) ) {
+        act.set_to_null();
+        return;
+    }
+
+    // We already checked if this is nullptr above
+    item *craft = target.get_item();
+    double counter = craft->item_counter;
+
+    act.moves_left = moves_total - ( counter / 10'000'000.0 ) * moves_total;
```
Comment (actual-nh) [inline src/activity_actor.cpp:2567]: The "quote marks" above are, umm, rather confusing.

File: src/crafting.cpp [hunk 5]
```diff
@@ -2104,6 +2106,81 @@ ret_val<bool> Character::can_disassemble( const item &obj, const inventory &inv
...
+
+    item_location disassembly_in_world;
+
+    if( !has_two_arms() ) {
+        disassembly_in_world = set_item_map_or_vehicle( *this, pos(), new_disassembly );
+    } else if( !has_wield_conflicts( new_disassembly ) ) {
+        if( cata::optional<item_location> it_loc = wield_craft( *this, new_disassembly ) ) {
+            disassembly_in_world = *it_loc;
+        }  else {
+            // This almost certianly shouldn't happen
```
Comment (actual-nh) [inline src/crafting.cpp:2125]:
```suggestion
            // This almost certainly shouldn't happen
```
Is a debug message indicated here?

File: src/crafting.cpp [hunk 6]
```diff
@@ -2104,6 +2106,81 @@ ret_val<bool> Character::can_disassemble( const item &obj, const inventory &inv
...
+    } else {
+        enum option : int {
+            WIELD_CRAFT = 0,
+            DROP_CRAFT,
+            STASH,
+            DROP
+        };
+
+        uilist amenu;
+        amenu.text = string_format( pgettext( "in progress disassembly", "What to do with the %s?" ),
```
Comment (actual-nh) [inline src/crafting.cpp:2137]:
```suggestion
        amenu.text = string_format( pgettext( "in-progress disassembly", "What to do with the %s?" ),
```

File: src/crafting.cpp [hunk 7]
```diff
@@ -2104,6 +2106,81 @@ ret_val<bool> Character::can_disassemble( const item &obj, const inventory &inv
...
+        amenu.addentry( DROP, true, '4', _( "Drop it on the ground." ) );
+
+        amenu.query();
+        const option choice = amenu.ret == UILIST_CANCEL ? DROP : static_cast<option>( amenu.ret );
+        switch( choice ) {
+            case WIELD_CRAFT: {
+                if( cata::optional<item_location> it_loc = wield_craft( *this, new_disassembly ) ) {
+                    disassembly_in_world = *it_loc;
+                } else {
+                    // This almost certainly shouldn't happen
```
Comment (actual-nh) [inline src/crafting.cpp:2155]: Again, is a debug message indicated here?

File: src/item.cpp [hunk 8]
```diff
@@ -391,6 +392,39 @@ item::item( const recipe *rec, int qty, std::list<item> items, std::vector<item_
...
 
+item::item( const recipe *rec, item &component )
+    : item( "disassembly", calendar::turn )
+{
+    craft_data_ = cata::make_value<craft_data>();
+    craft_data_->making = rec;
+    std::list<item>items( { component } );
+    components = items;
+
+    if( is_food() ) {
```
Comment (actual-nh) [inline src/item.cpp:403]: This assumes that, if a combination isn't food, none of its components will be. Is this justified?

File: src/item.cpp [hunk 9]
```diff
@@ -1594,12 +1628,22 @@ void item::basic_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
...
             }
             if( is_craft() ) {
-                const std::string desc = _( "This is an in progress %s.  "
-                                            "It is %d percent complete." );
-                const int percent_progress = item_counter / 100000;
-                info.push_back( iteminfo( "DESCRIPTION", string_format( desc,
-                                          craft_data_->making->result_name(),
-                                          percent_progress ) ) );
+                if( typeId() == itype_disassembly ) {
+                    const std::string desc = _( "This is an in progress disassembly of %s.  "
```
Comment (actual-nh) [inline src/item.cpp:1632]:
```suggestion
                    const std::string desc = _( "This is an in-progress disassembly of %s.  "
```

File: src/item.cpp [hunk 10]
```diff
@@ -1594,12 +1628,22 @@ void item::basic_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
...
+                                                "It is %d percent complete." );
+                    const int percent_progress = item_counter / 100000;
+                    info.push_back( iteminfo( "DESCRIPTION", string_format( desc,
+                                              craft_data_->making->result_name(),
+                                              percent_progress ) ) );
+                } else {
+                    const std::string desc = _( "This is an in progress %s.  "
```
Comment (actual-nh) [inline src/item.cpp:1639]:
```suggestion
                    const std::string desc = _( "This is an in-progress %s.  "
```

File: src/item.cpp [hunk 11]
```diff
@@ -1594,12 +1628,22 @@ void item::basic_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
...
-                                          craft_data_->making->result_name(),
-                                          percent_progress ) ) );
+                if( typeId() == itype_disassembly ) {
+                    const std::string desc = _( "This is an in progress disassembly of %s.  "
+                                                "It is %d percent complete." );
+                    const int percent_progress = item_counter / 100000;
+                    info.push_back( iteminfo( "DESCRIPTION", string_format( desc,
+                                              craft_data_->making->result_name(),
+                                              percent_progress ) ) );
+                } else {
```
Comment (actual-nh) [inline src/item.cpp:1638]: Is there some reason this common code can't be shared?

File: src/item.cpp [hunk 12]
```diff
@@ -4591,7 +4636,12 @@ std::string item::tname( unsigned int quantity, bool with_prefix, unsigned int t
             maintext += string_format( "+%d", amt );
         }
     } else if( is_craft() ) {
-        maintext = string_format( _( "in progress %s" ), craft_data_->making->result_name() );
+        if( typeId() == itype_disassembly ) {
+            maintext = string_format( _( "in progress disassembly of %s" ),
```
Comment (actual-nh) [inline src/item.cpp:4640]:
```suggestion
            maintext = string_format( _( "in-progress disassembly of %s" ),
```

File: src/item.cpp [hunk 13]
```diff
@@ -4591,7 +4636,12 @@ std::string item::tname( unsigned int quantity, bool with_prefix, unsigned int t
...
+                                      craft_data_->making->result_name() );
+        } else {
+            maintext = string_format( _( "in progress %s" ), craft_data_->making->result_name() );
```
Comment (actual-nh) [inline src/item.cpp:4643]:
```suggestion
            maintext = string_format( _( "in-progress %s" ), craft_data_->making->result_name() );
```

**Review by actual-nh — COMMENTED** [review]
Just a few things. (I note the comment in src/item.h uses a hyphen/dash for "in-progress", which is what I suggest for the other cases.)

File: data/json/items/generic.json (hunk 2 above)
Comment (Ramza13) [reply data/json/items/generic.json:2962]: The reason it is the way it is is because that's how the existing in progress crafting item is named.  I agree that it looks nicer with a hyphen but don't want to add changing the crafting object name to this PR.  A PR to correct it for both once this merges seems like a good idea.

File: src/activity_actor.cpp (hunk 4 above)
Comment (Ramza13) [reply src/activity_actor.cpp:2567]: Its a convention used by the existing code for the usage of item counters as progress and in that context does make some sense, though I agree at first glance its weird.

File: src/item.cpp (hunk 8 above)
Comment (Ramza13) [reply src/item.cpp:403]: The goal here is to deal with rot so if the top level item isn't rotting then none of its components should either.  Honestly I am unsure if there even exist food items that can be disassembled so it might be a moot point.

**Comment by Ramza13** [comment]
Containers now spill as soon as you begin disassembling them.
