### PR TITLE
mission_companion: explicitly set end_line for each loop

### LINKED ISSUE #30548: Foreman Construction Missions Menu Crash
# Describe the bug
Crash with NPC Foreman at the ranch, after turning in "Collect 30 Glass Sheets" I went into the Construction Missions and scrolled down to the second option, when I scroll back up to the first option it crashes.

# Steps To Reproduce

Talk to Foreman, turn in quest.
Enter Construction Menu from "I figured you might be looking for some help" dialogue. 
Scroll down to the second option in the menu, and then scroll back to the first.

# Expected behavior

No crash D:

# Screenshots
unknown

The menu the crash happens in.

# Versions and configuration

- OS: Windows [64-bit]
- Game Version: 0.D-3019-g9dbe860
- Graphics Version: Tiles
- Mods loaded: 
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bens GF recipes [Tolerate_This],
    Craftable Gun Pack [craftgp],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Extended Realistic Guns [realguns],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Medieval and Historic Content [Medieval_Stuff],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Urban Development [Urban_Development],
    Boats [boats],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Disable Religious Texts [no_religious_Texts],
    No Ants [No_Anthills],
    No Fungal Monsters [No_Fungi],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills]

# Additional context

[Crash Logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3185217/Crash.Logs.zip)
[Springs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3185219/Springs.zip)

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "mission_companion: explicitly set end_line for each loop"```

#### Purpose of change
Fixes #30548 
Fixes a crash that occurs when scrolling through the companion mission assignment options due to an out of range error in this line `print_colored_text( w_info, start_line, 0, col, col, mission_text[start_line + info_offset] );`

#### Describe the solution
end_line was not always getting reset for each loop through the dialogue window, and sometimes could keep a previous iteration's value that was invalid for the current iteration.  This would cause an out of range crash when retrieving mission text.

### CODE REVIEW

**Comment by esotericist** [comment]
I don't know how I managed to make a single-comment review by accident, but whatevs.

Anyway I actually don't think this'll fix the real problem in all cases, and to the extent that it seemed to was probably by accident.

File: src/mission_companion.cpp [hunk 1]
```diff
@@ -480,9 +480,8 @@ bool talk_function::display_and_choose_opts( mission_data &mission_key, const tr
             .viewport_pos( info_offset )
             .viewport_size( info_height )
             .apply( w_info );
-            if( info_offset < mission_text.size() ) {
-                end_line = std::min( info_height, mission_text.size() - info_offset );
-            }
+            end_line = info_offset < mission_text.size() ?
```
Comment (esotericist) [inline src/mission_companion.cpp]:
```suggestion
            end_line = std::min( info_height, mission_text.size() - info_offset );
```

File: src/mission_companion.cpp [hunk 2]
```diff
@@ -480,9 +480,8 @@ bool talk_function::display_and_choose_opts( mission_data &mission_key, const tr
...
+                       std::min( info_height, mission_text.size() - info_offset ) : 0;
```
Comment (esotericist) [inline src/mission_companion.cpp]:
```suggestion
```

File: src/mission_companion.cpp (hunk 1 above)
Comment (esotericist) [reply src/mission_companion.cpp]: The conditional here is a vestige of previous logic, and should be handled by the same check above the invocation to `scrollbar()`.

`end_line` should be set basically every time.

**Comment by esotericist** [comment]
... I still can't figure out how to suggest changes to multiple lines at once. I feel dumb.

**Comment by esotericist** [comment]
By the by, the "Assign Ally to Menial Labor" entry should probably have *some* text?

**Comment by ZhilkinSerg** [comment]
> 
> 
> ... I still can't figure out how to suggest changes to multiple lines at once. I feel dumb.

Suggest removing all lines, but the first and add all new lines to first line suggestion.
