### PR TITLE
Corrected messages if NPC is screaming or howling

### LINKED ISSUE #24535: Shouting NPCs will interrupt you with message saying you are shouting yourself.
Game version: 0.C-29716-gc6c3ebb (tiles)

Operating system: Windows 10

Tiles or curses: Tiles

Mods active:   "dda",  "filthy_morale",  "novitamins",  "a_mutated_arsenal",  "makeshift",  "More_Survival_Tools",  "alt_map_key",  "mutant_npcs",  "npc_traits", "more_buildings",  "more_locations",   "Experimental-Z-Level",  "Urban_Development",  "boats",  "deoxymod",  "no_religious_Texts",  "more_classes_scenarios",  "no_reviving_zombies",  "StatsThroughSkills"

### Expected behavior

When an NPC with "shouter" shouts while you are reading, the game will ask you to stop because you heard your NPC shout.

### Actual behavior

It will ask you to stop because you heard yourself shout.

### Steps to reproduce the behavior

Start a game with the "npc_traits" default mod, acquire NPCs until you get one with "shouter" trait, and perform long actions until they shout while you are performing the action.

[dropbox link to a .7z file with my save and my mod folder to easily check if it was fixed.](https://www.dropbox.com/s/ubnoxjgpvu23ax7/save.7z?dl=0) There's an NPC with the shouter trait and some books nearby to read.

### LINKED ISSUE #25342: When reading with an allied NPC with Howler nearby, you will howl instead.
**Describe the bug**  
When your NPC ally has the Howler mutation, the game treats it as if you are mutated yourself when reading.

**To Reproduce**  
1. Befriend a NPC with the Howler mutation. I'm not sure if it applies to other noise making mutations if they exist. In my case the NPC was the starter NPC.
2. Try to read a book.

**Expected behavior**  
The NPC howls, instead of you.

**Screenshots**  
image
image
image (the NPC in question)

**Versions and configuration(please complete the following information):**
 - OS: on the SSH server.
 - Game Version: 0.C-30390-g94dfc59-dirty
 - Graphics version: Terminal
 - Mods loaded: 99% sure the relevant mod is Mutant NPCs

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Bugfixes "Corrected messages if NPC is screaming or howling'"```

#### Purpose of change
Closes #25342.
Closes #24535.

#### Describe the solution
Added `if_player` check for screaming and howling, and if it's not player (= npc), then show slightly different message.

#### Additional context
Before:
default

After:
default

### CODE REVIEW

**Comment by MT-Arnoldussen** [comment]
this should also close #24535

File: src/player.cpp [hunk 1]
```diff
@@ -2898,15 +2898,15 @@ void player::shout( std::string msg )
...
     }
 
     if ( has_trait( trait_SHOUT3 ) ) {
         shout_multiplier = 4;
         base = 20;
         if ( msg.empty() ) {
-            msg = _("yourself let out a piercing howl!");
+            msg = is_player() ? _("yourself let out a piercing howl!") : _("a piercing howl!");
         }
     }
```
Comment (kevingranade) [inline src/player.cpp]: One line down from here is the case for the shouter not having a mutation, missed that one.

File: src/player.cpp [hunk 2]
```diff
@@ -2941,11 +2941,15 @@ void player::shout( std::string msg )
...
 
     if( noise <= minimum_noise ) {
-        add_msg( m_warning, _( "The sound of your voice is almost completely muffled!" ) );
+        add_msg_player_or_npc( m_warning,
```
Comment (kevingranade) [inline src/player.cpp]: No need to print this one if a NPC is shouting, the player can't hear it anyway.

File: src/player.cpp [hunk 3]
```diff
@@ -2941,11 +2941,15 @@ void player::shout( std::string msg )
...
+                               _( "The sound of your voice is almost completely muffled!" ),
+                               _( "The sound of <npcname>'s voice is almost completely muffled!" ) );
         msg.clear();
     } else if( noise * 2 <= noise + penalty ) {
         // The shout's volume is 1/2 or lower of what it would be without the penalty
-        add_msg( m_warning, _( "The sound of your voice is significantly muffled!" ) );
+        add_msg_player_or_npc( m_warning,
+                               _( "The sound of your voice is significantly muffled!" ),
+                               _( "The sound of <npcname>'s voice is significantly muffled!" ) );
```
Comment (kevingranade) [inline src/player.cpp]: I'm not sure if this is needed, and if it is it needs to be worked into the sound description somehow instead of printed here, because that handles whether the player can hear it at all or not.

File: src/player.cpp (hunk 2 above)
Comment (Night-Pryanik) [reply src/player.cpp]: `noise <= minimum_noise`
NPC's shout could have volume 2, and if it is, player can hear it, right?

File: src/player.cpp (hunk 3 above)
Comment (Night-Pryanik) [reply src/player.cpp]: NPC says or shouts something, and the log provides us with info about it. I don't understand what's the problem.

Comment (kevingranade) [reply src/player.cpp]: Because the player might not be aware of it.

For example the player is deaf and the npc is on 5he other side of a wall, we shouldn't print a message.

File: src/player.cpp (hunk 1 above)
Comment (kevingranade) [reply src/player.cpp]: That's not critical 5hen, but might as well handle it.

**Comment by Night-Pryanik** [comment]
Reverted the special case for muffled voices of NPC, as reworking it as Kevin wants is out of scope of this PR.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild
