### PR TITLE
Only list solid items in wield menu

### LINKED ISSUE #41628: 'A'ctivating a First Aid Kit led to the antiseptic being on the floor spilled
# Describe the bug
Had 2 first aid kits - used `a` to `Get content`
Then the antiseptic & saline solution ended up spilled on the floor

# Steps To Reproduce
1. Have First Aid Kit
2. `a`ctivate to Get Content
3. See that antiseptic is on floor

# Expected behavior
Antiseptic is in a neat little bottle in your inventory.

# Screenshots
image

image

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-3550-g6770666a22 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
Built from hash `fc61c75b43`

### LINKED ISSUE #47488: Wield menu includes liquids
# Describe the bug

When using the `w`ield menu, liquids are displayed in the menu, although liquids can never be wielded.

# Steps To Reproduce

1. Obtain some liquids in containers (clean water, antiseptic, root beer, cough syrup, etc.)
2. Press `w` to wield - liquids are included in the wield menu, but they cannot be wielded

# Expected behavior

Liquids should never appear in the `w`ield menu, since liquids can never be wielded (regardless of whether they are spilled or not).

# Screenshots

image

Note, the red message says "Can't wield spilt liquids", but in fact you can't wield *any* liquids, so there is no reason to show them here.

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9603-g42468f6cab [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

# Additional context

This bug was mentioned in the comments of #41628

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
Interface "Only list solid items in wield menu"

#### Purpose of change
This fixes #41628 and fixes #47488, where liquids are listed in wield menu, but in fact the player can never wield any liquid. The UI display here was confusing.

#### Describe the solution
Only list solid phase items in `weapon_inventory_preset::is_shown`.

#### Describe alternatives you've considered
Do not change it.

#### Testing
Have some liquid items in the inventory or nearby, eg. a bottle of clean water, and press `w`. Note that the bottle containing water is listed in the menu which is the expected behaviour, and water itself is not displayed:
螢幕截圖 2021-02-13 下午11 18 20

#### Additional context
Before the patch, water is also listed:
螢幕截圖 2021-02-13 下午11 24 39

### CODE REVIEW

File: src/game_inventory.cpp [hunk 1]
```diff
@@ -1311,6 +1311,10 @@ class weapon_inventory_preset: public inventory_selector_preset
             }, _( "WIELD COST" ) );
         }
 
+        bool is_shown( const item_location &loc ) const override {
+            return !loc->made_of( phase_id::LIQUID );
```
Comment (ZhilkinSerg) [inline src/game_inventory.cpp:1315]: There are gas and plasma that should not be wielded too, so maybe it is better to check for `SOLID` instead?

Comment (BrettDong) [reply src/game_inventory.cpp]: Thank you for the suggestion! Updated to list `made_of( phase_id::SOLID )` items only.
