### PR TITLE
Fix zeds teleporting through doors when following player on stairs

### LINKED ISSUE #11451: Zeds following you upstairs ignore pathfinding
Zeds that are blocked by doors, and are following the character, magically get past the doors and emerge behind you when you go upstairs.

Here's the easiest way to reproduce this: Start in an evac shelter and go to the basement. Open the doors, and debug spawn a zombie in the chamber. Wait for the zombie to get within 2-3 tiles, and close the doors. Return to the surface, and the zombie will soon appear behind directly behind you.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9151706-zeds-following-you-upstairs-ignore-pathfinding?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
Zeds following through stairs use an ugly hack where they could teleport through things they'd bash if given the chance. This results in stupid situations where the player can go upstairs, kill following zeds, go back and find intact doors.

The stair-following hack got broken by some update and no one complained. Then I fixed pathfinding for NPCs (which got broken in bashable update, when `"BASHABLE"` terrain flag got removed), which brought back the stair-following hack back. Now complaints do happen, because the hack still hasn't been updated and the old, wonky behavior is still in.

In this PR I:
- Remove the ability of purely aquatic monsters to follow the player up/down stairs
- Remove the ability of following monsters to bypass bashable terrain they could bash

This of course results in the player being able to just close the door and go upstairs, leaving zeds unloaded until the player goes back, but the alternative is having zeds teleport through closed doors.

The monster stair hack is soon to be removed (z-level updated etc.), so adding more hacks just to keep this one hack running sounds rather counter-productive to me. It didn't work properly in 0.B and no one cared.

EDIT: Closes #11451

### CODE REVIEW

File: src/monmove.cpp [hunk 1]
```diff
@@ -1091,51 +1091,64 @@ void monster::knock_back_from(int x, int y)
...
 
- return false;
+    return false;
 }
 
 int monster::turns_to_reach(int x, int y)
 {
+    // Note: values in this function aren't turns, but "pairs of turns"
+    // This is because move_cost returns 2 for flat ground, 8 for rubble etc.
+    // This function is a(n old) temporary hack that should soon be removed
```
Comment (BevapDin) [inline src/monmove.cpp]: What pairs? I don't see any pairs in this function. `monster::move_to` decreases the moves of the monster by the value returns by `calc_movecost`.

Comment (Coolthulhu) [inline src/monmove.cpp]: Oh right, I missed the `calc_` part
