### PR TITLE
Fix consume crash for CBMs

### LINKED ISSUE #40512: Trying to (E)at with fuel for an installed CBM in range causes a crash.
# Describe the bug

Attempting to (E)at with valid fuel in range for a CBM you have installed causes a crash. Unloading the container and using "fuel bionic" option from that menu works, though.

# Steps To Reproduce

1.) Have/install a CBM that accepts some form of fuel.
2.) (E)at with a valid fuel for that CBM in range (in inventory, or on an adjacent tile).
3.) Crash.

# Expected behavior

Expected attempting to (E)at to bring up the (E)at menu.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-2124-g6b93842 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix a crash when trying to consume fuel for cbms"

#### Purpose of change
Fixes #40512
Prevents a null reference from crashing the game.

#### Describe the solution
Checked for null val

### CODE REVIEW

File: src/consumption.cpp [hunk 1]
```diff
@@ -1637,10 +1637,11 @@ time_duration Character::get_consume_time( const item &it )
                          5 ), 1 ) );  //Default 5 mL (1 tablespoon) per second
     float consume_time_modifier = 1;//only for food and drinks
     const bool eat_verb  = it.has_flag( flag_USE_EAT_VERB );
```
Comment (jbytheway) [inline src/consumption.cpp:1639]:
```suggestion
    const bool eat_verb = it.has_flag( flag_USE_EAT_VERB );
```

File: src/consumption.cpp [hunk 2]
```diff
@@ -1637,10 +1637,11 @@ time_duration Character::get_consume_time( const item &it )
...
-    if( eat_verb || it.get_comestible()->comesttype == "FOOD" ) {
+    if( eat_verb || ( it.get_comestible() != nullptr && it.get_comestible()->comesttype == "FOOD" ) ) {
```
Comment (jbytheway) [inline src/consumption.cpp:1640]: Maybe worth factoring out the common code.  Have something like
```
const std::string comest_type = it.get_comestible() ? it.get_comestible()->comesttype : "";
```
before the `if`.  Might be cleaner code, or might not.  Just an idea.
