### PR TITLE
Make engine-on spawning chance decrease over time

### LINKED ISSUE #35987: Cars loading around Refugee Center can spawn running
# Describe the bug

Not a high priority bug, but it seemed strange when a small horde of zombies came clambering at a window at the refugee center and I went outside to put them down and I saw that they were summoned by a running vehicle.  

# Steps To Reproduce

1. Goto Refugee Center
2. Are there cars spawned? 
3. Are some of them currently running?
4. Note that you can't interact to stop the sound without angering the Free Traders.
5. Guards also sometimes noticed the sound and wandered looking for it.

# Expected behavior

Cars outside the refugee center to not be running aimlessly as if abandoned by previous owners.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

 - OS: [e.g. iOS 8 or Windows 10 or Ubuntu 18.04]
 - Game Version: [from the main menu, e.g. 0.C-29938-g90f5268437]
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [e.g.dda, boats, hacktheplanet, StatsThroughSkills]

# Additional context

### PR DESCRIPTION
**Pull request by jkraybill**
#### Summary
```SUMMARY: Bugfixes "Make engine-on spawning chance decrease over time"```

#### Purpose of change
Fixes #35987 by decreasing the chance that vehicles spawn with their engines on, as a function of time.

#### Describe the solution
Previously, vehicles that spawned with working engines had those engines on 1/8 of the time.

This seems OK, except that it leads to lots of situations where a running vehicle is inexplicable -- if it's 60 days after the cataclysm, you don't expect to find an eighth of all abandoned working vehicles with their engine still running.

I originally removed the code that was making some vehicles spawn running, but after the feedback in #38490, I closed that PR and decided a compromise might be more acceptable.

Vehicles now spawn with their engine running with a chance equal to 1 / (days since apocalypse + 4), so 25% on day 0, down to 1/34 on day 30 and so on.

#### Describe alternatives you've considered
I do think vehicles never spawning with their engines running is a reasonable solution, but I think this is a decent solution also which just makes running cars progressively rarer as the game goes on.

A more realistic decay function could also be used, since it would probably be a rapid exponential decay in the real world, but I rejected that since a realistic decay function would probably be so close to "vehicles never spawn with engines running" that it doesn't seem worth debating that.

#### Testing
I spawned a bunch of megastores at different time values. At day = 0/1/2/3, it was easy but progressively rarer to find running vehicles; at day 30+ I didn't find any.

### CODE REVIEW

**Comment by NickGrease** [comment]
I always figured if I found a running car (30 days or 30 months) it was another survivor - maybe doing a quick smash and grab in surrounding buildings - or quickly abandoned when a horde was spotted - or dragged out of the drivers seat by some monstrosity... I guess my imagination is a little more... forgiving.

**Comment by pjf** [comment]
From a balance standpoint, should we force zero gas to some/all of the cars that would have been running without this change? (Essentially they were running, but have since run out of gas...)

**Comment by wapcaplet** [comment]
I like this solution much better than having no vehicles running at all. Even if the fuel math doesn't make total sense, I think that part is less important than the added gameplay factors introduced by sometimes-running vehicles. Could I jump in that car and drive it away? Maybe, if I clear all the zombies that were attracted to the noise. At least I know that car runs and has some gas I can come back for later . . . that kind of thing.

Anyway, nice work with so few lines changed.

**Comment by jkraybill** [comment]
@pjf I thought about that but it seemed too close to release to add content like that, plus that scenario is essentially already represented by zero-fuel working vehicles with keys, so this code represents the vehicles that are running but haven't run out of gas. I'd endorse a post-0.E enhancement of vehicle spawning scenarios -- e.g. running cars could spawn with evidence of a struggle nearby, or recently deceased survivors inside.

File: src/vehicle.cpp [hunk 1]
```diff
@@ -403,8 +403,11 @@ void vehicle::init_state( int init_veh_fuel, int init_veh_status )
     //Provide some variety to non-mint vehicles
     if( veh_status != 0 ) {
         //Leave engine running in some vehicles, if the engine has not been destroyed
+        //chance decays from 1 in 4 vehicles on day 0 to 1 in (day + 4) in the future.
+        int current_day = std::max( to_days<int>( calendar::turn - calendar::turn_zero ), 0 );
```
Comment (Night-Pryanik) [inline src/vehicle.cpp]: I think we should better use `calendar::start_of_cataclysm` instead of `calendar::turn_zero` here. Scenarios can override starting date, so if we start, for example, "The Next Summer" scenario, on turn 0 of this scenario we still have a decent chance to find a running vehicle despite ~9 months past the Cataclysm. The same for non-default (later) starting dates for ordinary scenarios.
