### PR TITLE
[CR] Limit weather seed size, noise generator unable to handle large values.

### LINKED ISSUE #13965: Broken weather generation
Weather generation seems to be broken in https://github.com/CleverRaven/Cataclysm-DDA/commit/16041b8b46820ca48f006bcfe07020392fc68cfb and newer.
It's always Flurries/Drizzle. No Perlin noise is generated, as you can see using «Display weather» tool in debug menu.
Savefile: https://mega.nz/#!Q50ChCIS!I4i6aLNZUsVF-gkjJeGAucycxtWrpCubyeYBoQo9My4
Mirror: https://yadi.sk/d/saY3OOWNkM6ai
Previous versions handle it well, creating dynamic weather.

I have tested different seed values in *.weather savefile.
If I change it to something like 10000, all works perfectly, but as it approaches to 100000000, non-drizzle areas become smaller and then disappear completely.
My build on GNU/Linux has MAX_RAND=2^31-1, so seed is nearly always greater than 100000000. Windows builds are not affected by this issue; it looks like they use MAX_RAND=2^15-1 and will never generate such seed. But if you load Linux-generated world in Windows client, you'll see the same constant Drizzle weather.
Tested on Debian 8 (g++ 4.9) curses and latest Windows curses/SDL builds from http://dev.narc.ro/cataclysm/jenkins-latest/Windows/

Simple fix in game.cpp:
```diff
- weatherGen.set_seed( rand() )
+ weatherGen.set_seed( rand() % 32767 )
```
I'm not sure if this is a good idea as I can't understand why large seed values was acceptable before this commit, but not after.

### PR DESCRIPTION
**Pull request by DanmakuDan**
Fixes #13965.

The simplex noise generator used in the weather system can't handle large rand values found in some non-Windows systems. This limits the values that can be generated from rand() and in older saves. Still looking for suggestion on how to handle the limitation.

### CODE REVIEW

File: src/savegame.cpp [hunk 1]
```diff
@@ -280,7 +280,9 @@ void game::load_weather(std::ifstream & fin) {
         int seed(0);
         std::stringstream liness(line);
         liness >> label >> seed;
-        weather_gen->set_seed( seed );
+        //limit seed size from old saves
+        //weather noise generator can't deal with large values
+        weather_gen->set_seed( seed % 32768 );
```
Comment (BevapDin) [inline src/savegame.cpp]: Looks like code (and comment) duplication. The limiting should be done in the weather generator (along with the comment).

Maybe it's even enough to do it inside `weather_generator::get_weather`, the only place where the seed is actually used. That would keep the existing saves unchanged (stored seed == loaded seed) and it would allow a later change to the calculations that may work again with bigger numbers.
