### PR TITLE
bugfix: barely overkilling creatures no longer gives you tons of meat

### LINKED ISSUE #27325: Explosion of meat after a Puno Strike on a Child Zombie
**Describe the bug**  
When you Overkill a zombie child with a Puno strike (Melee 3 Eskrima Weapon Martial art) using an expandable baton, the Child zombie explode with a meat shower. A couple of days ago, this would result in 10 tainted meat that would spawn around the corpse. Now it spawn around 80 to 200 Chunk of Tainted meat.

**To Reproduce**  
1. Make a Mall cop with 3 melee in the Mall Cop Scenario, wield an expandable baton and activate it. Now keep striking child zombies until one of them die to a Puno Strike (critical hit, 135 damage).

**Expected behavior**  
I was expecting that the Child zombie would drop an appropriate amount of meat after an overkill. I believe that 20 pound of tainted me from a single child zombie is too much.

**Screenshots**  

https://media.discordapp.net/attachments/252368751016542218/527544942269300758/unknown.png?width=812&height=457

image

**Versions and configuration(please complete the following information):**
 - OS: [e.g. Windows 10]
 - Game Version [from the main menu, e.g. 0.C-35812-g2e77bdf]
 - Graphics version [Retrodays]
 - Mods loaded [DDA, Disable NPC need, Simplified nutrition, Bens GF recipe, Craftable gun pack, Deadleave fictional gun, Extended realistic gun, Icecoon arsenal, Makeshift Items mod, Medieval and historical content, more survival tool, Mythological replicas, More location, Fuji's and Oa's building mod, More city's location, Arcana and Necromancy, Classes and scenario mod and Classic Roguelike classes]

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

https://drive.google.com/open?id=1_i6iafDMVCemxqP-p0lkAg5rOg7mnMP8

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Bugfixes "barely overkilling creatures no longer gives you tons of meat"```
#### Purpose of change

Fixes #27325
#### Describe the solution

pile_size in the scatter_chunks function is now capped to the total chunks of meat, and the input of that function is no longer the total number of chunks that could make up the monster

### CODE REVIEW

**Comment by KorGgenT** [comment]
jenkins rebuild

File: src/mondeath.cpp [hunk 1]
```diff
@@ -182,9 +184,9 @@ void mdeath::splatter( monster &z )
             // only flesh and bones survive.
             if( entry.type == "flesh" || entry.type == "bone" ) {
                 // the larger the overflow damage, the less you get
-                scatter_chunks( entry.drop, ( entry.mass_ratio / overflow_ratio / 10 * to_gram(
-                                                  z.get_weight() ) ) / to_gram( ( item::find_type( entry.drop ) )->weight ), z, gib_distance,
-                                to_gram( ( item::find_type( entry.drop ) )->weight ) / ( gib_distance - 1 ) );
+                int chunk_amt = entry.mass_ratio / overflow_ratio / 10 * to_gram( z.get_weight() ) / to_gram( (
```
Comment (Night-Pryanik) [inline src/mondeath.cpp]: Could be `const`.
