### PR TITLE
npc: various NPC AI fixes

### LINKED ISSUE #34173: NPC engagement rules invalid,  will attack every nearby enemies.
# Describe the bug

No matter which rule is selected, the NPC will engage every nearby enemy

# Steps To Reproduce

1. Recruit an NPC
2. Select engagement rule to "do not engage"
3. Spawn debug monster
4. NPC spontaneously move to attack the debug monster.

# Expected behavior

NPC should stay in place and not attack

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-7814-gfb08b0b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### LINKED ISSUE #40701: Companions bug
# Describe the bug

The game can't track companions properly - two additional companions I'd never met popped in the camp menu as available for work assignments. I was able to assign them to jobs, but the option to recover them was unavailable. One of them (or with the exact same name and nickname at least) would spawn when I created a new character (following the first one's death) and would immediately start walking away, unlike other default NPCs. 

EDIT: I followed the NPC, thinking he might be going to the job I assigned him as the previous character but no, he moved to an LMOE shelter about 20 tiles away. 

# Steps To Reproduce

1. Create a camp.
2. Find two NPCs you've never met as available for job assignment. 
3. Character died, one of these NPCs is the first one he meets in the shelter. 

# Expected behavior

Only have your current companions in the camp menu.

# Versions and configuration

0.E-2278-gf8f9f52
Windows 10

### LINKED ISSUE #40980: NPCs won't obey commands
# Describe the bug

 NPCs won't follow the combat commands, specifically the engagement rules. NPCs will always charge an enemy, regardless of your settings and (C)hat commands.

# Steps To Reproduce

1. Start a game on a map with the "Starting NPCs spawn" set to always.
2. Convince the NPC to join you.
3. Set their combat>engagement rules to "don't fight unless your life depends on it.
4. Roam around to find a hostile NPC, like a zombie, and run away. Your NPC will charge the zombies, ignoring your command.

# Expected behavior

 NPCs would ignore enemies and flee with you, only fighting if they're surrounded or grabbed.

# Versions and configuration

 OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-2702-ge4d9a10 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Stats Through Kills [stats_through_kills]
]

 - OS: Windows 7
 - Game Version: 0.E-2702-ge4d9a10 (tiles) (experimental)
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Stats Through Kills [stats_through_kills]

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "npc: various NPC AI fixes"```

#### Purpose of change
Fixes #40980 
Fixes #40701
Fixes #34173

Make NPCs actually disengage from combat when ordered to stay close to the avatar no matter what.

Make NPCs capable of getting into vehicles, even when the follow distance is less than the path length for the NPC to get into the vehicle.

Make NPCs that are ordered to not engage or stay in one place actually not engage or stay in one place.

#### Describe the solution
Add a new variable `must_retreat` which is set when `rule::follow_close` is `true` and the distance between NPC and avatar is more than `follow_distance`.  If `must_retreat` is true, NPCs do not evaluate other NPCs and monsters as possible targets, so they will be able to follow the avatar.

Change the ordering of `action_follow_player` and `action_follow_embarked` so that NPCs will try to get into a vehicle (which doesn't check if the NPC is within `follow_distance`) before they try to follow the avatar (which does).  This should fix the issue of an NPC with a low follow distance not being able to legally move to a position where they can access a door to get into a vehicle.

Add a new variable `self_defense_only` and change the minimum engage distance to weapon reach range if it is set.  NPCs with `self_defense_only` set do not move to engage monsters if their allies are threatened, only if they are threatened within by attackers within weapon range.

#### Testing
Spawned an NPC and various monsters and determined that the NPC would follow when ordered to, wouldn't engage unless ordered to, and would engage monsters that threatened the avatar even if the NPC wasn't threatened if the NPC had orders to engage nearby enemies.

#### Additional context
Stupid pea brain NPCs.

### CODE REVIEW

File: src/npcmove.cpp [hunk 1]
```diff
@@ -376,6 +376,22 @@ void npc::assess_danger()
         max_range = *confident_range_cache;
     }
     Character &player_character = get_player_character();
+    const bool self_defense_only = rules.engagement == combat_engagement::NO_MOVE ||
+                                   rules.engagement == combat_engagement::NONE;
+    const bool no_fighting = rules.has_flag( ally_rule::forbid_engage );
+    const bool must_retreat = rules.has_flag( ally_rule::follow_close ) &&
+                              !too_close( pos(), player_character.pos(), follow_distance() );
```
Comment (olanti-p) [inline src/npcmove.cpp:383]: I believe this makes NPCs with 'stick close to me, no matter what' rule ignore enemies if player tells them to guard a position and then walks away.
