### PR TITLE
Blazemod fixes

### LINKED ISSUE #18270: Blazemod Vortex components broken
At least in the most recent version I have (17944, haven't seen any PRs for blazemod since), there are two problems with the Vortex parts:
1. Neither one is capable of actually functioning. They seem to require a 'vortex core', and one is produced  in their recipes, but it doesn't seem possible to put that in your vehicle in any meaningful way. No 'vortex core holder' or anything.
2. The vortex generator produces only as much power as an upgraded solar panel. For such a high cost it is basically useless. Pretty sure it hasn't been updated for some new vehicles change or something. 1,000 battery wouldn't be unwarranted, considering its status as an endgame part.

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Mods "Update more of blazemod and make vortex parts work"```

#### Purpose of change
As part of #24730, update blazemod vortex and diamond parts to be reasonably functional.
Fixes #18270

#### Describe the solution
Adds a new PERPETUAL flag to indicate that no vehicle fuel is consumed by an engine fueled by a perpetual fuel or a perpetual reactor. The PERPETUAL flag is also used to replace a bunch of hardcoded checks to the muscle_fuel_type.

Adds PERPETUAL to the blazemod vpower and vortex generator. The vortex generator is now a perpetual motion machine that produces 37kW of electrical power. The vortex engine is now a 50 HP 
engine that consumes no fuel. This gives the vortex engine an interesting niche as a perpetual engine for small vehicles like motorcycles.

Cleaned up the various diamond and vortex parts, making all the diamond and vortex guns mountable on normal turrets, automated, etc.

Fix a bug where blob frames didn't have an INITIAL_PART, and you couldn't start vehicle construction with only blob frames at hand.

Added documentation for the changes.

#### Describe alternatives you've considered
I originally tried to make the vortex engine a very powerful engine with a very potent fuel, but the vehicle code will consume at least 1 charge of fuel per turn. That's mostly fine when a vehicle's fuel is 10,000 units of gasoline per 10L tank, but not very good when a vehicle's fuel is 100 units of vortex power.

Making the vortex engine a low power perpetual motion machine gives it an interesting niche as a fuel source for a nomad's motorcycle. You could already do a similar thing with a lot of solar panels, but that's a better solution for a medium sized deathmobile with lots of roof area. Now a nomad can have the same ability, but really only if they use a very small bike.

#### Additional comments
In the short term, since electric motors are impossibly efficient, you can use a vortex generator to produce enough power to run a large electric motor. I'm already planning to fix electric motors so I'm not worried about the issue.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
How do I reload vortex engines?

File: src/vehicle.cpp [hunk 1]
```diff
@@ -616,6 +616,12 @@ bool vehicle::is_engine_type( const int e, const itype_id  &ft ) const
     return part_info( engines[e] ).fuel_type == ft;
 }
 
+bool vehicle::is_perpetual_type( const int e ) const
+{
+    const itype_id  &ft = part_info( engines[e] ).fuel_type;
```
Comment (Night-Pryanik) [inline src/vehicle.cpp]: Excessive space before `&ft`.

Comment (mlangsdorf) [reply src/vehicle.cpp]: I see. I should fix that.

Comment (mlangsdorf) [reply src/vehicle.cpp]: Okay, now I don't see.
vortex engines are TOOLS, they don't have a tank capacity or ammo count. So they're not a valid fuel source for get_printable_fuel_types(), and don't display a fuel indicator,
 like so:
vortexenginefuelindicators

vortex generators are a little weird, because they show up in the Reactors list, but I don't think that's a problem.
vortexgeneratorfuelindicators
