### PR TITLE
Random NPC name fix. Delete legacy files after json conversion.

### LINKED ISSUE #13860: Setting default name overrides NPC names
ragnarok

First noticed when I got back into the game after a modding break, and decided I'd set a default name in case my fighter spawned somewhere Fun

I soon spammed the "spawn NPC" to test this and...yep. Hi, I'm Ragnar. And he's Ragnar. And so's she. I should've set my default name to Spartacus.

### PR DESCRIPTION
**Pull request by OzoneH3**
Give NPCs a random name instead of the default name: Fixes #13860

Delete legacy autopickup and worldoption files after json conversion.

### CODE REVIEW

File: src/auto_pickup.cpp [hunk 1]
```diff
@@ -771,7 +771,11 @@ void auto_pickup::load(const bool bCharacter)
 
     if( !fin.good() ) {
         if (load_legacy(bCharacter)) {
-            save(bCharacter);
+            if (save(bCharacter)) {
+                if(file_exist(sFile)) {
```
Comment (BevapDin) [inline src/auto_pickup.cpp]: Checking the existence is not necessary, `remove_file` works fine even when the file does not exist. It will simply return `false` (as deleting the file failed), but you're not checking the return value anyway, so it won't make any difference.
