### PR TITLE
Go bag is an activate item with updated contents

### LINKED ISSUE #22622: Filthy Go bag leads to filthy electronics, and filthy components
Game version: 0.C-25438-g7acb622

Operating system: Win 10x64

Tiles or curses: Tiles

Mods active:
* Standard ones
* StatsThroughSkills

### Expected behavior
Maybe only the clothes in the go bag should be filthy?

### Actual behavior
Disassembling the filthy go bag leads to filthy parts, even at the component level... Seems wrong?

### Steps to reproduce the behavior
* Get filthy go bag
* Disassemble
* Get filthy flashlight
* Disassemble
* Get lightstrip (unpowered) (filthy)
* Can't use it to craft lightstrip (unpowered) :(

### LINKED ISSUE #24060: Go-bags only give non-fitting apparel
### Expected behavior
When a go bag is disassembled into the various bits of military apparel there should be the standard chance of having some of it be fitting
### Actual behavior
None of the clothing/armor is fitting
### Steps to reproduce the behavior
Disassemble a go-bag

Something I’ve noticed for a while and keep forgetting to open an issue for. It makes go-bags a lot less useful than they should be and makes the profession that starts with one (National Guard, I think?) handicapped by having most of their starting equipment be ill fitting.

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary

```SUMMARY: Content "Go bag is an activate item with updated contents"```

#### Purpose of change

Fixes #22622 
Fixes #24060
Changes the way you get the contents of the go bag from disassemble to an activate function.

#### Describe the solution

The go bag item has always been a bit weird when it comes to getting the items from it because you needed to disassemble it. This lead to a few bugs such as not having clothes that fit, random item charges, or everything being filthy. Now you can no longer disassemble the go bag and instead you activate it to get your items. This has the following changes to the items:

- If the go bag is filthy, only the backpack and duffel bag will be filthy instead of every item.
- All batteries in the go bag and that are loaded into electronics in the go bag are now light batteries (high-capacity) with 150/150 charges, 
- The lighter in the go bag always has 100/100 charges.
- The National Guard profession now starts with a "personal go bag". It is mostly identical to the normal go bag except that it has a slightly different description and every item in the personal go bag is guaranteed to fit the player. The personal go bag doesn't spawn in the world, only normal go bags do.
- Wearable items in normal go bags that vary in size have the normal chance of either fitting you or not fitting you when the normal go bag is opened. However, all items of the same type will match in fitting or not. So either all the t-shirts fit you or none of them do.

Aside from these fixes, I took this chance to revisit the items that the go bag gives. I originally assumed that the go bag was a standard issue set of deployment gear used by all members of the National Guard. However, I couldn't find any information that this was true. Checking the other branches didn't give me any more information aside from them containing uniforms. Considering that a go bag is another name for a [bug-out bag](https://en.wikipedia.org/wiki/Bug-out_bag) and military members can make personal modifications to their standard issue bags, this seems like a good reason to improve the bag contents.

I've updated the go bag to contain gear more inline with short term survival instead of just holding a uniform. I build the contents with these guidelines:
- The go bag is a combination of a duffel bag and a backpack filled with items. Space of normal sized items isn't really an issue even with all of the military uniform items.
- The military uniform in the go bag is standard issue and nothing more. Weapons, extra armor, and equipment accessories would have been provided by the military had everything not gone wrong.
- The go bag contains supplies for surviving 24 hours. A normal go bag is for 72 hours but we can say that the National Guard member believed that the military would be able to feed them. They were very wrong.

Go bag contents:
- backpack
- duffel bag
- army helmet
- army jacket
- army pants
- chest rig
- compression top
- long underwear bottom
- pair of combat boots
- pair of tactical gloves
- 3x t-shirt
- 3x socks
- rain coat
- rain hood
- towel
- first aid kit
- flashlight (off) (150/150)
- lighter (100/100)
- light battery (high-capacity) (150/150)
- multi-tool
- pocket knife
- pair of ear plugs
- radio (off) (150/150)
- rollmat
- rolled sleeping bag
- MRE - Hash Browns & Bacon
- MRE - Macaroni Marinara
- MRE - Meatballs & Marinara
- 2x plastic bottle of clean water (2/2)

#### Describe alternatives you've considered

A lot of different items could be added to the go bag. I picked the ones that seemed the most common from the bug-out bag lists I've read and would be most useful in a zombie apocalypse.

### CODE REVIEW

File: src/iuse.cpp [hunk 1]
```diff
@@ -9187,6 +9187,79 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
+            g->m.add_item_or_charges( p->posx(), p->posy(), content );
+        }
+    }
+
+    p->i_rem( it );
+
+    return 0;
+}
+
+
```
Comment (alanbrady) [inline src/iuse.cpp]: Extra new line

File: src/iuse.cpp [hunk 2]
```diff
@@ -9187,6 +9187,79 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
+                content.put_in( water );
+            } else if( content_pair.first == "light_plus_battery_cell" ||
+                       content_pair.first == "flashlight" ||
+                       content_pair.first == "radio" ) {
+                content.ammo_set( "battery", 150 );
+            } else if( content_pair.first == "lighter" ) {
+                content.charges = 100;
+            }
+
+            g->m.add_item_or_charges( p->posx(), p->posy(), content );
```
Comment (alanbrady) [inline src/iuse.cpp]: `add_item_or_charges` does a full copy so I don't think you need to do the full loop for each `content_par.second`, just the add since they'll be identical yes?  I'm not sure someone would pack 3 random shirt sizes.

File: src/iuse.cpp [hunk 3]
```diff
@@ -9187,6 +9187,79 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
+        { "multitool", 1 },
+        { "1st_aid", 1 },
+        { "rollmat", 1 },
+        { "sleeping_bag_roll", 1 },
+        { "ear_plugs", 1 },
+        { "mre_hashbrownbacon_box", 1 },
+        { "mre_macaronimarinara_box", 1 },
+        { "mre_meatball_box", 1 },
+        { "bottle_plastic", 2 }
+    };
```
Comment (alanbrady) [inline src/iuse.cpp]: I'm not convinced there's a good reason to move this out of json.  Altering the contents now requires code changes/recompile and this is exactly the sort thing we have json parsing for.

File: data/json/items/armor.json [hunk 4]
```diff
@@ -4014,7 +4014,27 @@
...
+    "material": [ "cotton", "plastic" ],
+    "symbol": "[",
+    "color": "green",
+    "covers": [ "TORSO", "ARMS" ],
+    "coverage": 50,
+    "encumbrance": 35,
+    "warmth": 10,
+    "material_thickness": 3,
+    "flags": [ "BELTED", "WATER_FRIENDLY" ],
+    "use_action": "GOBAG"
```
Comment (alanbrady) [inline data/json/items/armor.json]: Use `copy-from` instead of explicitly copying the same fields.

File: src/iuse.cpp (hunk 3 above)
Comment (Hymore246) [reply src/iuse.cpp]: I'm not opposed to this but I'm not sure how to leave it in json and fix the bugs at the same time. Aside from #22622 and #24060, the lighter spawns with random charges and the batteries spawn with 0 charges. Is there a way to keep the item list with the item and fix all the bugs?

File: src/iuse.cpp [hunk 5]
```diff
@@ -9187,6 +9187,77 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
+    p->add_msg_if_player( _( "You empty the contents of the go bag onto the floor." ) );
+
+    item duffelbag = item( "duffelbag" );
+    item backpack = item( "backpack" );
+    if( it->has_flag( "FILTHY" ) ) {
+        duffelbag.set_flag( "FILTHY" );
+        backpack.set_flag( "FILTHY" );
+    }
+    g->m.add_item_or_charges( p->posx(), p->posy(), duffelbag );
+    g->m.add_item_or_charges( p->posx(), p->posy(), backpack );
```
Comment (BevapDin) [inline src/iuse.cpp]: Please use the 3D overload:
```suggestion
    g->m.add_item_or_charges( p->pos(), backpack );
```
Same above and below.

File: src/iuse.cpp (hunk 3 above)
Comment (ZhilkinSerg) [reply src/iuse.cpp]: Create an item group with specific amount of charges. If it is not allowed yet - change the code to make it possible.

**Comment by ZhilkinSerg** [comment]
Should put `magic` word before each issue number.

```
Fixes #22622
Fixes #24060
```

**Comment by TechyBen** [comment]
Will the future inventory stacking code change make this easily fixable? It could spawn as a backpack/pack with contents in it? :)

File: src/iuse.cpp [hunk 6]
```diff
@@ -9189,68 +9189,26 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
-        } else if( content_pair.first == "light_plus_battery_cell" ||
-                   content_pair.first == "flashlight" ||
-                   content_pair.first == "radio" ) {
-            content.ammo_set( "battery", 150 );
-        } else if( content_pair.first == "lighter" ) {
-            content.charges = 100;
+    for( auto &content : items ) {
+        if( content.is_armor() ) {
+            if( content.typeId() != last_armor ) {
+                content_fits = it->typeId() == "personal_gobag" || content.has_flag( "FIT" ) ;
```
Comment (anothersimulacrum) [inline src/iuse.cpp]: I'd prefer you don't have a hardcoded check for a certain item by its id.

File: src/iuse.cpp [hunk 7]
```diff
@@ -9189,68 +9189,26 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
+                last_armor = content.typeId();
+            }
+            content_fits ? content.set_flag( "FIT" ) : content.unset_flag( "FIT" );
         }
 
-        for( int i = 0; i < content_pair.second; i++ ) {
-            g->m.add_item_or_charges( p->posx(), p->posy(), content );
+        if( ( content.typeId() == "duffelbag" || content.typeId() == "backpack" ) &&
```
Comment (anothersimulacrum) [inline src/iuse.cpp]: Same here

File: src/iuse.cpp (hunk 6 above)
Comment (Hymore246) [reply src/iuse.cpp]: Not sure I can fix that. How will the method know if it should make every item fit if it can't check to see if the right item is being used?

File: src/iuse.cpp (hunk 7 above)
Comment (Hymore246) [reply src/iuse.cpp]: This one is tricky because the duffel bag and backpack should be filthy if the go bag is filthy. I don't think there is a way to implement that without checking specifically for those items.

File: src/iuse.cpp (hunk 6 above)
Comment (anothersimulacrum) [reply src/iuse.cpp]: You can use a flag, or some type of field. Checking for a specific item id is fragile makes it hard to change.

File: src/iuse.cpp (hunk 7 above)
Comment (anothersimulacrum) [reply src/iuse.cpp]: You can check for items with storage, or items with storage greater than some number, rather than two specific items.

File: src/iuse.cpp [hunk 8]
```diff
@@ -9187,6 +9187,35 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
     return 0;
 }
 
+int iuse::gobag( player *p, item *it, bool, const tripoint & )
+{
+    auto items = item_group::items_from( "gobag_contents", calendar::turn );
+    bool content_fits = it->typeId() == "personal_gobag";
```
Comment (Night-Pryanik) [inline src/iuse.cpp]: This bool isn't checked anywhere except for `for( auto &content : items ) {` cycle below, so it's best to declare it inside the cycle.

File: src/iuse.cpp [hunk 9]
```diff
@@ -9187,6 +9187,35 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
+
+    p->add_msg_if_player( _( "You empty the contents of the go bag onto the floor." ) );
+
+    for( auto &content : items ) {
+        if( content.is_armor() ) {
+            if( content.typeId() != last_armor ) {
+                content_fits = it->typeId() == "personal_gobag" || content.has_flag( "FIT" ) ;
+                last_armor = content.typeId();
+            }
+            content_fits ? content.set_flag( "FIT" ) : content.unset_flag( "FIT" );
```
Comment (Night-Pryanik) [inline src/iuse.cpp]: I don't understand the logic for this. Firstly check for `id` of the `gobag_contents` item group. Here goes the duffelbag from this item group. It doesn't have the `FIT` flag. And on the next step this line unsets its already missing `FIT` flag.

Comment (Hymore246) [reply src/iuse.cpp]: The game does a random check to see if the item fits when it is created using items_from(). Without any input from me, the game generates items that either randomly fit or do not fit. That check is to insure that all items of the same type (socks, t-shirts) fit the same way. It's a hack but I can't think of a better way to get consistency for the items.

Comment (Night-Pryanik) [reply src/iuse.cpp]: I get what you want to do, but I don't get why you're setting the already applied or unsetting already missing flags. If item fits, there's no need to make it fit one more time.

File: src/iuse.cpp (hunk 8 above)
Comment (Hymore246) [reply src/iuse.cpp]: It needs to be declared and initialized outside since it's possible to use it without altering it in the loop. The value needs to be remember between loops too. Moving it inside the loop will cause the shirts/socks to not match in size.

File: src/iuse.cpp (hunk 9 above)
Comment (Hymore246) [reply src/iuse.cpp]: Ah, now I get it. I'll make a better if-else statement to handle that.

File: data/json/items/armor.json [hunk 10]
```diff
@@ -4014,7 +4014,15 @@
...
     "flags": [ "BELTED", "WATER_FRIENDLY" ],
-    "use_action": "DISASSEMBLE"
+    "use_action": "GOBAG"
+  },
+  {
+    "id": "personal_gobag",
+    "type": "ARMOR",
+    "name": "personal go bag",
+    "description": "A huge duffel bag with backpack attached, both packed to the gills.  You have packed this to be ready for deployment.  Activate to unpack and enjoy.",
+    "volume": 144,
```
Comment (Rail-Runner) [inline data/json/items/armor.json]: Is there any reason for it to be larger than a normal go bag?

Comment (Hymore246) [reply data/json/items/armor.json]: I'm using volume as a way to determine if the player used a normal or personal go bag since I using the item's id is fragile.

Comment (Rail-Runner) [reply data/json/items/armor.json]: Using volume for that is much more fragile, I think. If someone decides to change go bag's volume because it's too big or too small, it'll be broken. With IDs, people at least try to keep them unchanged to not ruin save compatibility.

Comment (anothersimulacrum) [reply data/json/items/armor.json]: I'd strongly recommend using a flag or maybe field instead of and id or the volume. Both those solutions are fragile, and in my opinion, checking for a specific ID is bad practice.

File: src/iuse.cpp [hunk 11]
```diff
@@ -9187,6 +9187,40 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
     return 0;
 }
 
+int iuse::gobag( player *p, item *it, bool, const tripoint & )
+{
+    auto items = item_group::items_from( "gobag_contents", calendar::turn );
```
Comment (anothersimulacrum) [inline src/iuse.cpp]: Death to auto
```suggestion
    std::vector<item> items = item_group::items_from( "gobag_contents", calendar::turn );
```

File: src/iuse.cpp [hunk 12]
```diff
@@ -9187,6 +9187,40 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
+    bool content_fits = units::to_liter( it->volume() ) >= 36; // personal go bag is bigger
+    std::string last_armor;
+
+    p->add_msg_if_player( _( "You empty the contents of the go bag onto the floor." ) );
+
+    for( auto &content : items ) {
```
Comment (anothersimulacrum) [inline src/iuse.cpp]:
```suggestion
    for( item &content : items ) {
```

File: src/iuse.cpp [hunk 13]
```diff
@@ -9187,6 +9187,40 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
+        if( content.is_armor() ) {
+            if( content.typeId() != last_armor ) {
+                content_fits = units::to_liter(it->volume()) >= 36 || content.has_flag( "FIT" );
```
Comment (anothersimulacrum) [inline src/iuse.cpp]:
```suggestion
                content_fits = units::to_liter( it->volume() ) >= 36 || content.has_flag( "FIT" );
```

File: src/iuse.cpp [hunk 14]
```diff
@@ -9187,6 +9187,40 @@ int iuse::disassemble( player *p, item *it, bool, const tripoint & )
...
+                last_armor = content.typeId();
+            }
+
+            if( content_fits && !content.has_flag( "FIT" ) ) {
+                content.set_flag( "FIT" );
+            }
+            else if( !content_fits && content.has_flag( "FIT" ) ) {
```
Comment (anothersimulacrum) [inline src/iuse.cpp]: This should be moved to the line above, so it's `} else if`

File: data/json/itemgroups/misc.json [hunk 15]
```diff
@@ -98,5 +98,42 @@
...
+      { "item": "hood_rain" },
+      { "item": "long_underpants" },
+      { "item": "towel" },
+      { "item": "boots_combat" },
+      { "item": "socks", "count": 3 },
+      { "item": "gloves_tactical" },
+      { "item": "light_plus_battery_cell", "charges": 150 },
+      { "item": "light_plus_battery_cell", "charges": 150, "container-item": "flashlight" },
+      { "item": "light_plus_battery_cell", "charges": 150, "container-item": "radio" },
+      { "item": "lighter", "charges": 100  },
```
Comment (anothersimulacrum) [inline data/json/itemgroups/misc.json]:
```suggestion
      { "item": "lighter", "charges": 100 },
```

File: data/json/itemgroups/misc.json [hunk 16]
```diff
@@ -98,5 +98,42 @@
...
+      { "item": "pockknife" },
+      { "item": "multitool" },
+      { "item": "1st_aid" },
+      { "item": "rollmat" },
+      { "item": "sleeping_bag_roll" },
+      { "item": "ear_plugs" },
+      { "item": "mre_hashbrownbacon_box" },
+      { "item": "mre_macaronimarinara_box" },
+      { "item": "mre_meatball_box" },
+      { "item": "water_clean", "count": 2, "charges": 2, "container-item": "bottle_plastic" }
```
Comment (anothersimulacrum) [inline data/json/itemgroups/misc.json]:
```suggestion
      { "item": "water_clean", "count": 2, "charges": 2, "container-item": "bottle_plastic" }
```

File: data/json/items/armor.json (hunk 10 above)
Comment (Hymore246) [reply data/json/items/armor.json]: I agree, I took another approach by using the way the alcohol methods are handled. It works better in my opinion.
