### PR TITLE
Fix insert into pockets no move cost

### LINKED ISSUE #47298: Missing move cost for inserting items into pockets
# Describe the bug

Items can be inserted into pockets instantly (0 move cost). This works for any item in your inventory or that are on the same tile as you, and also applies to unwielding items that can opt to be placed in a pocket (i.e. knife into sheath). 

Taking items out of pockets incurs regular expected move cost.

# Steps To Reproduce

1. Equip a container.
2. Stand within pickup range of an item, or have it in a separate container.
3. Select (i)nsert on the empty container, insert an item.
4. Observe move counter displaying 0.

5. Bonus: Stand next to hostile mob(s) and shuffle items back and forth between containers with impunity.

# Expected behavior

Survivor does not toki wo tomare to manage their inventory

# Screenshots

Here's me shuffling 8 knives from a backpack into 8 sheaths after being grabbed by a zombie.

image

image

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-9443-g4eb4e8f-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by Saicchi**
#### Summary
Bugfixes "Fix inserting into pockets costing no moves"

#### Purpose of change
Fixes #47298

#### Describe the solution
Make `game_menus::inv::insert_items` call an `activity_actor` for the items instead; moving the loop over `drop_locations` without changing it.
The cost of moving an item from a container to another container or from the map to another container is: `cost to obtain item + cost to move item to container`

#### Describe alternatives you've considered
Use `100` for `move_cost` ( `cost to move item to container` ) in `item_move_cost` instead of `Pickup::cost_to_move_item`.
The `pick_one_up` function which handles picking item up uses `100` for every item no matter how heavy or big it is.

#### Testing
- [x] Inserting takes time
- [x] Time is varied based on the item
- [x] Time is varied based on item location
- [x] Time is varied based on container
- [x] General inserting functionality is the same

#### Additional context
**Since picking an item on the ground always takes 100 moves**, but trying to pick an item in the ground with insert here will take a bit more moves since the formula is different. I believe using just `100` no matter what the item is not intended.

### CODE REVIEW

File: src/activity_actor.cpp [hunk 1]
```diff
@@ -2348,6 +2348,124 @@ std::unique_ptr<activity_actor> move_furniture_activity_actor::deserialize( Json
...
+                        holstered_item.first.remove_item();
+                    }
+                }
+            }
+        }
+
+        if( !success ) {
+            who.add_msg_if_player(
+                string_format(
+                    _( "Could not put %s into %s, aborting." ),
```
Comment (BrettDong) [inline src/activity_actor.cpp:2417]:
```suggestion
                    _( "Could not put %1$s into %2$s, aborting." ),
```

File: src/activity_actor.cpp [hunk 2]
```diff
@@ -2348,6 +2348,124 @@ std::unique_ptr<activity_actor> move_furniture_activity_actor::deserialize( Json
...
+        // item was lost, so just go to next item
+        success = true;
+    }
+
+    items.pop_front();
+    if( items.empty() || !success ) {
+        handler.handle_by( who );
+        act.set_to_null();
+        return;
+    }
```
Comment (Qrox) [inline src/activity_actor.cpp:2430]: `handle_by` may ask the player to handle unsealed containers, so it should only be called when all items are moved. Otherwise if the containers are moved or contents are spilled, later invocation of this function will use invalid item locations.

**Review by BrettDong — APPROVED** [review]

**Comment by topherclay** [comment]
I'm a big fan of getting `obtain_cost` to be used more consistently!
