### PR TITLE
Fix warning text for consuming food with parasites

### LINKED ISSUE #53849: Attempting to drink dirty water through examine gives warning about raw meat
### Describe the bug

When attempting to drink unclean water with a chance of parasites the player will be warned that eating raw meat is probably unhealthy. This seems to only happen when using "Examine" and "Consume it", and not when trying to drink dirty water through the Consume (E) menu.

### Steps to reproduce

1. Go to some water you can examine that is unclean
2. Attempt to consume the water using Examine and Consume It
3. Note the message about raw meat

### Expected behavior

I expect that the warning will not be about meat if I am drinking water. I mean it's a good tip but irrelevant in the context :P

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 40ed6f5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

When initially created this issue stated that the issue didn't happen with toilets. I thought this was the case because I tried to consume that water with E rather than e. It does occur with toilets as well.

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary
Bugfixes "Warning text for consumption of unclean water assumes it is raw meat"

#### Purpose of change

Fixes #53849

Warning text was hard-coded to assume that anything with parasites was meat.

Steps to reproduce:
Attempt to drink murky water found in a swamp.
See warning text refer to raw meat.

#### Describe the solution

Change the warning text to use the item name.

#### Testing

Consumed water taken from a murky pool in the swamp. Warning text now uses the item name. See screen capture below.

#### Additional context

image

### CODE REVIEW

File: src/consumption.cpp [hunk 1]
```diff
@@ -824,7 +824,8 @@ ret_val<edible_rating> Character::will_eat( const item &food, bool interactive )
 
     if( food.get_comestible()->parasites > 0 && !food.has_flag( flag_NO_PARASITES ) &&
         !has_flag( json_flag_PARAIMMUNE ) ) {
-        add_consequence( _( "Eating this raw meat probably isn't very healthy." ), PARASITES );
+        add_consequence( string_format( _( "Eating this %s probably isn't very healthy." ), food.tname() ),
```
Comment (Alex-Folts) [inline src/consumption.cpp:827]: I think "Consuming this %s probably isn't very healthy." would sounds better.

Comment (RoyBerube) [reply src/consumption.cpp:827]: I agree.

**Review by Maleclypse — COMMENTED** [review]
Should the warning mention "Consuming this without preparation, probably isn't healthy" or something like that?
