### PR TITLE
Fix faction display crash

### LINKED ISSUE #34313: Segmentation error when checking factions
# Describe the bug

The game crashes when I try to check factions. (# tab tab). My only follower is currently on a gathering mission. First time I got crash, I went to the camp, recalled my follower, asked him for training, for which he asked money and then disappeared. I found him near my home few tiles away and realised he is not my companion (at that time checking factions worked well) but I could give him commands like he were one. The crashed happened some time after conversation (perhaps I was checking factions as well, but not sure)

# Steps To Reproduce

1. Load save game.
2. Check factions (# tab tab)

# Expected behavior

Obviously, game not crashing.

# Screenshots

# Versions and configuration

 - OS: Windows 8.1
 - Game Version: 0.D-7950-ga718f4c
 - Graphics version: Tiles
 - Mods loaded: dda, disable NPC needs, generic guns, alternative map key, hydroponics, mining mod

# Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3666465/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3666466/debug.log)
[saveFile.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3666463/saveFile.zip)

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Fix faction display crash"```

#### Purpose of change
Fixes #34313 

#### Describe the solution
active_vec_size was not being reset to 0 , when the vector was empty.

#### Describe alternatives you've considered
N/A
#### Additional context
N/A

### CODE REVIEW

File: src/faction.cpp [hunk 1]
```diff
@@ -707,11 +707,13 @@ void faction_manager::display() const
             if( !camps.empty() ) {
                 camp = camps[selection];
             }
+            active_vec_size = camps.size();
         } else if( tab == tab_mode::TAB_OTHERFACTIONS ) {
             if( !valfac.empty() ) {
                 cur_fac = valfac[selection];
                 active_vec_size = valfac.size();
```
Comment (ZhilkinSerg) [inline src/faction.cpp]:
```suggestion
```
