### PR TITLE
Fix font loading

### LINKED ISSUE #37916: Game fails to display non-latin alphabet characters possibly due to PR #37668
# Describe the bug
All non-latin alphabet characters fail to be displayed in build #10316. Likely caused by erroneous code in PR#37668.
I believe that the problem is caused by `std::unique_ptr<Font> Font::load_font( const std::string &typeface, int fontsize` in `src/sdltiles.cpp`, where fonts in data/font are not loaded unless an error is thrown during loading of user's font.
```
   if( ends_with( typeface, ".bmp" ) || ends_with( typeface, ".png" ) ) {
        // Seems to be an image file, not a font.
        // Try to load as bitmap font from user font dir, then from font dir.
        try {
            return std::unique_ptr<Font>( std::make_unique<BitmapFont>( fontwidth, fontheight,
                                          PATH_INFO::fontdir() + typeface ) );
                                          PATH_INFO::user_font() + typeface ) );
        } catch( std::exception &err ) {
            try {
                return std::unique_ptr<Font>( std::make_unique<BitmapFont>( fontwidth, fontheight,
                                              PATH_INFO::fontdir() + typeface ) );
            } catch( std::exception &err ) {
                dbg( D_ERROR ) << "Failed to load " << typeface << ": " << err.what();
                // Continue to load as truetype font
            }
        }
```

# Steps To Reproduce
Download build #10316 and switch to other languages like Russian or Chinese.

# Expected behavior
The characters are displayed correctly.

# Screenshots

# Versions and configuration

 - OS: Windows
 - Game Version: 0.D-Windows_x64-Tiles-10317
 - Graphics version: Tiles
 - Mods loaded: dda

# Additional context
I dont know how to create a PR to fix it.

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: Bugfixes "Fix font loading"```

#### Purpose of change

Fixes #37916

#### Describe the solution

See commit messages.

#### Testing

Change in-game language to one using non-Latin alphabet (i.e. Russian, Chinese, Korean or Japanese) and see that font glyphs are displayed.

#### Additional context

1. We can restore Terminus Bold font after changing its internal identifier (or make font style selection configurable)

2. While working on this PR I've found out that some glyphs (like the ones with with cedilla) are not displayed properly when current Terminus font is used. I will fix it in a different PR.

**Terminus:**
image

**Unifont:**
image

### CODE REVIEW

**Comment by 8street** [comment]
Please merge it quickly.

**Comment by Funguss** [comment]
There's a fonts.json in config, why didn't you use that? Also, I tried deleting the font and changing the json but I've still got terminus bold...

I dunno why people hate on the unifont, I happen to think it looks great. But I like single pixel width sans serif in general. Fancier fonts feel invasive for me, like I'm being told to interpret things in a certain way. In my current game I arrived at a post office I'd already cleared just before dawn and was imagining the sunrise and the cool spring air, how calm that moment would be. Then I met a wandering zombie security guard and casually speared him through a broken window. It felt relaxed, but this terminus bold would have stood in the way of that moment.

File: src/sdltiles.cpp [hunk 1]
```diff
@@ -3534,6 +3534,8 @@ void catacurses::init_interface()
     // initialize sound set
     load_soundset();
 
+    // Recreate font list;
+    save_font_list();
```
Comment (BevapDin) [inline src/sdltiles.cpp]: `save_font_list` looks through many folders and opens all contained font files. This can take quite a while. Is it really necessary to do this on every start?

Comment (ZhilkinSerg) [reply src/sdltiles.cpp]: > 
> 
> `save_font_list` looks through many folders and opens all contained font files. This can take quite a while. Is it really necessary to do this on every start?

Otherwise fonts are cached in `config/fontlist.txt` and no new fonts could be used unless this file is manually deleted and recreated.

File: src/sdltiles.cpp [hunk 2]
```diff
@@ -3534,6 +3534,8 @@ void catacurses::init_interface()
     // initialize sound set
     load_soundset();
 
+    // Recreate font list;
```
Comment (ZhilkinSerg) [inline src/sdltiles.cpp]:
```suggestion
```

File: src/sdltiles.cpp (hunk 1 above)
Comment (ZhilkinSerg) [inline src/sdltiles.cpp]:
```suggestion
```

Comment (BevapDin) [reply src/sdltiles.cpp]: At this point, we might as well remove the file completely and just load the list of fonts here directly into memory. No point in storing it on disk when it's reloaded each time the program starts.

Comment (ZhilkinSerg) [reply src/sdltiles.cpp]: On second thought, it is not really a necessary change to fix font loading issues, so I've reverted it.

**Comment by ZhilkinSerg** [comment]
I've self-merged it as it was kinda serious issue without progress for almost a week.
