### PR TITLE
Uncap proficiency gain, proficiency gain tests

### LINKED ISSUE #49979: High values of proficiency experience are capped.
### Describe the bug

Proficiency experience is capped at `1000_seconds` of practice ( before being modified by focus ), this results in the player unable to get full value of proficiencies that give more than `1000_seconds` ( `16_minutes + 40_seconds` ) of experience.

### Steps To Reproduce

1. Finishg safecracking with **100 focus**.
2. Enable debug mode, and checkk that instead of `60_minutes` player only gets ``16_minutes + 40_seconds` seconds of experience.

### Expected behavior

Player gets full `60_minutes` of experience.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F-762-gfff825cdc5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm]
]

### Additional context

```c++
int Character::adjust_for_focus( int amount ) const
{
    int effective_focus = get_focus();
    effective_focus = enchantment_cache->modify_value( enchant_vals::mod::LEARNING_FOCUS,
                      effective_focus );
    effective_focus += ( get_int() - get_option<int>( "INT_BASED_LEARNING_BASE_VALUE" ) ) *
                       get_option<int>( "INT_BASED_LEARNING_FOCUS_ADJUSTMENT" );
    effective_focus = std::max( effective_focus, 1 );
    return effective_focus * std::min( amount, 1000 );
}

void Character::practice_proficiency( const proficiency_id &prof, const time_duration &amount,
                                      const cata::optional<time_duration> &max )
{
    int amt = to_seconds<int>( amount );
    const float pct_before = _proficiencies->pct_practiced( prof );
    time_duration focused_amount = time_duration::from_seconds( adjust_for_focus( amt ) / 100 );
    const bool learned = _proficiencies->practice( prof, focused_amount, max );
    ...
}
```

### PR DESCRIPTION
**Pull request by actually-a-cat**
#### Summary
Bugfixes "Fixed slow crafts giving too little proficiency practice"

#### Purpose of change
Pulled out from #60564, The book stuff ended up being confusing and this is the important part.

Partial fix for #60452, point 2. 

Fixes #49979.

The essence of the problem is that `adjust_for_focus` is used to adjust arbitrary things (seconds, ticks, minutes, experience points) so it can't make assumptions. But it did rounding and capping which is meaningless given arbitrary input.

#### Describe the solution
`adjust_for_focus` now calculates with floats to avoid rounding errors and doesn't cap anything. It also normalizes the result, that's not strictly necessary but makes sense.

Any rounding and capping have been moved to call sites as appropriate.

#### Testing
This affects: 
1. magic XP gain
2. book reading XP gain
3. crafting XP gain
4. proficiency XP gain

1 and 2 seem to work correctly (or in case of 2, at least not more incorrectly than before)

3 is well-covered by unit tests. Change in rounding behavior causes negligible changes to skill gain (1 turn per level except for some very long ones, up to 0.03% for those). The tests have been adjusted.

For 4, there are two new tests. 

"proficiency_gain_short_crafts" is a generic test that learns a proficiency by repeatedly crafting a short recipe and verifies time taken. I wasn't able to get it exactly on target but it is within a few minutes.

"proficiency_gain_long_craft" is a regression test for the capping issue. It crafts an extremely long recipe to verify that it's possible to learn a proficiency within one 5% tick.

### CODE REVIEW

File: tests/crafting_test.cpp [hunk 1]
```diff
@@ -448,10 +449,20 @@ static int actually_test_craft( const recipe_id &rid, int interrupt_after_turns,
...
+                                int skill_level = -1 )
+{
+    setup_test_craft( rid );
+    avatar &player_character = get_avatar();
+
     int turns = 0;
     while( player_character.activity.id() == ACT_CRAFT ) {
         if( turns >= interrupt_after_turns ||
-            ( skill_level >= 0 && player_character.get_skill_level( rec.skill_used ) > skill_level ) ) {
+            ( skill_level >= 0 && player_character.get_skill_level( rid.obj().skill_used ) > skill_level ) ) {
```
Comment (anothersimulacrum) [inline tests/crafting_test.cpp:465]:
```suggestion
            ( skill_level >= 0 && player_character.get_skill_level( rid->skill_used ) > skill_level ) ) {
```

File: tests/crafting_test.cpp [hunk 2]
```diff
@@ -464,6 +475,85 @@ static int actually_test_craft( const recipe_id &rid, int interrupt_after_turns,
...
+TEST_CASE( "proficiency_gain_short_crafts", "[crafting][proficiency]" )
+{
+    std::vector<item> tools = { item( "2x4" ) };
+
+    const recipe_id &rec = recipe_cudgel_simple;
+    prep_craft( rec, tools, true );
+    avatar &ch = get_avatar();
+    // Set skill above requirement so that skill training doesn't steal any focus
+    ch.set_skill_level( skill_fabrication, 1 );
+    REQUIRE( rec.obj().get_skill_cap() < ch.get_skill_level( rec.obj().skill_used ) );
```
Comment (anothersimulacrum) [inline tests/crafting_test.cpp:509]:
```suggestion
    REQUIRE( rec->get_skill_cap() < ch.get_skill_level( rec->skill_used ) );
```

File: tests/crafting_test.cpp [hunk 3]
```diff
@@ -464,6 +475,85 @@ static int actually_test_craft( const recipe_id &rid, int interrupt_after_turns,
...
+
+    REQUIRE( ch.get_proficiency_practice( proficiency_prof_carving ) == 0.0f );
+
+    int turns_taken = 0;
+    const int max_turns = 100'000;
+
+    float time_malus = rec.obj().proficiency_time_maluses( ch );
```
Comment (anothersimulacrum) [inline tests/crafting_test.cpp:516]:
```suggestion
    float time_malus = rec->proficiency_time_maluses( ch );
```

File: tests/crafting_test.cpp [hunk 4]
```diff
@@ -464,6 +475,85 @@ static int actually_test_craft( const recipe_id &rid, int interrupt_after_turns,
...
+
+    do {
+        turns_taken += test_craft_for_prof( rec, proficiency_prof_carving, 1.0f );
+        give_tools( tools );
+
+        // Escape door to avoid infinite loop if there is no progress
+        REQUIRE( turns_taken < max_turns );
+    } while( !ch.has_proficiency( proficiency_prof_carving ) );
+
+    time_duration expected_time = proficiency_prof_carving.obj().time_to_learn() * time_malus + overrun;
```
Comment (anothersimulacrum) [inline tests/crafting_test.cpp:530]:
```suggestion
    time_duration expected_time = proficiency_prof_carving->time_to_learn() * time_malus + overrun;
```

File: tests/crafting_test.cpp [hunk 5]
```diff
@@ -464,6 +475,85 @@ static int actually_test_craft( const recipe_id &rid, int interrupt_after_turns,
...
+// Test gaining proficiency all at once after finishing 5% of a very long recipe
+TEST_CASE( "proficiency_gain_long_craft", "[crafting][proficiency]" )
+{
+    std::vector<item> tools = { item( "2x4" ) };
+    const recipe_id &rec = recipe_cudgel_slow;
+    prep_craft( rec, tools, true );
+    avatar &ch = get_avatar();
+    // Set skill above requirement so that skill training doesn't steal any focus
+    ch.set_skill_level( skill_fabrication, 1 );
+    REQUIRE( rec.obj().get_skill_cap() < ch.get_skill_level( rec.obj().skill_used ) );
```
Comment (anothersimulacrum) [inline tests/crafting_test.cpp:543]:
```suggestion
    REQUIRE( rec->get_skill_cap() < ch.get_skill_level( rec->skill_used ) );
```
