### PR TITLE
Fixes "Mutations and traits are a global list"

### LINKED ISSUE #11143: Mutations and traits are a global list
So, I just looked into how mutations work and discovered the following (possibly old news to some of you):
- all mutations that can exist are placed in a global `std::map<std::string, trait> traits` (in `src/player.cpp`). This is the only place `trait` objects exist.
- all characters have `list<std::string> my_traits` and `list<std::string> my_mutations`, which are lists of **mutation IDs** -- i.e. references into the global `traits` map.
- when a player activates a mutation, they activate it for **all** characters that have that mutation in the current instance of the game. Technically, this means that if both you and an NPC have, say... Retractable Claws, you both turn them off and on at the exact same time.
- the global list of mutations is never saved (naturally), therefore all mutations will be inactive upon the next load regardless of their current state.
- key assignments to specific mutations are kept in a per-`character` `std::map<std::string, char> trait_keys;`

While this may have made sense when mutations were purely static things with nothing but names, prerequisites, etc., it no longer does.

I propose that the global list of traits should be a list of `mutation_type`s instead. Analogously to `itype`s, you'd keep the static parts of mutations in there, which would allow you to store simpler `mutation` objects in the characters. These `mutation` objects would include the invlet assignment, whether the mutation was currently turned on, and whether it's in cooldown (and for how much longer). Of note, this is also analogous to the bionics implementation.

The benefit of this system is that you could then store the lighter `mutation` objects in the savegame, which I shan't bother enumerating the implications of.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/8321647-mutations-and-traits-are-a-global-list?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BevapDin**
Fixes #11143
- static mutation data (describing the mutation, not related to a specific creature in the game) is in `mutation_branch`.
- mutation status as part of a creature (whether it's activated by the creature, the invlet, ...) is in `trait_data`.
- The `mutation_data` map is hidden, but a const-qualified version of it can be accessed through some static functions in the class. This ensures that global mutation data is not modified after loading it (as it would affect all creatures).
- `Character::my_mutations` is now a map of `trait_data` objects, those objects contain the trait invlet from `Character::trait_keys` and the per-creature data of mutations (e.g. whether it's on).
- I added consistency checking of mutation data and consequently fixed some wrong mutation ids.

Questions:
- Rename `mutation_branch` to `mutation_type`?

### CODE REVIEW

File: src/character.h [hunk 1]
```diff
@@ -290,9 +291,30 @@ class Character : public Creature
         Character(Character &&) = default;
         Character &operator=(const Character &) = default;
         Character &operator=(Character &&) = default;
-        
+        struct trait_data : public JsonSerializer, public JsonDeserializer {
+            /** Key to select the mutation in the UI. */
+            char key = ' ';
+            /** TODO: I don't know who I am - comment me. */
+            int charge = 0;
```
Comment (KA101) [inline src/character.h]: I'm gonna take a wild guess and say that charge and cooldown are similar.

File: src/mutation.cpp [hunk 2]
```diff
@@ -40,40 +44,19 @@ void Character::toggle_trait(const std::string &flag)
...
+    const auto iter = my_mutations.find( flag );
+    if( iter == my_mutations.end() ) {
+        my_mutations[flag]; // Creates a new entry with default values
     } else {
-        set.erase( toggled_element );
-        trait_keys.erase(str);
+        my_mutations.erase( iter );
     }
+    // TODO: why does this not call mutation_loss_effect / mutation_effect?
+    recalc_sight_limits();
```
Comment (KA101) [inline src/mutation.cpp]: I'm thinking it's because those are handled in gaining or removing a mutation, last I knew.  Currently the only stuff that gets specifically toggled rather than mutate_towards'd is thresholds and profession traits; mutate_towards calls the effects.

So yeah, probably should get 'em for future-proofing.

File: src/mutation.cpp [hunk 3]
```diff
@@ -308,66 +291,65 @@ void Character::mutation_loss_effect(std::string mut)
...
       // Insufficient Foo to *maintain* operation is handled in player::suffer
-        add_msg(m_warning, _("You feel like using your %s would kill you!"), traits[mut].name.c_str());
+        add_msg(m_warning, _("You feel like using your %s would kill you!"), mdata.name.c_str());
         return;
     }
-    if (traits[mut].powered && traits[mut].charge > 0) {
+    if (tdata.powered && tdata.charge > 0) {
         // Already-on units just lose a bit of charge
-        traits[mut].charge--;
+        tdata.charge--;
```
Comment (KA101) [inline src/mutation.cpp]: Yeah, here's charge.  It's supposed to handle timing the active traits that take X resources per T time.

**Comment by BevapDin** [comment]
I added some documentation and removed the TODOs.

About mutation_loss_effect / mutation_effect in `toggle_mutation`: that is probably fine. It is called for example from `mutation_towards` and the code there calls `mutation_loss_effect` / `mutation_effect`, so it's fine there.

It might be useful to implement simple `add_mutation` / `remove_mutation` functions to be used in iuse.cpp (the marloss / threshold stuff) and in mission_start.cpp. Actually if you get the same type of mission (that gives the PROF_FED trait) twice, you'll lose the PROF_FED traits again - because it *toggles* the mutation (-:

**Comment by KA101** [comment]
Yeah, the quests need some attention and I'll grant that add/remove would be handy.

I'm kinda waiting on this one, both thanks to large/0.C freeze and having finally worked up a fix for that multi-cancellation issue (though I'm thinking a while/do might be more effective).

File: src/character.h [hunk 4]
```diff
@@ -290,9 +291,34 @@ class Character : public Creature
         Character(Character &&) = default;
         Character &operator=(const Character &) = default;
         Character &operator=(Character &&) = default;
-        
+        struct trait_data : public JsonSerializer, public JsonDeserializer {
+            /** Key to select the mutation in the UI. */
+            char key = ' ';
```
Comment (kevingranade) [inline src/character.h]: This belongs in the UI code, stashing it in the referent like this has caused a lot of pain over in the inventory code.

Comment (BevapDin) [inline src/character.h]: So you want a separate map for the char key to mutation mapping? Should that be done for bionics as well?

It seems a bit pointless and error prone, one has to keep both maps synchronized all the time.

Comment (KA101) [inline src/character.h]: You two figure that out and let me know, please.  ;-)
