### PR TITLE
Fix worn holster wield times

### LINKED ISSUE #28395: (w)ielding from a scabbard/holster takes longer than (a)ctivating it
**Describe the bug**  
When you try to take out a sword by (w)ielding the scabbard and confirming the prompt to take out the sword instead, you need more time than when you (a)ctivate the scabbard instead. Same thing for guns and holsters.

**To Reproduce**  
1. Make a player with a broadsword, a scabbard and a watch(optional).
2. Wear the scabbard and put the sword in it.
3. (a)ctivate the scabbard and note the time it takes.
4. Put the sword back.
5. (w)ield the scabbard and confirm the prompt, noting the time again.
6. Wielding took longer than activating.

**Expected behavior**  
You use the same time to take out the weapon both times.

**Versions and configuration:**
 - OS: Win 7
 - Game Version: 0.C-37527-gd075e8d
 - Graphics version: Tiles
 - Mods loaded: DDA, Disable NPC Needs, Filthy Clothing, Simplified Nutrition, NPC traits, Zetsukaze's Hair Extensions!, (DP_RP) REMIX Indicators

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
```SUMMARY: Bugfixes "Fix worn holster wield times."```

#### Purpose of change
Fixes #28395.

#### Describe the solution
`holster_actor::use()` checks if/where the item is worn at when determining wield costs. However, after recent changes to `game::wield()` the item isn't actually worn at the time that is it invoked, rather floating in limbo. This prompts the player if they want to activate their holster instead of wielding before continuing and putting the item in limbo.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -9945,6 +9945,18 @@ void game::wield( item_location &loc )
         add_msg( m_info, "%s", ret.c_str() );
     }
 
+    // Need to do this here because holster_actor::use() because holster_actor::use()
```
Comment (AMurkin) [inline src/game.cpp]:
```suggestion
    // Need to do this here because holster_actor::use()
```

**Comment by AMurkin** [comment]
Also
```cpp
query_yn( _( "Draw %s from %s?" ), target.get_contained().tname(), target.tname() )
```
