### PR TITLE
Perk Category doesn't exist

### LINKED ISSUE #75019: [Bombastic Perks] Bombastic Perks count towards mutation instability
### Describe the bug

When computing mutation instability, the perks from Bombastic Perks count towards the total mutation instability.

In mutation.cpp L182 it checks for the category to be nonempty. However, Bombastic Perks belong to the 'perks' category. 

### Attach save file

before taking perks
[Bombastic Only-trimmed.tar.gz](https://github.com/user-attachments/files/16228572/Bombastic.Only-trimmed.tar.gz)
after taking perks
[Bombastic Only-trimmed.tar.gz](https://github.com/user-attachments/files/16228578/Bombastic.Only-trimmed.tar.gz)

### Steps to reproduce

1. create a new player
2. add 5 bombastic perks levels
3. inject primer + catalyst

### Expected behavior

Expect the frequency of negative mutations to be independent of how many perks you have taken from Bombastic Perks.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 22.04.4 LTS; Release: 22.04; Codename: jammy; 
- Game Version: cdda-experimental-2024-07-06-1626 76a777a [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bombastic Perks [bombastic_perks]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
Fix #75019. Perk category exists as a string only and was never created as a mutation_category.  It only exists to cause instability.

#### Describe the solution
Remove category and add valid false

#### Describe alternatives you've considered
wait

#### Testing
soon

### CODE REVIEW

File: src/mutation.cpp [hunk 1]
```diff
@@ -179,7 +179,7 @@ int Character::get_instability_per_category( const mutation_category_id &categ )
     // For each and every trait we have...
     for( const trait_id &mut : get_mutations() ) {
         // only count muts that have 0 or more points, aren't a threshold, have a category, and aren't a base trait.
-        if( mut.obj().points > -1 && !mut.obj().threshold && !mut.obj().category.empty() &&
+        if( mut.obj().points > -1 && !mut.obj().threshold && !mut.obj().category.empty() && !mut.obj().category.perks() &&
```
Comment (Maleclypse) [inline src/mutation.cpp:182]:
```suggestion
        if( mut.obj().points > -1 && !mut.obj().threshold && !mut.obj().category.empty() && !mut.obj().category.perk() &&
```
