### PR TITLE
Prevent integer overflow with max charges, container and cargo volume

### LINKED ISSUE #26423: Unable to put items with charges into cargo dimension, other items are ok
**Describe the bug**  
Moving items into a cargo dimension works, but moving items with charges like ammo/duct tape gets a message stating the destination is full.

**To Reproduce**  
1. Have a cargo dimension on a vehicle
2. Move an item in
3. Move some ammo in

**Expected behavior**  
Both should be able to work if there is enough space in the cargo dimension

**Screenshots**  
Before moving the gun:
beforemovegun

After moving the gun:
aftermovegun

Trying to move the ammo:
tryingtomoveammo

**Versions and configuration(please complete the following information):**
- First noticed on build 8080, downgraded to 8078 with the same issue. 8076 has no such issue. Suspect it has to do with PR Fix truncated per-charge volume (#26031) in build 8077.

### PR DESCRIPTION
**Pull request by Zetsukaze**
### Summary
`SUMMARY: Bugfixes "Set max for item stack charges, container volume and cargo volume."`

#### Purpose of change
Fixes #26423 Unable to put items in cargo dimension.
The cargo dimension volume was too large, causing items with charges and a small volume per charge to create an integer overflow, making it impossible to store items even if there was still available space.

#### Describe the solution
With a max volume and stack charge, the numbers will be within the upper bounds of an int type variable.

#### Describe alternatives you've considered
Casting volume to int64_t, which Kevin did not feel was appropriate for an over-sized container

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
```SUMMARY: Bugfixes "Set max for item stack charges, container volume and cargo volume."```

**Comment by ZhilkinSerg** [comment]
That should be taken literally. PR summary line parsing script expects line of certain format.

**Comment by Zetsukaze** [comment]
Ah okay, thanks!

File: src/item_factory.cpp [hunk 1]
```diff
@@ -176,9 +176,11 @@ void Item_factory::finalize_pre( itype &obj )
         obj.integral_volume = obj.volume;
     }
     // for ammo and comestibles stack size defaults to count of initial charges
+    // Set max stack size to 200 to prevent integer overflow
     if( obj.stackable && obj.stack_size == 0 ) {
-        obj.stack_size = obj.charges_default();
+        obj.stack_size = std::min(obj.charges_default(), 200);
```
Comment (ZhilkinSerg) [inline src/item_factory.cpp]:
```suggestion
        obj.stack_size = std::min( obj.charges_default(), 200 );
```

File: src/vehicle.cpp [hunk 2]
```diff
@@ -93,7 +93,8 @@ void vehicle_stack::insert_at( std::list<item>::iterator index,
 units::volume vehicle_stack::max_volume() const
 {
     if( myorigin->part_flag( part_num, "CARGO" ) && myorigin->parts[part_num].is_available() ) {
-        return myorigin->parts[part_num].info().size;
+        // Set max volume for vehicle cargo to prevent integer overflow
+        return std::min(myorigin->parts[part_num].info().size, units::from_milliliter( 10000000 ));
```
Comment (ZhilkinSerg) [inline src/vehicle.cpp]:
```suggestion
        return std::min( myorigin->parts[part_num].info().size, units::from_milliliter( 10000000 ) );
```

**Comment by ZhilkinSerg** [comment]
You should not put `Fixes #26423 Unable to put items in cargo dimension` to ``` leave it as:

Fixes #26423 

to link properly.

**Comment by Zetsukaze** [comment]
Ah, was following the template given.

File: src/item_factory.cpp [hunk 3]
```diff
@@ -176,9 +176,11 @@ void Item_factory::finalize_pre( itype &obj )
         obj.integral_volume = obj.volume;
     }
     // for ammo and comestibles stack size defaults to count of initial charges
+    // Set max stack size to 200 to prevent integer overflow
     if( obj.stackable && obj.stack_size == 0 ) {
-        obj.stack_size = obj.charges_default();
+        obj.stack_size = std::min( obj.charges_default(), 200 );
     }
+
```
Comment (ZhilkinSerg) [inline src/item_factory.cpp]:
```suggestion

```

File: src/item_factory.cpp [hunk 4]
```diff
@@ -191,6 +193,11 @@ void Item_factory::finalize_pre( itype &obj )
         }
     }
 
+    // Set max volume for containers to prevent integer overflow
+    if (obj.container && obj.container->contains > units::from_milliliter( 10000000 ) ) {
```
Comment (ZhilkinSerg) [inline src/item_factory.cpp]:
```suggestion
    if( obj.container && obj.container->contains > units::from_milliliter( 10000000 ) ) {
```

File: src/item_factory.cpp (hunk 3 above)
Comment (Zetsukaze) [reply src/item_factory.cpp]: You don't have eof newlines?

File: src/item_factory.cpp [hunk 5]
```diff
@@ -176,9 +176,11 @@ void Item_factory::finalize_pre( itype &obj )
         obj.integral_volume = obj.volume;
     }
     // for ammo and comestibles stack size defaults to count of initial charges
+    // Set max stack size to 200 to prevent integer overflow
```
[the remark this answers is not in the document]
Comment (Zetsukaze) [reply src/item_factory.cpp]: Should we throw a debug message every time something tries to set stack sizes and container volumes above the limit?

File: src/item_factory.cpp (hunk 3 above)
Comment (ZhilkinSerg) [reply src/item_factory.cpp]: There are stray whitespaces on this line.

Comment (Zetsukaze) [reply src/item_factory.cpp]: oh whoops thought it was the eof from first glance. 😳

File: src/item_factory.cpp (hunk 5 above)
[the remark this answers is not in the document]
Comment (Zetsukaze) [reply src/item_factory.cpp]: The current code has a logic error. I fixed it and did some debugging/testing, and it does act weird when the stack size changes. The volume of the same stack of gold gets multiplied by 5. How should we set a max stack size and avoid causing this problem?

[the remark this answers is not in the document]
Comment (kevingranade) [reply src/item_factory.cpp]: I'd be fine with debugmsg + truncate the value to the acceptable range.
It's just having it fully silent is the problem.

AFAIK the stack size change needs to be accompanied by adjusting the accompanying stats to make it work out.
For example with gold it seems like it needs to have volume 1mL, weight 20g for a single unit of "gold", and the stack size should be whatever is most convinient, probably 200 since that's a rather small unit.  Count should be adjusted proportionally with the adjustment to grams in order to make it spawn in the same amounts.

[the remark this answers is not in the document]
Comment (Zetsukaze) [reply src/item_factory.cpp]: Changed the stack sizes for items above 200 to 200, and changed the volumes to match. Because the stack size only affects volume, I kept the weight and counts the same so that the density of each charge remained the same, and wouldn't affect crafting recipes.

**Comment by Zetsukaze** [comment]
Related to #26103 I think

File: src/item_factory.cpp [hunk 6]
```diff
@@ -191,6 +198,12 @@ void Item_factory::finalize_pre( itype &obj )
         }
     }
 
+    // Set max volume for containers to prevent integer overflow
+    if( obj.container && obj.container->contains > units::from_milliliter( 10000000 ) ) {
```
Comment (jbytheway) [inline src/item_factory.cpp]: I think you can use the user-defined literal for these constants; so this would be `10000000_ml`.

File: src/item.cpp [hunk 7]
```diff
@@ -536,9 +536,7 @@ long item::charges_per_volume( const units::volume &vol ) const
     if( type->volume == 0 ) {
         return INFINITE_CHARGES; // TODO: items should not have 0 volume at all!
     }
-    // Type cast to prevent integer overflow with large volume containers like the cargo dimension
-    return count_by_charges() ? vol * static_cast<int64_t>( type->stack_size ) / type->volume
-           : vol / volume();
+    return count_by_charges() ? vol * type->stack_size / type->volume : vol / volume();
```
Comment (jbytheway) [inline src/item.cpp]: This change has broken the unit test I wrote.  I feel like it's better to leave this cast, since it's useful for things just temporarily larger than `INT_MAX`.  But if it has to go then you'll need to update the test.

File: src/item_factory.cpp (hunk 6 above)
Comment (Zetsukaze) [reply src/item_factory.cpp]: Yup, Tried it and it works the same, thanks!

File: src/item.cpp (hunk 7 above)
Comment (Zetsukaze) [reply src/item.cpp]: Yup, that's reasonable. I have put back the internal typecast.

**Comment by AMurkin** [comment]
In da7e58d you didn't restore a comment and you omit spaces inside brackets.

**Comment by Zetsukaze** [comment]
Thanks! I'm used to having no spaces in brackets though, is this a C++ convention?

**Comment by AMurkin** [comment]
It's this project's [code style](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CODE_STYLE.md).

File: src/item.cpp [hunk 8]
```diff
@@ -538,7 +538,7 @@ long item::charges_per_volume( const units::volume &vol ) const
     }
     // Type cast to prevent integer overflow with large volume containers like the cargo dimension
     return count_by_charges() ? vol * static_cast<int64_t>( type->stack_size ) / type->volume
-           : vol / volume();
+                              : vol / volume();
```
Comment (ZhilkinSerg) [inline src/item.cpp]:
```suggestion
          : vol / volume();
```
