### PR TITLE
Stop reading if it got too dark for some reason

### LINKED ISSUE #39970: Blind Reading Possible
# Describe the bug

Being blinded while reading a skill book does not slow down or interrupt the reading process. It is even possible to complete a level up while blinded provided it happens after the reading is initiated.

# Steps To Reproduce

1. Go to wizard tower top floor
2. Stand next to greater mana crystal while room is otherwise dark
3. Read a skillbook until a level is gained

# Expected behavior

Unless the book is Braille or otherwise could be felt, being unable to see should lock all reading and reading progress until this condition is fixed.
Perhaps an interface to simply wait this condition out rather than stopping the automatic reading action itself could be an option, but at the least the blind function should interact somehow. 

# Versions and configuration

 - OS: Ubuntu 18.04
 - Game Version: version 0.E
 - Graphics version: Terminal
 - Ingame language: English
 - Mods loaded: dda, aftershock, magiclysm, dinomod, crazy cataclysm. my sweet cataclysm, mythical martial arts, speedydex, stats (kills), stats (skills)

# Additional context
Reading a skillbook one chapter at a time also has this problem. 
Reading a spell scroll from the magiclysm mod stops this reading action as expected
[blindReadSave.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/4542200/blindReadSave.tar.gz)
Save added for convenience

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary

SUMMARY: Bugfixes "Stop reading if it got too dark for some reason."

#### Purpose of change
Closes #39970 - Blind Reading Possible.

#### Describe the solution
Added a check for `fine_vision_mod > 4` in `read_do_turn` activity function.

#### Describe alternatives you've considered
None.

#### Testing
Got a book with long reading times (Antique Adornments), activated flashbang, threw it right to me, started reading the book. Flash blinded my character, and it stopped reading.
Got the same book, set time to 20:30, started reading. When night falls and it got too dark to read, my character stopped reading.

#### Additional context
None.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -3197,6 +3197,13 @@ void activity_handlers::butcher_do_turn( player_activity * /*act*/, player *p )
 
 void activity_handlers::read_do_turn( player_activity *act, player *p )
 {
+    if( p->fine_detail_vision_mod() > 4 ) {
```
Comment (ZhilkinSerg) [inline src/activity_handlers.cpp:3200]: Is this magic number used somewhere else? Maybe we should use some constexpr for it?

Comment (kevingranade) [reply src/activity_handlers.cpp:3200]: Yes let's make this a constant or an enum, but it's in dozens of places, so let's do that in another PR.
