### PR TITLE
Expand generic factory to include relative and proportional support.

### LINKED ISSUE #43117: (Biosilicified) chitin armor doesn't actually protect from acid
# Describe the bug

The description of the biosilicified armor states it's acid-resistant, but actual acid protection value stated is 0.

# Steps To Reproduce

1. Debug menu -> learn all recipes
2. Crafting menu -> biosilicified armor
3. Check the screenshot

# Expected behavior
Description matches reality.

# Screenshots
image

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-5241-g89c6d05 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context
Other equipment does actually have acid protection.

### PR DESCRIPTION
**Pull request by anothersimulacrum**
#### Summary
SUMMARY: Infrastructure "Allow using relative and proportional with generic_factory"

#### Purpose of change
In the hope of eventually removing the assign() functions, and expanding support for generic factory (and continuing to support existing use cases), generic_factory needs to support relative and proportional.

Also, some enums needed to be converted to enum classes so the compiler wouldn't get confused and try to use them with proportional.

Fixes #43117
#### Describe the solution
To do this, do some template vodoo.
Create two templated structs, and take advantage of SFINAE (yeah, I had to look that up) with these to determine which template function to use.
Three basically discriminate between whether or not the type can specify value proportionally or relatively.
For proportionally, this is whether or not the type can be multiplied by a float, and for relative, this is whether or not the type can use the += operator with itself.

Also, add some error checking for when a proportional value is inappropriately specified.

Huge thanks to jbytheway for helping me use template vodoo to accomplish this.

#### Testing
Game loads without error. Bio-chitin armor has acid protection.

### CODE REVIEW

File: src/generic_factory.h [hunk 1]
```diff
@@ -844,6 +1011,51 @@ class generic_typed_reader
             }
         }
 
+        // These two functions are effectively handle_relative
+        // but they need to use the reader, so they must be here
```
Comment (jbytheway) [inline src/generic_factory.h:1015]: Why is this true for relative but not proportional?

Comment (anothersimulacrum) [reply src/generic_factory.h:1015]: Proportional is only reading a float, relative is reading the same type of value.

Comment (anothersimulacrum) [reply src/generic_factory.h:1015]: And now there's a comment saying so.

**Comment by anothersimulacrum** [comment]
Fairly sure everything here is working and is in a good enough state for this to be merged. So I think this is just waiting on 0.F.

**Comment by Wishbringer** [comment]
Should this be 0.F tagged? It fixes ammo types that uses copy-from and relative damage_type with armor_penetration.
(AP ammo doesn't have armor penetration)
Example ammo id "50_mk211" gets 0 penetration rather than +20 without this.

**Comment by anothersimulacrum** [comment]
As the person who introduced that bug, as far as I can tell, it's a display issue. As long as the damage is loaded using `assign()`, which it is right now, relative/proportional work correctly for it. You can test this using 9mm against an armored zombie if you're interested.
I do intend to look into that and fix it before 0.F, but it's not a loading issue as far as I can tell.
