### PR TITLE
Fix weighted list RNG on platforms with a different RAND_MAX value

### LINKED ISSUE #14410: Random vehicles not spawning
When starting a new world, no random vehicles are spawning on roads in cities.

It seem that the first bad commit where this starts occurring is: 84a8913976ced0b31b5e816811a64c32dd61da16

### PR DESCRIPTION
**Pull request by remyroy**
Fixes #14410.

### CODE REVIEW

File: src/weighted_list.h [hunk 1]
```diff
@@ -220,13 +220,8 @@ template <typename T> struct weighted_float_list : public weighted_list<double,
...
 
-        size_t pick_ent( long long rand_ll ) const override {
-            double picked;
-            if( rand_ll == -1 ) {
-                picked = rng_float( nextafter( 0.0, 1.0 ), this->total_weight );
-            } else {
-                picked = ( double )rand_ll / ( double )INT_MAX * ( this->total_weight );
-            }
+        size_t pick_ent( unsigned int randi ) const override {
+            double picked = ( double )randi / ( double )RAND_MAX * ( this->total_weight );
```
Comment (sparr) [inline src/weighted_list.h]: `double picked = ( double )(randi%RAND_MAX) / ( double )RAND_MAX * ( this->total_weight );`

this will make sure the picked number is <total_weight, in cases where randi>RAND_MAX because INT_MAX>RAND_MAX (such as on the windows platform where this bug was identified)

**Comment by remyroy** [comment]
randi should never be greater than RAND_MAX with our current code using weighted_float_list but for completion, I'll make the modification.

**Comment by sparr** [comment]
I would merge this if I could test it on Windows.

**Comment by Malkeus** [comment]
I now have a headache and a copy of CleverRaven:master with your changes compiling on my Windows 7 64bit system. I'll get back to you with the results soon.

**Comment by Malkeus** [comment]
Random vehicles appear to only be spawning in cities. I traveled for several dozen map tiles of non-city roads and didn't see a single vehicle. City car levels seem to be at or slightly above the normal levels. I may have had an unlucky run, I will create a new world and try again.
