### PR TITLE
Fix ammo disassembly and allow for disassembly of multiple rounds

### LINKED ISSUE #37345: Disassembling 30 bullets gives the components of a single round
# Describe the bug

If you want to disassemble 5.56 NATO rounds, you can only do so 30 rounds at a time. However, that only gives the components of a single bullet.

# Steps To Reproduce

1. Try to disassemble a round.
2. Get the message that you need 30 rounds.
3. Disassemble 30 rounds.
4. Wonder where 29 bullet casings disappeared off to.

# Expected behavior

30 rounds disassembled = 30 bullet casings.

# Screenshots

bullet1
image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11584-g115abba [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

This could be fixed by either reverting to the old way of disassembling a single bullet at a time, or increasing the disassemble materials 30 fold.

### PR DESCRIPTION
**Pull request by SeventhSandwich**
```SUMMARY: Bugfixes "Fix ammo disassembly and allow for disassembly of multiple rounds"```

#### Purpose of change
Fixes #37345
The current build of the game has a two-pronged issue with disassembling ammo. Firstly, you can only disassemble in multiples of whatever the 'count' of the ammo's JSON entry is. This varies from round to round. Secondly, disassembling that amount of ammo (for instance, 50 rounds of 9mm FMJ) only returns the materials needed for one round. This is not intended behavior because the uncraft recipe for each ammo type is designed to return one round's worth of materials. 

#### Describe the solution
This PR adds a popup window when the player chooses to disassemble ammo. It prompts the player to enter an amount of ammo to disassemble, and then starts a disassembly activity with a length of time scaled to the amount of ammo being deconstructed. After it finishes, it drops the correct number of materials. 

To keep track of the number of rounds the player wants to disassemble, I store the selected quantity of rounds in the 'position' attribute of the player_activity class (which is unused during item disassembly). This is a little bit hacky, but I didn't want to add an entirely new attribute just for a single purpose like ammo disassembly. If devs would prefer that instead, I'm open to revisions. 

#### Describe alternatives you've considered
I thought of doing something like #37494 but ruled it out because of the difficulty of upkeep. It is also nice to have the ability to disassemble fewer than 50 rounds of ammunition.

 I also thought of implementing a new JSON flag to disassemble things by charge count, but I couldn't think of any use cases besides ammunition. 

#### Testing
I built CDDA in Visual Studio 2019 and tested various types of ammo (default-kind and crafted) and tried different quantities. Everything seems to work perfectly.

#### Additional context
None.

### CODE REVIEW

**Comment by Brian-Otten** [comment]
I'm a big fan of the small extra prompt to decide how much to disassemble, so the player is fully aware of what's happening.

File: src/crafting.cpp [hunk 1]
```diff
@@ -2148,7 +2172,7 @@ void player::complete_disassemble( item_location &target, const recipe &dis )
             item newit( comp.type, calendar::turn );
             // Counted-by-charge items that can be disassembled individually
             // have their component count multiplied by the number of charges.
-            if( dis_item.count_by_charges() && dis.has_flag( flag_UNCRAFT_SINGLE_CHARGE ) ) {
+            if( dis_item.count_by_charges() && ( dis.has_flag( flag_UNCRAFT_SINGLE_CHARGE ) ) ) {
```
Comment (BevapDin) [inline src/crafting.cpp]: What's that for?

File: src/crafting.cpp [hunk 2]
```diff
@@ -2177,6 +2201,10 @@ void player::complete_disassemble( item_location &target, const recipe &dis )
                 newit.ammo_set( newit.ammo_default(), newit.ammo_capacity() );
             }
 
+            if( dis_item.is_ammo() ) { //If ammo, overwrite component count with selected quantity of ammo
```
Comment (BevapDin) [inline src/crafting.cpp]: This should be more several lines above. Specifically somewhere before the "Compress liquids and counted-by-charges items into one item," comment. Currently this will create several *identical* entries within `components`.

I also suggest instead of simply overriding the value, to just multiply it. See https://github.com/CleverRaven/Cataclysm-DDA/pull/37709/files#diff-244fef9df19695eb07ac24b399d34e91L2152-R2176 where it currently applies the charges from the product.

File: src/crafting.cpp (hunk 1 above)
Comment (SeventhSandwich) [reply src/crafting.cpp]: Ahhhh, that wasn't supposed to be left in! :(

File: src/crafting.cpp (hunk 2 above)
Comment (SeventhSandwich) [reply src/crafting.cpp]: Fixed this and the redundant parenthesis

File: src/crafting.cpp [hunk 3]
```diff
@@ -2008,6 +2024,8 @@ bool player::disassemble( item_location target, bool interactive )
     activity.index = false;
     activity.targets.emplace_back( std::move( target ) );
     activity.str_values.push_back( r.result() );
+    activity.position = std::min( num_dis,
```
Comment (ZhilkinSerg) [inline src/crafting.cpp]:
```suggestion
    // Unused position attribute used to store ammo to disassemble
```

File: src/crafting.cpp [hunk 4]
```diff
@@ -1997,9 +1999,23 @@ bool player::disassemble( item_location target, bool interactive )
...
+        popup_input.title( title ).edit( num_dis );
+        if( popup_input.canceled() || num_dis <= 0 ) {
+            add_msg( _( "Never mind." ) );
+            return false;
+        }
+    }
 
     if( activity.id() != ACT_DISASSEMBLE ) {
-        assign_activity( ACT_DISASSEMBLE, r.time );
+        if (num_dis != 0) { assign_activity(ACT_DISASSEMBLE, r.time * num_dis); }
```
Comment (ZhilkinSerg) [inline src/crafting.cpp]:
```suggestion
        if( num_dis != 0 ) {
            assign_activity( ACT_DISASSEMBLE, r.time * num_dis );
        }
```

File: src/crafting.cpp [hunk 5]
```diff
@@ -2008,6 +2024,8 @@ bool player::disassemble( item_location target, bool interactive )
     activity.index = false;
     activity.targets.emplace_back( std::move( target ) );
     activity.str_values.push_back( r.result() );
+    activity.position = std::min( num_dis,
+                                  obj.charges ); // Unused position attribute used to store ammo to disassemble
```
Comment (ZhilkinSerg) [inline src/crafting.cpp]:
```suggestion
    activity.position = std::min( num_dis, obj.charges ); 
```

File: src/crafting.cpp [hunk 6]
```diff
@@ -2151,6 +2175,9 @@ void player::complete_disassemble( item_location &target, const recipe &dis )
             if( dis_item.count_by_charges() && dis.has_flag( flag_UNCRAFT_SINGLE_CHARGE ) ) {
                 compcount *= std::min( dis_item.charges, dis.create_result().charges );
             }
+            if (dis_item.is_ammo()) { //If ammo, overwrite component count with selected quantity of ammo
```
Comment (ZhilkinSerg) [inline src/crafting.cpp]:
```suggestion
            //If ammo, overwrite component count with selected quantity of ammo
            if( dis_item.is_ammo() ) {
```

**Comment by ZhilkinSerg** [comment]
You need to style your changes - see https://github.com/CleverRaven/Cataclysm-DDA/pull/24006 for instruction for VS.

**Comment by SeventhSandwich** [comment]
I did run it through Astyle - I'm not sure why it didn't catch the spacing on that if statement

**Comment by ZhilkinSerg** [comment]
Nope, it is still not-astyled properly.
