### PR TITLE
Fix npc crash in decide_needs()

### LINKED ISSUE #42229: Talking to neutral NPC causes crash
# Describe the bug
Trying to talk to a gardener NPC I found causes a crash to desktop

# Steps To Reproduce

1. Walk up next to NPC
2. Pressing "C" for talk
3. Select "Talk to"
4. Select Gardener NPC
5. Crash

# Expected behavior
To actually talk to the NPC and not crash

# Screenshots

image
This happens when I load up my save, the NPC has a laser finger as a weapon
# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4226-g1ea5556 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Crazy Cataclysm [crazy_cataclysm],
    Mythical Martial Arts [MMA],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Fuji's Military Profession Pack [fuji_mpp]
]
[crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4939571/crash.zip)
(Sent in wrong save file, fixed it) 
[Bogalusa.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4939734/Bogalusa.zip)

# Additional context

### PR DESCRIPTION
**Pull request by andrei8l**
#### Summary

`SUMMARY: Bugfixes "Fix NPC crash when wielding bio guns"`

#### Purpose of change

NPCs can crash the game while wielding guns with no ammo (such as the laser finger CBM)

Fixes #42229

#### Describe the solution
Use accessors instead of implementation details in `npc::decide_needs`

#### Describe alternatives you've considered

N/A

#### Testing

Try to reproduce bug report

#### Additional context

N/A

### CODE REVIEW

File: src/npc.cpp [hunk 1]
```diff
@@ -1496,7 +1496,10 @@ void npc::decide_needs()
                               charges_of( itype_UPS_off, ups_drain );
             needrank[need_ammo] = static_cast<double>( ups_charges ) / ups_drain;
         } else {
-            needrank[need_ammo] = get_ammo( ammotype( *weapon.type->gun->ammo.begin() ) ).size();
+            const auto ammo_type = weapon.ammo_type();
```
Comment (anothersimulacrum) [inline src/npc.cpp:1499]:
```suggestion
            const ammotype ammo_type = weapon.ammo_type();
```

Comment (andrei8l) [reply src/npc.cpp]: thanks

**Comment by andrei8l** [comment]
Fixed; sorry about that. I rushed this PR a little bit
