### PR TITLE
[CR]Generic martial art bonuses

### LINKED ISSUE #15101: Counter attack prevents any other actions
How to reproduce: Learn any kind of martial arts that comes with counter attack, have enough skill in melee or something, find a lot of Zs, melee them. Then the game will stuck as you counter attack the zombies, and it will take several hours in game until all zombies or player die.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Martial art bonuses were all hardcoded to depend on specific skills and have results in specific damage.
As a result, adding anything new resulted in a lot of code duplication.

Changed the required skills to use a `skill_id->int` map, required item damage to a `damage_type->int`. Currently still loaded as hardcoded, but internally the handling is a single loop rather than a set of `if`s.

Merged player methods `mabuff_bash_bonus` and `mabuff_cut_bonus` into `mabuff_damage_bonus( damage_type )`. Same for armor methods. Added an example debug technique that adds, fire resistance from buff.

Changed bonuses (from buffs and techniques) to more generic system. Currently rather ugly due to it tokenizing strings to maintain backwards compatibility and simple ids without giant blocks of `if`s, hence the [CR].
This allows loading bonuses of all weird, possibly unhandled types. For example, electric damage bonus multiplier from intelligence.

Changed ALL counters in unmodded game to cost 20 moves. Flat 20 moves.
Not hardcoded, just changed them all to have 0 move cost multiplier and 20 move cost penalty.
Also [CR] on this, because it changes balance.
Closes #15101

Bonus code is common for buffs and techniques now. Moved to bonuses.h/.cpp files.

Added a `bool` that makes martial art/buff/technique require a strictly unarmed user, as opposed to user with an unarmed weapon.

Added docs describing martial arts, buffs and techniques.

Example debug martial art shows off:
- Weird armor types - fire and electricity resistance
- Automatic bonus handling for weird combinations, such as the fire and electricity resistance
- Weird bonuses - move cost being affected by strength, flat move cost penalty
- Armor penetration
- Requirement of strict unarmedness for a buff and for a technique

### CODE REVIEW

File: src/bonuses.cpp [hunk 1]
```diff
@@ -0,0 +1,272 @@
...
+                ss = nss;
+                continue;
+            }
+
+            skipped_token = true;
+            break;
+        }
+
+        if( skipped_token ) {
+            // This isn't a set of ma_ modifiers
```
Comment (illi-kun) [inline src/bonuses.cpp]: I guess this condition is true only in case of error in json parameter definition, so maybe we can show some warnings here? (In log file, probably)

Comment (Coolthulhu) [inline src/bonuses.cpp]: Added. That generates quite a lot of output due to most members not being generic bonuses, but I guess that's OK since color data loading errors produce far more.

Comment (illi-kun) [inline src/bonuses.cpp]: We need to distinct two different conditions:
1) parameter is not a bonus but it's used in some other place;
2) parameter is not a bonus due to typo in json definition and this parameter isn't used at all.

Former case should not appear in debug log but  latter one surely should. And that's why I'd prefer to keep showing color data warnings (and fix the underlying issue sometime): color generator doing incorrect assumptions about color names and log highlights this fact. Sorry I was unclear in my initial message.

Comment (Coolthulhu) [inline src/bonuses.cpp]: > Former case should not appear in debug log but latter one surely should.

That would require either the json reader to mark fields that have been accessed already, or the entire bonus block to be completely separate from the buff/technique block.

**Comment by Rivet-the-Zombie** [comment]
I really like this!

**Comment by illi-kun** [comment]
> That would require either the json reader to mark fields that have been accessed already, or the entire bonus block to be completely separate from the buff/technique block.

It doesn't worth the efforts, it's much easier to check typos in names of json parameters using grep with dictionary containing all possible json parameters (I did similar things for checking flags using json_flags.doc as a dictionary). I'll keep a final decision about necessity of these debug messages in their current statement for you.

File: src/bonuses.cpp [hunk 2]
```diff
@@ -0,0 +1,275 @@
...
+#include "debug.h"
+#include <map>
+#include <string>
+#include <utility>
+#include <sstream>
+#include <vector>
+
+#define dbg(x) DebugLog((DebugLevel)(x),D_MAIN) << __FILE__ << ":" << __LINE__ << ": "
+
+// Tokenize
```
Comment (kevingranade) [inline src/bonuses.cpp]: what? why? The thing has already been run through a json tokenizer, why are you adding another one?
You can turn ```"bash_arm_str" : 0.3,``` into e.g. ```[["bash", "arm", "str"], 0.3]```.  There might be a cleaner syntax you can use, but having it be slightly messier is way better than using a custom parser just for this field.

Comment (Coolthulhu) [inline src/bonuses.cpp]: > The thing has already been run through a json tokenizer, why are you adding another one?

Didn't know we have a json tokenizer.
How to get tokens from it? I can't find anything in json.h

Comment (kevingranade) [inline src/bonuses.cpp]: What I mean is to make this a json object, like ```"bonus" : [["bash", "arm", "str"], 0.3"]```
Which you can parse like:
```
void bonus_container::load( JsonObject &jo ) {
    JsonArray ja = jo.get_array("bonus");
    if( !ja.has_more() ) {
        return;
    }
    JsonArray qualifiers = ja.next_array();
    while( qualifiers.has_more() ) {
        std::string qualifier = qualifiers.next_string();
        if( qualifier == "bash" ) {
            // Handle bash logic.
        } else if( qualifier == "arm" ) {
        // etc...
    }
    const float val = ja.next_float();
}
```

**Comment by Coolthulhu** [comment]
Got rid of manual tokenization. Bonuses are now specified like:
```
"flat_bonuses" : [
    ["armor", "bash", "str", 1.0],
    ["damage", "cut", "dex", 1.0]
],
"mult_bonuses" : [
    ["movecost", 0.5]
]
```

Had to rewrite the jsons. Added some very minor tweaks, like limiting Krav Maga damage bonus to stabbing (was also for cutting). Cutting bonus/multiplier is no longer applied to stabbing damage, techniques like rapid attack now have a separate multiplier for stabbing.
