### PR TITLE
make it possible for cbms to be fueled by non-fuel items

### LINKED ISSUE #49478: [Magiclysm] Blood Power Generator CBM not working
# Describe the bug
Blood Power Generator CBM can't be fueled

# Steps To Reproduce
start a world with Magiclysm enabled
spawn :
 - a Blood Power Generator CBM
 - a Power Storage II CBM
 - an NPC
 - a Butchering Kit
 - a Large Water Skin
give yourself the 'install bionics' debug mutation, and install the CBMs
debug kill all nearby NPCs
bring the stuff over to the body, Butcher -> Bleed -> Waterskin

Now that you have a waterskin with fresh blood, try to fill the CBM
I've tried Activating, Eating, powering the CBM with blood in my inventory, and setting auto-on (expected the activate and auto-on to prompt me to refill if it's empty)

# Expected behavior
- a Refill option on the CBM menu for cbm's that have tanks to allow me to refill them directly
- an Auto-Refill prompt when trying to turn activate a CBM that doesn't have enough left in tank (if you have some in your inventory)
- an Auto-Refill prompt when a power generator CBM tries to turn on (like from the autostart) but doesn't have enough fuel (if you have some in your inventory)
- possibly a prompt when trying to consum(e) something that's both comestible, and a usable ammo for a CBM

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: a0a4318 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context

related to #45040 but I'm not convinced charges are the actual problem
I've tried the following without success:
 - Increasing the volume of the Blood Power Generator CBM Tank by 100x
 - Making the blood non-comestible
 - Adding missing properties from gasoline with changes to match blood

Thing's I've noticed:
 - I've had inconsistent results with changes in the mod's materials.json for blood not overriding the default materials.json blood
 - There's some artificial blocks in the bionic fuel checks that explicitly refuse to acknowledge comestible materials for no reason other than that they're comestible [specifically in `Character::can_fuel_bionic_with`] (which is an incorrect approach)
 - I would have expected the activation code to (if a bionic is empty) call the bionic's own refill command rather than trying to metamind the refill for all bionics itself.  If it's an efficiency thing when consum(e)ing then there should probably be a map where the Keys are 'what installed bionics say they can consume' and the values are the bionics that say they can accept that fuel, or better yet a refill command in the bionics menu so the player can directly fill what they want rather than the player needing to risk "Eat"ing stuff like gasoline

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
Features "make it possible for cbms to be fueled by non-fuel items"

#### Purpose of change
This is basically the opposite of, and reverts #45537
Fixes #49478
Closes #49479
Closes #49352

#### Describe the solution
first, reverts the change that makes it impossible to burn comestibles. Then, goes to the logic that picks exactly what happens when you consume an item and makes it so the item tries to fill up the appropriate CBM if you aren't at your max power and the CBM is full. otherwise it attempts to eat it instead.
This is technically a feature and a bugfix both, but it's fairly small and low-impact, in such a way as it can easily be bugtested.

#### Describe alternatives you've considered
Removing the blood powered CBM
Adding UI information, making this stay broken in this stable cycle.

#### Testing
see attached issue this PR closes. butcher a mi-go for tainted blood.

also, with the ethanol burner cbm, try Eating vodka til your power's full. you'll find you end up drinking it.

#### Additional context
A good follow-up for this PR in experimental is to add the ability to fill the appropriate CBMs directly from the menus, rather than using the Eat menu as a sort of workaround for the whole feature.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -2267,10 +2267,6 @@ bionic_id Character::get_remote_fueled_bionic() const
 
 bool Character::can_fuel_bionic_with( const item &it ) const
 {
-    if( ( !it.is_fuel() && !it.type->magazine && !it.flammable() ) || it.is_comestible() ) {
```
Comment (Fris0uman) [inline src/character.cpp:2270]: Are you sure that removing the check for is_fuel() is not going to cause issues? I think the code for fuel consumption expects to find fuel data further down the line

Comment (KorGgenT) [reply src/character.cpp:2270]: hm, i see. that could end up being bad if anyone does any hinky json...

File: data/mods/Magiclysm/bionics.json [hunk 2]
```diff
@@ -5,7 +5,7 @@
     "name": { "str": "Blood Power Generator CBM" },
     "description": "Embedded into your back and connected to your bionic power supply is a powerfull spell focus able to consume blood from dead creatures to produce bionic power.  It can store up to 100 mL of blood.",
     "occupied_bodyparts": [ [ "torso", 8 ] ],
-    "fuel_options": [ "blood", "dragon_blood", "tainted_blood" ],
+    "fuel_options": [ "blood", "dragon_blood", "tainted_blood", "hblood" ],
```
Comment (Xpyder) [inline data/mods/Magiclysm/bionics.json:8]: Shouldn't "tainted_blood" here be replaced with "blood_tainted" as is set elsewhere in this PR?

**Review by Xpyder — COMMENTED** [review]
Not sure that review was the right choice here, first time trying to enter a code comment

File: data/mods/Magiclysm/bionics.json (hunk 2 above)
Comment (KorGgenT) [reply data/mods/Magiclysm/bionics.json:8]: well drat. that means we have to make another PR.

File: src/character.cpp (hunk 1 above)
Comment (Maleclypse) [reply src/character.cpp:2270]: Would this change be the problem battery and ethanol CBMs are having now?

Comment (KorGgenT) [reply src/character.cpp:2270]: which would be...?

Comment (Zireael07) [reply src/character.cpp:2270]: Battery CBM doesn't work: https://github.com/CleverRaven/Cataclysm-DDA/issues/49509
