### PR TITLE
Post Processing on Professions

### LINKED ISSUE #38675: Bullets & batteries randomizing their numbers in chargen
# Describe the bug

Bullets and batteries are randomizing themselves, up to the maximum defined by the profession(Reenactor has 0-1 in rifle, 1-14 in pouch, 1-15 spare).

# Steps To Reproduce

1. Pick a profession with a gun or phone.
2. Hold down the enter key.
3. Watch as the numbers randomize.

# Expected behavior

Item numbers are granted per the profession's defined items.

# Screenshots

N/A

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12981-g2dbeade [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Magiclysm [magiclysm],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills]
]

# Additional context

### PR DESCRIPTION
**Pull request by Mikesteam1234**
Post processing on profession selection and generation on game start.

#### Summary
SUMMARY: Bugfixes "Changes starting charge/ammo values on items and is now a correct reflection of what will be given to the player in game."

#### Purpose of change
Fixes #38675 - Adds post processing to profession generation, allowing for correct representation of charge/ammo values for items that will be given to the player at the start of the game. _Fix up for debate on final values_

#### Describe the solution
Added post processing to profession::items() stopping randomization that was happening during selection of the profession and again at the start of the game. This would result in a player receiving starting items/charges/ammo that was not indicative of what they chose on profession selection. 

This was accomplished through a couple iterators grabbing values for said items and setting them to their default values, it does this for every item on the character.

#### Describe alternatives you've considered
Currently the way magazines are implemented they do not contain a default value.
Professions contain a max charge value found in the JSON file however, this does not help in choosing a default. This fix is a compromise that takes the half of the magazines capacity as a default. This was chosen because most defaults are half of the items max value.

Ideally, the default value of a magazine would be defined in the profession JSON file.

#### Testing
Testing was done in-game on all professions that had items that could be randomized such as charge's/ammo/food. This change only modifies values of said items, this code will be executed during selection of the profession and during the moment the player selects confirm and the game is started. 

Further programmatic testing and unit tests was not done due to my inexperience with such a large project. I felt the above testing was extensive enough and since the change is minor could be safely integrated into the project without said unit tests. However, during this time I will continue attempting to develop unit testing skills, and consult with the boys down at the discord.

#### Additional context
Personally I believe profession generation code should be run once during selection for any unique chosen profession. As it stands, if the user holds the enter key, the chosen profession is generated as fast as the program will let them. This information should be stored somewhere and accessed later on start of the game. Maybe a follow up to the optimization of the character generation could be further looked at.

This is my first contribution to a big project, go easy on me :) hope to work with you guys more in the future, thanks for all the help in learning the code base. This fix could be greatly improved and modified so don't hesitate to speak up, I'd like to know your thoughts.

### CODE REVIEW

File: src/profession.cpp [hunk 1]
```diff
@@ -428,6 +428,54 @@ std::list<item> profession::items( bool male, const std::vector<trait_id> &trait
...
+                            default value will be given to the player. This issue occurs
+                            on holding the enter key to make rapid selection of a profession.
+
+        TODO:   Currently the way magazines are implemented they do not contain a default value.
+                Professions contain a max charge value found in the JSON file however, this
+                does not help in choosing a default. Below is a compromise that takes the
+                half of the magazines capacity as a default. This was chosen because most
+                defaults are half of the items max value.
+       -- Ideally, the default value of a magazine would be defined in the profession JSON file. --
+    */
```
Comment (damien) [inline src/profession.cpp]: 👏 👏 👏 

Always happy to seed thorough documentation. Well done on this feature, and good on you for writing stellar docs! 🎉
