### PR TITLE
Fix wrong calorie count on batch crafted foods

### LINKED ISSUE #51361: Fish fillets sometimes have zero calories.
### Describe the bug

As stated, fish fillets sometimes are seemingly made of air, with no calories but their respective quench/joy modifiers, this translates to any food derivating from those fillets being a time waste since they also have no calories, this bug seems to be at random but its significantly more common when doing anything in batch with the fish, like butchering in batch or cooking in batch.

### Steps To Reproduce

1. Make a character with a fishing rod.
2. Start fishing in a river. (Not sure about ponds, maybe it has to do with an especific type of fish found in rivers)
3. Butcher a bunch of the fish and cook them together.
Its probable in not gonna happen the first few times, as I said, it seems like the calories dissapear at random.

### Expected behavior

The fish is supposed to have some sort of caloric value, I dont think its intentional that eating cooked fish is sometimes less nutritious than eating a dandelion.

### Screenshots

Bug

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 8bab31e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Extra Mutated Scenarios [extra_mut_scens],
    Mining Mod [Mining_Mod],
    SpeedyDex [speedydex]
]

### Additional context

It seems like if you cook fish with no caloric value together with fish that has calories the calories dissapear from the non-bugged fish, making the entire batch worthless.

### LINKED ISSUE #52429: Batch-cooking sweetbreads results in 0 calories product, that turns into 1000%+ nominal calories product after a reload.
### Describe the bug

See attached screenshot, compare:
1) food values predicted in crafting menu
2) food values after being cooked
3) food values after saving and reloading on the spot 

### Steps To Reproduce

1. Cook all 8 sweetbreads at once.
2. Check the values.
3. Save, reload, check again.

### Expected behavior

Get the product that crafting menu predicts. 

### Screenshots

sweetbread

### Save game:
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7406195/save.zip)

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 25ec152 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Bionic Slots [cbm_slots],
    No Hope [no_hope],
    Rural-Only Mapgen [ruralbiome]
]

### Additional context

I've seen similar thing happen to other food, practically guarantee the issue is not isolated to sweetbread. I also suspect the problem has something to do with batch cooking several "different" pieces of food.

### LINKED ISSUE #52628: The Zero Calorie Milk Diet
### Describe the bug

After playing for an extended period the calories of crafted milk ( or also other often repeated foods?) will suddenly drop to 0. This is reflected visually in the consume menu (as a blank) and can be verified via debug.

Saving and reloading, however, will somewhat fix this - except in my save some pre made milk now has DOUBLE the intended calories per unit.

Edit: Seems to mostly affect larger batches of crafted milk(10+)

Update: Got another persons confirmation on reddit (u/carmikka55). In their case they were experiencing the issue with batch drying fruit so it's not just related to milk. 
### Steps To Reproduce

1. Play for awhile cooking big batches of milk
2. Notice that after awhile milk now has no calories
3. Save and reload and maybe see some fucky shit

### Expected behavior

Milk has the normal 132 calories at all times.

### Screenshots

_No response_

### Versions and configuration

-----------------------------------------
10:23:41.267 : Starting log.
10:23:41.267 INFO : Cataclysm DDA version 18b1e6e
10:23:41.268 INFO : [main] C locale set to C
10:23:41.268 INFO : [main] C++ locale set to C
10:23:41.268 INFO : SDL version used during compile is 2.0.14
10:23:41.268 INFO : SDL version used during linking and in runtime is 2.0.14
10:23:41.381 INFO : Number of render drivers on your system: 5
10:23:41.382 INFO : Render driver: 0/direct3d
10:23:41.382 INFO : Render driver: 1/direct3d11
10:23:41.382 INFO : Render driver: 2/opengl
10:23:41.382 INFO : Render driver: 3/opengles2
10:23:41.382 INFO : Render driver: 4/software
10:23:41.390 INFO : [options] C locale set to C
10:23:41.390 INFO : [options] C++ locale set to C
10:23:41.391 INFO : Setting language to: 'en'
10:23:41.391 INFO : [i18n] Scanning core translations from lang/mo/
10:23:41.391 INFO : [i18n] Scanning mod translations from ./mods/
10:23:41.401 WARNING : opendir [./mods/] failed with "No such process".
10:23:41.709 INFO : Active renderer: 4/software
10:23:42.830 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
10:23:42.898 INFO : Setting language to: 'en'
10:23:43.270 WARNING : opendir [./mods/] failed with "No such process".
10:23:52.665 WARNING : opendir [./save/Chastangq/mods] failed with "No such process".
10:24:03.208 INFO : Loaded tileset: UltimateCataclysm
10:24:03.968 INFO : Loaded tileset: UltimateCataclysm
10:30:20.593 ERROR GAME : (error message will follow backtrace)
  #0
    (dbghelp: @0x7ff7adb15a59[cataclysm-tiles.exe+0x1d5a59]), 
    (libbacktrace: register_frame_ctor+0x7ff66c5f75f9@0x7ff7adb15a59),
    (libbacktrace: 0x7ff7adb15a59    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff7adb1681c[cataclysm-tiles.exe+0x1d681c]), 
    (libbacktrace: register_frame_ctor+0x7ff66c5f83bc@0x7ff7adb1681c),
    (libbacktrace: 0x7ff7adb1681c    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff7adb4416a[cataclysm-tiles.exe+0x20416a]), 
    (libbacktrace: register_frame_ctor+0x7ff66c625d0a@0x7ff7adb4416a),
    (libbacktrace: 0x7ff7adb4416a    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff7aecccc37[cataclysm-tiles.exe+0x138cc37]), 
    (libbacktrace: register_frame_ctor+0x7ff66d7ae7d7@0x7ff7aecccc37),
    (libbacktrace: 0x7ff7aecccc37    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0x7ff7ad9413c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: register_frame_ctor+0x7ff66c422f61@0x7ff7ad9413c1),
    (libbacktrace: 0x7ff7ad9413c1    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0x7ff7ad9414d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: register_frame_ctor+0x7ff66c423076@0x7ff7ad9414d6),
    (libbacktrace: 0x7ff7ad9414d6    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffc67137034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: RtlUserThreadStart+0x21@0x7ffc688c2651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/do_turn.cpp:406: game:monmove: chicken can't move to its location!  (64:66:0), pavement
10:30:21.087 ERROR GAME : src/do_turn.cpp:406: game:monmove: chicken can't move to its location!  (61:62:0), pavement
12:27:57.189 INFO : Monster flag usage statistics:
FLAG;COUNT
DIGS;21307904
CAN_DIG;21153154
AQUATIC;20177213
SEES;16914331
WATER_CAMOUFLAGE;14134083
CAMOUFLAGE;14131870
NIGHT_INVISIBILITY;14127116
FLIES;3661655
SUNDEATH;3434989
SWARMS;3293800
GROUP_MORALE;3293800
PRIORITIZE_TARGETS;3293800
ELECTRIC_FIELD;3293382
IMMOBILE;586066
RIDEABLE_MECH;585987
NO_BREATHE;271450
SWIMS;214625
PATH_AVOID_DANGER_1;141593
PATH_AVOID_DANGER_2;141593
PATH_AVOID_FIRE;141593
PATH_AVOID_FALL;141593
CLIMBS;103150
PET_WONT_FOLLOW;70002
ACIDTRAIL;65716
SHORTACIDTRAIL;65716
SLUDGETRAIL;65716
SMALLSLUDGETRAIL;65716
DRIPS_NAPALM;65716
DRIPS_GASOLINE;65716
LOUDMOVES;65701
KEEP_DISTANCE;51488
ANIMAL;50448
PUSH_VEH;45870
STUMBLES;31177
CAN_OPEN_DOORS;31177
REVIVES;18913
SMELLS;16719
ELECTRONIC;14908
HEARS;14872
GOODHEARING;14754
KEENNOSE;13283
PACIFIST;8419
PUSH_MON;8306
SLUDGEPROOF;4091
PLASTIC;2935
ACIDPROOF;2855
MILKABLE;2566
ABSORBS;646
ABSORBS_SPLITS;646
NOT_HALLUCINATION;646
BORES;645
DESTROYS;642
BASHES;614
VERMIN;559
NEMESIS;550
GROUP_BASH;510
WARM;433
LARVA;423
ARTHROPOD_BLOOD;423
ACID_BLOOD;423
BILE_BLOOD;423
HIT_AND_RUN;408
ATTACKMON;364
QUEEN;343
PET_MOUNTABLE;203
PAY_BOT;127
NO_BREED;114
CANPLAY;43
VENOM;40
PARALYZEVENOM;40
BADVENOM;39
HARDTOSHOOT;25
RANGED_ATTACKER;4
NOHEAD;2
GRABS;1
FILTHY;1
POISON;0
WEBWALK;0
ELECTRIC;0
FIREPROOF;0
COLDPROOF;0
FIREY;0
FUR;0
LEATHER;0
WOOL;0
BONES;0
FAT;0
CONSOLE_DESPAWN;0
ID_CARD_DESPAWN;0
MILITARY_MECH;0
MECH_RECON_VISION;0
MECH_DEFENSIVE;0
GUILT;0
HUMAN;0
FLAMMABLE;0
CHITIN;0
NOGIB;0
CBM_CIV;0
CBM_POWER;0
CBM_SCI;0
CBM_OP;0
CBM_TECH;0
CBM_SUBS;0
FISHABLE;0
INTERIOR_AMMO;0
REVIVES_HEALTHY;0
NO_NECRO;0
PET_HARNESSABLE;0
DOGFOOD;0
SHEARABLE;0
NO_FUNG_DMG;0
STUN_IMMUNE;0
DROPS_AMMO;0
INSECTICIDEPROOF;0

15:09:19.728 ERROR GAME : (error message will follow backtrace)
  #0
    (dbghelp: @0x7ff7adb15a59[cataclysm-tiles.exe+0x1d5a59]), 
    (libbacktrace: register_frame_ctor+0x7ff66c5f75f9@0x7ff7adb15a59),
    (libbacktrace: 0x7ff7adb15a59    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff7adb1681c[cataclysm-tiles.exe+0x1d681c]), 
    (libbacktrace: register_frame_ctor+0x7ff66c5f83bc@0x7ff7adb1681c),
    (libbacktrace: 0x7ff7adb1681c    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff7adb4416a[cataclysm-tiles.exe+0x20416a]), 
    (libbacktrace: register_frame_ctor+0x7ff66c625d0a@0x7ff7adb4416a),
    (libbacktrace: 0x7ff7adb4416a    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff7aecccc37[cataclysm-tiles.exe+0x138cc37]), 
    (libbacktrace: register_frame_ctor+0x7ff66d7ae7d7@0x7ff7aecccc37),
    (libbacktrace: 0x7ff7aecccc37    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0x7ff7ad9413c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: register_frame_ctor+0x7ff66c422f61@0x7ff7ad9413c1),
    (libbacktrace: 0x7ff7ad9413c1    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0x7ff7ad9414d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: register_frame_ctor+0x7ff66c423076@0x7ff7ad9414d6),
    (libbacktrace: 0x7ff7ad9414d6    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffc67137034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: RtlUserThreadStart+0x21@0x7ffc688c2651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/do_turn.cpp:406: game:monmove: decayed zombie can't move to its location!  (32:118:0), sidewalk
18:04:01.011 WARNING : opendir [./save/Chastangq/mods] failed with "No such process".
18:04:12.657 INFO : Loaded tileset: UltimateCataclysm
18:04:12.657 INFO : Loaded tileset: UltimateCataclysm
18:56:46.356 ERROR GAME : (error message will follow backtrace)
  #0
    (dbghelp: @0x7ff7adb15a59[cataclysm-tiles.exe+0x1d5a59]), 
    (libbacktrace: register_frame_ctor+0x7ff66c5f75f9@0x7ff7adb15a59),
    (libbacktrace: 0x7ff7adb15a59    [unknown src]:0    [unknown func]),
  #1
    (dbghelp: @0x7ff7adb1681c[cataclysm-tiles.exe+0x1d681c]), 
    (libbacktrace: register_frame_ctor+0x7ff66c5f83bc@0x7ff7adb1681c),
    (libbacktrace: 0x7ff7adb1681c    [unknown src]:0    [unknown func]),
  #2
    (dbghelp: @0x7ff7adb4416a[cataclysm-tiles.exe+0x20416a]), 
    (libbacktrace: register_frame_ctor+0x7ff66c625d0a@0x7ff7adb4416a),
    (libbacktrace: 0x7ff7adb4416a    [unknown src]:0    [unknown func]),
  #3
    (dbghelp: @0x7ff7aecccc37[cataclysm-tiles.exe+0x138cc37]), 
    (libbacktrace: register_frame_ctor+0x7ff66d7ae7d7@0x7ff7aecccc37),
    (libbacktrace: 0x7ff7aecccc37    [unknown src]:0    [unknown func]),
  #4
    (dbghelp: @0x7ff7ad9413c1[cataclysm-tiles.exe+0x13c1]), 
    (libbacktrace: register_frame_ctor+0x7ff66c422f61@0x7ff7ad9413c1),
    (libbacktrace: 0x7ff7ad9413c1    [unknown src]:0    [unknown func]),
  #5
    (dbghelp: @0x7ff7ad9414d6[cataclysm-tiles.exe+0x14d6]), 
    (libbacktrace: register_frame_ctor+0x7ff66c423076@0x7ff7ad9414d6),
    (libbacktrace: 0x7ff7ad9414d6    [unknown src]:0    [unknown func]),
  #6
    (dbghelp: BaseThreadInitThunk+0x14@0x7ffc67137034[KERNEL32.DLL+0x17034]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
  #7
    (dbghelp: RtlUserThreadStart+0x21@0x7ffc688c2651[ntdll.dll+0x52651]), 
    (backtrace_syminfo failed: errno = -1, msg = no symbol table in PE/COFF executable),
    (backtrace_pcinfo failed: errno = -1, msg = no debug info in PE/COFF executable),
Backtrace emission took 0 seconds.
(continued from above) ERROR : src/do_turn.cpp:406: game:monmove: decayed zombie can't move to its location!  (80:117:0), sidewalk
19:15:10.539 INFO : npc::set_omt_destination - new goal for NPC [Bob Goldberg] with [need_safety] is [shelter_2] in (-34,-102,0).
21:04:50.588 INFO : Monster flag usage statistics:
FLAG;COUNT
DIGS;90009739
CAN_DIG;85651983
AQUATIC;83430869
SEES;73912385
WATER_CAMOUFLAGE;49831603
CAMOUFLAGE;49830648
NIGHT_INVISIBILITY;49814196
FLIES;21834857
SUNDEATH;18825925
SWARMS;14503824
GROUP_MORALE;14503824
PRIORITIZE_TARGETS;14503824
ELECTRIC_FIELD;14468666
RIDEABLE_MECH;8891161
IMMOBILE;8883850
KEEP_DISTANCE;8000913
NO_BREATHE;6256907
PATH_AVOID_DANGER_1;4357362
PATH_AVOID_DANGER_2;4357362
PATH_AVOID_FIRE;4357362
PATH_AVOID_FALL;4357362
SWIMS;3664541
CLIMBS;3253716
STUMBLES;3028246
CAN_OPEN_DOORS;3028246
SMELLS;2561044
ELECTRONIC;1957930
ANIMAL;1915014
PUSH_VEH;1323391
KEENNOSE;1086234
ACIDTRAIL;954889
SHORTACIDTRAIL;954889
SLUDGETRAIL;954889
SMALLSLUDGETRAIL;954889
DRIPS_NAPALM;954889
DRIPS_GASOLINE;954889
LOUDMOVES;954876
PET_WONT_FOLLOW;222528
PUSH_MON;81554
REVIVES;81138
PACIFIST;79098
HEARS;41306
ACIDPROOF;41120
GOODHEARING;40678
PLASTIC;23958
GROUP_BASH;19130
WARM;8900
LARVA;8897
ARTHROPOD_BLOOD;8893
ACID_BLOOD;8893
BILE_BLOOD;8893
MILKABLE;7350
ATTACKMON;6909
QUEEN;5815
VERMIN;5119
NEMESIS;5100
HIT_AND_RUN;3255
VENOM;2869
PARALYZEVENOM;2869
BADVENOM;2867
ABSORBS;646
ABSORBS_SPLITS;646
NOT_HALLUCINATION;646
BORES;645
DESTROYS;642
BASHES;614
ELECTRIC;536
PET_MOUNTABLE;425
COLDPROOF;268
PAY_BOT;255
STUN_IMMUNE;172
NO_BREED;132
GRABS;102
CANPLAY;87
FILTHY;62
DOGFOOD;39
HARDTOSHOOT;27
NOHEAD;9
POISON;3
REVIVES_HEALTHY;3
RANGED_ATTACKER;3
WEBWALK;0
FIREPROOF;0
SLUDGEPROOF;0
FIREY;0
FUR;0
LEATHER;0
WOOL;0
BONES;0
FAT;0
CONSOLE_DESPAWN;0
ID_CARD_DESPAWN;0
MILITARY_MECH;0
MECH_RECON_VISION;0
MECH_DEFENSIVE;0
GUILT;0
HUMAN;0
FLAMMABLE;0
CHITIN;0
NOGIB;0
CBM_CIV;0
CBM_POWER;0
CBM_SCI;0
CBM_OP;0
CBM_TECH;0
CBM_SUBS;0
FISHABLE;0
INTERIOR_AMMO;0
NO_NECRO;0
PET_HARNESSABLE;0
SHEARABLE;0
NO_FUNG_DMG;0
DROPS_AMMO;0
INSECTICIDEPROOF;0

22:05:46.582 INFO : npc::set_omt_destination - new goal for NPC [Tanisha 'Magpie' Betancourt] with [need_safety] is [farm_lot_wire_turn_h] in (2,-135,0).
00:32:05.455 INFO : npc::set_omt_destination - new goal for NPC [Laurel Burdick] with [need_weapon] is [lmoe] in (-14,-201,0).
00:36:04.377 : Log shutdown.
-----------------------------------------

-----------------------------------------
00:39:12.596 : Starting log.
00:39:12.596 INFO : Cataclysm DDA version 18b1e6e
00:39:12.597 INFO : [main] C locale set to C
00:39:12.597 INFO : [main] C++ locale set to C
00:39:12.597 INFO : SDL version used during compile is 2.0.14
00:39:12.597 INFO : SDL version used during linking and in runtime is 2.0.14
00:39:12.795 INFO : Number of render drivers on your system: 5
00:39:12.795 INFO : Render driver: 0/direct3d
00:39:12.795 INFO : Render driver: 1/direct3d11
00:39:12.795 INFO : Render driver: 2/opengl
00:39:12.795 INFO : Render driver: 3/opengles2
00:39:12.796 INFO : Render driver: 4/software
00:39:12.807 INFO : [options] C locale set to C
00:39:12.807 INFO : [options] C++ locale set to C
00:39:12.807 INFO : Setting language to: 'en'
00:39:12.807 INFO : [i18n] Scanning core translations from lang/mo/
00:39:12.807 INFO : [i18n] Scanning mod translations from ./mods/
00:39:12.817 WARNING : opendir [./mods/] failed with "No such process".
00:39:13.305 INFO : Active renderer: 4/software
00:39:14.756 INFO : USE_COLOR_MODULATED_TEXTURES is set to 0
00:39:14.843 INFO : Setting language to: 'en'
00:39:15.367 WARNING : opendir [./mods/] failed with "No such process".
00:39:24.666 WARNING : opendir [./save/Chastangq/mods] failed with "No such process".
00:39:39.863 INFO : Loaded tileset: UltimateCataclysm
00:39:41.194 INFO : Loaded tileset: UltimateCataclysm

### Additional context

_No response_

### LINKED ISSUE #52676: Incorrect calories of boiled fiddlestick heads
### Describe the bug

Calories and RDA of boiled fiddlestick heads may vary between multiples of 0, 2, or 3 when batch boiling fiddlesticks with mixed status.

### Steps To Reproduce

Gather fiddlesticks.
Wait, and maybe save/load cycle.
gather more.
Batch boil.

If you see calories as 0, eating them really does give 0 calories.  Save and load, you may then see a multiple of 2/3.

### Expected behavior

18 calories

### Screenshots

Screenshot 2021-11-06 110250
Screenshot 2021-11-06 110306

### Versions and configuration

0.F-2

### Additional context

_No response_

### LINKED ISSUE #54469: Cooked Foods Have No Caloric Value
### Describe the bug

Ran into this once the other day and again tonight cooking two times in succession - sometimes I'll cook something and it has nothing at all in the Calories column. Had this happen with a good-sized pile of jerky the other day, and tonight a starving new character made 40 boiled fiddleheads and can't get sustenance from them. No idea what causes it or why, it's very rare and there doesn't seem to be anything in the log about a cooking failure etc, and the recipe in & menu does show the items as having calories.

With the jerky I made the other day, I left the reality bubble for a while and when I came back it was fine. I drove about 10 squares away from the boiled fiddleheads this time and came back right away and there was no change, so it may take a overnight stay or something, to make it work I'm wondering? Weird bug, hard to reproduce, I've cooked hundreds of items across a few characters and only seen this happen twice.

I was cooking stacks, FWIW.

### Steps to reproduce

1. Cook some food.
2. Hit E to eat.
3. Notice that sometimes the calories column is empty for an item.

### Expected behavior

Expect successfully cooked foods to give calories, or at least show a fail message if not.

### Screenshots

image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: f1997bf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Graphical Overmap [Graphical_Overmap],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by mqrause**
#### Summary
Bugfixes "Fix wrong calorie count on batch crafted foods"

#### Purpose of change

Fixes #51361
Fixes #52429
Fixes #52676
Fixes #52628
Fixes #54469

#### Describe the solution

Merge components on the finished craft so their count doesn't get rounded down when divided by batch size.

#### Testing

1. Spawn a fillet of fish
2. wait an hour or so, then spawn another fillet of fish
3. have two stacks of fillets of fish that don't combine
4. batch craft two cooked fish
5. without this fix the result has 0 calories, with it it has 260 per portion
6. without this fix, save and load would fix the 0 charges components, resulting in one cooked fish made of two fillets of fish, doubling the calories

#### Additional context

The real fix, as so often, would be removing count_by_charges.

### CODE REVIEW

File: src/crafting.cpp [hunk 1]
```diff
@@ -1278,10 +1281,22 @@ void Character::complete_craft( item &craft, const cata::optional<tripoint> &loc
                 if( should_heat || remove_raw ) {
                     comp.set_flag_recursive( flag_COOKED );
                 }
+
+                //when batch crafting, set_components depends on components being merged, so merge any unmerged ones here
```
Comment (NetSysFire) [inline src/crafting.cpp:1285]:
```suggestion
                // when batch crafting, set_components depends on components being merged, so merge any unmerged ones here
```

consistent whitespace with comments
