### PR TITLE
Fix the crash when attaching UPS conversion mod (#21293)

### LINKED ISSUE #21293: OpenBSD builds crash when applying UPS Conversion (item::is_tool() @ item.cpp:3772)
## Description of Problem
Latest Cataclysm DDA from github builds without any modification on OpenBSD 6.1 x86_64 with either clang (in snapshots) or gcc v4.9.4 (in ports).

No matter which compiler used, applying a UPS conversion mod on any tool that accepts it will crash the game. 

This crash is reproducible on other OpenBSD installs, not on Linux however.

It's not specific to tiles or curses.

When built with GCC and debugged with GDB (both in ports), the following backtrace is produced. 

```
Thread 1 received signal SIGBUS, Bus error.
item::is_tool (this=this@entry=0xee89ffdc10) at src/item.cpp:3772
3772        return type->tool != nullptr;
(gdb) bt
#0  item::is_tool (this=this@entry=0xee89ffdc10) at src/item.cpp:3772
#1  0x000000ec5eef141f in player::invoke_item (this=this@entry=0xeea0d62000, used=used@entry=0xee89ffdc10, pt=...) at src/player.cpp:8854
#2  0x000000ec5eef1d5b in player::invoke_item (this=this@entry=0xeea0d62000, used=used@entry=0xee89ffdc10) at src/player.cpp:8843
#3  0x000000ec5ef1a56f in player::use (this=0xeea0d62000, inventory_position=inventory_position@entry=63) at src/player.cpp:8833
#4  0x000000ec5f33b82c in game::use_item (this=this@entry=0xee84da3c00, pos=63, pos@entry=-2147483648) at src/game.cpp:6975
#5  0x000000ec5f34c4f3 in game::handle_action (this=this@entry=0xee84da3c00) at src/game.cpp:2875
#6  0x000000ec5f350778 in game::do_turn (this=0xee84da3c00) at src/game.cpp:1468
#7  0x000000ec5f2b9a2c in main (argc=<optimized out>, argv=<optimized out>) at src/main.cpp:485
```

## How do I reproduce it?

Install latest OpenBSD in a VM or on bare metal (if you want a good firewall later). Use the package manager to install newer GCC than what's included in base and everything needed to clone and build CDDA:
`# pkg_add -U gcc gdb gmake autoconf automake git`

Install SDL libraries for tiles support:
`# pkg_add -U sdl2 sdl2-gfx sdl2-image sdl2-ttf`

Pull latest
`$ git clone --depth=1 https://github.com/CleverRaven/Cataclysm-DDA`

Compile the source
`$ gmake CXX=eg++ TILES=1 -j4`

Debug live process
`$ egdb cataclysm-tiles`

Great, now with the debugging menu, give yourself a welder and a UPS Conversion mod. Apply the mod and the game will crash.

## Notes

OpenBSD takes a different approach to software security and will actively cause processes to crash if they violate safe memory practises.

### PR DESCRIPTION
**Pull request by BrettDong**
Fixes #21293 .

The crash is a use-after-free of the instance of the UPS conversion mod in player's inventory. `p->i_rem` is called first, which removes the item. But later, `(the removed mod item)::is_tool` is called, causing the crash.

The fix is to delay the actual removal of the item to some time after invoking `item::is_tool`. I created an activity to do so because there is no better approach I can think of.

### CODE REVIEW

File: src/iuse.cpp [hunk 1]
```diff
@@ -5567,14 +5567,12 @@ int iuse::toolmod_attach( player *p, item *it, bool, const tripoint& ) {
...
     }
 
-    if( !loc->ammo_remaining() || g->unload( *loc ) ) {
-        //~ $1 - toolmod, $2 - base item
-        p->add_msg_if_player( m_good, _( "You attach the %1$s to the %2$s" ),
-                              it->tname().c_str(), loc->tname().c_str() );
-
-        loc->contents.push_back( p->i_rem( it ) );
+    if( loc->ammo_remaining() ) {
+        g->unload( *loc );
```
Comment (BevapDin) [inline src/iuse.cpp]: The result of `unload` is now ignored. It is actually important as it may be `false`, which indicates the user has canceled the unloading (e.g. because they don't have a suitable container for liquid ammo).

Also: why did you remove the comment (starting with `~` means it's for the translators)?

Also: why are you now calling `add_msg` instead of `add_msg_if_player`?

Comment (BrettDong) [inline src/iuse.cpp]: I copy-pasted the code from `gunmod_add_finish`. I'll update both of them.

File: src/activity_handlers.cpp [hunk 2]
```diff
@@ -1784,6 +1785,20 @@ void activity_handlers::gunmod_add_finish( player_activity *act, player *p )
...
 
+void activity_handlers::toolmod_add_finish( player_activity *act, player *p )
+{
+    act->set_to_null();
+    if( act->values.size() != 1 ) {
+        debugmsg( "Insufficient arguments to ACT_TOOLMOD_ADD" );
+        return;
+    }
+    item &tool = p->i_at( act->position );
+    item &mod = p->i_at( act->values[0] );
```
Comment (codemime) [inline src/activity_handlers.cpp]: Both variables can be made `const`.

File: src/activity_handlers.cpp [hunk 3]
```diff
@@ -1784,6 +1785,20 @@ void activity_handlers::gunmod_add_finish( player_activity *act, player *p )
     }
 }
 
+void activity_handlers::toolmod_add_finish( player_activity *act, player *p )
+{
+    act->set_to_null();
+    if( act->values.size() != 1 ) {
+        debugmsg( "Insufficient arguments to ACT_TOOLMOD_ADD" );
```
Comment (codemime) [inline src/activity_handlers.cpp]: "Insufficient _number_ of arguments ..." would be clearer.

File: src/activity_handlers.cpp (hunk 2 above)
Comment (BrettDong) [inline src/activity_handlers.cpp]: No, they'll be modified: `tools.contents` will have a new element, and `mod` will be removed.

Comment (codemime) [inline src/activity_handlers.cpp]: True in case of `tool` (I've managed to miss this somehow), but `mod` still can be made `const` since `i_rem()` accepts a constant pointer.
