### PR TITLE
can't remove irremovable toolmods

### LINKED ISSUE #35959: Bugs with installing and uninstalling toolmods
# Describe the bug

1. When installing some toolmod (for example, medium battery mod on e-ink tablet PC), the message is `Permanently install medium battery mod in your e-ink table PC?`. However, you can remove said mod with a screwdriver with no problems despite that warning.
2. Removing said mod from tool doesn't return it to player. Mod simply disappears.
3. There is no message on successful removing.

# Steps To Reproduce
Try to install medium battery mod on e-ink tablet PC, then try to remove the mod.

# Expected behavior
Either forbid removing toolmods (as they should be permanent) or correctly give them to player in case of successful removing. In the latter case, there should be a message.

# Versions and configuration
 - OS: Windows 10 Pro x64
 - Game Version: 0.D-9836
 - Graphics version: Tiles
 - Mods loaded: Default only

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Bugfixes "can't remove irremovable toolmods and feedback on toolmod removal"```
#### Purpose of change

Fixes #35959
#### Describe the solution

Does both of the things the issue suggests: Does not allow you to remove toolmods that are irremovable, and gives a message as feedback when removing a toolmod. If a tool cannot have any mods removed from it, it won't show up in the list when you try to remove them in the toolmod removal menu.
#### Testing

spawn e-ink tablet and medium battery mod
unload e-ink tablet
install battery mod into e-ink tablet
activate toolbox to try to remove mods
get the message "you don't have any modified tools."

I don't actually know a mod that's removable to test the message, but i added that too because it seemed very reasonable to have.

### CODE REVIEW

File: src/iuse.cpp [hunk 1]
```diff
@@ -1678,8 +1686,10 @@ int iuse::remove_all_mods( player *p, item *, bool, const tripoint & )
 
     if( !loc->ammo_remaining() || g->unload( *loc ) ) {
         auto mod = std::find_if( loc->contents.begin(), loc->contents.end(), []( const item & e ) {
-            return e.is_toolmod();
+            return e.is_toolmod() && !e.is_irremovable();
         } );
+        add_msg( m_info, string_format( "%s %s", _( "You remove the following mods from the tool:" ),
```
Comment (Qrox) [inline src/iuse.cpp]:
```suggestion
        add_msg( m_info, _( "You remove the %s from the tool." ), mod->tname() );
```

File: src/iuse.cpp [hunk 2]
```diff
@@ -1666,7 +1666,15 @@ int iuse::remove_all_mods( player *p, item *, bool, const tripoint & )
     }
 
     auto loc = g->inv_map_splice( []( const item & e ) {
-        return !e.toolmods().empty();
+        if( e.toolmods().empty() ) {
```
Comment (BevapDin) [inline src/iuse.cpp]: Checking this special case in unnecessary. If `toolmods()` returns an empty container, the loop below will essentially skip it and the lambda returns false.
