### PR TITLE
Fix pets jumping into fire 

### LINKED ISSUE #60581: Cats should not be set on fire while starting a fire
### Describe the bug

Two recent youtubers have burned their cats to death while setting fires. One crashed the game to save the cat, the other was very sad. Neither intended to burn their beloved cats to death.

### Steps to reproduce

Spawn a cat, spawn catfood to give it, spawn a fireplace, start a fire. There is a nonzero chance the cat will wander into the fire while you are lighting it and burn to death

### Expected behavior

You do not set your sweet kitty on fire

### Screenshots

_No response_

### Versions and configuration

Recent experimental

### Additional context

See https://www.youtube.com/watch?v=kebdSC1qgjI&lc=UgzLQBKoiUHCabkvm714AaABAg.9eoYUwM4OWh9f1ehFMH1b_ minute 54

### PR DESCRIPTION
**Pull request by Manushenkov**
#### Summary
Bugfixes "Your pets won't walk into fire and traps anymore"

#### Purpose of change
This was a pet rat, it jumped into the fireplace and died. F
image

#### Describe the solution
~~Very few things have both STUMBLE and AVOID_DANGER flags. namely cockroaches, so~~ i enabled stumble() to check for avoid danger before stumbling. this fixes the bug because pets manually call the stumble function when they're around you

#### Describe alternatives you've considered
Making dogs fireproof? 

#### Testing
Spawned 5 dogs, before they'd jump into lit fireplaces occasionally, now i can' wait for a few hours and they don't

### CODE REVIEW

File: src/monmove.cpp [hunk 1]
```diff
@@ -2382,6 +2382,9 @@ void monster::stumble()
     while( !valid_stumbles.empty() && !is_dead() ) {
         const tripoint_bub_ms dest = random_entry_removed( valid_stumbles );
         if( can_move_to( dest ) &&
+            // Don't stumble into dangerous tiles if monster has AVOID_DANGER flag
+            // Makes it do that your pets don't stumble into traps and fireplaces
```
Comment (thaelina) [inline src/monmove.cpp]:
```suggestion
            // Makes it so that your pets don't stumble into traps and fireplaces
```

**Review by thaelina — CHANGES_REQUESTED** [review]

**Comment by mqrause** [comment]
Sounds like this will fix #60581. #77538 is also related, but probably a different issue.

**Comment by thaelina** [comment]
This will affect more than just pets, it's for every monster that can stumble. 

Personally I'm not sure if when something stumbles it should be avoiding any dangers at all, including the one that is already checked in here but it's just my opinion really. 
A stumble is an uncontrolled movement and plenty of people have hurt themselves by accidentally running into things they did not want to, including myself.

**Comment by Manushenkov** [comment]
> This will affect more than just pets, it's for every monster that can stumble.
> 
> Personally I'm not sure if when something stumbles it should be avoiding any dangers at all, including the one that is already checked in here but it's just my opinion really. A stumble is an uncontrolled movement and plenty of people have hurt themselves by accidentally running into things they did not want to, including myself.

I investigated a bit deeper, the stumbles() function is mostly used to just randomly move monsters around, to make the world alive so to speak, it doesn't have anything to do with STUMBLES flag, the flag is used for pathfinding 

with one exception

```
if( has_effect( effect_stunned ) || has_effect( effect_psi_stunned ) ) {
    stumble();
    moves = 0;
    return;
}
```

So with this change stunned and psi_stunned monsters that have PATH_AVOID_* will stop stumbling into traps/fire. They probably should but that can be addressed in another PR because they also currently will avoid water

**Comment by Manushenkov** [comment]
Actually i'll just add a new commit for involuntary stumble

**Comment by mqrause** [comment]
Splitting it up into voluntary/involuntary is good. Duplicating the code isn't.

File: src/monmove.cpp
Comment (Manushenkov) [inline src/monmove.cpp]: The new function is different enough, making adding helper functions rather unwieldy, i could move this part into a helper, without the 
```
    const tripoint_bub_ms below( pos_bub() + tripoint::below );
    if( here.valid_move( pos_bub(), below, false, true ) ) {
        valid_stumbles.push_back( below );
    }
```
part below it, because i don't want downstairs involuntary stumbles (that's more like falling)

Code duplication seems fine to me here, or i could refactor with a helper if it'd make more sense 

Another approach is passing a "is_voluntary" flag into 1 unified function

Comment (mqrause) [reply src/monmove.cpp]: > Another approach is passing a "is_voluntary" flag into 1 unified function

That's the approach I would choose. Ultimately you're just turning some checks off for involuntary stumbling. You could still add wrapper functions around it if you want to give it more intuitive names.
