### PR TITLE
Fix for unarmed still using bash damage

### LINKED ISSUE #23454: Martial art styles are using Bashing Weapons instead of Unarmed Combat
Game version: latest

Operating system: Windows 7

Tiles or curses: tiles

Mods active: N/A

### Expected behavior
When using martial arts without a weapon, the unarmed combat skill should be used.

### Actual behavior
The bashing weapons skill is used instead, the damage output is very low.

### Steps to reproduce the behavior
Create a Blackbelt character, choose Muay-Thai as a preffered style (should work with any style, it's just the one I typically use), try to punch some zombies. Watch yourself dealing ridiculously low damage and training Bashing Weapons instead of Unarmed Combat. Upon selecting "No style" everything works as intended.

Looks like the bug was introduced in one of these commits https://github.com/CleverRaven/Cataclysm-DDA/commit/651fce62a30fe1588d34100a76408a044bd71c6b https://github.com/CleverRaven/Cataclysm-DDA/commit/4c1e7f35c4151d82caa4224f39f4de8995466b56 https://github.com/CleverRaven/Cataclysm-DDA/commit/063f797bf7b0c0074e872777012f3b798fe8b6cb https://github.com/CleverRaven/Cataclysm-DDA/commit/cc3b7172682e9e0342177365f7a8df237f1b3851

### PR DESCRIPTION
**Pull request by NotFuji**
Closes #23454
Tested with Taekwondo and Muay Thai, both receive appropriate damage bonuses.

Also fixed spears acting like a fist-on-a-stick when using "force unarmed"

### CODE REVIEW

**Comment by Coolthulhu** [comment]
A better fix would be not to use `player::unarmed_weapon` and instead add `item::unarmed_weapon` where you'd check `is_null() || has_flag("UNARMED_WEAPON")`.

Basically, instead of saying "the player is armed with an unarmed attack", which is rather fragile (it works for most cases at the moment, but consider future developments like off-hand attacks), you'd be saying "attacks with this item are unarmed". With null item, AKA lack of item, counting as unarmed.

File: src/item.cpp [hunk 1]
```diff
@@ -391,6 +391,11 @@ bool item::is_null() const
     return (type == nullptr || type == nullitem() || typeId() == s_null);
 }
 
+bool item::unarmed_weapon() const
```
Comment (Night-Pryanik) [inline src/item.cpp]: I'd rename this to `is_unarmed_weapon`, but this is minor.

File: src/item.cpp [hunk 2]
```diff
@@ -391,6 +391,11 @@ bool item::is_null() const
...
+{
+    return ( has_flag( "UNARMED_WEAPON" ) || is_null() );
```
Comment (Night-Pryanik) [inline src/item.cpp]: External brackets are redundant.
