### PR TITLE
Fix auto attack to handle lighting and glass better

### LINKED ISSUE #37904: Autoattack wont attack things nearby in the lab start.
# Describe the bug
Pressing auto attack while next to zombies in the lab start wont attack them it just waits.

# Steps To Reproduce

1. Start in a lab as security guard
2. Find some zombies, not the brute you start next to auto attack works on him.
3. Try to auto attack

# Expected behavior
Autoattack to swing at clearly hostile zombies next to me

# Screenshots
image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-12170-g2073ce1 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

 -->

# Additional context
Autoattack works for the first swing after loading, or if you open up the debug menu and close it right away it'll work for a single attack.
This hasnt happened to me yet starting on another scenario type, only in the lab.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix autoattack missing targets and targeting through glass"

#### Purpose of change
Fixes #37904
Fixes auto attack targeting invalid targets and ignoring valid ones

#### Describe the solution
Apparently map::sees is a bit buggy so used suggestions of people on discord to use find clear path instead.  To handle glass and the like iterate through the returned path to make walls invalidate a target.

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -5387,8 +5387,17 @@ std::vector<Creature *> player::get_visible_creatures( const int range ) const
 std::vector<Creature *> player::get_targetable_creatures( const int range ) const
 {
     return g->get_creatures_if( [this, range]( const Creature & critter ) -> bool {
-        bool can_see = ( ( sees( critter ) && g->m.sees( pos(), critter.pos(), 100 ) ) //the call to map.sees is to make sure that even if we can see it through walls
-                         || sees_with_infrared( critter ) );                           //via a mutation or cbm we only attack targets with a line of sight
+        bool can_see = ( ( sees( critter ) || sees_with_infrared( critter ) ) );
```
Comment (ZhilkinSerg) [inline src/player.cpp]:
```suggestion
        bool can_see = ( sees( critter ) || sees_with_infrared( critter ) );
```

File: src/player.cpp [hunk 2]
```diff
@@ -5387,8 +5387,17 @@ std::vector<Creature *> player::get_visible_creatures( const int range ) const
...
+        if( can_see )   //handles the case where we can see something with glass in the way or a mutation lets us see through walls
+        {
+            std::vector<tripoint> path = g->m.find_clear_path( pos(), critter.pos() );
+            for( tripoint point : path ) {
```
Comment (ZhilkinSerg) [inline src/player.cpp]:
```suggestion
            for( const tripoint &point : path ) {
```
