### PR TITLE
Fix the vehicle bounds after refresh (if the vehicle has no parts)

### LINKED ISSUE #32391: std::bad_alloc
# Describe the bug

I was ramming into the refugee center again.
```
	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	.../src/debug.cpp:621
	std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::str() const
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/sstream:639
	log_crash
	.../src/crash.cpp:263
	crash_terminate_handler()
	.../src/crash.cpp:327
	__cxxabiv1::__terminate(void (*)())
	/var/tmp/portage/sys-devel/gcc-9.1.0-r1/work/gcc-9.1.0/libstdc++-v3/libsupc++/eh_terminate.cc:47
	std::terminate()
	??:?
	__cxa_throw
	??:?
	std::__throw_bad_cast()
	.../src/c++11/functexcept.cc:58
	__gnu_cxx::new_allocator<drag_column>::allocate(unsigned long, void const*)
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/ext/new_allocator.h:111
	std::allocator_traits<std::allocator<drag_column> >::allocate(std::allocator<drag_column>&, unsigned long)
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/alloc_traits.h:436
	std::_Vector_base<drag_column, std::allocator<drag_column> >::_M_allocate(unsigned long)
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_vector.h:296
	std::_Vector_base<drag_column, std::allocator<drag_column> >::_M_create_storage(unsigned long)
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_vector.h:311
	std::_Vector_base<drag_column, std::allocator<drag_column> >::_Vector_base(unsigned long, std::allocator<drag_column> const&)
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_vector.h:260
	std::vector<drag_column, std::allocator<drag_column> >::vector(unsigned long, std::allocator<drag_column> const&)
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_vector.h:416
	vehicle::coeff_air_drag() const
	.../src/vehicle.cpp:3566
	vehicle::slowdown(int) const
	.../src/vehicle_move.cpp:82
	vehicle::gain_moves()
	.../src/vehicle.cpp:4740
	map::vehmove()
	.../src/map.cpp:364
	std::map<tripoint, submap*, std::less<tripoint>, std::allocator<std::pair<tripoint const, submap*> > >::begin()
	/usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_map.h:355
	mapbuffer::begin()
	.../src/mapbuffer.h:65
	game::do_turn()
	.../src/game.cpp:1499
	main
	.../src/main.cpp:688
	__libc_start_main
	??:?
	_start
	??:?
```
e616c9e43ae96cf8558c8266d6cd5c6cec3ea2f8

[2019.07.09.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3390411/2019.07.09.zip)

Load and ram the refugee center repeatedly until you lose the engine, then repeat.

### PR DESCRIPTION
**Pull request by ipcyborg**
#### Summary
```SUMMARY: Bugfixes "Fix the vehicle bounds after refresh (if the vehicle has no parts)"```

#### Purpose of change
Fixes #32391

#### Describe the solution
This issue is explained here: https://github.com/CleverRaven/Cataclysm-DDA/issues/32391#issuecomment-517250186
The same goes for `vehicle::coeff_water_drag`.

Fixed by ensuring that vehicle bounds `mount_min` and `mount_max`  are set to (0,0) if the vehicle has no parts, instead of initial (123, -123). 
Also fixed the `rail_wheel_bounding_box`, since it was left like this: (INT_MAX, INT_MIN).

#### Describe alternatives you've considered
Tried to fix by doing `vehicle::refresh` in `vehicle::coeff_air_drag`, or in `vehicle::slowdown`. Failed, since the refresh is already done, but failed, since there is no parts in the vehicle.

Another alternative is to remove this vehicle with no parts at all - it is probably just a damaged, torn off vehicle part or something . But I don't know how to do it inside of the vehicle class code: probably should be done in the `game` or `map` while handling vehicle?

#### Testing
All `cata_test-tiles` tests passed.
Also tested with a lot of ramming of the refugee center (save file provided here #32391).

#### Additional context
Sometimes `vehicle::coeff_air_drag` reports "vehicle %s has negative drag slowdown". That is because there is no parts and the air drag is calculated incorrectly (has a very large negative value).
Need to be fixed in the separate PR.

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -5291,6 +5294,15 @@ void vehicle::refresh()
     rail_wheel_bounding_box.p1 = point( railwheel_xmin, railwheel_ymin );
     rail_wheel_bounding_box.p2 = point( railwheel_xmax, railwheel_ymax );
 
+    if( !refresh_done ) {
+        mount_min.x = 0;
+        mount_min.y = 0;
+        mount_max.x = 0;
+        mount_max.y = 0;
+        rail_wheel_bounding_box.p1 = point( 0, 0 );
```
Comment (ZhilkinSerg) [inline src/vehicle.cpp]:
```suggestion
        rail_wheel_bounding_box.p1 = point_zero;
```

File: src/vehicle.cpp [hunk 2]
```diff
@@ -5291,6 +5294,15 @@ void vehicle::refresh()
...
+        rail_wheel_bounding_box.p2 = point( 0, 0 );
```
Comment (ZhilkinSerg) [inline src/vehicle.cpp]:
```suggestion
        rail_wheel_bounding_box.p2 = point_zero;
```

File: src/vehicle.cpp [hunk 3]
```diff
@@ -5291,6 +5294,15 @@ void vehicle::refresh()
     rail_wheel_bounding_box.p1 = point( railwheel_xmin, railwheel_ymin );
     rail_wheel_bounding_box.p2 = point( railwheel_xmax, railwheel_ymax );
 
+    if( !refresh_done ) {
+        mount_min.x = 0;
+        mount_min.y = 0;
+        mount_max.x = 0;
+        mount_max.y = 0;
```
Comment (BevapDin) [inline src/vehicle.cpp]:
```suggestion
        mount_min = mount_max = point_zero;
```

File: src/vehicle.cpp [hunk 4]
```diff
@@ -5291,6 +5294,15 @@ void vehicle::refresh()
     rail_wheel_bounding_box.p1 = point( railwheel_xmin, railwheel_ymin );
     rail_wheel_bounding_box.p2 = point( railwheel_xmax, railwheel_ymax );
 
+    if( !refresh_done ) {
+        mount_min.x = 0;
```
Comment (ZhilkinSerg) [inline src/vehicle.cpp]: You won't need this three rows if you assign everythinh in the fourth one.

Comment (ipcyborg) [reply src/vehicle.cpp]: Yes, already fixed, thanks!
