### PR TITLE
Fields dont damage creatures in vehicles

### LINKED ISSUE #38918: Acid burns animals inside a vehicle
# Describe the bug
Animals carried inside a vehicle are injured by pools of acid on the road below.

# Steps To Reproduce
Load the attached save, and drive the RV straight ahead. Watch all the adorable baby chicks melt, then shed a tear for them, and finally CTRL-C because those cute little yellow v's deserve better.

# Expected behavior

Puddles of acid shouldn't harm animals inside an enclosed vehicle.

# Versions and configuration

Linux, 64 bit, happens regardless of mods loaded

# Additional context
https://anonfiles.com/J8I9B8i1o1/testworld-chicksonacid.tar_gz

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Fixes #38918 
As in title, creatures take damage from acid even when in a vehicle.
The same applies to other fields.

#### Describe the solution
Add a test to verify issue.
Exit early from creature_in_field if the creature is on a vehicle.

#### Describe alternatives you've considered
This needs a more nuanced fix to only bail out of fields that should be excluded, but in this case the improperly applied field effects have a much higher impact than the ones that will be improperly avoided.

#### Testing
New unit test pretty much handles it.

### CODE REVIEW

File: src/map_field.cpp [hunk 1]
```diff
@@ -1747,6 +1747,10 @@ void map::monster_in_field( monster &z )
         // Digging monsters are immune to fields
         return;
     }
+    if( veh_at( z.pos() ) ) {
+        // Immune when in a vehicle for now.
```
Comment (AMurkin) [inline src/map_field.cpp]: Use a task tag?
```suggestion
        // FIXME: Immune when in a vehicle for now.
```
