### PR TITLE
Fix eating from vehicle

### LINKED ISSUE #18168: 'E'ating soup from a tin located in a dragged shopping cart dumps the remainder of the soup on the floor.
I believe this started happening just recently in one of the recent builds.  I just upgraded to 0.C-5430 (was using 0.C-5427 before) and noticed this started happening.  A typical way for this to happen is I am raiding a home and collect all the unspoiled canned food, then I heat up the can using the hobo stove to make the can 'hot', and 'E'at it straight from the shopping cart, and bam, 3 charges of the soup are gone.  Then I drag the shopping cart a few tiles and notice there is a liquid '~' icon with 3 charges of soup on the floor (or whatever unused charges would be, so maybe sometimes 1).

Edit: since this might not happen with every type of canned liquid, I'll note it was 'meat soup' last time it happened.

### PR DESCRIPTION
**Pull request by alanbrady**
The problem is when dragging around a shopping cart and eating some food
from a non-resealable container, the game just puts the newly unsealed
tin can back in the cart.  Putting an opened bucket/non-resealable
container back into a vehicle causes the contents to then spill.  This
is almost certainly not what the player wanted.

This fixes the issue by using the same check used in put_into_vehicle()
to put potentially spillable things into vehicles.  To avoid code
duplication this puts the needed functionality into its own function into 
pickup.h/cpp and refactors put_into_vehicle() to use the new function.

As a side affect, this fixes the player being able to have spillable buckets in
their inventory if they start as sealed and become unsealed.

A future fix should probably add the option to wield the container directly 
as well.

Fixes #18168 

SUMMARY: Bugfixes "Fix eating from tin cans from a vehicle"

### CODE REVIEW

**Comment by dissociativity** [comment]
1 step closer to 0.D
[](https://github.com/CleverRaven/Cataclysm-DDA/issues/18168)

File: src/item.cpp [hunk 1]
```diff
@@ -4139,6 +4139,21 @@ const item &item::get_contained() const
     return contents.front();
 }
 
+bool item::handle_spillable_contents( player &p )
+{
+    if( is_bucket_nonempty()  && !spill_contents( p )  ) {
```
Comment (Night-Pryanik) [inline src/item.cpp]: Excessive space before &&.

Comment (alanbrady) [reply src/item.cpp]: Good eye

File: src/item.cpp [hunk 2]
```diff
@@ -4139,6 +4139,21 @@ const item &item::get_contained() const
     return contents.front();
 }
 
+bool item::handle_spillable_contents( player &p )
```
Comment (OrenAudeles) [inline src/item.cpp]: Could be made a free function `bool handle_spillable_contents( player &p, item &it)` since item functions `is_bucket_nonempty` and `spill_contents` are publicly accessible. This does not need to be a member function.

**Comment by alanbrady** [comment]
Hrm just did some testing and I seem to have broke something in put_into_vehicle, will check it out.
