### PR TITLE
Fix movement cost for throwing stacking items

### LINKED ISSUE #39077: Stacking throwing items have variable "Moves to fire" based on their stack count (bigger stack = more moves)
# Describe the bug

If you throw nets, bolas or throwing sticks, the cost of the throw action depends of the numbers of items in the stack.

# Expected behavior

I was expecting the action to have a fixed movement cost (at least for my char with his current bonuses/penalties).

# Steps To Reproduce

1. Debug a stack of 3 bolas, put it in your inventory
2. Use 't' to throw the bolas
3. Check the Moves to fire in the sidebar (in my case it was 174)
4. Throw it
5. Check inventory, in WEAPON HELD you have a stack of 2 in your hand (3 debugged - 1 thrown), this is what triggers the bug.
6. Use 't' to throw another bola.
7. Check the Moves to fire in the sidebar, it's different from point 3. (in my case it was 130)

You can keep throwing, and as the stack gets lower, the cost of movement is reduced.

# Additional context
I did some analysis in the code/JSONs and i think I know what is the issue, but I'm not sure how it would be the best way to fix this because I'm not that experienced with C++ or the class designs...

All the affected items seem to be marked in the JSONs as "AMMO" type and "thrown" ammo_type (example of affected: net/bolas, not affected: throwing axes/knives).

When you wield or try to throw these kind of items, the whole stack goes to your hand in WEAPON HELD slot (in the case of throwing axes, only 1 item of the stack goes to the hand).

Then the code in calculates the attack_time() in item.cpp as:
image
Which use volume()/weight() as part of the formula, and those methods return the volume/weight for the stack instead of a single item, changing the attack cost depending on stack size.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.D-13348-g7f3a4a4 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Alternative Map Key [alt_map_key]
]

### PR DESCRIPTION
**Pull request by KurzedMetal**
#### Summary
SUMMARY: Bugfixes "Fix throwing movement cost for stacking items like bola/net/throwing stick."

#### Purpose of change
Fixes #39077

#### Describe the solution
Like I explained in #39077, the problem was itemp.cpp attack_time() formula using full stack weight/volume instead of a single item. I just added a division to the formula to divide that part by the stack item count.

#### Describe alternatives you've considered
I checked if any existing method I could returned volume/weight for single item so I could reuse them, but they don't exist.

#### Testing
Tested in a local build, before the change, throwing a bola from a stack of 3 costed 170, 130 for the first 2 throws, now it cost 70 for every throw (at least for my testing character, numbers may vary for other char).

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -4600,7 +4600,7 @@ int item::lift_strength() const
 
 int item::attack_time() const
 {
-    int ret = 65 + volume() / 62.5_ml + weight() / 60_gram;
+    int ret = 65 + ( volume() / 62.5_ml + weight() / 60_gram ) / count();
```
Comment (Night-Pryanik) [inline src/item.cpp]: Could 'count' ever be zero?

Comment (KurzedMetal) [reply src/item.cpp]: If you see the definition of count() you'd see it's not possible.
