### PR TITLE
Display RAS weapon reload time in aim ui

### LINKED ISSUE #50571: Reload and fire unloading when not loaded
### Describe the bug

If you bring up the `f`ire menu with a `RELOAD_AND_SHOOT` weapon equipped and then `esc` out of it, you lose several seconds unloading the weapon that you haven't loaded yet.

### Steps To Reproduce

1. Spawn a slingshot
2. Bring up the `f`ire menu
3. Immediately `esc` out of the menu
4. Several seconds pass as you unload the weapon that you didn't load yet

### Expected behavior

I expect to be able to hit `esc` to bail out for free, unless I've `r`eloaded the weapon or I've begun to aim.

### Screenshots

_No response_

### Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.F-1395-gbcb8e7f596 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

I've tested that the unload code is hitting this message:
https://github.com/CleverRaven/Cataclysm-DDA/blob/bcb8e7f596513f0a72d064c1c4f0fd1bed0461fe/src/activity_actor.cpp#L2655
but I haven't traced the code any more than that.

As a side note, the aiming times don't take into account the time to load the weapon, but the first time you steady your aim (`.`), it takes seconds to load the ammo that weren't advertised to the player.

### LINKED ISSUE #54997: RELOAD_AND_SHOOT weapons do not display the move cost of loading them with ammo in the 'f'ire menu, and lock you into loading ammo dangerously.
### Describe the bug

Weapons such as bows and slings that are loaded with each firing do not display the cost of loading the ammo into the weapon in the 'f'ire menu. After the fire menu is entered and the ammo is selected, pressing '.' or 'a/c/p' results in extra movement points being spent on obtaining the ammo from its container **without having displayed that information to the player, and with no way to stop loading the ammo even if in danger/hurt.** This combined with a container that is slow to get items from could result in a potentially lethal amount of time passing with no way to opt out.

Related to #54973 
RELOAD_AND_SHOOT weapons have something weird going on in general when it comes to loading and unloading ammo within the 'f'ire menu.

### Steps to reproduce

1. Create a character, give them:
- A slingshot
- A short rope
- Several pebbles, inside the short rope
2. Wield the slingshot, spawn a zombie near the character.
3. Press 'f' and see the supposed amount of movement points it costs to aim and fire the sling shot at various levels
4. Select an aiming option with 'a/c/p' or slightly increase aim level with '.' and see the massive number of turns that pass due to the cost of removing ammo from the short rope, the lack of pop-ups about danger, and the inability to stop the loading of ammo from continuing.

### Expected behavior

- The 'f'ire menu should display how long it takes to load the weapon with ammo.
- The loading process should be stoppable and give pop-ups when in danger.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 1607
- Game Version: 272b7a4 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### LINKED ISSUE #73287: Wrong stamina cost of RAS weapon
### Describe the bug

First, stamina cost set in load_RAS_weapon is wrong.

https://github.com/CleverRaven/Cataclysm-DDA/blob/7636bccdac05607dc8549d3741455b75e848673b/src/activity_actor.cpp#L528-L530

https://github.com/CleverRaven/Cataclysm-DDA/blob/7636bccdac05607dc8549d3741455b75e848673b/src/item.cpp#L14704-L14718

As you can see, `get_min_str()` always returns positive number or zero, so load_RAS_weapon is not burning but regenerating stamina.

Second, stamina cost of RAS weapon is also caculated in ranged.cpp.

https://github.com/CleverRaven/Cataclysm-DDA/blob/7636bccdac05607dc8549d3741455b75e848673b/src/ranged.cpp#L1493-L1511

I'm not sure why it needs to be caculated twice.

### Attach save file

N/A

### Steps to reproduce

1. Add one line in load_RAS_weapon to print get_min_str, compile and run the game, enter and quit the aim ui, see get_min_str returns a positive number.

### Expected behavior

Correctly caculate the stamina cost of RAS weapon.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.3447 (23H2)
- Game Version: 0.G-9016-g1b87e4d5a7-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by osuphobia**
#### Summary
Interface "Display RAS weapon reload time in aim ui"
#### Purpose of change
Port over and modified https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2468
Fix https://github.com/CleverRaven/Cataclysm-DDA/issues/50571
Fix https://github.com/CleverRaven/Cataclysm-DDA/issues/54997
Fix https://github.com/CleverRaven/Cataclysm-DDA/issues/73287
#### Describe the solution
The move points needed for reloading RAS weapon is added to firing cost in aim ui, these moves are not consumed if you don't try to shoot or aim your bow. If you try to make your aim steadier by pressing `.`, your will reload your bow first.
As https://github.com/CleverRaven/Cataclysm-DDA/commit/d94eea7b5acdb915e6c9908ff72e74456def0e61 is solved, AIM_AFTER_FIRING is enabled for RAS weapon.
Deal with https://github.com/CleverRaven/Cataclysm-DDA/issues/73287, to make sure the stamina is cost correctly.
Modified the reload time test case to compare the total firing cost.

More details:

Before this PR, pressing `f` will choose the ammo and immediately reload with it, the moves and stamina are also consumed at this point. This caused several problems which are described in the issues.
After my modifications, calling `load_RAS_weapon` only determines what ammo the RAS weapon will use, but you don't reload with it at this point, and the moves needed are also not consumed but added to the total time_to_attack needed.
The item_location of ammo selected for reloading is saved at `reload_loc`, it is a reference of favorite ammo (if exists), or ammo manually selected.

It's just like you are only checking how your bow will perform with currently selected arrow.
The game will call `update_ammo_range_from_gun_mode` and use reload_loc to caculate and display ammo, range, and relevant data.
This also enabled the use of reload/switch ammo option for RAS weapon, the option was useless as you can't do anything with a weapon already fully loaded.
Canceling at this point will also cost no moves and stamina, and the refunding of moves in `unload_RAS_weapon` is also needless now.

Once you decide to really use you RAS weapon with currently selected ammo, by either triggering an aim action or one of the four firing actions, you will then reload with it, and consume the moves and stamina needed. The moves and stamina will not be refunded (and there is no need to do so anymore, as AIM_AFTER_FIRING will no longer trigger this mechanic).

#### Describe alternatives you've considered
Choose the way in https://github.com/CleverRaven/Cataclysm-DDA/pull/73305.
#### Testing
Compiled and tested locally.
RAS_time1
RAS_time2
#### Additional context
Based on https://github.com/CleverRaven/Cataclysm-DDA/pull/73305, it was reverted https://github.com/CleverRaven/Cataclysm-DDA/pull/73482 becuase of the attribution issue.
Made further adjustment so the inconsistency pointed out in https://github.com/CleverRaven/Cataclysm-DDA/issues/73354#issuecomment-2081741740 is fixed.
Please do not squash if this is to be merged to keep the credits.

### CODE REVIEW

File: src/activity_actor.cpp [hunk 1]
```diff
@@ -518,48 +508,37 @@ bool aim_activity_actor::load_RAS_weapon()
...
-
-        // Note: this code works only for avatar
-        item_location loc = item_location( you, gun.target );
-        you.unload( loc, true );
-
-        // Give back time for unloading as essentially nothing has been done.
-        if( first_turn ) {
-            you.set_moves( moves_before_unload );
+        if( !loaded_RAS_weapon ) {
+            // Refund stamina cost if not loaded.
```
Comment (anothersimulacrum) [inline src/activity_actor.cpp:531]: Don't refund, just only do the cost on reload?

File: src/ranged.cpp [hunk 2]
```diff
@@ -2650,6 +2689,15 @@ target_handler::trajectory target_ui::run()
                 loop_exit_code = ExitCode::Timeout;
                 break;
             }
+
+            if( you->get_wielded_item()->has_flag( flag_RELOAD_AND_SHOOT ) ) {
+                if( !you->get_wielded_item()->ammo_remaining() && activity->reload_loc ) {
+                    you->mod_moves( -RAS_time );
```
Comment (anothersimulacrum) [inline src/ranged.cpp:2695]: Don't mod moves, add moves to the activity.

File: src/activity_actor.cpp (hunk 1 above)
Comment (osuphobia) [reply src/activity_actor.cpp:531]: The old feature intended to refund moves never worked. In my reverted PR, PC will not reload the bow until pressing `f`ire, and quitting the aim ui also cost no moves. In this PR, PC will not reload the bow until pressing `f`ire or `.` to make aim steadier(codes your reviewed below is for this feature) , so quitting the aim ui in the "first turn" will not cost moves.

Comment (anothersimulacrum) [reply src/activity_actor.cpp:531]: I missed that, apologies. I don't think we need a refund mechanic though, we should just only burn things when they need to be burnt.

Comment (osuphobia) [reply src/activity_actor.cpp:531]: Yes, but when writing this PR, I didn't come up with a good replacement to the current plan where stamina needed for reloading the bow is burnt in aim_activity_actor::load_RAS_weapon(). Do you have any idea?
By the way, stamina is also cost in mod_stamina_archery, see https://github.com/CleverRaven/Cataclysm-DDA/issues/73287.

File: src/ranged.cpp (hunk 2 above)
Comment (osuphobia) [reply src/ranged.cpp:2695]: Ok, I'll change this.

Comment (osuphobia) [reply src/ranged.cpp:2695]: Sorry, can you please tell me how to change this? As stated above, PC will reload the bow in this part, by using mod_moves I mean the moves to reload is used up immediately here, and will not be counted any more in time_to_attack.

File: src/activity_actor.cpp (hunk 1 above)
Comment (osuphobia) [reply src/activity_actor.cpp:531]:
```diff
diff --git a/src/activity_actor.cpp b/src/activity_actor.cpp
index 54e7382bdf..6711873e25 100644
--- a/src/activity_actor.cpp
+++ b/src/activity_actor.cpp
@@ -509,9 +509,6 @@ bool aim_activity_actor::load_RAS_weapon()
         return false;
     }

-    // Burn 0.6% max base stamina without cardio/BMI factored in x the strength required to fire.
-    you.burn_energy_arms( - gun->get_min_str() * static_cast<int>( 0.006f *
-                          get_option<int>( "PLAYER_MAX_STAMINA_BASE" ) ) );

     reload_loc = opt.ammo;
     return true;
@@ -527,12 +524,6 @@ void aim_activity_actor::unload_RAS_weapon()

     gun_mode gun = weapon->gun_current_mode();
     if( gun->has_flag( flag_RELOAD_AND_SHOOT ) ) {
-        if( !loaded_RAS_weapon ) {
-            // Refund stamina cost if not loaded.
-            you.burn_energy_arms( gun->get_min_str() * static_cast<int>( 0.006f *
-                                  get_option<int>( "PLAYER_MAX_STAMINA_BASE" ) ) );
-            return;
-        }
         if( gun->ammo_remaining() ) {
             item_location loc = item_location( you, gun.target );
             you.unload( loc, true );
diff --git a/src/ranged.cpp b/src/ranged.cpp
index 2bd9e5ef9a..1b360612da 100644
--- a/src/ranged.cpp
+++ b/src/ranged.cpp
@@ -880,7 +880,7 @@ int Character::fire_gun( const tripoint &target, int shots, item &gun, item_loca
         return 0;
     }
     if( gun.ammo_required() > 0 && !gun.ammo_remaining() && !ammo ) {
-        debugmsg( "%s's gun %s is empty and has no ammo for reloading.", gun.tname() );
+        debugmsg( "%s is empty and has no ammo for reloading.", gun.tname() );
         return 0;
     }
     bool is_mech_weapon = false;
@@ -931,7 +931,10 @@ int Character::fire_gun( const tripoint &target, int shots, item &gun, item_loca
     int delay = 0; // delayed recoil that has yet to be applied
     while( curshot != shots ) {
         if( !!ammo && !gun.ammo_remaining() ) {
-            gun.reload( get_avatar(), ammo, 1 );
+            Character &you = get_avatar();
+            gun.reload( you, ammo, 1 );
+            you.burn_energy_arms( - gun.get_min_str() * static_cast<int>( 0.006f *
+                                  get_option<int>( "PLAYER_MAX_STAMINA_BASE" ) ) );
         }
         if( gun.faults.count( fault_gun_chamber_spent ) && curshot == 0 ) {
             mod_moves( -get_speed() * 0.5 );
@@ -2690,10 +2693,13 @@ target_handler::trajectory target_ui::run()
                 break;
             }

-            if( you->get_wielded_item()->has_flag( flag_RELOAD_AND_SHOOT ) ) {
-                if( !you->get_wielded_item()->ammo_remaining() && activity->reload_loc ) {
+            item_location weapon = activity->get_weapon();
+            if( weapon->has_flag( flag_RELOAD_AND_SHOOT ) ) {
+                if( !weapon->ammo_remaining() && activity->reload_loc ) {
                     you->mod_moves( -RAS_time );
-                    you->get_wielded_item()->reload( get_avatar(), activity->reload_loc, 1 );
+                    weapon->reload( get_avatar(), activity->reload_loc, 1 );
+                    you->burn_energy_arms( - weapon->get_min_str() * static_cast<int>( 0.006f *
+                                           get_option<int>( "PLAYER_MAX_STAMINA_BASE" ) ) );
                     activity->reload_loc = item_location();
                     activity->loaded_RAS_weapon = true;
                 }
```
This could be a solution?

File: src/ranged.cpp (hunk 2 above)
Comment (osuphobia) [reply src/ranged.cpp:2699]:
```suggestion
                    activity->aif_duration += RAS_time;
```
Would this be a proper solution?

Comment (osuphobia) [reply src/ranged.cpp:2699]: @anothersimulacrum 

The way bow works before this PR:
1. Pressing f to choose the arrow and immediately reload with it.
2. Steady your aim or fire your bow, then the moves needed for reloading is consumed at once.
3. Not to shoot and quit the aim ui, with your bow unloaded immediately.

In step two, there were two bugs. The first one is, if you press f to enter the aim ui, then immediately quit it without any aiming action, you were supposed to get all the moves "refunded". The functions were wrote in that way, but failed to do so, thus you were losing moves by simply entering the aim ui. That's why auto re-aiming was banned for RAS weapon.
The second one is, if you aim at an adjacent tile and try pressing `.` to steady your aim, since that it can not be steadier, you just wait for one turn. Then, despite that there is an arrow notched, the moves needed for reloading is not consumed, firing your bow or quitting the aim ui will not consume the moves either.

This PR fixed those things, moves are not consumed if you don't try to shoot or aim your bow. If you try to make your aim steadier by pressing `.`, your will reload your bow first, then moves needed for reloading is consumed, and I believe that's the intended behavior.

https://github.com/CleverRaven/Cataclysm-DDA/blob/1aca3eb08b535090058514c8abf9396d91a4b591/src/activity_actor.cpp#L516-L536

https://github.com/CleverRaven/Cataclysm-DDA/blob/1aca3eb08b535090058514c8abf9396d91a4b591/src/ranged.cpp#L1060

The existing functions use mod_moves, so I just copied the method. I failed to find a way to "add moves to the activity", can you show me an example?

Comment (anothersimulacrum) [reply src/ranged.cpp:2700]: Apologies, both for taking time to reply, and for the confusion - I thought it was more obvious (it's not!).
You add to `activity->moves_left` (and if you're feeling fancy, `moves_total`).

File: src/activity_actor.cpp (hunk 1 above)
Comment (anothersimulacrum) [reply src/activity_actor.cpp]: That looks good, yes.

File: src/ranged.cpp (hunk 2 above)
Comment (osuphobia) [reply src/ranged.cpp:2700]: Hi, thanks for your review. I asked @RenechCDDA for help, got the same advice, and unfortunately it didn't work.
If I understand it right, activity->moves_left is not for controlling moves needed when used in the aim activity.
https://github.com/CleverRaven/Cataclysm-DDA/blob/10a7e40a116696da62ace8fe8964621f8d88505b/src/activity_actor.cpp#L309-L314

https://github.com/CleverRaven/Cataclysm-DDA/blob/10a7e40a116696da62ace8fe8964621f8d88505b/src/activity_actor.cpp#L351-L357

https://github.com/CleverRaven/Cataclysm-DDA/blob/10a7e40a116696da62ace8fe8964621f8d88505b/src/ranged.cpp#L1516-L1537

In aim_activity_actor, moves_left is set to 1 when starting to aim, set to 0 when quitting the aim ui, and that's all. It is not modified or used elsewhere. Changing it from one  positive integer to another dosen't affect anything.

Instead, moves needed for aiming is consumed in do_aim, pressing `.` will consume 1 move for ten times, and choosing AIMED_SHOT etc will consume moves needed to reach certain aiming level.

Again, if I understand it right, using mod_moves is the only way here to affect moves that PC have.

Comment (osuphobia) [reply src/ranged.cpp:2700]: Also, this part seems to be wrong. PC's stamina is drained every time do_aim is called. I'm not sure, is it trying to compare 
moves_left with 1, but accidentally used moves PC has?
```
             // Only drain stamina on initial draw 
             if( you.get_moves() == 1 ) { 
                 mod_stamina_archery( you, relevant ); 
             } 
```

Comment (anothersimulacrum) [reply src/ranged.cpp:2700]: Ack, you are right, my bad. I didn't realize the aiming activity was so funky and I gave you a bad suggestion. Use `mod_moves`.

Comment (anothersimulacrum) [reply src/ranged.cpp:2700]: I don't see any reason why the stamina would be drained every call to do_aim, I don't have any explanation for why you'd see that, unfortunately.

Comment (osuphobia) [reply src/ranged.cpp:2700]: > I don't see any reason why the stamina would be drained every call to do_aim, I don't have any explanation for why you'd see that, unfortunately.

Well, I will deal with it in another PR. Thanks for your help!

**Comment by Maleclypse** [comment]
@I-am-Erk is this the desired order of operations for archery?

**Comment by I-am-Erk** [comment]
I've been trying to review and understand this, @osuphobia, but even asking other devs we're all still a bit unclear on what exactly is going on. I think we need a more clear breakdown in the PR description of what you're doing and why in order to properly review this. I get the impression what you're doing is probably fine, but in order to know for sure, in the current state, I'd have to learn all the RAS weapon code from scratch.

File: src/ranged.cpp [hunk 3]
```diff
@@ -918,6 +930,12 @@ int Character::fire_gun( const tripoint &target, int shots, item &gun )
     int hits = 0; // total shots on target
     int delay = 0; // delayed recoil that has yet to be applied
     while( curshot != shots ) {
+        if( !!ammo && !gun.ammo_remaining() ) {
+            Character &you = get_avatar();
+            gun.reload( you, ammo, 1 );
+            you.burn_energy_arms( - gun.get_min_str() * static_cast<int>( 0.006f *
+                                  get_option<int>( "PLAYER_MAX_STAMINA_BASE" ) ) );
+        }
```
Comment (kevingranade) [inline src/ranged.cpp:938]:
```suggestion
        // Special handling for weapons where we supply the ammo separately (i.e. ammo is populated)
        // instead of it being loaded into the weapon, reload right before firing.
        if( !!ammo && !gun.ammo_remaining() ) {
            Character &you = get_avatar();
            gun.reload( you, ammo, 1 );
            you.burn_energy_arms( - gun.get_min_str() * static_cast<int>( 0.006f *
                                  get_option<int>( "PLAYER_MAX_STAMINA_BASE" ) ) );
        }
```

File: src/turret.cpp [hunk 4]
```diff
@@ -317,7 +317,7 @@ int turret_data::fire( Character &c, const tripoint &target )
     gun_mode mode = base()->gun_current_mode();
 
     prepare_fire( c );
-    shots = c.fire_gun( target, mode.qty, *mode );
+    shots = c.fire_gun( target, mode.qty, *mode, item_location() );
```
Comment (kevingranade) [inline src/turret.cpp:320]: Why is this necessary? You have supplied a default argument in the prototype of character::fire_gun()

**Comment by kevingranade** [comment]
If I'm understanding this correctly, the change here is "defer loading (including spending time and stamina on it) of reload and shoot weapons until you interact with the aim menu by either triggering an aim action or firing", and also "list whole cost of firing in UI, including reload time", is that right?

File: src/ranged.cpp [hunk 5]
```diff
@@ -155,7 +155,9 @@ static const std::set<material_id> ferric = { material_iron, material_steel, mat
 static constexpr int AIF_DURATION_LIMIT = 10;
 
 static projectile make_gun_projectile( const item &gun );
-static int time_to_attack( const Character &p, const itype &firing );
+static int NPC_time_to_attack( const Character &p, const itype &firing );
+static int time_to_attack( const Character &p, const item &firing, const item_location &loc );
+static int RAS_time = 0;
```
Comment (kevingranade) [inline src/ranged.cpp:160]: I can see why you would want to do this, but it's not ok, this data needs to be plumbed into the affected methods not stashed like this.

File: src/turret.cpp (hunk 4 above)
Comment (osuphobia) [reply src/turret.cpp:320]: Just followed the way they did in the BN PR, will remove this.

File: src/ranged.cpp (hunk 5 above)
Comment (osuphobia) [reply src/ranged.cpp:160]: OK, I'll rewrite this part :)

**Comment by osuphobia** [comment]
> I've been trying to review and understand this, @osuphobia, but even asking other devs we're all still a bit unclear on what exactly is going on. I think we need a more clear breakdown in the PR description of what you're doing and why in order to properly review this. I get the impression what you're doing is probably fine, but in order to know for sure, in the current state, I'd have to learn all the RAS weapon code from scratch.

@I-am-Erk 
What I did is basically the same as Kevin's description. 
Before this PR, pressing `f` will choose the ammo and immediately reload with it, the moves and stamina are also consumed at this point.
After my modifications, calling load_RAS_weapon only determines what ammo the RAS weapon will use, but you don't reload with it at this point, and the moves needed are also not consumed but added to the total time_to_attack needed.

It's just like you are only checking how your bow will perform with currently selected arrow in the "first turn".
This also enabled the use of reload/switch ammo option for RAS weapon, the option was useless as you can't do anything with a weapon already fully loaded.
Canceling at this point will also cost no moves and stamina, and the refunding of moves in unload_RAS_weapon is also needless now.

Once you decide to really use you RAS weapon with currently selected ammo, by either triggering an aim action or one of the four firing actions, you will then reload with it, and consume the moves and stamina needed.

File: src/ranged.cpp [hunk 6]
```diff
@@ -155,9 +155,8 @@ static const std::set<material_id> ferric = { material_iron, material_steel, mat
 static constexpr int AIF_DURATION_LIMIT = 10;
 
 static projectile make_gun_projectile( const item &gun );
-static int NPC_time_to_attack( const Character &p, const itype &firing );
-static int time_to_attack( const Character &p, const item &firing, const item_location &loc );
-static int RAS_time = 0;
+static int time_to_attack( const Character &p, const itype &firing );
+static int RAS_time( const Character &p, const item &firing, const item_location &loc );
```
Comment (osuphobia) [inline src/ranged.cpp:159]: I rewrote this part in a3eb1559a62ac8c53a7a71f09af3e05d182cfe3c, can you review it again? @kevingranade
