### PR TITLE
Add Character sight tests, fix Ursine eyes

### LINKED ISSUE #44084: Ursine Vision nearsighted in all situation
# Describe the bug

As the description, nearsighted should be only when light. Result always as nearsighted.
Also without glasses when you choose Ursine Vision as start trait.

# Steps To Reproduce

1. Create a character with Ursine Vision
2. Skip to night time
3. Check the max sight
4. Wear glasses, check the max sight again

# Expected behavior

Can be 1 of them:

1. Change the Ursine Vision description, and add glasses when choose as start trait
2. Only nearsighted when direct light

# Screenshots

image
image

# Additional context

Max sight of Ursine Vision is define from here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/character.cpp#L1984-L1986

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

SUMMARY: Bugfixes "Add Character sight tests, fix Ursine eyes"

#### Purpose of change

The main objective of this PR will be to allow Ursine eyes to have full range in darkness, and limited range in bright light unless wearing glasses. This will make the mutation consistent with its description.

A secondary goal is to have that feature tested, along with other trait-related sight impairments.

Fix #44084 

#### Describe the solution

- Add tests for character sight impairments, including a failing test for Ursine eyes in the dark
- Fix Ursine eyes mutation, so they have unrestricted vision in the dark (and so the new test passes)
- Make `sight_impaired()` return true when character `is_blind` (and so the new test passes)
- Remove an apparently unnecessary call to `recalc_sight_limits` in the `player` constructor, which crashed the game after adding the call to `get_map`.
- TODO: Extend vision range in the dark to match mutation description

New tests include:
- Blindfold: impaired, 0 sight range (was failing before blindfold fix, now passes)
- Boomered: impaired, 1 range
- Nearsighted:
  - impaired, 4 range without glasses
  - unimpaired, 60 range with glasses
- Darkness effect: impaired, 10 range
- Ursine eyes:
  - light: impaired, 4 range without glasses, 60 with glasses
  - dark: unimpaired, 60 range without glasses (was failing before, now passing with the bugfix)

#### Describe alternatives you've considered

~~I have some doubt about the impact of removing `recalc_sight_limits` from the `player` constructor, but it does not seem necessary, nor appropriate to call it here.~~ Resolved in 5fa219e

In a half moon or full moon, Ursine Vision does not give any extra range. Even plain human characters can see 27 tiles in a full moon, so there does not seem much reason to press the advantage at this level. I don't know whether it's reasonable to extend the range for half-moon lighting conditions.

It's also quite silly that one can "activate" their Ursine Vision at will, but I don't see any good way to remove that functionality, and it might affect a lot of other mutations outside the scope of this PR.

Due to enum-based lighting mechanics for the moon, moonlight does not gradually transition from day-to-day as the moon's phase changes. There is a hard, stepped pattern in the moon's light for each discrete phase as documented in [tests/moon_test.cpp](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/tests/moon_test.cpp). This also contributes to the extra night vision being a rather crude approximation.

There is one last problem, apparently due to how `ambient_light_at` does not catch up when ascending stairs into light, I get full vision when I first come up the stairs into the light:

image

After 1 turn, this diminishes back to the expected 4 tiles:

image

In other words, immediately after climbing stairs, the `ambient_light_at` the player's position is still computed to be a very low (dark) number, so `recalc_sight_limits` gives Ursine Eyes the uninhibited range of being in darkness, until the player waits a turn or takes a step. This gives the player a slight "cheat" advantage, but is deeper than I want to tackle in this PR (which is already pushing the bounds of scope creep).

#### Testing

Run `tests/cata_test '[sight],[vision]'` and make sure all tests pass.

Playtest the "Ursine Vision" mutation with debug - `p`layer `M`utate`. See reduced range in the day, better range at night. Get some eyeglasses and see that it helps.

Use debug menu `m`ap `t`ime to set the current day to 60 (new moon), 67 (half moon), 74 (full moon) in the wee hours to test moonlight effects.

Use the `[` player mutation menu to "activate" and "deactivate" the mutation and see the difference in range at night-time (this has no effect during the day).

#### Additional context

Underground, I can see 6 tiles away (this is the same as a character with normal vision, ~~and needs to be increased~~):

image

Outdoors, at night with a new moon, Ursine Vision gives a 7-tile visibility range:

image

Without Ursine Vision, the range is only 2 tiles:

image

### CODE REVIEW

**Comment by wapcaplet** [comment]
Actually fixing this bug is much more of a pain in the arse than I expected. Even with `is_in_sunlight()` being true at the character's position, both `light_at()` and `ambient_light_at()` are zero, and `fine_detail_vision_mod()` is returning a large value (8.0) indicating extreme darkness.

**Comment by wapcaplet** [comment]
Leaving in `WIP` status while I try to figure out some problems with Ursine Vision:
- Full moon is too bright, and severely reduces Ursine vision range (it should not)
- When coming up stairs into daylight, visibility range is not immediately reduced, but takes a turn to take effect

File: src/player.cpp [hunk 1]
```diff
@@ -250,7 +250,6 @@ player::player()
         vitamin_levels[ v.first ] = 0;
     }
 
-    recalc_sight_limits();
```
Comment (wapcaplet) [inline src/player.cpp:253]: Can anyone tell me if this is going to be a problem? I removed it because this constructor is called before we even reach the main game menu, causing a segfault trying to `get_map` (because there's no map yet), and there doesn't seem to be any point in recalculating the character's sight limits so early. There are plenty of other recalc calls to make up for it long before an actual character is spawned in-game.

If this is safe to remove, I wonder if the folowing `calc_encumbrance()` could go away too.

Or, perhaps both could be gated by some check for whether the map has been initialized yet. I'm open to suggestions.

Comment (wapcaplet) [reply src/player.cpp:253]: Resolved in 5fa219e

**Comment by wapcaplet** [comment]
Appveyor got this failure in `grenade_lethality` that I cannot reproduce locally with the same seed:

```
Randomness seeded to: 1599930063
-------------------------------------------------------------------------------
grenade_lethality
-------------------------------------------------------------------------------
C:\Projects\Cataclysm-DDA\tests\explosion_balance_test.cpp(143)
...............................................................................
C:\Projects\Cataclysm-DDA\tests\explosion_balance_test.cpp(143): FAILED:
due to a fatal error condition:
  SIGSEGV - Stack overflow
===============================================================================
test cases:    145 |    144 passed | 1 failed
assertions: 522342 | 522341 passed | 1 failed
Command exited with code -1073741571
```
