### PR TITLE
Fix activities not getting interrupted by dangerously close enemies

### LINKED ISSUE #54091: Dropping should be interrupted when the enemies get dangerously close
### Describe the bug

Dropping items is not automatically interrupted when the enemies get dangerously close to you.

### Steps to reproduce

1. Wear a hiking backpack
2. Debug wish for 100 splintered wood
3. Spawn a zombie 30 tiles away from you
3. Notice that you do not get interrupted when the zombie gets dangerously close
4. The first automatic interruption is "Ouch, something hurts! Stop dropping?"

Alternatively:
1. Load the attached save file: [tmp.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7821270/tmp.zip)
2. Drop the 218 splintered wood under your feet
3. Notice that you do not get interrupted when the zombie gets dangerously close
4. The first automatic interruption is "Ouch, something hurts! Stop dropping?"

### Expected behavior

I expected dropping to work the same way as waiting, crafting and many other activities: if enemies get close, I get interrupted before they start attacking me

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: :core-4.1-amd64:core-4.1-noarch; Distributor ID: Fedora; Description: Fedora release 34 (Thirty Four); Release: 34; Codename: ThirtyFour; 
- Game Version: 4d22129 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### Additional context

Possibly related: https://github.com/CleverRaven/Cataclysm-DDA/issues/50979

### PR DESCRIPTION
**Pull request by mqrause**
#### Summary
Bugfixes "Fix activities not getting interrupted by dangerously close enemies"

#### Purpose of change

Fixes #54091

#### Describe the solution

Initialize `player_activity::moves_left` to `calendar::INDEFINITELY_LONG`.
I saw the craft and disassemble actors do this to allow interruption, so default to this. All activities based on speed or time overwrite it anyway, the rest would have to set it to that.
Only outlier is `longsalvage_activity_actor` which is written in a weird way, so it still can't be interrupted.

Added a test that checks a few activities for their interruption capabilities.

#### Describe alternatives you've considered

Rewriting all activities to be based on speed or time and make use of `moves_left`.

#### Testing

Run tests with `[activity][interruption]`.

### CODE REVIEW

**Comment by Maleclypse** [comment]
Is there any way that a test can be added to check if anything causes a regression on this in the future?

**Comment by mqrause** [comment]
> Is there any way that a test can be added to check if anything causes a regression on this in the future?

I tried fiddling around with that a bit. Seems hard because all the stuff happens in the main game loop. I mostly don't know how to make a monster move in a unit test.

**Comment by kevingranade** [comment]
Look at tests/monster_test.cpp

**Comment by mqrause** [comment]
Added a crude test to one of the test cases in `player_activity_test.cpp`. I'd love some feedback before expanding on that.

**Comment by Maleclypse** [comment]
@wapcaplet Are you able to help with this test? If not no worries. :)

**Comment by mqrause** [comment]
Updated with interrupting fields changes. If I get a thumbs up for the test structure/design, all that's left is to generalize it and apply it to the other activity tests to get a bit more coverage. The ones present in `player_activities_test.cpp` probably aren't the most representative, but I don't want work on this to explode by adding completely new activities.

File: src/player_activity.cpp [hunk 1]
```diff
@@ -464,3 +466,28 @@ void player_activity::inherit_distractions( const player_activity &other )
         ignore_distraction( type );
     }
 }
+
+
+std::map<distraction_type, std::string> player_activity::get_distractions()
```
Comment (wapcaplet) [inline src/player_activity.cpp:471]: This function is a good candidate for a simpler and more focused unit test, now that you've factored it out of `do_turn`.

It's great to have the sort of "end-to-end" (which you've already done) that sets up the activity and actually confirms that interruption works during activity processing, but because this function is now isolated from the activity processing stuff, it might be easier to test it directly, checking that it returns the expected distraction type and message in different field/monster situations.

File: src/game.cpp [hunk 2]
```diff
@@ -3854,6 +3854,18 @@ Creature *game::is_hostile_within( int distance, bool dangerous )
     return nullptr;
 }
 
+field_entry *game::is_in_dangerous_field()
```
Comment (wapcaplet) [inline src/game.cpp:3857]: This also looks like it would be quite easy to unit test.

File: src/player_activity.cpp (hunk 1 above)
Comment (mqrause) [reply src/player_activity.cpp:471]: Yeah, classic case of not seeing the forest for the trees.

There's still worth in checking this for different activities, but no actual processing is needed. Simply constructing and starting the activity is enough. I guess the real work here will be making a list with all/many of the activities. Then just run some standard cases with and without monsters and fields on them.

**Comment by wapcaplet** [comment]
The tests are looking much better and more comprehensive now, nice work.

**Comment by mqrause** [comment]
I think I'm done here. There's still a ton that _could_ be done, but the coverage should be good enough for a start.

**Comment by mqrause** [comment]
Actually looping over sections like that silently skips them because they need to be unique.
