### PR TITLE
Fix off-by-one error in bomb fragment calculation.

### LINKED ISSUE #26367: Buffer overflow in game::shrapnel
**Describe the bug**  
I ran the unit tests with AddressSanitizer and it found a stack overflow in `game::shrapnel` (in the `grenade_lethality` test).

**Details**
`visited_cache` is defined here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/ff0c8d4ccbea7ba7626e7498bf1267e2fa470069/src/explosion.cpp#L439
`end` is defined here:
https://github.com/CleverRaven/Cataclysm-DDA/blob/ff0c8d4ccbea7ba7626e7498bf1267e2fa470069/src/explosion.cpp#L445
then the problematic access is in this loop:
https://github.com/CleverRaven/Cataclysm-DDA/blob/ff0c8d4ccbea7ba7626e7498bf1267e2fa470069/src/explosion.cpp#L459-L462
In the test `m.getmapsize()` returns `MAPSIZE` (which happens to be 11), and the loop bounds are inclusive, so `end.x` and `end.y` can equal `MAPSIZE * SEEX` and `MAPSIZE * SEEY` respectively, which overflows the `visited_cache` array (many times).

**Additional context**  
Looks like this code was last modified in #24836.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Fixes #26367 
Pretty straightforward, the loop goes out of bounds and shouldn't.  I don't know if this had any symptoms in practice, but it's definitely wrong.

### CODE REVIEW

File: src/explosion.cpp [hunk 1]
```diff
@@ -442,7 +442,7 @@ std::vector<tripoint> game::shrapnel( const tripoint &src, int power,
     // Basically bisect between 0 and map diameter using shrapnel_calc().
     // Need to update shadowcasting to support limiting range without adjusting initial distance.
     const tripoint start = { 0, 0, src.z };
-    const tripoint end = { m.getmapsize() *SEEX, m.getmapsize() *SEEY, src.z };
+    const tripoint end = { m.getmapsize() * SEEX, m.getmapsize() * SEEY, src.z };
```
Comment (narc0tiq) [inline src/explosion.cpp]: `astyle` v3.0.1 thinks you're dereferencing the pointers `SEEX` and `SEEY`, thus why it wants
```suggestion
    const tripoint end = { m.getmapsize() *SEEX, m.getmapsize() *SEEY, src.z };
```

...should I grab a newer astyle for the build machine?

Comment (kevingranade) [reply src/explosion.cpp]: No let's not open that cannon worms, this was just me manually "fixing" it and forgetting to make sure astyle agreed with me.
