### PR TITLE
Shorten acid ant trails, and stop formic infanticide

### LINKED ISSUE #25054: Acid ants still produce too much acid
**Describe the bug**  
Acid ants produce far too much acid despite changes in the past to alleviate it. An average ant is able to produce whole pools worth of stuff on its own, leaking it at the speed and in quantities suggesting eldritch, reality-bending dimensions of the inside of its body.

**To Reproduce**  
1. Find acid ants.
2. Provoke acid ants.

**Expected behavior**  
Acid ants produce acid in very low quantities, comparable to that of acidic zombies.

**Screenshots**  
too much acid

**Versions and configuration(please complete the following information):**
Operating system: Win7
Game version: 0.C-30780
Tiles or curses: Tiles
Mods active: More Survival Tools, Stats Through Skill, Vehicle Additions Pack, Tanks and Other Vehicles, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits, Extended Realistic Guns.

### LINKED ISSUE #26743: Acid Ant larvae not immune to acid
**Describe the bug**  
The larvae that appear in sulfurous ant hives aren't immune to acid, and so die rapidly from the acid that ends up covering everything.

**To Reproduce**  
 - Enter a larvae chamber in an acid ant hill
 - Observe all of the larvae die to acid splatter

**Expected behavior**  
Ants shouldn't be murdering their own young with their acid trails

**Versions and configuration(please complete the following information):**
 - O.C-33849-gcd5965ed4a

### PR DESCRIPTION
**Pull request by I-am-Erk**
#### Summary

```SUMMARY: Bugfixes "Acid ants: soldier trail length and larvae immunity"```  

#### Purpose of change

Fixes #26743 Acid Ant larvae not immune to acid
I hope fixes #25054 Acid ants still produce too much acid

#### Describe the solution

Larvae not immune to acid: While regular ant larvae aren't immune to acid either, this is currently producing larval genocide in acid anthills and probably isn't intended. Making them acidproof is a reasonable solution, as they're mutant ants, not real ones.

Soldiers produce too much acid: The idea is that soldier ant trails should now be on a timer that lets them produce scattered trails instead of one long uninterrupted slime trail. 
EDIT: Changed this to a 20% chance per step of dropping an acid trail, for cleaner code that also works instead of not-working.

#### Describe alternatives you've considered

Soldier ant trails could be removed, but they are pretty flavourful and I think this would be a sad solution.
SHORTACIDTRAIL could instead pick a random number between 1 and 5, and if it rolls a 5, produce a blob of acid.

EDIT: Could go back to the original version, but code it to actually work, leaving short 3-tile trails then a 5-tile gap using a timer variable that decrements every time the function is called, then resets at 0.

#### Additional context

I hope I've done this correctly, it's my first real C++ coding in a long time, and I can't do a test compile from my work computer. It's just a for loop though.

#### Progress
- [x] Make larvae acid proof
- [x] create shortacidtrail flag
- [x] make shortacidtrail flag release less acid than regular acidtrail

### CODE REVIEW

**Comment by I-am-Erk** [comment]
I don't know why gorgon hates my PRs so much. \<swear\> you too Jenkins.

**Comment by DracoGriffin** [comment]
This was kind of annoying to reference but I don't want to buy any entomology or myrmecology books. So in an effort to keep things free:

Ant reference
[Source](https://books.google.com/books?id=iEkQAQAAMAAJ&lpg=PA73&ots=b2qW7WHO4k&dq=ant%20larvae%20chitin%20development&pg=PA73#v=onepage&q=ant%20larvae%20chitin%20development&f=false)

>**Callow Stage** The newly hatched ant, ... . The coloration, which is due to the **_deposition of chitin_** and perhaps some pigment, will take place in two days; that is, in less than two days one cannot distinguish the younger from the older individuals.

(Emphasis mine)
[Source](http://www.antwiki.org/wiki/Solenopsis_molesta#Development)

I agree with the revised acid trail, but if larvae die to acid, that's a separate thing. They don't have the immunity yet as their chitin hasn't fully developed. And given the numbers of ants, it shouldn't cause any issues if larvae are dying anyway really (if a survivor is really culling an entire anthill, why do they care if larvae die? Secondly, if they want the larvae alive, then they should be trapping ant queens for that or something).

**Comment by I-am-Erk** [comment]
I don't know that citing real larval chitin properties makes much sense, since the very fact that we have giant ants defies conventional biology. The logic for having larvae acid proof is pretty straightforward:

1. Player attacks may contain acid, but it's rarely a major feature. It's not likely to even be noticeable to the player.

2. Coding soldiers to only secrete acid outside the hive unless threatened, the most realistic solution, is quite difficult and adds very little to the game,

3. Larvae finding their home environment fatally hostile isn't logical.

Rather than try to program soldiers to behave more realistically around larvae, for very little gain, it makes a lot of sense to simply make larvae acid proof, a change that will have little other effect on the player.

-

I don't really understand what an astyle error is, I'm afraid. Maybe I'll try compiling it at home and see if I can get a clearer error.

**Comment by kevingranade** [comment]
Feel free to code an alternate adjustment that resolves this issue more to your liking, but the argument that larvae must be killed en masse by their hivemates simply because they're, "thin skinned", doesn't hold up.

Acid immunity is a viable adjustment, so I'm inclined to merge it.

File: src/monmove.cpp [hunk 1]
```diff
@@ -1173,7 +1173,18 @@ bool monster::move_to( const tripoint &p, bool force, const float stagger_adjust
     if( has_flag( MF_ACIDTRAIL ) ) {
         g->m.add_field( pos(), fd_acid, 3 );
     }
-
+    
+    // Not all acid trail monsters leave as much acid. Generate trails of three tiles, then pause for ten tiles.
+    if( has_flag( MF_SHORTACIDTRAIL ) ) {
+        for( int acidlength = 3; acidlength >= -10; acidlength = acidlength -1 ) {
```
Comment (BevapDin) [inline src/monmove.cpp]:
```suggestion
        for( int acidlength = 3; acidlength >= -10; acidlength-- ) {
```

File: src/monmove.cpp [hunk 2]
```diff
@@ -1173,7 +1173,18 @@ bool monster::move_to( const tripoint &p, bool force, const float stagger_adjust
...
+            if( acidlength >=1 ) {
+                g->m.add_field( pos(), fd_acid, acidlength );
+            } else { if( acidlength == -9 ) {
```
Comment (BevapDin) [inline src/monmove.cpp]:
```suggestion
            } else if( acidlength == -9 ) {
```

File: src/monmove.cpp [hunk 3]
```diff
@@ -1173,7 +1173,18 @@ bool monster::move_to( const tripoint &p, bool force, const float stagger_adjust
...
+                acidlength = 3; // reset loop
```
[the remark this answers is not in the document]
Comment (I-am-Erk) [reply src/monmove.cpp]: The loop shouldn't reset until there have been five non-acid iterations of it. Have I missed something?

File: src/mtype.h [hunk 4]
```diff
@@ -105,6 +105,7 @@ enum m_flag : int {
     MF_ELECTRIC,            // Shocks unarmed attackers
     MF_ACIDPROOF,           // Immune to acid
     MF_ACIDTRAIL,           // Leaves a trail of acid
+    MF_SHORTACIDTRAIL,           // Leaves an intermittent trail of acid
```
Comment (Night-Pryanik) [inline src/mtype.h]:
```suggestion
    MF_SHORTACIDTRAIL,       // Leaves an intermittent trail of acid
```

File: src/monmove.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (AMurkin) [reply src/monmove.cpp]: This is definitely an endless loop.
I suggest this code:
```cpp
    if( has_flag( MF_SHORTACIDTRAIL ) ) {
        if( one_in( 5 ) ) {
            g->m.add_field( pos(), fd_acid, 3 );
        }
    }
```

[the remark this answers is not in the document]
Comment (I-am-Erk) [reply src/monmove.cpp]: Oh, yes. Duh. To do what I want to do it wouldn't be a for loop, I'd have to decrement the trail length variable every time the function was called.

I'll probably just change it to a random drop though, it's cleaner.

**Comment by I-am-Erk** [comment]
OK. Code changed to a more logical and not dysfunctional version. This should work now.

File: src/monmove.cpp [hunk 5]
```diff
@@ -1173,7 +1173,14 @@ bool monster::move_to( const tripoint &p, bool force, const float stagger_adjust
     if( has_flag( MF_ACIDTRAIL ) ) {
         g->m.add_field( pos(), fd_acid, 3 );
     }
-
+
```
Comment (kevingranade) [inline src/monmove.cpp]:
```suggestion

```
