### PR TITLE
Remove zombie code from zzip from last refactor

### LINKED ISSUE #83163: Error when decompressing/compressing with the zzip.exe
### Describe the bug

When I try to execute 
`zzip ./save/Sky Island/#Sm9hbw==.sav.zzip` 
the following error occurs:
```
Decompressing ./Sky Island/#Sm9hbw==.sav.zzip -> ./save/Sky Island/
Unable to handle "./save/Sky Island/#Sm9hbw==.sav.zzip"
./save/Sky Island/#Sm9hbw==.sav.zzip:0: Error reading zzip header.
```

I have also tried to compress a save file, but i didn't get it to work, though that bit could be on me
Regardless, it failed silently

I'm on windows

### Attach save file

[Sky Island-trimmed.tar.gz](https://github.com/user-attachments/files/22679347/Sky.Island-trimmed.tar.gz)

### Steps to reproduce

1. Try to use the zzip as indicated above on the save below

### Expected behavior

I expected the decompression and compression to work

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.3194 (24H2)
- Game Version: cdda-experimental-2025-10-02-1836 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Mind Over Matter [mindovermatter],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved],
    Bombastic Perks [bombastic_perks],
    Martial Mastery [perk_melee_system],
    DinoMod [DinoMod],
    Sky Island [skyisland]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by akrieger**
#### Summary
None

#### Purpose of change
Fixes #83163.

zzip.exe was broken on the decompression path after the last change. I moved code around and either did too many ctrl-z's or did a bad rebase/merge, but a copy of the moved code stayed behind in the old location. This made it break trying to decompress anything because it would try to read the zzip header twice and fail the second time.

There was also a zombie early return in a loop from the earlier code which was not in a loop but in a callback invoked repeatedly, where return made sense. This broke decompressing files with multiple entries, it would only decompress one file and then quit.

There was a memory leak triggered by loading zzips without a dictionary. This happens for .sav files and for the new compact_to flow which opens the destination temporary zzip without a dictionary because we just copy entries over.

#### Describe the solution
Delete the zombie code.

#### Testing
Manually decompress zzips of each category (sav, map, map memory, overmap) and validate the results. Recompress the same and validate.

ASAN job on this PR should be green.

### CODE REVIEW

File: tools/save/zzip_main.cpp [hunk 1]
```diff
@@ -220,22 +220,8 @@ struct ZzipStream {
...
             ZSTD_FrameHeader header;
-            size_t error_code = ZSTD_getFrameHeader( &header, base, remaining_len );
-            if( ZSTD_isError( error_code ) ||
-                header.dictID != kFooterChecksumMagic ||
-                header.frameContentSize != 2 * sizeof( uint64_t ) ) {
-                RETURN_ERROR( ZzipError( zzip_path, 0, "Error reading zzip header." ) );
-            }
-
-            base += ZSTD_SKIPPABLEHEADERSIZE + 2 * sizeof( uint64_t );
-            remaining_len -= ZSTD_SKIPPABLEHEADERSIZE + 2 * sizeof( uint64_t );
```
Comment (akrieger) [inline tools/save/zzip_main.cpp:238]: This was copied to up line 187.

**Comment by akrieger** [comment]
https://github.com/akrieger/Cataclysm-DDA/actions/runs/18248716994/job/51961927213#step:19:1 Asan passed in my repo but we should still wait for it here.
