### PR TITLE
Make overmapbuffer zzip aware

### LINKED ISSUE #84123: Can't place Balthazar Bunker
### Describe the bug

When I activate the modified radio, I get the following bug after the message:

 DEBUG : Couldn't find placed overmap special balthazar_bunker???

 REPORTING FUNCTION : find_or_create_om_terrain
 C++ SOURCE FILE    : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\mission_util.cpp
 LINE               : 208
 VERSION            : cdda-experimental-2025-12-09-0810-dirty

### Attach save file

[NH Mag-trimmed.tar.gz](https://github.com/user-attachments/files/24059635/NH.Mag-trimmed.tar.gz)

### Steps to reproduce

Activate modified radio.

### Expected behavior

I expect to not get an error message, and probably to get a quest.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26200.7171 (25H2)
- Game Version: cdda-experimental-2025-12-09-0810-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Magiclysm [magiclysm],
    No Hope [no_hope]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
Fix #84123.

#### Describe the solution
Copy the zzip administration for overmap files to overmapbuffer. Defined constants for repeatedly used strings, especially since this now spreads the usage to another file.

#### Describe alternatives you've considered
- Let the overmapbuffer::terrain_filename() add the zzip suffix if zzip is active. Made an attempt which failed for some reason. Gave up without investigating further.
- Change overmapbuffer::terrain_filename() to include the "overmaps" path segment when zzip is active. Probably doesn't work since different file systems use different separators.
- Change overmapbuffer::terrain_filename() to return a complete path rather than a simple file name. May be the cleanest solution, but didn't want to expand this activity further.
- Introduce an overmap::file_exist(point_abs_om) operation for usage by overmapbuffer.cpp and an overmap::om_path(point_abs_om) operation for usage both by the new operation and the two places in overmap.cpp where paths are calculated (you'd still have to process the file differently depending on zzip usage, but you can have a common local constant for the path to the file).

#### Testing
Limited to:
- Loaded the save from #84123 and verified activating the modified radio did generate a target location. Also verified the overmap looked approximately the same as it did originally ("approximately", because I don't have photographic memory).
- Loaded my save, which doesn't use zzip compression, and verified the overmap looked reasonable.
- Loaded my save, debug spawned a modified radio, verified coordinates to the facility were generated anew when it was activated (I've already been there before, but have noted previously that activating the radio again generates the quest again). So this shows it still happens.

### CODE REVIEW

**Comment by akrieger** [comment]
This looks about how I expected the fix to look. I'll try to detail review later but if you say it works it doesn't seem like there's anything to debate.

File: src/overmap.h [hunk 1]
```diff
@@ -62,6 +62,9 @@ struct map_data_summary;
 struct region_settings;
 template <typename T> struct enum_traits;
 
+const std::string zzip_overmap_directory = "overmaps";
+const std::string zzip_suffix = ".zzip";
```
Comment (akrieger) [inline src/overmap.h]:
```suggestion
static constexpr std::string_view kZzipOvermapDirectory = "overmaps";
static constexpr std::string_view kZzipSuffix = ".zzip";
```

Comment (akrieger) [reply src/overmap.h]: Although the `.zzip` one could go inside the .cpp file, there's little reason for that to be global especially in `overmap.h`. Maybe in `worldfactory.h` or `path_info.h`.

File: src/worldfactory.h
Comment (akrieger) [inline src/worldfactory.h:11]:
```suggestion
#include <string>
#include <string_view>
```
