### PR TITLE
Partially refactor activity resuming

### LINKED ISSUE #16376: Waiting a short time is superseded by a previously cancelled long wait.
I've noticed this issue in the distant past on multiple occasions, just didn't decide to bring it up till now as you can always just cancel the wait again. I'll give a rundown on how to reproduce it.

To duplicate this bug just choose to wait for an extended period of time using the "|". 
 Cancel the wait using the ".", and then try to wait a shorter time. The initial long wait is resumed instead of the new wait time.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Problem:
`player::assign_activity` has bad format - it assigns the activity first and then modifies the assigned activity. As a result it is not possible to properly resume many activities, as necessary information isn't available at the time the decision (to resume or start anew) needs to be made.

Solution:
Have `player::assign_activity` assign a fully defined activity. Comparing those is much easier

I added `player_activity::can_resume_with` to allow defining activities which shouldn't be resumed or that have different conditions for resuming. Currently only strict no resume and batch size is checked.

Fixes a bug where batch crafting would be resumed regardless of batch size. For example, starting crafting a batch size 20, stopping it and resuming with batch size 1 would count as resuming, potentially causing debugmsgs and failed crafting due to missing components.

Fixes a bug where reopening advanced inventory after interruption would resume moving items around, despite them most likely being different items than the ones originally designated for moving.
Ditto for dropping and stashing.

Fixes #16376

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -14134,34 +14134,34 @@ void game::wait()
 
     switch (as_m.ret) {
     case 1:
-        time = 5000;
+        time = 100 * MINUTES( 5 );
```
Comment (codemime) [inline src/game.cpp]: Since it's `time` (I mean not `moves`), it would be more consistent (and less verbose) to multiply only once:
```c++
player_activity new_act( actType, 100 * time, 0 );
```
Also, if you extract the `switch` into a function, you would save x10 `break`s and get a meaningful name:
```c++
...
case 5:
    return HOURS( 3 );
case 6:
    return HOURS( 6 );
...
```

File: src/player.cpp [hunk 2]
```diff
@@ -12532,17 +12532,21 @@ void player::learn_recipe( const recipe * const rec, bool force )
...
 void player::assign_activity(activity_type type, int moves, int index, int pos, std::string name)
 {
-    if( !backlog.empty() && backlog.front().type == type && backlog.front().index == index &&
-        backlog.front().position == pos && backlog.front().name == name &&
-        !backlog.front().auto_resume) {
-        add_msg_if_player( _("You resume your task."));
+    assign_activity( player_activity( type, moves, index, pos, name ) );
+}
+
+void player::assign_activity( const player_activity &act, bool no_resume )
```
Comment (BevapDin) [inline src/player.cpp]: Might be better to change the parameter to `resume` or `allow_resume` to get rid of the potentially confusing double negation in the check below.

File: src/player_activity.cpp [hunk 3]
```diff
@@ -34,26 +34,27 @@ player_activity::player_activity( activity_type t, int turns, int Index, int pos
...
-        _( " Stop stashing?" ), _( " Stop picking up?" ),
-        _( " Stop moving items?" ), _( " Stop interacting with inventory?" ),
-        _( " Stop fiddling with your clothes?" ), _( " Stop lighting the fire?" ),
-        _( " Stop working the winch?" ), _( " Stop filling the container?" ),
-        _( " Stop hotwiring the vehicle?" ), _( " Stop aiming?" ),
-        _( " Stop using the ATM?" ), _( " Stop trying to start the vehicle?" ),
-        _( " Stop welding?" ), _( " Stop cracking?" ), _( " Stop repairing?" ),
-        _( " Stop modifying gun?" )
+    static const std::array<std::string, NUM_ACTIVITIES> stop_phrase = {{
+            _( " Stop?" ), _( " Stop reloading?" ),
```
Comment (BevapDin) [inline src/player_activity.cpp]: Btw. This looks like one of those whitespace in translation issues. The phrase from here is appended to another string to be displayed in the yes-no query. The code should insert the single space there and not require it to be part of the original phrase.

File: src/player_activity.cpp [hunk 4]
```diff
@@ -473,3 +475,83 @@ void player_activity::finish( player *p )
...
+        case ACT_VEHICLE:
+        case ACT_FIRSTAID:
+        case ACT_VIBE:
+        case ACT_MAKE_ZLAVE:
+        case ACT_GUNMOD_ADD:
+        case ACT_REPAIR_ITEM:
+            // Those should have extra limitations
+            // But for now it's better to allow too much than too little
+            break;
+        default:
```
Comment (BevapDin) [inline src/player_activity.cpp]: The default case prevents the compiler warning about missing enumeration values. Is it really necessary, or can you just add the missing values as additional cases (instead of the default case)?

**Comment by BevapDin** [comment]
I added missing cases in the switch statements to prevent the compiler warnings.

The switches in `player_activity::can_resume_with`, `player_activity::is_suspendable` and `player_activity::is_abortable` should be merged somehow. They depend upon each other a bit: suspendable but not resumable is senseless and there are similar pointless combinations.
