### PR TITLE
Fix debug message when starting location is not available in the world

### LINKED ISSUE #15210: Ambush scenario bug
When you start a new game with the ambush scenario,a debug message  DEBUG:Could not find starting overmap terrain cabin  appears and then you start at the edge of a forest with a few zombies around you.

### PR DESCRIPTION
**Pull request by BevapDin**
If the starting location can not be found and the world does not have any overmaps (new world or world was reset), it shows a Yes/No query to regenerate the initial overmap and than try again to find a location. The query is there so users can stop it after several unsuccessful retries (which will bring the user back to the main screen).

~~Or, if the world has already some overmap, it shows a popup with a message about the problem and brings the user back to the main screen.~~

Fixes #15210

Edit: changed it always generate a new (non-existing) overmap, regardless of existing overmap.

---

Taking the user back to character generation is ... possible, but the way the main menu is created and used makes this difficult and a hack at best. It requires at least a bit refactoring of that code.

### CODE REVIEW

**Comment by Zireael07** [comment]
We're now iterating through ALL overmaps? As of 49e7f74?

That's HUGE!

**Comment by Malkeus** [comment]
Will this drastically slow down starting new survivors on heavily explored worlds? And does it start with the original spawn overmap and iterate outwards from there? I'll try to answer my 2nd question on my own, but I often don't have a lot of luck following the more cerebral coding.

**Comment by BevapDin** [comment]
> We're now iterating through ALL overmaps?

It actually only tests the 32*32*4 overmaps around (0,0), so theoretically not *all*, but practically.

> Will this drastically slow down starting new survivors on heavily explored worlds?

Depends on where it can find the start location. If it has to search all available overmaps, it will take some time I assume. I haven't tested it with many overmaps, only with few, and that didn't seem to take much more time.

> And does it start with the original spawn overmap and iterate outwards from there?

Yes. It uses `closest_points_first` around the (0,0) overmap.

**Comment by Malkeus** [comment]
Thanks BevapDin, this sounds like it will be a great addition. How much more difficult would it be to have the game generate a new overmap on the edge of existing ones and regen it over and over until it gets what it's looking for, similar to your new world/new survivor method?

**Comment by BevapDin** [comment]
> How much more difficult would it be to have the game generate a new overmap on the edge of existing ones and regen it over and over until it gets what it's looking for, similar to your new world/new survivor method?

I changed it accordingly. It's actually a bit simpler now.

**Comment by Malkeus** [comment]
Very cool, no more easy starts for mall cops!

**Comment by Nymall** [comment]
I'm looking forward to actually being able to play an "assult on precinct z" character start, or the firefighter one. I've never been able to get either of those to work.

**Comment by BevapDin** [comment]
> I'm looking forward to actually being able to play an "assult on precinct z" character start, or the firefighter one. I've never been able to get either of those to work.

Well, the PR doesn't make them work, it only prevents the player from continuing with a broken start, and allows them to try again. If your world options make the required terrain so unlikely that it never actually spawns, you still wont be able to use it.

**Comment by Malkeus** [comment]
"Patiently" resting a book on the 'y' key and then leaving for work.... :P

**Comment by Coolthulhu** [comment]
Something doesn't work correctly. First test, with impossible to achieve settings worked correctly, but a second one dumped my character in a wrong place.

First test was 16 city size 0 distance and sheltered start. Second one was 10 city size 2 distance and also sheltered. The second test was started in the same instance of the game, after answering "no" to "do you want to regen world" prompt (after multiple "yes"es).

File: src/start_location.cpp [hunk 1]
```diff
@@ -191,27 +191,56 @@ void start_location::prepare_map( tinymap &m ) const
...
+            }
+        }
+    }
+
+    while( true ) {
+        popup_nowait( _( "Please wait as we build your world" ) );
+        const overmap &initial_overmap = overmap_buffer.get( non_existing_omt.x, non_existing_omt.y );
+        const tripoint omtstart = initial_overmap.find_random_omt( target() );
+        if( omtstart != overmap::invalid_tripoint ) {
+            return omtstart + point( non_existing_omt.x * OMAPX, non_existing_omt.y + OMAPY );
```
Comment (Coolthulhu) [inline src/start_location.cpp]: There it is - a typo. `non_existing_omt.y + OMAPY` -> `non_existing_omt.y * OMAPY`
