### PR TITLE
Fix some furn/terrain related issues

### LINKED ISSUE #32260: Roof tiles not falling down
# Describe the bug

When burning down a building, some tiles above it are kept there. **_This is unrealistic._**

# Steps To Reproduce

1. Burn down a building

# Expected behavior

Whenever a building is burned down, all the tiles above it should fall down as well.

# Screenshots

# Additional context

**_We need realism to be applied to all roofs so they don't defy gravity!_**

### LINKED ISSUE #34662: Down Mattress Errors
# Describe the bug
When scrolling over the entry for down mattress in the crafting menu, it is written as "down_mattress" and gives this error when selected.

 DEBUG    : invalid furniture id "f_feather_mattress"

 FUNCTION : const T& generic_factory<T>::obj(const string_id<T>&) const [with T = furn_t]
 FILE     : src/generic_factory.h
 LINE     : 356

# Steps To Reproduce

Scroll over the down mattress entry.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8418-g126c27b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    [DP_MOD] Hide DEBUG [DP_No_Debug_Tile],
    No Fungal Monsters [No_Fungi],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by free-coffee**
#### Summary

`SUMMARY: None`
#### Purpose of change

Fixes #32260 :  Collapsing of terrains doesn't effect other z-levels, leading to flying roofs.
Fixes #34662 :  Scrolling to the 'down_mattress' recipe throws an 'invalid furniture id "f_feather_mattress" ' error.
#33374 provisional fix :  The Terrains Reinforced (with shutters), Ballistic & Laminated glass can be shot through without affecting it. To implement pierce-deterioration for terrains is proposed and not addressed here, which is why this is only provisional.

#### Describe the solution

- Expanding the collapse_at function to affect a z-radius of one with special-handling the other z-levels.
- Correcting the typo/missed-update json entry.
- Handling the glass walls like normal reinforced glass with laminated being an exception. Laminated is handled like normal glass but has only a one-in 40 chance of breaking on being shot through.

#### Testing

Tried to shoot through the glass.

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -2933,18 +2933,21 @@ void map::collapse_at( const tripoint &p, const bool silent )
...
-    for( const tripoint &t : points_in_radius( p, 1 ) ) {
-        if( p == t ) {
+    for( const tripoint &t : points_in_radius( p, 1, 1 ) ) {
+        if( p == t || ( t.z < p.z && has_flag( "SUPPORTS_ROOF", p ) ) ) {
             continue;
         }
         if( has_flag( "COLLAPSES", t ) && one_in( collapse_check( t ) ) ) {
             destroy( t, silent );
             // We only check for rubble spread if it doesn't already collapse to prevent double crushing
+        } else if( t.z > p.z && has_flag("FLAT", t) ) {
```
Comment (ZhilkinSerg) [inline src/map.cpp]:
```suggestion
        } else if( t.z > p.z && has_flag( "FLAT", t ) ) {
```

File: src/map.cpp [hunk 2]
```diff
@@ -2933,18 +2933,21 @@ void map::collapse_at( const tripoint &p, const bool silent )
...
+            destroy( t );
         } else if( has_flag( "FLAT", t ) && one_in( 8 ) ) {
             crush( t );
             make_rubble( t );
         }
     }
+
```
Comment (ZhilkinSerg) [inline src/map.cpp]:
```suggestion
```
