### PR TITLE
Fix 'vehicle runs over something' spam

### LINKED ISSUE #31836: <vehicle's tires> runs over something spam
# Describe the bug

Every time I move my cart via (G)rab I get 'The Storage Cart's 4" casters runs over something.'

Also get similar spam (per tire) from the Armored Car I found, ie:
'The Armored Car's 32" armored wheel runs over something.'

# Steps To Reproduce

1. Spawn a dragable vehicle
2. Move the dragable vehicle around.

NOTE: Steps were generated using [New Game] [Play Now! (Fixed Scenario)].
(Technically can also test with a vehicle that you can drive but a dragable vehicle is something you can do on the first turn.)

# Expected behavior

NOT getting said message spam when moving a vehicle, except perhaps if rolling over an actual trap.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on Windows 7
- Game Version: 0.D-4963-g3eec9d8 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Disable NPC Needs [no_npc_food],
    Simplified Nutrition [novitamins]
]

# Additional context

Encountered this after updating from build 9208 to 9219.

As a test I remarked out the following section and recompiled, no more message spam.  Though I suspect that isn't the proper fix for this.

https://github.com/CleverRaven/Cataclysm-DDA/blob/3eec9d8b2a4f50ee5323d1941f9f1ea7a0007d38/src/vehicle_move.cpp#L813-L820

### PR DESCRIPTION
**Pull request by OrenAudeles**
#### Summary
```SUMMARY: Bugfixes "Fix 'vehicle runs over something' spam"```

#### Purpose of change
Fixes #31836 - Vehicle tires runs over something message log spam.
Bug introduced in #31734 

#### Describe the solution
If there is no trap then `trap_id t` will be `tr_null`. We can test for this and exit early.

### CODE REVIEW

File: src/vehicle_move.cpp [hunk 1]
```diff
@@ -804,6 +804,10 @@ void vehicle::handle_trap( const tripoint &p, int part )
     const trap &tr = g->m.tr_at( p );
     const trap_id t = tr.loadid;
 
+    if( t == tr_null ) {
```
Comment (Night-Pryanik) [inline src/vehicle_move.cpp]: Technically speaking, there IS a trap with `tr_null` id. It doesn't do anything, but it exists. To be sure in non-existence of any traps you can use `tr.is_null()` check.

Comment (OrenAudeles) [reply src/vehicle_move.cpp]: `tr.is_null()` is `return loadid == tr_null;` so there is no difference in functionality between `t == tr_null` and calling `tr.is_null()`

Comment (Night-Pryanik) [reply src/vehicle_move.cpp]: Ok, got it.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/insert-tire-here-runs-over-something-xevery-wheel/20556/4
