### PR TITLE
Zombie slave fixes

### LINKED ISSUE #11100: Hallucinations kill zombie slaves
0.B-2687-289e460 Curses 
Windows 7 x86
After making a zombie slave out of feral hunter, I noticed that sometimes it would die for no apparent reason while tied up in another room. Turns out that when the character is hallucinating, appearing hallucinations of monsters can and will attack zombie slaves, causing damage.
The logs from one of these events read:
```
"The charred nightmare hits the feral hunter!"
"The feral hunter dies!"
"You block none of the damage with your !"
"The charred nightmare hits your left arm."
"You whack the charred nightmare for 21 damage. Critical!"
"The charred nightmare disappears."
```
I'm not sure if this occurs with unrestrained slaves as well, but it definetly happens if they are tied up.
Also, note the odd message about blocking damage. I was unarmed at the time. 
Finally, a question. When a tied up zombie slave dies, the rope that was restraining it disappears. Was it supposed to work this way or is it a bug?

### PR DESCRIPTION
**Pull request by ValidAQ**
This resolves #11100. 
- Change `monster::hit_monster` to only inflict damage if attacker is not a hallucination
- Make creatures with `tied` effect drop a short rope on death

### CODE REVIEW

File: src/monster.cpp [hunk 1]
```diff
@@ -1289,6 +1291,12 @@ void monster::die(Creature* nkiller) {
                                   name().c_str() );
         }
     }
+    // We were tied up at the moment of death, add a short rope to inventory
+    if ( has_effect("tied") ) {
```
Comment (KA101) [inline src/monster.cpp]: I want to say this should itself have a hallucination check, but realistically you can't have a tied-up hallucination.  So yeah, leave it as is.
