### PR TITLE
IR Vision can see through smoke

### LINKED ISSUE #54253: Infrared vision cannot see through smoke/gas
### Describe the bug

Infrared vision is unable to see through smoke or gas, one of the few situations where i'd have expected it to give you an advantage.

### Steps to reproduce

1. Use infrared goggles or infrared vision mutation on a survivor (tested using the mutation).
2. Throw down smoke, gas or similar.
3. Attempt to see a valid creature through it.

### Expected behavior

I would expect infrared vision to provide you with some visibility through smoke, toxic gas or similar gas clouds.

### Screenshots

unknown 1
unknown 1
unknown 1
In the above images, I am standing in smoke with a valid infrared vision target next to me.
If I move away one tile, it is no longer visible.
As proof infrared vision is working (albeit in another slightly buggy way?), moving closer so I can see it but activating optical dampeners to blind myself shows the target.

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 1793043 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Mythical Martial Arts [MMA],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### LINKED ISSUE #66948: IR doesn't see through smoke
### Describe the bug

Infrared vision should be able to see through smoke as it does IRL but it does not in game.

### Attach save file

n/a

### Steps to reproduce

1. Spawn IR goggles and wear them and turn them on.
2. Spawn smoker zombies.
3. Observe being unable to detect the smokers through IR.

### Expected behavior

IR should show up through smoke clouds.

### Screenshots
image

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 944de85 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Slots [cbm_slots],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by worm-girl**
#### Summary
Bugfixes "Allows Infrared vision to see through smoke"

#### Purpose of change

Fixes #54253 
Fixes #66948 
and probably others.

Infrared vision was using a simple calculation to determine line of sight. Because this was drawing on the same transparency cache that normal vision used, and because the map cache for performance reasons can't be drawn multiple times a second just for rare cases like IR, there wasn't a good way to make smoke block normal but not IR vision, because under our current model, both are active at the same time. This also caused some weirdness where having IR vision up slightly changed the way transparency behaved in some edge cases, but not in a way that was helpful or made any real sense.

This was a fairly major problem because the primary use case for infrared was seeing through fields. It wasn't particularly useful as a mode of darkvision because night vision is pretty forgiving in this game, and anyone with access to IR is either working with mutations or very powerful technology, both of which suggest that darkness is not a huge barrier.

#### Describe the solution

Stops using pl_line_of_sight for IR vision. This function worked well enough normally, but was not able to deal with smoke's translucency code. Instead, we touch up map::sees to accept new conditions which can be run without drawing a new map cache. The result is that IR vision can see through smoke, but normal vision cannot.

#### Describe alternatives you've considered

This method does not fix every possible use case. It's a step in the right direction but more could be done. Namely, it doesn't allow the use of remote IR cameras, which we don't have, but would be nice.

Some smoke, such as the higher-end smoke grenades now used by the military, contains particles which are intended to baffle IR vision. 99% of the smoke the player encounters is either coming from a zombie which probably isn't using such a sophisticated method, or it's coming from a fire. Regular fire smoke, while hot, does not impede IR vision this way - IR cameras are used by firefighters, for example. We also had several fields like poison gas and fog which were impeding IR even though they would be even less likely to do so. If we want IR-baffling smoke, it probably wouldn't be too hard to add a new field which acts like smoke but is flagged to block IR somehow.

I have left the pl_line_of_sight() function intact for now because it's still used for the echolocation in #70797 - once that PR is merged, I will move it over to this method and remove the obsolete function.

#### Testing

- Spawned a character, gave them the IR vision mutation.
- Spawned Ashen Brawlers and some regular zombies to hang out with them. I was able to see their heat signatures through the smoke, but the smoke still obscured tiles otherwise.
- There was no noticeable performance dip, nor was one expected as we're not rebuilding the map cache.
- Hid behind a wall. Could not see through the wall. IR can see through thin stuff IRL but its previous behavior was that all wall tiles would block it and that's still the case.
- Hid in a roomy shell. Could not see through the shell. 👍 

#### Additional context

image

I can't take any credit for this fix as @andrei8l put it together for me. Thanks choom!

### CODE REVIEW

File: src/lightmap.cpp [hunk 1]
```diff
@@ -803,25 +803,25 @@ bool map::pl_sees( const tripoint &t, const int max_range ) const
...
+//    }
+
+//    if( max_range >= 0 && square_dist( t, get_player_character().pos() ) > max_range ) {
+//        // Out of range!
+//        return false;
+//    }
+
+//    // Any epsilon > 0 is fine - it means lightmap processing visited the point
+//    return map_cache.seen_cache[t.x][t.y] > 0.0f;
+//}
```
Comment (Kamayana) [inline src/lightmap.cpp:825]: Unless you think it's worth keeping, this means `pl_line_of_sight` could be done away with entirely, rather than just commented out.
```suggestion
```
And if it's deleted, so should the corresponding header definition:
https://github.com/CleverRaven/Cataclysm-DDA/blob/20c59f6d19498477ff8a54d1b581307e7182f88b/src/map.h#L1830C9-L1836C48

**Review by Kamayana — CHANGES_REQUESTED** [review]

File: src/lightmap.cpp (hunk 1 above)
Comment (fairyarmadillo) [reply src/lightmap.cpp:825]: The new echolocation in #70797 uses this dead code, but I intend to switch it to the method in this PR. This is probably going to get merged first, so I guess I can just remove it and update echolocation accordingly later.

**Comment by Maleclypse** [comment]
Hmm some vision checks failing in the required tests when I went to look and see if it was an rng fail that needed kicking.

**Comment by fairyarmadillo** [comment]
> Hmm some vision checks failing in the required tests when I went to look and see if it was an rng fail that needed kicking.

I believe that's new since I removed the old function. The tests are probably trying to call a nonexistent function, I'll try to sort it out.

**Comment by fairyarmadillo** [comment]
That did it. The only failed test now has to do with mapgen, which this doesn't touch.

**Comment by RadioAndrea** [comment]
Hello,

I attempted to use infrared goggles in experimental-2024-02-18-2056 and I could not get them to work.

In order to debug the issue I used debug mutations to add infrared vision to the player, I also attempted to add lizard eyes + lizard IR. Neither of these work.

When using infrared goggles, the player vision is reduced to one square, no matter if goggles are on or off.

when using mutations, no heat-bearing monsters are shown (in this instance I tested on a turkey).

Possibly a regression?

**Comment by fairyarmadillo** [comment]
> Hello,
> 
> I attempted to use infrared goggles in experimental-2024-02-18-2056 and I could not get them to work.
> 
> In order to debug the issue I used debug mutations to add infrared vision to the player, I also attempted to add lizard eyes + lizard IR. Neither of these work.
> 
> When using infrared goggles, the player vision is reduced to one square, no matter if goggles are on or off.
> 
> when using mutations, no heat-bearing monsters are shown (in this instance I tested on a turkey).
> 
> Possibly a regression?

image

image

- OS: Windows
    - OS Version: 10.0.19045.3930 (22H2)
- Game Version: 2138374 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

Tested and working both with goggles and the mutation in today's experimental #0459. Try updating?

**Comment by RadioAndrea** [comment]
OS: Linux x64 - Fedora 39
Game Version: prebuilt experimental 2024-02-19-0059
    Graphics Version: Tiles, Cuteclysm
    Game Language: System language 
    Mods loaded: None
    
I grabbed the new latest since I posted to test, new world, new character, spawned in IR's and no joy.
    
If it's just me seeing this, I'll open a separate ticket since it might be a linux thing.
    
This is wearing thermals with a battery installed and turned on. Move one space up and we can see there was a person there the whole time!
    
    
Screenshot from 2024-02-18 22-14-02
Screenshot from 2024-02-18 22-13-58

**Comment by RadioAndrea** [comment]
Addendum: ignore my ramblings, it's a tileset issue, will report to them, cheers
