### PR TITLE
Fix monster z vision

### LINKED ISSUE #37945: Preoccupied enemies
Occasionally a zombie, or a group of zombies, will idle in a location for no obvious reason and ignore the player. This behaviour suggests that they're targeting enemies nearby, however in most situations I've been unable to identify any... unless they were on a different Z level. This has occurred with zombies targeting sewer snakes or rats in basements to zombies crowding beneath a floating wasps nests in the steel mill. There were no giant wasps in sight, but map editor revealed them all to be chilling at Z10, unconcerned with us ground crawlers.

# Steps To Reproduce

Basically wander about in a city until you see zombies that know you're there but just don't care.

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12105-gda56791 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct]
]

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: Bugfixes "Prevent monsters from seeing each other across z-levels."

#### Purpose of change
Fixes #37945 
Monsters would fixate on a faction enemy on a different level that they should not be able to detect.
The underlying cause was that creature::sees() would use different logic for adjacent enemies than for distant enemies, and this logic did not respect intervening floors or ceilings.
A related issue is that map::sees() would ignore a floor or ceiling that would block the final tile of a vision ray, making some tiles just below the surface to be visible from above the surface.

#### Describe the solution
Use map::sees() to check for visibility of vertically adjacent creatures in creature::sees( creature ).
Avoid the "opaque tiles are visible" behaviour in map::sees() when transitioning between levels. 

#### Testing
The new test outlines the primary failure modes.
Can reproduce in game by spawning a zombie directly above or below a turret, the zombie would previously stay within one tile and above or below the turret attempting but failing to attack it, but now it will wander freely.

### CODE REVIEW

**Comment by AMurkin** [comment]
Tests are failing. But I hope it will fix #36412 and #34506 in the end.

File: tests/monster_vision.cpp [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+    // No floor between monsters
+    CHECK( upper.sees( sky ) );
+    CHECK( sky.sees( upper ) );
+    // Adjacent monsters.
+    CHECK( upper.sees( adjacent ) );
+    CHECK( adjacent.sees( upper ) );
+    // distant monsters.
+    CHECK( upper.sees( distant ) );
+    CHECK( distant.sees( upper ) );
+}
```
Comment (umamaistempo) [inline tests/monster_vision.cpp]: Hypothetically speaking, do you think it would be a good idea to also check that `lower` (or `deep`) also do not see `adjacent` nor `distant` to cover a possible bug where a light operation might not consider the floor on diagonal angles ?

Yes, it's redundant because of the check on `creature.cpp` requires both to be on the same Z-level, but with progress on Experimental Z levels I could see this in the future being changed to depend only on vision (not used to the codebase, so mostly guess work here) 🤔

Comment (kevingranade) [reply tests/monster_vision.cpp]: Yea, I have it open right now because of a config bug that was making it fail (idk, fields maybe?), so I'll add some cross checking.

Comment (kevingranade) [reply tests/monster_vision.cpp]: Well crap, now one more test is failing :/

Comment (kevingranade) [reply tests/monster_vision.cpp]: Thanks for poking me to check this, as a result I uncovered and fixed a *6 year old bug* in the foundational line drawing code.  There are probably dozens of latent bugs that this fixed.

**Comment by kevingranade** [comment]
This is ready for merge, the test failures are unrelated to this PR.
