### PR TITLE
Check for possible to wield completed craft

### LINKED ISSUE #29928: Interrupted and moved intermediate crafting results vanishes after completion
**To Reproduce**  
1. Start crafting a forge.
2. Interrupt it.
3. Pick the in-progress item.
4. Move 20 tiles away from the place your crafted it at.
5. Resume crafting till completion.
6. Observe it completed and completely vanished.

**Versions and configuration(please complete the following information):**
0.D-2215-g6b8c6f2a60-dirty

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Check for possible to wield completed craft"```

#### Purpose of change
Fixes #29928 

#### Describe the solution
The completed craft did not check if it was possible to wield the resulting item, it attempted to do so, failed then didnt actually put the item anywhere.
Ive added a check, and if wielding fails due to wearing an item that restricts hands , or not having eonugh hands ( if the item requires two hands ) , and then drops it on the floor instead of just disappearing it.

#### Describe alternatives you've considered
N/A
#### Testing
linked issue was not really about moving away from the vehicle, but the presence of vehicle cargo spots may have hidden the issue.
tested this was the cause by removing swag bag, item completed fine.
after the fix, while wearing swag bag, crafting a forge ( which requires two hands ) was them dumped on the floor.
#### Additional context
N/A

### CODE REVIEW

File: src/crafting.cpp [hunk 1]
```diff
@@ -1212,7 +1212,11 @@ void player::complete_craft( item &craft, const tripoint &loc )
         if( newit.made_of( LIQUID ) ) {
             liquid_handler::handle_all_liquid( newit, PICKUP_RANGE );
         } else if( loc == tripoint_zero ) {
-            wield_craft( *this, newit );
+            if( newit.is_two_handed( *this ) && ( !has_two_arms() || worn_with_flag( "RESTRICT_HANDS" ) ) ) {
```
Comment (ifreund) [inline src/crafting.cpp]: First of all, you rock for fixing this.

One minor code style thing though, this check could be merged into the `else if` just above.  That way you avoid the duplicate calls to `set_item_map_or_vehicle()`

**Comment by Ramza13** [comment]
So I can look up details later but I believe you want to be using the can_wield function rather than just checking for two handed flag as there are other cases where you can't wield something such as if you have a broken arm.

**Comment by davidpwbrown** [comment]
> So I can look up details later but I believe you want to be using the can_wield function rather than just checking for two handed flag as there are other cases where you can't wield something.

yeah can_wield() just encapsulates the same checks, ill use that, its neater.
