### PR TITLE
Fix issue with auto_aim

### LINKED ISSUE #38285: Auto-target does not auto-target through display racks
# Describe the bug

As title, also noticed that it doesn't auto-target through unbroken windows

# Steps To Reproduce

1. Display rack between you and enemy
2. Display rack blocks auto-target, but you can still aim at enemy and shoot at enemy like normal

# Expected behavior

Auto target through display rack

# Versions and configuration
- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12476-gfef327b [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi],
    Disable Religious Texts [no_religious_Texts]
]

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix problems with auto aim"

#### Purpose of change
Fixes #38285
Fixes auto aim for ranged weapons not targeting through glass, chain link fences, etc while preventing melee attacks trying to attack through things they can't go through.

#### Describe the solution
Added param to differentiate between ranged and melee auto attacks, reverted ranged behavior and modified reach attacks to only target things they could hit

#### Testing
Auto targeted through fence with gun, couldn't do so through glass with melee.

### CODE REVIEW

File: src/ranged.cpp [hunk 1]
```diff
@@ -2384,7 +2384,7 @@ void target_ui::update_target_list( player &pc )
     // Get targets in range and sort them by distance (targets[0] is the closest)
     // FIXME: get_targetable_creatures does not consider some of the visible creatures
     //        as targets (e.g. those behind fences), but you can still see and shoot them
-    targets = pc.get_targetable_creatures( range );
+    targets = pc.get_targetable_creatures( range, false );
```
Comment (olanti-p) [inline src/ranged.cpp:2387]: This `false` should be `mode == TargetMode::Reach`. Otherwise pressing `TAB` while selecting a target for melee attack would consider the ones behind glass as valid.

File: src/character.cpp [hunk 2]
```diff
@@ -10447,15 +10447,22 @@ std::vector<Creature *> Character::get_visible_creatures( const int range ) cons
...
 }
 
-std::vector<Creature *> Character::get_targetable_creatures( const int range ) const
-{
-    return g->get_creatures_if( [this, range]( const Creature & critter ) -> bool {
-        bool can_see = sees( critter ) || sees_with_infrared( critter );
-        if( can_see )   //handles the case where we can see something with glass in the way or a mutation lets us see through walls
+std::vector<Creature *> Character::get_targetable_creatures( const int range, bool melee ) const
+{
+    std::vector<ter_id> glass = { t_door_glass_c, t_door_glass_o, t_door_glass_frosted_c, t_door_glass_frosted_o, t_wall_glass, t_wall_glass_alarm,
```
Comment (ZhilkinSerg) [inline src/character.cpp:10452]: We should jsonize it through terrain flag probably later.

Comment (Ramza13) [reply src/character.cpp:10452]: Yea either later tonight or tomorrow I'll take a stab at that.
