### PR TITLE
Fix some crashes and item disappearance

### LINKED ISSUE #41635: Crash when wielding item from inside container that is currently wielded
# Describe the bug

Game crashes.

# Steps To Reproduce

Have a container.
Put item inside container.
Wield the container.
Try to wield the item from inside of the container.
Game asks what to do with the previous wielded item. Doesn't matter what you choose.
Game crashes.

# Expected behavior

Game does not crash.

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-3553-ge888413 [64-bit]
- Graphics Version: Tiles
- Game Language: Deutsch [de]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Dark Days of the Dead [classic_zombies],
    No Monsters [Only_Wildlife]
]

# Additional context

Save: 
[TEST.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4840592/TEST.zip)

Try to wield any item (grenade/lighter/bandage) from within the jeans that the character is holding.

Call stack:

```
>	Cataclysm-vcpkg-static-Release-x64.exe!item_contents::contained_where(const item & contained) Line 447	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!handle_contents_changed(const item_location & acted_item) Line 2007	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!game::inventory_item_menu(item_location locThisItem, const std::function<int __cdecl(void)> & iStartX, const std::function<int __cdecl(void)> & iWidth, game::inventory_item_menu_positon position) Line 2296	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!game_menus::inv::common(avatar & you) Line 231	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!game::handle_action() Line 1979	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!game::do_turn() Line 1475	C++
 	Cataclysm-vcpkg-static-Release-x64.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 697	C++
```

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
SUMMARY: Bugfixes "Fix some crashes and item disappearance"

#### Purpose of change
See commit messages. Fixes #41635.

#### Describe the solution
1. Check that charge count is non-zero before adding the item and dividing values with charge count. Show debug message if charge count is zero.
2. Remove the static specifier of a vector of items, since item types are stored as pointers which will be invalidated when unloading saves.
3. Remove the first `i_add` call in `pick_one_up`. This call, originally an `i_add_to_container` call, was introduced in #21646 to add ammo to quivers automatically, and since `i_add` now also has this functionality, the latter `i_add` call in the switch statement is already sufficient. Furthermore, the code now checks if the result from `i_add` is null or points to the original item, restore the original charge count if the latter is the case, and only remove the original item if the result is not null and points to a different item instead, so the amount if item stays the same under all circumstances.
4. Remove the first `i_add_to_container` call and check for `i_add` results in `player::add_or_drop_with_msg` for the same reason as 3. Additionally, add an `allow_drop` parameter to `i_add`, so I can special-case item dropping in `player::add_or_drop_with_msg` to show the correct message, and disallow dropping items again when picking up items. Finally, skip the wielded item in `Character::best_pocket` if the wielded item is to be avoided, so unloading items from wielded item behaves correctly.
5. Add a `allow_wield` parameter to `i_add`, and use it to disallow wielding items in `player::add_or_drop_with_msg` if the item to be added is inside the currently wielded item.
6. Check directly whether the item to wield is contained in the currently wielded item.

#### Testing
1. Can't reproduce the crash for a second time, but NPC trading was working as before, and the change seems reasonable to me.
2. Loaded a save, quitted using debug menu, and loaded a second time, and the game did not show `std::bad_alloc` error or crash.
3. Tested picking up some tained bones when the inventory and hands are full, and canceling the subsequent query to wield the item, and the item was still on the ground and did not disappear.
4. Unloaded a quiver filled with arrows when inventory is full or not full, and the arrows were either dropped on the ground or added to inventory instead of disappearing.
5. Unloaded a quiver filled with arrows an the player is now not prompted to handle the quiver. Instead the arrows are dropped on the ground if the inventory is full.
6. Tried to wield an item from a wielded container, and the appropriate message was shown instead of crashing.

#### Additional context
There really should be some centralized system for moving items between aribitrary places...

### CODE REVIEW

File: src/npctrade.cpp [hunk 1]
```diff
@@ -163,6 +163,10 @@ std::vector<item_pricing> npc_trading::init_buying( player &buyer, player &selle
             return;
         }
 
+        if( it.count() <= 0 ) {
```
Comment (BevapDin) [inline src/npctrade.cpp:166]: This appears like it's hiding a bug. If `item::count` returns 0, that means it's an item counted by charges, but with 0 charges. For example "water (0)", which makes no sense. There should not be such an item.

I suggest you add some debug message about this inconsistent state.
