### PR TITLE
Use 64 bit int to read 64 bit int values

### LINKED ISSUE #83461: Bionic power levels set to 0 on loading
### Describe the bug

Sometimes when loading up a game, the player's bionic power levels will be set to zero. 

The game seems to be properly writing the player's bionic power level to file, as opening up the character save file and looking at `power_level` shows the appropriate value being written after being saved. 

The issue seems to come up when loading the save and, specifically, when the power level is expressed in terms of mJ and thus can be a much larger value than what you'd see expressed in kJ or J.

### Attach save file

[Test World-trimmed.tar.gz](https://github.com/user-attachments/files/23111606/Test.World-trimmed.tar.gz)

### Steps to reproduce

1.) Open up the provided character save and note that `power_level` is saved as "8000 kJ"
2.) Load save.
3.) Activate internal climate control CBM.
4.) Take a step.
5.) Save game.
6.) Note in the character save that `power_level` is saved as "7999806250 mJ" or somewhere thereabouts.
7.) Load save.
8.) Note your bionic power level is now zero.

### Expected behavior

Bionic power levels not being zero upon loading game.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.6456 (22H2)
- Game Version: cdda-experimental-2025-10-23-1650 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

Hypothesis: integer overflow?

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
Fix #83461, i.e. bugged reading of int64 values when integer part larger than int.

#### Describe the solution
Use int64_t instead of int when parsing int64_t values.

#### Describe alternatives you've considered

Replace the stupid "correction" code in savegame_json.cpp that hides the error by setting the power to 0, and instead issue an error report to indicate something is wrong. Obviously not an alternative, but rather a complement.
It can be noted that there are other cases of this kind of "corrections" in the JSON parsing code.

#### Testing
Loaded the save that previously produced a 0 bionic power value and saw that it now shows the truncated value of the saved value (truncated due to UI size limitations).

#### Additional context
A high level language would have thrown an exception when multiplying an int beyond its limits, rather than blitherly producing a garbage value that then is set to 0 in savegame_json.cpp without any thoughts to indicate the value is wrong.

### CODE REVIEW

File: src/units.h [hunk 1]
```diff
@@ -9,6 +9,7 @@
 #include <limits>
 #include <map>
 #include <sstream>
+#include <stdint.h>
```
Comment (ehughsbaird) [inline src/units.h]: C++ style headers, please.
```suggestion
#include <cstdint>
```

File: src/units.h [hunk 2]
```diff
@@ -1348,7 +1349,7 @@ T read_from_json_string_common( const std::string_view s,
             // above always throws but lambdas cannot be marked [[noreturn]]
             throw std::string( "Exceptionally impossible" );
         }
-        int value = 0;
```
Comment (ehughsbaird) [inline src/units.h:1351]: This could use `T::value_type` - it shouldn't matter behavior-wise though, `get_unit()` will correctly do float conversion.

**Review by ehughsbaird — APPROVED** [review]
Good fix.

File: src/units.h (hunk 1 above)
Comment (PatrikLundell) [reply src/units.h]: IMYU should have demanded that instead, then, as I just inserted what it demanded, although it looked odd with a .h among a bunch of suffixless entries.

Anyway, I'm changing it, leaving changing IMYU to whoever is suitable to update that.

Comment (ehughsbaird) [reply src/units.h]: Yeah, it's a known issue with iwyu requesting the C-style headers.

File: src/units.h (hunk 2 above)
Comment (PatrikLundell) [reply src/units.h:1351]: My compiler was rather unhappy with that change. Also note that the code doesn't support a floating point, just an integer value (potentially large) and a unit string, so the largest integer type you intend to support seems reasonable.

**Comment by Light-Wave** [comment]
Could be worth considering this section of the docs if you haven't already
https://github.com/CleverRaven/Cataclysm-DDA/blob/b20e93321aec9bfde434f90d7d0084008938e1fc/doc/c%2B%2B/CODE_STYLE.md?plain=1#L49-L58

**Comment by PatrikLundell** [comment]
@Light-Wave: I fail to see how that documentation is relevant here. This is one of those cases where you need something larger than int, even if you supposedly don't. It can also be noted that size_t needs to be used when dealing with C++ container classes, despite what that documentation says.

Now, it is, of course, problematic to use types that aren't of a defined size/resolution on all potential platforms. Rather than int, you really should use an int32_t (I don't know if one is defined), and similarly, you should use well defined floating point types as well, rather than whatever different compilers happen to select. It's made worse by C(++) silently doing various stupid things when you blow through type limits, rather than throwing exceptions, but that's what you get when using high level assembly rather than high level languages for things that don't require maximum execution speed at the price of no protection against malicious or stupid usage. It's one thing of writing a driver of a few kB, and another to write multi million line systems, in particular when the people involved are of varying skill levels.
