### PR TITLE
Fix crafting with liquids in furniture

### LINKED ISSUE #19483: Unable to craft using water from wooden keg
Idk if this always worked like that, but here we go:

I have made my first Wooden Keg. Filled it with plenty of water (70). My hopes was that it would use water from the keg automaticaly when I order a recipe that requires water, like clean water, for example.

What is currently happening is that when I make the recipe, it asks for the water (me or nearby). If I choose the water from nearby, the time passes, it says it can't train my cooking more, uses no water from the keg, neither produces the clean water I asked for.

Currently I'm pouring water somewhere else first, then I make my recipes.

Sorry if this is duplicated from some other related bug.

### PR DESCRIPTION
**Pull request by lucasmr**
Fixes #19483. This implements a more generic function use_charges_from_furn, enabling crafting with any kind of liquid and any furniture that has the "LIQUIDCONT" flag. Also added this flag on toilets.

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -4932,36 +4932,30 @@ long remove_charges_in_list(const itype *type, map_stack stack, long quantity)
...
-                items.erase( water );
+    if( m->has_flag( "LIQUIDCONT", p ) ) {
+        auto item_list = m->i_at( p );
+        auto current_item = item_list.begin();
+        for( ; current_item != item_list.end(); ++current_item ) {
+            // looking for a liquid that matches
+            if( current_item->made_of( LIQUID ) && type == current_item->typeId() ) {
+                ret.push_back( *current_item );
+                if( current_item->charges - quantity > 0 ) {
+                    // Update the returned water amount to match the requested amount
```
Comment (Night-Pryanik) [inline src/map.cpp]: Update comments to mention any liquid and not only water.

File: data/json/furniture.json [hunk 2]
```diff
@@ -262,7 +262,7 @@
         "description": "Emergency water source, from the tank, and provider of relief.",
         "move_cost_mod": 2,
         "required_str": -1,
-        "flags": ["TRANSPARENT", "FLAMMABLE_HARD", "MOUNTABLE"],
+        "flags": ["TRANSPARENT", "FLAMMABLE_HARD", "MOUNTABLE", "LIQUIDCONT"],
```
Comment (ZhilkinSerg) [inline data/json/furniture.json]: Why not `LIQUID_CONTAINER`?

Comment (lucasmr) [reply data/json/furniture.json]: There was already a LIQUIDCONT flag, so no need to create another.
