### PR TITLE
fixed lockpicking prof exploit

### LINKED ISSUE #47168: lockpicking proficiency increase even after stopping action using ( . ) key
lockpicking proficiency increase even after stopping action using ( . ) key
its too easy to increase lockpicking this way

# Steps To Reproduce
1. get some lockpicking tool
2. find a locked door
3. start lockpicking door
4. stop ( using . key ) before you finish lockpicking
5. lockpicking proficiency increased even though it shouldn't

# Expected behavior
lockpicking proficiency should not increased if we stop ( . ) before finishing

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
Bugfixes "Fixes lockpicking prof exploit"

#### Purpose of change
Lockpicking attempts always fired their practise session immediatly after starting the activity. As a result it could be abused by repeatedly interrupting the activity and starting a new attempt (each giving the full xp)

Fixes #47168

#### Describe the solution
Moved the practise session calls into the activities finish method and addedfrom_moves to calendar to have a way to convert moves into time_duration. (in case future activities need a way to convert moves for practise sessions)

#### Testing

- Spawn in some makeshift lockpicks and start picking a locked door.
- Stop the activity with "."
- Check prof xp and repeat process

### CODE REVIEW

File: src/calendar.h [hunk 1]
```diff
@@ -203,6 +203,10 @@ class time_duration
             return time_duration( t );
         }
         template<typename T>
+        static constexpr time_duration from_moves( const T t ) {
+            return time_duration( t / 100 );
+        }
```
Comment (anothersimulacrum) [inline src/calendar.h:208]: We've got a couple of places that could use this, search `from_moves` in the current repo.

Comment (Jamuro-g) [reply src/calendar.h:208]: i will look into it.
should i do it in the same pr or wait for this one to be merged and make a seperate one?
