### PR TITLE
Revamp achievement requirement tracking

### LINKED ISSUE #39879: Achievements keep tracking scores after they're completed
# Describe the bug
After you complete an achievement the game continues adding to the score so that it says stuff like `103/1 zombies killed` or w/e. In the case of the 'Rude Awakening' it voids your already completed achievement when you add to the score after the time has expired.

# Steps To Reproduce
1. spawn in, kill a few zombies in the first minute, `3/1 monsters killed`, achievement marked as completed
2. wait until 8:01:01, kill another zombie, `4/1 monsters killed`, achievement VOID

# Expected behavior
when an achievement is completed (or failed by missing requirements) it should stop counting things for it

# Screenshots
zombies killed in first minute
01 Untitled
wait a minute kill another
02 Untitled

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.E-1182-g9f6568b [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Bugfixes "Achievements no longer become un-completed after they are completed"

#### Purpose of change
Fixes #39879.

#### Describe the solution
We now stop tracking requirement values when the achievement is completed or fails.  Moreover, fixes a bug where a completed achievement could be un-completed by further changes to the underlying statistics.

The achievements screen now shows the requirements values as whatever they were when the achievement was completed or failed.

This inspired a fairly substantial refactoring, which helped me clean up and document some of the related code at the same time.

#### Describe alternatives you've considered
I'm still not sure of the best presentation, but this is certainly a step in the right direction.

#### Testing
Expanded unit tests; playing in-game.

### CODE REVIEW

File: src/achievement.cpp [hunk 1]
```diff
@@ -335,6 +354,10 @@ class requirement_watcher : stat_watcher
             stats.add_watcher( req.statistic, this );
         }
 
+        const cata_variant current_value() const {
```
Comment (ifreund) [inline src/achievement.cpp:357]: Clang tidy caught this:
```suggestion
        cata_variant current_value() const {
```
