### PR TITLE
Fix weapons dropping without message on reload

### LINKED ISSUE #49890: Glock 18 disappears when reloaded with 30-round magazine, no log message
### Describe the bug

I just encountered a weird bug.

My modded Glock 18 (with ergonomic grip, pistol stock, and underbarrel laser sight) is currently loaded with a Glock 9x19mm 17-round magazine.

It turns out, when I (r)eload it with a Glock 9x19mm 30-round magazine, the gun disappears!

This doesn't seem to happen if I manually (u)nload the 17-round magazine first, then (r)eload the empty gun with the other magazine.  But the disappearing-gun bug consistently happens when I attempt to reload the already-loaded gun.

[Had some trouble attaching the save file directly, [you can retrieve it from my Dropbox here](https://www.dropbox.com/s/2q1cwvf4vll4u43/algernop.tar.gz?dl=0)].

### Steps To Reproduce

1.  Press (r) to bring up the "Reload item" menu.
2.  Select "Glock 18C+3 (17/17 9x19mm)" to reload.
3.  The 30-round Glock magazine in my inventory is replaced with the 17-round Glock magazine, but the gun that we just reloaded has disappeared!
4.  No log message about reloading the gun appears.

### Expected behavior

I expected the Glock 18C+3 to remain in my inventory, loaded with the 30-round magazine.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 21.04; Release: 21.04; Codename: hirsute; 
- Game Version: ab86019 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Graphical Overmap [Graphical_Overmap]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by WelpThatWorked**
#### Summary
None

#### Purpose of change
Fix #49890 

#### Describe the solution
Items without remote use flag always mark use_loc false, so they bypass the proper checks to generate the log message, being removed from the inventory later (?), leading to the player thinking the weapon disappeared. Add a check to not do that. 

#### Testing

Loaded save given by issue, reloaded Glock 18c with 30round mag. Weapon dropped after reloading, generating the expected message.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -9191,7 +9191,7 @@ void game::reload( item_location &loc, bool prompt, bool empty )
     }
 
     bool use_loc = true;
-    if( !it->has_flag( flag_ALLOWS_REMOTE_USE ) ) {
+    if( !u.has_item(*it) && !it->has_flag( flag_ALLOWS_REMOTE_USE ) ) {
```
Comment (Wishbringer) [inline src/game.cpp:9194]:
```suggestion
    if( !u.has_item( *it ) && !it->has_flag( flag_ALLOWS_REMOTE_USE ) ) {
```
