### PR TITLE
Ensure that all items in the same stack have the same invlet

### LINKED ISSUE #17404: Inventory letters are sometimes incorrectly reported in the message area
Version: 0.C-15980-g55e722e
This is similar to #10165. A long time ago, it was closed as not a bug, but I disagree.

I started out with `m - plastic bag of pork sticks` and `n - plastic bag of potato chips` in my inventory. After eating the pork sticks, the message area reported `m - an empty plastic bag` (correct). Then I ate the chips and the message area reported `n - an empty plastic bag`, but in the inventory, no item was associated with `n` and the 2 empty plastic bags were associated with `m`.

If the message area reports something, it had better be accurate- the expected behavior is for the message area to report `m - 2 empty plastic bags` or something along those lines. It appears that this happens whenever there is already an empty container in the inventory.

### PR DESCRIPTION
**Pull request by sethsimon**
Fixes #17404.

Currently, items in the same stack (that is, an inventory is a `list< list< item > >`, and by stack, I mean the `list< item >`) are allowed to have different invlets, but only the invlet of the front of the stack is used. By enforcing a rule (implemented in `inventory::restack`) that all items in the same stack must have the same invlet, code that deals with invlets can be a little simpler.

This PR also modifies `player::consume` so that the inventory is restacked and sorted before printing any messages about invlets.

### CODE REVIEW

File: src/inventory.cpp [hunk 1]
```diff
@@ -372,6 +372,16 @@ void inventory::restack(player *p)
     for( auto &elem : to_restack ) {
         add_item( elem );
     }
+
+    //Ensure that all items in the same stack have the same invlet.
+    for( auto outer = items.begin(); outer != items.end(); outer++ ) {
```
Comment (BevapDin) [inline src/inventory.cpp]: Both loops could be written as range-based for loops (see loop directly above).

Also, just assign the letter, there is no need to check for it already being there.

Comment (sethsimon) [inline src/inventory.cpp]: Noted.
