### PR TITLE
Military maps no longer reveal farm silos and animal shelters

### LINKED ISSUE #32280: Military Operations Map marks incorrect locations
Describe the bug
After reading any "Military Operations" category map, you will notice that regular silos and animal shelters are marked.  I assume that this is related somehow to the fact that it checks for "nuclear silos" and "evacuation shelters", and the other locations are getting caught in that check.

1. Start a new character with an unexplored map.
2. Spawn in a military operations map.
3. Read it and check the map screen.

Expected behavior
The military should have no interest in animal shelters and regular silos, therefore they shouldn't be marked.

Screenshots
https://i.imgur.com/YhVZKUJ.png
https://i.imgur.com/8MZctLR.png

- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-5441-g5f096ff [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    sees-player icon, -attitude [sees_player_less_attitude],
    No Rail Stations [No_Rail_Stations],
    [DP_MOD] Hide DEBUG [DP_No_Debug_Tile],
    No Fungal Monsters [No_Fungi]

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
#### Summary

```SUMMARY: Bugfixes "Military maps no longer reveal farm silos and animal shelters"```

#### Purpose of change

Fixes #32280.

#### Describe the solution

Allow usage of `om_terrain_match_type` in items with `reveal_map` use action.

### CODE REVIEW

File: src/iuse_actor.h [hunk 1]
```diff
@@ -25,6 +25,7 @@ class player;
 struct iteminfo;
 struct tripoint;
 
+enum ot_match_type;
```
Comment (ZhilkinSerg) [inline src/iuse_actor.h]:
```suggestion
```

File: src/iuse_actor.cpp [hunk 2]
```diff
@@ -1078,16 +1078,28 @@ void reveal_map_actor::load( JsonObject &obj )
...
     while( jarr.has_more() ) {
-        omt_types.push_back( jarr.next_string() );
+        if( jarr.test_string() ) {
+            ter = jarr.next_string();
+            ter_match_type = ot_match_type::contains;
+        } else {
+            JsonObject jo = jarr.next_object();
+            ter = jo.get_string( "om_terrain" );
+            ter_match_type = jo.get_enum_value<ot_match_type>( jo.get_string( "om_terrain_match_type",
+                             "CONTAINS" ), ot_match_type::contains );
```
Comment (Night-Pryanik) [inline src/iuse_actor.cpp]: Seems like `get_enum_value` here isn't doing what we want for it to do. It checks for a **member** called `TYPE`, `EXACT` and any other enum from `ot_match_type` enum list. Obviously it didn't find anything like that, so it falls back to default value, `CONTAINS`.

Comment (ZhilkinSerg) [reply src/iuse_actor.cpp]: Right, it should not use `get_string`, just do `get_enum_value<>` directly.
