### PR TITLE
Fix some of the NPC attacking logic

### LINKED ISSUE #49830: NPCs keep causing game errors
### Describe the bug

Every time I give my NPCs multiple melee weapons, or virtually any other items, they throw them instead of using the weapon as a melee weapon, causing a game error in the process.

### Steps To Reproduce

Give an NPC multiple melee weapons, such as a combat knifes. Go up to a enemy, cause error.

In vanilla, NPCs still throw their melee weapons away, but hte game doesn't error.

### Expected behavior

The NPC should use melee weapons as melee weapons, even if the damage from throwing the weapon is respectable. Also, I wouldn't expect this to cause an error, but the error will likely be fixed soon.

### Screenshots

image
image
image
Aftermath
image

### Versions and configuration

- OS: Windows 10
- Game Version: 2021-07-10-1214
- Graphics version: tiles
- Ingame language: American English
- Mods loaded: 
      [
  "dda",
  "no_npc_food",
  "package_bionic_professions",
  "BL9_100monres",
  "secronom",
  "secronom_lore_expansion",
  "realdarkskies",
  "MMA",
  "MMA_Mods_Extension",
  "adv_gear",
  "aftershock",
  "amplified_players_features",
  "Arcana",
  "ArmUpSurvEx",
  "arsenal_breach",
  "Arts' Guns",
  "battle_maid",
  "Bootleg_Walkers",
  "crt_expansion",
  "Cata++",
  "Dorf_Life",
  "dried_fruits",
  "ExArch",
  "growable-pots",
  "Gourmand'sGraces",
  "magiclysm",
  "Medieval_Mod_Reborn",
  "Mining_Mod",
  "MST_Extra",
  "mutant_animals",
  "mutant_insects",
  "Mutation_Changes",
  "sees_player_hitbutton",
  "sierra_madre",
  "Tankmod_Revived",
  "vamp_stuff",
  "WildLiving",
  "sarcophagi_access",
  "vamp_stuff+arcana",
  "recruitment_options",
  "fuji_mpp",
  "More_Military",
  "no_cbm_slots",
  "speedydex",
  "stats_through_kills",
  "StatsThroughSkills",
  "No_Fungi",
  "pneumo_fun",
  "blazemod",
  "Heavy miners",
  "EngineeringEssentials",
  "bow_opness",
  "More_Survivors_Stories",
  "wandering_masters",
  "AAA",
  "fallout",
  "Locked_and_Loaded",
  "demon_spider_a",
  "modern_weapon",
  "crazy_labs",
  "modular_turrets_no_blacklist",
  "Salvaged_Robots",
  "light_weariness",
  "extra_mut_scens",
  "food_irradiator",
  "hydroponics",
  "zets_hair_extensions_undead",
  "more_locations",
  "zets_hair_ext_more_locations",
  "morlock_village",
  "No_Rail_Stations",
  "WHALEYHAIR_UDP",
  "realdarkskies_faction_balance",
  "advtech",
  "bioco"
]

### Additional context

https://www.dropbox.com/s/41mnje817dsbzvk/Piercy.7z?dl=0
Running Kenen's latest modpack with UDP tileset mods.

https://www.dropbox.com/s/ifphqgzmw49yktm/High%20Shoals.7z?dl=0
Vanilla.

### LINKED ISSUE #49834: NPCs throw their items even when set to not use ranged weapons
### Describe the bug

Currently NPCs are throwing their entire inventory including equipped weapons that are far better as actual melee weapons.

This includes things like radios, bats, bottles, just about everything I've seen.

### Steps To Reproduce

1. Spawn NPC and force them friendly through debug or other means
2. Tell NPC to not use ranged weapons
3. Engage in combat with zombies (any kind of hostile really)

### Expected behavior

NPCs should never throw away their best melee weapon at a bare minimum unless it's a last resort.
NPCs should not throw items in the first place unless they've been instructed to use ranged weaponry.

### Screenshots

image

image

### Versions and configuration

- OS: Windows
- Game Version: aa126fe
- Graphics version: Tiles
- Ingame language: English
- Mods loaded: DDA, Magiclysm

### Additional context

Savegame:

[Vine Hill - TEST.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6796184/Vine.Hill.-.TEST.zip)

### PR DESCRIPTION
**Pull request by GoLoT**
#### Summary
Bugfixes "Fix some of the NPC attack logic"

#### Purpose of change
Keep in mind this is a quick fix for the more pressing issues with the new NPC attack logic. The goal is to try to avoid NPCs throwing all their inventory, fixing NPCs trying to shoot unequipped weapons and getting them to use weapons in less stupid ways.
Fixes #49834
Fixes #49830

#### Describe the solution
This is in no way a perfect solution and it has its issues. For the most part NPCs will now try to behave according to the flags set, trying to avoid friendly fire, not killing themselves while in a car, moving to nearby targets when a melee weapon is the preferred weapon and so on.

~~EDIT: Updated the npc_attack test so it compiles but the expected values are the old ones, making the test fail. I think it's pointless to try to fix the test now as the values would be meaningless since the evaluation functions will need adjustments.~~

EDIT: Tests updated to reflect scenarios and outcomes instead of checking evaluation values.

#### Describe alternatives you've considered
Proposing a revert of the original commit until this is solved. I chose to push a quick fix so NPCs can at least defend themselves while the feature is polished.

#### Testing
I didn't do nearly enough testing but I did test the most basic stuff. I tried giving an NPC a ranged and a melee weapon and it used the ranged weapon until out of ammo. Then switched to the melee weapon.

I tried driving the NPC around and it stood in the vehicle and tried to shoot enemies until running out of ammo. Then it switched to a melee weapon and waited for enemies to come without jumping from the vehicle or trying to kill himself.

Throwing is severely nerfed now and items that are dangerous (i.e. active grenades) are given a huge boost. The math behind choosing to throw items is... well... missing. I simply gave it some multipliers that seem to be working so far. When an item has the NPC_THROWN flag it will be more likely to be thrown but it still has to be a better choice (as in better damage output) than using a melee weapon.

With the changes I didn't get any more "missing gun" errors or infinite loops and the NPCs at the very least showed a will to live. Also they kept their inventory, and being selfish in a cataclysm is always a good thing.

### CODE REVIEW

**Comment by GoLoT** [comment]
@KorGgenT evaluate() results are close to what they were before but still need tweaking and adding other multipliers (like taking into account being surrounded when choosing weapons). If you feel the values are off or not in line with your original idea, feel free to pick this PR apart and take only the changes needed.

**Comment by mlangsdorf** [comment]
I may be slightly confused, but it looks like the checks for `rules.has_flag( ally_rule::use_guns )` and `rules.has_flag( ally_rule::use_silent )` got lost in the initial PR and are still absent.  Would you please double-check if that's the case and if so, please add them back to the gun and throw `can_use()` routines?  Thanks.

**Comment by GoLoT** [comment]
@mlangsdorf those were added in the original PR [here](https://github.com/CleverRaven/Cataclysm-DDA/pull/47562/files#diff-c0bb4be7b25fabd8562e41fd6a19f1ba9eeaf1c08256cd063f2ee6cfd1338d0dR1431) and working properly now that weights are favoring ranged weapons over throwing.

The checks aren't present for throwing though. Should throwing be considered non-silent?

File: src/npc_attack.cpp [hunk 1]
```diff
@@ -19,9 +19,9 @@ const std::map<Creature::Attitude, int> attitude_multiplier = {
     { Creature::Attitude::NEUTRAL, -1 }
 };
 // if you are attacking your target, multiply potential by this number
-const int target_modifier = 3;
+const float target_modifier = 1.5f;
 // if you kill the creature, multiply the potential by this number
-const int kill_modifier = 2;
+const float kill_modifier = 1.5f;
```
Comment (KorGgenT) [inline src/npc_attack.cpp:24]: why are we switching to float math?

File: src/npc_attack.cpp [hunk 2]
```diff
@@ -105,8 +140,7 @@ void npc_attack_melee::use( npc &source, const tripoint &location ) const
 
 tripoint_range<tripoint> npc_attack_melee::targetable_points( const npc &source ) const
 {
-    const int reach_range{ weapon.reach_range( source ) };
-    return get_map().points_in_radius( source.pos(), reach_range );
+    return get_map().points_in_radius( source.pos(), 8 );
```
Comment (KorGgenT) [inline src/npc_attack.cpp:143]: an npc can't technically target these points. explain?

File: src/npc_attack.cpp [hunk 3]
```diff
@@ -177,35 +211,62 @@ npc_attack_rating npc_attack_melee::evaluate_critter( const npc &source,
...
+        }
         return;
     }
 
     const int dist = rl_dist( source.pos(), location );
 
-    if( source.aim_per_move( weapon, source.recoil ) > 0 &&
-        source.confident_shoot_range( weapon, source.get_most_accurate_sight( weapon ) ) >= dist ) {
+    // Only aim if we aren't in risk of being hit
+    // TODO: Get distance to closest enemy
```
Comment (KorGgenT) [inline src/npc_attack.cpp:260]: these comments refer to something that needs to be in evaluate(), not use().

File: src/npc_attack.cpp [hunk 4]
```diff
@@ -298,17 +359,26 @@ npc_attack_rating npc_attack_gun::evaluate_tripoint(
...
-    const int distance_penalty = std::max( distance_to_me - 1,
-                                           ( source.closest_enemy_to_friendly_distance() - 1 ) * 2 );
-    double potential = damage * attitude_mult - distance_penalty;
+
+    if( att != Creature::Attitude::HOSTILE ) {
+        // No point in throwing stuff at neutral/friendly targets
+        return npc_attack_rating( cata::nullopt, location );
+    }
+
+    bool avoids_friendly_fire = source.rules.has_flag( ally_rule::avoid_friendly_fire );
```
Comment (KorGgenT) [inline src/npc_attack.cpp:368]:
```suggestion
    const bool avoids_friendly_fire = source.rules.has_flag( ally_rule::avoid_friendly_fire );
```

File: src/npc_attack.cpp [hunk 5]
```diff
@@ -298,17 +359,26 @@ npc_attack_rating npc_attack_gun::evaluate_tripoint(
...
+    double potential = damage;
+
+    // Make attacks that involve moving to find clear LOS slightly less likely
+    if( has_obstruction( source.pos(), location, avoids_friendly_fire ) ) {
+        potential *= 0.9f;
+    } else if( avoids_friendly_fire && !source.wont_hit_friend( location, gun, false ) ) {
+        potential *= 0.95f;
+    }
+
+    // Prefer targets not directly next to you
```
Comment (KorGgenT) [inline src/npc_attack.cpp:379]: why? npcs still have to deal with those

File: src/npc_attack.cpp [hunk 6]
```diff
@@ -329,10 +399,13 @@ void npc_attack_activate_item::use( npc &source, const tripoint &/*location*/ )
 
 bool npc_attack_activate_item::can_use( const npc &source ) const
 {
-    const bool can_use_grenades = ( source.is_player_ally() &&
-                                    !source.rules.has_flag( ally_rule::use_grenades ) ) || source.is_hallucination();
-    //TODO: make this more complete. only does BOMB type items
-    return can_use_grenades && activatable_item.has_flag( flag_NPC_ACTIVATE );
+    if( !activatable_item.has_flag( flag_NPC_ACTIVATE ) ) {
```
Comment (KorGgenT) [inline src/npc_attack.cpp:402]: i don't understand the purpose of churning this function. your changes are the exact same result.

File: src/npc_attack.cpp [hunk 7]
```diff
@@ -361,21 +434,34 @@ std::vector<npc_attack_rating> npc_attack_activate_item::all_evaluations( const
 
 void npc_attack_throw::use( npc &source, const tripoint &location ) const
 {
-    // WARNING! wielding the item invalidates the reference!
```
Comment (KorGgenT) [inline src/npc_attack.cpp:364]: this is still true, i dunno why you removed this comment

File: src/npc_attack.cpp [hunk 8]
```diff
@@ -384,30 +470,30 @@ bool npc_attack_throw::can_use( const npc &source ) const
...
-           !( thrown_item.has_flag( flag_NPC_THROW_NOW ) || thrown_item.has_flag( flag_NPC_ACTIVATE ) ) &&
-           // i don't trust you as far as i can throw you.
-           source.throw_range( single_item ) != 0;
+    if( thrown_item.has_flag( flag_NPC_THROW_NOW ) || thrown_item.has_flag( flag_NPC_THROWN ) ) {
+        //Always allow throwing items that are flagged as throw now or npc_thrown
+        return true;
+    }
+
+    bool throwable = source.throw_range( single_item ) > 0 && !source.is_worn( thrown_item ) &&
+                     !thrown_item.has_flag( flag_NPC_ACTIVATE );
```
Comment (KorGgenT) [inline src/npc_attack.cpp:491]: you reversed tihs. are you sure this is correct that you can't throw items that have NPC_ACTIVATE?

File: src/npc_attack.cpp [hunk 9]
```diff
@@ -384,30 +470,30 @@ bool npc_attack_throw::can_use( const npc &source ) const
...
+    throwable = throwable && !thrown_item.is_gun() && !thrown_item.is_armor() &&
+                !thrown_item.is_comestible() && !thrown_item.is_magazine() && !thrown_item.is_tool() &&
+                !thrown_item.is_unarmed_weapon();
```
Comment (KorGgenT) [inline src/npc_attack.cpp:494]: seems really wonky tbh. we really should have some better logic here that doesn't require you to check the item's type in code like this.

File: src/npc_attack.cpp [hunk 10]
```diff
@@ -429,7 +515,23 @@ npc_attack_rating npc_attack_throw::evaluate(
         return effectiveness;
     }
     const int penalty = base_penalty( source );
+    // TODO: Should this be a field to cache the result?
+    bool avoids_friendly_fire = source.rules.has_flag( ally_rule::avoid_friendly_fire );
```
Comment (KorGgenT) [inline src/npc_attack.cpp:531]:
```suggestion
    const bool avoids_friendly_fire = source.rules.has_flag( ally_rule::avoid_friendly_fire );
```

File: src/npc_attack.cpp [hunk 11]
```diff
@@ -486,23 +588,28 @@ npc_attack_rating npc_attack_throw::evaluate_tripoint(
...
+        return npc_attack_rating( cata::nullopt, location );
     }
 
     const float throw_mult = throw_cost( source, single_item ) * source.speed_rating() / 100.0f;
     const int damage = source.thrown_item_total_damage_raw( single_item );
     float dps = damage / throw_mult;
     const int distance_to_me = rl_dist( location, source.pos() );
-    const int distance_penalty = std::max( distance_to_me - 1,
-                                           ( source.closest_enemy_to_friendly_distance() - 1 ) * 2 );
+    const int distance_penalty = std::max( std::min( distance_to_me,
```
Comment (KorGgenT) [inline src/npc_attack.cpp:619]: use clamp instead of std::max( std::min())

File: src/npc_attack.h [hunk 12]
```diff
@@ -77,8 +77,9 @@ class npc_attack_melee : public npc_attack
 class npc_attack_gun : public npc_attack
 {
         const gun_mode gunmode;
+        item &gun;
```
Comment (KorGgenT) [inline src/npc_attack.h:80]: wait, why? you get that from gunmode!

File: src/npc_attack.cpp (hunk 1 above)
Comment (GoLoT) [reply src/npc_attack.cpp:24]: It's a change to use small multipliers to not boost the priority too much for targets/kill targets. This can be reverted.

File: src/npc_attack.cpp (hunk 5 above)
Comment (GoLoT) [reply src/npc_attack.cpp:379]: Trying to reduce weights for closer targets so melee weapons can be a preferred choice for those targets even if the damage would be lower. Shooting point blank comes with issues as you can't aim properly.

File: src/npc_attack.cpp (hunk 8 above)
Comment (GoLoT) [reply src/npc_attack.cpp:491]: Had to double check. NPC_ACTIVATE is the inactive version of explosives. When they are activated they loose the flag so throwing NPC_ACTIVATE items would mean throwing inactive grenades.

File: src/npc_attack.cpp (hunk 6 above)
Comment (GoLoT) [reply src/npc_attack.cpp:402]: Bailing early for items that aren't activable so more checks (is_player_ally(), etc) don't have to be done. If more checks are added, this will still cull any extra checks for those items.

File: src/npc_attack.cpp (hunk 9 above)
Comment (GoLoT) [reply src/npc_attack.cpp:494]: Yup. Left a comment below so it can be addressed eventually.

File: src/npc_attack.cpp (hunk 3 above)
Comment (GoLoT) [reply src/npc_attack.cpp:260]: Evaluate won't really work for this though. Evaluate will give a target and preferred attack, but in some cases the NPC will choose to try and finish an enemy that isn't the closest and the NPC might get stuck trying to aim while being whacked by a nearby enemy constantly messing up the aim.

It has to be done here so the NPC tries to hipfire.

File: src/npc_attack.h (hunk 12 above)
Comment (GoLoT) [reply src/npc_attack.h:80]: Tried to make the gunmode member non-const but it still complained about const-ness whenever I tried to get the weapon with *gunmode. It seems to always choose the const version of the function over the non-const.

File: src/npc_attack.cpp [hunk 13]
```diff
@@ -486,23 +600,28 @@ npc_attack_rating npc_attack_throw::evaluate_tripoint(
...
+                                           source.closest_enemy_to_friendly_distance() ) - 3, 0 );
+    const float suitable_item_mult = thrown_item.has_flag( flag_NPC_THROWN ) ? 0.2f : -0.15f;
+    const float distance_mult = -distance_penalty / 10.0f;
 
-    double potential = dps * attitude_mult - distance_penalty;
+    double potential = dps * ( 1.0f + distance_mult + suitable_item_mult );
     if( critter && damage >= critter->get_hp() ) {
```
Comment (actual-nh) [inline src/npc_attack.cpp:625]:
```suggestion
    if( potential > 0.0f && critter && damage >= critter->get_hp() ) {
```
And the same down below for that multiplication of potential.

File: src/npc_attack.cpp [hunk 14]
```diff
@@ -486,23 +600,28 @@ npc_attack_rating npc_attack_throw::evaluate_tripoint(
...
 
     const float throw_mult = throw_cost( source, single_item ) * source.speed_rating() / 100.0f;
     const int damage = source.thrown_item_total_damage_raw( single_item );
     float dps = damage / throw_mult;
     const int distance_to_me = rl_dist( location, source.pos() );
-    const int distance_penalty = std::max( distance_to_me - 1,
-                                           ( source.closest_enemy_to_friendly_distance() - 1 ) * 2 );
+    const int distance_penalty = std::max( std::min( distance_to_me,
+                                           source.closest_enemy_to_friendly_distance() ) - 3, 0 );
+    const float suitable_item_mult = thrown_item.has_flag( flag_NPC_THROWN ) ? 0.2f : -0.15f;
```
Comment (actual-nh) [inline src/npc_attack.cpp:621]: If this is a melee/true ranged weapon without flag_NPC_THROW, perhaps base this penalty on the weapon dps?

File: src/npc_attack.cpp [hunk 15]
```diff
@@ -486,23 +600,28 @@ npc_attack_rating npc_attack_throw::evaluate_tripoint(
...
     }
 
     const float throw_mult = throw_cost( source, single_item ) * source.speed_rating() / 100.0f;
     const int damage = source.thrown_item_total_damage_raw( single_item );
     float dps = damage / throw_mult;
     const int distance_to_me = rl_dist( location, source.pos() );
-    const int distance_penalty = std::max( distance_to_me - 1,
-                                           ( source.closest_enemy_to_friendly_distance() - 1 ) * 2 );
+    const int distance_penalty = std::max( std::min( distance_to_me,
+                                           source.closest_enemy_to_friendly_distance() ) - 3, 0 );
```
Comment (actual-nh) [inline src/npc_attack.cpp:620]:
```suggestion
    const int closest_enemy_dist = source.closest_enemy_to_friendly_distance();
    int distance_penalty = std::abs( distance_to_me - 3) ;
    // Ideally, the 3 in the above should be adjusted for reach weapons, etc
    if ( closest_enemy_dist < distance_penalty + 2 ) { // not sure exactly how to adjust distance_penalty here
        distance_penalty = std::min( distance_penalty, std::abs( closest_enemy_dist - 1 ) * 2 );
    }
```
This will need considerable formatting! It penalizes throwing when something is close enough that melee should be preferred, or when throwing too close to a friendly.

File: src/npc_attack.cpp [hunk 16]
```diff
@@ -298,17 +359,26 @@ npc_attack_rating npc_attack_gun::evaluate_tripoint(
...
+
+    // Make attacks that involve moving to find clear LOS slightly less likely
+    if( has_obstruction( source.pos(), location, avoids_friendly_fire ) ) {
+        potential *= 0.9f;
+    } else if( avoids_friendly_fire && !source.wont_hit_friend( location, gun, false ) ) {
+        potential *= 0.95f;
+    }
+
+    // Prefer targets not directly next to you
+    potential *= distance_to_me > 2 ? 1.15f : 0.85f;
```
Comment (actual-nh) [inline src/npc_attack.cpp:380]: Perhaps the 2 should be adjusted (increased?) for reach weapons?

**Review by actual-nh — COMMENTED** [review]
A few thoughts.

File: src/npc_attack.cpp (hunk 14 above)
Comment (GoLoT) [reply src/npc_attack.cpp:621]: At first I tried to add a check to see if the weapon had higher dps when wielded than thrown but it didn't work out as expected. I eventually reduced the multiplier for items not flagged and it made the NPCs not throw weapons as often. I think cudgels are still thrown in some circunstamces but that's why the math still needs a lot of work.

It's mainly the logic when executing actions that I fixed but the math is just placeholder and random values that simply worked for my tests.

File: src/npc_attack.cpp (hunk 16 above)
Comment (GoLoT) [reply src/npc_attack.cpp:380]: The multiplier here is simply trying to get the NPC to pick a melee weapon (if a decent one is available) when in close range by lowering the potential for this weapon as ranged weapons usually have a much higher damage value. I don't recall seeing any enemies with reach attacks but if there are any, it won't really matter that much.

The weights need work but the main goal was to fix the logic issues that led to NPCs throwing all their inventories, throwing errors and not being able to chase targets in melee.

File: src/npc_attack.cpp (hunk 15 above)
Comment (GoLoT) [reply src/npc_attack.cpp:620]: I'll add this change along with one of KorGgenT suggestions when I have access to my environment to test it, it will be in a few hours. The math still is a placeholder and will need more tweaking in a new PR. Hopefully from somene that can work it out as right now the modifiers for each kind of attack are inconsistent.

File: src/npc_attack.cpp (hunk 16 above)
Comment (actual-nh) [reply src/npc_attack.cpp:380]: OK. (There are monsters with reach special attacks, BTW.)

File: src/npc_attack.cpp (hunk 2 above)
Comment (KorGgenT) [reply src/npc_attack.cpp:143]: moving toward enemies is in a different part of the code. this function is "the npc has already chosen to use melee, what are the targets?"

Comment (GoLoT) [reply src/npc_attack.cpp:143]: It doesn't work that way though. As long as the NPC has any items it will decide throwing said items is the way to go and won't bother moving into melee range.

File: src/npc_attack.cpp (hunk 16 above)
Comment (GoLoT) [reply src/npc_attack.cpp:380]: This is probably not the best way to deal with nearby targets anyway. I think a new PR to balance/tweak weights and add some checks that are missing is in order.

File: src/npc_attack.cpp (hunk 11 above)
Comment (GoLoT) [reply src/npc_attack.cpp:619]: I couldn't get it to work in VS. It turns out std::clamp() is from C++17 and the project is set up for C++14. I'll make it more verbose so at least the min -> max thing doesn't impact readability.

**Comment by GoLoT** [comment]
I think I addressed every review comment, the UI doesn't make it easy so if I missed something let me know. Same if you feel something isn't clear.

I think this PR is ready for merge if no one has objections. Tweaking the weights is definitely needed but I think that should be done in a new PR as the more pressing issue is trying to leave experimental in a playable state. Trying to do everything in this PR can extend indefinitely and will delay the fix. Fine tuning weights can wait and needs further discussion as right now the attacks and weapons are tested independently without any context of other possible attack methods, making it hard to find a way to make NPCs make sensible choices. Tests have to be updated to reflect the new weights/evaluations when the evaluation functions are stable.

There is also the matter of throwing explosives that I didn't really test and the lack of support for some NPC flags.

I repeated some of my tests right now and everything seems to be working so far. One of the tests that showed multiple issues before was letting the barred zombies in a regufee center out and watching the guard NPCs go crazy. I tried that again and they got rid of the zombies as usual without any apparent issues. Also tested again with a single NPC and he used his ranged weapon until he broke an arm and couldn't wield it. Then he switched to melee and eventually died as a hero.

File: src/npc_attack.cpp (hunk 13 above)
Comment (GoLoT) [reply src/npc_attack.cpp]: Done manually. I'll mark it as resolved.

**Comment by personjerry** [comment]
Perhaps as a stopgap there can be a combat setting for NPCs to not consider throwing at all? I.e. `if (no_throw_flag) potential = 0;`

**Comment by GoLoT** [comment]
As per @mlangsdorf 's suggestion I added a check to prevent throwing items (unless it's an active explosive) if ranged attacks are disallowed. A separate flag can be added if needed though.

**Comment by actual-nh** [comment]
> I think this PR is ready for merge if no one has objections. Tweaking the weights is definitely needed but I think that should be done in a new PR as the more pressing issue is trying to leave experimental in a playable state. Trying to do everything in this PR can extend indefinitely and will delay the fix. Fine tuning weights can wait and needs further discussion as right now the attacks and weapons are tested independently without any context of other possible attack methods, making it hard to find a way to make NPCs make sensible choices. Tests have to be updated to reflect the new weights/evaluations when the evaluation functions are stable.

I think at least some of the tests can be changed to requiring a specific ordering of result values instead of requiring specific result values - if the question is whether the code is working for doing a melee weapon at melee range, don't check its numeric evaluation, check to make sure it's better than a gun/thrown weapon/etc.

**Comment by GoLoT** [comment]
Reworked tests to reflect scenarios and outcomes instead of testing specific return values. More tests scenarios will have to be added and evaluation functions updated accordingly (TDD).

If all checks pass this should be ready to merge. There are some behavior issues still but the NPCs should at least defend themselves. Tweaking will come from playtesting and new tests.

File: src/npc_attack.cpp (hunk 11 above)
Comment (jbytheway) [reply src/npc_attack.cpp]: We have our own `clamp` in `cata_utility.h`.

Comment (GoLoT) [reply src/npc_attack.cpp]: Thanks. Found it when I was reworking the tests and already updated the code to use clamp where applicable. I'll mark as resolved to avoid confusion.

File: src/npc_attack.cpp (hunk 7 above)
Comment (GoLoT) [reply src/npc_attack.cpp:366]: Sorry, missed this comment. Now after trying to wield the weapon the reference isn't used anymore and the next action is recalculated next turn (likely attacking with that weapon if nothing has changed), creating a new attack instance with its own weapon reference.

**Comment by actual-nh** [comment]
Something wrong re `ammo_sufficient`, possibly other things?

File: src/npc_attack.cpp [hunk 17]
```diff
@@ -172,40 +214,63 @@ npc_attack_rating npc_attack_melee::evaluate_critter( const npc &source,
...
-    if( !weapon.ammo_sufficient( &source ) ) {
-        source.do_reload( weapon );
+    if( !source.is_wielding( gun ) ) {
+        if( !source.wield( gun ) ) {
+            debugmsg( "ERROR: npc tried to equip a weapon it couldn't wield" );
+        }
+        return;
+    }
+
+    if( !gun.ammo_sufficient() ) {
```
Comment (anothersimulacrum) [inline src/npc_attack.cpp:244]:
```suggestion
    if( !gun.ammo_sufficient( &source ) ) {
```

Comment (GoLoT) [reply src/npc_attack.cpp]: Thanks, I messed up when fixing the conflicts.

**Comment by I-am-Erk** [comment]
@GoLoT how is this doing? Is it about ready?

**Comment by GoLoT** [comment]
I think @kevingranade wanted to take a look at it but the ASan issues kept him busy.

Unless someone finds a specific issue that prevents merging, I consider it ready. There are issues that I have more or less pin-pointed but I didn't want to extend this PR. I'll work on those in separate PRs when this is merged while I test everything on my current experimental run.

File: src/npc_attack.cpp [hunk 18]
```diff
@@ -32,20 +28,42 @@ const int base_throw_now = 10'000;
...
+{
+    int distance = rl_dist( target.pos(), source.pos() );
+    for( const weak_ptr_fast<Creature> &buddy : source.get_cached_friends() ) {
+        if( !buddy.expired() ) {
+            distance = std::min( distance, rl_dist( target.pos(), buddy.lock()->pos() ) );
+        }
+    }
+    return distance;
+}*/
+
```
Comment (KorGgenT) [inline src/npc_attack.cpp:66]: we don't like keeping commented code in the codebase either. we can just write it again later, but it's best to just remove it if you would keep it commented.

Comment (KorGgenT) [reply src/npc_attack.cpp:66]:
```suggestion
```

**Comment by cainiaowu** [comment]
There was some behavior tree implementation in #39810, perhaps the NPC AI could use some of that.
