### PR TITLE
Trains support, subway mapgen changes.

### LINKED ISSUE #29743: Railroad track tiles block movement of vehicle
**Describe the bug**  
Railroad track tiles prevent movement of vehicle. It produces message "<Carname> collides with the railroad track"

**To Reproduce**  
1. Teleport to railroad station
2. Spawn any vehicle
3. Move or drive vehicle to railroad truck tile

**Expected behavior**  
Vehicle can move over these tiles.

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version: 0.D-1963-gf689218
 - Graphics version: Tiles
 - Mods loaded: None

**Additional context**  
On build # 8806 it worked fine, on build # 8807 it started happening. I'm sure it's related to #29628

### PR DESCRIPTION
**Pull request by egorzaderiy**
#### Summary
```SUMMARY: Features "Allows trains to move and turn on railroad tiles. Adds appropriate mapgen for subway. "```

#### Purpose of change
Fixes #29743 - Allows movement through railroad for trains. 

#### Describe the solution
For vehicle to through tiles marked with "RAIL" flag, it should satisfy following conditions:

1. All wheels should have "RAIL" flag.
2. At least one wheel should be on rail track. (method `vehicle::can_use_rails()`)

Vehicle can turn to multiplies of 45°.
Vehicle turn alghorytm: 

1. All above conditions ^ `vehicle::can_use_rails()` should be true
2. Calculate new position of wheels using turn degree
3. Check if new position of wheel will land on rail 
4. Check that 3 rails in derection of movement will be of correct type (`t_railroad_track_d` when turn to diagonal and `t_railroad_track` when turn not diagonal)
5. Count number of wheels that will land on rails
6.1. Check that at least 2 wheels not on one side of car will land on rails
6.2. For cars when all wheels on one axis (bikes) only 1 wheel should land on rails

Auto-turning: rails will autoturn if count of wheels positions on rail after turn is bigger or equal to count of the same without turning. This can result of vehicle not moving straight but turning to left/right on junctions.

About mapgen: it have to be changed for subway, else all vehicles will constantly smash walls. 

#### Describe alternatives you've considered
1. Special terrain indicating that rails will turn right/left/not turn, etc.
2. Precalculating possible way and turning points as vehicle moves.
3. Special alghorytm that mutates car parts coordinates in unusual way (instead of using `tileray`). Line by line shifting.
```
O---Oxxx
| ->|   x
|   |    x
O---Oxxx
        x
         x
```
on approaching turn it will become:
```
O--
|  -
|   O
O-- |x
   -|
    O
     x
```
Problem with this - can't determine correct moment to change face direction, is it even exist?
#### Additional context
[Video demo](https://www.dropbox.com/s/3b3ojc0rl125q4b/trains.flv?dl=0)
[Video of autoturn feature](https://www.dropbox.com/s/0fw7ca2ampg3f9n/trains2.flv?dl=0)

- I think current solution wins in effeciency and simpleness over alternatives.
- Distance between wheels determines how vehicle will turn.

I want to add some other features:
- [X] Autoturn when there is only one correct way

I left `lab_train_depot` mapgen unchanged, because it's complicated and is out of scope for this PR.

CR because I want feedback about the code and my choosen approach.

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -2986,6 +2986,24 @@ bool vehicle::is_moving() const
     return velocity != 0;
 }
 
+bool vehicle::can_use_rails() const
+{
+    bool canUse = true;
```
Comment (Night-Pryanik) [inline src/vehicle.cpp]: Could you please replace camelCase with underscores?

File: src/vehicle_move.cpp [hunk 2]
```diff
@@ -1132,11 +1136,126 @@ bool vehicle::act_on_map()
...
+        int turning_wheels_that_are_one_axis_counter = 0;
+
+        for ( int part_index : wheelcache ) {
+            const auto &wheel = parts[part_index];
+            bool rails_ahead = true;
+
+            tripoint newWheelPos = global_pos3 () + parts[part_index].precalc[1];
+
+            // maximum number of incorrect tiles for this type of turn(diagonal or not)
+            const int allowed_incorret_tiles_diagonal = 1;
```
Comment (Night-Pryanik) [inline src/vehicle_move.cpp]:
```suggestion
            const int allowed_incorrect_tiles_diagonal = 1;
```

File: src/vehicle_move.cpp [hunk 3]
```diff
@@ -1132,11 +1136,126 @@ bool vehicle::act_on_map()
...
+            const int allowed_incorret_tiles_not_diagonal = 2;
```
Comment (Night-Pryanik) [inline src/vehicle_move.cpp]:
```suggestion
            const int allowed_incorrect_tiles_not_diagonal = 2;
```

File: src/vehicle_move.cpp [hunk 4]
```diff
@@ -1132,11 +1136,126 @@ bool vehicle::act_on_map()
...
+            int incorret_tiles_diagonal = 0;
```
Comment (Night-Pryanik) [inline src/vehicle_move.cpp]:
```suggestion
            int incorrect_tiles_diagonal = 0;
```

File: src/vehicle_move.cpp (hunk 2 above)
Comment (Night-Pryanik) [inline src/vehicle_move.cpp]: `incorrect`? Here and below.

File: src/vehicle.cpp (hunk 1 above)
Comment (egorzaderiy) [reply src/vehicle.cpp]: Sure, other languages sometimes popup

File: src/vehicle_move.cpp (hunk 2 above)
Comment (egorzaderiy) [reply src/vehicle_move.cpp]: fixed

**Comment by egorzaderiy** [comment]
Should i commit my vehicle used for testing?

File: data/json/terrain.json [hunk 5]
```diff
@@ -9996,72 +9996,6 @@
     },
     "flags": [ "BASHABLE", "TRANSPARENT", "NOITEM", "MOUNTABLE" ]
   },
-  {
-    "id": "t_railroad_tie",
```
Comment (egorzaderiy) [inline data/json/terrain.json]: removed some "*_tie" duplicate entries in json.

**Comment by egorzaderiy** [comment]
It's ready, some things that I left unchanged:

- vehicle speed on rails terrain
- mapgen for lab `lab_train_depot`

**Comment by ifreund** [comment]
First of all, this is really awesome and I can't wait to build a death-train in game.

One concern I have from a realism perspective is that arbitrarily long trains can turn at sharp 45 degree angles as long as there is enough open space around the bend in the track.  As far as I understand the mechanics involved, in real life there is a hard upper limit on the distance between the front and back wheels for a given track curvature.  I really have no clue as to how to calculate this accurately, but I suspect it would be fairly low for the 45 degree curves we have in game now. 

One option for addressing this in this PR, would be to pick a rather arbitrary value as the upper limit, say 8 tiles between front and back wheels.  I think that would already be more realistic than allowing arbitrarily long trains to travel around our tight track curves.  

This could also be expanded to a more in depth calculation taking things such as wheel size, track width, track curvature, etc. in a later PR, or completely left out of this PR to be implemented at a later date.

**Comment by Amoebka** [comment]
> the 45 degree curves we have in game now

Surely those are just necessary abstractions and the tracks don't actually turn 45 degrees in game's setting? I also disagree with setting a hard cap on the distance between wheels. Since the game doesn't support multiple wagons connected to a single engine, having one long vehicle is just an abstraction for a multiwagon train. Otherwise, they are impossible, which is disappointing.

**Comment by egorzaderiy** [comment]
> the tracks don't actually turn 45 degrees in game's setting?

Track actually turn 45 degrees in game right now, see subway mapgen

> One concern I have from a realism perspective is that arbitrarily long trains can turn at sharp 45 degree angles

Well I could try to make this system work for other angles, but for this to work, mapgen could be very difficult to correctly make.

**Comment by hyper2snyper** [comment]
Could there possibly be a way to make some trains, lets say subway trains, go on their own? Like you pay for a ride.

**Comment by Amoebka** [comment]
>Track actually turn 45 degrees in game right now, see subway mapgen

I know they turn 45 in game. What I'm trying to say is that 45 degree turns are an abstraction. As in, if you are an actual character in the world of CDDA you see tracks turn all kinds of flowing curves like we have IRL, but if you are a player you see the same tracks as 45 degree turns because that's how square tiles work. From this point of view, trains turning 45 isn't a realism issue because it's not "really" 45, that's just how the game draws it.

**Comment by egorzaderiy** [comment]
> Like you pay for a ride.
Thats possible with autoturn feature, I think

**Comment by egorzaderiy** [comment]
After reviewing comments, my suggestion is - leave this PR as is and implement hard cap on long trains in next PR.
Please let me know if my implementation goes to wrong way or I should choose different approach.

File: data/json/vehicleparts/wheel.json [hunk 6]
```diff
@@ -15,7 +15,14 @@
...
-    "flags": [ "WHEEL" ]
+    "flags": [ "WHEEL", "RAIL" ]
+  },
+  {
+    "id": "metal_wheel_steerable",
+    "copy-from": "metal_wheel",
+    "type": "vehicle_part",
+    "name": "metal wheel (steerable)",
+    "extend": { "flags": [ "STEERABLE" ] }
   },
```
Comment (mlangsdorf) [inline data/json/vehicleparts/wheel.json]: I'd really prefer to see a new rail wheel, something like:
```
  {
    "id": "rail_wheel",
    "type": "vehicle_part",
    "name": "railroad wheel",
    "item": "wheel_rail",
    "location": "under",
    "symbol": "|",
    "broken_symbol": "x",
    "difficulty": 2,
    "durability": 360,
    "description": "A strong metal wheel.  A flange helps keep it on a rail, but makes it perform terribly when not on a rail.",
    "damage_modifier": 70,
    "breaks_into": [ { "item": "scrap", "count": [ 4, 6 ] }, { "item": "steel_chunk", "count": [ 2, 3 ] } ],
    "rolling_resistance": 0.25,
    "wheel_type": "rail",
    "contact_area": 80,
    "flags": [ "WHEEL", "RAIL" ]
  },
```
and add a rail wheel definition to src/veh_type.cpp:
```
static const std::vector<std::pair<std::string, int>> rail_terrain_mod = {{
        { "RAIL", 8 }
    }
};
```
and adjust vpart_info::load_wheel in the same file:
```
        } else if( wheel_type == "rail" ) {
            wh_info.terrain_mod = rail_terrain_mod;
            wh_info.or_rating = 0.05;
        }
```

File: src/vehicle.cpp [hunk 7]
```diff
@@ -2985,6 +2985,24 @@ bool vehicle::is_moving() const
     return velocity != 0;
 }
 
+bool vehicle::can_use_rails() const
+{
+    bool can_use = true;
+    bool is_wheel_on_rail = false;
+    for( int part_index : wheelcache ) {
```
Comment (mlangsdorf) [inline src/vehicle.cpp]: consider caching the rail wheels in vehicle::refresh() so you'd have this instead:
```
    bool can_use = !railcache.empty();
￼     bool is_wheel_on_rail = false;
￼     for( int part_index : railcache ) {

File: src/vehicle_move.cpp [hunk 8]
```diff
@@ -1129,13 +1248,77 @@ bool vehicle::act_on_map()
         skidding = true;
     }
 
-    // Where do we go
+    bool allow_turn_on_rail = false;
+    if( can_use_rails ) {
```
Comment (mlangsdorf) [inline src/vehicle_move.cpp]: put this all in a separate function, please.

File: src/vehicle_move.cpp [hunk 9]
```diff
@@ -1009,6 +1011,121 @@ float get_collision_factor( const float delta_v )
...
+        dp.x = mdir.dx();
+        dp.y = mdir.dy();
+    }
+
+    // number of wheels that will land on rail
+    wheels_on_rail = 0;
+
+    int yVal = INT_MAX;
+    // is all wheels of vehicle on one axis?(bike)
+    all_wheels_on_one_axis = true;
```
Comment (mlangsdorf) [inline src/vehicle_move.cpp]: calculate and cache this in vehicle::refresh()

File: data/json/vehicleparts/wheel.json (hunk 6 above)
Comment (egorzaderiy) [reply data/json/vehicleparts/wheel.json]: Oh well, thats how i did it initially, but decided to simplify it. Even the names matched. Will fix

File: src/vehicle.cpp (hunk 7 above)
Comment (egorzaderiy) [reply src/vehicle.cpp]: So you suggest adding separated cache for rail wheels?

File: data/json/vehicleparts/wheel.json (hunk 6 above)
Comment (egorzaderiy) [reply data/json/vehicleparts/wheel.json]: Also I've chosen metal wheel because I saw it on Passenger Car on train vehicle, should I really create new wheel? What about previous then?

Comment (mlangsdorf) [reply data/json/vehicleparts/wheel.json]: yes, you should create the new wheel.
and you should update the vehicle prototypes to use it.

File: src/vehicle.cpp (hunk 7 above)
Comment (mlangsdorf) [reply src/vehicle.cpp]: yes.

File: src/vehicle_move.cpp (hunk 9 above)
Comment (egorzaderiy) [reply src/vehicle_move.cpp]: `yVal` can't be cached, it is used to calculate `turning_wheels_that_are_one_axis`

File: data/json/vehicleparts/wheel.json (hunk 6 above)
Comment (egorzaderiy) [reply data/json/vehicleparts/wheel.json]: I did that, but old metal_wheel is used only in some spawnlists. 
Also I don't understand how to correctly add penalties for moving on `ROAD`for example, I increase `{ "RAIL", 8 }` value, but it looks like nothing changes, it can go full speed on road. Meanwhile on rails it can go only slow. How to correctly do that?

File: src/vehicle_move.cpp (hunk 8 above)
Comment (egorzaderiy) [reply src/vehicle_move.cpp]: done

**Comment by egorzaderiy** [comment]
I've cached suggested variables, but can't think that else can be cached

File: src/veh_type.cpp [hunk 10]
```diff
@@ -228,8 +233,10 @@ void vpart_info::load_wheel( cata::optional<vpslot_wheel> &whptr, JsonObject &jo
     }
     assign( jo, "rolling_resistance", wh_info.rolling_resistance );
     assign( jo, "contact_area", wh_info.contact_area );
-    wh_info.terrain_mod = standard_terrain_mod;
-    wh_info.or_rating = 0.5f;
+    if( !jo.has_member( "copy-from" ) ) { // if flag presented, it is already set
+        wh_info.terrain_mod = standard_terrain_mod;
+        wh_info.or_rating = 0.5f;
+    }
```
Comment (egorzaderiy) [inline src/veh_type.cpp]: Fixed this weirdness when steerable wheels did't have correct `wheel_type`, because they are `copy-from` and it was reset to `standart` here. This also applies to all over wheels.

**Comment by kevingranade** [comment]
Please do commit your test vehicle.

**Comment by egorzaderiy** [comment]
> Please do commit your test vehicle.

Added two draisines - small and big, and motorcycle with rail wheels just for testing one-axis vehicles.
`Six-Seated Motorized Draisine`, `Two-Seated Motorized Draisine`, `Rail Motorcycle`

**Comment by Mecares** [comment]
One step closer to roller coasters and abandoned amusement parks. Cant wait for zombie clowns because regular are not scary enough.

**Comment by paulenka-aleh** [comment]
> Cant wait for zombie clowns because regular are not scary enough.

And the boss clown living in sewers

File: data/json/vehicles/trains.json [hunk 11]
```diff
@@ -124,5 +124,129 @@
...
+    "name": "Two-Seated Motorized Draisine",
+    "blueprint": [
+      [ "O-O" ],
+      [ "|#|" ],
+      [ "|X|" ],
+      [ "|#|" ],
+      [ "O-O" ]
+    ],
+    "parts": [
+      { "x": 0, "y": 1, "parts": [ "xlframe_vertical_2", { "part": "tank_small", "fuel": "gasoline" } ] },
```
Comment (mlangsdorf) [inline data/json/vehicles/trains.json]: Please use parts for the the rest of these entries:
```
{ "x": 0, "y": 0, "parts": [ "seat", "controls" ] },
{ "x": 0, "y": 1, "parts": [ "engine_vtwin", "alternator_motorbike", "battery_motorbike" }
```
it's up to you how much you want to compact them but there's no need to have a separate entry for each part.

File: src/mapgen_functions.cpp [hunk 12]
```diff
@@ -1245,58 +1245,60 @@ void mapgen_subway( map *m, oter_id terrain_type, mapgendata dat, const time_poi
...
-........................\n\
-D^....................^D\n\
-DD^..................^DD\n\
-^DD^................^DD^\n\
-^^DD^..............^DD^^\n\
-D^^DD^....####....^DD^^D\n\
-DD^^DD^..######..^DD^^DD\n\
-.DD^^DD^.######.^DD^^DD.",
-                                        mapf::ter_bind( ". # ^ D",
+..^/D^^/D^....^D/^^D/^..\n\
```
Comment (mlangsdorf) [inline src/mapgen_functions.cpp]:
```suggestion
                                           "..^/D^^/D^....^D/^^D/^..\n"
```
for this an every line afterwards - it looks nicer.

File: data/json/vehicles/trains.json (hunk 11 above)
Comment (egorzaderiy) [reply data/json/vehicles/trains.json]: eh i've used vehicleDef.py script to make templates, it produces lines like that

**Comment by ZhilkinSerg** [comment]
Once derailed it is not possible to move vehicle back to track:

image

**Comment by ZhilkinSerg** [comment]
Tracks are automatically changed on turns:

image

image

image

**Comment by ZhilkinSerg** [comment]
Vehicles derail pretty easily without obvious reasons.

**Comment by Night-Pryanik** [comment]
> Once derailed it is not possible to move vehicle back to track:

I think this is realistic.

**Comment by ZhilkinSerg** [comment]
> 
> 
> > Once derailed it is not possible to move vehicle back to track:
> 
> I think this is realistic.

Sure, I agree, but we should probably add possibility for cranes (or insanely strong characters with smaller vehicles) to put vehicles back on rails.

**Comment by Night-Pryanik** [comment]
I believe in this situation derailed vehicles won't be moving on its own (by dragging or else) and therefore won't be colliding with rails, so we could implement a special case handling such feature.
