### PR TITLE
Prevent endless deathcam loop when dying while asleep

### LINKED ISSUE #37977: Uninterrupted Sleep on Death
# Describe the bug

Freezing to death does not interrupt sleep.
When sleeping the game will display "Wait till you wake up...". This message is displayed even after the death of the character (i.e. by freezing to death). In the log the last few displayed messages are:
```
...
Your head hurts!
Your head hurts!
Your head hurts!
Your limb breaks!
```
At this point the game continues simulating the environment but does not allow the player to interrupt this process forcing them to kill the process with SIGINT/SIGKILL (SIGTERM is ignored).

# Steps To Reproduce

1. Create new character.
2. Take off all clothing
3. Sleep
4. Freeze to death and watch the simulation

# Expected behavior

After dying the usual prompt "Watch your last moments etc." should be displayed.

# Screenshots

ss

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.0; Distributor ID: VoidLinux; Description: Void Linux; Release: rolling; Codename: void; 
- Game Version: 0.D-12149-g7a3893221e-dirty [64-bit] (unrelated changes)
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Graphical Overmap [Graphical_Overmap],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context
When catching the common cold while sleeping the player wakes up due to coughing and does not die. Possibly ~a bug~ unexpected behaviour?

### PR DESCRIPTION
**Pull request by jkraybill**
#### Summary
```SUMMARY: Bugfixes "Prevent endless deathcam loop when dying while asleep"```

#### Purpose of change
Fixes #37977 by waking the character post-death in deathcam mode to prevent an endless deathcam loop.

#### Describe the solution
A dead sleeping character is woken up post-death in deathcam mode. This enables player input, which is what triggers the "Press ESC... to accept your fate" message and ability to exit deathcam.

#### Describe alternatives you've considered
I looked at moving the way the "ESC to end" input is taken upon deathcam but that looked a lot more complex and error-prone than just ending the sleep effect upon death.

#### Testing
Froze to death many times by spawning a blindfold and a couple codeine and taking off clothing in winter and sleeping with a blindfold on.

#### Additional context
The original bug report #37977 does not mention deathcam mode; it is possible that this is not a complete fix if there is some way to get in this state without entering deathcam mode. However I (nor others) could not repro outside of deathcam mode, and looking at the code I couldn't theorize how this could otherwise occur.

I do recommend awaiting some feedback from the OP on #37977 to confirm that deathcam could have been set to auto or inadvertently accepted.

### CODE REVIEW

**Comment by Qrox** [comment]
> I looked at moving the way the "ESC to end" input is taken upon deathcam but that looked a lot more complex and error-prone than just ending the sleep effect upon death.

Does changing the following line

https://github.com/CleverRaven/Cataclysm-DDA/blob/274c8d874a604572e4b7e3ffcd5d0ec79971f9b3/src/game.cpp#L1431

to the following work?

```
if( !u.has_effect( efftype_id( "sleep" ) ) || uquit == QUIT_WATCH ) {
```

**Comment by jkraybill** [comment]
@Qrox much more elegant, thanks!

File: src/game.cpp [hunk 1]
```diff
@@ -1428,7 +1428,7 @@ bool game::do_turn()
         sfx::do_hearing_loss();
     }
 
-    if( !u.has_effect( efftype_id( "sleep" ) ) ) {
+    if( ( !u.has_effect( efftype_id( "sleep" ) ) || uquit == QUIT_WATCH ) ) {
```
Comment (BevapDin) [inline src/game.cpp]:
```suggestion
    if( !u.has_effect( efftype_id( "sleep" ) ) || uquit == QUIT_WATCH ) {
```

Comment (jkraybill) [reply src/game.cpp]: Thanks!
