### PR TITLE
Characters have actual volume, sane-ify sane-ified vehicle size checks. Enforce with unit tests

### LINKED ISSUE #74068: Cramped space. Incorrect volume calculation?
### Describe the bug

Standard character. Completely naked. Sits in a normal car and gets this effect.

It should not be like this. My assumption is that the calculation of character volume or free space is not done correctly.

### Attach save file

[Бивис-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/15442114/-trimmed.tar.gz)

### Steps to reproduce

Create a character and get in the car.

### Expected behavior

Lack of effect, for a normal character on a normal car.

### Screenshots

pict 1

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043 (21H1)
- Game Version: cdda-experimental-2024-05-25-0347 388ca6c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Additionally looked at how this effect would react to starvation. Set it to 15k cal (skeletal). The effect didn't go anywhere.

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
None

#### Purpose of change
Fixes #74068

Please stop pinging me. Yes I saw the first one

#### Describe the solution
Give characters actual volume

Remove pain from cramped space

Completely different volume calculation for characters, not related to monster calculation

(this is a big one)

--- >**Character volume includes carried volume, including their weapon** < ---

(big one up above!)

Flip an oopsie greater than

Embrace testing, testing is good

#### Describe alternatives you've considered
*Revert*?

#### Testing
~~my own unit test is currently failing.~~ it passes now

#### Additional context
Character size to volume is based on height, but here is a (better) graph plotted to the average heights for each size class:

image

**Note:** There still might be some json weirdness where volumes don't match up to what is 'expected'. I would expect some seats to be cramped, this is intended. Cramped space no longer gives pain and a penalty to fighting inside a restricted vehicle space makes sense to me. So yes, if you can't swing your broadsword 100% effectively from the driver's seat that is intended behavior.

If you find a vehicle part that looks wrong, please feel free to PR a fix. I did not exhaustively review each and every cargo vehicle part.

### CODE REVIEW

**Comment by fairyarmadillo** [comment]
I spent a long time trying to get power armor to stop people from fitting through windows and sitting comfortably in compact cars, but every fix I tried wound up messing with BMI and calorie requirements. If this actually makes the player feel like they're wearing T-60 power armor (including making them big enough to use knockdown techs on huge enemies) that will be completely awesome.

**Comment by Alm999** [comment]
Volume based on height is great, but what if my character is "Morbidly Obese" as well (e.g. "Weight XXXL" starting trait)?

**Comment by Vgoloshivskiy** [comment]
Can't wait until this get merged. will you be unable to use Mech suits / Combat Exosceletons designed for normal sized people with this?

File: src/character.cpp [hunk 1]
```diff
@@ -3090,6 +3090,27 @@ void Character::on_move( const tripoint_abs_ms &old_pos )
     }
 }
 
+units::volume Character::get_total_volume() const
+{
+    item_location wep = get_wielded_item();
+    units::volume wep_volume = wep ? wep->volume() : 0_ml;
+    // Note: Does not measure volume of worn items that do not themselves contain anything
+    return get_base_volume() + volume_carried() + wep_volume;
```
Comment (Procyonae) [inline src/character.cpp:3098]: volume_carried() here doesn't seem appropriate, unless I'm reading it wrong wearing a giant empty rucksack counts as 0, while a snack bar in my jeans pocket apparently makes the space I'm in more cramped?

Comment (RenechCDDA) [reply src/character.cpp:3098]: That is the intention. Using worn clothes' volume would be wildly inappropriate, since (depending on the clothing in question) it would add negligible amounts of volume to your person. A wetsuit is 5L, but it's definitely not going to add 5L of *volume* to your person when being worn.

There is room for more nuance here, like separating out rigid and non-rigid items and materials.

**Comment by RenechCDDA** [comment]
> Volume based on height is great, but what if my character is "Morbidly Obese" as well (e.g. "Weight XXXL" starting trait)?

There is no difference in volume calculation based on body fat. I tried reading up on it but calculating that turns out to be "it's complicated" and varies greatly depending on age and sex. If you are interested in adding this, I recommend `Determination of human body volume from height and weight, authored by JULIUS SENDROY, JR. AND HAROLD A. COLLISON`

File: src/character.cpp (hunk 1 above)
Comment (Procyonae) [reply src/character.cpp:3098]: volume_carried() is wildly inappropriate too imo

Comment (RenechCDDA) [reply src/character.cpp:3098]: How? If you're carrying a 500L fridge and you try to step into a vehicle it's... just not gonna work? Same thing if you're wearing a huge box backpack.

Comment (Procyonae) [reply src/character.cpp:3098]: > Same thing if you're wearing a huge box backpack.

volume_carried() doesn't count that as volume unless it's full which was my original point...

Comment (RenechCDDA) [reply src/character.cpp:3098]: It does? In the tests we use a giant novelty backpack with 80L of volume capacity. Putting it on and putting a 10L rock into it causes an open tile to become cramped for movement purposes. It increases the character's volume from 70L to above 75L (where the aisle starts being cramped). If it counted the full 80L then our total volume would be 70+80 = 150L, and we couldn't move through the aisle at all. But we can, and it's just cramped.

Comment (Procyonae) [reply src/character.cpp:3098]: That's my point... the novelty backpack should be counting the full 80L (or whatever volume takes up when empty) bc it's not surrounding the player like a wetsuit. At the very least you should be counting BELTED stuff.
It's also pretty silly that like a flak jacket with plates would count the plates volume but an empty power armour suit wouldn't count as anything.
