### PR TITLE
Replaced is_wearing check with is_worn when an item is thrown

### LINKED ISSUE #47044: Can’t throw clothes if already wearing another item of the same kind
# Describe the bug
Character can't throw item, e.g. hip flask, if wearing same kind of item, e.g. another hip flask. Message displayed on attempt to throw item: “You are not wearing that item”.

# Steps To Reproduce
1. Get two wearable items, e.g. 2 hip flasks or 2 wrist watches
2. Wear one of items
3. Wield other item
4. Throw wielded item (by throw hotkey, or via inventory - item - menu - throw)

Actual result: Message displayed on attempt to throw item: “You are not wearing that item”. Game is not switched to throw targeting mode
Note: after dropping item which was on a character, it is possible to throw wielded item.

# Expected behavior
Game should be switched to throw targeting mode on "throw" command. 
User should be able to throw item regardless of character wearing another item of the same kind or not.

# Screenshots
N/A

# Versions and configuration
Platform : Windows_x64
Graphics : Tiles
Build number : #11388
Build version: 0.E-9111-gd1e702b
Major version: 0.E
Mods loaded: default mods (IIRC: dark days ahead, disable NPC needs, bionic professions)

# Additional context
N/A

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary

SUMMARY: Bugfixes "Fixed problem with item identification when throwing"

#### Purpose of change

Character::is_wearing() was only taking an itype_id and as a result wasn't able to differentiate between instances of the same item

Fixes #47044

#### Describe the solution

replaced the check of is_wearing() with is_worn()

#### Testing

Spawn in two items that can be worn (i used hipflasks like the noted issue)
Wear one
try to throw the other one

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -3957,6 +3957,16 @@ bool Character::is_wearing( const itype_id &it ) const
     return false;
 }
 
+bool Character::is_wearing( const item &it ) const
```
Comment (Qrox) [inline src/character.cpp:3960]: There's `Character::is_worn` in `character.h` with exactly the same function.

Comment (Jamuro-g) [reply src/character.cpp:3960]: thank you, testing it right now ... i ll swap the call out to is_worn and remove the new method

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/cant-throw-clothes-if-already-wearing-another-item-of-the-same-kind/25782/5

**Review by BrettDong — APPROVED** [review]
