### PR TITLE
Chapters are Character-mapped for unique books

### LINKED ISSUE #77920: Books stored in smartphone are new instances of the book type
### Describe the bug

When player reads books, the books lose charge equal to its ability to boost player's status effectively (chapters are read and player knows them so they're not new and interesting anymore). When a book is stored in a smartphone, the copy stored doesn't reflect this, as if it was a different book with different chapters.

### Attach save file

N/A

### Steps to reproduce

1. Store a book into a smartphone.
2. Read a chapter of the physical copy.
3. Check read menu, there's a difference between the physical copy and the smartphone version - the digital copy didn't lose a chapter.

### Expected behavior

Reading a chapter from the book reads the chapter from all its copies.

### Screenshots

_No response_

### Versions and configuration

OS: Windows 10 Pro 64-bit 22H2 19045.5131
Game Version: 0f2c155 (tiles)
build 2024-11-15-0512
Ingame Language: Enskt

### Additional context

Or is it like when playing games on different platforms is a different experience? :)

### PR DESCRIPTION
**Pull request by ShnitzelX2**
#### Summary
Bugfixes "chapters are character-mapped for unique books"

#### Purpose of change

Closes #77920

As explained in above issue, books can be copied indefinitely for infinite fun.

#### Describe the solution

Chapters read for each book itype are mapped per-Character instead of per-item *unless* `"generic": true` is added to a book specifying it as a type of book rather than a specific title (e.g. `book of essays`)

#### Testing

Read a copy of Dune, noted that another copy had same "chapters read"
Read a (generic = true) Playboy until all the charges were gone, noted a new copy had 4 chapters still left

Read a manual to make sure it still worked

#### Additional context

Not that it explains much, but you can see the copies of Dune I've read have the same chapters read and the other generic books don't:
image

### CODE REVIEW

File: src/character.h [hunk 1]
```diff
@@ -2313,6 +2313,7 @@ class Character : public Creature, public visitable
         /** Calculates the total fun bonus relative to this character's traits and chapter progress */
         bool fun_to_read( const item &book ) const;
         int book_fun_for( const item &book, const Character &p ) const;
+        mutable std::map<itype_id, int> book_chapters;
```
Comment (moxian) [inline src/character.h:2316]: why is this marked as `mutable`? I think it would be better to change `item::mark_chapter_as_read` to not accept `const Character&` instead?

Separately, please add a short comment noting that it represents the amount of chapters *remaining* in a given book, (and not the amount *read* as I originally assumed)

**Review by moxian — CHANGES_REQUESTED** [review]
Please document the newly added `generic` field in .md somewhere 

More importantly, I'm not very familiar with our save handling, but the lack of explicit de-/serialization of the newly added `Character::book_chapters` makes me think that this info would be lost after a save-load cycle? Can you please double-check that this part works?

**Comment by ShnitzelX2** [comment]
So I've fixed:

> document the newly added generic field in .md 

> de-/serialization of the newly added Character::book_chapters

> marked as mutable

> please add a short comment noting that it represents the amount of chapters remaining in a given book

> linked issue being present for generic books

Great reviews, thanks. Double-check if you'd like.

File: src/character.h [hunk 2]
```diff
@@ -2313,6 +2313,7 @@ class Character : public Creature, public visitable
         /** Calculates the total fun bonus relative to this character's traits and chapter progress */
         bool fun_to_read( const item &book ) const;
         int book_fun_for( const item &book, const Character &p ) const;
+        std::map<itype_id, int> book_chapters;
```
Comment (moxian) [inline src/character.h:2316]: I'd still like to see a comment here on semantics (whether it's chapters read or chapters remaining).
Or perhaps rename the field to `book_chapters_remain` or something.

Looks good otherwise 👍

**Review by moxian — APPROVED** [review]
Uh.. do i need to press this approve button here? Still not quite sure how github reviews work, apologies

File: src/character.h (hunk 2 above)
Comment (ShnitzelX2) [reply src/character.h:2316]: oh, that got left on another branch, I'll add it back in
