### PR TITLE
Fix using a null item in target_handler::target_ui

### LINKED ISSUE #35434: Segmentation fault when switching firing modes in a vehicle using multiple turrets
# Describe the bug

Game crashes when pressing s to switch firing mode (semi-auto to auto) while targeting a turret in a vehicle with multiple turrets

# Steps To Reproduce

1. Load attatched save
2. press e,5,v,T,1,s (in other words, aim the avalange turret and when it targets something, press s to switch firing modes
3. observe crash

# Expected behavior
Switch firing mode of the avalange rifle from semi auto to auto

# Screenshots
image

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-9280-g86b3adc [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Makeshift Items Mod [makeshift],
    Mining Mod [Mining_Mod],
    Folding Parts pack [deoxymod],
    Simplified Nutrition [novitamins],
    Magiclysm [magiclysm],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Garden Pots [growable-pots],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    Hydroponics [hydroponics],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Bens GF recipes [Tolerate_This],
    Icecoon's Arsenal [ew_pack],
    Cataclysm++ [Cata++],
    Urban Development [Urban_Development],
    Mythological Replicas [nw_pack],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs]
]
win8.1

# Additional context
[crash-and-debug-log.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3827936/crash-and-debug-log.zip)

save file:
https://ufile.io/lrp60s7y

### PR DESCRIPTION
**Pull request by BevapDin**
```SUMMARY: None```

Basically if the function was not given a valid pointer, it would just use `g->u.weapon`, which is often a null item (not wielding anything is required to fire a vehicle turret). In turn, some functions got called with that null item and some of them blindly assumes it will be a gun item and simply crashed when it wasn't.

Fixes #35434.

### CODE REVIEW

File: src/ranged.cpp [hunk 1]
```diff
@@ -1324,8 +1323,9 @@ std::vector<tripoint> target_handler::target_ui( player &pc, target_mode mode,
         aim_mode = aim_types.begin();
     }
 
-    int num_instruction_lines = draw_targeting_window( w_target, relevant->tname(),
-                                mode, ctxt, aim_types, tiny );
+    // @TODO this assumes that relevant == null means firigin turrets, but that may not
```
Comment (Night-Pryanik) [inline src/ranged.cpp]:
```suggestion
    // @TODO this assumes that relevant == null means firing turrets, but that may not
```

File: src/ranged.cpp [hunk 2]
```diff
@@ -1427,7 +1427,9 @@ std::vector<tripoint> target_handler::target_ui( player &pc, target_mode mode,
             if( !compact ) {
                 line_number++;
             }
-            if( mode == TARGET_MODE_FIRE || mode == TARGET_MODE_TURRET_MANUAL ) {
+            // Assumes that relevant == null means firing turrets (maybe even multiple at once),
+            // so printing their firing mode / ammo / ... of one of them is missleading.
```
Comment (Night-Pryanik) [inline src/ranged.cpp]:
```suggestion
            // so printing their firing mode / ammo / ... of one of them is misleading.
```

File: src/ranged.cpp [hunk 3]
```diff
@@ -1470,7 +1472,9 @@ std::vector<tripoint> target_handler::target_ui( player &pc, target_mode mode,
                           c_red, '*' );
             }
 
-            if( mode == TARGET_MODE_FIRE ) {
+            // Assumes that relevant == null means firing turrets (maybe even multiple at once),
+            // so printing their firing mode / ammo / ... of one of them is missleading.
```
Comment (Night-Pryanik) [inline src/ranged.cpp]:
```suggestion
            // so printing their firing mode / ammo / ... of one of them is misleading.
```
