### PR TITLE
Fix segfault when starting fire and losing item

### LINKED ISSUE #49100: Crash while lighting fire
# Describe the bug

While using a matchbook on a specific gas pump to light a fire the game segfaults. The game segfaults before the fire is lit.

# Steps To Reproduce

1. Open the attached save.
2. Activate the partially used matchbook on the gas pump next to the player
3. Press `I` a few times to ignore the zombies attacking you
4. Experience the segfault (it happens 75% of the time, try lighting it again if it doesn't work)

# Expected behavior

The gas pump catches on fire without a crash.

# Versions and configuration

I'm on commit 7bd98499abf2374a37e4fd32036f91b1f3c67a0d, on the tiles version of the game. In-game language is english and the loaded mods are whatever's stock.

# Additional context

I spun up `gdb` to try to figure out what's going wrong. Here's the backtrace:
```
#0  item::is_gun (this=this@entry=0x0) at /home/uelen/build/Cataclysm-DDA/src/item.cpp:6752
#1  0x000055555633dd7b in item::has_flag (this=this@entry=0x0, f=...)
    at /home/uelen/build/Cataclysm-DDA/src/item.cpp:5551
#2  0x0000555555b2a718 in activity_handlers::start_fire_do_turn (act=0x5555581acda8, p=0x5555581ac910)
    at /home/uelen/build/Cataclysm-DDA/src/activity_handlers.cpp:1988
#3  0x0000555555b53a0a in std::__invoke_impl<void, void (*&)(player_activity*, player*), player_activity*, pla
yer*> (__f=<optimized out>) at /usr/include/c++/11.1.0/bits/invoke.h:61
#4  std::__invoke_r<void, void (*&)(player_activity*, player*), player_activity*, player*> (
    __fn=<optimized out>) at /usr/include/c++/11.1.0/bits/invoke.h:154
#5  std::_Function_handler<void (player_activity*, player*), void (*)(player_activity*, player*)>::_M_invoke(s
td::_Any_data const&, player_activity*&&, player*&&) (__functor=..., __args#0=<optimized out>,
    __args#1=<optimized out>) at /usr/include/c++/11.1.0/bits/std_function.h:291
#6  0x0000555555b92a04 in std::function<void (player_activity*, player*)>::operator()(player_activity*, player
*) const (__args#1=<optimized out>, __args#0=<optimized out>, this=<optimized out>)
    at /usr/include/c++/11.1.0/bits/std_function.h:560
#7  activity_type::call_do_turn (this=<optimized out>, act=act@entry=0x5555581acda8,
    p=p@entry=0x5555581ac910) at /home/uelen/build/Cataclysm-DDA/src/activity_type.cpp:109
#8  0x0000555556cafa53 in player_activity::do_turn (this=0x5555581acda8, p=...)
#9  0x000055555610c858 in game::process_activity (this=this@entry=0x5555581ac1d0)
    at /home/uelen/build/Cataclysm-DDA/src/game.cpp:1699
#10 0x000055555617869e in game::do_turn (this=0x5555581ac1d0)
    at /home/uelen/build/Cataclysm-DDA/src/game.cpp:1474
#11 0x0000555555a99319 in main (argc=<optimized out>, argv=<optimized out>)
    at /usr/include/c++/11.1.0/bits/unique_ptr.h:173
```

 In `src/activity_handlers.cpp`, on line 1987, `*act->targets.front()` seems to return null, and sets `firestarter` to null. It causes a subsequent crash in `item::is_gun()` in `item::has_flag()`. My cpp debugging skill isn't great so I can't figure out the root cause of this though, unfortunately.

Here's the save:
[save.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/6567318/save.tar.gz)

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6567334/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/6567335/debug.log)

### PR DESCRIPTION
**Pull request by waylon531**
#### Summary
Bugfixes "Fix a segfault when starting a fire and losing your firestarter"

#### Purpose of change

Sometimes, when losing your firestarter while starting a fire, the game
will segfault. This appears to be caused by the item* in the item_location
for the firestarter getting set to null. This pointer gets cast into a reference in the existing code and causes a segfault when you call any method on it.

Fixes #49100

#### Describe the solution

This patch adds a check to see if the item pointer is null before trying to use it, and cancels the firestarting process if it is null.

#### Describe alternatives you've considered

It might be possible to stop `item_location`s from casting a null pointer to a reference when they're returning an `item`, but I really don't understand the codebase well enough to attempt this.

#### Testing

I was able to test this patch out on my savefile from when I reported this bug. The issue seems to be fixed.

### CODE REVIEW

**Comment by actual-nh** [comment]
It would be very nice to have this in 0.F, but the added string (unless it's found someplace else?) makes it under String Freeze (giving the translators a chance to catch up).

**Comment by waylon531** [comment]
That string is actually a duplicate of another string in the same function. There's an original lost item check being performed in this function, which is where the string originally was, but it doesn't catch the case I encountered. I would have refactored it all into one single check but there isn't any easy/good way to.

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -1984,6 +1984,18 @@ void activity_handlers::start_fire_do_turn( player_activity *act, player *p )
         }
     }
 
+    // Sometimes when an item is dropped it causes the whole item* to get set to null.
+    // This null pointer gets cast to a reference at some point, causing UB and 
+    // segfaults. It looks like something is supposed to catch this, maybe 
+    // get_safe_reference in item.cpp, but it's not working so we check for a 
+    // null pointer here.
+    //
```
Comment (BrettDong) [inline src/activity_handlers.cpp:1992]: Some trailing spaces are causing `astyle` error:
```suggestion
    // Sometimes when an item is dropped it causes the whole item* to get set to null.
    // This null pointer gets cast to a reference at some point, causing UB and
    // segfaults. It looks like something is supposed to catch this, maybe
    // get_safe_reference in item.cpp, but it's not working so we check for a
    // null pointer here.
    //
```
