### PR TITLE
Prevent monsters from dragging people in seatbelts, fix dragged players getting run over by their own cars

### LINKED ISSUE #22764: Grapplers pulling out of a 5 point harness
Game version: 0.C-25577

Operating system: Windows 7

Tiles or curses: Tiles

Mods active:
Dark Days ahead
filthy clothing
disable npc needs
simplified nutrition
makeshift items
more survival tools
alternative map key
folding parts pack
vehicle additions pack
tanks and other verhicles

### Expected behavior
Grappler zombie grabbing me at 40mph in 5-point harness should either have it's arms dislocated (take damage), or be dragged along with me.  Either way I should stay in the seat.

### Actual behavior
Magically pulls me out of the vehicle while taking no damage

### Steps to reproduce the behavior
On Powerbike (design like motorcycle, but with car parts, including full seat, 5-point harness, and v4 engine)
At 40mph
Pass grappler zombie
Die

### PR DESCRIPTION
**Pull request by Ilysen**
#### Summary
Bugfixes "Players can no longer be dragged while in a vehicle with a seatbelt; dragged players will not be run over by their own vehicles while still inside of them"

#### Purpose of change

This has been a bit of a long-standing issue and it has two symptoms:
1. The first symptom - monsters being able to drag people even if they're wearing a seatbelt or 5-point harness - just exists because there's no check to see if the player is in such a tile.
2. The second symptom - dragged players being splattered by their own cars while still inside them - is caused because the game unboards the player from their vehicle, but both lacks checks to make sure the player will still be inside the vehicle before doing the drag, and lacks a check that re-boards the player onto the vehicle after being dragged, causing them to be considered outside the vehicle and thus being ran over.

Fixes #22764

#### Describe the solution

`mattack::ranged_pull` and `mattack::grab_drag` now check to see if the player is in a vehicle, and if so, the player resists the attack if the tile they're on has a part with the `SEATBELT` flag. This will apply a small amount of damage to both the player and the monster, to simulate being crushed against the seat and having their arms strained very intensely respectively.

Additionally, immediately after the player is moved (which happens after they're unboarded from the vehicle), the game will check if there's a vehicle on their new tile, and if that tile also has a boardable part, the player will automatically board the vehicle.

#### Describe alternatives you've considered

Losing more runs. :P

In all seriousness, there's a few possible things that could be done to fix this. Checks could be done to make sure that the player will no longer be outside the vehicle before allowing them to be unboarded, but I struggled to make this work since my C++ skills are pretty shoddy. Additionally, I had considered only having characters controlling vehicles to be considered wearing a seatbelt, but I believe this would not account for NPCs riding in the car that would presumably have their seatbelts on, so I ended up opting against it.

#### Testing

1. Get a vehicle and open the trunk door. Take control of it, but don't start driving yet.
2. Spawn a grappler zombie or another creature with the mentioned attacks. Let it enter the trunk.
3. Start driving and keep going until the monster uses its attacks.
4. See that it's resisted by having a seatbelt. You'll both take some minor damage.
5. Repeat steps 1-3, but have no seatbelts in the car. You will be dragged away from the controls.
6. Pass time. The car will continue driving and spin out of control, but you won't be run over by your own vehicle anymore due to still being inside of it. You'll instead keep traveling with the vehicle.

#### Known issues

This PR does ***not*** fix an existing bug in which `map::unboard_vehicle` throws an error when the player is dragged out of a vehicle that they're currently inside of and onto open ground. I tried debugging this for about an hour and made no progress in fixing it. As a result of the PR fixing a different bug that unboarded the player from their vehicle when they were dragged at all, this bug is now more visible because it can happen much more often. The error message is harmless, but that's still a problem; please let me know if you might have any ideas as to how to fix that.

#### Additional context

image

### CODE REVIEW

File: src/monattack.cpp [hunk 1]
```diff
@@ -2962,16 +2985,27 @@ bool mattack::grab_drag( monster *z )
         return false;
     }
 
+    const optional_vpart_position veh_part = get_map().veh_at( target->pos() );
+    if( foe->in_vehicle && veh_part ) {
+        const cata::optional<vpart_reference> vp_seatbelt = veh_part.avail_part_with_feature( "SEATBELT" );
+        if( vp_seatbelt ) {
+            target->add_msg_player_or_npc( m_good, _( "%1s tries to drag you, but is stopped by your %2s!" ),
```
Comment (NetSysFire) [inline src/monattack.cpp:2992]: You are using three different colors for the same action, `m_good` (green), `m_info` (blue) and `m_warning` (yellow) as far as I can see. I would get rid of one of them, potentially `m_good`. Being dragged unsuccessfully is still most definitely a cause of concern because there is danger nearby, so neutral (`m_info`) seems the most appropriate here.

Comment (Night-Pryanik) [reply src/monattack.cpp:2992]: There is `m_mixed` exactly for these kind of situations.

Comment (NetSysFire) [reply src/monattack.cpp:2992]: Good point.

Comment (Ilysen) [reply src/monattack.cpp:2992]: I've actually used these message spans due to the existing messages for the attacks using them as well; they're kinda all over the place in normal `grab_drag` too. Should I change em there too?

File: src/monattack.cpp [hunk 2]
```diff
@@ -2770,6 +2773,20 @@ bool mattack::ranged_pull( monster *z )
...
 
+    const optional_vpart_position veh_part = here.veh_at( target->pos() );
+    if( foe->in_vehicle && veh_part ) {
+        const cata::optional<vpart_reference> vp_seatbelt = veh_part.avail_part_with_feature( "SEATBELT" );
+        if( vp_seatbelt ) {
+            z->moves -= 200;
+            game_message_type msg_type = foe && foe->is_avatar() ? m_warning : m_info;
+            target->add_msg_player_or_npc( msg_type, _( "%1s tries to drag you, but is stopped by your %2s!" ),
+                                           _( "%1s tries to drag <npcname>, but is stopped by their %2s!" ),
+                                           z->disp_name( false, true ), vp_seatbelt->part().name() );
```
Comment (kevingranade) [inline src/monattack.cpp:2784]: This needs to deal some damage instead of just being nullified.  It can go to both the attacker and the target.

Comment (Ilysen) [reply src/monattack.cpp:2784]: mmkay. in the next commit, I'll make it do some torso damage (to simulate being crushed/squeezed against the belt/seat/whatever) in addition to the message span stuff mentioned in the earlier comments.

**Comment by Ilysen** [comment]
made some changes. I opted to use two messages instead of one - the first to show that the player isn't dragged, and the second to place emphasis on the damage being caused by that attempt to drag - but mostly because I couldn't figure out an elegant way to highlight it in one message. totally open to suggestions to make that happen, though.
