### PR TITLE
Fix null tools

### LINKED ISSUE #16751: Tool containing a null
I killed a zombie and it dropped a curved needle that had "seeing this is a bug" below its own description.

I saved the game and checked the save to see what's going on and in the save, the needle had a null item (item with id "null") as its contents. This didn't change when I unloaded the needle.

That may be the cause of unusable tools described on forums. Tools with contents will not be used as components and possibly as tools either (cans with contents can't be used to boil water).

Tagging as magazine because it is clearly associated with changes to magazine system.

### PR DESCRIPTION
**Pull request by mugling**
Inspired by #17025 and fixes #16751. Tried submitting a PR for @Coolthulhu's repository but can't get it to work.
- a650e6d is @Coolthulhu's migration for existing bugged saves
- d372d16 stops items with integral magazines spawning with a `null` magazine when `with_ammo`
- 4fe7f75 incidentally increases the robustness of `item::ammo_set`

### CODE REVIEW

File: src/savegame_json.cpp [hunk 1]
```diff
@@ -1491,6 +1491,11 @@ void item::io( Archive& archive )
         // only for backward compatibility (nowadays mode is stored in item_vars)
         gun_set_mode(mode);
     }
+
+    // Fixes #16751
```
Comment (Coolthulhu) [inline src/savegame_json.cpp]: Would be better if it described the bug, such as "Fixes bugged saves with tools containing nulls"

**Comment by Coolthulhu** [comment]
It may be worth adding a `is_null` check in the emplace function (and debugmsg on null) to prevent it happening later on.

**Comment by mugling** [comment]
@Coolthulhu I did consider this. Is it likely to prove a performance concern?

**Comment by Coolthulhu** [comment]
No, `is_null` check is at worst a string comparison, `emplace( item )` is an order of magnitude more expensive.

**Comment by mugling** [comment]
@Coolthulhu see d001e67. We can't back out of adding a null item due to the return of a reference but we can add a `debugmsg`
