### PR TITLE
"rows" is defaulted to just spaces

### LINKED ISSUE #72511: Palettes containing parameters shouldn't be skipped regardless of whether rows is specified
### Describe the bug

The "palettes" member is skipped when "rows" is unspecified which leads to having to define empty rows like the example below which cause bloat to an otherwise nice method of simplifying mapgen and reducing bloat where palette parameters are required for nest placement.

```
  {
    "type": "mapgen",
    "method": "json",
    "om_terrain": "derelict_property",
    "//": "rows only defined because otherwise palettes, needed for parameter selection, throws a skipped member error",
    "object": {
      "rows": [
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        ",
        "                        "
      ],
      "fallback_predecessor_mapgen": "forest",
      "palettes": [ "derelict_variant_parameter_palette" ],
      "place_nested": [ { "chunks": [ { "param": "variant", "fallback": "derelict_property_1" } ], "x": 0, "y": 0 } ]
    }
  },
```

### Attach save file

N/A

### Steps to reproduce

Remove "rows" from "derelict_property"
Open game
Get skipped member error

### Expected behavior

Remove "rows" from "derelict_property"
Open game
Everything peachy

### Screenshots

_No response_

### Versions and configuration

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Procyonae**
#### Summary
None

#### Purpose of change

Fixes #72511

#### Describe the solution

If "rows" isn't provided a row of the expected size of just spaces is used every time one is expected
Removes existing blank "rows" no longer needed

#### Testing

Compiles and seems to work

#### Additional context

Most of the c++ change shown is just whitespace idk why git is highlighting the whole thing

### CODE REVIEW

**Comment by GuardianDll** [comment]
could you remove this thing also?
https://github.com/CleverRaven/Cataclysm-DDA/blob/dd4e109b2a0a7085dc3b51cb76aca2a0ea0bce55/data/json/mapgen/debug.json#L8-L33

**Comment by Maleclypse** [comment]
I think Flexbuffers is an akrieger word

File: src/mapgen.cpp [hunk 1]
```diff
@@ -4479,59 +4468,87 @@ bool mapgen_function_json_base::setup_common( const JsonObject &jo )
...
+
+    if( palette.keys_with_terrain.empty() && !fallback_terrain_exists ) {
+        return false;
+    }
+
+    parameters = palette.get_parameters();
+
+    for( int c = m_offset.y; c < expected_dim.y; c++ ) {
+        const std::string row = parray.get_string( c );
+        static std::vector<std::string_view> row_keys;
```
Comment (akrieger) [inline src/mapgen.cpp:4502]: It might end up simpler to do something like this.
```suggestion

    std::function<std::string(int)> get_row;
    std::function<void(std::string)> json_error;
    ...
    if ( jo.has_array( "rows" ) ) {
        parray = jo.get_array( "rows" );
        if( static_cast<int>( parray.size() ) < expected_dim.y ) {
            parray.throw_error( 
                string_format( "format: rows: must have %d rows, not %d; check mapgensize if applicable", total_size.y, parray.size() ) );
        get_row = [&]( int i ) {
          return parray.get_string( i );
        };
        json_error = [&]( std::string error ) {
          parray.string_error( error );
        }
    } else {
        // Construct default "rows" of just spaces
        const std::string spaces( expected_dim.x, ' ' );
        get_row = [=](int) {
          return spaces;
        };
        json_error = [](std::string error) {
          // won't happen.
        };
    }

    // just like mapf::basic_bind("stuff",blargle("foo", etc) ), only json input and faster when applying
    mapgen_palette palette = mapgen_palette::load_temp( jo, "dda", context_ );
    auto &keys_with_terrain = palette.keys_with_terrain;
    mapgen_palette::placing_map &format_placings = palette.format_placings;

    if( palette.keys_with_terrain.empty() && !fallback_terrain_exists ) {
        return false;
    }

    parameters = palette.get_parameters();

    for( int c = m_offset.y; c < expected_dim.y; c++ ) {
        const std::string row = parray.get_string( c );
        static std::vector<std::string_view> row_keys;
```

File: src/mapgen.cpp [hunk 2]
```diff
@@ -4489,14 +4489,22 @@ bool mapgen_function_json_base::setup_common( const JsonObject &jo )
...
         if( row_keys.size() != static_cast<size_t>( total_size.x ) ) {
-            parray.throw_error(
-                string_format( "  format: row %d must have %d columns, not %d; check mapgensize if applicable",
-                               c + 1, total_size.x, row_keys.size() ) );
+            if( !default_rows ) {
+                parray.throw_error(
+                    string_format( "format: row %d must have %d columns, not %d; check mapgensize if applicable",
+                                   c + 1, total_size.x, row_keys.size() ) );
+            } else {
+                jo.throw_error( "Defaulted rows somehow used the wrong number of rows!" );
```
Comment (akrieger) [inline src/mapgen.cpp:4506]: Same.

File: src/mapgen.cpp [hunk 3]
```diff
@@ -4508,19 +4516,26 @@ bool mapgen_function_json_base::setup_common( const JsonObject &jo )
...
+            }
+            if( !has_terrain && !has_placing && key.str != " " && key.str != "." ) {
+                try {
+                    if( !default_rows ) {
+                        parray.string_error(
+                            c, i + 1,
+                            string_format( "format: rows: row %d column %d: '%s' has no terrain, furniture, or other definition",
+                                           c + 1, i + 1, key.str ) );
+                    } else {
+                        jo.throw_error( "Defaulted rows somehow has a non ' ' character!" );
```
Comment (akrieger) [inline src/mapgen.cpp:4537]: Same.

**Review by akrieger — APPROVED** [review]

**Comment by I-am-Erk** [comment]
Oh, nice
