### PR TITLE
Fix ammo's charge being reduced when calculating reload move_points

### LINKED ISSUE #64543: Items with charges disappear when moving certain amount to personal inventory
### Describe the bug

Moving a certain amount of an item with charges to personal inventory makes half of the amount disappear.

### Attach save file

N/A

### Steps to reproduce

1. Spawn item with charges
2. Move an amount of the item to inventory
3. Half of the amount of moved item disappears

### Expected behavior

Expect to move specified amount and not disappear

### Screenshots

_No response_

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: HUAWEI; Model: DBY-W09; Release: 10; Incremental: 102.0.0.275C185; 
- Game Version: 71d3982 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills]
]

### Additional context

Moving the whole stack works properly, as well as moving between containers. Seems like only personal inventory is affected.

### LINKED ISSUE #64552: segfault when reloading an item
### Describe the bug

I had this bug twice or thrice between yesterday and 2 days ago, but only now i managed to get a 100% reproduction rate save.

The game just segfaults when i'm reloading my tailor kit, unfortunately i don't know more this time

### Attach save file

[Emerald Lake Hills-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11068455/Emerald.Lake.Hills-trimmed.tar.gz)

### Steps to reproduce

1 load save
2 hit "reload" button
3 select the tailor kit and hit enter
4 game should segfault

### Expected behavior

reload action being executed succesfully and no crash 

### Screenshots

_No response_

### Versions and configuration

Windows 10
build 2023-03-25-0547 msvc
Tiles
English
mods:
[
  "dda",
  "no_npc_food",
  "no_fungal_growth",
  "Tamable_Wildlife",
  "stats_through_kills",
  "speedydex",
  "package_bionic_professions",
  "blazeindustries",
  "rub_reb",
  "No_Person",
  "extra_mut_scens",
  "MMA",
  "translate_dialogue",
  "No_Rail_Stations"
]

### Additional context

_No response_

### LINKED ISSUE #64588: Ammo disappears when attempting to reload a magazine
### Describe the bug

More specifically: 
When opening the reload menu to reload a magazine with ammo that is not in the inventory, a portion of that ammo disappears. 

The ammo disappears not only when opening the menu, but also closing it.

This does not occur to ammo that is inside the inventory.

### Attach save file

[i am debug-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11071008/i.am.debug-trimmed.tar.gz)

Contains a debug character surrounded by two piles of 9mm ammo, carrying an empty magazine and a Glock 19.

### Steps to reproduce

1. Spawn empty magazine and compatible ammo on the floor.
2. Open the reload menu and then close out of it again. 
3. Look at the total ammo, it should be depleted.
4. Reopen the menu, see that the ammo total has gone down.
5. Put some ammo in inventory. 
6. Open reload menu and close it again, reopening to see that the ammo in the inventory remains constant.

### Expected behavior

Not paying an ammo tax.

### Screenshots

Before:
Spawned in 100 rounds.
before

**Not pictured: ammo total when opening the menu was 70 rounds instead of original 100.**

After opening and closing menu:
after

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22000.1696 (21H2)
- Game Version: d98a4cc [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Likely related to #64552.

### PR DESCRIPTION
**Pull request by SurFlurer**
#### Summary
Bugfixes "Fix ammo's charge being reduced when calculating reload move_points"

#### Purpose of change
Fix #64588
Fix #64552
Probably fix #64543

In `obtain_cost()`, the `target()` function returns the real ptr to the ammo item. So `target()->split()` will actually reduce the ammo's charge.

#### Describe the solution
Thanks for irwiss's idea, I modified `obtain_cost()` to avoid splitting the ammo item, reducing object copying overhead.

I added a parameter `charges_in_it = -1` to `item_handling_cost()`, which makes it possible to specify a proportion of charges in that item when calling that function.  The parameter's sanity check is eventually handled by item::volume().

#### Describe alternatives you've considered
Keep it simple and just create a copy of `*target()` for splitting.

#### Testing
Good in game.

### CODE REVIEW

File: src/item_location.cpp [hunk 1]
```diff
@@ -255,7 +255,7 @@ class item_location::impl::item_on_map : public item_location::impl
             item *obj = target();
             item temp;
             if( target()->count_by_charges() ) {
-                temp = target()->split( qty );
+                temp = target()->split( qty,/*is_fake =*/true );
```
Comment (irwiss) [inline src/item_location.cpp:258]: imo instead of placing an overload on "innocent" function (as in, the function does what it's supposed to do) you can modify the way it's used weirdly instead, by creating a copy and splitting that;
```suggestion
                temp = item( *target() ).split( qty );
```

Comment (SurFlurer) [reply src/item_location.cpp:258]: Honestly, I implemented in this way at first during debugging, but later I chose to modify the function as not to introduce the overhead of copying large object.

Fair, you have the point. I will commit suggested changes. Thanks.

Comment (irwiss) [reply src/item_location.cpp:258]: if you want to save a copy then modifying Character::item_handling_cost to support a number of charges is a better target; put a default `..., int charges = -1` then in character.cpp line 6714 where it grabs the item::volume and that one has charges_in_vol to override charges, so you won't need to do any splitting at all

Comment (SurFlurer) [reply src/item_location.cpp]: Thank you, I'll look into it, maybe in another PR. This one will just be a quick-fix.

File: src/item_location.cpp [hunk 2]
```diff
@@ -398,22 +392,14 @@ class item_location::impl::item_on_person : public item_location::impl
...
-                if( !temp.is_null() ) {
-                    obj = &temp;
-                }
-            }
-
-            item &target_ref = *target();
-            if( who->is_wielding( target_ref ) ) {
-                mv = who->item_handling_cost( *obj, false, 0 );
+            int handled_qty = obj->count_by_charges() ? ( qty <= 0 ||
+                              qty >= obj->charges ) ? obj->charges : qty : -1;
```
Comment (andrei8l) [inline src/item_location.cpp:397]: Doesn't this accomplish the same thing?
```suggestion
            int handled_qty = std::clamp( qty, -1, obj->count() );
```

Comment (SurFlurer) [reply src/item_location.cpp:397]: Yes, and another look into item::volume() even makes me think that qty can be directly passed to it.....

**Review by irwiss — APPROVED** [review]
