### PR TITLE
Invalidate draw point cache if viewport size or position changes

### LINKED ISSUE #70351: Can't scroll outside view area with 'x'
### Describe the bug

When trying to scroll out of the viewport to look at a distant object using the x key, you can't, there is just a black screen.

### Attach save file

N/A

### Steps to reproduce

1. Make a character
2. Press x
3. Scroll a few tiles to the side

### Expected behavior

For the view to scroll properly

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3803 (22H2)
- Game Version: e42250c [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Extra Mutated Scenarios [extra_mut_scens],
    Tamable Wildlife [Tamable_Wildlife],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro]
]

### Additional context

If this is some kind of way to increase performance, it's not worth it... you can scroll more if you zoom out but it's very annoying that way.

### LINKED ISSUE #70408: List all items/monster around player (V) view bug similiar to looking previous looking round (x)
### Describe the bug

same as the previous view bug that was fixed when looking around with the 'x' key
but it's for 'V' key to list all monsters or items

### Attach save file

N/A

### Steps to reproduce

Use the 'V' feature and zoom in or zoom out

### Expected behavior

View to scroll properly

### Screenshots

Screenshot 2023-12-24 133223
Screenshot 2023-12-24 133247

### Versions and configuration

OS: Windows
OS Version: 10.0.22621.2861 (22H2)
Game Version: 5cb45b3 [64-bit]
Graphics Version: Tiles
Game Language: System language []
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms],
Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by physics-enthusiast**
#### Summary
Bugfixes "Invalidate draw point cache if viewport size or position changes"

#### Purpose of change
Attempt to implement the viewport caching suggested by @Qrox in #70355. 
Fixes #70351, fixes #70408.

#### Describe the solution
Save the previous corners of the viewport and invalidate draw_points_cache if they have changed

#### Testing
Game compiled successfully. "List all items around the player" and "Look around" function as expected again.

#### Additional context
Credit goes to @Rewryte for figuring out the problem and @Qrox for the (hopefully) more robust solution.

### CODE REVIEW

File: src/map.h [hunk 1]
```diff
@@ -2352,6 +2352,10 @@ class map
 #if defined(TILES)
         bool draw_points_cache_dirty = true;
         std::map<int, std::map<int, std::vector<tile_render_info>>> draw_points_cache;
+        int prev_min_col;
+        int prev_max_col;
+        int prev_min_row;
+        int prev_max_row;
```
Comment (BrettDong) [inline src/map.h:2358]: Where are these four variables assigned?

File: src/cata_tiles.cpp [hunk 2]
```diff
@@ -1304,6 +1304,11 @@ void cata_tiles::draw( const point &dest, const tripoint &center, int width, int
     const int max_col = top_any_tile_range.p_max.x;
     const int min_row = bottom_any_tile_range.p_min.y;
     const int max_row = top_any_tile_range.p_max.y;
+    //invalidate draw_points_cache if viewport dimensions have changed
+    if( min_col != here.prev_min_col || max_col != here.prev_max_col || min_row != here.prev_min_row ||
+        max_row != here.prev_max_row ) {
+        here.draw_points_cache_dirty = true;
```
Comment (BrettDong) [inline src/cata_tiles.cpp:1310]: It's better to call the public member function `cata_tiles::set_draw_cache_dirty()` rather than assigning the member variable directly.

File: src/map.h (hunk 1 above)
Comment (physics-enthusiast) [reply src/map.h:2358]: Oh, I forgot to set them to the current values, my bad. Coincidentally this still "solves" the issue, but it does so by effectively disabling the draw cache entirely, which wasn't my intention. Whoops.

**Comment by physics-enthusiast** [comment]
Yay it works again

File: src/cata_tiles.cpp [hunk 3]
```diff
@@ -1353,6 +1353,13 @@ void cata_tiles::draw( const point &dest, const tripoint &center, int width, int
                                 std::max( max_mm_reg.y, southeast->y ) );
         }
     }
+    //invalidate draw_points_cache if viewport dimensions have changed
+    if( min_mm_reg != here.prev_min_mm_reg || max_mm_reg != here.prev_max_mm_reg ) {
```
Comment (Qrox) [inline src/cata_tiles.cpp:1357]: I think the cache is only related to the viewport size, but these are the size of the memorized area.

Which does remind me that map memory currently does not remember visible tiles on other z-levels, but that's something for a different PR.

Comment (physics-enthusiast) [reply src/cata_tiles.cpp]: There also appears to be a secondary (and possibly related) bug that tiles not rendered are in general not memorised, even on the same z-level. So with this PR I can see all tiles in the _current_ view range, but not tiles that would have been visible in _previous_ view ranges.
