### PR TITLE
Feeding NPC follower rotten items has response text added

### LINKED ISSUE #46580: Feeding follower NPC rotten juice pulp does not remove pulp from inventory.
When feeding Follower rotten juice pulp from my inventory, the item is not removed after follower eats item.

My follower has the mutation saprovore which lets them eat decaying material. I made some rotten fruit juice, from water and a rotten orange. I fed follower the juice pulp, and follower confirms eating it, saying that hit the spot, but the juice pulp is still in my inventory. can repeat indefinitely.

# Steps To Reproduce

1. have follower with saprovore.
2. make fruit juice from rotten orange.
3. feed follower the byproduct rotten juice pulp
4. repeat step 3 if desired

# Expected behavior

juice pulp is removed from inventory and follower's calories goes up

# Screenshots
 
image
image
image

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-8475-g41708d3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [] (english)
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Engineering essentials [EngineeringEssentials],
    Generator mod [generatormod],
    Make bows great again [bow_opness],
    Whaleys Collectables [collectablemod],
    Add Rice [rice],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    Armor Up! Survivor Expansion - UndeadPeople Tileset [ArmUpSurvExUDP],
    Cataclysm++ [Cata++],
    Cataclysm++ - UndeadPeople Tileset [Cata++UDP],
    Dried Fruits [dried_fruits],
    Dried Fruits - UndeadPeople Tileset [dried_fruitsUDP],
    Expanded Archery [ExArch],
    Expanded Archery - UndeadPeople Tileset [ExArchUDP],
    Garden Pots [growable-pots],
    Garden Pots - UndeadPeople Tileset [growable-potsUDP],
    Gourmand's Graces [Gourmand'sGraces],
    Gourmand's Graces - UndeadPeople Tileset [Gourmand'sGracesUDP],
    Graphical Overmap [Graphical_Overmap],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Medieval Mod Reborn - UndeadPeople Tileset [Medieval_Mod_RebornUDP],
    Mining Mod [Mining_Mod],
    Mining Mod - UndeadPeople Tileset [Mining_ModUDP],
    Modular Turrets with No Blacklist [modular_turrets_no_blacklist],
    Modular Turrets with No Blacklist - UndeadPeople Tileset [modular_turrets_no_blacklist_UDP],
    More Locations [more_locations],
    More Locations - UndeadPeople Tileset [more_locationsUDP],
    MST Extra [MST_Extra],
    MST Extra - UndeadPeople Tileset [MST_ExtraUDP],
    MSX Black Military Cars [UDP_BlackMilitaryCars],
    MSX Indicators: REMIX [UDP_REMIX_INDICATORS],
    MSX No Highlight [UDP_No_Highlight],
    Mutant Animals [mutant_animals],
    Mutant Animals - UndeadPeople Tileset [mutant_animalsUDP],
    Mutation Changes [Mutation_Changes],
    Mutation Changes - UndeadPeople Tileset [Mutation_ChangesUDP],
    Beta National Guard Camp [national_guard_camp_alt],
    National Guard Camp (Kenan Version) - UndeadPeople Tileset [national_guard_camp_altUDP],
    Salvaged Robots [Salvaged_Robots],
    Salvaged Robots - UndeadPeople Tileset [Salvaged_RobotsUDP],
    sees-player icon, retrodays [sees_player_retro],
    Flowerpot (uekibati) mod [Uekibati_mod],
    Soy mod [Soy mod],
    Soy mod - UndeadPeople Tileset [Soymod_UDP],
    Tankmod: Revived [Tankmod_Revived],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    Blazemod - Vehicle Additions Pack [blazemod],
    Vehicle Additions Pack - UndeadPeople Tileset [blazemodUDP],
    Wild Living [WildLiving],
    Wild Living - UndeadPeople Tileset [WildLivingUDP],
    Abrahms Recipes 1 [AbrahmsRecipes1],
    Merchant Mod [Merchant],
    Sarcophagi Access [sarcophagi_access],
    Roadheader and other mining vehicles [Heavy miners],
    Folding Parts pack [deoxymod],
    Whaleys TALL Buildings [whaleys_tallbuild],
    Ships From Oa Additional Buildings [Ships],
    Oa's Early Game Mutations mod [oa_early_game_mutations_mod],
    No Rail Stations [No_Rail_Stations],
    More City Locations [cityside],
    EXTENDED_BUILDINGS [ZSFixed_Extended_Buildings],
    Wandering Masters [wandering_masters],
    Tekitou Map Commercial Overhaul [tekitoumap],
    NPC Recruitment Options [recruitment_options],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    More Survivor Notes [more_survivor_notes],
    Mutant NPCs B10492 [mutant_npcs_10492],
    machine [machine],
    Hydroponics [hydroponics],
    Food Irradiator [food_irradiator],
    Even More Mutations [even_more_mutations],
    Diluted Mutagens [diluted_mutagens],
    CDDA Variety Pack [ks_variety_pack],
    Alternative Map Key [alt_map_key],
    <color_yellow>Mythical Martial Arts - Mods Extension</color> [MMA_Mods_Extension],
    Jury-Rigged Robots [jury_rigged_robots],
    Draco's Pig Mod [DracoPigMod],
    Draco's Dog Mod [DracoDogMod],
    Crazy Labs [crazy_labs],
    Thermal Electric UPS [thermal_ups],
    The Vermilion Mod [VermilionMod],
    The Glory Of Cereal! [CerealMod],
    The Cool Mod [cool_mod],
    Pixel's Various Fuckery [Pix's Shit],
    Mythological Replicas [nw_pack],
    MOD to grow tea leaves [More tea leaf],
    Makeshift Items Mod [makeshift],
    Large capacity storage CBMs [eps_cbm],
    Icecoon's Arsenal [ew_pack],
    Gun Cotton [guncotton],
    Climate Defying Farming [climate_defying_farming],
    CBM Equipment [CBM_Arms],
    Bionics Systems Recipes [bio_recipes],
    Bens GF recipes [Tolerate_This],
    Fuji's Military Profession Pack [fuji_mpp],
    Military Professions Mod [More_Military],
    Portable Autodoc [portable_autodoc],
    Safe Autodoc [safe_autodoc],
    Safe Portable Autodoc [safe_portable_autodoc],
    Sly's Beauteous Beastly Bugfix [sly_beastfix],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    ZSFIXED_C:DDA Extra Professions & Gears [ZSFIXED_cddaxp],
    <color_light_blue>BL9-100%-monster-resilience-version</color> [BL9_100monres],
    BL9 - UndeadPeople Tileset [BL9_100monresUDP],
    Compatible Add Bandits [GOV_BANDITS],
    Compatible Add Bandits - UndeadPeople Tileset [GOV_BANDITS_UDP],
    No Fungal Monsters [No_Fungi],
    Homestead Instruments Inc. [homestead],
    DinoMod [DinoMod]
]

# Additional context

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
SUMMARY: Bugfixes "NPC followers had no response/check for the player trying to feed them rotten food."

#### Purpose of change
Giving a npc folllower spoiled food splipped through the existing checks and resulted in the "That hit the spot!" message, without consuming the item.

Fixes #46580

#### Describe the solution
Added a check if the food is rotten (can be expanded upon once npc needs make a return)

#### Testing
Spawn in npc follower and attempt to feed (via the dialog menu: use this item) him/her rotten food items.

### CODE REVIEW

File: src/talker_npc.cpp [hunk 1]
```diff
@@ -435,17 +435,25 @@ static consumption_result try_consume( npc &p, item &it, std::string &reason )
             reason = _( "It doesn't look like a good idea to consume this…" );
             return REFUSED;
         } else {
+
+            if( to_eat.rotten() ) {
+                //TODO: once npc needs are operational again check npc hunger state and allow eating if desperate
+                reason = _( "This is rotten! I won't eat that." );
```
Comment (actual-nh) [inline src/talker_npc.cpp:441]:
```suggestion
                reason = _( "This is rotten!  I won't eat that." );
```

**Comment by Qrox** [comment]
NPCs should probably accept the food if they are saprovore.

File: src/talker_npc.cpp [hunk 2]
```diff
@@ -435,17 +435,25 @@ static consumption_result try_consume( npc &p, item &it, std::string &reason )
             reason = _( "It doesn't look like a good idea to consume this…" );
             return REFUSED;
         } else {
+
+            if( to_eat.rotten() ) {
```
Comment (BrettDong) [inline src/talker_npc.cpp:439]: As per @Qrox's suggestion, NPCs with saprovore trait should accept rotten food.
Declare `trait_SAPROVORE` as
```c++
static const trait_id trait_SAPROVORE( "SAPROVORE" );
```
at the beginning of the file, and change the condition to
```suggestion
            if( !p.as_character()->has_active_mutation( trait_SAPROVORE ) && to_eat.rotten() ) {
```
to allow them eat rotten food from the avatar.

**Comment by BrettDong** [comment]
You added your IDE build files to the last commit.

**Comment by Jamuro-g** [comment]
> You added your IDE build files to the last commit.

sry my bad, trying to fix it right now

File: src/talker_npc.cpp [hunk 3]
```diff
@@ -435,17 +436,24 @@ static consumption_result try_consume( npc &p, item &it, std::string &reason )
...
             reason = _( "Thanks, that hit the spot." );
-
         }
+
     } else if( to_eat.is_medication() ) {
         if( !comest->tool.is_null() ) {
             bool has = p.has_amount( comest->tool, 1 );
             if( item::count_by_charges( comest->tool ) ) {
                 has = p.has_charges( comest->tool, 1 );
+
```
Comment (BrettDong) [inline src/talker_npc.cpp:456]:
```suggestion
```

**Review by BrettDong — APPROVED** [review]
