### PR TITLE
Fix CBM not drawing power

### LINKED ISSUE #34745: Enhanced Memory Banks costs no power to use
# Describe the bug
The Enhanced Memory Banks CBM costs no power to activate nor upkeep. In the bionics menu it also shows that it won't drain any power.

# Steps To Reproduce
1. Create a character with the Bionic Game Master class, which starts with the Enhanced Memory Banks CBM
2. Turn on the CBM
3. Observe that no power is drained to activate it nor to keep it active.

# Expected behavior
Unless the Enhanced Memory Banks CBM was changed recently to not cost any bionics power, it should be draining power. Or if it's intentional for it to be free, then it should be a passive CBM because there's no downside to having it active if it doesn't cost power.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8520-gcb7938e [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Bugfixes "Fix CBM not drawing power"```

#### Purpose of change
Fix CBM not drawing power
Fixes #34745 
#### Describe the solution
use units::energy instead of converting int to kilojoule
extend the use of energy::unit a little bit

#### Testing
Start new game with bionic prepper
Turn climate control on
Wait
Power goes down as expected.

### CODE REVIEW

File: src/bionics.cpp [hunk 1]
```diff
@@ -1474,7 +1475,7 @@ void player::perform_uninstall( bionic_id bid, int difficulty, int success, int
         remove_bionic( bid );
 
         // remove power bank provided by bionic
-        mod_max_power_level( -units::from_kilojoule( power_lvl ) );
+        mod_max_power_level( - power_lvl );
```
Comment (anothersimulacrum) [inline src/bionics.cpp]:
```suggestion
        mod_max_power_level( -power_lvl );
```

File: src/bionics.cpp [hunk 2]
```diff
@@ -900,10 +900,11 @@ bool player::burn_fuel( int b, bool start )
  * @param rate divides the number of turns we may charge (rate of 2 discharges in half the time).
  * @return indicates whether we successfully charged the bionic.
  */
-static bool attempt_recharge( player &p, bionic &bio, int &amount, int factor = 1, int rate = 1 )
+static bool attempt_recharge( player &p, bionic &bio, units::energy &amount, int factor = 1,
+                              int rate = 1 )
 {
     const bionic_data &info = bio.info();
-    const int armor_power_cost = 1;
+    const units::energy  armor_power_cost = 1_kJ;
```
Comment (Karthas077) [inline src/bionics.cpp]:
```suggestion
    const units::energy armor_power_cost = 1_kJ;
```
double space

File: src/player.h [hunk 3]
```diff
@@ -324,7 +324,7 @@ class player : public Character
         bool uninstall_bionic( const bionic_id &b_id, player &installer, bool autodoc = false,
                                int skill_level = -1 );
         /**Succes or failure of removal happens here*/
-        void perform_uninstall( bionic_id bid, int difficulty, int success, int power_lvl, int pl_skill );
+        void perform_uninstall( bionic_id bid, int difficulty, int success, units::energy power_lvl, int pl_skill );
```
Comment (Karthas077) [inline src/player.h]:
```suggestion
        void perform_uninstall( bionic_id bid, int difficulty, int success, units::energy power_lvl,
                                int pl_skill );
```
Astyle
