### PR TITLE
Fix compiler warning (dist used w/o declaration)

### LINKED ISSUE #14347: warning: ‘dist’ may be used uninitialized in this function
src/monattack.cpp: In function ‘void mattack::shriek_stun(monster*, int)’:
src/monattack.cpp:284:85: warning: ‘dist’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             target->add_effect("dazed", rng( 10 , 20 ), num_bp, false, rng( 1, ( 15 - dist ) / 3 ) );

### PR DESCRIPTION
**Pull request by Griffinhart**
Fixes #14347.

### CODE REVIEW

File: src/monattack.cpp [hunk 1]
```diff
@@ -257,9 +257,8 @@ void mattack::shriek_stun(monster *z, int index)
     }
 
     Creature *target = z->attack_target();
-    int dist;
-    if( target == nullptr || (dist = rl_dist( z->pos(), target->pos() )) > 7 ||
-        !z->sees( *target ) ) {
+    int dist = rl_dist( z->pos(), target->pos() );
```
Comment (BevapDin) [inline src/monattack.cpp]: `target` could be null. Simplest solution is to just initialized `dist` to 0 and keep the original `if` condition. Btw. gcc 5.2.0 also complains about this, but clang 3.7.0 doesn't.

Comment (Griffinhart) [inline src/monattack.cpp]: If `target` is null, then `if (target == nullptr ...` should catch that, no?
