### PR TITLE
Workaround to invincible vehicles, orphaned parts disentegrate

### LINKED ISSUE #23189: A vehicle with a coil of frames surrounding it is invincible.
### Expected behavior
Smashing vehicles into things damages and eventually destroys them.
### Actual behavior
A vehicle with a coil of frames surrounding it is invincible.
### Steps to reproduce behavior
https://www.reddit.com/r/cataclysmdda/comments/830vz0/invincible_vehicle_and_how_does_it_work
### Explanation
Vehicles in cdda cannot be split into two parts, which means if two parts of a vehicle is connected only by a frame, this frame will be unbreakable. Only one end of the strand of frames around this car is connected to it. If any frame in it breaks except the free end of it (the white v), the strand is split from the car, which is not allowed to happen. This makes all frames in it except the free end unbreakable. You can crash the largest car down to scrap with it without even getting a scratch on it.

### PR DESCRIPTION
**Pull request by kevingranade**
Fixes #23189 

#### Summary
```SUMMARY: Bugfixes "Prevent invincible vehicle effect"```  

#### Purpose of change
If you create a vehicle with a mostly-disconnected row of parts surrounding it, the vehicle becomes invincible due to a flaw in vehicle destruction logic.  The code previously could not handle destroying a frame (the last part to be destroyed in a particular tile) if destroying that frame would result in two disconnected chunks of vehicle.
A simple example is a bicycle:
```
0#0
```
If you destroy the # part, the vehicle code would "break" the part, but not remove it because it would result in two separate chunks of vehicle.  This is not a particularly useful exploit, but if you construct your vehicle as outlined in #23189, the vehicle becomes effectively invincible, because the only part of the "coil" that is subject to destruction is the "tip", which is generally going to be hidden somewhere safe.

#### Describe the solution
This solution takes the simple expedient of picking one of the chunks and destroying all of the parts on it.  It currently uses the "origin" tile of the vehicle to make this decision, but this approach has some flaws.  The main one I've identified is that if you smash the origin tile itself, the game allows it, and then you can proceed to smash the vehicle in half, leaving two separate but mysteriously still fixed in place vehicle parts.

#### Describe alternatives you've considered
A much more correct approach is to spawn a number of new vehicles from the disconnected chunks, but that's hard.
There are a number of decent approaches to determining which side of the break is the "real" vehicle and which one should be destroyed, I picked an arbitrary and simple one here, but am open to suggestions.
Other options I've considered are vehicle center of mass (look out, might not be a part),
player location if present (still need an option for other vehicles), or a randomly selected part for maximum fun.

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -3816,17 +3816,31 @@ int vehicle::break_off( int p, int dmg )
...
+        for( point offset : offsets ) {
+            std::vector<int> at_risk_part = parts_at_relative( smashed_part_position.x + offset.x,
+                                            smashed_part_position.y + offset.y,
+                                            false );
+            if( at_risk_part.empty() ) {
+                continue;
+            }
+            if( !is_connected( parts[ vehicle_origin[ 0 ] ], parts[ at_risk_part[ 0 ] ],
+                               parts[ p ] ) ) {
+                // Ludricrous damage level to insure it happens.
```
Comment (Night-Pryanik) [inline src/vehicle.cpp]: Ludicrous

Comment (Regilith) [reply src/vehicle.cpp]: ensure

**Comment by ZhilkinSerg** [comment]
I can still create vehicle with unconnected parts, but they are breaking easily while driving:

1. Add frames and wing mirror as shown in the image below.
2. Break yellow frames.
3. Winged mirror cannot be uninstalled now as it supports red frames, but you can break it.
4. Smash winged mirror by hands.
5. Red frames are now flying around vehicle unconnected (not invincible though).

image

image

image

**Comment by kevingranade** [comment]
This is a pre-existing bug in vehicle::is_connected(), I'll fix it too.
In short, it's too permissive about what parts are allowed to count as connections, it should only count structural parts, instead it also counts protrusions.
