### PR TITLE
Safemode custom rules fix in new games and added ignore timers

### LINKED ISSUE #26339: Custom Safe Mode rules cause safe mode to fail in certain conditions
**Describe the bug**  
If I have custom rules, I need to take a few extra steps to cause Safe mode to function as it is supposed to. This only needs to be done once per every time I start the executable.

**To Reproduce**  
1. Load some custom safe mode rules. These are the ones that I use (You will need to convert it back to .json to use it): 
[safemode.txt](https://github.com/CleverRaven/Cataclysm-DDA/files/2499372/safemode.txt)
2. Boot up Cataclysm
3. Begin a new game.
4. Spawn an enemy that triggers safe mode. If you're using the attached ruleset, a shocker brute does just fine.
5. Note that despite safe mode being on, nothing happens.
6. Go to the safe mode rules manager. Make a change to a rule, and change it back.
7. Save the changes you made.
8. Safe mode works now.

**Expected behavior**  
Safe mode should work after step 4. This is a potentially dangerous bug for new characters.

**Screenshots**  

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version 0.C-33469-g72b502c (tiles)

**Additional context**  
E.g. A link to a savegame that allows the issue to be reproduced.

### PR DESCRIPTION
**Pull request by GoLoT**
#### Summary
SUMMARY: Bugfixes "Fixes safemode custom rules when creating a new character"

#### Purpose of change
Fixes #26339 - Safemode custom rules not working with new characters
Also adds a new option for safemode 

#### Describe the solution
Force reloading the global rules on a new game creation.
Add a new field to monsters to track when they were last seen so monsters don't stay permanently ignored. This can be disabled with a setting value of 0.

#### Describe alternatives you've considered
Not adding the new ignore timer and keeping this only as a bugfix. Decided it was a good feature so I added it with a [CR] tag.

### CODE REVIEW

File: src/monster.h [hunk 1]
```diff
@@ -429,6 +429,7 @@ class monster : public Creature
         }
 
         short ignoring;
+        int lastseen_turn = INT_MIN;
```
Comment (BevapDin) [inline src/monster.h]: Please use `time_point` instead of `int` for time points. And as it's value is optional, wrap it into a `cata::optional` instead of using an arbitrary value as sentinel.

Comment (GoLoT) [reply src/monster.h]: Got it. Pushing changes now.

File: src/game.cpp [hunk 2]
```diff
@@ -4319,9 +4323,12 @@ int game::mon_info( const catacurses::window &w )
                     if( critter.ignoring > 0 ) {
                         if( safe_mode != SAFE_MODE_ON ) {
                             critter.ignoring = 0;
-                        } else if( mon_dist > critter.ignoring / 2 || mon_dist < 6 ) {
+                        } else if( ( sm_ignored_turns == 0 || ( critter.lastseen_turn.has_value() &&
```
Comment (AMurkin) [inline src/game.cpp]:
```suggestion
                        } else if( ( sm_ignored_turns == 0 || ( critter.lastseen_turn &&
```

File: src/options.cpp [hunk 3]
```diff
@@ -1057,6 +1057,11 @@ void options_manager::add_options_general()
          1, 100, 50
        );
 
+    add( "SAFEMODEIGNORETURNS", "general", translate_marker( "Turns to remember ignored monsters" ),
+         translate_marker( "Number of turns an ignored monster stays ignored after it is no longer seen. 0 disables this option and monsters are permanently ignored." ),
```
Comment (AMurkin) [inline src/options.cpp]:
```suggestion
         translate_marker( "Number of turns an ignored monster stays ignored after it is no longer seen.  0 disables this option and monsters are permanently ignored." ),
```

**Comment by GoLoT** [comment]
Since the code has been reviewed I'm removing the [CR] tag. I'm still open to feedback on the new ignore timer option. Since it can be disabled I don't think anyone should have an issue with it but if someone thinks the current default timer is too long/short or that it should be disabled by default, feel free to say so.
