### PR TITLE
Replace chop logs construction with long action

### LINKED ISSUE #22931: Stone axe can't chop tree trunks into logs or planks
Game version:
Build 7116

Operating system:
Windows 10

Tiles or curses:
Tiles

Mods active:
Default

### Expected behavior
Be able to use the primitive stone axe to chop tree trunks into logs and planks.

### Actual behavior
Unable to do so, the construction action requires a level 2 tree cutting or level 2 wood sawing item. Stone axe is level 1 tree cutting. It used to be level 2 but was changed (nerfed?) at some point making it unable to create logs or planks. Possibly the same problem with stone adze as it's currently level 1 wood sawing but the action requires level 2.

### Steps to reproduce the behavior
Spawn stone axe, go to forest, chop down a tree, attempt to cut down resulting tree trunks using the Construction menu

### Suggested fix
Change stone axe to level 2 tree cutting OR change the "Chop Tree Trunk Into Logs" and/or "Chop Tree Trunk Into Planks" constructions to require level 1 tree cutting so the stone axe can be used to make logs and/or planks.

### PR DESCRIPTION
**Pull request by boydkr**
Builds on #22730, moving forestry actions to items instead of construction.

Fixes #22931

Time required to chop down a tree depends on tool quality and player's strength:
 * character with 10 str and an axe with tree-cutting 2 will take an hour
 * takes twice as long to chop logs as to cut down the tree (generates 2-3 logs)

### CODE REVIEW

File: src/iuse.cpp [hunk 1]
```diff
@@ -4142,6 +4142,34 @@ int iuse::chop_tree( player *p, item *it, bool t, const tripoint &pos )
...
+    if( !choose_adjacent( _( "Chop which which tree trunk?" ), dirp ) ) {
+        return 0;
+    }
+
+    int moves;
+
+    const ter_id ter = g->m.ter( dirp );
+    if( ter == t_trunk ) {
+        /** @EFFECT_STR reduces time required to chop down a tree */
+        moves = MINUTES( 70 - p->str_cur ) * 2 / it->get_quality( AXE ) * 100;
```
Comment (boydkr) [inline src/iuse.cpp]: I think this equation (used here and in `chop_tree`) could use some balance love.

Strength has a tiny effect (1 minute per cut for each strength).  Quality has a massive effect.

Comment (Night-Pryanik) [reply src/iuse.cpp]: Do you have something exact in mind?

**Comment by Night-Pryanik** [comment]
You can also add `do_turn` function to handle messages appearing during the process describing how much time the process will take.

**Comment by boydkr** [comment]
It reuses the `do_turn` for tree chopping. It seemed appropriate

**Comment by smolbird** [comment]
Competes with https://github.com/CleverRaven/Cataclysm-DDA/pull/22933

File: src/activity_handlers.cpp [hunk 2]
```diff
@@ -2121,6 +2123,20 @@ void activity_handlers::chop_tree_finish( player_activity *act, player *p ) {
     act->set_to_null();
 }
 
+void activity_handlers::chop_logs_finish( player_activity *act, player *p ) {
+    const tripoint &pos = act->placement;
+
+    g->m.ter_set( pos, t_dirt );
```
Comment (kevingranade) [inline src/activity_handlers.cpp]: Not necessary hear, but just realized it'd be neat to have a stump item here, might even be useful, it could have the flag for resting a longarm on.

File: src/iuse.cpp (hunk 1 above)
Comment (kevingranade) [reply src/iuse.cpp]: Maybe move strength to the denominator, something like:
```MINUTES( 70 ) / ( ( it->get_quality( AXE ) * 10) + p->str_cur );```
