### PR TITLE
Disapearing autoclave fix

### LINKED ISSUE #32670: Disapearing Autoclave
# Describe the bug

Autoclave and content desapear if it runs out of battery before end of cycle and is outside of the player inventory.

# Steps To Reproduce

1. Get autoclave
2. Load with insufficient amount of battery (<8000)
3. Activate 
4. Put on the ground
5. Wait 
6. It desapears.

This does not happen if you keep the autoclave in your inventory.

# Expected behavior

Autoclave de-activate and CBM is spawned back on the same tile.

# Versions and configuration

 -  Windows 10 
 - build 9380
 - Graphics version: [Tiles or Terminal]
 - Mods loaded: [dda, NPCneeds]

# Additional context

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary
```SUMMARY: Bugfixes "Fix autoclave disapearance"```

#### Purpose of change
Fixes #32670 
Makes it impossible to put filthy cbm in autoclave
#### Describe the solution

Disallow usage of autoclave if amount of charges is not enough for one cycle
Add check for FILTHY tag
Autoclave don't drop CBM by itself, you need to activate it once again to get CBM out.

#### Additional context
The disapearing bug was actually caused by the autoclave going into negative charges and then disapearing.

I don't know how to get the CBM out without requiring one more activation, this might get a bit tedious for the player and is not very clear since the activate menu says `Sterilize` and `U`nload will try to remove the battery.

### CODE REVIEW

File: src/game_inventory.cpp [hunk 1]
```diff
@@ -1835,13 +1835,16 @@ class bionic_sterilize_preset : public inventory_selector_preset
...
-        std::string get_denial( const item_location & ) const override {
+        std::string get_denial( const item_location &loc ) const override {
             auto reqs = *requirement_id( "autoclave_item" );
 
             if( !reqs.can_make_with_inventory( p.crafting_inventory(), is_crafting_component ) ) {
                 return pgettext( "volume of water", "2 L" );
             }
 
+            if( loc.get_item()->has_flag( "FILTHY" ) ) {
+                return string_format( _( "CBM is filthy.  Wash it first." ) );
```
Comment (BevapDin) [inline src/game_inventory.cpp]:
```suggestion
                return _( "CBM is filthy.  Wash it first." );
```
There is **really** no need for string formatting a single string without any parameters.

**Comment by BevapDin** [comment]
Thinking about this: the autoclave should refuse to start when it has not enough charges.

But more importantly: it should not drop the contained items when it aborts. Especially no on the map. Imagine an active autoclave in a **moving** vehicle suddenly stops as it runs out of charges and drops its content on the map, while the player drives away unaware of that.

The contents should stay inside the item and when the player invokes it again, it should query whether to use the contained items or remove them and add new ones.

**Comment by Fris0uman** [comment]
OK, that make sense. Removing the item is not what makes it desapear, I think it's getting to negative charges that does it.

**Comment by Fris0uman** [comment]
jenkins rebuild

File: src/iuse.cpp [hunk 2]
```diff
@@ -8074,27 +8059,57 @@ int iuse::autoclave( player *p, item *it, bool t, const tripoint &pos )
...
+                if( !query_yn( _( "Do you want to use the autoclave?" ) ) ) {
+                    return 0;
+                }
+                empty = true;
+            }
+        }
 
-        if( !to_sterile ) {
+        // Power_draw seem to consume random amount of battery so +100 to be safe
+        if( ( ( it->type->tool->power_draw / 1000 ) * to_seconds<int>( 90_minutes ) ) / 1000 + 100 >
```
Comment (BevapDin) [inline src/iuse.cpp]: This is a long term. It's difficult to see that this is the same term as used below in the popup and it would be much better if you stored this in a variable so the term only appears once.

Comment (Fris0uman) [reply src/iuse.cpp]: Better?

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/autoclave-just-disappeared/20943/2
