### PR TITLE
Fix smoking rack lighting time bug

### LINKED ISSUE #38018: Lighting a smoking rack with a camp fire drill consumes no time
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.D-12253-g6c50a8c00f-dirty [64-bit]
- Graphics Version: Curses
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### PR DESCRIPTION
**Pull request by IpsumCapra**
#### Summary
Bugfixes "Smoking Rack & Kiln: consume time on firing"

#### Purpose of change
Fix a bug where lighting a smoking rack consumes no time. Time consumed is now dependent on the fire starter used. The fix also affects kilns, which previously did not consume time on firing as well.

* fixes #38018

#### Describe the solution
When trying to fire the Smoking Rack, the user is prompted to either use a Finger Lighter CBM, or a regular fire starter (if available). After choosing, borrowed, simplified logic from `iexamine::fireplace` is used to determine whether lighting the fire was successful. ~~Instead of using the fire starter however, its `moves_cost_slow` is waited for, as to not literally set fire to the smoking rack, but still be able to emulate using it.~~

#### Describe alternatives you've considered
~~I would've liked to have called the `use` method on the fire starter, but this leads to setting fire to the smoking rack.~~ The alternative has been implemented.

#### Testing
`make check` was run after every change. In game tests were done to see everything works as it should. If necessary, I am open to implementing tests, but it wasn't clear to me where I should put them.

Manual test was performed by putting down a smoking rack, loading it up with a raw wasteland sausage and charcoal, and lighting it in several different ways. Examples:

*  Using a fire drill
*  Having both a fire drill and electric lighter in the inventory
*  Having an electric lighter in the inventory and a Finger Lighter CBM installed

### CODE REVIEW

File: src/iexamine.cpp [hunk 1]
```diff
@@ -6592,7 +6592,58 @@ static void smoker_activate( Character &you, const tripoint_bub_ms &examp )
...
+        auto success = false;
+        for( auto &firestarter : firestarters ) {
+            item *it = firestarter.second;
+            const use_function *usef = it->type->get_use( "firestarter" );
+            const firestarter_actor *actor = dynamic_cast<const firestarter_actor *>( usef->get_actor_ptr() );
+            you.add_msg_if_player( _( "You attempt to start a fire with your %s…" ), it->tname() );
+            const ret_val<void> can_use = actor->can_use( you, *it, examp );
+            if( can_use.success() ) {
+                // Wait for moves_cost_slow instead of using as we don't want to literally set fire to the smoking rack.
+                you.mod_moves( -actor->moves_cost_slow );
```
Comment (moxian) [inline src/iexamine.cpp:6629]: This will stunlock you for 5 (or however many) minutes with no option for you to do anything about it. If a cockroach happens to pass by when you're lighting the rack, you will die.

I think it would be much better to put the "don't literally put the smoking rack on fire" logic into the firestarter handling.
I.e. move the 
```cpp
    for( item &it : here.i_at( examp ) ) {
        if( it.has_flag( flag_SMOKABLE ) ) {
            it.process_temperature_rot( 1, examp, get_map(), nullptr );
            it.set_flag( flag_PROCESSING );
        }
}
``` 
and everything following into a deducated function (`void smoking_rack_start_smoking(args)` perhaps?), and conditionally call that in [`firestarter_actor::resolve_firestarter_use`](https://github.com/CleverRaven/Cataclysm-DDA/blob/e20131043d7bc2e1dfc5b4ecbd48b823d0647402/src/iuse_actor.cpp#L1498)
```cpp
let success = false;
if (there_is_a_smoking_rack_actually(here, pos)){
  smoking_rack_start_smoking(here, pos);
  success = true;
} else {
  success = here->add_field( pos, fd_fire, 1, 10_minutes );
}
if (success) { /* handle pyromania stuff */  }
```
(although perhaps there's no need for a function, and you can directly inline all this logic into `firestarter_actor::resolve_firestarter_use` directly? it probably won't look good tho, but your call).

You might also need to amend the several checks in `activity_handlers::start_fire_do_turn` with ` || are_we_lightning_a_smoking_rack()` 

And once `actor->use` works fine on smoking rack, you'd be able to share *that* part of fire-lightning between the fireplace and the smoking rack, without the need to duplicate the code anymore (but that's a nice-to-have at this point)

----
This *is* going to be more code and a more tricky to implement, but I see no better way to avoid the stunlock here.

**Review by moxian — CHANGES_REQUESTED** [review]

File: src/iexamine.cpp (hunk 1 above)
Comment (GuardianDll) [reply src/iexamine.cpp:6629]: You can also tie it to a proper activity actor infrastructure, or try to use older, but still useful activity handler function

Comment (moxian) [reply src/iexamine.cpp:6629]: Rewriting firestarter to activity actors is an option, but it doesn't seem to have any immediate benefits for this change in particular, and it requires quite some amount of work.
It would be a welcome change, but better as a separate PR IMHO.

Comment (IpsumCapra) [reply src/iexamine.cpp:6629]: Thanks for your suggestions! I'll try to set up the lighting in the fire starter logic. I see kilns (and maybe other objects?) suffer from the same bug. As such I'll try to come up with a (somewhat) modular solution. Do you think i would have to create a new PR for that?

Comment (GuardianDll) [reply src/iexamine.cpp:6629]: You can make it in the same PR
Do you mean you gonna try to make some robust use_firestarter function? if that's so, it may be wise to actually tie it to already existing firestarter_actor, used for firestarter use action?

Comment (IpsumCapra) [reply src/iexamine.cpp:6629]: Alright, great. To answer your question, I was already planning to implement it as part of the firestarter_actor. I'll try to get it working, and if i have to move around some code after, that's no problem for me.

**Comment by IpsumCapra** [comment]
Alright, I think I made a solid PoC, limited to the smoking rack. If y'all think this is the way to go, I can implement it for kilns too. I would like your advice on whether I have put my changes in the right place, and if there perhaps is a way to know from where `firestarter_actor::use` was called. It would help me skip a query that prompts the user whether they want to light the smoking rack on fire when you use the smoking rack menu (because I doubt you would use the menu just to set the smoking rack on fire).

File: src/iuse_actor.cpp [hunk 2]
```diff
@@ -1519,6 +1553,21 @@ void firestarter_actor::resolve_firestarter_use( Character *p, map *here,
...
 
+bool firestarter_actor::resolve_start( Character *p, map *here,
+                                       const tripoint_bub_ms &pos, start_type type )
+{
+    switch( type ) {
+        case ST_FIRE:
+            return here->add_field( pos, fd_fire, 1, 10_minutes );
+        case ST_SMOKER:
+            return iexamine::smoker_fire( *p, pos );
+        case ST_KILN:
```
Comment (moxian) [inline src/iuse_actor.cpp:1564]: Add a `debugmsg` for TODO stuff like this, so that if it accidentally slips through into the live game, we would at least get a bug report from the users.

File: src/iexamine.h [hunk 3]
```diff
@@ -139,6 +140,11 @@ void on_smoke_out( const tripoint_bub_ms &examp,
 void mill_finalize( Character &, const tripoint_bub_ms &examp );
 void quern_examine( Character &you, const tripoint_bub_ms &examp );
 void smoker_options( Character &you, const tripoint_bub_ms &examp );
+bool smoker_prep( Character &you, const tripoint_bub_ms &examp,
+                  item **charcoal_ref = nullptr,
+                  std::optional<std::reference_wrapper<furn_id>> next_smoker_t_ref = std::nullopt,
+                  std::optional<std::reference_wrapper<int>> charges_ref = std::nullopt );
```
Comment (moxian) [inline src/iexamine.h:146]: Don't expose this monster of an argument list in the public API. Make this acept just the character + tripoint), and put the rest of the arguments into `static bool smoker_prep_internal()` (that `bool iexamine::smoker_fire` calls under the hood).

Or better yet, move just the "populating the output arguments" functionality into a dedicated `static` function, so that there's a clear(er) separation between "calculate the internal values" and "present some feedback to the player". If that means you'll have to iterate over the items in the rack twice - that's okay, performance is not critical here. 
(That might also negate the need to have a meaningful return value, but maybe not, I haven't thought about it enough).

If the return `bool` is here to stay - please add a short comment about what its semantics (same below)

**Review by moxian — COMMENTED** [review]
> Alright, I think I made a solid PoC, limited to the smoking rack. If y'all think this is the way to go, I can implement it for kilns too.

Looks good 👍 . Whether you want to extend it to kilns here or do in a separate PR (or at all, really) is your call.

> I would like your advice on whether I have put my changes in the right place

Looks reasonable, yep. I've left some comments on the smaller details.

> and if there perhaps is a way to know from where `firestarter_actor::use` was called. It would help me skip a query that prompts the user whether they want to light the smoking rack on fire when you use the smoking rack menu (because I doubt you would use the menu just to set the smoking rack on fire).

I don't think knowing from where use() was called is possible or even desirable. If you mean the query that I think you mean - just skip it completely, and assume a default answer.

Also please test whether this works with a slow firestarter (like bow fire drill), because I have a suspicion there might be some issues in `start_fire_do_turn` (which is called by the `ACT_START_FIRE` activity handler, which, in turn, is started by the `p->assign_activity( ACT_START_FIRE, moves, potential_skill_gain,` line in `firestarter_actor::use`

**Comment by moxian** [comment]
> and if there perhaps is a way to know from where firestarter_actor::use was called

Oh, right, I thought about it a bit later, and completely forgot to mention - you could pass some arbitrary extra information through the `->use()` call if firestarter_action was an "activity actor" rather than "activity handler". Look into `activity_actor_definitions.h` / `activity_actor.cpp` for some examples.  And #76163 as a random example of migration (the `const bool pulp_acid = false` is the "extra data" in this particular case)

**Comment by IpsumCapra** [comment]
From my tests, slow firestarters now also seem to work. Ones using tinder (like the bow fire drill) though, can't be used with smoking racks at this time as I can't seem to put tinder into the smoker. How would you suggest I resolve this?

**Comment by moxian** [comment]
I think changing (pseudocode) `if (has_tinder())` to `if (has_tinder() || is_smoking_rack())` ~~or perhaps `if (has_tinder() && start_type == firestarter::start_type::FIRE)`~~ (nevermind we can't do that without moving firestarter to activity actor) is not *too* ugly.

File: src/activity_handlers.cpp [hunk 4]
```diff
@@ -1925,11 +1930,29 @@ void activity_handlers::start_fire_finish( player_activity *act, Character *you
...
+
+    firestarter_actor::start_type st = firestarter_actor::start_type::FIRE;
+
+    if( is_smoking_rack || is_kiln ) {
+        if( is_smoking_rack ) {
+            st = firestarter_actor::start_type::SMOKER;
+        } else {
+            st = firestarter_actor::start_type::KILN;
+        }
+    }
```
Comment (moxian) [inline src/activity_handlers.cpp:1949]:
```suggestion
    if( is_smoking_rack ) {
        st = firestarter_actor::start_type::SMOKER;
    } else if ( is_kiln ) {
        st = firestarter_actor::start_type::KILN;
    }
```

File: src/activity_handlers.cpp [hunk 5]
```diff
@@ -1964,7 +1987,12 @@ void activity_handlers::start_fire_do_turn( player_activity *act, Character *you
     }
 
     item &firestarter = *act->targets.front();
-    if( firestarter.has_flag( flag_REQUIRES_TINDER ) ) {
+
+    const furn_id f_id = here.furn( here.get_bub( act->placement ) );
+    const bool is_smoker = f_id == furn_f_smoking_rack ||
+                           f_id == furn_f_metal_smoking_rack;
+
+    if( firestarter.has_flag( flag_REQUIRES_TINDER ) && !is_smoker ) {
```
Comment (moxian) [inline src/activity_handlers.cpp:1995]: this doesn't check for kiln

File: src/iexamine.cpp [hunk 6]
```diff
@@ -3142,45 +3139,106 @@ void iexamine::aggie_plant( Character &you, const tripoint_bub_ms &examp )
...
+        }
+    } else {
+        you.mod_power_level( -bio_lighter->power_activate );
+        you.mod_moves( -to_moves<int>( 1_seconds ) );
+        firestarter_actor::resolve_firestarter_use( &you, &get_map(), examp,
+                st );
+    }
+}
+
+static units::volume total_volume_at_pos( const tripoint_bub_ms &examp )
```
Comment (moxian) [inline src/iexamine.cpp:3215]: i question moving this into a separate function, given that it's only called once. But no strong opinions here, it's probably fine.

File: src/iexamine.cpp [hunk 7]
```diff
@@ -3142,45 +3139,106 @@ void iexamine::aggie_plant( Character &you, const tripoint_bub_ms &examp )
...
+{
+    if( !kiln_prep( you, examp ) ) {
         return;
     }
+
+    pick_firestarter_and_fire( you, examp, firestarter_actor::start_type::KILN );
+}
+
+static void kiln_prep_internal( Character &you, const tripoint_bub_ms &examp,
+                                std::reference_wrapper<int> char_charges_ref )
```
Comment (moxian) [inline src/iexamine.cpp:3238]: you can return `char_chargers` from the function normally, no need for reference wrapper.

File: src/iexamine.cpp [hunk 8]
```diff
@@ -6514,41 +6601,57 @@ static void mill_activate( Character &you, const tripoint_bub_ms &examp )
...
+    };
+
+    pick_firestarter_and_fire( you, examp, firestarter_actor::start_type::SMOKER );
+}
+
+static void smoker_prep_internal(
+    const tripoint_bub_ms &examp,
+    item **charcoal_ref,
+    std::reference_wrapper<units::volume> food_volume_ref
+)
```
Comment (moxian) [inline src/iexamine.cpp:6616]: I should have thought about it the last round of review, but we can also make this signature much less scary as well by returning an `std::pair<item *, units::volume>`

File: src/iuse_actor.cpp [hunk 9]
```diff
@@ -1428,30 +1436,46 @@ std::unique_ptr<iuse_actor> firestarter_actor::clone() const
...
+    const bool is_smoking_rack = f_id == furn_f_metal_smoking_rack ||
+                                 f_id == furn_f_smoking_rack;
+    const bool is_kiln = f_id == furn_f_kiln_empty ||
+                         f_id == furn_f_kiln_metal_empty || f_id == furn_f_kiln_portable_empty;
+
+    if( is_smoking_rack || is_kiln ) {
+        if( is_smoking_rack ) {
+            return iexamine::smoker_prep( p, pos ) ? start_type::SMOKER : start_type::NONE;
+        } else {
+            return iexamine::kiln_prep( p, pos ) ? start_type::SMOKER : start_type::NONE;
```
Comment (moxian) [inline src/iuse_actor.cpp:1471]:
```suggestion
            return iexamine::kiln_prep( p, pos ) ? start_type::KILN : start_type::NONE;
```
i assume?

(and similar to my other comment elsewhere, there's no need for the outer `if (is_smoking_rack || is_kiln)` if you're checking for those in the inner if anyway)

**Review by moxian — COMMENTED** [review]
Looks good! Just some small comments.

File: src/iuse_actor.cpp (hunk 9 above)
Comment (IpsumCapra) [reply src/iuse_actor.cpp:1471]: Oops, you're entirely right. Those outer if statements are remnants from when there was actually logic being executed before the return is done.

File: src/activity_handlers.cpp (hunk 5 above)
Comment (IpsumCapra) [reply src/activity_handlers.cpp:1995]: Correct. That's because I _am_ actually able to put tinder inside of the kiln, just not inside of the smoking rack. Do you still want me to add it?

File: src/iexamine.cpp (hunk 6 above)
Comment (IpsumCapra) [reply src/iexamine.cpp:3215]: Used to be called twice, that's why I moved the logic into a function along the way I apparently lost one of the calls...

File: src/activity_handlers.cpp (hunk 5 above)
Comment (moxian) [reply src/activity_handlers.cpp:1993]: No, this is good!

**Review by moxian — APPROVED** [review]
LGTM! Thank you!

**Comment by Maleclypse** [comment]
Can you resolve conflicts please?
