### PR TITLE
NPCs taking canned food donations no longer remove the food from the can

### LINKED ISSUE #68456: `u_bulk_trade_accept` doesn't respect item containers.
### Describe the bug

When using `u_bulk_trade_accept` to sell items, specifically canned ones, the containers that they are not respected by the trade option and will leave the player with a bunch of empty containers. If done with sealed canned goods, you will be left with a bunch of sealed, empty cans.

### Attach save file

N/A

### Steps to reproduce

1. Use any `u_bulk_trade_accept` code that takes canned goods in a repeat response, I used Eddie's trade interaction.
2. Spawn in contained canned goods, I used corn.
3. Trade them all and be left with a bunch of empty cans.

### Expected behavior

I expect that if I sell canned goods or sealed things like that, that I will also sell the can instead of magically removing the food and leaving me with empty, sealed cans.

### Screenshots

Before selling my corn.
inventory
After selling my corn.
buggy inventory

### Versions and configuration

-OS: Windows 11
-Game Version: cdda-windows-tiles-sounds-x64-2023-09-26-1218
-Graphics Version: Tiles
-Ingame language: English
-Mods loaded: [ dda, no_npc_food, personal_portal_storms, no_fungal_growth ]

### Additional context

None.

### PR DESCRIPTION
**Pull request by katemonster33**
#### Summary
Bugfixes "fixes issue where NPCs could take an item like canned corn as a donation and would remove the corn from the can and give you the can back."

#### Purpose of change
Fixes: #68456

#### Describe the solution
Modify f_bulk_trade_accept to look for sealed items with a single pocket that contains only the target item. If it is found, remove the item from inventory and give it to the NPC.

#### Testing
Spawn the New England Church Retreat, find Eddie, spawn 10x canned corn in inventory (contained), talk to Eddie and give him the 10 cans. Verify the cans and corn both end up in Eddie's inventory.

### CODE REVIEW

File: src/npctalk.cpp [hunk 1]
```diff
@@ -4047,9 +4066,15 @@ talk_effect_fun_t::func f_bulk_trade_accept( const JsonObject &jo, std::string_v
         if( tmp.count_by_charges() ) {
             seller->use_charges( d.cur_item, seller_has );
         } else {
-            seller->use_amount( d.cur_item, seller_has );
+            seller->use_amount( d.cur_item, seller_has_loose );
+            seller->remove_items_with( is_canned_item );
```
Comment (nornagon) [inline src/npctalk.cpp:4070]: This looks like it removes all canned items from the seller? Do we want to be more specific than that?

Comment (katemonster33) [reply src/npctalk.cpp:4070]: is_canned_item variable name could be improved, it's a lambda that looks for items that contains a single, sealed pocket, that contains only 1 of the item type we are looking for.

Comment (nornagon) [reply src/npctalk.cpp:4070]: ohh, doh, missed the type check at the end of the lambda. cool cool.

File: src/npctalk.cpp [hunk 2]
```diff
@@ -4047,9 +4066,15 @@ talk_effect_fun_t::func f_bulk_trade_accept( const JsonObject &jo, std::string_v
...
+        }
+        if( seller_cans.size() != seller_has ) {
```
Comment (nornagon) [inline src/npctalk.cpp:4072]: emscripten build is complaining about this: 

```
src/npctalk.cpp:4072:32: error: comparison of integers of different signs: 'size_type' (aka 'unsigned long') and 'int' [-Werror,-Wsign-compare]
 4072 |         if( seller_cans.size() != seller_has ) {
      |             ~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~
```

probably `seller_has` should be a `size_t`

Comment (katemonster33) [reply src/npctalk.cpp]: Yep I fixed that
