### PR TITLE
handle empty travel path

### LINKED ISSUE #80279: `Go to destination` crashes the game when the player is not on the same z-level
### Describe the bug

If you have an auto travel route and press `g`, you normally either start traveling or don't if it can't find a path. When on a different z-level than the path however, the game crashes.

### Attach save file

[Test-trimmed.tar.gz](https://github.com/user-attachments/files/19399739/Test-trimmed.tar.gz)

### Steps to reproduce

If using the save, open the map and press `g`.
Otherwise, make a path and cancel before reaching the end, go to a different z-level and press `g`.

### Expected behavior

The game not to crash.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5608 (22H2)
- Game Version: 11b4b17 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/19399749/crash.log)

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
Fix #80279, i.e. crash when trying to auto travel while on different Z level.

#### Describe the solution
Check whether the path is empty and return false if it is, rather than attempt to get the first element of the empty path and blow up.

Added popup to inform player about the failure. Doesn't exit the overmap, though.

#### Describe alternatives you've considered
Change the pathing logic to be able to handle Z levels. That seems difficult.

Try to figure out how to automatically escape from the overmap.

#### Testing
Repeat the error.
Change the code.
- Repeat the error situation without the game crashing.
- Get the popup.
- Accept or reject the popup.
- Escape from the overmap.

#### Additional context
As indicated, the game ought to be able to handle travel between Z levels (although the bug report save doesn't allow that from the ground level either, presumably due to the need to deal with fences).

### CODE REVIEW

File: src/overmap_ui.cpp [hunk 1]
```diff
@@ -1847,6 +1848,17 @@ static bool try_travel_to_destination( avatar &player_character, const tripoint_
                                        const tripoint_abs_omt dest, const bool driving )
 {
     std::vector<tripoint_abs_omt> path = get_overmap_path_to( dest, driving );
+
+    if( path.empty() ) {
+        if( dest.z() == player_character.posz() ) {
+            add_msg( m_warning, _( "Unable to find a path from the current location." ) );
+        } else {
+            add_msg( m_warning,
+                     _( "Auto travel only can only be used with the source and destination on the same Z level." ) );
```
Comment (Brambor) [inline src/overmap_ui.cpp:1857]:
```suggestion
                     _( "Auto travel can only be used with the source and destination on the same Z level." ) );
```

**Comment by RenechCDDA** [comment]
> Try to figure out how to automatically escape from the overmap so the feedback becomes visible directly, rather than having it be delayed until the player exits the overmap.

You should be able to just use `popup`, no?
