### PR TITLE
Fix dissector leaving bugged corpses

### LINKED ISSUE #17728: Bugged broken cyborg corpse on dissector
I checked it in item editor and it has huge negative damage.

### PR DESCRIPTION
**Pull request by BevapDin**
Fixes #17728

`trapfunc::dissector` calls `monster::explode` if the initial damage killed the monsters. That function in turn sets the HP of the monster to `INT_MIN`. In `mondeath::normal`, the hp of the monster are inverted: `-mon.get_hp()` is calculate, which is `-INT_MIN`, but that overflows (`INT_MIN` could be `-INT_MAX - 1`).

The first commit prevents the overflow, the second commit removes the call to `monster::explode` in the trap function. With the fixed overflow, `mondeath::normal` would never leave a body here because the body is basically destroyed.

### CODE REVIEW

File: src/trapfunc.cpp [hunk 1]
```diff
@@ -627,9 +627,6 @@ void trapfunc::dissector( Creature *c, const tripoint &p )
             n->deal_damage( nullptr, bp_foot_r, damage_instance( DT_CUT, 10 ) );
         } else if( z != nullptr ) {
             z->apply_damage( nullptr, bp_torso, 60 );
-            if( z->is_dead() ) {
-                z->explode();
```
Comment (Coolthulhu) [inline src/trapfunc.cpp]: This was supposed to make dissectors splatter things it kills.

Comment (BevapDin) [inline src/trapfunc.cpp]: But it also makes the corpses vanish, which makes the broken cyborg (which spawns nearby and usually runs into a dissector before the player encounters them) useless. The player will only encounter a bloody dissector and nothing more. We may as well spawn a standard zombie there.
