### PR TITLE
Fix spawned monster upgrading

### LINKED ISSUE #12106: Fungaloid spores are fungaloids
Playing Cataclysm 0.C build 3035

For some reason, rather than spores being spawned it spawns fungaloids as seen here when I rammed my way out. 

untitled

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11753840-fungaloid-spores-are-fungaloids?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by i2amroy**
Fixes #12106 permanently.

This turns the "spawn a new monster" block of 4 lines or so into a single function that takes a monster id and a tripoint and then returns a pointer to the newly made monster. This function updates the summoned monster's last update check to the current date, instead of leaving it at the default value of 0.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -6792,6 +6792,18 @@ Creature const* game::critter_at( const tripoint &p ) const
...
+monster * game::summon_mon( const std::string id, const tripoint &p )
+{
+    monster mon(GetMType(id));
+    // Set their last upgrade check to the current day.
+    mon.reset_last_load();
+    mon.spawn(p);
+    add_zombie(mon);
+
+    // Return the non-local copy of the monster
+    return &zombie(critter_tracker.mon_at(p));
```
Comment (i2amroy) [inline src/game.cpp]: Anyone know of a better way to do this than searching through the critter_tracker again to find the monster we just added? I couldn't think of any better way to get a permanent pointer to the monster.

Comment (BevapDin) [inline src/game.cpp]: You could make `add_zombie` return the new monster, than `return add_zombie(...)`. `add_zombie` already returns a bool, but is only used in catalua.cpp

But you want to check the result of `add_zombie` anyway, there are several situations when it *wont* have add a zombie, calling `critter_tracker.mon_at(p)` will fail then:
- the monster id was mon_null,
- the monsters location is outside the map
- (most likely) the monster is blacklisted

Comment (i2amroy) [inline src/game.cpp]: Good points, I'll look into them. Thanks. : )
