### PR TITLE
Make copy of item to be thrown - fix throwing bugs

### LINKED ISSUE #36239: Flashlights disappearing when trying to throw past turrets
# Describe the bug
When exiting labs from the inside, sometimes I use an opaque object to block LOS with the turret peek (X) around the object, while wielding a flashlight, and throw the flashlight towards the door. The flashlight vanishes, and I can not find it from that point forward. Happened just now in build 10021 and twice in an earlier build.

# Steps To Reproduce
As above.

# Expected behavior
Flashlights should not disappear.

# Additional context

I think the flashlights may be hitting the turret. As a thrown object maybe they are being considered a projectile? Even if they do hit, they shouldn't go out. I'm just trying to throw past them, for lighting purposes. I'm getting no message about doing 0 damage to the turret. This time was a heavy duty flashlight so it shouldn't be breaking either.

### LINKED ISSUE #36271: Throwing rocks crashes game
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3985483/crash.log)
Game version: 
0.D-10481-gd4ee75a (tiles)
Build 10033

Operating system: 
Windows 7 Pro 64-bit

Tiles or curses: 
Tiles

Mods active:
Aftershock
Makeshift Items Mod
More Survival Tools
Modular Turrets
Salvaged Robots
Alternative Map Key
More Locations
Fuji's More Buildings
No Rail Stations
Folding Parts Pack
Vehicle Addition Pack
Tanks and Other Vehicles
Arcana and Magic Items
Manual Bionic Installation
Safe Autodoc
Simplified Nutrition
SpeedyDex
Stats Through Kills
Stats Through Skills

### Expected behavior
Throwing rocks doesn't crash game
### Actual behavior
Throwing rocks crashes game 

### Steps to reproduce the behavior
I wielded 10+ rocks, when I throw one rock and check my inventory, I see I only have one rock left being wielded. When I throw that last rock it looks like it's been thrown, but no rock lands on (or near) the target square. When I picked up the first rock I threw (The one that cost 10+ rocks to throw) it shows that it is only one rock. When I try to throw that bugged rock the game crashes with the following error message:

CRASH LOG FILE: config/crash.log 
VERSION: 0.D-10481-gd4ee75a
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:
   @0x555932[cataclysm-tiles.exe+0x155932]
   @0x555BAA[cataclysm-tiles.exe+0x155BAA]
   SMPEG_error+0x3DAF3@0xCA8825[[cataclysm-tiles.exe+0x8A8825]
   @0x727C9D3
   @0x1006b666
   RtlKnownExceptionFilter+0xB7@0x76F150E7[ntdll.dll+0x750E7]
   RtlKnownExceptionChain+0x36@0x76ED97D5[[ntdll.dll+0x397D5]

This error message is followed by a Microsoft Visual C++ Library Runtime termination message.

### LINKED ISSUE #36293: Throwing wielded objects
When using a thrown object such as "throwing axe" or "throwing knife" it deals a minuscule amount of damage when thrown while wielded, but when thrown straight from the inventory it deals full/appropriate damage. Thrown object also disappears after being thrown while wielded.

# Steps To Reproduce

1. Spawn new character, thrown axe/knife, and (basic) zed.
2. Wield axe/knife and throw at zed. It will fail to penetrate armor. (Repeat ad nauseam)
3. Drop axe/knife and throw one from inventory, normal damage and armor pen. Weapon appears on ground when thrown.

# Expected behavior

Normal damage regardless of if the weapon is wielded or not. 
Normal weapon recovery when being thrown while wielded.

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1903
- Game Version: 0.D-10554-g418fa9c [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

I've tested this with homebrew items, and weapons with the same results.

### PR DESCRIPTION
**Pull request by ghost**
#### Summary

```SUMMARY: Bugfixes "Make copy of item to be thrown - fix throwing bugs"```

#### Purpose of change
Fixes #36271 
Fixes #36239 
Fixes #36293 

#### Describe the solution
#36106 changed how throwing works, unfortunately throwing did some sneaky stuff with copies that broke after that PR.

the throw function made a copy, and manipulated charges on that, and deleted the original.
The new function created a reference to the original,  and kept the code that set the ( should be copy ) charges to 1, and then deleted it if it was the last charge or not stackable.

What ive done is create a copy again, send that to the ranged.cpp throwing function, and set the copies charges to 1, and subtract the originals charges appropiately. and delete the original if need be. ( but only after a copy has been sent to ranged.cpp )

#### Describe alternatives you've considered
N/A

#### Testing
new character, spawn 10 rocks, throw them all, charges reduce properly, thrown drops are the right stack size, and thre last rock is thrown and is deposited on the map, and no rocks left in inventory.

#### Additional context
N/A

### CODE REVIEW

File: src/avatar_action.cpp [hunk 1]
```diff
@@ -979,8 +979,17 @@ void avatar_action::plthrow( avatar &you, item_location loc,
...
         return;
     }
-
-    item &thrown = *loc;
+    // make a copy and get the original.
+    // the copy is thrown and has its and the originals charges set appropiately
+    // or deleted from inventory if its charges(1) or not stackable.
+    item *orig = loc.get_item();
+    item thrown;
+    if( orig ) {
```
Comment (KorGgenT) [inline src/avatar_action.cpp]: i feel like it would be _technically_ better to do `if( !loc ) {return;}` then assign `orig` and `thrown`.

Comment (davidpwbrown) [reply src/avatar_action.cpp]: if( !loc ) is already checked above.

Comment (davidpwbrown) [reply src/avatar_action.cpp]: Ah I see, that makes checking get_item() redundant as loc has alreayd been checked, ive removed that now.

**Comment by ChucklesTheBeard** [comment]
Does not close #36271 - Throwing directly from inventory without manually wielding first still segfaults.

File: src/avatar_action.cpp [hunk 2]
```diff
@@ -1006,16 +1009,16 @@ void avatar_action::plthrow( avatar &you, item_location loc,
...
         if( !ret.success() ) {
             add_msg( m_info, "%s", ret.c_str() );
             return;
         }
     }
     // you must wield the item to throw it
-    if( !you.is_wielding( thrown ) ) {
-        you.wield( thrown );
+    if( !you.is_wielding( *orig ) ) {
+        you.wield( *orig );
```
Comment (BevapDin) [inline src/avatar_action.cpp]: This removes the item from the main inventory / the worn item list. The item pointer `orig` will be invalid after that,

Comment (davidpwbrown) [reply src/avatar_action.cpp]: Dosnt seem to cause any problems.

After it's wielded, further operations are called on it, like if( orig->count_by_charges() ) etc, and its fine. 
Though I suppose that could be changed to `you.weapon`  ?

**Comment by davidpwbrown** [comment]
> Does not close #36271 - Throwing directly from inventory without manually wielding first still segfaults.
> [ fresh crash.log](https://gist.github.com/ChucklesTheBeard/74113fe8c4cf0c6681841b6ac9e74d15)

Im throwing from inventory with this PR applied, and its not segfaulting.... you applied this PR yes? and what are the exact repro steps?

File: src/avatar_action.cpp (hunk 2 above)
Comment (davidpwbrown) [reply src/avatar_action.cpp]: Well, ive redefined `orig` as `you.weapon` after wielding, added protection for failed wielding to return if wielding prompt is escaped out of, and continued to use you.weapon afterwards anyway , just incase pointer is invalidated.

**Comment by ChucklesTheBeard** [comment]
Steps to reproduce are the same. I thought I may had screwed up the merge or build flags somehow so I went ahead and re-ran by doing:

```
$ git checkout f1c09f9e76
$ make clean
$ make -j12
$ ./cataclysm --userdir ~/<doesn't matter>
```
g++ version: g++ (GCC) 9.2.0
kernel version: 5.4.5-arch1-1
arch: x86_64

1. Create new world.
2. Start new game: wilderness scenario / field location.
3. Wish for 1 rock.
4. [t]hrow
5. [m]rock (1)
SIGSEGV

[crash.log](https://gist.github.com/ChucklesTheBeard/307c3b8b823080f62e260a9cab8c7d27)

[This save](https://github.com/CleverRaven/Cataclysm-DDA/files/3986591/DebuggerVille.zip) skips steps 1-3. Are you unable to reproduce the crash with that save?

I'm unable to reliably reproduce the issue in the default evacuee start, but wilderness+field starts reproduce the issue reliably.

**Comment by davidpwbrown** [comment]
I could've got very lucky with the invalidation and it accessed same memory, but I threw rocks over and over and over again and no crash... but yeah with latest commit that shouldnt be a risk anymore ( hopefully )

**Comment by davidpwbrown** [comment]
Yeah after latest commit, your attached save, throwing works ok, no crash, for me.

**Comment by ChucklesTheBeard** [comment]
Yep, after 78568ae, it no longer crashes! :tada:
