### PR TITLE
Fix aircraft mechanic profession typo

### LINKED ISSUE #45669: Aircraft mechanic proficiency does nothing due to typo?
# Describe the bug
Airframe and Powerplant Mechanics proficiency has no effect on the ability to repair or maintain aircraft.

# Steps To Reproduce
In https://github.com/CleverRaven/Cataclysm-DDA/blob/8a304fa281b118240741d8078fc8c3a0e8f18656/src/veh_interact.cpp#L79 it looks like the proficiency is incorrectly "aircraft_mechanic" instead of "prof_aircraft_mechanic".

To reproduce:
1. Run the latest or a recent experimental (i.e. build 11187)
2. Save edit to grant your character the proficiency "prof_aircraft_mechanic"
3. Note the proficiency is properly displayed in the @ menu
4. Attempt to repair a helicopter and observe you are incapable of keeping it airworthy.
5. Save edit to grant your character the proficiency "aircraft_mechanic" (no "prof_")
6. Attempt to repair a helicopter and observe you now can repair the helicopter.

Alternatively, instead of save editing, add these items in the Aftershock mod to test:
##  in bionics.json - 
```
  {
    "id": "afs_bio_neurosoft_aeromechanics_fail",
    "type": "bionic",
    "name": { "str": "Neurosoft: Aeromechanics F" },
    "description": "A brain implant that fails to grant instinctual knowledge about the repair of flying machines.",
    "occupied_bodyparts": [ [ "head", 2 ] ],
    "learned_proficiencies": [ "prof_aircraft_mechanic" ]
  },
  {
    "id": "afs_bio_neurosoft_aeromechanics_pass",
    "type": "bionic",
    "name": { "str": "Neurosoft: Aeromechanics P" },
    "description": "A brain implant that grants instinctual knowledge about the repair of flying machines.",
    "occupied_bodyparts": [ [ "head", 2 ] ],
    "learned_proficiencies": [ "prof_aircraft_mechanic", "aircraft_mechanic" ]
  },

```
## in cbms.json -
```
  {
    "id": "afs_bio_neurosoft_aeromechanics_fail",
    "copy-from": "bionic_general",
    "type": "BIONIC_ITEM",
    "name": { "str": "Neurosoft: Aeromechanics CBM F" },
    "description": "A brain implant that fails to grant instinctual knowledge about the repair of flying machines.",
    "price": 1000000,
    "price_postapoc": 100000,
    "difficulty": 8
  },
  {
    "id": "afs_bio_neurosoft_aeromechanics_pass",
    "copy-from": "bionic_general",
    "type": "BIONIC_ITEM",
    "name": { "str": "Neurosoft: Aeromechanics CBM P" },
    "description": "A brain implant that grants instinctual knowledge about the repair of flying machines.",
    "price": 1000000,
    "price_postapoc": 100000,
    "difficulty": 8
  },
```

# Expected behavior
prof_aircraft_mechanic should confer the ability to repair aircraft and veh_interact.cpp should look for the entire "prof_aircraft_mechanic" and not just "aircraft_mechanic" in the proficiency list.

# Screenshots
image
image

# Versions and configuration
Affects all versions since initial introduction of aircraft mechanics proficiency.

# Additional context
Not sure this is actually a bug and not intended to intentionally prevent players from being able to use helicopters, even via modding.

### PR DESCRIPTION
**Pull request by hjk321**
#### Summary

SUMMARY: Bugfixes "Fixed a typo preventing the Airframe and Powerplant Mechanics proficiency from allowing the player to repair aircraft"

#### Purpose of change

Fixes #45669

### CODE REVIEW

File: src/veh_interact.cpp [hunk 1]
```diff
@@ -76,7 +76,7 @@ static const itype_id itype_plut_cell( "plut_cell" );
 
 static const skill_id skill_mechanics( "mechanics" );
 
-static const proficiency_id proficiency_aircraft_mechanic( "aircraft_mechanic" );
+static const proficiency_id proficiency_aircraft_mechanic( "prof_aircraft_mechanic" );
```
Comment (ZhilkinSerg) [inline src/veh_interact.cpp:79]:
```suggestion
static const proficiency_id proficiency_prof_aircraft_mechanic( "prof_aircraft_mechanic" );
```

**Comment by emptytriangle** [comment]
This didn't fix https://github.com/CleverRaven/Cataclysm-DDA/blob/722e024b7f03cf0daaa4ae4eae550863187582f4/src/vehicle.cpp#L98 so it still doesn't work
