### PR TITLE
Fix connector drawing in bionic menu

### LINKED ISSUE #41619: Bionic slots mod UI connects wrong limbs
# Describe the bug

Bionic slots mod UI lines connect to wrong limbs.

# Steps To Reproduce

1. Make a world with bionic slots mod.
2. Make a character with bionics.
3. Check bionics.

# Expected behavior

Lines would connect to correct limbs.

# Screenshots

Screenshot_2020-06-27_03-03-39

# Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 20.0.3; Codename: Lysia; 
- Game Version: 0.E-3547-g7d8b01612f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Bionic Slots [cbm_slots]
]

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

SUMMARY: None

#### Purpose of change
Fixes #41619

#### Describe the solution

Store order of bodyparts in a map

#### Testing

Enable bionic slots
Start a prototype cyborg
Look at bionic menu
Connector conect to correct limbs

image

### CODE REVIEW

File: src/bionics_ui.cpp [hunk 1]
```diff
@@ -267,13 +267,16 @@ static void draw_description( const catacurses::window &win, const bionic &bio )
 }
 
 static void draw_connectors( const catacurses::window &win, const point &start,
-                             int last_x, const bionic_id &bio_id )
+                             int last_x, const bionic_id &bio_id, const std::map<bodypart_str_id, size_t> bp_to_pos )
```
Comment (BevapDin) [inline src/bionics_ui.cpp:270]:
```suggestion
                             int last_x, const bionic_id &bio_id, const std::map<bodypart_str_id, size_t> &bp_to_pos )
```
