### PR TITLE
Atomic coffeepot food and drink heating/defrosting (Fixes #52394)

### LINKED ISSUE #52394: Cannot unfreeze clean water with an atomic coffee maker
### Describe the bug

Even though it's perfectly fine for turning frozen `water` into `clean water (hot)`.

### Steps To Reproduce

Try `a`ctivating an `atomic coffee maker`.

### Expected behavior

Being able to unfreeze liquids with it or being unable to craft `clean water` from `water (frozen)` with it.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.F-3467-g203ff0ba6a-dirty [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dnworden**
#### Summary
Bugfixes "Lets the atomic coffeepot thaw and heat up food and drink, but without the full abilities of a hotplate."

#### Purpose of change

Fixes #52394.

#### Describe the solution

Adds a new use action "hotplate_atomic" which is only on the atomic coffeepot. This allows the coffeepot to heat up items, but it can't cook food or drink (well, besides coffee and such), and it also can't cauterize wounds like a hotplate.

#### Describe alternatives you've considered

Giving back the regular hotplate functionality to the atomic coffeepot, but the comment that was on the atomic coffeepot's item description made me reconsider that.

#### Testing

Ran the game, spawned in an atomic coffeepot, used atomic coffeepot to heat up food and thaw out frozen clean water. Made sure the atomic coffeepot could not cook meat to make sure it didn't have the same functionality as a hotplate.

#### Additional context

I also removed a check in the original hotplate use action that checked if the item was an atomic coffeepot, since that would never happen as the atomic coffeepot lacks the hotplate flag in the first place.

### CODE REVIEW

**Comment by l29ah** [comment]
Shouldn't the regular coffeemaker be given the functionality as well?

**Comment by dnworden** [comment]
@l29ah Well, your bug report specifically mentioned an atomic coffeepot, but I'll make some changes so that the regular coffeepot has the new functionality too.

**Comment by dnworden** [comment]
Not exactly sure why the appveyor build failed since I don't think there are any compilation errors. Is there any way to tell github I'm ready to run a validation check?

**Comment by Amoebka** [comment]
Ok, but why would the normal coffeepot have the hotplate functionality when the atomic one doesn't? Perhaps you can rename "hotplate_atomic" to something like "heat_no_cook" and assign it to both versions, as well as other items of similar nature?

**Comment by dnworden** [comment]
@Amoebka I'm only giving the atomic coffeepot the ability to heat stuff but not cook food since there was a comment on the item saying it shouldn't be hot enough to cook with. I am not changing the regular coffeepot at all, and as such it still has normal hotplate functionality. If the regular coffeepot needs changing I think that a different PR could be made, but for the time being the regular coffeepot being able to cook food is probably fine since it's been in the code for ages without issue.

**Comment by dnworden** [comment]
Fixed the PR summary, should be ready for merging now.

**Comment by dnworden** [comment]
@wapcaplet Do you know why my astyle and appveyor checks are failing? I think my code matches the style of the other code in iuse.cpp, which is where astyle says the problem is. Is there something I'm missing here?

Aside from the style error, I think that this PR is ready to merge. It works as intended when I try it ingame.

File: src/iuse.cpp [hunk 1]
```diff
@@ -5227,6 +5227,20 @@ cata::optional<int> iuse::hotplate( Character *p, item *it, bool, const tripoint
...
 }
 
+cata::optional<int> iuse::hotplate_atomic( Character *p, item *it, bool, const tripoint & )
+{
+    if( p->is_mounted() ) {
+        p->add_msg_if_player( m_info, _( "You can't do that while mounted." ) );
+        return cata::nullopt;
+    }
+    
+    if ( it->typeId() == itype_atomic_coffeepot ) {
```
Comment (wapcaplet) [inline src/iuse.cpp:5237]:
```suggestion
    if( it->typeId() == itype_atomic_coffeepot ) {
```

Here is the bit that astyle doesn't like - just remove this space between `if` and `(` and it should work.

**Comment by wapcaplet** [comment]
Congrats on your first pull request! I marked the change that `astyle` wants to make. Not sure about the Appveyor one, but it's probably nothing to worry about.

I see you've made your commits directly to your fork's `master` branch. That's probably fine for your first PR, but for future reference, it will be better if you create a new branch for each PR. This lets you keep each of your pull requests isolated from one another.

**Comment by dnworden** [comment]
@wapcaplet Oh, I didn't realize that's how to separate out the pull requests. Thank you for helping me find the issue with the PR and with that branching function!

**Comment by dnworden** [comment]
@wapcaplet Well, after looking at the appveyor again it looks like the appveyor itself isn’t building Cataclysm DDA correctly separate from my PR. I think that it might be safe to ignore it this time, but if I’m mistaken please let me know if there’s anything more I can do to fix this. I would have used branches if I knew about them and I’m hoping to get this done so I can open more pull requests (like making junk loot at least marginally useful)

**Comment by wapcaplet** [comment]
I grabbed a copy of your branch and playtested it myself, and it looks good - I can use an atomic coffee maker to thaw frozen water as expected.

@dnworden I think it is up to someone with merge permissions now to approve (re)running the workflow, since it's your first PR. I'll leave a note in our development discord, and someone should get the ball rolling for you soon. If you don't see any updates in a couple days, it's probably OK to ping Zhilkin or Rivet. Thanks for your patience!

File: src/iuse.cpp [hunk 2]
```diff
@@ -5227,6 +5227,20 @@ cata::optional<int> iuse::hotplate( Character *p, item *it, bool, const tripoint
     return cata::nullopt;
 }
 
+cata::optional<int> iuse::hotplate_atomic( Character *p, item *it, bool, const tripoint & )
+{
+    if( p->is_mounted() ) {
+        p->add_msg_if_player( m_info, _( "You can't do that while mounted." ) );
+        return cata::nullopt;
+    }
+
```
Comment (wapcaplet) [inline src/iuse.cpp:5236]:
```suggestion

```

I didn't notice before, this line has trailing whitespace. Removing the spaces on this line should allow the style check to pass.
