### PR TITLE
Fix multi tile door closing

### LINKED ISSUE #13388: Can close vehicle doors while standing on them
Win 7 x64 w/tiles, build 0.C-3590.  As per the title.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26102625-can-close-vehicle-doors-while-standing-on-them?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix multi tile door closing"

#### Purpose of change
Fix #13388
Fix multi tile door closing

#### Describe the solution
Check all attached doors for obstacles rather than just the one.

### CODE REVIEW

File: src/vehicle_use.cpp [hunk 1]
```diff
@@ -1542,6 +1542,27 @@ bool vehicle::is_open( int part_index ) const
...
 }
 
+bool vehicle::can_close( int part_index )
+{
+    for( auto const &vec : find_lines_of_parts( part_index, "OPENABLE" ) ) {
+        for( auto const &partID : vec ) {
+            const Creature *const mon = g->critter_at( global_part_pos3( parts[partID] ) );
+            if( mon ) {
+                if( mon->is_player() ) {
+                    get_player_character().add_msg_if_player( m_info, _( "There's some buffoon in the way!" ) );
```
Comment (BrettDong) [inline src/vehicle_use.cpp:1552]: Isn't it variable `who` in `doors::close_door` who wants to close the door?

File: src/gates.cpp [hunk 2]
```diff
@@ -283,10 +283,12 @@ void doors::close_door( map &m, Creature &who, const tripoint &closep )
             if( !veh->handle_potential_theft( get_avatar() ) ) {
                 return;
             }
-            veh->close( closable );
-            //~ %1$s - vehicle name, %2$s - part name
-            who.add_msg_if_player( _( "You close the %1$s's %2$s." ), veh->name, veh->part( closable ).name() );
-            didit = true;
+            if( veh->can_close( closable ) ) {
```
Comment (BrettDong) [inline src/gates.cpp:286]: You did not pass `who` here.
```suggestion
            if( veh->can_close( closable, who ) ) {
```
