### PR TITLE
Fix C++ exception handling on Android

### LINKED ISSUE #48349: C++ exception is not caught on Android build
# Describe the bug
When there is a JSON error, the app just crashes back to system. The user can't see the red debug message telling where the JSON error is. This is very annoying to some novice mods creators [who write mods on Android phones] as they are unable to figure out where they've done wrong.

# Steps To Reproduce
1. Make some errors in JSON, for example, ~~accidentally~~ omit a bracket in `data/mods/Aftershock/modinfo.json`
2. Launch the game
3. Instant crash back to Android

# Expected behavior
Should display a red debug message showing JSON error:
螢幕截圖 2021-04-03 下午3 12 20

# Versions and configuration
 - OS: Android
 - Game Version: Reproducible on every versions

# Additional context
Log pulled from ADB:
```
04-03 01:59:38.517 22618 22618 F DEBUG   : Revision: '0'
04-03 01:59:38.517 22618 22618 F DEBUG   : ABI: 'arm64'
04-03 01:59:38.518 22618 22618 F DEBUG   : Happend: 'Sat Apr  3 01:59:38 2021
04-03 01:59:38.518 22618 22618 F DEBUG   : '
04-03 01:59:38.518 22618 22618 F DEBUG   : SYSVMTYPE: Art
04-03 01:59:38.518 22618 22618 F DEBUG   : APPVMTYPE: Art
04-03 01:59:38.518 22618 22618 F DEBUG   : pid: 22561, tid: 22610, name: SDLThread  >>> com.cleverraven.cataclysmdda.experimental <<<
04-03 01:59:38.518 22618 22618 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-03 01:59:38.518 22618 22618 F DEBUG   : Abort message: 'terminating with uncaught exception of type JsonError: Json error: storage/emulated/0/Android/data/com.cleverraven.cataclysmdda.experimental/files/data/mods/Aftershock/modinfo.json:2:5: expected array or object
04-03 01:59:38.518 22618 22618 F DEBUG   : 
04-03 01:59:38.518 22618 22618 F DEBUG   :     "
04-03 01:59:38.518 22618 22618 F DEBUG   :     ^
04-03 01:59:38.518 22618 22618 F DEBUG   :      type": "MOD_INFO",
04-03 01:59:38.518 22618 22618 F DEBUG   :     "id": "aftershock",
04-03 01:59:38.518 22618 22618 F DEBUG   :     "name": "Aftershock",
04-03 01:59:38.518 22618 22618 F DEBUG   : '
04-03 01:59:38.518 22618 22618 F DEBUG   :     x0  0000000000000000  x1  0000000000005852  x2  0000000000000006  x3  0000000000000008
04-03 01:59:38.518 22618 22618 F DEBUG   :     x4  fefefefefefeff09  x5  fefefefefefeff09  x6  fefefefefefeff09  x7  7f7f7f7f7f7f7f7f
04-03 01:59:38.518 22618 22618 F DEBUG   :     x8  0000000000000083  x9  e01fed7e159f4f51  x10 0000000000000000  x11 fffffffc7ffffbdf
04-03 01:59:38.518 22618 22618 F DEBUG   :     x12 0000000000000001  x13 000000006068044a  x14 00069247f8108a00  x15 00000a71d9354e7d
04-03 01:59:38.518 22618 22618 F DEBUG   :     x16 00000079c7c702c0  x17 00000079c7baee34  x18 0000000000000001  x19 0000000000005821
04-03 01:59:38.518 22618 22618 F DEBUG   :     x20 0000000000005852  x21 00000079241fcf78  x22 ffffff80ffffffc8  x23 00000079241fd030
04-03 01:59:38.518 22618 22618 F DEBUG   :     x24 00000079241fcf10  x25 00000079241fcf50  x26 000000000000000a  x27 0000000000000001
04-03 01:59:38.518 22618 22618 F DEBUG   :     x28 0000007926bef590  x29 00000079241fce80
04-03 01:59:38.518 22618 22618 F DEBUG   :     sp  00000079241fce40  lr  00000079c7ba3960  pc  00000079c7ba3988
04-03 01:59:38.570 22618 22618 F DEBUG   : 
04-03 01:59:38.570 22618 22618 F DEBUG   : backtrace:
04-03 01:59:38.571 22618 22618 F DEBUG   :     #00 pc 0000000000022988  /system/lib64/libc.so (abort+116)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #01 pc 000000000009ce88  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libc++_shared.so
04-03 01:59:38.571 22618 22618 F DEBUG   :     #02 pc 000000000009d07c  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libc++_shared.so
04-03 01:59:38.571 22618 22618 F DEBUG   :     #03 pc 00000000000aead0  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libc++_shared.so
04-03 01:59:38.571 22618 22618 F DEBUG   :     #04 pc 00000000000ae0fc  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libc++_shared.so
04-03 01:59:38.571 22618 22618 F DEBUG   :     #05 pc 00000000000ae058  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libc++_shared.so (__cxa_throw+112)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #06 pc 00000000010cce34  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (JsonIn::error(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, int)+2116)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #07 pc 000000000129e2ac  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so
04-03 01:59:38.571 22618 22618 F DEBUG   :     #08 pc 0000000000bcd6e4  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so
04-03 01:59:38.571 22618 22618 F DEBUG   :     #09 pc 0000000000bca95c  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (read_from_file(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, std::__ndk1::function<void (std::__ndk1::basic_istream<char, std::__ndk1::char_traits<char>>&)> const&)+116)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #10 pc 0000000000bcaeac  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (read_from_file_optional_json(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, std::__ndk1::function<void (JsonIn&)> const&)+76)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #11 pc 000000000129a0bc  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (mod_manager::load_mod_info(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+176)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #12 pc 0000000001299fb8  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (mod_manager::load_mods_from(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&)+80)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #13 pc 000000000129981c  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (mod_manager::refresh_mod_list()+80)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #14 pc 00000000012996dc  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (mod_manager::mod_manager()+148)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #15 pc 00000000017922a8  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (pimpl<mod_manager>::pimpl()+28)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #16 pc 0000000001791ed8  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (worldfactory::worldfactory()+88)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #17 pc 0000000000e092cc  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (game::game()+800)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #18 pc 0000000001132d40  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libmain.so (SDL_main+3456)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #19 pc 00000000000475ec  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/lib/arm64/libSDL2.so (Java_org_libsdl_app_SDLActivity_nativeRunMain+704)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #20 pc 0000000000003c84  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/oat/arm64/base.odex (offset 0x3000) (org.libsdl.app.SDLActivity.nativeRunMain+228)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #21 pc 000000000058024c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #22 pc 00000000000d8628  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #23 pc 000000000028cec8  /system/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+344)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #24 pc 0000000000286ed0  /system/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+968)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #25 pc 0000000000548984  /system/lib64/libart.so (MterpInvokeStatic+204)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #26 pc 0000000000572694  /system/lib64/libart.so (ExecuteMterpImpl+14612)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #27 pc 000000000000d388  /data/app/com.cleverraven.cataclysmdda.experimental-srfc5L8DD4Xfv6oIRLhwKA==/oat/arm64/base.vdex (org.libsdl.app.SDLMain.run+168)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #28 pc 0000000000260bd4  /system/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEb.llvm.2850692617+488)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #29 pc 0000000000533414  /system/lib64/libart.so (artQuickToInterpreterBridge+1020)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #30 pc 00000000005890fc  /system/lib64/libart.so (art_quick_to_interpreter_bridge+92)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #31 pc 00000000002c1038  /system/framework/arm64/boot.oat (offset 0x13b000) (java.lang.Thread.run+72)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #32 pc 000000000057ff88  /system/lib64/libart.so (art_quick_invoke_stub+584)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #33 pc 00000000000d8608  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #34 pc 000000000047ac6c  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #35 pc 000000000047bd28  /system/lib64/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, jvalue*)+424)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #36 pc 00000000004a7abc  /system/lib64/libart.so (art::Thread::CreateCallback(void*)+1120)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #37 pc 0000000000083588  /system/lib64/libc.so (__pthread_start(void*)+36)
04-03 01:59:38.571 22618 22618 F DEBUG   :     #38 pc 00000000000241dc  /system/lib64/libc.so (__start_thread+68)
04-03 02:00:59.873 23069 23128 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 23128 (SDLThread), pid 23069 (SDLActivity)
```

Apparent there is something wrong with C++ exception handling, because JSON errors are supposed to be caught in `read_from_file()`:
```c++
bool read_from_file( const std::string &path, const std::function<void( std::istream & )> &reader )
{
    try {
        std::ifstream fin( path, std::ios::binary );
        if( !fin ) {
            throw std::runtime_error( "opening file failed" );
        }
        reader( fin );
        if( fin.bad() ) {
            throw std::runtime_error( "reading file failed" );
        }
        return true;

    } catch( const std::exception &err ) {
        debugmsg( _( "Failed to read from \"%1$s\": %2$s" ), path.c_str(), err.what() );
        return false;
    }
}
```
But that didn't happen on Android. The process terminated with `uncaught exception`.

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
Bugfixes "Fix binary compatibility issue on Android"

#### Purpose of change
Fix #48349 : C++ exception is not caught on Android build

The underlying issue of #48349 is that pre-built `libintl-lite.so` has some binary compatibility problem with the compiled game source code and causes bizarre behaviour when a C++ runtime exception is thrown, and probably other unexpected behaviours which haven't been discovered yet. The reason is probably because `libintl-lite.so` was compiled against a different C++ standard library, symbols collide, making the final executable defective.

Pre-built `libintl-lite.so` from `deps.zip`:
```
$(brew --prefix binutils)/bin/readelf -sW libintl-lite/arm64-v8a/libintl-lite.so | grep -i unwind 
    51: 00000000000065dc   244 FUNC    GLOBAL DEFAULT   13 _Unwind_ForcedUnwind
    57: 0000000000004d14    88 FUNC    GLOBAL DEFAULT   13 _Unwind_GetGR
    58: 0000000000004e80    88 FUNC    GLOBAL DEFAULT   13 _Unwind_SetGR
    59: 00000000000066d0   252 FUNC    GLOBAL DEFAULT   13 _Unwind_Resume
    62: 00000000000067cc   248 FUNC    GLOBAL DEFAULT   13 _Unwind_Resume_or_Rethrow
    64: 0000000000004ee0    20 FUNC    GLOBAL DEFAULT   13 _Unwind_GetIPInfo
    65: 0000000000004f3c     8 FUNC    GLOBAL DEFAULT   13 _Unwind_GetTextRelBase
    76: 0000000000004f0c    40 FUNC    GLOBAL DEFAULT   13 _Unwind_FindEnclosingFunction
    78: 0000000000004e78     8 FUNC    GLOBAL DEFAULT   13 _Unwind_GetCFA
    83: 0000000000006464   376 FUNC    GLOBAL DEFAULT   13 _Unwind_RaiseException
    88: 0000000000004f34     8 FUNC    GLOBAL DEFAULT   13 _Unwind_GetDataRelBase
    92: 0000000000004efc     8 FUNC    GLOBAL DEFAULT   13 _Unwind_GetLanguageSpecificData
    94: 0000000000004ed8     8 FUNC    GLOBAL DEFAULT   13 _Unwind_GetIP
    95: 0000000000008054   452 FUNC    GLOBAL DEFAULT   13 _Unwind_Find_FDE
    96: 00000000000068c4    36 FUNC    GLOBAL DEFAULT   13 _Unwind_DeleteException
    98: 0000000000004ef4     8 FUNC    GLOBAL DEFAULT   13 _Unwind_SetIP
   100: 0000000000004f04     8 FUNC    GLOBAL DEFAULT   13 _Unwind_GetRegionStart
   102: 00000000000068e8   208 FUNC    GLOBAL DEFAULT   13 _Unwind_Backtrace
```
***
Compiled from source:
```
$(brew --prefix binutils)/bin/readelf -sW android/app/build/intermediates/ndkBuild/experimentalRelease/obj/local/arm64-v8a/libintl-lite.so | grep -i unwind
    84: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS unwind-dw2.c
    91: 0000000000004558    60 FUNC    LOCAL  DEFAULT   13 _Unwind_SetSpColumn
    92: 0000000000004594    88 FUNC    LOCAL  DEFAULT   13 _Unwind_GetGR.localalias.0
   101: 0000000000005a40   192 FUNC    LOCAL  DEFAULT   13 _Unwind_RaiseException_Phase2
   102: 0000000000005b00   236 FUNC    LOCAL  DEFAULT   13 _Unwind_ForcedUnwind_Phase2
   103: 0000000000005ce0     4 FUNC    LOCAL  DEFAULT   13 _Unwind_DebugHook
   107: 0000000000000000     0 FILE    LOCAL  DEFAULT  ABS unwind-dw2-fde-dip.c
   123: 000000000000693c  1052 FUNC    LOCAL  DEFAULT   13 _Unwind_IteratePhdrCallback
   150: 0000000000004594    88 FUNC    LOCAL  HIDDEN    13 _Unwind_GetGR
   151: 00000000000046f8     8 FUNC    LOCAL  HIDDEN    13 _Unwind_GetCFA
   152: 0000000000004700    88 FUNC    LOCAL  HIDDEN    13 _Unwind_SetGR
   153: 0000000000004758     8 FUNC    LOCAL  HIDDEN    13 _Unwind_GetIP
   154: 0000000000004760    20 FUNC    LOCAL  HIDDEN    13 _Unwind_GetIPInfo
   155: 0000000000004774     8 FUNC    LOCAL  HIDDEN    13 _Unwind_SetIP
   156: 000000000000477c     8 FUNC    LOCAL  HIDDEN    13 _Unwind_GetLanguageSpecificData
   157: 0000000000004784     8 FUNC    LOCAL  HIDDEN    13 _Unwind_GetRegionStart
   158: 000000000000478c    40 FUNC    LOCAL  HIDDEN    13 _Unwind_FindEnclosingFunction
   159: 00000000000047b4     8 FUNC    LOCAL  HIDDEN    13 _Unwind_GetDataRelBase
   160: 00000000000047bc     8 FUNC    LOCAL  HIDDEN    13 _Unwind_GetTextRelBase
   162: 0000000000005ce4   376 FUNC    LOCAL  HIDDEN    13 _Unwind_RaiseException
   163: 0000000000005e5c   244 FUNC    LOCAL  HIDDEN    13 _Unwind_ForcedUnwind
   164: 0000000000005f50   252 FUNC    LOCAL  HIDDEN    13 _Unwind_Resume
   165: 000000000000604c   248 FUNC    LOCAL  HIDDEN    13 _Unwind_Resume_or_Rethrow
   166: 0000000000006144    36 FUNC    LOCAL  HIDDEN    13 _Unwind_DeleteException
   167: 0000000000006168   208 FUNC    LOCAL  HIDDEN    13 _Unwind_Backtrace
   177: 00000000000078d4   452 FUNC    LOCAL  HIDDEN    13 _Unwind_Find_FDE
```

#### Describe the solution
Mainline `libintl-lite` source code from https://github.com/a1studmuffin/libintl-lite and compile it from source code along with game source code together when building an Android game. This ensures that `libintl-lite` is compiled with the exact same C++ standard library and with C++ exceptions and RTTI enabled.

#### Describe alternatives you've considered
* Just re-compile `libintl-lite` with modern Android NDK toolchain and put the updated `libintl-lite.so` into `deps.zip`. But this kind of issue will appear again should Android NDK changes their C++ toolchain in the future.
* Or, refactor `libintl-lite`  to use pure C, or C++ without exception and RTTI.

#### Testing
Try to reproduce #48349. Now the app does not crash and shows the expected debug message screen:
Screenshot_20210403_163213_com cleverraven cataclysmdda experimental

#### Additional context
This may also have fixed some other weird Android specific problems caused by binary incompatibility. I don't know.

### CODE REVIEW

File: src/sdltiles.cpp [hunk 1]
```diff
@@ -545,7 +545,9 @@ void refresh_display()
 #endif
 #if defined(__ANDROID__)
     draw_terminal_size_preview();
-    draw_quick_shortcuts();
+    if( g ) {
+        draw_quick_shortcuts();
```
Comment (ZhilkinSerg) [inline src/sdltiles.cpp:549]: Isn't this hiding shortcuts in main menu (and other menus that are shown before game is started)?

Comment (BrettDong) [reply src/sdltiles.cpp:549]: Three buttons "unknown key XX" will appear at the bottom (in the screenshot) and pressing them crashes the app.
