### PR TITLE
Guarantee NPC weapon spawns

### LINKED ISSUE #58648: `npc::starting_weapon` doesn't spawn a weapon if the npc has the wrong skillset
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/e34eeaacc7a51fe8bb1798d662bee648749a70c1/src/npc.cpp#L1190-L1211

The best skill here can be any skill with the the `combat_skill` tag, but this doesn't check for `melee`, `marksmanship`, `launchers`, `dodging` or `unarmed` and thus will spawn no weapon. Moving the check for `stabbing` to a default else case as the comment suggests was intended would mostly solve it but feel wrong for some of these skills.

### Steps to reproduce

Spawn some random npcs and look at skills and weapons I guess.

### Expected behavior

The method should probably always create a weapon, maybe excluding `unarmed` as the best skill. If npcs without a weapon are intended, it should probably be handled before calling this method (in `npc::randomize`).

### Screenshots

_No response_

### Versions and configuration

9d30272dfe8c326d228782e4670dd2684cafd41e

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by TheKFB**
#### Summary
Bugfixes "Fix NPCs spawning without weapons"

#### Purpose of change

Fixes #58648

Previously, best_skill() would return skills that starting_weapon() would not check for (and wouldn't make sense to check for), resulting in NPCs without weapons.

#### Describe the solution

best_skill() was changed to best_combat_skill() to better reflect its usage, and also given an argument to provide levels of granularity for different uses depending on how strict a definition of "combat skill" is required. Now, best_combat_skill() will always return a skill that starting_weapon() can use.

#### Describe alternatives you've considered

Just trying to do what Erik suggested

#### Testing

Spawned a bunch of NPCs and saw they all had weapons, even when their dodge skill (or similar) was higher than their other weapon skills.

### CODE REVIEW

**Comment by TheKFB** [comment]
This is my first C++ related PR so any input is appreciated.

File: src/npc.cpp [hunk 1]
```diff
@@ -1198,13 +1203,22 @@ void npc::place_on_map()
...
+skill_id npc::best_combat_skill( int selector ) const
 {
     int highest_level = std::numeric_limits<int>::min();
     skill_id highest_skill( skill_id::NULL_ID() );
 
     for( const auto &p : *_skills ) {
         if( p.first.obj().is_combat_skill() ) {
+            if( ( ( selector >= 1 ) && ( p.first == skill_dodge || p.first == skill_gun ||
+                                         p.first == skill_melee ) )
+                || ( ( selector >= 2 ) && ( p.first == skill_unarmed || p.first == skill_launcher ) ) ) {
```
Comment (Fris0uman) [inline src/npc.cpp:1218]: this means that NPC can't spawn with a launcher? Could you maybe unfold this in a switch; where for each value you do the loop and ignore a different set of skills? It would be more code but probably easier to read for anyone coming after you. Also it would be nice to use something more explicit than a int like enum in the function calls

Comment (TheKFB) [reply src/npc.cpp]: Thanks for the input, I reworked it a little and I think it looks cleaner now but let me know if it still needs changes.

Also yeah, an NPC can't spawn with a launcher but that's how it worked before I started messing around with things. That was also in the suggestion Erik gave in the original issue.
