### PR TITLE
fix time travel due to 1s turns

### LINKED ISSUE #31249: Character get sent back in time on load.
# Describe the bug
The date gets messed up, when loading in an game from Build #9112.

# Expected behavior
The date is way off, i think it has reverted to Spring/jumped forward to next Spring.
I think that 

# Screenshots
Before:
image

After:
image

# Versions and configuration 
**(Non-updated version)**
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4039-g02eaddf [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bootleg Walkers [Bootleg_Walkers],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Mining Mod [Mining_Mod],
    Beta National Guard Camp [national_guard_camp],
    Dorf Life [Dorf_Life],
    Arcana and Magic Items [Arcana],
    Magiclysm [magiclysm],
    Necromancy [necromancy],
    Manual Bionic Installation [manualbionicinstall],
    Prevent Zombie Revivication [no_reviving_zombies]
]

# Additional context
I think that it is because of https://github.com/CleverRaven/Cataclysm-DDA/pull/30253 .
Season length is set to 14.
Start date was Spring 1

I am not quite sure how the date is calculated, but here is my guess:
Before:
`1 day = 24*60*(60/6) = ‭14400‬ ticks`
Now:
`1 day = 24*60*(60/1) = 86400 ticks`
Difference:
`+72000‬ ticks`

`Spring day 1 -> Autumn day 10 = ‭38‬ days`
Before:
`38‬ days = 547,200 ticks`
Now:
`38‬ days = 3,283,200 ticks`
Difference:
`+2,736,000 ticks`

Now, since the game know that the "date" is 547,200 ticks, that is equal to 6.3 days, according to the new date-system.
That means that the date is now:
Spring 7

Save from Build #9112:
[Clemson.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3268843/Clemson.zip)

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary

```SUMMARY: Bugfixes "Fix time travel due to 1s turns"```
#### Purpose of change

Fixes #31249
When loading a save from 0.D in 0.E, you get sent back in time. this fixes that by altering some key things upon load given the previous savegame loading version:
- start date
- turns
- item birthdays
- item last_rot_check
#### Testing

Created a game in 0.D summer and waited a few days. Spawned in some fresh meat and dropped it at my feet, and walked away several OMTs. Loaded the game with these changes and observed the meat did not rot in my hands, the season is the same, and the meat i dropped a few OMTs away is still fresh.
#### Additional context

This PR should hang out for a couple days just so people who are playing on experimental and migrate their savs periodically have a chance to bump their savegame version.

### CODE REVIEW

File: src/savegame_json.cpp [hunk 1]
```diff
@@ -2077,6 +2077,11 @@ void item::io( Archive &archive )
     // NB! field is named `irridation` in legacy files
     archive.io( "irridation", irradiation, 0 );
     archive.io( "bday", bday, calendar::start_of_cataclysm );
+    // 0.E stable
+    if( savegame_loading_version < 27 ) {
+        const time_duration tmp_bday = ( bday - calendar::turn_zero ) * 6;
+        bday = calendar::turn_zero + tmp_bday;
+    }
```
Comment (Qrox) [inline src/savegame_json.cpp]: These should be moved afte line 2140 to avoid changing the values on saving.

File: src/savegame_json.cpp [hunk 2]
```diff
@@ -2091,6 +2096,11 @@ void item::io( Archive &archive )
     archive.io( "item_counter", item_counter, static_cast<decltype( item_counter )>( 0 ) );
     archive.io( "rot", rot, 0_turns );
     archive.io( "last_rot_check", last_rot_check, calendar::start_of_cataclysm );
+    // 0.E stable
+    if( savegame_loading_version < 27 ) {
+        const time_duration tmp_rot = ( last_rot_check - calendar::turn_zero ) * 6;
+        last_rot_check = calendar::turn_zero + tmp_rot;
+    }
```
Comment (Qrox) [inline src/savegame_json.cpp]: These should be moved afte line 2140 to avoid changing the values on saving.

**Comment by Qrox** [comment]
I think this will also make saves created after the 1s turn change and before this PR gets merged to time-travel forward when loaded?

**Comment by kevingranade** [comment]
Yes, that's the reason for the suggestion to wait a while before merging the PR, to give players a chance to pick up the new version number in their saves.

File: src/savegame.cpp [hunk 3]
```diff
@@ -172,6 +172,11 @@ void game::unserialize( std::istream &fin )
         data.read( "calendar_start", tmpcalstart );
         calendar::initial_season = static_cast<season_type>( data.get_int( "initial_season",
                                    static_cast<int>( SPRING ) ) );
+        // 0.E stable
+        if( savegame_loading_version < 27 ) {
```
Comment (Qrox) [inline src/savegame.cpp]: Then I think it should be `< 26` here? Otherwise any saves before this PR gets merged (version <= 26) still gets their time multiplied by 6.

Comment (KorGgenT) [reply src/savegame.cpp]: no it means i'll need to make another savegame bump pr. this is still a draft because i need to be sure that i'm hitting all the bases

File: src/mapbuffer.cpp [hunk 4]
```diff
@@ -287,10 +287,9 @@ void mapbuffer::deserialize( JsonIn &jsin )
         bool rubpow_update = false;
```
Comment (BevapDin) [inline src/mapbuffer.cpp]:
```suggestion
```

**Comment by esotericist** [comment]
Took the time to set up a 0.D world with 3 revealed overmaps, and a scattering of fruit pies across 5 locations.
[TimeTest.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4022328/TimeTest.zip)

I marked all of the locations where I have fruit pies with map notes. For instance, this is the starting evac shelter (first overmap):
image

Directly southwest from that, in the same overmap, is the first refugee center I gifted with a single fruit pie. (it's on the road in front of the building. Don't mind the military base, the character is invincible.) (still first overmap)
image

Almost straight west is a tacoma ranch (the notes are in the wrong location, the actual target is the road out front like with the refugee center). (second overmap)
image

This location is notable, because the stack of 99 pies there, *should* be rotten (due to being something like 30 days old), but somehow isn't.

There's also a single pie which shouldn't be rotten. its stats reflect what's expected.

Directly north of the midpoint between the first refugee center and the first ranch, is the second refugee center (still second overmap):
image

It had a slight ant problem, but those are dead and now there is pie.

North a bunch and west a little, is the second ranch (third overmap):
image

I saved and loaded in the first overmap, then explored the second and third overmaps in a second go. everything except the rotting seems to be approximately what I expect.

**Comment by esotericist** [comment]
Additional Debug data.

The evac shelter fruit pie in 0.D, immediately after loading archived 0.D save (no time passed beyond movement):
image

should-be-rotten pies in first ranch in 0.D can't be examined immediately after loading archived save; I think they're removed due to being too rotten.

The evac shelter fruit pie in 0.E, immediately after loading archived 0.D save (no time passed beyond movement):
image

should-be-rotten pies in first ranch in 0.E, only a handful of turns passed (still for movement):
image

**Comment by esotericist** [comment]
With latest commit, the previously-rotten pies are gone when loading a fresh copy of the 0.D save into 0.E.

**Comment by esotericist** [comment]
Things that I haven't tested yet:

*  Monster evolution (the nature of the change means we don't have to worry about zombies suddenly hulking out, but evolution effectively stopping for old monsters could be weird)
*  Crop growth (crops ending up needing more time to grow could be pretty sucky for a player transitioning from 0.D, if they were agri-focused)

**Comment by KorGgenT** [comment]
all right, i think 5 days since the savegame bump is pretty good for those on experimental.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/date-change-and-sudden-food-rotting/22450/2
