### PR TITLE
Fix base64 encoding of horde passability bitsets

### LINKED ISSUE #83423: Save corruption bug
### Describe the bug

Game can't load its own save files.

### Attach save file

[Bombay-trimmed.tar.gz](https://github.com/user-attachments/files/23052597/Bombay-trimmed.tar.gz)

### Steps to reproduce

1. Quicksave
2. Alt+F4
3. Load save

### Expected behavior

Loads save

### Screenshots

Image

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Gentoo; Description: Gentoo Linux; Release: 2.18; Codename: n/a; 
- Game Version: cdda-experimental-2025-10-22-0535 45cbdcf [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Bionic Professions [package_bionic_professions],
    Mind Over Matter [mindovermatter],
    Translate Complex Dialogue [translate_dialogue],
    Stats Through Kills — EOC [STK_EOC]
]

### Additional context

_No response_

### LINKED ISSUE #83516: Upon loading a save, a completely new map (m) has shown, with no relation to the real map which I was traversing
### Describe the bug

I've played for 2-3 hours yesterday on build https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2025-10-28-2011, loaded the save today to see that my [m]ap has no relation to what I see around me. Unfortunately, save has been subsequently removed.

Debug log from the save load is attached, if its of any use.

### Attach save file

Can't provide. I have debug log with errors from my world load. 

### Steps to reproduce

1. Bug is opened after discussion on discord, no exact steps to reproduce available

### Expected behavior

n/a

### Screenshots

_No response_

### Versions and configuration

https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2025-10-28-2011, linux

### Additional context

[debug.log](https://github.com/user-attachments/files/23215979/debug.log) log from my whole play session. Log lines starting from 18:15 and onward (latest section) are the log lines which happened during (faulty) save load attempt.

### PR DESCRIPTION
**Pull request by akrieger**
#### Summary
Bugfixes "Fix rare overmap save corruption from specific horde metadata"

#### Purpose of change
Fixes #83516. Fixes #83423. Fixed #83395. We were getting many reports of people's saves loading weird and overmaps being regenerated. Turns out the base64 encode/decode code was very old and makes some assumptions about the inputs. Such as, if the input starts with a `#`, then it must already be base64 encoded. This is not correct for packed passability bitsets where the packed data can be any arbitrary character.

#### Describe the solution
Rewrite the base64 encode/decode functions for strings and bitsets on top of a common core which does not do any prefix checks. Make the prefix checks only happen in the string functions. Handle loading encoded bitsets with a prefix to forward migrate data.

#### Testing
Before: bitset starts with `#` and gets encoded as the same (garbage data after not shown due to embedded null character).
image

After: bitset is properly encoded in base64 without prefix.
image

### CODE REVIEW

**Comment by kevingranade** [comment]
Tl;dr
Screenshot_20251105_163835_Discord

File: src/catacharset.cpp [hunk 1]
```diff
@@ -216,32 +216,70 @@ static const std::array<char, 64> base64_encoding_table = {{
...
+    }
+    return ret;
+}
+
+static constexpr const std::array<char, 256> base64_decoding_table = build_base64_decoding_table();
+
 static const std::array<int, 3> mod_table = {{0, 2, 1}};
 
-static void build_base64_decoding_table()
+static std::string base64_encode_raw( std::string_view bits );
```
Comment (kevingranade) [inline src/catacharset.cpp]:
```suggestion
static std::string base64_encode_raw( std::string_view str );
```

File: src/catacharset.cpp [hunk 2]
```diff
@@ -216,32 +216,70 @@ static const std::array<char, 64> base64_encoding_table = {{
...
+static std::string base64_decode_raw( std::string_view bits );
```
Comment (kevingranade) [inline src/catacharset.cpp]:
```suggestion
static std::string base64_decode_raw( std::string_view instr );
```

File: src/catacharset.cpp [hunk 3]
```diff
@@ -216,32 +216,70 @@ static const std::array<char, 64> base64_encoding_table = {{
...
-        built = true;
+        memcpy( &raw_bitset_data[i * 8], &bits, sizeof( bits ) );
+    }
+    return base64_encode_raw( raw_bitset_data );
+}
+
+void base64_decode_bitset( std::string_view packed_bitset,
+                           std::bitset<576> &destination_bitset )
+{
+    if( !packed_bitset.empty() && packed_bitset[0] == '#' ) {
```
Comment (kevingranade) [inline src/catacharset.cpp:253]: Doesn't this have the same issue as we need to fix where if the (post migration) first character happens to be # it will be removed?  You can make this safe with a length check though.

Comment (kevingranade) [reply src/catacharset.cpp:253]: Nevermind of course it doesn't, the string you're examining here is base64 encoded so will only have the specified characters.

**Comment by kevingranade** [comment]
overmap_map_data_cache_test.cpp just needs to include catacharset.h and maybe update the signatures when it calls the encode and decide functions.
