### PR TITLE
Minor light level refactor

### LINKED ISSUE #45837: Character::sees_with_infrared is checking daylight level to determine sight range?
### Describe the bug

https://github.com/CleverRaven/Cataclysm-DDA/blob/03138e03ea464d2d620250ccf5ba2f0fd3f558e0/src/character.cpp#L11676

This is in sees_with_infrared.

### Expected behavior

If anything, IR vision at night, at least for seeing warm-blooded creatures, should be **_improved_** by a colder background; however, any vision enhancements for IR at night should probably be fixed when is_warm is fixed (currently always returns "true"). Until then, I suggest using half daylight level (so a range halfway between vision_night and vision_day) at all times.

### PR DESCRIPTION
**Pull request by Hirmuolio**
#### Summary
None

#### Purpose of change

Light level is a float. But there are many places where it was rounded down to integer (most likely old code from time when light level was integer). On some occasions the float was turned into double. And sometimes floats were being converted to floats.

Fix #45837 (sort of at least. Maybe the range should be lower).

#### Describe the solution

Just handle the light level as float.

`Character::sight_range()` which handles NPC vision range on certain situations now gives different vision ranges for NPCs due to removed rounding. Updated the one test case where it was visible.

IR vision code was a bit odd. It was most likely old code written back when player vision did not depend on the illumination of the tile they stand on (for example nowadays standing on bright tile reduces vision range for dark tiles).
Replaced `sight_range( default_daylight_level() )` with just `unimpaired_range()`.

Monster vision had seemingly wrong behavior if light level was above 100. Their sight range would start to decrease as it would start to apply night vision calculations.
Now it just uses the day vision range for all light levels at or above 100.

#### Describe alternatives you've considered

IR vision could always just be the max 60 tiles.  The IR gogles are more like looking through a display so being nearsighted does not actually reduce view range.

#### Testing

Compiles.
Tests pass.
IR goggles work.
Player sight ranges seem to be same.

#### Additional context
NPC vision range is different from player vision range...
In middle of night player has vision range of 2 tiles.
With the rounding errors (before this refactor) NPC in middle of night has vision range of 1 tiles.
With the rounding errors gone (this refactor) NPC in same situation has vision range of 3 tiles.

### CODE REVIEW

**Comment by Wishbringer** [comment]
I think this might be why Vormithrax always warns not to trust the variable light levels, the turrets will fire even though they shouldn't be able to see you. If so this is a huge fix. :1st_place_medal:

**Comment by Wishbringer** [comment]
If this fixes the variable light issues, Vormithrax won't need to complain about it anymore. :1st_place_medal:

**Comment by Hirmuolio** [comment]
I don't think this will fix that.

The game has 3*2 = 6 different ways to calculate wether something can see something.

Three seprate checks for light level (player, NPC and monster each use different one).
Two separate checks for line of sight (plyer uses one while NPC/monsters use another).

**Comment by Wishbringer** [comment]
The issue was that turrets sometimes could see in the dark with variable light in the area even though they shouldn't be able to.

File: src/monster.cpp [hunk 1]
```diff
@@ -1059,22 +1059,21 @@ bool monster::can_act() const
...
     if( !can_see() || effect_cache[VISION_IMPAIRED] ||
         ( underwater && !swims() && !has_flag( MF_AQUATIC ) && !digging() ) ) {
         return 1;
     }
-    static const int default_daylight = default_daylight_level();
+    static const float default_daylight = default_daylight_level();
     if( light_level == 0 ) {
         return type->vision_night;
-    } else if( light_level == default_daylight ) {
+    } else if( light_level >= default_daylight ) {
```
Comment (Willenbrink) [inline src/monster.cpp:1072]: Was this perhaps intended as some sort of blinding? Because it seems reasonable to me that a floodlight could reduce the sight range of someone in its area.
As an aside, there is a linear_interpolation function [here](https://github.com/CleverRaven/Cataclysm-DDA/blob/20872a7e7900a080c43b6659a261f1859fba86f3/src/suffer.cpp#L873-L886). Maybe that could be used here to make the intent clearer (and maybe moved to some math/helper functions file?). Something like
```cpp
if( light_level <= default_daylight) {
  return linear_interpolation( 0, type->vision_night, 
                default_daylight, type->vision_day );
} else {
  return linear_interpolation( default_daylight, type->vision_day,
                             2*default_daylight, type->vision_night);
}
```
Then, at twice the usual brightness you can't see further than your nightvision as you must shield your eyes from the light. Just a thought.

**Review by Willenbrink — CHANGES_REQUESTED** [review]

File: src/monster.cpp (hunk 1 above)
Comment (Hirmuolio) [reply src/monster.cpp:1072]: I think cases of illumination level over 100 are bending system to beyond its limitations and should generally be ignored.

Comment (Willenbrink) [reply src/monster.cpp:1072]: Okay, I'm currently looking through the code but can't really find exact definitions of how brightness should be handled. For example, [default_daylight_level](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/calendar.cpp#L47) is still a double. Are values above 100 impossible? I'm thinking that refactoring light level into its own class would be nice to ensure some invariants. I may have a go at it myself once this PR is merged.

Comment (Willenbrink) [reply src/monster.cpp:1072]: I've decided to take a look at moving the light level into its own class. Once that is well encapsulated, it should just be a matter of defining some constants and modifying the addition etc. to respect any linear/non-linear scale, upper bounds etc.
