### PR TITLE
Fix crash when repairing items

### LINKED ISSUE #51674: Segmentation fault and crash when attempting to reinforce duffel bag.
### Describe the bug

I was going through repairing/reinforcing my clothes and eventually found that attempting to do so on my duffel bag caused the game to seg fault and crash.

### Steps To Reproduce

Load attached Save
Activate sewing kit in inventory
Select worn duffel bag
Choose to repeat until reinforced
Wait about 2 seconds...
Seg Fault

### Expected behavior

I expect nothing, but hope for the game to not seg fault.

### Screenshots

Just before the crash.
image

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.3 LTS; Release: 20.04; Codename: focal; 
- Game Version: 8d47fe3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

Since it is seg faulting i don't think it can create a crash log file as there is none in the config folder.
I have uploaded the save folder and debug.log in a zip.
[crash_debug_and_save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7187112/crash_debug_and_save.zip)

### LINKED ISSUE #51828: Tailoring seems crushing the game from time to time
### Describe the bug

Tailoring activity crashes the game

### Steps To Reproduce

1. create new world without any mods, except these game suggests by default (bionic prof, no fungi growth, etc.)
2. create random char
3. give yourself atomic lamp (or other source of light), tailors kit, 1000 thread, 100 cotton patchwork cloth parts
4. start using your tailors kit on any piece of cloth, for example on these you wear
5. in tailoring menu choose "repeat until reinforced"
6. try different cloths. For me it always fails on "long-sleeving shirt" and "pair of socks" that my player is wearing
7. Enjoy the crash
```
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: /home/dzmitry-dranitski/.cataclysm-dda/config/crash.log
VERSION: 4f8529e
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation faultError creating SDL message box: No message system available

STACK TRACE:

    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x41) [0x55761dc7a4c3]
    ./cataclysm-tiles(+0x96304e) [0x55761dc5c04e]
    ./cataclysm-tiles(+0x963296) [0x55761dc5c296]
    /usr/lib/libc.so.6(+0x3cda0) [0x7fa1af0a5da0]
    ./cataclysm-tiles(item::has_flag(string_id<json_flag> const&) const+0x7c) [0x55761de99058]
    ./cataclysm-tiles(activity_handlers::repair_item_finish(player_activity*, Character*)+0x39c) [0x55761da35e42]
    ./cataclysm-tiles(std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const+0x24) [0x55761da5dbd8]
    ./cataclysm-tiles(activity_type::call_finish(player_activity*, Character*) const+0x37) [0x55761da5cd23]
    ./cataclysm-tiles(player_activity::do_turn(Character&)+0x95e) [0x55761e3d09fa]
    ./cataclysm-tiles(do_turn()+0x378) [0x55761dcc1c1a]
    ./cataclysm-tiles(main+0x12a8) [0x55761d8bcddc]
    /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7fa1af090b25]
    ./cataclysm-tiles(_start+0x2e) [0x55761d9d46fe]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash
    crash.cpp:?
    signal_handler
    crash.cpp:?
    ??
    ??:0
    item::has_flag(string_id<json_flag> const&) const
    ??:?
    activity_handlers::repair_item_finish(player_activity*, Character*)
    ??:?
    std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const
    ??:?
    activity_type::call_finish(player_activity*, Character*) const
    ??:?
    player_activity::do_turn(Character&)
    ??:?
    do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    ??:?
    _start
    ??:?
Aborted (core dumped)
15:59:20-dzmitry.dranitski@:~/repos/Cataclysm-DDA$ ./cataclysm-tiles 
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: /home/dzmitry-dranitski/.cataclysm-dda/config/crash.log
VERSION: 4f8529e
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation faultError creating SDL message box: No message system available

STACK TRACE:

    ./cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x41) [0x55cc81aec4c3]
    ./cataclysm-tiles(+0x96304e) [0x55cc81ace04e]
    ./cataclysm-tiles(+0x963296) [0x55cc81ace296]
    /usr/lib/libc.so.6(+0x3cda0) [0x7f773f5b9da0]
    ./cataclysm-tiles(item::has_flag(string_id<json_flag> const&) const+0x7c) [0x55cc81d0b058]
    ./cataclysm-tiles(activity_handlers::repair_item_finish(player_activity*, Character*)+0x39c) [0x55cc818a7e42]
    ./cataclysm-tiles(std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const+0x24) [0x55cc818cfbd8]
    ./cataclysm-tiles(activity_type::call_finish(player_activity*, Character*) const+0x37) [0x55cc818ced23]
    ./cataclysm-tiles(player_activity::do_turn(Character&)+0x95e) [0x55cc822429fa]
    ./cataclysm-tiles(do_turn()+0x378) [0x55cc81b33c1a]
    ./cataclysm-tiles(main+0x12a8) [0x55cc8172eddc]
    /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7f773f5a4b25]
    ./cataclysm-tiles(_start+0x2e) [0x55cc818466fe]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    log_crash
    crash.cpp:?
    signal_handler
    crash.cpp:?
    ??
    ??:0
    item::has_flag(string_id<json_flag> const&) const
    ??:?
    activity_handlers::repair_item_finish(player_activity*, Character*)
    ??:?
    std::function<void (player_activity*, Character*)>::operator()(player_activity*, Character*) const
    ??:?
    activity_type::call_finish(player_activity*, Character*) const
    ??:?
    player_activity::do_turn(Character&)
    ??:?
    do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    ??:?
    _start
    ??:?
Aborted (core dumped)
```

### Expected behavior

No crash

### Screenshots

_No response_

### Versions and configuration

OS: Arch Linux
Experimental https://github.com/CleverRaven/Cataclysm-DDA/commit/4f8529e53d1462ae7404cd61c125a4bc1190c383

### Additional context

I've prepared a savegame of my world to reproduce. However ive faced it in different worlds

[tailoring.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7217799/tailoring.zip)

### PR DESCRIPTION
**Pull request by svenstaro**
#### Summary
Bugfixes "Crash when repairing items"

#### Purpose of change

This fixes #51828 and also fixes #51674.

#### Describe the solution

This was caused by #51600 which pops the current target if `cannot_continue_repair` is `true`.
However, this popped target is later used as `fix_location` (it's a reference set earlier).

#### Describe alternatives you've considered

None, fix seems straight forward.

#### Testing

Before: Repair something and watch it crash.
Now: Repair something and it'll work.

#### Additional context

@ferociousdork seemed to come to the same conclusion: https://github.com/CleverRaven/Cataclysm-DDA/issues/51828#issuecomment-925886719

### CODE REVIEW

**Comment by dseguin** [comment]
Thank you for fixing that! I should really stop making these silly mistakes.

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -2393,7 +2393,7 @@ void activity_handlers::repair_item_finish( player_activity *act, Character *you
         const bool event_happened = attempt == repair_item_actor::AS_FAILURE ||
                                     attempt == repair_item_actor::AS_SUCCESS ||
                                     old_level != you->get_skill_level( actor->used_skill );
-        const bool can_refit = !destroyed && fix_location->has_flag( flag_VARSIZE ) &&
+        const bool can_refit = !destroyed && !cannot_continue_repair && fix_location->has_flag( flag_VARSIZE ) &&
```
Comment (kevingranade) [inline src/activity_handlers.cpp:2396]:
```suggestion
        const bool can_refit = !destroyed && !cannot_continue_repair &&
                               fix_location->has_flag( flag_VARSIZE ) &&
```
