### PR TITLE
Fix suicidally weak player ptr

### LINKED ISSUE #27016: Hostile NPCs not attacking
**Describe the bug**  
Doing missions for the Refugee Center and bandits just stand there and let me poke them to death with my rapier.  This happened on every mission.

**Versions and configuration(please complete the following information):**
0.C-35078-g99ec0d1

**Additional context**  
[before_last_restore.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2660158/before_last_restore.zip)

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
```SUMMARY: Bugfixes "Restore NPC ability to target player."```  

#### Purpose of change
Fixes #27016 
Due to some shared pointer shennanigans, NPCs became unable to target players, this fixes that and adds a regression test to hopefully alert us if it happens again.
The cause is described in detail at https://github.com/CleverRaven/Cataclysm-DDA/issues/27016#issuecomment-446698016

#### Describe the solution
This adds a shared_ptr to the player class that is populated to a pointer to the player when needed, and then a copy of the shared pointer is returned.  This insures that shared or weak pointers created from this shared pointer stay in scope.

#### Describe alternatives you've considered
Adjusting the game class to hold a shared_ptr to the player instead of embedding the player object directly.  This would require a great deal of refactoring of code from g->u to *(g->u) or similar, would risk some slight performance regression (g->u is accessed a great deal in the codebase, adding a level of indirection to it may be problematic), and comes with risk of additional regressions.
Adding an additional shared_ptr to the player in the game object is another option, but I prefer the self-referential option as providing cleaner guarantees about the lifetime of the object.

To test, simply spawn a NPC and insure hostility by attacking it.  The NPC should attack the player in response (unless it's overintimidated and runs away, you might need to try several times).

### CODE REVIEW

**Comment by jbytheway** [comment]
> #### Describe the solution
> 
> This adds a shared_ptr to the player class that is populated to a pointer to the player when needed, and then a copy of the shared pointer is returned. This insures that shared or weak pointers created from this shared pointer stay in scope.

I'm a little concerned because this makes a new, unsafe, way to get a `shared_ptr` to an `npc`, which could lead to puzzling bugs down the line.

> Adjusting the game class to hold a shared_ptr to the player instead of embedding the player object directly. This would require a great deal of refactoring of code from g->u to *(g->u) or similar, would risk some slight performance regression (g->u is accessed a great deal in the codebase, adding a level of indirection to it may be problematic), and comes with risk of additional regressions.

I don't think that's true; `g->u` is already not the place where the real `player` object is; it's just a reference to it.  I think what would actually be necessary is changing `g->u_ptr` to a `shared_ptr`, which should have much less impact.

**Comment by kevingranade** [comment]
> I'm a little concerned because this makes a new, unsafe, way to get a shared_ptr to an npc, which could lead to puzzling bugs down the line.
There's already an insane number of player-specific functions it's unsafe to call on an npc, the fix for this is to finish the process of reparenting npc onto character, not pretend it's sane to have player be a parent of npc.  In the short term I could override the function in NPC to sabotage it if this is a concern.

File: src/npc.h [hunk 1]
```diff
@@ -460,6 +460,11 @@ class npc : public player
 
         void load_npc_template( const string_id<npc_template> &ident );
 
+        /** This method is not valid to invoke on a NPC. **/
```
Comment (BevapDin) [inline src/npc.h]: Then you should probably add an assertion or a `debugmsg` to report that abuse.

Instead of adding the shared pointer to the `player` class, why not add it to the `game` class? Make it a const value and initialize it with the pointer from `game::u_ptr` (which is initialized once when the `pimpl` is created and is never changed after that):

```
game::game() : u_ptr(), u( *u_ptr ), u_shared_ptr( &u, []( player* ) {} ), ...
```

This avoids changing the *public* interface of the player class.

**Comment by kevingranade** [comment]
Ok I don't totally agree with the rationale, but I don't prefer the player version by enough to override both of you. I'll rework it real quick.

**Comment by kevingranade** [comment]
And by rework I mean just merge @jbytheway 's version.
