### PR TITLE
fix proficiency precision lost in EoC

### LINKED ISSUE #70368: Weapon proficiencies improve and regress while fighting
### Describe the bug

I noticed how my character has stopped progressing any weapon proficiencies for some time now. I paid close attention to how their progress changes, only to notice how they progress and regress with each attack.
This applies to all weapon proficiencies that I previously developed, now they're just stuck, to give some examples:
- improved fencing weapons to 44.1% and medium swords to 42.1% with a cane sword
- improved polarms to 55.1% and spears to 61.1% with a pike and other spears

Looking closely attack after attack, the proficiencies seem to just oscillate between XX.0% and XX.2%.

### Attach save file

[Lemay-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/13757156/Lemay-trimmed.tar.gz)

### Steps to reproduce

1. Look at Polearm Familiarity to see that you are XX.X% of the way towards learning it.
2. Attack something with a pike.
3. Look at the proficiency again.
(Repeat enough times to see the number change, but always stay within the same boundaries.)

### Expected behavior

Proficiencies improve as normal.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.G-5961-gc6f63976b3 [64-bit]
- Graphics Version: Curses
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by GuardianDll**
#### Summary
Bugfixes "Proficiency training works now again"
#### Purpose of change
fix #70368
#### Describe the solution
apply patch from https://github.com/CleverRaven/Cataclysm-DDA/issues/70368#issuecomment-1868264669
#### Describe alternatives you've considered
There may be another percision loss, but someone need to find them first
#### Testing
punched debug monster with a spear, got both spear and polearm prof as expected

### CODE REVIEW

File: src/math_parser_diag.cpp [hunk 1]
```diff
@@ -627,20 +627,19 @@ std::function<double( dialogue & )> proficiency_eval( char scope,
         time_duration raw = d.actor( beta )->proficiency_practiced_time( prof );
         std::string const format = fmt_val.str( d );
         if( format == "percent" ) {
-            return static_cast<int>( raw * 100  / prof->time_to_learn() );
+            return static_cast<double>( raw * 100  / prof->time_to_learn() );
```
Comment (andrei8l) [inline src/math_parser_diag.cpp:630]:
```suggestion
            return raw * 100.0  / prof->time_to_learn();
```
same for `"permille"`
