### PR TITLE
Get random number of rebars instead of pipes after cutting up metal from windows with bars with hacksaw and oxytorch

### LINKED ISSUE #47470: Sawing barred windows produces the wrong material
# Describe the bug
I was looking for rebar to add some bars to my house's windows when I remembered the nearby town had a bunch of barred windows.  I used my trusty hacksaw to cut the bars away, but to my surprise they dropped pipes and not rebar.  Sadly, pipes are not actually usable for building my own window bars.

There's also some other weird behavior surrounding barred windows:
 - Barred windows can have curtains, but you can't weld bars onto windows that have curtains, and likewise barred windows with curtains can't be sawed without tearing the curtains off first.
 - If you saw barred windows without curtains, the glass magically disappears.

# Steps To Reproduce
1. Find any window and tear the curtains off
2. Spawn a welder, 8 rebar, 6 small metal plates, a multitool, welding goggles, and a hacksaw
3. Add bars to the window with the construction menu
4. Activate the hacksaw to saw the bars back off of the window 
5. Observe that the window glass has vanished and the rebar you welded onto the window has magically become pipes.

# Expected behavior
Sawing bars off of a window produces the same material that window bars are made of.  Welding bars onto a window then cutting them back off with a saw doesn't cause the glass to magically disappear (either it's left intact or it breaks into shards, but it should definitely not vanish entirely).  Windows with curtains can be given bars, and barred windows with curtains can have the bars sawed off.

# Versions and configuration
- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 20.04.2 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9578-gcbcfab179d [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Stats Through Skills [StatsThroughSkills]
]

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Balance "Get random number of rebars instead of pipes after cutting up metal from windows with bars with hacksaw and oxytorch."

#### Purpose of change
Closes #47470 - Sawing barred windows produces the wrong material.

#### Describe the solution
- Replaced pipes with rebars as things you get from cutting metal from windows with bars.
- Number of rebars is now random rather than fixed.
- Added ability to cut metal also from windows with bars and open and closed curtains.
- Added ability to cut metal also from windows with metal grating.

#### Describe alternatives you've considered
None.

#### Testing
Got yourself full oxytorch, welding goggles, and hacksaw. Debug-spawned windows with bars and with closed curtains. Cut metal from them using my tools. Got rebar.

#### Additional context
The PR is ready, but I'm putting it as draft as I noticed that using oxytorch on windows is super fast (15 seconds max, even on sturdy terrain like gun safes). So I wonder, is cutting metal with oxytorch THAT fast? Anyone? @Rivet-the-Zombie.

### CODE REVIEW

**Comment by actual-nh** [comment]
See #46257 for a lengthy discussion of time needed (for walls instead of bars, but some of it still applies); quite a lot of disagreement, unfortunately.

**Comment by Night-Pryanik** [comment]
Okay, I'll leave resolving the issue with required time to someone else then.

**Comment by actual-nh** [comment]
> Okay, I'll leave resolving the issue with required time to someone else then.

Understand. If @Rivet-the-Zombie (or anyone else) could help with that, it would be appreciated.

**Comment by NickGrease** [comment]
If you want to extrapolate from this video [(here)](https://youtu.be/KcPjyQGh7EU?t=609) cold cutting an I-Beam + cleaning in 6 minutes. 

For 'window rebar' - say between 4-8 bars per window @ 3/8" to 1/2" excluding initial setup time, it would be ~3 seconds per cut, with between 8 to 16 cuts or roughly 24 to 48 seconds for the whole job. If you want to add 3-4 seconds between cuts for preparation/adjustments that's roughly 1-2 minutes per window. Setup time (lighting the torch) can be fast if you know what your doing, say 30 seconds on the low end - a few minutes or more (its definitely not straight forward to get the mix right) if you know nothing.

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -3603,6 +3621,17 @@ void activity_handlers::hacksaw_finish( player_activity *act, player *p )
     } else if( ter == t_door_bar_c || ter == t_door_bar_locked ) {
         here.ter_set( pos, t_mdoor_frame );
         here.spawn_item( p->pos(), itype_pipe, 12 );
+    } else if( ter == t_metal_grate_window || ter == t_metal_grate_window_with_curtain ||
+               ter == t_metal_grate_window_with_curtain_open ) {
+        here.ter_set( pos, t_window_reinforced );
+        here.spawn_item( p->pos(), itype_rebar, rng( 1, 12 ) );
```
Comment (RadHazard) [inline src/activity_handlers.cpp:3627]: Just an FYI, it looks like the metal_grate_window uses pipes and not rebar in it's construction.  It probably *should* be using rebar, but for the moment it's pipes

File: src/activity_handlers.cpp [hunk 2]
```diff
@@ -3575,10 +3590,13 @@ void activity_handlers::hacksaw_finish( player_activity *act, player *p )
...
         here.ter_set( pos, t_window_alarm );
-        here.spawn_item( p->pos(), itype_pipe, 6 );
+        here.spawn_item( p->pos(), itype_rebar, rng( 1, 6 ) );
+    } else if( ter == t_window_bars_curtains || ter == t_window_bars_domestic ) {
+        here.ter_set( pos, t_window_domestic );
+        here.spawn_item( p->pos(), itype_rebar, rng( 1, 6 ) );
     } else if( ter == t_window_bars ) {
         here.ter_set( pos, t_window_empty );
-        here.spawn_item( p->pos(), itype_pipe, 6 );
+        here.spawn_item( p->pos(), itype_rebar, rng( 1, 6 ) );
```
Comment (RadHazard) [inline src/activity_handlers.cpp:3599]: I don't know if you decided on keeping it 1-6 intentionally, but in case it was just an oversight, the actual window bar construction recipe uses 8 rebar, not 6.  I'm not sure where the 6 pipes of the original cutting code came from.

File: src/activity_handlers.cpp (hunk 1 above)
Comment (Night-Pryanik) [reply src/activity_handlers.cpp:3627]: Yeah, I noticed that too. Just an oversight from my side. Will fix this soon.

File: src/activity_handlers.cpp (hunk 2 above)
Comment (Night-Pryanik) [reply src/activity_handlers.cpp:3599]: Yeah, I noticed that too. I thought that 2 pipes/rebars are just lost due to inefficient sawing/cutting, so I guess it's ok to have 1-6 things spawn on this.

Comment (RadHazard) [reply src/activity_handlers.cpp:3599]: Personally I'd say the randomness should already take care of simulating that inefficiency, but as long as you're aware of it I won't complain either way :+1:

Comment (NickGrease) [reply src/activity_handlers.cpp]: I don't think the numbers necessarily need to change, but maybe what they represent should. I would suggest that the number of bars returned simply model the number of bars on the window, oppose to efficiency - which is like being asked to cut a piece of paper in half and inexplicably cutting a circle out of it. 😄

**Comment by Rivet-the-Zombie** [comment]
>is cutting metal with oxytorch THAT fast?

Once it's been heated and you're giving it straight oxygen to cut with, yes. The preheating part is going to be the most time consuming part of such a project - you'll have to heat each individual bar separately.
