### PR TITLE
Steal / Disarm / Tazer Aggression Fixes

### LINKED ISSUE #19535: Stealing from NPCs doesn't count as starting the fight
Merged #19326 a bit too soon, but it's not really a big deal.

Stealing/disarm makes the NPCs angry at the player, but doesn't count as starting the fight for the purpose of murder penalty. It obviously should.

### PR DESCRIPTION
**Pull request by tswood**
Fixes #19535.

Primary Changes:
* Properly flag the player for having started an aggression on a non-hostile NPC in the following situations:
 * Disarming
 * Failed Stealing

Additional Changes:
* Stealing is only available against non-hostiles. Open to reasonable scenarios for having it available regardless.
* Add prompt to stealing.
* Update attack menu action prompting. Will now only prompt if the target is a non-hostile.
* Allow attempting to disarm a hostile. Previously, the menu option was available but was no-op if the target was hostile.
* Update `iuse::tazer` to make use of same NPC aggression functionality.
* Update attack menu action to make use of the same NPC aggression functionality.

Relisting of #19557 since I fubar'd the orignal branch.

### CODE REVIEW

File: src/iuse.cpp [hunk 1]
```diff
@@ -3878,61 +3878,58 @@ int iuse::tazer(player *p, item *it, bool, const tripoint &pos )
...
     p->moves -= 100;
 
     ///\EFFECT_DODGE increases chance of dodging a tazer attack
-    int target_dice = target->get_dodge();
-    if( dice( numdice, 10 ) < dice( target_dice, 10 ) ) {
-        // A miss!
-        p->add_msg_player_or_npc( _("You attempt to shock %s, but miss."),
-                                  _("<npcname> attempts to shock %s, but misses."),
+    const bool tazer_was_dodged = dice( numdice, 10 ) < dice( target->get_dodge(), 10 );
+    if( tazer_was_dodged ) {
```
Comment (sethsimon) [inline src/iuse.cpp]: Since these are the only uses of `tazer_was_dodged`, it should be written as `if( dice( numdice, 10 ) < .....`

File: src/npc.h [hunk 2]
```diff
@@ -610,6 +610,12 @@ class npc : public player
  bool turned_hostile() const; // True if our anger is at least equal to...
  int hostile_anger_level() const; // ... this value!
  void make_angry(); // Called if the player attacks us
+     /*
+     * Angers and makes the NPC consider the creature an attacker
+     * if the creature is a player and the NPC is not already hostile
+     * towards the player.
+     */
+    void on_attacked( const Creature &attacker );
```
Comment (sethsimon) [inline src/npc.h]: Why is this indented more than everything else?

File: src/iuse.cpp (hunk 1 above)
Comment (tswood) [inline src/iuse.cpp]: Good catch. I'll inline it. Thought I had another usage but was wrong.

**Comment by tswood** [comment]
My initial guess would be pre-existing, but they're certainly worth looking into. I'll see what I can do to sort those out.

Thanks for taking a look!

**Comment by sethsimon** [comment]
You're welcome, good luck.
>This indentation is, IIRC, the more correct size for new formatting.

Sorry, you're right, never mind about that.

**Comment by codemime** [comment]
Looks good, but needs a minor cleanup.

**Comment by tswood** [comment]
Apologies. Got busy with the holidays and haven't made time to transition back into the swing of things. I'll be sure to tidy revisit this and tidy anything remaining up.

As to the fleeing NPC attacking the player, I did some research. What I found was that when a fleeing creature has an adjacent hostile, it will do a check to see if it can outrun the hostile. If it can, it'll continue to flee. Otherwise it'll turn and attack, though still be considered "fleeing" behaviorally. In the case of the hostile being the player, it appears the player is pretty much guaranteed to be considered faster due to being able to run. I can recheck this and validate it with some numbers, but would prefer to take it into another issue if possible.
