### PR TITLE
Fix "tried to set invalid ammo for sauerkraut" bug with sealed jars

### LINKED ISSUE #16322: "Tried to set invalid ammo none for sauerkraut"
* Pick up sealed sauerkraut
* Wield it
* Activate it
* Debugmsg

The jar actually turned into jar of 'kraut, but the result had only 1 charge. Pickled veggies and meat, opened just after that, didn't bug out.

Could be save related. If it is, it's probably minor enough not to keep it open.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #16322 

The first problem was that `item::ammo_set` was used. `ammo_set` doesn't work with non-ammo arguments, such as food.
Changed it so that it is only used if `ammo_type` is specified.

Another problem was that some of the target items were non-charged, yet target charges were specified. It isn't handled well.
Fixed by changing the badly specified items (from volume 1 and stack size 1 to volume 2 and stack size 2) and added a warning on load if a non-charged item is specified with >1 charge number.

Finally, added a throw when both a container and ammo type are specified. It wasn't used anywhere and wasn't handled well.
Ammo type is specified in only one item and it is a very minor feature.

### CODE REVIEW

File: src/iuse_actor.cpp [hunk 1]
```diff
@@ -120,13 +125,12 @@ long iuse_transform::use(player *p, item *it, bool t, const tripoint &pos ) cons
...
+            obj->ammo_set( ammo_type.empty() ? obj->ammo_current() : ammo_type, ammo_qty );
+        }
     } else {
         it->convert( container );
-        obj = &it->emplace_back( target );
-    }
-
-    if( ammo_qty >= 0 ) {
-        obj->ammo_set( ammo_type.empty() ? obj->ammo_current() : ammo_type, ammo_qty );
+        obj = &it->emplace_back( item( target, calendar::turn, ammo_qty >= 0 ? ammo_qty : 1 ) ) ;
```
Comment (mugling) [inline src/iuse_actor.cpp]: I don't think you need to explicitly call the constructor there
Possibly `std::max` rather than the ternary operator?
