### PR TITLE
Ensure mapgen order is sensible

### LINKED ISSUE #49788: Nested maps with palettes aren't drawing wall terrain fully
# Describe the bug
Basement nested mapgen uses a lot of walls that surround the perimeter of the nested chunk.  They don't seem to be spawning, or only the first tile is being drawn.

# Steps To Reproduce
Spawn in a map.
Hop around some basements and look for nested chunks where the furniture doesn't seem to line up with the walls.

note: debug spawning the chunk will include the walls.
# Expected behavior
full nest placement.
`room_10x10_recording_studio_N` is a good example of a failing nested map chunk.  
The wall symbol "|" does override the same symbol in the palette it references in the nested map gen entry.

# Screenshots
Red circle is a tile of placed wall. the rest never spawned.
image

# Versions and configuration
Newest build checked,  no mods or other changes.

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
Bugfixes "Ensure mapgen order is sensible"

#### Purpose of change
When terrain and furniture were merged into the same mapgen system as everything else it changed the order in which mapgen happened.  In particular, some terrain was now placed after nested mapgen, which caused the terrain from the nest to be overridden.

Fixes #49788 (the issue with missing walls in basements).

#### Describe the solution
Add the ability to define an ordering in which the `jmapgen_piece`s should be applied, and ensure that terrain and furniture go first.  This should more closely match what happened before the changes in #48498.

#### Describe alternatives you've considered
I also tried to ensure that faction ownership changes and terrain transformations go at the end, even after nested mapgen.  This seemed like the right call, though I suspect it's subject to debate.

#### Testing
Verified that the example from #49788 now works correctly:
nested-recording-studio

#### Additional context
Discovered this cause while continuing my work on parametric mapgen.

### CODE REVIEW

File: src/mapgen.h [hunk 1]
```diff
@@ -169,6 +169,17 @@ class jmapgen_piece
...
+        /** The pieces will be applied in order of phases.  The phases are as
+         * follows:
+         * -2 - terrain
+         * -1 - furniture
+         *  0 - everything else
+         *  1 - nested mapgen
+         *  2 - transforms and faction ownership
+         */
+        virtual int phase() const {
+            return 0;
```
Comment (ZhilkinSerg) [inline src/mapgen.h:181]: Maybe we should use some constants instead of magic numbers?

Comment (kevingranade) [reply src/mapgen.h:181]: Seems like a perfect use case for a little enum.
