### PR TITLE
Fix zone sorting and category display in advanced inventory UI.

### LINKED ISSUE #41037: Autosort doesn't sort Items in Containers
# Describe the bug

Items which are stored in Containers are ignored by autosort as long as they are in a Container and always are Sorted to the Container Zone

# Steps To Reproduce

1. Spawn some Food, Drink, Medicine Items which are stored in Containers.
2. Set Zones to Sort Items
3. All items are sortet in the Container Zone

# Expected behavior

Containers designed to sort one item should be sortet together with contained item, or else autosort would be not possible with liquids

# Screenshots

Screenshoot 1

Red are expectet sortet Zones Green is the Zone it is actualy sortet to

Screenshot 2

Green Zone

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2769-gf387ce8 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    No Fungal Monsters [No_Fungi],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by EvgenijM86**
#### Summary

SUMMARY: Bugfixes "Fix zone sorting and category display in advanced inventory UI."

#### Purpose of change

Fix #41037
And also change category display in advanced inventory UI.

#### Describe the solution

Add a bool flag in get_category() that controls if we want to get category of the items itself, or it's contents. Set that flag too true in 3 places (false by default).

#### Describe alternatives you've considered

None.

#### Testing
Containers display correct category, depending on their contents.
Zone sorting seems to place containers in correct zones, depending on their contents.

#### Additional context
image

### CODE REVIEW

**Comment by EvgenijM86** [comment]
Note: category is now dynamic and depends on container contents. If category values are cached in zone and advanced inventory UI AND are not updated when item is updated, then it may lead to outdated category being displayed. So far I have not seen this happened. But maybe someone who knows the code of Zone manager or advanced inventory UI should review this before merging.

File: src/item.h [hunk 1]
```diff
@@ -462,7 +462,8 @@ class item : public visitable<item>
         bool burn( fire_data &frd );
 
         // Returns the category of this item.
-        const item_category &get_category() const;
+        // If (insides == true) returns the category of item inside this item. I.e. "can of meat" would be food, instead of container.
+        const item_category &get_category( bool insides = false ) const;
```
Comment (BevapDin) [inline src/item.h:466]: Please consider making this a separate function instead of adding a boolean parameter.

Reading `it.get_category( true )` doesn't tell the reader what the boolean means. It could related to anything, not just items in containers.

File: src/item.cpp [hunk 2]
```diff
@@ -8415,10 +8416,16 @@ void item::set_snippet( const snippet_id &id )
...
 
-const item_category &item::get_category() const
+const item_category &item::get_category( bool insides ) const
 {
     static item_category null_category;
-    return type->category_force.is_valid() ? type->category_force.obj() : null_category;
+    if( insides && type->category_force == item_category_container &&
+        contents.num_item_stacks() == 1 ) {
+        const item &ci = contents.only_item();
+        return ci.type->category_force.is_valid() ? ci.type->category_force.obj() : null_category;
```
Comment (BevapDin) [inline src/item.cpp:8425]:
```suggestion
        return ci.get_category();
```
Or possibly this, in case the contained item is a container as well (e.g. a bottle of something within a backpack).
```suggestion
        return ci.get_category( true );
```

File: src/item.h (hunk 1 above)
Comment (EvgenijM86) [reply src/item.h]: Done.

File: src/item.cpp (hunk 2 above)
Comment (EvgenijM86) [reply src/item.cpp]: I have picked ci.get_category() for now. I don't know if multiple nested containers should be classified by the items that is store in the innermost container. Like, if we have 10 nested backpacks with a single aspirin pill - is that pile of stuff really drugs, or is it containers simply because there are more containers than actual contents?
