### PR TITLE
Moved Stats window modifiers out to Info window

### LINKED ISSUE #23489: Number for ranged penalty in player menu displaced by 1
Game version: ae5bdc0

Operating system: GNU/Linux

Tiles or curses: curses

Mods active: N/A

### Expected behavior
In the player menu, all numbers align nicely.

### Actual behavior
In the player menu (@), go to “Dexterity”.
The number for ranged penalty seems to be slightly misplaced (off-by-one), compared to the other numbers.

### Steps to reproduce the behavior
* In the player menu (@), go to “Dexterity”.
* Look at the numbers

### PR DESCRIPTION
**Pull request by gastamper**
This PR resolves #23489 and #23487 by moving the Stats window modifiers out to the Info window, as below:
capture

This PR *does* however leave unresolved the issue of the line referenced in #23487 being extremely long and fitting poorly within the general length of the other similar strings, but is left untouched since the change to that line probably warrants some discussion.  As a compromise, the start point of the lines for Dexterity was pushed out to 37 to accommodate the offending string.

### CODE REVIEW

**Comment by illi-kun** [comment]
> This PR does however leave unresolved the issue

This PR closes the mentioned issue completely, because now the line about penalty fits the window. No need to keep the issue open just because one line a bit longer than others.

Good job!

File: src/player_display.cpp [hunk 1]
```diff
@@ -677,60 +677,56 @@ Strength - 4;    Dexterity - 4;    Intelligence - 4;    Perception - 4" ) );
                 if( line == 0 ) {
                     // Display player current strength effects
                     mvwprintz( w_stats, 2, 1, h_light_gray, _( "Strength:" ) );
-                    mvwprintz( w_stats, 6, 1, c_magenta, _( "Base HP:" ) );
```
Comment (illi-kun) [inline src/player_display.cpp]: Comments about current effects from stats should be moved\removed, because these effects described in another place now.

Comment (gastamper) [reply src/player_display.cpp]: Thanks for catching that, I've added a commit which clarifies the comments in question.
