### PR TITLE
Make Solar Sensitivity mutation respect clothing coverage, precious

### LINKED ISSUE #43133: Solar Sensitivity deals damage to all limbs despite 100% coverage.
# Describe the bug
The mutation Solar Sensitivity, and some of its connected mutations, Light Sensitive, Very Light Sensitive and Troglobite, do not seem to take clothing coverage into account, resulting in Solar Sensitivity dealing damage to all limbs and the lesser versions of it applying negative effects to stats and pain.

# Steps To Reproduce

1. Get Solar Sensitivity mutation.
2. Equip Thermal Electric Outift (convenient 100% coverage on all bodyparts except eyes), equip sunglasses. (Alternatives: ANBC Suit or Zentai)
3. Step into the sun and witness the damage received.

# Expected behavior

Clothing coverage is taken into account, just like with the Albino trait. If the sun doesn't reach the skin, it can't deal damage.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-4920-g6a34646 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

The sun, it burns. _Hissss!_

### PR DESCRIPTION
**Pull request by wapcaplet**
#### Summary

SUMMARY: Balance "Make Solar Sensitivity mutation respect clothing coverage, precious"

#### Purpose of change

The Solar Sensitivity mutation is too simplistic. No matter if you are naked or completely clothed, the sun burns all body parts at the same rate. In a bikini or a burka, being in full sun will burn you to death in 10-15 minutes. But not to worry - all you need to do is wield an umbrella, and you will be 100% safe.

Instead, this mutation should consider how exposed each body part is, and apply pain and injury effects in proportion to how much skin is exposed to the sun.

Fix #43133 

#### Describe the solution

The `Character::suffer_from_albinism` provides much of the logic needed, but needs factoring out and generalization first (and a little documentation and testing wouldn't hurt either).

Adds new functions to the `Character` class:
- `Character::bodypart_exposure` to map each bodypart to how exposed it is (0.0: covered, 1.0: naked)

Refactor:
- `Character::suffer_from_albinism` to `suffer_from_sunburn`, now handling both `ALBINO` and `SUNBURN` (Solar Sensitivity) effects and damage. Commented to explain the logic, since it's somewhat lengthy now.

Add tests:
- `tests/char_exposure_test.cpp` covering a simple example of overlapping ... coverage
- `tests/char_suffering_test.cpp` covering most effects of albinism and solar sensitivity

#### Describe alternatives you've considered

The legacy calculation for Solar Sensitivity applies damage to all body parts at a chance of one-in-10-turns. Instead, perhaps the exposure for each part could determine its chance of being hurt - and since clothing coverage is fairly easy to come by, I think a fair baseline to start with would be for 90% coverage to give the same 1-in-10 chance of injury. Then the chance of injury to a body part can be inversely proportional to how much coverage it has:

- 100% covered: No chance of injury, completely safe from sun
- 90% covered: 10% chance of injury per turn, body part death in 10-15 minutes (at 84 hp default)
- Half-clothed: 50% chance
- Naked: 100% chance of injury every turn, death in less than 2 minutes

~~I have not implemented this yet, just talking it through to myself on this draft PR so it's available for comment and discussion. I welcome other suggestions!~~ This is now basically the way it's implemented.

Considered factoring out a separate function for each of these two related mutations, but so much of the logic is similar that it ended up being cleaner to just do it all in `suffer_from_sunburn` with a couple clauses for the two different mutations. This leaves more opportunity for dropping in an intermediate mutation, and/or to one day factor out common effects (like pain and focus loss) into JSON data. That is all just speculation for now.

#### Testing

Run `tests/cata_test '[suffer]'`

Playtest with different clothing coverages; see that each body part can be irritated or damaged at different rates. See that sunglasses are still essential, not just to *look* cool, but to *be* cool, stay focused, and keep your wits about you.

#### Additional context

Some details still nag at me, and I am not super confident of the reliability of these tests (especially the pain tests, that can vary wildly), but I'm at a good stopping point and can't bear to look at this one any longer, so anything else will have to wait for a future PR.

### CODE REVIEW

**Comment by Fris0uman** [comment]
Can this be used to handle mutations with lmunation?  There's a bit of code somewhere to make you emit less or no light if the bodypaet that's supposed to glow is covered.

**Comment by wapcaplet** [comment]
> Can this be used to handle mutations with lmunation? There's a bit of code somewhere to make you emit less or no light if the bodypaet that's supposed to glow is covered.

@Fris0uman Maybe - I think I see the code you are thinking of in `Character::active_light`. It's checking a lot of other flags like `SEMITANGIBLE`, `PERSONAL`, and `AURA`, but aside from that it looks like it's using the same kind of overlapping-coverage calculation, so it could be refactored to use the new `bodypart_coverage` function. Not sure how much benefit it would give, maybe save a few lines. This function looks like it would be easy to write tests for, at least.

**Comment by wapcaplet** [comment]
This character with Solar Sensitivity wears a t-shirt (90% coverage, torso only), motorcycle pants (100% coverage, legs), filter mask and rain hood (100% to mouth and head, to prevent all head damage). The left hand has a 5% coverage wristwatch:

image

The right hand, both arms, and both feet are completely exposed, and take the most damage. Since hand damage combines with arm damage, this leads to the arms being damaged the fastest, then legs (from bare feet), and somed to the partly-exposed torso. After 12 minutes in the blazing sun, it's looking pretty dire for the arms (and the wristwatch didn't give much protection):

image

The legs could be doing better if we got some socks, and the torso's alright but another 90% layer over that T-shirt would cut damage to 1%. Much of the pain comes from not having sunglasses on.

**Comment by wapcaplet** [comment]
Here's another Solar Sensitivity character who's better prepared. Only the feet are 100% protected, but the torso and arms have two 90% layers (leaving only 1% exposure), and the balaclava, gloves, and pants all give 95%. Plus, some nice sunglasses to shade the eyes and cut down on the pain:

image

This character was able to spend 20 minutes out in the sun, and lost only 1-4 hit points on the exposed parts. The pain is still pretty bad:

image

**Comment by wapcaplet** [comment]
One last example for Solar Sensitivity, a fully-kitted character in light survivor gear, which provides 100% coverage to all body parts:

image

However, nobody likes running around with mouth encumbrance, so the mouth remains fully exposed, and that's a problem for this dude, since mouth damage stacks with head damage. It's manageable, but unless this character effectively keeps his mouth covered in the daylight, it'll cause a fair amount of pain and damage to the head:

image

**Comment by wapcaplet** [comment]
One last but critically important scenario, the ultimate protection - an umbrella and sunglasses. This Solar-Sensitivity-cursed character has just spent the last 35 minutes out in the sun, wearing only sunglasses and a wristwatch - but wielding an umbrella. That amount of time in the sun would straight up kill most vampires, but there is no pain, no injury, just a bit hungry is all, as it should be:

image

But as soon as a zombie comes along, better be ready to fight it off:

image

Umbrella-fu saves the day!

File: src/suffer.cpp [hunk 1]
```diff
@@ -794,16 +783,73 @@ void Character::suffer_in_sunlight()
...
 }
 
-void Character::suffer_from_albinism()
+std::map<bodypart_id, float> Character::bodypart_exposure()
+{
+    std::map<bodypart_id, float> bp_exposure;
+
+    // Set of all body parts affected by clothing coverage
+    // FIXME: Factor this out (same list is used in player.cpp)
+    body_part_set affected_bp { {
```
Comment (Fris0uman) [inline src/suffer.cpp:792]: could this be move the json definition of the mutation? There might already be an affected body part entry there.

File: tests/char_suffer_test.cpp [hunk 2]
```diff
@@ -0,0 +1,335 @@
...
+#include "player_helpers.h"
+
+// Tests for Character suffering
+//
+// Covers functions:
+// - Character::suffer_from_sunburn
+
+// Main body parts that can have HP loss
+const std::vector<bodypart_str_id> body_parts_with_hp{
+    bodypart_str_id( "head" ), bodypart_str_id( "torso" ),
```
Comment (Fris0uman) [inline tests/char_suffer_test.cpp:16]: you could replace this with get_all_bodyparts( true )

File: src/suffer.cpp (hunk 1 above)
Comment (wapcaplet) [reply src/suffer.cpp:792]: I do not see any fields in mutations that could be used for affected body parts - we have numerous other fields that include body parts like "lumination", "no_cbm_on_bp", "armor", "encumbrance_covered", "wet_protection", and "restricts_gear", but it's not clear how I might repurpose those for this, and I'm hesitant to add even more fields, at least not in this PR.

File: tests/char_suffer_test.cpp (hunk 2 above)
Comment (wapcaplet) [reply tests/char_suffer_test.cpp:16]: I did it this way here because I needed the name of the body part, which I could not figure out how to get from `bodypart_id` (which just uses integers). `Creature::get_all_body_parts( true )` returns `bodypart_id`, not `bodypart_str_id`.

Do you know of some way to get the part name from a `bodypart_id`?

Comment (jbytheway) [reply tests/char_suffer_test.cpp:16]: `int_id` offers access to the underlying part, just like `string_id` does.  So you can just do
```c++
bodypart_id bp = ...;
bp->name();
```
Also, you can convert between `int_id` and `string_id` using the `id()` member function; you're already doing this in the `suffer.cpp` code.

File: src/suffer.cpp (hunk 1 above)
Comment (Fris0uman) [reply src/suffer.cpp:792]: You're right, maybe I meant to add that at some point and then didn't... U_U" Disregard this suggestion then ^^"

Comment (jbytheway) [reply src/suffer.cpp:792]: Shouldn't this one *also* just use `get_all_body_parts`?  Is it different from the list of all body parts?

File: tests/char_exposure_test.cpp [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+    bodypart_id leg_r = bodypart_str_id( "leg_r" );
+    bodypart_id foot_l = bodypart_str_id( "foot_l" );
+    bodypart_id foot_r = bodypart_str_id( "foot_r" );
+
+    std::map<bodypart_id, float> bp_exposure;
+
+    GIVEN( "nothing is worn" ) {
+        dummy.worn.clear();
+
+        THEN( "exposure is 100%% on all body parts" ) {
```
Comment (jbytheway) [inline tests/char_exposure_test.cpp:32]: Should the `%` characters be escaped in this context?  I wouldn't have thought so.

Comment (wapcaplet) [reply tests/char_exposure_test.cpp:32]: You are right, looks like it is not necessary. I had done the same for several previous test cases, but forget why - could be just Vim's syntax highlighting steered me wrong. Will adjust.

File: tests/char_suffer_test.cpp (hunk 2 above)
Comment (wapcaplet) [reply tests/char_suffer_test.cpp]: @jbytheway Thanks - I tried `bp->name()` but it did not work for me (giving the below error from clang) but I got it working well with `bp.id().str()` so I went with that for now.

```
char_suffer_test.cpp:219:30: error: type 'const translation' does not provide a call operator
                    CAPTURE( bp->name() );
                             ^~~~~~~~
```

File: src/suffer.cpp (hunk 1 above)
Comment (wapcaplet) [reply src/suffer.cpp]: Sure enough, this list has all the same parts as `get_all_body_parts` now (it used to exclude the eyes, but not anymore). So this function became somewhat simpler in 146ef9d81

**Comment by wapcaplet** [comment]
Thank you @Fris0uman and @jbytheway for the reviews. I believe I've addressed your concerns in the latest updates.

File: tests/char_suffer_test.cpp (hunk 2 above)
Comment (jbytheway) [reply tests/char_suffer_test.cpp]: Ad, so you wanted the id; I thought you meant the translated name.

File: src/suffer.cpp [hunk 4]
```diff
@@ -794,16 +783,61 @@ void Character::suffer_in_sunlight()
...
         return;
     }
+
+    std::string sunlight_effect;
+    if( has_trait( trait_ALBINO ) || has_effect( effect_datura ) ) {
+        // Albinism and datura have the same effects, once per minute on average
+        if( !one_turn_in( 1_minutes ) ) {
+            return;
+        }
+        sunlight_effect = "The sunlight is really irritating";
```
Comment (ZhilkinSerg) [inline src/suffer.cpp:826]:
```suggestion
        sunlight_effect = _( "The sunlight is really irritating" );
```

File: src/suffer.cpp [hunk 5]
```diff
@@ -794,16 +783,61 @@ void Character::suffer_in_sunlight()
...
+    } else if( has_trait( trait_SUNBURN ) ) {
+        // Sunburn effects occur about 3 times per minute
+        if( !one_turn_in( 20_seconds ) ) {
+            return;
+        }
+        sunlight_effect = "The sunlight burns";
```
Comment (ZhilkinSerg) [inline src/suffer.cpp:832]:
```suggestion
        sunlight_effect = _( "The sunlight burns" );
```

File: src/suffer.cpp (hunk 4 above)
Comment (wapcaplet) [reply src/suffer.cpp:826]: Good catch, thanks! Fix incoming.

File: src/suffer.cpp (hunk 5 above)
Comment (wapcaplet) [reply src/suffer.cpp:832]: Thanks, fix is on the way.

**Comment by wapcaplet** [comment]
Failing tests in CI, seem unlikely to be related to my changes:

```
C:\Projects\Cataclysm-DDA\tests\string_formatter_test.cpp(31): FAILED:
  CHECK( original_result == expected )
with expansion:
  "0" == "1"
with messages:
  serial := 155
  format := "%.0f"
```

```
Randomness seeded to: 1598880526

-------------------------------------------------------------------------------
bionics
  bio_batteries
-------------------------------------------------------------------------------
bionics_test.cpp:104
...............................................................................

player_helpers.cpp:173: FAILED:
  REQUIRE( p.has_active_bionic( bioid ) )
with expansion:
  false
with messages:
  no power capacity at first
```

**Comment by wapcaplet** [comment]
Travis CI is now failing on the `DRAGON_BLACK` mutation tests that I have seen failing in other PRs:

```
MOD>       Given: The player has all pre-threshold mutations for DRAGON_BLACK
MOD>        Then: DRAGON_BLACK is the strongest category
MOD>        Then: Threshold breach chance is at least 0.2
MOD>        Then: Threshold breach chance is at most 0.4
```
