### PR TITLE
Stop aiming if you lost your gun.

### LINKED ISSUE #11453: pulling aiming weapon crashes game
If a zombie technician pulls your weapon away from you while you are aiming with it, game will crash.

(well game crashed twice while firing at technicians, might be something else too)

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/9164460-pulling-aiming-weapon-crashes-game?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by kevingranade**
Fixes #11453 
Just bails out of the aiming loop when it detects the player is unarmed.

### CODE REVIEW

File: src/player_activity.cpp [hunk 1]
```diff
@@ -141,6 +141,11 @@ void player_activity::do_turn( player *p )
             break;
         case ACT_AIM:
             if( index == 0 ) {
+                if( !p->weapon.is_gun() ) {
```
Comment (DavidKeaton) [inline src/player_activity.cpp]: hah, I just finished the fix for this. dangit!
