### PR TITLE
Remove 0.F artifact migration

### LINKED ISSUE #63939: [XEDRA Evolved] Certain spell artifacts turns into normal artifact after save load
### Describe the bug

Certain artifacts, like `muscles` turns into normal artifacts after saving the game and then load the save.

### Attach save file

N/A

### Steps to reproduce

1. spawn in a bunch of `muscles`,
2. save and quit,
3. load into said save,
4. normal artifacts.

### Expected behavior

not morphing into normal type of artifacts.

### Screenshots

Before a save/load
Screenshot_20230305-000525

After
Screenshot_20230305-001225

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: samsung; Model: SM-A710F; Release: 7.0; Incremental: A710FXXU2CRC2; 
- Game Version: c1e38de [32-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No scent tracking zombies [no_scent_tracking_zombies],
    Magiclysm [magiclysm],
    Xedra Evolved [xedra_evolved]
]

### Additional context

Apparently some artifacts don't change, like `hurricane lamp with thorns`.

### PR DESCRIPTION
**Pull request by Maleclypse**
#### Summary
None

#### Purpose of change
Removes the 0.F Artifact migration that was eating a bunch of artifacts on load. Should fix #63939

#### Describe the solution
Removes artifact migrations that say "Remove after 0.F"

#### Describe alternatives you've considered
Waiting for someone else to do this.  I do hope irwss checks my solution.

### CODE REVIEW

**Comment by Maleclypse** [comment]
@irwiss I forgot to at you in the description when I mentioned I hope you look over this.

**Review by irwiss — APPROVED** [review]
That's all that came up when I looked at this migration yep, git blame also shows #42137 as the PR that introduced the migration so that should be all of it

File: src/savegame_json.cpp [hunk 1]
```diff
@@ -3200,17 +3182,6 @@ void item::deserialize( const JsonObject &data )
 }
 
 void item::serialize( JsonOut &json ) const
-{
```
Comment (irwiss) [inline src/savegame_json.cpp:3203]: Ah you axed a bracket
