### PR TITLE
Fix scenarios that change starting year doing so incorrectly on first load

### LINKED ISSUE #81287: Next summer scenario don't change year
### Describe the bug

Next summer scenario don't change year at first launch, its only change the season

But, if you start creating character with next summer scenario with incorrect date
then abort it before finish
then delete world
And start creating character again with next summer scenario again
In this case the year will be correct

### Attach save file

N/A

### Steps to reproduce

Don't have other world or characters
Close game
Launch game
Start creating character
Choose "Next summer" scenario
See incorrect day
Start game
You can see through debug menu or diary(by creating new page), that year is incorrect, and zombies are not strong enough 

### Expected behavior

Correct date of next summer scenario

### Screenshots

Image

Image

Image

### Versions and configuration

OS: Windows
OS Version: 10.0.19045.5854 (22H2)
Game Version: cdda-experimental-2025-06-14-1819 [64-bit]
Graphics Version: Tiles
Game Language: Русский [ru]
Mods loaded: [
Dark Days Ahead [dda],
Disable NPC Needs [no_npc_food],
Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by EvanKozak**
#### Summary
Bugfixes "Fix incorrect date from starting year scenarios on first load"

#### Purpose of change
Fixes #81287

The Next Summer scenario, and any other scenario that changes the start year of the game or the cataclysm to anything higher than 1 (in vanilla, just Brave New World), load an incorrect date whenever you create a character after first opening the game but load properly if you abort and create another one.

#### Describe the solution
`scenario::load()` uses `calendar::year_length()`, which ultimately relies on `cur_season_length`, to calculate the game and cataclysm start dates. In `game::setup()`, the call to load modfiles (which calls `scenario::load()`) happens before the call to set `cur_season_length`, so when `calendar::year_length()` gets used on a first load, it uses `cur_season_length`'s default value of 1 which causes the incorrect date bug. 

In `tests/test_main.cpp` the call to set `cur_season_length` *is* before the call to load modfiles, so that's why the bug isn't present in the test suite and doesn't get caught by`tests/start_date_test.cpp`.

My solution is to use the option for SEASON_LENGTH instead of `calendar::year_length()` to calculate the date in `scenario::load()`, which has the benefit of making the scenarios load correctly regardless of when `cur_season_length` is set. `scenario::load()` does this for the day and season parts of the calculation already. 

I also moved the season set calls before the calls to load modfiles to make it consistent with `tests/test_main.cpp` and in case anything else relies on `cur_season_length` being set.

#### Describe alternatives you've considered
I considered just moving the season set calls, which also fixes the bug, but I think this solution is better for the reasons above.

#### Testing
Open game with existing world
Create custom character
Select The Next Summer (and Brave New World) scenarios
See that start of game is correct

Open game with no worlds 
Create custom character
Select The Next Summer (and Brave New World) scenarios
See that start of game is correct

Both are incorrect before changes.
Both are correct after change including without moving season set calls before load modfiles call.

Also tried moving the season set calls to happen after the load modfiles call in `tests/test_main.cpp` which caused `tests/start_date_test.cpp` to properly fail.

### CODE REVIEW

File: src/scenario.cpp [hunk 1]
```diff
@@ -115,6 +115,8 @@ void scenario::load( const JsonObject &jo, std::string_view )
     optional( jo, was_loaded, "eoc", _eoc, auto_flags_reader<effect_on_condition_id> {} );
 
     if( !was_loaded ) {
+        const time_duration year_length = time_duration::from_days( get_option<int>( "SEASON_LENGTH" ) ) *
```
Comment (RenechCDDA) [inline src/scenario.cpp]: This should not be decoupled from calendar::year_length(). Either calender::year_length() is correct (and it should be used) or it is wrong and it should be fixed. We should not be doing math for how long a year is outside of the calendar namespace.

Comment (EvanKozak) [reply src/scenario.cpp]: Okay, I changed it to just set the season length before load_world_modfiles() and added a comment about the order. I checked again in-game, and the bug is still fixed like this.

**Comment by Maleclypse** [comment]
Thanks!
