### PR TITLE
fixes for removing integrated armor on mutation

### LINKED ISSUE #58005: Mutating Protective Bark and Shifting Bark doesn't remove worn rigid gear that conflicts.
### Describe the bug

Mutating these two won't immediately remove conflicting armor or clothing, but doesn't allow it to be put back on if it is taken off. 

### Steps to reproduce

1. Wear rigid gear, such as a helmet on the head.
2. Mutate protective bark or shifting bark via any methods.
3. Conflicting rigid gear will not be removed.

### Expected behavior

Rigid gear immediately removed upon mutating.

### Screenshots

image
Debug used to mutate quickly.

### Versions and configuration

MacOS 12.3.1
Experimental Version cd180bf
Tiles
English Language

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bombasticSlacks**
#### Summary
None

#### Purpose of change
fixes #58005

#### Describe the solution
Adds a new JSON list for specifying limbs to remove rigid armor from, also checks directly against any of the mutations integrated armors.

If the armor and the integrated are rigid on the same part, you remove the armor.

#### Describe alternatives you've considered
Do the calculation for the integrated armor bp list earlier, but there isn't a convenient finalize for it. Shouldn't be too expensive.

#### Testing
Spawned in, gave myself rigid armor. Mutated bark.

#### Additional context
image

### CODE REVIEW

File: src/mutation.cpp [hunk 1]
```diff
@@ -362,6 +365,39 @@ bool mutation_branch::conflicts_with_item( const item &it ) const
...
+    // this also seems to check the armor against itself, logic should be skipped by the integrated check
+    for( const itype_id &integrated : integrated_armor ) {
+        if( it.has_flag( json_flag_INTEGRATED ) ) {
+            // skip other integrated armor, that should be handled with other rules
+            continue;
+        }
+
+        item tmparmor = item( integrated );
+        for( const sub_bodypart_id &sbp : tmparmor.get_covered_sub_body_parts() ) {
+            if( ( tmparmor.is_bp_rigid( sbp ) ) && it.covers( sbp ) && ( it.is_bp_rigid( sbp ) ) ) {
```
Comment (Night-Pryanik) [inline src/mutation.cpp:392]:
```suggestion
            if( tmparmor.is_bp_rigid( sbp ) && it.covers( sbp ) && it.is_bp_rigid( sbp ) ) {
```

File: src/mutation.cpp [hunk 2]
```diff
@@ -362,6 +365,39 @@ bool mutation_branch::conflicts_with_item( const item &it ) const
...
+bool mutation_branch::conflicts_with_item_rigid( const item &it ) const
+{
+    for( const bodypart_str_id &bp : remove_rigid ) {
+        if( it.covers( bp.id() ) && it.is_bp_rigid( bp.id() ) ) {
+            return true;
+        }
+    }
+
+    for( const sub_bodypart_str_id &bp : remove_rigid_subparts ) {
+        if( it.covers( bp.id() ) && it.is_bp_rigid( bp.id() ) ) {
```
Comment (Night-Pryanik) [inline src/mutation.cpp:377]:
```suggestion
        if( it.covers( bp.id() && it.is_bp_rigid( bp.id() ) {
```

File: src/mutation.cpp [hunk 3]
```diff
@@ -362,6 +365,39 @@ bool mutation_branch::conflicts_with_item( const item &it ) const
     return false;
 }
 
+bool mutation_branch::conflicts_with_item_rigid( const item &it ) const
+{
+    for( const bodypart_str_id &bp : remove_rigid ) {
+        if( it.covers( bp.id() ) && it.is_bp_rigid( bp.id() ) ) {
```
Comment (Night-Pryanik) [inline src/mutation.cpp:371]:
```suggestion
        if( it.covers( bp.id() && it.is_bp_rigid( bp.id() ) {
```
