### PR TITLE
Fix item with the same relic_data stack

### LINKED ISSUE #45542: Items with relic_data don't stack
# Describe the bug
Usually,the completly same item(same attributes) will stack together to save the looking-space of invertory.
but now,if the item has a relic_data,It will be showen one by one in your invertory,even if they have the same attributes

If you have 20 strenght-ring in your pockets,in the past,it will show '20 strenght-rings'in one line,but now,it will show 'strenght-ring' for 20 lines,it makes the invertory menu ugly and hard to use.

# Steps To Reproduce
1.debug for 30 strenght-ring(with Magiclysm mod)
2.open [i]nvertory menu.

# Expected behavior
They should stack together again.

# Screenshots
image

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7642-gac49e40 [64-bit]
- Graphics Version: Tiles
- Game Language: 系统语言 []
- Mods loaded: [
    浩劫余生 [dda],
    禁用NPC需求 [no_npc_food],
    C.R.I.T 扩展 [crt_expansion],
    Blaze 载具工业 [blazeindustries],
    大魔法 [magiclysm],
    余波未尽 [aftershock],
    恐龙世界 [DinoMod],
    Zetsukaze's Hair - 0.E EDIT [zets_hair_extensions_undead],
    疯狂大灾变 [crazy_cataclysm],
    神话武术 [MMA],
    移除真菌类怪物 [No_Fungi],
    Fuji的军事职业Mod [fuji_mpp],
    技能提升属性 [StatsThroughSkills],
    敏捷速度加成 [speedydex],
    杀怪提升属性 [stats_through_kills],
    余震个人用强化模组 [After_Shock_Personal_UsageMod],
    坦克mod:复活 [Tankmod_Revived],
    阻止僵尸复活 [no_reviving_zombies_fix],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    DinoMod - UndeadPeople Tileset [DinoModUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Tankmod: Revived - UndeadPeople Tileset [Tankmod_RevivedUDP],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP]
]

# Additional context

### PR DESCRIPTION
**Pull request by MikuMiddo**
#### Summary
SUMMARY: BugFixes "Fix item with the same relic_data stack"

#### Purpose of change
Fixes #45542 

#### Describe the solution
The items that have relic_data is widerly used in kinds of mods,and most of time,item with relic_data is not an artifact.So they should stack together in one line rather than sorted in invertory one by one.
I add two operator overload for `relic==relic` and `enchantment==enchantment`.
Also change the stack check function to `if( is_relic()&&!(*relic_data==*rhs.relic_data ))`
@anothersimulacrum provided this idea,thanks!

#### Describe alternatives you've considered
A friend told me that I can also add a [FLAG] to control the stack_with,but I thought that It will just make the modder more confuse with the flag system.

#### Testing
Tried to debug for item with same relic_data,and change the relic_data in json,then debug for them.Working properly.
Items before debug
image
Debug for Items with same relic_data
image
Debug for Items with different relic_data
QQ图片20201203204718

### CODE REVIEW

File: src/relic.cpp [hunk 1]
```diff
@@ -693,3 +693,24 @@ relic relic_procgen_data::generate( const relic_procgen_data::generation_rules &
...
+    is_the_same &= (source_relic.charges_per_use() == target_relic.charges_per_use());
+    is_the_same &= (source_relic.has_activation() == target_relic.has_activation());
+    is_the_same &= (source_relic.has_recharge() == target_relic.has_recharge());
+    is_the_same &= (source_relic.max_charges() == target_relic.max_charges());
+    is_the_same &= (source_relic.name() == target_relic.name());
+
+    is_the_same &= (source_relic.get_enchantments().size() == target_relic.get_enchantments().size());
+    if (is_the_same) 
+    {
+        for (int i = 0; i < source_relic.get_enchantments().size(); i++)
```
Comment (BrettDong) [inline src/relic.cpp:710]:
```suggestion
        for (std::size_t i = 0; i < source_relic.get_enchantments().size(); i++)
```

File: src/relic.h [hunk 2]
```diff
@@ -223,6 +223,8 @@ class relic
 
         // what is the power level of this artifact, given a specific ruleset
         int power_level( const relic_procgen_id &ruleset ) const;
+
+        friend bool operator==( relic source_relic, relic &target_relic );
```
Comment (anothersimulacrum) [inline src/relic.h:227]:
```suggestion
        friend bool operator==( const relic &source_relic, const relic &target_relic );
```
