### PR TITLE
Prevent auto attacking allies

### LINKED ISSUE #36375: Autocombat (TAB) tries to move into friendly robots
# Describe the bug

When using autocombat (pressing TAB by default) adjacent to a friendly robot, player character will attempt to move into the robot triggering the disable/swap prompt. This makes melee combat with robotic allies helping you extremely annoying and tedious (can't use tab because of the prompt spam).

# Steps To Reproduce

1. Stand adjacent to a zombie and a friendly robot.
2. Press tab or whatever button you have for autocombat.
3. Sometimes you will hit the zombie, sometimes you will be prompted to swap positions with your robot.

# Expected behavior

Friendly robots aren't treated as acceptable targets for autocombat. Pressing tab when adjacent to both ally and enemy always attacks the enemy. Pressing tab when adjacent to an ally and no enemies doesn't trigger the disable/swap promt and waits a turn instead.

# Versions and configuration

 - OS: win10
 - Game Version: 0.D-10626-gb9b3dc2
 - Graphics version: tiles
 - Mods loaded: none

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Prevent auto attacking allies"

#### Purpose of change
Fixes #36375
 

#### Describe the solution
Moved check for attitude from only being done for ranged usage to being done for it and autoattack.

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -6379,7 +6379,7 @@ std::vector<Creature *> player::get_visible_creatures( const int range ) const
 std::vector<Creature *> player::get_targetable_creatures( const int range ) const
 {
     return g->get_creatures_if( [this, range]( const Creature & critter ) -> bool {
-        return this != &critter && pos() != critter.pos() && // TODO: get rid of fake npcs (pos() check)
+        return this != &critter && pos() != critter.pos() && attitude_to( critter ) != Creature::Attitude::A_FRIENDLY &&// TODO: get rid of fake npcs (pos() check)
```
Comment (ZhilkinSerg) [inline src/player.cpp]:
```suggestion
        // TODO: get rid of fake npcs (pos() check)
        return this != &critter && pos() != critter.pos() && attitude_to( critter ) != Creature::Attitude::A_FRIENDLY &&
```
