### PR TITLE
Fix liquid handling

### LINKED ISSUE #14731: Water collection long action is broken.
Build 4143

It's defaulting to a single action of ten water units each time you examine a water source and attempt to fill a container - item type containers, not vehicle tanks. Doesn't matter if it's in your hands, your inventory, in a vehicle trunk, or on the ground.

### PR DESCRIPTION
**Pull request by BevapDin**
The main liquid handling function now displays a menu with the available actions (when declining to chose a container item):
- pour into nearby vehicle (one entry for each suitable nearby vehicle, excluding the source vehicle, if any),
- pour onto ground / into a keg (furniture),
- consume (if food).

This can be extended for other targets.

It starts a player activity if references to the source and the target can be stored somewhere. This is not always possible, e.g. when handling liquid crafting results, the liquid doesn't exist as persistent item until it is fully handled.

I added a few wrapper functions to allow callers to show their intend:
- `handle_all_liquid` forces the player to handle all of the liquid, no player activity started (because the function does not know where the liquid comes from). It basically calls `handle_liquid` until all has been handled.
- `consume_liquid` similar to the above, but may return early if the player _explicitly_ cancels the action. (See return value of `handle_liquid`.)
- `handle_liquid_from_ground` handles liquid on the ground, including the removal of the item when it has been handled completely (it requires a list iterator). This may start a player activity.

`handle_liquid` is mostly like before, but its return value is different: now it returns whether the player has _chosen_ to handle the liquid.

`true` means the player tried to select some destination for the liquid. The actual transfer _may_ not have happened, but it was intended. `false` means the player outright canceled the handling. This is an important distinction for actions that can be canceled, for example unloading a tool: if the player has no place to store the (liquid) ammo, the unloading should be canceled. The new result value allows the function to be called in a loop until the player either cancels the action (finally recognized they have no suitable container at all), or they have (after possibly several attempts) found and selected a suitable target.

Player activities are started if the source is
- a tank in a vehicle, or
- an liquid item on the ground (e.g. inside a standing keg) or,
- an infinite source on the ground,
  and the target is
- a tank in a vehicle, or
- a place on the ground (or a standing keg), or
- a container in the inventory of the player.

Other combinations will be done immediately, but will consume a fixed amount of move points.

`handle_liquid` now also takes care of consuming move points. Callers don't need to do this anymore.

Fixes #14731

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -4729,11 +4729,11 @@ item &map::add_item_at( const tripoint &p,
 item map::water_from(const tripoint &p)
 {
     if( has_flag( "SALT_WATER", p ) ) {
-        item ret( "salt_water", 0 );
+        item ret( "salt_water", 0, std::numeric_limits<long>::max() );
```
Comment (mugling) [inline src/map.cpp]: ``src/map.cpp:4732:36: warning: implicit conversion from 'type' (aka 'long') to 'int' changes value from 9223372036854775807 to -1 [-Wconstant-conversion]``

File: src/map.cpp [hunk 2]
```diff
@@ -4729,11 +4729,11 @@ item &map::add_item_at( const tripoint &p,
...
         return ret;
     }
 
-    item ret( "water", 0 );
+    item ret( "water", 0, std::numeric_limits<long>::max() );
```
Comment (mugling) [inline src/map.cpp]: And again here

Comment (mugling) [inline src/map.cpp]: The `item` constructor appears to be at fault here.

We should probably define `typedef long charges_type` and gradually start migrating towards using this with the eventual goal of expressing `charges` as an `int`

File: src/game.cpp [hunk 3]
```diff
@@ -10242,245 +10242,226 @@ void game::grab()
...
+            }
+        } );
+    }
 
-    //is container selected?
-    item *cont = &( u.i_at( pos ) );
-    if( u.has_item( *cont ) ) {
-        if (cont == NULL || cont->is_null()) {
-            return -1;
+    menu.addentry( -1, true, 'g', _( "Pour on the ground / into an adjacent keg" ) );
```
Comment (mugling) [inline src/game.cpp]: Kegs are rare and should be a separate action, possibly with a direction eg. `pour in to key NW`

File: src/game.cpp [hunk 4]
```diff
@@ -10242,245 +10242,226 @@ void game::grab()
...
+        // Pre-select this one as it is the most likely one for rotten liquids
+        menu.selected = menu.entries.size() - 1;
     }
-    return -1;
+
+    if( menu.entries.empty() ) {
+        return false;
+    }
+    // Has no associated action, it's there to show that cancelling is an option.
+    menu.addentry( -1, true, MENU_AUTOASSIGN, _( "Cancel" ) );
```
Comment (mugling) [inline src/game.cpp]: Setting `menu.return_invalid = true` would allow escaping from the menu which is more consistent. It also stops the hotkey `1` being inconsistently applied to the cancel or vehicle options.

File: src/map.cpp (hunk 1 above)
Comment (BevapDin) [inline src/map.cpp]: Well, can you tell why the `qty` parameter of the item constructor is an `int`, when it is used to initialize the `charges` member, which is a `long`?

Comment (mugling) [inline src/map.cpp]: See below

> The item constructor appears to be at fault here.

File: src/map.cpp (hunk 2 above)
Comment (BevapDin) [inline src/map.cpp]: Actually, I propose changing `charges` back to `int`.

`long` and `int` are the same on many platforms (including my pretty normal Linux 32bit), so it doesn't really give any advantages. It causes other problems:

Out of curiosity, I annotated some of the printf-like functions with `__attribute__((format (printf, 1, 2)))`, which makes gcc check the supplied format string. It issues warnings if the contained format specifiers don't match the arguments.

I get several of those warnings:
```
src/iexamine.cpp:456:53: warning: format '%d' expects argument of type 'int', but argument 2 has type 'long int' [-Wformat=]
```
They are caused by code like this: `string_format( "Money left: %d", card->charges )`. Here "%d" is used to print the charges, it requires an `int`, but charges is a `long`.

File: src/game.cpp (hunk 3 above)
Comment (BevapDin) [inline src/game.cpp]: So you propose another menu entry "Pour into adjacent keg"? Or a separate entry for *each* adjacent keg ("Pour into keg (Northwest)", "Pour into keg (North)" - like it's done for the vehicles?

File: src/map.cpp (hunk 2 above)
Comment (mugling) [inline src/map.cpp]: > Actually, I propose changing charges back to int.

Yes, but this could cause a lot of subtle bugs like the one you describe above

File: src/game.cpp (hunk 3 above)
Comment (mugling) [inline src/game.cpp]: Separate entry for each keg

**Comment by mugling** [comment]
Merge conflict
