### PR TITLE
fix smartphone advanced recovery

### LINKED ISSUE #80549: Advanced Phone Recovery Does Not Work
### Describe the bug

So it seems that when looking for a hackPRO to perform an advanced phone recovery, it's looking for the physical hackPRO outside of any storage medium, in other words, you cannot perform an advanced phone recovery if you have hackPRO on a phone/laptop/memory card/USB drive. You need to debug spawn hackPRO in to be able to perform an advanced phone recovery.

### Attach save file

N/A

### Steps to reproduce

1. Have everything needed to perform an advanced phone recovery
2. Advanced phone recovery doesn't work
3. Debug spawn in hackPRO
4. Advanced phone recovery works

### Expected behavior

The expected behavior should of course be that having hackPRO on any storage medium should allow you to perform an advanced phone recovery, it seems it doesn't check for having hackPRO inside of storage devices which is an oversight.

### Screenshots

I have enough Computer skills

Image
hackPRO is on the laptop and has enough charges

Image
Advanced phone recovery is grayed out

Image
And finally after debug spawning hackPRO, advanced recovery is possible

Image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.3775 (24H2)
- Game Version: cdda-experimental-2025-04-11-0931 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Work in Progress Limb Stuff [limb_wip],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    Mining Mod [Mining_Mod],
    Bombastic Perks [bombastic_perks],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No Hope [no_hope]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MilosRasic**
#### Summary
Bugfixes "Smartphone advanced recovery fix"

#### Purpose of change

Fixes #80549

#### Describe the solution

This PR fixes the linked bug by creating and using a new EOC condition `u_has_software`, which checks if the character has a device of a certain type, with a certain number of charges and a software in it. If called without a device ID, it will match any device. If called without charges, it will match any number of charges, including devices without charges.

This also changes the original condition, which would also pass if you had a laptop with 20 charges and hackPRO on a laptop with no charges or on another smartphone.

#### Describe alternatives you've considered

Considered 100% matching the original condition, which would have been easier, but I think it was written when there were only laptops, cellphones and USB sticks. In the current state, it would pass for some weird combinations. The new condition requires hackPRO to be on the laptop with at least 20 charges, which is more realistic.

#### Testing

Loaded up a save where I have hackPRO on a laptop and a bunch of locked phones. Verified that advanced recovery can be activated and works as expected.

Also verified that basic recovery is not broken.

Moved hackPRO to a laptop with 15 charges and verified that I am not able to use advanced recovery any more.

Plugged the laptop with 15 charges and hackPRO into the power grid and verified that advanced recovery can be used and works as expected.

#### Additional context

none

### CODE REVIEW

**Comment by GuardianDll** [comment]
Please document u_has_software in effect_on_condition.md

File: src/character_inventory.cpp [hunk 1]
```diff
@@ -230,6 +230,47 @@ int Character::count_softwares( const itype_id &id )
     return count;
 }
 
+bool Character::has_software( const itype_id &software_id, int min_charges,
+                              const itype_id &device_id ) const
+{
+    map &here = get_map();
+
+    for( const item_location &it_loc : const_cast<Character *>( this )->all_items_loc() ) {
```
Comment (RenechCDDA) [inline src/character_inventory.cpp:238]: This const_cast seems completely unnecessary.

Comment (MilosRasic) [reply src/character_inventory.cpp:238]: If I remove it:

> src/character_inventory.cpp:238:40: error: 'this' argument to member function 'all_items_loc' has type 'const Character', but function is not marked const
>   238 |     for( const item_location &it_loc : all_items_loc() ) {

I tried unmarking the function as const, but then I have to also un-const the functions that are calling it, all the way up to making `actor` not const in the lambda returned by `f_has_software()`.

This works, but then I get:
> src/talker_character.cpp:716:12: error: 'this' argument to member function 'has_software' has type 'const Character', but function is not marked const
>   716 |     return me_chr_const->has_software( software_id, min_charges, device_id );

At this point, I think this course of action is no longer worth exploring because `me_chr_const` is used all over the place and expected to be const.

I've also considered marking `all_items_loc()` as const rather than casting it, but it too is used all over the place.

This seems like the least painful option.

Please let me know if you see a better way.

**Comment by MilosRasic** [comment]
> Please document u_has_software in effect_on_condition.md

done

File: src/character_inventory.cpp (hunk 1 above)
Comment (RenechCDDA) [reply src/character_inventory.cpp:238]: On review, you're correct. That's a nasty problem and I'm satisfied enough with your approach.
