### PR TITLE
Handled nowhere parent

### LINKED ISSUE #75792: segfault on save
### Describe the bug

Hi there!

Autosave in lab loads with lots of errors and all tries to re-save got segfault

### Attach save file

[Sane4eG-trimmed.tar.gz](https://github.com/user-attachments/files/16647925/Sane4eG-trimmed.tar.gz)

### Steps to reproduce

load - quick save/save & quit

### Expected behavior

at least no errors on save

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: n/a; Distributor ID: ManjaroLinux; Description: Manjaro Linux; Release: 24.0.6; Codename: Wynsdey; 
- Game Version: cdda-experimental-2024-08-09-1521 9b2ac1a [64-bit]
- Graphics Version: Tiles
- Game Language: Русский <color_dark_gray>(91,4%)</color> [ru]
- Mods loaded: [
    Тёмные Дни Впереди [dda],
    Отключить потребности у НПС [no_npc_food],
    Портальные штормы игнорируют НПС [personal_portal_storms],
    Медленный рост фунгалоидов [no_fungal_growth],
    иконка видит-игрока, HitButton_iso [sees_player_hitbutton],
    Перевод сложных диалогов [translate_dialogue],
    Скорость от ловкости [speedydex],
    Характеристики за убийства [stats_through_kills],
    Характеристики за навыки [StatsThroughSkills],
    Приручаемая живность [Tamable_Wildlife]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
Fix #75792, i.e. item location load failure crashes saving.

#### Describe the solution
Handle an item_location parent of "nowhere" by making the item_location itself "nowhere", rather than trying to move the item to the garbage location of "nowhere".

#### Describe alternatives you've considered
Try to figure out if the original error handling is incorrect for other cases and if it's even possible for other cases.
It's safer to assume it can somehow happen for other cases, so the placement of the item on the ground is a valid strategy for those cases.

#### Testing
Loaded the bug report save, quick saved, saved & quit, loaded the save again.

### CODE REVIEW

**Comment by PatrikLundell** [comment]
I agree the change only handles the symptoms of an earlier error, and the error message reflects that.
However, I think it's still worthwhile to try to handle errors as gracefully as possible.

That said, it's far superior to fix the original error if it can be located, and while I think both changes should be made if possible, I'd go with fixing a root problem if only one thing is done.

I didn't even try to look at the horrible unreadable one liners the JSON files contain, both because of the mess and because I don't have much hope of finding anything useful.

Auto saving has a history of messing up things, and I wouldn't be shocked if you can get messed up saves if you're eating from the eating menu while it kicks in (which I guess these activities represent). However, testing it might be tricky unless you can somehow trigger auto saving manually while the PC is chewing.

File: src/item_location.cpp [hunk 1]
```diff
@@ -841,6 +841,11 @@ void item_location::deserialize( const JsonObject &obj )
         item_location parent;
         obj.read( "parent", parent );
         if( !parent.ptr->valid() ) {
+            if( parent.where() == type::invalid ) {
```
Comment (mqrause) [inline src/item_location.cpp:844]:
```suggestion
            if( parent == nowhere ) {
```

Essentially the same check, just simplified.

**Review by mqrause — COMMENTED** [review]
Yeah, identifying the real cause is something between hard and impossible. On the user end, a fairly easy fix is to delete the entire backlog. But that's not that good of a solution considering it happens somewhat regularly.

But looking at the deserialization and item_location default values in general, what mostly seems unsafe to me is using `tripoint_min`. That's simply not a valid tripoint to use anywhere and the ultimate cause of the crash. But if we have no valid tripoint, I think the item_location ultimately has to become `nowhere`.
