### PR TITLE
clang -Wimplicit-int-float-conversion fixes

### LINKED ISSUE #36510: clang 10 compile issue
# Describe the bug
Clang 10 compile issue.
`
[ 32%] Building CXX object src/CMakeFiles/libcataclysm-tiles.dir/loading_ui.cpp.o
/home/developer/GitHub/gregoranders/Cataclysm-DDA.source/src/lightmap.cpp:1209:49: error: implicit conversion from 'int' to 'float' changes value from 1056478197 to 1056478208 [-Werror,-Wimplicit-int-float-conversion]
    u.i = static_cast<long long>( 6051102 * x + 1056478197 );
                                              ~ ^~~~~~~~~~
/home/developer/GitHub/gregoranders/Cataclysm-DDA.source/src/lightmap.cpp:1210:35: error: implicit conversion from 'int' to 'float' changes value from 1056478197 to 1056478208 [-Werror,-Wimplicit-int-float-conversion]
    v.i = static_cast<long long>( 1056478197 - 6051102 * x );
                                  ^~~~~~~~~~ ~
2 errors generated.
make[2]: *** [src/CMakeFiles/libcataclysm-tiles.dir/build.make:1549: src/CMakeFiles/libcataclysm-tiles.dir/lightmap.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
`

# Steps To Reproduce
compile with clang 10

# Versions and configuration
Commit: f8ba267d1ce720998b863e7ac2f90a15003d5171

clang version 10.0.0 (/var/tmp/portage/sys-devel/clang-10.0.0.9999/work/x/y/clang)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/10/bin

### LINKED ISSUE #37006: Clang 10 -Wimplicit-int-float-conversion warnings
# Describe the bug

LLVM/Clang 10 is coming soon (the LLVM team is currently scheduled to branch for 10.x within a week). There are numerous `-Wimplicit-int-float-conversion` warnings appearing when compiling with LLVM/Clang 10 (i.e. LLVM master):

```
[125/358] Building CXX object src/CMakeFiles/libcataclysm.dir/lightmap.cpp.o
../src/lightmap.cpp:1209:49: warning: implicit conversion from 'int' to 'float' changes value from 1056478197 to 1056478208 [-Wimplicit-int-float-conversion]
    u.i = static_cast<long long>( 6051102 * x + 1056478197 );
                                              ~ ^~~~~~~~~~
../src/lightmap.cpp:1210:35: warning: implicit conversion from 'int' to 'float' changes value from 1056478197 to 1056478208 [-Wimplicit-int-float-conversion]
    v.i = static_cast<long long>( 1056478197 - 6051102 * x );
                                  ^~~~~~~~~~ ~
2 warnings generated.
[171/358] Building CXX object src/CMakeFiles/libcataclysm.dir/monmove.cpp.o
../src/monmove.cpp:252:16: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
        return INT_MAX;
        ~~~~~~ ^~~~~~~
/home/steven/.apps/llvm-master/lib/clang/10.0.0/include/limits.h:46:19: note: expanded from macro 'INT_MAX'
#define INT_MAX   __INT_MAX__
                  ^~~~~~~~~~~
<built-in>:75:21: note: expanded from here
#define __INT_MAX__ 2147483647
                    ^~~~~~~~~~
../src/monmove.cpp:257:16: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
        return INT_MAX;
        ~~~~~~ ^~~~~~~
/home/steven/.apps/llvm-master/lib/clang/10.0.0/include/limits.h:46:19: note: expanded from macro 'INT_MAX'
#define INT_MAX   __INT_MAX__
                  ^~~~~~~~~~~
<built-in>:75:21: note: expanded from here
#define __INT_MAX__ 2147483647
                    ^~~~~~~~~~
../src/monmove.cpp:261:16: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
        return INT_MAX;
        ~~~~~~ ^~~~~~~
/home/steven/.apps/llvm-master/lib/clang/10.0.0/include/limits.h:46:19: note: expanded from macro 'INT_MAX'
#define INT_MAX   __INT_MAX__
                  ^~~~~~~~~~~
<built-in>:75:21: note: expanded from here
#define __INT_MAX__ 2147483647
                    ^~~~~~~~~~
../src/monmove.cpp:279:12: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
    return INT_MAX;
    ~~~~~~ ^~~~~~~
/home/steven/.apps/llvm-master/lib/clang/10.0.0/include/limits.h:46:19: note: expanded from macro 'INT_MAX'
#define INT_MAX   __INT_MAX__
                  ^~~~~~~~~~~
<built-in>:75:21: note: expanded from here
#define __INT_MAX__ 2147483647
                    ^~~~~~~~~~
../src/monmove.cpp:458:37: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
                } else if( rating < INT_MAX && rating > dist && wandf <= 0 ) {
                                  ~ ^~~~~~~
/home/steven/.apps/llvm-master/lib/clang/10.0.0/include/limits.h:46:19: note: expanded from macro 'INT_MAX'
#define INT_MAX   __INT_MAX__
                  ^~~~~~~~~~~
<built-in>:75:21: note: expanded from here
#define __INT_MAX__ 2147483647
                    ^~~~~~~~~~
5 warnings generated.
[224/358] Building CXX object src/CMakeFiles/libcataclysm.dir/options.cpp.o
../src/options.cpp:167:28: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
            thisOpt.fMax = INT_MAX;
                         ~ ^~~~~~~
/home/steven/.apps/llvm-master/lib/clang/10.0.0/include/limits.h:46:19: note: expanded from macro 'INT_MAX'
#define INT_MAX   __INT_MAX__
                  ^~~~~~~~~~~
<built-in>:75:21: note: expanded from here
#define __INT_MAX__ 2147483647
                    ^~~~~~~~~~
1 warning generated.
[245/358] Building CXX object src/CMakeFiles/libcataclysm.dir/npcmove.cpp.o
../src/npcmove.cpp:246:65: warning: implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [-Wimplicit-int-float-conversion]
    float best_rating = include_pos ? rate_pt( pos(), 0.0f ) :  INT_MAX;
          ~~~~~~~~~~~                                           ^~~~~~~
/home/steven/.apps/llvm-master/lib/clang/10.0.0/include/limits.h:46:19: note: expanded from macro 'INT_MAX'
#define INT_MAX   __INT_MAX__
                  ^~~~~~~~~~~
<built-in>:75:21: note: expanded from here
#define __INT_MAX__ 2147483647
                    ^~~~~~~~~~
1 warning generated.
```

# Steps To Reproduce
1. Install/build LLVM master branch (soon to be LLVM 10)
2. Build with clang/clang++ from LLVM master
3. Observe warnings

# Expected behavior
Shouldn't have warnings. :wink: 

# Screenshots
N/A

# Versions and configuration
Observed in Cataclysm DDA revision 9081079b485e9244b07d4944a42640c4847a2009 with LLVM master branch, revision https://github.com/llvm/llvm-project/commit/6fdd6a7b3f696972edc244488f59532d05136a27

# Additional context

The warnings about use of `INT_MAX` might just be fixable by using `FLT_MAX` (?).

The warnings in `lightmap.cpp` are more concerning, as I'm not sure what the basis for the math in `fastexp` actually is -- so I'm not sure how to fix that while maintaining the same (or better) level of precision/accuracy.

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Fixes #36510
Fixes #37006 
Clang 10 adds a new warning, this corrects our code or silences the warning when "we know better":tm:

#### Describe the solution
Replace INT_MAX with FLT_MAX in a number of places.
Silence the warning due to the hackery in fastexp().

#### Describe alternatives you've considered
Could silence more of the warnings, but FLT_MAX seems to be correct in all of those cases.
Could use std::numeric_limits<float>::max() instead, but that's kind of just bikeshedding.

#### Additional Context
This replaces #38881 since something about github permissions prevents me from applying a fix to that one.

### CODE REVIEW

File: src/lightmap.cpp [hunk 1]
```diff
@@ -1237,8 +1237,12 @@ float fastexp( float x )
         float f;
         int i;
     } u, v;
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wunknown-pragmas"
```
Comment (kevingranade) [inline src/lightmap.cpp]:
```suggestion
#pragma GCC diagnostic ignored "-Wno-pragmas"
```

File: src/lightmap.cpp [hunk 2]
```diff
@@ -1237,8 +1237,12 @@ float fastexp( float x )
         float f;
         int i;
     } u, v;
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wno-pragmas"
```
Comment (kevingranade) [inline src/lightmap.cpp]:
```suggestion
#pragma GCC diagnostic ignored "-Wpragmas"
```

File: src/monmove.cpp [hunk 3]
```diff
@@ -8,6 +8,7 @@
 #include <memory>
 #include <ostream>
 #include <list>
+#include <float.h>
```
Comment (ZhilkinSerg) [inline src/monmove.cpp]:
```suggestion
#include <cfloat>
```

File: src/npcmove.cpp [hunk 4]
```diff
@@ -9,6 +9,7 @@
 #include <tuple>
 #include <cmath>
 #include <type_traits>
+#include <float.h>
```
Comment (ZhilkinSerg) [inline src/npcmove.cpp]:
```suggestion
#include <cfloat>
```

File: src/options.cpp [hunk 5]
```diff
@@ -2,6 +2,7 @@
 
 #include <climits>
 #include <type_traits>
+#include <float.h>
```
Comment (ZhilkinSerg) [inline src/options.cpp]:
```suggestion
#include <cfloat>
```

File: src/lightmap.cpp [hunk 6]
```diff
@@ -1237,8 +1237,12 @@ float fastexp( float x )
         float f;
         int i;
     } u, v;
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wpragmas"
```
Comment (ZhilkinSerg) [inline src/lightmap.cpp]: Is it the same thing as I did in #38431?

```
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
```

Comment (kevingranade) [reply src/lightmap.cpp]: No, this one means "STFU about any warnings related to pragmas".
GCC was choking on the other ignored pragma because it didn't recognize the warning flag.
