### PR TITLE
Fix UPS guns for multiple ammotype support

### LINKED ISSUE #31399: Character creation crash
# Describe the bug

Game gives an error during character creation and then aborts character creation.

# Steps To Reproduce

Steps to reproduce the behaviour:
1. Select Dark Days Ahead and Aftershock Mods (seems to only be with Aftershock)
2. Try to create a character

# Expected behaviour

To create a new character and play with Aftershock Mod loaded

# Screenshots

none

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Ubuntu; Description: Ubuntu 18.04.2 LTS; Release: 18.04; Codename: bionic; 
- Game Version: 0.D-4255-gc42e417478 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]

This report was generated with default mods... for obvious reasons.

# Additional context

 DEBUG    : Error: basic_string::_M_construct null not valid
 
 FUNCTION : bool main_menu::new_character_tab()
 FILE     : src/main_menu.cpp
 LINE     : 709

### PR DESCRIPTION
**Pull request by mark7**
Recent support for multiple ammotypes broke UPS guns, as they have no
ammotype.  Fix.

#### Summary
SUMMARY: Bugfixes "Fix electrically-powered vehicle guns broken by multiple ammotype support"

#### Purpose of change
Fixes #31399

Recent support added for multiple ammotypes in hashref 64516a6b95 had caused character creation to bail out when using mods containing electrically-powered vehicle weapons with no ammotype.  This included CrazyCataclysm and Aftershock.

#### Describe the solution
Doesn't insert ammo into guns that have no ammotype.

### CODE REVIEW

**Comment by mark7** [comment]
This patch seems to me to work in a quick test (and gets master working with Aftershock and Crazy Cataclysm again), but (a) I have no familiarity with this portion of the code, and (b) watching the changelogs, the design of things related to charges seem to be in flux at the moment.  I'd appreciate a glance from someone familiar with how vehicle weapons ought to work (@ymber, if you're handy?).  Thanks.

File: src/veh_type.cpp [hunk 1]
```diff
@@ -1061,7 +1061,9 @@ void vehicle_prototype::finalize()
                     }
                 }
                 if( pt.ammo_types.empty() ) {
-                    pt.ammo_types.insert( ammotype( *base->gun->ammo.begin() )->default_ammotype() );
+                    if (!base->gun->ammo.empty()) {
```
Comment (kevingranade) [inline src/veh_type.cpp]:
```suggestion
                    if( !base->gun->ammo.empty() ) {
```

**Comment by ymber** [comment]
@mark7 This is how vehicle weapons ought to work. Checking the prototype instead of the base item was an oversight in #30874.
