### PR TITLE
Obsolete lockpick iuse actor and add "PERFECT_LOCKPICK" flag

### LINKED ISSUE #41100: Skeleton Key of Opening behaves like regular lockpick
# Describe the bug
The skeleton key of opening can fail to open locks and take damage like hairpins or lockpicks. 
The key has `"pick_quality": 50` but with a low lockpicking skill the key can still fail to open doors and take damage.

# Steps To Reproduce

1. Make a player with lockpicking 0, spawn in skeleton key of opening.
2. Teleport to non-vandalized evac shelter.
3. Activate skeleton key of opening on the locked door to the shelter roof. 

# Expected behavior

The skeleton key unlocks the door in one try.

Alternatively, the skeleton key fails with lower lockpicking skill, but does not take damage because of its magical artifact quality.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2733-g6a45cf7 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Magiclysm [magiclysm]
]

# Additional context

### PR DESCRIPTION
**Pull request by olanti-p**
#### Summary
SUMMARY: Bugfixes "Fixed skeleton key of opening acting like a regular lockpick"

#### Purpose of change
Fixes #41100
Obsoletes lockpicking iuse actor and replaces it with iuse function.

#### Describe the solution
Made a new `PERFECT_LOCKPICK` item flag and added it to skeleton key and bionic lockpick. The new flag makes it so picking a lock takes only 5 seconds and results in a guaranteed success (though the amount of xp gained is reduced compared to picking the lock the hard way).

Removed `pick_lock_actor::pick_quality` field since it basically duplicated `LOCKPICK` item quality introduced with the overhaul (#39409) and wasn't really used anywhere anymore. Made sure all lockpicks have the `LOCKPICK` quality, and added a debugmsg to enforce it.

Converted `pick_lock_actor` into an iuse function since it doesn't have fields anymore.

#### Describe alternatives you've considered
Adding `PERFECT_LOCKPICK` as boolean in iuse actor, but using flags is much easier and provides flavor text for items.

Keeping the `pick_quality` field, but that would lead to confusion (like with skeleton key right now having useless `pick_quality`, but lacking the necessary `LOCKPICK` item quality)

Leaving the iuse actor with 0 fields, but that sounds like dead code.

#### Testing
Built a wall of locked doors, tried opening them with regular lockpicks, bionic lockpick and skeleton key. The last 2 always open the door and do it in seconds.

### CODE REVIEW

File: src/iuse.cpp [hunk 1]
```diff
@@ -3364,6 +3367,47 @@ int iuse::jackhammer( player *p, item *it, bool, const tripoint &pos )
...
+    } else {
+        target = pos;
+    }
+    if( !target.has_value() ) {
+        return 0;
+    }
+
+    int qual = it->get_quality( qual_LOCKPICK );
+    if( qual < 1 ) {
+        debugmsg( "Item %s with 'picklock' use action requires LOCKPICK quality of at least 1.",
```
Comment (olanti-p) [inline src/iuse.cpp:3390]:
```suggestion
        debugmsg( "Item %s with 'PICK_LOCK' use action requires LOCKPICK quality of at least 1.",
```
