### PR TITLE
[CR] Added a message notifying player about why he can't mine terrain/furniture with bash resistance above maximum mining ability for a pickaxe/jackhammer

### LINKED ISSUE #45974: Mi-go camp walls cannot be mined by pickaxe or jackhammer.
# Describe the bug

The game does not let you mine mi-go resin walls for resin chunks.

# Steps To Reproduce

1. Try to mine mi-go resin walls with a pickaxe.
2. The game will tell you "You can't mine there".

# Expected behavior

You should be able to mine mi-go resin walls just like on previous experimental versions.

# Screenshots

New Bitmap Image (3)

# Versions and configuration

    OS: Windows
        OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version [Windows 8.1 Pro build 9600]
    Game Version: 0.E-8109-g9953469 [64-bit]
    Graphics Version: Tiles
    Game Language: English [en]
    Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    C.R.I.T Expansion Mod [crt_expansion],
    Blaze Industries [blazeindustries],
    Alternative Map Key [alt_map_key],
    Graphical Overmap [Graphical_Overmap],
    sees-player icon, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    Mythical Martial Arts [MMA],
    More Survivor Stuff [more_survivor_stuff],
    Fuji's Military Profession Pack [fuji_mpp],
    Mutation Changes [Mutation_Changes],
    SpeedyDex [speedydex],
    Stats Through Skills [StatsThroughSkills],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP]
    ]

# Additional context

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Interface "Added a message notifying player about why he can't mine terrain/furniture with bash resistance above maximum mining ability for a pickaxe/jackhammer."

#### Purpose of change
* Close #45974.

#### Describe the solution
Added a message notifying player about why he can't mine terrain/furniture with bash resistance above maximum mining ability for a pickaxe/jackhammer.
I took a value of 70 for maximum mining ability, as it's `str_min` for bashing a `concrete wall`. The value could be increased or decreased if it feels too high or low.

#### Describe alternatives you've considered
Make maximum mining ability for jackhammer a bit higher than for pickaxe. But I'm not sure if it makes sense.

#### Testing
Activated pickaxe, selected resin wall. Got usual `You can't mine there.` message and also new `The material is so hard that you hardly can make even a dent.`

#### Additional context
While skimming through various types of terrain in order to find a good candidate for a maximum mining ability, I noticed that we have `reinforced concrete wall` with a `str_min` value of 120. And despite its own description stating that `only serious explosives and high-speed impacts would be capable of damaging this wall.`, it's still easily mineable by a ordinary pickaxe (i.e. has `MINEABLE` flag), which obviously isn't a serious explosive nor it's capable of making really high-speed impacts. Should I increase maximum mining ability to 120? Or should we remove possibility of mining reinforced concrete wall with a pickaxe?

Also I'm not sure why `simple concrete wall` has better bash protection than ordinary `concrete wall` (90 versus 70).

### CODE REVIEW

File: src/iuse.cpp [hunk 1]
```diff
@@ -3509,10 +3509,15 @@ cata::optional<int> iuse::jackhammer( Character *p, item *it, bool, const tripoi
...
-    bool mineable_furn = here.has_flag_furn( ter_furn_flag::TFLAG_MINEABLE, pnt );
-    bool mineable_ter = here.has_flag_ter( ter_furn_flag::TFLAG_MINEABLE, pnt );
+    const bool mineable_furn = here.has_flag_furn( ter_furn_flag::TFLAG_MINEABLE, pnt );
+    const bool mineable_ter = here.has_flag_ter( ter_furn_flag::TFLAG_MINEABLE, pnt );
+    const int max_mining_ability = 70;
     if( !mineable_furn && !mineable_ter ) {
         p->add_msg_if_player( m_info, _( "You can't drill there." ) );
+        if( here.bash_resistance( pnt ) > max_mining_ability ) {
+            p->add_msg_if_player( m_info,
+                                  _( "The material is so hard that you hardly can make even a dent." ) );
```
Comment (Xenoamor) [inline src/iuse.cpp:3519]: Personally I find this sentence a bit confusing. It might be the double hard/hardly appearance of the "hardly can make even". Would something like "This seems so hard you can barely make a dent" be clearer?

Comment (Xenoamor) [reply src/iuse.cpp:3519]: Or maybe something that strongly implies you'll never mine it like "This material is so hard you can't even make a dent"

**Comment by PatrikLundell** [comment]
My amateur view is that "mining" a reinforced concrete wall should require additional tools to deal with the metal reinforcements. Thus, it ought to be penetrable with the right set of tools, but that set isn't just a pick axe analog. I would guess an oxytorch, angle grinder (if that exists in the game), or similar would be needed to deal with the reinforcements.

Also, I don't think it's reasonable for a jackhammer to be capable of dealing with things pick axes can't: the difference between them is speed and effort, both of which the game is currently incapable of modeling.

File: src/iuse.cpp (hunk 1 above)
Comment (kevingranade) [inline src/iuse.cpp:3519]:
```suggestion
                                  _( "The material is too hard for you to even make a dent." ) );
```

File: src/iuse.cpp [hunk 2]
```diff
@@ -3620,10 +3625,15 @@ cata::optional<int> iuse::pickaxe( Character *p, item *it, bool, const tripoint
...
-    bool mineable_furn = here.has_flag_furn( ter_furn_flag::TFLAG_MINEABLE, pnt );
-    bool mineable_ter = here.has_flag_ter( ter_furn_flag::TFLAG_MINEABLE, pnt );
+    const bool mineable_furn = here.has_flag_furn( ter_furn_flag::TFLAG_MINEABLE, pnt );
+    const bool mineable_ter = here.has_flag_ter( ter_furn_flag::TFLAG_MINEABLE, pnt );
+    const int max_mining_ability = 70;
     if( !mineable_furn && !mineable_ter ) {
         p->add_msg_if_player( m_info, _( "You can't mine there." ) );
+        if( here.bash_resistance( pnt ) > max_mining_ability ) {
+            p->add_msg_if_player( m_info,
+                                  _( "The material is so hard that you can't even make a dent." ) );
```
Comment (kevingranade) [inline src/iuse.cpp:3635]:
```suggestion
                                  _( The material is too hard for you to even make a dent." ) );
```

File: src/iuse.cpp [hunk 3]
```diff
@@ -3620,10 +3625,15 @@ cata::optional<int> iuse::pickaxe( Character *p, item *it, bool, const tripoint
...
-    bool mineable_furn = here.has_flag_furn( ter_furn_flag::TFLAG_MINEABLE, pnt );
-    bool mineable_ter = here.has_flag_ter( ter_furn_flag::TFLAG_MINEABLE, pnt );
+    const bool mineable_furn = here.has_flag_furn( ter_furn_flag::TFLAG_MINEABLE, pnt );
+    const bool mineable_ter = here.has_flag_ter( ter_furn_flag::TFLAG_MINEABLE, pnt );
+    const int max_mining_ability = 70;
     if( !mineable_furn && !mineable_ter ) {
         p->add_msg_if_player( m_info, _( "You can't mine there." ) );
+        if( here.bash_resistance( pnt ) > max_mining_ability ) {
+            p->add_msg_if_player( m_info,
+                                  _( The material is too hard for you to even make a dent." ) );
```
Comment (kevingranade) [inline src/iuse.cpp:3635]:
```suggestion
                                  _( "The material is too hard for you to even make a dent." ) );
```
