### PR TITLE
Fix effects not buffing stats

### LINKED ISSUE #12473: Broken handling of current stats
I've had a little session with gdb today and found out, that all these neat CBMs actually don't do what they seem to do.

All code that is accessing player public members (int_cur, str_cur, etc.) and using these for calculations (smashing, melee, reading, etc.) is using nerfed values without CBM bonus.

Pieces of code that actually grab the stats via creature::get_int() (that actually handles the bonus correctly) work fine.

This also applies to stuff like meth which buff your stats, but don't get ever used in calculations.

This relates closely to #12390. 

Obviously, there are several solutions to this problem.

On the long run, it would be best if there was universal and standardized way of accessing player stats to avoid future problems.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/17989419-broken-handling-of-current-stats?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
In master, stat operations in a given turn are in order:
- Reset bonuses
- Calculate bonuses from effects
- Apply bonuses
- Calculate bonuses from everything else (mutations, bionics - active and passive, stims, pain etc.)

Except for some specific things like carrying capacity, which is always recalculated from stat+bonus.

Additionally, after using a bionic (which invokes `player::reset()`) the stat changes from effects are not applied for a single turn.

Here I fixed the bonus calculation/application order and also moved calculations of stat bonuses from effects from `player::process_effects()` to `player::reset_stats()`, so that `player::reset()` will invoke it.
`process_effects()` wasn't doing all the work (it doesn't handle speed) anyway, so it's not like I broke an unbroken rule by moving that portion of the code.

Additionally changed player display code to use `[stat]_cur` rather than `get_[stat]`. As a result the stats that are displayed are the stats that will actually be used in calculations. This will make spotting bugs easier.

We should probably remove the stat getters. They should be inlined where they actually matter, rest of the code should use the cached values of `[stat]_cur` rather than recalculating them with the getters.

EDIT:
Closes #12473

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -3800,10 +3768,10 @@ void player::disp_status(WINDOW *w, WINDOW *w2)
     int y  = sideStyle ?  0 :  3;
     int dx = sideStyle ?  0 :  6;
     int dy = sideStyle ?  1 :  0;
-    mvwprintz(w, y + dy * 0, x + dx * 0, col_str, _("Str%2d"), get_str());
-    mvwprintz(w, y + dy * 1, x + dx * 1, col_dex, _("Dex%2d"), get_dex());
-    mvwprintz(w, y + dy * 2, x + dx * 2, col_int, _("Int%2d"), get_int());
-    mvwprintz(w, y + dy * 3, x + dx * 3, col_per, _("Per%2d"), get_per());
+    mvwprintz( w, y + dy * 0, x + dx * 0, col_str, _("Str%2d"), str_cur );
```
Comment (BevapDin) [inline src/player.cpp]: Why the regression to directly accessing the member? I though stats should be accessed via the getter, so the member can be made protected.

Comment (Coolthulhu) [inline src/player.cpp]: It obfuscated the bug. In theory the getter should return the same thing as `[stat]_cur` and thus make it OK to use those interchangeably, but it didn't.

Most calculations in the game use stat members directly, so I decided to first fix the problem rather than doing the full replace of members by getters.

Transition from members to getters should probably start by making getters return members without performing any operations on them.

**Comment by DavidKeaton** [comment]
I'd rather use a getter. With the recent efforts made to replace direct member access, this is confusing.

**Comment by Coolthulhu** [comment]
Eventually yes, but for now usage of the getter there is confusing and resulted in the bug where bionics/stims/etc. don't affect stats. It's certainly better to have consistent usage of member than inconsistent usage of member mixed with getter.

**Comment by DavidKeaton** [comment]
why not just have a `get_base_stat()` and `get_stat()`?

**Comment by Coolthulhu** [comment]
I didn't test it whether it would work properly at all times. It could probably be changed to that, but here I focused on fixing that one bug.

**Comment by kevingranade** [comment]
I also consider using the member directly a regression, if anything it
should go in the complete opposite direction and replace ALL references to
the members with either getters or setters except in the getters and
setters themselves.

**Comment by Coolthulhu** [comment]
I changed the getters in display back to members for consistency, rest is untouched.

The regression is very small and very localized - only stat display code (so that players and testers know exactly what their stats are, not what are they supposed to be). Having displayed and actual stats differ was a bug on its own and the reason the stat change bug stayed unfixed for so long despite how big of a change in gameplay it is.

Replacing all the usages would of course be the proper solution, but it would be bigger than this PR, which is supposed to be just a fix to a non-minor bug (two bugs actually - one minor, one quite important).

**Comment by BevapDin** [comment]
`Creature::reset_stats` should probably be made protected. Calling it without first calling `Creature::reset_bonuses` (should also be protected), will screw up as the old bonus values are still there.

I see currently nothing really wrong with this PR. The change from direct member access to getter functions can be done in a separate PR.

**Comment by kevingranade** [comment]
Looks good, just holding off to avoid invalidating Coolthulu's mega-merge.
