### PR TITLE
Fix drop stolen items

### LINKED ISSUE #44470: Char does not drop item when he is supposed to(refugee center)
# Describe the bug
If you have been caught stealing stuff in refugee center you will trigger dialog menu with guard. First option("Okay, okay, this is all misunderstanding. Sorry, I'll drop it now.") assumes that your char will drop stolen item/s but he doesn't. Item just stays in your inventory and guard becomes friendly again.

# Steps To Reproduce
Pick up any item in refugee center. Wait for guard to talk to you. Choose first option in dialogue menu. Enjoy your item/s.

# Expected behavior
Your char supposed to drop item manually/automatically upon choosing first dialogue option.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-6300-g1d05168 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix drop stolen items"

#### Purpose of change
Fixes #44470
Fix drop stolen items

#### Describe the solution
Iterate through players containers to find stolen items.  Also add old owner field to debug info.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -1339,6 +1339,15 @@ bool item::is_old_owner( const Character &c, bool available_to_take ) const
     return c.get_faction()->id == get_old_owner();
 }
 
+std::string item::get_old_owner_name() const
+{
+    if( !g->faction_manager_ptr->get( get_old_owner() ) ) {
+        debugmsg( "item::get_owner_name() item %s has no valid nor null faction id ", tname() );
```
Comment (Night-Pryanik) [inline src/item.cpp:1345]:
```suggestion
        debugmsg( "item::get_owner_name() item %s has no valid nor null faction id", tname() );
```

File: src/item.cpp [hunk 2]
```diff
@@ -1650,6 +1659,10 @@ void item::debug_info( std::vector<iteminfo> &info, const iteminfo_query *parts,
 {
     if( debug && parts->test( iteminfo_parts::BASE_DEBUG ) ) {
         if( g != nullptr ) {
+            if( !old_owner.is_null() ) {
+                info.push_back( iteminfo( "BASE", string_format( _( "Old Owner: %s" ),
```
Comment (Night-Pryanik) [inline src/item.cpp:1663]:
```suggestion
                info.push_back( iteminfo( "BASE", string_format( _( "Old owner: %s" ),
```
