### PR TITLE
Fix for freezing bugs - part 2

### LINKED ISSUE #24875: Can't eat food when it's below freezing
**Describe the bug**  

It seems that when the ambient temperature is below freezing (e.g. -6 °C), food freezes so fast it's sometimes impossible to eat it.

**To Reproduce**  

0. I'm in my car with a kitchen unit and some meat in my inventory.
1. I craft cooked meat.
2. Immediately, it becomes inedible "cooked meat (fresh) (hot) (frozen)", which is both nonsensical and way too fast.
3. If I use the kitchen unit as a hotplate, then it stays "cooked meat (fresh) (hot) (frozen)", but becomes edible.

Sometimes food stays inedible even after defrosting it, but I can't reproduce that reliably.

**Expected behavior**  

Food becomes frozen much more slowly, at lest at temperatures near zero. Food can't be both hot and frozen at the same time. Defrosting works reliably.

**Versions and configuration:**
 - Game Version: 0.C-30616-g5d18af2

### LINKED ISSUE #24893: Frozen liquids in containers are impossible to defrost by heating
**Describe the bug**  
If you have a frozen liquid in a container there is currently no way to defrost it by heating it up. Even worse early game if you clean up water and pour it into a bottle it will very quickly (immediately?) freeze up in your inventory. Afterwards the game does not give an option when using pots/frying pans to defrost something that is inside a container.

**To Reproduce**  

1. Basic start, spring, low temperature
2. Light a fire near a source of water (toilet), have a few containers on hand
3. Clean up dirty water and pour it into a glass bottle
4. Water will soon freeze in your inventory
5. Attempt to 'a' use a pot or frying pan to heat the frozen clean water - there will be no such option

**Expected behavior**  
You should be able to defrost the liquid contents of containers, otherwise they are unusable.

**Screenshots**  
zrzut ekranu 2018-08-17 o 13 13 20
zrzut ekranu 2018-08-17 o 13 13 47
zrzut ekranu 2018-08-17 o 13 13 36

**Additional context**  
You could dump the contents of the container on the floor (clean water on the seconds screenshot) and the game will give you the option to heat it up but it will place it back on the floor from which you have no way to get it back in a container. The fact that you could somehow pick it up to heat it but then you can't get it in a container from the floor doesn't make much sense either, but is out of scope of this issue.

### LINKED ISSUE #24898: Misspell in mushy item descriptions
**Describe the bug**  
Mushy foods are described as having "bacame" mushy and tasteless.

**To Reproduce**  
1. Freeze food that tastes bad when frozen.

**Expected behavior**  
Ideally also describe *why* you expect it to happen.

**Screenshots**  

OS, mods, and game version not applicable.

### PR DESCRIPTION
**Pull request by nexusmrsep**
Resolves #24875 (this was solved only partially)
Resolves #24893 
Resolves #24898

This patch solves few problems:

1.  As play-testing by @chaosvolt showed, previous patch #24880 removed only a part of the problem of multiple opposite flags. This patch removes the second part of the problem, and my play-testing showed that flags don't multiply when heating frozen food or crafting hot food.
2. As @jakub-niscior noticed in #24893, liquids in containers couldn't be reheated for use. This PR solves this problem.
3. As @Xhuis noticed in #24898, MUSHY and No_FROST flag feedback needed some clarification and spelling errors removal.
4. I'm still not entirely satisfied with the speed of cooling/freezing. For now I have done two things to bring it towards sane values. 
- One is adding (cold) state to all food not only to those that have EATEN_COLD flag. This new (cold) state activates before freezing, so its equal to more time before food realy starts to freeze. Flags now go HOT-->COLD-->FROZEN. If item is not HOT, it goes from normal to COLD then to FROZEN. From FROZEN in above freezing temperatures items go to COLD, and in low temperature (between freezing and refrigerator temperature) it will stay COLD, and above that it will get back to normal.
- Second is lowering temperature difference influence on cooling quickness and increasing temperature of defrosted food.
There might be more tweaks in this topic, but removing bugs gets priority over that.
5. Fixes activation of non-food comestibles (bandages, meds) on spawn. This should prevent suffix (active) from being added. It might not prevent existing (active) meds, and deactivating them via code would endanger further implementation of active meds. Rotation of items in game should fix that eventually.

### CODE REVIEW

**Comment by stk2008** [comment]
Yes thank you cant wait for merge :0

File: src/map.cpp [hunk 1]
```diff
@@ -4580,11 +4580,11 @@ void map::apply_in_fridge( item &it, int temp )
 {
     unsigned int diff_freeze = abs(temp - FREEZING_TEMPERATURE);
     diff_freeze = diff_freeze < 1 ? 1 : diff_freeze;
-    diff_freeze = diff_freeze > 10 ? 10 : diff_freeze;
+    diff_freeze = diff_freeze > 5 ? 5 : diff_freeze;
```
Comment (Night-Pryanik) [inline src/map.cpp]: You can use `std::min( 5, diff_freeze )` for this and `std::max( 1, diff_freeze )` above. The same for `diff_cold` below.

Comment (nexusmrsep) [reply src/map.cpp]: would it be better performance wise?

Comment (Night-Pryanik) [reply src/map.cpp]: Honestly, I don't know. For me it's just more clear and readable. Need consulting from more competent guys.

Comment (ZhilkinSerg) [reply src/map.cpp]: > would it be better performance wise?

It won't be more slow, but much more readable.

File: src/item.cpp [hunk 2]
```diff
@@ -982,11 +982,11 @@ std::string item::info(std::vector<iteminfo> &info, const iteminfo_query *parts,
                                                          "It's on a brink of becoming inedible." ) );
                 }
             }
-            if( food_item->has_flag( "NO_FREEZE" ) && !food_item->rotten() ) {
-                info.emplace_back( "DESCRIPTION", _( "* Quality of this food suffers when it's <neutral>frozen.</neutral>." ) );
+            if( food_item->has_flag( "NO_FREEZE" ) && !food_item->rotten() && !food_item->has_flag( "MUSHY" ) ) {
+                info.emplace_back( "DESCRIPTION", _( "* Quality of this food suffers when it's <neutral>frozen, and it becames mushy after defrosting</neutral>." ) );
```
Comment (Xhuis) [inline src/item.cpp]: This is still an error. Here's a suggestion:
`(...), and it will become mushy after thawing out.`

File: src/map.cpp [hunk 3]
```diff
@@ -4579,12 +4579,12 @@ void map::make_active( item_location &loc )
 void map::apply_in_fridge( item &it, int temp )
 {
     unsigned int diff_freeze = abs(temp - FREEZING_TEMPERATURE);
-    diff_freeze = diff_freeze < 1 ? 1 : diff_freeze;
-    diff_freeze = diff_freeze > 5 ? 5 : diff_freeze;
+    diff_freeze = std::max( 1, diff_freeze );
```
Comment (ZhilkinSerg) [inline src/map.cpp]: You can't put int and unsigned int together.

image

Comment (nexusmrsep) [reply src/map.cpp]: just noticed that in a compiler, sorry

File: src/map.cpp [hunk 4]
```diff
@@ -4579,12 +4579,12 @@ void map::make_active( item_location &loc )
...
-    diff_freeze = diff_freeze < 1 ? 1 : diff_freeze;
-    diff_freeze = diff_freeze > 10 ? 10 : diff_freeze;
+    diff_freeze = std::max( static_cast<unsigned int>(1), diff_freeze );
+    diff_freeze = std::min( static_cast<unsigned int>(5), diff_freeze );
 
     unsigned int diff_cold = abs(temp - FRIDGE_TEMPERATURE);
-    diff_cold = diff_cold < 1 ? 1 : diff_cold;
-    diff_cold = diff_cold > 10 ? 10 : diff_cold;
+    diff_freeze = std::max( static_cast<unsigned int>(1), diff_cold );
+    diff_freeze = std::min( static_cast<unsigned int>(5), diff_cold );
```
Comment (Brambor) [inline src/map.cpp]: Sorry for bothering. These two lines seems wierd as the above one keeps `diff_cold` and those two change to `diff_freeze`. I'm writing this just so that it can be double-checked.

Comment (nexusmrsep) [reply src/map.cpp]: You are right and fix is included in PR #24971 waiting to be merged.
