### PR TITLE
Remove trailing zeros from variables

### LINKED ISSUE #65261: John Bailey's zombie kill count appears as a float in dialogue
### Describe the bug

This is a rather minor bug. It's only a matter of game immersion. John Bailey's `npc_val:zkc_john` appears as a float in dialogue.

"I'm up to 10.000000 so far."

### Attach save file

[test-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/11302942/test-trimmed.tar.gz)

### Steps to reproduce

1. Load the save.
2. Talk to John Bailey, and proceed to the topic `TALK_RC_John_Bailey_ZKC`.
3. Find out the number has a decimal point and 6 following zeros, which is unnecessary in real person-to-person dialog.

### Expected behavior

I would like to see the kill count as a integer.

### Screenshots

图片

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.2846 (22H2)
- Game Version: 0.G-1503-ge8a1eafffb [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fixes #65261

### CODE REVIEW

File: src/condition.cpp [hunk 1]
```diff
@@ -2173,9 +2186,9 @@ conditional_t::get_set_dbl( const J &jo, const std::optional<dbl_or_var_part> &m
                 var_name = get_talk_varname( jo, "var_name", false, empty );
             }
             return [is_npc, var_name, type, min, max]( dialogue const & d, double input ) {
-                write_var_value( type, var_name, d.actor( is_npc ), std::to_string( handle_min_max( d, input,
-                                 min,
-                                 max ) ) );
+
+                write_var_value( type, var_name, d.actor( is_npc ),
+                                 remove_trailing_zeroes( std::to_string( handle_min_max( d, input, min, max ) ) ) );
```
Comment (andrei8l) [inline src/condition.cpp:2191]:
```suggestion
                write_var_value( type, var_name, d.actor( is_npc ),
                                 // NOLINTNEXTLINE(cata-translate-string-literal)
                                 string_format( "%g", handle_min_max( d, input, min, max ) ) );
```
Uses 6 digits of precision and strips trailing zeroes and decimal point.
