### PR TITLE
Implement surrounded start, fix monster spawns

### LINKED ISSUE #15454: Ambush scenario not spawning zombies
The 'ambush' scenario does not spawn zombies outside of the cabin anymore.

### LINKED ISSUE #20769: Surrounded start is hardcoded only for evac shelter
There are two effects of surrounded start/"black road" option:
* Evac shelter spawns some extra zombies around it (this happens even if it's not the first shelter you see)
* Monsters in player's vision aren't removed at start of the game

I can't really classify it as bug, because it is more like an unimplemented feature. However there are some surrounded start scenarios where it can be considered a bug.

### LINKED ISSUE #21334: map::place_spawns code is weird, unintuitive, incorrect
`map::place_spawns` is used in pretty much all monster spawning, meaning that pretty much every json mapgen and most function ones are affected.

There there are three variables: `int chance` and `float density` and spawn rate setting.
Chance and spawn rate settings both affect the chance for monster to spawn. If `chance / spawn` is lower than 2, the spawn will always happen (because it uses integer `one_in`). This alone is confusing: item spawns use chance as percentage.
Then spawn rate is used again: this time to modify density.

EDIT: Also, there is a multiplication by `rng(10, 50)`, which just arbitrarily scales spawn count. It would be much, much cleaner if density was just plain density per tile.

So:
* Spawn rate is used twice, meaning that actual number of monsters grows (or decreases) quadratically with it
* Spawn chances on non-integer spawn rates are truncated, making the above problem much worse
* Chance is nonstandard across jsons, necessitating looking into docs to figure out basic things (seems that campsite and restaurant jsons use the wrong chances)

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #20769
Closes #15454
Closes #21334

Surrounded start was horribly hardcoded for evac start and only that.
I implemented it for all spawns, though it's not an exact reimplementation, just implementation of the idea in loosely similar way.
Works like this:
* Monsters are spawned on all overmap squares adjacent to player's overmap square (excluding player's overmap square)
* Every such overmap square gets from ~9 to ~45 "monster points" (same units as `"cost_multiplier"` in monster group) in spawns, which translates to around ~5 monsters in a typical case
* This happens on game start, meaning that a player entering a world with surround start will always bring the monsters with themselves - they aren't a property of the location but of the world or scenario

Also fixed the following issues with spawns:
* In many cases spawn count of monsters would be lower than expected due to double decrement (in the proper function and in the caller), by two different values. Some jsons are badly formed and abuse this bug. Fixed the bug and added a special case for the badly formed jsons not to crash
* Spawn rate setting effects were considered twice: once for monster density and once for chance, resulting in quadratic (instead of linear) scaling
* Spawn chance roll was truncating chance (used in `one_in`) to `int`, dropping a LOT of precision, getting really wonky with non-integer spawn rate settings

I'm bundling those fixes because those problems were big enough that I couldn't cleanly implement this otherwise. A lot of the spawn code works in spite of itself rather than because of itself.

### CODE REVIEW

File: src/start_location.cpp [hunk 1]
```diff
@@ -446,3 +446,27 @@ void start_location::handle_heli_crash( player &u ) const
         }
     }
 }
+
+static void add_monsters( const tripoint &omtstart, const mongroup_id &type, float expected_points )
```
Comment (codemime) [inline src/start_location.cpp]: Not necessary, but the file has an anonymous namespace already. I'd use it instead of `static`.

**Comment by Coolthulhu** [comment]
It doesn't look like the errors are related to changed code.
Jenkins, rebuild

**Comment by Coolthulhu** [comment]
How do I get the whole "Jenkins rebuild" thing to work? Did I miss something?

**Comment by kevingranade** [comment]
Jenkins isn't failing, travis is.  It looks like we're encountering either
OOM or time exceeded errors on travis boxes.
