### PR TITLE
Sort out loot - teleport exploit fix

### LINKED ISSUE #25116: player can teleport items using loot sorting
**Describe the bug**  
If the player stands in a hidden location where they can see the target items and destination, and monsters can also see the items, the player can use loot sorting to teleport items from the source to the destination without risking detection.

**To Reproduce**  
1. Place a pile of items in view of a zombie.
2. Stand in a location where the zombie cannot see you.
3. Place loot zones matching the items adjacent to the player.
4. Place a n inserted loot zone over the target items.
5. Trigger loot sorting.
6. The player folds space and retrieves the items without moving to them.

**Expected behavior**  
The zombie should detect the player picking up the items, since it is simulating the player moving to them.

### PR DESCRIPTION
**Pull request by Robik81**
#### Summary
SUMMARY: Bugfixes "Sort out loot teleport items from inaccessible or guarded location exploit fix."

#### Purpose of change
Fixes #25116 
Sort out loot feature could be exploited for moving items from inaccessible location or location with monsters without alerting them.

#### Describe the solution
Player physically moves to an adjacent tile of every source tile that has any item that needs to be sorted out, before sorting from such tile takes place.

#### Additional context
Since sort out loot feature can optionally utilize a grabbed cart free space, I had to also implement pathing that avoids rough terrain. It is not perfect and could be improved on, but it is better than not trying to avoid such terrain at all.

Whenever the player grabs a cart, his pathfinder settings is changed to avoid rough terrain. Avoiding is disabled again upon releasing.

If route to source tile can't be planned, player is notified, sorting without using a cart is suggested and activity is stopped.

### CODE REVIEW

**Comment by Robik81** [comment]
Gorgon:

> 08:21:34 Validating Summary line from pull request.
> 08:21:34 build-scripts/validate_pr_in_jenkins: command substitution: line 8: syntax error near unexpected token `)'
> 08:21:34 build-scripts/validate_pr_in_jenkins: command substitution: line 8: `)?(None)|({allowed_section_titles}) \".*?\")('
> 08:21:34 grep: unrecognized character after (? or (?-
> 08:21:34 Invalid Summary line, please provide a summary similar to the following:
> 08:21:34 SUMMARY: Features "Added ability to fly."

**Comment by Zireael07** [comment]
I think your summary line is missing an ending "

**Comment by Robik81** [comment]
> I think your summary line is missing an ending "

Yeah, just noticed that.

**Comment by ZhilkinSerg** [comment]
Jenkins rebuild.

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by Night-Pryanik** [comment]
Jenkins rebuild

**Comment by alanbrady** [comment]
This seems to solve the problem but I think it can be improved further.  Instead of doing a move activity if the route is greater than 1, it should instead move all the items that are in range 1, then start routing to the next closest item.  I believe this will cut down on the number of moves required since the way it's currently setup here, if the items are sufficiently spread apart it could take forever to visit each item.

Additionally, because you're cycling the destination activity with a ACT_MOVE_LOOT, is it not possible to end up in an infinite recursion?

Lastly, because the move is done in the middle of the activity, won't this alter the loot zone and potentially cause erratic sorting?

File: src/activity_item_handling.cpp [hunk 1]
```diff
@@ -806,6 +808,29 @@ void activity_on_turn_move_loot( player_activity &, player &p )
                     }
 
                     if( g->m.free_volume( dest_loc ) > it->volume() ) {
+                        // get route to source tile, if we didn't get it previously
+                        if( !has_route ) {
+                            route = g->m.route( p.pos(), src_loc, p.get_pathfinding_settings(), p.get_path_avoid() );
```
Comment (alanbrady) [inline src/activity_item_handling.cpp]: Is getting the pathfinding settings and path avoidance necessary every loop?

**Comment by kevingranade** [comment]
Jenkins rebuild.

**Comment by Robik81** [comment]
> This seems to solve the problem but I think it can be improved further. Instead of doing a move activity if the route is greater than 1, it should instead move all the items that are in range 1, then start routing to the next closest item. I believe this will cut down on the number of moves required since the way it's currently setup here, if the items are sufficiently spread apart it could take forever to visit each item.

It should (hopefully) visit every source tile only once, no matter how many items there is. Sorting source tiles by distance might cut some moves, but it should not take _forever_ without it.

> Additionally, because you're cycling the destination activity with a ACT_MOVE_LOOT, is it not possible to end up in an infinite recursion?

Only if you get a valid path, got interrupted somehow at the last auto-move to destination (when the activity is restarted) and you get valid path to same tile again, etc. This infinite cycle happened in my tilling / planting, where I was 1 tile from destination and got interrupted by monster which triggered safe mode and prevented moving but pathing still returned route. Now that I check for safe mode in the code, never happened again.

> Lastly, because the move is done in the middle of the activity, won't this alter the loot zone and potentially cause erratic sorting?

Hmm, did not happen during my testing, I'l test a bit more, with varied loot source tile, not just 2 i tried.

File: src/activity_item_handling.cpp (hunk 1 above)
Comment (Robik81) [reply src/activity_item_handling.cpp]: If by every loop you mean once per each source tile that actually has loot to sort.

get_pathfinding_settings() just returns pointer
get_path_avoid should be quite quick unless you see zillion NPCs

Much more computing power is lost by nature of activity processing. You do lot of stuff that you throw away once player turn moves reaches zero or negative and you return the execution back to the game. And you do it again and again each time the activity is recalled. Yes, you could possibly cache some to save computing, but you risk that the world changes in the meanwhile and break stuff in your cache.

Since this is call on demand activity and not something that runs all the time, optimization to the ground is probably not necessary right now, could always be improved upon later.

**Comment by alanbrady** [comment]
> Route is set for player and activity is stopped. Player movement is then handled outside the activity. Activity is called again after the player reaches the destination.

Right, and when the activity gets called again, won't this:

https://github.com/CleverRaven/Cataclysm-DDA/blob/50879f9f900a641c74656e92db3fd28e1cc9c801/src/activity_item_handling.cpp#L770

be different from when you called it originally?

**Comment by Robik81** [comment]
> Right, and when the activity gets called again, won't this:
> 
> Cataclysm-DDA/src/activity_item_handling.cpp
> 
> Line 770 in 50879f9
> 
>  const auto &src_set = mgr.get_near( zone_type_id( "LOOT_UNSORTED" ), abspos ); 
> be different from when you called it originally?

Not necessarily, but it might.

You are right, I'll add the sort by distance to sort tiles.

**Comment by Robik81** [comment]
I use the sort by distance in tilling code, should not be a big deal and could prevent eager hopping to newly 'discovered' source tile after the movement. Worth a try,

I'd also like to check if I could postpone the activity restart after the last auto-move (if successful), not just before it. That would make SAFE-MODE check obsolete and also prevent any other case of possible infinite loop.

**Comment by Robik81** [comment]
gorgon:
20:54:47 astyle regressions found.
20:54:47 Formatted  src/enums.h
20:54:47 Makefile:1038: recipe for target 'astyle-check' failed
20:54:47 make: *** [astyle-check] Error 1

this PR does not touch enums.h

**Comment by Robik81** [comment]
Anyway... 

 - added sorting of source tiles by distance from the player to prevent possible bunny hopping from tile to tile after 'discovering' new source tiles
- player activity is now not started during the processing of the last move in the route vector (before the move is actually done), but after successfully moving to destination tile, this should prevent any possibility of infinite loop due to not reaching the destination
