### PR TITLE
correct height when a uilist has desired_bounds not including height

### LINKED ISSUE #77191: interactable menus collapsing
### Describe the bug

menu collapses, for example you cant see how you can interact with an item (because it also keeps spazzing out)

### Attach save file

N/A

### Steps to reproduce

go into inventory
press enter on an item
:(

### Expected behavior

i expect the menu to show me all the interactions

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22631.4317 (23H2)
- Game Version: 74e77cc [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Dark Days of the Dead [classic_zombies],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Tamable Wildlife [Tamable_Wildlife],
    No filthy clothes [idon'twanttoclean]
]

### Additional context

very sad :(

### PR DESCRIPTION
**Pull request by db48x**
#### Summary
Bugfixes "calculate correct height when a uilist has desired_bounds not including a height"

#### Purpose of change
Fixes #77191

#### Describe the solution
When the desired bounds doesn't include a height, use the screen height instead of -1 as the desired height.

https://github.com/user-attachments/assets/20d472fa-0ec6-4199-a7ce-df57b3148620

### CODE REVIEW

File: src/ui.cpp [hunk 1]
```diff
@@ -746,9 +746,10 @@ void uilist::calc_data()
     calculated_menu_size.x += calculated_hotkey_width + padding;
     calculated_menu_size.x += calculated_label_width + padding;
     calculated_menu_size.x += calculated_secondary_width + padding;
-    float max_avail_height = ImGui::GetMainViewport()->Size.y;
-    if( desired_bounds.has_value() ) {
-        max_avail_height = desired_bounds.value().h;
+    float max_avail_height = 0.9 * ImGui::GetMainViewport()->Size.y;
+    float desired_height;
+    if( desired_bounds.has_value() && ( desired_height = desired_bounds.value().h != -1 ) ) {
```
Comment (Brambor) [inline src/ui.cpp:751]: Could you change `desired_height = desired_bounds.value().h != -1` please? It is confusing to me.
I assume it does:
1. eval `!=`
2. assign the resulting boolean value to the float desired_height

But I am not sure and I don't understand what it is for if it does that.

No, I guess it does:
1. assign `=`
2. compare `!=`
3. return compared value to the rest of the and statement.

No, the precedence of != is 10 and precedence of = is 16, so it has to first do !=, right?

Anyway, change it for us, lesser programmers, please :)

Comment (db48x) [reply src/ui.cpp:751]: Sure, I can do that.

File: src/ui.cpp [hunk 2]
```diff
@@ -747,9 +747,11 @@ void uilist::calc_data()
     calculated_menu_size.x += calculated_label_width + padding;
     calculated_menu_size.x += calculated_secondary_width + padding;
     float max_avail_height = 0.9 * ImGui::GetMainViewport()->Size.y;
-    float desired_height;
-    if( desired_bounds.has_value() && ( desired_height = desired_bounds.value().h != -1 ) ) {
-        max_avail_height = std::min( max_avail_height, desired_height );
+    if( desired_bounds.has_value() ) {
+        float desired_height = desired_height = desired_bounds.value().h;
```
Comment (Brambor) [inline src/ui.cpp:751]: Why do `desired_height = desired_height`? Why assign it to itself?

Comment (db48x) [reply src/ui.cpp]: /me waves; these are not the droids you’re looking for

Comment (Brambor) [reply src/ui.cpp]: These aren't the droids we're looking for.

Thanks. It could be const, but it is readable now :)

Comment (db48x) [reply src/ui.cpp]: YW :D
