### PR TITLE
fix: inedible MELTS while FROZEN (milkshake)

### LINKED ISSUE #51117: Cannot eat frozen ice cream
### Describe the bug

I cannot eat frozen ice cream, and it doesn't show as "unedible" in the `Consume item` menu either.

Edit: it is edible if you [o]pen the container and [E]at it, but the rest still stands.

Even if you unload the container and have (frozen) ice cream in your inventory, you still have to [e]xamine it directly to [E]at it.

### Steps To Reproduce

1. Debug: Make melted ice cream from debug menu (in container).
2. Debug: Make it winter, make it snowing, go outside.
3. Drop ice cream and wait for it to freeze.
4. Observe that it is not in `Consume item` menu and when you [e]xamine it, you cannot [E]at it.

### Expected behavior

Being able to eat frozen ice cream, which is supposed to be delicious when frozen!

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 0.F-1980-g7dfdf4ef1f [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Brambor**
#### Summary
Bugfixes "Allow eating frozen food flagged with MELTS (like a milkshake)"

#### Purpose of change

[JSON_FLAGS.md](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/JSON_FLAGS.md) says:
`MELTS` Provides half fun unless frozen. Edible when frozen.

Fix milkshake not being edible while FROZEN the proper way.
So fix #51117 the proper way.

#### Describe the solution

fix if
revert (temporary fix) #51220

#### Describe alternatives you've considered

Add EDIBLE_FROZEN to milkshake.
Ha! Like I would do that!

#### Testing

On master ice cream (frozen) is edible and milkshake (frozen) is not.
After change, both are edible frozen.

#### Additional context

Boolean table:

FROZEN | EDIBLE_FROZEN | MELTS || should be edible
000 1
001 1
010 1
011 1
100 0
101 1
110 1
111 1

### CODE REVIEW

File: src/consumption.cpp [hunk 1]
```diff
@@ -1590,7 +1590,8 @@ bool Character::can_estimate_rot() const
 bool Character::can_consume_as_is( const item &it ) const
 {
     if( it.is_comestible() ) {
-        return !( it.has_flag( flag_FROZEN ) && !it.has_flag( flag_EDIBLE_FROZEN ) );
+        return !( it.has_flag( flag_FROZEN ) && !it.has_flag( flag_EDIBLE_FROZEN ) &&
+                  !it.has_flag( flag_MELTS ) );
```
Comment (eltank) [inline src/consumption.cpp:1594]:
```suggestion
        return !it.has_flag( flag_FROZEN ) || it.has_flag( flag_EDIBLE_FROZEN ) ||
                  it.has_flag( flag_MELTS );
```

Please avoid double negation, it's confusing.

Comment (Brambor) [reply src/consumption.cpp:1594]: Aaah. Thanks, will think of it the next time!
That's why you need math to do programming 😛.

**Comment by eltank** [comment]
Suggested description change:

Bugfixes "Allow eating frozen food flagged with MELTS (like milkshake)"

The first word has to spelled exactly like that, "Bugfixes"

**Review by eltank — APPROVED** [review]

**Comment by Brambor** [comment]
I believe the check error is unrelated.
