### PR TITLE
Fix antennae handling for auto attacking

### LINKED ISSUE #37234: Antennae Multilevel attacks
# Describe the bug

A character with antennae is capable of detecting creatures within a short distance. This includes those up or down a level relative to the survivor. Using [TAB] to auto attack results in certain situations allowing the character to attack a creature below them as if they were on the same level as the character.

# Steps To Reproduce

1. Make a player with the antennae mutation.
2. Encounter a creature below the character (Bug originally found with the character fighting and killing a sewer gator below them. Similar results from a C.H.U.D.). 
3. Use [TAB] to auto attack. Attacks should hit the creature below the survivor occasionally. (Perhaps when the creature moves into a valid position where an attack on the same level would be valid? Unknown how the inner workings of the bug works.)

# Expected behavior

Survivors should not be capable of combat through solid floors like pavement.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-11044-g605409a [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Craftable Gun Pack [craftgp],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Roadheader and other mining vehicles [Heavy miners],
    Tanks and Other Vehicles [Tanks]
]

# Additional context
N/A

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix antennae handling for auto attacking"

#### Purpose of change
Fixes #37234
Antennae allowed attempting to auto attack targets across z levels and through walls.

#### Describe the solution
Added check to make sure targetable creatures can not only be seen by player but are reachable from current location

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -5386,7 +5386,7 @@ std::vector<Creature *> player::get_targetable_creatures( const int range ) cons
         // TODO: get rid of fake npcs (pos() check)
         return this != &critter && pos() != critter.pos() && attitude_to( critter ) != Creature::Attitude::A_FRIENDLY &&
         round( rl_dist_exact( pos(), critter.pos() ) ) <= range &&
-        ( sees( critter ) || sees_with_infrared( critter ) );
+        ( ( sees( critter ) && g->m.sees( pos(), critter.pos(), 100 ) ) || sees_with_infrared( critter ) );
```
Comment (Night-Pryanik) [inline src/player.cpp]: There are so much conditions in here. Maybe split this one big check to several smaller checks?

Comment (Ramza13) [reply src/player.cpp]: Good idea
