### PR TITLE
No healing for you Sugar

### LINKED ISSUE #36483: Sweet Cataclysm Feedback
# Describe the bug

u/fris0uman asked me to list the things I notice: 

1. You have some Natural Healing even if you are not supposed to. 

2. Despite no need to drink you still can and your level of thirst also changes. The level of thirst can jump drastically sometimes. 

3. You can get sick. 

4. Many Medicines can't be used from the activation Menu but manually activating them still works.

5. Honey and its derivatives can't be eaten. But French Fries can be. 

# Steps To Reproduce

Being made of Sugar and playing the game... Sorry if I can't be more precise. 

# Expected behavior

1. You are not supposed to heal naturally but you do sometimes. Even a couple of points at night can make a difference. This might make sense if you apply a heavy calorie penalty to healing and flavor it as your body reconstituting itself. Basically moving sugar from one place to another to "heal"
2. The level of thirst changes and you get the speed debuff from being thirsty. Not sure if there are more serious consequences to come. If you don't need to drink it might be better if the level of Hydration can't change. Sometimes after eating a lot of dry food like Potato Chips or Tortillas the Hydration suddenly jumps to "Hydrated" 

3. Getting sick of normal disease for a person made entirely of sugar doesn't make much sense. I have the second cold now in not even 10 days. Since the health stat is frozen at 0 no usual disease prevention means such as eating healthy to have a positive health stat work. If a health stat of 0 is neutral I'd suggest raising it slightly if the effects of [Disease Immune] can't be integrated into [Made of Sugar] 

4. Since you are made of Sugar many drugs should have no effect. In practice most drugs can still be used. This is required from a gameplay perspective as well. How are you meant to purge radiation without some Prussian Blue? Not sure if something should be changed here. 
Maybe some resistances to conditions and variants of the Caramel Ointment are the alternative. If you wan some disease I could imagine a yeast infection for a person made of sugar would be nasty. The yeast eats your body, dealing damage similar to the mutation Weakening. Cured with an ointment that has been enriched with fungicide. 
 
5. Honey is mostly sugar with very little water. A lot less Water than Cola or Grape Drink or all the other things your can drink. I think it would make sense when there is a list of foods that is allowed despite not being Junk Food and some Junk Foods that are not allowed either. Cooked Corn Dogs, Fast Food French Fries and similar things can be eaten. Maybe Royal Jelly should be allowed as well. 

# Screenshots
1. 
Screenshot (14)
Screenshot (15)

2.
Screenshot (20)

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-10709-gd18fc5d [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Magiclysm [magiclysm],
    Garden Pots [growable-pots],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Alternative Map Key [alt_map_key],
    Mutant NPCs [mutant_npcs],
    My Sweet Cataclysm [my_sweet_cataclysm],
    More Locations [more_locations],
    Folding Parts pack [deoxymod],
    Sleep Deprivation [sleepdeprivation],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

-

### PR DESCRIPTION
**Pull request by Fris0uman**
#### Summary

SUMMARY: Mods "Properly prevent use of forbidden healing items in My Sweet Cataclysm"

#### Purpose of change
Fixes #36483

Made Of Sugar mutation properly forbid use of medecine and removes natural healing completely

#### Describe the solution

Add can_use_healing_item() checks where they were missing
Add NO_MINIMAL_HEALING flag to disable minimal healing
Fix "healing_resting" value to -1.0

#### Testing
Get Made Of Sugar mutation
Set limbs health to 60
Set fatigue to 900
Sleep for two days
No healing

Spawn cought syrup
Try to use it through `%` menu > can't
Try to use it through `E`at menu > can't
Try to use it through `a`ctivate menu > can't
Try to use it through inventory menu > can't
Try to use it through  Advanced inventory menu > can't

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -7665,7 +7665,9 @@ bool Character::invoke_item( item *used, const std::string &method )
 
 bool Character::invoke_item( item *used, const std::string &method, const tripoint &pt )
 {
-    if( !has_enough_charges( *used, true ) ) {
+    if( !has_enough_charges( *used, true ) || ( used->is_medication() &&
+            !can_use_heal_item( *used ) ) ) {
+        add_msg_if_player( m_bad, _( "Your biology is not compatible with that healing item." ) );
```
Comment (akirashirosawa) [inline src/character.cpp:7670]: When try to use any item in hands (using Shift + A), get the message: "Your biology is not compatible with that healing item."  Maybe problem is here?

**Comment by Fris0uman** [comment]
Can you open an issue about it?

**Comment by akirashirosawa** [comment]
@Fris0uman 
> Can you open an issue about it?

Okay, here issue #41699
