### PR TITLE
Basic restructuring of the faction camp code

### LINKED ISSUE #24997: FACTION CAMP use manual time calculation instead of time_duration
**Describe the bug**  
This code cause some weird display overflow when the time to complete is out of original timescale.

**To Reproduce**  
1. Debug yourself some npc and mind control trait.
2. Build the base camp with debug spawn material until you reach recipe "faction_base_camp_6". 
3. see the "191 hours left".

**Expected behavior**  
It should be "7 days 23 hours left", also reinventing wheels.

**Screenshots**  
image

**Versions and configuration(please complete the following information):**
master latest.

**Additional context**  
Faction camp code really needs a proper clean up, there are a lot of copy-paste code and the whole structure is quite byzantine.

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Infrastructure "Basic restructuring of the faction camp code"```

#### Purpose of change
Clean up the faction camp code to the point where is has some abstraction and logical structure.

Fixes #24997 - Instead of manual calculating time offsets, just use to_string.

#### Describe the solution
* Reorganize the code into logical group.
* Use tripoints wherever possible instead of an ad-hoc mix of points and tripoints
* Break the huge if statements into somewhat smaller if statements that call functions
* Replace a lot of string compares with integer compares.
* Use to_string instead of calculating time conversions.
* Change the code so that NPCs consistently eat food when returning from missions, as opposed to
sometimes before and sometimes after and sometimes not at all.

#### Describe alternatives you've considered
There's still a lot more to do, but this puts the code on a solid enough basis that more features can be added.

#### Additional context
Built on top of #26269

### CODE REVIEW

File: src/faction_camp.cpp [hunk 1]
```diff
@@ -0,0 +1,3349 @@
...
+    popup( _( "Forests and swamps are the only valid cutting locations." ) );
+    const tripoint omt_pos = p.global_omt_location();
+    tripoint forest = om_target_tile( omt_pos, 1, 50, log_sources );
+    if( forest != tripoint( -999, -999, -999 ) ) {
+        int tree_est = om_harvest_trees( p, forest, .50, false, false );
+        int tree_young_est = om_harvest_ter( p, forest, ter_id( "t_tree_young" ), .50, false );
+        int dist = rl_dist( forest.x, forest.y, omt_pos.x, omt_pos.y );
+        //Very roughly what the player does + 6 hours for prep, clean up, breaks
+        time_duration chop_time = 6_hours + ( 1_hours * tree_est ) + ( 7_minutes * tree_young_est );
+        //Generous to
```
Comment (BevapDin) [inline src/faction_camp.cpp]: Please don't add (or keep existing) commented out code. It has no use at all. Is it actual useful code? Why is it commented out and not run?

Comment (BevapDin) [inline src/faction_camp.cpp]: This id type should be returned. The caller can use it directly and it documents what the function actually returns. If the caller absolutely needs a string, they can do the conversion on their own.

Comment (BevapDin) [inline src/faction_camp.cpp]: We have a function `direction_from` that yields a `direction` (e.g. NORTH, or BELOW) and we have a function `direction_name_short`, so consider using them like `text = direction_name_short( direction_from( direction_vector ) )`.

Comment (BevapDin) [inline src/faction_camp.cpp]: Why convert it here? Just take a parameter of type `recipe_id`. The caller properly already has one anyway.

Comment (BevapDin) [inline src/faction_camp.cpp]: Why is this showing the skill id and not its name?

Comment (BevapDin) [reply src/faction_camp.cpp]: And please make this a reference.

Comment (BevapDin) [inline src/faction_camp.cpp]: You do not need to copy the recipe, a reference (to const) is fine.

**Comment by BevapDin** [comment]
This is a general question: should the code here print the times exactly (e.g. "2 days, 5 hours and 40 minutes")?

The information is usually not hidden as the player can read about this *before* the mission is started, all they have to do now is to write down when they started it and how long it will take.

I opt for showing the full time (code would also be simpler as one could just call `to_string` for any duration).

----

@mlangsdorf thanks for the refactoring, a lot of the mentioned problems come from the original code.

**Comment by AMurkin** [comment]
@BevapDin, 6 of your comments pointing at the same line of code. Something wrong here.

File: src/faction_camp.cpp [hunk 2]
```diff
@@ -0,0 +1,3349 @@
...
+
+                const recipe *recp = &recipe_id( it->second ).obj();
+                bool craftable = recp->requirements().can_make_with_inventory( found_inv, 1 );
+
+                mission_key.push( title_e, "", dr, false, craftable );
+
+            }
+        }
+        npc_list = companion_list( p, "_faction_camp_crafting_", true );
+        if( !npc_list.empty() ) {
```
[the remark this answers is not in the document]
Comment (mlangsdorf) [reply src/faction_camp.cpp]: I didn't even notice that was being done. Thanks, will fix.

**Comment by BevapDin** [comment]
> 6 of your comments pointing at the same line of code. Something wrong here.

Yes, I see this as well when looking at https://github.com/CleverRaven/Cataclysm-DDA/pull/26296 - but when looking at the diff via https://github.com/CleverRaven/Cataclysm-DDA/pull/26296/files?w=1 they are all at the right place. I blame github.

File: src/faction_camp.cpp (hunk 1 above)
Comment (BevapDin) [inline src/faction_camp.cpp]: Why the call to `c_str`? `plant_names` contains `std::string` just what `type_name` returns. Same as above.

Comment (BevapDin) [inline src/faction_camp.cpp]: Shorter code: `if( std::find( plant_names.begin(), plant_names.end(), type_name(...) ) == plant_names.end() ) {` then add the name of the plant.

Comment (BevapDin) [inline src/faction_camp.cpp]: The parentheses around the calculation are not needed, same as above.

Comment (BevapDin) [inline src/faction_camp.cpp]: This should be `units::mass` and `units::volume` respectively. You can divide two `mass` objects.

Comment (BevapDin) [inline src/faction_camp.cpp]: Don't define variables at the top of functions like in C. Define them as late as possible. In this case below when you actually calculate its value. And than you can use `std::max` to ensure it's not zero: `const int trips = std::max( 1.0, ceil( total_m / max_m ) );`

Comment (BevapDin) [inline src/faction_camp.cpp]: A copy here is completely unnecessary, a reference to const is just fine.

Comment (BevapDin) [inline src/faction_camp.cpp]: Consider `std::max( trips, trips_v );`

Comment (BevapDin) [inline src/faction_camp.cpp]: `== false` is not needed, use `!` to negate the boolean instead.

Comment (BevapDin) [inline src/faction_camp.cpp]: Why are you formatting a single string without any arguments? What is the expected result?

Comment (BevapDin) [inline src/faction_camp.cpp]: You can check this on the item itself, you don't need to use the type id for it.

Comment (BevapDin) [inline src/faction_camp.cpp]: Why the separate definition of `outcome`? Just declare and initialize it here.

Comment (BevapDin) [inline src/faction_camp.cpp]: `bldg_exp` should already be a `recipe_id`.

Comment (BevapDin) [inline src/faction_camp.cpp]: This should be a reference (there are more places like this).

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: At various times, it's a terrain id and a recipe id. I'm leaving it as for now.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

[the remark this answers is not in the document]
Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

[the remark this answers is not in the document]
Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: I have no idea what was going through acidia's head when he wrote some of this stuff.

Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Doh! Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: I actually cleaned this up a lot more in a separate commit when I started adding new functionality, but this is a fine time to fix this. So fixed.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Nice! Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Although I agree with you in principle, the code works now with the string references and my first attempt at fixing them caused CDDA to crash on program start. Since my goal in this refactor is to just the code to the start where I can work on it without refactoring it to minimal standards, I will leave this as is.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Unfortunately, the NPCs are currently encoded with "[NW]" which is different from "[NW  "] so doing that, while sensible, would break saved games and result in NPCs lost in the ether.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Probably a copy-pasta error from using ident in other locations.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Nice! Fixed, thanks.

Comment (mlangsdorf) [reply src/faction_camp.cpp]: Fixed, thanks.

**Comment by mlangsdorf** [comment]
The weirdness in the comment lines is because github doesn't render large diffs by default, so around line 1166, it gives up on src/faction_camp.cpp and everything else just gets that little bit.

**Comment by mlangsdorf** [comment]
Okay, I fixed all that stuff and then forgot to push the fixes.  Please hold on reviewing for 24 hours.

**Comment by mlangsdorf** [comment]
Fixes pushed and ready for review.
