### PR TITLE
Prevented training by NPC in the moving vehicle

### LINKED ISSUE #21712: Skill Training with NPC while in a moving vehicle
### Expected Behavior
Not allowed to talk to an NPC to complete a quest while in a moving vehicle, especially not allowed to do skill training by the NPC while in a moving vehicle.

### Actual behavior
Vehicle continues forward into lake until training is complete without any way to cancel the skill training ahead of time.  NPC teleports to correct relative position to player once in the lake, which is kind of weird.

### Steps to reproduce the behavior
Drive a vehicle on cruise control past an NPC and complete a quest with skill training as your reward.

Honestly I should have expected this.  RIP Safety Van.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #21712.

### CODE REVIEW

File: src/npctalk.cpp [hunk 1]
```diff
@@ -2255,6 +2256,14 @@ void dialogue::gen_responses( const talk_topic &the_topic )
             // TODO: Allow NPCs to break training properly
             // Don't allow them to walk away in the middle of training
             std::stringstream reasons;
+            int part;
+            vehicle *veh = g->m.veh_at( p->pos(), part );
+            if( veh != nullptr ) {
+                if( abs( veh->velocity ) > 0 ) {
+                    reasons << _( "Let's not do it in the moving vehicle." ) << std::endl;
```
Comment (DracoGriffin) [inline src/npctalk.cpp]: This statement seems to convey something else, perhaps the message could be more along "I'm not going to train you while you're operating a vehicle!" or "I can't train you properly if we're in a moving vehicle!"

File: src/npctalk.cpp [hunk 2]
```diff
@@ -2255,6 +2256,14 @@ void dialogue::gen_responses( const talk_topic &the_topic )
             // TODO: Allow NPCs to break training properly
             // Don't allow them to walk away in the middle of training
             std::stringstream reasons;
+            int part;
+            vehicle *veh = g->m.veh_at( p->pos(), part );
```
Comment (BevapDin) [inline src/npctalk.cpp]: When you don't need the part index, don't request it (use the `map::veh_at` overload without the `part` parameter).
