### PR TITLE
Fix infinite loop on parsing spells on arm64.

### LINKED ISSUE #38704: [Android] Magiclym does not load
# Describe the bug

On the latest experimental version from http://dev.narc.ro/cataclysm/jenkins-latest/Android/Tiles/ the world loading screen does not pass the Magiclysm mod but does not throw any exception.

# Steps To Reproduce

1. Download latest experimental version
2. Create new world with Magiclysm active
3. Create new Character on that World

# Expected Behavior

It should load Magiclysm

### PR DESCRIPTION
**Pull request by JRF63**
#### Summary

SUMMARY: Bugfixes "Fix infinite loop on parsing spells on arm64."

#### Purpose of change

Fixes #38704.

Because of finite precision, `get_level` and `exp_for_level` are not _exactly_ inverses of each other, more so with -ffast-math. What's happening on android is that we get an infinite loop on parsing `Magiclysm/monsters/dragon.json` at this part:
```c++
// fake_spell::get_spell @ magic.cpp
while( sp.get_level() < level_of_spell ) {
    sp.gain_level();
}
```
because `get_level` and `exp_for_level` disagrees on how much experience a level 9 spell should have.

#### Describe the solution

The maximum spell level is 84 - an `int` would overflow on the amount of experience a level 85 would have.

In x86 (with or without -ffast-math) and arm64 (without -ffast-math) the infinite loop will still occur after spell level 47 with the current equation/algorithm. By switching to `double`'s instead of `float`'s this limit is lifted to 84.

#### Describe alternatives you've considered

Make `exp_for_level` not produce an underestimate by scaling level by a bit:
```c++
static int exp_for_level( int level )
{
    // level 0 never needs xp
    if( level == 0 ) {
        return 0;
    }
    // hack to make exp_for_level and get_level agree
    constexpr float nudge = 1.0f + 1e-6f;
    return std::ceil( std::exp( ( ( nudge * level ) - c ) * b ) ) - a;
}
```

#### Testing

Built an experimental release apk and slapped it on my phone. Selected Magiclysm on world creation and made a random character.

#### Additional context

I have a minimal working example that shows this infinite loop. I'll cough it out if anyone wants to play with this.

### CODE REVIEW

File: src/magic.cpp [hunk 1]
```diff
@@ -1070,11 +1070,18 @@ std::string spell::damage_type_string() const
...
 // constants defined below are just for the formula to be used,
 // in order for the inverse formula to be equivalent
 constexpr float a = 6200.0f;
 constexpr float b = 0.146661f;
 constexpr float c = -62.5f;
+#else
+// ARM64 needs double
+constexpr double a = 6200.0f;
+constexpr double b = 0.146661f;
+constexpr double c = -62.5f;
```
Comment (anothersimulacrum) [inline src/magic.cpp:1083]: Shouldn't they lose the `f` here, since they're doubles, or is there magic (heh) I'm not seeing?

Comment (KorGgenT) [reply src/magic.cpp:1083]: i think they should but only because there's technically some implicit casting here i believe

Comment (JRF63) [reply src/magic.cpp:1083]: Oh right.

Comment (Qrox) [reply src/magic.cpp:1083]: Can we just use `exp_for_level` for the calculation of `spell::get_level` though? Subtract from the current exp until it is lower than the required exp of a level, and then return that level.

Comment (JRF63) [reply src/magic.cpp]: > 
> 
> Can we just use `exp_for_level` for the calculation of `spell::get_level` though? Subtract from the current exp until it is lower than the required exp of a level, and then return that level.

This is actually more correct than just throwing more bits at the problem. Transcendental functions aren't that cheap to compute though. How about precomputing them in an array?

**Comment by ZhilkinSerg** [comment]
Just make it double for all architectures maybe?

File: src/magic.cpp (hunk 1 above)
Comment (Qrox) [reply src/magic.cpp]: Precomputing can indeed speed it up, and currently the experience for each level only depends on these constants so it should be pretty straighforward to implement too.

**Comment by JRF63** [comment]
Can I leave it to the maintainers if we would apply this for all archs? Edit rights are enabled.

File: src/magic.cpp (hunk 1 above)
Comment (jbytheway) [reply src/magic.cpp]: I'm not a big fan of a precomputed table, but it might be the best option for another reason: we need to ensure that the thresholds for each level are the same across different platforms, because otherwise when you save your game on one platform and load it on another you might get inconsistent results.

File: src/magic.cpp [hunk 2]
```diff
@@ -1070,11 +1070,18 @@ std::string spell::damage_type_string() const
...
 // in order for the inverse formula to be equivalent
 constexpr float a = 6200.0f;
 constexpr float b = 0.146661f;
 constexpr float c = -62.5f;
+#else
+// ARM64 needs double
+constexpr double a = 6200.0;
+constexpr double b = 0.146661;
+constexpr double c = -62.5;
+#endif
```
Comment (KorGgenT) [inline src/magic.cpp:1084]:
```suggestion
// constants defined below are just for the formula to be used,
// in order for the inverse formula to be equivalent
constexpr double a = 6200.0;
constexpr double b = 0.146661;
constexpr double c = -62.5;
```
agreed with ZS, you yourself said some architectures fail out at level 47

**Comment by ZhilkinSerg** [comment]
Worth backporting to `0.E-branch` for possible `0.E-3`.
