### PR TITLE
Fix distributing food with empties containers

### LINKED ISSUE #37149: Faction Camps: Distributing food with low enjoyability empties containers in the food stockpile
# Describe the bug

Using the action "Distribute Food" will empty all containers placed in the basecamp food zone and place them outside, emptying their contents on the floor if they are below the enjoyability threshold. This includes liquids, which get wasted.

# Steps To Reproduce

1. Have a faction camp with the Basecamp: Food and Basecamp: Storage zones defined
2. Place a container of some edible but unpleasant fluid in the Food zone. (Animal Cooking Oil or Acid Water are two options this definitely occurs with)
3. Use the Distribute Food action from the bulletin board.

# Expected behavior

Containers filled with unappealing foods are left alone instead of being dumped out.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-11235-g00699b2 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

### LINKED ISSUE #40712: Seg Fault on Distributing Food in Faction Camp
# Describe the bug

When using 'Distribute Food' in the faction camp, certain items lead to a seg fault.  Specifically, I found that a box of spaghetti pasta caused it.  Unloading it from the box and trying doesn't seg fault but it also doesn't accept the food.

# Steps To Reproduce

Start Faction Camp
Assign a food zone.
Place box of spaghetti in food zone.
Distribute Food through the bulletin board menu
Observe Seg Fault.

My crash and debug log are below, but I did not include a save.  I explain why in Additional Information.

# Expected behavior

I figure it should distribute the food and leave the box behind or disappear the box as well.  Based on the fact that I can't distribute the loose noodles I figure it might just not be able to distribute these items, but this should still not lead to a seg fault.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2278-gf8f9f52 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    No Fungal Monsters [No_Fungi]
]

# Additional context

I did not provide a save file.  I set one up, but the seg fault only occurs the first time I try to do it.  All attempts after it (even if you reload the save that just seg faulted) lead to the box disappearing and the spaghetti being dropped on the ground but not distributed.  This is also obviously not what should be happening, but it doesn't illustrate the seg fault.  So you'll have to do this yourself, unfortunately.

It was happening to me repeatedly in a video (episode 102 in my tutorial lets play, unfortunately it won't be up on the channel for several days so I can't link it.  Even if I could I don't think it would help any more than my describing it.) but when I set out to actually test it I couldn't get it to repeat reliably, it only occurred sometimes.
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4653829/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4653830/debug.log)

### PR DESCRIPTION
**Pull request by BevapDin**
```SUMMARY: None```

Fixes #37149. It rewrites the whole food distributing block, and thereby also fixes #40712.

I also removed the littering feature. It would teleport empty contains on a specific area (using magic values as coordinates) with no regard for the surround (e.g. into fire, or into an enclosed area).

### CODE REVIEW

**Comment by Fris0uman** [comment]
> I also removed the littering feature

Does that make the containers disapear?

File: src/faction_camp.cpp [hunk 1]
```diff
@@ -3882,66 +3882,93 @@ bool basecamp::distribute_food()
...
-                    } else if( rots_in >= 2 ) {
-                        rot_multip = slow_rot;
-                    } else {
-                        rot_multip = quick_rot;
-                    }
-                    total += comest->get_comestible()->default_nutrition.kcal * rot_multip * i.count();
-                } else {
-                    keep_me.push_back( *comest );
+
+    const auto rot_multip = [&]( const item & it, item * const container ) {
```
Comment (mlangsdorf) [inline src/faction_camp.cpp:3889]:
```suggestion
    const double rot_multip = [&]( const item & it, item * const container ) {
```

File: src/faction_camp.cpp [hunk 2]
```diff
@@ -3882,66 +3882,93 @@ bool basecamp::distribute_food()
...
+        const time_duration rots_in = ( it.get_shelf_life() - it.get_rot() ) / spoil_mod;
+        if( rots_in >= 5_days ) {
+            return 1.;
+        } else if( rots_in >= 2_days ) {
+            return slow_rot;
+        } else {
+            return quick_rot;
+        }
+    };
+    const auto consume_non_recursive = [&]( item & it, item * const container ) {
```
Comment (mlangsdorf) [inline src/faction_camp.cpp:3913]:
```suggestion
    const bool consume_non_recursive = [&]( item & it, item * const container ) {
```

File: src/faction_camp.cpp [hunk 3]
```diff
@@ -3882,66 +3882,93 @@ bool basecamp::distribute_food()
...
+        if( kcal <= 0 ) {
+            // can happen if calories is low and rot is high.
+            return false;
+        }
+        total += kcal;
+        return true;
+    };
+
+    // Returns whether the item should be removed from the map.
+    const auto consume = [&]( item & it, item * const container ) {
```
Comment (mlangsdorf) [inline src/faction_camp.cpp:3935]:
```suggestion
    const bool consume = [&]( item & it, item * const container ) {
```

File: src/faction_camp.cpp [hunk 4]
```diff
@@ -3882,66 +3882,93 @@ bool basecamp::distribute_food()
...
-                    } else if( rots_in >= 2 ) {
-                        rot_multip = slow_rot;
-                    } else {
-                        rot_multip = quick_rot;
-                    }
-                    total += comest->get_comestible()->default_nutrition.kcal * rot_multip * i.count();
-                } else {
-                    keep_me.push_back( *comest );
+
+    const double rot_multip = [&]( const item & it, item * const container ) {
```
Comment (kevingranade) [inline src/faction_camp.cpp:3889]:
```suggestion
    const auto rot_multip = [&]( const item & it, item * const container ) {
```

File: src/faction_camp.cpp [hunk 5]
```diff
@@ -3882,66 +3882,93 @@ bool basecamp::distribute_food()
...
+        const time_duration rots_in = ( it.get_shelf_life() - it.get_rot() ) / spoil_mod;
+        if( rots_in >= 5_days ) {
+            return 1.;
+        } else if( rots_in >= 2_days ) {
+            return slow_rot;
+        } else {
+            return quick_rot;
+        }
+    };
+    const bool consume_non_recursive = [&]( item & it, item * const container ) {
```
Comment (kevingranade) [inline src/faction_camp.cpp:3913]:
```suggestion
    const auto consume_non_recursive = [&]( item & it, item * const container ) {
```

File: src/faction_camp.cpp [hunk 6]
```diff
@@ -3882,66 +3882,93 @@ bool basecamp::distribute_food()
...
+        if( kcal <= 0 ) {
+            // can happen if calories is low and rot is high.
+            return false;
+        }
+        total += kcal;
+        return true;
+    };
+
+    // Returns whether the item should be removed from the map.
+    const bool consume = [&]( item & it, item * const container ) {
```
Comment (kevingranade) [inline src/faction_camp.cpp:3935]:
```suggestion
    const auto consume = [&]( item & it, item * const container ) {
```
