### PR TITLE
Fixed crash when generating map

### LINKED ISSUE #33640: crash when using mapgen_update as the generator for map extras
# Describe the bug

I was trying to use the new functions of #31682 by adding map extras wholly by editing the jsons.  It works, but there were occasional crashes when first generating and loading a world.  I figured out it was only happening when the player first spawned in the shelter and the extras appeared somewhere in his reality bubble. 

# Steps To Reproduce

1. Add mapgen extras.
2. Start new game.
3. crash

# Expected behavior
No crashes. 

# Versions and configuration
 - OS: Windows
 - Game Version: 9544
 - Graphics version: Tiles
 - Mods loaded: vanilla + experiment

# Additional context
I don't have a save, because it crashes on inital load.  I'm uploading the mod I was experimenting with, but I have edited it so road extras spawn with a chance of 2, so 50% of all roads will have an extra, and set the weight for an offending extra super high.  This basically guarantees that it will crash if you spawn in a shelter or other spot next to a road.  
[Extra_Bandits.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3553891/Extra_Bandits.zip)

### LINKED ISSUE #34028: Segfault in submap::get_ter during world generation
I've just started a new game!
```
VERSION: 0.D-7608-gafeb203bf8-dirty
TYPE: Signal
MESSAGE: SIGSEGV: Segmentation fault
STACK TRACE:

	cataclysm(_Z21debug_write_backtraceRSo+0x33) [0x56068bc09dfa]
	cataclysm(+0x180b23a) [0x56068bbda23a]
	cataclysm(+0x180b446) [0x56068bbda446]
	/lib64/libc.so.6(+0x396b0) [0x7fa339eed6b0]
	cataclysm(_ZNK6submap7get_terERK5point+0x33) [0x56068c25dc97]
	cataclysm(_ZNK3map20has_flag_ter_or_furnERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERK8tripoint+0x8e) [0x56068c22af10]
	cataclysm(_ZNK3map8has_flagERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERK8tripoint+0x2b) [0x56068c22aa85]
	cataclysm(+0x1e6b2c7) [0x56068c23a2c7]
	cataclysm(_ZN3map19add_item_or_chargesERK8tripoint4itemb+0x11c) [0x56068c23a7c2]
	cataclysm(+0x281f8d2) [0x56068cbee8d2]
	cataclysm(_ZN7vehicle11remove_partEi+0x44f) [0x56068cbeedb9]
	cataclysm(_ZN7vehicle5smashEfff5pointf+0x6f9) [0x56068cbe7829]
	cataclysm(_ZN3map18add_vehicle_to_mapESt10unique_ptrI7vehicleSt14default_deleteIS1_EEb+0x8f2) [0x56068c33353e]
	cataclysm(_ZN3map11add_vehicleERK9string_idI17vehicle_prototypeERK8tripointiiib+0x326) [0x56068c332ae8]
	cataclysm(_ZN3map11add_vehicleERK9string_idI17vehicle_prototypeERK5pointiiib+0x7c) [0x56068c332680]
	cataclysm(+0x1eb9f4c) [0x56068c288f4c]
	cataclysm(_ZN9MapExtras14apply_functionERK9string_idI9map_extraER3mapRK8tripoint+0xb7) [0x56068c29bedb]
	cataclysm(_ZN9MapExtras14apply_functionERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEER3mapRK8tripoint+0x53) [0x56068c29c759]
	cataclysm(_ZN3map8generateERK8tripointRK10time_point+0x821) [0x56068c2f8f6b]
	cataclysm(_ZN3map5loadnERK8tripointb+0x470) [0x56068c249afa]

	Attempting to repeat stack trace using debug symbols...
	debug_write_backtrace(std::ostream&)
	.../src/debug.cpp:620
	log_crash
	.../src/crash.cpp:264
	signal_handler
	.../src/crash.cpp:293
	??
	??:0
	submap::get_ter(point const&) const
	.../src/submap.h:86
	map::has_flag_ter_or_furn(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tripoint const&) const
	.../src/map.cpp:2323
	map::has_flag(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, tripoint const&) const
	.../src/map.cpp:2288
	operator()
	.../src/map.cpp:4282 (discriminator 2)
	map::add_item_or_charges(tripoint const&, item, bool)
	.../src/map.cpp:4320
	operator()
	.../src/vehicle.cpp:1736 (discriminator 3)
	vehicle::remove_part(int)
	.../src/vehicle.cpp:1750 (discriminator 6)
	vehicle::smash(float, float, float, point, float)
	.../src/vehicle.cpp:751
	map::add_vehicle_to_map(std::unique_ptr<vehicle, std::default_delete<vehicle> >, bool)
	.../src/mapgen.cpp:6880
	map::add_vehicle(string_id<vehicle_prototype> const&, tripoint const&, int, int, int, bool)
	.../src/mapgen.cpp:6774 (discriminator 2)
	map::add_vehicle(string_id<vehicle_prototype> const&, point const&, int, int, int, bool)
	.../src/mapgen.cpp:6730
	mx_roadblock
	.../src/map_extras.cpp:631 (discriminator 4)
	MapExtras::apply_function(string_id<map_extra> const&, map&, tripoint const&)
	.../src/map_extras.cpp:2726
	MapExtras::apply_function(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, map&, tripoint const&)
	.../src/map_extras.cpp:2783 (discriminator 2)
	map::generate(tripoint const&, time_point const&)
	.../src/mapgen.cpp:162
	map::loadn(tripoint const&, bool)
	.../src/map.cpp:6852
```

### PR DESCRIPTION
**Pull request by ipcyborg**
#### Summary
```SUMMARY: Bugfixes "Crash when generating map"```

#### Purpose of change
Fixes #33640, fixes #34028

#### Describe the solution
Originally the submap was inserted always at 0 z-level { gridx, gridy }, but used, saved and deleted on specific z-level i, j, p.z.
Fixed new submap inserting on correct z-level. Added some extra checks.

#### Describe alternatives you've considered
1) Initialize full `grid` in `map` constructor, not in `generate`, when it is resized.  Too much of a change, probably incorrect.
2) Delay the initialization of `grid` until it is required (when `getsubmap` is used and there is `nullptr` there). Not sure if this is efficient. 

#### Additional context
Thanks for a great mod `Extra_Bandits.zip` provided in #33640 - it was almost 100% reproducible.
Tested after the fix for about 10 new starts, no crash. Still more testing is required.

### CODE REVIEW

File: src/mapgen.cpp [hunk 1]
```diff
@@ -116,7 +116,13 @@ void map::generate( const tripoint &p, const time_point &when )
     //  because other submaps won't be touched.
     for( int gridx = 0; gridx < my_MAPSIZE; gridx++ ) {
         for( int gridy = 0; gridy < my_MAPSIZE; gridy++ ) {
-            setsubmap( get_nonant( { gridx, gridy } ), new submap() );
+            if( zlevels ) {
+                for( int gridz = -OVERMAP_DEPTH; gridz <= OVERMAP_HEIGHT; gridz++ ) {
+                    setsubmap( get_nonant( { gridx, gridy, gridz } ), new submap() );
```
Comment (BevapDin) [inline src/mapgen.cpp]: The new submaps (those that are not part of the generated map) are not properly delete. See the end of this function:

There new submaps that should be kept (have been generated here) are saved, and the other submaps are delete again. But the loops there only go over X and Y, ignoring the Z-level.

Note that map generates only 2x2 submaps (on a specific z-level), anything outside of that range may already exist.

Why does the mapgen code even access the other z-levels, the maps there may have already been generated!

Comment (ipcyborg) [reply src/mapgen.cpp]: >are not properly delete.

Agreed, it needs to be deleted there `delete get_submap_at_grid( { i, j, p.z } );`. Also probably should set the submap to `nullptr` after deletion.

From the comment in code:
> At the bottom of this function, we save the upper-left 4 submaps, and delete the rest.

Looks like I am missing the point of this generation. Will recheck this function and this fix.

May be it is not required to initialize full gird, but instead add the null-checks for all usages of submaps?

Comment (ipcyborg) [reply src/mapgen.cpp]: I think I have found the origin of this ussue: the submap was inserted always at 0 z-level  `{ gridx, gridy }`, but used, saved and deleted on specific z-level `i, j, p.z`.

Fixed new submap inserting on correct z-level. Added some extra checks.
