### PR TITLE
Smoking Rack CTD #32468

### LINKED ISSUE #32468: Smoking Rack (Lighting while Rack has Dehydrated Meat causes Crash)
# Describe the bug

Crash from using Smoking Rack on dehydrated meat (If you leave the meat in the rack and smoke it, when its dehydrated)

# Steps To Reproduce

 1) Create Smoking Rack
 2) Add Meat
 3) Light Rack
 4) Wait for Meat to Smoke and Remove from Rack
 5) Put Smoked Meat into rack
 6) Light Rack
 7) Wait for Smoking to finish
 8) Try and Light Rack again, Get Crash to Desktop.

# Expected behavior
 Message That the meat is cooked
Don't let a player Smoke food Unless they have emptied the rack First

# Versions and configuration

 - OS: Windows 7 64bit Home Premium
 - Game Version: 0.D-5703-g850f19c (I Think). Build #9344
 - Graphics version: Tiles
 - Mods loaded:   "dda",  "no_npc_food",  "makeshift",  "More_Survival_Tools",  "mutant_npcs",  "hydroponics",  "more_locations",  "cityside",  "FujiStruct",  "Urban_Development",  "deoxymod",  "blazemod",  "Tanks",  "safeautodoc",  "novitamins",  "stats_through_kills",  "alt_map_key"

PS:
I apologize I don't have a save that causes this, It should be fairly quick to setup though. If its absolutely needed I will make one and add it later. Also I will obtain a crash log at that time If required (I had 2 crashes happen and don't know which one the log I have is for).

### PR DESCRIPTION
**Pull request by TRScheel**
#### Summary: 
```SUMMARY: Bugfixes "Smoking Rack (Lighting while Rack has Dehydrated Meat causes Crash)"```

#### Purpose of change
Fixes #32468

I've confirmed this solves the CTD by reproducing it before and after.

#### Describe the solution
Swaps the order of item deletion and movement when something isn't smokable.

#### Describe alternatives you've considered
Using the assign_activity process

### CODE REVIEW

**Comment by NickGrease** [comment]
Summary line should look like:
`SUMMARY: Bugfixes "Smoking Rack (Lighting while Rack has Dehydrated Meat causes Crash)"`
Note: Bugfix**es**, no need to include PR# in summary
Note2: Can enclose line with backticks (`) - though I think that's just a style, not a rule.

File: src/iexamine.cpp [hunk 1]
```diff
@@ -4430,8 +4430,8 @@ static void smoker_activate( player &p, const tripoint &examp )
                      false ) );
             add_msg( _( "You remove %s from the rack." ), it.tname() );
             g->m.add_item_or_charges( p.pos(), it );
-            g->m.i_rem( examp, &it );
             p.mod_moves( -p.item_handling_cost( it ) );
+            g->m.i_rem(examp, &it);
```
Comment (NickGrease) [inline src/iexamine.cpp]:
```suggestion
            g->m.i_rem( examp, &it );
```

Comment (kevingranade) [reply src/iexamine.cpp]: This formatting thing is the only thing holding up a merge.
