### PR TITLE
Fix crash from changing monster::special_attacks while iteration over it.

### LINKED ISSUE #14430: Game crashes frequently for unknown reason
Current version is 0.C-8197-g1f7d1bc, but this started in earlier versions within the last three days or so. Ncurses, Ubuntu 14.04.

Screenshot: https://www.dropbox.com/s/3fma21yll088rvl/crashscreen.png?dl=0
Save: https://www.dropbox.com/s/h1dhuetha02kwzk/crash.zip?dl=0

The game crashes very frequently in some areas. It might be related to certain monsters and their special attacks. This usually happens when fungals are nearby, but I've also run into it several times in science labs and in the vicinity of slime pits. The save file I've provided always crashes for me within 5 turns if I keep driving forward with the speed the car is currently going. I managed to get away and continue the game by accelerating to high speeds and driving away before the crash happened.

### PR DESCRIPTION
**Pull request by BevapDin**
Thanks to @CIB for the excellent save.

Fixes #14430 (at least for the given saves).

The save has a blob, which has the special attack function `formblob`, which can transform the monster that performs the action (shrink to a smaller blob type). This is done by calling `monster::poly`, which clears and repopulates the `special_attacks` map. This invalidates the iterators that are used in `monmove` and causes the crash there.

I changed the code to iterate over the map in the monster type, which should never change at all. If the monster is changed, it will continue to iterate over the map of the previous type. If the new monster type has the same attacks, they will be execute just fine (no change at all), but if the new type does not have them, they are ignored.

### CODE REVIEW

**Comment by sparr** [comment]
You seem to have also changed the timing logic so that a special attack will only proc on a turn where its cooldown starts at zero, rather than on a turn where it starts at 1 and decrements to zero.

I approve of this change. It will slightly change the balance on some existing monsters, but it makes the cooldown numbers more sensible to me. I discussed this non-feature on IRC when I was touching this code.

File: src/monmove.cpp [hunk 1]
```diff
@@ -484,19 +484,33 @@ void monster::move()
...
+        if( local_attack_data.cooldown == 0 && !pacified && !is_hallucination() ) {
+            if( !sp_type.second.attack( this ) ) {
+                continue;
             }
-
-            if( special_attack.cooldown == 0 && !pacified && !is_hallucination() ) {
-                if (type->special_attacks.at(special_name).attack( this )) {
-                    reset_special(special_name);
-                }
+            // `special_attacks` might have changed at this point. Sadly `reset_special`
```
Comment (CIB) [inline src/monmove.cpp]: Good, I like keeping info like this around for future devs. :+1:
