### PR TITLE
Check if empty before trying to access first item

### LINKED ISSUE #82752: Crash While Looting
### Describe the bug

The game keeps crashing every time I try to loot some corpses. Something gone wrong with the inventory probably. 

### Attach save file

[Lacost-trimmed.tar.gz](https://github.com/user-attachments/files/22129443/Lacost-trimmed.tar.gz)

### Steps to reproduce

1. Load the save.
2. Try to loot nearby corpses.

### Expected behavior

No crashes?

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.5796 (22H2)
- Game Version: cdda-experimental-2025-09-03-0632 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Minimod: No Skill Rust [minimod_no_rust]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/22129464/crash.log)

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
Fix #82752, i.e. crash while looting.

#### Describe the solution
Check that the pocket you're accessing isn't empty before trying to access its first item.

#### Testing
Verified the game crashed when trying to 'g'et items from the corpse to the NE of the PC in the bug report save before the change.
Verified it's possible to access the same corpse without crashing after the save.

#### Additional context
I'm not convinced the code change is the correct one, as I'm not familiar with how pockets work. It's obvious you can't access the first item of an empty pocket, so that change is a given. I THINK an empty pocket means things are good from the perspective of the tests that are blocked, but there are a bit too many negations involved, so I'd appreciate if someone who knows about pockets could take a look at the logic.

### CODE REVIEW

**Comment by Brambor** [comment]
I tried to simplify it logically, but with no success:

```cpp
// Original
ip == nullptr || ( ip &&
                   ( !ip->can_contain( item_copy ).success() ||
                     ( !ip->empty() && ( !ip->front().can_combine( item_copy ) ||
                             item_copy.typeId() != ip->front().typeId() ) ) ) )

// Styled:
ip == nullptr
|| ( ip
	&& ( !ip->can_contain( item_copy ).success()
		|| ( !ip->empty()
			&& ( !ip->front().can_combine( item_copy )
				|| item_copy.typeId() != ip->front().typeId() ) ) ) )

// One of my attempts:
ip == nullptr
|| ( ip
	&& !( ip->can_contain( item_copy ).success()
		&& ( ip->empty()
			|| ( ip->front().can_combine( item_copy )
				&& item_copy.typeId() == ip->front().typeId() ) ) ) )
```

Negation of expression in brackets is (probably) worse than three direct negations.

But I feel that stylised like mine, it is more readable.

**Comment by PatrikLundell** [comment]
We are under the tyrant rule of Astyle, and so are not allowed to use any formatting except the one it dictates. Nevertheless, thanks for trying to improve that mess.

**Comment by Gottfrei** [comment]
why this fix is still not merged? its a critical bug basically.

**Comment by PatrikLundell** [comment]
I would guess it's taken time because there haven't been a deluge of people who were willing to review the logic, until @Brambor stepped up yesterday.

**Comment by Brambor** [comment]
> We are under the tyrant rule of Astyle, and so are not allowed to use any formatting except the one it dictates.

It is not too restrictive, however. One can format the code, then astyle it and see what it produces. The following code is astyled:

```cpp
                        if( ip == nullptr
                            || ( ip
                                 && ( !ip->can_contain( item_copy ).success()
                                      || ( !ip->empty()
                                           && ( !ip->front().can_combine( item_copy )
                                                || item_copy.typeId() != ip->front().typeId() ) ) ) ) ) {
```

**Comment by PatrikLundell** [comment]
It turns out @Brambor is correct: Astyle does apparently have some loopholes where there are some flexibility in formatting. Thus, I've modified the formatting of the code (and pushed it through Astyle) as suggested.

**Comment by RenechCDDA** [comment]
> why this fix is still not merged? its a critical bug basically.

@Gottfrei This is *not* critical. Please do not make comments asking why X or Y hasn't been done yet.

Everyone working on this game is a volunteer. We don't get paid. We don't have schedules for when we do this. We all have lives, and nobody is forcing you to play on a specific version. If you cannot deal with that, do not play on the versions you have issues with. Our official recommendation is that you should be playing *stable*, where this sort of issue will never occur.

A merger needs to look at it and will generally build and test it in some manner to make sure it works as claimed. At the very least they need to look at what it does and press the big red button. There's a handful of mergers, and they really do have lives. Reviewing PRs, especially in our gigantic codebase, is not easy. It's not something you can do during a TV commercial.

**Comment by Gottfrei** [comment]
@RenechCDDA it is critical. crash that appears in such a routine activity as looting with constant frequency is definetly a big issue. and I'm here not to argue with you about how to work with open source projects.

**Comment by kevingranade** [comment]
@Gottfrei We do not offer support at a "critical issue" level, the SLA we offer is "when we get around to it", which is part of the reason that it remains a fun activity we do for free.

Your demands are invalid, and by repeating yourself and not listening to feedback they are becoming spam instead of a mere misunderstanding. If it continues you will not be allowed to continue commenting.

File: src/game_inventory.cpp [hunk 1]
```diff
@@ -563,10 +563,11 @@ class pickup_inventory_preset : public inventory_selector_preset
                                     item_copy, nullptr, false );
 
                         item_pocket *ip = pocke.second;
-                        if( ip == nullptr || ( ip &&
-                                               ( !ip->can_contain( item_copy ).success() ||
-                                                 !ip->front().can_combine( item_copy ) ||
-                                                 item_copy.typeId() != ip->front().typeId() ) ) ) {
+                        if( ip == nullptr ||
+                            ( ip &&
```
Comment (akrieger) [inline src/game_inventory.cpp]: We don't need this `ip` test if we already tested if its nullptr (the rhs of the `||` will only be evaluated if the lhs is false, i.e. `ip` is not nullptr).

File: src/game_inventory.cpp [hunk 2]
```diff
@@ -563,10 +563,11 @@ class pickup_inventory_preset : public inventory_selector_preset
...
+                              ( !ip->can_contain( item_copy ).success() ||
+                                ( !ip->empty() && ( !ip->front().can_combine( item_copy ) ||
+                                                    item_copy.typeId() != ip->front().typeId() ) ) ) ) ) {
```
Comment (akrieger) [inline src/game_inventory.cpp]:
```suggestion
                        if( ip == nullptr ||
                              !ip->can_contain( item_copy ).success() ||
                                ( !ip->empty() && ( !ip->front().can_combine( item_copy ) ||
                                                    item_copy.typeId() != ip->front().typeId() ) ) ) ) {
```

Comment (PatrikLundell) [reply src/game_inventory.cpp]: Implemented your suggestion, but managed to trick astyle into a slightly nicer formatting.

**Comment by Gottfrei** [comment]
@kevingranade im sorry. i didn't know that you solve problems regardless of their priority.
