### PR TITLE
fixes#54183

### LINKED ISSUE #54183: Pressing enter twice in a new diary page crashes the game
### Describe the bug

-

### Steps to reproduce

1. Open the diary.
2. Create your very first page (`n`)
3. Write something. Press Enter twice (to separate paragraphs, more or less)
4. Crash

```
/usr/include/c++/11.1.0/bits/basic_string.h:1123: std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::back() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference = char&]: Assertion '!empty()' failed.
The program has crashed.
See the log file for a stack trace.
CRASH LOG FILE: /home/user/.config/cataclysm-dda/crash.log
VERSION: 0.F
TYPE: Signal
MESSAGE: SIGABRT: Abnormal termination
STACK TRACE:

    cataclysm-tiles(debug_write_backtrace(std::ostream&)+0x46) [0x55ed4f1e7b5a]
    cataclysm-tiles(+0x9f45d2) [0x55ed4f1c55d2]
    cataclysm-tiles(+0x9f485b) [0x55ed4f1c585b]
    /usr/lib/libc.so.6(+0x3cda0) [0x7fea1716dda0]
    /usr/lib/libc.so.6(gsignal+0x142) [0x7fea1716dd22]
    /usr/lib/libc.so.6(abort+0x116) [0x7fea17157862]
    cataclysm-tiles(std::type_info::name() const+0) [0x55ed4eef4826]
    cataclysm-tiles(string_editor_window::get_line_and_position(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, int)+0xa8) [0x55ed4fb8a062]
    cataclysm-tiles(string_editor_window::query_string[abi:cxx11](bool)+0xd9) [0x55ed4fb8ac15]
    cataclysm-tiles(diary::edit_page_ui(catacurses::window&)+0x9d) [0x55ed4f23988f]
    cataclysm-tiles(diary::show_diary_ui(diary*)+0x7cf) [0x55ed4f23a241]
    cataclysm-tiles(game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)+0x46c9) [0x55ed4f3a6ea3]
    cataclysm-tiles(game::handle_action()+0xb79) [0x55ed4f3a957f]
    cataclysm-tiles(do_turn()+0x5bb) [0x55ed4f24561d]
    cataclysm-tiles(main+0x18b7) [0x55ed4edd04d0]
    /usr/lib/libc.so.6(__libc_start_main+0xd5) [0x7fea17158b25]
    cataclysm-tiles(_start+0x2e) [0x55ed4eeed9ee]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    ??:?
    init_crash_handlers()
    ??:?
    init_crash_handlers()
    ??:?
    __restore_rt
    sigaction.c:?
    __GI_raise
    :?
    __GI_abort
    :?
    std::type_info::name() const
    ??:?
    string_editor_window::get_line_and_position(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, int)
    ??:?
    string_editor_window::query_string[abi:cxx11](bool)
    ??:?
    diary::edit_page_ui(catacurses::window&)
    ??:?
    diary::show_diary_ui(diary*)
    ??:?
    game::do_regular_action(action_id&, avatar&, cata::optional<tripoint> const&)
    ??:?
    game::handle_action()
    ??:?
    do_turn()
    ??:?
    main
    ??:?
    __libc_start_main
    ??:?
    _start
    ??:?
```

### Expected behavior

It does not crash.

### Screenshots

_No response_

### Versions and configuration

- OS: Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.F [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by LFKrause**
#### Summary
Bugfixes "Fix calling .back() on empty string"

#### Purpose of change
Fixes #54183

#### Describe the solution
Its fixes the bug by checking for empty string before trying to call .back()

#### Testing
1. Open the Diary.
2. Press (n) for new page
3. Press 'enter' to Edit the page
4. Press 'enter' multiple time
game should not crash

### CODE REVIEW

**Comment by kevingranade** [comment]
Run make astyle in your project directory and commit the changes it makes.

File: src/string_editor_window.cpp [hunk 1]
```diff
@@ -42,7 +42,7 @@ std::pair<int, int> string_editor_window::get_line_and_position( std::vector<std
         utf8_wrapper linetext( foldedtext[i] );
         int temp = linetext.display_width();
         //foldstring, cuts " " away, so it is possible to get a hughe disconect between folded and unfolded string.
-        temp += ( foldedtext[i].back() != ' ' ) ? 1 : 0;
+        if(!foldedtext[i].empty()) temp += ( foldedtext[i].back() != ' ' ) ? 1 : 0;
```
Comment (Wishbringer) [inline src/string_editor_window.cpp:45]:
```suggestion
        if( !foldedtext[i].empty() ) temp += ( foldedtext[i].back() != ' ' ) ? 1 : 0;
```
I think these are the only changes that's needed (easier than trying to understand astyle).
