### PR TITLE
Head encumb fix

### LINKED ISSUE #12010: Headgear with encumbrance > 20 is unwearable
I've tried putting on a great helm (enc 40) and it says "You can't wear a helmet!"

Problem appears to be in this line https://github.com/CleverRaven/Cataclysm-DDA/blob/master/src/player.cpp#L10218 : it forbids wearing any headwear with enc > 20.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11056226-headgear-with-encumbrance-20-is-unwearable?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by PropaneSoup**
Fixes #12010. You'll still need to wear your balaclava (fits) before your barbute helmet, but now you'll be able to wear it at all.

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -10215,7 +10215,7 @@ bool player::wear_item(item *to_wear, bool interactive)
         }
 
         // this simply checked if it was zero, I've updated this for the new encumb system
-        if (to_wear->covers(bp_head) && (encumb(bp_head) + to_wear->get_encumber()) > 20) {
+        if (to_wear->covers(bp_head) && (encumb(bp_head) > 10 || ((to_wear->get_encumber()) < 10 && to_wear->has_flag("FIT")))) {
```
Comment (KA101) [inline src/player.cpp]: I'd feel a little more comfortable with the OR'd component in parens.  Probably not necessary, but wev.
