### PR TITLE
Fix placement of basement stairs

### LINKED ISSUE #24090: Downstairs to basements aren't spawning
Game version: 
Build 7486

Operating system: 
Windows 7

Tiles or curses: 
Tiles

Mods active: 
Filthy Clothing, Disable NPC Needs, Simplified Nutrition

### Expected behavior
Downstairs to basements.

### Actual behavior
Only 4/80 basements upstairs tested are connected to downstairs. World settings seemed to have no effects (City size& spacing as well as "Align up and down stairs").

Tested 20 basements each out of 2 maps with citysize 3, city spacing 7, align up and down stairs off; 
1 map with 4/4, align up and down stairs off; 1 map with 4/4, align up and down stairs on. Other settings are on default. 

### Steps to reproduce the behavior
Create a world
Debug Reveal map
Debug long range teleport into basements
Exit the basements (Use clairvoyance artifact, short range teleport & kill all monsters for maximum convenience.)

### PR DESCRIPTION
**Pull request by ZhilkinSerg**
# What was changed:

- added function  in `mapgendata` struct to check terrain below current map;
- moved basement stairs placement to separate function (`place_stairs`);
- added call to new function for json mapgen - fixes #24090;
- additionally fixed prepper house to appear in `alt_map_key` mod.

### CODE REVIEW

File: src/mapgen_functions.cpp [hunk 1]
```diff
@@ -275,6 +276,17 @@ bool mapgendata::is_groundcover( const ter_id iid ) const {
     return false;
 }
 
+bool mapgendata::has_basement() const
+{
+    std::vector<std::string> all_basements = region.city_spec.basements.all;
+    for( auto b : all_basements ) {
```
[the remark this answers is not in the document]
Comment (ZhilkinSerg) [reply src/mapgen_functions.cpp]: It won't be possible to use `t_below` unless inside of `any_of` unless I put value of `t_below` to square brackets which is only possible for variables, therefore it will look like this to compile successfully:

```c++
bool mapgendata::has_basement() const
{
    std::vector<std::string> all_basements = region.city_spec.basements.all;
    oter_id what_is_below = t_below;
    return std::any_of( all_basements.begin(),
    all_basements.end(), [what_is_below]( const std::string & b ) {
        return what_is_below == oter_id( b );
    } );
}
```

[the remark this answers is not in the document]
Comment (AMurkin) [reply src/mapgen_functions.cpp]: I see. Thanks.

File: src/overmap.h [hunk 2]
```diff
@@ -46,6 +46,7 @@ class building_bin {
         building_bin() {};
         void add( const overmap_special_id &building, int weight );
         overmap_special_id pick() const;
+        std::vector<std::string> all;
```
Comment (ZhilkinSerg) [inline src/overmap.h]: Note: It would be more clear to use `std::vector<oter_id>` here, but this causes error during game loading, so I stuck with `std::string`.

**Comment by AMurkin** [comment]
Nice!

**Comment by BorkBorkGoesTheCode** [comment]
What's the priority for fixing this bug?

**Comment by ZhilkinSerg** [comment]
> What's the priority for fixing this bug?

The changes are not trivial, so I don't want to self-merge and we better wait for someone else to review and merge (@kevingranade, @BevapDin, @codemime, @Rivet-the-Zombie, @illi-kun).

In the meanwhile I can upload archive with Windows x64 binary with this fix merged, so people could test basement downstairs placement.

File: src/mapgen_functions.cpp [hunk 3]
```diff
@@ -276,6 +276,17 @@ bool mapgendata::is_groundcover( const ter_id iid ) const {
     return false;
 }
 
+bool mapgendata::has_basement() const
+{
+    std::vector<std::string> all_basements = region.city_spec.basements.all;
```
Comment (woutershep) [inline src/mapgen_functions.cpp]: Shouldn't this be a const reference instead of a expensive deep copy?

File: src/mapgen_functions.cpp [hunk 4]
```diff
@@ -4167,3 +4113,72 @@ void madd_field( map *m, int x, int y, field_id t, int density )
     tripoint actual_location( x, y, m->get_abs_sub().z );
     m->add_field( actual_location, t, density, 0 );
 }
+
+void place_stairs( map *m, oter_id terrain_type, mapgendata dat,
+                   const int actual_house_height, const int lw, const int rw )
+{
+    if( dat.has_basement() ) {
```
Comment (woutershep) [inline src/mapgen_functions.cpp]: Since you moved this into it's own function you can drop an entire level of indentation by doing an early return with `if( !dat.has_basement() ) return;`

**Comment by Night-Pryanik** [comment]
Should this also fix #22010?

**Comment by ZhilkinSerg** [comment]
> Should this also fix #22010?

Most likely not.

File: src/mapgen.cpp [hunk 5]
```diff
@@ -1928,6 +1929,8 @@ void mapgen_function_json::generate( map *m, const oter_id &terrain_type, const
         lua_mapgen( m, terrain_type, md, t, d, luascript );
     }
 
+    place_stairs( m, terrain_type, md );
```
Comment (BrianLefler) [inline src/mapgen.cpp]: Should place_stairs go 4 lines lower, after the call to m->rotate(...) ?

Seems like we should want it to be one of the last things to happen in json creation, both as a general precaution and specifically so that ALIGN_STAIRS (if on) is trying to align with the final orientation, not pre-rotation.

Comment (ZhilkinSerg) [reply src/mapgen.cpp]: Could be true, but I am not sure - stairs code in house function was located prior to rotation before I have moved it to a separate method.
