### PR TITLE
Fix visible tiles revealing invisible tiles below

### LINKED ISSUE #66040: 3D vision lets you see unseen tiles below
### Describe the bug

It seems the newly added 3D vision (#65738) does not take the visibility of tiles below into account, letting you see what is below even if the tiles cannot be seen from the player character's position.

Pinging @Rewryte as the author of the change.

### Attach save file

N/A

### Steps to reproduce

1. Turn 3D fov on
2. Go into look around mode and look from z-levels above
3. Notice that the tiles not seen on the current z-level can be seen from above

### Expected behavior

Unseen tiles are hidden and map memory is displayed instead if available

### Screenshots

Unseen tiles in the current z-level:

image

The tiles are visible from two z-levels above:

image

### Versions and configuration

bd8b8abd02b4d4d0022dd048e706344e884e4789

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Rewryte**
#### Summary
Bugfixes "Fix visible tiles revealing invisible tiles below"

#### Purpose of change
The way 3D vision currently handles tile visibility is by calculating visibility variables for the current z-level and have every z-level underneath inherit the same values.  In cases where a tile on the current z-level should be visible but the tile underneath should not, the player will be able to see both tiles due to the non-visible tile underneath inheriting the visibility variables of the visible tile above it.  Correcting this will fix #66040.  Also a prerequisite for the lightmap changes in #67434.

#### Describe the solution
There are two parts to this solution:

1. Instead on updating the visibility cache on the current z-level only, we update the z-levels below as well, limited by the 3D vertical range setting.
2. In the tileset code, pull new variables from the visibility cache on each z-level to determine light level.

Naturally, these make processing visibility somewhat more CPU intensive.  To compensate, map cache and visibility cache are no longer calculated every draw.  Any event that alters these can simply call `map::build_map_cache` and `map::update_visibility_cache` instead.  This involves the removal of the temporary fix introduced in #15868.  The issues targeted by the fix (#15842 and #15854) are not reproducible.

Overall, these changes have a positive effect on draw performance leading to an 11% decrease in draw times.

#### Testing
Compiles ok.
Confirmed that invisible tiles no longer show as visible when viewing visible tiles on a higher z-level.

Before:
before
After:
after

### CODE REVIEW

**Comment by Rewryte** [comment]
This will be in draft until optimizations are complete.  Currently seeing a 57.6% increase in draw times.

**Comment by Rewryte** [comment]
Currently fixing visual bugs resulting from the removal of map cache and visibility cache calculations from `game::draw`

**Comment by Maleclypse** [comment]
Is this intended to still be in draft?  No stress if yes. It just reads as if it's ready to go possibly.

**Comment by Rewryte** [comment]
> Is this intended to still be in draft? No stress if yes. It just reads as if it's ready to go possibly.

It's more or less done.  Tests are passing on my end (MSYS2).  Just pushed out one more fix to prevent cache bloat during tests.

**Comment by ehughsbaird** [comment]
FYI, this resulted in a massive increase in test run times https://github.com/CleverRaven/Cataclysm-DDA/issues/68154.

File: src/player_activity.cpp [hunk 1]
```diff
@@ -240,23 +240,28 @@ void player_activity::do_turn( Character &you )
...
-                no_drink_nearby_for_auto_consume = true;
+            if( you.get_thirst() > 130 && !no_drink_nearby_for_auto_consume ) {
+                int consume_moves = get_auto_consume_moves( you, false );
+                moves_left += consume_moves;
+                if( consume_moves == 0 ) {
+                    no_drink_nearby_for_auto_consume = true;
+                }
             }
         }
+        // Also update map and visibility caches every 2 minutes
```
Comment (ZhilkinSerg) [inline src/player_activity.cpp:261]: Why?

Comment (Rewryte) [reply src/player_activity.cpp:261]: Lighting conditions can change while the player is performing an activity, such as a construction that takes place through sunrise.  Now that visibility is no longer calculated every draw, it should be done here for the player to perceive a lighting change during the activity.  Doing so every turn would seem excessive given the speed of activities, so I opted for a calculation every 2 minutes, similar to hunger.

Comment (ZhilkinSerg) [reply src/player_activity.cpp:261]: I don't think it is a good approach. We can update player hunger every 2 minutes, but it is not good for visibility or lighting. Lighting cache should be updated whenever lighting conditions change, visibility cache should be updated when visibility changes - e.g. when lighting condition change, when player moves, when player constructs something, when fields around player change their state, etc.

Comment (Brambor) [reply src/player_activity.cpp:261]: Can't you get when to update from world time implicating light level change throughout sunset / sunrise?
I don't know if it is a good solution, but it would react to the change directly and should be faster if the brightness doesn't change.
It would still be rebuilding unnecessarily when player is underground and doesn't see natural light.

Comment (Rewryte) [reply src/player_activity.cpp:261]: Current plan is to make the conditions more general rather than specific, so mainly position and time.  Time in particular, should cover nearly all the conditions mentioned here.  To keep everything in one place, I would advice that further suggestions be made in #68138.  Thanks.
