### PR TITLE
[CR]Fix traps ignoring monster armor

### LINKED ISSUE #25713: Trap damage ignores armor
In addition to [being invulernable](https://github.com/CleverRaven/Cataclysm-DDA/issues/23540), traps also completely bypass armor when doing damage. This allows otherwise imposing enemies like tank drones or armored zombies to be easily felled by the mightly wood-and-nail nailboard trap.

Obviously, an infinitely re-usable trap that can also fell the most powerful monsters in the game is somewhat of a balancing concern.

### PR DESCRIPTION
**Pull request by cavos**
#### Summary
```SUMMARY: Bugfixes "Fix traps ignoring monster armor"```

#### Purpose of change
Fixes #25713 - Trap damage ignores armor

#### Describe the solution
Fixed the issue by replacing `apply_damage` by `deal_damage` for monster instances.

#### Additional context
For discussion:
- some traps (eg. caltrops) deal different damage for player and monster (usually monster is hurt less) - is this desired?
- lava trap: how to apply fire resistance to damage?

### CODE REVIEW

File: src/trapfunc.cpp [hunk 1]
```diff
@@ -102,16 +102,13 @@ void trapfunc::beartrap( Creature *c, const tripoint &p )
 
         // Actual effects
         c->add_effect( effect_beartrap, 1_turns, hit, true );
-        monster *z = dynamic_cast<monster *>( c );
+        damage_instance d;
+        d.add_damage( DT_BASH, 12 );
+        d.add_damage( DT_CUT, 18 );
+        c->deal_damage( nullptr, hit, d);
```
Comment (ZhilkinSerg) [inline src/trapfunc.cpp]: Missing whitespace after between d and right parenthesis.

**Comment by kevingranade** [comment]
> some traps (eg. caltrops) deal different damage for player and monster (usually monster is hurt less) - is this desired?

It's not ideal, but they have different HP levels too so it's not absolutley necessary.

> lava trap: how to apply fire resistance to damage?

I'm not too worried about this, we can handle it in another PR.
