### PR TITLE
Unload partial ammo of wielded item without duplication

### LINKED ISSUE #47001: Unloading the a STANAG magazine causes the bullet to duplicate
# Describe the bug

When unloading a magazine with a few bullets inside and a full inventory you get prompted to drop the magazine, if you do, the bullets get duplicated, half inside the magazine and half in your hands. You get an error message when unloading the magazine
(edit: apparently it only works with a magazine that was naturally generated with only a few bullets. The bug doesn't work if you reload the magazine before or if the magazine has a bullet count bigger than one digit). 
(edit 2: it also works with shotguns and other magazines).

# Steps To Reproduce

1. Have a full inventory;
2. Hold a STANAG magazine in your hands;
3. Unload the magazine;
4. When prompted, drop the magazine.

# Expected behavior

The bullets get duplicated, with half of them inside the magazine and half in your hands. Unloading the magazine causes a error screen to appear.

# Screenshots

-magazine with bullets inside-

-unloading causes an error message to appear-

-getting prompted to drop the magazine-

-half of the bullets in my hand-

-other half of the bullets still inside the magazine-

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9181-g308bec1-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod [crt_expansion],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Aftershock [aftershock],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Crazy Cataclysm [crazy_cataclysm],
    Crazy Cataclysm - UndeadPeople Tileset [CrazyCataclysmUDP],
    Mythical Martial Arts [MMA],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Fuji's Military Profession Pack [fuji_mpp],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Bionic Slots [cbm_slots]
]

# Additional context
I forgot to take a screenshot of the error before pressing to ignore...
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/5863068/debug.log)

### LINKED ISSUE #48842: Thread duplication
# Describe the bug

Trying to (U)nload a partial amount of Thread (and Nomex/Sinew) from a (w)ielded Tailor's Kit with a full inventory gives the error
```
DEBUG    : Tried removing item from object which did not contain it

 FUNCTION : item visitable::remove_item(item&)
 FILE     : src/visitable.cpp
 LINE     : 496
```

# Steps To Reproduce

1. Take off all clothing
2. Load ~100 or so thread into a Tailor's Kit
3. (w)ield the Tailor's Kit
4. Attempt to (U)nload the Tailor's Kit

# Expected behavior

Thread is safely removed without any duplication.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E-10395-g4525b4f
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: none.

# Additional context

Brand new debug world in the correct conditions to trigger the duplication.

[Test.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/6462656/Test.zip)

This MIGHT have been fixed by #47885 but I'm having some issues updating versions at the moment and this is occurring outside of AIM, and has a debug message not mentioned in the other issues of that type.

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

Bugfixes "Unload partial ammo of wielded item without duplication"

#### Purpose of change

Fixes #47001
Fixes #48842

Unloading of a wielded tool or magazine with half of its ammo or less in the magazine results in a debug message and ammo duplication.

#### Describe the solution

The code was failing to detect when the ammo was in the item, and so it would attempt to wield the ammo if no inventory room was available. Changed the code to detect the ammo while loaded in the tool and drop it correctly when unloaded.

#### Describe alternatives you've considered

Initially I was going to just completely disallow wielding of the unloaded ammo if anything was wielded, but decided on this approach. This way should cause fewer unintended side effects.

#### Testing

Full test program: no problems found. 

Tested with: sewing kit, double barrel shotgun, and 30 round Stanag magazine.

Loaded each item with half or below half of its ammo capacity. Wielded the item while having no inventory space. 'U'nload dropped the ammo to the ground without the debug message or item duplication.

#### Additional context

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -12811,7 +12811,16 @@ bool Character::add_or_drop_with_msg( item &it, const bool /*unloading*/, const
     } else if( !this->can_pickWeight( it, !get_option<bool>( "DANGEROUS_PICKUPS" ) ) ) {
         put_into_vehicle_or_drop( *this, item_drop_reason::too_heavy, { it } );
     } else {
-        const bool allow_wield = !weapon.has_item( it ) && weapon.magazine_current() != &it;
+        bool wielded_has_it = false;
+        // Cannot use weapon.has_item(it) because it skips any pockets that
```
Comment (lancewf) [inline src/character.cpp:12815]: Could the `has_item` method be fixed to include pockets that are not containers.

Comment (lancewf) [reply src/character.cpp:12815]: Never mind I see the code now it explicitly skips none containers. 
https://github.com/CleverRaven/Cataclysm-DDA/blob/243f3ead43d156a2470a00ccadbcb6b03c509a05/src/visitable.cpp#L356

**Review by lancewf — APPROVED** [review]
Run a few manual tests with a few guns, a magazine, and the sewing kit. 
This also fixes #29839
