### PR TITLE
Fixed amount of plutonium unloaded from vehicles

### LINKED ISSUE #25697: Infinite Plutonium Exploit
**Describe the bug**  
Loading and unloading a microreactor creates infinite plutonium due to a fault in the conversion of plutonium cells to plutonium power units.  Rather than getting a few plutonium cells when you unload it, you get thousands because it doesn't convert back.

**To Reproduce**  
1. Load a microreactor on a vehicle with plutonium cells.
2. Unload the microreator.
3. ???
4. Profit, thousands of plutonium cells.

**Expected behavior**  
It should re-convert back to the smaller number of plutonium cells, rather than plutonium power units

**Screenshots**  

**Versions and configuration(please complete the following information):**
0.C-32217-g7818226

### PR DESCRIPTION
**Pull request by KnightosMaster**
#### Summary
 ```SUMMARY: Bugfixes "Unloading plutonium from vehicles now gives the correct amount."```  

#### Purpose of change
Fixes #25697

#### Describe the solution
Added a simple check to see if the fuel being unloaded is plutonium, if yes, divide the amount by PLUTONIUM_CHARGES.

#### Describe alternatives you've considered
None

### CODE REVIEW

**Comment by KnightosMaster** [comment]
It is checking for the item  id (itype_id), if I understand correctly.

File: src/veh_interact.cpp [hunk 1]
```diff
@@ -2482,6 +2482,7 @@ void act_vehicle_unload_fuel( vehicle* veh ) {
         uimenu smenu;
         smenu.text = _("Remove what?");
         for( auto & fuel : fuels ) {
+            if( fuel == "plut_cell" && veh->fuel_left( fuel )<500 ) continue;
```
Comment (Qrox) [inline src/veh_interact.cpp]: Please use `PLUTONIUM_CHARGES` instead of a magical number. Also please add spaces around binary operators.

File: src/veh_interact.cpp [hunk 2]
```diff
@@ -2496,9 +2497,16 @@ void act_vehicle_unload_fuel( vehicle* veh ) {
     }
 
     int qty = veh->fuel_left( fuel );
-    item solid_fuel( fuel, calendar::turn, qty );
-    g->u.i_add( solid_fuel );
-    veh->drain( fuel, qty );
+    if( fuel == "plut_cell" ) {
+        item plutonium( fuel, calendar::turn, qty/PLUTONIUM_CHARGES);
+        g->u.i_add( plutonium );
+        veh->drain( fuel, qty - ( qty%500 ) );
```
Comment (Qrox) [inline src/veh_interact.cpp]: Magical number.

File: src/veh_interact.cpp [hunk 3]
```diff
@@ -2496,9 +2497,16 @@ void act_vehicle_unload_fuel( vehicle* veh ) {
...
+    } else {
+        item solid_fuel( fuel, calendar::turn, qty);
```
Comment (Qrox) [inline src/veh_interact.cpp]: Space before the closing parenthesis.

File: src/veh_interact.cpp [hunk 4]
```diff
@@ -2496,9 +2497,16 @@ void act_vehicle_unload_fuel( vehicle* veh ) {
     }
 
     int qty = veh->fuel_left( fuel );
-    item solid_fuel( fuel, calendar::turn, qty );
-    g->u.i_add( solid_fuel );
-    veh->drain( fuel, qty );
+    if( fuel == "plut_cell" ) {
+        item plutonium( fuel, calendar::turn, qty/PLUTONIUM_CHARGES);
```
Comment (Qrox) [inline src/veh_interact.cpp]: Spaces around '/' and before the closing parenthesis.

File: src/veh_interact.cpp [hunk 5]
```diff
@@ -2482,6 +2482,7 @@ void act_vehicle_unload_fuel( vehicle* veh ) {
         uimenu smenu;
         smenu.text = _("Remove what?");
         for( auto & fuel : fuels ) {
+            if( fuel == "plut_cell" && veh->fuel_left( fuel ) < PLUTONIUM_CHARGES ) continue;
```
Comment (Qrox) [inline src/veh_interact.cpp]: Forgot this:
```suggestion
            if( fuel == "plut_cell" && veh->fuel_left( fuel ) < PLUTONIUM_CHARGES ) {
                continue;
            }
```
