### PR TITLE
Fix auto drinking unclean water

### LINKED ISSUE #48421: Auto-drink zone lacking clean water leads to constant "Drink this? Looks unclean. Y/n?" which makes it hard to interrupt the crafting process
# Describe the bug

Setting up auto-drink zone and only having non-clean water in it leads to stream of "This looks unclean. Drink it? Y/N". It is very difficult to interrupt crafting process during this stream of questions, because as soon as N is answered, crafting is continued and question is immediatelly asked again.

# Steps To Reproduce

1. Set up auto drink zone.
2. Only have non-clean water in it.
3. Start a long crafting process.
4. Get thirsty.

# Expected behavior
Instead of Y/N in this question, there should be an option to "No, and interrupt crafting" or "No, and don't ask again".
This makes it easier to interrupt crafting and take care of the lack of clean drinkables problem.

# Screenshots
Not applicable.

# Versions and configuration

- OS:  Linux
    - OS Version: LSB Version: 1.4; Distributor ID: Arch; Description: Arch Linux; Release: rolling; Codename: n/a; 
- Game Version: 0.E-10239-gdc8bba6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    <color_light_red>Secronom</color> [secronom],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Magiclysm Revamp and Additions [magicrevamp],
    Make bows great again [bow_opness],
    Arcana and Magic Items [Arcana],
    Add Rice [rice],
    Armor Up! Survivor Expansion [ArmUpSurvEx],
    BioCo Content [bioco],
    CBM Equipment [CBM_Arms],
    Craft Ammo Mags & Belt Links [SD_Magcrafting],
    Culinary Days Ahead [culinary_days_ahead],
    Dried Fruits [dried_fruits],
    Expanded Archery [ExArch],
    Garden Pots [growable-pots],
    Large capacity storage CBMs [eps_cbm],
    Makeshift Items Mod [makeshift],
    Medieval Mod Reborn [Medieval_Mod_Reborn],
    Miscellaneous Magiclysm Expansions [demon_spider_a],
    MOD to grow tea leaves [More tea leaf],
    MST Extra [MST_Extra],
    Homestead Instruments Inc. [homestead],
    Project APEX [apex],
    Thermal Electric UPS [thermal_ups],
    Wild Living [WildLiving],
    DinoMod [DinoMod],
    Mutant Animals [mutant_animals],
    Mutant Insects [mutant_insects],
    Cataclysm++ [Cata++],
    Mining Mod [Mining_Mod],
    Vampiric Stuff [vamp_stuff],
    Vampiric Stuff + Arcana Mod Extension [vamp_stuff+arcana],
    Dorf Life [Dorf_Life],
    Blazemod - Vehicle Additions Pack [blazemod],
    Tankmod: Revived [Tankmod_Revived],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Arcana Addon [Graphical_Overmap_SDG_Arcana],
    Graphical Overmap Cataclysm++ [Graphical_Overmap_SDG_Cata++],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Graphical Overmap Secronom [Graphical_Overmap_SDG_secronom],
    Graphical Overmap Vanilla Additions [Graphical_Overmap_SDG],
    Autodoc Harmless and Perfect [autodoc_harmless_perfect],
    No Bionic Slots [no_cbm_slots],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    <color_light_blue>Lighter Weariness</color> [light_weariness],
    Merchant Mod [Merchant],
    Stats Through Skills [StatsThroughSkills]

 -->

# Additional context
N/A

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fix #48421
Prevents auto drinking from considering unclean water.

### CODE REVIEW

File: src/activity_item_handling.cpp [hunk 1]
```diff
@@ -2928,6 +2928,12 @@ int get_auto_consume_moves( player &p, const bool food )
                 // its frozen
```
Comment (actual-nh) [inline src/activity_item_handling.cpp:2928]:
```suggestion
                // it's frozen
```
(Yes, I'm compulsive.)
