### PR TITLE
Check for items in vehicle for warmth when sleeping

### LINKED ISSUE #39495: Blanket is not used to keep warm while sleeping
# Describe the bug

In a cold car seat.

# Steps To Reproduce
Load the game and sleep. Wake up from aching hands. Wearing the blanket could have prevented that.

# Expected behavior
The character using the blanket on the seat to sleep at a comfortable temperature.

# Screenshots

# Versions and configuration
- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-588-g217f4235ab-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2020.02.22.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4466335/2020.02.22.zip)

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

SUMMARY: Bugfixes "Check for items in vehicle for warmth when sleeping"

#### Purpose of change
Fixes #39495

Sleeping in a vehicle would only use items on the map for warmth.

#### Describe the solution

Items found in the vehicle at the same position as the player arechecked for warmth. Items on the map are not included if a vehicle cargo space is found..

#### Describe alternatives you've considered

Including everything on the ground as well as in the vehicle.

#### Testing

Full test program: complete success.

Tested with a breakpoint in `Character::floor_item_warmth` to watch the returned warmth value. Slept on the ground, a vehicle seat, and a vehicle cargo space. Warmth values consistently match the blankets used and if a vehicle cargo space is present all items on the ground are ignored.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -10943,24 +10943,36 @@ int Character::floor_bedding_warmth( const tripoint &pos )
...
-    }
-
     int item_warmth = 0;
-    // Search the floor for items
-    const map_stack floor_item = here.i_at( pos );
-    for( const item &elem : floor_item ) {
-        if( !elem.is_armor() ) {
-            continue;
+
+    auto warm = [&item_warmth]( auto stack ) {
```
Comment (Aivean) [inline src/character.cpp:10948]:
```suggestion
    auto warm = [&item_warmth]( const auto &stack ) {
```

**Comment by Aivean** [comment]
> Considered overriding items on the map with just the vehicle items. It would not allow using large items that don't fit in a seat cargo space though.

I'd say this sounds better than current variant.

First, vehicle seats should have some downsides compared to beds. 

Second, it seems weird to use items lying under the vehicle. I know that currently it's possible to pick up or drop such items while being inside the vehicle, but that always seemed like a bug/exploit to me.

**Comment by Cimanyd0** [comment]
>First, vehicle seats should have some downsides compared to beds.

Why would the lack of a QOL feature make sense as a downside to sleeping in a vehicle seat? You could still `W`ear the blanket first, so it wouldn't prevent you from doing anything, it would just make it inconvenient.

There would be the downside that if you forget to move the blanket before driving off, it would be under the car.

>Second, it seems weird to use items lying under the vehicle. I know that currently it's possible to pick up or drop such items while being inside the vehicle, but that always seemed like a bug/exploit to me.

It's just as weird that you can't put a blanket _on_ the seat. Or even on a vehicle bed. Or in an aisle.

**Comment by Aivean** [comment]
> Why would the lack of a QOL feature make sense as a downside to sleeping in a vehicle seat? You could still `W`ear the blanket first, so it wouldn't prevent you from doing anything, it would just make it inconvenient.

That's a questionable "QoL" feature. If there is a way to solve a problem by taking extra steps, it doesn't automatically mean that these steps should be made for you. Ad absurdum, game could reload your guns for you, kite zombies for you, and eventually turn into zero-play "press X to win" RPG.

Currently there is little reason to have a dedicated bed in your vehicle. With this change, having a dedicated sleeping space, which is not driving seat, becomes somewhat more appealing.

> There would be the downside that if you forget to move the blanket before driving off, it would be under the car.

Let's not rely on bugs for game balance.

> It's just as weird that you can't put a blanket on the seat. Or even on a vehicle bed. Or in an aisle.

I partially agree. 

Vehicle bed should be given more storage capacity, if it currently can't fit the blanket.  Having items lying in aisles could be supported in the future, but it has to be implemented carefully.

But with vehicle seats it's not that simple. Their current storage capacity reflects the amount of stuff that could be stashed under/around them so that player's ability to use them for driving is not hindered. Maybe we can think about increasing their storage capacity but adding an explicit mechanic that prevents you from driving if too much stuff is stored on the seat.

**Comment by actual-nh** [comment]
> But with vehicle seats it's not that simple. Their current storage capacity reflects the amount of stuff that could be stashed under/around them so that player's ability to use them for driving is not hindered. Maybe we can think about increasing their storage capacity but adding an explicit mechanic that prevents you from driving if too much stuff is stored on the seat.

How about allowing use of material on the same tile **_if_** you aren't driving (as in, you're sleeping)? Use a blanket for sleeping, fine. Use wrapped around you while you (try to) drive, too bulky.

**Comment by Cimanyd0** [comment]
The feature that uses items for warmth while sleeping, without having to wear them, has already been in the game for [over 7 years](https://github.com/CleverRaven/Cataclysm-DDA/pull/2492). It's not a new thing.

How is that kind of thing questionable? How would making you manually take every single action make the game any better?

Limiting that QoL feature based on the amount of storage inside/under a vehicle part, for the sake of "game balance", would be like relying on a bug for game balance. If there is not as much difference between vehicle seats and vehicle beds as there is in real life, that's a separate issue.
 
>Vehicle bed should be given more storage capacity, if it currently can't fit the blanket.

A vehicle bed can store 50L, but that must be under the bed or something, because you can still sleep no matter what you put in that storage. This means that if you put a blanket in the bed, you're using that storage space instead of putting it _on_ the bed. The same is true of seats. My point is that the current system is weird whether this PR includes items that "fall to the ground" or not, but including them seems more realistic because you can sleep with a blanket whether it fits under your seat or not.

**Comment by Aivean** [comment]
> The feature that uses items for warmth while sleeping, without having to wear them, has already been in the game for over 7 years. It's not a new thing.

>  My point is that the current system is weird whether this PR includes items that "fall to the ground" or not, but including them seems more realistic because you can sleep with a blanket whether it fits under your seat or not.

I disagree. If a bug was in the game for over 7 years it doesn't mean that it shouldn't be fixed.

Game balance aside, consider the following scenario: you are driving in the town, ramming zombies. Then you stop in the middle of a street to get some sleep. Coincidentally, your seat happen to be over some zombie corpse. With this PR as is, your character will use filthy zombie gear **from underneath the vehicle** for warmth.

**Comment by actual-nh** [comment]
> Game balance aside, consider the following scenario: you are driving in the town, ramming zombies. Then you stop in the middle of a street to get some sleep. Coincidentally, your seat happen to be over some zombie corpse. With this PR as is, your character will use filthy zombie gear **from underneath the vehicle** for warmth.

In other words, the heart of the problem is things falling "to the ground" (that should be in the vehicle), which become indistinguishable from things already on the ground (that should be on the ground).

**Comment by Aivean** [comment]
> In other words, the heart of the problem is things falling "to the ground" (that should be in the vehicle), which become indistinguishable from things already on the ground (that should be on the ground, and not treated as inside the vehicle).

Correct. 

Fixing that is not simple, it requires adding whole new system for managing items "on the vehicle floor", potentially including some drawbacks, as having such items shifting and bouncing around when driving.  This is well out of the scope of this PR and 0.F release.

For this PR I believe the suggested alternative is better, as it's more consistent with both real world and game balance, and also doesn't rely on the current buggy mechanic.

File: src/character.cpp (hunk 1 above)
Comment (RoyBerube) [reply src/character.cpp:10948]: Will do.

**Comment by RoyBerube** [comment]
I'll change it so that items on the ground and in the vehicle are not combined for warmth. The vehicle cargo space such as a seat will override anything found on the ground. 

I agree it is odd behavior that items spill onto the ground when cargo is full; it is best to assume that interaction will get fixed sometime in the future.

**Comment by actual-nh** [comment]
> But with vehicle seats it's not that simple. Their current storage capacity reflects the amount of stuff that could be stashed under/around them so that player's ability to use them for driving is not hindered. Maybe we can think about increasing their storage capacity but adding an explicit mechanic that prevents you from driving if too much stuff is stored on the seat.

Actually, for the driver's seat, I suspect it would work better to make the **_controls_** have storage space - but not be operable otherwise if anything is in said storage space.

**Comment by actual-nh** [comment]
You may want to change the title of the PR and the summary, then.

File: src/character.cpp [hunk 2]
```diff
@@ -10943,27 +10943,37 @@ int Character::floor_bedding_warmth( const tripoint &pos )
...
+    map &here = get_map();
+
+    if( !!here.veh_at( pos ) ) {
+        if( const cata::optional<vpart_reference> vp = here.veh_at( pos ).part_with_feature( VPFLAG_CARGO,
+                false ) ) {
+            vehicle *const veh = &vp->vehicle();
+            const int cargo = vp->part_index();
+            vehicle_stack vehicle_items = veh->get_items( cargo );
+            warm( vehicle_items );
+            return item_warmth;
```
Comment (Aivean) [inline src/character.cpp:10972]: I suggest to move `return item_warmth;` outside the inner `if`, so that if player is not on the `VPFLAG_CARGO` tile, but still in the vehicle, returned warmth is zero.

**Review by Aivean — CHANGES_REQUESTED** [review]

File: src/character.cpp (hunk 2 above)
Comment (RoyBerube) [reply src/character.cpp:10972]: I suppose it makes sense as it is more consistent with keeping items on the ground overriden by the vehicle

**Review by Aivean — APPROVED** [review]

**Comment by l29ah** [comment]
> First, vehicle seats should have some downsides compared to beds.

But all the seats already have their comfort values less than beds.
