### PR TITLE
basecamps: fix NPC companions deleting seeds before farming

### LINKED ISSUE #28241: Survivor Camp Farms can't be planted by npcs
**Describe the bug**  
When finishing up the plant seeds action in the farm expansion to the camp, the results is a duplicate pile of seeds (based on the number of seeds in the originally selected pile), and still barren fields.

**To Reproduce**  
1. Make a farming expansion (I have only tested the first one).
2. Take any seed to the camp manager and submit the seeds and an npc to plant the seeds.
3. Finish the action after the appropriate amount of time. The result is more seeds and fields that are yet to be seeded.

**Expected behavior**  
The appropriate seed count should be taken from the used seed stacks and the fields should be seeded.

**Versions and configuration(please complete the following information):**
 - OS: [e.g. Windows 10]
 - Game Version [0.C-37442-gd597d68]
 - Graphics version [Tiles]

**Additional context**  
[Nocturne (2).zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2873515/Nocturne.2.zip)

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "basecamps: fix NPC companions deleting seeds before farming"```

#### Purpose of change
Fixes #28241 
The function that was retrieving NPCs sent to plant seeds in a farm was calling a function that chose the NPC to return and cleared their mission inventory, then sending that NPC to plant the field with seesd in their mission inventory.  Obviously, this did not work.  Using the function that just chooses an NPC to return allows the NPC to plant seeds from their mission inventory, and then a second function can finish cleaning up the NPC for the mission return.

#### Describe the solution
Use the two stage `companion_choose_return`/`finish_return` to return a companion from farm activities, so that the companion still has a mission inventory when they're called upon to do the actual planting,
instead of the single stage `mission_return` that clears the inventory before passing the shared npc ptr back to the caller.

#### Describe alternatives you've considered
Not being an idiot about my own code is apparently not a valid option, unfortunately.

### CODE REVIEW

File: src/faction_camp.cpp [hunk 1]
```diff
@@ -2181,7 +2189,7 @@ bool basecamp::survey_return( npc &p )
 bool basecamp::farm_return( npc &p, const std::string &task, const tripoint &omt_tgt, farm_ops op )
 {
     const std::string msg = _( "returns from working your fields... " );
-    npc_ptr comp = mission_return( p, task, 15_minutes, true, msg, "survival", 2 );
+    npc_ptr comp =  companion_choose_return( p, task, 15_minutes );
```
Comment (Night-Pryanik) [inline src/faction_camp.cpp]: Stray space.

**Comment by kevingranade** [comment]
Also merged to 0.D.
