### PR TITLE
[Magiclysm] Fix ring stacking by adding ONE_PER_LAYER flag

### LINKED ISSUE #45774: Magiclysm - Similar Stat Rings of different values (+1/+2/+3/+4) can all be worn at the same time
# Describe the bug
You can equip multiple rings of STR/DEX/INT/PER  of the same stat as long as the enchantment is different.

# Steps To Reproduce
Put +4 ring on.
Put +3 ring on.
Put +2 ring on.
Put +1 ring on.
Bam +10 to a stat.

# Expected behavior
A message saying you can only equip one ring of this type and preventing you from equipping said "bonus" rings.
You are not allowed to stack stat rings of the same value (no 2x +4 rings) so I don't believe stacking different values is intended.

# Screenshots
image

# Versions and configuration

- OS: Windows
- OS Version: Windows 7 Professional 64-bit
- Game Version: 0.E-7920-ge62c502 [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Magiclysm [magiclysm],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP]
]

# Additional context
The hand the rings are equipped on doesn't seem to matter, can stack it all on one hand or split rings between both hands.

### PR DESCRIPTION
**Pull request by KorGgenT**
#### Summary
Bugfixes "[Magiclysm] Fix ring stacking by adding ONE_PER_LAYER flag"

#### Purpose of change
Fixes #45774

#### Describe the solution
added a new flag called ONE_PER_LAYER that has a strict requirement of only one item on that layer of bodypart. it's more general than just a magiclysm fix, so the flag itself had to go into the vanilla flags.json.

#### Testing
load up magiclysm, spawn 3 unique magic rings and try to put them on. note that the first two get put on properly, and the second one you put on has its side updated. the third one you attempt to wear says it conflicts.

### CODE REVIEW

File: src/character.cpp [hunk 1]
```diff
@@ -4421,6 +4443,21 @@ bool Character::change_side( item &it, bool interactive )
         return false;
     }
 
+    const bool item_one_per_layer = it.has_flag( flag_id( "ONE_PER_LAYER" ) );
+    for( const item &worn_item : worn ) {
+        if( item_one_per_layer && worn_item.has_flag( flag_id( "ONE_PER_LAYER" ) ) ) {
+            const cata::optional<side> sidedness_conflict = it.covers_overlaps( worn_item );
+            if( sidedness_conflict ) {
+                const std::string player_msg = _( "Your %s conflicts with %s so you cannot swap its side.",
+                                                  it.tname(), worn_item.tname() );
```
Comment (anothersimulacrum) [inline src/character.cpp:4452]:
```suggestion
                const std::string player_msg = _( "Your %s conflicts with %s so you cannot swap its side." ),
                                                  it.tname(), worn_item.tname();
```

**Comment by Salty-Panda** [comment]
Will you add more slots?
E.g. head with layer - neck.

**Comment by Qrox** [comment]
Only allowing one ring per hand it a bit gamey. How about allowing as many rings as possible on hands but cancel their stats bonus out when multiple are worn on the same hand "due to magical inference"?

**Comment by KorGgenT** [comment]
> Only allowing one ring per hand is a bit gamey. How about allowing as many rings as possible on hands but cancel their stats bonus out when multiple are worn on the same hand "due to magical inference"?

at the risk of sounding lazy, i don't want to do that because it would add a lot of complexity to the enchantment system, and i am quite happy with this solution for magiclysm.

**Comment by KorGgenT** [comment]
> Will you add more slots?
> E.g. head with layer - neck.

sounds like a great idea for something in the future.

File: src/character.cpp [hunk 2]
```diff
@@ -4421,6 +4443,22 @@ bool Character::change_side( item &it, bool interactive )
...
 
+    const bool item_one_per_layer = it.has_flag( flag_id( "ONE_PER_LAYER" ) );
+    for( const item &worn_item : worn ) {
+        if( item_one_per_layer && worn_item.has_flag( flag_id( "ONE_PER_LAYER" ) ) ) {
+            const cata::optional<side> sidedness_conflict = it.covers_overlaps( worn_item );
+            if( sidedness_conflict ) {
+                const std::string player_msg = string_format(
+                                                   _( "Your %s conflicts with %s, so you cannot swap its side." ),
+                                                   it.tname(), worn_item.tname() );
+                const std::string npc_msg = _( "<npcname>'s %s conflicts with %s so they cannot swap its side.",
```
Comment (BrettDong) [inline src/character.cpp:4454]:
```suggestion
                const std::string npc_msg = _( "<npcname>'s %s conflicts with %s so they cannot swap its side." ),
```

File: src/character.cpp [hunk 3]
```diff
@@ -4421,6 +4443,22 @@ bool Character::change_side( item &it, bool interactive )
...
+                                               it.tname(), worn_item.tname() );
```
Comment (Qrox) [inline src/character.cpp:4455]:
```suggestion
                const std::string npc_msg = string_format( _( "<npcname>'s %s conflicts with %s so they cannot swap its side." ),
                                               it.tname(), worn_item.tname() );
```

File: src/character.cpp [hunk 4]
```diff
@@ -3862,10 +3862,32 @@ ret_val<bool> Character::can_wear( const item &it, bool with_equip_change ) cons
...
+    };
     for( const item &i : worn ) {
         if( i.has_flag( flag_ONLY_ONE ) && i.typeId() == it.typeId() ) {
             return ret_val<bool>::make_failure( _( "Can't wear more than one %s!" ), it.tname() );
         }
+
+        if( this_restricts_only_one || i.has_flag( flag_id( "ONE_PER_LAYER" ) ) ) {
+            cata::optional<side> overlaps = it.covers_overlaps( i );
+            if( overlaps && sidedness_conflicts( *overlaps ) ) {
+                return ret_val<bool>::make_failure( _( "%s conflicts with %s!" ), it.tname(), i.tname() );
```
Comment (Night-Pryanik) [inline src/character.cpp:3888]: Could you please make the arguments positional?

Comment (KorGgenT) [reply src/character.cpp:3888]: positional?

Comment (BrettDong) [reply src/character.cpp:3888]: > positional?

For example instead of `%s %d`, use `%1$s` for the first parameter, `%2$d` for the second parameter, etc.

This allows translators to change the order of wording in a sentence in other languages.

Comment (actual-nh) [reply src/character.cpp:3888]: See [this comment](https://github.com/CleverRaven/Cataclysm-DDA/pull/45838#discussion_r545633792).

Comment (KorGgenT) [reply src/character.cpp:3888]: i can certainly do this, though i will say i don't think it changes anything
