### PR TITLE
Fix npc death of last member removing your_followers faction entirely

### LINKED ISSUE #34144: When NPC dies, property is considered someone else's despite being in the 'your followers' faction
When NPC dies, property is considered someone else's despite being in the 'your followers' faction.
# Steps To Reproduce
1:Recruit your shelter friend
2:Go about your day looting and doing standard things
3:have your friend die of horrific infection or any other causes
4:Can't craft properly anymore due to ownership issues and have to pick up and drop 'steal' it all back into your ownership.

# Expected behavior
My property remains my property even if one of my allies die.

# Versions and configuration

7756, 21/09/2019.
last commit, this one with faction fixes: 
https://github.com/CleverRaven/Cataclysm-DDA/commit/8b59cb22b5e70bb7fc3d039328de8e64ae7f1c2d
Windows x64 tiles
mods loaded:
-   "dda",
-   "Tolerate_This",
-   "growable-pots",
-   "makeshift",
-   "More_Survival_Tools",
-   "Medieval_Stuff",
-   "modular_turrets",
-   "Salvaged_Robots",
-   "national_guard_camp",
-   "more_locations",
-   "FujiStruct",
-   "mapgen_demo",
-   "DP_REMIX_INDICATORS",
-   "sees_player_retro",
-   "cbm_slots",
-   "sleepdeprivation",
-   "No_Rail_Stations",
-   "no_npc_food"

# Additional context
save here:
https://mega.nz/#!zd13jaYI!8pJIaiklX__rh2L1tXgMYDiaMlXsVkmN6E4o7YO6jKQ

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "Fix npc death of last member removing your_followers faction entirely'"```

#### Purpose of change
Fixes #34144 

#### Describe the solution
When NPC dies, their membership is removed from the count of members of that faction.
If however they were the last follower of your_followers faction, it removed your_followers faction entirely, because the player dosnt count as a member.

Next call to faction_manager::get() then found the template for your_followers and recreated it, but it wasnt the same faction as the items owners, so it counted as stealing.

This disallows the removal of the your_followers faction.

There is more to fix here, and there is still some weirdness in the list of factions in the debug printed out info, but ill get to those fixes, this fixes the most egregious error first.

#### Describe alternatives you've considered
N/A

#### Additional context
N/A

### CODE REVIEW

File: src/pickup.cpp [hunk 1]
```diff
@@ -848,12 +848,10 @@ void Pickup::pick_up( const tripoint &p, int min, from_where get_items_from )
...
                     std::string stolen;
                     bool stealing = false;
-                    if( this_item.has_owner() ) {
-                        const faction *item_fac = this_item.get_owner();
-                        if( item_fac != g->u.get_faction() ) {
-                            stolen = "<color_light_red>!</color>";
-                            stealing = true;
-                        }
+                    if( this_item.has_owner() &&
+                        this_item.get_owner() != g->faction_manager_ptr->get( faction_id( "your_followers" ) ) ) {
```
Comment (BevapDin) [inline src/pickup.cpp]: What's wrong with using `g->u.get_faction()` here?

File: src/npc.cpp [hunk 2]
```diff
@@ -439,9 +439,17 @@ void npc::randomize_from_faction( faction *fac )
...
+        my_fac->remove_member( getID() );
+    }
     my_fac = g->faction_manager_ptr->get( id );
-    fac_id = my_fac->id;
-    my_fac->add_to_membership( getID(), disp_name(), known_to_u );
+    if( my_fac ) {
+        my_fac->add_to_membership( getID(), disp_name(), known_to_u );
+        fac_id = my_fac->id;
+    } else {
+        my_fac = nullptr;
```
Comment (BevapDin) [inline src/npc.cpp]: Redundant assignment. If `my_fac` evaluates to `false` in the if-condition above, it means it is null. Setting it here has no effect.

File: src/pickup.cpp (hunk 1 above)
Comment (davidpwbrown) [reply src/pickup.cpp]: Ah nothing, I thought get_faction() might be what was causing the problem and forgot to put the code back to how it was.
