### PR TITLE
Anger npc if player asks for equipment

### LINKED ISSUE #61861: Exploit: Can gain endless social skill by asking an NPC for items over and over again.
### Describe the bug

There is no limit to the amount of times you can ask an npc for items through the "Want to share some useful items with me?" dialogue. You gain social skill for going through these dialogue checks even at a guaranteed 0% chance of success, so you can grind your social skill theoretically indefinitely, all in a single in-game second. (it becomes very slow to do after social level 2, though).

Another effect is that you can make the NPC's "Value" opinion of you will spiral into extremely negative values because it decreases each time you do this.

### Steps to reproduce

1. Make character with 0 social skill in a scenario with starting NPC
2. Ask the starting NPC for useful items
3. Repeat step 2 over and over again. See that social skill rises up with no limit.

### Expected behavior

I kind of expected that they'd actually follow through with their threats to kill me if I asked them again. A perfectly reasonable response for when The Flash won't take no for an answer and keeps asking for handouts hundreds of times per second.

Maybe the player should get locked out of asking for items if they fail too many times, similar to asking them to become your follower.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2130 (21H2)
- Game Version: 3c1b99e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Leonkoithara**
#### Summary
Bugfixes "NPCs get angry when player asks for equipment"

#### Purpose of change
Fixes #61861 

#### Describe the solution
Increase the NPCs anger towards the player so that they cannot keep indefinitely asking for items to increase social skill without them turning hostile.

#### Testing
Spawn in an npc and keep asking them to share items until they turn hostile.

### CODE REVIEW

File: src/npctalk_funcs.cpp [hunk 1]
```diff
@@ -587,6 +587,8 @@ void talk_function::give_equipment_allowance( npc &p, int allowance )
 {
     std::vector<item_pricing> giving = npc_trading::init_selling( p );
     int chosen = -1;
+    // Add asked_for_item effect whether or not NPC has items to give
+    p.add_effect( effect_asked_for_item, 3_hours );
```
Comment (Maleclypse) [inline src/npctalk_funcs.cpp:591]:
```suggestion
    p.add_effect( effect_asked_for_item, 3_hours );
```
3 days or even a week seems more reasonable than able to ask every three hours?

Comment (MNG-cataclysm) [inline src/npctalk_funcs.cpp:591]: Couldn't this be done with regular JSON instead of C++? It would be easier that way and more accessible to the general programming base.

**Review by MNG-cataclysm — CHANGES_REQUESTED** [review]

File: src/npctalk_funcs.cpp (hunk 1 above)
Comment (Leonkoithara) [reply src/npctalk_funcs.cpp:591]: It can be done via JSON however I'm not sure what else depends on this effect to be added when this function is called. Therefore I could just let the npctalk_funcs.cpp remain the same and modify the JSON to add the effect or just slightly modify this file and wait for someone else to move all effects to the JSON instead of hardecoding it.

Comment (Leonkoithara) [reply src/npctalk_funcs.cpp:591]: Yes will change it to 3 days once the other conversation is resolved.

Comment (MNG-cataclysm) [reply src/npctalk_funcs.cpp:591]: All you'd need to do is remove the C++ function, make the effect have a time on it, and use an if conditional statement for the associated dialogue so it wouldn't appear if the NPC had this effect.

Comment (Leonkoithara) [reply src/npctalk_funcs.cpp]: Hi reverted the change in code and made the effect via JSON it so that when we receive item from NPC the effect is added. I did not remove the function entirely because various other functions depend on calling this function and the effect to be added and moving all of them to JSON is out of scope of this PR and I'm not entirely certain what all functions do call it, but perhaps something to look into at a later date.

Comment (Leonkoithara) [reply src/npctalk_funcs.cpp]: @Maleclypse the conversation has been resolved if all else looks good please merge.
