### PR TITLE
Fixes the wrong message order.

### LINKED ISSUE #9388: Combat messages out of order (fencing)
fencing
Cougar steps adjacent to me, I hit it for 44 damage, and then it attacks me, only to be met with an automatic and fatal stop thrust.

I can't figure out what the optimal chronological order of these messages would be, but I do know that the cougar should not be breaking my stuff after it is already dead. Also, there's not much point to blocking with a rapier when there hasn't even been an attack declared yet.

Solutions? Discuss?

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/5065396-combat-messages-out-of-order-fencing?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BevapDin**
Fixes #9388

Low level functions like `Creature::apply_damage` (the lowest function that affects HP of a creature) and `Creature::deal_damage` and other similar functions call `Creature::die`. The `die` function has many side effects like printing messages ("The %s dies!"), but it also calls the mondeath functions etc.

Some of those functions return the actually applied damage (`deal_damage` reduces the damage by armor values, so dealing 10 units of damage might only result in applying 4 units of damage, or none at all). This is used in melee.cpp to print messages afterwards like "You hit the %s for %d damage." With the call to `die` inside of `deal_damage` (indirectly because it calls `apply_damage`), that message would be printed after the "The %s dies!" message (and after any further effects).

For easier usage, the commonly applied code `if(critter.is_dead_state()) { critter.die(); }` is packed into a function `check_dead_state()`. The killer is also set through the `apply_damage` function if the applied damage kills the creature.

Additional things:
- Wrap access to `monster::hp` into functions, use the functions defined in the Creature class where possible, this allows to make `monster::hp` private.
- Fix another potential bug: despawning of out of bounds monsters is done in a separate loop to not mess up the indexes in the monster_faction set.
- Change `player::hp_convert` to `hp_to_bp`, returning the converted value instead of storing it in a by-reference parameter. Same wit `player::bp_to_hp`.
- Add a source parameter to `player::hurtall` and `player::hitall`, so the killing creature can be recorded properly. Make both function call `apply_damage` instead of accessing the hp directly.

Much of the changes are
- the added calls to `check_dead_state()`, which was previously done by the `deal_damage` etc. calls.
- added source creature parameter to `hurtall` / `hitall`.

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -4943,38 +4943,22 @@ void player::healall(int dam)
...
         int cut = 0;
-        absorb((body_part) i, ddam, cut);
-        hp_cur[i] -= ddam;
-        if (hp_cur[i] < 0) {
-            lifetime_stats()->damage_taken += hp_cur[i];
-            hp_cur[i] = 0;
-        }
-
-        // Average of pre and post armor damage levels, divided by 8.
-        mod_pain( (dam + ddam) / 16 );
```
Comment (KA101) [inline src/player.cpp]: Just checking, is mo_pain handled elsewhere?

Comment (BevapDin) [inline src/player.cpp]: Yes, the whole removed code is handled in `apply_damage` (and more), I figured, why the repetition. And there are slight (and pointless) differences: `hitall` wakes you up, but `hurtall` does not.
