### PR TITLE
Fixed wrong vitamin set in debug menu

### LINKED ISSUE #29285: Debug menu selection doesn't work properly for vitamins.
**Describe the bug**  

When attempting to zero my vitamin values, I noticed that selecting a vitamin caused a change in the vitamin below it. It also makes selection of calcium not possible.

**To Reproduce**  
1. Open the debug menu.
2. Select edit player/NPC
3. Select yourself
4. Choose needs
5. Select a vitamin.

**Expected behavior**  
I expected to change the value for the vitamin I chose.

**Screenshots**  
DebugVitaminNeeds

**Versions and configuration(please complete the following information):**
 - OS: Windows 10
 - Game Version: 0.D-1411-g6c79f15
 - Graphics version: Tiles
 - Mods loaded: Disable NPC Needs, Filthy Clothing, Alternative Map Key, Mapgen Demo, More City Locations, More Locations, Fuji's More Buildings, StatsThroughSkills.

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
```SUMMARY: Bugfixes "Fixed wrong vitamin set in debug menu."```

#### Purpose of change
Closes #29285.

#### Describe the solution
I guess it was just an off-by-one error.

### CODE REVIEW

File: src/debug_menu.cpp [hunk 1]
```diff
@@ -345,10 +345,10 @@ void character_edit_menu()
                     break;
 
                 default:
-                    if( smenu.ret > 3 && smenu.ret < static_cast<int>( vits.size() + 4 ) ) {
-                        auto iter = std::next( vits.begin(), smenu.ret - 4 );
+                    if( smenu.ret > 3 && smenu.ret < static_cast<int>( vits.size() + 5 ) ) {
```
Comment (AMurkin) [inline src/debug_menu.cpp]: But it's better to use a variable instead of all 5s.
```suggestion
                    if( smenu.ret >= 5 && smenu.ret < static_cast<int>( vits.size() + 5 ) ) {
```
