### PR TITLE
Info panel fixes and adding scrollbars

### LINKED ISSUE #50851: Proficiencies slidebar doesn't show up when 1 item is off the screen.
### Describe the bug

See pic, I have big list of Proficiencies. Just big enough to leave last item out the screen. If it were 2 longer, sidebar would appear (though not optimal).

I guess it is just an off by 1 error?

### Steps To Reproduce

Easily, right?

### Expected behavior

Everything fits onto the screen. Just when it doesn't, a sidebar appears.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 31ef3ba [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

I will try to fix this, let me have a day for it :)

### PR DESCRIPTION
**Pull request by Brambor**
#### Summary
None

#### Purpose of change
Fixes #50851,
While fixing this issue I found (and fixed) other issues:

- [x] EFFECTS tab has priority over PROFICIENCIES tab.
- [x] PROFICIENCIES tab has disgusting scrolling & is scrolling with others (while it's not selected).
- [x] Tabs TRAITS, BIONICS, EFFECTS are missing scrollbar.
- [x] Left side of the BIONICS tab doesn't have a border.
- [x] Always start with space (`| Abc` instead of `|Abc`) - EFFECTS & PROFICIENCIES

#### Describe the solution
 - Made similar code into functions. <strike>I might have overdone it in the case of `static void draw_scrollbar`</strike>.
 - Merged features that were in some tabs, but not all. This fixed off by one error causing #50851.
 - Fix border off by 1 error.
 - Some refactoring.

#### Describe alternatives you've considered
Since the scrollbar was only on one tab, remove it. But the scrollbar is useful, so I fixed it there and added it elsewhere.

#### Testing

Made save with lots of effects, bionic traits, mutations & proficiencies. Scrolling works, scrollbars too, everything is accounted for (nothing is under the screen as was in #50851). Resizing works.

#### Additional context

- There are more opportunities for merging two or more similar blocks of code into a function.
- c++17 would be nice.

Before:
looks_master

After:
loks_current

### CODE REVIEW

**Comment by Brambor** [comment]
My first c++ change in CDDA + first proper pull request.
So feedback is welecome. Did I overdo or underdo something?

File: src/player_display.cpp [hunk 1]
```diff
@@ -96,6 +96,55 @@ static std::vector<std::pair<bodypart_id, bool>> list_and_combine_bps( const Cha
...
+        scrollbar()
+        .offset_x( width )
+        .offset_y( height_offset )
+        .content_size( list_lenght )
+        .viewport_pos( range_first )
+        .viewport_size( height )
+        .scroll_to_last( false )
+        .apply( win );
+    }
+}
```
Comment (Qrox) [inline src/player_display.cpp:146]: The intention of using the `scrollbar` class is that it's clear from sight what the arguments are for. If you really want less code duplication, there's `draw_scrollbar` from `output.h`, but that function is sort of deprecated.

File: src/player_display.cpp [hunk 2]
```diff
@@ -300,18 +340,15 @@ static void draw_proficiencies_tab( const catacurses::window &win, const unsigne
...
-    const int width = getmaxx( win ) - 1;
-    bool draw_scrollbar = profs.size() > static_cast<size_t>( height );
-    int y = 1;
-    int start = draw_scrollbar ? line : 0;
-    for( size_t i = start; i < profs.size(); ++i ) {
-        if( y > height ) {
-            break;
-        }
+
+    const size_t height = getmaxy( win ) - 1;
```
Comment (Qrox) [inline src/player_display.cpp:347]: Using `size_t` invites all sorts of nasty surprises. I recommend always using `int` unless it cannot be done without `size_t`.

**Comment by Qrox** [comment]
To fix the border bug, change the x position and width of the border at `src/player_display.cpp:1407`.

```diff
 ui_bionics.on_screen_resize( [&]( ui_adaptor & ui_bionics ) {
     bionics_win_size_y = calculate_trait_and_bionic_height().second;
     bionics_win_size_y = trait_and_bionic_height.second;
     w_bionics = catacurses::newwin( bionics_win_size_y, grid_width,
                                     point( grid_width + 1,
                                            infooffsetybottom + trait_win_size_y + 1 ) );
-    w_bionics_border = catacurses::newwin( bionics_win_size_y + 1, grid_width + 1,
-                                           point( grid_width + 1,
+    w_bionics_border = catacurses::newwin( bionics_win_size_y + 1, grid_width + 2,
+                                           point( grid_width,
                                                    infooffsetybottom + trait_win_size_y + 1 ) );
    border_bionics.set( point( grid_width, infooffsetybottom + trait_win_size_y ),
                        point( grid_width + 2, bionics_win_size_y + 2 ) );
    ui_bionics.position_from_window( w_bionics_border );
 } );
```

And I think a similar change should also be made for the traits tab, in case the traits tab is longer than the skills tab.

File: src/player_display.cpp [hunk 3]
```diff
@@ -1372,14 +1380,21 @@ void player::disp_info()
         draw_stats_tab( w_stats, *this, line, curtab );
     } );
 
+    // TRAITS & BIONICS
+    const std::pair<unsigned int, unsigned int> trait_and_bionic_height =
+        calculate_shared_column_win_height(
+            static_cast<unsigned>( TERMY ) - infooffsetybottom,
+            trait_win_size_y_max,
+            bionics_win_size_y_max
+        );
```
Comment (Qrox) [inline src/player_display.cpp:1372]: This should be inside the `on_screen_resize` callback. `TERMY` is dependent on the game window size so this value needs to be calculated every time the screen is resized.

File: src/player_display.cpp [hunk 4]
```diff
@@ -1453,12 +1455,21 @@ void player::disp_info()
         draw_encumbrance_tab( w_encumb, *this, line, curtab );
     } );
 
+    // EFFECTS & PROFICIENCIES
+    const std::pair<unsigned int, unsigned int> effect_and_proficiency_height =
+        calculate_shared_column_win_height(
+            static_cast<unsigned>( TERMY ) - infooffsetybottom,
+            effect_win_size_y_max,
+            proficiency_win_size_y_max
+        );
```
Comment (Qrox) [inline src/player_display.cpp:1445]: Same here.

File: src/player_display.cpp [hunk 5]
```diff
@@ -96,6 +96,31 @@ static std::vector<std::pair<bodypart_id, bool>> list_and_combine_bps( const Cha
     return bps;
 }
 
+static std::pair<size_t, size_t> subindex_around_cursor(
+    const size_t list_lenght,
```
Comment (Qrox) [inline src/player_display.cpp:100]: list_lenght -> list_length. And I believe `calcStartPos` from `output.h` does exactly this?

File: src/player_display.cpp [hunk 6]
```diff
@@ -349,15 +347,15 @@ static void draw_proficiencies_tab( const catacurses::window &win, const unsigne
             name = trim_by_length( cur.id->name(), width );
         }
         const nc_color col = focused && i == line ? hilite( cur.color ) : cur.color;
-        y += fold_and_print( win, point( 0, y ), width, col, name );
+        fold_and_print( win, point( 0, 1 + i - range.first ), width, col, name );
```
Comment (Qrox) [inline src/player_display.cpp:364]: `y += ` is used here because `fold_and_print` can print multiple lines when the text is long. If this does happen I recommend caching the folded strings and print the strings and the scroll bar according to the number of lines folded. Alternatively you can use `trim_and_print` here like the other tabs.

File: src/player_display.cpp (hunk 3 above)
Comment (Brambor) [reply src/player_display.cpp:1372]: Question: `on_screen_resize` is in lambda catching context. So it is all in one context. Rather than calculating it twice for TRAITS & BIONICS, where can I best put code that works for both but has to be run only once? It would work putted in either `ui_traits.on_screen_resize` or `ui_bionics.on_screen_resize`, but that's disgusting. Is there some universal `ui_adaptor` type on whom I would call `.on_screen_resize(...)` ?

Comment (Qrox) [reply src/player_display.cpp:1372]: I think you can cache the result based on the argument values. Or just calculate it twice. It's not like these are super expensive operations.

Comment (Brambor) [reply src/player_display.cpp:1372]: I will calculate it twice. My motivation was less code duplication, not speed :)

File: src/player_display.cpp (hunk 6 above)
Comment (Brambor) [reply src/player_display.cpp:364]: Actually, it was already trimmed in the previous if-else statement, so it always returns 1. Maybe using it is therefore overkill?

Comment (Qrox) [reply src/player_display.cpp:364]: `print_colored_text` should be enough then.

File: src/player_display.cpp (hunk 5 above)
Comment (Brambor) [reply src/player_display.cpp:100]: It's a bit different, it does calculate `slice_start`, but not `slice_end`.
But maybe it could be used to reduce code duplicity a bit...

Comment (Brambor) [reply src/player_display.cpp:100]: I don't yet get `get_option<bool>( "MENU_SCROLL" )` in `calcStartPos` thought...

Comment (Qrox) [reply src/player_display.cpp:100]: `options.cpp:1659`:

```c++
    add( "MENU_SCROLL", "interface", to_translation( "Centered menu scrolling" ),
         to_translation( "If true, menus will start scrolling in the center of the list, and keep the list centered." ),
         true
       );
```

Comment (Brambor) [reply src/player_display.cpp:100]: Ok, so this is the existing function:
```cpp
void calcStartPos( int &iStartPos, const int iCurrentLine, const int iContentHeight,
                   const int iNumEntries )
{
    if( iNumEntries <= iContentHeight ) {
        iStartPos = 0;
    } else if( get_option<bool>( "MENU_SCROLL" ) ) {
        iStartPos = iCurrentLine - ( iContentHeight - 1 ) / 2;
        if( iStartPos < 0 ) {
            iStartPos = 0;
        } else if( iStartPos + iContentHeight > iNumEntries ) {
            iStartPos = iNumEntries - iContentHeight;
        }
    } else {
        if( iCurrentLine < iStartPos ) {
            iStartPos = iCurrentLine;
        } else if( iCurrentLine >= iStartPos + iContentHeight ) {
            iStartPos = 1 + iCurrentLine - iContentHeight;
        }
    }
}
```

I believe I'm doing the same it can provide for me on these two lines:
```cpp
    size_t slice_start = std::max( 0, int( cursor_pos ) - int( available_space ) / 2 );
    slice_start = std::min( slice_start, list_lenght - available_space );
```
in this function:
```cpp
static std::pair<size_t, size_t> subindex_around_cursor(
    const size_t list_lenght,
    const size_t available_space,
    const size_t cursor_pos,
    const bool focused
)
/**
 * Return indexes [start, end) that should be displayed from list long `list_lenght`,
 * given that cursor is at position `cursor_pos` and we have `available_space` spaces.
 *
 * Example:
 * list_lenght = 6, available_space = 3, cursor_pos = 2, focused = true;
 * so choose 3 from indexes [0, 1, 2, 3, 4, 5]
 * return {1, 4}
 */
{
    if( !focused || list_lenght <= available_space ) {
        return std::make_pair( 0, std::min( available_space, list_lenght ) );
    }
    size_t slice_start = std::max( 0, int( cursor_pos ) - int( available_space ) / 2 );
    slice_start = std::min( slice_start, list_lenght - available_space );
    size_t slice_end = slice_start + available_space;
    return std::make_pair( slice_start, slice_end );
}
```

The existing `calcStartPos` seems very wasteful to me...

Comment (Qrox) [reply src/player_display.cpp]: Using `calcStartPos` respects the "MENU_SCROLL" option though. That option can be true or false depending on user settings.

**Comment by chrispikula** [comment]
This is a really silly question, but is there any left-border bug on the third column?  Of was that never an issue?

**Comment by Qrox** [comment]
The third column already draws the left border according to the code.

File: src/player_display.cpp (hunk 5 above)
Comment (Brambor) [reply src/player_display.cpp]: Ok, I slept and now I understand the simple description of `"MENU_SCROLL"`, will do :)

Comment (Brambor) [reply src/player_display.cpp]: Actually, it's not as easy as plugging it in... it doesn't work while going up while scrolling (it goes up while cursor is on the last line)... But that's fixable, it just needs memory.

Comment (Brambor) [reply src/player_display.cpp]: However, is every menu drawn like this? It looks stupid to me, you should just have a method or a function to which you say "I have space there, and I have X items, figure out scrolling, ask me when you need to draw Xth line, I will provide text".
It seems that every time you make a window, you actually have to make it from characters. And there are lot's of menus in this game!

Or am I missing something?

Comment (Brambor) [reply src/player_display.cpp]: I got that impression from this, autopickup & crafting menus.

Comment (Qrox) [reply src/player_display.cpp]: Having a generic scrollbar class like you describe would be nice, but currently there isn't such a thing.

Comment (Brambor) [reply src/player_display.cpp]: If somebody is reading this @ ZhilkinSerg directed me to src/ui.h which contains `class uilist` described as `uilist: scrolling vertical list menu`. Looks intimidating on my first issue, I made a feature request (#50928) about the "MENU_SCROLL". Will not fix in this PR.

File: src/player_display.cpp (hunk 1 above)
Comment (Brambor) [reply src/player_display.cpp:143]: To be honest, I named my function the same, so I should probably change at least that.
I was hoping that eventually, only the body of for loop would survive in these functions returning iterator, so this function would be called only once as my other function. Then they both would be expanded and removed...

Comment (Brambor) [reply src/player_display.cpp:134]: This seems to be the last thing. I would like to keep it as-is. But I didn't really resolve the issue mentioned, so I will not mark this as resolved.

Comment (Brambor) [reply src/player_display.cpp]: Ok, I replaced it with the legacy function. Funnily enough, the `if` in  `if (do_draw_scrollbar) {draw_scrollbar(...);}` was useless, since it's handled in `class scrollbar::apply`.

**Comment by Brambor** [comment]
Edit: fixed that the scrollbar on encumbrance wasn't displaying.

Is that all @Qrox ?

**Comment by Qrox** [comment]
Yeah, thanks for addressing the comments.
