### PR TITLE
msg log entry added to insert activity

### LINKED ISSUE #47616: No log message when inserting items into containers
# Describe the bug

When `i`nserting items into a container, the message log does not indicate anything happening, even though it may take a long time.

# Steps To Reproduce

1. Get a container and some item(s) that will fit in it
2. Select the container and `i`nsert
3. Select some items to insert and press Enter - items are inserted, but nothing is written to the message log

# Expected behavior

Messages like "You insert your wrench into the backpack." or "You insert your bubble wrap into the large cardboard box. x 100"

# Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Pop; Description: Pop!_OS 20.04 LTS; Release: 20.04; Codename: focal; 
- Game Version: 0.E-9737-g511ddcb179 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
Interface "Added msg log entry to insert activity"

#### Purpose of change

Adds a msg log entry whenever an insert activity finishes.
Fixes #47616

#### Describe the solution
Added the msg to the insert_item_activity_actor's finish method

#### Testing

- Spawn in 2 backpacks
- Start inserting items from one into the other.

#### Additional context
Example:
image

### CODE REVIEW

File: src/activity_actor.cpp [hunk 1]
```diff
@@ -2401,6 +2403,8 @@ void insert_item_activity_actor::finish( player_activity &act, Character &who )
                 success = result > 0;
 
                 if( success ) {
+                    add_msg( string_format( _( "You insert your %s into the1 %s." ),
```
Comment (Night-Pryanik) [inline src/activity_actor.cpp:2406]:
```suggestion
                    add_msg( string_format( _( "You insert your %s into the %s." ),
```

File: src/activity_actor.cpp [hunk 2]
```diff
@@ -2384,6 +2384,8 @@ void insert_item_activity_actor::finish( player_activity &act, Character &who )
                 success = holster->put_in( it, item_pocket::pocket_type::CONTAINER,
                                            /*unseal_pockets=*/true ).success();
                 if( success ) {
+                    add_msg( string_format( _( "You insert your %s into the %s." ),
```
Comment (wapcaplet) [inline src/activity_actor.cpp:2387]:
```suggestion
                    who.add_msg_if_player( string_format( _( "You insert your %s into the %s." ),
```

Messages for things the player does (typically any message starting with the word "You") should use the more specific `add_msg_if_player` method. The `add_msg` method is unconditional and might conceivably be displayed when an NPC or monster does the activity. I know this file is already filled with incorrect usages of both functions, but it would be best not to make it worse :-)

Comment (Jamuro-g) [reply src/activity_actor.cpp:2387]: ah ok then i can skip the avatar check in the if

File: src/activity_actor.cpp [hunk 3]
```diff
@@ -2384,6 +2384,8 @@ void insert_item_activity_actor::finish( player_activity &act, Character &who )
                 success = holster->put_in( it, item_pocket::pocket_type::CONTAINER,
                                            /*unseal_pockets=*/true ).success();
                 if( success ) {
+                    who.add_msg_if_player( string_format( _( "You insert your %s into the %s." ),
```
Comment (actual-nh) [inline src/activity_actor.cpp:2387]:
```suggestion
                    who.add_msg_if_player( string_format( _( "You insert your %1$s into the %2$s." ),
```
Positional arguments, so translators can rearrange as needed.

File: src/activity_actor.cpp [hunk 4]
```diff
@@ -2401,6 +2403,8 @@ void insert_item_activity_actor::finish( player_activity &act, Character &who )
                 success = result > 0;
 
                 if( success ) {
+                    who.add_msg_if_player( string_format( _( "You insert your %s into the %s." ),
```
Comment (actual-nh) [inline src/activity_actor.cpp:2406]:
```suggestion
                    who.add_msg_if_player( string_format( _( "You insert your %1$s into the %2$s." ),
```
Ditto.

**Review by actual-nh — COMMENTED** [review]
A couple of changes to make translators' task easier.

File: src/activity_actor.cpp (hunk 3 above)
Comment (Jamuro-g) [reply src/activity_actor.cpp:2387]: ah thank you i was trying to find out how to do that

**Comment by NickGrease** [comment]
Would replacing 'insert' with put or place be better? I mean, if you're a programmer 'insert' is the correct term, but I've never heard someone say "insert your pants into the backpack". I can almost hear something like "insert the batteries into the flashlight", but again I think 'put' would work better. No big deal either way, just an observation.

**Comment by Jamuro-g** [comment]
> Would replacing 'insert' with put or place be better? I mean, if you're a programmer 'insert' is the correct term, but I've never heard someone say "insert your pants into the backpack". I can almost hear something like "insert the batteries into the flashlight", but again I think 'put' would work better. No big deal either way, just an observation.

You are right, it does sound a bit strange. I'll change it to put

File: src/activity_actor.cpp [hunk 5]
```diff
@@ -2384,7 +2384,7 @@ void insert_item_activity_actor::finish( player_activity &act, Character &who )
                 success = holster->put_in( it, item_pocket::pocket_type::CONTAINER,
                                            /*unseal_pockets=*/true ).success();
                 if( success ) {
-                    who.add_msg_if_player( string_format( _( "You insert your %1$s into the %2$s." ),
+                    who.add_msg_if_player( string_format( _( "You put your %1$s into the %2$s." ),
```
Comment (wapcaplet) [inline src/activity_actor.cpp:2387]:
```suggestion
                    //~ %1$s: item to put in the container, %2$s: container to put item in
                    who.add_msg_if_player( string_format( _( "You put your %1$s into the %2$s." ),
```

A comment like this will aid translators in knowing which string is which (since they may appear in a different order in some languages).

File: src/activity_actor.cpp [hunk 6]
```diff
@@ -2403,7 +2403,7 @@ void insert_item_activity_actor::finish( player_activity &act, Character &who )
                 success = result > 0;
 
                 if( success ) {
-                    who.add_msg_if_player( string_format( _( "You insert your %1$s into the %2$s." ),
+                    who.add_msg_if_player( string_format( _( "You put your %1$s into the %2$s." ),
```
Comment (wapcaplet) [inline src/activity_actor.cpp:2406]:
```suggestion
                    //~ %1$s: item to put in the container, %2$s: container to put item in
                    who.add_msg_if_player( string_format( _( "You put your %1$s into the %2$s." ),
```
See above.

**Review by wapcaplet — CHANGES_REQUESTED** [review]
