### PR TITLE
Resolve a bug in partial stack dropping/using and unify ui behaviour

### LINKED ISSUE #50431: Washing doesn't recalculate requirements on lowering item count
### Describe the bug

Requirements for washing are not recalculated when lowering item count specific way.

### Steps To Reproduce

1. Make a player with a washing board and a bunch of filthy rags.
2. [a]ctivate the washing board and select all rags for cleaning.
3. Without deselecting rags, select one filthy rag (press 1, then right arrow on rags).
4. Observe the required water and the cleanser stayed the same.

### Expected behavior

Recalculation on lowering item count. It is currently recalculated only on increasing item count.

### Screenshots

CDDA washing recalculation

### Versions and configuration

- OS: Windows 10
- Game Version: 2021-08-02-0846
- Graphics version: Tiles

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ZeroInternalReflection**
Resolves #50431

#### Summary
Bugfixes "Resolve a bug in partial stack dropping/using and unify ui behaviour"

#### Purpose of change
Fixes #50431.  When 'd'ropping part of a stack of items, or selecting part of a stack for an action such as washing items, any previous selection was not properly cleared in ::set_chosen_count().  So, the player might mark 3 items in a stack for washing, then change their mind and only was 2. The UI would be partially (but not completely) updated, but it would still wash all 3 items.
Test 1:
1. Select a stack of items to drop/wash (same behaviour)
2. Tell it to only drop 1 instead
3. UI says it will drop 1, but doesn't update volume/weight change
4. Drops the entire stack

Test 2:
1. Select 1 item from a stack to drop
2. Tell it to drop 2 items instead-
3. UI says it will drop 2, and updates volume/weight change accordingly
4. Drops 2

#### Describe the solution
Updating ::set_chosen_count() to clear any previously-flagged parts of the stack before doing anything else fixes this bug.  Moving ::set_chosen_count() to inventory_multiselector makes the ui behaviour more consistent between dropping/using items, and ensures this bug is resolved in both menus.

#### Describe alternatives you've considered
::set_chosen_count() could have been fixed in both inventory_iuse_selector() and inventory_drop_selector(), however the differences between these two classes did not seem worth having the code duplicated.

#### Testing
Manually spawned stacks of items for cleaning and dropping.  Selected various quantities, then changed the selection and confirmed both ui and behaviour updated correctly.
To my knowledge, cataclysm does not currently have any automated tests for ui behaviour.  If we do have the infrastructure for that, I can try to build that.

#### Additional context
The 'g'et and advanced inventory menu were unaffected by this issue and did not need updating.  The 'g'et currently only allows changes from 0 selected->x selected and x selected->0 selected, and ignores attempts to go x selected->y selected.  Similarly, the advanced inventory menu only gives the one opportunity to input quantities.  However, ensuring consistent behaviour across these menus would be beneficial.

### CODE REVIEW

**Comment by mqrause** [comment]
Nice, that's part of what I need for the pickup menu!

**Comment by ZeroInternalReflection** [comment]
@mqrause 

I'm also experimenting with some other ways to reduce code duplication in inventory_ui.cpp.  One of the things I'm trying which is relevant to what you're working on with pickup_selector is moving as many of the standard actions (filtering, examining, etc.) as possible to inventory_selector::on_input() rather than having it show up in the execute() in each derived class.

**Comment by mqrause** [comment]
That sounds great and probably saves me all the work in that regard.

File: src/iuse.cpp [hunk 1]
```diff
@@ -9506,12 +9506,12 @@ cata::optional<int> iuse::wash_items( Character *p, bool soft_items, bool hard_i
...
     } );
-    auto make_raw_stats = [available_water, available_cleanser](
-                              const std::map<const item_location *, int> &locs
+    auto make_raw_stats = [available_water,
+                           available_cleanser]( const std::vector<std::pair<item_location, int>> &locs
     ) {
         units::volume total_volume = 0_ml;
         for( const auto &pair : locs ) {
-            total_volume += ( *pair.first )->volume( false, true );
+            total_volume += ( *pair.first ).volume( false, true );
```
Comment (mqrause) [inline src/iuse.cpp:9514]:
```suggestion
            total_volume += pair.first->volume( false, true );
```

It's the same, but easier to read.
