### PR TITLE
Prevent causing effects when value 0

### LINKED ISSUE #42491: Thunderstorm causes hurt message
# Describe the bug
When doing a activity like reading ect during a thunderstorm, the player gets a message about being hurt and asked if they wanna stop the activity. even though it cause no damage or pain whatsoever, it was able to still dent my hard hooded helmet and clothing.

# Steps To Reproduce

1. spawn in a Book, change weather to thunderstorm (or even better, wait until you get a thunderstorm session so it lasts longer)
2. Read book
3. Get hurt

# Expected behavior

that even when indoor, the thunderstorm wouldnt try to rip your clothes apart

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.E-4457-g92af4ff [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

# Additional context

Lightning storm is also affected.

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix weather effects displaying pain even when value is 0."

#### Purpose of change
Fix #42491
Prevent weather with effects showing message about 0 pain.

#### Describe the solution
Checked for zero values before causing effects to happen.

### CODE REVIEW

File: src/weather.cpp [hunk 1]
```diff
@@ -586,19 +586,28 @@ void handle_weather_effects( weather_type_id const w )
...
         }
-        player_character.mod_healthy( current_effect.healthy );
-        player_character.mod_rad( current_effect.radiation );
-        wet( player_character, current_effect.wet );
-        player_character.mod_pain( current_effect.pain );
+        if( current_effect.healthy != 0 ) {
+            player_character.mod_healthy( current_effect.healthy );
+        }
+        if( current_effect.radiation != 0 ) {
+            player_character.mod_rad( current_effect.radiation );
```
Comment (ZhilkinSerg) [inline src/weather.cpp:603]: I think it would be better to move zero checks to called functions.

Comment (Ramza13) [reply src/weather.cpp]: So for damage at least I don't know enough about damage to be sure that's a good idea. It touches a lot more than this change and I don't know enough to be sure it wouldn't cause other bugs.
