### PR TITLE
Pathing up and down misaligned stairs for NPCs

### LINKED ISSUE #56501: Followers will not go down into subway stations after you
### Describe the bug

I have an NPC follower who will not go down the stairs into subway stations after me, unless I debug control them to do so.

### Steps to reproduce

1. Have an NPC follower.
2. Descend from Z-level 0 of a subway station to Z-level -1.
3. Observe the NPC never follows you down.

### Expected behavior

I expect the NPC follower to know how the stairs work.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19043.1586 (21H1)
- Game Version: 0b63322 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations],
    No Vault [No_Vault],
    ASCIITiles overmap color fix [colors_fix_asciitiles]
]

### Additional context

I suspect this is happening because the stairs in subway stations also teleport you. Suggest redesigning the subway station to avoid having to do this.

### PR DESCRIPTION
**Pull request by RoyBerube**
#### Summary

Bugfixes "Pathing up and down misaligned stairs for NPCs"

#### Purpose of change

Fixes #56501

NPCs could not path up or down on map locations where the stairs on the next floor were not at the same x and y location.

To reproduce:
1. Have an NPC follower at the subway ground level floor. Subway main and mid levels must have misaligned stairs.
2. Use the stairs down.
3. Notice the NPC does not follow.

#### Describe the solution
NPC pathfinding was assuming the stairs on the next floor were aligned with the current floor. 

The solution is to use the same technique as the player when using stairs; do a search within range for a stair on the next floor.
Modified associated code to allow for NPC to use the method as well as the player character.

#### Describe alternatives you've considered
Writing a new `find_or_make_stairs()` method for NPCs.

Fix the map generation. I don't understand that code so did not attempt it.

#### Testing

Used stairs at a subway with NPC in tow. NPC follows across all levels up and down.

Tested elevators. Still working.

Does not fix monsters. They still will not follow across misaligned stairs because they can not see the player after the level transition.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -11217,29 +11218,30 @@ void game::start_hauling( const tripoint &pos )
...
 
 cata::optional<tripoint> game::find_or_make_stairs( map &mp, const int z_after, bool &rope_ladder,
-        bool peeking )
+        bool peeking, const tripoint pos )
 {
+    const bool is_avatar = u.pos() == pos;
     const int omtilesz = SEEX * 2;
-    real_coords rc( m.getabs( point( u.posx(), u.posy() ) ) );
-    tripoint omtile_align_start( m.getlocal( rc.begin_om_pos() ), z_after );
+    real_coords rc( mp.getabs( point( pos.x, pos.y ) ) );
```
Comment (dseguin) [inline src/game.cpp:11225]:
```suggestion
    real_coords rc( mp.getabs( pos.xy() ) );
```

File: src/game.cpp [hunk 2]
```diff
@@ -11217,29 +11218,30 @@ void game::start_hauling( const tripoint &pos )
 }
 
 cata::optional<tripoint> game::find_or_make_stairs( map &mp, const int z_after, bool &rope_ladder,
-        bool peeking )
+        bool peeking, const tripoint pos )
```
Comment (dseguin) [inline src/game.cpp:11221]:
```suggestion
        bool peeking, const tripoint &pos )
```
Last changes, I promise :P
Clang-tidy is pretty strict about const qualified parameters now, passing by reference will get around that

File: src/game.h [hunk 3]
```diff
@@ -273,9 +273,11 @@ class game
          */
         void vertical_move( int z, bool force, bool peeking = false );
         void start_hauling( const tripoint &pos );
-        /** Returns the other end of the stairs (if any). May query, affect u etc.  */
+        /** Returns the other end of the stairs (if any). May query, affect u etc.
+        * @param pos Disable queries and msgs if not the same position as player.
+        */
         cata::optional<tripoint> find_or_make_stairs( map &mp, int z_after, bool &rope_ladder,
-                bool peeking );
+                bool peeking, const tripoint pos );
```
Comment (dseguin) [inline src/game.h:280]:
```suggestion
                bool peeking, const tripoint &pos );
```
