### PR TITLE
Fix message ttl issues & unbound keys triggering auto-save

### LINKED ISSUE #15995: Misc bugs with sidebar message log ttl
Regarding the message ttl feature added in https://github.com/CleverRaven/Cataclysm-DDA/pull/15907,

1. When using the right-click actions, some messages last 1 turn too long e.g. "Nothing relevant here."
2. Some actions clear messages that probably shouldn't e.g. zooming in/out, viewing character info, shifting the view offset with H,J,K,L.

I'm working on a pr to address these.

### LINKED ISSUE #16006: Pressing unbound keys can trigger autosave
Unbound keys (i.e. the ones that say "Unknown command: 'x'") can trigger autosave.

The ACTION_NULL action is causing the autosave counter to increment. It's also causing night vision cache to invalidate unnecessarily.

PR coming shortly.

### PR DESCRIPTION
**Pull request by lucianposton**
1. The first commit fixes #16006, unbound keys triggering auto-save.
2. The second commit fixes #15995, the various message ttl issues.
   
   This commit moves around logic in game::handle_event() so that the
   user_action_counter can be incremented after blocking for user input but
   before any messages are written to the sidebar log. Previously, the counter
   was incremented immediately prior to blocking for input. However, this caused
   the issues with the SEC_SELECT info messages' ttl misbehavior.
   
   This commit also introduces a function to test whether an action will cause a
   _perceived_ worldstate change to the user. This function is checked prior to
   incrementing the user_action_counter in order to allow some actions to not
   cause messages to expire e.g. shifting the view offset, viewing informational
   screens like player info, zooming in/out, etc.
3. The third commit is a refactoring to make game::handle_action more readable. It adds action_id's for mouse events, SELECT & SEC_SELECT, to the action_id enum in order to facilitate this.

Fixes #15995, #16006

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -3196,6 +3140,84 @@ bool game::handle_action()
...
+        act = ACTION_CLOSE;
+    } else {
+        int dx = abs(u.posx() - mouse_target.x);
+        int dy = abs(u.posy() - mouse_target.y);
+        if (dx < 2 && dy < 2) {
+            if (dy == 0 && dx == 0) {
+                // Clicked on self
+                act = ACTION_PICKUP;
+            } else {
+                // Clicked adjacent tile
```
Comment (BevapDin) [inline src/game.cpp]: The "is adjacent" check is duplicated a few lines above in the condition for `ACTION_CLOSE`. It would be nice to extract that check into a boolean constant at the top of the function and use that in both conditions.

This may also allow you to get rid of the redundant comments.

Comment (lucianposton) [inline src/game.cpp]: Added a commit to simplify those conditionals

File: src/game.cpp [hunk 2]
```diff
@@ -3178,6 +3178,8 @@ bool game::try_get_right_click_action( action_id &act, const tripoint &mouse_tar
         return false;
     }
 
+    const bool is_adjacent = std::abs(mouse_target.x - u.posx()) <= 1 && std::abs(mouse_target.y - u.posy()) <= 1;
+    const bool is_self = std::abs(mouse_target.x - u.posx()) <= 0 && std::abs(mouse_target.y - u.posy()) <= 0;
```
Comment (codemime) [inline src/game.cpp]: You could simplify them even more by using:
```c++
const int dist = square_dist( mouse_target, u.pos() ) // Supposing mouse_target and u are on the same z-level
```
It's defined in line.h

Comment (lucianposton) [inline src/game.cpp]: That probably won't be a safe assumption once z-levels are added. I'd imagine you'd be able to offset your view by z-levels, just as you can offset it by x and y currently.

Comment (codemime) [inline src/game.cpp]: Then we probably need another version of `square_dist()` which can ignore z-coord. I'm absolutely sure it will be used more than once.

Comment (lucianposton) [inline src/game.cpp]: Ok. changed to use square_dist() is latest commit
