### PR TITLE
Fix filthy wearable weapon drops

### LINKED ISSUE #36874: Guns with attached shoulder strap can drop with "filthy" tag
# Describe the bug

%subj%. Also, when you remove shoulder strap, it is not filthy but the gun still is.

# Steps To Reproduce

Well, kill zoldiers/biops and hope for "lucky" drop, I guess?

# Expected behavior

Guns with shoulder strap should not drop filthy (I guess they count as clothing because you can wear them, so filthy can proc on their generation?).
Alternatives are either make shoulder strap detached from such a gun filthy, or make all zed-dropped guns have a chance to be filthy, both of which don't make much sense, gameplay-wise anyway. At least while only usage of filthy clothing is being penalized.

# Screenshots

cataclysm-tiles_2020_01_10_18_26_33_580

# Versions and configuration

- OS: Windows 7
- Game Version: 0.D-11099-gb8625b0 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Skills [StatsThroughSkills]
]

### PR DESCRIPTION
**Pull request by saurocyte**
#### Summary
```SUMMARY:  Bugfixes "Fix monsters dropping filthy weapons with shoulder strap mod"```

#### Purpose of change
Fixes #36874 

#### Testing
Try to reproduce #36874

### CODE REVIEW

File: src/monster.cpp [hunk 1]
```diff
@@ -2323,7 +2323,8 @@ void monster::drop_items_on_death()
 
     if( has_flag( MF_FILTHY ) && get_option<bool>( "FILTHY_CLOTHES" ) ) {
         for( const auto &it : dropped ) {
-            if( it->is_armor() || it->is_pet_armor() ) {
+            if( (it->is_armor() || it->is_pet_armor()) && !it->is_gun()) {
```
Comment (Night-Pryanik) [inline src/monster.cpp]:
```suggestion
            if( ( it->is_armor() || it->is_pet_armor() ) && !it->is_gun() ) {
```
