### PR TITLE
Fix game freeze when player cannot contain mission reward

### LINKED ISSUE #47282: The recently added mission from the new island prison crashes the game at success
# Describe the bug

#46726 introduced several things, one of which is a new mission from the leader of the new, prisoner faction, but when you try to complete it, the game crashes. 

~~That, and the mission itself has a mistake, it asks you for a Military Id, but the safe from where you are supposed to retrieve it only has an Industrial Id, maybe this is intentional, I don't know, but then it should be at least clearer what is it that you need to find.~~ Edit: My mistake, the Military ID is in "The Chief"'s safe, I was looking into "The Warden"'s safe...

# Steps To Reproduce

1. Make a player start in the island prison, second variant
2. Teleport to the leader of the prisoners
3. Accept the mission, grant yourself an Industrial Id, try to complete it, nothing happens, do the same with a Military Id, the game crashes
OR
1. Load the game from the save below
2. Try to complete the mission
3.  The game crashes 

# Expected behavior

That the game doesn't crash when you complete a mission.
~~That, and to see the npc request items that are actually where they are sending you to find them, or that at least they recognize they didn't wanted what you found.~~

# Screenshots

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-9442-ge9e4d33-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: Español (España) [es_ES]
- Mods loaded: [
    Dark Days Ahead [dda],
    Desactivar necesidades de los PNJ [no_npc_food],
    Profesiones Biónicas [package_bionic_professions],
    SpeedyDex [speedydex],
    Estadísticas a través de las muertes [stats_through_kills]
]

# Additional context

Logs:
[logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5937976/logs.zip)
Save folder:
[Arbuckle.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5937977/Arbuckle.zip)

As a side note, I would like to mention that the rewards are basically worthless, they should at least let you commerce with them or contract them as mercenaries, or, well, something, it's a pretty difficult mission and the leader can get the best stuff in the whole island if you give him the ID. And, if you don't give him the ID, those things can be yours, and you can easily take all of their food, I demand a better reward for this mission, at the very least give me a gun, or a set of armor taken from one of the dead guards... But again, I would prefer a little of respect from the prisoners.

Edit: I forgot to mention, but this bug doesn't happens when you just meet the leader for the first time with already a Military Id and just give it to him, I hope that helps to search for the problem

Edit 2: Grammar

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
Bugfixes "Fix game freeze when player cannot contain mission reward"

#### Purpose of change
Fix #47282 : The game stuck in an infinite loop trying to add the mission reward item to the player's inventory when the player cannot contain it.

#### Describe the solution
Swap the order of two statements in `item_pocket::handle_liquid_or_spill`.

#### Describe alternatives you've considered
A band-aid fix, see https://github.com/BrettDong/Cataclysm-DDA/commit/29e4c2b5b03db6e4bfa5bddb876fcf2a9da1281d: Add a check `can_stash`. If the player cannot stash the reward item, then place it on the ground instead. This avoids the infinite loop.

#### Testing
Load the save in #47282 and the game does not freeze.

### CODE REVIEW

File: src/npctalk.cpp [hunk 1]
```diff
@@ -1759,7 +1759,11 @@ void talk_effect_fun_t::set_u_buy_item( const itype_id &item_name, int cost, int
             item container( container_name, calendar::turn );
             container.put_in( item( item_name, calendar::turn, count ),
                               item_pocket::pocket_type::CONTAINER );
-            d.alpha->i_add( container );
+            if( d.alpha->get_character()->can_stash( container ) ) {
+                d.alpha->i_add( container );
+            } else {
+                get_map().add_item( d.alpha->pos(), container );
```
Comment (anothersimulacrum) [inline src/npctalk.cpp:1765]: Add a message that they put in on the ground?

**Comment by BrettDong** [comment]
Marking as draft because I just found that it is supposed to pop up an unwield menu without this patch. The real bug is deeper in item pocket system. Currently this is a band-aid fix and does not address the real bug under the hood.
