### PR TITLE
World related fixes

### LINKED ISSUE #18686: In-game keybinding inaccesible from main menu, required action poorly indicated
First observed in Windows graphical build 5616, further found to still be present in build 5646.

The in-game keybindings can no longer be changed from the main menu, instead only accessible in-game. The option menu instead has the considerably-less-useful menu for rebinding menu navigation. Actual gameplay commands are infinitely more likely to be changed by players.

Hitting escape during brings up options, among them the menu for changing in-game keybindings. But the same keypress in the main menu brings up the "Do you want to quit?" dialog. Given you can close the window manually or select the quit option at the far right of the menu, I see no reason for keybindings being inaccessible from the title.

Furthermore, the new method of access is not hinted at on the main menu, nor readily apparent in the help menu. Whereas hitting `?' is a common convention in roguelikes and relatively intuitive, the new method of access is not consistently applied at present, and less intuitive for both new players and older ones.

I would recommend either the escape keybinding be consistent between both the main menu and in-game, _or_ make the keybinding section of the settings menu allow players to reconfigure actual gameplay controls instead of (or in addition to) menu navigation controls.

### LINKED ISSUE #20421: If options are opened from main menu, number queries do not appear
* Start game
* Don't load world
* Open a menu with number queries, for example world generation
* Select a numeric value
* Press enter
* Expected: opens a menu "pick a number"
* Got: nothing

The same option will have a query in the same menu if it is opened in game, in loaded world.

### LINKED ISSUE #21658: No way to see World Mod Settings after it's made
### Expected Behavior
In the title screen World menu, it would be nice if there were an option to see what the world settings and mods are for a given world. While you can see many of the world setting in the options menu once in game, this doesn't include mods.

### PR DESCRIPTION
**Pull request by OzoneH3**
Closes #21658
Closes #20421
Closes #18686

* Fixed: In-game keybindings inaccessible from title main menu
* Use options_manager interface when changing options on world create. (Removes duplicated logic)
* Option to display active world mods while ingame and from the title menu.
* Redid World menu to be in line with Load menu.

### CODE REVIEW

File: src/worldfactory.cpp [hunk 1]
```diff
@@ -874,7 +734,52 @@ void worldfactory::draw_mod_list( WINDOW *w, int &start, int &cursor, const std:
     }
 
     wrefresh( w );
-    wrefresh(w_shift);
+    wrefresh( w_shift );
+}
+
+void worldfactory::show_active_world_mods() {
```
Comment (Coolthulhu) [inline src/worldfactory.cpp]: You could probably use `uimenu` here instead of drawing the menu manually.

Comment (OzoneH3) [reply src/worldfactory.cpp]: I'm using the same function that draws the mods while creating the world (draw_mod_list()). That way I don't have to deal with ordering, naming and especially categories.

File: src/worldfactory.cpp [hunk 2]
```diff
@@ -1385,6 +1290,12 @@ void worldfactory::draw_worldgen_tabs(WINDOW *w, unsigned int current)
         }
     }
 
+    static std::vector<std::string> tab_strings = {{
```
Comment (codemime) [inline src/worldfactory.cpp]: Being `static` means the vector won't be re-translated when the language changes. This should probably be `const`, but not `static`.

Comment (Coolthulhu) [reply src/worldfactory.cpp]: Or can be `static const`, but should not be translated here, instead just marked with `translate_marker` and translated later.

**Comment by Coolthulhu** [comment]
The queries show up, but actually using them results in a crash.

File: src/main_menu.cpp [hunk 3]
```diff
@@ -851,145 +856,154 @@ void main_menu::world_tab()
...
 
-                        if( all_worldnames.empty() ) {
+                        if( do_delete ) {
                             sel2 = 0; // reset to create world selection
                         }
                     }
                 }
-                print_menu( w_open, sel1, iMenuOffsetX, iMenuOffsetY );
+            }
+        } else if( layer == 2 ) { // Show world names
```
Comment (Coolthulhu) [inline src/main_menu.cpp]: Those layer magic constants would be much more readable if you defined an enum for them.

File: src/options.cpp [hunk 4]
```diff
@@ -1659,23 +1674,25 @@ void options_manager::show(bool ingame)
...
-        for (int i = 0; i < (int)vPages.size(); i++) {
-            if (!mPageItems[i].empty()) { //skip empty pages
-                wprintz(w_options_header, c_white, "[");
-                if ( ingame && i == iWorldOptPage ) {
-                    wprintz(w_options_header,
-                            (iCurrentPage == i) ? hilite(c_ltgreen) : c_ltgreen, _("Current world"));
-                } else {
-                    wprintz(w_options_header, (iCurrentPage == i) ?
-                            hilite( c_ltgreen ) : c_ltgreen, "%s", _( vPages[i].second.c_str() ) );
+        if ( !world_options_only ) {
```
Comment (Coolthulhu) [inline src/options.cpp]: Styling

File: src/worldfactory.cpp [hunk 5]
```diff
@@ -602,156 +598,20 @@ std::string worldfactory::pick_random_name()
     return get_next_valid_worldname();
 }
 
-int worldfactory::show_worldgen_tab_options(WINDOW *win, WORLDPTR world)
+int worldfactory::show_worldgen_tab_options(WINDOW*, WORLDPTR world)
```
Comment (Coolthulhu) [inline src/worldfactory.cpp]: If you don't need that WINDOW argument, get rid of it.

File: src/main_menu.cpp [hunk 6]
```diff
@@ -785,20 +786,24 @@ bool main_menu::load_character_tab()
                 } );
                 savegames.erase( new_end, savegames.end() );
             }
+
+            mvwprintz( w_open, iMenuOffsetY - 2 - sel2, 15 + iMenuOffsetX + extra_w / 2, h_white, wn.c_str() );
```
Comment (Coolthulhu) [inline src/main_menu.cpp]: All those magical constants in position arguments make it hard to understand where do things go.
The whole thing would be much more readable if that `15`, `40` and similar had names. Say, `worldmenu_x_offset` or something like that.

File: src/main_menu.cpp [hunk 7]
```diff
@@ -851,145 +856,154 @@ void main_menu::world_tab()
...
+                    --sel2;
+                } else {
+                    sel2 = all_worldnames.size();
+                }
+            } else if( action == "UP" ) {
+                if( sel2 < ( int )all_worldnames.size() ) {
+                    ++sel2;
+                } else {
+                    sel2 = 0;
+                }
```
Comment (Coolthulhu) [inline src/main_menu.cpp]: You repasted that block of code multiple times. This specific kind of copypaste code is also used in many places in game code.
It would be good to have a function for it, like what `clamp` does for clamping.
Say, `void wrap( int &x, int max )` or `int wrap( int x, int max )`.

File: src/options.cpp [hunk 8]
```diff
@@ -1659,23 +1674,25 @@ void options_manager::show(bool ingame)
...
+            mvwprintz(w_options_header, 0, 7, c_white, "");
+            for (int i = 0; i < (int)vPages.size(); i++) {
+                if (!mPageItems[i].empty()) { //skip empty pages
```
Comment (Coolthulhu) [inline src/options.cpp]: You could invert the `if` to save on nesting.
The number of indents here is huge, squeezing the code against the right margin.

**Comment by Coolthulhu** [comment]
Generally works, except for that query thing, which is broken and must be fixed.

The code quality is rather low, full of boilerplate and not easy to read. Would be good if you cleaned it up. It isn't strictly necessary because a lot of that is just maintenance of old code that was ugly already, but it would certainly help not to have to deal with magic numbers in UI placement in the future.

**Comment by OzoneH3** [comment]
> except for that query thing, which is broken and must be fixed.

This is a options problem, same behaviour in the current master.
It does not crash for me, I have to use the correct decimal point though
eg. 1,23 for it to work, even though it's displayed as 1.23 afterwards.

```
ssTemp.imbue(std::locale(""));
// This uses the current locale, to allow the users
// to use their own decimal format.
```

**Comment by AMurkin** [comment]
That issue #20927?

File: src/worldfactory.cpp (hunk 5 above)
Comment (OzoneH3) [reply src/worldfactory.cpp]: Can't that's what it expects:

```
typedef std::function<int( WINDOW *, WORLDPTR )> worldgen_display;
std::vector<worldgen_display> tabs;
```

File: src/main_menu.cpp (hunk 3 above)
Comment (OzoneH3) [reply src/main_menu.cpp]: How would an enum calling them layer_1, layer_2, layer_3 make them any better?

File: src/main_menu.cpp (hunk 6 above)
Comment (OzoneH3) [reply src/main_menu.cpp]: This whole thing could use a refactor for sure.

File: src/main_menu.cpp (hunk 3 above)
Comment (Coolthulhu) [reply src/main_menu.cpp]: It wouldn't. You'd have to make a sane enum, with names like `world_names`, not `layer_2`.

**Comment by OzoneH3** [comment]
Also your own ticket on the subject: #20624
Seems to only affect self compiled versions.

**Comment by kevingranade** [comment]
Yes we'd like the ui code to be cleaner, but as you're fixing bugs and matching the existing changes, I don't see any reason to block the changes based on lack of refactoring.
