### PR TITLE
Fixes for butchery and smoking rack.

### LINKED ISSUE #24920: Should field dressed zombie carcasses still revive?
As far as I can tell, when I field dress a zombie corpse, the resulting carcass is still capable of reviving itself. Is that the intended behavior?

### LINKED ISSUE #24925: Leather tarp isn't a valid flat surface despite the description saying that it is?
**Describe the bug**  
The Leather tarp isn't a valid "table" when it says that it is?

**To Reproduce**  
Steps to reproduce the behaviour:
1. Make butchering rack
2. Make leather tarp and set leather tarp up
3. Bring pulped zombie corpse onto butchering rack

**Expected behavior**  
Being able to do a full butchery with a butchering rack and a leather tarp

**Screenshots**  
image

**Versions and configuration(please complete the following information):**
 - OS: Windows 7
 - Game Version 0.C-30680-gb8ef478
 - Graphics version Tiles
 - Mods loaded [   "dda",   "Experimental-Z-Level",   "more_locations",   "FujiStruct",   "Medieval_Stuff",   "More_Survival_Tools",   "Packaging",   "RL_Classes",   "SD_Magcrafting",   "StatsThroughSkills",   "blazemod",   "Tanks",   "Urban_Development",   "ZSFIXED_cddaxp",   "boats",   "cityside",   "craftgp",   "deoxymod",   "ew_pack",   "filthy_morale",   "makeshift",   "more_buildings",   "more_classes_scenarios",   "mutant_npcs",   "national_guard_camp",   "no_npc_food",   "npc_traits",   "oa_additional_buildings_mod",   "realguns",   "Tolerate_This" ]

### PR DESCRIPTION
**Pull request by nexusmrsep**
Those a are few minor fixes for butchery and smoking rack:

1. Resolves #24925 - flag name was renamed along the patching process, but leather tarp was left behind. Changed `FLAT_FURN` to `FLAT_SURF`, and it is now recognized as a butchering aid.

2. Some food that used `copy_from` in their json files inherited `SMOKABLE` flag and were improperly accepted by the smoking rack: offal & jerky. This flag is now removed from them.

3. It was suggested to me, that manwurst description should not only mention curing but also smoking, as manwurst is a result of smoking raw manwurst.

4. Resolves #24920 - prevents zombies from raising from quartered and field dressed corpses

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -6508,6 +6508,10 @@ bool game::revive_corpse( const tripoint &p, item &it )
         it.active = false;
         return false;
     }
+    if( it.has_flag( "FIELD_DRESS" ) || it.has_flag( "FIELD_DRESS_FAILED" ) || it.has_flag( "QUARTERED" ) ) {
+        // Failed reanimation due to corpse being butchered
+        return false;
```
Comment (narc0tiq) [inline src/game.cpp]: Should this also set the corpse item's `active` to `false`, like above?
