### PR TITLE
Unseal source and target containers when inserting contents and refactor unsealing code

### LINKED ISSUE #46047: tried to put an item (water_clean, amount 1) in a container (bottle_plastic) that cannot contain it
# Describe the bug
```
14:15:41.703 ERROR : (error message will follow backtrace)
    /usr/bin/cataclysm(_Z21debug_write_backtraceRSo+0x3a) [0x55c9b6f3510a]
    /usr/bin/cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x2d9) [0x55c9b6f36e69]
    /usr/bin/cataclysm(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x67) [0x55c9b6f3ab37]
    /usr/bin/cataclysm(_ZN4item9fill_withERKS_i+0x561) [0x55c9b7318601]
    /usr/bin/cataclysm(_ZN9Character9pour_intoER4itemS1_+0x27d) [0x55c9b6db87dd]
    /usr/bin/cataclysm(_ZN17activity_handlers19fill_liquid_do_turnEP15player_activityP6player+0xb21) [0x55c9b6bad591]
    /usr/bin/cataclysm(_ZNK13activity_type12call_do_turnEP15player_activityP6player+0x93) [0x55c9b6bf8033]
    /usr/bin/cataclysm(_ZN15player_activity7do_turnER6player+0x146e) [0x55c9b7ba64fe]
    /usr/bin/cataclysm(_ZN4game16process_activityEv+0x4b) [0x55c9b70c395b]
    /usr/bin/cataclysm(_ZN4game7do_turnEv+0x1bb8) [0x55c9b7135b88]
    /usr/bin/cataclysm(main+0x1178) [0x55c9b6a3e488]
    /lib64/libc.so.6(__libc_start_main+0xeb) [0x7f5a854eeebb]
    /usr/bin/cataclysm(_start+0x2a) [0x55c9b6b27ffa]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:893
    DebugLog(DebugLevel, DebugClass)
    …/src/debug.cpp:1052
    std::char_traits<char>::length(char const*)
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/char_traits.h:335
    std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/ostream:571
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.cpp:293
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local() const
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:222
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:231
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:658
    void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.h:80
    item::fill_with(item const&, int)
    …/src/item.cpp:8783
    Character::pour_into(item&, item&)
    …/src/character.cpp:7594
    activity_handlers::fill_liquid_do_turn(player_activity*, player*)
    …/src/activity_handlers.cpp:1503
    activity_type::call_do_turn(player_activity*, player*) const
    …/src/activity_type.cpp:112
    player_activity::do_turn(player&)
    …/src/player_activity.cpp:278
    game::process_activity()
    …/src/game.cpp:1697
    game::process_activity()
    …/src/game.cpp:1691
    game::do_turn()
    …/src/game.cpp:1519
    main
    …/src/main.cpp:709
    __libc_start_main
    ??:?
    _start
    ??:?
Backtrace emission took 9 seconds.
(continued from above) ERROR : src/item.cpp:8783 [int item::fill_with(const item&, int)] tried to put an item (water_clean, amount 1) in a container (bottle_plastic) that cannot contain it
```

# Steps To Reproduce
Load the game and try to fill your sealed clean water bottles with more clean water from the water heater.

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-8193-g93bf48bc94-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context

[2020.12.12.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5688410/2020.12.12.zip)

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
SUMMARY: Bugfixes "Unseal source and target containers when inserting contents"

#### Purpose of change

1. Unseal source and target containers when inserting contents.
2. Fixes #46047.
3. Refactor the unsealing code to reduce repetition and properly implement #45643.

This PR mainly addresses inserting and the inventory item menu. Some code still does not handle unsealing correctly, which needs to be addressed in further PRs.

#### Describe the solution
1. Created a new class `contents_change_handler` and used it to record unsealed containers and handle them in a single batch. Used the class in places where previously `handle_contents_changed_helper` and `Character::handle_contents_changed` were used. Some non-functioning calls to `handle_contents_changed_helper::handle` in the inventory item menu were removed. They'll be fixed in follow-up PRs)
2. Fixed #46047. Added an `allow_sealed` parameter to `item::fill_with` to allow explicitly inserting into sealed containers.
3. Properly implemented #45643's fix for the incorrect handling of multiple favorited stacks of the same item type. Instead of moving the entire unsealing code to after charges are consumed, which caused items to be removed before accessed so null item pockets were returned, only call `item_pocket::unseal` to unseal the pockets and delay the call to `item_pocket::on_contents_changed` to the container handling code. (It went unnoticed because the code checked for null item pockets but didn't report with a debug message (now it does), and the preceding code happened to have already unsealed the containers)
4. Properly implemented #45643's fix for restacking item when favoriting items from the inventory item menu. Instead of calling `handle_contents_changed_helper::handle` when favoriting an item, which caused the container of the favorited item to be unsealed, find the item pocket and call `item_pocket::restack` directly.
5. Removed the handling call after `o`pening container inventory from the inventory item menu. The menu should not restack items after returning, because the player might have opened another inventory item menu and started an activity which needs the items to stay in their original stacks.

#### Testing
1. Spawned a gallon jug and a sealed plastic bottle of water, inserted the water into the jug and the plastic bottle was unsealed.
2. Made a partially filled sealed gallon jug using the item editor in mapgen debug menu, and successfully inserted another charge. The jug was unsealed and no debug message was displayed.
3. Ran the `unseal_and_spill` unit test and it passed.
4. Activated water in a sealed plastic bottle from the inventory item menu and the bottle was unsealed.
5. Made a sealed gallon jug containing a platinum ring, wore/wielded/threw the ring from the inventory item menu, and the jug was unsealed.
6. Dropped water from a sealed plastic bottle from the inventory item menu/multidrop menu and the bottle was unsealed.
7. Followed the steps in #45643, the game did not crash, and single stack or multiple stacks of favorite items were correctly dropped.
8. Favorited 5 bandages using the inventory item menu while there are already 5 favorited bandages in inventory, and the bandages were restacked.
9. Ate clam chowder from a sealed tin can from the inventory item menu/consume menu, and the can was unsealed and spilled. If consumption was canceled (due to being full, for example) the can was not unsealed nor spilled.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -1080,18 +1080,22 @@ bool item::merge_charges( const item &rhs )
...
-    ret_val<bool> result = contents.insert_item( payload, pk_type );
+    ret_val<item_pocket *> result = contents.insert_item( payload, pk_type );
     if( !result.success() ) {
         debugmsg( "tried to put an item (%s) count (%d) in a container (%s) that cannot contain it: %s",
                   payload.typeId().str(), payload.count(), typeId().str(), result.str() );
     }
     if( pk_type == item_pocket::pocket_type::MOD ) {
         update_modified_pockets();
     }
+    if( unseal_pockets ) {
```
Comment (Qrox) [inline src/item.cpp:1094]:
```suggestion
    if( unseal_pockets && result.success() ) {
```

File: src/item.cpp [hunk 2]
```diff
@@ -1080,18 +1080,22 @@ bool item::merge_charges( const item &rhs )
...
+        result.value()->unseal();
+    }
     on_contents_changed();
-    return result;
+    return ret_val<bool>::make_success( result.str() );
```
Comment (Qrox) [inline src/item.cpp:1098]:
```suggestion
    if( result.success() ) {
        return ret_val<bool>::make_success( result.str() );
    } else {
        return ret_val<bool>::make_failure( result.str() );
    }
```
