### PR TITLE
Make profession choice affect points again

### LINKED ISSUE #39208: Profession choice not effecting points
# Describe the bug
Choosing a different profession when making a new character doesn't give/cost any points
# Steps To Reproduce
1. Start new game with a custom character
2. Be a blackbelt for free
3. Be a tweaker for no reason
# Expected behavior
professions should have different point costs
# Versions and configuration
all default, latest experimental
# Additional context
wasn't present in the recent stable

### PR DESCRIPTION
**Pull request by Qrox**
#### Summary
SUMMARY: None

#### Purpose of change
Fixes #39208. Thanks to @ZhilkinSerg for pinpointing the issue.

#### Describe the solution
Calculate point difference before changing the profession.

#### Testing
Tested by selecting different professions and the points now changes correctly.

### CODE REVIEW

File: src/newcharacter.cpp [hunk 1]
```diff
@@ -1596,11 +1596,11 @@ tab_direction set_profession( avatar &u, points_left &points,
             for( const trait_id &old_trait : u.prof->get_locked_traits() ) {
                 u.toggle_trait( old_trait );
             }
+            const int netPointCost = sorted_profs[cur_id]->point_cost() - u.prof->point_cost();
```
Comment (ZhilkinSerg) [inline src/newcharacter.cpp:1599]: I don't know how I managed to do that, so I can't tell you specific reproduce steps yet, but `sorted_profs` was empty for me once and app crashed on this line trying to access `point_cost()`.

Maybe we better guard this with `!sorted_profs.empty()` (and fallback to 0 if it is empty)?

Comment (Qrox) [reply src/newcharacter.cpp:1599]: I think this can happen when the profession list is empty due to filtering and the screen is refreshed before the "no result" popup is closed. I'll look into it.

Comment (ZhilkinSerg) [reply src/newcharacter.cpp:1599]: Could be a profession blacklist thing probably (DSA mode [has them](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/data/mods/Dark-Skies-Above/overrides/scenarios.json)) - after you switch mods loaded data should be cleared, but it is not always the case (#30242). Maybe profession blacklists are not restored to normal after you start with vanilla, after you've started with the mod, so profession list becomes empty.

Comment (Qrox) [reply src/newcharacter.cpp:1599]: `DynamicDataLoader::unload_data` already calls `scenario::reset` though, which calls `generic_factory<scenario>::reset`, so I'm not sure how that would happen.
