### PR TITLE
Fix crash when reloading with items not in the inventory

### LINKED ISSUE #42089: Reloading makeshift arc welder crashes game
# Describe the bug

Reloading a newly created "Makeshift arc welder" is crashing my game hard (segfault)

# Steps To Reproduce

Haven't tried to reproduce from scratch, but can attach save file.

1. Load save file
2. Note that Makeshift arc welder is wielded
3. Move: SW, W, W, W
4. Press "r" to reload wielded welder
5. Pick any battery

CRASH

# Expected behavior

Expect to be able to reload arc welder

# Screenshots

n/a

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-4045-g350a9a9860 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    DinoMod [DinoMod],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

# Additional context

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4912280/debug.log)
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/4912277/crash.log)
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4912304/save.zip) <-- ZIP is actually a 7z file, Github no like that file extension so :shrug: 

Built from 4a20b0aa83

### PR DESCRIPTION
**Pull request by UrbanCMC**
#### Summary

SUMMARY: Bugfixes "Fixes a crash when reloading with items not in the inventory"

#### Purpose of change

Fixes #42089 which describes a crash whenever an item is reloaded from a stack outside of the inventory, as long as that stack contains at least 2 items.

#### Describe the solution

As documented in the issue, the `reload` function deletes the original `ammo` item, which is then checked for different flags.

To avoid this, the required checks are now done while the item still exists.

#### Testing

Spawn weapons and reloadable tools and their respective ammunition, with all ammunition in a pile on the ground.
Check that reloading doesn't cause a crash.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -2042,14 +2042,16 @@ void activity_handlers::reload_finish( player_activity *act, player *p )
     item &ammo = *act->targets[ 1 ];
     std::string reloadable_name = reloadable.tname();
     std::string ammo_name = ammo.tname();
```
Comment (Qrox) [inline src/activity_handlers.cpp:2044]: Adding a comment to explain why these values are stored here would be a good idea, so no one tries to "simplify" the code by moving these checks back to the if statements in the future.
