### PR TITLE
Let fire spread to tiles with items (#35824)

### LINKED ISSUE #35824: Fire does not spread while on the ground
# Describe the bug

When placing a body or pile of bodies on the floor outside on multiple adjacent tiles, and then applying wood underneath them, lighting one pile of wood does not spread the fire to the adjacent tiles.

When approaching a fungal tower and lighting the fungal bed on fire, or a fungal stalk, the fire does not spread to adjacent tiles.

# Steps To Reproduce

1. Start a world.
2. Kill zombies/find tower
3. Get lighter
4. Light a fire on desired object
5. Fire does not spread beyond the tile you set on fire, said fire goes out when the fuel is exhausted.

# Expected behavior

Fires used to spread to adjacent, burnable tiles and objects. When lighting multiple corners of a fungal bed in clear weather, I expect it to spread to adjacent tiles.

Fires used to be a good way to dispose of rotting bodies, the fires easily spread to other piles of wood nearby and burned the corpses and things I wanted to trash.

This makes sense because fire should spread to nearby burnable objects, especially when the fire becomes 'raging'.

# Screenshots

[Here is the fire at 'raging'.](https://i.gyazo.com/402e9138ecdafe80609ea61cb31b6ad6.png)
[Here are the wind conditions.](https://i.gyazo.com/5e057f590b7b17b252fd77b1dd345e3e.png)

# Versions and configuration

[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3913947/debug.log)

 - OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-9800-g248b687 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Safe Autodoc [safeautodoc],
    DeadLeaves' Fictional Guns [FIC_Weapons],
    Extended Realistic Guns [realguns],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    Medieval and Historic Classes and Shields [Medieval_Stuff],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    DinoMod [DinoMod],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Crazy Cataclysm [crazy_cataclysm],
    Mutant NPCs [mutant_npcs],
    Beta National Guard Camp [national_guard_camp],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Mapgen Demo [mapgen_demo],
    Urban Development [Urban_Development],
    Boats [boats],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Classes and Scenarios Mod [more_classes_scenarios],
    Classic Roguelike Classes [RL_Classes],
    Manual Bionic Installation [manualbionicinstall],
    Stats Through Skills [StatsThroughSkills],
    No Filthy Clothing [no_filthy_clothing],
    Sleep Deprivation [sleepdeprivation],
    Garden Pots [growable-pots],
    Mythical Martial Arts [MMA],
    Alternative Map Key [alt_map_key],
    C.R.I.T Expansion Mod [crt_expansion],
    Hydroponics [hydroponics],
    Necromancy [necromancy],
    Bionic Slots [cbm_slots],
    SpeedyDex [speedydex],
    Magiclysm [magiclysm],
    No Rail Stations [No_Rail_Stations],
    Roadheader and other mining vehicles [Heavy miners],
    Stats Through Kills [stats_through_kills],
    Fuji's Military Profession Pack [fuji_mpp]

# Additional context

It used to work, now it doesn't. I am just confused as to why. It probably has an easy fix, but I have tried to reload my game, I have tried to change the wind direction through the debug menu, none of it works.

This persists across saves.

### PR DESCRIPTION
**Pull request by satheon49**
#### Summary

SUMMARY: Bugfixes "Allow fire to spread to adjecent tiles with items"

#### Purpose of change

Fixes #35824

Fire could not spread to adjacent tiles if those tiles were neither flammable nor contained flammable furniture.

#### Describe the solution

The problem was that either flammable terrain or flammable furniture had to be true for fire to be allowed to spread.
```
            ( can_spread && rng( 1, 100 ) < spread_chance &&
------>           ( dster.is_flammable() || dsfrn.is_flammable() ) && <-----------
                ( in_pit == ( dster.id.id() == t_pit ) ) &&
                (
                    ( power >= 3 && cur.get_field_age() < 0_turns && one_in( 20 ) ) ||
                    ( power >= 2 && ( ter_furn_has_flag( dster, dsfrn, TFLAG_FLAMMABLE ) && one_in( 2 ) ) ) ||
                    ( power >= 2 && ( ter_furn_has_flag( dster, dsfrn, TFLAG_FLAMMABLE_ASH ) && one_in( 2 ) ) ) ||
                    ( power >= 3 && ( ter_furn_has_flag( dster, dsfrn, TFLAG_FLAMMABLE_HARD ) && one_in( 5 ) ) ) ||
                    nearwebfld || ( dst.get_item_count() > 0 &&
                                    flammable_items_at( p + eight_horizontal_neighbors[i] ) &&
                                    one_in( 5 ) )
                ) )
```
The solution was to check for either flammable terrain, flammable furniture OR flammable items. 

#### Describe alternatives you've considered

Checking terrain, furniture, items OR nearwebfld. Currently there needs to be something stuck in the web for it to catch fire.

If you have a raging fire it spreads fast like REALLY fast. Maybe the one_in( 5 ) check should be increased a bit. Maybe it is a relic from the time when turns where 6 seconds.

#### Testing

1. Spawn 100 splintered woods and 10 planks and light them on fire.
2. Place a few flammable items next to the fire.
2. As soon as the fire reaches intensity 3 (raging) (about 10min waiting) it will start to spread to adjacent tiles

### CODE REVIEW

File: src/map_field.cpp [hunk 1]
```diff
@@ -1335,17 +1337,18 @@ bool map::process_fire_field_in_submap( maptile &map_tile, const tripoint &p, fi
             // Allow weaker fires to spread occasionally
             const int power = cur.get_field_intensity() + one_in( 5 );
             if( can_spread && rng( 1, 100 - windpower ) < spread_chance &&
-                ( dster.is_flammable() || dsfrn.is_flammable() ) &&
+                ( dster.is_flammable() ||
+                  dsfrn.is_flammable() ||
+                  ( dst.get_item_count() > 0 &&
+                    flammable_items_at( p + eight_horizontal_neighbors[i] ) &&
```
Comment (Aivean) [inline src/map_field.cpp:1343]: Please put call to `one_in( 5 )` before `flammable_items_at(...)` , as `flammable_items_at` is much more expensive than `one_in`. 

Also, could you please profile fire spreading in large area before and after the change? I'm a bit concerned about performance.

Comment (satheon49) [reply src/map_field.cpp]: Sure. I just wanted to change as little as possible from original code to avoid introducing any new problems. I will reorder the on_in( 5 ) though since it is part of the changed lines anyway.

I believe there might be other optimizations possibilities within process_fire_field_in_submap for example:
- reordering any && so likeliest to fail is first (see l1350-1352
- reordering any || so likeliest to succeed is first
- looking into whether flammable furniture/terrain has even to be checked again at that point since it was already given a chance to spread in a prior loop
- having nearwebfld next to terrain/furniture/flammable items check because I am increasingly certain that it should be there
...
However I would like to keep those potential optimizations separate from this PR since they might break something and need to be thoroughly tested.

**Comment by Aivean** [comment]
I found the PR that changed fire spreading behavior: #32143. 
The `( dster.is_flammable() || dsfrn.is_flammable() )` line was added to prevent the fire spreading through the non-flammable walls.

I believe the condition would be a bit more readable in the following way (with lines that caused the bug removed):
```cpp
           if( can_spread && rng( 1, 100 ) < spread_chance &&
                ( in_pit == ( dster.id.id() == t_pit ) ) &&
                (
                    ( power >= 2 && ( ter_furn_has_flag( dster, dsfrn, TFLAG_FLAMMABLE ) && one_in( 2 ) ) ) ||
                    ( power >= 2 && ( ter_furn_has_flag( dster, dsfrn, TFLAG_FLAMMABLE_ASH ) && one_in( 2 ) ) ) ||
                    ( power >= 3 && ( ter_furn_has_flag( dster, dsfrn, TFLAG_FLAMMABLE_HARD ) && one_in( 5 ) ) ) ||
                    nearwebfld ||
                    ( one_in( 5 ) && dst.get_item_count() > 0 &&
                      flammable_items_at( p + eight_horizontal_neighbors[i] ) )
                ) ) {
...
```

**Comment by satheon49** [comment]
I am confused. How could the fire spread through walls before? At least at the moment it only checks the 8 neighboring tiles and if they were non flammable/non webbed walls and didn't have items (which they couldn't have) they wouldn't burn. Or were more tiles allowed as spread targets before?

Let me check whether removing this line will reintroduce the behavior shown in the PR. It shouldn't as far as I understand the code. If it still works I will update the PR and remove `( dster.is_flammable() || dsfrn.is_flammable() )`.

The change would also allow webs to catch fire again without having anything flammable (at a later point we might also want to look into not checking for webs but rather FLAMMABLE flag on field_types).

**Comment by Aivean** [comment]
@satheon49 , sorry, in the code above I also sneakily removed this line: `( power >= 3 && cur.get_field_age() < 0_turns && one_in( 20 ) ) ||`.  I believe this line was the cause of the fire spreading through walls. 

I think this line could be safely removed (it's effect on fire spreading chance is negligible) and, along with removing `( dster.is_flammable() || dsfrn.is_flammable() )` it should make the fire spreading logic more concise and readable.

**Comment by satheon49** [comment]
Thanks for the explanation but I think it would prevent forest fires (I guess smokey bear approves). I would rather add a check for WALL: `( power >= 3 && cur.get_field_age() < 0_turns && one_in( 20 ) && !dster.has_flag( TFLAG_WALL ) )`. 

Flammable walls will already spread fire anyway similar to fungus so this change would just prevent non-flammable walls from spreading fire.

**Comment by Aivean** [comment]
> Thanks for the explanation but I think it would prevent forest fires (I guess smokey bear approves) since it would not allow fire to slowly crawl over open ground. I would rather add a check for WALL: ( power >= 3 && cur.get_field_age() < 0_turns && one_in( 20 ) && !dster.has_flag( TFLAG_WALL ) ).

That's an interesting point. However, I think that this change would be adding *new* behavior to the fire spreading. Note, previously, because of the `( dster.is_flammable() || dsfrn.is_flammable() )` condition, `( power >= 3 && cur.get_field_age() < 0_turns && one_in( 20 ) )` only applied to the flammable terrain, so either forest fires were not working or they were using different mechanism. 

I'm not against that change, but I think that it would be better done as a separate PR.

**Review by Aivean — APPROVED** [review]

File: src/map_field.cpp (hunk 1 above)
Comment (Aivean) [reply src/map_field.cpp]: Please mark this as resolved.

**Comment by anothersimulacrum** [comment]
Just a note of confirmation that it works
fire

If you're willing, it'd be a good idea to encode this in a test case, but that is far from something that you need to do here.

**Comment by satheon49** [comment]
Maybe once we decide to make further changes to fire like
- having FLAMMABLE field type instead of just a hardcoded web check
- preventing WALL from spreading fire but allowing open ground if the source fire can maintain it

Though to be totally honest I am not exactly keen on writing them (but that might change if I can teach my IDE to run single tests and be able to jump to failing tests like I am used to from non C++ projects).

**Comment by Aivean** [comment]
> * having FLAMMABLE field type instead of just a hardcoded web check

"Unhardcoding" things is always welcome.

> * preventing WALL from spreading fire but allowing open ground if the source fire can maintain it

I think this is a good idea, but it would require rigorous testing, as it could change the fire behavior in unexpected ways.

----

Also, thank you for contributing. 

If I could be of any help with anything, feel free to ping me here or on the discord.

**Comment by kevingranade** [comment]
I'm not particularly interested in solving the forest fire use case right now, forest fires propagate via completely different mechanisms compared to small campfire like things like we're discussing, and attempting to force "out of control campfires" to be able to jump multiple meters is more likely to cause more local problems.

In short, I think the "fires can exist on a tile that has no fuel" feature is actively counterproductive to making fires work correctly.

Forest fires primarily propagate via burning underbrush, which our system handles just fine, but also by irradiance once the fire becomes large enough.  Essentially a fully engulfed tree is putting out enough IR to dry out and then trigger fires in adjacent trees.  We could certainly look into an effect like that, but random single-tile fires shouldn't be triggering that kind of check because it's super expensive.

**Comment by satheon49** [comment]
> In short, I think the "fires can exist on a tile that has no fuel" feature is actively counterproductive to making fires work correctly.

I just pointed out that this PR will actually remove a feature that existed in the past. The timeline was like that:
- fire could spread to adjacent tiles without fuel
- this also allowed fires to spread through walls which was fixed in #32143 but broke fires spreading to flammable items, webs and empty ground
- this PR fixes fires spreading to tiles with flammable items and webs but removes the ability to spread to empty ground

I am not even sure I want forest fires because they are unlikely to ever stop once they get going.

**Comment by Aivean** [comment]
To be clear, in the current state this PR fixes fire spreading to the tiles with flammable items. It doesn't add nor remove fire spreading to the empty tiles and walls (but it does remove code remnants of that from before #32143 ).

I think this is ready and good to be merged.

**Comment by kevingranade** [comment]
Tested against a pile of "one of every item in the game".
Screenshot from 2020-12-13 15-24-36
#thisisfine
