### PR TITLE
Fix NPC reload

### LINKED ISSUE #15397: NPC's not using ranged weapons
Commit 0.C-10705-g16a9b72
(i think i built it during last week sometime. Friday 12/2 maybe?)

So.. no NPC has yet managed to use his ranged weapon against me... Faced one with a glock, another with a bow and another with a flamethrower... They turned hostile after me refusing to drop weapon.
I'd be dead if not for that bug..

### LINKED ISSUE #15508: NPC can't reload - so his brain explodes
Running latest experimental 4374.
Issue happens a lot when I'm at the refugee center and a zombie gets inside.
NPC wielding a ranged weapon will attempt to fire at the zombie, but can't reload.
The following message appears:DEBUG: NPC_REload Failed: No usable ammo
The NPC's brain then explodes.
[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/139782/save.zip)
explosion

### PR DESCRIPTION
**Pull request by Coolthulhu**
Allows NPCs to reload items with magazines and with charges.

Closes #15397
Closes #15508

Doesn't let them reload magazines yet.

EDIT: Removed a badly handled default argument in `item::reload` - the `qty` argument has to be strictly positive, while the default argument was `-1`.

### CODE REVIEW

File: src/npcmove.cpp [hunk 1]
```diff
@@ -346,27 +346,17 @@ void npc::execute_action( npc_action action )
...
-        if( ammo.empty() ) {
+        if( !usable_ammo ) {
             debugmsg( "npc_reload failed: no usable ammo" );
             break;
         }
 
-        int reload_time = item_reload_cost( weapon, *ammo[0] );
+        int reload_time = item_reload_cost( weapon, *usable_ammo );
 
-        if( !weapon.reload( *this, std::move( ammo[0] ) ) ) {
```
Comment (mugling) [inline src/npcmove.cpp]: This was the only usage of the default argument for `qty`?

Comment (Coolthulhu) [inline src/npcmove.cpp]: I think so. After I removed the default argument, I didn't need to change anything else.

Comment (mugling) [inline src/npcmove.cpp]: With the exception of the unit tests (which could do with reworking in any case)
