### PR TITLE
Fix check for available wheels when changing tires

### LINKED ISSUE #28333: Cannot change wheel (wheel not detected by `has_components()`?)
**Describe the bug**  

Even if all tools/components are present, changing wheels (tires) is impossible, because the inventory does not detect presence of relevant vehicle part.

**To Reproduce**  

0. (NOTE: savegame provided below)
1. Stand next to a bicycle (light vehicle - no need for jack).
2. Have a multi-tool and appropriate-size wheel.
3. `e`xamine vehicle.
4. `c`hange tire on appropriate tile.
5. Observe wheel displayed in red.

**Expected behavior**  

Wheel is detected in inventory and action is permitted.

**Screenshots**  

N/A

**Versions and configuration:**
 - OS: Arch Linux 64-bit
 - Game Version: `0.C-37535-g60ad4a4a0e` (commit 60ad4a4a0e4140b0329e53c65d1e7309cb991a15)
 - Graphics version: Terminal
 - Mods loaded: vanilla

**Additional context**  

This happens on all vehicles I've tried, not just bicycles.

Tried last merge commit before PR #28114 - same issue. Did not attempt bisect.

-----

[vanilla.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2897045/vanilla.zip)

### PR DESCRIPTION
**Pull request by ifreund**
#### Summary
```SUMMARY: Bugfixes "Fix check for available wheels when changing tires."```

#### Purpose of change
Fixes  #28333.

#### Describe the solution
Allow passing "any" to `amount_of` to find all items.  When used in conjunction with a filter this can be used to find the the number of items that match a pattern, even if they have different types.

Use this functionality to replace the incomplete hardcoded list of wheels.

### CODE REVIEW

File: src/veh_interact.cpp [hunk 1]
```diff
@@ -375,12 +375,7 @@ void veh_interact::cache_tool_availability()
 
     has_wrench = crafting_inv.has_quality( quality_id( "WRENCH" ) );
 
-    has_wheel = crafting_inv.has_components( "wheel", 1 ) ||
-                crafting_inv.has_components( "wheel_wide", 1 ) ||
-                crafting_inv.has_components( "wheel_armor", 1 ) ||
-                crafting_inv.has_components( "wheel_bicycle", 1 ) ||
-                crafting_inv.has_components( "wheel_motorbike", 1 ) ||
-                crafting_inv.has_components( "wheel_small", 1 );
+    has_wheel = crafting_inv.has_components( "any", 1, []( const item & it ){ return item::find_type( it.typeId() )->wheel ? true : false; } );
```
Comment (AMurkin) [inline src/veh_interact.cpp]:
```suggestion
    has_wheel = crafting_inv.has_components( "any", 1, []( const item & it ){ return item::find_type( it.typeId() )->wheel; } );
```

Comment (ifreund) [reply src/veh_interact.cpp]: the return type would then be `cata::optional<islot_wheel>` instead of bool.  It doesn't want to implicitly cast for some reason in this case.

Comment (AMurkin) [reply src/veh_interact.cpp]: !! it then?

Comment (ifreund) [reply src/veh_interact.cpp]: Oh yeah that would be nicer.
