### PR TITLE
Fix scaling factor for high-dpi displays

### LINKED ISSUE #83682: Improper scaling factor on high-dpi and Apple Retina displays
### Describe the bug

When adjusting the scaling factor to `2x` or `4x`, the game's math fails to account for the difference between logical and physical pixels. This means that high-dpi and Apple Retina displays are forced to use much smaller text and sprite sizes than are necessary.

My PR fixes this discrepancy here
- #83631 

### Attach save file

N/A

### Steps to reproduce

1. Change scaling factor to `2x` or `4x` on a high-dpi display
2. Reload
3. Despite in most cases fitting, the config change fails and reverts to `1x` 

### Expected behavior

The font and sprite sizes should be larger

### Screenshots

_No response_

### Versions and configuration

All depends on hardware, every version of DDA

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rachel-bousfield**
#### Summary
Bugfixes "Fix the scaling factor for high-dpi displays."

#### Purpose of change

The number of pixels returned by `SDL_GetWindowSize` do not take into account dpi scaling, like on Apple Retina displays. Thankfully SDL 2.26 (Nov 2022) provides a `SDL_GetWindowSizeInPixels` for accounting for exactly this.

Additionally, even in full screen mode the dimensions of `SDL_DisplayMode` are incorrect due to `SDL_GetDesktopDisplayMode` similarly not factoring in dpi scale.

#### Describe the solution

Switch to `SDL_GetWindowSizeInPixels` and implement a new `get_display_scale` function for measuring the dpi scaling ratios. The measurement creates a small, hidden window to quickly measure the horizontal and vertical stretch necessary to account for dpi. On failure the return values are 1x, ensuring no logical change.

#### Describe alternatives you've considered

One could perhaps imagine a larger refactor where we always perform window measurements, but even in this case we'd want precisely the same affordance provided by `get_display_scale`. This keeps things minimal and known to not break other platforms.

#### Testing

I've tested this on my MacBook in each mode, though given it's backend agnostic it should work cross-platform. A friend has also on Windows and I'll soon be on Linux with an intentionally out-dated SDL version too.

**EDIT:** Confirmed it works on Linux with and without old versions of SDL (pre 2022)

#### Additional context

None

Resolves #83682

### CODE REVIEW

**Comment by rachel-bousfield** [comment]
Apologies, it's my first time contributing. Feel free to change what this points against. The code in question hasn't changed in many years so it shouldn't matter

**Comment by rachel-bousfield** [comment]
Tested to confirm this works on Linux both with and without outdated (pre 2022) versions of SDL2

File: src/sdltiles.cpp [hunk 1]
```diff
@@ -3624,6 +3624,38 @@ int projected_window_height()
     return get_option<int>( "TERMINAL_Y" ) * fontheight;
 }
 
+// Measures scaling factor for high-dpi displays
+static std::pair<float, float> get_display_scale( int display_index )
+{
+#if SDL_VERSION_ATLEAST(2,26,0)
+    int x = SDL_WINDOWPOS_CENTERED_DISPLAY( display_index );
+    int y = SDL_WINDOWPOS_CENTERED_DISPLAY( display_index );
```
Comment (ehughsbaird) [inline src/sdltiles.cpp:3634]: You should silence clang-tidy for this error, it's not relevant here.
```suggestion
    // NOLINTNEXTLINE(cata-combine-locals-into-point)
    int x = SDL_WINDOWPOS_CENTERED_DISPLAY( display_index );
    // NOLINTNEXTLINE(cata-combine-locals-into-point)
    int y = SDL_WINDOWPOS_CENTERED_DISPLAY( display_index );
```

File: src/sdltiles.cpp [hunk 2]
```diff
@@ -3624,6 +3624,38 @@ int projected_window_height()
...
+                        16, 16,
+                        SDL_WINDOW_HIDDEN | SDL_WINDOW_ALLOW_HIGHDPI
+                    );
+    if( !w ) {
+        return std::make_pair( 1.0f, 1.0f );
+    }
+
+    int lw, lh;
+    SDL_GetWindowSize( w, &lw, &lh );
+    int pw, ph;
```
Comment (ehughsbaird) [inline src/sdltiles.cpp]: Clang-tidy wants these declared on separate lines.

I'd prefer to initialize them in case the GetWindowSize call fails, so we know the check below using them will return `1.f, 1.f`. The SDL documentation doesn't describe what happens to them if it fails (but I expect the answer is GetWindowSize doesn't _really_ fail).
```suggestion
    int lw = 0;
    int lh = 0;
    SDL_GetWindowSize( w, &lw, &lh );
    int pw;
    int ph;
```

Comment (rachel-bousfield) [reply src/sdltiles.cpp]: Makes sense, adopted your feedback :)

**Comment by harakka** [comment]
Any chance you could give some reproduction steps to testing this on Linux? Eg. what settings to have to get the problem to show without your changes. I tried this on KDE+wayland with desktop scaling set to 175% and in-game scaling set to 2x and don't see any difference.

On the plus side, I can confirm the game still renders as before with these changes :sweat_smile:

**Comment by rachel-bousfield** [comment]
@harakka The bug happens when the following are true

1. Your desktop environment makes `SDL_GetWindowSize` return a smaller number of pixels than the display contains. This is usually due to high-dpi displays like Apple Retina where for example my `2560 px` display returns `1280 px`
2. Your `Display Scaling Factor` option under the in-game `Graphics` settings tab is `2x` or `4x` and just barely would fit

The game will then essentially check if there's enough space for the tile size. So in my case it'll think the answer is "no" since on an `1280 px` display there wouldn't be enough tiles. But in actuality there's plenty of space since I actually have twice as many pixels.

Here's a screenshot at the `1x` configuration:
Screenshot 2025-11-09 at 11 33 10 AM

Here it is in my PR at `2x`
Screenshot 2025-11-09 at 11 33 56 AM

On `master` the check fails and instead shows the same result as `1x`, overwriting my settings permanently to `1x`. Yet as you can see in the `2x` picture things look reasonable. I can navigate menus, play the game, etc exactly as normal

**Comment by akrieger** [comment]
Does this need to be back ported to 0.I?

**Comment by kevingranade** [comment]
It seems like a good candidate

**Comment by akrieger** [comment]
More like I don't remember when the relevant scaling/dpi handling code went in, if it was before or after the cut.

**Comment by akrieger** [comment]
I was thinking of https://github.com/CleverRaven/Cataclysm-DDA/pull/81139. But maybe this PR is unconditionally useful.
