### PR TITLE
Fix compiler error

### LINKED ISSUE #18639: Broken build #5634
As of merging https://github.com/CleverRaven/Cataclysm-DDA/pull/18399 Jenkins has failed half the builds due to:

`src/pickup.cpp:52:10: error: declaration of 'item item_idx::item' [-fpermissive]
     item item;
          ^
In file included from src/inventory.h:5:0,
                 from src/character.h:6,
                 from src/player.h:4,
                 from src/pickup.cpp:5:
src/item.h:113:7: error: changes meaning of 'item' from 'class item' [-fpermissive]
 class item : public JsonSerializer, public JsonDeserializer, public visitable<item>
       ^`

For what it's worth the PR that triggered it compiled and ran (Windows curses/tiles) fine when I tested it. This error is beyond my ability to fix, but I'm holding off on simply reverting it (that UI update is pretty awesome) in case the fix is something that's simple for a person with more knowledge than myself.

### PR DESCRIPTION
**Pull request by OzoneH3**
```
src/pickup.cpp:52:10: error: declaration of ‘item item_idx::item’ [-fpermissive]
     item item;
          ^
src/item.h:113:7: error: changes meaning of ‘item’ from ‘class item’ [-fpermissive]
 class item : public JsonSerializer, public JsonDeserializer, public visitable<item>
       ^

```

Closes #18639

### CODE REVIEW

File: src/pickup.cpp [hunk 1]
```diff
@@ -927,7 +927,7 @@ void Pickup::pick_up( const tripoint &pos, int min )
                 units::volume volume_picked_up = 0;
                 for( size_t i = 0; i < getitem.size(); i++ ) {
                     if( getitem[i].pick ) {
-                        item temp = stacked_here[i].begin()->item;
+                        item temp = stacked_here[i].begin()->_item;
```
Comment (codemime) [inline src/pickup.cpp]: Here's another one `item temp`.

**Comment by Rivet-the-Zombie** [comment]
Seems to compile and runs fine without a complaint. If I can get an additional verification of this (the build that broke compiled fine and ran for me as well, so I'm hesitant to merge it on the basis of my own testing alone) I'll merge it right away!

**Comment by OzoneH3** [comment]
It's weird because on another machine the clang didn't complain, on this one it does...

**Comment by codemime** [comment]
Different versions?

> If I can get an additional verification of this 

The fix look OK. I can try to compile it using `Clang 3.6` and `g++ 4.9.2` on Linux (if it would suffice).

**Comment by OzoneH3** [comment]
> Different versions?

Nevermind, was using gcc here, clang works fine as well.

**Comment by Rivet-the-Zombie** [comment]
Glad to hear it! Let's keep our fingers crossed.

File: src/pickup.cpp [hunk 2]
```diff
@@ -49,7 +49,7 @@ struct pickup_count {
 };
 
 struct item_idx {
-    item item;
+    item _item;
```
Comment (mugling) [inline src/pickup.cpp]: Does this fall foul of the reserve C/C++ identifier rules?
