### PR TITLE
Fix range-loop-analysis (clang 12)

### LINKED ISSUE #45653: many range-loop-analysis errors on clang 12
Can't build Cataclysm-DDA after update to macOS Big Sur.

When compiling the first file, an error occurs:
```
In file included from src/achievement.cpp:15:
src/generic_factory.h:307:34: error: loop variable 'e' is always a copy because the range of type
      'JsonArray' does not return a reference [-Werror,-Wrange-loop-analysis]
                for( const auto &e : jo.get_array( legacy_id_member_name ) ) {
                                 ^
src/achievement.cpp:404:25: note: in instantiation of member function
      'generic_factory<achievement>::load' requested here
    achievement_factory.load( jo, src );
                        ^
src/generic_factory.h:307:22: note: use non-reference type 'JsonValue'
                for( const auto &e : jo.get_array( legacy_id_member_name ) ) {
                     ^~~~~~~~~~~~~~~
```
After the fix, the following appears:
```
src/activity_item_handling.cpp:2870:25: error: loop variable 'loc' of type 'const tripoint' creates a
      copy from type 'const tripoint' [-Werror,-Wrange-loop-analysis]
    for( const tripoint loc : dest_set ) {
                        ^
src/activity_item_handling.cpp:2870:10: note: use reference type 'const tripoint &' to prevent copying
    for( const tripoint loc : dest_set ) {
         ^~~~~~~~~~~~~~~~~~~~
                        &
```
After correcting this - the following:
```
src/armor_layers.cpp:655:32: error: loop variable 'cover' of type 'const bodypart_id' (aka
      'const int_id<body_part_type>') creates a copy from type 'const bodypart_id'
      [-Werror,-Wrange-loop-analysis]
        for( const bodypart_id cover : armor_cat ) {
                               ^
src/armor_layers.cpp:655:14: note: use reference type 'const bodypart_id &' (aka
      'const int_id<body_part_type> &') to prevent copying
        for( const bodypart_id cover : armor_cat ) {
             ^~~~~~~~~~~~~~~~~~~~~~~~~
                               &
src/armor_layers.cpp:667:32: error: loop variable 'cover' of type 'const bodypart_id' (aka
      'const int_id<body_part_type>') creates a copy from type 'const bodypart_id'
      [-Werror,-Wrange-loop-analysis]
        for( const bodypart_id cover : rl ) {
                               ^
src/armor_layers.cpp:667:14: note: use reference type 'const bodypart_id &' (aka
      'const int_id<body_part_type> &') to prevent copying
        for( const bodypart_id cover : rl ) {
             ^~~~~~~~~~~~~~~~~~~~~~~~~
                               &
```
I did not check further. But I think that even with the letter `a` there will be more errors.
# Steps To Reproduce
Just `make`:
```
make -B -j4 app NATIVE=osx OSX_MIN=11.0.1 RELEASE=1 TILES=1 CLANG=1 USE_HOME_DIR=1 SOUND=1 LANGUAGES="ru"
```
`clang --version`:
```
Apple clang version 12.0.0 (clang-1200.0.32.27)
Target: x86_64-apple-darwin20.1.0
```
# Expected behavior
Is there any way to automate this fixes (it's pretty trivial)?
Maybe show the entire list of errors, and not stop after each.

Is it possible to disable `-Wrange-loop-analysis`?

# Versions and configuration
macOS Big Sur 11.0.1
Clang 12.0.0

### PR DESCRIPTION
**Pull request by akirashirosawa**
#### Summary
SUMMARY: None
#### Purpose of change
Fix #45653
#### Describe the solution
Just following the instructions of clang, I added or removed `&` to the loop variables.
#### Describe alternatives you've considered
Do something less mechanical and more consciously.
#### Testing
The project compiles, the game starts and runs fine. 
`All tests passed (3473533 assertions in 611 test cases)`
#### Additional context
The tests are passed much faster. Maybe because of clang 12, maybe because of code optimizations that I did not pay attention to.

### CODE REVIEW

**Comment by CAHEK7** [comment]
The code may became faster because of added references instead of copying, but for gcc-9 it seems negligible: 89.0s vs 88.5s, mostly looks like random fluctuations.
I guess either clang performs much better than gcc or there was a baseline without optimizations at all or something OS specific happened.

File: src/generic_factory.h [hunk 1]
```diff
@@ -304,7 +304,7 @@ class generic_factory
                 }
 
             } else if( jo.has_array( legacy_id_member_name ) ) {
-                for( const auto &e : jo.get_array( legacy_id_member_name ) ) {
+                for( const auto e : jo.get_array( legacy_id_member_name ) ) {
```
Comment (ZhilkinSerg) [inline src/generic_factory.h:307]:
```suggestion
                for( const JsonArray e : jo.get_array( legacy_id_member_name ) ) {
```

File: src/generic_factory.h [hunk 2]
```diff
@@ -304,7 +304,7 @@ class generic_factory
                 }
 
             } else if( jo.has_array( legacy_id_member_name ) ) {
-                for( const auto &e : jo.get_array( legacy_id_member_name ) ) {
+                for( const JsonValue &e : jo.get_array( legacy_id_member_name ) ) {
```
Comment (akirashirosawa) [inline src/generic_factory.h:307]:
```suggestion
                for( const JsonValue e : jo.get_array( legacy_id_member_name ) ) {
```
```
In file included from src/achievement.cpp:15:
src/generic_factory.h:307:39: error: loop variable 'e' is always a copy because the range of type
      'JsonArray' does not return a reference [-Werror,-Wrange-loop-analysis]
                for( const JsonValue &e : jo.get_array( legacy_id_member_name ) ) {
                                      ^
src/achievement.cpp:404:25: note: in instantiation of member function
      'generic_factory<achievement>::load' requested here
    achievement_factory.load( jo, src );
                        ^
src/generic_factory.h:307:22: note: use non-reference type 'JsonValue'
                for( const JsonValue &e : jo.get_array( legacy_id_member_name ) ) {
                     ^~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [obj/tiles/achievement.o] Error 1
```
