### PR TITLE
Fix player::fire_gun when using multiple ammo units per shot

### LINKED ISSUE #15028: Unexpected shortage of ammo whilst firing flamethrower
Latest Dev build 64bit using tiles

I have found a bandit bulldozer and it has a flamethrower on it if I fire flamethrower I get this error message in red

Unexpected shortage of ammo whilst firing flamethrower

It still fires flames and kills monsters so not a big deal tbh

Thanks :)

### LINKED ISSUE #15240: Vehicle-mounted flamethrowers print debugmsg every shot
"Unexpected shortage of ammo"
Happens regardless of whether burst mode is on or off.

### LINKED ISSUE #15405: Crash when burst firing flamethrower and running out of gas mid-burst
Seems to only affect RM451.
* Load RM451 with gas
* Use up ammo until the charge count is less than 100 but more than 20
* Burst fire at a target that will survive the entire burst (say, a Debug Monster)

### PR DESCRIPTION
**Pull request by mugling**
Based upon suggestions from @BevapDin and @Coolthulhu 

Closes #15405
Closes #15028 
Closes #15240

> item::ammo_data returns null here. I suspect the code in vehicle.cpp doesn't set up the ammo data correctly.

This seems likely especially given 5348bec fixes the segfault.

### CODE REVIEW

File: src/ranged.cpp [hunk 1]
```diff
@@ -378,6 +378,10 @@ int player::fire_gun( const tripoint &target, int shots, item& gun )
         }
     }
 
+    if( shots <= 0 ) {
+        debugmsg( "Attempted to fire zero or negative shots using %s", gun.tname().c_str() );
```
Comment (Coolthulhu) [inline src/ranged.cpp]: This debugmsg still triggers.
* Spawn a vehicle
* Add flamethrower
* Add between 0 and 100 gasoline (ie. more than 0 but less than 100)
* Get debugmsg every turn the flamethrower tries to fire

**Comment by mugling** [comment]
In that case the `debugmsg` is correct as the caller is trying to invoke `player::fire_gun` with insufficient ammo. We should look further at the vehicle code as opposed to dropping the `debugmsg`
