### PR TITLE
Fix for WEBWALK flag 

### LINKED ISSUE #48639: Demon spiders' WEBWALK flag doesn't work
# Describe the bug

Demon spiders and spiderlings are stopped by webs and trigger "breaks free of web" messages.
They have WEBWALK flag though, so the problem might be somewhere in c++.

# Steps To Reproduce

Spawn special mapgen `demon_spider_lair`, lure spiders outside, watch them break webs

# Expected behavior

WEBWALK flag work properly

# Screenshots

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 2004
- Game Version: 0.E-10383-gad91f6a [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    Mythical Martial Arts [MMA],
    C.R.I.T Expansion Mod [crt_expansion],
    No Fungal Monsters [No_Fungi],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Bionic Professions [package_bionic_professions],
    Aftershock - UndeadPeople Tileset [AftershockUDP],
    Blaze Industries - UndeadPeople Tileset [BlazeIndustriesUDP],
    C.R.I.T Expansion Mod - UndeadPeople Tileset [crt_expansionUDP],
    Magiclysm - UndeadPeople Tileset [MagiclysmUDP],
    Mythical Martial Arts - UndeadPeople Tileset [MMAUDP]
]

### LINKED ISSUE #50654: WEBWALK monster flag doesn't work
### Describe the bug

Adding the `WEBWALK` monster flag to mobs doesn't confer immunity to spider webs to them, only defining them explicitly in `fd_web`'s `immune_mtypes` array does. This means a bunch of spiders are actually hampered by their own webs.

### Steps To Reproduce

1. Spawn a spider nest map extra (or web fields directly)
2. Spawn a monster with `WEBWALK` in one, observe it losing movement and destroying the webs
3. Observe it doing the same if it moves into a web (it's not only when spawned on top of one)
4. Add the same mob to the list of immune monsters and observe them passing webs without trouble

### Expected behavior

The flag that allows monsters to walk on webs allowing them to walk on webs without a problem.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows 10
- Game Version: 0.F-1169-g4cc11cc413
- Graphics version: Tiles
- Mods loaded: DDA

### Additional context

Came up while testing a monster that emits webs, said mob promptly got stuck in its own web.

### PR DESCRIPTION
**Pull request by khudson13**
Adds code to is_immune_field() for handling WEBWALK flag

#### Summary
Bugfixes "WEBWALK flag works now"

#### Purpose of change
Fixes #50654 and Fixes #48639  

#### Describe the solution
Added a couple lines to is_immune_field() within monmove.cpp. There just wasn't any code to handle the specific immunity before.

#### Describe alternatives you've considered
This was my first dive into Cata's C++ and you don't need to know how long it took me to find the relevant function. This is the only solution I could find, but as far as I can tell it's the right one.

#### Testing
I first tested the bug in the latest experimental to make sure it's properly broken. Spawned in one of those spider web forest things and a clairvoyance artifact so I could see, and watched as all the sad giant mutant spiders struggled in their own webs.

Then I compiled a new build with my new code and did the same thing there. All the spiders rushed out to kill me horribly, totally unobstructed by their own webs as hoped. Those big web areas should be substantially more dangerous now.

I specifically spawned in several different kinds of spider, including Magiclysm's Demon Spider, to make sure everyone got to come along for the horrible, spidery ride.

### CODE REVIEW

**Comment by actual-nh** [comment]
Ping: @Venera3?

File: src/monmove.cpp [hunk 1]
```diff
@@ -88,6 +88,9 @@ bool monster::is_immune_field( const field_type_id &fid ) const
     if( fid == fd_insecticidal_gas ) {
         return !made_of( material_id( "iflesh" ) ) || has_flag( MF_INSECTICIDEPROOF );
     }
+	if( fid == fd_web ) {
+		return has_flag( MF_WEBWALK );
+	}
```
Comment (actual-nh) [inline src/monmove.cpp:93]:
```suggestion
     if( fid == fd_web ) {
          return has_flag( MF_WEBWALK );
    }
```
This will hopefully resolve the astyle issue.

Comment (khudson13) [reply src/monmove.cpp]: Thank you!

File: src/monmove.cpp [hunk 2]
```diff
@@ -88,6 +88,9 @@ bool monster::is_immune_field( const field_type_id &fid ) const
     if( fid == fd_insecticidal_gas ) {
         return !made_of( material_id( "iflesh" ) ) || has_flag( MF_INSECTICIDEPROOF );
     }
+    if( fid == fd_web ) {
+          return has_flag( MF_WEBWALK );
```
Comment (actual-nh) [inline src/monmove.cpp:92]:
```suggestion
        return has_flag( MF_WEBWALK );
```
Sigh.... I guessed on the indentation there and didn't get it right - should have copied it off the line above. Re astyle, etc, you should probably take a look at doc/CODE_STYLE.md and doc/DEVELOPER_TOOLING.md.

Comment (khudson13) [reply src/monmove.cpp:92]: I'll have a look at those, thank you. I tried to make sure my new code looked like everything around it but... obviously something wasn't quite right. Thanks very much for your input!

**Review by Maleclypse — APPROVED** [review]

**Comment by Venera3** [comment]
There's an (obviously broken) bit in `map_field.cpp` that tries to handle this, I'd remove that to prevent confusion.
