### PR TITLE
Fix lag from copying players and make them noncopyable

### LINKED ISSUE #26147: Lag during inventory manipulation
**Describe the bug**  
When manipulating players inventory there is consistient half second lag on all inputs, issue is present in:
- (I)nventory
- Multi(D)rop
- (E)at

Also while opening (E)at menu huge few seconds lag takes place. 

**To Reproduce**  
Try using any of those menus, I am not sure how to reproduce it or if its present only in my games.

**Expected behavior**  
I expect no lag on inputs.

**Versions and configuration(please complete the following information):**
 - OS: Win 7
 - Game Version: 0.C-33158-gd0fe67
 - Graphics version: Tiles
 - Mods loaded: Makeshift Items,  Alternative Map Key,  Boats, Folding Parts,  Vehicle Additions
,  Tanks and Other Vehicles,  Arcana and Magic Items, No Accid Zeds(modified to remove smokers aswell)  No Flaming Weapons,  StatsThroughSkills,  Simplified Nutrition,  Book Scanner,  DeadLeaves' Fictional Guns,  Expanded Archery,  Medieval and Historic Content,  More Survival Tools,  Mythological Replicas, 
 No Freeze,  Modular Turrets,  Manual Bionic Installation,  Safe Autodoc.

**Additional context**  ``
Savefile:
https://drive.google.com/open?id=1EDNORLBhTpk7BLXuVcEAL0JCroqf4RhR

### PR DESCRIPTION
**Pull request by jbytheway**
#### Summary
SUMMARY: Bugfixes "Fix lag due to copying player objects"

#### Purpose of change
Issue #26147 described a few situations where lag was caused by copying `player` objects.  We shouldn't ever be copying player objects.  Some cases were fixed in #26272.  This deals with the rest, and fixes #26147.

#### Describe the solution
To ensure this problem is gone and cannot accidentally return, we make `player` noncopyable.  That also requires that `npc` be noncopyable.  Since it was easy, I also made `Character` noncopyable.

The remaining situations where such objects were being copied were:
* The new character screen, in order to predict recipes after skill selection.
* The wash clothes window, for no obvious reason.
* The multidrop window, in order to predict weight and volume after dropping.
* The NPC trade screen, in order to predict NPC weight and volume after trading.
* Some tests.

To resolve all these required some changes:
* Calculations of whether recipes were possible are moved into `SkillLevelMap` from `player` and `Character`.  So the new character screen can just copy that.
* Weight and volume functions get new, more flexible versions which can account for predicting weight or volume after the inventory has some change made to it.
* The tests can no longer copy a model NPC; they must create one anew each time.

As a side-effect, the wash clothes window no longer displays weight and volume at all (it served no purpose).

#### Describe alternatives you've considered
The messiest one to get working was the multidrop window.  The way it handles item stacks is fairly weird.  I suspect there's an opportunity there for further refactoring, but that would be a bigger change than seems sensible for this bugfix.

#### Additional context
This lays the groundwork for an improvement to the wash clothes window; it should be easy now to put water and soap requirements in the area where weight and volume previously were, but I don't want to do that on this PR.

### CODE REVIEW

File: src/skill.cpp [hunk 1]
```diff
@@ -217,6 +219,88 @@ bool SkillLevel::can_train() const
...
+
+int SkillLevelMap::get_skill_level( const skill_id &ident ) const
+{
+    return get_skill_level_object( ident ).level();
+}
+
+int SkillLevelMap::get_skill_level( const skill_id &ident, const item &context ) const
+{
+    auto id = context.is_null() ? ident : context.contextualize_skill( ident );
+    return get_skill_level( std::move( id ) );
```
Comment (BevapDin) [inline src/skill.cpp]: The move here is useless, the other `get_skill_level` function takes its argument as reference anyway.

File: src/character.h [hunk 2]
```diff
@@ -543,9 +543,29 @@ class Character : public Creature, public visitable<Character>
...
+        struct item_tweaks {
+            item_tweaks() = default;
+            item_tweaks( const std::map<const item *, int> &w ) :
+                without_items( &w )
+            {}
+            item_tweaks( const inventory &r ) :
+                replace_inv( &r )
+            {}
+            const std::map<const item *, int> *without_items = nullptr;
+            const inventory *replace_inv = nullptr;
```
Comment (BevapDin) [inline src/character.h]: Any reasons that this are pointers? It could be references, or `optional<T>` if you want a "not used" value.

File: src/character.h [hunk 3]
```diff
@@ -543,9 +543,29 @@ class Character : public Creature, public visitable<Character>
...
+        };
+
+        units::mass weight_carried_with_tweaks( item_tweaks ) const;
+        units::volume volume_carried_with_tweaks( item_tweaks ) const;
```
Comment (BevapDin) [inline src/character.h]: Any reason these functions take by value and not by const reference?

File: src/skill.cpp (hunk 1 above)
Comment (jbytheway) [reply src/skill.cpp]: True.  It's also harmless, and might help in the future if that function changes.  But I can see that's unlikely, so happy to change if you wish.

File: src/character.h (hunk 2 above)
Comment (jbytheway) [reply src/character.h]: They can't be references because they might not be present.  And optional values are expensive to copy.  I experimented with various ways of writing the code, and this seemed the cleanest.

File: src/character.h (hunk 3 above)
Comment (jbytheway) [reply src/character.h]: No particular reason; would work fine either way.

File: src/character.h (hunk 2 above)
Comment (BevapDin) [reply src/character.h]: In that case, I recommend `optional<std::reference_wrapper<T>>`. It
- indicates that the value is optional,
- that (if it exists) is a reference (never null),
- is fast to copy as `reference_wrapper` is basically just a pointer,
- is easy to distinguish from a pointer (which may indicate ownership, or may require dynamic memory allocation, who knows).

File: src/skill.cpp (hunk 1 above)
Comment (jbytheway) [reply src/skill.cpp]: On reflection, it has a performance impact on debug builds, so I'll get rid of it.
