### PR TITLE
Fix tools that use UPS conversion mods

### LINKED ISSUE #31377: UPS-modded lights do not work
# Describe the bug
Lighting tools that have been modded to use UPS charges don't work. In 0.D stable, this wasn't so much an issue, as they'd slowly recharge. Now they just plain do not work.

# Steps To Reproduce
1. Create a player with a flashlight and a UPS loaded with a charged battery
2. Apply a UPS conversion mod to the flashlight
3. Activate the flashlight. It will immediately go dead.

# Expected behavior
The flashlight shines and drains the UPS

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1803
- Game Version: 0.D-4219-g5bce0cd [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]
# Additional context
So, I was toodling around with UPS modded tools in an effort to try to understand how they work, and it looks like flashlights are some sort of black sheep. I don't understand how flashlights work in the game code at all.

### PR DESCRIPTION
**Pull request by Inglonias**
#### Summary
 ```SUMMARY: Bugfixes "Makes UPS modified tools work as intended"```

#### Purpose of change
Fixes #31377

#### Describe the solution
Replaced calls to `ammo_sufficient` and `ammo_remaining` with `units_sufficient` and `units_remaining` in the context of turning battery powered tools on and off. The `units_sufficient` and `units_remaining` functions take `USE_UPS` into account, but require a character object to be passed in. Since iuse has that anyhow, there's no harm in doing this.

#### Describe alternatives you've considered
Add a check in `ammo_sufficient` and `ammo_remaining` for UPS charges, but as far as I can tell, that requires an argument of a character or player pointer, and I don't want to adjust everything in the game thta calls `ammo_sufficient` and `ammo_remaining` for a new function definition.

#### Additional context
If I missed any tools, please let me know ASAP

Paging @esotericist 

Thanks to [NK4517 on Reddit](https://www.reddit.com/r/cataclysmdda/comments/c355gs/how_do_i_use_gunsmith_repairkit_and_ups_mod_tools/erupsg1/) (AKA @Naka123 on Github) for pushing me to get this done. Their work essentially confirmed and implemented a theory I was toying with, but hadn't put into code yet. Without them, this wouldn't have happened today.

### CODE REVIEW

**Comment by Inglonias** [comment]
Just a note. #29983 is made obsolete by this PR.

File: src/iuse_actor.cpp [hunk 1]
```diff
@@ -2740,7 +2740,7 @@ bool repair_item_actor::can_use_tool( const player &p, const item &tool, bool pr
         }
         return false;
     }
-    if( !tool.ammo_sufficient() ) {
+    if ( !tool.units_sufficient( p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse_actor.cpp]:
```suggestion
    if( !tool.units_sufficient( p ) ) {
```

File: src/iuse_actor.cpp [hunk 2]
```diff
@@ -1718,7 +1718,7 @@ ret_val<bool> cauterize_actor::can_use( const player &p, const item &it, bool,
                        _( "You need a source of flame (4 charges worth) before you can cauterize yourself." ) );
         }
     } else {
-        if( !it.ammo_sufficient() ) {
+        if ( !it.units_sufficient( p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse_actor.cpp]:
```suggestion
        if( !it.units_sufficient( p ) ) {
```

File: src/iuse_actor.cpp [hunk 3]
```diff
@@ -191,7 +191,7 @@ int iuse_transform::use( player &p, item &it, bool t, const tripoint &pos ) cons
         p.add_msg_if_player( m_info, _( "You need to wear the %1$s before activating it." ), it.tname() );
         return 0;
     }
-    if( need_charges && it.ammo_remaining() < need_charges ) {
+    if ( need_charges && it.units_remaining( p ) < need_charges ) {
```
Comment (ZhilkinSerg) [inline src/iuse_actor.cpp]:
```suggestion
    if( need_charges && it.units_remaining( p ) < need_charges ) {
```

File: src/iuse.cpp [hunk 4]
```diff
@@ -8178,7 +8178,7 @@ int iuse::multicooker( player *p, item *it, bool t, const tripoint &pos )
     static const int charges_to_start = 50;
 
     if( t ) {
-        if( !it->ammo_sufficient() ) {
+        if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
        if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 5]
```diff
@@ -8043,7 +8043,7 @@ int iuse::remoteveh( player *p, item *it, bool t, const tripoint &pos )
     vehicle *remote = g->remoteveh();
     if( t ) {
         bool stop = false;
-        if( !it->ammo_sufficient() ) {
+        if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
        if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 6]
```diff
@@ -7864,7 +7864,7 @@ static void sendRadioSignal( player &p, const std::string &signal )
 int iuse::radiocontrol( player *p, item *it, bool t, const tripoint & )
 {
     if( t ) {
-        if( !it->ammo_sufficient() ) {
+        if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
        if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 7]
```diff
@@ -5887,7 +5887,7 @@ bool iuse::robotcontrol_can_target( player *p, const monster &m )
 
 int iuse::robotcontrol( player *p, item *it, bool, const tripoint & )
 {
-    if( !it->ammo_sufficient() ) {
+    if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
    if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 8]
```diff
@@ -5620,7 +5620,7 @@ int iuse::contacts( player *p, item *it, bool, const tripoint & )
 
 int iuse::talking_doll( player *p, item *it, bool, const tripoint & )
 {
-    if( !it->ammo_sufficient() ) {
+    if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
    if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 9]
```diff
@@ -5356,7 +5356,7 @@ int iuse::heat_food( player *p, item *it, bool, const tripoint & )
 
 int iuse::hotplate( player *p, item *it, bool, const tripoint & )
 {
-    if( it->typeId() != "atomic_coffeepot" && ( !it->ammo_sufficient() ) ) {
+    if ( it->typeId() != "atomic_coffeepot" && ( !it->units_sufficient( *p )) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
    if( it->typeId() != "atomic_coffeepot" && ( !it->units_sufficient( *p ) ) ) {
```

File: src/iuse.cpp [hunk 10]
```diff
@@ -4425,7 +4425,7 @@ int iuse::vibe( player *p, item *it, bool, const tripoint & )
         p->add_msg_if_player( m_info, _( "It's waterproof, but oxygen maybe?" ) );
         return 0;
     }
-    if( !it->ammo_sufficient() ) {
+    if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
    if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 11]
```diff
@@ -4030,7 +4030,7 @@ int iuse::shocktonfa_on( player *p, item *it, bool t, const tripoint &pos )
 
 int iuse::mp3( player *p, item *it, bool, const tripoint & )
 {
-    if( !it->ammo_sufficient() ) {
+    if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
    if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 12]
```diff
@@ -4006,7 +4006,7 @@ int iuse::shocktonfa_on( player *p, item *it, bool t, const tripoint &pos )
     if( t ) { // Effects while simply on
 
     } else {
-        if( !it->ammo_sufficient() ) {
+        if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
        if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 13]
```diff
@@ -3895,7 +3895,7 @@ int iuse::portal( player *p, item *it, bool, const tripoint & )
 
 int iuse::tazer( player *p, item *it, bool, const tripoint &pos )
 {
-    if( !it->ammo_sufficient() ) {
+    if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
    if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 14]
```diff
@@ -2321,7 +2321,7 @@ int iuse::radio_on( player *p, item *it, bool t, const tripoint &pos )
 
 int iuse::noise_emitter_off( player *p, item *it, bool, const tripoint & )
 {
-    if( !it->ammo_sufficient() ) {
+    if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
    if( !it->units_sufficient( *p ) ) {
```

File: src/iuse.cpp [hunk 15]
```diff
@@ -2198,7 +2198,7 @@ int iuse::water_purifier( player *p, item *it, bool, const tripoint & )
 
 int iuse::radio_off( player *p, item *it, bool, const tripoint & )
 {
-    if( !it->ammo_sufficient() ) {
+    if ( !it->units_sufficient( *p ) ) {
```
Comment (ZhilkinSerg) [inline src/iuse.cpp]:
```suggestion
    if( !it->units_sufficient( *p ) ) {
```

**Comment by ZhilkinSerg** [comment]
What about `iuse::teleport`?

**Comment by Inglonias** [comment]
> 
> 
> What about `iuse::teleport`?

Teleporters don't use batteries,

**Comment by Inglonias** [comment]
Spacing issues are resolved.

**Comment by akerigan** [comment]
> If I missed any tools, please let me know ASAP
UPS soldering doesn't fix/disassemble

**Comment by Inglonias** [comment]
Alright. Good to know.
