### PR TITLE
vehicles: split disconnected frames into a new vehicle

### LINKED ISSUE #23189: A vehicle with a coil of frames surrounding it is invincible.
### Expected behavior
Smashing vehicles into things damages and eventually destroys them.
### Actual behavior
A vehicle with a coil of frames surrounding it is invincible.
### Steps to reproduce behavior
https://www.reddit.com/r/cataclysmdda/comments/830vz0/invincible_vehicle_and_how_does_it_work
### Explanation
Vehicles in cdda cannot be split into two parts, which means if two parts of a vehicle is connected only by a frame, this frame will be unbreakable. Only one end of the strand of frames around this car is connected to it. If any frame in it breaks except the free end of it (the white v), the strand is split from the car, which is not allowed to happen. This makes all frames in it except the free end unbreakable. You can crash the largest car down to scrap with it without even getting a scratch on it.

### LINKED ISSUE #25717: Vehicle at 32 km/h rams into a little column and ultimitaly breaks ALL parts leaving nothing but ashes
**Describe the bug**  
i saved my game at storage units wanted to rush to the refugee center and go with my vehicle and ram everything into my way when i accedently rammed into a small column which broke my entire vehicle with me and my NPC still alive and in the same position before it broke apart

**To Reproduce**  
1. drive car and try to ram (i dont know how but it just broke v pics down)
2.if it didnt work then explain the pics

**Expected behavior**  
should stop since i am moving with a safe "extra" speed probably even ramm me outside without breaking vehicle 

**Screenshots**  
ZIP of save
[Carboomwaitwhat.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/2398871/Carboomwaitwhat.zip)

1

2

3
asjd
4
rvas

**Versions and configuration(please complete the following information):**
 - Windows 10
 - Game Version 0.C-32309-g6e7b56a
 - Graphics version Tiles 
 - Mods loaded  [ DarkDaysAhead , Mining Mod , More Survival Tools , Classic RogueLike Classes , StatsThroughSkills , Vehicle Additions Pack , Tanks and other Vehicles , Bionic System Mod , Boats , Folding Parts Pack , Filthy Clothing , Makeshift Item Mod , Classes And Scenarios Mod , Disable NPC Needs , NPC Traits , Mytholigal Ryplicas]

**Additional context**  
My RV speed might be between (32 - 48)

i dont know what happened so someone help

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "vehicles: split disconnected frames into a new vehicle"```

#### Purpose of change
Fixes #25717 
Fixes #23189 

When the last frame connected a collection of parts to the rest of a vehicle is eligible for destruction,
instead of keeping the frame (to preserve the vehicle integrity) or destroying the soon to be 
disconnected parts, splits the parts off into a new vehicle and remove them from the existing
vehicle.

#### Describe the solution
When the last frame connected some parts to the vehicle center is destroyed, use a flood fill algorithm to find all the parts in the current vehicle that could be in different vehicles. Then call the code to 
split parts into a new vehicle.

#### Describe alternatives you've considered
I wrote a lot of really bad code to find the different vehicles, but OrenAudeles' flood fill algorithm worked really well after I buckled down and used it correctly.

#### Additional context
vehiclesplitv3-1
The results of driving a sports car with an active mini-nuke into the center of a bunch of parked vehicles. All the parts in red are new vehicles spawned from the parent vehicle.

vehiclesplitv3-2
Results of the column split test. The small column and the brick wall have carved a trench into their respective cars without destroying them.

### CODE REVIEW

**Comment by Inglonias** [comment]
I love how my test has a name now. That's fun. Did you drive the cars into the terrain for half an hour each?

More seriously, this is a long time coming, and honestly I'm amazed we can do this at all. Pats on the back to all involved!

**Comment by mlangsdorf** [comment]
Yes, I drove the cars into the terrain for 1/2 each, as specified in the test case.

**Comment by ZhilkinSerg** [comment]
Looks good in-game, but I had issues with performance on single occasion - didn't had chance to profile yet and couldn't reproduce it another time, so it could be unrelated to vehicle split code.

File: src/map.cpp [hunk 1]
```diff
@@ -475,6 +475,9 @@ void map::move_vehicle( vehicle &veh, const tripoint &dp, const tileray &facing
             if( coll.type == veh_coll_veh ) {
                 continue;
             }
+            if( static_cast<size_t>( coll.part ) > veh.parts.size() ) {
```
Comment (BevapDin) [inline src/map.cpp]: You probably meant to compare via `>=` because this will still allow invalid indizes (equal to `size()`), which causes UB in the array operator below.

File: src/map.cpp [hunk 2]
```diff
@@ -964,12 +967,10 @@ vehicle *map::displace_vehicle( tripoint &p, const tripoint &dp )
         }
 
         if( psg->pos() != part_pos ) {
-            debugmsg( "Passenger/part position mismatch: passenger %d,%d,%d, part %d %d,%d,%d",
-                      g->u.posx(), g->u.posy(), g->u.posz(),
-                      prt,
-                      part_pos.x, part_pos.y, part_pos.z );
-            veh->parts[prt].remove_flag( vehicle_part::passenger_flag );
-            continue;
+            add_msg( m_debug, "Passenger/part position mismatch: passenger %d,%d,%d, part %d %d,%d,%d",
```
Comment (BevapDin) [inline src/map.cpp]: Why did you change this? Messages with `m_debug` are *only* shown when debug mode is enabled, which must be done manually And messages like this can easily be missed. `debugmsg` messages are always shown and can't be missed. If this message indicates a serious problem, it should announce this loudly.

File: src/vehicle.cpp [hunk 3]
```diff
@@ -1636,6 +1636,101 @@ bool vehicle::remove_carried_vehicle( std::vector<int> carried_parts )
...
+// split the current vehicle into up to 3 new vehicles that do not connect to each other
+bool vehicle::find_and_split_vehicles( int exclude )
+{
+    std::vector<int> valid_parts = all_parts_at_location( part_location_structure );
+    std::set<int> checked_parts;
+    checked_parts.insert( exclude );
+
+    std::vector<std::vector <int>> all_vehicles;
+
+    size_t cnt;
```
Comment (BevapDin) [inline src/vehicle.cpp]: Whydid you define this outside of the loop (it's only used inside of it)?

File: src/vehicle.cpp [hunk 4]
```diff
@@ -1666,77 +1761,110 @@ bool vehicle::split_vehicles( std::vector<std::vector <int>> new_vehs,
...
     return did_split;
 }
 
+bool vehicle::split_vehicles( std::vector<std::vector <int>> new_vehs )
+{
+    std::vector<vehicle *> null_vehicles;
+    std::vector<std::vector <point>> null_mounts;
+    std::vector<point> nothing;
+    null_vehicles.assign( new_vehs.size(), nullptr );
+    null_mounts.assign( new_vehs.size(), nothing );
```
Comment (BevapDin) [inline src/vehicle.cpp]: `std::vector` has a constructor that does this (it takes a count and an object, just like `assign` and does the same).

File: src/vehicle.cpp [hunk 5]
```diff
@@ -1666,77 +1761,110 @@ bool vehicle::split_vehicles( std::vector<std::vector <int>> new_vehs,
...
-                new_vehicle->parts.back().mount = split_mounts[ new_part ];
+            if( !split_mounts.empty() ) {
+                new_mount = split_mounts[ new_part ];
+                new_vehicle->parts.back().mount = new_mount;
             }
-            // put the passenger on the new vehicle
-            if( passenger ) {
-                g->m.board_vehicle( passenger->pos(), passenger );
+            // remove labels associated with the mov_part
+            std::string label_str;
```
Comment (BevapDin) [inline src/vehicle.cpp]: Why is this defined outside of the `if` block (it is only used inside of it)?

File: src/map.cpp (hunk 2 above)
Comment (mlangsdorf) [reply src/map.cpp]: I don't think it's a severe problem at this point. It can happen when a vehicle's skew changes due to parts splitting off. I did my best to correct for it, but it still happens sometimes for reasons I don't understand.

File: src/vehicle.cpp (hunk 5 above)
Comment (mlangsdorf) [reply src/vehicle.cpp]: Leftovers from previous versions of the code. Fixed, thanks!

File: src/vehicle.cpp (hunk 4 above)
Comment (mlangsdorf) [reply src/vehicle.cpp]: Fixed.

File: src/vehicle.cpp (hunk 3 above)
Comment (mlangsdorf) [reply src/vehicle.cpp]: Fixed.

File: src/map.cpp (hunk 1 above)
Comment (mlangsdorf) [reply src/map.cpp]: Fixed, thanks.

**Comment by kevingranade** [comment]
While testing this encountered a crash at vehicle_move.cpp line 334 because it attempted to dereference a non-existent index.  The parts array is shifting inside this loop and random parts are being acted on.

**Comment by mlangsdorf** [comment]
I refactor the code to address the crash at vehicle_move.cpp and then adjusted vehicle::smash() to remove parts at duplicated locations. I can still get weird behavior by spawning 4-5 vehicles on top of each and then running a car into them at very high speeds, but it's less a "hang" and more "weird animation effects as the crash gets calculated."

I may need to take on the collision refactor sooner than I had hoped. Too much weird stuff is going on there and a lot of the underlying assumptions are changing.

File: src/vehicle.cpp [hunk 6]
```diff
@@ -1636,6 +1655,101 @@ bool vehicle::remove_carried_vehicle( std::vector<int> carried_parts )
...
+                break;
+            }
+        }
+        if( test_part == -1 || static_cast<size_t>( test_part ) > parts.size() ) {
+            break;
+        }
+
+        int head = 0;
+        int tail = 0;
+        std::pair<int, std::vector<int>> possible_parts[ 128 ];
```
Comment (BevapDin) [inline src/vehicle.cpp]: Why do you need a container of fixed size instead of a resizable container?

File: src/vehicle.cpp [hunk 7]
```diff
@@ -1636,6 +1655,101 @@ bool vehicle::remove_carried_vehicle( std::vector<int> carried_parts )
...
+        const auto push_neighbor = [&]( int p, std::vector<int> with_p ) {
+            possible_parts[ tail ].first = p;
+            possible_parts[ tail ].second = with_p;
+            tail = ( tail + 1 ) % 128;
+        };
+        auto pop_neighbor = [&]( void ) {
```
Comment (BevapDin) [inline src/vehicle.cpp]: That void is not needed at all.

File: src/vehicle.cpp (hunk 6 above)
Comment (mlangsdorf) [reply src/vehicle.cpp]: No good reason. Fixed.

File: src/vehicle.cpp (hunk 7 above)
Comment (mlangsdorf) [reply src/vehicle.cpp]: Fixed, thanks.
