### PR TITLE
Fix for Adreneline CBM/Injector, Mycus wrath

### LINKED ISSUE #14719: Adrenaline Pump CBM glitch
Ok, so this is another one from the [forum](http://smf.cataclysmdda.com/index.php?topic=11923.0). The adrenaline pump cbm gives the player the adrenaline comedown debuff, instantly upon use, but displays the expected "YOu feel a rush of adrenaline" message. During testing with debug mode on, I got this message "Bad Intensity, ID:adrenaline". After waiting one turn, the adrenaline comedown vanished and was replaced with Adrenaline rush and gave all its proper bonuses. The duration at that point for adrenaline rush was 199, so we've lost 1 turn of adrenaline rush to the glitch. Upon reaching 149, adrenaline comedown kicks in as expected. Then I tried activating the pump again...and the counter went to 156. Just 7 more turns of adrenaline rush for 50 power.

I went and found the relevant code, and adrenaline pump cbm gives an initial duration of 200, with additional activations giving 50 duration. I'm trying to work out the math in add_effect, but it's not exactly my strong suit.

So two errors to report;
1 "Bad Intensity, ID:adrenaline" at activation, leading to 1 turn of adrenaline comedown before the rush kicks in.
2. Activating adrenaline pump while already affected with adrenaline only gives about 7 turns of additional bonus, should give 50.

Adrenaline pump cbm : bionics.cpp line 895
add_effect(): creature.cpp line 772

### PR DESCRIPTION
**Pull request by TheRafters**
This adds a new..reference function? to effect.cpp/h. I needed to retrieve int_dur_factor for use in creature.cpp.
I then used the new function to force set the intensity if int_dur_factor > 0.

This resolves #14719 for real this time. After this change, there is no longer a debug message after using adrenaline cbm, injector or mycus wrath. Testing included adrenaline cbm, adrenaline injector and mycus wrath with some meth and cocaine as a chaser.

The bug was minor, but very noticeable when you needed the adrenaline rush to gtfo in a hurry. After activating or reactivating adrenaline cbm, adrenaline injector or mycus wrath(via seeing a plant monster), the intensity would be set to 0 for a single turn, giving you the stat and speed loss of adrenaline comedown and mycus respite. The next turn it would be caught by a sanity check and trigger a debug message, then function normally.

Still unresolved to my satisfaction: why does reupping with the adrenaline injector give 30 turns of duration instead of the expected 12? The cbm gives 7 as expected...vexing.

I had fun with this, and learned something. I hope this is the correct fix this time around ;)

### CODE REVIEW

**Comment by Malkeus** [comment]
lol...ignore the not declared in this scope bit, that was a panic'd earlier commit that i reverted. the update creature.h was also a reverted change that carried over from my local branch and I couldn't figure out how to remove. If either one will cause a problem, let me know and I'll do a clean branch.

File: src/creature.cpp [hunk 1]
```diff
@@ -802,6 +801,7 @@ void Creature::add_effect( efftype_id eff_id, int dur, body_part bp,
             if (e.get_max_duration() > 0 && e.get_duration() > e.get_max_duration()) {
                 e.set_duration(e.get_max_duration());
             }
+
```
Comment (Malkeus) [inline src/creature.cpp]: Why?

File: src/creature.cpp [hunk 2]
```diff
@@ -787,7 +787,6 @@ void Creature::add_effect( efftype_id eff_id, int dur, body_part bp,
     if (effect_types[eff_id].get_main_parts()) {
         bp = mutate_to_main_part(bp);
     }
-
```
Comment (Malkeus) [inline src/creature.cpp]: seriously, why?

File: src/creature.cpp [hunk 3]
```diff
@@ -814,6 +814,11 @@ void Creature::add_effect( efftype_id eff_id, int dur, body_part bp,
                 e.mod_intensity(e.get_int_add_val());
             }
 
+            // Force intensity if it is duration based
+            if (e.get_int_dur_factor() != 0) {
```
Comment (BevapDin) [inline src/creature.cpp]: Style issue: no space in front of the `(`, but a space after it. And another space before the `)`. See doc/CODE_STYLE.txt

Applies to the other added code as well. (Function declaration and definition are fine as they are now.)

And I agree with questions. Why are you adding and removing empty lines seemingly at random?

**Comment by Malkeus** [comment]
I will fix the style issues later today. The lines seem to be holdovers from the fiasco of my first attempt, I couldn't figure out how to make th4em go away short of starting over completely. I blame my own stupidity compounded by smartgit. I'm honestly thrilled that the only issues are style ones :)

File: src/effect.h [hunk 4]
```diff
@@ -225,6 +225,8 @@ class effect : public JsonSerializer, public JsonDeserializer
         bool get_harmful_cough() const;
         /** Returns the percentage value by further applications of existing effects' duration is multiplied by. */
         int get_dur_add_perc() const;
+        /** Returns the duration interval at which the effects intensity is decremented */
```
Comment (Malkeus) [inline src/effect.h]: I feel like this isn't very informative, any suggestions?

**Comment by Malkeus** [comment]
Should I style the rest of this functions similarly? I notice it doesn't follow the same style. Also I'm not clear on how
e.set_intensity( ( e.get_duration() / e.get_int_dur_factor() ) + 1 );
should look. Is this acceptable or was the original ok?

original:
e.set_intensity((e.get_duration() / e.get_int_dur_factor()) + 1);

**Comment by BevapDin** [comment]
The version `e.set_intensity( ( e.get_duration() / e.get_int_dur_factor() ) + 1 );` is correct.

> Should I style the rest of this function similarly?

If you *change* large parts of a function, you could apply `astyle` before changing it. But here you only add a few lines, so it's not necessarily.

**Comment by Malkeus** [comment]
Ok, thank you, I'll keep that in mind. This is ready to for merging then.

File: src/effect.h (hunk 4 above)
Comment (Coolthulhu) [inline src/effect.h]: "Returns the number of turns it takes for the intensity to fall by 1 or 0 if intensity isn't based on duration.

File: src/creature.cpp [hunk 5]
```diff
@@ -814,6 +814,11 @@ void Creature::add_effect( efftype_id eff_id, int dur, body_part bp,
                 e.mod_intensity(e.get_int_add_val());
             }
 
+            // Force intensity if it is duration based
+            if( e.get_int_dur_factor() != 0 ) {
+                // + 1 here so that the lowest is intensity 1, not 0
+                e.set_intensity( ( e.get_duration() / e.get_int_dur_factor() ) + 1 );
+            }
```
Comment (Coolthulhu) [inline src/creature.cpp]: Why add it twice?
Can't existing effects be assumed to have correct intensity?

Comment (Malkeus) [inline src/creature.cpp]: I assumed no, because of the existing check for bad intensity. I'm compiling without this check to entry to see what happens.

File: src/effect.h (hunk 4 above)
Comment (Malkeus) [inline src/effect.h]: Thank you, that's much better.

File: src/creature.cpp (hunk 5 above)
Comment (Malkeus) [inline src/creature.cpp]: It all seems to work fine, I'll delete this from my commit.

**Comment by Malkeus** [comment]
Sleek and smooth, like a swimmer zombies legs.
