### PR TITLE
Don't try to shoot with empty gun

### LINKED ISSUE #77602: Segmentation fault
### Describe the bug

seems to be related to npc trying to avoid friendly fire, after I disabled the option in the npc rules it didn't crash

### Attach save file

[Miamisburg-trimmed.tar.gz](https://github.com/user-attachments/files/17635286/Miamisburg-trimmed.tar.gz)

### Steps to reproduce

1. turn off safe mode
2. hold tab until it crashes

### Expected behavior

not crash

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4412 (22H2)
- Game Version: 19807c7 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Translate Complex Dialogue [translate_dialogue]
]

### Additional context

[crash.log](https://github.com/user-attachments/files/17635203/crash.log)
[debug.log](https://github.com/user-attachments/files/17635240/debug.log)

### PR DESCRIPTION
**Pull request by PatrikLundell**
#### Summary
None

#### Purpose of change
Fix #77602, i.e. segmentation fault when trying to evaluate dispersion from an empty gun.

#### Describe the solution
Change npc_attack_gun::can_use to reject gun usage when a gun is empty, not only when it can't be wielded.
This causes the gun not to be attempted to be evaluated for firing performance down the line.

#### Describe alternatives you've considered
- Leave it to someone qualified. Now those people will have to evaluate this PR instead.
- Add a check in npc::wont_hit_friend to return "false" if there's no ammo. That also causes the symptoms to disappear, but thought it better to not evaluate the firing of an empty gun at all. Competent reviewers may disagree.

#### Testing
Loaded the save in the bug report and verified that not only didn't it blow up, but Liam did actually reload a gun (don't know if "varmint gun" is the same as the "Ruger" seen with the debugger), so the rejection doesn't seem to block gun usage to the degree that there is no attempt at reloading.

#### Additional context
The comment for the item::ammo_data() function is dangerously misleading. It claims it will return a nullptr if the gun isn't loaded, but that's a partial lie, as it happily returns data involving an empty magazine (although it probably rejects a direct loaded gun that's empty. Thus, anyone trusting enough to believe this may get a nasty surprise (segfault) when faced with an empty magazine and trying to use the ammo pointer that was promised to lead somewhere (it didn't matter here, as the ammo_data() results wasn't checked anyway).

Needs to be reviewed by competent reviewers. I THINK it's reasonable to bail out early, but it's possible this may lead to things that should be attempted being untried. Seeing the companion reload indicates at least one such possible failure seems to not happen in absolutely all cases.

### CODE REVIEW

File: src/npc_attack.cpp [hunk 1]
```diff
@@ -465,8 +466,9 @@ void npc_attack_gun::use( npc &source, const tripoint_bub_ms &location ) const
 
 bool npc_attack_gun::can_use( const npc &source ) const
 {
-    // can't attack with something you can't wield
-    return source.is_wielding( *gunmode ) || source.can_wield( *gunmode ).success();
+    // can't attack with something you can't wield or which lacks ammo.
+    return ( source.is_wielding( *gunmode ) || source.can_wield( *gunmode ).success() )
+           && gun.ammo_data() != nullptr && gun.ammo_data()->ammo != nullptr;
```
Comment (akrieger) [inline src/npc_attack.cpp:471]: I'm mildly concerned that `ammo_data()` could be silently expensive so this is now twice expensive, but I can't find an obvious proof of that.

Comment (PatrikLundell) [reply src/npc_attack.cpp]: Introduced new operations for cheaper checks for presence of ammo and ammo_data and replaced ammo_data() calls where suitable.

I hope this addresses the concern of @akrieger, at the cost of some mild scope creep.

Comment (akrieger) [reply src/npc_attack.cpp]: Sorry I didn't mean to do all of that. I just know that other places, computing stuff like `ammo_data()` is expensive, so if you wanted to 'fix this' you'd just stash the return value in a local variable instead of inlining the function call into the return statement twice.

Comment (PatrikLundell) [reply src/npc_attack.cpp]: Well, if it's a problem here it's a problem elsewhere, and so is better dealt with rather than skirted around with patches at random points.
