### PR TITLE
Adjust blackpowder fouling mechanics and other fault_fix QoL

### LINKED ISSUE #63515: Blackpowder Fouling Extremely Rapid
### Describe the bug

If placed in inventory, weapons that have been fired with EVEN ONCE with blackpowder will rust away in a matter of HOURS.

This is easiest to see with flintlock pistols or pistols you shoot with manually loaded black powder munitions, but happens to seemingly all guns.

### Attach save file

N/A

### Steps to reproduce

Spawn in pocket universe, 2 each of a handful of guns, and black powder ammo. Fire each once, drop 1 of the pair and put the other in pocket universe. Rest.

### Expected behavior

Having the weapon in inventory should not impact rust rate; also, _weapons should not rust to XX within 2 hours of being used once._

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2364 (21H2)
- Game Version: 2ee4928 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Xedra Evolved [xedra_evolved],
    Magiclysm [magiclysm],
    Blaze Industries [blazeindustries],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    My Sweet Cataclysm [my_sweet_cataclysm]
]

### Additional context

_No response_

### LINKED ISSUE #64067: (Blackpowder ammo) Firearm fast-degrade durability to XX
### Describe the bug

Not sure if intended...

Anyway, Flintlock guns in current have a tendency break after one shot and require a full repair with the Firearm Repair Kit which in itself is done incrementally so it takes in excess of 75+ Solder and 5+ Scrap Metal to repair. 

Issue is more due to the gun being insta-ruined and not going down in durability levels.

Tested with Debug spawning multiple rifles and multi-firing 100+ shots at a Turkey. Gun will insta-ruin at random after a shot. 

### Attach save file

[Boles Acres Megafauna-trimmed.tar.gz](https://github.com/CleverRaven/Cataclysm-DDA/files/10924319/Boles.Acres.Megafauna-trimmed.tar.gz)

### Steps to reproduce

- Craft Flintlock Musket/Rifle and load with Paper Cartridge choice of ammo.
- Fire at target or monster.
- Gun randomly will break entirely to XX quality state and not go down durability levels. 

### Expected behavior

Firearms should proceed to degrade under Durability system esp since Black Powder Fouling mechanic is in play as well-not explode into a million pieces. 

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2604 (21H2)
- Game Version: 936b383 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Innawood [innawood],
    sees-player, run, crouch, bleed icons, retrodays [sees_player_retro],
    sees-player icon, HitButton_iso [sees_player_hitbutton],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Translate Complex Dialogue [translate_dialogue],
    Tamable Wildlife [Tamable_Wildlife],
    Megafauna [megafauna]
]

### Additional context

- Issue only tested with Paper Cartridge ammo. Not sure if problem persists with Shot ammo.
- If "Fouling and Lubricate" Mend was used before repair/durability failure: Fouling status reappears as soon as Gun is Mended. 
- Added: using Lubricate outright breaks the gun if used when weapon is at full durability. Wtf.

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Balance "Redo blackpowder fouling mechanics and firearm cleaning"

#### Purpose of change
Fixes #63515
Fixes #64067
Blackpowder fouling was broken mechanically and also cleaning guns in general took too long.

#### Describe the solution
- Blackpowder fouling is deterministic. It takes exactly 6 hours for the first tick of rusting damage to damage a firearm. After that, it takes 12 hours for the next, 18 for the next, and 24 for the next, for 60 hours total to tick down to XX (gun completely ruined). Rusting also happens outside of your inventory, when previously it only ever rusted while being carried. This rate of rusting speeds up as the gun accumulates dirt (2-6x as fast as default). EDIT: Raised this time to 12, +24, +36, +48 (120 hours to go to XX at min fouling)
- Blackpowder is cleaned differently than smokeless, with hot soapy water instead of solvent. This is true to IRL, traditional solvents aren't effective for cleaning blackpowder, and water+soap isn't sufficient for smokeless.
- Base time to clean a gun is 1 hour.
- Fault_fix json objects can specify proficiencies and a float which, if you possess that proficiency, reduces total time to fix the item by that much. If you don't have the proficiency, mending the item trains that proficiency.
- Fault_fix json objects can specify flags and a float, which, if the item you're mending has that proficiency, reduces total time to fix the item by that much.
- Created a "Gun Cleaning" proficiency and gave it to many hobbies and professions. This halves the time to clean guns if you have it.
- Created an "EASY_CLEAN" flag. Guns which have this (muzzleloaders, break action, revolver, bolt action and pipe guns) are twice as fast to clean. (Thus if you're experienced and have an easy to clean gun it's 15 minutes total)
- Blackpowder causes casings to become filthy. They don't rust, but have to be cleaned before they get handloaded again. This is because blackpowder residue affects casings too IRL!

#### Describe alternatives you've considered
- Make black powder fouling easier to clean materially. According to @tenmillimaster cleaning doesn't necessarily require soap, or even hot water, but most sources I see recommend hot water and soap for a thorough cleaning. If it's just water it wouldn't even need to be relubricated necessarily.
- Make fouling rusting not damage a gun while you're cleaning it. The solution to make this happen is extremely complicated and will require a lot of hardcode for a variety of reasons (canceling an activity doesn't reference the item that you're mending for ACT_MEND_ITEM which means you can't remove a flag from the item to denote it's being worked on except upon completion of the mend act, and you can't reference the item while you're working on ACT_MEND_ITEM either - so the only way is to specifically see if the player is ACT_MEND_ITEM for their current activity and pause rusting which would make mending an engine pause rusting for example... etc). It's also an extremely niche benefit because as long as you wash a gun quickly (before 5 hours or so) it never matters, especially if you have proficiencies to clean it quickly.
- Make rusting take more than 6 hours, it's a fairly narrow window already, and while you are supposed to clean a gun ASAP if firing it with blackpowder and not leave it overnight, I could easily see this being 10 or 12 hours especially because it is common practice to give a gun a quick wipedown that doesn't really fix the underlying fouling issue but at least forestalls it. Open to suggestions.

#### Testing
- Loaded up in game without errors.
- Shot a blackpowder-loaded gun once and then waited 6 hours for it to rust successfully.
- Shot a blackpowder-loaded gun and then dropped it and waited 6 hours for it to rust successfully. 
- Shot various kinds of blackpowder-loaded guns, such as a single barrel shotgun and AR-15 and confirmed in each case the casing spat out was filthy.
- Checked out the mend menu and made sure the times to mend items decreased appropriately with the proper proficiencies and item flags.
- Mended an item and confirmed it trained my proficiency when I completed the mending.

#### Additional context
Example of the easy clean flag
EASY_CLEAN

### CODE REVIEW

**Comment by randomtyper** [comment]
I'd say increase the time until first tick of damage to about 12-24 hours and then use the formula. Or a few days, but that is stretching it. Sure, leaving a gun for a year after a long shooting session will leave it ruined, but for a week and from pristine to totally ruined? I doubt so.

That said, the corrosion from black powder is highly reliant on humidity. In tropical conditions, your gun may start to rust in mere hours (if it can even fire), in dry winter you may leave the gun uncleaned for a month and still have it in good condition.

An actual test, untreated surfaces start to rust in about 24 hours, and the testing conditions are pretty harsh:
http://www.ctmuzzleloaders.com/ctml_experiments/corrosion/corrosion2.html

Conditions:
"To simulate a 'dirty' fingerprint carrying corrosive material, six grains of black powder were burned in a loosely covered stainless steel pan, and the residue was dissolved in 5 ml of water. A small section of sponge was dampened with enough of this mixture so it left a thin layer of material wherever it touched. The sponge was pressed against each surface for three seconds, which left a 'fingerprint like' array of water marks. This should be a fairly severe test, since the water felt slippery, a sign of plenty of dissolved corrosive residues. All surfaces were photographed, and the humidity box was stored in a warm (80 degree) room".

Results:
"As expected, the untreated surfaces started rusting in less than a day, with the polished surface seeming slightly more susceptable than the matte surface. After 24 hours, most surfaces showed at least some signs of rust. After one week, only the EEzOx, Ballistol and Lehighs were rust-free".

If 1 tick of damage is "a bit rusty", then 24 hour mark makes sense.

File: src/item.cpp [hunk 1]
```diff
@@ -13216,7 +13217,11 @@ bool item::process_tool( Character *carrier, const tripoint &pos )
 
 bool item::process_blackpowder_fouling( Character *carrier )
 {
-    if( damage() < max_damage() && one_in( 2000 ) ) {
+    // rust is deterministic. 12 hours for first rust, then 24 (36 total), then 36 (72 total) and finally 48 (120 hours to go to XX)
+    // this speeds up by the amount the gun is dirty, 2-6x as fast depending on dirt level.
+    set_var( "rust_timer", get_var( "rust_timer", 0 ) + 1 + static_cast<int>( get_var( "dirt",
+             0 ) / 2000 ) );
+    if( damage() < max_damage() && get_var( "rust_timer", 0 ) > 43200 / ( damage() + 1 ) ) {
```
Comment (Qrox) [inline src/item.cpp:13224]: `rust_timer` should be reset after increasing damage if it is not already, otherwise the gun will likely rust to XX in a few turns after 12 hours because `43200 / (damage() + 1)` will be lower every time the damage is increased.

Comment (anoobindisguise) [reply src/item.cpp:13224]: You're right, thanks for catching it.

File: data/json/faults/fixes_gun.json [hunk 2]
```diff
@@ -5,22 +5,51 @@
     "name": "Clean fouling",
     "success_msg": "You clean your %s.",
     "time": "50 m",
-    "faults_removed": [ "fault_gun_dirt", "fault_gun_blackpowder" ],
+    "faults_removed": [ "fault_gun_dirt" ],
     "faults_added": [ "fault_gun_unlubricated" ],
     "skills": { "mechanics": 1 },
     "set_variables": { "dirt": "0" },
-    "requirements": [ [ "gun_cleaning", 1 ] ]
+    "requirements": [ [ "gun_cleaning_bp", 1 ] ],
```
[the remark this answers is not in the document]
Comment (anoobindisguise) [reply data/json/faults/fixes_gun.json]: Yep! Thanks for sanity checking me.

**Comment by Hirmuolio** [comment]
`inc_damage()` applies damage in massive chunks. Maybe applying smaller amounts of damage with `mod_damage( int qty )` more frequently would be better and more flexible.

**Comment by bombasticSlacks** [comment]
Looks like this works and is good progress, fidelity could be increased further in the future.

**Comment by anoobindisguise** [comment]
> `inc_damage()` applies damage in massive chunks. Maybe applying smaller amounts of damage with `mod_damage( int qty )` more frequently would be better and more flexible.

Right now everything that exists does damage in the form of || -> |/ -> |. -> \. -> XX so I'm not worried about this. When durability becomes more granular it can be changed.
