### PR TITLE
npctrade: further improvements

### LINKED ISSUE #31091: Lab trader over weight limit, prevent buying from them
# Describe the bug
Trading with a lab through the intercom. The lab is over the weight limit. I try to buy something from them, without selling anything. This is not possible  because "The intercom can't carry all that" which makes no sense.

# Expected behavior
Buying should never be impeeded by the seller being overweight. Probaly not selling either, since they have the whole building to store stuf..

# Screenshots

sHJBPg9

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-3509-ge10d164 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Slots [cbm_slots],
    Manual Bionic Installation [manualbionicinstall],
    Safe Autodoc [safeautodoc],
    StatsThroughSkills [StatsThroughSkills],
    Simplified Nutrition [novitamins],
    Battery Migration for Existing Games [Battery_Overhaul_Legacy_Mode],
    Alternative Map Key [alt_map_key]
]

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Features "npctrade: further improvements"```

#### Purpose of change
Fixes #31091 
Fix some minor issues with trading with NPCs:
* Remove the old inventory_exchange() code in favor of just keeping track of the weight and volume of goods transferred.  Also, give NPC shopkeepers an excessively large limit for the amount of goods they can trade.
* Have NPCs check whether they own a good before trying to sell it.
* Restock NPC trade goods inside the trade call, not during map load.

#### Describe the solution
inventory_exchange() was weird legacy code that was mostly replaced by transfer_items() but still lingered to keep track of NPC available weight and volume.  There is no good reason to flush and refill the entire inventory every time the player selects the item, so just track weight_left and volume_left directly.
    
Also, give NPC shopkeepers the ability to trade up to 5000L or 5000 kg of goods, regardless of whether they can carry that much.  Remove the DEBUG storage trait from the Free Merchants shopkeeper.

Check if the NPC actually owns something before trying to sell it.

Instead of checking to restock an NPC's trade goods when they are loaded on the map, check if it's been 3 days since the last trade when the player starts the trade.
    
Increase the amount of stuff that shopkeepers have to sell, based on the faction wealth, and faction shopkeepers always restock with some faction currency.  Remove the faction currency from the shopkeeper lists, but add other faction's currency to represent that people are trading this stuff around.  Players can decide if they  want Flat Coins when there's no Campus.

#### Describe alternatives you've considered
I'd like to have NPCs check if the player owns something before the NPC buys it, but the logic for that is going to be annoying as long as my_fac is not part of Character::, so I'll do a separate PR to for that.

### CODE REVIEW

**Comment by Mecares** [comment]
Would be nice to be able to ask the trader when he is roughly expecting to restock.

**Comment by mlangsdorf** [comment]
That's going to be a bit of work, but I can add that to my next PR for NPC dialogue options.

File: src/npctrade.h [hunk 1]
```diff
@@ -42,6 +42,8 @@ class item_pricing
         int npc_has = 0;
         int u_charges = 0;
         int npc_charges = 0;
+        units::mass weight = units::from_gram( 0 );
```
Comment (ZhilkinSerg) [inline src/npctrade.h]: You can use `0_gram` and `0_ml`.
