### PR TITLE
iterator_traits<vehicle_part_iterator<T>> is missing reference

### LINKED ISSUE #58643: `iterator_traits<vehicle_part_iterator<T>>` is missing `reference`
### Describe the bug

I work on MSVC's C++ Standard Library implementation, and we regularly build popular open-source projects, including yours, with our development toolsets in order to prevent regressions from breaking your code. This also allows us to provide advance notice of breaking changes - in this case, we've found an issue in your code that will cause compiler errors with an upcoming version of the Visual C++ toolset.

Specifically, we merged https://github.com/microsoft/STL/pull/2447 implementing a new optimization in the `minmax_element` family of algorithms. This optimization involves inspecting iterator types to see if they're eligible for the optimization, and as part of that, we need to inspect `iterator_traits<UserDefinedIterator>::reference` at compile-time.

There's an `iterator_traits<vehicle_part_iterator<T>>` in your codebase that does not provide a `reference` typedef (or `pointer`):

https://github.com/CleverRaven/Cataclysm-DDA/blob/bcd8b3b0948b50fb46df118c380f752251ca4519/src/vpart_range.h#L84-L90

When compiled with the upcoming VS 2022 17.4 Preview 1 toolset or later, this will emit an error of the form:

```
error C2794: 'reference': is not a member of any direct or indirect base class of 'std::iterator_traits<_FwdIt>'
        with
        [
            _FwdIt=vehicle_part_iterator<vehicle_part_range>
        ]
```

The fix should be straightforward (and backwards-compatible with all previous toolsets, and other compilers). According to the C++ Working Paper [N4910](https://isocpp.org/files/papers/N4910.pdf) 25.3.2.3 [[iterator.traits]/1](https://eel.is/c++draft/iterator.traits#1), the `reference` and `pointer` typedefs should match what `operator*()` and `operator->()` return, respectively:

https://github.com/CleverRaven/Cataclysm-DDA/blob/bcd8b3b0948b50fb46df118c380f752251ca4519/src/vpart_range.h#L53-L57

Therefore, this should be added to `iterator_traits<vehicle_part_iterator<T>>`:

```cpp
using reference = const vpart_reference &;
using pointer = const vpart_reference *;
```

---

Unrelated aside: I saw the comment "This requires adding more operators to the iterator, which may not be efficient." It is certainly tedious to provide the large number of operators required for random-access iterators (including the obscure `n + iter`). However, this will have a minimal impact on compile-time throughput (build speed), and will typically *improve* run-time performance. This is because many STL algorithms and data structures will detect random-access iterators automatically, and perform constant-time operations. If they only have forward-iterator operations to work with, they have to fall back to linear-time operations. A simple example is calculating the distance between two iterators (which is used by `vector` range construction and many other places). `std::distance()` will detect random-access iterators and call `last - first` which performs a single subtraction, but for forward iterators it must repeatedly increment a copy of `first` until it's equal to `last`.

### Steps to reproduce

See bug description (requires VS 2022 17.4 Preview 1 or later to reproduce, which has not yet shipped).

### Expected behavior

Cataclysm-DDA should compile without errors.

### Screenshots

_No response_

### Versions and configuration

Compile-time issue, not running the game. Again, requires VS 2022 17.4 Preview 1 (or the latest build of https://github.com/microsoft/STL ).

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
#### Summary
None

#### Purpose of change

Fix #58643

### CODE REVIEW

File: src/vpart_range.h [hunk 1]
```diff
@@ -84,8 +84,8 @@ namespace std
 template<class T> struct iterator_traits<vehicle_part_iterator<T>> {
     using difference_type = size_t;
     using value_type = vpart_reference;
-    // TODO: maybe change into random access iterator? This requires adding
-    // more operators to the iterator, which may not be efficient.
```
Comment (Qrox) [inline src/vpart_range.h:88]: Why removing this comment? The iterator is still non-random-access as far as I can tell, so we should keep the "change into random access iterator" part.

**Comment by BrettDong** [comment]
Please follow the pull request template to pick a category (can be None) to fill in the summary line. The summary line is mandatory so we can generate change log from pull requests on GitHub.

**Comment by SaumyaBhushan** [comment]
> I would guess that this PR is intended to address #58643? If that's the case, adding "Fix #58643" (without the quotes) under "Purpose of change" would link the PR to that issue and cause it to be closed automatically when this PR is closed due to being merged.

I have linked this PR with the issue

**Review by BrettDong — APPROVED** [review]
