### PR TITLE
Prevent generating normal distribution with zero sigma

### LINKED ISSUE #56030: Portal storm crashes to desktop
### Describe the bug

Portal storm with game included mod "Innawoods" and "No Monsters" causes crash to desktop.

### Steps to reproduce

[savegame.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/8234436/savegame.zip)

1. Load savegame
2. Wait or craft for a while
3. Portal storm warning prompt appears
4. Continue
5. Game crashes to desktop without error

### Expected behavior

No crash. Alternatively, no portal storms for a proper "untouched world" scenario.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19041.329 (2004)
- Game Version: 53f9bd3 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Innawood [innawood],
    No Monsters [Only_Wildlife]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by BrettDong**
#### Summary
Bugfixes "Prevent generating normal distribution with zero sigma"

#### Purpose of change
* Fix #56030 

Innawood mod defines a regional setting where city shop radius and city park radius both follow a normal distribution of mean 0 and standard deviation 0 (#53960):
```json
    "city": {
      "shop_radius": 0,
      "shop_sigma": 0,
      "park_radius": 0,
      "park_sigma": 0,
      "houses": { "house_w_1": 50 },
      "parks": { "small_wooded_trail": 300 },
      "shops": { "s_gas": 700 }
    },
```

However constructing a `std::normal_distribution` with zero sigma is undefined behaviour in C++ standard:

This causes the crash in #56030.

#### Describe the solution
Add a check for standard deviation to prevent constructing normal distribution with zero sigma.

### CODE REVIEW

File: src/overmap.cpp [hunk 1]
```diff
@@ -4860,10 +4860,14 @@ overmap_special_id overmap::pick_random_building_to_place( int town_dist ) const
     //Normally distribute shops and parks
     //Clamp at 1/2 radius to prevent houses from spawning in the city center.
     //Parks are nearly guaranteed to have a non-zero chance of spawning anywhere in the city.
-    int shop_normal = std::max( static_cast<int>( normal_roll( shop_radius, shop_sigma ) ),
-                                shop_radius );
-    int park_normal = std::max( static_cast<int>( normal_roll( park_radius, park_sigma ) ),
-                                park_radius );
+    int shop_normal = shop_radius;
+    if( shop_sigma > 0 ) {
+        shop_normal = std::max( shop_normal, static_cast<int>( normal_roll( shop_radius, shop_sigma ) ) );
```
Comment (Qrox) [inline src/overmap.cpp:4865]: Maybe change `normal_roll` to support zero stddev?

Comment (BrettDong) [reply src/overmap.cpp:4865]: `normal_roll` is a hot path so I don't want to add a branch there.
