### PR TITLE
Standardize epower drain

### LINKED ISSUE #20375: Something wrong with vehicle power usage?
I'm losing battery charge and I'm fairly sure I shouldn't be. I have a V8 diesel with a truck alternator. The only other things running are 3 headlights and a stereo. I'm driving around at 30 to 40 mph in the dark, if that matters. Still, I'm using up just shy of 1000 power and that alternator should be putting out 1320. And yet I'm slowly, but surely, losing battery charge. 

The only other thing that could possibly be using power is if the Cable Charging System bionic screwed up, as I didn't unhook before driving, just let it decouple naturally (which, btw, is kinda weird, if understandable in its own right, I should be able to charge even from a moving vehicle. I understand the *why*, so I'm not calling it a bug, just odd)

Am I missing something here? I mean, if I had been using a car battery instead of storage batteries I'd be flat out of power.

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #20375

Two parts (stereo and chimes) used weird power drain mechanics where they drained batteries directly rather than playing nicely like everyone else. As a result their power consumption was 373 times listed epower. This shows that no one really tested the damn chimes when they were last changed (implemented?) because a pair of chimes consumes the whole output of a minireactor.

Also more clean design: rather than hardcoding every flag as epower drainer, there is now a separate flag: `"ENABLED_DRAINS_EPOWER"`. Does exactly what it name says for all core parts and also turns off the part if energy drops to 0.
For modded parts with positive epower despite being of "consumer type", it means "`epower/373` is added to vehicle with this part every turn if it is enabled".
Before, this was special-cased for fridges, cameras, lights and so on.

### CODE REVIEW

File: src/veh_type.cpp [hunk 1]
```diff
@@ -70,9 +70,9 @@ static const std::unordered_map<std::string, vpart_bitflags> vpart_bitflag_map =
     { "CARGO", VPFLAG_CARGO },
     { "INTERNAL", VPFLAG_INTERNAL },
     { "SOLAR_PANEL", VPFLAG_SOLAR_PANEL },
-    { "VPFLAG_TRACK", VPFLAG_TRACK },
     { "RECHARGE", VPFLAG_RECHARGE },
-    { "VISION", VPFLAG_EXTENDS_VISION }
+    { "VISION", VPFLAG_EXTENDS_VISION },
+    { "ENABLED_DRAINS_EPOWER", VPFLAG_ENABLED_DRAINS_EPOWER },
```
Comment (Night-Pryanik) [inline src/veh_type.cpp]: Redundant comma?
