### PR TITLE
Projectile damage reduction from weapon damage never goes to 0

### LINKED ISSUE #32958: Damaged bow only fires arrows one tile.
# Describe the bug

I have a damaged short bow that, when firing arrows from it, will only launch arrows one tile.

# Steps To Reproduce

1. Make a bow, damage it, equip it, have some arrows
2. Aim at any target more than one square away, steady aim if you like, it shouldn't affect things.
3. Fire the arrow and observe the behavior of the arrow flying only one square.

# Expected behavior

I expect a mildly damaged bow to fire normally, perhaps with a slight penalty, but still be mainly functional. I don't expect bows to stop functioning as bows until they reach XX damage.

# Screenshots

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-6116-g0b8fac6 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Alternative Map Key [alt_map_key],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks]
]

# Additional context

None that I can think of.

### PR DESCRIPTION
**Pull request by kevingranade**
SUMMARY: Bugfixes "fix damaged weapons having zero range."

#### Purpose of change
Fixes #32958
Weapon damage caused projectile damage to drop to 0, triggering the failure mode where the projectile would immediately drop to the ground.
This was exacerbated, but not caused, by archery balance changes that reduced intrinsic bow damage, replacing it with multipliers.

#### Describe the solution
Insure projectile damage is never reduced below 1 by weapon damage.

#### Describe alternatives you've considered
At some point I want to replace all of this with a physical model of projectiles and convert it to damage only at impact.
Short of that, the fact that weapon damage directly decreases projectile damage like this is also questionable.

#### Testing
I have not tested this yet.
What needs checking is that a damaged short bow can still fire, and that damage to the weapon still reduces projectile damage up to that point.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -6083,7 +6083,10 @@ damage_instance item::gun_damage( bool with_ammo ) const
     if( item_damage > 0 ) {
         // TODO: This isn't a good solution for multi-damage guns/ammos
         for( damage_unit &du : ret ) {
-            du.amount -= item_damage * 2;
+            if( du.amount <= 1.0 ) {
+                continue;
+            }
+            du.amount = std::max( 1.0, du.amount - item_damage * 2 );
```
Comment (kevingranade) [inline src/item.cpp]:
```suggestion
            du.amount = std::max<float>( 1.0f, du.amount - item_damage * 2 );
```
