### PR TITLE
Show "Time: ???" when underground and without watches

### LINKED ISSUE #20117: Natural Time-Telling underground
ATM the natural time-telling also works underground. Which I think should not be possible.

Taken from the Wiki:
"As long as the character can see the sky (e.g. is not underground) they will see a small sundial pictograph in their UI display. This picture will change throughout the day and night and corresponds to the hour of the day. It is impossible to tell the exact time without a device. If the character is underground (e.g. in a basement, etc.) the sundial will be replaced with the grey-tinted message "underground." This limits natural time telling to above-ground use."

to reproduce: start Prison Break scenario

### PR DESCRIPTION
**Pull request by Night-Pryanik**
Closes #20117.

We might also need to remove "Wait until dusk/dawn/noon etc" from Waiting menu when underground and without watches.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -4939,7 +4939,9 @@ void game::draw_sidebar()
         }
 
         wprintz(time_window, c_white, "]");
-    }
+    } else {
+        wprintz( time_window, c_white, "Time: ???" );
```
Comment (BrettDong) [inline src/game.cpp]: You need to I18N this: 
```C++
wprintz( time_window, c_white, _( "Time: ???" ) );
```

**Comment by Night-Pryanik** [comment]
> You need to I18N this

Damn, forgot about this. Sorry!
