### PR TITLE
Fix effect triggering

### LINKED ISSUE #10617: (bc17d56) Painkillers Broken again
Painkillers, no matter the type, don't appear to work once more. The "Painkillers" disease not being added to the list of active effects again. Seems to be a repeat of the earlier bug.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/7227229-bc17d56-painkillers-broken-again?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by i2amroy**
Fixes some <= 0 confusion stuff and makes having a nonzero addition value properly override having a default (0) chance to trigger.

Fixes #10617

### CODE REVIEW

**Comment by macrosblackd** [comment]
I will begin testing this soon as I finish tweaking my archery related stuff.

File: src/effect.cpp [hunk 1]
```diff
@@ -469,14 +469,23 @@ std::string effect::disp_desc(bool reduced) const
...
-    values.push_back(desc_freq(get_percentage("HURT", reduced), get_avg_mod("HURT", reduced), _("damage"), _("damage")));
-    values.push_back(desc_freq(get_percentage("THIRST", reduced), get_avg_mod("THIRST", reduced), _("thirst"), _("quench")));
-    values.push_back(desc_freq(get_percentage("HUNGER", reduced), get_avg_mod("HUNGER", reduced), _("hunger"), _("sate")));
-    values.push_back(desc_freq(get_percentage("FATIGUE", reduced), get_avg_mod("FATIGUE", reduced), _("fatigue"), _("rest")));
-    values.push_back(desc_freq(get_percentage("COUGH", reduced), get_avg_mod("COUGH", reduced), _("coughing"), _("coughing")));
-    values.push_back(desc_freq(get_percentage("VOMIT", reduced), get_avg_mod("VOMIT", reduced), _("vomiting"), _("vomiting")));
-    values.push_back(desc_freq(get_percentage("SLEEP", reduced), get_avg_mod("SLEEP", reduced), _("blackouts"), _("blackouts")));
+    int val = 0;
+    val = get_avg_mod("PAIN", reduced);
+    values.push_back(desc_freq(get_percentage("PAIN", val, reduced), val, _("pain"), _("pain")));
```
Comment (KA101) [inline src/effect.cpp]: Huh.  This looks like it might be workable for the mutation fix.  I wasn't sure how best to handle that.
