### PR TITLE
fix "Automatic vehicle turrets 'attempted to fire zero or negative shots' "

### LINKED ISSUE #23689: Automatic vehicle turrets "attempted to fire zero or negative shots"
Game version: 0.C-27741

Operating system: Windows 7

Tiles or curses: Tiles

Mods active: More Survival Tools, No Explosive Zombies, No Fungal Monsters, StatsThroughSkill IV, Vehicle Additions Pack, Tanks and Other Vehicles, Bionics Systems Mod, Boats, Icecoon's Arsenal, Filthy Clothing, Makeshift Items Mod, More Buildings, No Flaming Weapons, Disable Mutagens, Disable NPC Needs, No Antique Firearms, No Fictional Guns, NPC Traits

### Expected behavior
Automatic vehicle turrets open fire on enemies till out of ammo after which they stop without any issues.

### Actual behavior
Upon running out of ammo, said units throw an error (with variation depending on the turret/gun etc) every time when targetting and attempting to fire at the enemy:

uhoh

### Steps to reproduce the behavior
Set vehicle's ballistic-type turrets to automatic fire, provide targets for the turrets till they run out of bullets.

Referencing #15426 as old, similar issue with NPCs

### PR DESCRIPTION
**Pull request by TheFreckle**
resolves #23689

There was no status check to see if the turret was able to fire, so it kept trying to fire.

Built and tested, works as intended. No debug message appears when turret runs out of ammo with hostile targets in sight.

### CODE REVIEW

File: src/turret.cpp [hunk 1]
```diff
@@ -513,6 +513,10 @@ int vehicle::automatic_fire_turret( vehicle_part &pt )
 
     int shots = 0;
 
+    if ( gun.query() != turret_data::status::ready ) {
```
Comment (ZhilkinSerg) [inline src/turret.cpp]: Astyle error - should be no whitespace after `if`:

image
