### PR TITLE
Fix restore targeted bayonet usage for guns

### LINKED ISSUE #45379: Guns with a sword bayonet can't switch firing modes
# Describe the bug

When a sword bayonet is attached to a gun, it prevents the player from switching firing modes via the [**f**]ire -> [**s**]witch menu. Note that using [**F**] still works, although the bayonet can be selected as a mode, which is a bit odd.

# Steps To Reproduce
1. Spawn a trench gun and make sure it has a bayonet attached.
2. Enter the [**f**]ire menu
3. Press [**s**]witch and attempt to change to the double fire mode
4. Repeat step 3 and note that the firing mode has not changed

# Expected behavior

Firing mode should switch normally

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 2004
- Game Version: 0.E-7499-gb48a967 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda]
]

# Additional context

I only tested with the Trench Gun and AK-47M using a sword bayonet, but I assume this applies to other compatible guns and possibly other types of bayonet.

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
Bugfixes "Fix restore targeted bayonet usage for guns"

#### Purpose of change

guns with reach attacks (due to attached bayonets) were in a bad place.
You could only use the reach option via tab attacking (not chosing your targets yourself) and bayonets did make it impossible to switch fire modes of guns.

Fixes #45379

#### Describe the solution
Went through the ranged code and enabled reach attacks for guns with bayonets as fire mode option.
Had to change a bit of code to handle the switch from an activity based action (fire mode) to one that isn't (reach attack)

#### Testing

- Spawn in a gun that can take a bayonet and another as control unit (idealy the gun has multiple fire modes)
- Attach bayonet
- Spawn in mob
- press [f] to get into fire mode ui and shoot
- press [s] to switch fire mode 
- switch to bayonet mode
- press [f] to be able to manually target monsters (instead of having to rely on tabs target selection)
- press [s] to switch back to another fire mode

- Rinse and repeat for different guns with and without bayonets and turrets

#### Additional context
Sadly i couldn't figure out how to do the switch to/from melee mode without closing the firing ui. (this only affects fire modes, not the aim presets)
Maybe someone else knows how to do that.

### CODE REVIEW

File: src/ranged.cpp [hunk 1]
```diff
@@ -2202,9 +2205,12 @@ void target_ui::init_window_and_input()
         ctxt.register_action( "LEVEL_UP" );
         ctxt.register_action( "LEVEL_DOWN" );
     }
-    if( mode == TargetMode::Fire || mode == TargetMode::TurretManual ) {
+    if( mode == TargetMode::Fire || mode == TargetMode::TurretManual || ( mode == TargetMode::Reach &&
+            relevant && relevant->is_gun() && you->get_aim_types( *relevant ).size() > 1 ) ) {
```
Comment (olanti-p) [inline src/ranged.cpp:2209]: Check for `relevant != nullptr` is unnecessary here
```suggestion
            relevant->is_gun() && you->get_aim_types( *relevant ).size() > 1 ) ) {
```

File: src/ranged.cpp [hunk 2]
```diff
@@ -3114,13 +3123,16 @@ void target_ui::draw_controls_list( int text_y )
         lines.push_back( {2, colored( col_fire, aim )} );
         lines.push_back( {4, colored( col_fire, aim_and_fire )} );
     }
-    if( mode == TargetMode::Fire || mode == TargetMode::TurretManual ) {
+    if( mode == TargetMode::Fire || mode == TargetMode::TurretManual || ( mode == TargetMode::Reach &&
+            relevant && relevant->is_gun() && you->get_aim_types( *relevant ).size() > 1 ) ) {
```
Comment (olanti-p) [inline src/ranged.cpp:3127]: Same here

File: src/ranged.cpp [hunk 3]
```diff
@@ -2771,19 +2774,18 @@ void target_ui::action_switch_mode()
...
         for( std::pair<gun_mode_id, gun_mode> it : all_gun_modes ) {
-            if( it.second.flags.count( "REACH_ATTACK" ) ) {
-                continue;
-            }
             if( skip-- == 0 ) {
                 relevant->gun_set_mode( it.first );
                 break;
             }
         }
+        refresh = true;
```
Comment (olanti-p) [inline src/ranged.cpp:2788]: You may want to restrict this to abort only when switching to melee mode. There's no need to abort aiming when switching between e.g. single shot and burst fire, or burst fire and an underbarrel attachment.

File: src/ranged.cpp [hunk 4]
```diff
@@ -2801,10 +2803,17 @@ void target_ui::action_switch_mode()
             range = turret->range();
         }
     } else {
-        ammo = relevant->gun_current_mode().target->ammo_data();
-        range = relevant->gun_current_mode().target->gun_range( you );
+        if( relevant->gun_current_mode().melee() ) {
+            mode = TargetMode::Reach;
```
Comment (olanti-p) [inline src/ranged.cpp:2807]: Changing UI mode from inside `target_ui::run()` is dangerous since it breaks a bunch of assumption in other places.
E.g. with `TargetMode::Fire` it's guaranteed that `relevant != nullptr` and `activity != nullptr`, but with `TargetMode::Reach` it's always `activity == nullptr`. Not sure if it _actually_ breaks anything in your case though.

File: src/ranged.cpp (hunk 1 above)
Comment (actual-nh) [reply src/ranged.cpp:2209]: Why?

Comment (olanti-p) [reply src/ranged.cpp:2209]: Because every mode except `TargetMode::Turrets` and `TargetMode::Spell` guarantees `relevant` is not `nullptr`

File: src/ranged.cpp (hunk 2 above)
Comment (actual-nh) [reply src/ranged.cpp:3127]: Why (re relevant & nullptr)?

File: src/ranged.cpp (hunk 1 above)
Comment (Jamuro-g) [reply src/ranged.cpp:2209]: fair enough, i ll make sure to test it in a bit (or at worst tomorrow)

File: src/ranged.cpp (hunk 4 above)
Comment (Jamuro-g) [reply src/ranged.cpp]: update: implemented the suggested changes. the ui now only closes if a switch from/to melee mode happens and relevant nullpointer checks were removed (wasn't able to cause a crash)
