### PR TITLE
Only apply one multiplier to deconstruction results.

### LINKED ISSUE #38982: exponential growth of ammo-components through (batch) disassemble
Hey folks, i didn't look for existing bug reports, so apologies if this has been reported already.

# Describe the bug
Using the disassemble menu, accessible via "(" [i believe..], my character disassembled a bunch of unused ammo and obtained components². Specifically i had 50 rounds of .357 magnum, hit "(" and entered in the prompt to disassemble "050" (amount) of .357 magnum and got 2500 .357 magnum casings and about a proportional amount of other components.

If you look up my save-file, the .357 casings are in the character inventory, there is pile of components under the car, right on the square of the character, and 3 to 6 squares to the north-west is a pile of casings i discarded.

I don't know which ammo types are affected, but it are several and this didn't happen before i updated to new experimental from a 8 month old build.

# Steps To Reproduce

1. take or debug some ammo (probably any type, but at least .357, 00shot, birdshot, .22LR, .380)
2. hit "(" to disassemble , select ammo, enter the full amount you have after the leading zero, hit "enter"
3. take a count of components

# Expected behavior

I don't want to cheat this easy. 

# Screenshots
none

# Versions and configuration

[save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4372445/save.zip)
[config.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4372447/config.zip)

 - OS: Win10
 - Game Version: 0.D-13361-g6fc9301
 - Graphics version: Loaded tileset: UNDEAD_PEOPLE
 - Ingame language: english

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
Fixes #38982 
Certain ammo would double apply a multiplier in the result generation process.

#### Describe the solution
Make the two multipliers mutually exclusive.

#### Testing
Spawn some 00 shot and a kinetic bullet puller.
Increase skills to insure success.
Disassemble a number of rounds at once.
Verify the correct amount of materials are produced.

### CODE REVIEW

File: src/crafting.cpp [hunk 1]
```diff
@@ -2203,14 +2203,13 @@ void player::complete_disassemble( item_location &target, const recipe &dis )
...
             item newit( comp.type, calendar::turn );
-            // Counted-by-charge items that can be disassembled individually
-            // have their component count multiplied by the number of charges.
-            if( dis_item.count_by_charges() && dis.has_flag( flag_UNCRAFT_SINGLE_CHARGE ) ) {
-                compcount *= std::min( dis_item.charges, dis.create_result().charges );
-            }
             //If ammo, overwrite component count with selected quantity of ammo
             if( dis_item.is_ammo() ) {
                 compcount *= activity.position;
+            } else if( dis_item.count_by_charges() && dis.has_flag( flag_UNCRAFT_SINGLE_CHARGE ) ) {
```
Comment (ZhilkinSerg) [inline src/crafting.cpp]: It looks like we can now remove `UNCRAFT_SINGLE_CHARGE` from all deconstruction recipes with ammo result.

Comment (kevingranade) [reply src/crafting.cpp]: Yes it's redundant.

Comment (ZhilkinSerg) [reply src/crafting.cpp]: Okay, I will do that in follow-up PR if nobody would be quicker.
