### PR TITLE
Tune up grenade fragments, fragment generation in general

### LINKED ISSUE #67162: Frag Grenades are OP
### Describe the bug

When frag grenades were first converted over to using the shrapnel system, they worked about like you'd expect, chewing up soft targets but working poorly against armor, and failing against really powerful enemies. At some point, something changed, and now they pretty much one-shot any enemy in the game. Shoggoths, skeletal juggernauts, the melded task force, kraken, frog mother, and jabberwock all get one-shotted by a single frag grenade, which easily does 400-700 damage even a couple of tiles away.

A note in the task force's JSON suggests that this is entirely unintentional:  

> "//": "483 L and HARDTOSHOOT to prevent a frag autokilling them, adjust when grenades are a bit less deadly to large things.",

I'm not totally sure how this happened. I know there were some changes to critical hits that reduced or removed the damage threshold, and changes to shrapnel, especially surrounding shotguns, but I can't pin down the specific PR that caused this.

### Attach save file

n/a

### Steps to reproduce

Make a survivor
Throw a grenade at anything
It dies if it's near the center of the blast unless it's got obscene armor values
Since most powerful monsters are also slow, this is very easy to do

### Expected behavior

I don't think common hand grenades should be one-shotting regenerating armored flesh colossi. Maybe a rocket or something, sure.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.3208 (22H2)
- Game Version: 6060d00 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kevingranade**
This also restores the ability of bomb fragments to pass through occupied tiles.

#### Summary
Balance "Retuned frag grenades to be less effective against ballistic armor and lose power over distance faster"

#### Purpose of change
Fixes #67162 
The inability of fragments to pass though a tile with a monster on it is definitely not intended, fixed that.
I went back and forth on whether the skeletal juggernaught dying to a frag grenade at extreme close range is a problem, but at the end of the day I went ahead and dialed down damage per fragment, and by the time I got balance shuffled around the way I wanted it they're now completely immune to grenades, but still get shredded by pipe bombs and other ordinance with larger fragments.

#### Describe the solution
See my comment in the diff for where the fix to fragments-through-an-occupied-tile happened.
Basically I shrunk the fragment size of the grenade, which means there are more fragments (about 10,000) that each do a much smaller amount of damage.  This is potentially a bit overboard but it meets my goals, and getting this code to work as intended continues to be surprisingly tricky so now that I have it stabilized again I don't want to keep tweaking it.
I also tuned some parts of the algorithm and beefed up feedback on the fragmentation lethality tests.

#### Testing
Adjusted tests pass with a large ish number of runs, need to keep an eye out for fragility.
Ran some manual tests like a grenade in a big horde of zombies or juggernaughts.
spawn a grenade, wield, arm, throw, wait 5 turns, spawn a pile of monsters on top of it, wait another turn.
Zombies: ~30 zombies nearest to the grenade died. Many more wounded.
Skeletal Juggernaughts: Negligible damage. They are wounded dlightly by the blast, but that's like 5 hp.
Frog Mother: The ones immediately adjacent to the grenade died, the rest were wounded heavily but of course started regenerating immediately. This is working as intended, anything without armor is going to have a bad time in close proximity to a fragmentation bomb.

#### Additional Context
If you're skeptical of that damage output, consider this, the official doctrine for the frag grenade this is based on is that an unarmored human within 5m of a detonation has a 95% casualty rate.  Then consider that being *adjacent* to a frag grenade detonation is roughly 16x as damaging, and standing in the same tile as a frag grenade is roughly 12x as damaging as that.  That is multiplicative, so same-tile-as-the-grenade has roughly 196x overkill vs a human.

### CODE REVIEW

File: src/explosion.h [hunk 1]
```diff
@@ -101,6 +101,8 @@ void draw_explosion( const tripoint &p, int radius, const nc_color &col );
 void draw_custom_explosion( const tripoint &p, const std::map<tripoint, nc_color> &area,
                             const std::optional<std::string> &tile_id = std::nullopt );
 
+int ballistic_damage( float velocity, float mass );
+float gurney_spherical( const double charge, const double mass );
```
Comment (kevingranade) [inline src/explosion.h:105]:
```suggestion
float gurney_spherical( double charge, double mass );
```
