### PR TITLE
Power Tools do tool things

### LINKED ISSUE #55472: Angle Grinders Cannot Cut Metal Bars
### Describe the bug

Angle grinders (angle_grinder) do not give the options to cut metal bars despite having the metal sawing 2 quality. I would expect an angle grinder that has enough charges to perform the same function if not even faster that a hacksaw would in cutting metal bars. 

### Steps to reproduce

1. Approach a metal barred window (Gun Store).
2. Spawn an angle grinder with enough battery charge to function.
3. Attempt to activate the angle grinder by either the activate menu or activating the item itself. The examine option does not work either.

### Expected behavior

I would expect an angle grinder that has enough charges to perform the same function if not even faster that a hacksaw would in cutting metal bars. 

### Screenshots

image
image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0 2009
- Game Version: 97018ef [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

_No response_

### LINKED ISSUE #56407: Reciprocating saw cannot be activated.
### Describe the bug

I cannot activate the saw for the base one's uses (wood saw and hacksaw), such as cutting metal, or cutting a tree. Looks like a bug, or an oversight.

### Steps to reproduce

1. Get a reciprocating saw
2. Make sure it's loaded
3. try to activate it
4. 
image

### Expected behavior

I expected it to be able to work on anything hacksaw and wood saw can be used for, due to its available quality when powered.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.1586 (21H2)
- Game Version: d1776b2 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Alternate ear graphics [alt_ear_gfx]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ducanishah**
#### Summary
Features "Angle grinder can cut metal, and is very good at it. Reciprocating saw nerfed to be in line with reality. Aftershock murdersaw gains immense sawing power, and Magiclysm artificer toolkit gets a better hacksaw."

#### Purpose of change
Power tools weren't getting use_methods assigned to them from json based on charged_qualities, and as such could not be used for actions such as cutting metal. This changes that, and makes it so any current and future power tools whose charged_qualities should give them use_methods from the tool_quality json, will get them. 
This PR also increases the metal cutting power of the angle grinder so it can cut through metal five times faster than a hacksaw, because it makes sense.
Buffed the SAW_M of the artificer's magical multitool (twice as fast as a hacksaw, being a magical tool that is, I would imagine, the perfect possible incarnation of a hand hacksaw, but still a hacksaw) and the aftershock murdersaw (10 times faster than hacksaw), being a bigass diamond saw, and sci fi. The safetyless version has sawing quality equivalent to an angle grinder, half as good as the safety-having version. This is because I reason you have to go slower to avoid injuring yourself, but it still cuts incredibly well when you do manage to get it safely wrangled.
Fixes #55472
Fixes #56407

#### Describe the solution
Added code to the itemfactory finalize_pre method to add use_methods based on tool charged_qualities.
Add code to the hacksaw activity_actor to allow arbitrarily higher SAW_M qualities to increase the speed of sawing through gates/windows/fences/bars.

#### Describe alternatives you've considered
Do not make power tools useful.

#### Testing
- [x] Hacksaw on bars
- [x] Angle grinder on bars
- [x] Attempt to use angle grinder on bars without any charge (should not start)
Tested both with no battery and empty battery.
- [x] Angle grinder on bars without enough charge (should cut off partway through)
- [x] Attempt to use hacksaw to continue cutting (should not resume, but restart from beginning)
- [x] Angle grinder reload and resume (should resume, not sure if using hacksaw will drop the activity_actor or not)
This does resume properly, but using a hacksaw in between *does* stop you from resuming with the angle grinder afterwards, which is fine. To note: Using either a hacksaw or angle grinder on *another* set of bars does not reset it, but partially using a hacksaw on the first set of bars *does* reset it, even if you don't fully saw through with the hacksaw. Still fine functionality, though I am curious why the activity_actor with the angle grinder is getting dropped.
- [x] Angle grinder on bars, run out of charge, then reload and use on unrelated set of bars
- [x] Attempt to use angle grinder to resume hacksaw cutting on bars (should start over and take only 3 minutes, not resume)

- [x] Use hacksaw to saw down barrel
- [x] Use angle grinder to saw down barrel
- [x] Try to saw barrel without charge, be denied.
- [x] Spawn reciprocating saw, verify it has no use actions, see that it has the given qualities, try crafting with it with and without charge, confirm it is working as expected.
Tested both wood and metal because I couldn't stand only testing one.

#### Additional context
The TEST_HACKSAW object has been changed to SAW_M 2, so that the expected cutting time matches reality, instead of the prior SAW_M 10 it was at, which under the new system changes the speed.

I had to move the hacksaw can_resume_internal from the activity actor definitions file to the main activity actor file--I needed to make sure tasks would not be resumed with different tools, as this would create unexpected to behavior.
- [x] Maybe fix the whole "separate ammo consumption for different use_methods from json" issue (#54120)
Separate project, separate PR to be made

- [x] Figure out if the sawing barrels menu being messed up is my fault or was around before me--
Unable to reproduce--considering it resolved.
- [x] Figure out what to do with the reciprocating saw, and potentially modify all wood cutting code to respect different levels of SAW_W if it doesn't already
- [x] Possibly make hacksaw tasks resumable with different tools. This will involve reassigning the tool of the activity actor and performing comparison to properly scale remaining moves according to any difference in SAW_M quality.
Not worth it for a feature that will, at worst, cost someone a few minutes of cutting time or part of a medium battery charge. Maybe fun to do sometime just to prove I can, but not something I feel like putting my focus into right now.
- [x] Maybe make angle grinder consume charge to saw down barrel
Would involve migrating the saw_barrel i_use to the activity actor system. While potentially a good learning experienced, I left a good todo and shelved it for now. Might open an issue and mark good first issue, but I'll probably just do it another time.

### CODE REVIEW

File: src/item_factory.cpp [hunk 1]
```diff
@@ -231,6 +231,15 @@ void Item_factory::finalize_pre( itype &obj )
             }
         }
     }
+    for( const auto &q : obj.charged_qualities ) {
+        for( const auto &u : q.first.obj().usages ) {
+            if( q.second >= u.first ) {
+                emplace_usage( obj.use_methods, u.second );
+                // I do not know how to get the ammo scale, so hopefully it naturally comes with the item's scale?
+                //obj.ammo_scale.emplace(u.second, 0.0f);
```
Comment (Night-Pryanik) [inline src/item_factory.cpp:239]:
```suggestion
```
