### PR TITLE
More yield for quartered corpses

### LINKED ISSUE #45962: Quartering a corpse reduces each quarter's yield by a factor of 16, instead of 4
# Describe the bug

Quartering a corpse reduces each quarter's yield by a factor of 16, instead of 4.

# Steps To Reproduce

1. Debug in two animals of the same type.
2. Do "kill all monsters" in debug menu.
3. Animal 1: field dress -> full butcher
4. Animal 2: field dress -> quarter -> full butcher (all 4 quarters)
5. Pile 1 will have close to 4x as much meat as pile 2.

# Expected behavior

Both procedures should yield similar amounts, or perhaps with a small penalty for quartering; certainly not a 75% penalty.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-7242-gb71918d [64-bit]
- Graphics Version: Tiles
- Game Language: English
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by satheon49**
#### Summary

SUMMARY: Balance "Increased yield for butchering quartered corpses"

#### Purpose of change

Fixes #45962

The factor 1/4 was uesd twice for quartering. Once for weight when actually quartering a corpse and a second time when butchering a quartered corpse.

#### Describe the solution

Since weight is already part of the equation butchering four quartered corpses should yield only slightly less meat than an unquartered corpse. I have currently set this to 95%. If anyone thinks this should be higher or lower let me know.

#### Describe alternatives you've considered

Just removing the factor altogether and have four quartered corpses equal one whole corpse.

#### Testing

1. Spawn 2 wild boars, butchering kit, butchering rack and wood saw
2. Killed the boars
3. Field dressed both corpses and quartered one
4. Moved any product of field dressing to other tiles
5. Full butchered quartered and whole corpses and compared yields.

### CODE REVIEW

File: src/activity_handlers.cpp [hunk 1]
```diff
@@ -785,7 +785,7 @@ static void butchery_drops_harvest( item *corpse_item, const mtype &mt, player &
     int monster_weight = to_gram( mt.weight );
     monster_weight += std::round( monster_weight * rng_float( -0.1, 0.1 ) );
     if( corpse_item->has_flag( flag_QUARTERED ) ) {
-        monster_weight /= 4;
+        monster_weight /= 1.05;
```
Comment (olanti-p) [inline src/activity_handlers.cpp:788]: I'm nitpicking here, but this is actually 95.24%. Something like
```suggestion
        monster_weight *= 0.95;
```
would be more readable.
