### PR TITLE
Limit the times a flamer Z can drip napalm.

### LINKED ISSUE #33807: Burner Zombie drops way too much napalm.
# Describe the bug

Burner Zombies drip (250) every so often, but there is no limit too how much they can actually drip, witch means a burner zombie could coat an entire city in napalm.

# Steps To Reproduce

1. Spawn a Burner Zombie in a locked glass room.
2. Wait for a while.
3. The zombie will have dropped way more napalm than he could possibly have in it's flamethrower.

# Expected behavior

There is a point where the zombie would not drip anymore, or maybe not even drip at all since he has a explosive attack that would require fuel and his flamethrower never drops empty.

# Screenshots

Too_much_napalm

Way_too_much_napalm

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.D-7294-ga7a4710
 - Graphics version: Tiles
 - Mods loaded: DDA, Magiclysm, No Rail Stations, Bionic Slots, Disable NPC Needs, SpeedyDex, Stats Through Kills

# Additional context

I was living at the top of the nearby church and the burner wandered into my reality bubble from somewhere I never saw since I have wander spawns turned on.

### PR DESCRIPTION
**Pull request by alkemann**
#### Summary
```SUMMARY: Bugfixes "Limits how much zombies can leak napalm/gasoline"```

#### Purpose of change
Fixes #33807 

#### Describe the solution
Reduced the amount of liquid dropped, added pressurized tank as ammo to the Z and reduce the amount in the tank each time it leaks. Only leak if more in tank.

#### Describe alternatives you've considered
Using the set_value/get_value on the creature to remember how much it has already leaked.

#### Additional context
There is a similar flag for gasoline drip, but as far as I can tell it is not currently used by any monster, so this PR does not "fix" the endless drop for them.

### CODE REVIEW

**Comment by alkemann** [comment]
Initial attempt has a compile failure even though I do the exact same as in item:
```
ccache c++  -DRELEASE -DMACOSX -DGIT_VERSION -DOSX_SDL2_LIBS -DTILES -DBACKTRACE -ffast-math -Os  -Werror -Wall -Wextra -Wmissing-declarations -Wold-style-cast -Woverloaded-virtual -Wpedantic    -fsigned-char  -std=c++14 -MMD -MP -mmacosx-version-min=10.14 -I/usr/local/include/SDL2 -D_THREAD_SAFE -I/usr/local/include -c src/addiction.cpp -o obj/tiles/addiction.o
In file included from src/character.h:22,
                 from src/player.h:21,
                 from src/activity_type.cpp:14:
src/creature.h:365:13: error: 'int Creature::get_value(const string&) const' cannot be overloaded with 'std::string Creature::get_value(const string&) const'
  365 |         int get_value( const std::string &key ) const;
      |             ^~~~~~~~~
src/creature.h:364:21: note: previous declaration 'std::string Creature::get_value(const string&) const'
  364 |         std::string get_value( const std::string &key ) const;
      |                     ^~~~~~~~~
make: *** [obj/tiles/activity_type.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from src/character.h:22,
                 from src/player.h:21,
                 from src/addiction.cpp:8:
src/creature.h:365:13: error: 'int Creature::get_value(const string&) const' cannot be overloaded with 'std::string Creature::get_value(const string&) const'
  365 |         int get_value( const std::string &key ) const;
      |             ^~~~~~~~~
src/creature.h:364:21: note: previous declaration 'std::string Creature::get_value(const string&) const'
  364 |         std::string get_value( const std::string &key ) const;
      |                     ^~~~~~~~~
make: *** [obj/tiles/addiction.o] Error 1
In file included from src/character.h:22,
                 from src/player.h:21,
                 from src/avatar.h:12,
                 from src/action.cpp:10:
src/creature.h:365:13: error: 'int Creature::get_value(const string&) const' cannot be overloaded with 'std::string Creature::get_value(const string&) const'
  365 |         int get_value( const std::string &key ) const;
      |             ^~~~~~~~~
src/creature.h:364:21: note: previous declaration 'std::string Creature::get_value(const string&) const'
  364 |         std::string get_value( const std::string &key ) const;
      |                     ^~~~~~~~~
make: *** [obj/tiles/action.o] Error 1
In file included from src/character.h:22,
                 from src/player.h:21,
                 from src/avatar.h:12,
                 from src/activity_item_handling.cpp:12:
src/creature.h:365:13: error: 'int Creature::get_value(const string&) const' cannot be overloaded with 'std::string Creature::get_value(const string&) const'
  365 |         int get_value( const std::string &key ) const;
      |             ^~~~~~~~~
src/creature.h:364:21: note: previous declaration 'std::string Creature::get_value(const string&) const'
  364 |         std::string get_value( const std::string &key ) const;
      |                     ^~~~~~~~~
make: *** [obj/tiles/activity_item_handling.o] Error 1
In file included from src/character.h:22,
                 from src/player.h:21,
                 from src/avatar.h:12,
                 from src/activity_handlers.cpp:20:
src/creature.h:365:13: error: 'int Creature::get_value(const string&) const' cannot be overloaded with 'std::string Creature::get_value(const string&) const'
  365 |         int get_value( const std::string &key ) const;
      |             ^~~~~~~~~
src/creature.h:364:21: note: previous declaration 'std::string Creature::get_value(const string&) const'
  364 |         std::string get_value( const std::string &key ) const;
      |                     ^~~~~~~~~
make: *** [obj/tiles/activity_handlers.o] Error 1
```

**Comment by Qrox** [comment]
The two functions have the same paramter list, while `get_var` in `item` have different default parameters. You can either add default parameter to the two function if that makes sense, or rename the new function.

**Comment by alkemann** [comment]
So you can only overload with different return types if you also change arguments at the same time?

**Comment by AMurkin** [comment]
[Function return types are not considered for uniqueness](https://www.learncpp.com/cpp-tutorial/76-function-overloading/).

File: src/monmove.cpp [hunk 1]
```diff
@@ -1474,12 +1474,19 @@ bool monster::move_to( const tripoint &p, bool force, const float stagger_adjust
     }
 
     if( has_flag( MF_DRIPS_NAPALM ) ) {
-        if( one_in( 10 ) ) {
-            g->m.add_item_or_charges( pos(), item( "napalm" ) );
+        if( true ) { // one_in( 10 ) // removed randomness to test
```
Comment (AMurkin) [inline src/monmove.cpp]:
```cpp
if( true )
```
I know, it's a draft, but do not do it, please.

Comment (alkemann) [reply src/monmove.cpp]: :) Normally I wouldn't have pushed with that. But I was seeking help with the compiling and needed the code pushed to continue from home computer. Point taken.

**Comment by BevapDin** [comment]
We already have `monster::ammo` to store how much ammo (gun bullets) it contains, why can't you use that for the napalm counter? (Note that this is already handled correctly for dying and for resurrected monsters.)

**Comment by alkemann** [comment]
Just because ignorance of that as a thing I could use BevapDin. I'll investigate, thanks

**Comment by alkemann** [comment]
@BevapDin it seems from a glance without really understanding the details that the Burner zombie is not in fact wielding/carrying a flamethrower, but that one will be generated with a random amount of charges upon death. Meaning there isn't an item to check/modify before the point of death. Am I understanding this correctly?

File: src/monmove.cpp [hunk 2]
```diff
@@ -1474,12 +1474,23 @@ bool monster::move_to( const tripoint &p, bool force, const float stagger_adjust
...
+            // grab the pressurized tank from the monster
+            // find out how much is in it,
+            int store = ammo["pressurized_tank"];
+            // if it has more napalm, drop some and reduce ammo in tank
+            if( store > 0 ) {
+                g->m.add_item_or_charges( pos(), item( "napalm" ) ); // TODO how to set amount leaked
```
Comment (BevapDin) [inline src/monmove.cpp]: Use `map::spawn_item` - it has an explicit `charges` parameter so you can set the amount of spawned napalm. Or create the `item` instance with an explicit charges amount (see constructor of `item` - the `qty` parameter sets its charges).

Comment (alkemann) [reply src/monmove.cpp]: Hey. when spawning with that method, it drops jerry cans instead of the liquid

Comment (alkemann) [reply src/monmove.cpp]: Hey. when spawning with that method, it drops jerry cans instead of the liquid. I got it working with the item() by just adding a number.

**Comment by alkemann** [comment]
How much and often should it drop now that it will drop significantly less. 

A consequence of this change is that these Zs will empty their tanks before the player comes in physical/visual contact.

File: src/monmove.cpp [hunk 3]
```diff
@@ -1475,11 +1475,19 @@ bool monster::move_to( const tripoint &p, bool force, const float stagger_adjust
 
     if( has_flag( MF_DRIPS_NAPALM ) ) {
         if( one_in( 10 ) ) {
-            g->m.add_item_or_charges( pos(), item( "napalm" ) );
+            // if it has more napalm, drop some and reduce ammo in tank
+            if( ammo["pressurized_tank"] > 0 ) {
```
Comment (alkemann) [inline src/monmove.cpp]: Does this need an "isset" check for a case where the `MF_DRIPS_NAPALM` flag is added to a monster without giving that monster the right ammo type?

**Comment by alkemann** [comment]
Should I remove the support for int set/get values on Creature since it is not used by the change? It seems a general valuable addition though.

**Comment by kevingranade** [comment]
Please remove it, dead code is no bueno.
