### PR TITLE
Fix segfault when loading save game activity backlog

### LINKED ISSUE #42844: Segfault / crash on attempt to load save file
# Segfault crash on attempt to load save file attached

# Steps To Reproduce
Load the attached save file.

# Versions and configuration

 - OS: Windows 10
 - Game Version: 0.E.4943-ge0136e2
 - Graphics version: Tiles
 - Ingame language: English
 - Mods loaded: Disable NPC Needs, No Fungal Monsters

[Fernan Lake Village.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5049225/Fernan.Lake.Village.zip)
[crash-logs.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5049226/crash-logs.zip)

### PR DESCRIPTION
**Pull request by 790**
#### Summary

SUMMARY: Bugfixes "Fix segfault when loading save game activity backlog"

#### Purpose of change

Fixes a crash when loading save games that have activity backlog pointing to a the wrong item with a different container size.
Fixes #42844

#### Describe the solution

Check the container is as least as big as the item index it's looking for and throw a debug message instead of crashing.

#### Describe alternatives you've considered

Fixing the bad targets getting into save games. This is the ideal solution but for now this is just a quick crash fix so saves can load and it's probably a good check to have anyway.

#### Testing

Applied fix and loaded save game, no longer crashes and instead shows debug messages.

#### Additional context

This seems to have arisen from another bug where the save games activity backlog ends up containing ACT_MENU_EAT or ACT_CONSUME_DRINK_MENU, and perhaps others, having invalid targets to items in containers, this doesn't fix that bug, just the crash so people can load their saves, although other issues may arise due to pointing at the wrong containers.

The offending backlog entry in my save:

```
{
        "type": "ACT_EAT_MENU",
        "actor": null,
        "moves_left": 21474836,
        "index": -1,
        "position": -2147483648,
        "coords": [],
        "coord_set": [],
        "name": "",
        "targets": [
          {
            "idx": -1,
            "type": "in_container",
            "parent": {
              "type": "map",
              "pos": [
                63,
                69,
                0
              ],
              "idx": 24
            }
          }
        ],
        "placement": [
          -2147483648,
          -2147483648,
          -2147483648
        ],
        "values": [
          0,
          27
        ],
        "str_values": [
          ""
        ],
        "auto_resume": false,
        "monsters": []
      }
```

### CODE REVIEW

File: src/item_location.cpp [hunk 1]
```diff
@@ -718,9 +718,15 @@ void item_location::deserialize( JsonIn &js )
...
         }
         const std::list<item *> parent_contents = parent->contents.all_items_top();
-        auto iter = parent_contents.begin();
-        std::advance( iter, idx );
-        ptr.reset( new impl::item_in_container( parent, *iter ) );
+        if( idx > -1 && idx < static_cast<int>( parent_contents.size() ) ) {
+            auto iter = parent_contents.begin();
+            std::advance( iter, idx );
+            ptr.reset( new impl::item_in_container( parent, *iter ) );
+        }
```
Comment (ZhilkinSerg) [inline src/item_location.cpp:725]:
```suggestion
```

File: src/item_location.cpp [hunk 2]
```diff
@@ -718,9 +718,15 @@ void item_location::deserialize( JsonIn &js )
...
+        else {
```
Comment (ZhilkinSerg) [inline src/item_location.cpp:726]:
```suggestion
        } else {
```
