### PR TITLE
NPCs: fix crash involving UPS weapons

### LINKED ISSUE #34491: UPS based weapons cause NPC to crash
# Describe the bug

Giving a NPC a UPS based weapon causes crash when trying to speak to them after they have it wielded. 

# Steps To Reproduce

1. Make a player with a A7 RIfle, with a loaded UPS in inventory.
2. Have a NPC follower.
3. Give UPS(loaded) to NPC.
4. Have NPC use A7 rifle. NPC will wield.
5. Try to talk to NPC.

# Expected behavior

Being able to equip a NPC with an A7 rifle. Having NPC be able to use A7 rifle. Being able to talk to npc after its equipped as normal.

# Screenshots

**If applicable**, add screenshots to help explain your problem.

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.D-8200-g1ba9252 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

 - 
[Crash.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3693640/Crash.zip)
# Additional context

### PR DESCRIPTION
**Pull request by mlangsdorf**
#### Summary
```SUMMARY: Bugfixes "NPCs: fix crash involving UPS weapons"```

#### Purpose of change
Fixes #34491

NPCs with UPS weapons would crash while deciding their needs
because they tried to dereference a variable that doesn't exist
for UPS weapons.

#### Describe the solution
Special case UPS weapons in decide_needs(), and assign their rank based on the number of available UPS shots.

#### Describe alternatives you've considered
It might be worthwhile to add `need_ups` and `need_battery` needs, but that can be put off until NPC looting improves.

#### Testing
Without the commit, I gave an NPC a laser rifle and a loaded UPS and confirmed that the game crashed when I talked to them.  I applied the commit and talked to the NPC again and the game did not crash.  I also spawned a zombie master; the NPC shot the zombie master with the laser rile.  I talked to the NPC again and there were fewer charges in the UPS.

### CODE REVIEW

File: src/npc.cpp [hunk 1]
```diff
@@ -1455,7 +1455,15 @@ void npc::decide_needs()
         elem = 20;
     }
     if( weapon.is_gun() ) {
-        needrank[need_ammo] = 5 * get_ammo( ammotype( *weapon.type->gun->ammo.begin() ) ).size();
+        int ups_drain = weapon.get_gun_ups_drain();
+        if( ups_drain > 0 ) {
+            int ups_charges = has_charges( "UPS_off", ups_drain ) +
```
Comment (ZhilkinSerg) [inline src/npc.cpp]: I don't get the idea.

`has_charges` returns Boolean. You either get sum of two `true` or sum of two `false`, so basically either 2 or 0.

Comment (mlangsdorf) [reply src/npc.cpp]: Doh!  I thought it turn the amount.  I want charges_of(), don't I?

Comment (ZhilkinSerg) [reply src/npc.cpp]: Yes, looking into doxygen it should be it.

Comment (mlangsdorf) [reply src/npc.cpp]: Fixed, thanks.

File: src/npc.cpp [hunk 2]
```diff
@@ -1455,7 +1455,15 @@ void npc::decide_needs()
         elem = 20;
     }
     if( weapon.is_gun() ) {
-        needrank[need_ammo] = 5 * get_ammo( ammotype( *weapon.type->gun->ammo.begin() ) ).size();
+        int ups_drain = weapon.get_gun_ups_drain();
+        if( ups_drain > 0 ) {
+            int ups_charges = charges_of( "UPS_off", ups_drain ) +
+                              charges_of( "UPS_off", ups_drain );
+            needrank[need_ammo] = ups_charges / ups_drain;
```
Comment (ZhilkinSerg) [inline src/npc.cpp]: Need to do something with clang tidy here.

```
/home/travis/build/CleverRaven/Cataclysm-DDA/src/npc.cpp:1462:35: error: result of integer division used in a floating point context; possible loss of precision [bugprone-integer-division,-warnings-as-errors]

            needrank[need_ammo] = ups_charges / ups_drain;
```

Comment (mlangsdorf) [reply src/npc.cpp]: silently upconvert you silly machine!  I'll add the explicit cast to shut it up.
