### PR TITLE
Fix unmountable turret bug

### LINKED ISSUE #39436: Cannot install weapon in vehicle turrent mount
# Describe the bug

Unable to install weapons in a vehicle turret mount. Installation menu cannot find item, can find all other ingredients (tools / skills).

# Steps To Reproduce

1. Create new character with tools (e.g. Home Mechanic)
2. Set skills to 10 with debug menu
3. Spawn a new Humvee with debug menu
4. Remove mounted M240
5. Attempt to reinstall M240

# Expected behavior

Installation menu allows installation of turret weapons.

# Screenshots

turret-bug

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-468-g9e02bc1 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food]
]

### PR DESCRIPTION
**Pull request by OddSkollar**
#### Summary
SUMMARY: Bugfixes "Players unable to mount turrets on vehicles."

#### Purpose of change
Fixes #39436

#### Describe the solution
Very small change to item::allow_crafting_component(); prior to fix it was incorrectly registering guns themselves as contained objects, preventing eligibility for mounting.

#### Describe alternatives you've considered
None, I want to play with my new ballista.

#### Testing
image

#### Additional context
I only found the bug's location, Korg provided the code.

### CODE REVIEW

File: src/item.cpp [hunk 1]
```diff
@@ -8048,7 +8048,10 @@ bool item::allow_crafting_component() const
     // fixes #18886 - turret installation may require items with irremovable mods
     if( is_gun() ) {
         bool valid = true;
-        visit_items( [&valid]( const item * it ) {
+        visit_items( [&]( const item * it ) {
+            if ( this == it ) {
```
Comment (ZhilkinSerg) [inline src/item.cpp:8052]:
```suggestion
            if( this == it ) {
```

**Comment by OddSkollar** [comment]
Sorry, I have very little idea of what Travis/CI does or why it's angry, will have to figure that out in the morning.

I also don't know how to attach labels and apologize for that additional overhead.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/mods-unleashed-compilation-for-e-v-1-0-experimental-v-0-01/22725/97
