### PR TITLE
Fix undefined behavior with can_examine on keycard readers

### LINKED ISSUE #51525: Game crashes when walking next to laboratory card reader.
### Describe the bug

Game crashes when standing in any tile adjacent to a laboratory card reader.

### Steps To Reproduce

1.Make a character
2.Teleport to laboratory
3.Go to any tile adjacent to a card reader.

### Expected behavior

Game not crashing.

### Screenshots

_No response_

### Versions and configuration

- OS: Android
    - OS Version: Manufacturer: Xiaomi; Model: Redmi Note 8; Release: 11; Incremental: 9650; 
- Game Version: 4d92cc6 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions]
]

### Additional context

[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7148042/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/7148043/debug.log)
[Save.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/7148066/Save.zip)

I have a custom ROM installed, ArrowOS v.11 with Ryzen kernel, I've tried multiple ROMs and kernels just in case the issue was the phone but this isn't the case.
I've also tried multiple different worlds and versions to no avail, however this bug is not present in the latest stable version so it must've been introduced in one of the experimentals, I don't know which though.
I can't test this on the PC version because I currently don't have a PC.

### PR DESCRIPTION
**Pull request by Musteval**
#### Summary
Bugfixes "Fix crash when walking near card readers on some platforms"

#### Purpose of change

Fixes #51525 

#### Describe the solution

Ensure that iexamine_functions is always set, and remove some cruft I forgot to take out of mapdata.h on my previous PR.

#### Describe alternatives you've considered

I don't really like having two separate instance variables like this - it might be better to rewrite all the iexamine_functions handlers to also be actors with no state. But that'd be a bigger PR.

#### Testing

Was not able to reproduce the crash on PC, but:
- Ensured that cardreaders had `iexamine_functions_from_string( "none" )` rather than undefined as their iexamine_functions, saw card readers stop working (so previously this was working based on UB)
- Updated can_examine to return true if examine_actor is set, saw card readers start working again
- Walked around forest examining things, saw it work and not crash

### CODE REVIEW

File: src/mapdata.cpp [hunk 1]
```diff
@@ -1301,6 +1301,7 @@ void map_data_common_t::load( const JsonObject &jo, const std::string & )
         JsonObject data = jo.get_object( "examine_action" );
         examine_actor = iexamine_actor_from_jsobj( data );
         examine_actor->load( data );
+        examine_func = iexamine_functions_from_string( "none" );
```
Comment (anothersimulacrum) [inline src/mapdata.cpp:1304]: I think it is error prone and wrong to give something both an examine func and a examine actor, because it means we can potentially accidentally ignore the actor for the terrain/furniture - I think a hard failure is better than a silent one.

Comment (MarlossCDDA) [reply src/mapdata.cpp:1304]: Well, examine_func is a reference not a pointer, so I don't think I can just set it to NULL - it's this, some other function, or undefined behavior.

Comment (actual-nh) [reply src/mapdata.cpp:1304]: I don't suppose one could create an interface function, so that trying to invoke its examine_func would invoke the examine_actor instead? I haven't looked at the code in question, admittedly.

**Comment by actual-nh** [comment]
The error is a UB being caught - in rad_scorch, which I doubt has anything to do with this PR.

File: src/mapdata.cpp (hunk 1 above)
Comment (anothersimulacrum) [reply src/mapdata.cpp:1304]: Or we go the simple route and make an iexamine that complains loudly about being used. I'd recommend that.

Comment (MarlossCDDA) [reply src/mapdata.cpp]: 57bb662

File: src/iexamine.cpp [hunk 2]
```diff
@@ -227,6 +227,12 @@ bool iexamine::always_false( const tripoint &/*examp*/ )
     return false;
 }
 
+bool iexamine::false_and_debugmsg( const tripoint &/*examp*/ )
+{
+    debugmsg( "Called false_and_debugmsg - was a terrain with an actor configured incorrectly?" );
```
Comment (actual-nh) [inline src/iexamine.cpp]: Why not do `get_map().tername( examp )` here also, as with `invalid`?

File: src/iexamine.cpp [hunk 3]
```diff
@@ -6330,6 +6343,8 @@ iexamine_functions iexamine_functions_from_string( const std::string &function_n
         iexamine_examine_function func = iter->second;
         if( function_name == "none" ) {
             return iexamine_functions{&iexamine::always_false, func};
+        } else if( function_name == "invalid" ) {
+            return iexamine_functions{&iexamine::false_and_debugmsg, func};
```
Comment (actual-nh) [inline src/iexamine.cpp:6347]: Not part of this PR, but it would be nice to be a bit clearer about which iexamine functions actually return a value (without needing to look at the function itself or its specification in a header file).

**Review by actual-nh — APPROVED** [review]

File: src/iexamine.cpp (hunk 3 above)
Comment (MarlossCDDA) [reply src/iexamine.cpp:6347]: I'm actually thinking it'd be better to just make "is examinable" a method on iexamine_actor along with `call()` and rip out most of what I added in my previous PR - gonna try and take a stab at that this week.

**Review by anothersimulacrum — APPROVED** [review]
