### PR TITLE
Several tweaks regarding deployable furniture

### LINKED ISSUE #62171: Error when placing stepladder in open air
### Describe the bug

`a`ctivating a stepladder to place it over a ledge, such as off the roof of a one-story building, produces an error like this:

```
 DEBUG    : Setting furniture f_ladder at (71,67,1) where terrain is t_open_air (which is_open_air)
If this is intentional, set the ALLOW_ON_OPEN_AIR flag on the furniture

 FUNCTION : furn_set
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\map.cpp
 LINE     : 1616
 VERSION  : 579e201
```

Despite this error message, the stepladder will be placed on the level below as expected.

### Steps to reproduce

1. Obtain and wield a stepladder.
2. Navigate to the roof of a one-story building.
3. Walk to the edge of the building.
4. Activate the stepladder and select an open air tile at the edge of the building, one story above ground.

### Expected behavior

The stepladder should be placed on the level below (and it is) but should not produce an error message.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19044.2251 (21H2)
- Game Version: 579e201 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Night-Pryanik**
#### Summary
Bugfixes "Deployed furniture won't be floating anymore if deployed on open air"

#### Purpose of change
* Closes #62171.

#### Describe the solution
Added `ALLOW_ON_OPEN_AIR` flag to wooden and aluminum stepladders.

Also I made two things:
- Deployed furniture will now fall down if deployed on open air;
- Added a prompt asking player if he really wants to deploy a furniture on z-level > 1.

#### Describe alternatives you've considered
None.

#### Testing
While standing next to the ledge on the second floor, activated the stepladder and chose the ledge as destination. Stepladder was deployed on the ground floor, no errors popped up.

#### Additional context
изображение

### CODE REVIEW

**Comment by PatrikLundell** [comment]
What happens if you try that on a higher floor? You shouldn't be allowed to place a ladder in the air at the level below, and I think it would be appropriate to warn the player if it results in the logical result of the ladder being dropped.

**Comment by Night-Pryanik** [comment]
> What happens if you try that on a higher floor?

Stepladders will be floating in the air, but my PR didn't bring it, it's a pre-existing problem.

**Comment by Night-Pryanik** [comment]
Ok, I made two things:
- Deployed furniture will now fall down if deployed on open air;
- Added a prompt asking player if he really wants to deploy a furniture on z-level > 1.
изображение

File: src/iuse_actor.cpp [hunk 1]
```diff
@@ -1095,6 +1095,14 @@ static ret_val<tripoint> check_deploy_square( Character *p, item &it, const trip
                                                 _( "You attempt to become one with the %s.  It doesn't work." ), it.tname() );
     }
 
+    if( pnt.z() > 1 ) {
```
Comment (ehughsbaird) [inline src/iuse_actor.cpp:1098]: You get this message if you try to deploy the anything above the ground floor - I suggest look at how iexamine::ledge determines the number of levels that are open below a point, and check that instead.
https://github.com/CleverRaven/Cataclysm-DDA/blob/8c9ca7a48cc6855311fa53f89fabb6aa9ab879c3/src/iexamine.cpp#L5530-L5537

Comment (ehughsbaird) [reply src/iuse_actor.cpp:1098]: Because the solution will tell me that a ladder I deploy in a stable situation on a roof is going to fall several stories when it is not.

Comment (Night-Pryanik) [reply src/iuse_actor.cpp]: Thanks for the review, issues resolved in [514a65e](https://github.com/CleverRaven/Cataclysm-DDA/pull/77083/commits/514a65eea5749094c823a6bd97fddc5d1dbaff22).
