### PR TITLE
fixed vehicle racking menu

### LINKED ISSUE #47179: Bike racks in certain configurations display phantom names
# Describe the bug

When attempting to unload a racked vehicle in a certain configuration, the game shows two copies of the vehicle's name.

# Steps To Reproduce

1. Load attached save.
2. `e`xamine 1NE and choose to unload vehicle.

# Expected behavior

I suppose I only expected one vehicle to display.

# Screenshots

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 20H2 (build 19042.746)
- Game Version: 0.E-9186-gd2f3109-dirty [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded:
    - Dark Days Ahead [dda],
    - C.R.I.T Expansion Mod [crt_expansion],
    - No Fungal Monsters [No_Fungi],
    - Disable NPC Needs [no_npc_food],
    - Alternative Map Key [alt_map_key],
    - SpeedyDex [speedydex],
    - Stats Through Kills [stats_through_kills],
    - Stats Through Skills [StatsThroughSkills],
    - No Rail Stations [No_Rail_Stations]

# Additional context

The bike racks are in the positions marked by arrows. I am standing in the position marked by X. What may be happening is the game is mirroring the name of the racked vehicle to the other set of bike racks for reasons unknown to man or God because both sets are contiguous.

```
 |===|
 |   |
 |   |
 |   |
>|   |
>|   |
>|===|
X^^^^
```

### PR DESCRIPTION
**Pull request by Jamuro-g**
#### Summary
Bugfixes "Fixes vehicle racking menu. No more duplicates&phantom names"

#### Purpose of change

Overlapping bike rack lines (for example in corners) caused the racking ui prompt to count the vehicle for both rack lines.
It couldn't cause any issues (fixed that in an earlier pr) but it showed basically useless entries.

Fixes #47179

#### Describe the solution

Added a method that checks the found vehicle parts and bike racks for duplicates accross different vehicle entries and removes 
 the "shorter" one.
Basically bike racks accross a cornerpiece would find the same vehicle twice (once the full vehicle and once just the 1 tile at the corner).

#### Describe alternatives you've considered
Rewriting ( and probably splitting) the use_bike_rack method
This issue happens mostly due to how carried vehicles are fetched at the same time and the same way as potential racking candidates.

#### Testing

- Spawn in vehicle with bike racks
- Add bike racks to form a corner (see linked issue for an example)
- Spawn in a bike/motorcycle/... and rack it
- Go to the cornerpiece of the bike racks and activate it to open the racking menu

It no longer should show the racked vehicle twice.

### CODE REVIEW

**Comment by BrettDong** [comment]
I think you can write `validate_carried_vehicles` that works on reference of `std::vector<std::vector<>>` and without recursion. It's expensive to copy `std::vector<std::vector<>>`.

**Comment by Jamuro-g** [comment]
> I think you can write `validate_carried_vehicles` that works on reference of `std::vector<std::vector<>>` and without recursion. It's expensive to copy `std::vector<std::vector<>>`.

that's fair, i am not entirely happy with the recursion either ... i ll take another crack at it during the weekend.

File: src/vehicle_use.cpp [hunk 1]
```diff
@@ -1970,6 +1974,31 @@ void vehicle::use_bike_rack( int part )
...
+    while( it != carried_vehicles.end() ) {
+        for( std::vector<std::vector<int>>::iterator it2 = it + 1; it2 < carried_vehicles.end(); it2++ ) {
+            if( std::search( ( *it2 ).begin(), ( *it2 ).end(), ( *it ).begin(),
+                             ( *it ).end() ) != ( *it2 ).end() ) {
+                it = carried_vehicles.erase( it );
+            }
+        }
+        it++;
+    }
+    return carried_vehicles;
```
Comment (BrettDong) [inline src/vehicle_use.cpp:1998]: Now you are modifying the parameter reference in-place so you don't need return value anymore.

Comment (Jamuro-g) [reply src/vehicle_use.cpp]: updated

File: src/vehicle_use.cpp [hunk 2]
```diff
@@ -1970,6 +1974,30 @@ void vehicle::use_bike_rack( int part )
...
+
+    std::vector<std::vector<int>>::iterator it = carried_vehicles.begin();
+    while( it != carried_vehicles.end() ) {
+        for( std::vector<std::vector<int>>::iterator it2 = it + 1; it2 < carried_vehicles.end(); it2++ ) {
+            if( std::search( ( *it2 ).begin(), ( *it2 ).end(), ( *it ).begin(),
+                             ( *it ).end() ) != ( *it2 ).end() ) {
+                it = carried_vehicles.erase( it );
+            }
+        }
+        it++;
```
Comment (BrettDong) [inline src/vehicle_use.cpp:1996]: Will this skip and omit an element when erase happens in the inner loop? IIRC erase returns an iterator to the next element after the erased one.
