### PR TITLE
Make trying to fall asleep a player activity, not effect

### LINKED ISSUE #25708: Trying to sleep is uninterruptible while zombie bashing your car/allies
**Describe the bug**  
It is an old but very annoying problem. If your toon try to sleep but can’t, the time passes without interrupt. If this time zombies attack your vehicle, your allies etc. you can’t react to the danger.

Here a lone zombie broke my windshield and fight with a friendly NPC while my toon tried to sleep:
[screenshot](https://discourse-cdn-sjc2.com/standard11/uploads/cataclysmdda/original/2X/0/087075066ec23b64bd4ef3ecfe4eb8b68756b181.png)

**To Reproduce**  
1) Debug a car.
2) Debug a zombie few steps away from the car the way the zombie can see you
3) Try to sleep and watch the spam messages about the zombie bashing your car.

**Expected behavior**  
Trying to sleep should be interruptable like reading, butchering, etc.

**Versions and configuration(please complete the following information):**
 - OS: Win 7 x64
 - Game Version: 0.C-32309-g6e7b56a
 - Graphics version: Tiles
 - Mods loaded: defaults

### LINKED ISSUE #25711: When your sleep is interrupted the screen does not update
**Describe the bug**  
If you sleeping but a noise wakes you up then the screen shows only the dark screen like you still sleeping until your next move.

**To Reproduce**  
1. Debug a car.
2. Set your fatigue to 500 (d,1,n,f,500)
3. Debug a zombie few steps away from the car the way the zombie can see you
4. Go to sleep and wake up when the zombie starts to bash your car. You will just see some question marks but everything else is dark like when you sleep.

**Expected behavior**  
See your surrounding like when you wake up properly.

**Versions and configuration(please complete the following information):**
 - OS: Win 7 x64
 - Game Version: 0.C-32309-g6e7b56a
 - Graphics version: Tiles
 - Mods loaded: defaults

**Additional context**  
It is not a new bug at least few months old. There was a screen update error in Jun - it was [fixed](https://github.com/CleverRaven/Cataclysm-DDA/pull/24038) - maybe related to it.
[Here](https://discourse.cataclysmdda.org/t/screen-refreshing-problems-7468/15718) is the forum topic about it.

### PR DESCRIPTION
**Pull request by alanbrady**
#### Summary
```SUMMARY: Bugfixes "Make trying to sleep into an activity"```

#### Purpose of change
The way trying to sleep currently works is you just pass out for 30 minutes and then we check if you're actually asleep.

This changes it so you first start trying to fall asleep and we keep checking until either we fall asleep or, if we set an alarm, the alarm goes off, or if 24 hours passes we'll give up.

This new activity can of course be interrupted manually with `.` or by creatures wandering around nearby or all the other usual interruptions to activities.

This fixes the problem of zombie mobbing by using an activity instead of the weird lying down effect which appears to just make you pass out for 30 minutes.

#### Describe the solution
Refactor trying to fall asleep into a player activity instead of a "lying down effect".

I refactored a chunk of the hardcoded "lying down" effect into a player function so I could reuse it.

Also, because this calls "can_sleep" every turn to determine if we can sleep while in the activity, I added a time barrier to the can_sleep call because there's a bit of randomness to the call.

I also changed the sleep menu so that it aborts the menu on invalid input.

#### Additional Context
This doesn't actually remove the effect `effect_lying_down` although I'm not actually sure how useful it is anymore.  It *looks* like NPCs still use it for stuff although I don't see a reason they can't also use this new activity.  Leaving it alone for now.

#### Testing Hints
I tested them, but third-party validation should check trying to sleep/actually sleeping with:
- Alarm clock
- Bionic clock
- Proximity Sensor
- No clock
- Asthma
- Creature attacks
- Hearing loud noises

[removed UI pictures since there is now no longer a new menu]

Fixes #25708
Fixes #25711

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -9839,14 +9845,59 @@ bool player::can_sleep()
...
+        if( one_in( 15 ) ) {
+            add_msg_if_player( _( "You snuggle your %s to keep warm." ), item_name.c_str() );
+        } else {
+            add_msg_if_player( _( "You use your %s to keep warm." ), item_name.c_str() );
+        }
+    }
+    if( has_active_mutation( trait_id( "HIBERNATE" ) ) && get_hunger() < -60 ) {
+        add_memorial_log( pgettext( "memorial_male", "Entered hibernation." ),
+                          pgettext( "memorial_female", "Entered hibernation." ) );
+        // some days worth of round-the-clock Snooze.  Cata seasons default to 14 days.
```
Comment (Night-Pryanik) [inline src/player.cpp]: " Cata seasons default to 14 days." it's 91 now.

Comment (alanbrady) [reply src/player.cpp]: Good catch, I didn't add this but was shifted code.  Will fix.

**Comment by narc0tiq** [comment]
I'm wondering if we should ask the player at all -- being an activity (thus, interruptible at any point), I have no problem taking the player at their word when they say they want to sleep, and assume they mean to keep trying until they succeed.

In brief testing, this seems to interact poorly with setting an alarm: the alarm timer apparently only starts when you fall asleep, whereas I expected it to start when the activity starts. Specifically:
- *Given* a character who has just slept (and will therefore not fall asleep in the next 3 hours),
- *When* I tell her to try to sleep for an indeterminate period **and** set an alarm in 3 hours (the minimum possible),
- *Then* I expect the alarm to interrupt her attempt to sleep in 3 hours.

Instead, she just kept failing to fall asleep; I didn't validate that she would've slept for exactly 3 hours after finally falling asleep, but assume that would be the case.

**Comment by alanbrady** [comment]
> I'm wondering if we should ask the player at all -- being an activity (thus, interruptible at any point), I have no problem taking the player at their word when they say they want to sleep, and assume they mean to keep trying until they succeed.

I'm open to this idea.  It does remove choice but saves key-presses.  It seems reasonable.

> In brief testing, this seems to interact poorly with setting an alarm: the alarm timer apparently only starts when you fall asleep, whereas I expected it to start when the activity starts.

I thought I tested this and it started after trying to sleep.  I'll check it out and fix it.

Thanks!

**Comment by alanbrady** [comment]
I made your recommended changes @narc0tiq and I believe I fixed the alarm clock thing.  Let me know what you think.

File: src/handle_action.cpp [hunk 2]
```diff
@@ -769,15 +770,18 @@ static void sleep()
...
         }
-    }
 
-    as_m.query();
-    if( as_m.ret >= 3 && as_m.ret <= 9 ) {
-        u.add_effect( effect_alarm_clock, 1_hours * as_m.ret );
+        as_m.query();
+        if( as_m.ret >= 3 && as_m.ret <= 9 ) {
+            u.add_effect( effect_alarm_clock, 1_hours * as_m.ret );
+            try_sleep_dur = 1_hours * as_m.ret;
```
Comment (narc0tiq) [inline src/handle_action.cpp]: I just noticed this line sets the `try_sleep_dur` to the time-to-alarm; that explains why one time my player gave up trying to sleep before the alarm went off while the second time I got the expected beep-beep-beep and such. At a guess, sometimes the activity will process before the `effect_alarm_clock`, and other times the alarm will process first.

I don't think that's unrealistic (I imagine the character taking a look at the clock, seeing the alarm is about to trigger, and just abandoning the sleep attempt -- something I've done myself at times), just mentioning something you might've missed.

**Comment by narc0tiq** [comment]
The alarm definitely worked now; I'm also much happier without the third uimenu, so that definitely worked for me. From a player perspective, this feels very good right now. I've also taken a brief look around the code and everything looks sane; that said, I just keep up the build system, so maybe I missed something.

I did have a quick grammar note: I'd expect two words for "alarm clock" rather than the hyphenated "alarm-clock" (which I just noticed). Not a show-stopper, by any means, but also an easy fix.

Thanks for the changes, I do like them quite a bit!

**Comment by narc0tiq** [comment]
I did just notice "You fall asleep" popped up twice, but unsure why. Could `player::fall_asleep()` be getting called twice?

**Comment by alanbrady** [comment]
> I just noticed this line sets the try_sleep_dur to the time-to-alarm; that explains why one time my player gave up trying to sleep before the alarm went off while the second time I got the expected beep-beep-beep and such. At a guess, sometimes the activity will process before the effect_alarm_clock, and other times the alarm will process first.

> I don't think that's unrealistic (I imagine the character taking a look at the clock, seeing the alarm is about to trigger, and just abandoning the sleep attempt -- something I've done myself at times), just mentioning something you might've missed.

Hrm... this is unexpected for me, I'm not sure how that would have happened.  I'll test it some more.  I agree it's not a big deal for this to happen, but it is unexpected and perhaps indicative of some bug I missed.

>I did have a quick grammar note: I'd expect two words for "alarm clock" rather than the hyphenated "alarm-clock" (which I just noticed). Not a show-stopper, by any means, but also an easy fix.

I agree here, I was going with consistency since the other alarm clock messages use a hyphen.  I don't mind fixing.

> I did just notice "You fall asleep" popped up twice, but unsure why. Could player::fall_asleep() be getting called twice?

Hrm... might be related to the alarm clock not going off in some situation.  Something is definitely a little squirrel-ly I think.  I again didn't notice this in my testing but I likely missed it.

**Comment by alanbrady** [comment]
Ok this is truly bizarre.  If you grep for "You fall asleep" string, it only exists in two places and only one of them can be triggering here.  If I change the string in fall_asleep, the second one, unchanged, is still printing from somewhere, which seems impossible to me.  Putting a trace in fall_asleep verifies it's not getting called a second time, it's coming from somewhere else.  What. the. hell.

**Comment by alanbrady** [comment]
Derp nevermind, I found the other string, it's getting pulled from json/effects.json.  Shouldn't this mean the You fall asleep x2 message has been there before this patch?

File: src/sounds.cpp [hunk 3]
```diff
@@ -332,15 +332,23 @@ void sounds::process_sound_markers( player *p )
...
                     p->add_msg_if_player( _( "Your alarm-clock wakes you up." ) );
+                } else {
+                    p->add_msg_if_player( _( "Your alarm-clock went off and you haven't slept a wink." ) );
                 }
                 p->add_msg_if_player( _( "You turn off your alarm-clock." ) );
             }
-            p->get_effect( effect_alarm_clock ).set_duration( 0_turns );
+            if( !trying_to_sleep ) {
+                p->get_effect( effect_alarm_clock ).set_duration( 0_turns );
+            }
```
Comment (Qrox) [inline src/sounds.cpp]: I'm not sure if this line is correct. If the player wakes up to some noise not coming from the alarm (like a zombie knocking at the door), `trying_to_sleep` will be true, and the alarm clock effect will not be cleared, which might cause problems if they try to sleep for a second time without setting the alarm.

Comment (alanbrady) [reply src/sounds.cpp]: Looking at this again I think you're correct.  I'm not certain why I thought checking for trying_for_sleep was necessary.  Will fix.  Thanks!
