### PR TITLE
Uneccesary debug message when picking a door that gets bashed.

### LINKED ISSUE #56948: Error when door gets smashed in middle of lockpicking
### Describe the bug

I was in middle of picking a lock on the door, when it was smashed from another side by a zed, resulting in caught error popping up, so I was able to simply continue playing the game.

Error log:
```
12:41:54.974 ERROR : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\activity_actor.cpp:2281 [finish] t_door_b lockpick_result is null
```

### Steps to reproduce

1. Start lockpicking the door while zed starts bashing it from another side.
2. ??
3. Profit!

### Expected behavior

I would expect the action to fail gracefully, not error out.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.22598.100 (22H2)
- Game Version: a820c3e [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by psuedolet**
#### Summary
Bugfixes "Replace the debug message when an actively picked door gets bashed with a player message"

#### Purpose of change
Remove a debug message that unnecessarily pops up during a normal game event. It's acceptable for pickable terrain/furniture to transform into non-pickable terrain/furniture, while the player is attempting to pick it. So don't show an error message. Fixes #56948 

#### Describe the solution
Instead of showing a debug message, add a player message informing them that they can't open this lock.

#### Describe alternatives you've considered
1. Add support for terrain/furniture to have a "lockpick_message" without a "lockpick_result" as an way to explicitly define un-pickable objects in JSON.

### CODE REVIEW

File: src/activity_actor.cpp [hunk 1]
```diff
@@ -2269,7 +2269,7 @@ void lockpick_activity_actor::finish( player_activity &act, Character &who )
 
     if( here.has_furn( target ) ) {
         if( furn_type->lockpick_result.is_null() ) {
-            debugmsg( "%s lockpick_result is null", furn_type.id().str() );
+            who.add_msg_if_player( m_bad, _( "You can't open this lock" ) );
```
Comment (Night-Pryanik) [inline src/activity_actor.cpp:2272]:
```suggestion
            who.add_msg_if_player( m_bad, _( "You can't open this lock." ) );
```

File: src/activity_actor.cpp [hunk 2]
```diff
@@ -2279,7 +2279,7 @@ void lockpick_activity_actor::finish( player_activity &act, Character &who )
         }
     } else {
         if( ter_type->lockpick_result.is_null() ) {
-            debugmsg( "%s lockpick_result is null", ter_type.id().str() );
+            who.add_msg_if_player( m_bad, _( "You can't open this lock" ) );
```
Comment (Night-Pryanik) [inline src/activity_actor.cpp:2282]:
```suggestion
            who.add_msg_if_player( m_bad, _( "You can't open this lock." ) );
```
