### PR TITLE
fix: allow negative floats in external options

### LINKED ISSUE #79993: External options: FLT_MIN doesn't mean smallest float
### Describe the bug

I have just spent a good hour tracking down a bug with external options apparently not parsing negative floats.

Introduced by Kevin in https://github.com/CleverRaven/Cataclysm-DDA/pull/38886, it seems like the assumption was that FLT_MIN is similar to INT_MIN, but it's not, it's actually the smallest **positive** float, which means external options with `"sType": "float"` will silently make negative values 0 on receive.

Change to -FLT_MAX at https://github.com/CleverRaven/Cataclysm-DDA/blob/2f958ecebfa58c21949b4851c4df2de9c8971383/src/options.cpp#L331
[or use numeric_limits]

### Attach save file

N/A

### Steps to reproduce

N/A

### Expected behavior

N/A

### Screenshots

_No response_

### Versions and configuration

N/A

### Additional context
Image

### PR DESCRIPTION
**Pull request by scarf005**
#### Summary
Bugfixes "Allow negative float values in external options"

#### Purpose of change

fixes #79993 

#### Describe the solution

use `std::numeric_limits` for mininum float value

#### Describe alternatives you've considered

not that i can think of.

#### Testing

write a negative value in float option, see it's correctly loaded as negative value.

### CODE REVIEW

**Comment by ZhilkinSerg** [comment]
```PATCH
diff --git a/src/options.cpp b/src/options.cpp
index 0bcfa323ac..af359b11b0 100644
--- a/src/options.cpp
+++ b/src/options.cpp
@@ -322,14 +322,14 @@ void options_manager::add_external( const std::string &sNameIn, const std::strin
             thisOpt.bDefault = false;
             break;
         case cOpt::CVT_INT:
-            thisOpt.iMin = INT_MIN;
-            thisOpt.iMax = INT_MAX;
+            thisOpt.iMin = std::numeric_limits<int>::lowest();
+            thisOpt.iMax = std::numeric_limits<int>::max();
             thisOpt.iDefault = 0;
             thisOpt.iSet = 0;
             break;
         case cOpt::CVT_FLOAT:
-            thisOpt.fMin = FLT_MIN;
-            thisOpt.fMax = FLT_MAX;
+            thisOpt.fMin = std::numeric_limits<float>::lowest();
+            thisOpt.fMax = std::numeric_limits<float>::max();
             thisOpt.fDefault = 0;
             thisOpt.fSet = 0;
             thisOpt.fStep = 1;
```

**Review by RenechCDDA — APPROVED** [review]
Very funky bug, reasonable approach to resolve it.

File: src/options.cpp [hunk 1]
```diff
@@ -4,6 +4,7 @@
 #include <climits>
 #include <clocale>
 #include <iterator>
+#include <limits>
```
Comment (ZhilkinSerg) [inline src/options.cpp:7]: It is already included through `climits` above.

Comment (GuardianDll) [reply src/options.cpp:7]: IWYU failed to run twice, i am not sure is it an issue of this pr or not
ill restart it again, but i suspect it would fail this time either

Comment (moxian) [reply src/options.cpp:7]: it's an issue with IWYU setup, not with this PR.
I'll take a look, but a bit later, I'm very busy this week.

Basically, if IWYU fails with no obvious "please fix your includes!!!" error - it's a setup issue and can be ignored/treated as passing.
