### PR TITLE
[READY] Ranged balance unit test

### LINKED ISSUE #19718: The buildbot is dormant
It doesn't seem to be checking PRs at the moment.

### LINKED ISSUE #21158: Automatic fire, perfect target switching
An A7 laser rifle on automatic fire will do a 5-round burst, but I've now noticed several times that when it takes less rounds to kill an enemy, the character may change its target on the fly and fire the remaining rounds with perfect accuracy at another target, even if aiming direction differs by 30° or more.

This is not how auto-fire works, especially not if you use careful or precise aim. There should be no target switching in the middle of a burst.
untitled

### LINKED ISSUE #21244: Gun accuracy calculation broken
Players reporting of massive reducing in firearm accuracy.
Forum thread:
http://smf.cataclysmdda.com/index.php?topic=14523.0

Looks like we have massive regression after that:
https://github.com/CleverRaven/Cataclysm-DDA/pull/20941

This issue should be set as milestone to 0.D and probably marked as "Priority" because shooting is one of the core mechanics of the game.

### PR DESCRIPTION
**Pull request by kevingranade**
First stab at an automated test to ensure ranged balance as outlined in #21244 
Fixes #21244 
Fixes #19718
Fixes #21158 

- [x] NPCs need gear loadouts, they're currently naked.
- [x] Decrease quickdraw accuracy.
~~- [ ] Apply 5x increase to MAX_RECOIL and related values in a more consistent way.~~
- [x] Need to increase mid-range accuracy across the board.
- [x] Reduce accuracy at very high aim levels in some cases.
~~- [ ] Apply dispersion scaling changes to item definitions instead of as an override.~~
- [x] Evaluate new use cases.
- [x] add upper and lower caps on aim speed.
- [x] communicate new system to player.

### CODE REVIEW

**Comment by Coolthulhu** [comment]
RNG has to be there until you write a CD function for your distribution.
CDF for a sum of uniform variables is basically brute force approach: simulate all possible rolls, calculate distribution. Still, most likely better than relying on RNG.
That's a good reason not to use sum of random variables (except maybe as Irvin-Hall, for which there are known formulas).

One important thing those tests should test should be distribution of hit types, not just binary hit/miss.
And even if not test exactly yet, at least print.

**Comment by kevingranade** [comment]
Wild firing without aiming fails, it's too accurate.

File: tests/ranged_balance.cpp [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+    shooter.wear_item( item( "backpack" ) );
+
+    // Give shooter a loaded gun of the requested type.
+    item &gun = shooter.i_add( item( gun_id ) );
+    const itype_id ammo_id = gun.ammo_default();
+    if( gun.magazine_integral() ) {
+        item &ammo = shooter.i_add( item( ammo_id, calendar::turn, gun.ammo_capacity() ) );
+	REQUIRE( gun.is_reloadable_with( ammo_id ) );
+	REQUIRE( shooter.can_reload( gun, ammo_id ) );
+	gun.reload( shooter, item_location( shooter, &ammo ), gun.ammo_capacity() );
```
Comment (Coolthulhu) [inline tests/ranged_balance.cpp]: The test files could use some styling. For example, tabs->spaces.

File: tests/ranged_balance.cpp [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+    tripoint target_pos( shooter.pos() + tripoint( range, 0, 0 ) );
+    monster &test_target = spawn_test_monster( "debug_mon", target_pos );
+
+    item &gun = shooter.weapon;
+
+    dispersion_sources dispersion =
+      shooter.get_weapon_dispersion( gun,
+                                     rl_dist( shooter.pos(), test_target.pos() ) );
+    dispersion.add_range( std::max( static_cast<double>( gun.sight_dispersion() ),
+                                    shooter.recoil_total() * ( 1.0 - aim_ratio ) ) );
```
Comment (Coolthulhu) [inline tests/ranged_balance.cpp]: `recoil_total` would probably just return `RECOIL_MIN`, except when something is weirdly initialized or after burst.
But `projectile_attack` doesn't increase recoil.

File: tests/ranged_balance.cpp [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+}
+
+static void test_shooting_scenario( npc &shooter, std::string gun_type,
+                                    int minimum_range, int good_range )
+{
+    clear_map();
+
+    statistics minimum_stats = firing_test( shooter, gun_type, 0.0, minimum_range );
+    INFO( "Accumulated " << minimum_stats.n() << " samples." );
+    CHECK( minimum_stats.avg() < 0.01 );
```
Comment (Coolthulhu) [inline tests/ranged_balance.cpp]: Why 1%? That's very strict, especially when you're counting grazes and not just good hits.

File: tests/ranged_balance.cpp [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+    statistics firing_stats;
+    do {
+        // Top off target hp to make sure it doesn't die.
+        test_target.set_hp( test_target.get_hp_max() );
+        // Calling projectile_ttack() instead of fire_gun() because it returns wether it was a hit or not.
+        // Conviniently, it also avoids consuming the ammo.
+        dealt_projectile_attack shot =
+          projectile_attack( make_gun_projectile( gun ), shooter.pos(), test_target.pos(),
+                             dispersion, &shooter, nullptr );
+        firing_stats.add( shot.hit_critter != nullptr );
```
Comment (Coolthulhu) [inline tests/ranged_balance.cpp]: Would be more meaningful to count only hits above certain threshold of accuracy.
Grazes are relatively common and their damage is at most 1/8 of base damage. For weak firearms, it means no damage against even moderately armored targets.

File: tests/ranged_balance.cpp (hunk 1 above)
Comment (kevingranade) [inline tests/ranged_balance.cpp]: I'm partially waiting on #21494 and partially just being sloppy since I'm still rewriting large sections of it as I go.  Will be 100% astyled by the time I mark it ready to merge.

File: tests/ranged_balance.cpp (hunk 3 above)
Comment (kevingranade) [inline tests/ranged_balance.cpp]: Why not? If it starts failing we can adjust, but in this case we're asserting "almost never hits", so I'd like to be as strong as is practical.
Note I'm not rejecting your request to factor in hit quality, I'm just filling this out in what I think is the best order, I'll circe back around to check if hit quality is practical to extract once I have the use cases covered.

File: tests/ranged_balance.cpp (hunk 4 above)
Comment (kevingranade) [inline tests/ranged_balance.cpp]: If it's practical to make assertions about hit quality, I'll also make assertions about it, but grazes aren't meaningless to make assertions about.

File: tests/ranged_balance.cpp (hunk 2 above)
Comment (kevingranade) [inline tests/ranged_balance.cpp]: Good catch, this isn't doing remotely the right thing.

Comment (kevingranade) [inline tests/ranged_balance.cpp]: Actually I think it is doing what I want right now, but it's farly fragile, I should just use RECOL_MIN.

File: tests/ranged_balance.cpp (hunk 3 above)
Comment (Coolthulhu) [inline tests/ranged_balance.cpp]: Well, the test cases may need adjusting then.
Almost always missing at 5 tiles is comparable to reliably missing broad side of the barn from inside.

Comment (kevingranade) [inline tests/ranged_balance.cpp]: You might have missed the detail that this is with no aiming at all, this is effectively the quickdraw scenario.
Also it's not remotely a barn-sized target, it's exactly analagous to shooting at a person-sized and shaped target at the stated range.  Depending on how we set up our range adjustment, that 5-tile range will almost certainly be equivalent to 20' or so, at which point a novice always missing a man-sized target when quickdrawing is perfectly reasonable.

Comment (Coolthulhu) [inline tests/ranged_balance.cpp]: I wouldn't enforce "always misses" on novices. It may be reasonable to expect it, but it only complicates things when balancing.
It does matter for experts - those certainly need to be capped from above, but again - 1% cap is really strict, at this point it's a problematic limitation that doesn't test an in-game situation.

Any hit rate below 10% that includes grazes is well into not being worth it for proper firearms. It would make sense for pneumatics or lasers, where ammunition is very cheap, but firearms are expensive to maintain and also loud.
It's basically a statistical outlier - one that is not worth including in the model.
If you bumped the rate to at least 10%, it would both become more practical and easier to actually enforce without breaking other values.

But then again, going for capping the 10% "good hit" rate would be even better. It would test actual in-game effects, not implementation details.

Comment (kevingranade) [inline tests/ranged_balance.cpp]: I'll agree to the extent that assertions about "solid hits" are higher value than assertions about "technical hits", and if we do encounter a deadlock while balancing, the "technical hits" are the ones to relax.

**Comment by kevingranade** [comment]
Needed a massive overhaul for performance reasons, it was taking multiple seconds to complete, and it's just going to continue to get worse over time.
Two major changes were to call projectile_attack_roll() and make assertions about missed_by (solid order of magnitude improvement) and to inject the desired thresholds into the test fixture so it could bail out once the confidence intervals shrunk to not include any desired thresholds.  This also allows us to make assertions about several hit qualities at the same range, but that might end up being unecessary.

This covers the bases outlined in #21244 but needs some additional tweaking and then of course the actual balance changes.

- [ ] NPCs need gear loadouts, they're currently naked.
- [ ] Guns need to be geared up when appropriate, currently it only uses vanilla guns.

**Comment by kevingranade** [comment]
Constraint for quickdraw turned out to be overly-agressive after all, it took dropping it to one hit out of 10, increasing the range slightly and increasing MAX_RECOIL (and associated values) by 5x to enforce it properly, but that did it and it seems like a workable adjustment, the original MAX_RECOIL was just a shot in the dark after all *rimshot*.

**Comment by kevingranade** [comment]
For context, "completely unaimed" is now 3,000 MOA, which in more accessable terms, is roughly 3" (radius) per tle of distance.  That doesn't sound like much, but it's 5x as high as it used to be, and it's plenty to make you miss when added to other sources of inaccuracy.  I'm pretty happy with that result, it actually gives us a basis for what unaimed accuracy should be as opposed to it being totally arbitrary.

This does cause a problem though, now that aiming is a lot faster, it's more of a no-brainer to keep aiming to the maximum, since the spike in accuracy at the very end is extremely high.
I think we need a progressive aim speed, but before that, we need some expectations around aiming speed as well, otherwise the fixes to accuracy are quite likely to end up wrecking other parts of the system.

**Comment by Firestorm01X2** [comment]
How abot add relation between aming speed and player weapon skill so unexpirienced player aims slower.

**Comment by kevingranade** [comment]
It's already there.

**Comment by kevingranade** [comment]
Additional info, I wrote a test to find the dispersion value where hit rate exceeds 50% at various ranges, and here's the output:
  Range: 1 Dispersion: 1785
  Range: 2 Dispersion: 891
  Range: 3 Dispersion: 582
  Range: 4 Dispersion: 426
  Range: 5 Dispersion: 342
  Range: 6 Dispersion: 301
  Range: 7 Dispersion: 245
  Range: 8 Dispersion: 216
  Range: 9 Dispersion: 192
  Range: 10 Dispersion: 169
  Range: 11 Dispersion: 147
  Range: 12 Dispersion: 146
  Range: 13 Dispersion: 133
  Range: 14 Dispersion: 120
  Range: 15 Dispersion: 114
  Range: 16 Dispersion: 107
  Range: 17 Dispersion: 101
  Range: 18 Dispersion: 95
  Range: 19 Dispersion: 90
  Range: 20 Dispersion: 85
  Range: 21 Dispersion: 82
  Range: 22 Dispersion: 78
  Range: 23 Dispersion: 74
  Range: 24 Dispersion: 72
  Range: 25 Dispersion: 69
  Range: 26 Dispersion: 66
  Range: 27 Dispersion: 63
  Range: 28 Dispersion: 49
  Range: 29 Dispersion: 49
  Range: 30 Dispersion: 49
  Range: 31 Dispersion: 49
  Range: 32 Dispersion: 49
  Range: 33 Dispersion: 49
  Range: 34 Dispersion: 49
  Range: 35 Dispersion: 49
  Range: 36 Dispersion: 49
  Range: 37 Dispersion: 46
  Range: 38 Dispersion: 45
  Range: 39 Dispersion: 44
  Range: 40 Dispersion: 42
  Range: 41 Dispersion: 41
  Range: 42 Dispersion: 40
  Range: 43 Dispersion: 40
  Range: 44 Dispersion: 39
  Range: 45 Dispersion: 38
  Range: 46 Dispersion: 37
  Range: 47 Dispersion: 36
  Range: 48 Dispersion: 36
  Range: 49 Dispersion: 34
  Range: 50 Dispersion: 34
  Range: 51 Dispersion: 34
  Range: 52 Dispersion: 33
  Range: 53 Dispersion: 32
  Range: 54 Dispersion: 21
  Range: 55 Dispersion: 21
  Range: 56 Dispersion: 21
  Range: 57 Dispersion: 21
  Range: 58 Dispersion: 21
  Range: 59 Dispersion: 21
  Range: 60 Dispersion: 21

File: src/character.cpp [hunk 5]
```diff
@@ -195,10 +195,10 @@ double Character::aim_per_move( const item& gun, double recoil ) const
     }
 
     // get fastest sight that can be used to improve aim further below @ref recoil
-    int cost = INT_MAX;
+    int sight_cost = INT_MAX;
     int limit = 0;
     if( !gun.has_flag( "DISABLE_SIGHTS" ) && effective_dispersion( gun.type->gun->sight_dispersion ) < recoil ) {
-        cost  = std::max( std::min( gun.volume() / 250_ml, 8 ), 1 );
```
Comment (kevingranade) [inline src/character.cpp]: Balance aside, this is a bugfix.  The previous version based aiming speed for unmodded guns on gun size, then completely ignored it once a sight ws added.

File: src/ranged.cpp [hunk 6]
```diff
@@ -1475,14 +1473,17 @@ static bool is_driving( const player &p )
...
 }
 
-
 // utility functions for projectile_attack
-dispersion_sources player::get_weapon_dispersion( const item &obj, float range ) const
+dispersion_sources player::get_weapon_dispersion( const item &obj ) const
 {
-    dispersion_sources dispersion = obj.gun_dispersion();
-
+    int weapon_dispersion = std::max( obj.gun_dispersion() / 3, 45 );
```
Comment (kevingranade) [inline src/ranged.cpp]: The division by three and minimum dispersion value are temporary fixes, they need to be applied across the weapon definitions.

**Comment by kevingranade** [comment]
All tests pass now.
See 8f13efec26c5d36aad1deade263f4fc1bb51804f for the balance adjustments, as well as a few changes to test criteria.

File: src/character.cpp [hunk 7]
```diff
@@ -207,43 +207,49 @@ double Character::aim_per_move( const item& gun, double recoil ) const
...
+    double aim_speed = 0.0;
 
+    // Ranges [0 - 10]
     /** @EFFECT_PISTOL increases aiming speed for pistols */
     /** @EFFECT_SMG increases aiming speed for SMGs */
     /** @EFFECT_RIFLE increases aiming speed for rifles */
     /** @EFFECT_SHOTGUN increases aiming speed for shotguns */
     /** @EFFECT_LAUNCHER increases aiming speed for launchers */
-    cost += ( ( MAX_SKILL / 2 ) - get_skill_level( gun.gun_skill() ) ) * 2;
+    aim_speed += std::max( MAX_SKILL, static_cast<int>( get_skill_level( gun.gun_skill() ) ) );
```
Comment (Coolthulhu) [inline src/character.cpp]: Looks like it should be `min`.

File: src/character.cpp [hunk 8]
```diff
@@ -1559,6 +1565,18 @@ int Character::get_int_bonus() const
...
+int Character::ranged_dex_mod() const
+{
+    ///\EFFECT_DEX <12 increases ranged penalty
+    return std::max( ( 12 - get_dex() ) * 15, 0 );
+}
+
+int Character::ranged_per_mod() const
+{
+    ///\EFFECT_DEX <12 increases ranged aiming penalty
+    return std::max( ( 12 - get_per() ) * 15, 0 );
```
Comment (Coolthulhu) [inline src/character.cpp]: Back to those horrible thresholds?

File: src/character.cpp (hunk 7 above)
Comment (kevingranade) [reply src/character.cpp]: Yes it should, thanks, that'll throw the balance back out of whack so I'll need to tweak things a bit.

File: tests/ranged_balance.cpp [hunk 9]
```diff
@@ -0,0 +1,275 @@
...
+    bool threshold_within_confidence_interval = false;
+    do {
+        projectile_attack_aim aim = projectile_attack_roll( dispersion, range, 0.5 );
+        threshold_within_confidence_interval = false;
+        for( int i = 0; i < accuracy_levels.size(); ++i ) {
+            firing_stats[i].add( aim.missed_by < accuracy_levels[i] );
+            if( thresholds[i] == -1 ) {
+                continue;
+            }
+            if( firing_stats[i].n() < 100 ) {
```
Comment (Coolthulhu) [inline tests/ranged_balance.cpp]: I'm not sure if I understand what is happening here.
If the test has been performed for less than 100 samples, it should end?

Comments would really help a lot here.

File: tests/ranged_balance.cpp [hunk 10]
```diff
@@ -0,0 +1,275 @@
...
+{
+    {
+        dispersion_sources dispersion = get_dispersion( shooter, 0 );
+        std::array<statistics, 5> minimum_stats = firing_test( dispersion, min_quickdraw_range, {{ 0.2, 0.1, -1, -1, -1 }} );
+        INFO( dispersion );
+        INFO( "Range: " << min_quickdraw_range );
+        INFO( "Max aim speed: " << shooter.aim_per_move( shooter.weapon, MAX_RECOIL ) );
+        INFO( "Min aim speed: " << shooter.aim_per_move( shooter.weapon, shooter.recoil ) );
+        CHECK( minimum_stats[0].avg() < 0.2 );
+        CHECK( minimum_stats[1].avg() < 0.1 );
```
Comment (Coolthulhu) [inline tests/ranged_balance.cpp]: Those unnamed arrays could use an enum to address them. `minimum_stats[GRAZE]` is so much clearer than `minimum_stats[0]`.

**Comment by Coolthulhu** [comment]
How does the 5x MAX_RECOIL translate to actual gameplay?
Judging by comparison to how inaccurate current 600 recoil is, the 5x MAX_RECOIL will feel not like quickdraw, but like the character actually forgot to raise the gun from the holster.

**Comment by kevingranade** [comment]
It roughly enforces the invariants I outlined above, it's practically impossible to hit something outside of point-blank range if you don't aim.

More precisely point blank range is around 4 squares away if nothing else is interfering with your aim (i.e. play with the quickdraw range in the "expert_shooter_accuracy" test).  Outside of this range hit rate is under 10% for hits, and under 20% for even grazing hits. Inside this range the hit rate climbs, but it never gets particularly good.  Still, players will generally be able to rely on a point-blank shot before the monster starts smacking them around.

**Comment by Coolthulhu** [comment]
> Still, players will generally be able to rely on a point-blank shot before the monster starts smacking them around.

Grazing or sensible?
The ability to sneak in some good shots in between attacks from zombies is vital to making small arms usable. Pistols rely on being able to shoot on the move, where each move resets aim back to MAX_RECOIL.
If aim time from "freshly moved" to "50%+ chance of good+ hit" is above one turn, the gun becomes unusable in close quarters against anything big enough to consider using a gun on, unless the player can already outrun and outkite the thing.
Rifles can afford to be unreliable, as they already rely on range and burst damage. Pistols (other than laser) are absolutely dependent on reliability to have a niche.

**Comment by kevingranade** [comment]
> If aim time from "freshly moved" to "50%+ chance of good+ hit" is above one turn, the gun becomes unusable in close quarters against anything big enough to consider using a gun on, unless the player can already outrun and outkite the thing.

I'm fairly certain you can sneak shots in between enemy turns, but if you can't it's totally reasonable, guns should not work in melee, but I'm not worrying about enforcing that right now.

**Comment by Coolthulhu** [comment]
> guns should not work in melee

Well, they don't. No need to nerf that further beyond what is in master right now, as this will only further nerf already weak guns (pistols).
Or you could say they actually work all too well, because the best possible gun attack is an assault rifle burst at 1 tile range, but changing MAX_RECOIL does not affect that.

**Comment by kevingranade** [comment]
"What's in master right now" is not a valid balance target, if you think guns need to be usable in some particular use case, you need to articulate what that means so it can be enforced with a test.

Let me be more clear, the use case of "I want to use guns in melee" is not valid, so it does not influence the implementation.

**Comment by Coolthulhu** [comment]
All right.
Let's try it like this:

Gunner | Weapon | Aim moves | Min good at 3 tiles
--- | --- | --- | ---
Weak | Rifle | 100 | 20%
Weak | SMG | 80 | 30%
Weak | Shotgun | 50 | 30%
Weak | Pistol | 40 | 30%
Competent | Rifle | 100 | 30%
Competent | SMG | 70 | 40%
Competent | Shotgun | 50 | 50%
Competent | Pistol | 30 | 50%
God | Rifle | 100 | 40%
God | SMG | 60 | 50%
God | Shotgun | 50 | 75%
God | Pistol | 20 | 60%

3 tile range means `@..X`. That is, 1 tile range is melee, 3 tile range is two more. Assuming square distance mode.
When in doubt, rule of fun first, as long as it doesn't turn the whole idea upside down. That is, as long as rifles don't reach pistol's aim target before pistol does (they can reach their own faster, just not overtake pistols).

Assumptions:
* Weak gunner isn't using any relevant mods
* Competent gunner has unspecialized sights and generic (non-high-tier, not specialized for close range) replacements
* God gunner is using sights specialized for quick aiming and has gun customized for close range
* The weapon used is roughly generic for its category, not a carbine nor a giant sniper rifle, not holdout pistol but not a magnum with more mods than ammo capacity. It must use a relevant caliber ammo (ie. rifle caliber) and have properties expected from weapon type (rifle and SMG have burst, pistol fits in holster).
* Aim reset thing means that player is turning around while moving rather than just taking a step back with the gun on the target. That is, disengaging completely, lowering the weapon etc. This is not particularly realistic, but it's better to go with this assumption for now than to get contradictory results by assuming that taking a step back results in completely losing all aim yet does not involve upper body movement. Similar for changing aim from target to target.

Rationale:
* 3 tiles is roughly the length of a car in game. At this point, we can assume it's close combat and it will always look bad if at this range player can't hit anything in sensible time
* Aim time of less than a turn is important. If you can swing a plank and fully recover in a turn, you should be able to point the gun at target's center of mass in that time.
* Pistols are small, maneuverable, they don't need to be held in a very specific position to allow a tolerable quality hit at this very close range. In an emergency, firing them one handed is possible.
* Shotguns can be hip-fired in a pinch, hence lower aim time. Assuming straight grip here. This is a bit exaggerated for fun and balance, but may not actually need significant mechanical changes as buckshot currently has very low dispersion. Pistol grip shotguns can use rifle times here. Those should be kept weak early on, but at competent gunner it's better to buff than nerf them.
* Rifles are assumed to be assault rifles with pistol grips (real life pistol grips, not necessarily the gunmod). At least for competent and god gunners (weak can do with hunting).
* SMGs as usual - somewhere in between. Due to small caliber, they need to advance relatively fast, as they will miss out on their niche otherwise. When in doubt, buff those rather than nerfing.

When in doubt, let non-rifle guns be too strong for a while. They can be balanced by nerfs that also affect rifles.

**Comment by kevingranade** [comment]
Repeating:
> Let me be more clear, the use case of "I want to use guns in melee" is not valid, so it does not influence the implementation.

I'm not going to stall this PR to add a bunch of tests and adjust balance to preserve a use case that isn't valid.  The niche for guns is shooting targets at a distance, not close combat.  I will tolerate them being effective in close combat for now, but I fully intend to implement some form of [continuous dodging](http://smf.cataclysmdda.com/index.php?topic=14811.0) later, specifically to make the use case you're describing untenable.

The tests seem to be a little flaky still, I need to address that, and I'll review your use cases in case any of them are usable despite your rationales being invalid.

> When in doubt, rule of fun first

This is nonsensical to invoke with no qualifications. It's sensible to say, "it's unfun to have no options for dealing with challenges", but that's not remotely the case here, where you have innumerable options for dealing with challenges based on using these and other weapons as they are designed to be used.

You seem to be arguing for a definition of fun that demands turning the game into an action-movie-like power fantasy where everything you do has a chance of working no matter how absurd.
Some things you try won't work, that's part of the challenge.

>  If you can swing a plank and fully recover in a turn, you should be able to point the gun at target's center of mass in that time.

That's utterly invalid, melee attacks occur in split seconds, firearms are fundamentally much slower than that.  Hollywood and most games don't follow this distinction, but it's reality.  Our representation of melee combat is also off-base in this context, but that doesn't make your argument valid, the simplified distinction is that melee weapons are usable in melee and ranged weapons are not.

> Pistols are small, maneuverable, they don't need to be held in a very specific position to allow a tolerable quality hit at this very close range.

This is incorrect, untill you're literally within arm's reach, improper form with a pistol will lead to frequent misses.  If we're focusing on 3 tile ranges, form is critical.

> Shotguns can be hip-fired in a pinch.

This is some combination of wrong and irrelevant, again unless you're within arm's reach, hip-firing a shotgun is going to lead to you simply missing, additionally, even if you do hip-fire, it doesn't mean you spend no time settling your aim.

**Comment by Coolthulhu** [comment]
> You seem to be arguing for a definition of fun that demands turning the game into an action-movie-like power fantasy where everything you do has a chance of working no matter how absurd.

No, I'm arguing for a game where every option presented as viable is viable. As opposed to your implementation where after moving towards an opponent, pistol whipping them is literally - honestly, non-jokingly, unironically - more effective and easier to execute than shooting them with said pistol.
I'm also arguing for "power reality" where pulling out a pistol is more likely to trigger "oh my god he has a gun" than ">9mm shiggy diggy" and "bullets too slow, I can just run up to you and punch you to death".

> I'm not going to stall this PR to add a bunch of tests and adjust balance to preserve a use case that isn't valid. The niche for guns is shooting targets at a distance, not close combat.

You added a [CR] to the PR name, so I'm commenting. If you don't care about player (and game designer) perspective, you can self-merge right now and no one will revert it.

From me, it gets a failing grade for as long as it worsens the already horrible low aim accuracy and further slides into the "aim (nearly) fully or don't shoot at all" anti-design and thus noticeably increases the divide between good guns (rifles) and bad guns (pistols).

It also gets extra negative points for bringing back stat thresholds, thus blandifying character generation and preventing specialization, but that's a smaller issue.

**Comment by Firestorm01X2** [comment]
About close range shhoting. You know, "shotugn to the face" is poluar design solution for alot of games. It works well.

As far as I remeber accuracy drops significantly if player getting hit in close range already. Probaly it is enough for now.

**Comment by kevingranade** [comment]
> every option presented as viable is viable.

What does this even mean?  How do you determine if an action is "presented as viable"?  There are inumerable actions you can perform in this game, and whether they're viable or not is a matter of whether they work when you try them.
We certainly don't have messaging anywhere that says, "if you find a zombie 2 tiles away, try pulling out a gun to deal with it".

> pistol whipping them is literally - honestly, non-jokingly, unironically - more effective and easier to execute than shooting them with said pistol.

Once you're in melee range, that's actually the case.  The scenario where using a pistol in melee range is actually effective is wrestling the pistol into place at melee range and pulling the trigger.  We don't have a system that represents this (off the top of my head this would be something like my continuous dodge proposal, plus switchcing aiming from being firearms based to being a contest between the player and monster's melee skills), including your proposal to allow extemely quick aiming.  I'd be happy to entertain such a system, but that's not what you're suggesting.  Also such a system is out of scope for this PR.

> You added a [CR] to the PR name, so I'm commenting.

I'm not telling you you shouldn't comment, or that I'm upset about you commenting, I just don't agree with you and I'm providing my rationale.

> If you don't care about player (and game designer) perspective,

That's just rude.  One, you're conflating your own opinion wth "the will of the player", and second, you're characterizing my disagreement with your position as "don't care about".  I care a lot about player and designer opinions, and you in particular frequently have very good ideas.  However we have a fundamental disconnect about what the goal of this game is, which results in me deeply disagreeing with some of your positions.

> Is there reason to do it entirely different, apart from "Realism"? 

No, but that's how the design for dda works.
Is there a reason to do it "like the other games" other than, "it's what other games do"?

**Comment by DemAvalon** [comment]
I know I have no business puting my opinion here but...

> Is there a reason to do it "like the other games" other than, "it's what other games do"?

this is a very compelling reason:http://tvtropes.org/pmwiki/pmwiki.php/Main/RuleOfFun

If you don't take Coolthulhu's proposal into consideration (about range) you might as well remove pistols from the game, because no one will use them.

there is a term for this, but I can't remember the name, the basic idea is that once the player discovers the best possible move they will always do it and then they will disregard less effective strategies.

> pistol whipping them is literally - honestly, non-jokingly, unironically - more effective and easier to execute than shooting them with said pistol.
>Once you're in melee range, that's actually the case. The scenario where using a pistol in melee range is actually effective is wrestling the pistol into place at melee range and pulling the trigger. 

why would the player ever do that? if pistols can't compete with other guns on range and are useless on melee, players will simply not use them.

you need to stop thinking of this game in "real world" therms and instead as a video game (which it is), instead of thinking "this sounds reasonable to me" you need to think "what will the players think of this?, how will the player react to this?".

I know the game is free and that you do it out of your on will, that you are not payed to do this and it is within your power to disregard anything and everything you don't want into the game, but maybe you should take a step back and think if you should implement something just because "it sounds right to you" rather than "it will improve the player experience".

I say (well type) this with no hint of malice or anger, but rather with concern, I care about this game and it frustrates me that I can't do much to help its development, and it worries me that those that do might be loosing perspective.

so thats all, from a nobody that likes your game a lot.

**Comment by kevingranade** [comment]
> RuleOfFun

Again, that doesn't actually man anything in isolation, you need to make a case for why the change isn't fun, at which point you don't need to invoke RuleOfFun, it's just a discussion about whether a feature is fun or not.

> if pistols can't compete with other guns on range and are useless on melee, players will simply not use them.

Non-exhaustive and unsorted list of reasons to use pistols
1. Can't find a good rifle.
2. more portable
3. Can't find rifle ammo.
3a. Not enough rifle ammo to train rifles skill.
4. Likes pistols better.
5. Faster aiming
6. Shorter time between shots when firing many times.
7. Better ability to aim at short range. (pending)

Please don't tell me either how I think or how I "need to think".  You don't have a clue how much thought I put into this game.  You can disagree with someone without assuming they haven't thought things through.

**Comment by DemAvalon** [comment]
> Can't find a good rifle.

**Any** other firearm is better than **any** pistol (respecting equivalance ex: flintlock rifle/pistol,) with exception to the rare ones finding a firearm that is better than a pistol is trivial as all one needs to do is find any firearm that is not a pistol.

>more portable

The shoulder straps are incredibly easy to craft and allow anyone to just have a high powered rifle/shotgun/grenade launcher with them for the cost of some torso encumberance (there are also back holsters for such weapons)

>Can't find rifle ammo.

shotgun ammo is one of the easiest to find, and a shotgun will out perform a pistol, so instead of carrying a pistol in case they don't have ammo, players will carry SMGs, a shotgun, or even a good melee weapon.

> Not enough rifle ammo to train rifles skill.

there are books to teach gun skills, and NPCs to teach you those as well, once a player discovers that those are more efficient ways of learning their gun skill, they won't even consider wasting ammo unless they need or they have ludicrous amounts.

>Likes pistols better.

This is what rule of fun is all about, but while using the pistols they like, they will be thinking "I wish I could hit anything with this when I can see the white of their eyes"

>Shorter time between shots when firing many times.

Many rifles and SMGs have burst/full-auto modes which allow them to fire many times in an even shorter period of time, also gun mods can make a rifle/smg/shotgun have reduced firing time (while making a fully modded pistol not worthless)


>Better ability to aim at short range. (pending)

burst fire rifles/SMGs and shotguns will cause much more damage in any range the pistol might cover and more.

>Please don't tell me either how I think or how I "need to think". You don't have a clue how much thought I put into this game. You can disagree with someone without assuming they haven't thought things through.

You are absolutely correct and I apologize deeply and sincerely, it's that, from an outsider's perspective, it just looks like you tend to dismiss feedback, but that clearly is not the case and it was presumptuous of me to think otherwise.

I'm very sorry if what I said (well typed) offended you as that was not the intent at all and rather was the result of my poor communications skill and inarticulation that may have caused you to think as such, I'm just some idiot from the internet who likes video games.

Again, I'm very sorry for my rudeness and presumptuous words.

**Comment by Coolthulhu** [comment]
Huge post incoming.
tl;dr Pistols are still too weak because they compete with both rifles and melee, always losing to at least one of those. Also you can't build up pistol skill without grind.

> Faster aiming
> Better ability to aim at short range. (pending)

This would help a lot if it was actually meaningful. The problem with "meaningful" is that it has to be nearly (or actually) an order of magnitude better to actually matter, otherwise the rifle's better damage shines again.
If the pistol was aimed 50% faster, it would somewhat cover the short-range case, but it would still suck at all others, while rifle would do reasonably well at short-range, but exceptionally at all others. At 100% faster (order of magnitude), there would still be penalties for getting hit, but the pistol might have a niche.

Note that pistols always compete not just with rifles, but also with melee. This needs to be considered every time short range accuracy is considered an extra bonus.

> Shorter time between shots when firing many times.

This does matter with precisely one pistol: laser pistol.
All other pistols will eventually run out of ammo in the worst moment, forcing a reload and thus re-aim.
Additionally, firing many shots in short succession often involves compensating for recoil (tons of time loss for pistols with good damage) or switching targets (total loss of aim).

Also, getting the move cost difference to matter more than aim cost requires getting really high skill in the weapon. For pistols, it is unfeasible to get this level in normal play - it requires either dedicated grinding with weak weapons (anyone without autism will get bored of doing this instantly), getting a laser pistol, or some sort of personal challenge like "no killing in melee, ever".

> Not enough rifle ammo to train rifles skill.

You seem to be operating on assumption that it is feasible to train up to "actually really good" skill level in the game just by playing the game and using dropped/reloaded firearm ammo on targets that deserve a bullet (as opposed to being fodder that is easier to just bash down).
This is totally not the case.
There is more easy to access rifle ammo than pistol ammo, as getting 7 mechanics is much easier (faster, less tedious, less risky) than getting 6 rifle or pistol skill. At 7 mechanics, the player can build a pneumatic rifle, which uses rocks as ammo, enabling nearly infinite training.
By the time the player trains gun skills above lvl 5, the player most likely has crafting skills near 8, whole libraries of books in the trunk, possibly laser weapons, melee weapon skills near 8 and so on.

> What does this even mean? How do you determine if an action is "presented as viable"?

Each weapon type that has a skill - which takes a lot of time to grind, starting from 0, with barely any cross-train (lol marksmanship) between the categories - is clearly shown as at least being intended to be viable to the player. As a skill that you could train up to 10 and not regret not picking the Only Good Choice.

I have proposed merging skills, but this was shot down as too much abstraction. In merged categories, an SMG could be an upgrade from pistol just fine, an assault rifle could be a straight upgrade from shotgun and so on. As long as the categories could compete with each other on equal grounds, that is.

Now we have pistols that are just plain worse than rifles (except for that one laser pistol).
Pistols rely on short range combat. It is vitally important for them to be usable at this range, because they simply lose and lose hard to rifles at higher ranges.
You can't have "ranged weapons are always bad in near-melee range" and "a category of ranged weapon which excels at near-melee range is viable" together.
If the only non-desperate use case for pistols can be wholly replaced with "drop the gun and punch them in the face", pistols are simply redundant.

> That's just rude.

I'm only matching the tone here. After a whole post full of "absurd", "nonsensical", "utterly irrelevant" and so on being thrown around as synonyms for "I disagree", you had it coming.
I'm presenting a use case the player sees. If you don't feel the need to accept or present a solution that covers complaints from player's point of view, that IS not caring about player's point of view.

**Comment by Maddremor** [comment]
Butting in with a random idea: What if handguns (or weapons of small volume) were far more resistant to loosing steadiness from sources other than recoil from firing? Then you would be able to take snapshots or move around without gaining MAX_RECOIL with pistols. Additionally, if hit in melee, rifles would loose all stability while handguns could retain some accuracy, only becoming "unaimed" after multiple hits.

**Comment by DemAvalon** [comment]
Videos about close quarter shooting:

https://www.youtube.com/watch?v=c06mH6x2Ntc

https://www.youtube.com/watch?v=4s8t_5VT06M

https://www.youtube.com/watch?v=lVjU_5BRAO0

Pistols can be used in close combat situations, so maybe and this is merely a suggestion, if the player has a certain level in the firearm skill (maybe marksman) they could suffer a lesser disadvantage to close quarters shooting, with someone completely inept behaving as you describe, this could be done by adding an invisible trait to the player once they attain a certain skill level (ex: competent, expert gunsman etc..)

Also Firestorm01X2 made a good suggestion that guns that are large should suffer a greater penalty in close quarters while a small gun suffers less, not only this would encourage people to carry a side arm, but would also make players consider what mods to install on said firearms, as installing that pistol stock on to your glock would make it an awkward weapon for close quarter shooting.

Perhaps by checking if the gun's volume is greater than a certain value it becomes an awkward weapon for CQC, and if its much greater it becomes a very awkward weapon for CQC.

I'm not saying the player should get headshots when firing from the hip or anything like that but they should be able to hit the enemy's center of mass.

**Comment by kevingranade** [comment]
Added most of the suggested tests (I didn't make a wole new batch of test NPCs, I just used the existing ones, and I had already noted I wasn't messing with shotgun tests).

They all passed with no adjustments.

Honestly after playing around with this build, I feel like aim speed needs to be reigned in, aiming to a decent level is way too fast with even a beginner (i.e. spawn a character with no skills, spawn a glock, mag and ammo, go to town shooting things).

File: src/character.cpp [hunk 11]
```diff
@@ -207,43 +207,55 @@ double Character::aim_per_move( const item& gun, double recoil ) const
...
     /** @EFFECT_SMG increases aiming speed for SMGs */
     /** @EFFECT_RIFLE increases aiming speed for rifles */
     /** @EFFECT_SHOTGUN increases aiming speed for shotguns */
     /** @EFFECT_LAUNCHER increases aiming speed for launchers */
-    cost += ( ( MAX_SKILL / 2 ) - get_skill_level( gun.gun_skill() ) ) * 2;
+    aim_speed += std::min( MAX_SKILL, static_cast<int>( get_skill_level( gun.gun_skill() ) ) );
+
+    // Range [0 - 12]
+    /** @EFFECT_DEX increases aiming speed */
+    aim_speed += std::max( 0, get_dex() - 8 );
```
Comment (Coolthulhu) [inline src/character.cpp]: Design smell: threshold.
But this one can be trivially un-thresholded, by moving that `-8` to `aim_speed` and just adding `get_dex` here.

File: src/character.cpp [hunk 12]
```diff
@@ -1563,6 +1575,18 @@ int Character::get_int_bonus() const
     return int_bonus;
 }
 
+int Character::ranged_dex_mod() const
+{
+    ///\EFFECT_DEX <20 increases ranged penalty
+    return std::max( ( 20 - get_dex() ) * 5, 0 );
```
Comment (Coolthulhu) [inline src/character.cpp]: Dexterity is already better than perception in vast majority of cases, swapping that 5 and 2 between perception and dexterity would improve things.

File: src/ranged.cpp [hunk 13]
```diff
@@ -1475,14 +1473,17 @@ static bool is_driving( const player &p )
...
+    dispersion_sources dispersion( weapon_dispersion );
     /** @EFFECT_GUN improves usage of accurate weapons and sights */
-    dispersion.add_range( 10 * ( MAX_SKILL - std::min( int( get_skill_level( skill_gun ) ), MAX_SKILL ) ) );
+    dispersion.add_range( 3 * ( MAX_SKILL - std::min( int( get_skill_level( skill_gun ) ), MAX_SKILL ) ) );
+
+    dispersion.add_range( ranged_dex_mod() / 2  );
```
Comment (Coolthulhu) [inline src/ranged.cpp]: That division by 2 looks very wrong here.

File: tests/ranged_balance.cpp [hunk 14]
```diff
@@ -0,0 +1,317 @@
...
+    INFO( dispersion );
+    INFO( "Range: " << fast_shooting_range );
+    INFO( "Max aim speed: " << shooter.aim_per_move( shooter.weapon, MAX_RECOIL ) );
+    INFO( "Min aim speed: " << shooter.aim_per_move( shooter.weapon, shooter.recoil ) );
+    CAPTURE( fast_stats[1].n() );
+    CAPTURE( fast_stats[1].adj_wald_error() );
+    CHECK( fast_stats[1].avg() > hit_rate );
+}
+
+void assert_encumbrance( npc &shooter, int encumbrance )
```
Comment (Coolthulhu) [inline tests/ranged_balance.cpp]: Not an issue, just suggestion for the future:
Since encumbrance tests are often used, it would be useful to have a way of ensuring exact encumbrance just by number. For example, calling item factory to generate a set of temporary items with exact desired stats, providing player class with some `encumbrance_cache` structure which could be injected with a derived class, or creating a temporary trait/set of traits that does the job.

Tying encumbrance to real items in a test can be a problem when someone wants to change stats of those items and suddenly tests fail. Especially since they're really random here: beekeeping gloves?

File: src/ranged.cpp [hunk 15]
```diff
@@ -223,7 +222,8 @@ int player::fire_gun( const tripoint &target, int shots, item& gun )
 
         int qty = gun.gun_recoil( *this, bipod );
         delay  += qty * absorb;
-        recoil += qty * ( 1.0 - absorb );
+	// Remporaraly scale by 5x as we adjust MAX_RECOIL.
```
Comment (Coolthulhu) [inline src/ranged.cpp]: Tabs
Also, typo here

**Comment by Coolthulhu** [comment]
I don't see any tests for shotguns. Intentionally omitted or forgotten?

Other than the above issues, looks OK. It will need to be tested rather thoroughly in the game, though. In changes of this size, there are always those subtle bugs that manage to evade artificial tests.

**Comment by Firestorm01X2** [comment]
Just to be sure.
In case of future balancing between melee and firearm. In current reality melee weapon was expelled by firearm more than century ago because firearm is much more effective in combat.
Please consider that in future.

**Comment by kevingranade** [comment]
Yes it needs lots of exercising in game, for example aiming is way too fast and I'm in the process of adjusting it down.

**Comment by AncientSion** [comment]
im excited !

**Comment by kevingranade** [comment]
Both testing and manually playing around with a player in-game indicated that aim speed was in fact *way* too fast (roughly 50% too fast).  As a result I added a set of test assertions that establish an upper bound of the aim speed tests in addition to the existing lower bound.
Then came the hard part, slowing aim speed down without wrecking the existing tests.
In rough order of importance:
* Transformed the effect of weapon volume from a bonus to aim speed to an upper cap on speed.
  * Differentiated this cap based on weapon type, i.e. pstols hae a very high cap, rifles have a low one.
* Dropped a scaling factor for aim speed as a whole from 10.0 to 6.5.
* Doubled the magnitude of the skill bonus for aim speed for pistols.
* Increased aim speed of several sights.
* Increased the lower cap on aim speed a bit.

These are all super ad-hoc, but I'm posting them for comment since I got the tests all working again.  I plan on smoothing out some of the rough edges, such as assigning different multipliers for skill and weapon handling properties for each skill, and cleaning up the code a bit.

**Comment by Coolthulhu** [comment]
> Transformed the effect of weapon volume from a bonus to aim speed to an upper cap on speed. 

I don't see a problem with the idea itself, but it's hard to tell how will it perform without a table of sample values.
I calculated one for a Barrett M107A1 and it gets the lower cap (of upper cap). Looking at the formula, I can't see how could pistols ever get close to their cap, let alone to get so low that it will ever constrain their aim speed.

From comments, I calculated a maximum aim speed at pre-cap:
* 10 - starting
* +10 (+10 pistols, -1 rifles)  - skill
* +12 - dex
* +10 - sights

Total: 42, +10 for pistols, -1 for rifles
Meaning that the Cx4 Storm (1500ml) is already constrained by it (`cap_from_volume == 15`), while a pistol would need to be 2000ml to even notice the cap - and that's with the character getting the unfeasibly huge 52 aim speed otherwise.
Since shotguns are generally rifle-sized, this goes against shotguns. Modded SMGs would also be rifle sized.

Could be worth changing it to just linear scaling based on skill. But with pistol-smg difference being smaller than smg-rifle - rifles will always have those long range and burst damage applications that other types can never beat them at.

> Differentiated this cap based on weapon type, i.e. pstols hae a very high cap, rifles have a low one.

I don't like hardcoding per weapon type, especially directly in code. Tolerable as a proof of concept, but making it an item type (for example, for one of the base abstract weapon types) parameter and - very important - readily communicated to player, would be much preferable.
This will look bad for the weapons which don't fit neatly into one category, such as machine pistols with stocks, carbines and so on. I'm not against basing it all on game properties, but that will clash with the whole one skill type per gun type approach.
Then there's the issue of it being unfriendly to mods.

I don't have a better idea that will fit the requirements right now, though.

**Comment by kevingranade** [comment]
> I can't see how could pistols ever get close to their cap, let alone to get so low that it will ever constrain their aim speed.

They don't until I dial the multiplier down to about 1.125, at which point the expert shooter armed with a sw629 hits the cap, causing the fast shooting test fail.  I've dropped the multiplier to 1.25 for now, we can fine-tune it later.  It might be productive to link it to skill level as you suggest, but I'm not particularly interested in doing that as the way it is now meets the success criteria we've already outlined.

> Since shotguns are generally rifle-sized, this goes against shotguns. Modded SMGs would also be rifle sized.

That's precisely why I made it based on skill type, to differentiate between rifle/SMG/shotgun.

> I don't like hardcoding per weapon type

It's skill type, not weapon type, as suggested here: http://smf.cataclysmdda.com/index.php?topic=14821.msg304350#msg304350 and I think I recall it being suggested previously.
Basically pistol/SMG/shotgun handling get bonuses that make them faster to handle, as we continue to adjust we can start differentiating further by giving long range bonuses to rifles, reload speed bonuses where approporiate, etc.

> readily communicated to player

That's the remaining blocker for this PR, we can certainly communicate the effective weapon stats to the player without pushing them down into the weapons.

**Comment by Coolthulhu** [comment]
> That's precisely why I made it based on skill type, to differentiate between rifle/SMG/shotgun.

I mean, at the values you picked, shotguns and SMGs will hit the cap easily, not much later than rifle.
The multiplier on pistol looks good in that it is a higher multiplier, while rifles only get an adjustment. This means that high level shotguns and SMGs will lose any advantages they had over rifle, while keeping all the disadvantages.

**Comment by kevingranade** [comment]
> I mean, at the values you picked, shotguns and SMGs will hit the cap easily, not much later than rifle.

They were tweaked to make the tests pass, if that doesn't result in the behavior you want, you need to supply more tests, which I'd consider in a new OR, this one has already suffered from massive scope creep.

**Comment by Coolthulhu** [comment]
That multiplication of MAX_RECOIL was the single biggest reason for the feature creep necessary to ensure that it doesn't end up being a step backwards.
I guess if it meets the requirements of tests it has to be good enough for now.

As for the communication, I see the following options:
* Displaying it as aim time until 50% or 100% (or both) stability (stability is shown to player already)
* Displaying it as accuracy gain per turn of aiming, at some arbitrary value (50%?)
* If the formula is simple enough, displaying aim time in aim menu, as something like "time cost to increase stability by 10%", would also work

When in doubt, more information is better than less information. This is very important in case of major rebalancing, because player feedback is necessary and it can't be reliable without showing a lot of precise information.

**Comment by kevingranade** [comment]
I'm thinking it should revolve around the quick-select aim levels.  We can give time to aim to each level from scratch and range of 50% chance of a good hit for each level in item info, and time to reach each aim level and the projected hit chances dynamically in the aim menu.

I'm still trying to think of a good way to expose the aim speed cap based on weapon volume, it's indirectly exposed by "Maximum aim time" in item info, but that's very not-granular and it's also poluted by i.e. increases in aim level.  I think I want to add the base aim speed there (aim_per_move(..., MAX_RECOIL)), but I don't thik that's enough.

**Comment by kevingranade** [comment]
Ran out of time for now, I still need to add the new feedback to the aim menu, but that's the end AFAICT.

**Comment by Firestorm01X2** [comment]
So it is no longer [WIP]?

**Comment by kevingranade** [comment]
Poor wording, I need to add the feedback about aim speed and hit chances to the aim menu, THEN it's ready.

**Comment by kevingranade** [comment]
About 9/10 finished with the aim menu, I need to figure out how to display the new information in numeric mode, but the bar-based menu is working and looks pretty sweet.
Screenshot of new aim menu

**Comment by Firestorm01X2** [comment]
Is player really need exact digit in this case? I mean difference between like 30% and 35% maybe is not worth it. At the same time bar may be very representative

**Comment by kevingranade** [comment]
Ended up having to extensively overhaul the aim menu, it's a bit more reactive now since space is a lot tighter, I stole all the space on the sidebar if we really run short.

screenshot showing menu rendering at various sizes
[image](k2dnUQ)

I still need to add the aim speeds to the presets, but that should be tiny, and I've already reserved the space they need in the layout so I shouldn't have to mess with that again.

**Comment by Firestorm01X2** [comment]
What about bows and crossbows ? Will if be affected by this PR?

**Comment by kevingranade** [comment]
> What about bows and crossbows ? Will it be affected by this PR?

yes

**Comment by kevingranade** [comment]
unless something is broken, this is done.

**Comment by Firestorm01X2** [comment]
What about hard close range accuracy reduction? Was it implemented? I hope it is not.

**Comment by kevingranade** [comment]
> What about hard close range accuracy reduction? Was it implemented? I hope it is not.

These are the comments outlining how that was changed.
https://github.com/CleverRaven/Cataclysm-DDA/pull/21468#issuecomment-323492458
https://github.com/CleverRaven/Cataclysm-DDA/pull/21468#issuecomment-326731056
https://github.com/CleverRaven/Cataclysm-DDA/pull/21468#issuecomment-328398502

If none of those comments covers your question, you'll need to be more specific about what you mean.
Hitting things at close range is still utterly trivial, but you need to pay attention to your recoil a bit now.

**Comment by Firestorm01X2** [comment]
> Hitting things at close range is still utterly trivial, but you need to pay attention to your recoil a bit now.
Ok. Thank you. I just worried that it will be massive.

**Comment by Coolthulhu** [comment]
Moderate:
* The "even chance at range" is either wrong by a large margin or misleading. In my test, I'm standing one tile closer than even chance range and yet I'm consistently getting less than 50% good hits at given accuracy level. Tested on debug monster, so no size effects (it's medium) and no dodging.
* No shotgun test, no explanation for why not.
* Dexterity aim speed modifier is thresholded.
* Dexterity is now strictly better than perception when it comes to ranged combat. Perception is quickly getting really useless again.
* Dexterity penalty is divided by 2 when applied, meaning there's a rather major discrepancy in what is displayed and what is applied.

Minor:
* The text in UI is very verbose and wraps around in English. Could use to be shortened, for example "Even chance of good hit at Regular/Careful/Precise: 10/20/30" or "50+% good hits at Regular Aim at range:".
* Maximum aim time entry is now most likely obsolete - it displays the same number as "aim to precise"
* Steadiness starts above 0%. Exact value depends on sight penalty (lower sight penalty means starting at higher steadiness).
* The way `range_with_even_chance_of_good_hit` is implemented
* "Time to reach" is calculated by division by magic. `calendar::moves_to_seconds` or something would be clearer.

Minor issues can wait.
I'll need at least a sentence of explanation for each of the moderate issues. Those aren't minor enough to just let them sneak by the radar, but regressions significant enough to warrant an issue for each of them. Still, they don't necessarily need to block the PR.
No issues major enough to absolutely need fixing right now.

**Comment by kevingranade** [comment]
> The "even chance at range" is either wrong by a large margin or misleading. In my test, I'm standing one tile closer than even chance range and yet I'm consistently getting less than 50% good hits at given accuracy level. Tested on debug monster, so no size effects (it's medium) and no dodging.

It would have been nice for you to state the results of your test.  Depending on the magnitude of "consistently getting less", this is either irrelevant or a major bug.  It is *by design* neither accurate nor precise.  If it's within 10% or so it's fine, if it's more than 20% off it's definitely a problem, if it's between I'm not sure.

> No shotgun test, no explanation for why not.

Explicitly called out as being out of scope by https://github.com/CleverRaven/Cataclysm-DDA/issues/21244#issuecomment-309955043
Never incorporated into the main test cases, you asked for shotgun tests with https://github.com/CleverRaven/Cataclysm-DDA/pull/21468#issuecomment-326786000 along with a rationale for shotgun being significantly faster to aim than a SMG that I dispute in https://github.com/CleverRaven/Cataclysm-DDA/pull/21468#issuecomment-327669701
I noted I wasn't implementing them again in https://github.com/CleverRaven/Cataclysm-DDA/pull/21468#issuecomment-327669701

Bottom line, our shotguns are not video game shotguns.  At the ranges we're discussing the spread is nearly irrelevant, resulting in a projectile that is at best a few inches across, with very little impact on effective accuracy, and no impact at all on aiming speed.  They're on par with SMGs because they're assumed (like SMGs) to be designed for fast operation by adjusting their balance, and by equipping them with sights suited to fast target acquisition (unlike both scopes and iron sights for rifles).

> Dexterity aim speed modifier is thresholded.

You want the min of 0 removed so dex under 8 slows down aiming more? I was avoiding negative scaling of speed, but sure why not.

> Dexterity is now strictly better than perception when it comes to ranged combat. Perception is quickly getting really useless again.

The two penalties are applied at different places and have different effects, they aren't fungible, so your suggestion of swapping the modifiers isn't workable.  If you want perception to have more impact, find more places for it to be applied.
Dex improves both steadiness (allowing lower average dispersion) and manual dexterity with respect to handling guns (improving aim speed).
Perception improves visual acuity, leading to better ability to resolve a target, especially at long range.  At close range it's almost irrelevant, but if you're trying to make a distant shot it can cut your effective range by something like 3 squares per point under 20, in the extreme case a PER of 8 means you pretty much can't hit regularly outside of 25 tiles, and someone with PER 20 can get hits regularly out to 38 tiles or so.

Something you might have missed, after the division that currently occurs in player::get_weapon_dispersion(), the effective magnitude of the PER penalty is roughly the same as the DEX penalty (2.0 * value vs 2.5 * value).

> Dexterity penalty is divided by 2 when applied, meaning there's a rather major discrepancy in what is displayed and what is applied.

Can do, I'll bake the adjustment into ranged_dex_mod().

Minor:

> The text in UI is very verbose and wraps around in English. Could use to be shortened, for example "Even chance of good hit at Regular/Careful/Precise: 10/20/30" or "50+% good hits at Regular Aim at range:".

If it wraps that's major.  I'm guessing you mean in item::info()?

> Maximum aim time entry is now most likely obsolete - it displays the same number as "aim to precise"

I meant to remove that and forgot.

> Steadiness starts above 0%. Exact value depends on sight penalty (lower sight penalty means starting at higher steadiness).

Ok, might be a bug in some of the calculations.

> The way range_with_even_chance_of_good_hit is implemented

I assume you mean the table of range <-> dispersion mappings, if you have a better solution that doesn't demand that the entire system is designed around it, let's hear it.

> "Time to reach" is calculated by division by magic. calendar::moves_to_seconds or something would be clearer.

Sure.

**Comment by Coolthulhu** [comment]
>  It is by design neither accurate nor precise.

Skimping on display will only result in more problems like this one. Tests will catch a subset of them, but preventing players from catching the rest is just asking for trouble.
> If it's within 10% or so it's fine, if it's more than 20% off it's definitely a problem, if it's between I'm not sure.

Certainly above 10% although I didn't brute force it for long enough to make sure it's 20%, only to make sure it's clearly off.
I did the test like this: glock 19, extended magazine, precise-aim-fire all magazine at debug monster, "even range" was 5 tiles.
The results were roughly:
* At 5 tiles distance, the results clustered around 9-10 good hits (30%-35%)
* At 4 tiles, it increased to ~12 per test, meaning it's still too much off to blame just the rounding

> You want the min of 0 removed so dex under 8 slows down aiming more?

That would work.

> The two penalties are applied at different places and have different effects, they aren't fungible, so your suggestion of swapping the modifiers isn't workable.

That's just plain not true. At least that "isn't workable" part - they are different effects, but dexterity is strictly better at the same penalty.
End effect is that dexterity penalty is rolled separately before addition to final value, while perception penalty is added to one of the roll's max value. And that roll is likely to be pretty huge.
Essentially this boils down to:
```
dispersion = roll(dex_penalty()) + roll(big value + per_penalty()) + other rolls;
```

Statistically, this makes dexterity significantly more important when precise-aiming, due to its reliability.
Additionally, perception penalty only really matters when precise-aiming - it only affects your maximum possible accuracy (and indirectly but weakly aim speed), while dexterity affects all shots.
All of that before even considering aim speed bonuses.

So at the moment, dexterity is strictly better than perception at affecting ranged accuracy.

I was wondering why isn't it shown in the UI (the UI shows perception as more useful) and I'm pretty sure I found it:
In item.cpp, when you call `range_with_even_chance_of_good_hit`, you use average value of most dispersions, but add full value of aim threshold. In actual firing, aim threshold affects recoil, which too is rolled, meaning you should add only 50% of it there. This explains why perception appears to be better on display despite math clearly showing it to be worse than dexterity.

> If it wraps that's major. I'm guessing you mean in item::info()?

Yes. The part that calls `range_with_even_chance_of_good_hit`. When viewing the item as inventory->item, the item page covers some set width, which is lower than width of the text line.

> I assume you mean the table of range <-> dispersion mappings, if you have a better solution that doesn't demand that the entire system is designed around it, let's hear it.

Nothing that would fit in this PR, but the proper way would be:
* Transform the ranged roll formula to get function of dispersion roll and distance to hit quality
* Plug in hit quality and transform the formula to distance to dispersion roll
* The hard part: find the median dispersion roll for a given dispersion source set. May need to be brute forced.
* With median dispersion roll value found, bisect the distance->dispersion function until two such distances are found that one will get a good (or better) hit with median dispersion roll and the other will get below good hit.

**Comment by kevingranade** [comment]
> ... testing results ...

Thanks, that certainly sounds like it's off by enough that I need to investigate further.  With luck it's just the mistake you point out later regarding using maximum vs average value of get_weapon_dispersion() in range_with_even_chance_of_good_hit().
i.e. the dispersion values emitted by "synthetic_range_test" are max dispersion, not average, which means passing the result of dispersion_sources::avg() to range_with_even_chance_of_good_hit() is going to be wildly optimistic, which matches your testing results.

 > That's just plain not true. At least that "isn't workable" part - they are different effects, but dexterity is strictly better at the same penalty. ...plus good explanation...

How about this, I'll see how far I can shift the dexterity vs perception numbers without breaking all the tests.  It's not that the magnitudes *can't* move around, it's that it has the potential to require another pass of rebalancing the entire system, which is rather painful.

> Nothing that would fit in this PR, but the proper way would be: ...

Other than making it 'proper', what's the benefit of following your approach?  The existing approach simply assumes the distribution produced by dispersion_sources::roll() is approximately normal and that dispersion_sources( x ) is representative of dispersion_sources( a ).add_range( b ).add_range( n ) where x == a + ... + n, then does something roughly analogous to bisection to find the breakpoints you describe in your final step.  Without this assumption, we would need to have a monstrous number of inputs for all the permutations of dispersion_sources objects.
In practice this assumption is quite reasonable, and should yield a good approximation, which again is exactly what we want, NOT a precise value.

The easiest test of this is to jump straight to your step 3, brute force a median value for some sample set of distributions along with their equivalent approximations and see what the error is.  If that error is very large, then this is worth looking into further, otherwise it isn't.

Side note:
> Transform the ranged roll formula to get function of dispersion roll and distance to hit quality

This is precisely projectile_attack_roll() with a dispersion_source mocked to return a specific value instead of sampling from a distribution.  Again this is exactly what we want, because we don't want to replicate game logic in the test, otherwise they risk going out of sync.

**Comment by Coolthulhu** [comment]
> Other than making it 'proper', what's the benefit of following your approach?

* Understanding what is happening under the hood. This is better than just empirical data.
* Being able to enforce it with a test (that isn't brute force)
* Non-integer values - important when the expected range is low (say, 2.1 vs 2.9)

Now that I think about it, there is nothing wrong with using a precomputed table, the only problem is that the table is magic and "just works".
If the formula was pure math, problems like bad that bad range display and dexterity vs perception balance would be clear and would break tests.

> In practice this assumption is quite reasonable, and should yield a good approximation, which again is exactly what we want, NOT a precise value.

With an imprecise value, you can't tell if it is wrong, unless it is wrong enough. If a formula mixes up two variables but happens to mix up ones that - in your tests - have similar effect, you can't tell easily tell it and you can't enforce it.

>  Again this is exactly what we want, because we don't want to replicate game logic in the test, otherwise they risk going out of sync.

But you'd be immediately warned that they got out of sync.
With approximate, empirical data, you only catch errors that your tests are specifically made to cover.
With formulas, you get to know that something is wrong as soon as something is wrong.

**Comment by kevingranade** [comment]
> With luck it's just the mistake you point out later regarding using maximum vs average value of get_weapon_dispersion() in range_with_even_chance_of_good_hit().

Looks like this was it, spawned a glock, magazine, ammo on a random character, then stood at expected range for 50% good hits ( 6 squares in this case) and resulted in these ratios:
``` 3/15 1/15 4/15 4/15```
That's clearly not right, it's under 25%
Made the adjustment to item::info() to use get_weapon_dispersion().max(), then repeated experiment (now at 4 squares):
```5/15 10/15 10/15 8/15 5/15```
That's more like 38/75, which is right on the money.

Repeated with a Browning BLR with a scope and a match trigger, after bumping skills up to ~10.
item::info() reports 50/50 good hit range as 15. (that should make some people happy)
```0/4 1/4 3/4 1/4 3/4 0/4 3/4 3/4 4/4 2/4```
which was exactly 20/40.

**Comment by Coolthulhu** [comment]
Forgot to add minor issue: tabs.
`grep -P '\t' src/*.cpp` shows 6 entries

**Comment by kevingranade** [comment]
Ok, that's everything except the overhaul of range_with_even_chance_of_good_hit().

I made the multipliers for dex and per the same (2.25), which is the furthest I could adjust it without making the tests start failing.

**Comment by Coolthulhu** [comment]
All right, let's get it in for now. The rebases get heavy and it's good enough for now.

Problems not fixed yet:
* Dexterity is strictly better than perception. The tests should not break as long as sum of modifiers from dex+perception is ~5, meaning it should be safe to make perception give 5 per point and dexterity not help dispersion at all (just aim speed)
* The new `TICKS_TO_SECONDS` function returns `int`. We want `float`, otherwise it rounds wayyy too much. Also, the name is misleading: everywhere else those units are called "moves", while ticks are variable sized.
* As a consequence of the rounding above, "time to reach" always gets two trailing zeroes. Some extra precision isn't bad (one decimal would be perfect, because difference between 2.1 and 2.9 is almost 30%), but that ugly truncation above breaks it.
* Shotguns don't have own test or any other measure of whether they are balanced or not
* The "regular aim" etc. pseudo-headers in gun item display for guns aren't colored in any way, which makes it harder to spot where they start and end at a glance
* Aiming is too fast and doesn't slow down fast enough. This brings back part of the "aim perfectly or not at all" dysfunction. Aiming speed should probably get its own set of tests later.

**Comment by Coolthulhu** [comment]
Shit, should have been more careful - I totally missed the part where the tests for high-level characters got adjusted in the wrong way and relaxed into uselessness.

It still solves the part where guns are totally useless that resulted from the revert earlier on, but does not achieve balance.

**Comment by Firestorm01X2** [comment]
Create issue on that.

**Comment by Firestorm01X2** [comment]
There is chance that this PR caused crashes on throwing. Look for refernced issue.

**Comment by DanmakuDan** [comment]
In `ranged.cpp`,
```
int time_to_fire( const Character &p, const itype &firingt )
```
The item being thrown expects a gun type to be associated with it, but there is only a null pointer available for items that can only be thrown (`firingt.gun.get() = 0x0`), causing the crash in #22001.
```
const skill_id &skill_used = firingt.gun.get()->skill_used;
```
The game doesn't crash if you try to throw a gun. This apparently means if I try to throw a pistol, it will use my pistol skill to determine the time it takes to throw it. I tested changing handgun level 0 to level 20, and it caused the aim time to decrease from 80 to 10.

**Comment by Sagan-Ro** [comment]
Okay, so I have a few questions that are really bugging me:

1.  Why does my laser rifle on burst fire hit an enemy a couple of times then start shooting to the sides of the enemy.  As in two-to-five tiles left and right of my target's actual position?  If that is due to "recoil"... lasers aren't supposed to have recoil, right?

2.  Why does my character, even when debugged to level 40 skill in everything with 20 STR/INT/PRC/DEX with a scoped and fully outfitted M107 .50 caliber sniper rifle capable of accurately killing human-sized targets over a mile away... LITERALLY have trouble hitting a target across the street?  In what universe could that possibly make sense?

I am really, _**really**_ hoping the absolutely craptastic new "performance" of long-range weaponry and burst firing is just because the new system isn't finished yet.  I was playing release 6723 for over a month, and could tag enemies more than 2/3 the time with the Heavy Rail Rifle (scope+gyroscopic stabilizer+tuned mechanism+match trigger) around 55+ squares away.  Now I just get grazing hits over 20 squares, and any hit at all seems to go to zero at or past 25 squares.

Thank you so much, I would really like it if my sniper could actually, um... snipe.  It's pointless to have long-distance weapons in this game if long-distance attacks are no longer possible.

**Comment by kevingranade** [comment]
Please don't post in closed issues.
