### PR TITLE
Fix plural: item::display_name returns the proper plural name.

### LINKED ISSUE #12720: "Salvaged X patchs" should be "Salvaged X patches"
As the topic says it's a minor misspelling. I also noticed that "patchs" occurs just about everywhere: when picking them up or dropping them and not just when you salvage leather patches.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/22567898-salvaged-x-patchs-should-be-salvaged-x-patches?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BevapDin**
Fixes #12720

### CODE REVIEW

File: src/iuse_actor.cpp [hunk 1]
```diff
@@ -1093,8 +1093,8 @@ int salvage_actor::cut_up(player *p, item *it, item *cut) const
         int amount = salvaged.second;
         item result( mat_name, int(calendar::turn) );
         if (amount > 0) {
-            add_msg( m_good, ngettext("Salvaged %1$i %2$s.", "Salvaged %1$i %2$ss.", amount),
-                     amount, result.display_name().c_str() );
+            add_msg( m_good, ngettext("Salvaged %1$i %2$s.", "Salvaged %1$i %2$s.", amount),
```
Comment (narc0tiq) [inline src/iuse_actor.cpp]: Do you even need the `ngettext` call anymore? The format strings are the same.

Comment (BevapDin) [inline src/iuse_actor.cpp]: The verb could be different in some language based on whether it refers to one or several things. No idea whether it's actually used in any language.

Comment (narc0tiq) [inline src/iuse_actor.cpp]: Ah, fair enough.
