### PR TITLE
Fix broken messages about required skills

### LINKED ISSUE #18240: Vehicle install/remove "Skills required" displayed incorrectly
`%2$s %3$i` instead of "Mechanics 3" and the like.

Windows 7, release build, using GCC bundled with CodeBlocks 16.01 (I think it's 4.8.1).

### PR DESCRIPTION
**Pull request by illi-kun**
Fixes #18240.

Any ideas about better ways to fix this are welcomed.

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -10278,8 +10278,8 @@ void player::mend_item( item_location&& obj, bool interactive )
                 if ( !hasSkill && f.second ) {
                     f.second = false;
                 }
-                descr << string_format( "> <color_%1$s>%2$s %3$i</color>\n", hasSkill ? "c_green" : "c_red",
```
Comment (illi-kun) [inline src/player.cpp]: Done.

File: src/player.cpp [hunk 2]
```diff
@@ -10278,6 +10278,7 @@ void player::mend_item( item_location&& obj, bool interactive )
                 if ( !hasSkill && f.second ) {
                     f.second = false;
                 }
+                //~ %1$s represents the internal color name which shouldn't be translated, %2$s is skill name
```
Comment (mugling) [inline src/player.cpp]: ... 3 is?

Comment (illi-kun) [inline src/player.cpp]: ... and here we go.
