### PR TITLE
Fix character received items' charges error

### LINKED ISSUE #64245: Broken reward for Gather cattail stalks to create cattail jelly quest
### Describe the bug

When you complete the quest to collect 80 cattail stalks, the questgiver attempts to give you cattail jelly in a zipper bag.  This is not a valid container for cattail jelly and the game throws an error, preventing the cattail jelly from being given to the player.

### Attach save file

N/A

### Steps to reproduce

1. Be given cattail jelly quest by NPC.
2. Complete the quest.
3. Receive error message.

### Expected behavior

The reward should be in a watertight container such as a bottle instead.  Be sure the container is large enough to contain the reward, 7 units of jelly is 0.25 L.

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 6.1 7601
- Game Version: d6ec466 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Aftershock [aftershock],
    Generic Guns [generic_guns]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by SurFlurer**
#### Summary
Bugfixes "Fix mission reward items charges error"

#### Purpose of change
There are numerous scenarios that an item with json-defined charges gets spawned, and the charge that the character receives is wrong. Here's a non-exhaustive list of such scenarios:
1. Ammo conversion with the isolated artisans.
2. Mission with the isolated artisans that gives you 229 instead of 200 `545_ap`.
3. Mission with NPC_Claire_Isherwood that gives you 29 instead of 20 `poppy_pain`.
4. Mission with the old_guard_representative that gives you 36 instead of 17 `44magnum`.
5. ......

#### Describe the solution
When spawning the item that is count by charges, reset the charge of that to 1, to be prepared to receive the scenario-defined count. 

#### Describe alternatives you've considered
Wait for #60885 to solve this.

#### Testing
Good in game. Tests passed.

#### Additional context
Fixes https://github.com/CleverRaven/Cataclysm-DDA/issues/64245

### CODE REVIEW

File: src/npctalk.cpp [hunk 1]
```diff
@@ -2302,6 +2302,7 @@ static void receive_item( itype_id &item_name, int count, const std::string &con
     }
     if( container_name.empty() ) {
         if( new_item.count_by_charges() ) {
+            new_item.charges = 1;    // Reset item default charges, prepare to receive specific defined charges
             new_item.mod_charges( count - 1 );
```
Comment (mqrause) [inline src/npctalk.cpp:2306]:
```suggestion
            new_item.charges = count;
```

Might as well simplify it.
I also see the same thing a bit further down for items that come in a container.

Comment (SurFlurer) [reply src/npctalk.cpp:2306]: Yes! Thank you.

**Comment by sparr** [comment]
Fixes #64245
