### PR TITLE
Fix for UPS recharging non UPS items and not using bionic UPS

### LINKED ISSUE #32496: Advanced UPS charges a lighter
[2019.06.04.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3412426/2019.06.04.zip)

0.D-5723-g6790e59e64-dirty

### PR DESCRIPTION
**Pull request by RDru**
#### Summary
```SUMMARY: Bugfixes "UPS recharging non UPS powered items and not using bionic UPS"```

#### Purpose of change
UPS was recharging all items but not UPS ones.
Also bionic power was not taken into consideration when calculating max UPS power.

#### Describe the solution
Fixed the condition for recharging items.
Added bionic power when bionic UPS is active to UPS charge pool.

#### Additional context
Fixes #32496

### CODE REVIEW

File: src/player.cpp [hunk 1]
```diff
@@ -6616,10 +6616,13 @@ void player::process_active_items()
...
             ch_UPS += it.ammo_remaining() / 0.6;
         }
-        if( !it.has_flag( "USE_UPS" ) && it.charges < it.type->maximum_charges() ) {
+        if( it.has_flag( "USE_UPS" ) && it.charges < it.type->maximum_charges() ) {
             active_held_items.push_back( index );
         }
     }
+    if( has_active_bionic( bionic_id( "bio_ups" ) ) ) {
+        ch_UPS += power_level;
+    }
```
Comment (Petethegoat) [inline src/player.cpp]: Shouldn't think be in the loop above, so normal items see the bionic UPS as a valid supply to draw from? If I understand the bionic UPS description correctly, this should work fine.

Comment (RDru) [reply src/player.cpp]: This is just for getting the sum of all the UPS charges.
