### PR TITLE
Clearing rubble makes creature under it free.

### LINKED ISSUE #33801: You are still stuck in rubble even if you clear it with a shovel after getting stuck in it.
# Describe the bug
If you use a shovel to clear rubble that you are stuck in, you still have to struggle to get out of the rubble afterwards.

# Steps To Reproduce
1.Collapse a ceiling on top of your character.
2.Use a shovel and the period (.) key to clear the rubble on the tile you are standing on.
3.Try to move.  The game will act like you're stuck in rubble even though you just dug yourself out.

# Expected behavior
If you use a shovel to clear rubble that you are stuck in, you should be able to just walk away--not have to struggle to get out of rubble that doesn't exist anymore.

# Versions and configuration
 - OS: Windows 10
 - Game Version: 0.D-8574
 - Graphics version: Terminal

### PR DESCRIPTION
**Pull request by ipcyborg**
#### Summary
```SUMMARY: Bugfixes "You are still stuck in rubble even if you clear it with a shovel after getting stuck in it"```

#### Purpose of change
Fixes #33801

#### Describe the solution
Remove effect `effect_crushed` from any creature that was on the tile with rubble, after this rubble has been cleared.
Should affect: player, NPCs and monsters. 

On one hand, some message is required like `The %s frees itself from the rubble!`.
On the other hand:
1. Code in `map` looks like a bad place for it, no? Still there are messages there, even in `map::furn_set`.
2. There are messages for it already: in `monster::move_effects` and `Character::move_effects`. But I don't want to duplicate it in the map code, and don't know how to use them from there.

#### Describe alternatives you've considered
None. This solution was suggested in #33801.

#### Additional context
None

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -1290,6 +1290,13 @@ void map::furn_set( const tripoint &p, const furn_id &new_furniture )
         add_msg( _( "The %s you were grabbing is destroyed!" ), old_t.name() );
         g->u.grab( OBJECT_NONE );
     }
+    // If a creature was crushed under a rubble -> free it
+    if( old_id == f_rubble && new_furniture == f_null ) {
+        Creature *c = g->critter_at( p );
+        if( c && c->has_effect( effect_crushed ) ) {
```
Comment (Night-Pryanik) [inline src/map.cpp]: Check for having crushed effect is redundant here.

Comment (ipcyborg) [reply src/map.cpp]: Yes, it is checked later in `remove_effect`. Thanks!
Fixed.
