### PR TITLE
Move the lore snippets from the faction to the diary UI

### LINKED ISSUE #83338: Cannot scroll details in faction menu
### Describe the bug

Image

### Attach save file

N/A

### Steps to reproduce

1. Open the faction menu
2. Go to the LORE tab
3. Find a text too long to display

### Expected behavior

Scroll the text with `[` `]` or `<` `>`

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.26100.6584 (24H2)
- Game Version: 0.G-20658-gea512d84c5 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms]
]

### Additional context

#59688

_No response_

### PR DESCRIPTION
**Pull request by alef**
#### Summary
Interface "Move the lore snippets from the faction to the diary UI"

#### Purpose of change
Fixes #83338

#### Describe the solution
image

image

The summary page in the diary now lists the lore snippets. By moving the cursor over them, the diary page shows the text lore as previously in the faction UI. The major difference is now you can scroll the text in the page to read it further.

#### Describe alternatives you've considered
With less changes it would have shown the `desc` for the lore in the info box below, which also has no scrolling.
Another alternative would be to add an additional "Summary" only for the lore.

#### Testing
Built the Window version, run in a debug world, spawned some newspapers, screenshots.

#### Additional context
Maybe the "Creatures" should also go in the diary?

### CODE REVIEW

**Comment by alef** [comment]
IWYU: `src/faction.cpp:38:1: error: superfluous '#include "talker.h"'`

Not really, without it I get 
```
In file included from /usr/include/c++/13/bits/shared_ptr_base.h:59,
                 from /usr/include/c++/13/bits/shared_ptr.h:53,
                 from /usr/include/c++/13/bits/fs_path.h:46,
                 from /usr/include/c++/13/filesystem:49,
                 from pch/main-pch.hpp:43:
/usr/include/c++/13/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = talker]’:
/usr/include/c++/13/bits/unique_ptr.h:404:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = talker; _Dp = std::default_delete<talker>]’
src/faction.cpp:1123:61:   required from here
/usr/include/c++/13/bits/unique_ptr.h:97:23: error: invalid application of ‘sizeof’ to incomplete type ‘talker’
   97 |         static_assert(sizeof(_Tp)>0,
      |                       ^~~~~~~~~~~
```

File: src/faction.cpp [hunk 1]
```diff
@@ -35,7 +35,7 @@
 #include "point.h"
 #include "skill.h"
 #include "string_formatter.h"
-#include "text_snippets.h"
+#include "talker.h"
```
Comment (moxian) [inline src/faction.cpp]: Yep, this is a legitimate IWYU false-positive.

In my opinion, silencing this warning is the cleanest way to deal with it (and you can see this is done to `"talker.h"` specifically in a number of files across the codebase)
```suggestion
#include "talker.h"  // IWYU pragma: keep
```

**Comment by alef** [comment]
The GCC 9 tests succeed but the execution failed with `SIGBUS`:
```
environment: line 1: 12553 Bus error               (core dumped) $WINE "$test_bin" ${cata_test_opts} "$@" 2>&1
```

**Comment by GuardianDll** [comment]
Another option fixing it was to make the tab imgui, but this will always do, i presume
