### PR TITLE
[CR]Monsters add weight to vehicle when on boardable parts

### LINKED ISSUE #49172: 'Follower' animals do not add weight to vehicle when on trunks/aisles/etc
# Describe the bug

My bike weighed 218kg with me on it.  A cow boarded my bike's "trunk". The bike still weighed 218kg with the entire adult cow riding it.

# Steps To Reproduce

Spawn a domesticated animal
Feed it
Move onto vehicle that they can move onto as well
Compare weights

# Expected behavior

The vehicle's weight should increase by the animal's weight and handling characteristics should change accordingly.

# Screenshots

cdda1
cdda2

# Versions and configuration

- OS: Windows 10
    - OS Version: 10.0 1809
- Game Version: fe42098 [64-bit]
- Graphics Version: Tiles
- Game Language: System language [English]
- Mods loaded: [
    Dark Days Ahead [dda],
    Graphical Overmap [Graphical_Overmap]
]

# Additional context

-Not just cows, debug tested with some dogs too
-Friendly NPCs correctly add weight, just animals don't
-Animal compartments properly add weight when the animal is stored
-I can't seem to make animals follow me after putting them in and taking them out of an animal compartment, even with re-feeding/dog whistle. Not sure if this is a separate bug or I'm doing something wrong. Haven't used them much.

### PR DESCRIPTION
**Pull request by SurFlurer**
#### Summary
Bugfixes "Monsters add weight to vehicle when on boardable parts"

#### Purpose of change
Fix #49172

#### Describe the solution
Check for boardable vparts, if there's a monster, add its weight to the vehicle.

#### Describe alternatives you've considered
Leave it as is.

#### Testing
Spawn a cow and a SUV. Try to push the cow onto the SUV. See the weight correctly adds up.

#### Additional context
Do you think this fix needs a test unit? Please comment.

Also, it might be unwanted for certain animals to board the car without a livestock carrier. So I added [CR] to the title.

### CODE REVIEW

**Comment by SurFlurer** [comment]
It seems that github runners are somehow stuck... Will adding another commit fix this?

File: src/vehicle.cpp [hunk 1]
```diff
@@ -7585,7 +7585,10 @@ void vehicle::calc_mass_center( bool use_precalc ) const
             // Sometimes flag is wrongly set, don't crash!
             m_part += p != nullptr ? p->get_weight() : 0_gram;
         }
-
+        if( vp.has_feature( VPFLAG_BOARDABLE ) ) {
```
Comment (irwiss) [inline src/vehicle.cpp:7588]: Looks like there's no need to check the passenger_flag as `get_passenger` in the `if` above will check it anyway so the 2 `if`s can be merged

Comment (SurFlurer) [reply src/vehicle.cpp]: OK, I merged them.
