### PR TITLE
Fix fuel consumption UI inaccuracies

### LINKED ISSUE #37943: Fuel remaining wildly inaccurate
When 'e'xamining a vehicle you're driving the fuel remaining counter seems to calculate time until empty by using the old time format where one turn = three seconds. There may be other issues with it, but from some limited testing it seems that this accounts for most inaccuracy. 

# Steps To Reproduce
1. Get an electric vehicle and attach a small (e.g. car) battery.
2. Get up to a cruising speed of whatever you like.
3. 'e'xamine and note the time remaining on the clock. Compare the time remaining every few turns. Minutes will tick by over a matter of seconds.

# Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 0.D-12105-gda56791 [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Mythological Replicas [nw_pack],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    No Rail Stations [No_Rail_Stations],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    Roadheader and other mining vehicles [Heavy miners],
    No Fungal Monsters [No_Fungi],
    Beta National Guard Camp [national_guard_camp]
]

### LINKED ISSUE #58385: Big fuel loss after "fake parts update"
### Describe the bug

After this update https://github.com/CleverRaven/Cataclysm-DDA/pull/56143
[Cataclysm-DDA experimental build 2022-06-08-2059](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-08-2059)
The fuel consumption of cars has been greatly increased

### Steps to reproduce

I tested it on grass, not on the road, but situation is the same
1) Load update which comes before "Fake parts for filling vehicle gaps"
[Cataclysm-DDA experimental build 2022-06-08-1950](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-08-1950)
2) Spawn car. I tested it on "Flatbed truck" and "Cargo van"
3) Speed up to 25 km/h
4) Check fuel consumption
5) Load "Fake parts for filling vehicle gaps" update 
[Cataclysm-DDA experimental build 2022-06-08-2059](https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2022-06-08-2059)
6) Spawn "Flatbed truck" and "Cargo van"
7) Speed up to 25 km/h
8) Check fuel consumption

### Expected behavior

Normal fuel comsuption. I think, fake part logick doubles weight or something like this, but on screenshots you can see, weight stays the same before and after "fake part" update

### Screenshots

Check fuel consumption on the screenshots

<details>

<summary> "Flatbed truck" before and after "fake part update" </summary>
</details>

<details>

<summary> "Cargo van" before and after "fake part update" </summary>
</details>

<details>

<summary> Tested place </summary>
</details>

### Versions and configuration

<details>

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: 2ec0e5e [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

<summary> Cataclysm-DDA experimental build 2022-06-08-1950 version and configuration </summary>
</details>

<details>

- OS: Windows
    - OS Version: 10.0.19044.1706 (21H2)
- Game Version: befb7ab [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions]
]

<summary> Cataclysm-DDA experimental build 2022-06-08-2059 version and configuration </summary>
</details>

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by natsirt721**
#### Summary
Bugfixes "Fix inaccuracies in fuel consumption display"

#### Purpose of change
Fixes #37943
probably Fixes #58385

Related: #47384
As has been frequently noted, the fuel consumption display in the vehicle UI vastly over-reports fuel efficiency for chemical engines.  This changes that.

#### Describe the solution
`consumption_per_hour()` was making some assumptions that are no longer true about fuel usage. Fortunately, we already have how much energy's worth of each type of fuel was used, and we can determine the most recent consumption rate by dividing by the specific energy of the fuel and doing some unit conversion.

I also changed the return type from `int` to `long long` to avoid overflows. 

#### Describe alternatives you've considered
Something more like #47384, using a running average to populate the display instead of consumption for the most recent turn.

#### Testing
Spawned a variety of vehicle (electric bicycle, car, ambulance, semi truck, portable generator, mini locomotive) and drove them around, watching their reported fuel rates and noting when they actually ran out of fuel.

#### Additional context
I didn't see #47384 until I was writing this PR, if there's rationale for the more complex fix implemented there then I can try to bring those changes into this PR. Either way I think this is a good step in that direction.

Edit: fixed related PR number

### CODE REVIEW

File: src/vehicle.cpp [hunk 1]
```diff
@@ -3433,36 +3433,17 @@ int vehicle::basic_consumption( const itype_id &ftype ) const
     return fcon;
 }
 
-int vehicle::consumption_per_hour( const itype_id &ftype, int fuel_rate_w ) const
+long long vehicle::consumption_per_hour( const itype_id &ftype, int fuel_rate_w ) const
```
Comment (anothersimulacrum) [inline src/vehicle.cpp:3436]: [Use `int64_t`](https://github.com/CleverRaven/Cataclysm-DDA/blob/master/doc/CODE_STYLE.md#code-guidelines), but is `fuel_rate_w` really so close to `INT_MAX` that multiplying it by 3.6 (and probably even less) that it's going to overflow?

File: src/vehicle.cpp [hunk 2]
```diff
@@ -3433,36 +3433,17 @@ int vehicle::basic_consumption( const itype_id &ftype ) const
...
-            if( accel == 0 ) {
-                // FIXME: Long-term plan is to change the fuel consumption
-                // computation entirely; for now just warn if this would
-                // otherwise have been division-by-zero
-                debugmsg( "Vehicle unexpectedly has zero acceleration" );
-            } else {
-                amount_pct += 3600 * vslowdown / accel;
-            }
-        }
+        return 0.0;
```
Comment (anothersimulacrum) [inline src/vehicle.cpp:3440]:
```suggestion
        return 0;
```

File: src/vehicle.cpp (hunk 1 above)
Comment (natsirt721) [reply src/vehicle.cpp:3436]: I wasn't sure initially but I think thats due to how I had the constants. The cases causing overflow were for the larger engines at full capacity. Anything producing more that about 600 kW power would cause that. If I consolidate the constants I can probably walk this back.

Comment (anothersimulacrum) [reply src/vehicle.cpp:3436]: It's also valid to use a larger type for the calculations, then return a smaller type (though CI/compilers may be a bit annoying about casting to smaller types).

Comment (natsirt721) [reply src/vehicle.cpp:3436]: 32 bit integers should be able to support ~1/2 a DeLorean (580 MW) before overflowing. Thats commercial nuclear reactor range of power output. I think that should be plenty.
