### PR TITLE
Fix wall piercing, refactor a tiny bit

### LINKED ISSUE #13593: Reinforced glass can be shot through
Windows 8.1
Curses build 691dc5f

When a gun with high-ish damage (my guess is over 40, since that's the str_min value of reinforced glass walls) is fired through a reinforced glass wall, it passes through without destroying it and then deals ludicrous damage to whatever it hits. Replicated with M4A1(48dmg), Barret .50cal rifle(~70dmg) and RM99 revolver(~50dmg). AK-47(38dmg) rounds were stopped properly.

Screenshot:
cdda_reinf_glass_bug

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/26781151-reinforced-glass-can-be-shot-through?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #13593

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -3826,29 +3825,25 @@ void map::shoot( const tripoint &p, projectile &proj, const bool hit_items )
...
-                    tripoint tmp = p;
-                    int &i = tmp.x;
-                    int &j = tmp.y;
-                    for( i = p.x - 2; i <= p.x + 2; i++ ) {
-                        for( j = p.y - 2; j <= p.y + 2; j++ ) {
-                            if (move_cost( tmp ) > 0 && one_in(3)) {
-                                    spawn_item( tmp, "gasoline" );
-                            }
+                    for( const tripoint &pt : points_in_radius( p, 2 ) ) {
+                        if( one_in( 3 ) && move_cost( tmp ) > 0 ) {
```
Comment (kevingranade) [inline src/map.cpp]: s/tmp/pt/?
