### PR TITLE
Character randomization sometimes produces 'crossdressing' characters

### LINKED ISSUE #76808: Outfit gender is not saved in characte template
### Describe the bug

When you load a character template outfit is always set to male

### Attach save file

N/A

### Steps to reproduce

Make a character
Set outfit to female
Save template
Load template
See outfit being set to male

### Expected behavior

Outfit should be set to female

### Screenshots

_No response_

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.19045.4894 (22H2)
- Game Version: 26de5a1 [64-bit]
- Graphics Version: Tiles
- Game Language: English [en]
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Portal Storms Ignore NPCs [personal_portal_storms],
    Slowdown Fungal Growth [no_fungal_growth],
    Wilderness [wilderness] (custom mod, basically innawoods lite)
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RenechCDDA**
#### Summary
Features "Character randomization sometimes produces 'crossdressing' characters"

#### Purpose of change
While examining the new character code I noticed that character randomization *always* locked the outfit gender to actual gender. Not all people wear clothes considered typical for their gender, so this is a strange omission.

* Fix #76808 (by accident even)

#### Describe the solution
Give it a 10% chance to give the randomized character a different gender's outfit.

Character templates will properly save the outfit gender and re-apply it when that template is used again

#### Describe alternatives you've considered
I was just going to make it 50/50 on the outfit but that was TOO GAY. This is only moderately gay.

#### Testing
Randomizing sometimes gives other gender outfits:

https://github.com/user-attachments/assets/d6df94d0-0dfd-4e69-9c43-a091009bc03c

Outfit gender is properly saved with character template:

https://github.com/user-attachments/assets/21ad53c5-9086-42bd-af97-75d4d7f6fb64

### CODE REVIEW

**Comment by RenechCDDA** [comment]
Oops, accidentally pulled the proposed patch for #76808. But hey, it seems to work so nothing wrong with gaying it up some more.

File: src/newcharacter.cpp [hunk 1]
```diff
@@ -4547,7 +4547,11 @@ void set_description( tab_manager &tabs, avatar &you, const bool allow_reroll,
         } else if( action == "RANDOMIZE_CHAR_DESCRIPTION" ) {
             bool gender_selection = one_in( 2 );
             you.male = gender_selection;
-            outfit = gender_selection;
+            if( one_in( 10 ) ) {
```
Comment (Psithief) [inline src/newcharacter.cpp:4550]: You're not going for a demographically accurate probability here, I imagine?

Comment (Fris0uman) [reply src/newcharacter.cpp:4550]: We don't really need to base this on reality, it doesn't affect NPCs or any other thing than the player, in the case of making a random character.

Comment (kevingranade) [reply src/newcharacter.cpp:4550]: If you have demographics for us, feel free to provide them for context if nothing else.
I ran across this, but it's hard to draw conclusions from it https://www.statista.com/chart/30170/respondents-that-have-purchased-fashion-outside-of-their-gender-identity/
