### PR TITLE
Fix monsters not spawning

### LINKED ISSUE #12320: No Creatures Anywhere
In the latest experimental, there are no creatures/monsters to be found anywhere in the world. It appears to be related to #12318. Monsters spawn in experimental 3125 but not in 3126.

<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/13558374-no-creatures-anywhere?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F146201&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by BevapDin**
Use correct submap (depending on the z-level).

Initialize the position of the monster because can_move_to does not allow movement across z-levels and the initial z-pos of the monster is far away, so it always returned false.
This might also affect monsters on stairs not spawning (I'm not sure about that). In any case, there should probably be a separate function that checks whether the monster can _exists_  (wants to exist) on a target square, that function should not check the current position of the monster.

Reset `pos` because fx,fx (which it depends on) have changed.

Fixes #12320

### CODE REVIEW

File: src/map.cpp [hunk 1]
```diff
@@ -6335,6 +6335,7 @@ void map::spawn_monsters( const tripoint &gp, mongroup &group, bool ignore_sight
             continue;
         }
         monster tmp( GetMType( spawn_details.name ) );
+        tmp.spawn( p ); // So can_move_to works correctly
```
Comment (Coolthulhu) [inline src/map.cpp]: `p` is only declared in the loop below.

Comment (BevapDin) [inline src/map.cpp]: Ah, yes - this part wasn't tested, only the part below. It is fixed.

**Comment by Coolthulhu** [comment]
I'll probably remove that z-level check in `can_move_to` and instead check it somewhere in monster move code. It has a check for distance <= 1 - I'll add a zlevel check there.
