### PR TITLE
SUMMARY: Bugfixes "Fix crash when resizing window during character creation"

### LINKED ISSUE #24302: Resizing the window during character creation crashes the game
Game version: 0.C-29034-gf05215284e

Operating system: Windows 10

Tiles or curses: Tiles

### Expected behavior

No crash.

### Actual behavior

Exception thrown at 0x00007FF6F4D11E1E in Cataclysm.exe: 0xC0000005: Access violation reading location 0x0000000000000000.

Call stack:

```
>	Cataclysm.exe!submap::get_ter(const int x, const int y) Line 70	C++
 	Cataclysm.exe!map::build_outside_cache(int zlev) Line 7520	C++
 	Cataclysm.exe!map::build_map_cache(int zlev, bool skip_lightmap) Line 7592	C++
 	Cataclysm.exe!game::draw() Line 4601	C++
 	Cataclysm.exe!game::refresh_all() Line 4910	C++
 	Cataclysm.exe!game::init_ui(const bool resized) Line 711	C++
 	Cataclysm.exe!game_ui::init_ui() Line 8	C++
 	Cataclysm.exe!handle_resize(int w, int h) Line 1274	C++
 	Cataclysm.exe!CheckMessages() Line 1330	C++
 	Cataclysm.exe!input_manager::get_input_event() Line 1748	C++
 	Cataclysm.exe!input_context::handle_input() Line 711	C++
 	Cataclysm.exe!set_description(const catacurses::window & w, player & u, bool allow_reroll, points_left & points) Line 2304	C++
 	Cataclysm.exe!player::create(character_type type, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & tempname) Line 518	C++
 	Cataclysm.exe!main_menu::new_character_tab() Line 657	C++
 	Cataclysm.exe!main_menu::opening_screen() Line 417	C++
 	Cataclysm.exe!SDL_main(int argc, char * * argv) Line 518	C++
 	Cataclysm.exe!main_utf8(int argc, char * * argv) Line 127	C
 	Cataclysm.exe!WinMain(HINSTANCE__ * hInst, HINSTANCE__ * hPrev, char * szCmdLine, int sw) Line 191	C
 	Cataclysm.exe!invoke_main() Line 99	C++
 	Cataclysm.exe!__scrt_common_main_seh() Line 253	C++
 	Cataclysm.exe!__scrt_common_main() Line 296	C++
 	Cataclysm.exe!WinMainCRTStartup() Line 17	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

### Steps to reproduce the behavior

1. New Game → Random Character → select a world
2. Wait until the character screen is shown.
3. Resize the window.

### PR DESCRIPTION
**Pull request by ralreegorganon**
#### Summary
SUMMARY: Bugfixes "Fix crash when resizing window during character creation"

#### Purpose of change
Fixes #24302 - resizing window during character creation crashes game

#### Describe the solution
Previous check was asserting that the character's name was not empty as a check that the world was loaded and ready for the UI refresh after resizing. However, in the character creation screen, it is possible to have a character name and not have a loaded world (e.g. when the user used a random character or has typed in their character name). Resizing the window would then lead to a crash.

This updates that check to instead verify that the user's ID has been set.

#### Describe alternatives you've considered
* I looked at some other attributes currently used as markers for when the game was "ready", such as `game.new_game` and `world_generator.active_world` but they were not set or constant at appropriate times to differentiate this.
* I considered adding another flag to more directly represent when the world was in a state to accept calls to `refresh_all`, but the scope seemed broader than was necessary to mitigate this crash.

#### Additional context
This resolves the crashing issue, but the behavior when resizing the window during most game states is still less than desirable. In this particular case, the user will be presented with a blank screen, and only upon taking action that triggers a repaint of sections of the screen (e.g. shifting forward or backwards in tabs) will they actually see anything. This is the existing behavior (e.g. if attempted on the character creation screen without a name entered) that is prevalent across the entire application and out of scope for this resolution.

### CODE REVIEW

File: src/game.cpp [hunk 1]
```diff
@@ -708,8 +708,8 @@ void game::init_ui( const bool resized )
     liveview.init();
 
     //Refresh only if ingame. Will crash on main menu
```
Comment (OrenAudeles) [inline src/game.cpp]: Is this comment still accurate? If not please remove, or rephrase, it.
