### PR TITLE
[RDY][CR] Refactor visual effects of bleeding/gibbing/etc and fix an issue

### LINKED ISSUE #16655: Turret is bleeding
From 0.C-4623

Rammed a turret slowly and repeatedly with a spiked vehicle. It was pushed back for a while, then I realized it seemed to be leaving a blood trail.

blood

Probably shouldn't.

### PR DESCRIPTION
**Pull request by codemime**
Just a bit of refactoring. Fixes #16655. ~~WIP because not all occurrences of bleeding were replaced yet~~ Seems enough for now.

EDIT:  Summary:
- The `map` class becomes responsible for adding trivial types of splatters and splashes
- The `tripoint_range` class can now be used as a valid iterator (here the `random_entry()` is used for picking random points from a valid range)
- Line functions have been slightly tweaked to be able to shift a point along a line
- Monster explosion and butchering activity now use a unified function to determine the number of meat chunks.
- Hallucinations don't return neither blood nor giblets (according to @Coolthulhu's suggestion)
- Added a guard clause to prevent "fields of nothing"
- Vehicles get covered with blood after adding splatters of either blood or gibs
- ~30 lines of code are gone.

### CODE REVIEW

**Comment by karols146** [comment]
Wow that solution is awesome. Good job

**Comment by illi-kun** [comment]
Hehe, you guys are hunger for fix for this issue. Nice job!

File: src/creature.cpp [hunk 1]
```diff
@@ -102,6 +103,24 @@ void Creature::reset()
     reset_bonuses();
     reset_stats();
 }
+
+void Creature::bleed( const tripoint &where, int intensity ) const
```
Comment (Coolthulhu) [inline src/creature.cpp]: I don't really see a good reason for this function to exist in `Creature`. It delegates bleeding on map to the critter and re-gets a lot of stats over and over.

It should be blood splatter function's role to do the bleeding, critter should only provide blood type. Hallucinations can be handled by giving them no blood type.

Comment (codemime) [inline src/creature.cpp]: > It should be blood splatter function's role to do the bleeding, critter should only provide blood type.

I started to think similarly when had to deal with gore and also found blood spreading in mapgen. So I tend to agree.

> Hallucinations can be handled by giving them no blood type.

Good idea. I think it should be handled in `monster::bloodType()`.

> EDIT: By "blood splatter function" I mean the cause of bleeding. The function in ranged.cpp and the similar one in vehicle.cpp. They determine the trajectory of blood, so they should handle the bleeding on too.

There are even more of them scattered over the code. IMHO there should me as few of such functions, as possible, and they shouldn't belong neither to ranged.cpp nor vehicle.cpp.

Comment (Coolthulhu) [inline src/creature.cpp]: > There are even more of them scattered over the code. IMHO there should me as few of such functions, as possible, and they shouldn't belong neither to ranged.cpp nor vehicle.cpp.

Could be wrapped up as `map::splatter` taking blood type, point of origin and endpoint, handling things like blood trail stopping on an obstacle.
Alternatively it could take a list of points to splatter blood on, but that would leave trajectory logic to caller, not reducing duplication all that much.

**Comment by codemime** [comment]
@karols146, @illi-kun, @Coolthulhu  Thanks.
Ready to be reviewed / tested.

File: src/map.cpp [hunk 2]
```diff
@@ -5645,6 +5636,50 @@ void map::remove_field( const tripoint &p, const field_id field_to_remove )
     }
 }
 
+void map::add_splatter( const field_id type, const tripoint &where, int intensity )
```
Comment (Coolthulhu) [inline src/map.cpp]: This really doesn't look necessary

Comment (codemime) [inline src/map.cpp]: It prevents removing fields using negative `intensity` and IMHO more consistent (in case some other changes to _splatters_ will be made).

File: src/mondeath.cpp [hunk 3]
```diff
@@ -57,42 +57,33 @@ void mdeath::normal(monster *z)
     if ( z->type->in_species( ZOMBIE )) {
             sfx::play_variant_sound( "mon_death", "zombie_death", sfx::get_heard_volume(z->pos()));
         }
-    m_size monSize = z->type->size;
+    bool bigBeast = z->type->size >= MS_MEDIUM;
```
Comment (Coolthulhu) [inline src/mondeath.cpp]: Some old code uses `camelCase`, but separating words with an underscore is preferred.

File: src/monster.cpp [hunk 4]
```diff
@@ -1532,55 +1532,38 @@ void monster::explode()
...
-                        break;
+        for( size_t j = 0; j < traj.size(); j++ ) {
+            tarp = traj[j];
+            if( one_in( 2 ) && type_blood != fd_null ) {
+                g->m.add_splatter( type_blood, tarp );
+            } else {
+                g->m.add_splatter( type_gib, tarp, rng( 1, j + 1 ) );
+            }
+            if( g->m.impassable( tarp ) ) {
+                if( !g->m.bash( tarp, 3 ).success ) {
```
Comment (Coolthulhu) [inline src/monster.cpp]: Bash succeeding does not guarantee the obstacle is removed. For example, chipped walls and damaged doors.

File: src/creature.cpp [hunk 5]
```diff
@@ -102,6 +102,12 @@ void Creature::reset()
     reset_bonuses();
     reset_stats();
 }
+
+void Creature::bleed() const
```
Comment (Coolthulhu) [inline src/creature.cpp]: This looks really unnecessary. It doesn't really fix any code duplication since it would be used in very few places and it already managed to gain a potential bug: `bloodType` can return `fd_null`, which `add_splatter` will then use to create a field of nothing.

Comment (codemime) [inline src/creature.cpp]: It's used in three places and looks rather nice there. Why get rid of it?
>  already managed to gain a potential bug: bloodType can return fd_null, which add_splatter will then use to create a field of nothing.

Then the bug is in the `add_field()`. It should have a guard clause since fields of nothing are meaningless anyway.

File: src/map.cpp (hunk 2 above)
Comment (codemime) [inline src/map.cpp]: > Cancel on fd_null

This IMHO has to be done in `add_field()`.

> If the field type is fd_blood, splatter some blood on vehicle parts

Good suggestion, but why only blood? Any liquid (vomit, acid etc) would look nice on them. If it's a limitation of the implementation, it would be nice to extend it.

File: src/monster.cpp (hunk 4 above)
Comment (codemime) [inline src/monster.cpp]: Pre-existing code. I tried to keep the logic intact.

File: src/mondeath.cpp (hunk 3 above)
Comment (codemime) [inline src/mondeath.cpp]: Simply sticked to the neighbors here, usually I don't do that.

File: src/map.cpp (hunk 2 above)
Comment (codemime) [inline src/map.cpp]: > If the field type is fd_blood, splatter some blood on vehicle parts

Added.

**Comment by codemime** [comment]
All set.

File: src/player.cpp [hunk 6]
```diff
@@ -12963,19 +12963,6 @@ void player::burn_move_stamina( int moves )
     }
 }
 
-field_id player::playerBloodType() const
-{
-    if (has_trait("ACIDBLOOD"))
```
Comment (BevapDin) [inline src/player.cpp]: The logic in this function has been completely erased, why?

File: src/map_iterator.h [hunk 7]
```diff
@@ -1,6 +1,7 @@
 #ifndef MAP_ITERATOR_H
 #define MAP_ITERATOR_H
 
+#include <stddef.h>
```
Comment (BevapDin) [inline src/map_iterator.h]: The header for C++ is called `cstddef` - `stddef.h` is for C.

File: src/player.cpp (hunk 6 above)
Comment (codemime) [inline src/player.cpp]: It duplicates `Character::bloodType()` verbatim. If we ever need a different behavior here, we can always override it.

Comment (BevapDin) [inline src/player.cpp]: I see, that was not obvious from the diff. Code de-duplication is always nice.

File: src/ranged.cpp [hunk 8]
```diff
@@ -283,7 +293,8 @@ dealt_projectile_attack Creature::projectile_attack( const projectile &proj_arg,
             // Critter can still dodge the projectile
             // In this case hit_critter won't be set
             if( attack.hit_critter != nullptr ) {
-                splatter( blood_traj, dealt_dam.total_damage(), critter );
+                g->m.add_splatter_trail( critter->bloodType(), blood_traj,
+                                         blood_trail_len( dealt_dam.total_damage() ) );
```
Comment (Coolthulhu) [inline src/ranged.cpp]: This doesn't seem to do anything, I'm not getting any blood splatters from headshotting zeds with .50.

File: src/monster.cpp [hunk 9]
```diff
@@ -1532,55 +1532,39 @@ void monster::explode()
...
-            case MS_HUGE:
-                num_chunks = 16;
-                break;
-        }
 
-        for( int i = 0; i < num_chunks; i++ ) {
-            tripoint tarp( posx() + rng( -3, 3 ), posy() + rng( -3, 3 ), posz() );
-            std::vector<tripoint> traj = line_to( pos(), tarp, 0, 0 );
+    for( int i = 0; i < num_chunks; i++ ) {
+        tripoint tarp( pos() + tripoint( rng( -3, 3 ), rng( -3, 3 ), 0 ) );
```
Comment (Coolthulhu) [inline src/monster.cpp]: You can add points to tripoints, no need to explicitly specify that 0 z component.

Comment (codemime) [inline src/monster.cpp]: Will do.

**Comment by codemime** [comment]
Which version of `g++`? `g++ 4.9.2` does the conversion implicitly.

File: src/ranged.cpp (hunk 8 above)
Comment (codemime) [inline src/ranged.cpp]: The deleted line neither did anything (at least recently). See #16991.
