### PR TITLE
More portal storm dungeons bug fixes

### LINKED ISSUE #58925: When in the new portal storm maze/dungeon, sometimes the entire structure disappears
### Describe the bug

I ventured into the new dungeon like structure recently introduced for portal storms. As I was moving through it, the structure while doing its usual shifting, had suddenly disappeared, leaving me high in the sky.

But oddly enough, waiting turns does not make me fall. But if I try to move, it asks me if I really want to move to this ledge.

Also for context of how long it took before this happened, I was able to reach the portals at the end of the level, although I picked one which sent me to the start. The structure disappeared as I was halfway from reaching those portals again.

### Steps to reproduce

1. Trigger Portal Storm
2. Enter dungeon
3. Move around or wait
4. The entire structure will disappear.

### Expected behavior

It shouldn't disappear. Unless it is supposed to... It's not very clear what one might do after this though.

### Screenshots

Here my character is stuck in the air. The shifting masses that were also in the maze are here with me.
image
Also notice in my tiny overmap above the temperature reading, my memorized vehicles are shown to be below me, not far from where I entered the structure that spawned near my base

I wasn't gonna lose this character to a bug, so I teleported to the ground. Here is the ground level entrance, however the portal has despawned
image

### Versions and configuration

- OS: Windows
    - OS Version: MINGW/CYGWIN/MSYS2 on unknown Windows version
- Game Version: 26b4c80 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
None

#### Purpose of change
Fix #58925
Prevent enemies from triggering portal dungeon traps and allow dialog telefragging.

### CODE REVIEW

**Comment by anoobindisguise** [comment]
Am I understanding this correctly? If I don't wear a 5-point anchor going into the portal dungeons, the powers that be can telefrag me intentionally?

File: src/teleport.cpp [hunk 1]
```diff
@@ -75,24 +75,37 @@ bool teleport::teleport_to_point( Creature &critter, tripoint target, bool safe,
...
+            for( int y = 1; y < 5; y++ ) {
+                for( int i = 0; i < 15 && here.impassable( target ); i++ ) {
+                    target.x += rng( -y, y );
+                    target.y += rng( -y, y );
+                    if( !here.impassable( target ) ) {
+                        break;
+                        break;
+                    }
+                }
             }
```
Comment (andrei8l) [inline src/teleport.cpp:89]:
```suggestion
            const cata::optional<tripoint> nt =
                random_point( points_in_radius( target, 5 ),
            []( const tripoint & el ) {
                return get_map().passable( el );
            } );
            target = nt ? *nt : target;
```
