### PR TITLE
Consume fixes

### LINKED ISSUE #40505: Unable to drink or eat while at `Very Hungry`; Stomach overflow!
# Describe the bug

My character suddenly becomes unable to eat or drink even while the hunger meter is showing up as `very hungry`.  Forcing him to drink causes him to become engorged. Forcing him to drink again flips it back to `very hungry`!

Appears to be related to #40402 .

It appears that this can cause a savefile-breaking crash! See the comment on this issue, and the one after.

https://github.com/CleverRaven/Cataclysm-DDA/issues/40268#issuecomment-627200381

# Steps To Reproduce

1. Wait until stomach becomes empty. Check stomach via debug
2. Craft some clean water.
3. Drink clean water, pour rest into a container. (Warning: Don't try to use the eat menu inside my car, or the game breaks.)
4. Check stomach via debug.
5. Force yourself to drink again.
6. Check stomach again via debug. 

# Expected behavior

Stomach fills up instead of flipping back and forth between sane values and negatives! 

# Screenshots

Stomach at zero

image

Drink a liter of water...

image

MAGIC!!!

Try to drink more water, and this happens despite your hunger status showing up as `very hungry`!

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2123-g10dbb76 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries]
]

# Additional context

Save file: 
[Palmer Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4619232/Palmer.Heights.zip)

Mods: 
[mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4619277/mods.zip)

### LINKED ISSUE #40506: Consumed something that was not food, drink or medicine/drugs error while opening the Eat menu
# Describe the bug

If you're surrounded by mountains of loots and try to open the eat menu... The game thinks that you're trying to eat everything around you, and may crash! The more items you're surrounded with, the more likely it is for a crash to occur!

Debug message that's thrown for EACH items around you while opening the eat menu.

```
 DEBUG    : Consumed something that was not food, drink or medicine/drugs

 FUNCTION : time_duration Character::get_consume_time(const item&)
 FILE     : src/consumption.cpp
 LINE     : 1668
```

(I commented this on this issue, thinking that it was related. Might be a whole different thing by itself! https://github.com/CleverRaven/Cataclysm-DDA/issues/40268#issuecomment-627113341 )

# Steps To Reproduce

1. Load up my game, ignore all error messages.
2. Press `E` inside my car.
3. Despair at the flood of error messages, and possibly a crash! 

# Expected behavior

I'm not trying to eat everything! I'm just opening the eat menu, so... Instead of pretending that I ate everything around me, show me foods that I want to eat!

# Screenshots

image

# Versions and configuration

- OS: Windows
    - OS Version: 10.0 1903
- Game Version: 0.E-2123-g10dbb76 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Aftershock [aftershock],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    XEAS [XEAS],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    More City Locations [cityside],
    No Rail Stations [No_Rail_Stations],
    sees-player icon, retrodays [sees_player_retro],
    Stats Through Kills [stats_through_kills],
    SpeedyDex [speedydex],
    Arcana and Magic Items [Arcana],
    Graphical Overmap [Graphical_Overmap],
    Advanced Gear [adv_gear],
    Blaze Industries [blazeindustries]
]

# Additional context

Save: 
[Palmer Heights.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4613546/Palmer.Heights.zip)

Mods: 
[mods.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4613545/mods.zip)

### PR DESCRIPTION
**Pull request by Ramza13**
#### Summary
SUMMARY: Bugfixes "Fix bugs in the consume code."

#### Purpose of change
Fixes #40505
Fixes #40506
Fixed a divide by zero error and added sensible default case handling/removed debugmsg.

### CODE REVIEW

File: src/consumption.cpp [hunk 1]
```diff
@@ -1629,7 +1633,8 @@ time_duration Character::get_consume_time( const item &it )
 {
     const int charges = std::max( it.charges, 1 );
     int volume = units::to_milliliter( it.volume() ) / charges;
-    time_duration time = 0_seconds;
+    time_duration time = time = time_duration::from_seconds( std::max( ( volume /
```
Comment (kevingranade) [inline src/consumption.cpp]:
```suggestion
    time_duration time = time_duration::from_seconds( std::max( ( volume /
```

**Comment by Night-Pryanik** [comment]
Please properly fill the `Summary` section of the OP.

**Comment by DillonSimeone** [comment]
Bad news,  #40506 is still occurring.
