### PR TITLE
Prevent reloading when target ammo will not stack with ammo already in gun.

### LINKED ISSUE #41999: Remington 700 .30-06 does not reload properly
# Describe the bug

Gun reloads are unreliable. Not even sure what's causing it, but most of the time it does not reload, and then once in a while it reloads properly. Still consumes ammo every time. Attaching a save game at the exact situation where I found reloading not to work, in hopes that it will help pinpoint the issue.

# Steps To Reproduce

1. Load provided save game
2. Reload Remington 700 .30-06, which is in inventory
3. Cry as the ammo is sucked into the void
3a. Stare in deep vexation if/when the ammo is not, in fact, sucked into the void

# Expected behavior

Gun reloads properly, rather than devouring ammo.

# Versions and configuration

10820

- OS: Windows
    - OS Version: 10.0 1909
- Game Version: 0.E-3911-g312db57 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Aftershock [aftershock],
    Arcana and Magic Items [Arcana],
    C.R.I.T Expansion Mod [crt_expansion],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Alternative Map Key [alt_map_key],
    Cataclysm++ [Cata++],
    Bionic Slots [cbm_slots],
    Disable NPC Needs [no_npc_food]
]

[Prathersville.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/4901113/Prathersville.zip)

### LINKED ISSUE #45998: Impossible to reload S&W 619
# Describe the bug

```
01:16:20.095 ERROR : (error message will follow backtrace)
    /usr/bin/cataclysm(_Z21debug_write_backtraceRSo+0x3a) [0x55e7239da00a]
    /usr/bin/cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x2d9) [0x55e7239dbd69]
    /usr/bin/cataclysm(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x67) [0x55e7239dfa37]
    /usr/bin/cataclysm(_ZN13avatar_action8use_itemER6avatarR13item_location+0x77c) [0x55e723755d9c]
    /usr/bin/cataclysm(_ZN4game19inventory_item_menuE13item_locationRKSt8functionIFivEES5_NS_28inventory_item_menu_positionE+0x1a2f) [0x55e723b9262f]
    /usr/bin/cataclysm(_ZN18advanced_inventory14action_examineEP21advanced_inv_listitemR23advanced_inventory_pane+0x14b) [0x55e7236adf6b]
    /usr/bin/cataclysm(_ZN18advanced_inventory7displayEv+0xad3) [0x55e7236baed3]
    /usr/bin/cataclysm(_Z19create_advanced_invv+0x3c) [0x55e7236bb27c]
    /usr/bin/cataclysm(_ZNK13activity_type12call_do_turnEP15player_activityP6player+0x93) [0x55e72369be53]
    /usr/bin/cataclysm(_ZN15player_activity7do_turnER6player+0x146e) [0x55e72464925e]
    /usr/bin/cataclysm(_ZN4game16process_activityEv+0x4b) [0x55e723b6884b]
    /usr/bin/cataclysm(_ZN4game7do_turnEv+0x1f7) [0x55e723bd9147]
    /usr/bin/cataclysm(main+0x1178) [0x55e7234e2208]
    /lib64/libc.so.6(__libc_start_main+0xeb) [0x7f4948210ebb]
    /usr/bin/cataclysm(_start+0x2a) [0x55e7235cbd7a]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:893
    DebugLog(DebugLevel, DebugClass)
    …/src/debug.cpp:1052
    std::char_traits<char>::length(char const*)
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/char_traits.h:335
    std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/ostream:571
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.cpp:293
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local() const
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:222
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:231
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:658
    void realDebugmsg<>(char const*, char const*, char const*, char const*)
    …/src/debug.h:80
    avatar_action::use_item(avatar&, item_location&)
    …/src/avatar_action.cpp:1023
    game::inventory_item_menu(item_location, std::function<int ()> const&, std::function<int ()> const&, game::inventory_item_menu_position)
    …/src/game.cpp:2289
    std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:729
    std::__shared_ptr<item_location::impl, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:1169
    std::shared_ptr<item_location::impl>::~shared_ptr()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr.h:103
    item_location::~item_location()
    …/src/item_location.h:23
    advanced_inventory::action_examine(advanced_inv_listitem*, advanced_inventory_pane&)
    …/src/advanced_inv.cpp:1453
    advanced_inventory::display()
    …/src/advanced_inv.cpp:1659
    create_advanced_inv()
    …/src/advanced_inv.cpp:70
    activity_type::call_do_turn(player_activity*, player*) const
    …/src/activity_type.cpp:112
    player_activity::do_turn(player&)
    …/src/player_activity.cpp:278
    game::process_activity()
    …/src/game.cpp:1696
    game::process_activity()
    …/src/game.cpp:1690
    game::all_npcs()
    …/src/game.cpp:12218
    game::do_turn()
    …/src/game.cpp:1475
    main
    …/src/main.cpp:709
    __libc_start_main
    ??:?
    _start
    ??:?
Backtrace emission took 8 seconds.
(continued from above) ERROR : src/avatar_action.cpp:1023 [void avatar_action::use_item(avatar&, item_location&)] Failed to obtain target item
01:19:05.258 ERROR : (error message will follow backtrace)
    /usr/bin/cataclysm(_Z21debug_write_backtraceRSo+0x3a) [0x55e7239da00a]
    /usr/bin/cataclysm(_Z8DebugLog10DebugLevel10DebugClass+0x2d9) [0x55e7239dbd69]
    /usr/bin/cataclysm(_Z12realDebugmsgPKcS0_S0_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x67) [0x55e7239dfa37]
    /usr/bin/cataclysm(_ZN4item6put_inERKS_N11item_pocket11pocket_typeE+0x400) [0x55e723d9c320]
    /usr/bin/cataclysm(_ZN4item6reloadER9Character13item_locationi+0x64b) [0x55e723dbbdfb]
    /usr/bin/cataclysm(_ZN21reload_activity_actor6finishER15player_activityR9Character+0x131) [0x55e7236245e1]
    /usr/bin/cataclysm(_ZN15player_activity7do_turnER6player+0xb06) [0x55e7246488f6]
    /usr/bin/cataclysm(_ZN4game16process_activityEv+0x4b) [0x55e723b6884b]
    /usr/bin/cataclysm(_ZN4game7do_turnEv+0x1f7) [0x55e723bd9147]
    /usr/bin/cataclysm(main+0x1178) [0x55e7234e2208]
    /lib64/libc.so.6(__libc_start_main+0xeb) [0x7f4948210ebb]
    /usr/bin/cataclysm(_start+0x2a) [0x55e7235cbd7a]

    Attempting to repeat stack trace using debug symbols…
    debug_write_backtrace(std::ostream&)
    …/src/debug.cpp:893
    DebugLog(DebugLevel, DebugClass)
    …/src/debug.cpp:1052
    std::char_traits<char>::length(char const*)
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/char_traits.h:335
    std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*)
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/ostream:571
    realDebugmsg(char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.cpp:293
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local() const
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:222
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:231
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:658
    void realDebugmsg<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&>(char const*, char const*, char const*, char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int&&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
    …/src/debug.h:80
    item::put_in(item const&, item_pocket::pocket_type)
    …/src/item.cpp:1052
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_is_local() const
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:222
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:231
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/basic_string.h:658
    ret_val<bool>::~ret_val()
    …/src/ret_val.h:20
    item::reload(Character&, item_location, int)
    …/src/item.cpp:8230
    std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:729 (discriminator 1)
    std::__shared_ptr<item_location::impl, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr_base.h:1169 (discriminator 1)
    std::shared_ptr<item_location::impl>::~shared_ptr()
    /usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/g++-v9/bits/shared_ptr.h:103 (discriminator 1)
    item_location::~item_location()
    …/src/item_location.h:23 (discriminator 1)
    reload_activity_actor::finish(player_activity&, Character&)
    …/src/activity_actor.cpp:2328 (discriminator 1)
    player_activity::do_turn(player&)
    …/src/player_activity.cpp:313
    game::process_activity()
    …/src/game.cpp:1696
    game::process_activity()
    …/src/game.cpp:1690
    game::all_npcs()
    …/src/game.cpp:12218
    game::do_turn()
    …/src/game.cpp:1475
    main
    …/src/main.cpp:709
    __libc_start_main
    ??:?
    _start
    ??:?
Backtrace emission took 8 seconds.
(continued from above) ERROR : src/item.cpp:1052 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)] tried to put an item (38_special) count (1) in a container (sw_619) that cannot contain it: pocket unacceptable because holster already contains an item
01:19:23.989 ERROR : src/item.cpp:1052 [ret_val<bool> item::put_in(const item&, item_pocket::pocket_type)] tried to put an item (38_special) count (1) in a container (sw_619) that cannot contain it: pocket unacceptable because holster already contains an item
```

# Steps To Reproduce
Load the game and try to reload your gun.

# Expected behavior

# Screenshots

# Versions and configuration

- OS: Linux
    - OS Version: <unknown>
- Game Version: 0.E-8128-gc363e3344a-dirty [64-bit]
- Graphics Version: Curses
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Bionic Professions [package_bionic_professions],
    Alternative Map Key [alt_map_key],
    No Rail Stations [No_Rail_Stations]
]

# Additional context
[2020.12.11.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/5681853/2020.12.11.zip)

### PR DESCRIPTION
**Pull request by kevingranade**
#### Summary
SUMMARY: None

#### Purpose of change
In #45998 it was reported that revolver reloading was broken. Unless I'm missing it, we're missing that test entirely.
EDIT: We were missing that test, but that's not the problem.
The code that enumerates ammo to reload was not checking that the enumerated ammo would stack with the ammo present in the weapon.  As a result, once reloading actually occurred, it would encounter consistency errors and end up eating the ammo instead of reloading it, and throw a debugmsg.
Fixes #41999 
Fixes #45998 

#### Describe the solution
Add a revolver reload test that mirrors the magazine reload test.
Add code to ammo enumeration that will prevent selection of ammo that will not stack with the ammo present in the gun already.
Also remove a check for "RELOAD_AND_SHOOT" that is no longer necessary.
Reworded the error message displayed when you have ammo that *could* be used to reload a weapon, but cannot be used to do so with the current state of the gun.

#### Describe alternatives you've considered
It's possible to refactor this to prevent repeating most of this code by extracting almost all of this to a helper that doesn't care if it's a magazine or a gun with a magazine pocket, but I'm doing this in the web interface, so I don't want to touch refactoring, at least not at the moment.

#### Testing
Build and test, I'm actually expecting it to fail because I see no reason to doubt #45998
~~If so, I strongly suspect the issue is the "holster" flag on the magazine pocket is the problem.~~
The test did not fail because the scenario was more complicated than expected.
The situation is to have a weapon partially loaded with non-favorited ammunition, have a stack of matching but favorited ammo availailable, attempt to reload.
I also verified that removing the RELOAD_AND_SHOOT check didn't break firing a bow and arrow.

### CODE REVIEW

File: tests/reload_magazine_test.cpp [hunk 1]
```diff
@@ -304,3 +304,155 @@ TEST_CASE( "reload_magazine", "[magazine] [visitable] [item] [item_location]" )
...
+                item &ammo = player_character.i_add( item( bad_ammo ) );
+                bool ok = gun.reload( player_character, item_location( player_character, &ammo ),
+                                      gun.ammo_capacity( gun_ammo ) );
+                THEN( "further reloading should fail" ) {
+                    REQUIRE_FALSE( ok );
+                    REQUIRE( gun.ammo_remaining() == mag_cap - 2 );
+                }
+            }
+        }
+    }
```
Comment (kevingranade) [inline tests/reload_magazine_test.cpp:457]:
```suggestion
    }
```

File: tests/reload_magazine_test.cpp [hunk 2]
```diff
@@ -304,3 +304,155 @@ TEST_CASE( "reload_magazine", "[magazine] [visitable] [item] [item_location]" )
         }
     }
 }
+
+TEST_CASE( "reload_revolver", "[visitable] [item] [item_location]" )
+{
+    const itype_id gun_id( "sw_619" );
+    const ammotype gun_ammo( "38" );
+    const itype_id ammo_id( "38_special" ); // any type of compatible ammo
+    const itype_id alt_ammo( "357_mag_fmj" ); // any alternative type of compatible ammo
```
Comment (kevingranade) [inline tests/reload_magazine_test.cpp:313]:
```suggestion
    const itype_id alt_ammo( "357mag_fmj" ); // any alternative type of compatible ammo
```
