### PR TITLE
Fix mission name comparisons

### LINKED ISSUE #20818: Some missions are identified by name, which is translated
Found it when describing computer effects.
Found the following examples:

- [x] Repeater mod mission compares mission name with an untranslated, hardcoded string, meaning it will always fail if the mission name is translated (fixed by #20959)
- [ ] Complete mission computer effect compares translated mission name to translated computer name, meaning it will not work if those two are translated differently (including ALLCAPS or something like that)

Edit by @Leland: moved to checklist

### PR DESCRIPTION
**Pull request by Coolthulhu**
Closes #20818

There were 3 cases where translated mission name was used instead of ID:
* Get Prospectus mission
* Find Commo Team mission
* Complete Mission computer action

First one was simple, second one is like the first one except not testable because Find Commo Team mission is not used anywhere.
The third option would require adding new fields to the weird computer code (it has horrible non-json format), but fortunately this action is used by exactly one mission, so I just changed it to be "Complete that one specific mission" action instead. This also allowed me to scrap another hack from `computer::activate_function`.

Other minor fixes:
* Made mission name translated on print rather than on load
* When completing computer mission steps, point back to mission giver. Lack of this behavior was particularly confusing in case of "complete mission" action, which gives no indication that you have to go back to mission giver to complete the mission.

### CODE REVIEW

File: src/computer.h [hunk 1]
```diff
@@ -3,6 +3,7 @@
 #define COMPUTER_H
 
 #include "cursesdef.h" // WINDOW
+#include "string_id.h"
```
Comment (BevapDin) [inline src/computer.h]: This includes seems to unnecessary. Where in the header do you use `string_id`?

File: src/mission.cpp [hunk 2]
```diff
@@ -455,7 +456,7 @@ std::string mission::name()
     if (type == NULL) {
         return "NULL";
     }
-    return type->name;
+    return _( type->name );
```
Comment (BevapDin) [inline src/mission.cpp]: Don't you need to call it as `_( ....c_str() )`?

**Comment by narc0tiq** [comment]
Jenkins, rebuild please (I need to see if updating the Jenkins and its plugins unf--ked the PR builder).
