### PR TITLE
fix integrated armor burning up

### LINKED ISSUE #57479: Mutated skin (E.g. protective bark, phelloderm, epicuticle) can be permanently destroyed
### Describe the bug

Mutated skins visible in the (W)ear menu can be destroyed permanently, making the mutation it belongs to meaningless.

### Steps to reproduce

1. Have mutated skin, such as protective bark
2. Stand in a fire for a second or two
3. Have your skin permanently melt off, leaving you with a skin mutation that does nothing

### Expected behavior

This would be cool if the infrastructure for permanent injuries existed, but at least for now, mutated "apparel" should be indestructible or at least regenerate.

### Screenshots

image

### Versions and configuration

- OS: Windows
    - OS Version: 10.0.18363.1500 (1909)
- Game Version: 4974cb9 [64-bit]
- Graphics Version: Tiles
- Game Language: System language []
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    No Fungal Growth [no_fungal_growth],
    Bionic Professions [package_bionic_professions],
    Blaze Industries [blazeindustries],
    Magiclysm [magiclysm],
    DinoMod [DinoMod],
    Crazy Cataclysm [crazy_cataclysm],
    Graphical Overmap [Graphical_Overmap],
    Graphical Overmap Magiclysm [Graphical_Overmap_Magiclysm],
    SpeedyDex [speedydex],
    Stats Through Kills [stats_through_kills],
    Stats Through Skills [StatsThroughSkills],
    Aftershock [aftershock],
    No Rail Stations [No_Rail_Stations]
]

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by anoobindisguise**
#### Summary
Bugfixes "integrated armor is now fireproof"

#### Purpose of change
Fixes #57479

#### Describe the solution
If armor has the integrated flag the evaluation that would burn it short circuits.

#### Testing
Compiled, mutated some integrated armor which got burnt up previously, played around in fire, armor did not burn (only I did)

### CODE REVIEW

File: src/character_attire.cpp [hunk 1]
```diff
@@ -1782,7 +1782,7 @@ void outfit::absorb_damage( Character &guy, damage_unit &elem, bodypart_id bp,
         if( outermost && elem.type == damage_type::HEAT && elem.amount >= 1.0f ) {
             // TODO: Different fire intensity values based on damage
             fire_data frd{ 2 };
-            destroy = armor.burn( frd );
+            destroy = ( !armor.has_flag( flag_INTEGRATED ) && armor.burn( frd ) );
```
Comment (Night-Pryanik) [inline src/character_attire.cpp:1785]:
```suggestion
            destroy = !armor.has_flag( flag_INTEGRATED ) && armor.burn( frd );
```
