### PR TITLE
stop large critters from using tight passages

### LINKED ISSUE #32795: Tame horses will climb through windows to reach you
# Describe the bug

I was very surprised when cooking to have a horse climb in through the window so it could [make noise](https://github.com/CleverRaven/Cataclysm-DDA/issues/32746) while I crafted.

# Steps To Reproduce

1. Make friends with a horse.
1. Lock it outside, but accidentally leave a window open.
1. The horse is now inside.

# Expected behavior

Only small and agile horses climb through windows.

# Versions and configuration

- OS: Ubuntu 16.04 LTS
- Game Version: f95875f3eea4403333379d8a6d6e848c9d2ab837 with #32754, #32782 and MSX tiles applied.
- Graphics Version: Tiles
- Mods loaded:
```
    Dark Days Ahead [dda],
    Filthy Clothing [filthy_morale],
    Alternative Map Key [alt_map_key],
    [DP_MOD] Indicators: REMIX [DP_REMIX_INDICATORS],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Sleep Deprivation [sleepdeprivation],
    Bionic Slots [cbm_slots],
    sees-player icon, -attitude [sees_player_less_attitude]
```

### PR DESCRIPTION
**Pull request by ghost**
#### Summary
```SUMMARY: Bugfixes "stops large critters from using tight passages"```

#### Purpose of change
Fixes #32795

#### Describe the solution
Stops large or huge critters from using terrain flagged as a "THIN_OBSTACLE". The JSON is already in place, just needed the C++.

Edit: Now stops large or huge characters as well.

#### Describe alternatives you've considered
Several, but this was decidedly the best. See the comments linked in the issue above for details.

#### Testing
It was an extremely small change that just added a check in the monster pathing function using JSON flags already present. Although I'm going to wait to make sure the CI checks come back clean before removing the [WIP]. I'm still new at this.

#### Additional context
N/A

### CODE REVIEW

**Comment by kevingranade** [comment]
I'd like this to be symmetric with NPCs and players, if a horse can't fit through a window, neither should a horse-sized player.

**Comment by korvyr** [comment]
That should do it.

File: src/game.cpp [hunk 1]
```diff
@@ -9031,6 +9031,20 @@ std::vector<std::string> game::get_dangerous_tile( const tripoint &dest_loc ) co
...
 {
+    if( m.has_flag_ter( "THIN_OBSTACLE", dest_loc ) ) {
+        if( u.get_size() > MS_MEDIUM ) {
+            add_msg ( m_warning, _( "You can't fit there." ) );
+            return false; // character too large to fit through a tight passage
+        }
+        if( u.is_mounted() ) {
+            monster* mount = u.mounted_creature.get();
+            if( mount->get_size() > MS_MEDIUM ) {
+                add_msg ( m_warning, _( "You're mount can't fit there." ) );
```
Comment (cainiaowu) [inline src/game.cpp]:
```suggestion
                add_msg ( m_warning, _( "Your mount can't fit there." ) );
```

Comment (korvyr) [reply src/game.cpp]: grammar hard

File: src/game.cpp [hunk 2]
```diff
@@ -9031,6 +9031,20 @@ std::vector<std::string> game::get_dangerous_tile( const tripoint &dest_loc ) co
 
 bool game::walk_move( const tripoint &dest_loc )
 {
+    if( m.has_flag_ter( "THIN_OBSTACLE", dest_loc ) ) {
```
Comment (anothersimulacrum) [inline src/game.cpp]: This flag is used in a lot of other places - for example on underbrush. This should be replaced with a new flag.

**Comment by kevingranade** [comment]
This pull request has been mentioned on **Cataclysm: Dark Days Ahead**. There might be relevant details there:

https://discourse.cataclysmdda.org/t/uncomfortably-large-mutant-cant-fit-through-windows/21848/9
