### PR TITLE
Vitamins fixes and parasites [RDY]

### LINKED ISSUE #16304: Bone broth is inedible.
0.C-13314-g9b71645 (tiles)

Exactly what it says.

### PR DESCRIPTION
**Pull request by mugling**
Some simple fixes. As per @Rivet-the-Zombie's suggestion meat now contains a small quantity of calcium. Also fixes the issues with mutations from #16256 as identified by @Coolthulhu. Finally fixes #16304

### CODE REVIEW

**Comment by illi-kun** [comment]
Feel free to implement vitamin related feature in bionics.cpp. I'll take a break in bionic slots activity for a day or two.

File: src/consumption.cpp [hunk 1]
```diff
@@ -93,7 +93,7 @@ int player::vitamin_rate( const vitamin_id &vit ) const
         }
     }
 
-    return std::max( res, 0 );
+    return res, 0;
```
Comment (Coolthulhu) [inline src/consumption.cpp]: That doesn't look like something that was intended

Comment (mugling) [inline src/consumption.cpp]: Fixed in 6972f93

**Comment by mugling** [comment]
> Feel free to implement vitamin related feature in bionics.cpp

This can come later. I'll rebase as necessary against your work.

**Comment by Coolthulhu** [comment]
Pure herbivores need a source of calcium. Beans are pretty good at that. For now, just adding some minor calcium to veggy matter would be enough.

Yeast got inedible due to the powder thing, but yeast can be a good vitamin B1, B2, B6 and B9 (basically any B except B12, which it lacks completely) supplement.

It may be worth splitting off B12 from other vitamins. B12 deficiency is pretty common at the moment, but someone living like a medieval peasant, eating dirty roots and livers, would probably not get one. Or we can just assume survivors don't get B12 deficiency, but then it would be a good idea to mention it in the docs, to prevent stuff rich in B12 automatically containing other Bs.

Carnivores get their vitamin A primarily from the livers of their prey, they cannot synthesize it.

In general a lot of vitamins in carnivore diets come solely from the livers and other non-muscle organs. It may be worth splitting off meat into muscle meat (the tasty parts that can be crafted into meals) and organ meat (nutritious but unfit for vast majority of tasty products). Alternatively, for now the stomach can be treated as organs and get a big boost to all vitamin stats.

If you intend to keep using the material system for food stuff, it would be a good idea to split off "food material" system from "physical properties material" system. Cotton doesn't need vitamin data, eggs don't need resistance data.
This would work better with the eventual vitamin passing on craft - soup doesn't need to inherit material data from the bones used to produce it.

**Comment by Coolthulhu** [comment]
It seems that vitamin effect messages lack periods at the end.

**Comment by mugling** [comment]
> Pure herbivores need a source of calcium. Beans are pretty good at that. For now, just adding some minor calcium to veggy matter would be enough.

Ok, will do the same as for `flesh`/`hflesh`

> but yeast can be a good vitamin B1, B2, B6 and B9 (basically any B except B12, which it lacks completely)

The infrastructure is there for extending B vitamins but for now I want `VitB` to be B12 as per it's `name` argument. This can be a long-term goal once the balance of the existing vitamins is resolved.

> Alternatively, for now the stomach can be treated as organs and get a big boost to all vitamin stats.

Could we have `liver` as an item drop from some of the larger animals? Would force the player to hunt larger animals as well which is a plus for gameplay.

> If you intend to keep using the material system for food stuff, it would be a good idea to split off "food material" system from "physical properties material" system. Cotton doesn't need vitamin data, eggs don't need resistance data.

It's a stopgap for the time being. The correct implementation is to gradually migrate to comestibles inheriting from an abstract type (eg. `fruit`).

**Comment by mugling** [comment]
Finished for part 2

**Comment by Coolthulhu** [comment]
> Could we have liver as an item drop from some of the larger animals? Would force the player to hunt larger animals as well which is a plus for gameplay.

Medium sized animals should drop livers too. It should be possible to subsist on those, just that they should provide proportionally more calories than vitamins, resulting in tons of excess meat.

It would probably be better to name it "organ meat" than specifying the liver. Kidneys, hearts, intestines, spleens etc. are all good sources of some microelements and it would be better to aggregate them all than try to implement them separately. Mechanically, they're pretty much identical: they aren't fit for regular "meat" recipes and they are eaten for vitamins more than for calories.

**Comment by mugling** [comment]
> "organ meat" = offal

**Comment by Rivet-the-Zombie** [comment]
I've been considering adding offal as a butchering byproduct for that exact reason. It'd make a good filler for sausages too.

**Comment by Coolthulhu** [comment]
Offal sounds good too. It sounds more... offensive. Could come with a morale penalty, since most first worlders don't like eating "guts".

**Comment by Salganos** [comment]
I feel obliged to mention that meat (in general) does have some useful amount of Vitamin C, when raw and fresh (it's how various Inuit tribes got by), though a category system might not be ideal for expressing that.  Also that some animal livers have enough Vitamin A to be toxic.

Raw animal meat and organs are surprisingly nutritious, outside of being a serious risk for food poisoning (particularly when not fresh) and parasites (almost always).

**Comment by mugling** [comment]
With the following stats (eg. superior to meat but remains deficient in `VitC`)?
```
vitamins: [
  [ "calcium": 0.1 ],
  [ "iron" 2.0 ]
  [ "VitA", 0.5 ]
  [ "VitB", 1.0 ]
]
```

**Comment by mugling** [comment]
> Also that some animal livers have enough Vitamin A to be toxic

Not a significant issue if your `CARNIVORE`

> and parasites (almost always).

Only when domesticated, but we digress

**Comment by Coolthulhu** [comment]
> Not a significant issue if your CARNIVORE

You could give them immunity to hypervitaminosis A, but they really shouldn't produce their own vitamin A.

**Comment by mugling** [comment]
See 2d75d06. How do i add `offal` to animals?

**Comment by illi-kun** [comment]
Check ```/activity_handlers.cpp```, line 204.

**Comment by mugling** [comment]
2d75d06 adds `carnivore.json` which specifies the correct vitamins via the abstract `COMESTIBLE` for `flesh`. Offal now gains +5 `vitA`.

5273908 reworks the `iuse::RAW_*` item_actions as a more simple `parasites` property. Raw meat has ~3% chance to cause parasites whereas cooked meat only ~0.3%.

**Comment by mugling** [comment]
The only remaining change is to add offal to the activity handler but I'm not especially familiar with that code

**Comment by Coolthulhu** [comment]
NPCs should understand parasites or be immune to them. For now, immunity would be fine, since otherwise they would have to either avoid all cooked meat or it could require balancing.

**Comment by kevingranade** [comment]
Whaaaaa.....? offal is delicious man, everything from hearts to tripe to
chitterlings, yum.

**Comment by Rivet-the-Zombie** [comment]
>cooked meat only ~0.3%

Cooked meat really shouldn't carry that risk at all. It would be different if the item were something like 'rare steak', but sneaking parasites into what's assumed to be a safely prepared food is rather cruel to the player, and punishes them despite taking all possible precautions.

**Comment by mugling** [comment]
> chitterlings

I had to look that up...the wikipedia article opens with *"chitterlings is an economical dish"*

**Comment by mugling** [comment]
> safely prepared food

The counterpoint being that `cooked meat` can be produced using a skewer over a burning rag. Inactivating many parasites is more difficult than you would expect. IRL freezing is one of them most commonly used methods which obviously isn't an option open to the player. The higher level cooking recipes imply a better standard of cooking.

... talking of which we should we have vehicle freezers?

**Comment by Coolthulhu** [comment]
> The higher level cooking recipes imply a better standard of cooking.

We don't have "fried meat", "grilled meat" or "boiled meat" at the moment. Cooked meat represents all forms of cooking without extra ingredients, everything else requires at least spices.

**Comment by Salganos** [comment]
> freezing
This would need to happen during cold winters as well.  Some parasites can take a while to freeze to death, too.

**Comment by Rivet-the-Zombie** [comment]
>We don't have "fried meat", "grilled meat" or "boiled meat" at the moment. Cooked meat represents all forms of cooking without extra ingredients, everything else requires at least spices.

Those are good ideas! Until we have some means of distinction, giving parasites to cooked meat is counterintuitive and punishes the player even when they make the effort to render their food safe to eat.

**Comment by kevingranade** [comment]
If nothing else, there needs to be a safe way to prepare meat, and a clear
indication that some ways of doing it are unsafe.
Personally I'd prefer for "cooked meat" to be totally safe.

**Comment by mugling** [comment]
Ok see eb43020 which renders cooked meat safe.

The current re-implementation of `parasites` should be sufficient for now as a penalty for raw meat - we can extend it further to support differential types if additional sufficiently distinct risky foods are identified to justify the extra complexity.

**Comment by mugling** [comment]
Done for now

**Comment by Rivet-the-Zombie** [comment]
Planning on changing ````tainted```` to be a flag instead of a separate item list? I like the idea a lot; we'll be able to have separate tainted meat and tainted human meat!

**Comment by mugling** [comment]
> Planning on changing tainted to be a flag instead of a separate item list?

Yes, but I backed out of doing it in this PR as it requires overhaul of crafting. Am I correct @Coolthulhu was working on overhauling the crafting system?

**Comment by Coolthulhu** [comment]
> Am I correct @Coolthulhu was working on overhauling the crafting system?

Yeah, but it's currently stalled due to crafting system UI causing problems.

It operates on item types rather than items.

File: src/item.cpp [hunk 2]
```diff
@@ -1648,30 +1648,32 @@ std::string item::info( bool showtext, std::vector<iteminfo> &info ) const
...
+            ///\EFFECT_SURVIVAL >=5 allows detection of hallucinogenic food
+            if( has_flag( "HIDDEN_HALLU" ) && g->u.skillLevel( skill_survival ).level() >= 5 ) {
+                info.emplace_back( "DESCRIPTION", _( "* On closer inspection, this appears to be <neutral>hallucinogenic</neutral>." ) );
+            }
         }
 
-        if( ( is_food() && has_flag( "BREW" ) ) || ( is_food_container() &&
-                contents[0].has_flag( "BREW" ) ) ) {
+
+        if( ( is_food() && has_flag( "BREW" ) ) || ( is_food_container() && contents[0].has_flag( "BREW" ) ) ) {
```
Comment (Coolthulhu) [inline src/item.cpp]: Now that I look at this section and the section above, they could be combined. The food part could be extracted (something like `const item &the_food = is_food() ? *this : contents[0]`), then the flags would show for contained food too.

Currently it's no big deal, but human bone broth already hides its cannibalism description when in a container.

**Comment by Coolthulhu** [comment]
Now that parasites are no longer an iuse function, NPCs which relied on iuses to tell apart safe and dangerous food no longer see it. They should either ignore all food with parasites or be immune to all parasites.

**Comment by Coolthulhu** [comment]
Assigned before I looked into it. I can't auto-merge it right now due to conflict.

If you have a moment to spare, if you fixed that conflict and added some hack for NPC food selection (just forbidding automatically picking food with parasites, in `rate_food` in npcmove.cpp), I could merge it with this batch, assuming it has no major bugs.

**Comment by mugling** [comment]
Done

File: data/json/items/comestibles/carnivore.json [hunk 3]
```diff
@@ -0,0 +1,152 @@
...
+    "volume": 1,
+    "price": 500,
+    "spoils_in": 24,
+    "calories": 250,
+    "healthy": -1,
+    "fun": -10
+  },
+  {
+    "id": "meat_cooked",
+    "copy-from": "flesh",
```
Comment (Coolthulhu) [inline data/json/items/comestibles/carnivore.json]: Flesh? Not meat? It doesn't have nutrition

Comment (mugling) [inline data/json/items/comestibles/carnivore.json]: Yep, should copy from `meat`

File: data/json/items/comestibles/carnivore.json [hunk 4]
```diff
@@ -0,0 +1,152 @@
...
+    "name": "large stomach",
+    "description": "The stomach of a large woodland creature.  It is surprisingly durable.",
+    "proportional": {
+      "weight": 2.0,
+      "volume": 2.0,
+      "price": 1.5,
+      "calories": 2.0
+    }
+  }
+]
```
Comment (Coolthulhu) [inline data/json/items/comestibles/carnivore.json]: Tainted meat could also fit somewhere in this file.

Comment (mugling) [inline data/json/items/comestibles/carnivore.json]: > Tainted meat could also fit somewhere in this file.

I want to implement a `TAINTED` flag as opposed to further duplication

File: src/activity_handlers.cpp [hunk 5]
```diff
@@ -472,11 +472,17 @@ void activity_handlers::butcher_finish( player_activity *act, player *p )
...
+        item chunk( meat, age );
+        chunk.set_mtype( corpse );
+
+        // for now don't drop non-tainted parts overhaul of taint system to not require excessive item duplication
+        item parts( chunk.is_tainted() || chunk.made_of( material_id( "hflesh" ) ) ? meat : "offal", age );
+        parts.set_mtype( corpse );
+
+        g->m.add_item_or_charges( p->pos(), chunk );
+        for( int i = 1; i <= pieces; ++i ) {
+            g->m.add_item_or_charges( p->pos(), one_in( 3 ) ? parts : chunk );
```
Comment (Coolthulhu) [inline src/activity_handlers.cpp]: Would be better if it spawned one first and then the other. Mixing parts makes it harder to select the right ones.

File: data/json/items/comestibles/carnivore.json [hunk 6]
```diff
@@ -0,0 +1,152 @@
...
+    "name": "stomach",
+    "description": "The stomach of a woodland creature.  It is surprisingly durable.",
+    "weight": 72,
+    "volume": 1,
+    "price": 200,
+    "calories": 40,
+    "quench": 1,
+    "healthy": -1,
+    "fun": -15
+  },
```
Comment (Coolthulhu) [inline data/json/items/comestibles/carnivore.json]: Lacks spoiling data.

File: src/activity_handlers.cpp (hunk 5 above)
Comment (mugling) [inline src/activity_handlers.cpp]: Essential (now) or would-be nice (issue and next PR)?

File: data/json/items/comestibles/carnivore.json [hunk 7]
```diff
@@ -0,0 +1,152 @@
...
+  {
+    "id": "stomach",
+    "copy-from": "flesh",
+    "type":"COMESTIBLE",
+    "name": "stomach",
+    "description": "The stomach of a woodland creature.  It is surprisingly durable.",
+    "weight": 72,
+    "volume": 1,
+    "price": 200,
+    "calories": 40,
```
Comment (Coolthulhu) [inline data/json/items/comestibles/carnivore.json]: That's very low

File: data/json/items/comestibles/carnivore.json (hunk 6 above)
Comment (mugling) [inline data/json/items/comestibles/carnivore.json]: Hmmn, specify as part of `flesh` or for each item?

File: data/json/items/comestibles/carnivore.json (hunk 7 above)
Comment (mugling) [inline data/json/items/comestibles/carnivore.json]: No meaningful nutrition to be had

File: data/json/items/comestibles/carnivore.json (hunk 4 above)
Comment (Coolthulhu) [inline data/json/items/comestibles/carnivore.json]: Tainted meat is used in some recipes, most notably mutagen. It will be a while until "item with flag x" will be a valid crafting ingredient.

File: data/json/mutations.json [hunk 8]
```diff
@@ -3926,10 +3926,7 @@
         "cancels" : ["VEGETARIAN", "HERBIVORE", "RUMINANT",  "GRAZER"],
         "leads_to" : ["SAPROVORE"],
         "category" : ["MUTCAT_LIZARD", "MUTCAT_BEAST", "MUTCAT_SPIDER", "MUTCAT_CHIMERA", "MUTCAT_RAPTOR", "MUTCAT_FELINE"],
-        "vitamin_rates": [
-            [ "VitA", -999 ],
-            [ "VitC", -999 ]
-        ]
+        "vitamin_rates": [ [ "vitC", -2 ] ]
```
Comment (Coolthulhu) [inline data/json/mutations.json]: This either doesn't work or doesn't work well enough. My carnivore character keeps losing vitC at a rate very similar to other vitamins.

File: src/activity_handlers.cpp (hunk 5 above)
Comment (Coolthulhu) [inline src/activity_handlers.cpp]: Mixed items are a minor annoyance, can wait.

File: data/json/items/comestibles/carnivore.json (hunk 6 above)
Comment (Coolthulhu) [inline data/json/items/comestibles/carnivore.json]: As flesh would be safer, but some parts should rot slower. Not sure if stomachs do rot slower or faster than muscle meat, though.

Comment (mugling) [inline data/json/items/comestibles/carnivore.json]: Much faster

File: data/json/mutations.json (hunk 8 above)
Comment (mugling) [inline data/json/mutations.json]: Give me a moment to check

File: data/json/items/comestibles/carnivore.json [hunk 9]
```diff
@@ -0,0 +1,152 @@
...
+    }
+  },
+  {
+    "id": "human_flesh",
+    "copy-from": "meat",
+    "type": "COMESTIBLE",
+    "name": "human flesh",
+    "name_plural": "human fleshes",
+    "description": "Freshly butchered from a human body.",
+    "material": "hflesh"
```
Comment (Coolthulhu) [inline data/json/items/comestibles/carnivore.json]: Inheritance problem:

Human flesh is a "false material" that is later replaced with regular flesh with "CANNIBALISM" flag. This seems to happen before inheritance does, causing cooked creep below to lack the cannibalism flag.

File: src/activity_handlers.cpp [hunk 10]
```diff
@@ -472,11 +472,17 @@ void activity_handlers::butcher_finish( player_activity *act, player *p )
...
-        tmpitem.set_mtype( corpse );
-        while ( pieces > 0 ) {
-            pieces--;
-            g->m.add_item_or_charges(p->pos(), tmpitem);
+
+        item chunk( meat, age );
+        chunk.set_mtype( corpse );
+
+        // for now don't drop non-tainted parts overhaul of taint system to not require excessive item duplication
+        item parts( chunk.is_tainted() || chunk.made_of( material_id( "hflesh" ) ) ? meat : "offal", age );
```
Comment (Coolthulhu) [inline src/activity_handlers.cpp]: ```chunk.made_of( material_id( "hflesh" )```

You want to check for "CANNIBALISM" flag here, due to the material replacing.

File: data/json/items/comestibles/carnivore.json (hunk 9 above)
Comment (mugling) [inline data/json/items/comestibles/carnivore.json]: This will affect some already merged content also, I'll see if I can work it out

File: data/json/mutations.json (hunk 8 above)
Comment (mugling) [inline data/json/mutations.json]: Have candidate fix

File: src/activity_handlers.cpp (hunk 10 above)
Comment (mugling) [inline src/activity_handlers.cpp]: Needs adding to `materials.json` as documentation `//` field

File: data/json/items/comestibles/carnivore.json (hunk 9 above)
Comment (Coolthulhu) [inline data/json/items/comestibles/carnivore.json]: For now just passing "CANNIBALISM" flag is enough. Later on it may be split into "pure cannibalism" and "spiced up with cannibalism", but for now hflesh material is just flesh material + cannibalism flag.

File: data/json/mutations.json (hunk 8 above)
Comment (mugling) [inline data/json/mutations.json]: vitamin rates are expressed in minutes not hours with a default rate of 1 unit every 60 minutes.  	Fixed in f40993b

**Comment by mugling** [comment]
That should be all
