### PR TITLE
Apply extra care with monster dragging code to avoid segfaults

### LINKED ISSUE #33051: Game crash during an autosave
# Describe the bug
The game crashed while autosaving
Looks like it saved everything except the motorbike I was riding

Edit: The motorbike actually warped back to the refugee center entrance and got reset to a state it was in during previous autosave (gasoline amount, items in cargo hold). Same goes for the Free Merchants' cars that I sucked gasoline from

# Expected behavior
No crash

# Versions and configuration
- OS: Windows
    - OS Version: 10.0 1809
- Game Version: 0.D-6301-g3597e0f [64-bit]
- Graphics Version: Tiles
- Mods loaded: [
    Dark Days Ahead [dda],
    Disable NPC Needs [no_npc_food],
    Icecoon's Arsenal [ew_pack],
    Makeshift Items Mod [makeshift],
    More Survival Tools [More_Survival_Tools],
    Modular Turrets [modular_turrets],
    Salvaged Robots [Salvaged_Robots],
    Alternative Map Key [alt_map_key],
    Hydroponics [hydroponics],
    Mutant NPCs [mutant_npcs],
    More Locations [more_locations],
    Fuji's More Buildings [FujiStruct],
    Folding Parts pack [deoxymod],
    Vehicle Additions Pack [blazemod],
    Tanks and Other Vehicles [Tanks],
    No Fungal Monsters [No_Fungi],
    Safe Autodoc [safeautodoc],
    Simplified Nutrition [novitamins],
    StatsThroughSkills [StatsThroughSkills]
]

# Additional context
[crash.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3483434/crash.log)
[debug.log](https://github.com/CleverRaven/Cataclysm-DDA/files/3483435/debug.log)
[Powder Springs - corrupted.zip](https://github.com/CleverRaven/Cataclysm-DDA/files/3483438/Powder.Springs.-.corrupted.zip)

### LINKED ISSUE #33141: duplicated save and saving crashes
[<!--]
errormessage

While driving through a city I saved and got an error message, when I tryed loading back into the world I noticed I had two saves under the same name but they seemsed to both access the same file, after that whenever I tried saving while driving a similar error would come up and crash the game, saving my character's positon but not the car's. After a while of this it started effecting me even when I got out of the car so I have no idea what to do. I'm using a few mods like blazemod, more survival tools, extended guns and the like.

### PR DESCRIPTION
**Pull request by pjf**
#### Summary

```SUMMARY: Bugfixes "Fix potential segfault-on-save caused by mobs dragging critters that no longer exists."```

#### Purpose of change

Multiple reports of savegame crashes, notably #33051 and related issues.

#### Describe the solution

Based upon my interpretation of the stack-trace in #33104, it appears that `monster::store` is trying to use a dragged_foe that's not null, but is no longer valid, either. This may happen if the foe is dead, or any other condition that may cause the dragged critter object to be destroyed.

This commit:

- Always tracks the `dragged_foe_id` (an integer) rather than `dragged_foe` (a pointer) directly.
- Uses `critter_by_id()` to check the validity of the `dragged_foe_id` on the occasions when it needed. This is the same function used by the savegame loading code to restore the dragged foe.
- Moves the dragged_foe-finding functionality to its own method for clarity.
- Ensures the dragged_foe-finding code clears relevant status effects and members if we're no longer dragging a valid critter.
- Moves the nursebot operation code to its own method, also for clarity.

Note that I don't have a reproducable way to induce the bug, so I don't have a great test for this. However it's hard to have a segfault if you don't have a stale pointer to deference in the first place.

Fixes #33051. Fixes #33141.

#### Describe alternatives you've considered

Using a shared pointer, but that may require all the other critter handling code to also use shared pointers.

### CODE REVIEW

**Comment by Reaper9** [comment]
There might be other things causing the issue btw, as this happened to me when I quick-saved after literally 1 turn in a new world with a new character, with no dragging involved. Not sure how would `dragged_foe` get populated in this case, maybe the change to keep an int id instead of a pointer will fix it as well.

**Comment by pjf** [comment]
jenkins rebuild

**Comment by BevapDin** [comment]
> There might be other things causing the issue btw, as this happened to me when I quick-saved after literally 1 turn in a new world with a new character, with no dragging involved. 

Well, `monster::dragged_foe` is **never** initialized at all, except in monmove.cpp where the (also uninitialized) `monster::dragged_foe_id` is used. So it's basically UB all over.

File: src/monmove.cpp [hunk 1]
```diff
@@ -601,54 +601,11 @@ void monster::move()
...
 
-                dragged_foe->remove_effect( effect_grabbed );
-                remove_effect( effect_dragging );
-                dragged_foe = nullptr;
-
-            }
-        }
-    }
+    // Nursebot operations.
+    operate( dragged_foe );
```
Comment (BevapDin) [inline src/monmove.cpp]: You can combine this and the above into one statement, no need for a separate variable that is used only once.

File: src/monster.h [hunk 2]
```diff
@@ -525,6 +524,9 @@ class monster : public Creature
         std::bitset<NUM_MEFF> effect_cache;
         cata::optional<time_duration> summon_time_limit = cata::nullopt;
 
+        player *find_dragged_foe();
+        void operate( player *dragged_foe ); // Nursebot operations
```
Comment (BevapDin) [inline src/monster.h]: Please don't repeat comments all over the place (here, at the definition of the function and at the invocation of it).

In fact, just name it `nursebot_operate` or similar and you don't even need a comment at all.

File: src/monmove.cpp (hunk 1 above)
Comment (pjf) [reply src/monmove.cpp]: It's used later on by existing code.

https://github.com/CleverRaven/Cataclysm-DDA/pull/33145/files#diff-afa90fdb1ffaf9c03d93cd2d4ae78863L916

File: src/savegame_json.cpp [hunk 3]
```diff
@@ -1889,10 +1888,7 @@ void monster::store( JsonOut &json ) const
     }
     json.member( "inv", inv );
 
-    if( dragged_foe ) {
-        json.member( "dragged_foe_id", dragged_foe->getID() );
-    }
-
+    json.member( "dragged_foe_id", dragged_foe_id );
```
Comment (Qrox) [inline src/savegame_json.cpp]: You can save some storage space by not saving `dragged_foe_id` if it's invalid here, since monst monsters don't drag their opponents.

File: src/monster.h [hunk 4]
```diff
@@ -419,8 +419,7 @@ class monster : public Creature
         tripoint wander_pos; // Wander destination - Just try to move in that direction
         int wandf;           // Urge to wander - Increased by sound, decrements each move
         std::vector<item> inv; // Inventory
-        player *dragged_foe; // player being dragged by the monster
-        int dragged_foe_id; // id of player being dragged by the monster (for save/load)
+        int dragged_foe_id = -1; // id of player being dragged by the monster
```
Comment (Qrox) [inline src/monster.h]: While you're at it, could you please also fix the inconsistency as to what number is used for invalid id? For example, the following comment says that the invalid id should be 0:
https://github.com/CleverRaven/Cataclysm-DDA/blob/cdbd895fd439ee51ecb55048a416f0be14a0e201/src/player.h#L1645-L1646
The code in `game.cpp` also suggests so:
https://github.com/CleverRaven/Cataclysm-DDA/blob/cdbd895fd439ee51ecb55048a416f0be14a0e201/src/game.cpp#L3736-L3741
`next_npc_id` is initialized as 1 in a new game:
https://github.com/CleverRaven/Cataclysm-DDA/blob/cdbd895fd439ee51ecb55048a416f0be14a0e201/src/game.cpp#L270
And `assign_npc_id()` is used to assign id to newly created npcs and the player.
However, the following code uses -1 as the invalid number instead:
https://github.com/CleverRaven/Cataclysm-DDA/blob/cdbd895fd439ee51ecb55048a416f0be14a0e201/src/player.cpp#L10698-L10707
I think fixing `player::setID()` should be enough to address this problem

Comment (pjf) [reply src/monster.h]: I would love for this inconsistency to be fixed, but I'm concerned about it creeping the scope of this PR, especially since this addresses a bug that's causing segfaults on game save. The last thing I want is to add extra complexity, and addressing IDs for player objects could be done as a separate PR.

As it stands I believe all code will treat `-1` as an invalid ID, even if there's some debate as to whether `0` is valid or not.

Comment (Qrox) [reply src/monster.h]: Fair enough. It's not like the inconsistency has caused any problem since it has been there for at least 5 years...

Comment (BevapDin) [reply src/monster.h]: > could you please also fix the inconsistency as to what number is used for invalid id? 

And that is why you don't use sentinels. Instead use `std::optional<int>`, which makes it perfectly clear to the reader when it's valid (when the optional contains an actual `int`) and when not (when the optional is empty).

Comment (pjf) [reply src/monster.h]: Marking this as resolved. I'm sure a separate pull-request add proper optional types rather than using sentinels would be appreciated.

File: src/savegame_json.cpp (hunk 3 above)
Comment (pjf) [reply src/savegame_json.cpp]: I can, but we don't do so for most of the other attributes; most mobs aren't underwater or babies, for example. Having it always be written to the file makes the code easier to read and makes it easier to verify correct values are being stored by peeking at the save-files.

If we particularly cared about file storage then I'd hook into `json.member` itself, so it doesn't write values which are the same as the their defaults. But that's only something I'd evaluate once we start being concerned mobs are taking up too much space in the save files.

File: src/monster.h (hunk 2 above)
Comment (pjf) [reply src/monster.h]: Function renamed.

File: src/monmove.cpp [hunk 5]
```diff
@@ -929,6 +886,81 @@ void monster::move()
...
+    }
+    if( get_effect_dur( effect_countdown ) == 1_turns && !has_effect( effect_operating ) ) {
+        if( dragged_foe->has_effect( effect_grabbed ) ) {
+
+            bionic_collection collec = *dragged_foe->my_bionics;
+            int index = rng( 0, collec.size() - 1 );
+            bionic target_cbm = collec[index];
+
+            //8 intelligence*4 + 8 first aid*4 + 3 computer *3 + 4 electronic*1 = 77
+            float adjusted_skill = static_cast<float>( 77 ) - std::min( static_cast<float>( 40 ),
```
Comment (AMurkin) [inline src/monmove.cpp]: Is'n it 37.0?

**Comment by pjf** [comment]
jenkins rebuild

File: src/monmove.cpp (hunk 5 above)
Comment (pjf) [reply src/monmove.cpp]: I feel this entire equation would be better served with either a constant, or a call to a function which makes explicit what each term is doing. However I'm not changing the code, I've simply relocated it into its own method.
