### PR TITLE
Fixes martial arts messaging

### LINKED ISSUE #35111: Wrong message displaying when wielding non compatible item while using silat
Oh no, the Silat guy again

# Describe the bug

When using a silat weapon and change it to something not silat compatible (in this case Pelmeni (don't judge me), it doesn't say "Pelmeni aren't a Silat weapon". But: "Silat cannot be used with weapons". Changig back to a Quaterstaff works fine and Silat is used. 

# Steps To Reproduce

1. Have Character with Silat. Have Silat weapon equiped.
2. Equip non Silat itam.

# Expected behavior
Have the display that "Item is not a Silat weapon"

# Screenshots
silat

# Versions and configuration

9815

### PR DESCRIPTION
**Pull request by Hymore246**
#### Summary

```SUMMARY: Bugfixes "Fixes martial arts messaging"```

#### Purpose of change

Fixes incorrect martial arts initiation messages.

#### Describe the solution

Certain combination of styles and weapons would cause the incorrect messaging to appear. This update streamlines the method that calls the messages and fixes some of the potential bugs that were causing the problem.

#### Additional context

This PR **might** fix #35111 and #35249. The reason I say might is because I cannot recreate these bugs when I build the game but other people can see these bugs when they build and the bugs appear in the main game when downloaded from the launcher. The reason for this is that I am building with Visual Studio on Windows while other people use Linux and gcc. From what I understand, this sort of problem happens from time to time. So these bugs might be fixed but I have no way to actually test to be sure. This PR fixes other messaging bugs so it should still be merged but if the above issues are still occurring, someone else will need to address them since I cannot with Visual Studio on Windows.

### CODE REVIEW

File: src/martialarts.cpp [hunk 1]
```diff
@@ -245,6 +245,7 @@ void martialart::load( JsonObject &jo, const std::string & )
     optional( jo, was_loaded, "weapons", weapons, auto_flags_reader<itype_id> {} );
 
     optional( jo, was_loaded, "strictly_melee", strictly_melee, false );
+    optional( jo, was_loaded, "strictly_unamred", strictly_unarmed, false );
```
Comment (Night-Pryanik) [inline src/martialarts.cpp]:
```suggestion
    optional( jo, was_loaded, "strictly_unarmed", strictly_unarmed, false );
```

File: src/martialarts.cpp [hunk 2]
```diff
@@ -1157,17 +1158,15 @@ bool player::can_autolearn( const matype_id &ma_id ) const
...
-        }
-    } else {
+    if( ma.force_unarmed || ma.weapon_valid( owner.weapon ) ) {
         owner.add_msg_if_player( m_info, _( ma.get_initiate_avatar_message() ) );
+    } else if( ma.strictly_melee && !owner.is_armed() ) {
+        owner.add_msg_if_player( m_bad, _( "%s cannot be used unarmed." ), ma.name );
+    } else if( ma.strictly_unarmed && owner.is_armed() ) {
+        owner.add_msg_if_player( m_bad, _( "%s cannot be used with weapons." ), ma.name );
+    } else {
+        owner.add_msg_if_player( m_bad, _( "The %s is not a valid %s weapon." ), owner.weapon.tname( 1,
```
Comment (Night-Pryanik) [inline src/martialarts.cpp]: Translator comments would be welcome.
```suggestion
        owner.add_msg_if_player( m_bad, _( "The %1$s is not a valid %2$s weapon." ), owner.weapon.tname( 1,
```
